### ISSUE TITLE
[Request] Support for MAME's .chd format

### ISSUE THREAD

**Issue by tony971** [stenzek/duckstation#1]
The .chd format is great for cleaning up game folders, reducing games to one file. It also losslessly compresses them into a streamable format, using LZMA and FLAC for audio. Beetle supports this format as an example of implementation.

**Comment by stenzek** [comment]
Should be pretty straightforward. Thanks for the suggestion.

**Comment by tony971** [comment]
No problem. As an aside, dicformat might be superior to .chd, but this would be the only emulator I know to support it.

https://github.com/discimagechef/DiscImageChef

https://github.com/PCSX2/pcsx2/issues/2798#issuecomment-530911531

**Comment by stenzek** [comment]
Support added as of https://github.com/stenzek/duckstation/commit/c1c82eb3f30e2eea66e1ed7e615f0ae4f998eff2.

The only possible issue is with subchannel data, currently you will still need to use `.sbi` files for this (affects libcrypt games).
