### ISSUE TITLE
Mission - Impossible (Europe) (En,Fr,De,Es,It) really bad stuttering during gameplay

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#100]
during gameplay it stutters really badly
keeps printing this out in the log
![mission](https://user-images.githubusercontent.com/2696404/76670230-6f1a1180-65ca-11ea-94cd-90961166b624.PNG)

**Comment by benderscruffy** [comment]
40 Winks (USA) has the same problem

**Comment by kurayami6** [comment]
It's a thousand times worse now. The log spams walls of this garbage, the game runs at 4 FPS and the emulator itself at 12% speed. 

![Capture](https://user-images.githubusercontent.com/31968468/83709263-7b5dba00-a661-11ea-929d-209dea9cbbe9.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/83709272-7ef14100-a661-11ea-9c00-c55c70ff9a8a.PNG)

**Comment by stenzek** [comment]
Seems some of these games do spam invalid commands to the GPU, but otherwise run fine. The log is disabled by default now, so this shouldn't be an issue for users.
