### ISSUE TITLE
Add menu entry to start chdman compression of cue/iso

### ISSUE THREAD

**Issue by sickemulator** [stenzek/duckstation#1005]
Being extremely lazy, I would appreciate if you could add a menu entry that automatically starts chdman to compress cue/iso to .chd format (similar to what Dolphin does with .rvz format)

**Comment by stenzek** [comment]
Not the worst idea, but I also I don't have any interest in making the emulator dependent on the user having chdman installed, sorry.

You can go to game properties and copy the path from there at least, or open the containing directory from the context menu.

**Comment by sickemulator** [comment]
ok, note taken. My idea would have been to add possibility to enter the path of chdman.exe somewhere in the settings and enable the option in the context-menu only if user has indicated path. But you're the boss and thanks for looking into the suggestions so quickly.
