### ISSUE TITLE
Audio Lag with Vigilante 8 games in android

### ISSUE THREAD

**Issue by HJMBgit84** [stenzek/duckstation#1007]
Hi I would like to report that Vigilante 8 game has audio lag in the android version, mostly at the start of the game section, to be more clear, the sound is like if the game is doing gargling, that is the sound that it produces while playing V8

**Comment by stenzek** [comment]
Likely slowdown/frame time spikes on Android, the frame pacing changes may make it less noticable.

**Comment by HJMBgit84** [comment]
Tbh the sound is terrible anyway for this game on android :/ so maybe in the future I hope it will be playable but the gargling sound is so ugly, thanks for the reply.

**Comment by stenzek** [comment]
Checked my phone and there were no audio issues. A bit of slowdown when looking at the sun, probably due to GPU readbacks (which are very slow on android drivers).

**Comment by HJMBgit84** [comment]
I tested it on my Nubia Red magic 5S, Snapdragon 865 so I do not think is a device hardware issue, I am talking about V8 version 1 btw, the V8 version 2 is good just to clarify in case that is needed.

**Comment by stenzek** [comment]
Did you try the software renderer? If so, it's the readbacks which are the problem.

There's no working around it, it's just **stupidly slow** to read back from the GPU on android drivers. But I have some "hack" ideas which might be able to mitigate it somewhat.

**Comment by HJMBgit84** [comment]
You are right, the less buggy option for audio is the software renderer option but I think the image quality is affected somehow or maybe is just my mind, ok anxiously happy to test the hack ideas to see an improvement on that game :)
