### ISSUE TITLE
Please add Edit Controls on screen in Android

### ISSUE THREAD

**Issue by HJMBgit84** [stenzek/duckstation#1008]
Hi I would like to request please if is possible to edit controls position on screen due to when we need to put triggers on the Phone L1, L2 and R1 and T2 cannot be mapped because they are vertical and not horizontally to put cell phone triggers for L2 and R2

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/d7c3a0137f5f9db34c1b64a6c601adaa718d5510
