### ISSUE TITLE
3 text problem.

### ISSUE THREAD

**Issue by zkdpower** [stenzek/duckstation#1011]
Under Windows Version.
1.Display Setting - Recommended Value - "Hardware (D3D11)" can not translate to other language, please fix the code for qt.
2.Enhancement Setting - Texture Filtering - “mouse point to whichever”,  the Recommended Value should not be "unchecked".
3.Audio Setthing - Buffer Size - "no matter how you move the sliding block ,could not occur 2048 like Recommended Value Tip"

**Comment by stenzek** [comment]
Should be fixed in latest build.
