### ISSUE TITLE
[Request] Support for No$PSX's free BIOS clone

### ISSUE THREAD

**Issue by HeyItsLollie** [stenzek/duckstation#1012]
[**No$PSX**](https://problemkaputt.de/psx.htm), Martin Korth's PlayStation debugging emulator, comes with a free BIOS clone built-in, which can be ejected for use in other emulators ([and hardware](http://www.psxdev.net/forum/viewtopic.php?f=76&t=1304)).

This BIOS can be accessed via:
Utility > Remote Access... > Create nocash bios rom as raw image (PSX-XBOO.ROM)
This will drop a 256K bios rom in the No$PSX directory.

**Comment by stenzek** [comment]
If you pad the file to 512K it'll probably work.

**Comment by HeyItsLollie** [comment]
Okay, so the BIOS shows up when its size is raised to 512K! But neither duplicating nor padding seems to do the trick. DuckStation returns the error below, and then crashes immediately afterwards.

Panic triggered: 'Unknown CDROM command' in function CDROM::ExecuteCommand (D:\a\duckstation\duckstation\src\core\cdrom.cpp:1193)

**Comment by stenzek** [comment]
Can you enable the log (system console in advanced settings) and check the output? It should log which command has not been implemented.

**Comment by HeyItsLollie** [comment]
Sure, here's the last section of the log before crashing:
```
W(DoEXP2Access): EXP2 read: 0x1F802066
W(DoEXP2Access): EXP2 read: 0x1F802066
W(DoEXP2Access): EXP2 read: 0x1F802066

[Edit: The above line occurs once every millisecond for about ten seconds.]

W(DoEXP2Access): EXP2 read: 0x1F802066
W(DoEXP2Access): EXP2 read: 0x1F802066
W(DoEXP2Access): EXP2 read: 0x1F802066
W(Throttle): System too slow, lost 9998.76 ms
W(DoEXP2Access): EXP2 read: 0x1F802066
E(ExecuteCommand): Unknown CDROM command 0x001F with 6 parameters, please report
Panic triggered: 'Unknown CDROM command' in function CDROM::ExecuteCommand (D:\a\duckstation\duckstation\src\core\cdrom.cpp:1193)
```

And the full log: (sans 1100kb worth of "0x1F802066")
[duckstation - Nocash PS1 Bios Crash.log](https://github.com/stenzek/duckstation/files/5451803/duckstation.-.Nocash.PS1.Bios.Crash.log)

**Comment by stenzek** [comment]
Hmm, that's apparently a video CD commands. I can probably just stub it out, will push soon.

**Comment by HeyItsLollie** [comment]
Unfortunately still crashing on the latest update, but got past 0x001F this time! New error:

```
W(DoEXP2Access): EXP2 read: 0x1F802066
W(Throttle): System too slow, lost 9729.77 ms
W(DoEXP2Access): EXP2 read: 0x1F802066
E(ExecuteCommand): Unknown CDROM command 0x0050 with 11 parameters, please report
Panic triggered: 'Unknown CDROM command' in function CDROM::ExecuteCommand (D:\a\duckstation\duckstation\src\core\cdrom.cpp:1205)
```

If 0x001F was VCD, then I'm assuming this one is related to the set of "secret unlock commands" mentioned here:
https://problemkaputt.de/psx-spx.htm#cdromcontrollercommandsummary

Also, here's No$PSX's clone-bios files, so you can see this in action. (original 256k rom, and the 512k mirrored rom)
[PSX-XBOO (No$PSX).zip](https://github.com/stenzek/duckstation/files/5457691/PSX-XBOO.No.PSX.zip)

**Comment by stenzek** [comment]
Everything needed should be implemented now.

**Comment by HeyItsLollie** [comment]
It boots! Thank you!

![duckstation-qt-x64-ReleaseLTCG_20201030_02-31-04-769](https://user-images.githubusercontent.com/30498581/97605648-9f7bc680-1a5a-11eb-8cca-b42ba1fa1410.png)
![duckstation-qt-x64-ReleaseLTCG_20201030_02-48-29-581](https://user-images.githubusercontent.com/30498581/97605686-a9052e80-1a5a-11eb-9696-a5478b13820c.png)

Things get a little funky when using Start BIOS. It seems to think that an extremely large CD is in there, when it should say "No Disc". This doesn't appear to affect anything on a functional level, it's just funny to see. Everything works fine when booting a game. ✌

![2020-10-30_02-52-33](https://user-images.githubusercontent.com/30498581/97607179-65132900-1a5c-11eb-9175-3075dc4638a0.png)

**Comment by stenzek** [comment]
There's still potential legal issues with including a reverse engineered bios. Please stop bumping old threads.

This one can be close anyway since the bios works fine.

**Comment by dftf-stu** [comment]
> "Please stop bumping old threads."

Apologies, just wanted to add a reply on topics of-interest to me... I didn't think it would be an issue, especially seeing-as the thread was still open at-the-time.

**Comment by HeyItsLollie** [comment]
Unfortunate timing, but have to reopen this. When attempting to use No$PSX's BIOS, a panic is fired and DuckStation crashes immediately after.
`Panic triggered: 'Unimplemented config mode command' in function AnalogController::Transfer (D:\a\duckstation\duckstation\src\core\analog_controller.cpp:428)`

[duckstation - Nocash PS1 Bios Crash 210511 (AnalogController--Transfer).log](https://github.com/stenzek/duckstation/files/6456125/duckstation.-.Nocash.PS1.Bios.Crash.210511.AnalogController--Transfer.log)

**Comment by HeyItsLollie** [comment]
Shoot, I'll ping Martin Koth about it then. Afaik though the panic only started happening recently (within the past month or so at least), it wasn't an issue when support was originally added.

@dftf-stu :
> Interesting... does the one BIOS dump work for all-regions, or do you have to do one dump for each console region?
I'm pretty sure the one bios works for all regions! There's no way to select which region you dump for, it's just an option accessed via No$PSX's top-bar menu: Utility > Remote Access... > Create nocash bios rom as raw image (PSX-XBOO.ROM)

**Comment by HeyItsLollie** [comment]
99% certain I was using DualShock, I generally don't use digital-only profiles. (DualShock's analog/digital switch is usually enough to fix compat issues)

Worth noting though: Switching the controller profile to Digital *does* allow it to boot normally, and then I can switch the profile back to DualShock once the game has booted.
