### ISSUE TITLE
Hash pregap on binary tracks to match redump.org checksums

### ISSUE THREAD

**Issue by Nucleoprotein** [stenzek/duckstation#1018]
Hello,

There is problem with this game: 
http://redump.org/disc/1222/
![image](https://user-images.githubusercontent.com/8019035/97619202-370ff380-1a20-11eb-93f1-30311f076414.png)
Image is good and cue/bin tracks checksum match, but not in Duckstation seems that pregap is also needed to be hashed as part as second track if it's MODE2/RAW.
![Zrzut ekranu 2020-10-29 201420](https://user-images.githubusercontent.com/8019035/97621614-6d9b3d80-1a23-11eb-9223-77e6f8a3f4af.png)

**Comment by stenzek** [comment]
See if https://github.com/stenzek/duckstation/commit/e579cd2eb2a87a9863eb1a0d389313de20a878f9 makes any difference here.

**Comment by Nucleoprotein** [comment]
Closing, seems good:
![image](https://user-images.githubusercontent.com/8019035/101286483-0ffccc80-37eb-11eb-9123-2813edf7ac87.png)
