### ISSUE TITLE
Wrong bios file used to boot

### ISSUE THREAD

**Issue by Nucleoprotein** [stenzek/duckstation#1019]
Hello,

Selected No$PSX BIOS for all regions:
![image](https://user-images.githubusercontent.com/8019035/97622331-66286400-1a24-11eb-991e-fc1a7839a231.png)
but Euro games start by different bios - i see normal boot logo.
When i removed all other bios files from directory then it boots correctly.

**Comment by Zet-sensei** [comment]
I can confirm on my configuration.

Only the PAL region BIOS selection is affected.

**Comment by Nucleoprotein** [comment]
Seems that automatic check is forcing "proper" bios file:
![image](https://user-images.githubusercontent.com/8019035/97628546-23b75500-1a2d-11eb-9360-cb6a455ea606.png)
![image](https://user-images.githubusercontent.com/8019035/97628606-37fb5200-1a2d-11eb-92ae-b327cc0ca239.png)
Maybe this is this code: https://github.com/stenzek/duckstation/blob/master/src/core/bios.cpp#L137 ?
