### ISSUE TITLE
More flags in game list

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#102]
Using 40 Winks (Spain) and Barbie Explorer (Germany) as examples. Despite both of those games being versions unique to their respective countries the flag is just Europe for both. I think for games unique to a specific country the flag for that country should be used. 

![Capture](https://user-images.githubusercontent.com/31968468/76680570-b5f51f00-663d-11ea-89b8-0155b732ead5.PNG)

**Comment by kurayami6** [comment]
Also I don't think Australia is part of Europe.

![Capture](https://user-images.githubusercontent.com/31968468/76681649-64eb2800-6649-11ea-8dfa-977ebd15b9f7.PNG)

**Comment by stenzek** [comment]
The flag is based on the region, so there's only NTSC-U, NTSC-J, and PAL options. Australia uses PAL, hence the European flag.

I guess we could parse the country name out of the title, but that seems prone to breakage. And there's a lot of releases which are multi-language.

**Comment by stenzek** [comment]
Closing, as it's not a "country" field but a "region" field. I'm open to a better icon to indicate NTSC/PAL games.
