### ISSUE TITLE
resident evil freeze

### ISSUE THREAD

**Issue by dml360** [stenzek/duckstation#1023]
the game worked perfectly in old versions (build 01.-1864), but in new builds ones it starts there when you choose the character instead of going to the game, the emulator restarts in the bios and freeze.

RESIDENT EVIL DIRECTORS CUT
SLES-00971

i5 8400
gtx 1060 6gb
w10 pro

**Comment by Zet-sensei** [comment]
Can't reproduce.
Tested with all renderers and all CPU modes.
Tested with 3 European BIOSes & no$psx free bios.

Do you have any cheats or game/video enhancements (like PGXP) activated ?

![Duck](https://user-images.githubusercontent.com/52127625/97692654-53ec0b80-1aa0-11eb-8c6e-fce0d93ed1ce.png)

**Comment by dml360** [comment]
can be my iso, because it is modified for subtitles in Portuguese, the strange thing was to work in older versions of the emulator
