### ISSUE TITLE
Spyro 2 PAL: Black screen when entering the Level "Idol Springs"

### ISSUE THREAD

**Issue by GitToTheHub** [stenzek/duckstation#1024]
I was today playing Spyro 2 PAL with the latest master and when I entered the Level "Idol Springs" in "Summer Forest", i saw the intro scene for the level and after a black screen. I rebooted the game and loaded from Memory Card and after the loading screen "The Adventure continues.." there was again the black screen and nothing happened any more. I'm using the Graphic Backend D3D11, but this error happens in OGL and Software aswell. PGXP is disabled.

Game: Spyro 2 - Gateway to Glimmer (Europe) (En,Fr,De,Es,It)
DuckStation: 0.1-2168-gb5b1c725
Bios: SCPH7502

**Comment by stenzek** [comment]
Have you put the sbi file alongside your disc image?

**Comment by GitToTheHub** [comment]
I only have a bin- and cue-file. What is a sbi-file?
________________________________
Von: Connor McLaughlin <notifications@github.com>
Gesendet: Samstag, 31. Oktober 2020 14:55
An: stenzek/duckstation <duckstation@noreply.github.com>
Cc: Manuel Beck <manuelbeck87@outlook.de>; Author <author@noreply.github.com>
Betreff: Re: [stenzek/duckstation] Spyro 2 PAL: Black screen when entering the Level "Idol Springs" (#1024)


Have you put the sbi file alongside your disc image?

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation#libcrypt-protection-and-sbi-files

Spyro 2 PAL has libcrypt protection, sbi files contain the sectors with the key. You can download them from redump.org.

**Comment by GitToTheHub** [comment]
Thank I never heard about that. But in the past I already played the game with ePSXe and never had issues with a missing sbi-file. Do you know, why the game is playable in ePSXe?
________________________________
Von: Connor McLaughlin <notifications@github.com>
Gesendet: Samstag, 31. Oktober 2020 15:20
An: stenzek/duckstation <duckstation@noreply.github.com>
Cc: Manuel Beck <manuelbeck87@outlook.de>; Author <author@noreply.github.com>
Betreff: Re: [stenzek/duckstation] Spyro 2 PAL: Black screen when entering the Level "Idol Springs" (#1024)


https://github.com/stenzek/duckstation#libcrypt-protection-and-sbi-files

Spyro 2 PAL has libcrypt protection, sbi files contain the sectors with the key. You can download them from redump.org.

**Comment by Nucleoprotein** [comment]
Maybe you use old CloneCD format with .sub?

**Comment by stenzek** [comment]
No idea. Maybe epsxe has sbi files built in, but one could argue that would be shipping copyrighted data (not sure if the key counts) and thus potentially illegal.

**Comment by Nucleoprotein** [comment]
It does not have, but it can use SUB files - CloneCD format.

**Comment by GitToTheHub** [comment]
I tried this image in ePSXe 2.0.5 and there the game is working. I used the same memorycard and cd image and it worked though i only have a bin- and cue-file.
________________________________
Von: Robert Krawczyk <notifications@github.com>
Gesendet: Samstag, 31. Oktober 2020 15:26
An: stenzek/duckstation <duckstation@noreply.github.com>
Cc: Manuel Beck <manuelbeck87@outlook.de>; Author <author@noreply.github.com>
Betreff: Re: [stenzek/duckstation] Spyro 2 PAL: Black screen when entering the Level "Idol Springs" (#1024)


Maybe you use old CloneCD format with .sub?

**Comment by Nucleoprotein** [comment]
Then dunno why.

**Comment by GitToTheHub** [comment]
ok then maybe ePSXe have the sbi-file already integrated. I'm astonished, that ePSXe never had problems with that, because it's released in the Android Store for money ..

**Comment by GitToTheHub** [comment]
@Nucleoprotein I don't think it's a CCD-Format, because there is no ccd-File.

**Comment by GitToTheHub** [comment]
@stenzek I downloaded the sbi-file from redump.org and it's really playing. Thank you! When i remember correct, i had the same issue in the past with Spyro on my real playstation too, when i tried to burn the game.
But, if it would be illegal to distribute the sbi-file, then redump.org would not offer it, or? Something must be "ok" here.

**Comment by stenzek** [comment]
I'm not a lawyer, so I'd rather not take the risk.

**Comment by GitToTheHub** [comment]
I understand. Could you maybe detect if a sbi-file is missing and give the user an alert?
________________________________
Von: Connor McLaughlin <notifications@github.com>
Gesendet: Samstag, 31. Oktober 2020 15:50
An: stenzek/duckstation <duckstation@noreply.github.com>
Cc: Manuel Beck <manuelbeck87@outlook.de>; Author <author@noreply.github.com>
Betreff: Re: [stenzek/duckstation] Spyro 2 PAL: Black screen when entering the Level "Idol Springs" (#1024)


I'm not a lawyer, so I'd rather not take the risk.
