### ISSUE TITLE
OpenGL SSAA

### ISSUE THREAD

**Issue by KrossX** [stenzek/duckstation#1026]
Running on W7 + HD5770, so using deprecated hardware with deprecated renderer on deprecated OS (=P). That aside, there's no difference when I use SSAA over MSAA even though the log indicates it to be working. Adding the following code at the bottom of [GPU_HW_OpenGL::UpdateSettings()](https://github.com/stenzek/duckstation/blob/b5b1c725c1a561dc95e97284add4706884d76242/src/core/gpu_hw_opengl.cpp#L119) made it work as expected, like with D3D11.

```cpp
  if (m_multisamples)
    glEnable(GL_MULTISAMPLE);
  else
    glDisable(GL_MULTISAMPLE);

  if (m_per_sample_shading)
  {
      glEnable(GL_SAMPLE_SHADING);
      glMinSampleShading(1.0f);
  }
  else
    glDisable(GL_SAMPLE_SHADING);
```

**Comment by stenzek** [comment]
Sounds like the driver's not following the spec then. GL_MULISAMPLE shouldn't be required, nor should GL_SAMPLE_SHADING (the inputs to the shader enable sample rate shading).

**Comment by KrossX** [comment]
Driver bug, setting `m_use_glsl_interface_blocks` to false for the shader generator makes it work as well.

I couldn't find the default values for those enums so I checked with the reference book and indeed, GL_MULTISAMPLE is for the render to window side and defaults to enabled anway. GL_SAMPLE_SHADING sets `in` variables as `sample` by default, in case you cannot edit the shader.
