### ISSUE TITLE
some text message should be fix

### ISSUE THREAD

**Issue by zkdpower** [stenzek/duckstation#1028]
i found some issue follows should be fix.
DuckStation Setthings - Advanced Setthings - Tweaks/Hacks
(A) the "Enable Recompiler Fast Memory Access"s OSD message always is "swithcing to……“no matter i click or not,
i think the OSD message should fix to "enable to … or disable to…“, or simply CANCEL the OSD.
(B) the "Use Debug Host GPU Device"s Poping Message follows is untranslatable to other language.
1.Failed to acquire host display.
2.Failed to boot system after recreation.
(C) the OSD message follows is untranslatable to other language.
1."Recompiler (Fastest)CPU"
2."Cached Interpreter (Faster)CPU"

**Comment by stenzek** [comment]
> (A) the "Enable Recompiler Fast Memory Access"s OSD message always is "swithcing to……“no matter i click or not,
i think the OSD message should fix to "enable to … or disable to…“, or simply CANCEL the OSD.
> (B) the "Use Debug Host GPU Device"s Poping Message follows is untranslatable to other language.

These are advanced options and not intended to be used by general users.

> (C) the OSD message follows is untranslatable to other language.

I will check this one.
