### ISSUE TITLE
Texture filters causes glitches on some textures

### ISSUE THREAD

**Issue by Nucleoprotein** [stenzek/duckstation#1029]
Hello,

The problem (trees in background):
![SLUS-00707_2020-11-01_11-47-58](https://user-images.githubusercontent.com/8019035/97800852-da3b5580-1c38-11eb-8efa-97490d40e5fd.png)

I think i got similar problem with my RTX 2070S in other emu and it was fixed by some shader change... i need to dig that up

EDIT: found it: https://github.com/libretro/beetle-psx-libretro/commit/b11adfe55da92a02d1b9a5b9b71506223c5be226 but it can be not related

**Comment by stenzek** [comment]
Enhancements are not guaranteed to work with all games.

**Comment by Nucleoprotein** [comment]
Ok, but in OpenGL it works fine, only Vulkan and DX11 are affected:
![SLUS-00707_2020-11-01_12-08-43](https://user-images.githubusercontent.com/8019035/97801159-1d96c380-1c3b-11eb-99bb-896da9eaddc9.png)

**Comment by stenzek** [comment]
That's actually a bug - OpenGL isn't alpha blending pixels which are half-transparent when filtered.

Maybe I'll make an enhancement to disable the edge blending, because it breaks in other games too.
