### ISSUE TITLE
disappearing graphics in International Moto-X (Japan) 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#103]
Every time the bike rotates the rider's wrists and legs disappear. Haven't played it on real hardware so I apologize if it's not a bug and the game's just like that.

![Capture](https://user-images.githubusercontent.com/31968468/76686043-97f2e300-666c-11ea-936e-47b1065f6236.PNG)

**Comment by kurayami6** [comment]
Yeah I think the graphics are definitely not supposed to be like that.

![Capture2](https://user-images.githubusercontent.com/31968468/76697365-82240300-66ea-11ea-804f-425a07ec2617.PNG)

**Comment by stenzek** [comment]
Please confirm this is an issue on console first. From a quick search, the videos I've found also seem to exhibit this problem.

**Comment by kurayami6** [comment]
I don't have a real PS1 to test it but it's listed as a known issue in Mednafen. Looking up YouTube videos isn't reliable since if people are posting game footage, unless it's a speedrun it's almost always going to be from an emulator.

https://forum.fobby.net/index.php?t=msg&th=1114&start=0&

**Comment by HeroponRikiBestest** [comment]
Happens on real console. 
[rbqxl4.mp4.zip](https://github.com/stenzek/duckstation/files/4471761/rbqxl4.mp4.zip)

**Comment by kurayami6** [comment]
Alright I'll close this. @HeroponRikiBestest can tell the Mednafen devs that it apparently happens on real hardware since they have it listed as an emulation bug as well.

**Comment by HeroponRikiBestest** [comment]
can you link me to their issues page?

**Comment by kurayami6** [comment]
https://forum.fobby.net/index.php?t=msg&th=1114&start=0&

**Comment by stenzek** [comment]
Thank you for confirming on console! Much appreciated.

**Comment by HeroponRikiBestest** [comment]
Well, it wasnt me, it was someone in another discord with a real ps1 set up, you can thank them.

**Comment by kurayami6** [comment]
@HeroponRikiBestest Could you do me a favour and ask that person to check City Of Lost Children (USA) and see if that green pixel is there on real hardware? 

![SCUS-94150_2020-04-14_04-05-35](https://user-images.githubusercontent.com/31968468/79188779-5a4bca80-7e63-11ea-9848-c64b1118aa1b.png)

**Comment by HeroponRikiBestest** [comment]
The one on the inner ring of the cd? also, are you on discord? It would be easier to communicate

**Comment by kurayami6** [comment]
@HeroponRikiBestest Yeah that one. It's probably a game bug but I'd like to be sure. I don't have Discord. I have no idea how to use it.

**Comment by HeroponRikiBestest** [comment]
@kurayami6 it's really easy to use. Regardless, I'll ask them

**Comment by stenzek** [comment]
FWIW for the DuckStation Discord at least, registration is not mandatory and you can just join using the web browser. Link is in the readme on the repository's page.
