### ISSUE TITLE
Problem with switching to fullscreen

### ISSUE THREAD

**Issue by Nucleoprotein** [stenzek/duckstation#1036]
Hello,

To reproduce, set HW backend to DX11, set some exclusive fullscreen resolution, then switch to backends not supporting exclusive fullscreen. Then run game and press alt+enter - you will get this:
![image](https://user-images.githubusercontent.com/8019035/97811101-9b2cf480-1c78-11eb-9d7f-c7a4d2d3422d.png)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/d102b2facd69d029988808d949fd375abffe5ddb
