### ISSUE TITLE
Import / Export functionality for ePSXe memory card naming convention.

### ISSUE THREAD

**Issue by ElektroStudios** [stenzek/duckstation#1037]
In order to import all my collection of save games / memory cards from **ePSXe** to **DuckStation**, first I set **DuckStation** to store them in game code format, then I attempted to do a bulk file renaming on my memory cards directory from **ePSXe**. For much games it is as simple as following these substring replacing rules that can be easy replicated in any programming language: 

![alt text](https://i.imgur.com/XfOOIjd.png)

and as a (maybe not very optimized) Regular Expression too:
![alt text](https://i.imgur.com/vck0phL.png)

However, I noticed these naming convention is not followed for some other games. For example for **Valkyria Profile**, **ePSXe** generates a file with name: **SLU__024.72-00.mcr**, and **DuckStation** generates a file with name: **VP-ESEXE_1.mcd**

In these circumstances it seems impossible for me to figure out what the proper name would be for the memory card file for some games since like in that example it could totally change the naming rules to follow, and I ignore for which games this could or couldn't happen.

For this reason I would like to request a proper bulk renamer / memory card import functionality within **DuckStation** GUI, optionally with the chance to use game titles instead of game codes naming format for the renamed files. 
An export function to **ePSXe** file naming conventions would be less important, but very nice too.

PS: a bulk procedure is very important, because converting one by one could be a nightmare for any user that has many memory card files (I have more than 300, for example).

Please, consider this feature request. 

Thanks for read.

**Comment by stenzek** [comment]
I'm not sure where epsxe is getting these serials from. DuckStation pulls them from the SYSTEM.CNF file on the disc, which sometimes has a name which isn't the same as the serial, as you saw with Valkyrie Profile. Maybe it has an internal "fix up" list, not sure.

Renaming files seems like something which is better suited to other utilities like the one you've listed here, rather than something which should be built into the emu. There's no standard for card naming, so anything built will be specific to one other emulator. I'd rather just leave it up to the user than overcomplicate the UI with features like this.

**Comment by ElektroStudios** [comment]
Could you reconsider it before finally taking the decision to close the thread?. I could give you good argues:

 · Many users will no have basic knowledge to rename many files at once. 

 · In fact, many users even will not be aware that they can copy / use memory card files from **ePSXe** directory.

 · Would be ideal to have this kind of feature implemented in the emulator, rather than expecting the modding scene or fans / users / contributors to release some tool for people with no knowledges.

· You are a developer of **DusckStation**, no one than you could implement it in the proper way.

 · Until the release of **DuckStation**, **ePSXe** since October 2000 (its first public release) is still the most popular PSX emulator on the world for Windows. Just few people use **PCSX**, **RetroArch** cores or **DuckStation** in comparison being realistic. **ePSXe** is catalogued as "_The best free playstation emulator_" in many roms / games related websites, and it will be like that at least for some more decades.

For this reason I think it is not a crazy idea that **DuckStation** should consider to support memory card files migration from the most popular PSX emulator in the world, to make everyone happy and being easier to use **DuckStation**.

That's all I wanted to say. I hope you could reconsider it. I will not insist more, thanks for support!

**Comment by stenzek** [comment]
I appreciate the suggestions, but at least at the moment the stuff I work on is either what has widespread demand, or things I find personally interesting. And this is something I have zero interest in, and it's just overcomplicating the UI further.

I think a user with 300+ games/saves to migrate is probably an edge case, I'd expect most people to just have a handful of games which they play.

But the main reason I'm against it is I have no interest in adding features specific to another emulator. You don't see Retroarch having epsxe memory card import options either ;)

If there's a large demand for it I'd reconsider.

> · Until the release of DuckStation, ePSXe since October 2000 (its first public release) is still the most popular PSX emulator on the world for Windows. Just few people use PCSX, RetroArch cores or DuckStation or other options in comparison being realistic. ePSXe is catalogued as "The best free playstation emulator" in many roms / games related websites, and it will be like that at least for some more decades.

Yeah, and it's completely ridiculous, almost anything is more compatible than epsxe now. But those sources aren't going to change and it's a losing battle trying to convince people otherwise.

**Comment by stenzek** [comment]
As an aside, a converter from game code to game title and vice versa is something I'd potentially do.

**Comment by ElektroStudios** [comment]
> You don't see Retroarch having epsxe memory card import options either ;)

True, although the "srm" format for psx cores is the same as mcr / mcd too. Maybe nobody demanded that or like you they have no interest to implement that.

I just wanted to have **DuckStation** installed on my PC to definitely replace it for **ePSXe** migrating all my collection of save games for conservation, without worries to discover in the future that some save games are "lost" or not recognized due bad renamings of which I will not be aware until I notice something is wrong for "X" game (like happened for **Valkyrie Profile**).

We both know there will not be more demand for this feature than mine. I hope I haven't bothered you with my suggestions. I'm content with manually replacing the file names and expecting that everything goes well.

By the way, I don't know anything about compatibility comparisons between **ePSXe** and others, but your emulator is great, the GUIs are great specially the one did with QuickTime. Great job in general, really.

Keep it up, and until next time!

**Comment by Nucleoprotein** [comment]
SLU__024.72-00.mcr is very wrong for Valkyrie Profile as SLES-02472 is Medal of Honor (German), bad dump?

**Comment by stenzek** [comment]
Indeed, SLUS-01156 is what it should be.

Sounds like espxe got it wrong then. Another reason to not do this if we can't even trust the filenames.

**Comment by ElektroStudios** [comment]
I know the thread is closed, and I don't have an answer to the open question, but if it could be of interest:

![a](https://i.imgur.com/pe4sAl9.png)

![b](https://i.imgur.com/52cz37p.png)

I don't have any **SLUS_011.56-00.mcr** or similar name, the file that ePSXe is loading is **SLU__024.72-00.mcr**

**Comment by stenzek** [comment]
Valkyrie profile is SLUS-01156. It sounds like epsxe is using the internal file name as the memcard file name, which imo is silly, prone to errors and doesn't even match the serial of the game. So how are you supposed to know which game the file is for without opening it up in an ediotr

**Comment by stenzek** [comment]
Okay, scratch that, it's not coming from the save filename either (should be BASLUSP01156ValPro1).

I've got no idea where epsxe is getting these names from, but they're clearly wrong :)

**Comment by Nucleoprotein** [comment]
I have check ePSXe.exe - some gameids are hardcoded, Also some hardcoded fake SBIs.
@stenzek maybe add support for memcard folder ie. save states as loose files?
