### ISSUE TITLE
Resident Evil Director's Cut (Germany) (SLES-00971) crashes after character selection

### ISSUE THREAD

**Issue by CaptainAlphabet** [stenzek/duckstation#1038]
Hi!

I noticed that the German version of Resident Evil Director's Cut crashes after chosing a character. The device used for testing was a Nvidia Shield Android TV running the current DuckStation Libretro Core. I haven't tried that game for a while, but I know that it worked in the past. So unfortunately I can't tell when this problem appeared.

**Comment by stenzek** [comment]
Possibly the same as https://github.com/stenzek/duckstation/issues/1023 ?

Do you have any enhancements enabled?

**Comment by CaptainAlphabet** [comment]
Sorry. Haven't seen the existing issue.
Today's Libretro core build fixed the problem.
