### ISSUE TITLE
Digital Controller not work

### ISSUE THREAD

**Issue by teorex3** [stenzek/duckstation#1041]
Pressing in the program does not work, not a single button responds. In other emulators this joystick works fine.
Model: havit hv-g60
![776630](https://user-images.githubusercontent.com/35883258/98027550-e92f2d00-1e1d-11eb-87a9-c25ad8249c6a.jpg)

win7-64bit latest duckstation build

**Comment by stenzek** [comment]
Have you tried https://github.com/stenzek/duckstation#sdl-game-controller-database

**Comment by teorex3** [comment]
Fixed
