### ISSUE TITLE
auto hide mouse pointer

### ISSUE THREAD

**Issue by dml360** [stenzek/duckstation#1042]
resource request

I would like to suggest something very simple and even irrelevant but I think it is worth mentioning:
 it would be nice to have an option to hide the mouse icon on the screen after about 5 6 seconds after the game is started

ps: if you already have this option I'm sorry, I searched and I didn't find

**Comment by stenzek** [comment]
Mouse pointer is already hidden in fullscreen mode.

Hiding it in windowed mode would probably be a bad idea, as it's taking control away from the user.
