### ISSUE TITLE
Problem with texture filter: xBR

### ISSUE THREAD

**Issue by enriquealcaraz** [stenzek/duckstation#1043]
Problem with texture filter: xBR. In all games there are red or blue dots that annoy the high quality playable experience. 

config:
![image](https://user-images.githubusercontent.com/32360461/98137850-bf7c1180-1ec2-11eb-8ec2-d2b8eb386783.png)

Problem:
![image](https://user-images.githubusercontent.com/32360461/98137938-da4e8600-1ec2-11eb-8483-d2e4b20cc22e.png)
![image](https://user-images.githubusercontent.com/32360461/98138343-4a5d0c00-1ec3-11eb-8dbd-2ddd2ad21c41.png)
![image](https://user-images.githubusercontent.com/32360461/98138959-eedf4e00-1ec3-11eb-882d-5a342e090615.png)

**Comment by stenzek** [comment]
Try using the "No Edge Blending" variants of the filters.

Such is the nature of enhancements - they don't work in all games.
