### ISSUE TITLE
[SCES-01771] Destrega (Italy) - 3D Graphic is all glitchy and it's way too fast

### ISSUE THREAD

**Issue by DarkSwan86** [stenzek/duckstation#1046]
Hi @stenzek !

If you try to play this game all the stages are glitching and the game is way too fast, the CPU controlled characters are impossible to defeat! ^^"

I've tried this game on Duckstation on both Windows (W7 + AMD Radeon 480, latest driver) and Linux (Intel Graphic HD 3000 lastest mesa), same problem. I'm using the lastest snapshot at the moment of writing (https://github.com/stenzek/duckstation/commit/a17e15f1766df858b5b15aff2dcde485090389a0). If you need more information, i will provide them!

Thanks!

**Comment by DarkSwan86** [comment]
Little update, still broken on d1a42df . 

The problem is much more visible if you pause the game during a fight: seems that the game is "cycling" between 3 states, where the background geometry is fine, then after 3-4 seconds is partially corrupted and after 3-4 is completely black. 

On Windows both Direct11, OpenGL and Vulkan are affected.
On Linux OpenGL is affected (can't test Vulkan due to old GPU)

**Comment by stenzek** [comment]
It's the vsync timeout issue which affects a few games. As a workaround you can force NTSC timings, or enable TTY logging which also slows it down enough, until I come up with a proper fix

**Comment by DarkSwan86** [comment]
I can confirm that the NTSC make the game graphic almost stable, thanks!

Take your time, you are doing an amazing job with DuckStation!

**Comment by DarkSwan86** [comment]
Little update, i've tried the NTSC version of the game (SLUS-00732) and it's perfect with all the 4 renders on Windows, it doesn't need any workaround. It's only the PAL Italian version that it's still broken.

**Comment by stenzek** [comment]
Fixed with https://github.com/stenzek/duckstation/commit/fdc7066ead2196886516c8845af870334722f00d

**Comment by DarkSwan86** [comment]
I can confirm, both Windows (Vulkan) and Linux (OpenGL) are fixed, thanks!
