### ISSUE TITLE
CD-ROM Read Speedup value not saved on in-game settings

### ISSUE THREAD

**Issue by DonelBueno** [stenzek/duckstation#1048]
In "gamesettings.ini" file, when you set a different read speed to a game, it is saved just as:

CDROMReadSpeedup = true

It doesn't save the speedup value. Strangely, the emulator keeps the right value for sometime, then it is reset and you have to set it again. Manually adding the value to the ini (ReadSpeedup = x) doesn't change this behavior.

**Comment by Nucleoprotein** [comment]
I think this is saved in gamelist.cache

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/56ab103559cf60994147c26efaae7c53f33f2a3a
