### ISSUE TITLE
[Request] MDEC chroma smoothing?

### ISSUE THREAD

**Issue by levonnn** [stenzek/duckstation#105]
Do you plan to implement MDEC for FMVs?

**Comment by stenzek** [comment]
I'm not sure I'm understanding the question. MDEC is implemented and all games I've tested with FMVs appear to work, unless they're broken for other reasons.

**Comment by levonnn** [comment]
Sorry, I meant YUV filtering.

Described here:
https://www.libretro.com/index.php/new-vulkan-graphics-enhancements-features-in-beetle-psx-hw/

**Comment by stenzek** [comment]
Not as a priority. But perhaps in the future after compatibility is better.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/7dc71027cf54f317ada68f56f102cc47addc07c1
