### ISSUE TITLE
[Feature Request] PGXP 2D Geometry Tolerance

### ISSUE THREAD

**Issue by DonelBueno** [stenzek/duckstation#1053]
Some time ago, BeetlePSX implemented a feature called "PGXP 2D Geometry Tolerance", which fixes some glitches when using PGXP mode. Here is the PR: https://github.com/libretro/beetle-psx-libretro/pull/725

From my testing, this fixes HUD issues in games while using PGXP CPU mode, like the streched HUD in Wipeout XL and the racing map in Looney Tunes Racing.

Do you think you could implement it in DuckStation?

**Comment by stenzek** [comment]
I'm not convinced this is necessary. Why are you using CPU mode in games which don't need it?

Also, the HUD seems fine in Wipeout XL to me.

**Comment by DonelBueno** [comment]
In Looney Tunes Racing, CPU Mode fixes these lines between polygons:

![DuckStation_2020_11_08_09_25_21_211](https://user-images.githubusercontent.com/4239694/98464895-b205a680-21a4-11eb-8bfe-2ab8c338b924.png)
![DuckStation_2020_11_08_09_25_22_932](https://user-images.githubusercontent.com/4239694/98464896-b3cf6a00-21a4-11eb-9aa3-a7aff141b39b.png)

Racing map with CPU Mode on:

![DuckStation_2020_11_08_09_22_47_996](https://user-images.githubusercontent.com/4239694/98464902-c3e74980-21a4-11eb-9c6c-7eb59a7b5ddd.png)

**Comment by stenzek** [comment]
Do you have the additional precision option turned on in advanced? That causes holes inbetween polygons in Crash Team Racing as well, but it's fine with it disabled.

**Comment by DonelBueno** [comment]
It is disabled, I was sure to test it with on and off, same results.

**Comment by stenzek** [comment]
Hm, maybe I'll investigate it then. I'd rather come up with a proper fix, rather than a hack like the one you linked (which also has a performance cost for every polygon).

Otherwise if these are the only two games affected, it's probably not worth it the perf hit.

**Comment by DonelBueno** [comment]
Ok. I'll try to find more games where this option is beneficial.

I don't remember this option having any performance impact on my system, but I may be wrong.

Were you able to reproduce the stretched HUD elements in Wipeout XL?

**Comment by stenzek** [comment]
Wipeout seemed fine to me even with CPU mode on.

**Comment by Nucleoprotein** [comment]
For me is not:
![image](https://user-images.githubusercontent.com/8019035/98465796-c5783800-21cb-11eb-8219-d40b88e24d58.png)
![image](https://user-images.githubusercontent.com/8019035/98465810-dcb72580-21cb-11eb-9dda-7ad497109dc6.png)

**Comment by DonelBueno** [comment]
@stenzek 

`The game intended to be improved was Silent Hill. With PGXP set to CPU mode the tree leaves have less jitter though the map screen would flicker when zooming.`

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/f0ff7ce231b847663dcc4059c503b3f415e6802f, though I still doubt the usefulness of this.

The Wipeout issue (and by extension, BIOS) looks like it's because the precise values aren't being invalidated, will look into why they aren't and come up with a proper fix soon.
