### ISSUE TITLE
Resident evil 3 psx tela preta e demora no loading

### ISSUE THREAD

**Issue by xcamus** [stenzek/duckstation#1055]
Resident evil 3 esta tendo alguns problemas com tela preta e demora no carregando ao abrir o bau, e pegar alguns arquivos.
os pontos que identifiquei o problema
ao pegar o arquivo no bonde na parte onde se encontra com nicolai e carlos
no inicio do jogo perto daquela escada verde, quando se pega a erva verde também ocorre o problema de tela preta e uma demora significativa para o jogo continuar
Aproveitando o post tbm da tela preta e uma demora no carregamento no jogo dino crisis 2, depois que tem a primeira cena do dylan com sua filha, logo no inicio do jogo

**Comment by andercard0** [comment]
@xcamus nas proximas vezes que abrir um problema, por favor faça em Inglês por gentileza!

Translating to English he said:

Facing some issues in Resident Evil 3, black screens, huge delay on loadings, when open a chest e while grab some files.

Where the issues are found:
- when grab a file in the train nearby Nicolai and Carlos.
- Very start of the game nearby one of those green stairs, when i grab the green herb it happens as well.

one more thing, talking about hangs and black screens it does happens in Dino Crisis 2, after Dylan's first scene with his daughter in the begining of game.

**Comment by stenzek** [comment]
Looks like this has libcrypt protection, have you provided a sbi file alongside the disc image? (see https://github.com/stenzek/duckstation#libcrypt-protection-and-sbi-files)

**Comment by stenzek** [comment]
Closing due to lack of response, but this did sound like a libcrypt issue.
