### ISSUE TITLE
Duckstation GH Report Template

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#1057]
Yo, @stenzek as discussed on Discord here is the template in order to improve correct troubleshooting 
of issues raised here in the future. I couldn't create the template, only you can so decided to raise as a issue.

I would add a fourth point but I don't know if you agree:
4).Please, consider to file GH issues in English only in case you don't speak get in touch with us on Discord.

Personally, have no problem to translate when i see someone asking for help here in my language.

Template :

Before file a new issue first and foremost consider this:

**1)** All advanced options MUST be at their default values;
**2)** Do not share save state files. Memory Cards are ok;
**3)** All enhancements must be off;

Description of the issue / bug
[Describe what you are seeing and or hearing during the gameplay]

Steps to reproduce
[Try to provide as much details as possible to reproduce the issue]

Enhancements information
[Make Sure they are all turned off before report]

Operating system you're running
[Windows (7, 8, or 10) Android, or Linux]

Emulator version: 

Game details: 
[Serial Code, Region]
[I.e SLUS-00404 Ace Combat 2 (USA)]

**Comment by stenzek** [comment]
Thanks for this! I've reordered a few things and added some others and it's now active.
