### ISSUE TITLE
Ubuntu 20.04 - Blank GUI? 

### ISSUE THREAD

**Issue by ItsYorkshire** [stenzek/duckstation#1058]
Hi..  I have Icons but no text on the GUI using Appimage?

Anyone else getting this.. ?
![DuckStation](https://user-images.githubusercontent.com/67055582/98655879-e5c50580-2337-11eb-90e1-a32330681cf9.png)

**Comment by stenzek** [comment]
Seems fine on a fresh Ubuntu 20.04 install.

Are you using hidpi/desktop scaling by any chance? The AppImage is stuck building on 18.04, which means it has a much older Qt version, and hidpi is pretty terrible in older Qt versions.

**Comment by ItsYorkshire** [comment]
ooh..  Dunno m8..  Im fairly new to Ubuntu so..  If i go to Settings I dont see "Devices" but I have my scale set to 100%..

Im aslo using a HDMI out to another screen.. 
![hdmi](https://user-images.githubusercontent.com/67055582/98687555-c773ff80-2361-11eb-8265-0c9306a1c7dc.png)

**Comment by stenzek** [comment]
Very strange then. Have you tried building from source and seeing if that also has the problem? Instructions are here: https://github.com/stenzek/duckstation#linux-1

**Comment by ItsYorkshire** [comment]
No I haven't..  I'll give them a read through and have a go..  But it will be tomorrow now too much on atm.. as we do.. tnx for your feedback :)

**Comment by stenzek** [comment]
Another user informed me that their scaling problems were fixed after moving the AppImage builder to Ubuntu 20.04, and this may have also been the issue here.
