### ISSUE TITLE
Switching regions doesn't seem to do anything

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#106]
All games seem to work regardless of region setting. The PS1 is region locked so unless the region is set to "auto" a game from the wrong region shouldn't work. 

![Capture](https://user-images.githubusercontent.com/31968468/76699164-b0134280-66fe-11ea-9e9f-7ecbaa712ee4.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/76699167-b6a1ba00-66fe-11ea-9186-c42f55abf160.PNG)

![Capture3](https://user-images.githubusercontent.com/31968468/76699168-bb666e00-66fe-11ea-8cad-cfa1f2f79109.PNG)

**Comment by stenzek** [comment]
Hmm, I implemented the necessary stuff for this a little while back. Might have an error somewhere.
