### ISSUE TITLE
Koudelka (USA) Graphical Issues 

### ISSUE THREAD

**Issue by TRR95** [stenzek/duckstation#1060]
**Game details**
SLUS-01051 Koudelka (USA)

**Description of the issue / bug**
The character modals are glitchy, from minor issues like weird black spots to more major ones like seeing through their heads

**Steps to Reproduce**
Just play the game

**Enhancements information**
I've tried both turning them off and with some on and nothing changes, turning them off just makes them blurrier 

**Hardware/software**
- Tried All Four: D3D11/OpenGL/Vulkan/Software
- OS: Windows 10
- CPU: Ryzen 1600x
- GPU: NVIDIA GTX 750
- RAM: 8 GB

**Emulator version**
0.1-2249-gca14e53c

**Additional context**
![Untitled](https://user-images.githubusercontent.com/49062935/98758366-38cca600-2394-11eb-8a97-2a28c8306b9c.png)

**Comment by TRR95** [comment]
There are UI issues as well
![Capooture](https://user-images.githubusercontent.com/49062935/98930300-1163ff00-24a2-11eb-84a5-df3700f1d76f.PNG)

**Comment by stenzek** [comment]
Polygon gaps are normal as far as I can tell, just exaggerated by higher resolution. Would need a game patch to get rid of them, I think.

Missing menu items were caused by PGXP CPU mode.
