### ISSUE TITLE
libretro - NeGcon doesn't work

### ISSUE THREAD

**Issue by oboewan42** [stenzek/duckstation#1062]
Using RetroArch, setting the controller type to "NeGcon" causes an "Unsupported controller type" error message. 

The game (tested using Wipeout XL) does recognize that a NeGcon is plugged in, but none of the buttons work.

(It also produces the "Unsupported controller type" message when I set the controller type to GunCon or Mouse, but I haven't yet tested whether or not those work.)

**Comment by stenzek** [comment]
Probably should just remove those from the libretro list.

**Comment by vavelpo** [comment]
I hope Libretro Core will support neGcon.

**Comment by stenzek** [comment]
Merged with #1064
