### ISSUE TITLE
Missing features in libretro core

### ISSUE THREAD

**Issue by stenzek** [stenzek/duckstation#1064]
Creating a single thread for these so it's easier to track, if I ever find the motivation/get around to implementing them. Or if anyone else wants to ;)

- [x] Built in compatibility ini for disabling broken enhancements
- [ ] .srm memory cards
- [ ] GunCon
- [ ] Mouse
- [ ] NeGcon
- [ ] Display padding in software renderer
- [ ] Multi-button toggle for analog mode

**Comment by negativeExponent** [comment]
rumble, negcon please.

**Comment by stenzek** [comment]
Rumble is implemented?

**Comment by negativeExponent** [comment]
last time i checked, there was no rumble. unless you added one lately, in which then i missed. let me verify.

**Comment by stenzek** [comment]
Maybe it's a frontend bug. Last I checked it was working, and I don't really have any interest in investigating it unless it's also broken in standalone.

It's implemented here: https://github.com/stenzek/duckstation/blob/master/src/duckstation-libretro/libretro_host_interface.cpp#L997

**Comment by negativeExponent** [comment]
sequences are not in order. a quick and dirty fix is moving **g_libretro_host_interface.InitInterfaces();** to **retro_init**. or just move InitRumbleInterface() to there instead, again a quick and dirty fix for me without having to spend much time isolating.

**Comment by stenzek** [comment]
So you can't get retrieve of the interfaces "too early"? Someone really should document this stuff somewhere, how are developers supposed to know otherwise :/

**Comment by DonelBueno** [comment]
Strange, I have rumble working normally in RA. I just tested in Gran Turismo and it works fine.

**Comment by negativeExponent** [comment]
what platform are you testing on? im on linux with latest commits compiled for both duckstation and retroarch. Im asking coz in on my test coz in my test **m_interfaces_initialized** is already set as "true" causing  InitRumbleInterface() not to be called at all? and even if  InitRumbleInterface() then gets called, **m_rumble_interface_valid = g_retro_environment_callback(RETRO_ENVIRONMENT_GET_RUMBLE_INTERFACE, &m_rumble_interface);** returns zero all the time despite **set_rumble_state**  returning a valid pointer, so rumble function never gets even initialized nor even tries to call the rumble callback in https://github.com/stenzek/duckstation/blob/ca14e53c4aa719eed23916405aa54dec0b7d35cd/src/duckstation-libretro/libretro_host_interface.cpp#L997

and just to verify, Gran Turismo also does not have rumble effects.

**Comment by stenzek** [comment]
I get the impression this is API breakage from Retroarch, and it behaved differently in 1.9.0. I'll just move the init around, it's easy enough to do.

**Comment by negativeExponent** [comment]
i dunno about api breakage but rumble never worked even since my first issue posted here (regarding Tales of Phantasia slow transition effects)

**Comment by DonelBueno** [comment]
@negativeExponent I'm on Windows 10, maybe that's the difference.

Using the latest Duckstation build and RA 1.9.0 x64 Stable.

**Comment by Allariah** [comment]
Yeah there's some weird issues with the RetroArch/Libretro side I believe.

For example, when you try and load Time Crisis or Time Crisis: Project Titan, the core seems to correctly identify that there's a GunCon plugged in, as it prompts the Calibration Screen, but in the bottom left you get an error in the bottom left:
" Error: Unhandled controller type 'Namco GunCon'. "
![image](https://user-images.githubusercontent.com/1160349/102681902-20368380-41bd-11eb-8cdc-b4ff40b590b5.png)

**Comment by stenzek** [comment]
GunCon is not handled on the libretro side. The emulator itself simulates the guncon, but there's no connection with the frontend so it doesn't know where you're pointing. The main issue is (as far as I'm aware) there's no way to query the window dimensions from the core, and the way I compute the gun position requires this information.

**Comment by stenzek** [comment]
Closing as the libretro core has been removed now - please see https://github.com/stenzek/duckstation/commit/419726f4cca2a3e054d99e374b384966713c736c and the libretro fork if you wish to continue to use it.
