### ISSUE TITLE
[Enhancement/Android Standalone] Improve holding buttons on touchscreens

### ISSUE THREAD

**Issue by PookaMustard** [stenzek/duckstation#1065]
**Is your feature request related to a problem? Please describe.**
The touchscreen used by Duckstation isn't quite up to par for stuff like jumping while charging (the Spyro series), or holding all four shoulder buttons at once, or any other combo in which you press a button while holding another.

**Describe the solution you'd like**
I propose that the first button you hold remains held as long as you don't release your finger, and any buttons you swipe over are pressed/held as well until you swipe away. For an example:

1. Hold square
2. Swipe away from square: square remains held
3. Swipe over to X/cross: it is now held
4. Swipe away from X/cross: it is now released
5. Take your finger off the screen: Square is now released.

This feature can be configurable such that it you can enable or disable it for the D-pad. A live example of this can be experienced in the [Super Mario 64 native mobile port](https://github.com/JustMeDaFaq/sm64-port-android). It can work with multiple taps as well, providing support for features such as holding all four shoulder buttons with just two fingers.

**Describe alternatives you've considered**
None so far.

**Additional context**
When playing the aforementioned Super Mario 64 mobile port, I found it extremely easy to do stuff like long jumps, thanks to the fact I could hold Z/Trigger and swipe over to the A button without Z/Trigger getting released. I can imagine if this little trick did wonders for SM64, it would for many games, even if it needs to be enabled via the settings screen.

**Comment by clod2692** [comment]
Yes, buttons remap is absolutely necessary, i want to add that xbox elite controller's triggers don't work, but a remap option maybe could fix this issue

**Comment by PookaMustard** [comment]
Closed with the merging of #1723.
