### ISSUE TITLE
Red Asphalt (USA) don't work for me!

### ISSUE THREAD

**Issue by momoids** [stenzek/duckstation#1070]
After the opening screens, the screen goes black!
![01](https://user-images.githubusercontent.com/70231770/99142643-bcf18880-2635-11eb-991b-5dfa01ef7ca4.jpg)
![02](https://user-images.githubusercontent.com/70231770/99142644-bebb4c00-2635-11eb-8f15-ae2a083af926.jpg)
![03](https://user-images.githubusercontent.com/70231770/99142646-bebb4c00-2635-11eb-9949-d42d0ffbc7fc.jpg)
![04](https://user-images.githubusercontent.com/70231770/99142647-bf53e280-2635-11eb-9c03-f21b247aa315.jpg)

**Comment by stenzek** [comment]
DMA timing issue, same issue as https://github.com/stenzek/duckstation/issues/141

I have a fix, just need to check for regressions.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/71eb578db18570311c4ee9f4009e83cfecdee2aa
