### ISSUE TITLE
Flickering borders in some games

### ISSUE THREAD

**Issue by backgamon** [stenzek/duckstation#1073]
There are some games with flickering borders, mainly right of the screen.

Currently i found 2 games with that problem:
Die Hard Trilogy (driving part)
Steel Harbinger (whole game).

On cropping option:
All Borders
![1](https://user-images.githubusercontent.com/39404647/99151089-0fb05c00-2699-11eb-850f-04d271d87d6a.jpg)
Overscan area only
![2](https://user-images.githubusercontent.com/39404647/99151096-1b038780-2699-11eb-8319-7afb765df1f4.jpg)
None
![3](https://user-images.githubusercontent.com/39404647/99151099-222a9580-2699-11eb-9d89-ce9d9ee7d05e.jpg)

**Comment by ggrtk** [comment]
The flickering sections are in overscan area that isn't typically visible on CRT televisions. If the flickering behavior isn't visible when cropping is set to "Only Overscan Area", then this isn't an issue. "All Borders" and "None" aren't really meant for general usage.

**Comment by stenzek** [comment]
Working as intended like @ggrtk said.
