### ISSUE TITLE
Androido: Add github update version code in the app next to duckstation icon in the blue label to see it and know which is at the first sight

### ISSUE THREAD

**Issue by HJMBgit84** [stenzek/duckstation#1074]
please add option to see the app github release version i.e. 3f9ba4a in the label menu inside the app to see what's the version we have in android.

**Comment by stenzek** [comment]
I don't think the average Android user even knows there's a git repository, given they 1-star the app because of a small bug instead of reporting it. So I'm not convinced this is worthwhile :p

But that said, we probably should have a way of converting the tag (0.1-NNNN) to a commit.

**Comment by HJMBgit84** [comment]
Well, I did not discover your app for playstore, that is the reason why I commented this because everytime that I check on github I need to open the app info to see if it is the newest version instead of seeing it from the start at first sight :( anyway thanks for your work.

**Comment by stenzek** [comment]
Full version info added in https://github.com/stenzek/duckstation/commit/ead1be4728544d0207664646705da1d99af8b559 - hit the menu button in the game list, and tap "Show Version".
