### ISSUE TITLE
Spyro 3: Loading Screen flickering with Crop-Setting "All Borders"

### ISSUE THREAD

**Issue by GitToTheHub** [stenzek/duckstation#1076]
**Game details**
SCES-02835, Europe

**Description of the issue / bug**
When I set the the crop-setting to "All Borders" and a loading screen appears, the loading screen switches its size rapidly between a larger and smaller version. Here are screenshots of the switching:

Normal loading screen:
![SCES-02835_2020-11-14_21-36-55](https://user-images.githubusercontent.com/13721821/99157659-d7be0e80-26c2-11eb-9cf6-c248a84c817f.png)

Enlarged loading Screen:
![SCES-02835_2020-11-14_21-37-03](https://user-images.githubusercontent.com/13721821/99157660-d8ef3b80-26c2-11eb-861d-7e6b1d0b61db.png)

When I set the crop-setting to "None" or "Only Overscan Area", the issue will not occure, but you will see a light gray box at the bottom edge of the loading screen which is flickering and the loading screen itself wobbles a little bit.

**Hardware/software**
Windows 10 64-Bit, D3D11

**Emulator version**
Master from Sat, 14. Nov. 2020 (0.1-2268-g3f9ba4ac)

**Comment by ggrtk** [comment]
"All Borders" and "None" are not for general use.

Looks like the game is alternating between outputting 240 and 256 lines of VRAM on loading screens. The VRAM looks fine, I'm guessing there's some precision issues in how the host display draw rectangle is being calculated across those two different outputs that causes minor sampling differences, which might lead to the wobbling you're seeing.

**Comment by GitToTheHub** [comment]
Ok thank you, so is this is an issue, or not? Independent from this, I still see a wobbling of the loading screen in the crop-mode "Only Overscan Area" and the light gray box flickering at the bottom of the loading screen.

You wrote
> "All Borders" and "None" are not for general use.
So is the best setting here "Only Overscan Area" for the general use?

**Comment by ggrtk** [comment]
> So is the best setting here "Only Overscan Area" for the general use?

Yes, "Only Overscan Area" is the one to use for general use.

The light gray section is present in the game's VRAM and the game alternates between displaying it and not displaying it, so it's not really a bug.

Will submit a fix for the wobbling after some more testing.

**Comment by GitToTheHub** [comment]
Thank you for your comment. It sounds weird, that the game is doing this with the gray section .. It sounds like a bug from the game. Thank you for your effort :)

**Comment by stenzek** [comment]
This is no longer noticeable if you use linear upscaling. With it disabled, you'll still get a tiny bit of wobble - this is because the game is alternating between different display resolutions.
