### ISSUE TITLE
Spyro the Dragon (Jul 19, 1998 prototype) crashes instantly after BIOS screen

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#108]
Hidden Palace mentions that it has protection that stops it working on a standard console but doesn't specify what it CAN be played on. 

![Capture](https://user-images.githubusercontent.com/31968468/76702445-152a6080-671e-11ea-852b-edd18297dfbd.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/76702448-1f4c5f00-671e-11ea-8a8a-e84e87ef18fa.PNG)

**Comment by stenzek** [comment]
I'm not sure what the use of making this work would be. If it doesn't boot on the real console, then it'd require a non-realistic hack.

**Comment by kurayami6** [comment]
Would it work on a development unit? Hidden Palace included a patched version that removes the protection but it'd be nice to be able to play it unaltered.

**Comment by stenzek** [comment]
I guess emulating the development unit-specific properties could be an enhancement, assuming that's all it needs.

**Comment by kurayami6** [comment]
Pointless to keep this open. It need to be patched to run on real hardware anyway.
