### ISSUE TITLE
Compatibility rating stars doesn't work as intented on Linux

### ISSUE THREAD

**Issue by DarkSwan86** [stenzek/duckstation#1082]
Hi @stenzek ,

I'm building your emulator from the source and i've noticed that on Linux the stars on the frontend are not displayed correctly, they are always grey. On windows it works as intended. I've also tried to search on all the folders on the Linux build but there is no compatibility.xml anywhere.

Is it something missing from the Linux port? Thanks!

**Comment by ggrtk** [comment]
If you're building from source, you need to copy and place the `database` directory (found inside the repository's `data` directory) next to the DuckStation executable. The CMake build process doesn't automatically do this for you.

**Comment by stenzek** [comment]
> The CMake build process doesn't automatically do this for you.

We probably should change that...

**Comment by stenzek** [comment]
As far as I can tell, the database files are being bundled in the AppImage (at least the one from the CI), and compatibility ratings get displayed from a quick test. Remember not all games are tracked in the database yet!

**Comment by DarkSwan86** [comment]
Hi @stenzek ! 

I usually build from the source and i prefer not use the AppImage. 

Maybe it's not possible to change the CMake build to also install a copy of the database but can i ask you if you can add to the main page the instructions where you should put the compatibility.xml file? 

I've put it in .local/share/duckstation/database/ but still it doesn't work, what i'm missing? 

I'm using the same chd on both windows and linux and on windows the stars works on some of them.

Thanks for the patience!

**Comment by stenzek** [comment]
Building from source should definitely be fine. It should dump everything in a `bin` directory inside your build directory (should have database, inputprofiles, etc subdirectories)

**Comment by ggrtk** [comment]
Whoops, not sure why I said earlier that the CMake build doesn't place the `database` directory next to the DuckStation executable, it definitely does. Sorry for any confusion.

@DarkSwan86 The `database` folder needs to be placed next to the DuckStation executable in the program directory, not in the user directory. Like Stenzek said, everything should already be in the `bin` directory created during the build process. If you move the DuckStation executable, you need to move the `database`, `translations`, etc. folders along with it.

**Comment by DarkSwan86** [comment]
@ggrtk , i don't move anything manually, everything is installed via Pamac, using the AUR repo for the duckstation-git.

This is the PKBUILD file from within Pamac:


```
pkgname=duckstation-git
pkgver=latest.r2972.50273899
pkgdesc='A Sony PlayStation (PSX) emulator, focusing on playability, speed, and long-term maintainability'
pkgrel=1
arch=('x86_64' 'aarch64')
url="https://github.com/stenzek/duckstation"
license=('GPLv3')
makedepends=('git' 'cmake')
depends=('gtk2' 'sdl2' 'qt5-base' 'qt5-tools')
optdepends=(
)
provides=('duckstation')
conflicts=()

_branch=master
source=("git+https://github.com/stenzek/duckstation.git#branch=${_branch}")
sha256sums=('SKIP')

pkgver() {
  cd "${srcdir}/duckstation"
  printf "%s.r%s.%s" "$(git describe --abbrev=0 --tags)" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

build() {
  cd "${srcdir}/duckstation"

  cmake -DCMAKE_BUILD_TYPE=Release
  make
}

package() {
  cd "${srcdir}/duckstation"

  install -m 755 -d "${pkgdir}/usr/bin/"
  install -m 755 -t "${pkgdir}/usr/bin/" bin/duckstation-sdl bin/duckstation-qt

  install -m 755 -d "${pkgdir}/usr/share/applications/"
  install -m 644 appimage/duckstation-qt.desktop "${pkgdir}/usr/share/applications/duckstation.desktop"
  sed -e 's/Terminal=true/Terminal=false/' -e 's/Name=DuckStation Qt/Name=DuckStation/' -e 's/Icon=duckstation-qt/Icon=duckstation/' -i "${pkgdir}/usr/share/applications/duckstation.desktop"

  install -m 755 -d "${pkgdir}/usr/share/pixmaps/"
  install -m 644 appimage/icon-64px.png "${pkgdir}/usr/share/pixmaps/duckstation.png"
}
```

[HERE](https://pastebin.com/t9crRjsw) is the building log of my latest update. Is there something wrong that is not copied? :(

**Comment by DarkSwan86** [comment]
@stenzek i've rebuild again and the only folder inside "bin" is translation as you can see in this screenshot:

![ducksrc](https://user-images.githubusercontent.com/24975273/101288196-91595c80-37f5-11eb-93a4-1fc0225b1536.png)

**Comment by ggrtk** [comment]
I'd suggest bringing this up with the maintainer for the AUR package. As stated in the DuckStation README, "Binaries or packages distributed through other sources may be out of date and are not supported by the developer."

**Comment by stenzek** [comment]
I guess maybe we should offer the option to store the data files away from the executable to better support the 'linux style directory structure'...

**Comment by DarkSwan86** [comment]
As https://github.com/stenzek/duckstation/commit/b51a4856d7615e8df42bce09d1362d03c95c275a now the ratings stars work correctly. Probably something about the packager on AUR.
