### ISSUE TITLE
duckstation for nintendo switch

### ISSUE THREAD

**Issue by tabnk** [stenzek/duckstation#1083]
Is there a possibility to port duckstation to nintendo switch with https://github.com/switchbrew/libnx ?

**Comment by stenzek** [comment]
I don't own a Switch, so this is something I have no interest in. But if anyone else wants to port it, I'm open to merging things upstream.

I suspect enforcing W^X would be an issue, but the JIT could always double map.

All that said, I've heard it runs fine on Linux on the Switch ;)
