### ISSUE TITLE
Red Asphalt (USA) Stop in second loading bar!

### ISSUE THREAD

**Issue by momoids** [stenzek/duckstation#1085]
Game Stop in second loading bar!
![Red Asphalt (USA)](https://user-images.githubusercontent.com/70231770/99619878-204b3400-2a03-11eb-8994-f76f52556dcd.jpg)

**Comment by stenzek** [comment]
Make sure you're applying game settings, and not loading an old save state. Rescan your game list, and then right click -> default boot.

If that doesn't work, right click the game, and make sure GPU Run Ahead is set to 1 and Max DMA Slice Ticks is set to 200 in compatibility settings.
