### ISSUE TITLE
Graphics Issue with shadows in Suidoken 2 (PAL) (Spain) (retroarch)

### ISSUE THREAD

**Issue by darkxex** [stenzek/duckstation#1086]
Disc: SLES-02445
This is with Directx11 render and Vulkan render and OpenGL is the more bugged.
![image](https://user-images.githubusercontent.com/17991404/99753576-302b4c80-2ac5-11eb-923c-3470a3008443.png)

this is with Software render mode
![image](https://user-images.githubusercontent.com/17991404/99753836-d4ad8e80-2ac5-11eb-8657-1445cdcbd641.png)

note: i am using the last build of Retroarch. (core version 0.1- 2291

**Comment by darkxex** [comment]
![image](https://user-images.githubusercontent.com/17991404/99755678-1e987380-2aca-11eb-82d3-60aa7743babc.png)
I downloaded the windows x64 version with the default configuration and the bug persists.

**Comment by stenzek** [comment]
Seems to be mask bit related, it flickers on my end. Will investigate soon.

**Comment by darkxex** [comment]
thanks my friend, i will waiting for the fix.

**Comment by stenzek** [comment]
Can't test the Spanish version, but hopefully this change fixes it: https://github.com/stenzek/duckstation/commit/07dbc5a80dd56b3d1726d0261a9bd17c9297ccfc

**Comment by darkxex** [comment]
![image](https://user-images.githubusercontent.com/17991404/99895557-833d0500-2c67-11eb-9cc0-726e1279a9f1.png)
Fixed, checked in vulkan and direct11. thanks for all. thread is closed.
