### ISSUE TITLE
[Crash] Emulator crash if try to load state at the same time that a "load CD" operation is performed

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#1087]
**Version**
0.1-2291-g83db6853

**Game Example**
SLUS-00741 - Heart of Darkness (Disc 2)
In the disc 2 of Heart of Darkness this issue happens a lot, due the game works loading the CD every time.
I attached a memory card for a part that have this behavior that crashs the emulator on save state loading (you'll have to create your own savestate to this)
[Heart of Darkness (USA) (Disc 2)_1.zip](https://github.com/stenzek/duckstation/files/5575331/Heart.of.Darkness.USA.Disc.2._1.zip)

**One example to get the issue**
Get to the "dropped bridge part", save just before die, die and immediatelly try to load the state.

Also, would be good to have an "auto-savestate backup", saving the last savestate just before a new savestate is created to avoid lost progress when this kind of issue happens. Just auto-save the last savestate as [name of the savestate]_number.backup as example, in case of the last savestate is lost, the user can just rename the savestate before it as [name of the savestate]_number.sav ;)

**Comment by stenzek** [comment]
Can't seem to reproduce this. I might not be doing it correctly?

**Comment by stenzek** [comment]
Closing due to lack of response. If this is still happening, please upload the crash.dmp file and list the build used.
