### ISSUE TITLE
[Savestate] The button pressed when a savestate is wrote, keeps being pressed after load state

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#1088]
**Version**
0.1-2291-g83db6853

**Issue**
If you save a state with a button pressed in controller, the game will treat as the button is keeping pressed even when it's not.
The button just will be treated as not pressed if you press the same again

**Expected behavior**
After load the savestate, emulator see if the button isn't pressed anymore and react normally.

**Comment by stenzek** [comment]
Do you have "Load Devices From Save States" checked in options?

**Comment by Shideravan** [comment]
![image](https://user-images.githubusercontent.com/12163923/99866444-f5421b00-2b8f-11eb-8928-f40a10e61dbc.png)
No, but this behavior happens in both this option enabled ou disabled (I forcely reloaded the emulator and a game booting from the start when created a new save with this option checked too).
It might be worth noting that I'm using a physical controller (Nintendo Switch Pro Controller with Better Joy).

**Comment by Shideravan** [comment]
The behavior happens with keyboard only config too (Switch controller uninstaled).
Tested with Heart of Darkness game.

**Comment by Richard-L** [comment]
Yeah this has been around since the beginning and we addressed it in Discord once. Usually you can break the "lock" by hitting the same button again so it resets it.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/125d104df4f1d5eafcf7e367b4d15fc41f543a1e
