### ISSUE TITLE
game list with covers support

### ISSUE THREAD

**Issue by mrdeathjr28** [stenzek/duckstation#109]
hi

ePSXe have game list with covers, i dont know if this feature (qt-sdl modes) can be added in duckstation

![gmls](https://user-images.githubusercontent.com/6601480/76705554-ee811100-66ae-11ea-9092-8f4a9a69bd73.jpg)

thanks

**Comment by stenzek** [comment]
Definitely something I can look into.

Is there a good source for game covers which allows us to scrape their database?

**Comment by mrdeathjr28** [comment]
maybe this page can help:

https://psxdatacenter.com/sitenews.html

**Comment by bajolzas** [comment]
I would be cool if we could provide a png for a cover, instead of relying on a database.
I dont really want the US Suikoden cover to appear, I'd also like to give each arc the lad game its own cover

**Comment by DarkFrost89** [comment]
it is ftp database in psxdatacenter.com its looking good
https://psxdatacenter.com/images/hires/

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/43b0d84a1d51797f7463b760b82c0f60568ffcb6

See https://github.com/stenzek/duckstation/wiki/Adding-Game-Covers
