### ISSUE TITLE
Portable mode directory request/issue?

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#1097]
Here's the thing, I use the portable mode as I have Ducko with games on a portable drive, the problem is when I connect it to a PC with different amount of drives it gives the portable drive a different letter.
This breaks a few things as these things use specific paths like.
BIOS location.
Game listing.
Save states (disc location)

The first two ain't that big of a deal but the third one just makes save states unusable.
I'd be great if Ducko had it's own default folders in portable mode for BIOS and games that don't have to be specified, like the memory cards

**Comment by stenzek** [comment]
The working directory is changed to the user directory on startup. So you can use paths relative to that - just have to manually set them. In the ini.

I'm not sure how to solve the save state issue. How else is it to know where the disc is?

**Comment by foxsevent** [comment]
> I'm not sure how to solve the save state issue. How else is it to know where the disc is?
You can't, but you could get around by having the games in the games always in the same relative location like the memory cards.

Suing path relative may just both problems, could you explain a bit more how to do it?

**Comment by Nucleoprotein** [comment]
@stenzek 
Just display file selection? For checking if correct savestate is used use game ID or PSXEXE hash?
You can also automatically match by game ID for current loaded list of games - that would be awesome.

**Comment by stenzek** [comment]
> Using path relative may just solve both problems, could you explain a bit more how to do it?

If you have BIOS files in D:\DuckStation\bios, you would set the BIOS path to "bios". It would then search for a directory named bios in the user directory (D:\DuckStation).

> Just display file selection? For checking if correct savestate is used use game ID or PSXEXE hash?

I've thought about it, but it's easier said than done. Doing so creates a potential deadlock - UI thread is waiting for the emu thread, but the emu thread is waiting for the UI thread to display the selector. Passing strings back is also potentially messy. I don't think it's worth the complexity for such a niche use case.

> You can also automatically match by game ID from current loaded list of games - that would be awesome.

What if there are multiple images with the same ID?

**Comment by foxsevent** [comment]
> @stenzek
> Just display file selection? For checking if correct savestate is used use game ID or PSXEXE hash?
> You can also automatically match by game ID from current loaded list of games - that would be awesome.

The issue with the save states is an odd one as it happens when the game is already running, so Ducko knows where and what the game is it's just that information conflicts with the saved location of the game in the save state.
Like why does the save state cares where the game is? all it should care if it is the same game running by checking game ID or game file name, again could be made like the memory cards, where created save states are matched to game per ID or file name.

**Comment by Nucleoprotein** [comment]
> What if there are multiple images with the same ID?
Store and match PSXEXE hash?

**Comment by stenzek** [comment]
> The issue with the save states is an odd one as it happens when the game is already running, so Ducko knows where and what the game is it's just that information conflicts with the saved location of the game in the save state.
> Like why does the save state cares where the game is? all it should care if it is the same game running by checking game ID or game file name, again could be made like the memory cards, where created save states are matched to game per ID or file name.

You are incorrect here. Save states can be loaded without starting a game first. You can also have a save state without a disc inserted (homebrew exe booting for example). So yes, it needs the location when loading the state to know which disc image to mount.

> Store and match PSXEXE hash?

Again, way too much complexity for a niche use case. There's many programs which will have an issue if you move them around/change drive letters.

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation/blob/022f7465c4ad4707b1417ea760c85d95f47d2b9b/src/core/system.cpp#L945 - first thing it does when loading a state apart from checking the version is mount the disc image. If the path matches, it uses the existing image (avoids re-preloading on load state when that option is enabled).

**Comment by foxsevent** [comment]
> > The issue with the save states is an odd one as it happens when the game is already running, so Ducko knows where and what the game is it's just that information conflicts with the saved location of the game in the save state.
> > Like why does the save state cares where the game is? all it should care if it is the same game running by checking game ID or game file name, again could be made like the memory cards, where created save states are matched to game per ID or file name.
> 
> You are incorrect here. Save states can be loaded without starting a game first. You can also have a save state without a disc inserted (homebrew exe booting for example). So yes, it needs the location when loading the state to know which disc image to mount.
Fair enough, I didn't know, in any case thanks in my situation the problem is solved as I can just make a ISO folder and have Ducko always point to it, meaning there never will be location conflict.

The only thing I can add is to make this relative paths more user friendly in portable mode, like a default setting and have a ISO default folder.

Cheers.

**Comment by stenzek** [comment]
Not really sure what else could be done. Saying the bios path is "bios" rather than "D:\DuckStation\bios" would be more confusing to a user in my opinion.

Everything else (save states, memcards in per-game mode, screenshots, etc) uses auto paths from the user directory so it's not an issue.

**Comment by foxsevent** [comment]
> Not really sure what else could be done. Saying the bios path is "bios" rather than "D:\DuckStation\bios" would be more confusing to a user in my opinion.
> 
> Everything else (save states, memcards in per-game mode, screenshots, etc) uses auto paths from the user directory so it's not an issue.

I was thinking more like instead of telling people to go into settings - bios and there select their BIOS, just tell them to put the BIOS file into the BIOS folder.
Same with games rather than have user go to game list settings to specify location just tell them to throw the game file into the ISO folder in Duckstation.

Both ways don't have to exclude each other, just have a default set of folders for BIOS and ISO that the emulator searchers in it's directory by default and if user wants to change than he can do so in the settings.

**Comment by stenzek** [comment]
> I was thinking more like instead of telling people to go into settings - bios and there select their BIOS, just tell them to put the BIOS file into the BIOS folder.

That's actually how it already works - the default search directory is `<user directory>/bios`. Read the instructions on the main page ;)

**Comment by foxsevent** [comment]
> > I was thinking more like instead of telling people to go into settings - bios and there select their BIOS, just tell them to put the BIOS file into the BIOS folder.
> 
> That's actually how it already works - the default search directory is `<user directory>/bios`. Read the instructions on the main page ;)
> 
> (it just displays the full path in the settings so it's less confusing)

You should know already that nobody reads the manual by now xD, and that didn't work mer at least, when the drive letter changed the first error I got was BIOS file not found.

Then could you make a default for ISO?

**Comment by stenzek** [comment]
I guess you could try this for `<user directory>\iso`:
```
[GameList]
RecursivePaths = iso
```
May work, not sure. But this isn't something I want to support or encourage, it's too error prone (thinking about third party libraries/code changing the working directory).

**Comment by foxsevent** [comment]
> I guess you could try this for `<user directory>\iso`:
> 
> ```
> [GameList]
> RecursivePaths = iso
> ```
> 
> May work, not sure. But this isn't something I want to support or encourage, it's too error prone (thinking about third party libraries/code changing the working directory).

And that does work indeed, and works perfectly for portable mode where you swap the drive around, for other uses you know better so fair enough and thanks for the help.
