### ISSUE TITLE
The Misadventures of Tron Bonne (USA) - Game gets stuck randomly while playing

### ISSUE THREAD

**Issue by bowlofspiders** [stenzek/duckstation#1098]
**Game details**
SLUS-00896, USA

**Description of the issue / bug**
When the game attempts to load a dialogue box the game will get stuck not allowing you to proceed
This can also happen when opening the pause menu

![SLUS-00896_2020-11-23_08-50-32](https://user-images.githubusercontent.com/53333627/99976416-6b51a800-2d71-11eb-8195-b9b2b8e572b3.png)

![SLUS-00896_2020-11-23_09-36-25](https://user-images.githubusercontent.com/53333627/99976451-74427980-2d71-11eb-8e54-289431d5d390.png)

**Steps to Reproduce**
Play through Mission 2 then play through Mission 1
This bug seems to happen after the game has been running 5-10 minutes
Memory card: [Misadventures of Tron Bonne, The (USA)_1.zip](https://github.com/stenzek/duckstation/files/5583807/Misadventures.of.Tron.Bonne.The.USA._1.zip)

**Hardware/software**
i7 8700k
1080Ti
Windows 10 64-bit
D3D11 and OpenGL tested
Interpreter and recompiler

**Emulator version**
0.1-2347-g44b3c9be

**Comment by stenzek** [comment]
Relies on the block loop address being ignored but writes the value while the voice is off. Needs more thought so the fix does not regress Re-loaded The Hardcore Sequel.

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/917fa5dd0eb6c7d1240c4206d98c9107e6303423

**Comment by stenzek** [comment]
Oh, I probably should mention - you'll need to do a full boot after updating, not load a state. The interrupt which causes it to softlock will be stuck on in the state, and it needs a clean start to get properly disabled.

**Comment by bowlofspiders** [comment]
Thanks for this! Played for 20 minutes with with a full boot and no issues in build 0.1-2363-gfcbd6187. Closing.
