### ISSUE TITLE
Vagrant Story issue collection

### ISSUE THREAD

**Issue by trostboot** [stenzek/duckstation#11]
A selection of issues currently present in Vagrant Story (SLUS-01040), specifically its opening, so it's not very comprehensive.
Latest build (edb6d7c), CPU interpreter, HW OGL and SW renderers where noted.
Comparisons from standalone mednafen, I can't currently capture from real hardware.

**_Issues present in both HW OGL and SW renderer_**
Motion blur is broken.
Duckstation SW: 
![vs_sw_03](https://user-images.githubusercontent.com/17594477/73748112-1ba9dd80-4759-11ea-8bec-71c0c1be00e5.png) 
mednafen:
![Vagrant Story  NTSC-U -0001](https://user-images.githubusercontent.com/17594477/73748163-29f7f980-4759-11ea-8ef1-8fa0ac6aa26f.png)

Duckstation HW OGL:
![vs_hwgl_03](https://user-images.githubusercontent.com/17594477/73748251-4f850300-4759-11ea-96ac-735a2e9a8771.png)
mednafen:
![Vagrant Story  NTSC-U -0003](https://user-images.githubusercontent.com/17594477/73748279-5ad82e80-4759-11ea-93f9-be650e8c358e.png)

**_Issues present only in HW OGL renderer_**
Garbage on the bottom of the screen, flickering line at the top
![vs_hwgl_02](https://user-images.githubusercontent.com/17594477/73748503-e356cf00-4759-11ea-80f9-36572e91b4fe.png)
![Vagrant Story  NTSC-U -0005](https://user-images.githubusercontent.com/17594477/73748821-860f4d80-475a-11ea-863f-16ed1deb3dd6.png)

Overlapping geometry/broken geometry occlusion/something alone those lines:
![vs_hwgl_01](https://user-images.githubusercontent.com/17594477/73748617-18fbb800-475a-11ea-885f-c9673d3eb310.png)
![Vagrant Story  NTSC-U -0000](https://user-images.githubusercontent.com/17594477/73748627-1ef19900-475a-11ea-87a5-1d4127dc2358.png)
![vs_hwgl_04](https://user-images.githubusercontent.com/17594477/73748640-26b13d80-475a-11ea-872a-8db695210f16.png)
![Vagrant Story  NTSC-U -0004](https://user-images.githubusercontent.com/17594477/73748655-2d3fb500-475a-11ea-8f55-44e507fce76f.png)

Glitchy screen wipe
![vs_hwgl_05](https://user-images.githubusercontent.com/17594477/74006859-3d83aa00-497d-11ea-9f5c-35e6d2a4d122.png)

**_Audio issues_**
Lack of reverb obviously means the audio in general is very incorrect, but there's some other glitches occasionally. Excuse the volume differences for these clips, I didn't want to re-record it, but it does make the clipping seem worse in duckstation. Note the repeating sounds after the initial explosion.
[audio.zip](https://github.com/stenzek/duckstation/files/4153548/audio.zip)

**Comment by stenzek** [comment]
Thank you for the detailed report! Much appreciated. I'm currently on away on holidays but will try to look into it in a couple of weeks.

**Comment by stenzek** [comment]
Motion blur should be fixed in both hardware and software in https://github.com/stenzek/duckstation/commit/1e45c9c4e138eba2cc670962bb98d2e1b20939f0. I think this also affects some cutscene/battle transitions in FF8, possibly others.

The flickering lines around the map once you get ingame present only in the hardware renderer should've been fixed in https://github.com/stenzek/duckstation/commit/7e862cd63e511f2b7597506f68d88fa30937027b.

I'll look into the the other issues when I have time.

**Comment by trostboot** [comment]
Can confirm that the motion blur is fixed.

The flickering line is still there, however, but you may have been looking at a different issue that I hadn't noticed. I was referring to the (single pixel tall?) line at the top of the screen. It's always there in OGL HW mode, but not D3D11 HW or SW.

**Comment by trostboot** [comment]
There are some seams/off-color pixels on characters with HW rendering.
Left HW OGL, right SW, note the face and hair of Ashley, and the hood of the left NPC:
![vs_hw_sw_comp_01](https://user-images.githubusercontent.com/17594477/74107646-923c4600-4b72-11ea-979d-7277880520b4.png)
![vs_hw_sw_comp_02](https://user-images.githubusercontent.com/17594477/74107647-95373680-4b72-11ea-9fa9-b1af3f801032.png)

Additionally, saving the game to memory card causes on-screen message spam, causing slowdown.

**Comment by stenzek** [comment]
Missing geometry should be fixed by https://github.com/stenzek/duckstation/commit/149cbf6457940f6d3eb57ce3481e8534d1ef6673

The textures being misaligned is a more complex issue, but will look into it eventually.

**Comment by trostboot** [comment]
> Missing geometry should be fixed by [149cbf6](https://github.com/stenzek/duckstation/commit/149cbf6457940f6d3eb57ce3481e8534d1ef6673)

Can confirm it is fixed indeed.

**Comment by stenzek** [comment]
Texture alignment issues are fixed in latest master as far as I can tell.
