### ISSUE TITLE
Qt command line?

### ISSUE THREAD

**Issue by Blackbird88** [stenzek/duckstation#110]
No matter what I do I can't launch a game from a frontend with Qt version. It just opens it without launching anything. SDL is fine, but I really prefer Qt myself.
Is there some command line option needed for this to work or is it not implemented yet?

**Comment by stenzek** [comment]
Currently not yet implemented. Will do soon.

**Comment by tony971** [comment]
Would love to see this with a "nogui" command option for third party launchers. PCSX2 and mGBA have implementations of this. It basically boots directly to the game, only showing the render window, and closes the emulator with the escape key.

**Comment by stenzek** [comment]
You're probably better off using the SDL frontend for a "nogui" version, at least once I move it over to the common controller binding code. Qt would just get in the way.

That said, I'll probably look at a libretro interface or something else which is embedded at some point, which would fit cleaner into an alternative frontend.

**Comment by tony971** [comment]
If the plan is to have the two frontends share configurations, then having a potential nogui command as an SDL exclusive sounds fine. Render windows are render windows.

But if you're looking into libretro anyway, no reason to waste your time duplicating features.

**Comment by stenzek** [comment]
The configuration files are already shared :)

Adding a batch mode which closes the emulator when the game exits is easy.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/81cf4b469fe25e1a327d3cf4cf7b3e9276c5bb15, sorry for the delay!

Batch mode is included, should work okay with shortcuts and/or emulator frontends.

**Comment by Blackbird88** [comment]
-fullscreen doesn't work for me

**Comment by stenzek** [comment]
Works in SDL, not Qt apparently. Will investigate.

**Comment by stenzek** [comment]
Fixed in latest push.

**Comment by Blackbird88** [comment]
Works now! Thanks!
