### ISSUE TITLE
Crashes after update. (Retroarch core)

### ISSUE THREAD

**Issue by life8853** [stenzek/duckstation#1100]
When i use fully updated version after any games can't launch. When i deleted duckstation.opt games started openning but the OSD from retroarch like fps counter, retroachivements pop-ups where in very low resolution.
[duckstation.opt.TXT](https://github.com/stenzek/duckstation/files/5584829/duckstation.opt.TXT)

**Comment by 6lackmag3** [comment]
libretro armv7 core just crashes on game loading.

[retroarch__2020_11_23__23_00_31.log](https://github.com/stenzek/duckstation/files/5586033/retroarch__2020_11_23__23_00_31.log)

**Comment by ColorblindMonk** [comment]
I'm also getting the same problem on Windows and Android versions of the core. Only seems to happen when loading up the core with OpenGL set as the hardware renderer.

**Comment by stenzek** [comment]
Will push a fix soon.

For what it's worth, you should not be using OpenGL with DuckStation, it's the slowest renderer by far and has small errors in some games. If you're using Windows, use D3D11, or on Linux/Android, use Vulkan.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/7fd22958aeb517b7bd4f544d15c2572d88fbd924

**Comment by stenzek** [comment]
Closing as the issue has been resolved.
