### ISSUE TITLE
Libretro segmentation fault with vulkan 

### ISSUE THREAD

**Issue by herbymachine** [stenzek/duckstation#1101]
**Game details**
Any games

**Description of the issue / bug**
"retroarch" received signal SIGSEGV, Segmentation fault. 

**Steps to Reproduce**
Set duckstation_GPU.Renderer = "Vulkan". Load any game. 
Software and OpenGL renderer work fine.
[back trace](https://github.com/stenzek/duckstation/files/5589032/bt-duckstation.txt)

**Enhancements information**
None

**Hardware/software**
Intel® Core™ i7-8809G Processor with Radeon™ RX Vega M GH graphics 
AMDGPU - Mesa-20.2.3
retroarch 1.9.0 and [retroarch 96af31bce72e03d92a39724b0964f10b33411317](https://github.com/libretro/RetroArch/tree/96af31bce72e03d92a39724b0964f10b33411317)

**Emulator version**
[duckstation de61d61396a828dbc5afd9b8c08cf7d3711129b](https://github.com/stenzek/duckstation/tree/ade61d61396a828dbc5afd9b8c08cf7d3711129b)

**Additional context**
Other cores with vulkan renderer work (Beetle PSX HW)
Stand alone duckstation works with vulkan.
Gentoo, build from source.

**Comment by stenzek** [comment]
Can't reproduce this on Ubuntu 20.10 with a RX580.

Could you try a debug build and see if that gives you a different call stack? Might be something being inlined. `-DCMAKE_BUILD_TYPE=Debug` on the command line.

Otherwise, it could be a retroarch bug. I notice on my system that the gpu pointer is not null.

**Comment by herbymachine** [comment]
Tried to recompile with DCMAKE_BUILD_TYPE=Debug but it gave me the same call stack. Will check my system and probably submit a bug report for reproach. Thanks for your quick reply.

**Comment by stenzek** [comment]
Definitely something strange going on - it shouldn't be crashing on an assignment statement like that. I'd debug the retroarch issue myself but it's kinda difficult if I can't reproduce it :/

**Comment by emersonnovais** [comment]
I had same issue with Ubuntu 18.04 using glcore or gl in Retroarch. I had to restore a previous file from builbot and replace from Retroarch's update.

**Comment by stenzek** [comment]
@emersonnovais are you using the latest commit? Can you get a backtrace, or at least the log file?

**Comment by emersonnovais** [comment]
With the last update, the core crashes only in command line. If I load the game from Retroarch menu, there is no crash. My log:


emula-os@emulaos-Vostro-3500:/Roms/Sony Playstation 1$ retroarch -v -f -L ~/.config/retroarch/cores/duckstation_libretro.so 'Crash Bandicoot (USA).chd'
[INFO] RetroArch 1.9.0 (Git 5e551dd92b)
[INFO] [Overrides]: Redirecting save file to "/home/emula-os/.config/retroarch/saves/Crash Bandicoot (USA).srm".
[INFO] [Overrides]: Redirecting save state to "/home/emula-os/.config/retroarch/states/Crash Bandicoot (USA).state".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i5 CPU       M 460  @ 2.53GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2
[INFO] Built: Nov  2 2020
[INFO] Version: 1.9.0
[INFO] Git: 5e551dd92b
[INFO] =================================================
[INFO] [CORE]: Loading dynamic libretro core from: "/home/emula-os/.config/retroarch/cores/duckstation_libretro.so"
[INFO] [Overrides]: No core-specific overrides found at /home/emula-os/.config/retroarch/config/DuckStation/DuckStation.cfg.
[INFO] [Overrides]: No content-dir-specific overrides found at /home/emula-os/.config/retroarch/config/DuckStation/.cfg.
[INFO] [Overrides]: No game-specific overrides found at /home/emula-os/.config/retroarch/config/DuckStation/Crash Bandicoot (USA).cfg.
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: SET_CORE_OPTIONS.
[INFO] [Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Remaps]: remap directory: /home/emula-os/.config/retroarch/config/remaps
[INFO] [Overrides]: Redirecting save file to "/home/emula-os/.config/retroarch/saves/Crash Bandicoot (USA).srm".
[INFO] [Overrides]: Redirecting save state to "/home/emula-os/.config/retroarch/states/Crash Bandicoot (USA).state".
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [CONTENT LOAD]: Content loading skipped. Implementation will load it on its own.
[libretro INFO] [Main] retro_load_game(Crash Bandicoot (USA).chd)
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[libretro INFO] [HostInterface] Boot Filename: Crash Bandicoot (USA).chd
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[libretro INFO] [HostInterface] Creating 'Cubeb' audio stream, sample rate = 44100, channels = 2, buffer size = 2048
[libretro INFO] [System] Loading CD image 'Crash Bandicoot (USA).chd' from playlist index 0...
[libretro INFO] [System] Auto-detected console NTSC-U region for 'Crash Bandicoot (USA).chd' (region NTSC-U)
[INFO] [Environ]: SYSTEM_DIRECTORY: "/Roms/Bios".
[libretro INFO] [HostInterface] Searching for a NTSC-U/C (US, Canada) BIOS in '/Roms/Bios'...
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'flash.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'dsp4.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'panafz10e-anvil-norsa.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'panafz1j.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'MSX2FR.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'Games Express CD Card 1993 (J).pce': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'MSX2SE.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping '61C7EEC0.eeprom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'Kickstart v1.2 r33.180 (1986)(Commodore)(A500-A1000-A2000)[!].rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'palmos40-en-m505.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'c52.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'Mario Kart DS (U)(SCZ).dsv': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'us_bios.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'MSX2KREXT.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'CD-ROM System V2.01 (U).pce': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'EUR_BIOS.BIN': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'o2rom.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'gb_bios.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping '67F9AB3A.eeprom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'scph39001.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'dsp3.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'MSXFR.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'bios.min': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'erOS_TOS.IMG': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'WHDLoad.prefs': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'MSXSE.ROM': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'FMPAC.ROM': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'bios9.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'panafz10e-anvil-patched.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'NstDatabase.xml': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'Lynx Boot Image.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'Action Replay ROM.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'MSX2KR.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'dc_flash.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'neogeo.zip': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'sm1.sm1': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'sp-e.sp1': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'SS - Boot Disc.img': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'DC - Utopia CD Loader V1.1.nrg': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'RS232.ROM': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'bootloader-en-m515.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'CD-ROM System V2.10.pce': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'kick34005.A500': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'DISK.ROM.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'SS - Boot Disc.sub': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'ggenie.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'colecoa.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'MSX2FREXT.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'spch30004R.NVM': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'Palm OS 3.3-en-v.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'tos.img': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'MSX.ROM': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'uni-bios_1_2o.rom': incorrect size
[libretro INFO] [HostInterface] Using BIOS 'PSX - SCPH7001.BIN'
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Abortado (imagem do núcleo gravada)

**Comment by emersonnovais** [comment]
After I loaded the game via Retroarch menu, now works normally from EmulationStation command line. You may close this issue. Sorry for bother you. Thanks.

**Comment by stenzek** [comment]
Can you run it with gdb (`gdb --args /path/to/retroarch -v ....`), then run, then `bt full` and paste the output?

**Comment by eadmaster** [comment]
same issue here when started from the Linux cmdline.

**Comment by emersonnovais** [comment]
emula-os@emulaos-Vostro-3500:/Roms/Sony Playstation 1$ gdb --args /usr/bin/retroarch -v -L ~/.config/retroarch/cores/duckstation_libretro.so 'Crash Bandicoot (USA).chd'
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Lendo símbolos de /usr/bin/retroarch...Lendo símbolos de /usr/lib/debug/.build-id/e7/76bb4cc09c4d0c30ad9293d4171569ff6e1ef2.debug...concluído.
concluído.
(gdb) 
(gdb) run
Starting program: /usr/bin/retroarch -v -L /home/emula-os/.config/retroarch/cores/duckstation_libretro.so Crash\ Bandicoot\ \(USA\).chd
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[INFO] RetroArch 1.9.0 (Git 5e551dd92b)
[INFO] [Overrides]: Redirecting save file to "/home/emula-os/.config/retroarch/saves/Crash Bandicoot (USA).srm".
[INFO] [Overrides]: Redirecting save state to "/home/emula-os/.config/retroarch/states/Crash Bandicoot (USA).state".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i5 CPU       M 460  @ 2.53GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2
[INFO] Built: Nov  2 2020
[INFO] Version: 1.9.0
[INFO] Git: 5e551dd92b
[INFO] =================================================
[New Thread 0x7fffd5664700 (LWP 12174)]
[INFO] [CORE]: Loading dynamic libretro core from: "/home/emula-os/.config/retroarch/cores/duckstation_libretro.so"
[INFO] [Overrides]: No core-specific overrides found at /home/emula-os/.config/retroarch/config/DuckStation/DuckStation.cfg.
[INFO] [Overrides]: No content-dir-specific overrides found at /home/emula-os/.config/retroarch/config/DuckStation/.cfg.
[INFO] [Overrides]: No game-specific overrides found at /home/emula-os/.config/retroarch/config/DuckStation/Crash Bandicoot (USA).cfg.
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: SET_CORE_OPTIONS.
[INFO] [Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Remaps]: remap directory: /home/emula-os/.config/retroarch/config/remaps
[INFO] [Overrides]: Redirecting save file to "/home/emula-os/.config/retroarch/saves/Crash Bandicoot (USA).srm".
[INFO] [Overrides]: Redirecting save state to "/home/emula-os/.config/retroarch/states/Crash Bandicoot (USA).state".
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [CONTENT LOAD]: Content loading skipped. Implementation will load it on its own.
[libretro INFO] [Main] retro_load_game(Crash Bandicoot (USA).chd)
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[libretro INFO] [HostInterface] Boot Filename: Crash Bandicoot (USA).chd
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[libretro INFO] [HostInterface] Creating 'Cubeb' audio stream, sample rate = 44100, channels = 2, buffer size = 2048
[libretro INFO] [System] Loading CD image 'Crash Bandicoot (USA).chd' from playlist index 0...
[libretro INFO] [System] Auto-detected console NTSC-U region for 'Crash Bandicoot (USA).chd' (region NTSC-U)
[INFO] [Environ]: SYSTEM_DIRECTORY: "/Roms/Bios".
[libretro INFO] [HostInterface] Searching for a NTSC-U/C (US, Canada) BIOS in '/Roms/Bios'...
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'flash.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'dsp4.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'panafz10e-anvil-norsa.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'panafz1j.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'MSX2FR.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'Games Express CD Card 1993 (J).pce': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'MSX2SE.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping '61C7EEC0.eeprom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'Kickstart v1.2 r33.180 (1986)(Commodore)(A500-A1000-A2000)[!].rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'palmos40-en-m505.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'c52.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'Mario Kart DS (U)(SCZ).dsv': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'us_bios.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'MSX2KREXT.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'CD-ROM System V2.01 (U).pce': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'EUR_BIOS.BIN': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'o2rom.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'gb_bios.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping '67F9AB3A.eeprom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'scph39001.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'dsp3.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'MSXFR.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'bios.min': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'erOS_TOS.IMG': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'WHDLoad.prefs': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'MSXSE.ROM': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'FMPAC.ROM': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'bios9.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'panafz10e-anvil-patched.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'NstDatabase.xml': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'Lynx Boot Image.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'Action Replay ROM.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'MSX2KR.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'dc_flash.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'neogeo.zip': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'sm1.sm1': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'sp-e.sp1': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'SS - Boot Disc.img': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'DC - Utopia CD Loader V1.1.nrg': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'RS232.ROM': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'bootloader-en-m515.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'CD-ROM System V2.10.pce': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'kick34005.A500': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'DISK.ROM.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'SS - Boot Disc.sub': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'ggenie.bin': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'colecoa.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'MSX2FREXT.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'spch30004R.NVM': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'Palm OS 3.3-en-v.rom': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'tos.img': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'MSX.ROM': incorrect size
[libretro WARN] [FindBIOSImageInDirectory] Skipping 'uni-bios_1_2o.rom': incorrect size
[libretro INFO] [HostInterface] Using BIOS 'PSX - SCPH7001.BIN'
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Thread 1 "retroarch" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: Arquivo ou diretório inexistente.
(gdb) quit
A debugging session is active.

	Inferior 1 [process 12169] will be killed.

Quit anyway? (y or n) y
