### ISSUE TITLE
Hide Vulkan render if the GPU can't support it

### ISSUE THREAD

**Issue by DarkSwan86** [stenzek/duckstation#1102]
Hi @stenzek !

Little suggestion for Duckstation: on my pc i have an Intel HD3000 GPU that is only capable of OpenGL 3.3 but DS let me select the Vulkan render. 

If i select it and run a game it give me an error about the Host creation and exit from DS with a crash. 

Tested on the latest build from source (ade61d6) on Manjaro Linux.

I suggest that DS should query the GPU capability for both OpenGL and Vulkan and hide it if is not capable.

Thanks!

**Comment by Richard-L** [comment]
I remember we talked about this once. I think it's a good idea. Would suggest to grey out rather than hide, to still tell DS offers advanced rendering, the present hardware just doesn't support it.

**Comment by stenzek** [comment]
There's no way to know if the hardware supports vulkan or not unless it tries to create it. Last time I tried to reproduce the crash I couldn't but I'll try again later

**Comment by stenzek** [comment]
Crash is fixed with https://github.com/stenzek/duckstation/commit/bccecdbf1864761364c4ae588f01c67bcbf2aa32.

As I said, hiding the option isn't really straightforward, but at least it won't crash anymore. Perhaps a better error message is in order.
