### ISSUE TITLE
the latest version is broken with vulkan in retroarch.

### ISSUE THREAD

**Issue by darkxex** [stenzek/duckstation#1103]
![image](https://user-images.githubusercontent.com/17991404/100156852-69c6d380-2e88-11eb-8e75-965f021594f5.png)
if I have retroarch with vulkan, I can no longer change the internal resolution, or close the core from retroarch.

you can check it by trying to change the internal resolution with vulkan.

**Comment by Red-gehog** [comment]
I came running to see things about it, so I found your report. I'm having the same problem.

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/627a3109b32dde253ea103c1484d673b5b1f4391

**Comment by darkxex** [comment]
Fixed, thanks.
