### ISSUE TITLE
[SLPS-00728] Raiden DX (Japan) - Crash Reports

### ISSUE THREAD

**Issue by hk98sc87** [stenzek/duckstation#1106]
**Game details**
SLPS-00728, Raiden DX (Japan)

**Description of the issue / bug**
The game crashes when the opening ends while using software renderer, hardware renderer works correctly.
Push button to skip the opening before title screen, or wait it ends, and then the game would crash.

**Enhancements information**
All enhancements are turned off.

**Hardware/software**
Renderer: Software
OS: Windows 10 x64
CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
GPU: Intel(R) HD Graphics 530/NVIDIA GeForce GTX 960M
RAM: 16 GB

**Emulator version**
0.1-2363-gfcbd6187 (master)

**Comment by stenzek** [comment]
Seems fine here. Is there some other setting which you are changing?

**Comment by hk98sc87** [comment]
> Seems fine here. Is there some other setting which you are changing?

I found if the crop setting is set to "Only Overscan Area", the game would not crush, but when it is set to "None", the software renderer would crush during the title screen
