### ISSUE TITLE
Medievil (Italy) probably anti-piracy measure

### ISSUE THREAD

**Issue by Hereward-GH** [stenzek/duckstation#1114]
Every time i've tried to play "The Hilltop Mausoleum" the game stops with this image.
![SCES-01494_2020-11-28_11-51-49](https://user-images.githubusercontent.com/16437893/100513882-9e7ca880-3170-11eb-9dd8-e504eb0cc32f.png)

**Comment by stenzek** [comment]
Have you added the sbi file alongside the image?

**Comment by Hereward-GH** [comment]
Ehm... no.

**Comment by stenzek** [comment]
For libcrypt games you need the sbi file with the same name as your disc image. You can get the sbi files from redump.org or other sources.

**Comment by Zet-sensei** [comment]
Confirmed.
Anti-piracy protection with that icon on the game.

**Comment by stenzek** [comment]
Thanks @Zet-sensei , I'll close this since I'm assuming it works fine with the sbi.
