### ISSUE TITLE
Screenshot feature outputs 0 byte files

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#1115]
As of the last two or so versions, the screenshot feature sadly outputs 0 byte files every now and then.

![image](https://user-images.githubusercontent.com/4934209/100518841-7606a580-3194-11eb-9681-0ea174d5eb27.png)

![image](https://user-images.githubusercontent.com/4934209/100518882-bebe5e80-3194-11eb-9f55-4ced13984ada.png)

I use F10 for screenshots (default?). It's quite noticeable when it fails as there is no short hanging of the game, as would usually occur while a screenshot is being dumped.

Should game matter: SLUS-00691 Tomb Raider III - Adventures of Lara Croft (USA) (v1.2)

If this should in fact be Win7 related, feel free to close.

**Comment by stenzek** [comment]
Screenshots are compressed asynchronously now, so it only stalls emulation briefly while it downloads from the GPU, which may not be noticable.

Will need to see the log to know what's going on.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/39010320ea261259fb1da07c890f3ef5025b6633

**Comment by Richard-L** [comment]
Yup, perfect :+1:
