### ISSUE TITLE
[SCUS-94402] Raiden Project, The (USA) - Graphics Error

### ISSUE THREAD

**Issue by hk98sc87** [stenzek/duckstation#1116]
**Game details**
SCUS-94402, Raiden Project, The (USA)

**Description of the issue / bug**
When CPU mode is set to interpreter, there would be graphics error during the title screen.
![SCUS-94402_2020-11-28_12-20-18](https://user-images.githubusercontent.com/70301067/100538071-72dce980-3268-11eb-8a75-6693fe9f45f9.png)

**Enhancements information**
All enhancements are turned off

**Hardware/software**
CPU Emulation: Interpreter
OS: Windows 10 x64
CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
GPU: Intel(R) HD Graphics 530/NVIDIA GeForce GTX 960M

**Emulator version**
0.1-2401-gd1a42df1 (master)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/37c9e69b3e29278d722fcb92107048a6d957f515
