### ISSUE TITLE
[Request] Add Support for 3:2 Aspect Ratio (for MS Surface products)

### ISSUE THREAD

**Issue by clcarrow** [stenzek/duckstation#1118]
**Is your feature request related to a problem? Please describe.**
It is not currently possible to select 3:2 as the aspect ratio under Settings>Display Settings>Screen Display. This aspect ratio is very common in Microsoft's line of Surface products, including tablets, laptops, and AIOs. The addition of this aspect ratio would allow the widescreen hack to work appropriately on these screens.

**Describe the solution you'd like**
I would like to request the addition of support for the 3:2 aspect ratio in order to enhance the experience of using the widescreen hack with Surface and other 3:2 devices.

**Describe alternatives you've considered**
Perhaps an option for the aspect ratio to be autodetected (in addition to the selectable aspect ratios) could be implemented so long as interfacing between aspect ratios and the widescreen hack could work in such a dynamic way. I would guess (though I don't know) that just adding another screen ratio to the current list would be quicker and easier than this alternative, though.

**Additional context**
No additional context, but if I have failed to convey the issue or any vital information, please let me know.

Thank you very much for this excellent emulator. It works marvelously on my Surface 3, Intel Atom x7-z8700, 2GB RAM where many other ps1 emulators have failed, either due lack of processing power or old graphics APIs running poorly on my EOL Intel graphics chipset.

**Comment by stenzek** [comment]
Sure, I can add 5:4 at the same time.

I did consider automatically determining the ratio, but the main problem here is for the widescreen hack - it renders at the display resolution, and the codegen for a dynamic AR here would be less optimal.

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/98f70e9b510e17f9101696ca390e74845e7431bf
