### ISSUE TITLE
Parasite Eve 2 per game settings issue.

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#1122]
**Game details**
SLUS-01042 Parasite Eve 2

**Description of the issue / bug**
Game hangs on first logo if CD speedup is set to anything but the default, the issue is if I have in the main config CD speed up set to 4x for example and in game proprieties I set the CD speed up to default the game still hangs on the first logo screen. 

![Przechwytywanie](https://user-images.githubusercontent.com/64225743/100659489-fb36b980-3350-11eb-91a8-aa620637c435.PNG)

**Hardware/software**
PC.

**Emulator version**
Newest

**Comment by darkxex** [comment]
It also happens in the European version, but why don't you leave it in default, and select the option "preload image to ram" so you won't have waiting times.

**Comment by foxsevent** [comment]
> It also happens in the European version, but why don't you leave it in default, and select the option "preload image to ram" so you won't have waiting times.

Few reasons.
1. The game freezing ain't the issue here, it's that the per game setting doesn't override the main setting. 
2. "preload image to ram" doesn't help waiting times as Duckstation has to emulate the CD drive and it's limitations like the 150-300kbs read speed, that's what the CD speed up feature is for speeding up the data load.
 "preload image to ram" is mostly meant for when you're loading a game from a network server over LAN or if you want your HDD to not fully spin when plying games, the spin up and spin down of a HDD can cause hiccups.
3. Lastly the issue you have in mind only exists on PAL games EU/UK as they have a extra layer of anti piracy protection called libcrypt.

**Comment by darkxex** [comment]
oh sorry friend, what happens is that I only use retroarch, as a recommendation, the duckstation discord is quite active and the developer responds almost immediately when I have a problem.

**Comment by ggrtk** [comment]
Do you have "Apply Per-Game Settings" enabled in General Settings? Otherwise, see if CDROMReadSpeedup isn't being saved to gamesettings.ini in your user directory. I'm unable to reproduce this issue on both an updated version and a fresh install.

**Comment by stenzek** [comment]
Setting is applying here via game properties. Make sure you have apply per-game settings enabled as @ggrtk said.

**Comment by foxsevent** [comment]
> Do you have "Apply Per-Game Settings" enabled in General Settings? Otherwise, see if CDROMReadSpeedup isn't being saved to gamesettings.ini in your user directory. I'm unable to reproduce this issue on both an updated version and a fresh install.




> Setting is applying here via game properties. Make sure you have apply per-game settings enabled as @ggrtk said.

Checked and it's ticked same problem.
![Przechwytywanie](https://user-images.githubusercontent.com/64225743/100710071-70d17280-33af-11eb-8d3b-cc4d8682cef6.PNG)
Here's the game settings file for good measure.

# DuckStation Game Settings


# SLUS-00067 (Castlevania - Symphony of the Night)
[SLUS-00067]
DisablePGXP = true
DisablePGXPCulling = true
DisablePGXPTextureCorrection = true
GPUPGXP = false

#  (Parasite Eve II)
CDROMReadSpeedup = 1

**Comment by stenzek** [comment]
> Found what the issue is, it's because I use M3U playlists, per game settings applied to the list aren't applied to the discs inside of it, I have to edit each separate disc setting for the playlist to work.

Yep, that would explain it. I probably should disable the properties dialog for playlists.

**Comment by foxsevent** [comment]
> > Found what the issue is, it's because I use M3U playlists, per game settings applied to the list aren't applied to the discs inside of it, I have to edit each separate disc setting for the playlist to work.
> 
> Yep, that would explain it. I probably should disable the properties dialog for playlists.

While you're at it could you add "Edit memory cards" to the playlists menu, as they have their own memory cards.
