### ISSUE TITLE
In fullscreen a mouse cursor is invisible, how to make it visible in fullscreen?

### ISSUE THREAD

**Issue by metalslayer** [stenzek/duckstation#1127]
Please read before creating a new issue:

1. All advanced options MUST be at their default values;
2. All enhancements must be off;
3. Do not share save state files. Memory Cards are ok;
4. Please post your issue report in English as unfortunately this is the only language spoken by the developers. The Discord server has many helpful people if you need help translating.

Remove everything before and including this line before submitting.

**Game details**
[Serial Code, Region]
[i.e SLUS-00404 Ace Combat 2 (USA)]

**Description of the issue / bug**
[Describe what you are seeing and/or hearing during gameplay]

**Steps to Reproduce**
[Try to provide as much detail as possible to reproduce the issue]

**Enhancements information**
[Make sure they are all turned off before report]

**Hardware/software**
[If Android, which phone and Android version]
[If desktop, your CPU, graphics card, and operating system]
[GPU Renderer - D3D11/OpenGL/Vulkan]

**Emulator version**
[Shown in the title bar of the emulator]

**Additional context**

**Comment by stenzek** [comment]
Working as intended. In fullscreen the cursor is hidden... I suppose I could add an option to keep it visible, but I'm not really sure why it would be useful (except maybe for navigating the debug widgets).

**Comment by metalslayer** [comment]
When I play online via Parsec Gaming, it's hard to use Parsec Menu without a screen mouse.

**Comment by stenzek** [comment]
Option added in https://github.com/stenzek/duckstation/commit/0fbb69a3efa4510795e906486110413b9d37fcf6. General Settings -> "Hide Cursor In Fullscreen"

**Comment by metalslayer** [comment]
Thank you, I really appreciate that
