### ISSUE TITLE
Swapping discs after failing region check doesn't work

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#113]
I set the region to NTSC-U

![Capture](https://user-images.githubusercontent.com/31968468/76820158-6a6d8b80-685e-11ea-9d82-47aad9b5eec4.PNG)

Pick a game I know is the wrong region to get this screen

![Capture2](https://user-images.githubusercontent.com/31968468/76820163-6fcad600-685e-11ea-8544-1885f107c51a.PNG)

Try and pick a game with the right region

![Capture3](https://user-images.githubusercontent.com/31968468/76820194-92f58580-685e-11ea-9e0d-a7b0a1ab5e2c.PNG)

Nothing happens. It just stays on this screen forever even though the emulator acknowledges a new disc has been inserted 

![Capture4](https://user-images.githubusercontent.com/31968468/76820222-a6085580-685e-11ea-9660-c61ada94b103.PNG)

**Comment by stenzek** [comment]
I think this is working as intended. I just checked on my console and inserting a disc has no effect at that screen, it has to be manually reset.
