### ISSUE TITLE
CD changes does not work on the cd player screen. (in bios menu) 

### ISSUE THREAD

**Issue by gobrasoft** [stenzek/duckstation#1130]
The cd changing feature on the cd player screen should be added to the program. It would be really nice to be able to listen to some game music. But the cd changing function does not work on the bios screen.

Samsung note 8
Android 9.0

**Comment by stenzek** [comment]
Android disc changing is limited because of how the UI works. You can only change discs within a playlist.

**Comment by gobrasoft** [comment]
Biz bu işi bilmiyoruz desene sen şuna.
