### ISSUE TITLE
Add support for Justifier/Hyperblaster lightgun as well as Guncon.

### ISSUE THREAD

**Issue by titchgamer** [stenzek/duckstation#1131]
Please could you add support for the standard Justifier lightgun so we can play games like Star Wars rebel assault and Die hard etc.
Thanks :)

**Comment by Zet-sensei** [comment]
NAMCO GunCon is already implemented in the emulator.

KONAMI Justifier support is work-in-progress.

**Comment by titchgamer** [comment]
> KONAMI Justifier support is work-in-progress.

Fantastic thank you :)

**Comment by thatman84** [comment]
@stenzek with the implementation of justifier being tricky would you be open to a little bounty push? With the Sinden lightgun getting into more hands I’m sure I could drum up some support for you. Duck station is the go to emu in the Sinden community.

**Comment by stenzek** [comment]
I have it implemented on a branch, the problem is it's imprecise depending on the game. I implemented it based on the nocash doc, but mednafen is also off as well... Something is missing

**Comment by thatman84** [comment]
Ah ok then, hopefully something comes to light over time. I hear accuracy was an issue on real hardware.

Is there are possibility of getting a build of the branch for testing?

**Comment by ggrtk** [comment]
It's on the justifier branch, but it's months out of date so you'll have to rebase it yourself. I'm working on some stuff at the moment that will affect the justifier emulation and I'll likely have to run a few hardware tests for it at some point, so I don't think giving out a build for this is really going to be useful for anyone.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/d09497821468b6c86e7b8e68dfe9bd9c43373935.
