### ISSUE TITLE
Crop window which preserves aspect ratio

### ISSUE THREAD

**Issue by Awakened0** [stenzek/duckstation#1138]
**Description of the issue / bug**
Changing the new "Display Line Offset" options stretches the aspect ratio instead of retaining it.

**Steps to Reproduce**
Set the Start offset to 12 and the End one to -12 in Crash 1. The image will be stetched vertically compared to 0 offsets:

![Crash Bandicoot (USA)-201203-172057](https://user-images.githubusercontent.com/4565863/101096549-b51a6980-358d-11eb-93e4-4fab1691bcae.png)

![Crash Bandicoot (USA)-201203-172300](https://user-images.githubusercontent.com/4565863/101096567-b8adf080-358d-11eb-85eb-054396c50b61.png)

**Hardware/software**
Tested the libretro core in both Software and Vulkan renderer modes.

**Emulator version**
0.1-2433-g9089c973

**Comment by stenzek** [comment]
This is working as intended. What you're asking for is a crop offset which will preserve the aspect ratio.

**Comment by ggrtk** [comment]
This is something I had in mind with an "auto" aspect ratio in #654.

**Comment by Awakened0** [comment]
Both 1:1 PAR and the new Auto ratio now adjust properly with the offsets. Thanks!
