### ISSUE TITLE
4:3 Aspect Ratio Identical to 1:1 PAR

### ISSUE THREAD

**Issue by Awakened0** [stenzek/duckstation#1139]
**Description of the issue / bug**
The 4:3 aspect ratio option should be a little wider than 1:1 PAR, but currently they are the same (at least in the libretro core). I can achieve a proper 4:3 aspect by using the "All Borders" Crop Mode, which crops the vertical bars and stretches the image to 4:3. But ideally cropping options shouldn't change the aspect ratio.

**Steps to Reproduce**
Change the Aspect Ratio option to 4:3. It will have square pixels, just like the 1:1 PAR mode.

**Hardware/software**
Tested the libretro core in both Software and Vulkan renderer modes.

**Emulator version**
0.1-2433-g9089c973

**Comment by stenzek** [comment]
Probably libretro-specific issue since it's relying on the frontend to do AR correction. Might be easier to just remove the option.

**Comment by ggrtk** [comment]
Last I remember, there's a 1:1 PAR option in libretro frontends that relies on cores updating the base dimensions geometry info. We could remove the 1:1 PAR setting from the core options and do it this way. Or keep the core option, and update the aspect ratio geometry info instead.

**Comment by Awakened0** [comment]
As long as there's an easy way to set it per game with core options or overrides. 4:3 (TV Aspect) and 1:1 PAR (Square Pixels) are the most important aspect ratios to me, since I like to try to get perfect circles and squares in each game. PS1 is one of the systems where there's some split on devs that seemed to compensate for TV stretching vs just drawing things with square pixels.

Using the "All Borders" crop mode to switch between aspects works, but it can be a headache if certain games end up being cut off a little on one side or the other. Then you have to have more options to set the amount of vertical cropping. Since the vertical bars aren't visible unless I use widescreen hacks or take screenshots, I'd rather leave them alone.

**Comment by stenzek** [comment]
Messing with the geometry is risky, retroarch tends to reinitialise things when it's not necessary, and that's a disaster with hardware contexts since caching is completely broken.

**Comment by Awakened0** [comment]
Maybe better to wait for that stuff to improve on the frontend side then I guess. I stick to the software renderer in Beetle PSX, so I'm not sure how well the hardware renderers handle aspect options in that core.

**Comment by dankcushions** [comment]
in _theory_ `RETRO_ENVIRONMENT_SET_GEOMETRY` should not reinit. see https://github.com/libretro/RetroArch/blob/master/libretro-common/include/libretro.h#L925

i've seen it used with success on other hardware cores where the resolution changes at runtime. eg @m4xw's mp64-nx https://github.com/libretro/mupen64plus-libretro-nx/commit/4ec3be05d9d7a4565f81fd769abe9ccc08dba019 - though i'm not sure if it's really comparable

**Comment by m4xw** [comment]
> 
> 
> in _theory_ `RETRO_ENVIRONMENT_SET_GEOMETRY` should not reinit. see https://github.com/libretro/RetroArch/blob/master/libretro-common/include/libretro.h#L925
> 
> i've seen it used with success on other hardware cores where the resolution changes at runtime. eg @m4xw's mp64-nx [libretro/mupen64plus-libretro-nx@4ec3be0](https://github.com/libretro/mupen64plus-libretro-nx/commit/4ec3be05d9d7a4565f81fd769abe9ccc08dba019) - though i'm not sure if it's really comparable

Commit alone is a bit missleading, I basically allocated my max res at the start and it's guaranteed that each set has a lower or equal size resolution.

**Comment by Awakened0** [comment]
Tested it out, works great! Thanks @ggrtk and @stenzek !
