### ISSUE TITLE
BIOS sounds continue for WAY too long in Disney's Tarzan

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#114]
All the way up to this screen 

![SCUS-94456_2020-03-17_15-13-04](https://user-images.githubusercontent.com/31968468/76821498-3300de00-6862-11ea-9b31-8f331fea6bfb.png)

The log if it helps. 

![Capture](https://user-images.githubusercontent.com/31968468/76821545-57f55100-6862-11ea-86fa-8a62ffe9e3e3.PNG)

**Comment by stenzek** [comment]
Yeah, the logarithmic decrease for the release phase takes too long. Looked into it briefly the other night but nothing obvious was incorrect. Will need more research.

**Comment by benderscruffy** [comment]
happens in Nightmare Creatures (USA) aswell

**Comment by HeroponRikiBestest** [comment]
This also happens in Buggy (Europe) during the anti-piracy screen, the developer logo, and throughout the opening fmv.

**Comment by Zet-sensei** [comment]
Also occurs on WipEout (Europe) (v1.0) & WipEout (Europe) (v1.1) during the anti-piracy screen.

**Comment by HeroponRikiBestest** [comment]
Also occurs on CyberTiger (USA)

**Comment by kurayami6** [comment]
Happens in Tonka Space Station and about 50 other games as well. I really think fixing this should be prioritized. 

![SLUS-01007_2020-04-10_16-21-58](https://user-images.githubusercontent.com/31968468/78968377-bc48bf00-7b47-11ea-9205-f30cc103eaa7.png)

**Comment by stenzek** [comment]
Could you please check whether this happens on console, and if not console, other emulators? Medanfen seems to have the same issue, and I can also notice it to some extent on my console.

**Comment by kurayami6** [comment]
It's listed as a known issue in Mednafen as well.

![Capture](https://user-images.githubusercontent.com/31968468/78986791-769fec80-7b6f-11ea-816f-bafc605687e7.PNG)

**Comment by stenzek** [comment]
Alright, I have a feeling this is actually a CD-ROM issue.

Because the PlayStation screen/the game executable loading is too quick, the BIOS sounds (and thus the reverb from them) don't have enough time to fade out. Hacking a one second delay into all seeks fixes the issue (and the reverb is all zero).

Sounds like we (and Mednafen) need better modelling of CD-ROM seek times.

**Comment by stenzek** [comment]
Some more research: Recording from my console vs DuckStation. Ignore the scale, they're not normalized. Both booting the same game (FF7), which resets the reverb as soon as starting, so it doesn't have this bug.

Notice how it takes longer to "cut out" to zero. That is the executable loading part of the BIOS. It completes much quicker in DuckStation and the game starts sooner. Therefore yes, if we improve the CD-ROM timings, it'll take longer to boot, and the reverb will drop to near-zero/zero like the console.

![Screenshot from 2020-04-10 12-33-17](https://user-images.githubusercontent.com/11288319/78991140-93dab800-7b7b-11ea-96e1-e75bbd668b9d.png)

**Comment by stenzek** [comment]
I've adjusted some CD-ROM timings so games should take longer to boot, which makes this much less noticeable. It's still there, but honestly I suspect it's there on the console too, just more difficult to hear it. I'd love for someone to dump the audio of this game off their console for comparison ;)

**Comment by kurayami6** [comment]
The BIOS sound in Tarzan is now completely distorted and still keeps playing well into the game.

**Comment by stenzek** [comment]
I never said it would be gone completely - just much less noticeable. You have to have the volume up quite high to be able to hear it.

I'm not going to spend any more time on this until someone gets a recording from a console to compare against - it's just too unclear what it's supposed to sound like. Especially since none of the other emulators have it handled either.

**Comment by kurayami6** [comment]
Alright just take a break from this issue and fix something easier. No point getting angry.

**Comment by stenzek** [comment]
I'm not angry :) It's just very difficult to know what is "correct" when I don't have a reference to go off.

In this case, I roughly matched the time of the waveform from the emulator with that from my console for FF7. If you can get an audio recording from a console for this game, I can do the same.

**Comment by stenzek** [comment]
See #398.
