### ISSUE TITLE
Pause emulation when window loses focus

### ISSUE THREAD

**Issue by PodunkPedant** [stenzek/duckstation#1142]
Many emulators have an option for emulation to pause when its window loses focus, meaning it is no longer considered the active window after clicking somewhere else or hitting Alt+Tab, etc. It's a small feature but I found myself searching for it after I hit my "Pause" hotkey while running LaunchBox and realized my game was still playing in the background. I think this option would help in situations like this to add a little extra polish and convenience.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/af6b0dc189dc970210f8c97d9ef612bc2d6597fb as `Pause On Focus Loss` in `General Options`, disabled by default.
