### ISSUE TITLE
[Libretro] RGA scaling broken on OGA platform

### ISSUE THREAD

**Issue by ufoman** [stenzek/duckstation#1143]
**Game details**
SLUS-00213 Tekken 2 (USA)
(issue seems to be game agnostic)

**Description of the issue / bug**
An image enhancement feature, RGA scaling, available on Odroid Go Advance platform and clones, appears to be disabled when duckstation is used. Issue appears with both software and hardware (OpenGL) renderers.

**Steps to Reproduce**
1. Enable 4:3 aspect ratio and RGA scaling in RetroArch video settings
2. Boot the game
3. Observe the image scaling artifacts
4. Boot the same game with PCSX-ReArmed with RGA scaling enabled and observe a much cleaner image
5. Disable RGA scaling to observe the same result as in step 3

**Enhancements information**
This is with Libretro version, so some enhancements may be still enabled.

**Hardware/software**
Odroid Go Advance clone (Anbernic RG351P)
Issue manifests with software and OpenGL renderers (Vulkan is unsupported on the platform)

**Emulator version**
DuckStation (0.1-2421-gcd8f17db)

**Additional context**
Issue cannot be expressed in screenshots (they do not capture the final image filtered with RGA scaling).

**Comment by stenzek** [comment]
This sounds like a retroarch issue. I have a standalone version which uses libgo2 and it works fine.

**Comment by stenzek** [comment]
Closing as this I'm almost certain this is a frontend bug, and the developer of the goadvance driver has not reported any issues. I'd suggest using retrorun on the goadvance anyway, it's much faster.
