### ISSUE TITLE
Ringing sound during the opening cutscene in Shura no Mon (Japan) (SLPS-01202)

### ISSUE THREAD

**Issue by Tiberius1437** [stenzek/duckstation#1144]
Start the game up and you can hear it as soon as the BIOS screen ends. Couldn't figure out how to record audio sorry.

![SLPS-01202_2020-12-04_22-08-44](https://user-images.githubusercontent.com/68873449/101157303-03a73100-367e-11eb-83fb-fd24e07866ba.png)

**Comment by stenzek** [comment]
Does it happen with fast boot?

**Comment by Tiberius1437** [comment]
No, good call. I'll try a different BIOS. The one I'm using might be a bad dump.

**Comment by stenzek** [comment]
I doubt it's a dump issue. Was thinking it's the same issue as https://github.com/stenzek/duckstation/issues/407 which is caused by the cd reading too quickly.

**Comment by stenzek** [comment]
Yep, same cause as #407, so we'll track it there.
