### ISSUE TITLE
Fear Effect text broken in D3D11 render.

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#1151]
Fear Effect.
SLUS-00920

Duckstation 0.1-2457-gfd646226.
![SLUS-00920_2020-12-05_19-42-59](https://user-images.githubusercontent.com/64225743/101260992-0f552f00-3734-11eb-904a-a86c66a75056.png)
Like in the screenshoot, minor bug in D3D11 no enhancements, not broken on every other render.
Here's a memory card if one is needed.
[Fear Effect_1.zip](https://github.com/stenzek/duckstation/files/5647715/Fear.Effect_1.zip)

**Comment by stenzek** [comment]
Seems fine here in D3D11 (aside from the misaligned border). Are you sure you have all enhancements off?
![SLUS-00920_2020-12-06_17-25-55](https://user-images.githubusercontent.com/11288319/101274246-29e8e000-37e8-11eb-9e34-6f38aceca11d.png)

**Comment by foxsevent** [comment]
> Seems fine here in D3D11 (aside from the misaligned border). Are you sure you have all enhancements off?
> ![SLUS-00920_2020-12-06_17-25-55](https://user-images.githubusercontent.com/11288319/101274246-29e8e000-37e8-11eb-9e34-6f38aceca11d.png)

I thought I did, but apparently this is caused by having the CD speed set to above 4x, my bad apologies.
