### ISSUE TITLE
Parasite Eve 2 FMV camera, 3D model bug.

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#1152]
Parasite Eve 2
SLUS-01042
Duckstation 0.1-2457-gfd646226.

It's a very minor bug that I thought was caused by PGXP but it isn't so I post it here.
It's near the beginning of the game, when the camera moves the 3D model doesn't move smoothly, it shakes. 
Here's how it looks in Duckstation.
https://youtu.be/F4LysQ2nPXE
And here's how it should look,
https://youtu.be/80UrOpksWOI?t=688

**Comment by stenzek** [comment]
Seems to be MDEC timing related, using a higher delay fixes it.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/50bcdc0abb1b81f2642562177bab0c784d09973d
