### ISSUE TITLE
Fast forward not working 

### ISSUE THREAD

**Issue by Band-Aid** [stenzek/duckstation#1154]
**Game details**
All games

**Description of the issue / bug**
Fast forward is not working on any game.

**Steps to Reproduce**
Turn on Fast forward

**Hardware/software**
Surface Pro x, Windows 10 ARM, GPU SQ1 integrated gpu 
[If desktop, your CPU, graphics card, and operating system]
[GPU Renderer - D3D11]

**Emulator version**
0.1-2457 gfd646226

**Additional context**

**Comment by Nucleoprotein** [comment]
Have you disabled V-Sync?

**Comment by Band-Aid** [comment]
Yes, I've tried disabling V-sync but that doesn't speed up the game.
The emulation speed stays at 100%
Also tried speeding up the default emulation speed but that didn't do anything either. Stays at 100% 

![image](https://user-images.githubusercontent.com/21311546/101278020-cb2d6180-37fb-11eb-8df1-4b79c984e1fc.png)
![image](https://user-images.githubusercontent.com/21311546/101278043-0465d180-37fc-11eb-8e7b-d97b7d6213e6.png)

**Comment by Nucleoprotein** [comment]
If FPS are locked to refresh rate then seems V-Sync is somewhere forced, maybe in driver configuration?

**Comment by stenzek** [comment]
Try disabling render to main window.

**Comment by stenzek** [comment]
Also, try setting the max display fps to 60 on advanced options.

**Comment by Band-Aid** [comment]
- [x] disabling render to main window
 - [x] Set fps to 60
none of the above worked... but I noticed something weird, if I hide the game window (minimize, put in background) the game  suddenly speeds up. 
I noticed this because the music sped up and when I put the window in foreground I see the fps is 300% for a slight moment but as soon as the window is focused it slowdowns back to 100%
Something not working correctly when the game window is in foreground.

**Comment by stenzek** [comment]
Yeah, it's something to do with D3D and child windows - I had the same problem on my laptop at one point and had to use a blit swap chain to fix it (which is slower).

Strange that limiting the fps didn't work. That should basically frame skip (except the frames are still rendered, just not displayed). Maybe try 30 and see if fast forwarding gets you 2x speed?

**Comment by Band-Aid** [comment]
setting it to 30 didn't work either. Hmm, Strange. I'll play around with the settings a bit more.

**Comment by Band-Aid** [comment]
I was able to get it working by enabling full screen mode. Not ideal but at least there's a workaround :)

**Comment by stenzek** [comment]
Okay. I might re add the blit mode as an advanced option and we can try that

**Comment by stenzek** [comment]
Added a "Use Blit Swap Chain" option to advanced in https://github.com/stenzek/duckstation/commit/a511882cb8569823c4b63b9d07763d6c04ff1a9b, hopefully that'll unlock the present rate.

**Comment by Band-Aid** [comment]
Turning on Blit swap chain solved the issue! Thank you!

**Comment by stenzek** [comment]
Great! Thanks for the update.

**Comment by Band-Aid** [comment]
Hi @stenzek 
This issue happened again on the latest build. Did you remove the Blit swap option? I don't see it in advanced options anymore.

Build: 0.1-3862-g8f821c77 (dev)
