### ISSUE TITLE
Profiler for the second Xinput controller is broken.

### ISSUE THREAD

**Issue by metalslayer** [stenzek/duckstation#1155]
When I load xinput profiler for the first player it works just fine, but when I do the same way with the second, it just made blank.
https://www.youtube.com/watch?v=dnXrb3nkwCk&ab_channel=MetalslayerGameplays

**Comment by stenzek** [comment]
Working as intended. Input profiles contain bindings for all controllers, and the Configs which the emu ship with only have one controller bound, because that's what most people use.

If you want a second controller set up in the profile, bind it, and save a new profile.

**Comment by metalslayer** [comment]
Meh
