### ISSUE TITLE
.iso.gz compressed format support, same way as PCSX2 do it.

### ISSUE THREAD

**Issue by metalslayer** [stenzek/duckstation#1156]
The game weighs way lower and playing without a problem.

**Comment by stenzek** [comment]
This would require indexing as gzip is not seekable, and would not work well for multi track games. CHD will compress better and is compatible with more emus. If the lzma decompression overhead is too much, you can compress chds with deflate (same as gzip).

**Comment by metalslayer** [comment]
Thanks for the Tip it's a great format, just checked.
