### ISSUE TITLE
Feature Request: Mute sound when fast forward is on or FPS limit is off.

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#1159]
Title says it all.

**Comment by ImSpecial** [comment]
Going to hijack this and ask for in addition, if possible to have a "reduced" volume for when this is on/off. Kinda like this; https://i.imgur.com/BvQ3XYR.png

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/678146b9078bffce7b702df555e34ed61f754b7b
