### ISSUE TITLE
Medievil 2 sound error

### ISSUE THREAD

**Issue by shikulja** [stenzek/duckstation#116]
b86e0bc84668041fc29b856f2f644d199fea104a
when I open the door with the keys, a loud, unpleasant sound appears until I re-enter the game through the emulator menu again

[savestates.zip](https://github.com/stenzek/duckstation/files/4343264/savestates.zip)

video (need to make the sound louder)
https://youtu.be/5_5w--NRbso

**Comment by kurayami6** [comment]
Where in the game is this so I can check it?
