### ISSUE TITLE
Simple screen stretch for 4:3 on 16:9 monitors

### ISSUE THREAD

**Issue by metalslayer** [stenzek/duckstation#1165]
Some games have texture absence on 16:9 widescreen mode, it would be cool to have that feature.
I need this for my Crash Team Racing widescreen hack.

**Comment by stenzek** [comment]
If you mean stretching 4:3 to 16:9, this is possible already, set 16:9 aspect ratio and disable widescreen hack.

**Comment by metalslayer** [comment]
Here is an example of what I meant https://yadi.sk/d/Id3u0952DHGxOA

**Comment by stenzek** [comment]
You're not going to get rid of the missing geometry in the emulator - that's likely the game culling against the frustrum before it sends it to the GTE/GPU, and would require patching to fix.

**Comment by metalslayer** [comment]
All I need is stretch, nothing more.

**Comment by stenzek** [comment]
I still have no idea what you mean by "stretch". To me, stretching means rendering 4:3 and displaying 16:9.

If you want to crop the image, there is an open issue for that: https://github.com/stenzek/duckstation/issues/1138

**Comment by metalslayer** [comment]
Maybe this one will figure out about stretching
Mednaffe, Mendafen's UI
https://imgur.com/a/DBVTEHe

**Comment by Nucleoprotein** [comment]
@metalslayer 
As @stenzek said, that already is implemented. Select you aspect ratio and **uncheck** widescreen hack, and as Duck have no aspect ratio auto-detection you need to select your monitor ratio, then image will be stretched.

**Comment by metalslayer** [comment]
Oh, it works))
