### ISSUE TITLE
Support game controller half-axis to half-axis bindings

### ISSUE THREAD

**Issue by ggrtk** [stenzek/duckstation#1172]
https://cdn.discordapp.com/attachments/695640472202379428/784836890850492426/axis.png

Mentioned by a user on Discord. As shown in the picture provided by the user, when L is mapped to a game controller analog stick, it maps the whole game controller axis, meaning that when the analog stick is at neutral, L is in a constant half-pressed state.

**Comment by stenzek** [comment]
I believe I have this implemented as of https://github.com/stenzek/duckstation/commit/f861fa40e5c04827463a83eb881fa1e226f68fcd, https://github.com/stenzek/duckstation/commit/a84992c3954b8421c2cd440e882530defd0055d1, and https://github.com/stenzek/duckstation/commit/0ceb0f7a4a95dd498c48cfbc046d726a655b17aa.
