### ISSUE TITLE
Fastest renderer for Pi4?

### ISSUE THREAD

**Issue by vanfanel** [stenzek/duckstation#1175]
Hi @stenzek 

This is more a question. I have Vulkan, GLES and software renderers working with Duckstation on the Pi4 by now, using RetroArch, no X11 required (VK_KHR_Display extension works in latest GIT mesa), etc.

Also, you recently implemented a workaround for GLES on this platform, so it's looking good now, too!

What's supposed to be the fastest renderer? Vulkan and GLES look about the same, I'd say Vulkan is a bit slower right now (experimental MESA implementation I guess...).
On the other hand, the software renderer looks a bit faster as things are! This surprised me... but none of the three renderers are fullspeed on, let's say, Tekken 3 realtime demo.

Did you merge the go2fast2 renderer into main? Is there margin for speed up once you do?

Thanks!

**Comment by stenzek** [comment]
Vulkan seemed fastest for me. Software can outperform both, I'm not 100% sure why - possibly the GPU in the Pi being too weak, or it being memory bandwidth constrained (the shaders are FP32/INT32 and use RGBA8 render targets, not great for mobile GPUs). It also doesn't have the colour truncation bug which occurs in OpenGL.

All changes from go2fast2 are in master, except for the frontend itself.

**Comment by stenzek** [comment]
Regarding T3, that's kinda surprising, will have to check it myself. Given I can get 200fps or so in games like Spyro, would've thought that'd be enough headroom. It's possible that retroarch is adding too much overhead here, particularly for the GPU. I'm still chipping away at nogui, retroarch won't be needed for much longer :)

**Comment by vanfanel** [comment]
@stenzek From what I can see here on 64bit Raspberry Pi OS, Tekken 3 realtime-demo mode seems to be too much for the Pi 4 even with disabled interlacing.
Maybe using the "threaded video" option in RetroArch (not the one in DuckStation, which works great for software mode) would bring improvement.. at a HUGE impact of input lag.

Also, would RetroArch add GPU overhead even when using the software renderer?

And another question I would like to ask you: it's a general emulation question.
How will you sync audio without RetroArch? I mean: In RetroArch, cores run at the native physical screen refresh rate, which is great, and RetroArch resamples the audio to acomodate the exact video refresh rate: will you do it in-house with the NOGUI branch/version?

**Comment by stenzek** [comment]
> Also, would RetroArch add GPU overhead even when using the software renderer?

Somewhat. In my standalone version I elide one of the copies, which saves a little memory bandwidth.

> How will you sync audio without RetroArch? I mean: In RetroArch, cores run at the native physical screen refresh rate, which is great, and RetroArch resamples the audio to acomodate the exact video refresh rate: will you do it in-house with the NOGUI branch/version?

I do the opposite - sync to audio, and dupe video frames where needed. This way the emulator is running at the correct speed.

**Comment by vanfanel** [comment]
@stenzek But syncing on audio instead of video and duping frames when needed will cause occasional hiccups on the video, destroying movement smoothness... Can I suggest that you sync on video and resample the audio? It's the best solution, really. RetroArch does the right thing there.
Of course, syncing on audio and duping frames could still be an option. But games didn't have hiccups on the original hardware :(

**Comment by stenzek** [comment]
Resampling audio is slower, and also forces the emu to run slightly faster than it should..

IMO the video frame duping problem is solved - use a VFR monitor. That's a much better solution than resampling. When VFR wasn't a thing, sure, but it's a better option now.

**Comment by vanfanel** [comment]
@stenzek You are right: VFR monitors are the ultimate solution to the audio rate/video rate dilemma.
But the resampling option would still be desirable for enviroments where VFR is not possible: is the Raspberry Pi 4 compatible with VFR monitors? I don't think so. Also, OGA and OGA clones don't come, as far as I know, with VFR screens.

**Comment by stenzek** [comment]
On those OGA boards I don't think there's enough CPU time left for resampling, at least not currently. That's one of the reasons standalone runs faster than retroarch, and why threaded rendering makes such a difference.

**Comment by vanfanel** [comment]
@stenzek But Raspberry Pi 4 is still a target you look at as a viable platform for fullspeed standalone DuckStation, right?
Well, according to the Pi engineers, they are not going to support VRR monitors:
https://www.raspberrypi.org/forums/viewtopic.php?t=225940

I don't have an VRR monitor, but I guess there's need for specific support from the video source side, isn't it?
So, resampling would be good even if for the Pi4 alone: it's the main emulation platform in the world right now.

Other solution would be an option to set a video mode that matches the original PSX near-60Hz frequency: KMS/DRM is perfectly capable of that via drmModeSetCrtc() and a "fake" video mode. It will be compatible with most monitors for sure (in my experience with FPGAs, modern HDMI screens are very tolerant with these near-60Hz frequencies).

**Comment by stenzek** [comment]
Maybe in the future when I optimize things a bit more, I'll consider it.

I'm getting around 100fps in the Tekken 3 demo in both OpenGL and software on a Pi4 in 32-bit, running standalone on the desktop. Will try 64-bit soon.

**Comment by stenzek** [comment]
In Ubuntu 64-bit with LXDE, Pi4 @ 2ghz:

(interlacing on)
150fps OpenGL, 190fps Software

(interlacing off)
140fps OpenGL, 110fps Software

Software being slower with interlacing on is expected, as it doubles the amount it has to do per frame in 60fps games.

**Comment by vanfanel** [comment]
@stenzek Wow, great numbers.
Are you using RetroArch there or standalone DuckStation?
What buffering scheme are you using? (ie: do you let the CPU/GPU run before the last issued pageflip has completed?)
On the same conditions, do you get solid 60FPS with vsync ON?

Sorry for so many questions, I really want to know what's going on here because I have very high hopes on DuckStation :)

**Comment by stenzek** [comment]
Standalone on desktop. I refuse to try to use RetroArch on a Pi, every time I've done it, I have to try 20 different compiler flag variations before it builds successfully, and it takes like 5 minutes each time. Brought it up in the dev channel and it was ignored of course, nobody seems to know how to build it.

NoGUI doesn't block on presenting/page flip when fast forwarding, it's basically triple-buffered. It does when vsync is on. Seems I still have some synchronization issues on the vsync path though.

Near-solid 60fps, SD card causes frame spikes.

Performance on the same scene/run in NoGUI:
(interlacing off is faster in hardware because it has one fewer copy/blits to do)

```
OpenGL, interlacing off:
[    7.5836] I/NoGUIHostInterface: FPS: 161.88 VPS: 161.88 Average: 6.14ms Worst: 8.30ms
[    8.5847] I/NoGUIHostInterface: FPS: 164.81 VPS: 164.81 Average: 6.03ms Worst: 7.14ms
[    9.5866] I/NoGUIHostInterface: FPS: 154.71 VPS: 154.71 Average: 6.43ms Worst: 7.43ms
[   10.5892] I/NoGUIHostInterface: FPS: 144.62 VPS: 144.62 Average: 6.88ms Worst: 17.74ms
[   11.5909] I/NoGUIHostInterface: FPS: 156.73 VPS: 156.73 Average: 6.35ms Worst: 10.97ms
[   12.5948] I/NoGUIHostInterface: FPS: 162.37 VPS: 162.37 Average: 6.12ms Worst: 6.97ms

Software, interlacing off:
[    5.6621] I/NoGUIHostInterface: FPS: 123.32 VPS: 123.32 Average: 8.08ms Worst: 10.01ms
[    6.6639] I/NoGUIHostInterface: FPS: 132.76 VPS: 132.76 Average: 7.50ms Worst: 8.29ms
[    7.6701] I/NoGUIHostInterface: FPS: 120.25 VPS: 120.25 Average: 8.29ms Worst: 10.46ms
[    8.6730] I/NoGUIHostInterface: FPS: 128.63 VPS: 128.63 Average: 7.75ms Worst: 8.88ms
[    9.6837] I/NoGUIHostInterface: FPS: 123.68 VPS: 123.68 Average: 8.06ms Worst: 12.38ms

OpenGL, interlacing on:
[    7.5853] I/NoGUIHostInterface: FPS: 163.12 VPS: 163.12 Average: 6.10ms Worst: 8.31ms
[    8.5861] I/NoGUIHostInterface: FPS: 165.86 VPS: 165.86 Average: 5.99ms Worst: 7.03ms
[    9.5870] I/NoGUIHostInterface: FPS: 164.86 VPS: 164.86 Average: 6.03ms Worst: 7.08ms
[   10.5870] I/NoGUIHostInterface: FPS: 145.00 VPS: 145.00 Average: 6.86ms Worst: 17.07ms
[   11.5878] I/NoGUIHostInterface: FPS: 163.87 VPS: 163.87 Average: 6.07ms Worst: 6.89ms

Software, interlacing off:
[    3.6423] I/NoGUIHostInterface: FPS: 237.11 VPS: 237.11 Average: 4.19ms Worst: 6.16ms
[    4.6436] I/NoGUIHostInterface: FPS: 237.69 VPS: 237.69 Average: 4.18ms Worst: 5.50ms
[    5.6451] I/NoGUIHostInterface: FPS: 224.68 VPS: 224.68 Average: 4.42ms Worst: 8.59ms
[    6.6460] I/NoGUIHostInterface: FPS: 241.75 VPS: 241.75 Average: 4.11ms Worst: 5.31ms
[    7.6466] I/NoGUIHostInterface: FPS: 236.86 VPS: 236.86 Average: 4.20ms Worst: 5.37ms
[    8.6468] I/NoGUIHostInterface: FPS: 207.97 VPS: 207.97 Average: 4.78ms Worst: 6.77ms
```

**Comment by vanfanel** [comment]
> Standalone on desktop. I refuse to try to use RetroArch on a Pi, every time I've done it, I have to try 20 different compiler flag variations before it builds successfully, and it takes like 5 minutes each time. Brought it up in the dev channel and it was ignored of course, nobody seems to know how to build it.
> 
> NoGUI doesn't block on presenting/page flip when fast forwarding, it's basically triple-buffered. It does when vsync is on. Seems I still have some synchronization issues on the vsync path though.
> 
> Near-solid 60fps, SD card causes frame spikes.
> 
> Performance on the same scene/run in NoGUI:
> (interlacing off is faster in hardware because it has one fewer copy/blits to do)
> 
> ```
> OpenGL, interlacing off:
> [    7.5836] I/NoGUIHostInterface: FPS: 161.88 VPS: 161.88 Average: 6.14ms Worst: 8.30ms
> [    8.5847] I/NoGUIHostInterface: FPS: 164.81 VPS: 164.81 Average: 6.03ms Worst: 7.14ms
> [    9.5866] I/NoGUIHostInterface: FPS: 154.71 VPS: 154.71 Average: 6.43ms Worst: 7.43ms
> [   10.5892] I/NoGUIHostInterface: FPS: 144.62 VPS: 144.62 Average: 6.88ms Worst: 17.74ms
> [   11.5909] I/NoGUIHostInterface: FPS: 156.73 VPS: 156.73 Average: 6.35ms Worst: 10.97ms
> [   12.5948] I/NoGUIHostInterface: FPS: 162.37 VPS: 162.37 Average: 6.12ms Worst: 6.97ms
> 
> Software, interlacing off:
> [    5.6621] I/NoGUIHostInterface: FPS: 123.32 VPS: 123.32 Average: 8.08ms Worst: 10.01ms
> [    6.6639] I/NoGUIHostInterface: FPS: 132.76 VPS: 132.76 Average: 7.50ms Worst: 8.29ms
> [    7.6701] I/NoGUIHostInterface: FPS: 120.25 VPS: 120.25 Average: 8.29ms Worst: 10.46ms
> [    8.6730] I/NoGUIHostInterface: FPS: 128.63 VPS: 128.63 Average: 7.75ms Worst: 8.88ms
> [    9.6837] I/NoGUIHostInterface: FPS: 123.68 VPS: 123.68 Average: 8.06ms Worst: 12.38ms
> 
> OpenGL, interlacing on:
> [    7.5853] I/NoGUIHostInterface: FPS: 163.12 VPS: 163.12 Average: 6.10ms Worst: 8.31ms
> [    8.5861] I/NoGUIHostInterface: FPS: 165.86 VPS: 165.86 Average: 5.99ms Worst: 7.03ms
> [    9.5870] I/NoGUIHostInterface: FPS: 164.86 VPS: 164.86 Average: 6.03ms Worst: 7.08ms
> [   10.5870] I/NoGUIHostInterface: FPS: 145.00 VPS: 145.00 Average: 6.86ms Worst: 17.07ms
> [   11.5878] I/NoGUIHostInterface: FPS: 163.87 VPS: 163.87 Average: 6.07ms Worst: 6.89ms
> 
> Software, interlacing off:
> [    3.6423] I/NoGUIHostInterface: FPS: 237.11 VPS: 237.11 Average: 4.19ms Worst: 6.16ms
> [    4.6436] I/NoGUIHostInterface: FPS: 237.69 VPS: 237.69 Average: 4.18ms Worst: 5.50ms
> [    5.6451] I/NoGUIHostInterface: FPS: 224.68 VPS: 224.68 Average: 4.42ms Worst: 8.59ms
> [    6.6460] I/NoGUIHostInterface: FPS: 241.75 VPS: 241.75 Average: 4.11ms Worst: 5.31ms
> [    7.6466] I/NoGUIHostInterface: FPS: 236.86 VPS: 236.86 Average: 4.20ms Worst: 5.37ms
> [    8.6468] I/NoGUIHostInterface: FPS: 207.97 VPS: 207.97 Average: 4.78ms Worst: 6.77ms
> ```

Software + interlacing off seems very fine!
How comes SD causes frame spikes? Shouldn't threaded CD image access take care of that? Maybe I am missunderstanding something.

**Comment by stenzek** [comment]
It's either the SD card or CHD decompression, probably more likely the latter. The CD thread only reads a single sector ahead, and sometimes it's still too slow decompressing before the next sector is needed.
