### ISSUE TITLE
Android - First Dutch Translation

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#1177]
Yo @stenzek 

On behalf our friend DenSinH upload first Dutch translation for Android

[updated] 9/12

Arrays and Strings
[Dutch.zip](https://github.com/stenzek/duckstation/files/5665660/Dutch.zip)

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/523dda47fa9609d9b2a3ebea46e745a885f1adb6
