### ISSUE TITLE
Physics are broken on one of the platforms in Disney's Tarzan

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#118]
At the end of the level "Trashing the Camp" you're supposed to be able to bounce on this board to reach the sketch but the platform has no bounce. 

![SCUS-94456_2020-03-18_01-55-46](https://user-images.githubusercontent.com/31968468/76871632-67ef4e00-68bf-11ea-9ac7-7be0309e62fe.png)

Here's a video showing what's supposed to happen. I tried to post a save state right at the platform but GitHub won't let me so you'll have to use the game's built in level select cheat to get there quick. 

https://youtu.be/mWw2DvCduSg?t=418

**Comment by stenzek** [comment]
Save states aren't sharable at the moment anyway because the path to the CD image is included.

**Comment by kurayami6** [comment]
This one doesn't work either. 

![SCUS-94456_2020-03-18_19-59-46](https://user-images.githubusercontent.com/31968468/76943407-666f6580-6953-11ea-9003-3aa262e756da.png)

I also got to this point and the audio broke and turned into deafening static. Jesus fucking Christ my ears.

![SCUS-94456_2020-03-18_20-01-43](https://user-images.githubusercontent.com/31968468/76943442-7b4bf900-6953-11ea-9c95-5a1b865043ae.png)

**Comment by kurayami6** [comment]
All issues are fixed as of the latest version.
