### ISSUE TITLE
Feature Request: Playlists and Preload to RAM

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#1182]
If possible can there be an option to preload all the discs into RAM, thou yes that would be a huge dump in some cases 3-4GB so alternately could you add a small pop up window that asks which disc to boot in the playlist?

It's a small pain to have to preload CD1 just to switch to discs 2 and wait to preload that especially with compression.

Cheers.

**Comment by stenzek** [comment]
No sorry, that would require non trivial modifications to how playlists and media are handled.
