### ISSUE TITLE
PS1 Bios not working properly

### ISSUE THREAD

**Issue by jaystorm20** [stenzek/duckstation#1183]
I had downloaded epsxe and it was stuttering and going slow, the same happened with duckstation, i don't know where i am going wrong here, i am running wins 10 gaming pc with nvidia gforce gtx graphics card, i5 series processor and 8 gig ram

**Comment by stenzek** [comment]
What fps/speed percentage is it showing? You can display this in the settings.

Also make sure you're not overriding things like FPS in your graphics driver. Duckstation needs to present at 60fps.
