### ISSUE TITLE
Colour precision in hardware renderers

### ISSUE THREAD

**Issue by PavelDurov1488** [stenzek/duckstation#1184]
For example, FF VII

Software 1x
![image](https://user-images.githubusercontent.com/74456272/101715811-0f0fb780-3ad7-11eb-9398-bec2dcd2cc74.png)
HW D3d11 1x, no true color rendering
![image](https://user-images.githubusercontent.com/74456272/101715975-6d3c9a80-3ad7-11eb-9509-0d69e8c5cba5.png)

HW D3d11 1x, true color rendering

![image](https://user-images.githubusercontent.com/74456272/101716034-834a5b00-3ad7-11eb-9a86-ac73fb4e0657.png)

Rearmed 1x
![image](https://user-images.githubusercontent.com/74456272/101716373-18e5ea80-3ad8-11eb-9b6a-d7cb96f9d2a8.png)

So, now the most accurate mode for colors is  1x, no true color rendering, software

Its obvious, of course, but maybe fixable for hw renders...

**Comment by stenzek** [comment]
Yeah, it's a dither offset issue if I remember correctly, been meaning to fix it for hardware.

True colour rendering is an enhancement, and definitely will produce different results. Software is always 16-bit, the enhancements have no effect (except widescreen).

**Comment by PavelDurov1488** [comment]
Your project is very cool potentionally. As for me, I prefer 1x resolution cause i know how to use it...

But, if compare it with rearmed core on my ff vii version, DS works faster (image is not good). Also, in DS dithering exists in the battle battle, in pcsx there is no dithering in the battle

But for normal JRPG fans DS is bad solution (mostly), its too visible

Also, FF VII needs CPU Recompiler ICache ON, at least when there is end of the battle, I hear small speed up and higher sound tone %)

**Comment by stenzek** [comment]
> But, if compare it with rearmed core on my ff vii version, DS works faster (image is not good). Also, in DS dithering exists in the battle battle, in pcsx there is no dithering in the battle

I wouldn't use pcsx-rearmed as a ground truth - please compare with console, or at the very least with mednafen. Regarding dithering, duckstation is likely correct here.

> Also, FF VII needs CPU Recompiler ICache ON, at least when there is end of the battle, I hear small speed up and higher sound tone %)

Feel free to enable it, but I try to force enable it only for games which absolutely need it, as there's a performance hit on low-end devices.

**Comment by stenzek** [comment]
So I looked into this, are you certain you disabled true colour rendering in the second screenshot, and aren't using any texture filters? Because hardware and software are almost exactly the same for me, bar a tiny intensity difference in the green channel due to conversion to RGB565.

Software:
![image](https://user-images.githubusercontent.com/11288319/101790683-79177380-3b4e-11eb-8435-f2bf5ebbee23.png)
Hardware (true colour off):
![image](https://user-images.githubusercontent.com/11288319/101790699-7ddc2780-3b4e-11eb-884b-5249b9fd7eba.png)
Hardware (true colour on):
![image](https://user-images.githubusercontent.com/11288319/101790780-91878e00-3b4e-11eb-84a5-0e794141ca75.png)

**Comment by stenzek** [comment]
Closing as I can't see any issue here.

**Comment by PavelDurov1488** [comment]
Ohh, maybe it helps. I use retroarch, by the way. Save file from memory card is attached
[duckstation_shared_card_2.zip](https://github.com/stenzek/duckstation/files/5685012/duckstation_shared_card_2.zip)


![image](https://user-images.githubusercontent.com/74456272/102018457-52ed1000-3da8-11eb-8b7e-d923cc4736e8.png)
![image](https://user-images.githubusercontent.com/74456272/102018464-5da7a500-3da8-11eb-96b2-1e17d034b129.png)
![image](https://user-images.githubusercontent.com/74456272/102018460-584a5a80-3da8-11eb-8300-b031e5c8ba41.png)

**Comment by PavelDurov1488** [comment]
Maybe its only retroarch trouble...
