### ISSUE TITLE
Blur as alternative of texture filtering

### ISSUE THREAD

**Issue by PavelDurov1488** [stenzek/duckstation#1186]
Hmm

Tried your core for RetroArch for FF7 and there is >1x rendering problem

Final Fantasy 7 is 2D+3D world, PS1 graphic is minecraft-like, it's not problem or bug...

If you apply 2x rendering for better 3d, 2d world will be pixelated, cause bilinear filter for whole picture does not work correct

If you apply bilinear filter inside emulator, you get normal 2d world, but 3d objects has blurry textures now

Its possible to fix with gaussian blur it looks same, maybe it will be interesting...

![image](https://user-images.githubusercontent.com/74456272/101731638-e1d30180-3af6-11eb-8fa3-301aa008325c.png)
![image](https://user-images.githubusercontent.com/74456272/101731658-ea2b3c80-3af6-11eb-9009-9324ea00b3e4.png)
![image](https://user-images.githubusercontent.com/74456272/101731665-ebf50000-3af6-11eb-9e26-c15f97cbc8cd.png)
![image](https://user-images.githubusercontent.com/74456272/101731674-eeeff080-3af6-11eb-810c-53292811b100.png)
![image](https://user-images.githubusercontent.com/74456272/101731693-f8795880-3af6-11eb-863c-f9e2439f78f5.png)
![image](https://user-images.githubusercontent.com/74456272/101731704-fd3e0c80-3af6-11eb-9c71-308ead2099f2.png)
![image](https://user-images.githubusercontent.com/74456272/101731715-00d19380-3af7-11eb-9902-5850e1f26d9c.png)

**Comment by stenzek** [comment]
This sounds like postprocessing.

**Comment by PavelDurov1488** [comment]
Yep) But this solves many problems, like agressive dithering, banding,stair effect on 1x resolution...

For example, its Monkey Hero difference
![image](https://user-images.githubusercontent.com/74456272/101740687-22854780-3b04-11eb-876c-7eecb33e72be.png)

![image](https://user-images.githubusercontent.com/74456272/101740647-14372b80-3b04-11eb-872f-ec5b31270892.png)

**Comment by stenzek** [comment]
We'll track this in https://github.com/stenzek/duckstation/issues/1133 then.
