### ISSUE TITLE
[Request] Support to Supersampling anti-aliasing and downsample to native res

### ISSUE THREAD

**Issue by Red-gehog** [stenzek/duckstation#1187]
Hi! I came to suggest this anti-aliasing option. Supersampling is one of the best anti-aliasing options, it would be great to use it on the Duckstation, because this emulator is very fast. The downsample to native res is used to make it possible to use shaders such as nedi or scalefx-raa, taking advantage of the generated aliasing to obtain a better filtering of these shaders.

* I exemplified with images of the downsample to native resolution, but I am also referring to an option to use as anti-aliasing for 1080p as an example.

Examples (Beetle PSX HW), notice the crosswalk:

normal:
![Mad Stalker - Full Metal Force (Japan)-201210-042536](https://user-images.githubusercontent.com/73415642/101735192-431bb600-3aa0-11eb-84c7-b41abf216039.png)
-
-
scalefx-raa, no supersampling (downsample to native res)
![Mad Stalker - Full Metal Force (Japan)-201210-042545](https://user-images.githubusercontent.com/73415642/101735286-71999100-3aa0-11eb-8bec-ef52ca8326dd.png)
-
-
supersampling (downsample to native res) only:
![Mad Stalker - Full Metal Force (Japan)-201210-042716](https://user-images.githubusercontent.com/73415642/101735341-837b3400-3aa0-11eb-94bf-16a284396639.png)
-
-
scalefx-raa with supersampling (downsample to native res) activated:
![Mad Stalker - Full Metal Force (Japan)-201210-042731](https://user-images.githubusercontent.com/73415642/101735718-07352080-3aa1-11eb-99c8-f2e00c6fd46b.png)

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/3cb2cd8235df5edfd05b2c7ec10037b5f0bf1001
