### ISSUE TITLE
Graphical glitches in Crash Bandicoot: Warped 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#119]
![1584433776282](https://user-images.githubusercontent.com/31968468/76927633-9e66b080-6933-11ea-84ed-1b5488c13abe.png)

**Comment by stenzek** [comment]
Pretty sure this wasn't an issue a while back, but I've seen it in a few games now. It's a regression from something.

**Comment by stenzek** [comment]
Nevermind, I think this is invalid, the issue also occurs on console. It's just more noticeable at higher resolution.
