### ISSUE TITLE
[FF VII] Edges highlight with bilinear filtering

### ISSUE THREAD

**Issue by PavelDurov1488** [stenzek/duckstation#1191]
Not very visible, but...

Its with 'no edge blending'
![image](https://user-images.githubusercontent.com/74456272/101814098-9f421100-3b58-11eb-9474-970611339874.png)
Just bilinear
![image](https://user-images.githubusercontent.com/74456272/101814157-b8e35880-3b58-11eb-89be-b5ad64e6d6ca.png)
Without anything
![image](https://user-images.githubusercontent.com/74456272/101814218-cc8ebf00-3b58-11eb-88bf-e8a1713cc9fa.png)

But, haha, blur works with 2x rendering without internal filters :-)

![image](https://user-images.githubusercontent.com/74456272/101814316-f1833200-3b58-11eb-9ed6-c18afda79292.png)

Its 1x resolution
![image](https://user-images.githubusercontent.com/74456272/101814386-0a8be300-3b59-11eb-980d-e9dab499519c.png)

Its zip-file with mcd...
[SCUS-94163_1.zip](https://github.com/stenzek/duckstation/files/5674916/SCUS-94163_1.zip)

**Comment by stenzek** [comment]
Enhancements aren't guaranteed to work in every game.
