### ISSUE TITLE
Raspberry pi 4  internal Resolution scale 1x problem

### ISSUE THREAD

**Issue by Cibomatto2002** [stenzek/duckstation#1193]
using duckstation and noticed some games with text is messed up setting the internal Resolution scale to 2x fixes it but pie 4 can't do that to good because it slows down to much to play a game tried this on windows 10 and its fine at 1x here is a picture from the pie 4 at 1x of the problem. the game in the picture is Dragon Warrior 7

![2](https://user-images.githubusercontent.com/21169038/101838939-177fe680-3b07-11eb-9bd4-1a6d86174be1.jpg)

**Comment by stenzek** [comment]
See https://github.com/stenzek/duckstation/issues/283

**Comment by Cibomatto2002** [comment]
I did not see that post sorry about wasting your time

**Comment by stenzek** [comment]
No problem. It's actually tracked upstream in Mesa as well: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3758

**Comment by Botspot** [comment]
Is there a tutorial somewhere that shows how to install Duckstation on a Pi4?

**Comment by Cibomatto2002** [comment]
> Is there a tutorial somewhere that shows how to install Duckstation on a Pi4?

Lakka nightly has duckstation for the pi4. https://nightly.builds.lakka.tv/2020-12-21/RPi4.arm/

**Comment by Botspot** [comment]
An image? Sorry that won't work. I'd like to install Duckstation onto a pre-existing RPiOS install.

**Comment by stenzek** [comment]
> An image? Sorry that won't work. I'd like to install Duckstation onto a pre-existing RPiOS install.

https://github.com/stenzek/duckstation#linux-1
