### ISSUE TITLE
Analog-to-dpad does not apply when forcing digital controller

### ISSUE THREAD

**Issue by ggrtk** [stenzek/duckstation#1196]
For games with the ForceDigitalController trait, the AnalogDPadInDigitalMode setting does not apply because we force a change in controller type to digital controller rather than preventing the analog controller from starting in analog mode. From a user viewpoint, I think the expectation would be that if the currently set controller is analog controller, analog-to-dpad should work for games that are only compatible with digital mode.

To be honest, I have mixed feelings about ForceDigitalController as a game setting. It works a solution for games that don't work with forcing analog mode on reset, but it feels a bit unsatisfying to have to use a shipped database to override what is effectively a convenience hack. Forcing analog mode on reset causes problems with pre-analog controller titles, software that expects the controller to start up in digital mode and checks for that condition, etc. So maybe forcing analog mode could be a per-game user configurable setting rather than ForceDigitalController? Though that might open back up the "help why are analog controls not working" questions...

**Comment by ggrtk** [comment]
In any case, fixing this issue should be easy enough -- will go ahead with that for now.

**Comment by RinMaru** [comment]
I had this problem but was told its intentional

**Comment by stenzek** [comment]
@RinMaru it is working as intentional ;) But I'm happy to accept alternative implementations.

I'd be okay with renaming `ForceDigitalController` to `ForceAnalogMode`, perhaps adding a boolean setting which blocks analog mode enabling, and setting this via the gameini.

**Comment by ggrtk** [comment]
Considering this resolved by #1195.
