### ISSUE TITLE
SDL volume controls not working

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#1198]
**Game details**
Any.

**Description of the issue / bug**
when trying to change volume by hitting - for volume decrease and /  or + for volume increase, if my audio option is in SDL mode nothing happens. There is a OSD messages normally but sound doesn't change at all.

**Steps to Reproduce**
Press volume up or down (with your prefered shorcut key nothing will happen, besides OSD display showing: -10% -20% or +20%) etc

**Enhancements information**
Not related.

**Hardware/software**
Not related.

**Emulator version**
Latest (0.1-2520-ga391ba16)

**Additional context**
I do not know if this is related but I'd like to add in the same issue.

There is a soung bug as follows:
1. While playing > configurations > Sound (Tick): Mute all Sound

2. Try to umute, and will be forced as muted needing to restart over to turn it back on again.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/6e7f1501b53ac09a823038b965d91b87fc5307d5 and https://github.com/stenzek/duckstation/commit/f4d540bcc69e9360ca56ad00e60c7daac5fa5208.
