### ISSUE TITLE
[Feature Request] Screenshot capture

### ISSUE THREAD

**Issue by trostboot** [stenzek/duckstation#12]
Built-in screenshot capture would be very useful.

Nice-to-haves:

- Customizable path
- Option to save the image to the game directory instead (would disable the path option).
- Pulling from the database to name the file, with the game filename as a fallback (maybe also as an option).
- Option for either a raw 1:1 capture, or whatever is on screen post-scaling or any potential future filters.
- PNG
- Naming scheme for easy sorting, %name%_YYYY_MM_DD_HHMMSS

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/ba3b799343fb6eca38da9625f775f57f5322ee59

Still needs a few things:
 - Add a hotkey for capture
 - Different formats
 - Disable/enable scaling options (supported by the core code, just not exposed in the UI)
