### ISSUE TITLE
Stage name is broken in Transformers: Beast Wars Transmetals 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#120]
Duckstation

![SLUS-01160_2020-03-18_16-50-56](https://user-images.githubusercontent.com/31968468/76930392-7c246100-693a-11ea-9324-f9edd556b863.png)

Beetle PSX

![Transformers - Beast Wars Transmetals (USA)-200318-165533](https://user-images.githubusercontent.com/31968468/76930415-86def600-693a-11ea-8b05-07d54c4fde1b.png)

There are other issues like the character models flickering on the loading screens and pulsating when the game is paused but obviously I can't convey that through screenshots. Maybe a way to record short video clips would be useful. Dolphin has that even though it's a pain in the arse to use.

**Comment by stenzek** [comment]
Does this happen in the software renderer?

**Comment by kurayami6** [comment]
No. It's only broken in D3D11.

**Comment by stenzek** [comment]
I'm collapsing this to https://github.com/stenzek/duckstation/issues/153 as it seems to be the same issue. If it is a different issue and persists with the OpenGL/Software renderers, please re-open.
