### ISSUE TITLE
Use different covers same Game....

### ISSUE THREAD

**Issue by jvhellraiser** [stenzek/duckstation#1200]
Yeah you hear it right i have 2 of the same ISO one is hack the other is the Normal version
as you know Megaman X6 has a tweak utility if you use it you will have 2 Megaman X6
1 tweak 1 normal the problem is that i can't choose the cover i want for 1 or the other,..
![Screenshot 2020-12-11 220705](https://user-images.githubusercontent.com/16488761/101969860-39f42b80-3bfd-11eb-96c3-575cb8d2aa18.jpg)

And this one..
![Mmx6box](https://user-images.githubusercontent.com/16488761/101969922-a0794980-3bfd-11eb-98ec-0c5058dda477.jpg)

**Comment by stenzek** [comment]
You can use a cover image based on the filename of the game, but currently the database title takes priority:

e.g. `Mega Man 6 (USA).chd` and `Mega Man 6 (USA) (Modded).chd`, it will look for `Mega Man 6 (USA).png` and `Mega Man 6 (USA) (Modded).png`. But the first one takes priority. I'll change this soon.

**Comment by jvhellraiser** [comment]
> 
> 
> The game list should use the cover based on the file title first, as of [90997d4](https://github.com/stenzek/duckstation/commit/90997d4a8b6fdb604f3516fa4ae3fe03610d7410).
> 
> So name your cover the same as your modded filename.

I did rename the cover as the Megaman 6 tweak version,jpg 
and try to replace the cover but it still both cover change at the same time.
