### ISSUE TITLE
can't run duckstation on windows 7 ultimate 64 bit

### ISSUE THREAD

**Issue by Cibomatto2002** [stenzek/duckstation#1201]
using retroarch 1.9.0 all other emulators I have tried are working for playing ps1 games. mednafen_psx_libretro.dll, pcsx_rearmed_libretro.dll

My laptop may be to old to use duckstation. I don't think it has open gl i know for sure it does not have vulkan. when trying to run duckstation it goes back to retroarch 1.9.0

Acer Aspire 5733Z  I think it cam out in 2011 not sure.

Operating System
	Windows 7 ultimate 64-bit
CPU
	Intel Pentium P6200 @ 2.13GHz
	Arrandale 32nm Technology
RAM
	4.00GB Dual-Channel DDR3 @ 532MHz (7-7-7-20)
Motherboard
	Acer Aspire 5733Z (CPU)
Graphics
	Generic PnP Monitor (1366x768@60Hz)
	Intel HD Graphics (Acer Incorporated [ALI])
Storage
	465GB TOSHIBA MK5059GSXP (SATA )
Optical Drives
	HL-DT-ST DVDRAM GT32N
Audio
	Realtek High Definition Audio

**Comment by stenzek** [comment]
Have you tried the standalone version? You should be able to use the Direct3D renderer, or software (with D3D presentation).

Also, I do not officially support Windows 7 - see the note in the readme:
> Windows 10 is the only version of Windows supported by the developer. Windows 7/8 may work, but is not supported. I am aware some users are still using Windows 7, but it is no longer supported by Microsoft and too much effort to get running on modern hardware. Game bugs are unlikely to be affected by the operating system, however performance issues should be verified on Windows 10 before reporting.

**Comment by Cibomatto2002** [comment]
I had no idea there was a standalone version thanks for telling me I will try it out. i just use retroarch for everything.  iwill try it out and post if it works.

**Comment by Nucleoprotein** [comment]
d3dcompiler_47.dll is in here https://www.microsoft.com/en-us/download/details.aspx?id=35
msvcp140.dll is in here: https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by stenzek** [comment]
Closing as this is either a retroarch or support issue. If you still need help, feel free to continue to reply here, or chat to one of us on Discord.
