### ISSUE TITLE
[Bug] Final Fantasy VIII DRM

### ISSUE THREAD

**Issue by Tikilou** [stenzek/duckstation#1203]
Hi ! First, thanks for this fantastic emulator/works !

There is a problem with Final Fantasy VIII, wich have a DRM resulting to a blackscreen after playstation licence logo loading.
It works only with a patch, but the original PsOne work out of the box with the original game and i hope you can help with it for a full PsOne support even with DRM. :)

**Comment by stenzek** [comment]
Not really sure what you're asking for here. The region check can be disabled and is ignored anyway if you use fast boot. If the patched game doesn't boot in the emulator, it probably wouldn't boot on console either.

**Comment by stenzek** [comment]
If you're talking about PAL FF8, it has libcrypt protection and you need to provide a sbi file alongside the disc image. You can get these from redump.org. See https://github.com/stenzek/duckstation#libcrypt-protection-and-sbi-files - if your dump was named `ff8_disc1.cue`, you should name the sbi file `ff8_disc1.sbi`.

**Comment by Tikilou** [comment]
Thanks for your answer ! Everything is working now, i was thinking theses data already was inside the iso dump. Your emu is great, even support libcrypt DRM... =D
I've tested with NoCash Bios, SCPH-1001, and dumped PSP bios for PsOne, everything is okay :+1:
