### ISSUE TITLE
Frogger unexpected pause

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#1204]
New issue since https://github.com/stenzek/duckstation/issues/831 was closed.

Managed to capture the problem on video: [PlKjbWLfo8.zip](https://github.com/stenzek/duckstation/files/5683982/PlKjbWLfo8.zip)

If you step through the frames you can see just shortly before the issue occurs performance drops a little, and it's pausing because it thinks the controller was unplugged.

![PlKjbWLfo8 mp4_20201213_011621 525](https://user-images.githubusercontent.com/4934209/101999791-d2afa780-3ce0-11eb-930b-7f006abedaf9.jpg)

Is this related to it attempting to simulate memory card replugging? (OSD)

Perhaps Pandemonium is affected similarly https://github.com/stenzek/duckstation/issues/831#issuecomment-737319813

**Comment by stenzek** [comment]
Does setting the DMA max slice ticks in game properties to 200 or 100 make any difference?

**Comment by Richard-L** [comment]
100 seems to help in both games yeah. Reverting back to 0 does not make the problem re-appear though strangely.

**Comment by stenzek** [comment]
Gameini added in https://github.com/stenzek/duckstation/commit/fd0e75ea61e298aac6cb679491dd53efaba77b8f. I'll add Pandemonium later as well.
