### ISSUE TITLE
[SLUS-00545] Shadow Master (USA) - Crashes ingame in recompiler mode

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#1206]
**Game details**
SLUS-00545 - Shadow Master (USA)

**Description of the issue / bug**
The emulator crashes in the first few seconds of gameplay.

**Steps to Reproduce**
Use Recompiler mode. Start the game, then just play for few seconds. The emulator crashes.

**Hardware/software**
i7-4790, 16 GB RAM, GTX 1070, Windows 10 x64

**Emulator version**
0.1-2538-g5c6ee953

**Comment by darkxex** [comment]
![image](https://user-images.githubusercontent.com/17991404/102002537-34214780-3cdc-11eb-948b-696d8c034c79.png)
working in retroarch core.

**Comment by Shideravan** [comment]
I

> ![image](https://user-images.githubusercontent.com/17991404/102002537-34214780-3cdc-11eb-948b-696d8c034c79.png)
> working in retroarch core.

It's Shadow MASTER. Not Shadowman.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/5164840c25c67bc3143a9dce8b1c22458e7fd75f

**Comment by darkxex** [comment]
sorry, i'm stupid.
