### ISSUE TITLE
[SLPS-02243] Remote Control Dandy (Japan) - Crash during the opening cutscene

### ISSUE THREAD

**Issue by Krusher97** [stenzek/duckstation#1207]
**Game details**
SLPS-02243 - Remote Control Dandy (Japan)

**Description of the issue / bug**
The emulator freezes with a black screen right after the loading screen after the cutscene of the boy running out of the restaurant.

**Steps to Reproduce**
Start a new game and let the cutscene run.

**Enhancements information**
Default settings

**Hardware/software**
 CPU:i5 6500 3.2Ghz
GPU:Nvidia GeForce 750 Ti
OS:Windows 7 Ultimate 64-bit SP1
GPU Renderer - D3D11

**Emulator version**
0.1-2538

**Additional context**
Does not happen in mednafen

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/d0e68c71638a4d0092b77723c08daa3626c97e70
