### ISSUE TITLE
Automatic update of translation files.

### ISSUE THREAD

**Issue by shikulja** [stenzek/duckstation#1208]
The files are easy to translate, but updating is not a trivial task, need to install both qt and vs, this is too redundant

**Comment by stenzek** [comment]
You don't need to install Qt, everything is included in tree. See https://github.com/stenzek/duckstation/wiki/Translating-to-new-languages

**Comment by shikulja** [comment]
2. Drag and drop the .ts file you wish to edit onto create-update-and-edit-language.bat file in src\duckstation-qt\translations.
This will add the new strings to the .ts file, report how many new strings there are for translation, and open it in Qt Linguist for editing.

i get:

```
Системе не удается найти указанный путь.
Для продолжения нажмите любую клавишу . . .
```
(path not found)

because:
set "linguist=..\..\..\dep\msvc\qt\5.15.0\msvc2017_64\bin"

linguist - this is part of qt, but even after installing it, you still cannot use bat, because most likely either the version in the path name or msvc2017_64 was not included.

**Comment by stenzek** [comment]
Are you cloning the repository with submodules (recursive clone)? Linguist is included in my cut down qt distribution submodule (https://github.com/stenzek/duckstation-ext-qt-minimal/tree/master/5.15.0/msvc2017_64/bin). You can also do `git submodule update --init`.

**Comment by shikulja** [comment]
@stenzek thanks, I'll try
