### ISSUE TITLE
 it's retroarch's broken context resetting Emulation freezes, when reconnecting tv via hdmi after it was disconnected

### ISSUE THREAD

**Issue by Ninaadark18** [stenzek/duckstation#1209]
The whole emulator freeze in retroarch core (latest version 2020/12 xmas month) 
And lost all the progress that i make and cause destroy to the save file(all types shared or separate memory card) of the game by make it unreadable and unwritable 
Also when try to load the save file the game gose black screen.

**Comment by stenzek** [comment]
This sounds like a retroarch issue, as all of these sorts of things are out of the core's control.

If I had to guess, it's retroarch's broken context resetting. Does it happen in the software renderer? Could also try the standalone version in case it is a duckstation bug.

**Comment by Ninaadark18** [comment]
> This sounds like a retroarch issue, as all of these sorts of things are out of the core's control.
> 
> If I had to guess, it's retroarch's broken context resetting. Does it happen in the software renderer? Could also try the standalone version in case it is a duckstation bug.

thak you i try and it seems as you say  it's retroarch's broken context resetting
