### ISSUE TITLE
Main menu is a black screen in Vampire Hunter D

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#121]
Everything before and after it renders fine and I can press start to get past it, I just can't see it. Happens with all renderers.

Duckstation

![SLUS-01138_2020-03-19_04-17-21](https://user-images.githubusercontent.com/31968468/76988270-912fdd00-6998-11ea-9fbc-76a3f63fceaf.png)

Beetle PSX

![Vampire Hunter D (USA)-200319-041142](https://user-images.githubusercontent.com/31968468/76988316-9f7df900-6998-11ea-96ab-90b1a5db78a6.png)

**Comment by kurayami6** [comment]
Was hoping this would be fixed by the latest changes but unfortunately not. I can see it if I turn on "Show VRAM"

![SLUS-01138_2020-04-19_04-41-31](https://user-images.githubusercontent.com/31968468/79663027-1a386f00-81f8-11ea-87a1-f9d1390e5f6c.png)

**Comment by stenzek** [comment]
Not sure what's going on here - it's not sending any draw commands to the GPU at all.. something is missing.

**Comment by stenzek** [comment]
Needs tight CPU/DMA sync. Noting here for future gameini.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/71eb578db18570311c4ee9f4009e83cfecdee2aa plus the DMA changes.
