### ISSUE TITLE
[Libretro core] .m3u mulit-disk files not loading on OGA system

### ISSUE THREAD

**Issue by romadu** [stenzek/duckstation#1211]
**Game details**
m3u file for Xenogears (USA) (Disc 1) and (Disc 2) as bin/cue
m3u file for Metal Gear Solid (USA) (Disc 1)(Rev 1) and (Disc 2)(Rev 1) as bin/cue
m3u file for Heart of Darkness (USA) (Disc 1) and (Disc 2) as bin/cue
m3u file for Final Fantasy VII (USA) (Disc 1), (Disc 2) and (Disc 3) as bin/cue
m3u file for Driver 2 (USA) (Disc 1)(Rev 1) and (Disc 2)(Rev 1) as bin/cue
m3u file for Colony Wars (USA) (Disc1) and (Disc 2) as bin/cue

**Description of the issue / bug**
Game doesn't load. RetroArch log shows that game was loaded for 0 seconds, but no other error
Same m3u files work correctly in RetroArch with PSCX-Rearmed core

**Steps to Reproduce**
m3u file lists relevant .cue files for multi-disc game. m3u file is used to load multi-disc game in RetroArch with duckstation core.

**Enhancements information**
none

**Hardware/software**
RG351P arm 64 bit

**Emulator version**
Retroarch 1.9.0 - latest libretro core, just updated

**Additional context**

**Comment by stenzek** [comment]
Couldn't reproduce this when I tested. Maybe something else is missing, e.g. BIOS? Try checking the log - it should say why startup failed.
