### ISSUE TITLE
[Request] Auto download the NoCash Bios Clone ?

### ISSUE THREAD

**Issue by Tikilou** [stenzek/duckstation#1215]
Hi ! A cool feature could be to purpose at the first launch and in the bios settings to download add the Bios Clone from No$PSX in the bios list. It's sadly not open-source, but has freeware, could be cool to give this option to anybody (because it's still forbidden to have the dump of PsOne original bios if we don't have PsOne/PSP/PSvita/PS2/3/4/5.)
Do you thinks NoCash would agree for that ? :+1:

**Comment by stenzek** [comment]
Not really something I'm interested in, because while the nocash bios is very impressive, it could still cause compatibility issues. Also I'm not going to scrape something without the owner's permission.
