### ISSUE TITLE
Adding "Renderer" in the custom properties menu of individual games

### ISSUE THREAD

**Issue by tycooko** [stenzek/duckstation#1217]
Hello,
Would it be possible to determine which renderer the software uses for each game?
I would prefer to just leave "Vulkan" on for every game, but with that renderer I can't select xBR texture filtering because it makes DuckStation crash and especially Final Fantasy games look terrible with any other filter. So I'd like to activate OpenGL just for Final Fantasy games so that I can then select the filter I want.
Thank you!

OS: macOS Big Sur Version 11.0.1
Device: iMac (Retina 5K, 27-inch, 2020), model identifier iMac20,2
DuckStation version: 0.1-2553-g3ed42977 (master)

**Comment by stenzek** [comment]
Game settings are applied during startup, and switching the renderer here would create issues, if not make things very crash-prone. Better off trying to fix whatever is causing the crash in MoltenVK.
