### ISSUE TITLE
Irem Arcade Classics (Japan) menu screen black 3/4 of screen

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#122]
![irem](https://user-images.githubusercontent.com/2696404/77053235-020edd80-6a09-11ea-80a6-33d943d46d33.PNG)

**Comment by stenzek** [comment]
Woah, that's a strange one. Does it happen with all the crop modes?

**Comment by stenzek** [comment]
Couldn't reproduce - most likely a duplicate of https://github.com/stenzek/duckstation/issues/153
