### ISSUE TITLE
[SLUS-00547] Adidas Power Soccer 98 (USA) - Autopause

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#1222]
**Game details**
[SLUS-00547] Adidas Power Soccer 98 (USA)

**Description of the issue / bug**
The game pauses by himself with few minutes playing

**Steps to Reproduce**
Play some minutes. The game will start to autopause.

**Emulator version**
0.1-2553-g3ed42977

**Comment by stenzek** [comment]
Another one which needs tighter DMA. Fixed in https://github.com/stenzek/duckstation/commit/c0c035ab545dfd5d654609b69464fc72c40d4796
