### ISSUE TITLE
Time Crisis crosshair position on X axis doesn't line up with the cursor

### ISSUE THREAD

**Issue by Comfarol** [stenzek/duckstation#1223]
Time Crisis cross-hair position on the x axis doesn't line up with the cursor. 

Calibrating is off in the center of the screen while using the Duckstation cross hair to line it up perfectly.
![image](https://user-images.githubusercontent.com/27315987/102036599-fb35bf80-3e0e-11eb-858d-5a4702e9bc54.png)

Moving to either left or right sides of the screen it drifts away further and further.
![image](https://user-images.githubusercontent.com/27315987/102036848-a181c500-3e0f-11eb-91aa-3d3c05e0fc21.png)

Steps to reproduce
1. Set device to Guncon
2, Run Time Crisis to the calibration screen
3. Shoot in the center to calibrate.
4. Move cross hair to the left and right edges,

Tested on 4:3, 16:9 and widescreen hack on and off.
Tested other non Justifier games and they all calibrate correctly and play great.
Tested SLUS-00405 Time Crisis (USA), SCES-00657 Time Crisis (Europe) both share issue.

Thank you for your time.

**Comment by ggrtk** [comment]
We can add an adjustable scaling factor as mentioned here https://github.com/stenzek/duckstation/issues/583#issuecomment-653111117. The calibration might be fixable with a slight positional offset, not sure yet. Time Crisis just isn't very precise about this unfortunately.

**Comment by stenzek** [comment]
This was added in https://github.com/stenzek/duckstation/commit/4860313bef8e239d3ba11edbc2430bcd4aa8e03d#diff-0bb1cad1f33be9f995bae21b1d43c025c6d7c295923286a77f51d30dce0542b8
