### ISSUE TITLE
Shift key gets directionals stuck.

### ISSUE THREAD

**Issue by RiddleSnowcraft** [stenzek/duckstation#1225]
**Game details**
SLES-01726 Bugs Bunny: Lost in Time (USA)

**Description of the issue / bug**
I set the game to use the Shift key as a jump button. Jumping with a directional pressed makes the directional get stuck, leaving the character walking indefinitely until the affected directional is pressed a second time, then the key release is registered.

**Steps to Reproduce**
"Keyboard/Shift" is set as "Cross". "Keyboard/Left" is set as "Left".
To jump right, I press "Left" and then "Shift" to jump, letting go of the "Left" button before letting go of the "Shift" button.
This causes the character to keep walking left, as if the "Left" key is held after it's already been released.
Problem persists whether NumLock is on or off. Controller backends "None", "SDL" and "Xinput" don't affect the behaviour of the problem. Problem seems particular to the nature of the "Shift" key, as associating other keys to "Cross" results in no further issues.

**Hardware/software**
i5-2500 CPU @ 3.30GHz
NVidia Geforce GT710
D3D11

**Emulator version**
0.1-2553-g3ed42977 (master)

**Additional context**
Had the exact same problem on specific recent versions of VisualBoyAdvance, which I solved by downgrading to an earlier build of that. Not sure if this applies to Duckstation.

**Comment by stenzek** [comment]
Yup, it's likely because it's being treated as a modifier. I have plans to refactor the input so you can use multi key chords which don't depend on the modifiers (as well as multi button combos on controllers)

**Comment by RiddleSnowcraft** [comment]
Oh, I see.
I don't really have an idea of what a modifier is but I'm really thankful for the answer.
Right now I'm using Z for the jump button, which actually works fine with my current muscle memory, so I'm closing the issue. Thanks!

**Comment by stenzek** [comment]
Modifier keys are shift/control/alt/etc.

Glad you found a workaround, but it will get fixed properly soon :)
