### ISSUE TITLE
Create a Chocolatey package for DuckStation

### ISSUE THREAD

**Issue by lufemas** [stenzek/duckstation#1228]
Here is the docs: https://docs.chocolatey.org/en-us/create/create-packages

Using a package manager is the best way to install new applications on windows. The most used ones are Chocolatey and Scoop.
I think it should be a good idea to deliver it using a Windows Package Manager.

**Comment by stenzek** [comment]
How would this work with auto-updates? Does the package manager handle updates, or can the application update itself like DuckStation does?

I'm not really interested in packaging, but if someone else wants to set it up, I'm happy to provide links and such.

**Comment by lufemas** [comment]
The auto-updater isn't disabled by the install script, like chrome has it own auto update.
I will take a look on the package creation and maybe I can help with it.

**Comment by stenzek** [comment]
Not planning on doing this myself, and I'm trying to clean up requests I will never action.
