### ISSUE TITLE
Thousand Arms (USA) (Disc 1) missing speech and character keeps walking

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#123]
missing speech and your characters just keeps walking and the NPC characters never show up to continue the game
![thousand](https://user-images.githubusercontent.com/2696404/77055769-739c5b00-6a0c-11ea-9ddc-c9a79fda0dfd.PNG)

**Comment by stenzek** [comment]
Seems to be relying on a SPU interrupt triggering to progress, which for some reason isn't firing.

**Comment by stenzek** [comment]
Should be fixed on latest master.

**Comment by benderscruffy** [comment]
fixed
