### ISSUE TITLE
Impossible to toggle groups of cheats

### ISSUE THREAD

**Issue by tycooko** [stenzek/duckstation#1230]
In the macOS version, when ticking the box of a group of cheats inside the Cheat Manager, the app graphically confirms the action, marking the box as selected, but nothing actually happens. The cheats within the group don't seem selected in the Cheat Manager and they have no effect in the game (but they do if one ticks their boxes individually).
<img width="855" alt="Screen Shot 2020-12-15 at 18 57 36" src="https://user-images.githubusercontent.com/75950926/102253282-69f64400-3f07-11eb-86ac-46b0dc148534.png">

**Comment by ThanoS-max** [comment]
Assign a particular key for toggling cheats and that will open a menu inside the game, and then you can select multiple toggle cheats at the same time.

**Comment by tycooko** [comment]
I went into "Hotkey Settings" and tried with several keys (Q, C, etc.) with games that already had cheats saved.
At least in the macOS version, nothing happens. The menu inside the game doesn't appear.

**Comment by tycooko** [comment]
> Assign a particular key for toggling cheats and that will open a menu inside the game, and then you can select multiple toggle cheats at the same time.
I went into "Hotkey Settings" and tried with several keys (Q, C, etc.) with games that already had cheats saved.
At least in the macOS version, nothing happens. The menu inside the game doesn't appear.

**Comment by ThanoS-max** [comment]
Try assigning any F keys(F1, F2 , etc.).

**Comment by tycooko** [comment]
Just tried with Suikoden, Metal Gear Solid and Final Fantasy VIII. Still nothing, I'm afraid. :(

**Comment by stenzek** [comment]
Fixed in beta release - https://github.com/stenzek/duckstation/commit/9384f3a8e94b8481f775ce3289c1ce6d2843f04d.
