### ISSUE TITLE
Can you make a playstation 2 emulator too?? because ps 1 is very old and dont have very good games!

### ISSUE THREAD

**Issue by fisforfaheem** [stenzek/duckstation#1231]
it would mena a lot

**Comment by Cibomatto2002** [comment]
are you for real ps1 has some really good games on it. there is already a ps2 emulator made.

**Comment by tycooko** [comment]
*is in the channel dedicated to a PS1 emulator, visited by PS1 fans*
*insults the PS1*

Seems legit.

**Comment by Tiberius1437** [comment]
I'd love if that happened but I think a PS2 emulator would be too much for a solo developer. Not to mention you'd need a ton of testers since the PS2 has such a massive library.

**Comment by PavelDurov1488** [comment]
Haha awesome

**Comment by stenzek** [comment]
Sorry, not in the project scope.

PS2 is also much too complex for a single person in a reasonable amount of time.

**Comment by fisforfaheem** [comment]
Thanks  for warm replies ❤️❤️ hope to see someday ps 2 and ps3 eumaltors
for low end devices tooo. Also hope to see an easier of of installing and
setting up of this app as it is for dolphin emu
