### ISSUE TITLE
System wide installation on Linux

### ISSUE THREAD

**Issue by Sunderland93** [stenzek/duckstation#1233]
Hello. I try to build Duckstation for Debian and Ubuntu (PPA repo), but Cmake script ignoring `-DCMAKE_INSTALL_PREFIX=/usr` option, and the files remain in the directory `obj-x86_64-unknown/bin`. If I manualy move bin/duckstation-qt to `/usr/bin`, and directories like "translations", "inputprofiles", etc. to `/usr/share/duckstation`, then emulator doesn't detecting them.

**Comment by stenzek** [comment]
Working as intended, it's not meant to be installed in /usr. It looks at paths relative to the executive for things like the compatibility db and shaders.

I suppose supporting system wide installation could be a feature request.

**Comment by stenzek** [comment]
No plans to implement this. I really dislike the idea of splitting data from the program binaries, it makes it impossible to have multiple versions side-by-side, and more annoying to remove.

**Comment by kattjevfel** [comment]
This is the standard for installing applications linux though, are we really supposed to just have to install this as a big lump into /opt or similar?

**Comment by stenzek** [comment]
Yup. Or use the appimage. Like I said, there's good reasons for keeping data and binaries together.
