### ISSUE TITLE
Xbox Series X controller SDL incompatibility

### ISSUE THREAD

**Issue by kaiserwillem** [stenzek/duckstation#1234]
**Game details**
any

**Description of the issue / bug**
when trying to map the d-pad to the xbox series x controller the entire emulator crashes. happens both in the menu when mapping the d-pad and in games when pressing the d-pad in any direction 

**Steps to Reproduce**
press the d-pad in any direction.

**Enhancements information**
happens in the menus as well as in games

**Hardware/software**
Windows 10
AMD Ryzen 1500x
NVidia Geforce GTX 1660

**Emulator version**
0.1-2553-g3ed42977 (master)

**Additional context**
I'm specifically using the controller that came with the Xbox Series X. I didnt try any other controllers so I dont know if this is the same for the standard Xbox One controller.

**Comment by stenzek** [comment]
Works fine with the xbox one controller, I haven't got a series x controller to test yet :)

Does it crash if you set the controller interface to "XInput" instead of "SDL" in general settings?

**Comment by kaiserwillem** [comment]
Just tested that out. Changing to xinput does fix the problem.

**Comment by ggrtk** [comment]
May need to update SDL to 2.0.14 (in prerelease at the moment) for the Xbox Series X controller.

**Comment by stenzek** [comment]
Figured it might have been a SDL incompatibility, thanks for checking. Will build and update SDL some time in the next few days.

**Comment by Bekon241** [comment]
Xbox controller all my life use Xinput not SDL probably MS not change anything in Xseries controller then not need any fix :) Other wey You can use xppader or x360emulator to bind buttons on unsuported controler same change axis if needed and just let work your controler like psx controller or other who is full supported, before next update :)

**Comment by stenzek** [comment]
Updated SDL to 2.0.14 in https://github.com/stenzek/duckstation/commit/8debaa34d9b3d560040c881b651056776e7d3f42 - hopefully this will solve the problem. Otherwise, there's no disadvantage to using xinput.
