### ISSUE TITLE
Graphical glitch in E.T. the Extra-Terrestrial - Interplanetary Mission (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#124]
This glitchy box appears whenever you pick up an item. Happens with all renderers. 

![SLUS-01385_2020-03-19_22-25-54](https://user-images.githubusercontent.com/31968468/77063806-727e2480-6a32-11ea-9168-615ff7c6cc27.png)

**Comment by stenzek** [comment]
Wasn't able to reproduce. Might be https://github.com/stenzek/duckstation/issues/153
