### ISSUE TITLE
[SLUS-01046] Star Wars Episode I Jedi Power Battle (USA)- Music is scratchy/constantly pops.

### ISSUE THREAD

**Issue by RockmanKB** [stenzek/duckstation#1241]
[SLUS-01046] Star Wars Episode I Jedi Power Battle (USA)

**Description of the issue / bug**
Music is scratchy and pops constantly, sound effects are fine. 

**Steps to Reproduce**
Load the game up and listen to the main menu, character select and all other subsequent music.

**Enhancements information**
All enhancements are off.

**Hardware/software**
i7- Tenth Gen
NVIDIA GeForce 1650
Windows 10 64-bit

[GPU Renderer]
Tried all 3, issue is prevalent in each one.

**Emulator version**
0.1-2563-g30472b85 (Master)

**Additional context**
I’ve tried a bunch of different things (changing CPU speed, preloading the image to ram, messing with sound latency, etc), but it doesn’t effect anything. Other games run just fine.

**Comment by stenzek** [comment]
Wonder if this is related to 20 Seiki Striker Retsuden - very strangely encoded XA audio.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/b3edcc58419b147ea770b06e624958e48cc5c45f - should be available for update soon (15mins or so).
