### ISSUE TITLE
Memory card switching

### ISSUE THREAD

**Issue by saintbepis** [stenzek/duckstation#1242]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [it tends to be a nuisance when games only give you the option to only use the memory card on the first slot only.]

**Describe the solution you'd like**
[The solution to this would be to simulate switching the memory cards in the virtual slots so that the second memory card is in the first slot and the first memory card is in the second virtual slot.]

**Describe alternatives you've considered**
[The only other alternative would be to rename card to manually switch the slots but that takes more time than it's worth and another alternative would be to delete saved data but that would be a negative alternative.]

**Additional context**

**Comment by stenzek** [comment]
You could use the memory card manager to move the saves around between cards.

**Comment by saintbepis** [comment]
> You could use the memory card manager (either in duckstation or the bios) to move the saves around between cards.

I didn't realize you could do this, thank you.

**Comment by Ninaadark18** [comment]
> You could use the memory card manager (either in duckstation or the bios) to move the saves around between cards.

Could you add an option that we can choose mc1 or mc2 along with the auto-select by name 
 because you know memory card is 15 blocks of saves that's it, so when it's full we need to change to another one so I don't use a second memory card so I think I can choose another memory card by my own select then make it mc1 that's great
And thanks

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/57712d141deda364faad86043a5d398f380de2ab
