### ISSUE TITLE
Formula 1 Crash After Boot

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#1245]
**Game details**
Formula 1 (USA) (Rev 1) | SCUS-94353, US

**Description of the issue / bug**
As soon as the loading screen passes 
![formula 1](https://user-images.githubusercontent.com/43047877/102525140-a1d0c900-4078-11eb-9e36-629c64c04b4c.png)

Following error occurs:
![formula 1 2](https://user-images.githubusercontent.com/43047877/102525189-ae552180-4078-11eb-9397-afb468f64305.png)

**Steps to Reproduce**
Run the game.

**Enhancements information**
Emulator on vanilla state.

**Hardware/software**
Win 10, Ryzen 5 3600, 32Gb, RX580 8Gb

GPU Renderer - D3D11/OpenGL/Vulkan

**Emulator version**
Latest - 0.1-2598-g9e198706

**Additional context**
Happens in any CPU emulation mode: 
Inteperter, Cached or Recompiler.

**Comment by Shideravan** [comment]
I can confirm the issue for the game following the hashes below:
![image](https://user-images.githubusercontent.com/12163923/102663519-c6ec3700-415f-11eb-896a-9dd159b5f94c.png)

Although, the one with the following hases is working properly:
![image](https://user-images.githubusercontent.com/12163923/102663605-f00cc780-415f-11eb-8461-80b243d63488.png)
![image](https://user-images.githubusercontent.com/12163923/102663633-0024a700-4160-11eb-9a84-86bd38444190.png)

**Comment by Shideravan** [comment]
I can confirm the issue for the game following the hashes below:
![image](https://user-images.githubusercontent.com/12163923/102663741-319d7280-4160-11eb-938d-128d25da6643.png)


Although, the one with the following hases is working properly:
![image](https://user-images.githubusercontent.com/12163923/102663605-f00cc780-415f-11eb-8461-80b243d63488.png)
![image](https://user-images.githubusercontent.com/12163923/102663633-0024a700-4160-11eb-9a84-86bd38444190.png)

**Comment by Nucleoprotein** [comment]
This issue is already fixed in master

**Comment by andercard0** [comment]
> This issue is already fixed in https://github.com/stenzek/duckstation/commit/7c7145d1c5a04a87c3f0b0d759bd4cf839bf353d

Cool. But is not yet live so as soon as it be I'll replay and close it! :)

**Comment by stenzek** [comment]
Fixed by https://github.com/stenzek/duckstation/commit/7c7145d1c5a04a87c3f0b0d759bd4cf839bf353d
