### ISSUE TITLE
[Feature request] DInput vibration

### ISSUE THREAD

**Issue by Ever17lab** [stenzek/duckstation#1246]
Hey. I dont know, maybe vibration works with Dinput, but it does not work with my gamepad VID_0079&PID_0006

How it can helps... Epsxe (or pcsxr-like emuls) are old and works DInput vibration

You have stand-alone emulator and libretro core, but RetroArch does not have DInput vibration. So, if your program makes it possible, it will be best replace for epsxe-like emulator for supported systems

**Comment by stenzek** [comment]
I don't really want to write a DInput wrapper, since it's a long deprecated API. I'd think SDL would've exposed vibration though.

If you enable the system console log and set it to developer, what does it print when plugging in the controller?

**Comment by PavelDurov1488** [comment]
[   90.0847] I/SDLControllerInterface: Controller 1 inserted
[   90.0894] W(OpenGameController): Controller 1 (joystick 1) returned player ID
 -1, which is invalid or in use. Using ID 1 instead.
[   90.0903] I/SDLControllerInterface: Opened controller 1 (instance id 1, playe
r id 1): G-Shark GS-GP702
[   90.0918] W(OpenGameController): Rumble is not supported on 'G-Shark GS-GP702
'
[   90.0925] I/ControllerInterface: Host controller 1 connected, updating input
map
[   90.0939] I/SDLControllerInterface: Controller 0 deadzone size set to 0.25000
0

Yeah, you can write your program as you want, just... If something is old, it does not mean that it does not work. Maybe DInput is deprecated from developers side, but these controllers are still in production.

As another example, it's not so deprecated... As I know, Steam uses rumble in any type of controller. If Steam is N1 platform for games and supports DInput, it means that a lot of games support it.

From another side, if compare DuckStation with epsxe-like emulators, system requments are Win10x64+D3D11+Xinput vs WinXPx86+ +OpenGL2+Dinput. I wish your project will be best replace for old emulator, but you can do it when you want :)

**Comment by PavelDurov1488** [comment]
PS: as for me, I downgraded my laptop to Win 8.1, cause there is a lot of bad news about Win10 updates like BSODs, slow down, and you cant disable it. Some people uses Win7 cause oldschool or even WinXP :D 
![image](https://user-images.githubusercontent.com/74456272/102680740-04030880-41f6-11eb-8756-e40e1fa2bb5c.png)

**Comment by stenzek** [comment]
Sounds like it might be an SDL issue then - if you controller does not support XInput, it uses DInput through SDL, like many games do.

DuckStation's also a more accurate emulator than epsxe, so you can't compare the two. But I've heard it's much faster than epsxe on desktop (but not android yet). If you want to use an old system, you'll have to use a different emulator - that's the requirements I've specified for the project to keep the code cleaner and more maintainable.

The oldest system I own is a Broadwell-E Xeon, which won't run Windows 7, let alone anything older, so it's pretty difficult for me to support an OS which I can't even run.

**Comment by PavelDurov1488** [comment]
Steam has its own method to support DInput rumble, so, any Steam game supports DInput rumble
It's just from practice side, if you have good DInput gamepad, there is no much reason to buy XInput gamepad

By the way, there is force feedback driver, with this file DuckStation crashes
![image](https://user-images.githubusercontent.com/74456272/102694116-0139ff00-425a-11eb-9653-b7ef07845f23.png)

In driver utility I can vibrate even without this file... Maybe cause of it uses X86 library
![image](https://user-images.githubusercontent.com/74456272/102694298-0f3c4f80-425b-11eb-939d-b6c962606171.png)

**Comment by Nucleoprotein** [comment]
This is the driver fault it crashes ie. EZFRD64.dll, you can type name in Google and check that many other games/software crashes with this driver.

**Comment by PavelDurov1488** [comment]
Ah... Oh... Hmm...
By the way, pcsxr works with it, as I remember when I used Win10. Need to tune it to new Windows and check

What a strange thing... There is 2020 and for simple hardware there is still epsxe-like emulator solution >.<

**Comment by Margen67** [comment]
Have you tried running DuckStation with Steam or https://github.com/alessandroasm/generic-usb-gamepad-vibration-driver

**Comment by Phantasm90** [comment]
If you're still interested, here's what i did to get rumble on my gamepad:

1. Install the latest version of x360ce https://github.com/x360ce/x360ce
2. Install Microsoft Xbox 360 Accesories (if you don't already have it) then run x360ce as administrator, then go to **Options>Virtual Device** and install **ViGEm Bus**, after that go to **Options>HID Guardian** and install **HID Guardian**
3. Plug in your controller and map everything, for more details read here https://github.com/x360ce/x360ce/wiki/Beta-Testing
4. After you're done mapping your controller go to the **Force Feedback** tab and check the **Enable** box, on the **Effects Type / Implementatio**n choose either **Constant2** or **PeriodicSine2** (the latter works the best for my controller, might be different for yours though)
5. Go to the devices tab and check the **Hide** box, now Duckstation will only detect the virtual controller

And there you go, now you should be able to get vibration on Duckstation, remember to have x360ce open and minimized when your playing, if you're having trouble on testing the different settings of the force feedback tab or you're trying to undo the Hide option, just close x360ce, run it again as administrator and try again

**Comment by stenzek** [comment]
Never going to happen, dinput is a long deprecated API, and awful to work with.
