### ISSUE TITLE
Support loading PS2-size BIOSes

### ISSUE THREAD

**Issue by ggrtk** [stenzek/duckstation#1247]
Filing the feature request from https://github.com/stenzek/duckstation/issues/362#issuecomment-743934419 separately as it's not really related to UX/UI. Self-assigning this as a low priority feature.

**Comment by SA-X0** [comment]
Thank You ggrtk.
Sorry, i just didn't know whether to open Feature Request or on the UI.

**Comment by ggrtk** [comment]
Closing this issue as the feature has been added. The program will now load 4MB PS2 BIOSes and you can also search for them through the BIOS selector in the settings dialog. However, I wouldn't consider these BIOSes formally supported and bugs might occur while using them.
