### ISSUE TITLE
Artifacts on internal resolution scale > 1x ?

### ISSUE THREAD

**Issue by aybe** [stenzek/duckstation#1248]
**Game details**

SIPS-60007 Twisted Metal

**Description of the issue / bug**

You can see some artifacts when internal res. > 1x.

**Hardware/software**

[i7-4770, RX 5600 XT, Win10]
[GPU Renderer - D3D11]

**Emulator version**
0.1-2598-g9e198706

**Additional context**

See the arrow below clown head:

1x

<img width="1920" alt="2020-12-18_01-54-13" src="https://user-images.githubusercontent.com/1537591/102561456-15082880-40d5-11eb-981e-1bc16b887f26.png">

2x

<img width="1920" alt="2020-12-18_01-56-48" src="https://user-images.githubusercontent.com/1537591/102561412-eee28880-40d4-11eb-8211-5ac8d497146b.png">

9x

<img width="1920" alt="2020-12-18_01-57-06" src="https://user-images.githubusercontent.com/1537591/102561411-ee49f200-40d4-11eb-8617-50dcf64942ba.png">

**Comment by stenzek** [comment]
Probably interpolation differences. >1x floors the texture coordinates, 1x rounds.

**Comment by stenzek** [comment]
See https://github.com/stenzek/duckstation/issues/427

**Comment by aybe** [comment]
Ok, posted there, thanks.
