### ISSUE TITLE
Graphical glitches in Animorphs: Shattered Reality

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#125]
There's a rainbow coloured bar at the top of the screen.

![SLUS-01010_2020-03-20_01-53-43](https://user-images.githubusercontent.com/31968468/77082802-b54ef500-6a50-11ea-9461-4a9c876ebae4.png)

The loading screen turns green for some reason.

![SLUS-01010_2020-03-20_01-54-43](https://user-images.githubusercontent.com/31968468/77082913-d57eb400-6a50-11ea-9bd2-7f194da28006.png)

Here's the game being played on original hardware so you can see that neither of these issues are present.

https://www.youtube.com/watch?v=7s73i3bZ2HU

**Comment by HeroponRikiBestest** [comment]
The colored line only shows up if crop is set to none; setting it to only overscan area. The green loading screen is fixed if you start it on software renderer; although even then it still doesn't quite match the loading screen found in that video.

**Comment by stenzek** [comment]
Seems to be related to dithering.

**Comment by stenzek** [comment]
Screen-going-completely-green problem doesn't seem to be an issue anymore.
