### ISSUE TITLE
Please fix .bin don't get added without .cue

### ISSUE THREAD

**Issue by danny19901** [stenzek/duckstation#1250]
I've noticed that if games are just .bin and have no .cue file they don't get added to the game selection although if you choose start game and pick the game that's just .bin without a .cue it works perfectly but would be nice to add it the Qt and add artwork

**Comment by stenzek** [comment]
This is working as intended - if I scanned both .bin and .cue files, you would have duplicates in the game list. Even worse, for multi-track games you'd have every track listed.

You can use https://nielsbuus.dk/pg/psx_cue_maker/ to quickly generate cuesheets for bin files. Alternatively, naming them "iso" or "img" would also work.

**Comment by danny19901** [comment]
In my game folder for instance I have Harry potter.bin & Harry Potter.cue
And it displays it fine as 1 game but 
Digimon.bin without a .cue file doesn't show up at all in the selection of games what I'm trying to say is games that don't have a .cue file just don't get added into the game selection at all 
In my folder I have many games that are .bin & .cue and there not duplicated or anything and display fine but the games that are also in same folder that  are just .bin they don't show at all this is on windows 10 I hope this kind of makes sense specially the games that are just .bin and don't have a .cue file work if you boot from start game then choose it but would be cool if it was added to the bunch of games so could add artwork

I could take pictures if it helps clear it up a bit

**Comment by stenzek** [comment]
Like I said, there's an easy fix - create a cue file for your games which don't have them. Or rename them to iso.

If I included .bin files in the game list, then you would have two entries when there **is** a cuesheet - one for the bin, and one for the cue. That's why I don't include them.
