### ISSUE TITLE
Cheat Manager features

### ISSUE THREAD

**Issue by niko1point0** [stenzek/duckstation#1251]
Feature Request!
- Pointer scanner, for pointers and offsets
- "Browse Memory" to look at all bytes in memory at any given address
- String searches
- Array of Bytes searching

**Comment by stenzek** [comment]
> "Browse Memory" to look at all bytes in memory at any given address

Available in the debugger.

> String searches

Convert the string to ascii, use search in the debugger.

> Array of Bytes searching

Available in the debugger.

**Comment by niko1point0** [comment]
How do I use these features in the debugger?

**Comment by stenzek** [comment]
`Debug` -> `CPU Debugger`. Pause and examine memory. It only updates while paused (like a normal debugger).

If you know what addresses you want to look at, you can add them to the watch list in the cheat manager. Although I think I forgot to hook up the manual add button... :)

**Comment by niko1point0** [comment]
![image](https://user-images.githubusercontent.com/7824443/102570234-eaa67300-40b4-11eb-90da-252c57cb6637.png)
Debug -> CPU Debugger?

**Comment by stenzek** [comment]
Use the Qt frontend.

**Comment by niko1point0** [comment]
Great! Now if only we had a pointer scanner, that would be nice

**Comment by Shideravan** [comment]
Didn't these features already in Tools->Cheat Manager?
![image](https://user-images.githubusercontent.com/12163923/102664342-4d554880-4161-11eb-8202-1d8d51f2e06b.png)

**Comment by niko1point0** [comment]
@Shideravan There is no pointer scanner, or pointermap generation

**Comment by Unicorngoulash** [comment]
PS1 doesn't need pointerscans,the only thing that would do is perhaps lead you to a base address 3 bytes away from what your originally found. It does not work the way as it would with PS1 games, rarely have I encountered a PS1 game being evil enough to use something resembling pointers. 

But we have the find and replace "F4 code type" (Aob finder and injector) to deal with Dynamic memory instead.

```
Resident Evil 3 (Universal Region)

Auto Dodge Zombies (Hold L3)
D5000000 00000200
F4104BD0 00AA7000 <-- sets search range x4

05004234 040062AE <-- scans array ( 4/8 bytes possible)
AAAAAAAA AAAAAAAA <-- Ignores 8/8 byte part (A's)
010DAAAA AAAAAAAA <-- replace first 2 bytes with own ignore the rest
AAAAAAAA AAAAAAAA <-- No need to replace anything all A's
00000000 0000FFFF
D6000000 00000200
F4104BD0 00AA7000
010D4234 040062AE
AAAAAAAA AAAAAAAA
0500AAAA AAAAAAAA
AAAAAAAA AAAAAAAA
``` @niko1point0

**Comment by stenzek** [comment]
Combining with #2179.
