### ISSUE TITLE
Show VRAM broken in Vulkan

### ISSUE THREAD

**Issue by niko1point0** [stenzek/duckstation#1252]
![image](https://user-images.githubusercontent.com/7824443/102568740-183ded00-40b2-11eb-8809-df4097fcf2b0.png)

Does not work in Vulkan, but works fine in OpenGL and DirectX 11

**Comment by stenzek** [comment]
Which driver? It's working fine here.

**Comment by niko1point0** [comment]
GTX 1050 
![image](https://user-images.githubusercontent.com/7824443/102570077-ab782200-40b4-11eb-9444-d55e90a591cb.png)

**Comment by ThanoS-max** [comment]
It's working fine in 1050 as well as 1050ti.

**Comment by niko1point0** [comment]
Are you using the same driver? @ThanoS-max

**Comment by ThanoS-max** [comment]
![settings](https://user-images.githubusercontent.com/71967068/102642233-61aa3d00-4183-11eb-9815-16d325165d63.png)

**Comment by niko1point0** [comment]
Can I have the duckstation settings? I'd like to compare that to mine

**Comment by stenzek** [comment]
Does it work in D3D?

**Comment by niko1point0** [comment]
Yes it works in OpenGL and D3D for me, but not Vulkan @stenzek

**Comment by niko1point0** [comment]
![image](https://user-images.githubusercontent.com/7824443/102841889-c1972280-43d3-11eb-9c2d-986f0a4ec608.png)
I erased everything and redownloaded DuckStation, now suddenly it works. Maybe it was just bad luck
