### ISSUE TITLE
Pixel Differences Between Software and Vulkan

### ISSUE THREAD

**Issue by Awakened0** [stenzek/duckstation#1253]
When comparing screenshots of Beetle PSX software and Duckstation's software and Vulkan renderers, I noticed some pixels are different. Both software renderers are pretty close, with maybe some bits of dithering different between them. The Vulkan renderer differs the most from both though. I'm assuming it's less precise that software. I'm wondering if better precision is possible in the hardware renderer or if it's a sacrifice necessary for speed.

### Screenshot Comparisons:

[Crash Bandicoot (USA)](http://www.framecompare.com/image-compare/screenshotcomparison/KW6ZWNNX) - Crash's shadow has small differences between the software renderers. Lots of pixels in the distance differ in the Vulkan renderer, most notably the pixel in the right ship's eye.

[Crash Bandicoot 2 - Cortex Strikes Back (USA)](http://www.framecompare.com/image-compare/screenshotcomparison/F0MC1NNU) - The circle in the wall to the right of the 21 is interesting here. It's only missing part of it's top in Duckstation's software renderer.

[Crash Bandicoot - Warped (USA)](http://www.framecompare.com/image-compare/screenshotcomparison/KW6ZGNNX) - Software renderers are pretty close again. The white windows of one of the left towers are pretty different in Vulkan.

[Klonoa - Door to Phantomile (USA)](http://www.framecompare.com/image-compare/screenshotcomparison/F0MCMNNU) - Ignore the animated leaves and light shaft. The crease in the wooden floor beneath Klonoa looks different in Vulkan.

[Spyro the Dragon (USA)](http://www.framecompare.com/image-compare/screenshotcomparison/KW6ZPNNX) - Both of Duckstation's renderers have yellow dot dithering in the lighter patches of grass that Beetle's doesn't.

I also noticed that the + on the back of Mega Man's helmet in Mega Man Legends (USA) flickers during the character's idle animation in Vulkan. Wasn't sure if that was also related to pixel precision, but felt like it might be.

Software:
![mml-software](https://user-images.githubusercontent.com/4565863/102581326-534e1980-40ce-11eb-9735-ac4769c8dc16.gif)

Vulkan:
![mml-vulkan](https://user-images.githubusercontent.com/4565863/102581384-6fea5180-40ce-11eb-8153-46b722ee22e6.gif)

Games that are primarily 2D like Little Ralph and Gradius Gaiden looked pretty identical in all renderers.

I have all enhancements off, but enabled "CPU Recompiler ICache" to see if it helped with accuracy. Didn't seem to make a visual difference.

Running the libretro core, 0.1-2598-g9e198706

**Comment by stenzek** [comment]
PC GPUs have different rasterization rules compared to the PS1 GPU, which accounts for some of these differences. Not all GPUs are exactly the same either - the spec has thresholds, not exact requirements. It's "good enough" for most games though.

Probably not fixable without writing a compute shader-based rasterizer, and I'm not convinced it's worthwhile.

The brightness difference is likely just a result of different scaling in the RGB5551->RGB565 conversion.

For comparison, I tend to use Mednafen not Beetle, if I remember correctly, Beetle is years out of date and there's been numerous changes since.

**Comment by Awakened0** [comment]
>  It's "good enough" for most games though.

Yeah, besides the MML flicker, I only noticed differences when comparing screenshots. Still, since most of the time I prefer the native res look, the subtly more accurate image of the software renderer is preferable. The fast forward speed hit on my desktop isn't too big of a deal; still faster than Beetle.

The kinks in the software renderer under libretro (pause flickering, slower launching) were making me lean towards Vulkan. Once those are worked out though, the differences between it and Beetle's don't bother me.

> The brightness difference is likely just a result of different scaling in the RGB5551->RGB565 conversion.

That's another small difference I only noticed in screenshot comparisons.

> For comparison, I tend to use Mednafen not Beetle, if I remember correctly, Beetle is years out of date and there's been numerous changes since.

I probably should have too, but I would have had to unchd my games and redo my cropping and aspect settings so the screenshots matched up. Maybe Duck's software renderer is closer to Mednafen.

Anyways, I don't mind closing this.

**Comment by stenzek** [comment]
> I probably should have too, but I would have had to unchd my games and redo my cropping and aspect settings so the screenshots matched up. Maybe Duck's software renderer is closer to Mednafen.

For what it's worth, the rasterizer is a port from Mednafen (replaced my barycentric rasterizer), but the shading is the original code I wrote, so it's possible there's a difference there, and it may be incorrect.

**Comment by Awakened0** [comment]
Figured I'd mention that I took a screen of Spyro 1 in Mednafen 1.26.1 and it doesn't have the yellow dithering dots in light patches of grass like both renderers in Duckstation do: http://www.framecompare.com/image-compare/screenshotcomparison/KWPG7NNX
