### ISSUE TITLE
in the latest builds on windows in software mode there is only a black screen the games run only in audio 

### ISSUE THREAD

**Issue by ernestoivy** [stenzek/duckstation#1257]
Please read before creating a new issue:

1. Make sure there is not already an open issue for this bug;
2. All enhancements must be off;
3. All advanced options MUST be at their default values;
4. Do not share save state files. Memory Cards are ok;
5. Verify your dump as we can not assist with issues resulting from bad dumps;
6. If playing PAL region software, please check whether or not the game has LibCrypt protection and that if it does, you have a correct SBI file (see https://github.com/stenzek/duckstation#libcrypt-protection-and-sbi-files for more information);
7. Please post your issue report in English as unfortunately this is the only language spoken by the developers. The Discord server has many helpful people if you need help translating.

Remove everything before and including this line before submitting.

**Game details**
[Serial Code, Region]
[i.e SLUS-00404 Ace Combat 2 (USA)]

**Description of the issue / bug**
[Describe what you are seeing and/or hearing during gameplay]

**Steps to reproduce**
[Try to provide as much detail as possible to reproduce the issue]

**Enhancements information**
[Make sure they are all turned off before report]

**Hardware/software**
[If Android, which phone and Android version]
[If desktop, your CPU, graphics card, and operating system]
[GPU Renderer - D3D11/OpenGL/Vulkan]

**Emulator version**
[Shown in the title bar of the emulator]

**Additional context**
[Add any other context about the problem here]

**Comment by Shideravan** [comment]
What game did you tested? As of latest update from automatic updater (0.1-2598-g9e198706) is running fine for me for every game tested in software mode.

**Comment by ernestoivy** [comment]
i run a lot games what i mean latest i say several days ago at this day all builds showing a black screen only audio work in two computers win7 nvidia gtx750ti and win 10 nvidia gtx1060 

sorry my bad english

**Comment by andercard0** [comment]
> i run a lot games what i mean latest i say several days ago at this day all builds showing a black screen only audio work in two computers win7 nvidia gtx750ti and win 10 nvidia gtx1060 
> 
> sorry my bad english

Hi. Thanks for your time in report it but your report does not help at all. First, you should have to filled all the blanks in the template provided here, second, your statement does not explain anything at a too. Cause, i run many games without even mention what issues you facing foes bot help again! So please, edit your issue correctly telling what game, code, describing issues you facing etc!

**Comment by ernestoivy** [comment]
hahaha!!! .i.
