### ISSUE TITLE
macOS: Cccalibrator doesn't have any effect+using any filter generates bad_shader.txt files

### ISSUE THREAD

**Issue by tycooko** [stenzek/duckstation#1259]
1) The Cccalibrator filter doesn't have any effect at all with both OpelGL and Vulkan renderers.
2) Adding any filter (even the ones that work), generates a bad_shader.txt file in the root folder of DuckStation: [bad_shader_1.txt](https://github.com/stenzek/duckstation/files/5718572/bad_shader_1.txt)
3) The buttons "Load Preset" and "Save Preset" seem to be constantly greyed out?

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/7ca0d357cba75be7256bea17ff9b51c023e0d070

**Comment by tycooko** [comment]
So all three issues will be fixed in the near future?

**Comment by tycooko** [comment]
> Should be fixed by [7ca0d35](https://github.com/stenzek/duckstation/commit/7ca0d357cba75be7256bea17ff9b51c023e0d070)

So all three issues will be fixed in the near future?

**Comment by stenzek** [comment]
Presets weren't ever implemented, I might fix that up when I am next working on postprocessing, or remove the buttons.

I didn't write this shader, so no idea how it works or what it's expected to do. The other built-in shaders should work, if they don't, it's possibly a mac-specific issue.

**Comment by tycooko** [comment]
On both my iMac with macOS Big Sur, Version 11.1 (20C69), and my PC with Windows 10 Pro, Version 2004, OS version 19041.685, Cccalibrator triggers the same error message: "Failed to load post processing shader chain."
Beyond that, the filter has literally zero effects on any game (while promising control over luminance, some basic colors, image noise and saturation).
The other built-in shaders work on both Mac and Windows.
