### ISSUE TITLE
Mortal Kombat: Special Forces causes Duckstation to crash entirely 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#126]
BIOS, then this loading screen, then a crash.

![SLUS-00824_2020-03-20_02-41-14](https://user-images.githubusercontent.com/31968468/77085521-8fc3ea80-6a54-11ea-8347-7b20e6e3468b.png)

![Capture](https://user-images.githubusercontent.com/31968468/77085606-aec27c80-6a54-11ea-8b8e-165d9164fd2d.PNG)

**Comment by stenzek** [comment]
Please retry with latest master. I've fixed a crash while investigating a different issue which can happen with oversized fills.

**Comment by kurayami6** [comment]
Fixed. Thanks.
