### ISSUE TITLE
SDL front end doesnt have input configuration??

### ISSUE THREAD

**Issue by Askmewho** [stenzek/duckstation#1267]
leit motive: the sdl frontend works better on some platforms.

**Is your feature request related to a problem? Please describe.**

yes, my controls aren't working on SDL frontend, neither joystick or keyboard

**Describe the solution you'd like**
to include the input configuration inside the SDL frontend GUI

**Comment by stenzek** [comment]
Working as intended - it's basically a nogui frontend without most of the settings. It will be getting removed soon and replaced with one actually named nogui.

Use the  Qt frontend.

**Comment by ImSpecial** [comment]
Please don't remove the SDL version unless the "nogui" version is identical, I much prefer it over the Qt version as is, even with its limited settings, etc. I use the Qt version only when necessary for configuration, but SDL for everything else.

**Comment by stenzek** [comment]
NoGUI will be based on the current SDL interface, but with the ability to navigate it with controllers and such.

**Comment by ImSpecial** [comment]
Good news! Doomsday diverted.
