### ISSUE TITLE
Remove multiple cheat codes.

### ISSUE THREAD

**Issue by ZeroCool933** [stenzek/duckstation#1268]
The cheat list allows you to delete one cheat only at a time and it's a bit annoying to add and delete one at a time, 
It would be nice an option to delete all the codes that are loaded automatically when you open the cheat manager.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/de688615ff2a22f9425523f5388c1f0147dcec83
