### ISSUE TITLE
Loading screen doesn't fade out properly in Floating Runner - Quest for the 7 Crystals (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#127]
Instead of fading out at the end, this loading screen flickers horribly. Only happens with D3D11. 

![SLUS-00231_2020-03-20_03-48-19](https://user-images.githubusercontent.com/31968468/77093020-8770ad00-6a5e-11ea-98cb-be3fc4538e65.png)

**Comment by and468860** [comment]
uses maximum emulation speed

**Comment by and468860** [comment]
uses maximum emulation speed  emulador

**Comment by stenzek** [comment]
Does it also occur in OpenGL? It seems fine here.

**Comment by kurayami6** [comment]
I already said it only happens with D3D11.

**Comment by stenzek** [comment]
I'm collapsing this to https://github.com/stenzek/duckstation/issues/153 as it seems to be the same issue. If it is a different issue and persists with the OpenGL/Software renderers, please re-open.
