### ISSUE TITLE
GUI does not open

### ISSUE THREAD

**Issue by gregpetersde** [stenzek/duckstation#1272]
I downloaded `duckstation-windows-x64-release` yesterday on two Windows 64 PCs (a **laptop** running `Windows 10 64bit Home` and a **desktop** running `Windows 10 64bit Pro`).

On both systems I performed the same steps:

1. unpacked the ZIP file
2. copied the `duckstation-windows-x64-release` to `C:\Users\%USERNAME%\Documents\games\duckstation-windows-x64-release`
3.  double clicked on `duckstation-sdl-x64-ReleaseLTCG.exe`
 
On both system, a `DuckStation` folder has been created at `C:\Users\%USERNAME%\Documents\DuckStation`

However, only on the **laptop** the GUI started; I cannot see any GUI on the **desktop**.

What am I missing? Is there any additional information that I can provide?

The systems are fairly similar. e.g. Bitdefender free edition is running on both of them.

Thanks, Greg

**Comment by stenzek** [comment]
Create a shortcut, and add `-nocontroller` to the end of it (or run with `-nocontroller` on the command line). That will prevent the emulator from initializing SDL, which seems to crash with certain setups. If that works, go into settings and change the controller interface to XInput or None.

**Comment by gregpetersde** [comment]
Great, that worked.

Vest, Greg
