### ISSUE TITLE
Add GLES 2.0 implementation

### ISSUE THREAD

**Issue by mtoensing** [stenzek/duckstation#1273]
**Is your feature request related to a problem? Please describe.**
DuckStation runs slow on Odroid Go Advance in 64 Bit enviroments. Unfortunately², duckstation has no GLES 2.0 implementation (which is pretty weird for a core that claims it's aiming at low-end devices!) and is actually running using a software renderer.

**Describe the solution you'd like**
We still hope duckstation will lower it's GLES requirements to get a full hardware acceleration.

**Describe alternatives you've considered**
No duckstation then. 

**Additional context**
More information in the recalbox forum https://forum.recalbox.com/post/160870

**Comment by stenzek** [comment]
No plans for a GLES2 renderer. It wouldn't be able to achieve the same levels of accuracy, and would be slow.

I own a Go-Advance and have been tailoring several optimizations to it. It supports GLES3.2, but the software renderer ends up faster because of overhead in the Mali driver. It also doesn't help that the driver is several years behind latest.

Are you running retroarch? Without threaded video, it is indeed much too slow to be usable. But that's retroarch's fault, not the core. The NoGUI frontend (not currently in master) runs most games full speed.

**Comment by mtoensing** [comment]
@stenzek 

Thank you for your answer. 

> I own a Go-Advance and have been tailoring several optimizations to it.

Great. What image or distribution do you run on it? I would glady just use that. 

> Are you running retroarch? Without threaded video, it is indeed much too slow to be usable. But that's retroarch's fault, not the core. The NoGUI frontend for duckstation (not currently in master) runs most games full speed.

I tried Recalbox, Batocera, RRVL, EmuELEC. I don't know that is the backend for these but only Recalbox uses Duckstation. 

What should the Recalbox Team currently do? That seems like the most promising project but psx emulation is a real problem. For details see the post about duckstation und why it is slow in Recalbox: https://forum.recalbox.com/post/160870

**Comment by stenzek** [comment]
> Great. What image or distribution do you run on it? I would glady just use that.

Just the stock Ubuntu image. I use it as a development platform.

> What should the Recalbox Team currently do? That seems like the most promising project but psx emulation is a real problem. For details see the post about duckstation und why it is slow in Recalbox: https://forum.recalbox.com/post/160870

I don't really understand what's going on in thread. OGA is a GLES3-capable device, yet you have a staff member asking for GLES2 support?

Anyway, the only way to get somewhat usable performance for DuckStation on the Go Advance through retroarch is to enable threaded rendering. And even then it adds overhead which slows things down occasionally.

My original plan was to write a separate frontend (https://github.com/stenzek/duckstation/tree/go2fast2), but what I ended up doing instead was writing a "NoGUI" frontend which talks to DRM/KMS directly, that way it can be used on other platforms such as the Pi. Most of the work is done here, it just needs controller input hooked up to navigate the menus. Once this is finished, it'll be a better alternative than retroarch on these devices.

**Comment by mtoensing** [comment]
@stenzek 
Thank you for your detailed answer. Since I am just a user of recalbox I copied the relevant parts of your answer to their forum. 

I personally think that we don't need another frontend. Retroarch ist perfect but needs a better UI/UX. EmulationStation is just old and would perhaps disappear if retroarch could close that gap. So, you are on the right track to provice a "nogui" version. 

Keep up the good work and thank you!

**Comment by wn2000** [comment]
@stenzek Very interested in the "NoGUI" frontend that you mentioned. Is it available in the repository?
I have a RK3328 Mali-450 board, which only supports GLES2. If a GLES2 renderer is not in the plan, I'm interested in trying the NoGUI frontend with the software renderer.

**Comment by wn2000** [comment]
OK found the NoGUI branch and was able to build it. But it seems software renderer is not supported yet? I set `Renderer = Software` in `settings.ini` but it still tries to create a GL context and failed:
```
[    0.1347] E(CreateRenderDevice): Failed to create any GL context
[    0.1348] E(ReportError): Failed to create/initialize display render device
[    0.1349] E(Initialize): Failed to create host display
```
Also the **Latest News** section mentioned
> 2020/11/21: OpenGL ES 2.0 host display support added.
> You cannot use the hardware renderer with GLES2, it still requires GLES3, but GLES2 GPUs can now use the software renderer.

How should this be set up for a GLES2 GPU?

**Comment by stenzek** [comment]
It still needs a GL context for presentation to the screen. Try setting `LogLevel = Debug` in the ini, it should say why it didn't get any context.

**Comment by wn2000** [comment]
I set `LogLevel = Debug` but still only got the same 3 lines of error message.
I was launching it inside `/tmp` with
```
./duckstation-nogui -portable
```
as my home directory is read-only on this device.
I did see a `settings.ini` got created along with other directories in the current directory. But modifying `settings.ini` doesn't seem to take any effect.

**Comment by stenzek** [comment]
It was working the last time I was working on the branch, but it's been some time. Will look at it when I eventually get around to working on it again.

**Comment by wn2000** [comment]
Some progress. I did not enable EGL in the last build. After enabling EGL, now I'm getting this:
```
User directory: "/tmp"
arm_release_ver of this libMali is r7p0-00rel0, rk_so_ver is '1', built at '15:29:10', on 'Oct  8 2018'.
[    0.1377] I/GL::ContextEGL: EGL Version: 1.4
[    0.1379] I/GL::ContextEGL: EGL Extensions: EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_EXT_image_dma_buf_import EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_reusable_sync EGL_KHR_fence_sync EGL_KHR_swap_buffers_with_damage EGL_EXT_swap_buffers_with_damage EGL_KHR_lock_surface EGL_KHR_lock_surface2 EGL_EXT_create_context_robustness EGL_ANDROID_blob_cache EGL_KHR_create_context EGL_WL_bind_wayland_display EGL_KHR_partial_update EGL_KHR_create_context_no_error
[    0.1380] W(Initialize): EGL implementation does not support surfaceless contexts, emulating with pbuffers
[    0.1382] D/GL::ContextEGL: Trying version 4.6 (Core)
[    0.1383] E(CreateContext): eglChooseConfig() failed: 12288
[    0.1385] D/GL::ContextEGL: Trying version 4.5 (Core)
[    0.1386] E(CreateContext): eglChooseConfig() failed: 12288
[    0.1387] D/GL::ContextEGL: Trying version 4.4 (Core)
[    0.1388] E(CreateContext): eglChooseConfig() failed: 12288
[    0.1389] D/GL::ContextEGL: Trying version 4.3 (Core)
[    0.1391] E(CreateContext): eglChooseConfig() failed: 12288
[    0.1392] D/GL::ContextEGL: Trying version 4.2 (Core)
[    0.1393] E(CreateContext): eglChooseConfig() failed: 12288
[    0.1395] D/GL::ContextEGL: Trying version 4.1 (Core)
[    0.1396] E(CreateContext): eglChooseConfig() failed: 12288
[    0.1397] D/GL::ContextEGL: Trying version 4.0 (Core)
[    0.1398] E(CreateContext): eglChooseConfig() failed: 12288
[    0.1399] D/GL::ContextEGL: Trying version 3.3 (Core)
[    0.1401] E(CreateContext): eglChooseConfig() failed: 12288
[    0.1402] D/GL::ContextEGL: Trying version 3.2 (Core)
[    0.1403] E(CreateContext): eglChooseConfig() failed: 12288
[    0.1405] D/GL::ContextEGL: Trying version 3.1 (Core)
[    0.1406] E(CreateContext): eglChooseConfig() failed: 12288
[    0.1407] D/GL::ContextEGL: Trying version 3.0 (Core)
[    0.1408] E(CreateContext): eglChooseConfig() failed: 12288
[    0.1410] D/GL::ContextEGL: Trying version 3.2 (ES)
[    0.1411] E(CreateContext): eglChooseConfig() failed: 12292
[    0.1412] D/GL::ContextEGL: Trying version 3.1 (ES)
[    0.1413] E(CreateContext): eglChooseConfig() failed: 12292
[    0.1415] D/GL::ContextEGL: Trying version 3.0 (ES)
[    0.1416] E(CreateContext): eglChooseConfig() failed: 12292
[    0.1417] D/GL::ContextEGL: Trying version 2.0 (ES)
[    0.1423] I/GL::ContextEGL: Got version 2.0 (ES)
[    0.1478] I/GL::Context: Created a OpenGL ES context
[    0.1480] E(Create): Failed to load GLES functions for GLAD
[    0.1487] E(CreateRenderDevice): Failed to create any GL context
[    0.1488] E(ReportError): Failed to create/initialize display render device
[    0.1490] E(Initialize): Failed to create host display
```

**Comment by wn2000** [comment]
Did some printf and found it's failing in glad:
```cxx
int gladLoadGLES2Loader(GLADloadproc load) {
	GLVersion.major = 0; GLVersion.minor = 0;
	// returned null pointer for glGetString
	glGetString = (PFNGLGETSTRINGPROC)load("glGetString");
```
The `load` function is a lambda that uses `eglGetProcAddress`.
I found a similar issue here:
https://github.com/Dav1dde/glad/issues/79#issuecomment-281495944
Maybe the Mali driver has the same issue?

**Comment by stenzek** [comment]
I guess I can modify the loader to search libGLESv2 first. Strange that it works fine on bifrost though (with the blob, on my N2).

**Comment by wn2000** [comment]
Thanks I'll be happy to test anytime.
