### ISSUE TITLE
[SLES-00749] Note, The (Europe) - Game speed is too fast

### ISSUE THREAD

**Issue by Krusher97** [stenzek/duckstation#1275]
**Game details**
SLES-00749 - Note, The (Europe)

**Description of the issue / bug**
The game runs too fast. Very noticeable in the cutscene after you start a new game as it desyncs with the spoken dialogue almost immediately. 

**Steps to reproduce**
 Start a new game and let the cutscene run.

**Enhancements information**
 Default settings

**Hardware/software**
CPU:i5 6500 3.2Ghz
GPU:Nvidia GeForce 750 Ti
OS:Windows 7 Ultimate 64-bit SP1
GPU Renderer - D3D11

**Emulator version**
0.1-2615-g6224d0ab

**Additional context**
Works in mednafen

**Comment by stenzek** [comment]
Probably the same as Crash Bash - vsync timeouts.

**Comment by Krusher97** [comment]
For what its worth, the Japanese version isn't sped up.

**Comment by stenzek** [comment]
Appears to be fixed with https://github.com/stenzek/duckstation/commit/fdc7066ead2196886516c8845af870334722f00d
