### ISSUE TITLE
Dual shock PSX Controller bind need important info,on emulator controller setup page.

### ISSUE THREAD

**Issue by Bekon241** [stenzek/duckstation#1279]
Hi I play fiew games and i see my d-pad not work in analog mode properly.

**Reason:** When i bind controler first time i not look my led from analog OFF or ON
then i bind and in any game my d-pad never work in analog mode.

**Fix:** I check again and i find problem. Before bind analog on PSX DS controller must be on if not d-pad
is recognise like axis-1+1 -0 +0 this is bad. 

If controler is on (led) d-pad is binded corectly as button 11,10,12... look screen.

https://www.mediafire.com/view/3ksp2acpuedseam/duckstation-psx-dual-shock-config.jpg/file

Please add Warning! message in Duck emulator controler setup site about this. Becouse first time i think this is bug, but now all work like charm :)
**Warning! Before you bind psx Dualshock controller please ON Analog mode on psx controller (led on)
If not Your D-pad not will be bind corectly.**
Thanks. Cheers from Poland!

**Comment by ggrtk** [comment]
I'm fairly certain this is behavior that's specific to the controller adapter you mentioned here https://github.com/stenzek/duckstation/issues/64#issuecomment-749058229 that you use, so this is not a problem with the program itself.

**Comment by Bekon241** [comment]
> 
> 
> I'm fairly certain this is behavior that's specific to the controller adapter you mentioned here [#64 (comment)](https://github.com/stenzek/duckstation/issues/64#issuecomment-749058229) that you use, so this is not a problem with the program itse

**Comment by Bekon241** [comment]
> 
> 
> I'm fairly certain this is behavior that's specific to the controller adapter you mentioned here [#64 (comment)](https://github.com/stenzek/duckstation/issues/64#issuecomment-749058229) that you use, so this is not a problem with the program itself.

Ok but meybe d-pad must be as button not axis message will be helpfull for others :) I use Twin USB controler for psx and work awesome meny years :) But if not program problem this is nice :) Info meybe help someone with same problem :) bye then Friend

**Comment by ggrtk** [comment]
There's an open issue #965 for a controller page on the wiki that we could hopefully direct users to for troubleshooting issues like this.

**Comment by stenzek** [comment]
Yeah, this seems like something specific to this controller, and I'd rather not have controller-specific code in the emulator.
