### ISSUE TITLE
Skullmonkeys (USA) missing graphics

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#128]
after you walk past the big skull all the graphics disappear
![monkey](https://user-images.githubusercontent.com/2696404/77146488-2086de80-6ac6-11ea-9041-2b066bd1dad1.PNG)
![monkey1](https://user-images.githubusercontent.com/2696404/77146495-2250a200-6ac6-11ea-9314-63b4ecad74e7.PNG)

**Comment by Zet-sensei** [comment]
The playfield is now rendered layer by layer (with some delay between each) instead of having everything disappeared and only our sprite and the general background.

![Skullmonkeys](https://user-images.githubusercontent.com/52127625/80323070-589de180-8829-11ea-929d-dffa9410fcde.jpg)

**Comment by stenzek** [comment]
Should hopefully be fixed in https://github.com/stenzek/duckstation/commit/304391bd00a305597daa556f6dec5bab56579c08

**Comment by Zet-sensei** [comment]
Fixed.

Should be closed.

**Comment by stenzek** [comment]
Thanks for verifying :)
