### ISSUE TITLE
Add Image Filter duckstation.

### ISSUE THREAD

**Issue by Bekon241** [stenzek/duckstation#1281]
Is any chance to add image filter to that emulator?
Subject is simple. Old Monitor CRT display is little difrent then now all games on old TV looks great even if low resolution.
Now nothing looks same good even if resolution 4k and others setting.

Is any chance to add for emulator filter option like **BLUR**? If someone have Monster Hunter on Wii You can easy look how game looks with blur and without. This is rly nice filter and very smailar to old crt display looks. I dont think so new IPS/LCD/OLED monitor can dispay that image properly without pixel. But if Blur filter will be added, virtual effect added fo image this can be possible rly nice looking. Pixel on CRT screen have a litle glow around thats why psx game looks super nice in new monitor pixel never glow, and this is rly problem. All who play on CRT know what i mean.
This must be possible i think. PS. I know other emulators have meny image filter meybe, implementation not will be super hard.

**Comment by stenzek** [comment]
Postprocessing is supported, any Dolphin shaders should "just work".

I have an update in the works which adds support for custom vertex shaders and buffer scaling which is needed for more complex shaders.

**Comment by Bekon241** [comment]
Nice thanks for info. :) This is great news :)
