### ISSUE TITLE
Smooth fog

### ISSUE THREAD

**Issue by Margen67** [stenzek/duckstation#1282]
**Is your feature request related to a problem? Please describe.**
Fog can look quite blocky in certain games:
  * Jumping Flash!
  * LSD Dream Emulator

**Describe the solution you'd like**
An enhancement to make the fog smooth.

**Describe alternatives you've considered**
Disable fog (might require per-game hacks) and do it with shaders. (Impossible without depth?)

**Additional context**
![](https://cdn.discordapp.com/attachments/695823573830598706/790714526404182056/SCES-00003_2020-12-21_14-56-15.png)
![](https://cdn.discordapp.com/attachments/695823573830598706/790438549358116904/SLPS-01556_2020-12-20_20-40-06.png)

**Comment by stenzek** [comment]
I'm not sure if this would be possible. Fog is applied in the GTE, so it'd require a PGXP-like hack to track fog parameters with vertex data.

You'd also be assuming that fog got processed at the exact same time in the GTE as the projection, which isn't guaranteed.
