### ISSUE TITLE
I wont translate program to Polish language but...

### ISSUE THREAD

**Issue by Bekon241** [stenzek/duckstation#1283]
Hi
Anyone can help me?
I wont know how i can easy wey translate English -> Polish 
l look translation file on github is xml but orginal in translation forlder is *.qm
Can you tell me what tools i can use to create nice **langage duckstation-qt_pl.qm**
Easiest way posibble?
I need only info. about Tools what file i must edit if i wont create 100% translation.
Is all language in 1 file or more?
Little tutorial will be nice :) or tel me code page for that qm file coz in notepad i not see all fonts. :) 
Ah and moust important - i must know i can edit file using normal writing or i must change code page coz polish lang orginali use latin II and code page 852 we have wierd font like ąęśżźćńłó and i must know where i setup keyboard layout in language file other wey probably font not be displayed properly in duck station. Thanks.

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation/wiki/Translating-to-new-languages

XML file is UTF-8, shouldn't need to mess around with code pages.

There is already someone working on a Polish translation, I'd suggest talking to them on Discord in the #translations channel, maybe you can divide the work to save some time :)

**Comment by Bekon241** [comment]
Good to know :) Tumorow after back from work i try contact with him :)
