### ISSUE TITLE
Ingame disc swap UI via hotkeys

### ISSUE THREAD

**Issue by Bekon241** [stenzek/duckstation#1286]
I create project UI for this :)
Then probably write more is uselles...

Look screen. Simple as pig tail 😄
![CD Swap](https://www.mediafire.com/convkey/36e3/p579lhv9q3gr5mt6g.jpg)

**Comment by stenzek** [comment]
I'm planning on adding a UI for disc swapping similar to save states, but don't see the value in adding hotkeys for specific discs. Disc swapping is pretty infrequent.

**Comment by Bekon241** [comment]
This is only idea :) You can change system :) but some games can start from disc 2 like Xenogears  :) Hotkey is not good idea probably coz i think same like you better will be UI like in psp and system from it :) You can press select and just change cd image like on screen here :)

This work rly great after convert PSX to PBP file You press home button on PSP and you have UI with This :)
https://youtu.be/S7Zfa8K7ALw?t=445

**Comment by stenzek** [comment]
Try the disc swapping UI after I implement it. My plan would be to have a "select disc" and "swap disc" hotkey, so you would press "select discs" to highlight the disc you want, and then another hotkey to switch to it. Like the save state selector, except with discs instead of save states :)

**Comment by Bekon241** [comment]
Yes good choice You can also try menu like this and only 1 shortcut to open menu.
1. disc 1
2. disc 2
3. disc 2
And just use D-pad UP/Down
press X aplly then UI auto close.
😄

**Comment by stenzek** [comment]
Forgot to update when I added the fullscreen UI - disc swapping can be achieved easily with a controller though m3u or manual file selection:

![image](https://user-images.githubusercontent.com/11288319/112710910-42ecdc80-8f10-11eb-936b-5fe1d565e35a.png)

**Comment by Blackbird88** [comment]
Is the pause on disc change intentional? It's really annoying as Resume in the quick menu doesn't actually resume the game

**Comment by stenzek** [comment]
It should, if the setting is enabled. Will check.

**Comment by stenzek** [comment]
Unpausing when selecting the disc or resume game is working fine here. (With the pause on menu option enabled).

**Comment by Blackbird88** [comment]
I apologize, it must have been fixed recently, but before that it wouldn't resume the game after switching disc.

**Comment by stenzek** [comment]
Were you using a playlist? Yeah, it was missing there, I also fixed that at the same time as moving everything over to multi-disc images.

**Comment by Blackbird88** [comment]
Oh yeah I was using M3U playlist so that was it :D
