### ISSUE TITLE
Puzzle pieces are transparent in Easter Bunny's Big Day

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#129]
Duckstation

![SLUS-01551_2020-03-20_21-49-14](https://user-images.githubusercontent.com/31968468/77157033-b2a5db80-6af4-11ea-9413-818b33fd859e.png)

Beetle PSX

![Easter Bunny's Big Day (USA)-200320-214115](https://user-images.githubusercontent.com/31968468/77157084-c3565180-6af4-11ea-9e2a-4c667f9279f7.png)

**Comment by kurayami6** [comment]
There also seems to be something strange going on with renderers. Not sure if it's only with this game.

I start the game with D3D11 and the puzzle pieces are broken. 

![Capture2](https://user-images.githubusercontent.com/31968468/77157667-eaf9e980-6af5-11ea-88a4-0cc0872c6fd3.PNG)

I try switching to OpenGL and it doesn't make a difference

![Capture](https://user-images.githubusercontent.com/31968468/77157701-fcdb8c80-6af5-11ea-9cdb-2d5564bde9d9.PNG)

I then try resetting the emulator with OpenGL as the renderer and it fixes the puzzle pieces. So for some reason the switch to OpenGL isn't being registered until I reset the emulator. 

![Capture3](https://user-images.githubusercontent.com/31968468/77157768-1da3e200-6af6-11ea-9240-0b1ba4edcf9d.PNG)

**Comment by stenzek** [comment]
The switch does happen immediately, however to do so it saves the state, shuts down the emulator core, restarts it with the new renderer, and loads the state. So it's possible you're seeing a side-effect of that.

**Comment by stenzek** [comment]
I'm collapsing this to https://github.com/stenzek/duckstation/issues/153 as it seems to be the same issue. If it is a different issue and persists with the OpenGL/Software renderers, please re-open.
