### ISSUE TITLE
Xenogears freezing in a cutscene (real time 3D cutscene)

### ISSUE THREAD

**Issue by funregis** [stenzek/duckstation#1290]
Hi ,

Later in the game Xenogears ( cd1), The game freeze on a 3D cutscene , I've tried many settings , nothing working, here is the save state just before the cutscene

Can you see why if you have some time please?

**Comment by stenzek** [comment]
Please don't post save states - they contain copyrighted content. Post a memory card instead.

Have you tried without enhancements?

**Comment by funregis** [comment]
ok sorry for the state, I don't have a standard save (memory card), I only use save state. Yes I have disable all the enhancement. But I have foud a memory card save on gamefaqs. com just after the freeze, so it's ok

**Comment by stenzek** [comment]
Can't seem to see this memory card anywhere?

**Comment by funregis** [comment]
https://gamefaqs.gamespot.com/community/Duke_Darkwood

**Comment by forever8938** [comment]
I have the same issue on Macbook Pro 2015. Windows PC doesn't have this issue.

**Comment by Nucleoprotein** [comment]
@funregis 
But Sten needs memory card before the freeze fro debug...
Can you load save stare then save to memorycard and send it?

**Comment by funregis** [comment]
sorry it's not possible,  I had only saved just before the freeze, I hadn't saved on memory card

**Comment by forever8938** [comment]
BTW I see this issue in the intro movie, video freeze in 5 seconds while audio keeps going. However, on Windows PC I don't see this issue.

**Comment by stenzek** [comment]
Will need clear instructions on how to reproduce this freeze to investigate any further.
