### ISSUE TITLE
[Feature Request] Double clicking screen to toggle between Fullscreen/Windowed

### ISSUE THREAD

**Issue by ImSpecial** [stenzek/duckstation#1291]
Pretty simple request here, could double clicking the window with the mouse toggle between fullscreen/windowed, I know there's already an option for a hotkey to do fullscreen, default Alt+Return, but that doesn't feel "natural" to use IMO. 

Thanks for your consideration.

**Comment by dftf-stu** [comment]
Not sure why this was down-voted... double-clicking to enter or exit full-screen mode is an _extremely common_ convention.  Just look at any video-player app, such as Windows Media Player, VLC, Media Player Classic, iTunes and so-on: they all use double-click to go full-screen, and when in it, to exit.

It would be a simple thing to add to _DuckStation_ I would have thought?

**Comment by stenzek** [comment]
Not planning on implementing this, the current input system has no way to differentiate between a doubleclick for toggling fullscreen, or clicking for guncon buttons.

Using ALT+ENTER is also very standard and default in duckstation.

**Comment by ImSpecial** [comment]
Can you not just make a checkbox option or similar to enable a "Doubleclick for toggling but disable Guncon buttons" options?
