### ISSUE TITLE
[Feature Request] Alternative Turbo (Fast Forward) Speeds

### ISSUE THREAD

**Issue by ImSpecial** [stenzek/duckstation#1292]
Similar to how PPSSPP does it: https://i.imgur.com/rsZQjMF.png

Currently we have one setting for the Fast Forward Speed, Unlimited, 200%, 400%, etc.

What I'd like to see is to have some alternative speed options, two or three would be great, that could also be re-bindable to keys presses, etc. My use case would be something like; holding down TAB for unlimited, L3 clicks or Shift+1 for 200% toggle, R3 clicks or Shift+2 for 400% toggle. (Hope you know what I mean here.) 

I play a lot of RPG's, this helps get rid of the tedium, and even though I love "Unlimited", you can't really play and react at 1300% speeds. :P

Thanks for your consideration.

**Comment by stenzek** [comment]
My concern here would be adding even more options to an already rather full settings page.

**Comment by ImSpecial** [comment]
https://i.imgur.com/eiAMYKm.png
https://i.imgur.com/L4kZ1wM.png

Plenty of space my man, and scroll bars have no limits. :)

I think we have a long ways to go before "too many options" becomes a "choice paralysis" problem for the user, and then there's the fact that DuckStation is all bout features and enchantments too, who doesn't want more, and more, and more! This is all IMO of course, I'm also slightly biased ( :P ) here as it's something I want added, but I honestly don't see it as much of a problem either.

**Comment by stenzek** [comment]
Not so much space in the beta version (due to the update channel switcher, will be in stable soon).

![image](https://user-images.githubusercontent.com/11288319/102965687-15bc1700-453a-11eb-9c66-e120db8ee2c7.png)

At 100% DPI I think that'd be around 750 pixels high, which is really pushing the limits - the last time I had the settings window at 800 pixels high everyone with 768p/800p displays complained :(

**Comment by ImSpecial** [comment]
Damn, can't really argue with that, that does look rather cramped. More side categories, tabs, a scroll bar? I'm not sure what the best solution would be for you, but you'll probably have to do one of these sooner or later as limiting features based on a single window is a bit silly. Hopefully you can find a solution that works. :)

**Comment by Bekon241** [comment]
> 
> 
> Similar to how PPSSPP does it: https://i.imgur.com/rsZQjMF.png
> 
> Currently we have one setting for the Fast Forward Speed, Unlimited, 200%, 400%, etc.
> 
> What I'd like to see is to have some alternative speed options, two or three would be great, that could also be re-bindable to keys presses, etc. My use case would be something like; holding down TAB for unlimited, L3 clicks or Shift+1 for 200% toggle, R3 clicks or Shift+2 for 400% toggle. (Hope you know what I mean here.)
> 
> I play a lot of RPG's, this helps get rid of the tedium, and even though I love "Unlimited", you can't really play and react at 1300% speeds. :P
> 
> Thanks for your consideration.

Hi i think now is ok You can bind key like **shift+space** and work like toggle.
I Think about bind keys like this for controller. Reason is simple if i play i only speedup loading time or VIDEO in game i use psd dualshock contorller. If im far from my desk and play i not wont ude keyboard for this. I wont bind pab key as combo bind for psx controller when **button pressed** or **toggle.** Example "when button **pressed R2+L2+ 🔲 **. That will be nice coz i can use only  🎮 for play ald skip loading. Great program is xppader function in that app can let me bind 8x 16 buttons on psx controller i play TERA game from pc on psx controler when wos released and not support any controler yet. Function like autofire can be also usefull if you like play some games like River Ride or Musihimesama :) If i write that much i wont ask about 1 more usefull function, can You upgrade full screen option for check box  ✅ stey alweys on top. Becouse stupid windows 10 somtimes show low space on drive or other shity message in trey, Thanks :)

**Comment by Dave-Buuns** [comment]
Oh wow, I came to request this exact thing, I hope you can add this feature Mr. DuckStation dev. It is such a huge QoL thing for me.

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/54f55633214b8e32366b1d8bcdccd7cfc041c70e (preview build).

**Comment by ImSpecial** [comment]
Thanks a ton for adding this, cannot wait to give it a try!

Been meaning to ask you this, do you have a patreon or similar for this project? I wouldn't mind funding a small coffee fund for all the work you've done on this, the least I can do for the tons of enjoyment I've been getting by revisiting all my old childhood classics in DuckStation.

**Comment by stenzek** [comment]
Nope, it's just a fun side project for me. I prefer not to involve money because then people have too high expectations, and there's the issue of distributing it to other contributors as well.

**Comment by ImSpecial** [comment]
Fair enough. Well, I hope you keep having fun doing your fun side project. 👍
