### ISSUE TITLE
[Feature request] Separate filtering options for textures and 2D sprites

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [stenzek/duckstation#1293]
**Describe the feature you'd like**
Correct me if I'm wrong, but I don't see an option to enable filtering while keeping sprites (things like text, menus and HUD) unfiltered. It's either all or nothing.

**Additional context**
Such feature is present in emulators that use gpuPeteOpenGL (ePSXe, PCSX). It would be great to have it in this emulator too.

**Comment by 6lackmag3** [comment]
I would like to ask for opposite - filtering for 2D elements like ui + unfiltered 3D. It presents in Beetle PSX as 'adaptive smoothing' and works great for games with prerendered backgrounds like RE.

**Comment by PavelDurov1488** [comment]
Bilinear filtering is not so good thing as fullscreen blur https://github.com/stenzek/duckstation/issues/1186

Fullscreen blur for 2D backgrounds looks like bilinear filtering and makes 3D not so pixelizated, smothes dithering (works better than 'true color rendering') as you want and you will not see troubles with edges like https://github.com/stenzek/duckstation/issues/1191

It needs to port Gaussian blur, for example, this file is from retroarch 

[gaussblur.zip](https://github.com/stenzek/duckstation/files/5740420/gaussblur.zip)

**Comment by nbmrjuhneibkr** [comment]
> I would like to ask for opposite - filtering for 2D elements like ui + unfiltered 3D
Separate filtering options for 2D and 3D would implement both this and the original request.

**Comment by Lemoncak3** [comment]
Yes would love to see this feature, when playing RE if you just use the downsampling 2d and uneffecting 3d make the background become blurry.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/34f20798a1b8b191100b3041a501605fc69b5369.
