### ISSUE TITLE
Little Princess - Marl Oukoku no Ningyouhime 2 (Japan) sometimes hangs when starting a new game

### ISSUE THREAD

**Issue by Tiberius1437** [stenzek/duckstation#1296]
I tried it six or seven times and it worked twice so I think it's just random. 

![Capture2](https://user-images.githubusercontent.com/68873449/103035358-41331600-45bb-11eb-82fb-6668e117f38a.PNG)

**Comment by Nucleoprotein** [comment]
It might be DMA problem, check if setting DMA Max Slice Ticks (game properties, compatibility settigs tab) to different value like 100 or 200 solves this:
![image](https://user-images.githubusercontent.com/8019035/103038247-46b63f00-456e-11eb-8212-f73600ba654c.png)

**Comment by Tiberius1437** [comment]
It already is 100 by default but I'll try 200. 

![Capture](https://user-images.githubusercontent.com/68873449/103038717-41cfaa80-45c3-11eb-951a-77443174f114.PNG)

**Comment by Tiberius1437** [comment]
Tried 200, still hangs. I can turn on Vram and see it's stuck on the title screen.

![Capture](https://user-images.githubusercontent.com/68873449/103039328-b35c2880-45c4-11eb-961a-d3747508b7d8.PNG)

**Comment by stenzek** [comment]
I fixed this a while back, will have to check again. Make sure you have apply game settings on.

**Comment by Tiberius1437** [comment]
Yeah that made it work. Are per game hacks really a fix though?

**Comment by stenzek** [comment]
It's not really a "per game hack", the "correct" setting is to reduce the slice ticks globally. I just have the default set higher because it's compatible with most games and provides a performance improvement on low-end devices.

Once I figure out some other optimizations, I'll make the default lower and remove the per-game settings :)
