### ISSUE TITLE
Import cheats from epsxe files

### ISSUE THREAD

**Issue by slothic** [stenzek/duckstation#1298]
```
#Pole position
801D5944 0001
801D5D54 0500
#Stop Timer
8002F864 0000
80046F64 0000
#Simulation Disc\Any Car Can Play Any Circuit 
D00148E0 000C
800148E2 1000
#P1 speedboost Boost R2
D00A9538 2000
800A9CEE 0040
D00A9538 2000
800A9CEA 0040
#P1 Auto-Pilot select+up-down
D01F0C9A FFEE
800A9E3A 0001
D01F0C9A FFBE
800A9E3A 0000
#Press L2 to change tires - Works sometimes, usually only when tires are green
D00A9538 0020
800A9B7A FFFF
D00A9538 0020
800A9bE2 FFFF
D00A9538 0020
800A9C4A FFFF
D00A9538 0020
800A9Cb2 FFFF


```
Example of a cheat file above.

**Comment by PugsyMAME** [comment]
Don't understand what you want here. chtdb.txt is pretty much the same format as epsxe. If you have new cheats not in chtdb.txt please add them and everyone can use them.

There is still work to do with chtdb, the Gran Turismo games for example need a lot of work - there is quite a bit of de-duplication to do and some cheat addresses are just wrong.

If you update cheatdb.txt and don't submit the cheats make sure you keep a safe copy of you chtdb.txt file.

**Comment by slothic** [comment]
They might be similar, but not all users want to go in and add cheats, instead of just importing the file directly that they already messed with. For instance, clicking import in the cheat manager, could just have support for the base epsxe type.

**Comment by ImSpecial** [comment]
Agree with slothic, I have a ton of cheats for the games I've played over the years in ePSXe, and they're mostly all custom tailored to me and my playstyle, little edge cases like item X in slot Y that probably only I would care for, so I have no plans on adding anything to that massive unwieldy cheatdb as it stands. Anything that can get my old codes imported from ePSXe into DuckStation easier is very much desired.

**Comment by Bekon241** [comment]
**Question** i have orginal Action Replay. -> https://archiwum.allegro.pl/oferta/pro-action-replay-psx-ps1-psone-datel-unikat-i8570560874.html like this. And meny codes on it You think is possible convert print screen or photo to rtf file and save all as copy in txt file. Becouse i need 1 year if i must rewrite all again from tv screen.

I look build codes when i setup crt filter for final fantay IX and i know You dont have same code like me. I can play with in TM Beatrix after when You have air ship on CD3 and when YOU use tm manager. Beatrix items or skills can't be changed but after when i use code. I know whole procedure how to use it properly.

**Can i add code like this:** (this is fake now)

#Final Fantasy IX Beatrix in team.
801D5944 0001
801D5D54 0500 
88888888 8866

And how i can write: Message who tell user how to use code properly, how long can be?
#this is usable after you have air ship from Cid on cd3 You must go.... and more...

> I can use just hash # and write long message? or must be only short game tittle? Will be displayed properly if longer?

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/84181e2a1dd2ea71fdf2dcba0caa2203828b13c7

**Comment by stenzek** [comment]
@Bekon241 could be worth posting this query to #cheat-workshop on discord - somebody might be able to help you there.
