### ISSUE TITLE
DuckStation isn't recognizing any BIOS

### ISSUE THREAD

**Issue by effscumbag** [stenzek/duckstation#1299]
**Description of the issue / bug**
[DuckStation won't recognize any BIOS files I try to use. I put them in a folder in the DuckStation directory called "bios" like the guide said. But regardless, when I try to click "Start BIOS" I get a series of "Cannot find NTSC-U BIOS" errors. The settings page doesn't recognize them at all either, and file explorer just says that the BIOS folder is empty, like it's not recognizing them as legitimate BIOS files. But these are the same files that I've used with Mednafen before, so I know they're authentic.]

**Steps to reproduce**
[Not sure exactly how to reproduce the issue. But I'm curious if maybe the files need to be named a certain way to be recognized? The guide isn't very clear on how to set up BIOS files.]

**Enhancements information**
[Not using any enhancements, I'm basically running DuckStation right out of the box.]

**Hardware/software**
[Intel Core i7 10th Gen, GeForce GTX 1660 SUPER, and Windows 10]

**Emulator version**
[DuckStation 0.1-2632-g14c227a8 (stable)]

**Additional context**
[I feel like the answer to this problem is likely really obvious and I'm just missing it cuz I'm stupid, but I can't find any other info about this problem in the guide or in other bug reports so this is a last ditch effort to figure out what I'm doing wrong.]

**Comment by stenzek** [comment]
Make sure the path in red here is set to the directory containing your BIOS dumps:

![image](https://user-images.githubusercontent.com/11288319/103083367-fc919400-4627-11eb-95b6-985f5857904d.png)

**Comment by effscumbag** [comment]
Okay, so I was an idiot lol. I went back to check the BIOS directory it had chosen and I didn't notice that it had defaulted to a non-existent BIOS file on the C drive where I wasn't even keeping the main DuckStation directory. I switched to the actual directory and now it's working. Thank you and sorry for wasting your time lmao

**Comment by stenzek** [comment]
For what it's worth, it _should_ default to the bios subdirectory of the user directory, but the absolute vs relative paths aren't clear here. Something I need to improve :)
