### ISSUE TITLE
(Audio Bug) Legend of Mana (USA)

### ISSUE THREAD

**Issue by Abrahambrazil** [stenzek/duckstation#1300]
At first, I wanna say that this emulator is the best PSX emulator for Android.
Well, I'm using Duckstation 0.1-2632 (All the settings of the emulator are as DEFAULT) on my Xiaomi Mi Mix 2 with Android 10 and the games that I tested are running perfectly. I played Crash Bandicoot (USA) and CTR: Crash Team Racing (USA) and they are running like I'm using a console. However, the audio of Legend of Mana (USA) crashes after loading the game from memory card. Is it possible to fix this in the next update?
Thank you for the great emulator. You are making history. :) 

Steps to see the bug occurs:
Load the game up from the memory card and listen to the song that crashes when the character wakes up. 
My memory card with the save of the game: https://drive.google.com/file/d/14VJ2L5M_zpAHNUfjrSgxK-qdkImNljUU/view

**Comment by stenzek** [comment]
I guess this might be specific to ARM - loading the save on desktop and exiting the house seems fine.. unless I'm not doing the right thing here.

**Comment by Abrahambrazil** [comment]
> I guess this might be specific to ARM - loading the save on desktop and exiting the house seems fine.. unless I'm not doing the right thing here.

I agree, I think this bug only happens if you're running the emulator on a phone.

**Comment by vanfanel** [comment]
I would like to hint that, in my experience, ARM-exclusive bugs in C programs tend to be due to char being signed by default on ARM vs unsigned on X86 (maybe it was the opposite?)

**Comment by stenzek** [comment]
Seems fine on my phone. Should I be doing something after loading the save?

**Comment by Abrahambrazil** [comment]
> Seems fine on my phone. Should I be doing something after loading the save?
Well, here the bug happens right after the character wakes up, the sound crashes for about 4 seconds and then it comes back. It is crazy that sometimes this bug doesn't occur, but it happens 99% of the times.

**Comment by Abrahambrazil** [comment]
I played the game today with the latest build and the bug is still happening. :(

**Comment by stenzek** [comment]
Still unable to reproduce it. Maybe record a video (and include the speed OSD display).

**Comment by Abrahambrazil** [comment]
> Still unable to reproduce it. Maybe record a video (and include the speed OSD display).

I recorded the video, but the mic of the phone didn't capture the sound bug as loud as it is. It happens at 00:53. I tested the game today using the latest update and the rest of the game is running perfectly, the sound bug only happens when I load the game up. :(
https://streamable.com/bglzas

**Comment by stenzek** [comment]
I'm still confused, sorry. Are you saying the game should continue to play the background music while it's loading? Because most games don't play audio while loading.

**Comment by Abrahambrazil** [comment]
> I'm still confused, sorry. Are you saying the game should continue to play the background music while it's loading? Because most games don't play audio while loading.

No, I'm not. I'm saying that the audio crashes (it makes a noise) for about 3 seconds after the loading screen when the character appears in the bedroom. I know that this audio bug isn't a big deal. I'm just tying to help by pointing out bugs.

**Comment by stenzek** [comment]
Notice how the speed drops below 100% - that's why you're hearing a blip in the audio.

Are you using a CHD image by any chance? It could be decompression overhead, or your phone switching power states, plenty of possibilities.

**Comment by Abrahambrazil** [comment]
> Notice how the speed drops below 100% - that's why you're hearing a blip in the audio.
> 
> Are you using a CHD image by any chance? It could be decompression overhead, or your phone switching power states, plenty of possibilities.

But I'm using a bin/cue image.

**Comment by stenzek** [comment]
chd only affects decompression overhead. Power states could still be the issue, as it does not occur on the desktop version, and the fact that it doesn't happen consistently makes this more likely.

Anyway, I'll profile what it's doing on my AArch64 SBC and see if it shows up there - profiling on android itself doesn't work very well.

But overall it's a very minor issue, a tiny blip for a split second when loading for the first time.

**Comment by Abrahambrazil** [comment]
> chd only affects decompression overhead. Power states could still be the issue, as it does not occur on the desktop version, and the fact that it doesn't happen consistently makes this more likely.
> 
> Anyway, I'll profile what it's doing on my AArch64 SBC and see if it shows up there - profiling on android itself doesn't work very well.
> 
> But overall it's a very minor issue, a tiny blip for a split second when loading for the first time.

True. It's a minor issue and I'm sure it'll be fixed in future updates. :)

**Comment by stenzek** [comment]
Likely slowdown/frame time spikes on Android, the frame pacing changes may make it less noticable.
