### ISSUE TITLE
Missing Translations... (fr)

### ISSUE THREAD

**Issue by Foul** [stenzek/duckstation#1305]
Pause on Focus Loss --> Pause sur la Perte de Focus
Hide Cursor In Fullscreen --> Cacher le Curseur en Plein Ecran

Speed Control --> Contrôle de la Vitesse
Emulation Speed --> Vitesse de l’Emulation
Fast Forward Speed --> Vitesse de l'Avance Rapide
Unlimited --> Illimité

Frame Step : Pas de la Trame

Force Pop'n Controler Mode : Forcer le Mode Contrôleur Pop'n

Fullscreen Mode : Mode Plein Ecran

Threaded Rendering --> 

Widescreen Hack : Hack Ecran Large
...

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/5ed194e6a4b74b392248f02dce1666c871c2df74

These are pretty straightforward to update - see https://github.com/stenzek/duckstation/wiki/Translating-to-new-languages
