### ISSUE TITLE
Memory Card Editor corrupts Suikoden 2 save

### ISSUE THREAD

**Issue by tycooko** [stenzek/duckstation#1309]
When you use the Memory Card Editor to transfer a Suikoden 2 save from any memory card to any memory card, the M.C.E. corrupts the new, transferred, save (not the original one) and makes it look as if the game is at another point. 
In particular, the protagonist's castle is at night instead of being during the day, almost no one is around (in fact, if you check, you'll discover you have recruited just a few of the 108 Stars of Destiny, as opposed to the original save having all side characters unlocked), guards at almost every door prevent you from going outside and certain details in the castle seem to not have been unlocked yet (the elevator, for instance).
The following pictures are from the same ROM and the same save (thus, supposedly, the same point in the game). Only: on the left, there's the already transferred save and, on the right, the original one.

<img width="2103" alt="1" src="https://user-images.githubusercontent.com/75950926/103143765-3ee8cd00-471d-11eb-84c9-627764c0361c.png">
<img width="2098" alt="2" src="https://user-images.githubusercontent.com/75950926/103143766-43ad8100-471d-11eb-88cc-9b3af8a6b6fa.png">
<img width="2102" alt="3" src="https://user-images.githubusercontent.com/75950926/103143767-44deae00-471d-11eb-952d-0b344a43f31f.png">

What you need to follow and check this: a ROM for Suikoden 2 (I've tried this - and unfortunately was able to reproduce it - with both the NTSC ROM as well as the PAL ROM) and a working game save of the correct region. 
I've used the 14th file from this page, "From CFerrante (11/24/2001; 131KB)": [https://gamefaqs.gamespot.com/ps/198844-suikoden-ii/saves](https://gamefaqs.gamespot.com/ps/198844-suikoden-ii/saves). The save is in .gme format, which DuckStation cannot read, so I converted it with MemcardRex 1.8 (you may choose to convert it to an .mcd or an .mcr file: it will work either way).
Steps to reproduce the problem:
1. In Memory Card Settings, browse and connect the aforementioned file, "from CFerrante (11/24/2001; 131KB)". The save is titled SUIKODEN2-(3) LV64 32:42:59 BASLUS-00958GS2-3 .
2. Start Suikoden 2 and load the save: you will get the correct game (the images on the right, above). The castle will be normally lit, lots of people around, you will be able to go out, etc.
3. Close the game and go to System --> Start BIOS . Copy SUIKODEN2-(3) LV64 32:42:59 BASLUS-00958GS2-3 to the other memory card inside DuckStation.
4. Reboot Suikoden 2, load the file from the other memory card (the one you've just copied it to) and, once again, you will see the game behaving as expected.
5. Close the game one final time and go to the Memory Card Editor. Now, DELETE the most recent save, the one that is the result of the copy operation (NOT the first, original, one), save the modified memory card to make sure the software has really registered this modification and repeat the copying of the original file, but this time with the Memory Card Editor: select the original file; click the arrow button that points in the direction of the desired memory card, thus copying the save; save the memory card. You've basically just done what you did in the BIOS, which worked, but, this time, within the Memory Card Editor.
6. Start Suikoden 2 one last time, making sure you're loading the new, transferred file and not the original one. You'll now have the "bad" game (the images on the left, above).

Some clarification:
1. This happens from any format (that DuckStation can read) to any format. From .mcr to .mcd and the other way around, but also from .mcr to .mcr and from .mcd to .mcd. It happens in the NTSC-region game with NTSC-region saves and in the PAL-region game with PAL-region saves.
2. It doesn't have anything to do with the fact that the save is the third one in the game and this may confuse DuckStation: load the original save (before transferring it; when the game is still correct), save immediately inside the game but to another memory card with no Suikoden 2 saves to have a "first position" save ( SUIKODEN2-(1) ), follow the steps above and you'll be able to reproduce the issue again.
3. Once the save has been corrupted (after the transfer), it's unrecoverable: from then on, any emulator (I've tried with ePSXe and OpenEmu) will load the "bad" game.

For convenience, here are the converted saves that DuckStation can read:
[EndGameLV64.zip](https://github.com/stenzek/duckstation/files/5742566/EndGameLV64.zip).

**Comment by stenzek** [comment]
Many thanks for the detailed write-up, will look into this.

**Comment by tycooko** [comment]
Works perfectly. Thank you very much!
