### ISSUE TITLE
screen games is not right  area51 

### ISSUE THREAD

**Issue by and468860** [stenzek/duckstation#131]
![SLUS-00164_2020-03-20_14-49-04](https://user-images.githubusercontent.com/61087055/77176047-44382d80-6aa2-11ea-9529-8f33c3bdeaae.png)
games  screen  is not right area51 e maximum force

**Comment by stenzek** [comment]
Looks like an MDEC/GPU issue.

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/54abd37daa726dd95ba56a0fb0b5b60a7f493d91
