### ISSUE TITLE
place GLES or GL api option on the cmake solution

### ISSUE THREAD

**Issue by Askmewho** [stenzek/duckstation#1310]
Hi, I have problems right now trying to make it run with GLES 3.0 over panfrost mesa driver and it only works if I force GL 3.3.that being said, forcing 3.3 is like runnnin on software, the gpus is on idle and there is no upscaling option that actually works.  could you had that definition on the cmake txt so we can set GLES or GL, just to be sure if we are utilizing GLES or GL. I cand give you the backtrace if needed, maybe there is some extension failing on panfrost and that's all. thanks!!! great 2021 for Duckstation!!

**Comment by stenzek** [comment]
I really dislike the idea of compile time options for enabling features, it means you have builds specific to devices.

By default DuckStation will prefer desktop GL over GLES. If you set the `PREFER_GLES_CONTEXT` environment variable, it will try creating a GLES context before a GL context. See here: https://github.com/stenzek/duckstation/blob/56fc6940760bf4aedec30defb40d87d197a66758/src/common/gl/context.cpp#L39-L75

Could be worth looking at the backtrace, if it is a driver issue, I'm sure the Mesa people would be interested in fixing it.

**Comment by Askmewho** [comment]
oka @stenzek  thanks! on my testing scaling the resolution doesn't work at all.  why could that happen? the xbrz filter also doesn't actually work, maybe somehow it shif to software render after not working properly with OpenGL acceleration and that's why doesn't affect the experience at all?
