### ISSUE TITLE
FF7 ntsc timing bug in the end of battle

### ISSUE THREAD

**Issue by PavelDurov1488** [stenzek/duckstation#1311]
Hello...
**Game details**
Final Fantasy VII NTSC

**Description of the issue / bug**
Timing bug. In the end of battle. If you win or escape from the battle, you can **hear** that sound became faster and sound tone is higher. When you win or escape, graphic stops rendering for some seconds

**Steps to reproduce**

1. Load memory card file
[SCUS-94163_1.zip](https://github.com/stenzek/duckstation/files/5742606/SCUS-94163_1.zip)
2. Walk a little
3. When battle starts, escape, with L1+R1
You will hear audio/speed glitch now

**Enhancements information**
[Make sure they are all turned off before report]

**Hardware/software**
HD4000, Win8.1

**Emulator version**
Retroarch 1.9.0
![image](https://user-images.githubusercontent.com/74456272/103144530-4f359200-4787-11eb-947c-c366507c171f.png)

**Comment by stenzek** [comment]
Please test in standalone, retroarch screws with timing and I no longer support the core.

**Comment by PavelDurov1488** [comment]
Yeah, its libretro core issue


I updated libretro core to latest and can not hear so big speed improve. Maybe because I'm used to 

I dont know about timing problems in retroarch, at least in FF VII it's hearable when graphic stops to render in the game or something like this. When battle ends, you just see last screen for some seconds
![image](https://user-images.githubusercontent.com/74456272/103144807-5e6b0e80-478c-11eb-971e-89c0dafca45f.png)

**Comment by stenzek** [comment]
Like I said, please test it in the standalone version. I do not use RetroArch and I do not want to have anything to do with that project.

If the issue persists in the standalone version, I can investigate it.

**Comment by stenzek** [comment]
Also for these sorts of issues, console comparisons are important. The delay may be normal and a side-effect of the game having to re-load the scene from disc.

A quick check shows the game starts reading from the disc as soon as the EXP screen shows, so if you mash through the results screen quicker, it will take longer to return to the scene.

**Comment by PavelDurov1488** [comment]
I understand
![image](https://vk.com/sticker/1-9016-128)
Don't worry, its libretro issue-only

**Comment by PavelDurov1488** [comment]
Actually, in my case libretro core works better than standalone version...

**Comment by stenzek** [comment]
If it's only in the libretro core, then I can't do anything about it, sorry. You could ask the RetroArch maintainers but sadly I doubt they care.
