### ISSUE TITLE
Choppy audio

### ISSUE THREAD

**Issue by PavelDurov1488** [stenzek/duckstation#1313]
Ohh... You said that you don't want to have a deal with RetroArch, but at least on my system standalone program gives very choppy sound. Maybe it's  because you use crossplatform solution

I've tried to increase latency to 130ms/5760 frames and change backend, it did not help

Example on YouTube https://youtu.be/V7EF5a0ggro

[settings.zip](https://github.com/stenzek/duckstation/files/5742681/settings.zip)

RetroArch suggest XAudio, by default, for Windows
As alternative, it has OpenAL, as I know, it's crossplatform too

My system is Win 8.1, Core I5-3317U

**Comment by stenzek** [comment]
Try with vsync disabled, and the null audio backend.

**Comment by PavelDurov1488** [comment]
Oh, finally, it works!

**Comment by PavelDurov1488** [comment]
I activated vsync from intel panel, relaunched DS and have no choppy sound

To make true that system requement are 'better than potato', it needs fix for old graphic card https://github.com/stenzek/duckstation/issues/1218

Now... The only way to make D3D11 works correct, it needs Microsoft Basic Render Driver (OGL 3 is not supported on intel hd 4000)

1x resolution, as I see, without any problem, but it does not support upscaling without choppy sound

**Comment by stenzek** [comment]
Yes, using the software driver (WARP/Basic Render Driver) will significantly increase the hardware requirements when upscaling, because it's doing all that work on the CPU instead of the GPU.

I haven't got around to looking into that driver bug yet. Hopefully it happens on Haswell, because that's the oldest GPU I have.

**Comment by PavelDurov1488** [comment]
I hope it helps :)

Now, standalone DS still looses to retroarch core, in my case 

I use shaders, they usually works on GPU

In retroarch, even if core uses software render, it uses D3D11/OpenGL**2** for applying shaders

In stand-alone DuckStation software render+shaders uses CPU, as I see, in my case it's overloaded (base freq is 1.65, turbo boost is 2.6 GHz, now its something strange and to turboboost). D3D11+WARP uses cpu too and overloaded again

Xebra, 'most accurate ps1 emulator' uses OGL2 as i know, btw, but has no native shaders support. Only with reshade injection (it needs ogl3)

Hmm

**Comment by stenzek** [comment]
I think you might be misunderstanding my point about "running on a potato". It means that it'll run without any enhancements on a potato (which may mean using the software renderer), not with enhancements ;)

Nothing's stopping you from using the same config (software renderer + shaders) in standalone. Set the device to your Intel GPU, renderer to software, and apply shaders as normal.

**Comment by PavelDurov1488** [comment]
![image](https://user-images.githubusercontent.com/74456272/103146343-3e474980-47a4-11eb-9820-b5a0d46cc3cf.png)
¯\_(ツ)_/¯ cant choose adaptor

My point is lazyness, I think I can replace my laptop, but dont want until it will not be totally broken

Your point if focused on '**CPU** faster than a potato. CPU is not bottle's neck about emulation of 33 mhz CPU, as I know. Even with my 1.65ghz cpu i keep DS in background mode opened+ds in retroarch with shaders+browsers, total cpu eating is 60-80

Troubles with graphic. For example I have friends with intel i7 laptop, but they are old and intel hd4000

**Comment by stenzek** [comment]
It's probably stuck on WARP. Try setting the renderer to hardware, changing the adapter back to your Intel GPU, and then set the renderer back to software again.

**Comment by PavelDurov1488** [comment]
Ah, okay, you are right, its the best software render+shaders solution again :D

**Comment by PavelDurov1488** [comment]
About enhancements >.>
For example, you have solution like 24bit rendering, dithering remove...
Imho, its's not bit enchancement

For example, I saw very funny old school game review - Captain Bible, in this case dithering looks authentic
![image](https://user-images.githubusercontent.com/74456272/103146672-5ff6ff80-47a9-11eb-9a62-eefaae678e86.png)

If remove it, its not so authentic

Also, 24bit brokes colors. The sky is smoother, but sea is banded

![image](https://user-images.githubusercontent.com/74456272/103147065-a8b0b780-47ad-11eb-92db-f1e79bc9f52e.png)


Blur if soft and very easy to tune, possible to find comromise between original authentic dithering and soft graphic

I dont know how to port blur to DuckStation shader, I'm not a programmer... Maybe later

**Comment by stenzek** [comment]
I have a fix pending for the banding in true colour, will push later.

**Comment by PavelDurov1488** [comment]
¯\_(ツ)_/¯ i never see good dithering removal method in any emulator, don't beelive that its enhancements 
If you cant compare well, you see 'wow, colors are smother now and there is no huge grain'

Except of dithering upscaling

![image](https://user-images.githubusercontent.com/74456272/103152691-f85fa500-47e6-11eb-81b2-d8bd16a552ed.png)
![image](https://user-images.githubusercontent.com/74456272/103152707-1d541800-47e7-11eb-8296-9b4e1f107946.png)

True color sounds like its better, but its worse than image calibration

![image](https://user-images.githubusercontent.com/74456272/103152808-e6cacd00-47e7-11eb-8b53-2213094c4cd3.png)

**Comment by stenzek** [comment]
Try the latest preview build - it includes a fix for smudging of colours in true colour mode.

**Comment by PavelDurov1488** [comment]
(ﾉ>ω<)ﾉ :｡･:*:･ﾟ’★,｡･:*:･ﾟ’☆
(ﾉ>ω<)ﾉ :｡･:*:･ﾟ’★,｡･:*:･ﾟ’☆
(ﾉ>ω<)ﾉ :｡･:*:･ﾟ’★,｡･:*:･ﾟ’☆
It works now!

I mean, Intel HD 4000 color
![image](https://user-images.githubusercontent.com/74456272/103154930-b5f29400-47f7-11eb-820d-0d50e23626d9.png)
![image](https://user-images.githubusercontent.com/74456272/103154934-ba1eb180-47f7-11eb-95bb-6ac0f3bea0eb.png)

True color rendering works cool too (but i prefer dithering+blur)
![image](https://user-images.githubusercontent.com/74456272/103154936-c145bf80-47f7-11eb-87e5-def1e49749f2.png)

![image](https://user-images.githubusercontent.com/74456272/103154977-2ac5ce00-47f8-11eb-9500-e480c4613c63.png)

**Comment by PavelDurov1488** [comment]
Hmm. But, if FF VII works perfectly, Chrono Cross have same bug, with Intel hd4000
True color rendering helps save colors, but it removes dithering. With WARP everything is perfect
Software
![image](https://user-images.githubusercontent.com/74456272/103155227-1f73a200-47fa-11eb-8e86-b685367ca3ec.png)
Hardware with Intel HD4000
![image](https://user-images.githubusercontent.com/74456272/103155240-4a5df600-47fa-11eb-9461-b181ed2184ea.png)
Hardware with Intel HD4000+True color rendering
![image](https://user-images.githubusercontent.com/74456272/103155247-59dd3f00-47fa-11eb-9a02-bc19b38f1a51.png)
