### ISSUE TITLE
Auto-generate serials for games without SYSTEM.CNF

### ISSUE THREAD

**Issue by marcosoutsider** [stenzek/duckstation#1318]
**Game details**
SLPS00006, Nekketsu Oyako (Japan)

**Description of the issue / bug**
You can't use the save state function with this game. When you try, you get this message box: "Can't save per-game state without a running game code.". Tested with the original japanese version and the translated one with the same results. I've tried other games to make sure, and they all seems to work fine. The settings in the emulator was reset before opening this issue report.

**Controller Troubleshoot Report**

**Steps to reproduce**
Just load the ISO and try save state

**Enhancements information**
Everything is at the default value

**Hardware/software**
CPU: Core i7 8700
Graphics: EVGA Geforce RTX 2080
OS: Windows 10 x64 (v2004)
D3D11 (Hardware)

**Emulator version**
DuckStation v0.1-2663-gfd39f09a (dev)

**Additional context**
![image](https://user-images.githubusercontent.com/76620636/103153446-4fc22e80-476f-11eb-9f6c-64318bcc91a8.png)

**Comment by stenzek** [comment]
Happens when games are missing the system.cnf for their executable name. My plan was to hash the images (or executable) in such cases.

**Comment by stenzek** [comment]
In the meantime, you can use the global slots - they don't depend on having a serial.

**Comment by marcosoutsider** [comment]
Ok, thanks. I'm going to use global slots for now.

**Comment by stenzek** [comment]
First part of this is implemented in https://github.com/stenzek/duckstation/commit/6bbb1128b63845eda8632f1c3407a6c44b492147 - still needs a mapping to serial.
