### ISSUE TITLE
Background filtering

### ISSUE THREAD

**Issue by platinaa** [stenzek/duckstation#1319]
Hi stenzek ,

Thanks for your amazing work .

I have a question , in ePSXe , with or without texture filtering , background image always filtering at any resolution , like this

![ePSXe](https://user-images.githubusercontent.com/76620910/103153866-c5111c00-47ce-11eb-95b3-6466165c6bed.jpg)

but in duckstation , background image never filtering if resolution > 1x

![duckstation-qt-x64-ReleaseLTCG-2020-12-26-22-45-50](https://user-images.githubusercontent.com/76620910/103153909-17523d00-47cf-11eb-87a0-7b7893095a8e.jpg)

it's happen in not only background image but also logos image , title image in some games . 

I can use post-processing shade such as ReShade make full screen filtering , but High resolution polygon object will be blur .

Is there any chance of you can look into it ? It's real make some of game look better . 

Thanks you very much !

**Comment by Madxbio97** [comment]
Possible way to solve this (use the same solution from Beetle HW) https://www.youtube.com/watch?v=GdW7YxmGq6k
But I think that, this is complex feature request.

**Comment by platinaa** [comment]
> 
> 
> Possible way to solve this (use the same solution from Beetle HW) https://www.youtube.com/watch?v=GdW7YxmGq6k
> But I think that, this is complex feature request.

Yes, this Adaptive Smoothing looks great~

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/3cb2cd8235df5edfd05b2c7ec10037b5f0bf1001
