### ISSUE TITLE
Graphical glitches in Bubsy 3D

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#132]
These glitches only occur with the D3D11 renderer. 

Whenever Bubsy moves a white square appears behind him

![Capture](https://user-images.githubusercontent.com/31968468/77194865-cc671300-6b34-11ea-8e4c-dddf049e90a5.PNG)

Whenever he picks up an item this happens

![Capture2](https://user-images.githubusercontent.com/31968468/77194943-f4567680-6b34-11ea-933a-7b17ce8e96e8.PNG)

**Comment by stenzek** [comment]
I'm collapsing this to https://github.com/stenzek/duckstation/issues/153 as it seems to be the same issue. If it is a different issue and persists with the OpenGL/Software renderers, please re-open.
