### ISSUE TITLE
Discord rich presence?

### ISSUE THREAD

**Issue by LeoBerserk** [stenzek/duckstation#1321]
I know it's not important but it'd be nice to have it at some point!

Love the emu btw

**Comment by andercard0** [comment]
> I know it's not important but it'd be nice to have it at some point!
> 
> Love the emu btw

Hey, please check 
![image](https://user-images.githubusercontent.com/43047877/103161365-9a6b9700-47bf-11eb-9fd2-ef69377a173c.png)

**Comment by LeoBerserk** [comment]
Welp, I totally did not see it. Thank you so much
