### ISSUE TITLE
[Inquiry] Regarding A35 32bit libretro

### ISSUE THREAD

**Issue by kjhjekwls** [stenzek/duckstation#1324]
Hi,

Thank you so much for working on a great emulator.

I am using retroarch on ARM cortex-A35 with 32bit OS. I really want to run duckstation libretro on my platform.

Even I don't even know if this is possible, but could you provide libretro.so library binary that can run on ARM cortex-A35 with 32bit OS also?

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation/releases/download/latest/duckstation_libretro_linux_armv7.so.zip or https://github.com/stenzek/duckstation/releases/download/latest/duckstation_libretro_android_armv7.so.zip

Keep in mind the libretro core is no longer supported, and you'll likely find retroarch to have too much overhead for a cortex a35. I'll be releasing a nogui version in the future which will be measurably faster.
