### ISSUE TITLE
SaGa Frontier (USA)black screen but can still hear music and sound fx

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#133]
happens in all 3 renderers

**Comment by stenzek** [comment]
Seems it is actually rendering, just the display is disabled for some reason...

**Comment by stenzek** [comment]
Okay, I'm not sure this is valid. It might just not be resetting it. Are you using "fast boot"? Try with it turned off.

**Comment by benderscruffy** [comment]
can see graphics with fast boot turned off

**Comment by stenzek** [comment]
Fast boot is the issue then. It might affect other games, so I'll hardcode it to turn the display on at some point.

**Comment by DonelBueno** [comment]
This is the only game in my list that is broken when using "fast boot". You could add an entry for this specific game to use "full boot" or add boot options to per-game settings (don't know if it's a good ideia since there are already so many options).
