### ISSUE TITLE
Customizable order of games/More efficient arrangement system

### ISSUE THREAD

**Issue by tycooko** [stenzek/duckstation#1331]
DuckStation can only order games alphabetically and it does so literally: when it comes to roman numerals, it treats them as letters, so "Final Fantasy IX" is put before "Final Fantasy VIII".
I would love to be able to reorder my games freely or - if possible - you guys could "teach" the software to recognize roman numerals (or, more easily, tell it that when it sees specific titles it will treat "IX" as a "9" OR "V" as a "5", etc.).

**Comment by stenzek** [comment]
#362.
