### ISSUE TITLE
The 2D minigame before each race in Deadheat Road (Japan) (SLPS-00267) doesn't render sprites correctly

### ISSUE THREAD

**Issue by Tiberius1437** [stenzek/duckstation#1336]
![SLPS-00267_2020-12-29_06-51-30](https://user-images.githubusercontent.com/68873449/103240807-736eba00-49a5-11eb-9828-2a6bcd6875a2.png)

Here's what it's supposed to look like.

![Deadheat Road (Japan)-201229-071118](https://user-images.githubusercontent.com/68873449/103240832-85e8f380-49a5-11eb-8838-80a12fbf1f22.png)

**Comment by stenzek** [comment]
Seems to be DMA timing related, resulting in some transfers getting missed. Same issue as Vigilante 8.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/2501547acbfa855671d8468498bba7407e6af6a3 (preview build).
