### ISSUE TITLE
Tomb Raider 1 (USA) (Rev3)

### ISSUE THREAD

**Issue by aphonsoeliasf** [stenzek/duckstation#1337]
After exiting the temple, in the level the Tomb of Qualopec, when you defeat Larson the game freezes and never load.

**Comment by Nucleoprotein** [comment]
Please read bug report template and fill out it correctly, name is wrong too, "Tomb of Qualopec" suggests it's Tomb Raider 1.
Please also make sure your game dump is correct, Tomb Raider have like 7 releases: http://redump.org/discs/quicksearch/slus-00152

**Comment by stenzek** [comment]
Make sure your dump is valid as well. Tomb raider is known to hang if CDDA isn't correct.

**Comment by Alien-Grey** [comment]
You need to use BIN/CUE image files for Tomb Raider games. If yours is CloneCD format you can easily convert them to BIN/CUE with CloneCD Virtual Drive: https://www.elby.ch/nl/products/vcd.html and ImgBurn: https://www.imgburn.com/.

Load your image file with CloneCD Virtual Drive. Open ImgBurn and select the virtual drive and make a new dump.

**Comment by aphonsoeliasf** [comment]
> Please read bug report template and fill out it correctly, name is wrong too, "Tomb of Qualopec" suggests it's Tomb Raider 1.
> Please also make sure your game dump is correct, Tomb Raider have like 7 releases: http://redump.org/discs/quicksearch/slus-00152

Checked my dump game and matchs to redump site.

**Comment by stenzek** [comment]
Did you check the hashes in game properties? It could be a bad cuesheet or a parsing issue.

Otherwise, upload a memory card near the location and I can look into it

**Comment by aphonsoeliasf** [comment]
> Make sure your dump is valid as well. Tomb raider is known to hang if CDDA isn't correct.

**Comment by aphonsoeliasf** [comment]
> Did you check the hashes in game properties? It could be a bad cuesheet or a parsing issue.
> 
> Otherwise, upload a memory card near the location and I can look into it

I checked now and the hashes does not match, i made a dump from my original ps1 cd using ImgBurn.
