### ISSUE TITLE
Spyro 3 - PAL issue

### ISSUE THREAD

**Issue by Gaminho** [stenzek/duckstation#1338]
Hello,
First of all, thank you very much for sharing this emulator with us.
This is a really nice job and most of games work well without issue.

I saw something strange when I tried to play to Spyro 3 - Year of the dragon in PAL Version.
The first level works well but as soon as I try to go to another level, the emulator freeze in a dark screen.

I tried with ePSXe and it seems to work.

Thank you by advance,
Antoine

**Comment by stenzek** [comment]
Make sure your dump is valid, you have a sbi file, and haven't unchecked apply game settings. If you added a sbi file afterwards, reset the system once, don't load from state the first time.

**Comment by Gaminho** [comment]
Here's my settings, i have a sbi file and the emulator has been reset.
<img width="967" alt="Capture d’écran 2020-12-29 à 01 03 15" src="https://user-images.githubusercontent.com/22633478/103249900-ad25cd80-4971-11eb-994d-dedaa3afba1c.png">

**Comment by stenzek** [comment]
Tested a new game and completed Sunny Villa, no hangs here.
