### ISSUE TITLE
SPYRO 3 - PAL - Bug with load state

### ISSUE THREAD

**Issue by Gaminho** [stenzek/duckstation#1339]
I got this screen when i load from load state in Spyro 3, PAL version

Controls run but i can't play without characters, floors and walls.

<img width="967" alt="Capture d’écran 2020-12-29 à 01 48 30" src="https://user-images.githubusercontent.com/22633478/103251193-04c73780-4978-11eb-9913-9bfee220fb23.png">

**Comment by stenzek** [comment]
I think this might be a Mac bug. Try with Vulkan.

**Comment by stenzek** [comment]
Closing due to lack of response. Likely the issue was with the Mac OpenGL driver, I should just disable/remove the GL renderer on Mac builds...
