### ISSUE TITLE
Destruction Derby RAW - Buggy menu

### ISSUE THREAD

**Issue by Patrxgt** [stenzek/duckstation#1342]
**Game details**
SLUS-00912 Destruction Derby RAW (USA)

**Description of the issue / bug**
When using the menu, the ghost of the contextual buttons appears in the lower left corner.
![SLUS-00912_2020-12-29_12-31-17](https://user-images.githubusercontent.com/62941214/103281418-0245fb80-49d3-11eb-9233-664ca1f2ba52.png)

**Steps to reproduce**
Just turn on game and enter the menu.

**Enhancements information**
All enhancements have been disabled and enabling them does not fix the error.

**Hardware/software**
AMD Ryzen 5 3500 X 3.59GHz, NVIDIA GeForce RTX 2060 6GB VRAM, Windows 10 Home (64 bit)
GPU Renderer - Vulkan

**Emulator version**
0.1-2733-gfa7442fd (dev)

**Additional context**
None

**Comment by BloodRaynare** [comment]
Tried uncheck "Disable Interlacing? IIRC this game really love it's combing lines and wouldn't look right without it.

**Comment by stenzek** [comment]
Try setting DMA max slice ticks to 100 (right click -> game properties -> compatibility settings).

**Comment by stenzek** [comment]
Nevermind, this is just a case which needs interlacing enabled - will force it via gameini.

**Comment by BloodRaynare** [comment]
Ah yes, I would like to add another note too: On 2x resolution and beyond, there's a scan line artifacts in most part of the menus.

**Comment by Patrxgt** [comment]
> Tried uncheck "Disable Interlacing"? IIRC this is one of those game that really utilizes those combing lines and wouldn't look right without it.

Yep, it's not working with it or without it.

**Comment by Nucleoprotein** [comment]
This should be fixed in preview branch
