### ISSUE TITLE
Duckstation failing to load glBindFragDataLocationIndexed function seems emulator fault

### ISSUE THREAD

**Issue by Askmewho** [stenzek/duckstation#1355]
Hi, I am testing Duckstation with panfrost mesa driver (RK3399)

I will leave the mesa issue topic on this emulator
https://gitlab.freedesktop.org/mesa/mesa/-/issues/4028

this is what a mesa dev answered

```
t seems that the GL function loader in Duckstation is not loading glBindFragDataLocationIndexed, which is part of the blend_func_extended extension for dual-source blending, and the function pointer is being set to NULL.
Panfrost (at least for Midgard GPUs) fully supports dual-source blending, so there should be no Panfrost-specific issues with it.
Maybe you should file an issue on the Duckstation repo, as they will be familiar with how it loads GL extensions and should be able to help debug this issue.

As a workaround, you could try setting MESA_EXTENSION_OVERRIDE=-GL_ARB_blend_func_extended.
```
the workaround actually works, but it should be not that way :) 
Loving Duckstation!! Best regards! Salvador

**Comment by stenzek** [comment]
It's probably loading `GL_EXT_blend_func_extended` instead, since it's an ES context, which has a different function (`glBindFragDataLocationIndexedEXT`). Try with https://github.com/stenzek/duckstation/commit/6d501bff56062e7574251ba1a3e899ead130887e.

**Comment by stenzek** [comment]
Closing as I'm pretty sure the linked commit should solve the issue. Please let me know if the crash is still occurring.
