### ISSUE TITLE
Ability to remove animations in option menus

### ISSUE THREAD

**Issue by msmigiel** [stenzek/duckstation#1359]
Environment:
- Samsung Galaxy S5e tablet running Android 10
- Latest version of Duckstation in the Google Play store as of 12/31/2020

Feature Request:
When in the option menus and going between sections, there is some transition animation. Even on my mid range tablet, it makes the UI feel slow, especially when going from the first (General) to the last (Advanced) section - it takes a second or 2 to catch up. Personally I disable all animations on Android to make it feel faster. Please consider adding an option to remove such menu animations as it makes the UI feel slow.

**Comment by stenzek** [comment]
I doubt removing the animations would make much difference here.
