### ISSUE TITLE
Goryuujin Electro (Japan) instantly hangs after BIOS screen

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#136]
It stays on a black screen forever while the BIOS music loops. 

![Capture](https://user-images.githubusercontent.com/31968468/77227856-2cae9100-6bd7-11ea-9667-e7ff23969e47.PNG)

**Comment by stenzek** [comment]
Should be fixed on latest master.

**Comment by kurayami6** [comment]
It now hangs when starting a game.

![Capture](https://user-images.githubusercontent.com/31968468/77832251-cacaca00-7188-11ea-914e-01dcf627f8a8.PNG)

**Comment by Zet-sensei** [comment]
Fixed wwhen tested with https://github.com/stenzek/duckstation/commit/a4a112f5d8d2d48ef695db747df4026c27a8e79f

![Electro](https://user-images.githubusercontent.com/52127625/79031785-aff15000-7ba1-11ea-8760-b11d19562221.jpg)
