### ISSUE TITLE
Panic triggered: 'Failed to submit command buffer.'

### ISSUE THREAD

**Issue by rafagomeszero2** [stenzek/duckstation#1362]
**Game details**

SLES-03936 Digimon World 2003 (E)]

**Description of the issue / bug**
While playing in window mode, clicking outside the window or alt+tab to browser give an error message, and then the emulator crashes.
Re-opening the emulator, it loses the recent save states.
The error message: "Panic triggered: 'Failed to submit command buffer.' in function Vulkan::Context::DoSubmitCommandBuffer (D:\a\duckstation\duckstation\src\common\vulkan\context.cpp:914)
Do you want to attempt to break into a debugger: Pressing Cancel will abort the application."
Clicking both "Okay" or "Cancel" will close the emulator.
It does not happens all the time. Something like 10% 

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
No.
2. Which controller backend are you using in general settings
XInput

**Steps to reproduce**
Happens when the window lose the focus. Clicking outside or alt+tab

**Enhancements information**
No enhancements.

**Hardware/software**
CPU: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz   3.20 GHz
GPU: Radeon RX 590 Series 8 GB
OS: Windows 10 Pro 20H2
GPU Renderer: Vulkan

**Emulator version**
0.1-2799-g0d281538

**Comment by stenzek** [comment]
Can't seem to trigger this on a RX580 here with other games. Does it occur in other games for you, or just Digimon World 2003?

**Comment by stenzek** [comment]
Closing due to lack of response. If this is still happening on the latest preview build, please let me know.
