### ISSUE TITLE
NASCAR 2001 - Issues with sound and control

### ISSUE THREAD

**Issue by BloodRaynare** [stenzek/duckstation#1364]
**Game details**
NASCAR 2001, SLUS-01263

**Description of the issue / bug**
For the sound issue: Sometimes, the game's background music will stop briefly/only left channel plays, then it plays normally.
For the control issue: If DualShock is turned on and analog is used for steering, sometimes I'm unable to turn the car until I turn at the opposite direction (For example: I'm unable to turn to the left until I steer it to the right, then I can finally steer it to the left). Already tried to fiddle with Analog axis scale settings, but it didn't fix the problem.

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open? 
Well, the only driver I installed for my controller is only for the force feedback ones, which didn't work in DuckStation anyway.
2. Which controller backend are you using in general settings: 
I'm using SDL since for some reason I can't use Dinput.

**Steps to reproduce**
Sound: Just listen to the game's BGM on the main menu.
Control: Just try to enter any races. I recommend to try it on the Practice race.

**Enhancements information**
Enhancements already turned off

**Hardware/software**
HP Notebook 14
Intel i3-4030U 1.90Ghz
NVIDIA GeForce 820M
8GB RAM
Windows 8.1
D3D11

**Emulator version**
0.1-2799-g0d281538

**Additional context**
Most likely also happens with NASCAR Thunder 2002, 2003, and 2004, since those games is sharing the same engine with this one.

**Comment by stenzek** [comment]
SPU interrupt related.

**Comment by stenzek** [comment]
Sound issue should be fixed in https://github.com/stenzek/duckstation/commit/73f6521452fcc38ab6debbddcaf8487a308bc657

**Comment by BloodRaynare** [comment]
Thanks, now the sound has been fixed. How about the control issues though? 
But anyway, since the problem happens only with DualShock with analog mode on, I can just use the Digital Mode then enable the "Analog Sticks for D-Pad" which achieve the same thing + I can use the real D-Pad as well.

**Comment by BloodRaynare** [comment]
Just tried with my newly-arrived DS4 controller and no problems with the analog control. I assume must be the "Twin USB Gamepad" being buggy again.
