### ISSUE TITLE
Overlay all settings from input profile, not just bindings

### ISSUE THREAD

**Issue by johnnyruz** [stenzek/duckstation#1365]
**Game details**
SLUS-00405 Time Crisis 2 (USA)

**Description of the issue / bug**
It appears that custom crosshair settings are not being applied to game-specific input binding profiles.

I have a "default" controller profile setup as an Xbox One controller that is used for the majority of games, but for the Time Crisis games I have setup a Guncon profile that includes settings for applying a custom crosshair image.

If I leave the Xbox One controller profile selected in the main settings, when I start the game I see "Loading Profile: Time Crisis" and the buttons work as configured, however is still displayed as the default image at 1x scale.

However, if I also set the main controller profile to Time Crisis, when starting the game I get the "Loading Profile: Time Crisis" but the crosshair correctly reflects my settings.

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open? NO
2. Which controller backend are you using in general settings? SDL

**Steps to reproduce**
1. Create and save a custom Guncon profile that includes an update to the crosshair settings (custom image, crosshair image scale)
2. Set the main controller profile back to a non-Guncon setup
3. In the game properties of SLUS-00405 Time Crisis (USA), set the User Settings (Input) to a Guncon controller in Port 1, nothing in Port 2, and the Input Profile for Bindings to the profile you created in step 1
4. Start the game and confirm you see the message "Using Input Profile: [Name from step 1]"
5. Observe that the crosshair image remains as default and does not reflect the custom settings

6. Go back and set the Main/Default controller profile to the one you created in step 1
7. Start the game and confirm you see the message "Using Input Profile: [Name from step 1]"
8. Observe that the crosshair image is now displayed as configured in the profile  

**Enhancements information**
All Off

**Hardware/software**
Windows 10, i7-4790, 8GB RAM, AMD Radeon R7 250 2GB
GPU Renderer - D3D11

**Emulator version**
0.1-2799-g0d281538

**Additional context**
Very new to using Duckstation, apologies if I'm missing something obvious!

**Comment by stenzek** [comment]
It's working as intended, that's why in game settings it's listed as "use bindings from input profile" not "apply input profile" - it only grabs the bindings, not any other settings.

Unfortunately with the way the config system works, it's not possible to completely overlay one config over the base config. My bad for not designing the initial system with it in mind.

It is something I want to improve in the future, but not sure when I will get around to it.

**Comment by johnnyruz** [comment]
Thanks for the fast reply and adding this to the list and creating a better issue/problem description. Definitely higher priority items to work on. In the meantime I'll take a look at this as well and see if I can understand the code!

Ultimately my goal is to be able to launch with command line arguments from a frontend and override controller configurations (and maybe other settings) as needed. I have a solution working locally where I've added a command line parameter that allows you to provide a path to a different settings INI file and override the defaults that way, but managing multiple complete sets of ALL settings doesn't seem to be as clean or easy as using the already implemented per-game profile settings.

Absolutely fantastic emulator, great work!

**Comment by ggrtk** [comment]
Fwiw, this is probably related to #1013. I'd originally planned to resolve this by splitting profiles out from the main settings.ini and have controller profiles be loaded from these separate files on system boot.

Haven't gotten around to working on this idea yet though, so it's open to any suggestions.

**Comment by johnnyruz** [comment]
Yeah I'm sure it could be related and it sounds like splitting it out could be a good solution to solve #1013 as well as this feature request.

After digging into the code it just looks like while the crosshair configuration is successfully stored in the INI of the custom controller input profile, as @stenzek mentioned, anything that is not a "Button" or an "Axis" does not get mapped. The crosshairs appear to be considered as "Settings" so when namco_guncon.LoadSettings fires it always reads from the base settings since no settings were ever actually overridden in common_host_interface.UpdateControllerInputMap.

Looking into solving this optimally but my knowledge of the code (and C++ skills!) is definitely lacking, hence my original brute-force solution of just allowing for an override of the full settings file rather than just the Controller section.

I'll keep plugging but someone with more skill and knowledge takes an interest and knocks this out would definitely be appreciated!

**Comment by stenzek** [comment]
> Looking into solving this optimally but my knowledge of the code (and C++ skills!) is definitely lacking, hence my original brute-force solution of just allowing for an override of the full settings file rather than just the Controller section.

The problem with this is you'd lose any controller bindings set, because applying the input profile would overwrite them. Which is fine when you're explicitly applying it from controller settings, but not so much when it's happening as part of starting a game.

Like I said, ideally we can just stack settings interfaces - it would simplify per game settings in the first place, since it'd just be a second ini which is temporarily overlaid on top of the base settings, and doesn't affect them in any way.

**Comment by johnnyruz** [comment]
Yeah agreed, definitely problems with my original solution and the idea of stacking interfaces sounds like the right approach. 

To be clear my "override" was just adding a command line argument that allows you to pass the name of a full settings file. So use "settings_timecrisis1.ini" instead of the default "settings.ini". I don't lose anything and it works well to get my desired effect of having 99% of games use the defaults, but allowing the others that require a special config to have that applied at runtime. 

Definitely useful and good to have the option, but the obvious flaw is that any changes that you want to be global would have to also be updated in every one of the custom settings files. Your approach sounds a lot better!

**Comment by stenzek** [comment]
If you want to maintain entire multiple settings files, a command line parameter to override which file gets loaded for the base case wouldn't be difficult to add.

**Comment by johnnyruz** [comment]
As far as entire multiple settings files and loading from the command line, I believe I already have that complete and I can do a PR.

**Comment by stenzek** [comment]
All settings are overlaid post UI revamp.
