### ISSUE TITLE
Inventory/Pause freezes Tomb Raider emulation

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#1367]
**Game details**
SLES-00024 Tomb Raider (Europe)

**Description of the issue / bug**
I suppose this is a relatively specific issue and I understand if you're not interested. Still thought I'd report. I've disabled game settings and cannot find an SBI file.
The game has several bosses, and while most work, two will make emulation freeze when you're near them, and then want to enter the inventory (select) or pause the game (start). This is the behaviour:

https://user-images.githubusercontent.com/4934209/103457337-a6df7a80-4cfe-11eb-8f2a-11f86127e02a.mp4

^when recording I still had forced 60hz timings on, but I can reproduce it without that setting enabled (then at 25fps), too. Both problematic bosses I've found so far are in the "Natla's Mines" level. When you move on in the level (distance yourself from the bosses after defeating them), select and start work again as expected again.

**Controller Troubleshoot Report**
Digital Controller, playing with keyboard

**Steps to reproduce**
Play until the spot in the video, hit select or start.

**Hardware/software**
Win7-x64
Intel Core I7 7700
NVidia Quadro M620

Win10-x64
Intel Core 2 Quad Q9550S
NVidia GeForce GT 610

^both with D3D11

**Emulator version**
![image](https://user-images.githubusercontent.com/4934209/103457677-941a7500-4d01-11eb-9da1-60d4cbcc2788.png)

**Comment by stenzek** [comment]
PAL only?

**Comment by Richard-L** [comment]
SLUS-00152 Tomb Raider (USA) (Rev 3):

https://user-images.githubusercontent.com/4934209/103483884-99072380-4dea-11eb-87ab-84049a7f3ebe.mp4

^works as intended.

However I reproduced the issue by chance elsewhere in the level:

https://user-images.githubusercontent.com/4934209/103483902-c358e100-4dea-11eb-93ab-9b8a5976239e.mp4

This would suggest it's not necessarily related to the boss.

**Comment by Richard-L** [comment]
Found it also happening when dying:
https://user-images.githubusercontent.com/4934209/103711912-bbe73280-4fb8-11eb-8bc2-4f5d3ea879c1.mp4

My impression is it could be specific to this level for some reason.

**Comment by Kurayami7** [comment]
I've confirmed the issue. Tested with a Redump verified copy of the game and all enhancements off. The game crashed as I died in a lava pit. 

![SLES-00024_2021-01-14_12-43-46](https://user-images.githubusercontent.com/77198254/104533759-1a6e7980-5667-11eb-8b65-a69a1536bd80.png)

![Capture](https://user-images.githubusercontent.com/77198254/104533779-20645a80-5667-11eb-8a3d-a3e5af59cf71.PNG)

**Comment by Kurayami7** [comment]
I got the same crash after dying to the boss at the end of level 4. 

![SLUS-00152_2021-01-15_02-52-35](https://user-images.githubusercontent.com/77198254/104615324-3f053880-56dd-11eb-9884-a55cf93a80ce.png)

![Capture](https://user-images.githubusercontent.com/77198254/104615349-43c9ec80-56dd-11eb-8b2a-20cdb26b45f9.PNG)

**Comment by stenzek** [comment]
Please provide a memory card as the template requests.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/2c1999e622018136d2d0fc68da6fa9c9afcea888
