### ISSUE TITLE
Ian Livingston's Deathtrap Dungeon hangs on the first loading screen

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#137]
![Capture](https://user-images.githubusercontent.com/31968468/77228361-dc393280-6bda-11ea-8368-180b46f58b7f.PNG)

**Comment by benderscruffy** [comment]
goes ingame for me now
![dungeon](https://user-images.githubusercontent.com/2696404/77408420-a7072d00-6df2-11ea-8f56-c51115b56c14.PNG)

**Comment by kurayami6** [comment]
Yeah it doesn't crash anymore. Menu graphics are still broken in D3D11 but that's a separate issue.
