### ISSUE TITLE
DuckStation crashes with USB network joystick driver / DInput problems

### ISSUE THREAD

**Issue by PavelDurov1488** [stenzek/duckstation#1370]
Hey. It's EZFRD64.dll issue, may be you can fix it. I saw something like this was in Dophin https://github.com/dolphin-emu/dolphin/pull/5582

DuckStation does not crashes if select Dinput/Xinput, but there is another problem. With DInput I see (without gamepad too)

[    6.0771] E(Initialize): Failed to get DInput function pointers.
[    6.0774] W(UpdateControllerInterface): Failed to initialize controller inter
face, bindings are not possible.

**Game details**
Any

**Description of the issue / bug**
Crashes cause of EZFRD64.dll

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
Yeah, USB network joystick driver
2. Which controller backend are you using in general settings
SDL

**Steps to reproduce**
Install USB network joystick driver

**Enhancements information**
[Make sure they are all turned off before report]

**Hardware/software**
Windows 8.1

**Emulator version**
0.1-2799-g0d281538

**Additional context**
Maybe if in one day there is 32-bit DS, then it works, but if not... Not problem. Happy New Year, Stenzek!

**Comment by PavelDurov1488** [comment]
If install this vibration driver
https://github.com/alessandroasm/generic-usb-gamepad-vibration-driver/releases

No crashes, but no vibration (dxdiag shows that this exists)
![image](https://user-images.githubusercontent.com/74456272/103467686-05affd00-4dae-11eb-8efa-796b530a2dac.png)

**Comment by stenzek** [comment]
I would rather not add hacks for clearly broken drivers.

> If install this vibration driver
https://github.com/alessandroasm/generic-usb-gamepad-vibration-driver/releases
> No crashes, but no vibration (dxdiag shows that this exists)

That's because my dinput interface does not support force feedback yet. One thing at a time.

**Comment by PavelDurov1488** [comment]
It looks like DuckStation's DInput does not support DInput 

I see it even without gamepad and no reaction
[ 6.0771] E(Initialize): Failed to get DInput function pointers.
[ 6.0774] W(UpdateControllerInterface): Failed to initialize controller inter
face, bindings are not possible.

**Comment by Nucleoprotein** [comment]
It seems dinput8.dll does not have required function on 8.1 (GetdfDIJoystick) but - "Windows 10 is the only version of Windows supported by the developer. "

**Comment by stenzek** [comment]
Yup, works fine for me on win10. I'll look into an alternative for that function, just was hoping to avoid loading dinput8.dll when it's unnecessary. But it might get loaded transitively via SDL anyway

**Comment by PavelDurov1488** [comment]
I hope it can vibrate someday
![image](https://vk.com/sticker/1-71-128)
