### ISSUE TITLE
Hold key to fast foward

### ISSUE THREAD

**Issue by FramesJanco** [stenzek/duckstation#1371]
Having a hotkey to only use fast forward when a button is held would go a long way in making the feature more appealing. There are very few situations where toggle would be preferable since you generally just want to use it a little bit then stop immediately. It's a very simple addition too.

**Comment by andercard0** [comment]
> Having a hotkey to only use fast forward when a button is held would go a long way in making the feature more appealing. There are very few situations where toggle would be preferable since you generally just want to use it a little bit then stop immediately. It's a very simple addition too.

Indeed is a very addition and it is done already please check 
![image](https://user-images.githubusercontent.com/43047877/103469037-82a38e00-4d3e-11eb-8c73-cfa4cfd97ded.png)

You can set up any key for toggle fast forwarding.

**Comment by stenzek** [comment]
Indeed this already exists.
