### ISSUE TITLE
Flickering Lines in Umihara Kawase Shun (Japan) 

### ISSUE THREAD

**Issue by Abrahambrazil** [stenzek/duckstation#1373]
I'm playing Umihara Kawase Shun (Japan) using Duckstation 0.1-2798 (All the settings of the emulator are as DEFAULT) on my Xiaomi Mi Mix 2 with Android 10 and these flickering lines appear all the time. Is there any option to activate and make them disappear?
I also noticed these flickering lines in the games Digimon Rumble Arena (USA) and Street Fighter EX2 Plus (USA)

Steps to see the bug occurs:
Start the game and observe the edges of the screen of the game. 
(The screenshot doesn't capture them as big as they are, you gotta play the game on your phone to see them properly.)
![Screenshot_20210103-041400_DuckStation](https://user-images.githubusercontent.com/76560477/103474098-3298eb80-4d7f-11eb-9a16-ba15229a9fe2.png)

**Comment by stenzek** [comment]
Use Vulkan not OpenGL, or disable linear upscaling.

**Comment by Abrahambrazil** [comment]
> Use Vulkan not OpenGL, or disable linear upscaling.

Thank you so much! 
I used Vulkan and the flickering lines vanished from all the games.
