### ISSUE TITLE
The Unholy War (PAL) randomly pausing frequently

### ISSUE THREAD

**Issue by Idonttakeordersfromporkfaggots** [stenzek/duckstation#1374]
SLES-01300 The Unholy War (PAL) (listed as Unholy War, The (Europe) (En,Fr,De,Es,It))

the game will randomly pause frequently while in game this affects both mayhem and strategy mode.

i have tested using a PS4 controller and a Xbox one controller and used both SDL and DInput.

to reproduce the issue just simply enter a mayhem or startegy mode match and play normally it should only take about 10 seconds for the game to pause without the users input.

My enhncement settings are as follows
Internal resolution scale: 9X (4K)
Multisample antialiasing: 32MSSA (the game does however only support up to 8MSSA)
Texture filtering: xBR

True Colour rendering: enabled
Scaled dithering: disabled
Widescreen Hack: enabled
Disable Interlacing: enabled 
Force NTSC timings: enabled
Force 4:3 For 24-bit display: disabled
Chroma smoothing for 24-bit display: enabled
Geometry correction: enabled
Culling correction: enabled
Texture correction: enabled
Depth buffer: disabled

for the sake of testing i have tried playing the game with all enhancements disabled and the afformentioned problems still persisted.

I'm runnign the emulator on a windows 10 PC With an Intel core i9-9900KS CPU with a Nvidia Geforce RTX 2080 TI graphics card.
i am using vulcan as the GPU renderer for the emulator.

i am using version: 0.1-2799-g0d281538 of duckstation

the legacy of kain soul reaver demo included in the game runs without any issues.

**Comment by stenzek** [comment]
Right click -> game properties -> compatibility settings. Set "DMA Max Slice Ticks" to 100.

See if this makes any difference.

(I'm planning on making this the default eventually, as there's quite a few games which need the higher precision)

**Comment by Idonttakeordersfromporkfaggots** [comment]
That seems to have done the trick, thank you

**Comment by stenzek** [comment]
Great, thanks. I'll add an override in the database.
