### ISSUE TITLE
Duckstation crashes as soon as you try and load a game as of the latest version.

### ISSUE THREAD

**Issue by Tiberius1437** [stenzek/duckstation#1376]
![Capture](https://user-images.githubusercontent.com/68873449/103482371-9cbf9800-4e34-11eb-9ffb-38d25426ba9d.PNG)

**Comment by stenzek** [comment]
Your bug report is incomplete.

Preview or latest build?

Is it specific to this game?

Does it happen on a fresh boot?

**Comment by Tiberius1437** [comment]
Preview.
No, I tried 3 different games
No.

**Comment by stenzek** [comment]
Try switching back to the latest build in settings, and see if that build crashes.

You could try setting the recompiler fast mode in advanced settings to LUT instead of MMap - if there's some driver clashing with the fastmem range that will avoid it.

**Comment by stenzek** [comment]
So the issue is loading the save states for these particular games? Does creating a new save state and loading that also crash?

**Comment by Tiberius1437** [comment]
Oh you mean a fresh boot of the game. Yes it crashes.

**Comment by Tiberius1437** [comment]
Alright fresh download of the latest dev version and THEN updating fixed it. Fuck knows what was wrong with it.
