### ISSUE TITLE
(Audio Bug) Digimon Rumble Arena (USA) 

### ISSUE THREAD

**Issue by Abrahambrazil** [stenzek/duckstation#1379]
I'm playing Digimon Rumble Arena (USA) using Duckstation 0.1-2818 (I'm using Vulkan, region: NTSC-U, and all the other settings of the emulator are as DEFAULT) on my Xiaomi Mi Mix 2 with Android 10 and there is an audio bug on the game when I play with Gatomon in the 1 player mode. When I play with her and use the attack that she does when I press circle, there is an annoying noise at the end of the sound that the attack makes.  

Steps to see the bug occurs:
Start the game, select 1 player mode, choose Gatomon and use her attack by pressing CIRCLE. Use her attack far from your opponent in order to see the sound that it is going to make.

**Comment by stenzek** [comment]
Since this is android, you should check that any sound issues are not caused by frame drops. Make sure the emulation speed is not below 100% at any time.

**Comment by Abrahambrazil** [comment]
> Since this is android, you should check that any sound issues are not caused by frame drops. Make sure the emulation speed is not below 100% at any time.

Alright. 
But I'm sure that there isn't any lag or something related to the speed since the game is running perfectly and this audio bug only happens with this character,

**Comment by stenzek** [comment]
Not hearing anything which sounds broken here. Maybe I am not doing it correctly.

https://cdn.discordapp.com/attachments/783243171093020675/795586990531543070/Digimon_Rumble_Arena_USA_2021-01-04_19-36-24.mp4

**Comment by Abrahambrazil** [comment]
> Not hearing anything which sounds broken here. Maybe I am not doing it correctly.
> 
> https://cdn.discordapp.com/attachments/783243171093020675/795586990531543070/Digimon_Rumble_Arena_USA_2021-01-04_19-36-24.mp4

Maybe the audio bug only happens on Android.

**Comment by stenzek** [comment]
Sounds the same on my phone.

**Comment by Abrahambrazil** [comment]
> Sounds the same on my phone.

Well, I have no idea why mine isn't working properly as yours.

**Comment by Shideravan** [comment]
I also can't reproduce this issue. Did you checked your game dump?
Also, may be a good idea to check with a headphone, as some effects in this game have notably low quality, and maybe it's possible that a bad speaker can generate noise for some bad digitallized samples. When do you play the video from Stenzek you experience the same issue in the audio output from the mobile phone?

**Comment by stenzek** [comment]
Likely slowdown/frame time spikes on Android, the frame pacing changes may make it less noticable.
