### ISSUE TITLE
PAL vs NTSC default resolution.

### ISSUE THREAD

**Issue by rafaelmartines** [stenzek/duckstation#1380]
**Game details**
SCES-00004 Rapid Reload (Europe), SLES-00511 International Superstar Soccer Deluxe (Europe) probably other PAL region games too.

**Description of the issue / bug**
The PAL games that I tested has some differences in the default screen resolution, even after I tried to force 4:3 screen.

**Steps to reproduce**
Rapid Reload is also known as SCPS-10006 Gunners Heaven (Japan), so you can just bootup both ISOs and check the differences on the size of the screen like the screenshots below:

SCES-00004 Rapid Reload (Europe)
![SCES-00004_2021-01-04_08-25-35](https://user-images.githubusercontent.com/8183691/103531371-f3929500-4e67-11eb-95f4-f2fb96e21c1e.png)

SCPS-10006 Gunners Heaven (Japan)
![2021-01-04_08-25-12](https://user-images.githubusercontent.com/8183691/103531417-09a05580-4e68-11eb-895f-8953c2ccdc25.png)

**Enhancements information**
They are off.

**Hardware/software**
Tested with OpenGL and Vulkan
CPU: AMD Ryzen 5 1600 (12) @ 3.200GHz
GPU: NVIDIA GeForce GTX 1660 SUPER
OS: Ubuntu 20.04.1 LTS x86_64

**Emulator version**
0.1-2811-g59c7c32a

**Additional context**
I also tested this on SLES-00511 International Superstar Soccer Deluxe (Europe)

**Comment by stenzek** [comment]
PAL games do run at a different resolution to NTSC. It's still 4:3.

**Comment by rafaelmartines** [comment]
> PAL games do run at a different resolution to NTSC. It's still 4:3.

But on PCSX ReARMed they fill the whole screen :\ is that some setting up that I need to do? I didn't nothing on PCSX ReARMed

**Comment by stenzek** [comment]
That's probably because afaik most pal games are letterboxed rather than being designed for the higher resolution of PAL.

You could try the all borders crop mode, but be aware this may alter the aspect ratio.

**Comment by rafaelmartines** [comment]
> That's probably because afaik most pal games are letterboxed rather than being designed for the higher resolution of PAL.
> 
> You could try the all borders crop mode, but be aware this may alter the aspect ratio.

I mighty try it, I opened that issue 'cause Duckstation AFAIK will be delivered with Lakka 3.0 in the future, since BeetlePSX is too slow on RPi3 devices and I looking foward to migrate from PCSX to Duckstation <3

**Comment by stenzek** [comment]
Closing then, since in this case DuckStation is emulating the console correctly.

For what it's worth, you can also set custom crop values per-game (right click in game list -> game properties).

Note this is not available in the libretro core, the horizontal value is in ticks and libretro offers no way to control values in the ranges of thousands.
