### ISSUE TITLE
Add time/frame counter variable for postprocessing

### ISSUE THREAD

**Issue by Ever17lab** [stenzek/duckstation#1381]
Hey. If I make something like

```
void main()
{

  int FrameCount = GetFrameCount();
```

I see badshader with

```
Compile as ps_5_0 failed: -2147467259
F:\Prog\DuckStation\0(251,20-34): error X3004: undeclared identifier 'GetFrameCount'
```

Also, no reaction on time variable. It's needed for dynamic noise generation

[Cccalibrator.zip](https://github.com/stenzek/duckstation/files/5765107/Cccalibrator.zip)
 

**Game details**
Any

**Description of the issue / bug**
Time variable looks static / GetFrameCount does not work

**Steps to reproduce**
Add GetFrameCount to shader

**Hardware/software**
IntelHD4000, Win8.1

**Emulator version**
0.1-2799-g0d281538

**Additional context**
No...

**Comment by stenzek** [comment]
Yep, time was never implemented.

**Comment by PavelDurov1488** [comment]
But exists in shader generator
![image](https://user-images.githubusercontent.com/74456272/103551511-ef698480-4f06-11eb-838a-f0c34ddf0a8d.png)

**Comment by stenzek** [comment]
Yes, but it was never connected to anything.

**Comment by PavelDurov1488** [comment]
Wow!

**Comment by stenzek** [comment]
Was fixed long ago.
