### ISSUE TITLE
[ Android ] Auto-hide touchscreen controller not working properly

### ISSUE THREAD

**Issue by NightClawZ** [stenzek/duckstation#1385]
Hello, 

Whenever I enable the "Auto-hide touchscreen controller", they disappear whether or not I have a controller connected. 

I use a OnePlus 8T and previously had a SN30 connected to it, it still appears in the "Previously connected devices" in the bluetooth settings.

**Comment by stenzek** [comment]
It's working fine here on a OnePlus 6.. I wonder if there's some other device it's detecting as a controller..

**Comment by NightClawZ** [comment]
Just tried on a Galaxy Note 8 and it works. 
I had previously connected the same BT controller to both phones. 

My 8T also had another previously connected device : OnePlus Ear Buds. 

I enabled the Trace level and disabled all the enhancement and started an ISO for a little bit
Here the log file : [duckstation.log](https://github.com/stenzek/duckstation/files/5771310/duckstation.log)
. 
Hope it will help. Just tell me if I can assist somehow.

**Comment by NightClawZ** [comment]
This log may be more useful : it goes from starting the emulator, run a game and exit. 
[duckstation.2.log](https://github.com/stenzek/duckstation/files/5771368/duckstation.2.log)

**Comment by stenzek** [comment]
Couldn't ever reproduce this issue.
