### ISSUE TITLE
Bust a Groove US - Pause Randomly (again)

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#1386]
Serial Code, Region
Bust A Groove | SCUS-94263 - USA

**Description of the issue / bug**
As soon as game starts it pause automatically. 
(same behavior as reported in #577) only difference, now game pauses as soon as game starts. 

Note:
Not happening (god knows why) in Japanese version.

**Controller Troubleshoot Report**
Not Related

**Steps to reproduce**
Choose your character then wait till loading screen and play.

**Enhancements information**
None.

**Hardware/software**
Any: Renderer - D3D11/OpenGL/Vulkan

**Emulator version**
Preview  - 0.1-2828-gc3b0a870 & Dev - 0.1-2811-g59c7c32a

**Additional context**
Nothing.

**Comment by Unicorngoulash** [comment]
Some games auto-pause when the wrong controller type is in use like analog on a digital input game. Try forcing digital in  game properties and see if that helps.

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/68f97a8116741d3d9a61f4a9e66f1bdac0631ee5 (may also fix https://github.com/stenzek/duckstation/issues/586 as well).
