### ISSUE TITLE
Pausing the emulator and minimizing it causes the screen to turn white

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#139]
Pause the emulator in windowed mode, minimize it, bring it back up and the screen will be white.

![Capture](https://user-images.githubusercontent.com/31968468/77234299-58467100-6c01-11ea-87fc-aef80088b91a.PNG)

**Comment by stenzek** [comment]
I'm unable to reproduce this. All transitions, including minimizing/maximizing and switching in/out of fullscreen appear to be fine while paused.

**Comment by benderscruffy** [comment]
yep happens to me aswell
must be an AMD problem
but soon as you unpause it the game continues as normal

**Comment by kurayami6** [comment]
It's not a problem with AMD. I'm using NVIDIA.

**Comment by PatrickvL** [comment]
It might depend on Windows or it's graphics drivers not sending a repaint event when un-minimizing

**Comment by benderscruffy** [comment]
@kurayami6 
sorry thought you had an AMD card the same as me

**Comment by stenzek** [comment]
@PatrickvL possibly. In this case I respond to window resize events, not paint (the renderer is responsible for painting/buffer swapping on-demand, so no paint messages). I think both @benderscruffy and @kurayami6 are on Windows 7, so this may be the issue. I might see if I can find an event for minimized/restore and force re-display on that as well.

**Comment by stenzek** [comment]
Please retry on latest master, I may have forgot to set a flag on the display widget.

If that doesn't work, I'll set it up to forcibly redraw when the window is restored.

**Comment by benderscruffy** [comment]
no sorry not fixed

**Comment by stenzek** [comment]
Okay, I've added detection of minimize/restore and forced it to redraw when restored. See if that makes any difference.

**Comment by benderscruffy** [comment]
fixed in the latest master

**Comment by kurayami6** [comment]
Yeah it's fixed for me as well.
