### ISSUE TITLE
V-Rally - 97 Championship Edition (Europe) (En,Fr,De) (Rev 1) - SLES-00250 - Game menu pop up

### ISSUE THREAD

**Issue by Alien-Grey** [stenzek/duckstation#1390]
While racing the game menu constantly pops up. It's like pushing the Start button every time. I've tried a lot of differnt configuration settings to avoid this but didn't find a fix.  Also tried disabling all enhancements but that also makes no difference.

**Comment by BloodRaynare** [comment]
Try set the values of DMAMaxSliceTicks to 100 in the advanced settings, see it it's fixes it.

**Comment by Alien-Grey** [comment]
Thanks. Setting DMA Max Slice Ticks to 100 fixes it.

**Comment by stenzek** [comment]
So, I've come up with a potential solution which shouldn't hurt performance as much, as we won't need to set the values for all these games. Try the latest preview build, and set the slice ticks to 0, hopefully it won't be broken there.

**Comment by Alien-Grey** [comment]
Setting DMA Max Slice Ticks to 100 is the sweet spot. I tried this also with WipEout 2097 and not a single slowdown any more. I also had to lower the Audio Buffer to the minimum value of 1024 frames. This is with PGXP enabled with an Intel Atom® x7-Z8750 Processor @1.6GHz. That's freaking awesome.

**Comment by stenzek** [comment]
Did you try setting it to defaults on the preview branch? You shouldn't need to override it anymore, and fewer per game settings is a better solution.

**Comment by Alien-Grey** [comment]
I did try with the default setting on the preview branch and it fixes the issue.

**Comment by stenzek** [comment]
Great! Thanks for checking, no game specific settings are a much better solution :)
