### ISSUE TITLE
Adventures of Lomax / Lomax

### ISSUE THREAD

**Issue by Mclaneinc** [stenzek/duckstation#1393]
**Game details**
[Serial Code, Region]
SCUS-94906 Adventures of Lomax USA

**Description of the issue / bug**

Game boots to Sony of America screen and then sits there, does the same on the PAL version, no cheats, no enhancements, tried different renderers. Both games from the Redump project..

Thanks..

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
2. Which controller backend are you using in general settings

**Note:**
If you are using Duckstation on Android device please consider the following before report:
Are you using any kind of "memory optimizer" program such as: Ccleaner, Wisecleaner, Clean Master, Boost Android etc. ?
(if so, please, consider create an exception on it first and test; or even remove / uninstall it retest and then, if the problem persists continue with the report.

**Steps to reproduce**
[Try to provide as much detail as possible to reproduce the issue]

**Enhancements information**
[Make sure they are all turned off before report]

**Hardware/software**
[If Android, which phone and Android version]
[If desktop, your CPU, graphics card, and operating system]
[GPU Renderer - D3D11/OpenGL/Vulkan]

**Emulator version**
[Shown in the title bar of the emulator]

**Additional context**
[Add any other context about the problem here]

**Comment by stenzek** [comment]
Could you please check that your dump is valid? (game properties, compute hashes, compare with md5 on redump).

Also make sure you haven't changed any of the advanced settings (reset them to default to be safe).

**Comment by Zet-sensei** [comment]
After your reports, I've tested all versions of the game (Redump format & CHD format), with multiple BIOSes possibilities + CPU/Renderer Modes.

I can't seem to reproduce your issue at all.

![Lomax](https://user-images.githubusercontent.com/52127625/103775435-56358d80-502e-11eb-987d-d32ecf4b3d3c.jpg)

**Comment by Mclaneinc** [comment]
Sorry guys, reset everything and I must have had some corrupt stuff, many many apologies for the false report. I should know better I beta test quite a few emu's...Oops...

**Comment by stenzek** [comment]
All good, thanks for checking :)
