### ISSUE TITLE
FF VII Random Freezes

### ISSUE THREAD

**Issue by Ever17lab** [stenzek/duckstation#1396]
Hey. I have huge random freezes in FF VII

I thought it's translation's problem, but same thing in US image

**Game details**
[SCUS-94164] (USA) Final Fantasy VII

**Description of the issue / bug**
I have huge random freezes in FF VII

**Steps to reproduce**
Play sometime (~10minutes, you need to go down the stairs)
[shared_card_1.zip](https://github.com/stenzek/duckstation/files/5773093/shared_card_1.zip)
As for me, I met 1st freeze in this position
![image](https://user-images.githubusercontent.com/74456272/103710507-aa7e4480-5011-11eb-920d-3bf62e20b2a4.png)

**Enhancements information**
I dont know... If you don't have a time, maybe I can collect some information. I met this in libretro core too
It can freezes for >10 sec and then unfreeze. In last case my laptop was fully paralyzed, no reaction on hotkeys like alt+tab

**Hardware/software**
Win 8.1 i5-3317U 
Intel HD 4000

**Emulator version**
![image](https://user-images.githubusercontent.com/74456272/103711061-0dbca680-5013-11eb-8321-46f0db707dd2.png)

**Comment by stenzek** [comment]
Is your dump valid? Enhancements off? I finished FF7 in the emu a while back with no issues.

**Comment by PavelDurov1488** [comment]
Dump is valid, but... >.> people write that image could not be played on real hardware
It's not very valid. Maybe it can generate bad memcard and I see same things on original image
Enhancements off

**Comment by stenzek** [comment]
> It can freezes for >10 sec and then unfreeze. In last case my laptop was fully paralyzed, no reaction on hotkeys like alt+tab

Sorry, I missed this bit.

This sounds like either DuckStation generating bad graphics commands, or a driver bug. Probably more likely the driver, since when an application generates bad commands, the device is removed and it won't recover.

Does the hang happen with the software renderer?

**Comment by PavelDurov1488** [comment]
Yeah, the only render I use is software, but rom could be damaged too

_By the way I though that adapter switcher should be available even in software render, cause it's not fully software. For example, if you switch to Microsoft Basic Render on D3D11, then software, you get big CPU load_

**Comment by stenzek** [comment]
Either a driver bug, or a game freezing-for-a-short-time issue was fixed with https://github.com/stenzek/duckstation/commit/b7752ff30b7ec98825e48e62e18820b29a8a165c
