### ISSUE TITLE
Shadows are broken and there's graphical garbage on the left side of the screen with all hardware renderers in Arcade Gears - Pu-Li-Ru-La (Japan) (SLPS-00928)

### ISSUE THREAD

**Issue by Tiberius1437** [stenzek/duckstation#1399]
OpenGL, D3D11 and Vulkan at native resolution. Notice the broken shadows and the garbage line on the left hand side of the screen?

![Capture3](https://user-images.githubusercontent.com/68873449/103760135-c95bf580-5068-11eb-83bd-d5bc6f7bd52a.PNG)

At x4 resolution shadows are still broken but the garbage on the left is gone.

![SLPS-00928_2021-01-06_21-41-45](https://user-images.githubusercontent.com/68873449/103760487-4a1af180-5069-11eb-8c3a-0f906fa34413.png)

Software for comparison. 

![Capture](https://user-images.githubusercontent.com/68873449/103760161-d2e55d80-5068-11eb-9eaa-a03d7266162d.PNG)

**Comment by stenzek** [comment]
Line on the left side of the screen is probably fixed in the preview build with https://github.com/stenzek/duckstation/commit/f369e3c4763f3ac233cfedc428e93de1dd63da08

**Comment by stenzek** [comment]
![SLPS-00928_2021-01-14_01-02-10](https://user-images.githubusercontent.com/11288319/104469338-237a2f00-5604-11eb-8fd0-230fa40a317a.png)
Seems fine at 1x with hardware on the latest preview build.

**Comment by Tiberius1437** [comment]
No it's even worse now.

![garb](https://user-images.githubusercontent.com/68873449/104486404-d1470700-561f-11eb-9217-d134e89df92b.PNG)

**Comment by Nucleoprotein** [comment]
@Tiberius1437 
Does not looks like 1x 🤔 Please disable all enhancements, filters ect.

**Comment by stenzek** [comment]
Indeed. I suspect MSAA is enabled there, because I get a similar looking image when enabling MSAA.
