### ISSUE TITLE
Duck Station can't recognize XBOX 360 controller

### ISSUE THREAD

**Issue by mohsinous** [stenzek/duckstation#14]
my x360 wired gamepad is working well everywhere except Duck Station, it does not even recognize it!!!

**Comment by stenzek** [comment]
Which OS/frontend? The qt frontend does not have gamepad support yet.

**Comment by mohsinous** [comment]
Windows 10/QT
i am going to test sdl and let you know
thank you

**Comment by mohsinous** [comment]
SDL is working!!!
may i ask why??

**Comment by stenzek** [comment]
Because it's not finished yet. I've got a partial implementation with hardcoded bindings finished, but it's not in master yet because if you make custom bindings, it's not applied. I will finish it soon.
