### ISSUE TITLE
controller not detected any more

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#140]
G-Shark GS-GP702
doesnt detect my controller any more

**Comment by stenzek** [comment]
Which frontend? SDL's controller functionality is disabled until I refactor it. Also, please post the log, it should indicate if the controller is being opened or not.

**Comment by benderscruffy** [comment]
both frontends

**Comment by stenzek** [comment]
Okay, sounds like SDL is returning `-1` as the player ID. I was using this as

**Comment by benderscruffy** [comment]
fixed in the latest master

**Comment by GitHubDan01** [comment]
I am having this same issue the emulator is no longer recognizing my controller input and when trying to configure nothing happens no matter what button i try to assign
