### ISSUE TITLE
Twisted metal world tour (PAL) Music not playing

### ISSUE THREAD

**Issue by Idonttakeordersfromporkfaggots** [stenzek/duckstation#1400]
SCES-00567 Twisted Metal - World Tour (Europe)

every song in the game escept for the character select/options theme does not play

to reproduce the issue just simply boot up the game and either wait a few seconds for when the main menu music would play or just load any level

My enhncement settings are as follows
Internal resolution scale: 9X (4K)
Multisample antialiasing: 32MSSA (the game does however only support up to 8MSSA)
Texture filtering: xBR

True Colour rendering: enabled
Scaled dithering: disabled
Widescreen Hack: enabled
Disable Interlacing: enabled
Force NTSC timings: enabled
Force 4:3 For 24-bit display: disabled
Chroma smoothing for 24-bit display: enabled
Geometry correction: enabled
Culling correction: enabled
Texture correction: enabled
Depth buffer: disabled

i have tested the game with all enhancements disabled and the music still wouldn't play
i have also tested both SDL and Cubeb backends, the result was the same

I'm running the emulator on a windows 10 PC With an Intel core i9-9900KS CPU with a Nvidia Geforce RTX 2080 TI graphics card.
i am using vulcan as the GPU renderer for the emulator.

i am using version: 0.1-2814-g8bb4c110 of duckstation

**Comment by BloodRaynare** [comment]
Make sure your dump and the cuesheet is valid

**Comment by Idonttakeordersfromporkfaggots** [comment]
![image](https://user-images.githubusercontent.com/76909280/103789821-589ce500-5038-11eb-80fa-21efc04944a5.png)
Is this how the dump should look?

**Comment by BloodRaynare** [comment]
According to the redump database, yes.

**Comment by stenzek** [comment]
Right click in game list -> properties -> compute hashes, compare md5 for each track.

**Comment by Idonttakeordersfromporkfaggots** [comment]
![image](https://user-images.githubusercontent.com/76909280/103791061-e6c59b00-5039-11eb-93d3-2a54c59aa198.png)
just checked and it seems that only track 1 matches the hash in the redump

**Comment by stenzek** [comment]
Looks like the pregap might be missing. Try adding `PREGAP 00:02:00` to each track in your cuesheet, **except** the first track, and see if the hashes match up then/the audio plays.

I have a hack in the cue handler to add it when index 0/pregap is missing, but it only applies when there's a single bin file.

**Comment by Idonttakeordersfromporkfaggots** [comment]
does it matter where on each line i add the PREGAP?

**Comment by stenzek** [comment]
Put it before `INDEX 01`. Alternatively if you upload your cuesheet here I can add it for you.

**Comment by Idonttakeordersfromporkfaggots** [comment]
[redump.txt](https://github.com/stenzek/duckstation/files/5776942/redump.txt)
had to convert it to a .txt to upload it

**Comment by stenzek** [comment]
Ah, please upload the cuesheet for the game `Twisted Metal 2 World Tour.cue`.

**Comment by Idonttakeordersfromporkfaggots** [comment]
[Twisted Metal 2 World Tour cue.zip](https://github.com/stenzek/duckstation/files/5777007/Twisted.Metal.2.World.Tour.cue.zip)

**Comment by stenzek** [comment]
Oh, interesting - you have `INDEX 00`, so there is a pregap. Alright, I'll try to look into this soon, it could still be a bad dump, but possibly an emulator bug.

**Comment by stenzek** [comment]
CDDA in this game seems fine to me, so this could just a bad dump. Your track start offsets/lengths are correct though.

**Comment by Idonttakeordersfromporkfaggots** [comment]
Don't suppose you would know any good alternatives to ImgBurn would you?

**Comment by BloodRaynare** [comment]
There's a a tool used by redump guys called DiscImageCreator, however it assumes you own a preservation-grade Plextor CD-RW drives.

**Comment by stenzek** [comment]
I didn't check with a single bin file, might check that tomorrow - but apart from the hash difference (which probably won't affect much), not sure what else is different

**Comment by stenzek** [comment]
Testing with a single bin file and your cuesheet seems fine here too. So yeah, seems like it could be a dump issue.

I guess you could try checking the CD-ROM debug window to see if it's actually playing the audio, e.g. in the menu it should look like this: 
![image](https://user-images.githubusercontent.com/11288319/104148368-bdcc4e00-541d-11eb-8219-243196383629.png)

On Linux I usually use cdrdao, not sure about Windows.

**Comment by Idonttakeordersfromporkfaggots** [comment]
just tested it and as expected it's not playing the track
![image](https://user-images.githubusercontent.com/76909280/104184051-c5cec280-540a-11eb-8883-eb9846c38852.png)

**Comment by stenzek** [comment]
I think I see the issue...you're loading the bin not the cue. Make sure you load the cue - if you're using the qt frontend only cues are shown in the game list.

**Comment by Idonttakeordersfromporkfaggots** [comment]
It worked :)
![image](https://user-images.githubusercontent.com/76909280/104189179-3cbb8980-5412-11eb-9c26-d987e2e6b62b.png)

**Comment by stenzek** [comment]
Great, issue solved :) I probably should've asked which file you were opening to begin with, sorry about that.
