### ISSUE TITLE
Custom game list icons

### ISSUE THREAD

**Issue by fuhuan416** [stenzek/duckstation#1401]
**Emulator version**
0.1-2733-gfa7442fd(dev)

**Primary context**
The first issue: can't correctly identify the file size of ISO. Of course, the image is not PS1, but PS2. My Tekken 4 (PS2's ISO) is placed in a directory. Its file size is about 2GB, which is identified as 4096mb in duck station. In addition, there are XBOX360's ISO games, about 8GB, which are also recognized as 4096mb.

The second issue: I hope you can add the option of recursive scanning or not, because some users have many games in their folders, which will lead to a long scanning time, and the scanning process can not be canceled. I hope it can be improved.

In addition, it would be great if users could add their own custom icons to the game list!

**Comment by stenzek** [comment]
> The first issue: can't correctly identify the file size of ISO. Of course, the image is not PS1, but PS2. My Tekken 4 (PS2's ISO) is placed in a directory. Its file size is about 2GB, which is identified as 4096mb in duck station. In addition, there are XBOX360's ISO games, about 8GB, which are also recognized as 4096mb.

I've never tested any of the image reading code against larger files, so not surprising it breaks. It's not like you could load them anyway.

> The second issue: I hope you can add the option of recursive scanning or not, because some users have many games in their folders, which will lead to a long scanning time, and the scanning process can not be canceled. I hope it can be improved.

It asks you whether you want to scan recursively when you add the directory. Alternatively, go into game list settings, and uncheck the recursive box.

(unless you're on android, in which case it's always recursive)

**Comment by stenzek** [comment]
> In addition, it would be great if users could add their own custom icons to the game list!

https://github.com/stenzek/duckstation/wiki/Adding-Game-Covers

(but, if you want custom "small icons", that's a separate feature)

**Comment by fuhuan416** [comment]
Thank you very much for your reply. I didn't expect these two issues to be fixed long ago. Please forgive me for taking the liberty and thank you again. Duckstation is a stunning work!

**Comment by fuhuan416** [comment]
I'll close this issue
