### ISSUE TITLE
Using mouse causes fps drops and audio crackling in Alien Resurrection

### ISSUE THREAD

**Issue by Nightwalkerrrr** [stenzek/duckstation#1405]
**Game details**
[Serial Code, Region]
SLUS-00633, Alien Resurrection (USA)

**Description of the issue / bug**
Using mouse causes fps drops and audio crackling in Alien Resurrection. I tried resetting settings to default but it wont solve this issue. While playing without using a mouse, everything works fine
https://ibb.co/FnSsspF

**Hardware/software**
Ryzen r5 2600, rx5700, win10 2004
[GPU Renderer - Any]

**Emulator version**
0.1-2854-g24c37324 (dev)

**Comment by stenzek** [comment]
Seems fine here using a mouse.

**Comment by Nightwalkerrrr** [comment]
> Seems fine here using a mouse.

0:00 gamepad. No issues
2:50 keyboard + mouse. Many emulation speed drops and audio artefacts
https://youtu.be/ep1vt7akDpM

**Comment by stenzek** [comment]
Closing as I was unable to reproduce any issue here - may be worth trying without optimal frame pacing.
