### ISSUE TITLE
Crash when pressing Alt + F4

### ISSUE THREAD

**Issue by drdeathd** [stenzek/duckstation#1411]
I'm used to press that to quit the games and it's very annoying because I need to go to the task manager and kill the whole program when crash. I can't bind two keys to the shortcuts neither (maybe something to add) I mean, I can put Alt as a Power off button, but the program shouldn't crash for that crap anyway.

PD: I have the improvements disabled.

**Comment by stenzek** [comment]
I can't seem to reproduce any crash with alt+f4, nor when alt is bound to a hotkey.

It might be a third-party driver - try alt+f4-ing with the controller interface set to none.

**Comment by stenzek** [comment]
Closing due to lack of response. If this is still happening, please attach the crash dump.
