### ISSUE TITLE
NBA Jam Extreme (Japan) needs force interpereter on in per game settings or the players move at super speed

### ISSUE THREAD

**Issue by Tiberius1437** [stenzek/duckstation#1417]
![SLPS-00699_2021-01-09_04-15-29](https://user-images.githubusercontent.com/68873449/104044562-944ecf00-5231-11eb-9e10-0551ee6310d7.png)

**Comment by stenzek** [comment]
What about forcing icache instead? (Game properties). This has less of a performance hit.

**Comment by Tiberius1437** [comment]
Yeah that works too. Both options look like they might be making them move a bit too slow though? I'm not really sure.

**Comment by stenzek** [comment]
Gameini applied in https://github.com/stenzek/duckstation/commit/bc6444b6ff180182904d7f09271e6fd885f38379
