### ISSUE TITLE
Weird automatic update issue

### ISSUE THREAD

**Issue by CountZeroOr** [stenzek/duckstation#1418]
**Description of the issue / bug**
When updating Duckstation's Preview build with the new version after opening duckstation-qt-x64-ReleaseLTCG.exe, the update consistently fails to qcins.dll to the main directory from the UPDATE_STAGING directory.

Screen shots of error messages:
https://imgur.com/aMGyNTW
https://imgur.com/eYf6mYi

**Controller Troubleshoot Report**
N/A

**Steps to reproduce**
Run duckstation-qt-x64-ReleaseLTCG.exe after a Preview Build update and download and install the update

**Enhancements information**
Happens immediately after software is opened, not sure if applicable

**Hardware/software**
Windows 10, Intel Core i5-9600k 3.7 GHz, GTX 1660 Ti

**Emulator version**
Happens on multiple versions of the emulator.

**Additional context**
I have attempted running duckstation-qt-x64-ReleaseLTCG.exe as Administrator but the issue persists. I haven't tried setting updater.exe to run as Administrator under the compatibility menu yet.

**Comment by stenzek** [comment]
You definitely do **not** need administrator rights.

Just checked updates and it seems fine here. Maybe Dropbox is locking the files? Try the process outside of the dropbox folder.

**Comment by CountZeroOr** [comment]
Yeah, the update worked okay outside of the Dropbox folder. I'm also running Backblaze, so I think I'll just rely on that for the install.

**Comment by stenzek** [comment]
For what it's worth, there isn't really any point backing up the duckstation directory - by default everything is saved in the documents directory instead. Can just re-download the program itself if needed :)
