### ISSUE TITLE
Disc swapping doesn't work and crashes whatever game you're currently playing

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#142]
We'll use Animorphs as an example but it's happened with every game I've tried. While I'm playing it I try using the disc swap option to play Castlevania instead. The only thing that happens is the name at the top of the emulator changes and after a few seconds the screen goes black forever. 

![Capture](https://user-images.githubusercontent.com/31968468/77254972-5db2c280-6cb8-11ea-8b1f-8f6c7c0d9454.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/77254980-6d320b80-6cb8-11ea-9a76-04b0da0bb5b2.PNG)

I tried it with Alice in Cyberland and then swapping to whatever this game is called and the same thing happened except this time I got an error message. 

![Capture3](https://user-images.githubusercontent.com/31968468/77254995-7fac4500-6cb8-11ea-9909-a76c91dfeaaf.PNG)

**Comment by stenzek** [comment]
This.. used to work. Will look into it.

**Comment by stenzek** [comment]
Just tried switching discs with FF8 and it works fine.

The assertion probably shouldn't be happening, but it's not surprising that swapping discs crashes a game. I believe the physical console does that too until you reset it.
