### ISSUE TITLE
smaller Audio buffer size

### ISSUE THREAD

**Issue by Alien-Grey** [stenzek/duckstation#1420]
If possible please add smaller Audio buffer size. Improves emulation speed wiith low spec devices.

**Comment by stenzek** [comment]
A smaller buffer size would make it even more sensitive to frame time fluctuations.

Anyway, it won't help here - there's already a buffer size option, but if it's running too slow, it's not like buffering more will increase the speed. You can basically run the desktop version on a potato, if your system is below that spec, I'd consider upgrading. As for phones, targeting super low end devices was never in scope of the projects it's simply not possible to achieve high accuracy at that performance target.

**Comment by Alien-Grey** [comment]
I don't want to buffer more I want to buffer less because 1024 is still a bit too large. Smaller buffer less time spending buffering less slowdown. That's what I'm trying to say here.

**Comment by Nucleoprotein** [comment]
No, it will not cause less slowdown, smaller buffer only means lower latency, and with smaller buffer on slow HW you will get buffer underrunn and audio crackling, nothing more.

**Comment by stenzek** [comment]
The granularity of emulation is a single video frame, so buffering below 44100/60 (735) audio frames is not possible.

**Comment by Alien-Grey** [comment]
Thanks for explaining.

**Comment by Alien-Grey** [comment]
Just wanted to tell you guys that I did fix my issue with Enable Recompiler ICache. Audio buffer size is now back to default 2048 frames
