### ISSUE TITLE
4 Quality of Life Feature Requests

### ISSUE THREAD

**Issue by stagestage** [stenzek/duckstation#1421]
**Feature Requests**
*Using Duckstation on Android Nvidia Shield*

1. Screenshot icons for load states would be a nice improvement
2. When enabling a patch code, don't immediately go back to the game. Sometimes I want to enable two or more cheats and have to open up the in-game Duckstation menu again.
3. Allow binding a controller button for the in-game duckstation menu. (On Android you can press the 'Back' button to access it however my controller doesn't have a back button and I can't find an option to bind a button to 'Back')
4. We have a 'Toggle Fast Forward' option. A 'Toggle Rewind' option would be fantastic.

Thank you

**Comment by stenzek** [comment]
> We have a 'Toggle Fast Forward' option. A 'Toggle Rewind' option would be fantastic.

Rewind would require saving a state periodically, which could cause hitches/stuttering, especially on Android.

**Comment by stagestage** [comment]
> > We have a 'Toggle Fast Forward' option. A 'Toggle Rewind' option would be fantastic.
> 
> Rewind would require saving a state periodically, which could cause hitches/stuttering, especially on Android.

Thanks for your reply! Rewind works in Retroarch with the ReARMed core in Android. I haven't tested any other PS1 cores.

**Comment by stenzek** [comment]
> Thanks for your reply! Rewind works in Retroarch with the ReARMed core in Android. I haven't tested any other PS1 cores.

pcsxrearmed is not a hardware rendered core, so it wouldn't have lag from reading back from the GPU.

**Comment by stenzek** [comment]
I believe all of these are implemented now, bar rewind (not enabled on Android for performance reasons).
