### ISSUE TITLE
[BUG] Suikoden 2, other shadow bug?

### ISSUE THREAD

**Issue by darkxex** [stenzek/duckstation#1423]
![image](https://user-images.githubusercontent.com/17991404/104079423-afa1e600-5201-11eb-8838-7ead536753b3.png)
![image](https://user-images.githubusercontent.com/17991404/104079432-c21c1f80-5201-11eb-91d4-c7f762cb5957.png)
i am using Directx11.
default config of Standalone
**version**
![image](https://user-images.githubusercontent.com/17991404/104079446-de1fc100-5201-11eb-9d52-fd864c06d489.png)

**memory card of inn**
[Suikoden II (Spain)_1.zip](https://github.com/stenzek/duckstation/files/5789968/Suikoden.II.Spain._1.zip)

**Comment by stenzek** [comment]
Does the software renderer have this problem? If I remember correctly the shadows here draw in a specific way which doesn't work well with hardware renderers.

**Comment by darkxex** [comment]
Software
![image](https://user-images.githubusercontent.com/17991404/104079609-c6950800-5202-11eb-943a-2842255452ae.png)
d11
![image](https://user-images.githubusercontent.com/17991404/104079629-ddd3f580-5202-11eb-8107-2170e0cb2270.png)

**Comment by stenzek** [comment]
Yeah, it's likely the same issue I saw in another part of the game. The only way to solve this would be with batch splitting, which would hurt performance. Not sure if it's worth adding an option for it, since it's one game, and doesn't benefit from upscaling/hardware rendering anyway.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/a927bfbe50139e2305aa675a638d57bf2ce4e83e (preview build). Hopefully won't tank performance too much.
