### ISSUE TITLE
Double click to enable/disable fullscreen

### ISSUE THREAD

**Issue by kathyrollo** [stenzek/duckstation#1425]
**Is your feature request related to a problem? Please describe.**
I have 2 monitors. Pressing ESC exits the emulator when I simply want to go back to windowed mode so I can drag it across monitors.

**Describe the solution you'd like**
Double clicking toggles fullscreen mode. Pretty much like PCSX2.

**Describe alternatives you've considered**
The workaround is disabling fullscreen, drag it to the other monitor, and enable fullscreen there.

**Additional context**
Once fullscreen and you decide you want to move it again you have to exit which can be a bit cumbersome.

**Comment by stenzek** [comment]
The mouse buttons are used as controls though (e.g. PS mouse/guncon).

You can use alt+enter to toggle full screen (by default, it's a hotkey so you can rebind it)

**Comment by kathyrollo** [comment]
I can do with Alt + Enter. Thanks!

**Comment by ImSpecial** [comment]
I still hope this could be worked in somehow in the future. I know, I know, another option, but maybe for the option to have a little warning like (may interfear with S-Mouse / GunCon controller games), or have it auto disable for those type games only.

I dunno about others, but I'd get a heck of a lot more use from the double-clicking then the rare rare Guncon games I'd every play. (First time hearing about a GunCon, lol)
