### ISSUE TITLE
Save all DuckStation files in the root directory

### ISSUE THREAD

**Issue by kathyrollo** [stenzek/duckstation#1426]
**Is your feature request related to a problem? Please describe.**
By default, DuckStation creates the folder `C:\Users\<user>\Documents\DuckStation` where all files and settings are saved.

**Describe the solution you'd like**
Instead of creating a separate folder, can all DuckStation files just go into the same folder where the app is? This makes it more portable as it is easy to forget it saves files somewhere else.

**Describe alternatives you've considered**
A feature where users can customise directory paths is also an option.

**Additional context**
DuckStation does not use an installer so people normally assume all the stuff they need to bring it around (like thumbdrive editions) is all in one place.

**Comment by ggrtk** [comment]
See https://github.com/stenzek/duckstation#user-directories for portable mode.

**Comment by andercard0** [comment]
Please, create a **portable.txt** file on Duckstation's root directory!

**Comment by stenzek** [comment]
Yup, or start with `-portable`.

If you already have data in the documents directory, simply move it all into the executable directory. The presence of `settings.ini` is sufficient for triggering portable mode.

(I had plans to make this an option in the tools menu, but just procrastinated doing the actual file move, since it's a bit risky without copying-then-deleting, e.g. if the user runs out of space mid-way).

**Comment by stenzek** [comment]
> A feature where users can customise directory paths is also an option.

Sorry, forgot to address this - offering this option is a bit of a chicken-and-egg problem, it checks for `portable.txt` or `settings.ini` to whether to use portable mode, otherwise uses the documents directory. But if it was somewhere else, it wouldn't know where to look in the first place, so it would still end up falling back to documents :)

I suppose you could have two settings files, one in the program directory, telling it where to load the rest from, or use the registry, but it seems a bit messy. Probably easier to just use portable mode and move everything to where you want it.

**Comment by PugsyMAME** [comment]
Another option is to move the folder to somewhere else and make a symlink to the folder in the original position. That way, duckstation still think the files and folder is on the C drive but the files are somewhere else.

For example

I moved my DS folder to D:\Duckstation 

and then I opened a cmd line in administrator mode and ran something like:-

mklink /J C:\Users\<user>\Documents\DuckStation  D:\Duckstation

Obviously, it goes without saying make a backup of the folder before you do anything

**Comment by kathyrollo** [comment]
HI @stenzek ,

https://github.com/stenzek/duckstation/releases/tag/latest

Do my eyes deceive me or the `-portable` is missing?

![Annotation 2021-01-10 101128](https://user-images.githubusercontent.com/28589393/104110484-4a96df00-532c-11eb-860e-d43d86857a93.png)

I was using the `windows-x64` zip. Can you link to the portable download?

**Comment by andercard0** [comment]
> Hi @stenzek ,
> 
> https://github.com/stenzek/duckstation/releases/tag/latest
> 
> Do my eyes deceive me or the `-portable` is missing?
> 
> ![Annotation 2021-01-10 101128](https://user-images.githubusercontent.com/28589393/104110484-4a96df00-532c-11eb-860e-d43d86857a93.png)
> 
> I was using the `windows-x64` zip. Can you link to the portable download?

You need to create a txt file named as portable.txt inside of Duckstation's root directory after download and  unzip as follows 

![image](https://user-images.githubusercontent.com/43047877/104110637-5c3e9f00-52b8-11eb-81f8-3cbe48e448bf.png)

**Comment by ggrtk** [comment]
> Do my eyes deceive me or the `-portable` is missing?

`-portable` is a command line option for forcing portable mode.

Alternatively, if you follow the directions in the README and create an empty `portable.txt` file in the same directory as the executable, DuckStation will run in portable mode. You can also copy the `settings.ini` from your `%USERPROFILE%\Documents\DuckStation` directory into the executable directory and it will automatically run in portable mode that way as well.

**Comment by kathyrollo** [comment]
> Yup, or start with `-portable`.
> 
> If you already have data in the documents directory, simply move it all into the executable directory. The presence of `settings.ini` is sufficient for triggering portable mode.
> 
> (I had plans to make this an option in the tools menu, but just procrastinated doing the actual file move, since it's a bit risky without copying-then-deleting, e.g. if the user runs out of space mid-way).

Hi @stenzek , this worked, thanks! It was able to pick up my `settings.ini` so I did not have to create `portable.txt` at this point. The savestates also went to the root dir now.

Yes an option in the Tools menu sounds great as it seems users wouldn't really know unless they explicitly look for it in the docs (bit of UX improvement). Otherwise, all good.

Cheers!

**Comment by jwow999** [comment]
Hi, thanks stenzek as well as everyone else on this thread.  Can someone step-by-step explain how to change the directory to one of my choosing? I do not understand what an executable directory nor a root directory. As far as I'm concerned, every directory on my PC is executable.
