### ISSUE TITLE
Tekken3 graphic issues

### ISSUE THREAD

**Issue by fuhuan416** [stenzek/duckstation#1427]
ISO region: Tekken3 (Jpan, Asia)
Emulator version: 0.1-2896-g6fbffb6f (dev)
Renderer backend selected: Vulkan
GPU: nVidia GTX 1650
Do not do anything, the character is normal. Once in motion, the character will appear as in the second picture.
![01](https://user-images.githubusercontent.com/6281757/104107325-3a640d00-52f6-11eb-8652-ecf836c536fc.png)
![02](https://user-images.githubusercontent.com/6281757/104107329-3cc66700-52f6-11eb-94e2-7ffd55cca2d0.png)

**Comment by fuhuan416** [comment]
![01](https://user-images.githubusercontent.com/6281757/104119792-10016680-536d-11eb-8e08-b5960cdb92a9.png)
![02](https://user-images.githubusercontent.com/6281757/104119794-1394ed80-536d-11eb-94ed-377bd1f15466.png)
This time, I turned off the MOD and unzipped the game from the zip pack again. Japan version still has this problem, not at the beginning, but after a few minutes of play, it appears for a while, then disappears, then reappears.

**Comment by stenzek** [comment]
Can't see any of these issues on the US version. Do you have any enhancements enabled?

**Comment by fuhuan416** [comment]
> Can't see any of these issues on the US version. Do you have any enhancements enabled?

Yes, I've checked a lot of enhancements, this time I used USA version, but still like that. Maybe i should to unchecked 'Geomatry Correction' ?
![picture](https://user-images.githubusercontent.com/6281757/104225436-59db7100-5481-11eb-9668-78ca099bb48a.png)

**Comment by Nucleoprotein** [comment]
You have Depth Buffer enabled ... 🤦 Did you even read note before creating bug report? 
You should test without any enhancements before creating bug report, as  ar they are not warranted to work, and you issue is cause by "Depth Buffer" which is recommended to be disabled.

**Comment by fuhuan416** [comment]
> You have Depth Buffer enabled ... 🤦 Did you even read note in bug report template?
> You should test without any enhancements before creating bug report, as they are not warranted to work, and you issue is caused by "Depth Buffer" which is recommended to be disabled. When you hover over option there is a description with recommended value at bottom.

Thank you~ I will pay attention to the description of the options in the future, I will close this report, sorry~ I wish Duckstation grow and develop~

**Comment by Nucleoprotein** [comment]
I'm sorry too, maybe I was little too harsh. 
Depth Buffer is very very experimental feature, it will cause issues in many games.
