### ISSUE TITLE
Build failure on Linux

### ISSUE THREAD

**Issue by spinktvis** [stenzek/duckstation#1428]
While building duckstation on Arch Linux I receive the following build error:
```
[ 19%] Building C object dep/xxhash/CMakeFiles/xxhash.dir/src/xxh_x86dispatch.c.o
/duckstation-git/src/duckstation/dep/xxhash/src/xxh_x86dispatch.c:85:4: error: #error "Do not compile xxh_x86dispatch.c with AVX enabled! See the comment above."
   85 | #  error "Do not compile xxh_x86dispatch.c with AVX enabled! See the comment above."
```
When I instruct cmake to disable AVX by passing the following commands
cmake -DENABLE_AVX=FALSE -DENABLE_AVX2=FALSE -DARCH_FLAGS=x86-64

it then tells me;
```
CMake Warning:
  Manually-specified variables were not used by the project:

    ARCH_FLAGS
    ENABLE_AVX
    ENABLE_AVX2

```
So it seems to be hardcoded somewhere in the duckstation cmake files. Can this please be adjusted to at least allow disabling AVX or setting the Arch flags.

**Comment by stenzek** [comment]
You must be setting march or avx somewhere else, because it builds fine in Ubuntu.

**Comment by Nucleoprotein** [comment]
Check your CFLAGS and CXXFLAGS if you dont have **-march=native** or **-mavx*** there

**Comment by spinktvis** [comment]
Thanks for the quick replies. Sorry, it seems I wasn't clear enough in my original post. Yes, I have set my global compiler flags that do enable AVX. However, since I am building packages on the regular I won't be changing them, since that would be a tedious process to manually do all the time, next to trying to remember which projects need which compile flags. Besides, that is what the CMAKE files are for, so that a user can either pass flags to it, in this case to disable AVX, or that CMAKE includes the proper flags by default. Anyhow, its a quick fix, in CMakeLists.txt add the following switches;

```
line 166 |    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} **-mno-avx** -Wno-switch")
line 167 |    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} **-mno-avx** -Wno-switch")
```

This will prevent the use of AVX in compiling duckstation, while still respecting a users set compiler flags. After setting this, it compiles successfully while still making use of my global compiler flags that are set. I hope you can include this fix, I would make a pull request but I am unfamiliar with how.

**Comment by Nucleoprotein** [comment]
or define `XXH_X86DISPATCH_ALLOW_AVX` 
https://github.com/stenzek/duckstation/blob/master/dep/xxhash/src/xxh_x86dispatch.c#L84

**Comment by spinktvis** [comment]
That's probably even a better solution, thanks so much for the input. Hopefully the dev can use that.

**Comment by stenzek** [comment]
I don't like the idea of using high targets globally. It makes the binary impossible to run on downlevel CPUs. That's why the way that xxhash works here is good - it dynamically dispatches to the correct function based on CPU features at runtime.

**Comment by stenzek** [comment]
I'll consider setting the macro, but I'm still not convinced that it's worthwhile. If you're forcing compiler flags on packages which weren't ever tested with them, you're going to run into issues sooner or later, and that is not the developers fault - especially if you're running an unsupported configuration.

**Comment by spinktvis** [comment]
Awesome, I'd appreciate that. I'm strictly building packages for my own target machine (march=ivybridge), so no worries about the binary not being able to run on other CPU types. Unfortunately I do not have a AVX2 or higher CPU yet, else it'll probably have compiled without issues if I understood the comments in the source of xxhash correctly. So disabling AVX sounds good for me, since it only affects AVX, and not SSE, AVX2 and higher.

**Comment by stenzek** [comment]
For what it's worth, you won't see any increase from changing the target/cflags. The hot code in DuckStation is either JIT generated, or code which is not autovectorizable.

**Comment by spinktvis** [comment]
Closing this, compiled successfully, quickly tested FF7, works perfectly so far. Thanks for the quick fix.
