### ISSUE TITLE
OpenGL renderer has textures all messed up on macOS

### ISSUE THREAD

**Issue by tonyunreal** [stenzek/duckstation#1434]
**Game details**
SLPS-01800, R4 - Ridge Racer Type 4 (Japan, Asia)
SLPS-02406, Dai-2-Ji Super Robot Taisen (Japan)

The issue is present in every game I tested, using the above two games for screenshot.

**Description of the issue / bug**
Both the standalone duckstation emulator and the libretro core show disoriented textures, in both 2d and 3d games, when hardware renderer is selected. 

The screenshots below were taken with some enhancement options on, but the issue were present even with "disable all enhancement" checked.

![Screen Shot 2021-01-11 at 11 49 34 AM](https://user-images.githubusercontent.com/3460639/104151670-958e2080-5418-11eb-8ace-71481848ed51.png)

![Screen Shot 2021-01-11 at 2 08 11 PM](https://user-images.githubusercontent.com/3460639/104151677-9aeb6b00-5418-11eb-9655-21fcd31a4859.png)

![Screen Shot 2021-01-11 at 2 03 59 PM](https://user-images.githubusercontent.com/3460639/104151683-9e7ef200-5418-11eb-98fa-2d708a03ec31.jpg)

Software renderer in the standalone duckstation emulator works fine. Software renderer with the libretro core has the whole screen diagonally disoriented which might be a different issue.

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?

No.

2. Which controller backend are you using in general settings

SDL

**Hardware/software**
Mac mini (2020, M1), macOS Big Sur 11.1
GPU Renderer - OpenGL

**Emulator version**
0.1-2862-g6fbffb6f (dev) (standalone)
0.1-2854-g24c37324 (libretro core)

**Comment by stenzek** [comment]
Known issue - it's a bug in the OpenGL driver on macOS. Use the Vulkan/MoltenVK renderer instead.

**Comment by stenzek** [comment]
> Software renderer with the libretro core has the whole screen diagonally disoriented which might be a different issue.

This should be reported to the libretro repository, the core version is not supported here.

**Comment by tonyunreal** [comment]
> Known issue - it's a bug in the OpenGL driver on macOS. Use the Vulkan/MoltenVK renderer instead.

Got it. The MoltenVK renderer seemed to be working in the standalone DuckStation, at least in windowed mode.

**Comment by stenzek** [comment]
I'm aware of which commit broke it, so it could potentially be worked around with an #ifdef.. but there's other issues with the GL driver on macOS that I'm not sure if it's worth adding a hack. Plus I have no way to test it.

**Comment by stenzek** [comment]
This will likely be fixed by https://github.com/stenzek/duckstation/commit/6c05413220112cb898e3951f5e353a9b7c312f2b, but I can't confirm as I don't have a Mac.
