### ISSUE TITLE
"Fullscreen UI" Mode - Feedback/Ideas

### ISSUE THREAD

**Issue by stenzek** [stenzek/duckstation#1439]
Been working on this on and off over the last couple of days. Opening an issue so we can discuss ideas and post feedback.

This mode will be available in both the "nogui" frontend, as well as the Qt frontend (similar to how Steam can launch big picture mode). The "nogui" frontend probably isn't the best name, there's still a UI, it just doesn't depend on any system interface like Qt, and can run fullscreen on a framebuffer.

This will probably be the final nail the coffin for the current SDL frontend, SDL will be either replaced with the NoGUI binary, or not included in the download to reduce the size.

The design is inspired by a cross of Android and the current Qt frontend. It's designed using a reference resolution of 1280x720, but scales perfectly in either direction as long as it's a 16:9 display. Other aspect ratios are padded appropriately. Would you believe it's built using ImGui? :)

Some screenshots to get started:

(ignore the menu bar, the final version won't have that - it's just because I started with the current SDL frontend).

Main menu/landing page:
![image](https://user-images.githubusercontent.com/11288319/104195923-f3e5ee00-546e-11eb-89af-fedb93ffb095.png)

Settings interface:
![image](https://user-images.githubusercontent.com/11288319/104195957-ff391980-546e-11eb-8931-1990802d6085.png)

Settings - changing a choice item:
![image](https://user-images.githubusercontent.com/11288319/104196003-0bbd7200-546f-11eb-9714-6c6c4743f8f3.png)

Loading state without a game started:
![image](https://user-images.githubusercontent.com/11288319/104196079-1aa42480-546f-11eb-93cd-68623ac7a8a9.png)

**Comment by ds22x** [comment]
I'm really liking it so far.
The sooner this gets included, the better.

**Comment by stenzek** [comment]
Game list work in progress. I'll probably replace the flag with flag+compatibility stars.

Will probably add a grid view as well at some point.

![image](https://user-images.githubusercontent.com/11288319/104343323-8659c080-5547-11eb-906a-128b2fde1dbc.png)

**Comment by ds22x** [comment]
Seems like there's plenty of space for the stars anyway, so why not.

**Comment by andercard0** [comment]
Yo, @Stenzek

Some of my thoughts about this brilliant new NoGui (DuckPictureMode):

- Main Menu is okay but I'd like to see less information under the options
(as mine picture shows)

![Suggestions](https://user-images.githubusercontent.com/43047877/104369956-f42cca80-54fc-11eb-8171-36cf0b6c9805.png)

Been working on some buttons - as follows if you like those could export to test.

- Config. Icon
![Configuration Button Example](https://user-images.githubusercontent.com/43047877/104369987-fe4ec900-54fc-11eb-93e7-2161eed5019a.png)

- Game List
![Game List Button Example](https://user-images.githubusercontent.com/43047877/104369988-fee75f80-54fc-11eb-8724-37cca2ace1e0.png)

- Resume Icon
![Resume Button Example](https://user-images.githubusercontent.com/43047877/104369992-ff7ff600-54fc-11eb-84ff-4f1915e95265.png)

- Ability to hide those Flags + starts

- Had some insights in regards loading state page as well as follows:

![Suggestions3](https://user-images.githubusercontent.com/43047877/104370044-0eff3f00-54fd-11eb-9615-7a4f6219ec4a.png)


Again, less info under those buttons would be appreciated too or maybe
the ability to us, (users) turn those info On or Off as we pleased.

Note: font I'm using is "Zrnic Regular" if needed. For some weird reason could not attach it here - Shrugs...
Any suggestions in regards those buttons / icons colors or whatever let me know here or in Discord. I'll keep updating my suggestions here if they could be considered of if they are useful.

**Comment by vanfanel** [comment]
@stenzek Looks truly fantastic! I am building the latest NOGUI branch to try it just now!

My main concern with this backend (vs the libretro backend, for example) is, as you know, the framerate differences with the host machine, that causes some small "hiccups" in the framerate that I can perceive very clearly.
RetroArch manages it by syncing to the native display video rate, and resampling the audio to compensate for the difference vs the original system.

I seem to recall that you sync on audio, carry on with the video refresh difference, and just repeat a frame when there's nothing else new to draw. Am I right?

So, the only way around this would be a video mode which fits the original PSX video frequency. Is there such a mode on the DMT/CEA specifications? Not the same mode, but with the same vrefresh (drmModeModeInfo structs have precise refresh rate info in the vrefresh field, with 3 decimal digits in the form of a rational number, so 60.017 is 60017 in a drmModeModeInfo struct vrefresh member).

Another possibility would be to have a "sync on video" option, with audio simply "accelerated" to compensate, so the emulated system would internally run at the original PSX speed, but "externally" it would run at the same rate as the host physical display.

**Comment by stenzek** [comment]
> @stenzek Looks truly fantastic! I am building the latest NOGUI branch to try it just now!
> 
> And I see you have also added an option to sync to host refresh rate! Just PERFECT, I can't ask for anything more, I am in PSX heaven :D
> EDIT: Seems like the "sync to host refresh rate" is not yet activated on the NOGUI branch. Can't wait to test it!
> 
> Is the menu already available in the NOGUI backend? What's the key to enter it, please?

Nogui branch hasn't been rebased in some time. I'm working on there things independently and will merge eventually.

**Comment by vanfanel** [comment]
So, no menu available ATM in the NOGUI branch?

**Comment by stenzek** [comment]
No, not yet. I'll probably merge into master before rebasing nogui, since that has to have the evdev stuff merged in first too.

**Comment by vanfanel** [comment]
> No, not yet. I'll probably merge into master (as SDL) before rebasing nogui, since that has to have the evdev stuff merged in first too.

Great! I will stay tuned!

**Comment by stenzek** [comment]
Some more updates:

Main menu with icons:
(planning on making the logo customizable)
![image](https://user-images.githubusercontent.com/11288319/104620220-7a523800-56da-11eb-9397-e80f0d34884e.png)

Settings menu with icons:
![image](https://user-images.githubusercontent.com/11288319/104620372-a7064f80-56da-11eb-9145-576b15c10599.png)


Game list with index on right:
![image](https://user-images.githubusercontent.com/11288319/104620292-90f88f00-56da-11eb-9be9-a97b8cdcd08f.png)


Ingame/quick menu:
![image](https://user-images.githubusercontent.com/11288319/104619768-f730e200-56d9-11eb-9f6b-dfd04d0a71be.png)

**Comment by vanfanel** [comment]
Is that the Fat Chocobo from Final Fantasy IV? 


Also, I built this today on the Pi4. It runs fullspeed except.. FFVII battle loading sequence with the OpenGL renderer. Strangely, that runs fullspeed on software mode. But the BIOS logo has small audio dropouts in software mode.

Out of curiosity since you know PSX internals very well: what's so special about the FFVII whirl sequence when it loads a battle? It's not CDROM access since I tried pre-loading the image in RAM, etc. It must be something specially demanding with the Pi graphics system in OpenGL rendering, more demanding than Tekken 3 in fact!

**Comment by stenzek** [comment]
> Also, I built this today on the Pi4. It runs fullspeed except.. FFVII battle loading sequence with the OpenGL renderer. 

Don't use OpenGL, the Pi has a few driver bugs which cause rendering errors. Use Vulkan, it doesn't have these issues.

> Out of curiosity since you know PSX internals very well: what's so special about the FFVII whirl sequence when it loads a battle? 

Might just be the framebuffer copies.

**Comment by vanfanel** [comment]
> Might just be the framebuffer copies.

But that massive slowdown only happens with the OpenGL renderer. I guess because framebuffer copies is a VERY demanding operation in OpenGL? In software mode, it doesn't happen.

Also, is this branch working with VULKAN already? Is VULKAN faster than Software on the Pi4? On the libretro port of Duckstation, I used to find Software faster than VULKAN.

**Comment by fr500** [comment]
Looks amazing, kudos!
That's how a quick menu should look like, just what's relevant.

**Comment by stenzek** [comment]
Latest update: almost finished, just need to make OSD messages larger, add a pause indicator, controller mapping, and hook it up to the Qt frontend.

Grid view for games won't be in the initial release, but will be added later.

![image](https://user-images.githubusercontent.com/11288319/105872078-b627be80-6045-11eb-86a0-97fdee2791e4.png)
![image](https://cdn.discordapp.com/attachments/695640472202379428/803657557527756800/unknown.png)
![image](https://cdn.discordapp.com/attachments/695640472202379428/803657573215502386/unknown.png)
![image](https://cdn.discordapp.com/attachments/695640472202379428/803657800853094439/unknown.png)
![image](https://cdn.discordapp.com/attachments/695640472202379428/803657988782817340/unknown.png)
![image](https://cdn.discordapp.com/attachments/695640472202379428/803657909019738152/unknown.png)
![image](https://cdn.discordapp.com/attachments/695640472202379428/803658073167626250/unknown.png)

**Comment by andercard0** [comment]
ah, cool. but don't forget to remove this frown face from there :HaroldSmile

![image](https://user-images.githubusercontent.com/43047877/105881750-a5def780-5fe3-11eb-81ff-daa2ce51c462.png)

**Comment by stenzek** [comment]
Closing as the UI is now in master. Future suggestions can go in the main https://github.com/stenzek/duckstation/issues/362 thread.

I'll probably write up a guide for building with DRM/KMS and running directly on the framebuffer on Linux once I've ironed out some of the issues.

**Comment by vanfanel** [comment]
@stenzek Congratulations on this VERY interesting development! :)

**Comment by iwubcode** [comment]
> Would you believe it's built using ImGui? :)

I would because it's you but I still said *wow* when I saw this.  ImGui looks super ugly so I'm very curious how you made it look so pretty.

This was exactly what I was thinking about for the in-game menu for Dolphin.  Maybe I'll have to get back to it at some point using this as inspiration.

Nice work!!

**Comment by stenzek** [comment]
Fwiw, all the widgets and dialogs are isolated away, so easy to reuse. But it's still a decent chunk of code.
