### ISSUE TITLE
Graphics are broken in Atlantis - The Lost Tales (Europe) using D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#144]
The background is missing. The mouse trails all over the place.

![Capture](https://user-images.githubusercontent.com/31968468/77257284-6eb70000-6cc7-11ea-9657-2c3e5ab8ae96.PNG)

The text overlaps

![Capture2](https://user-images.githubusercontent.com/31968468/77257309-8d1cfb80-6cc7-11ea-90e0-8fb9c9eda265.PNG)

Here's what it looks like with OpenGL

![Capture4](https://user-images.githubusercontent.com/31968468/77257321-a2922580-6cc7-11ea-88a0-bc86ba919471.PNG)

**Comment by stenzek** [comment]
I feel like these might be unique to Windows 7.... I haven't been able to reproduce any of them.

**Comment by stenzek** [comment]
I'm collapsing this to https://github.com/stenzek/duckstation/issues/153 as it seems to be the same issue. If it is a different issue and persists with the OpenGL/Software renderers, please re-open.
