### ISSUE TITLE
Linux Compile Error:  -mcpu=cortex-a7 conflicts with -march=armv7-a

### ISSUE THREAD

**Issue by 2play** [stenzek/duckstation#1440]
Compile fails with:

[228/369] Building CXX object dep/vixl...xl.dir/src/aarch32/disasm-aarch32.cc.o
cc1plus: warning: **switch -mcpu=cortex-a7 conflicts with -march=armv7-a switch**
ninja: build stopped: subcommand failed.

Any tips to complete the compile?

**Comment by stenzek** [comment]
Don't override the cflags, or change the lines here: https://github.com/stenzek/duckstation/blob/c18fa06f0c871ed99022d5daed29dfc58c0b20a4/CMakeLists.txt#L195-L196

**Comment by stenzek** [comment]
Also not, if you are compiling on a Cortex-A7, unless it's very highly clocked I doubt it'll be fast enough to run smoothly.

**Comment by 2play** [comment]
@stenzek  Thank you for quick reply!
im compiling all defaults on a pi4 2GB @ 2000MHz

**Comment by stenzek** [comment]
I'd recommend using a 64-bit OS, you'll get better performance. But 32-bit on a Pi4 is okay, I developed the armv7 recompiler on one.

Try dropping the `-march=armv7-a` from the CFLAGS in the CMakeLists I guess. But strange that you need it, it overrode fine for me.

**Comment by 2play** [comment]
@stenzek 
ive disabled and worked!
thank you!
