### ISSUE TITLE
Final Fantasy VII (Europe) - SCES-00867 - Image cut off

### ISSUE THREAD

**Issue by Alien-Grey** [stenzek/duckstation#1443]
With the game Final Fantasy VII (Europe) the image is cut off at the left side. Screenshot taken with all enhancements disabled. happens with every renderer.

![SCES-00867_2021-01-11_18-59-20](https://user-images.githubusercontent.com/25705769/104220693-288e8100-5440-11eb-9ab9-3ed887bf6c81.png)

**Comment by stenzek** [comment]
Not a bug - just overcropping - it's fine with "None". Some TVs might have looked like this too.

I'll push a gameini update later which adjusts the range for the FF7 discs.

**Comment by Alien-Grey** [comment]
If you set cropping to all borders it's much bettter and that's probably how it should look.

There's also something else with this game that got me confused. It didn't always run smooth but disabling use read thread (asynchronous) seems to fix this.

**Comment by stenzek** [comment]
All borders doesn't preserve the original AR. Yes, many PAL releases were letterboxed and don't look great, but the emulator is correct here.

**Comment by Alien-Grey** [comment]
Checked with real hardware on an old PAL CRT TV. It's exactly the same so the emulator is correct like you said.

**Comment by stenzek** [comment]
Still, in this case I think offsetting the image is worth it, even if it's not "pure". (you can always disable apply game settings, or set the range to 0-0 yourself)

**Comment by Alien-Grey** [comment]
That's right because with Crop set to None or All Borders it doesn't fix everything. When the image is rendered at 730 x 480 pixels ithere doesn't seem to be an issue. But when it's rendered at 640 x 480 there is as can be seen in this screenshot.

![SCES-00867_2021-01-16_17-54-50](https://user-images.githubusercontent.com/25705769/104818064-7aab1a00-5825-11eb-845f-5b72c7202bc0.png)
