### ISSUE TITLE
Audio issue with "Resampling" option in Audio Settings turned on.

### ISSUE THREAD

**Issue by dark-mad-hatter** [stenzek/duckstation#1444]
**Game details**
Tested on these games:
SLUS-01017 Alundra 2 - A New Legend Begins (USA)
SLUS-01041 Chrono Cross (USA) (Disc 1)
SCUS-94488 Gran Turismo 2 (USA) (Simulation Mode)
just to name a few

**Description of the issue / bug**
With the option "Resampling" turned on in Audio Settings, increasing or decreasing the output volume slider will mute the audio.

**Steps to reproduce**
1. Start any game (I'll use Gran Turismo 2 for example)
2. Open System Settings, go to Audio Settings.
3. Increase or decrease Output Volume with Resampling turned on.
4. There will no longer be any audio

**Enhancements information**
Disable all enhancements in Advanced Settings turned on. All other advanced settings at default.

**Hardware/software**
Windows 10, version 20H2
Intel i5-7500
Nvidia GTX 1060 6GB
16G RAM

**Emulator version**
preview build
0.1-2910-ga0a24c77 (master)

**Additional context**
Ticking and unticking the "Resampling" or "Sync to Output" option while the game is running will fix the audio.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/b5ffbfe826b01f7e13eff11e67a7424bc74e0662
