### ISSUE TITLE
TEKKEN 3 Credits Crash

### ISSUE THREAD

**Issue by MarinDont** [stenzek/duckstation#1445]
ISO Region: USA
Enhancements: None (default settings)
Backend: D3D11
GPU: nVidia GTX 1050 ti

Tekken 3 Crashes to black screen if the ending cutscene of a character is watched to the end and the narrator says "The King of Iron Fist Tournament" then the game crashes.

If the cutscene is skipped there is no problem.

![image](https://user-images.githubusercontent.com/51217393/104259388-f16f9e00-5446-11eb-8c83-8995eb4b361a.png)

Hope the info helps!

**Comment by Kurayami7** [comment]
What does the log say? Go to advanced settings, click "show debug menu" set it to debug and click " log to system console" Then you should be able to see any error messages as the game crashes.

**Comment by MarinDont** [comment]
This is what it shows:
![image](https://user-images.githubusercontent.com/51217393/104260278-cd14c100-5448-11eb-878a-2e1f39e2d24b.png)

**Comment by Alien-Grey** [comment]
Did you use bin/cue files?

You need the cue file because Tekkken 3 has two CDDA tracks that are used for the ending credits.

**Comment by foxsevent** [comment]
Yeah this is most likely a broken copy of Tekken 3, this is a very old issue that everyone was reporting for ePSXe constantly.

I can confirm that ePSXe and Duckstation don't crash on the credits scene of Tekken 3 with a proper copy.

**Comment by stenzek** [comment]
Thanks @foxsevent.

@MarinDont please compute hashes for your game (right click in game list -> properties -> compute hashes), and compare MD5 to http://redump.org/disc/1464/

If the problem still persists with a good dump, please let me know and I'll re-open/investigate.
