### ISSUE TITLE
BIOS sound loops infinitely in Aging Disc (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#145]
Haven't a clue how these tests work or if the emulator passes but I can tell you for certain that the BIOS sound shouldn't be playing forever. 

![2020-03-24_05-18-29](https://user-images.githubusercontent.com/31968468/77349345-ffa4de80-6d8e-11ea-92a6-28ecc4d1db1f.png)

**Comment by stenzek** [comment]
This is likely the same issue as the other games (reverb). As a workaround, use fast boot.
