### ISSUE TITLE
Mute all sound and Fast Forward Sound volume bug

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#1450]
Two small bugs regarding these two.

First "Mute all sound" is reset each time I change any option in settings, basically if I have the sound muted and go change any option in settings the game sound gets unmuted.

Second "Fast Forward Sound Volume" only works if the Fast Forward speed is set to unlimited, setting the fast forward speed to 300% for example sets the "Fast Forward Sound Volume" to max and it can't be changed.

Cheers.

**Comment by stenzek** [comment]
I think was fixed already in the preview build: https://github.com/stenzek/duckstation/commit/b5ffbfe826b01f7e13eff11e67a7424bc74e0662

**Comment by foxsevent** [comment]
> I think was fixed already in the preview build: [b5ffbfe](https://github.com/stenzek/duckstation/commit/b5ffbfe826b01f7e13eff11e67a7424bc74e0662)

Yup, using the newest preview build the second issue is fixed not the first thou.

**Comment by stenzek** [comment]
It's actually working as intended - the mute hotkey is only a temporary toggle. Settings get reloaded/reapplied when you change anything, which overwrites the temporary value from the hotkey.

**Comment by foxsevent** [comment]
> It's actually working as intended - the mute hotkey is only a temporary toggle. Settings get reloaded/reapplied when you change anything, which overwrites the temporary value from the hotkey.

Fair enough,

Cheers.
