### ISSUE TITLE
Formation Soccer '97 - The Road to France (Japan) looks a lot better with crop mode set to "all borders"

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1452]
Only Overscan area.

![SLPS-00762_2021-01-13_11-25-59](https://user-images.githubusercontent.com/77198254/104390742-803d0180-5592-11eb-88a4-d5b12a420ace.png)

![SLPS-00762_2021-01-13_11-25-13](https://user-images.githubusercontent.com/77198254/104390753-859a4c00-5592-11eb-98b4-b1b0eae9d2a7.png)

All borders.

![SLPS-00762_2021-01-13_11-26-06](https://user-images.githubusercontent.com/77198254/104390765-8df28700-5592-11eb-98d4-cc77c3faabf0.png)

![SLPS-00762_2021-01-13_11-25-00](https://user-images.githubusercontent.com/77198254/104390771-92b73b00-5592-11eb-9d12-dee149ba0c0f.png)

**Comment by stenzek** [comment]
Not really a bug, for these games you probably want "none" (all borders generally doesn't use the correct aspect ratio).
