### ISSUE TITLE
Wrong subtitle and a cutscene that doesn't play correctly in Silent Hill (USA)

### ISSUE THREAD

**Issue by GoodWall533** [stenzek/duckstation#1457]
Already spoke with Stenzek about this in the Discord but I decided to open this anyway. The game softlocks in a cutscene and shows the wrong subtitle but you can skip it to continue playing. I played the game with no issue up until now. Had no enhancements enabled, had them disabled from the start. Checked the dump and everything's fine. According to Sten, it could be either a emu bug or something with the save game.

**Comment by foxsevent** [comment]
Could you maybe share what cut scene you're talking about?

**Comment by GoodWall533** [comment]
Right. Sorry, forgot to mention which cutscene. It's the one with Lisa in the alternate hospital after the Cybil boss fight. Here's a pic of the cutscene in question:
![2021-01-10_2](https://user-images.githubusercontent.com/73701483/104513232-12163000-55ce-11eb-969f-b64f80345c29.png)

**Comment by foxsevent** [comment]
Ah now that's an interesting bug.
For debugging purposes here;s a memory card with a save file right before that bug and a video guide how to get there.
https://youtu.be/HRYpJv4xA88
[Silent Hill (USA)_2.zip](https://github.com/stenzek/duckstation/files/5811332/Silent.Hill.USA._2.zip)

Cheers.

**Comment by Richard-L** [comment]
Oh does it let you continue playing now? Was just a permanent hang for me at the end of that cutscene.

**Comment by foxsevent** [comment]
> Oh does it let you continue playing now? Was just a permanent hang for me at the end of that cutscene.

Oh no it still hangs, you just can skip the cut scene even after the hang up.

**Comment by GoodWall533** [comment]
It does let you continue but only if you skip the cutscene. Otherwise it just stays there.

**Comment by GoodWall533** [comment]
Did anyone test if this bug still happens in the EU version?

**Comment by Sheriu3** [comment]
I just got to this part of the game on the EU version and it's the same for me.

**Comment by stenzek** [comment]
Looks like it's a CPU timing issue. Making RAM reads take one cycle longer forcing icache/using the interpreter fixes the issue for me.

I need to run some more hardware tests regarding RAM timing, but yeah, should be able to fix soon.

In the meantime, you can just skip the cutscene.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/9d0c5d4c6d5684ceec5e0ff7b99e0bd91de692f2
