### ISSUE TITLE
DexDrive PSX Save File

### ISSUE THREAD

**Issue by alyssonnaide** [stenzek/duckstation#1458]
Hi everyone

I newbie in here and my english is far for good.

First, i wanna thanks the developers for excellent work on DuckStation.

My request is, if possible, the DuckStation may read memory card files, like .gme, DexDrive PSX save file, this allow we download some save files from some sites like, https://gamefaqs.gamespot.com/.

All the best and thanks again.

alyssonnaide

**Comment by stenzek** [comment]
This is already possible - open the memory card editor and select import file, then save.

Unless you're using android - the memory card editor is not available there yet. But you can edit on the desktop version and copy across.

**Comment by alyssonnaide** [comment]
stenzek

Thanks a lot, i find the resource and worked.

Keep the good job.

alyssonnaide
