### ISSUE TITLE
Handling multiple games with same game code on game list

### ISSUE THREAD

**Issue by Nucleoprotein** [stenzek/duckstation#1460]
**Description of the issue / bug**
There is problem with displaying and handling multiple games with same code.
That is a problem affects also save states, emulator is loading same save states for all those files (which are different. see examples below)

**Steps to reproduce**
Add games with same code to game list. They names will be the same. There are multiple records in redump.dat but only the first one is used.

Example, different files, with different hashes:
![image](https://user-images.githubusercontent.com/8019035/104638473-802e2600-56a6-11eb-8b58-0447e771c05b.png)
![image](https://user-images.githubusercontent.com/8019035/104638934-1bbf9680-56a7-11eb-866a-be9acd40838f.png)

Example 2:
![image](https://user-images.githubusercontent.com/8019035/104638832-f3d03300-56a6-11eb-8d44-ff18c835e1c1.png)

**Comment by stenzek** [comment]
It is working as intended - the "resume" happens based on the game ID, and it just pulls that from the disc you select.

I agree it's not ideal, but I'm not really sure on a better way to handle it. Switching between e.g. a modded and unmodded disc would likely crash games, so switching the disc while loading the state is likely a bad idea.

**Comment by RaydenX93** [comment]
Related to https://github.com/stenzek/duckstation/issues/1077?

**Comment by stenzek** [comment]
Merging with #1077.
