### ISSUE TITLE
Resampling audio randomly crashes Duckstation when fast forwarded

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#1461]
As the title says, best way to replicate this I found in Breath of Fire 4, here's video on how to do it an memory card with the save file, thou this does happen on every game sometimes on startup.
https://youtu.be/NGOKmQeQpqk
[Breath of Fire IV (USA)_1.zip](https://github.com/stenzek/duckstation/files/5817226/Breath.of.Fire.IV.USA._1.zip)

Disabling resampling fixes this completely.

PS.
Sorry for lack of audio, it's a issue with the recording program.

**Comment by stenzek** [comment]
Not getting any crash here fast forwarding at 300%.. maybe it's a combination of settings.

**Comment by foxsevent** [comment]
Since last update issue seems to be fixed, so closing this until proven that it is not fixed.
