### ISSUE TITLE
Box downsampling to resolutions aside from 1x

### ISSUE THREAD

**Issue by Margen67** [stenzek/duckstation#1464]
**Is your feature request related to a problem? Please describe.**
Even at 32x resolution, there are still jaggies that aren't present with MS/SSAA.
Linear upscaling doesn't fix this.

**Describe the solution you'd like**
Box downsampling at resolutions aside from 1x;
![image](https://user-images.githubusercontent.com/3462541/104686567-4d8a2a80-56b2-11eb-8794-24819ad47cd4.png)

**Describe alternatives you've considered**
Use a box downsampling shader. (if one exists that is compatible with duckstation)

**Additional context**
Duckstation window:
![](https://cdn.discordapp.com/attachments/695823573830598706/796040361767993344/unknown.png)
Resized in external program:
![](https://cdn.discordapp.com/attachments/695823573830598706/796040435762987068/SLPS-01556_2021-01-05_02-58-53_resized.png)
Related issues:
 * #1308
 * #1187

**Comment by stenzek** [comment]
Was added in https://github.com/stenzek/duckstation/commit/585cf25ac484f5bd35399938b4ecdf796c24cf53
