### ISSUE TITLE
PGXP Question

### ISSUE THREAD

**Issue by Dookie64** [stenzek/duckstation#1466]
I'm running dusckstation on an intel i5 4690k 16gigs 4 gig gtx 960. Using pgxp on gran turismo and other games works flawless, however running on a slightly lower spec system is runs awful. its an i5 3570 8gigs ddr3 and 2gig gtx 680, it is very choppy and sluggish with pgxp on, also a little laggy when off. Is something wrong or are those specs just crap for this emulator? Both systems are windows 10 64 home.

**Comment by Nucleoprotein** [comment]
I think it is V-Sync problem, check if is disabled.

**Comment by DonelBueno** [comment]
Both systems should run the emulator VERY well, unless you are running a very high internal resolution and running out of VRAM on the 2 GB GPU.

**Comment by Dookie64** [comment]
I just checked on the v-sync but now no matter what settings i have, it all runs very slow. Only thing that seems to fix it is uninstall and reinstall retroarch.

**Comment by stenzek** [comment]
Sorry, the libretro core is no longer part of DuckStation, and is not supported here. If you're having the same issue with the standalone version, please let me know and I'll re-open. But otherwise you should direct your issue to the libretro repository.

**Comment by Dookie64** [comment]
Oh sorry, I forgot to mention it does the same thing with the standalone, i just wanted all my emulators in one place.

**Comment by stenzek** [comment]
Turn off vsync, or sync to host refresh rate. Try with the null audio backend.

**Comment by Dookie64** [comment]
It was the vsync, thank you so much, running perfect now!!!

**Comment by stenzek** [comment]
Cool, solved then I guess.

I'd suggest trying both vsync *on* and sync to host refresh rate *on* as well. This will give you smoother animations in 60fps games, if it doesn't break on your system.
