### ISSUE TITLE
hdr bug

### ISSUE THREAD

**Issue by spartaque12** [stenzek/duckstation#1467]
why does it disables HDR after game's fullscreen on windows 10?
specs: i7 2600k, rtx2060, win10 x64 1909
render: Vulkan

emu version: 0.1-2936

**Comment by Nucleoprotein** [comment]
Because there is no HDR PSX games? First PlayStation supporting HDR displays is PS4 and not even then all games are compatible with it.

**Comment by spartaque12** [comment]
> Because there is no HDR PSX games? First PlayStation supporting HDR displays is PS4 and not even then all games are compatible with it.

i understand, but why it forces to off?
i mean u could play literally any game on pc, if u launched it in borderless mode, but duckstation works some other way...
Just wanted to know if it possible to play borderless or something

**Comment by Nucleoprotein** [comment]
But why play non HDR ie. LDR content when HDR is active? It makes colors washed out...

**Comment by spartaque12** [comment]
> But why play non HDR ie. LDR content when HDR is active? It makes colors washed out...

it doesnt make washed out colors, just believe me

**Comment by Nucleoprotein** [comment]
> it doesnt make washed out colors, just believe me

I will believe more my own eyes, sorry.

**Comment by foxsevent** [comment]
Dunno why HDR doesn't work for ya, works fine here using D3D11 or Vulcan in borderless window mode.
Thou I do agree with the other dude, why bother, unless the content was made with HDR in mind it will not look any different, the color data simply ain't there, it's the same with black and white movies, you can't make them into color unless you redo/remake the whole movie.
The only thing that will be different is brightness as HDR ups the screen luminescence to the max .

**Comment by spartaque12** [comment]
> Dunno why HDR doesn't work for ya, works fine here using D3D11 or Vulcan in borderless window mode.
> Thou I do agree with the other dude, why bother, unless the content was made with HDR in mind it will not look any different, the color data simply ain't there, it's the same with black and white movies, you can't make them into color unless you redo/remake the whole movie.
> The only thing that will be different is brightness as HDR ups the screen luminescence to the max .

yeah ure right, it just maxes brightness, thats all, well d3d11 helped me to run borderless, idk why but window mode was unaccessible on vulkan
