### ISSUE TITLE
Tilting with L2 or R2 fills the screen with graphical garbage in Pro Pinball - Timeshock! (USA)

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1469]
Using L1 or R1 works fine. Tested with all enhancements off. Doesn't happen in Beetle PSX.

![Capture2](https://user-images.githubusercontent.com/77198254/104806556-877f3c00-582c-11eb-9fde-b74be953bb8f.PNG)

**Comment by stenzek** [comment]
It's a regression from the software scanout optimizations a while back, forgot to fix it..

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/29690c4635e069766ce7e20c564dedaadc8d066c
