### ISSUE TITLE
Glitches during the opening FMV of Fantastic Four (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#147]
There's a bunch of flashing squares at the top of the screen. It's hard to see in screenshots. Happens with both D3D11 and OpenGL. Doesn't happen in Beetle PSX. 

![Capture](https://user-images.githubusercontent.com/31968468/77364322-5c60c300-6da8-11ea-8a25-f4abc7ec0f22.PNG)

**Comment by kurayami6** [comment]
Rascal (USA) has the same problem.

![Capture](https://user-images.githubusercontent.com/31968468/77486937-21808d00-6e85-11ea-9076-8216ed70ba7f.PNG)

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/54abd37daa726dd95ba56a0fb0b5b60a7f493d91, or at least it was in the other games I've checked.

**Comment by kurayami6** [comment]
Fixed. Thanks.
