### ISSUE TITLE
A glitchy version of the first loading screen appears for a few frames in Aqua GT (Europe)

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1471]
Tested with all enhancements off. Doesn't happen in Beetle PSX. 

![SLES-03390_2021-01-17_05-28-08](https://user-images.githubusercontent.com/77198254/104819939-57b05280-5885-11eb-8229-322d8b4544af.png)

![Capture](https://user-images.githubusercontent.com/77198254/104819944-5d0d9d00-5885-11eb-8dff-d776c51a7c8d.PNG)

**Comment by Nucleoprotein** [comment]
Does not happen for me

**Comment by stenzek** [comment]
Fixed by https://github.com/stenzek/duckstation/commit/699d599d008f9f05aad15505579b7b835d6eade4
