### ISSUE TITLE
[Request] Add arcade systems based on Ps1 hardware

### ISSUE THREAD

**Issue by CocoNutFighter** [stenzek/duckstation#1473]
Hello, would it be possible to add in Duckstation the support of the Ps1 arcade sister systems ?
(Capcom Zn1/2 and Namco System 11/12), which are only a PS1 architecture boosted in video memory.

System12 hardware: https://www.system16.com/hardware.php?id=535

There is the Mame emulator that runs these systems, but it is not optimized, it requires a lot of resources,
no PS1 emulator offers it, only for Tekken Tag, Soulcalibur, Fighting Layer, and Star Gladiator 2 it would be great, 
Thank you for your work, I love Duckstation.

**Comment by stenzek** [comment]
Sorry, it's not in the scope of the project. Multiple systems is too much for basically one person, and I also don't have any of the hardware to run tests on.

Looking at that spec list, seems it has different sound chips, and potentially different GPU instructions. So not just "an increase in video memory" :)
