### ISSUE TITLE
Vagrant Story Pal (translation to Spanish)

### ISSUE THREAD

**Issue by guototo** [stenzek/duckstation#1474]
the translation has a selector at the beginning of pal or ntcs.
when you select one of the two the game does not start.

Vagrant Story pal sles 02754

sbi patch applied.

**Comment by stenzek** [comment]
Do you know if this translation works on console? The base Vagrant Story PAL game seems to work fine here.

**Comment by guototo** [comment]
Yes, it works on original console.

**Comment by stenzek** [comment]
Do you have a link to the translation?

**Comment by guototo** [comment]
https://www.romhacking.net/translations/2127/

I have only found in romhacking.

**Comment by Kurayami7** [comment]
How is the patch applied?

**Comment by guototo** [comment]
The way to apply the patch is simple, it is simply created with our
original copy of VAGRANT STORY © in PAL version (SLES 02754) an image in
ISO / BIN / IMG format or whatever we want, which occupies exactly
normal size (750,643,152 bytes) and disk size (750,645,248 bytes),
to occupy more or less, the patch will not work, so you will have to recreate it
in another way or with another program until it gives you this result.

Then, with the PPF-o-Matic version 3.0 program, which you will download from our
page, the created image is opened and indicated and below, the patch that
You have the option to "Apply" and, after a few seconds, you will get a message
informing that the process has ended successfully.

Then, you already have your image of the VAGRANT STORY © 100% in
Spanish and ready to play.

**Comment by Kurayami7** [comment]
Alright here's what I've got. The PAL version of Vagrant Story (Europe) with the Spanish translation patch applied hangs on this screen.

![SLES-02754_2021-01-18_23-10-48](https://user-images.githubusercontent.com/77198254/104914053-a7586080-59e2-11eb-92f4-7b549a188c60.png)

The log says this

![Capture](https://user-images.githubusercontent.com/77198254/104914071-af180500-59e2-11eb-99aa-1a063d623b70.PNG)

And you're sure this works on real hardware?

**Comment by guototo** [comment]
yes, I'm going to turn on the psx and I'll pass you a catch.

**Comment by stenzek** [comment]
No need, I've already fixed the issue - will push later

**Comment by guototo** [comment]
Ok.

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/914b9bf738be3da97f186a7f4d2de0c3ab8961bb

You'll need to switch to the preview build to check.

**Comment by guototo** [comment]
What do I have to do to make it work?.

**Comment by stenzek** [comment]
General Settings -> Change the update channel from `dev` to `preview`, and click `Check for Updates`.

**Comment by guototo** [comment]
Thank you very much, it works, you are the best.

If you noticed that a game is not going, I can notify you, how did you do with this one.

**Comment by stenzek** [comment]
Great, I can close the issue then.

Problems with games should be reported as issues like this one.
