### ISSUE TITLE
Controls not working right

### ISSUE THREAD

**Issue by 4thkindenter** [stenzek/duckstation#1477]
**Game details**
[All

**Description of the issue / bug**
Characters get stuck moving, either  crouching or jumping constantly. I am using JoytoKey for controls and launching through Rocket Launcher and hyperspin.

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open? No
2. Which controller backend are you using in general settings: I have tried all of them and thissue is still there

*

**Comment by stenzek** [comment]
Sounds like a problem with whatever wrapper you're using. Don't really see why it's necessary, duckstation has native controller support.

**Comment by 4thkindenter** [comment]
I am using it with a 4 player arcade I built and it doesn't recognize my USB encoders. Making keyboard controls and converting them with JoytoKey to button presses is the only way I can get it to work

**Comment by stenzek** [comment]
So you're saying the controller doesn't work with SDL, Xinput, or Dinput?

**Comment by 4thkindenter** [comment]
none of them. Only the keyboard

**Comment by stenzek** [comment]
Seems strange that your controller would be recognised by the wrapper but not SDL/dinput.

Did you try all three controller interfaces, and try binding the controller with each? Does the log print out any devices detected?

**Comment by 4thkindenter** [comment]
It looks like the log shows all my devices, but they won't let me bind any controls. I tried all the settings

**Comment by stenzek** [comment]
Could you post the log?

You are using the qt frontend and binding though controller settings, right?

**Comment by 4thkindenter** [comment]
I actually got it working after restarting my computer and using the SDL backend. Something must have been running in the background. Can you make individual game control files?

**Comment by stenzek** [comment]
Yes, you can create input profiles and then assign those profiles to games through game properties.
