### ISSUE TITLE
Title screen doesn't fade out properly as attract mode starts in Army Men - Air Attack 2 (USA) when upscaling

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1478]
Tested with all enhancements except upscaling off so that's definitely the cause. Happens with all hardware renderers. 

![SLUS-01132_2021-01-20_18-54-02](https://user-images.githubusercontent.com/77198254/105144283-1e136c00-5b51-11eb-9eb3-68288f70df40.png)

![SLUS-01132_2021-01-20_18-43-11](https://user-images.githubusercontent.com/77198254/105144294-223f8980-5b51-11eb-8500-35e2882851fb.png)

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation/issues/427
