### ISSUE TITLE
Pausing and then switching renderers causes the emulator to unpause itself

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#148]
I can't show it in motion but you get the idea. 

![Capture3](https://user-images.githubusercontent.com/31968468/77365634-959a3280-6daa-11ea-8da8-5931975d110f.PNG)

**Comment by stenzek** [comment]
It's an easy fix, but keep in mind the frame displayed will be from the "old" renderer, and any rendering differences won't be visible until the next frame.
