### ISSUE TITLE
PGXP doesn't work during the opening title screen of Covert Ops - Nuclear Dawn (USA)

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1483]
Tested with CPU mode on and off. Confirmed to not be an FMV. 

![SLUS-01151_2021-01-21_02-56-00](https://user-images.githubusercontent.com/77198254/105207384-930b9380-5b9b-11eb-9982-83a83025ab3e.png)

PGXP works fine during gameplay except CPU mode breaks text.

![SLUS-01151_2021-01-21_03-03-38](https://user-images.githubusercontent.com/77198254/105207479-afa7cb80-5b9b-11eb-9a36-fd234389b093.png)

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation/issues/733
