### ISSUE TITLE
Change the names in the emulator.

### ISSUE THREAD

**Issue by drdeathd** [stenzek/duckstation#1484]
Well, this is silly, but I would like to change the name of the games in the game list. I always wanna puke when I see "(USA), (rev 1.1), (en, sv, es), etc" it's disgusting. It doesn't have anything to do with the .bin file as I know.

**Comment by stenzek** [comment]
Might be silly to you, but those are the redump names and follow a strict convention.

Right click columns -> tick file title, and untick title, and it'll use the title from the filename instead.
