### ISSUE TITLE
Android - Duckstation Freezing

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#1485]
**Game details**
Not related to a specific game.

**Description of the issue / bug**
First, Duckstation is running really slow can't even pass BIOS screen. 

Second, as soon as i back to the game list, while tried to load other game from there Duckstation just freezes had to force it to close.

**Controller Troubleshoot Report**
Not related.

**Steps to reproduce**
Run Duckstation > choose a game from list > (game runs really slow) hit return > quit
As soon you return to the game list > Try to run another game then Ducky freezes.

**Enhancements information**
Nothing enabled at all, I've cleaned up all settings before test.

**Hardware/software**
Tested and confirmed issue with the following devices:

- Samsung J7 Prime SM-G610M Android version 8.1.0
- Motorola Moto G6 Android Version 9.0
- Motorola Moto G5 plus

[GPU Renderer - D3D11/OpenGL/Vulkan]
Not relevant I guess but, did test with Vulkan and Opengl same behavior 10 Fps or less 
From BIOS and beyond. (when it get into gameplay).

**Emulator version**
Latest from Playstore Duckstation 0.1-2955
Happens too with:      Duckstation 0.1-2949

Working good with:
Duckstation 0.1-2757

**Additional context**
Don't know if is relevant or not but, in my tests. at first I was using Playstaion 3 BIOS(ps1_rom) meaning, the one available on real console same used in standalone version on PC; Second test did with US version which is SCPH1001.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/443319766523e6396abe52a8e1721146e3943896
