### ISSUE TITLE
Chou-Kousoku Gran Doll (Japan) needs PGXP disabled in per game settings

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1486]
The game is entirely 2D and doesn't benefit from PGPXP at all. Having it on breaks the graphics. 

![SLPS-00935_2021-01-21_16-44-42](https://user-images.githubusercontent.com/77198254/105285697-05668d00-5c09-11eb-8033-f78750a7337f.png)

**Comment by Margen67** [comment]
Belongs in #733

**Comment by stenzek** [comment]
Eh, it's a gameini, will push later

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/baf8b1af43d29c05abcfb20c24a5d394c1c30f15
