### ISSUE TITLE
Star Ocean - Incorrect Reference CD's

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#1487]
**Game details**
SCUS-94421 Star Ocean - The Second Story

**Description of the issue / bug**
Description of Star Ocean game is wrong, first CD 1 as CD 2
![StarOcean](https://user-images.githubusercontent.com/43047877/105371391-582d4e00-5be3-11eb-9abc-ef90b5d260b0.png)

**Controller Troubleshoot Report**
Not Related

**Steps to reproduce**
Run Duckstation

**Enhancements information**
Not Related

**Emulator version**
Latest 0.1-2957-g3c3bfdea
(but i guess it does not matter in this case)

**Additional context**
I've tried to edit Redump Db but it seems not be the issue here as well. 

![redumptxt](https://user-images.githubusercontent.com/43047877/105371775-b2c6aa00-5be3-11eb-977f-9fcef8d97ba1.png)

**Comment by stenzek** [comment]
Hmm, it does seem to be the redump db at fault here.

**Comment by stenzek** [comment]
Hrm, so I think the problem here is that both discs have the same serial printed, but the executable name is different. Strange.

**Comment by andercard0** [comment]
Okay no problem! As a workaround if there is anyone curious on how to 'fix' that, again, temporally; 

Just rebuild the Cache folder without redump game list db. and done. 

![image](https://user-images.githubusercontent.com/43047877/105386298-012f7500-5bf3-11eb-9668-965c8f793fc2.png)

**Comment by andercard0** [comment]
Well.. I'm not sure if this should be reported separately so decided to report as a comment here because it is in regards the same subject; 

So, while changing my game cover for **Urban Chaos** i noticed that as soon as cover changes it changed for both games: Threads of fate as well as Urban chaos. as you might view down below:

![Urban_Threads](https://user-images.githubusercontent.com/43047877/106801179-2f27a700-6640-11eb-9b40-af6fe1c6395a.png)

Just tried to update redump database but nothing has changed at all if that matters. Only way to play urban chaos was via loading it's image and even so it sees my game as another.

![Urban_Not_Threads](https://user-images.githubusercontent.com/43047877/106801314-5d0ceb80-6640-11eb-87d9-164d5e879a9c.png)

Information of the games are: 

Threads of fate: 
- Game Code SLUS-01019
- Game Hash: bf49e5e7a09acc46625b5ced33dd45f5

Urban Chaos:
- Game Code SLUS-01019 - (exact same code)
- Game Hash: c9b4e03de8dd5c1fb799fc56e5cf031a

Emulator version: 0.1-3109-gfd269ec9

**Comment by Nucleoprotein** [comment]
hmm, it should be not the same:
http://redump.org/disc/2329/
http://redump.org/disc/158/

SLUS-01091 vs SLUS-01019

**Comment by andercard0** [comment]
> hmm, it should be not the same:
> http://redump.org/disc/2329/
> http://redump.org/disc/158/
> 
> SLUS-01091 vs SLUS-01019
> 
> EDIT: yeah, they do a typo in Urban Chaos CD data, there is SLUS_010.19 there...

Hm.. same with Skullmonkeys (France) version take a look

![image](https://user-images.githubusercontent.com/43047877/106891133-11525480-66c9-11eb-85f4-ba880cc22972.png)

**Comment by Nucleoprotein** [comment]
But they are with different prefix ie. SLES/SLPS etc. - that is allowed, many games duplicate numbers.
Duckstation matches game name using executable name from SYSTEM.CNF and in the case of Urban Chaos and Threads of Fate there is a typo in Urban Chaos data on CD as Urban Chaos have different code printed on covers and CD:
https://psxdatacenter.com/images/covers/U/U/SLUS-01091/SLUS-01091-D-ALL.html

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/ff14e8aede6f0e852d346ac27509fb2897b606f4

For the others, we'll have to add aliases for them on a case by case basis in the new game database.
