### ISSUE TITLE
Duckstation crashed partway through a match while playing Bakuretsu Soccer (Japan)

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1490]
I have no idea how to reproduce it. I've tried with enhancements on and off. I've tried with the software renderer and hardware renderers. The game is Redump verified. 

![Capture2](https://user-images.githubusercontent.com/77198254/105486808-3b883780-5d03-11eb-8d94-d29ef46257b9.PNG)

![Capture](https://user-images.githubusercontent.com/77198254/105486821-404ceb80-5d03-11eb-86a8-cf27ebeed863.PNG)

**Comment by stenzek** [comment]
Can't do much here without a crash dump or backtrace.

**Comment by Kurayami7** [comment]
Yeah fair enough. God it annoys me that I couldn't reproduce it.
