### ISSUE TITLE
Option to capture screen

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1491]
I'd like the ability to choose between "capture output" and "capture screen" or something along those lines for screenshots so I can take full sized shots of FMVs and games at x1 resolution.

![Capture](https://user-images.githubusercontent.com/77198254/105506329-0d642100-5d1e-11eb-9c73-11dcd226c453.PNG)

**Comment by Richard-L** [comment]
I had this problem too sometimes, but only ever with FMVs. Maybe would it be enough to simply output FMV screenshots the same size as in-game ones, and make this an option hidden somewhere in "advanced". If it's in one of the main Windows I worry about option bloat.

**Comment by PavelDurov1488** [comment]
Imho it's better to use postprocessing filter too, but it sounds hard, cause needs GPU recording
I use OBS with authentic shaders...
https://user-images.githubusercontent.com/74456272/105540568-e8d66c00-5d52-11eb-863e-1e387d4cf88f.mp4

**Comment by PavelDurov1488** [comment]
![image](https://user-images.githubusercontent.com/74456272/105542085-48357b80-5d55-11eb-87f2-d041d406b511.png)
![image](https://user-images.githubusercontent.com/74456272/105542137-5b484b80-5d55-11eb-80c0-ce531cb03fa5.png)
![image](https://user-images.githubusercontent.com/74456272/105542282-921e6180-5d55-11eb-94de-3c7d5b1e4833.png)

**Comment by Ninaadark18** [comment]
What the name of this beautiful game?

**Comment by Kurayami7** [comment]
Refrain Love Anata ni Aitai 

https://www.youtube.com/watch?v=PCm0Jn8M_Y4

**Comment by Ninaadark18** [comment]
> Refrain Love Anata ni Aitai
> 
> https://www.youtube.com/watch?v=PCm0Jn8M_Y4
Thanks dear

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/359d1509be3abfc884bc74b63c7091bc308e632d
