### ISSUE TITLE
Clicking inside the log window before Duckstation has opened crashes the emulator

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1494]
If you have "log to system console" active, each time you open Duckstation the log will appear about a second before the main emulator window. If you click inside the log window before the emulator itself has opened it will crash.

![Capture](https://user-images.githubusercontent.com/77198254/105540696-b759a280-5d4a-11eb-829a-2d3eddfbc274.PNG)

**Comment by stenzek** [comment]
Not a bug as discussed on discord - highlighting in the log window blocks print output which stalls the emulator until you unselect.

**Comment by Nucleoprotein** [comment]
You can disable quick edit mode programmatically:

```
DWORD prev_mode;
GetConsoleMode(hInput, &prev_mode); 
SetConsoleMode(hInput, ENABLE_EXTENDED_FLAGS | 
    (prev_mode & ~ENABLE_QUICK_EDIT_MODE));
```
