### ISSUE TITLE
Add Fast Boot to Game Properties - Compatibility Settings

### ISSUE THREAD

**Issue by Alien-Grey** [stenzek/duckstation#1495]
If Fast Boot is added to the Game Propeties - Compatibility Settings it would be an easy fix for games that have the boot sound loop isssue  like WipEout 2097.

**Comment by andercard0** [comment]
> If Fast Boot is added to the Game Propeties - Compatibility Settings it would be an easy fix for games that have the boot sound loop isssue  like WipEout 2097.

Could you please for god sake fill the request template ?

**Comment by Alien-Grey** [comment]
**Is your feature request related to a problem? Please describe.**
Yes. Some games have the boot sound loop issue.

**Describe the solution you'd like**
Add Fast Boot to Game Properties - Compatibility Settings as an easy fix.

**Describe alternatives you've considered**
Enable Fast Boot from global settings for games that need it and disable it for games that don't need it.

**Additional context**
None.

**Comment by stenzek** [comment]
I don't see the need for a game setting here. Fast boot is safe to enable globally (I have it enabled), and you can right click to override the boot mode anyway.
