### ISSUE TITLE
Parasite Eve cheat issue

### ISSUE THREAD

**Issue by noph34r** [stenzek/duckstation#1497]
i was playing Parasite Eve and try to use cheat
the problem was "no random battle" cheat, it does work but when i disable it i still havent encounter anything
i also try to manually save, reset game, exit program, still doesnt work
i even try to load from epsxe, still nothing, no random battle

thankfuly i still have save from older one and it's fine (but i also missing few hours obviously)
is there any "cheat" to reset "cheat"??

**Comment by stenzek** [comment]
Unfortunately, such is the nature of cheats - they mess with the game's memory, so corrupting saves is definitely possible. The author of the cheat might be able to help you reverse it, or you could try setting the memory value which the cheat effects from the old save.

But either way, this isn't an emulator bug - it just does what the cheat tells it to do.

**Comment by PugsyMAME** [comment]
You could try this, I don't know if it works.....not my sort of game
#Disable No Random Battles
A60A781A 80000000
