### ISSUE TITLE
Roland Garros French Open 2001 (Europe) hangs on the loading screen before a match

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1498]
Tested with all enhancements off and with a Redump verified copy of the game. Works fine in Beetle PSX.

![SLES-03449_2021-01-23_23-35-32](https://user-images.githubusercontent.com/77198254/105578885-693eb080-5dd7-11eb-853e-fcca3a642715.png)

![Capture](https://user-images.githubusercontent.com/77198254/105578886-6e036480-5dd7-11eb-80dc-c679fae6edf0.PNG)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/2446e945a793a9f30a6469758feb21471d42daa3
