### ISSUE TITLE
The ability to quit after being warned you're loading a game without an SBI file

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1499]
Currently there's no way to stop a game from loading after getting this warning, which defeats the purpose of having the warning in the first place. I'd like there to be an option to either quit or ignore the warning and continue. 

![Capture](https://user-images.githubusercontent.com/77198254/105588086-88dcd580-5de5-11eb-81e9-3467388e97f0.PNG)

**Comment by Kurayami7** [comment]
Oh also the spelling in the message should be corrected. It should be "add an SBI filed" not "add a SBI file"

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/6ab926ab280958c6fcab2666916769ba0acda674
