### ISSUE TITLE
Playstation BIOS clipping sounds.

### ISSUE THREAD

**Issue by JMC47** [stenzek/duckstation#15]
The sounds seem to cut off strangely compared to a real PSX startup.  Using the Japanese bios to boot my games, but another person using an english BIOS ran into the same issue.

[PSXRecording.zip](https://github.com/stenzek/duckstation/files/4182503/PSXRecording.zip)

Uploaded a quick recording of what I'm hearing in case it is not easy to reproduce.

I'm not 100% sure if this is recorded from another emulator or some kind of capture card, but this sounds a lot more correct.

https://youtu.be/rdjYk-fle1o

**Comment by stenzek** [comment]
I haven't compared the spu output against real hardware yet so there most likely is an issue here. There's also a could of missing features too. Will look into it when I get a chance.

**Comment by stenzek** [comment]
Latest commit has some SPU changes which seem to affect the startup sounds. I'll have to check the waveforms to see if it's better matched.

**Comment by stenzek** [comment]
This one's definitely not happening anymore.
