### ISSUE TITLE
Battle menu is broken in Alice In Cyberland (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#150]
It's a flickering mess, disappears and reappears and parts of it are missing entirely. Happens with both D3D11 and OpenGL. 

![SLPS-00636_2020-03-24_11-23-21](https://user-images.githubusercontent.com/31968468/77375798-aeaedd80-6dc2-11ea-93cd-b527c2ca6df7.png)

![SLPS-00636_2020-03-24_11-23-13](https://user-images.githubusercontent.com/31968468/77375817-ba9a9f80-6dc2-11ea-8c12-b150183d48f5.png)

Beetle PSX

![Alice in Cyberland (Japan)-200324-111642](https://user-images.githubusercontent.com/31968468/77375841-d00fc980-6dc2-11ea-9ac2-aca5752030e7.png)

![Alice in Cyberland (Japan)-200324-111615](https://user-images.githubusercontent.com/31968468/77375855-d69e4100-6dc2-11ea-840a-27b21d52cbcd.png)

**Comment by stenzek** [comment]
Fixed with GPU timings (not merged yet).

**Comment by stenzek** [comment]
Please re-test on latest build.

**Comment by kurayami6** [comment]
Fixed.

![SLPS-00636_2020-04-19_17-37-09](https://user-images.githubusercontent.com/31968468/79682307-7df88180-8264-11ea-832c-8bb9a7afa364.png)
