### ISSUE TITLE
Chrono Cross: Texture Issue

### ISSUE THREAD

**Issue by nf6429** [stenzek/duckstation#1501]
[i.e SLUS-01041 Chrono Cross (USA)]
[During boss battles, and occasionally normal ones, aspects of the ui will flicker and have garbage textures on them.]
[Go to boss fight, then element attacks, should see flickering or garbage textures, it seems random when it occurs though.]
[I5-6700U, Intel HD Graphics 520+Nvidia Geforce 940MX]
[GPU Renderer - D3D11/OpenGL]
[0.1-2956-g44331976]

**Additional context**
Pictures attached, I have all enhancements turned off. Normally it's more severe than this but it flickers fast, so is hard to capture screenshots of.
![Picture3](https://user-images.githubusercontent.com/37595436/105627702-5ad0b300-5e30-11eb-8428-ebb8dd11ddb6.png)
![Picture2](https://user-images.githubusercontent.com/37595436/105627706-60c69400-5e30-11eb-9648-708317a2228e.png)
![Picture1](https://user-images.githubusercontent.com/37595436/105627710-645a1b00-5e30-11eb-807e-ec9e81ccc3dd.png)

**Comment by stenzek** [comment]
Can you upload a memory card near one of these bosses with the issue?

Also try:
 - Enabling recompiler icache in compatibility settings (game properties).
 - Switching to the interpreter.
 - Switching to the software renderer.

**Comment by nf6429** [comment]
1. Doesn't appear to do anything, ui still glitches.
2.  Does nothing when I tried.
3.  Seems changes the way garbage textures look, being more inline with the text box black background, might just be by chance though.
Here's a memory card save. To get to a battle, just keep going left, down the ladder, then do a fight in the monster tournament. Attack, go into the elements menu, should glitch occasionally
https://drive.google.com/drive/folders/1YsgHxuexiwbMOMorOpwwFmlpTuAIjcso?usp=sharing

**Comment by Sekai9** [comment]
Are you using nearest-neighbor? if so please try using bilinear filtering and check if the issue persists.
I think this looks similar to some issue i found (which affects a lot of games), and i plan to report in a few days (needs some time).

**Comment by nf6429** [comment]
> Are you using nearest-neighbor? if so please try using bilinear filtering and check if the issue persists.
> I think this looks similar to some issue i found (which affects a lot of games), and i plan to report in a few days (needs some time).

@Sekai9 I tried both the scaling setting, on and off, made no difference. Example for bilinear.
![k](https://user-images.githubusercontent.com/37595436/105828622-42d96a80-5fbb-11eb-891a-df40f0b72d90.png)

**Comment by stenzek** [comment]
It won't - it's a timing or DMA issue - need to investigate further, under locking to 90% or so fixed it for me

**Comment by Sekai9** [comment]
This is how the game looks for me, please take a look:
https://streamable.com/6nfvjb
tested with a clean portable install of Duckstation (0.1-3000-g1b678038)

Using bilinear/software rendering makes the game look far better, but there are still some black lines/dots here and there.
So yeah, might not be related to the issue i was talking about. I'll create a new issue as soon as i get the time.

My system: Intel Core i5 5300U + Intel HD 5500, W10.

**Comment by Lucifel05** [comment]
I up the topic because I playing this game.
As the others said there are issues on Battles (Field effect, Magic Grind, Windows, and even sometimes on the floor).
I tried to change underclocking but that not fixe it entirely. Depend of the characters played and the background, the issue still occur.

**Comment by Lucifel05** [comment]
An example of this bug on the target window (it's not fixe, it twinkle and change place) :
![chrono cross bug](https://user-images.githubusercontent.com/79312139/108518147-87110f80-72c8-11eb-92a3-be9e2b8b2b71.jpg)

**Comment by stenzek** [comment]
Setting DMA Max Slice Ticks to 100 in Game Properties -> Compatibility Settings seems to fix this for me. But it's possible this will also need the RAM speed changes for Silent Hill.

**Comment by Lucifel05** [comment]
Hello Stenzek. 
I tried the DMA Max Slice Ticks to 100 setting but the bug is still here.

**Comment by TzakShrike** [comment]
Do the RAM timing changes for Toshinden help/change this issue?

**Comment by TzakShrike** [comment]
...assuming that those timing changes are in effect already (I didn't check), then no, they do not resolve this issue :)

**Comment by stenzek** [comment]
Appears to be fixed when using a more accurate CPU/DMA ratio (https://github.com/stenzek/duckstation/commit/600ae7bcc03c6b9d8537d8c05d56535c00183678, preview build, you'll need to rescan all games to apply the new parameters).

If it's still happening in other areas after rescanning, please let know.

**Comment by TsukiyoX** [comment]
Hi. It's happening to me, despite the new parameters and despite underclocking to 90%.

**Comment by Phantasm90** [comment]
I get weird these weird glitches on the battle text, this is the first battle of the game and it keeps glitching like that throughout out the game, not sure if this is supposed to be normal, tested on the latest preview build

https://user-images.githubusercontent.com/37343312/123006557-3d2b5980-d38e-11eb-8172-7ca0d58d3845.mp4

**Comment by stenzek** [comment]
No such issue here. Make sure you don't have "apply game settings" disabled in general settings, and rescan your games (pretty sure I've changed the game list since I added the override here so that should've triggered a rescan, but just in case).

**Comment by Phantasm90** [comment]
Maybe because i'm on Windows 7 have something to do with it? I never touched any of the settings so i don't know

**Comment by stenzek** [comment]
I checked on a completely clean install/settings and it was also fine. Maybe try the same (extract to a new dir with portable mode). Win7 shouldn't cause these kinds of bugs.

**Comment by Phantasm90** [comment]
I tried that now and it seemed to be fine until my third battle where the elements menu got glitchy again, i don't know what could be causing this

**Comment by xeropresence** [comment]
I'm seeing this issue on 0.1-4592-g161d90d0 (dev), checking the combability settings both dma max slice and dma halt ticks match the values in your commit.

**Comment by xeropresence** [comment]
Whoops, I did not realize I had to enable the underclocking in the compatibility section for the 90% underclock to be applied, with the 90% activated the issue goes away.
