### ISSUE TITLE
(Android) Ability to change opacity and hide gamepad overlay

### ISSUE THREAD

**Issue by 6lackmag3** [stenzek/duckstation#1504]
Hello! Can you add extra button to overlay that will hide/show other buttons? That way it would be much nicer to watch fmvs and long cutscenes.
Also it would be ultimately handy to have a customizable button for hotkeys.
Regards!

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/d11ee48fe1c9ecb32d5a74cb6ce7d7a95adb5747

Although unticking and ticking all buttons would be a pain if you just wanted to remove them for a FMV, so another option is to change the type to none, then back again.

**Comment by 6lackmag3** [comment]
> if you just wanted to remove them for a FMV, so another option is to change the type to none, then back again.

What about auto-hiding controls after 15 sec of inactivity? A very cool and useful feature found only in ppsspp I believe.
@stenzek please don't consider this as nagging. Just want to help in making DuckStation more convenient and user friendly. Thank yoy for your time and effort as always!
