### ISSUE TITLE
Feature request: Hotkeys for Overclocking

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#1506]
Overclocking is a great feature that works most of the time but it would be nice if we could disable easily in those few instances where it doesn't work nicely, like memory card access.

For example in Resident Evil games overclocking over 140% causes to memory card to fail with access error, other than that overclocking works fin in RE games.
Maybe also could be added hotkeys for increasing and deceasing overclocking, like hte volume hotkeys.

cheers,

**Comment by stenzek** [comment]
Present in latest builds.
