### ISSUE TITLE
'98 Koushien - Koukou Yakyuu Simulation (Japan) runs extremely slowly

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#151]
As you can see from the framerate it's practically running in slow motion. 

![Capture](https://user-images.githubusercontent.com/31968468/77385625-c4c99780-6ddc-11ea-9797-01bf42b75571.PNG)

The log says something is tanking performance.

![Capture2](https://user-images.githubusercontent.com/31968468/77385650-d4e17700-6ddc-11ea-8700-3ee016b43de7.PNG)

**Comment by stenzek** [comment]
Possibly GPU readbacks. Try the software renderer as well as enabling show GPU state in the debug menu and screenshotting the window.

**Comment by stenzek** [comment]
Actually, nevermind, it's still running 59vps / 100%. The game itself must be lagging.

**Comment by stenzek** [comment]
Please re-test on latest build.

**Comment by kurayami6** [comment]
Fixed
