### ISSUE TITLE
Text flickers in a few of the games in Jaleco Collection Vol. 1 (Japan)

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1513]
Tested with all enhancements off. Tested with interlacing on and off. Tested with DMA max slice ticks set to 100. Tested on real hardware and doesn't happen as far as I can tell.

Field Combat as an example.

![SLPS-03562_2021-01-26_19-46-31](https://user-images.githubusercontent.com/77198254/105829579-a940a600-6018-11eb-8dbf-366ac78e4496.png)

![SLPS-03562_2021-01-26_19-46-27](https://user-images.githubusercontent.com/77198254/105829589-ac3b9680-6018-11eb-9d9c-b9d56cf2bcc4.png)

Here's what the text looks like on real hardware on my TV.

![Capture](https://user-images.githubusercontent.com/77198254/105829662-c5444780-6018-11eb-8e9f-d28511621c46.PNG)

**Comment by stenzek** [comment]
Is the "A" on the right of the playfield displayed on the TV at all?

**Comment by Kurayami7** [comment]
It is. It's hard to see in a screenshot. 

![Capture](https://user-images.githubusercontent.com/77198254/106150180-2b72cb00-61cf-11eb-875b-d6182c7c18d7.PNG)

**Comment by stenzek** [comment]
I suspect this might be working as intended then - it kinda looks like your TV is interpreting the alternating frames as two fields (i.e. 480i instead of 240p), that's why it's coming up as lines and not flickering.

If it was an emu bug, I'd think the stray character in the second screen wouldn't be out of place ;)

**Comment by ggrtk** [comment]
Tested this on a CRT television and the first four letters visibly flicker while E only exhibits typical CRT flicker. The blue arrow icon is also visible.

**Comment by Kurayami7** [comment]
Thanks for checking. I don't have a CRT unfortunately and my 4K TV didn't show any flickering.
