### ISSUE TITLE
Upscaling + PGXP crashes the demo for Bugs Bunny: Lost in Time in Compilation 03 (Australia) at the exact same point every time

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1519]
Tested with a Redump verified copy of the game. Upscaling + PGXP will trigger the crash 100% of the time. I've also had it happen with PGXP + x1 resolution though only once out of about 20 attempts. I don't know if there are other ways to trigger it. I apologize if this report belongs in a specific thread but since it only happens consistently with both upscaling and PGXP I wasn't sure which of the two to put it in. 

![SLED-02439_2021-01-28_05-07-59](https://user-images.githubusercontent.com/77198254/106034890-910b7c80-6127-11eb-9f3f-42f351d08707.png)

![Capture](https://user-images.githubusercontent.com/77198254/106035040-bc8e6700-6127-11eb-87b7-e32390bec24d.PNG)

**Comment by stenzek** [comment]
What about if you disable PGXP culling>

**Comment by Kurayami7** [comment]
Yes that stops if from crashing.

**Comment by stenzek** [comment]
Override added in https://github.com/stenzek/duckstation/commit/57830bdd3668df65ce3db95d539cf6dd68a6c63a
