### ISSUE TITLE
Grahical glitches during the screen transitions in Inspector Gadget - Gadget's Crazy Maze (USA) (En,Fr,De,Es,It,Nl)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#152]
Happens with both OpenGL and D3D11. Doesn't happen in Beetle PSX.

![SLUS-01267_2020-03-25_00-28-07](https://user-images.githubusercontent.com/31968468/77432048-ab9f0600-6e31-11ea-99c4-3b5e21b9cf44.png)

**Comment by kurayami6** [comment]
The game has now regressed to the point where it softlocks on the title screen. Pressing start does nothing. 

![SLUS-01267_2020-06-03_23-45-04](https://user-images.githubusercontent.com/31968468/83644170-5717c400-a5f4-11ea-89c7-bb0d46fa6096.png)

**Comment by HeroponRikiBestest** [comment]
The game works fine for me as of the latest build. Please retest.

**Comment by kurayami6** [comment]
All issues seem to be fixed.
