### ISSUE TITLE
Integrate chdman-like functionality (CHD conversion) into DuckStation.

### ISSUE THREAD

**Issue by ImSpecial** [stenzek/duckstation#1521]
Could something like this ever be added to DuckStation? Similar to how Dolphin can do its conversion to and from for space saving, I think it would be great if DuckStation could do the same but for CHDs without having to track down 3rd party tools, then having to learn the correct command-line/procedure for it to work.

A simple right-click GUI option in DuckStation for "BIN/CUE --> CHD, CHD --> BIN/CUE" would be most excellent. :)

**Comment by sickemulator** [comment]
#1005

**Comment by ImSpecial** [comment]
quack quack

**Comment by stenzek** [comment]
Not within the scope at this point, sorry, as it's a decent chunk of code to pull in. Can re-open if I change my mind in the future.
