### ISSUE TITLE
No Vibration With X-Box One Controller

### ISSUE THREAD

**Issue by appollo147** [stenzek/duckstation#1523]
I have Windows 10 and use an X-Box One controller. I have tried both the SDL and Xinput backends and I can not get the vibration to work on any any Dual Shock compatible game. Could someone please tell me why it is not working? Is it just not fully implemented yet, or am I missing an option that needs to be turned on? Any help with this would be greatly appreciated.

**Comment by jpchow26** [comment]
Make sure you scroll down the controller settings panel and click the rumble field and press a button to set which controller to vibrate.
![image](https://user-images.githubusercontent.com/10886704/106180392-36474480-616a-11eb-8860-e554307230d8.png)

**Comment by stenzek** [comment]
Should work fine, and I've tested this numerous times there's a report. Make sure it's bound, or load the xbox one profile.

Depending on the game you could try tweaking the bias as well, if it's sending very small rumble intensities.

MGS options screen is a good test otherwise.

**Comment by Ryusan-AT** [comment]
You must also switch to 'analog' mode for the vibrations to work.

**Comment by ggrtk** [comment]
> You must also switch to 'analog' mode for the vibrations to work.

This isn't always necessary, but does it depend on how individual games do rumble. Metal Gear Solid will send rumble bytes to the controller even when the analog controller is set to digital mode, but other games may not.

**Comment by jdoexbox360** [comment]
I got rumble just fine in Ape Escape.
