### ISSUE TITLE
Issues with D3D11 renderer and Windows 7

### ISSUE THREAD

**Issue by stenzek** [stenzek/duckstation#153]
Collapsing all of these into one thread because they seem to be the same, and I've been unable to reproduce any of them on Intel and NVIDIA GPUs on Windows 10.

https://github.com/stenzek/duckstation/issues/144
https://github.com/stenzek/duckstation/issues/132
https://github.com/stenzek/duckstation/issues/129
https://github.com/stenzek/duckstation/issues/127
https://github.com/stenzek/duckstation/issues/120
https://github.com/stenzek/duckstation/issues/115
https://github.com/stenzek/duckstation/issues/85
https://github.com/stenzek/duckstation/issues/80

Seems to be related to VRAM uploads/transfers. As a workaround, use the OpenGL or Software renderers until I get around to setting up a W7 machine again and investigating.

**Comment by kurayami6** [comment]
Red butterflies in Miss Spider's Tea Party (USA) are broken with D3D11.

D3D11

![SLUS-01123_2020-03-28_06-47-42](https://user-images.githubusercontent.com/31968468/77798337-c5a54680-70c6-11ea-9635-8ff763b05ffb.png)

OpenGL

![SLUS-01123_2020-03-28_07-34-50](https://user-images.githubusercontent.com/31968468/77798373-d5bd2600-70c6-11ea-8c19-f5884d61464e.png)

**Comment by forz0i** [comment]
D3D11  is best  for all time  history emulator ps1 exemple
d3d   is  perfect   graphic  in windows  dx11 and dx12   for  windows 7 and
10  x64
xbera  arbex    bios hel    open gl  & d3d
retroarch          bios          beetle psx hw
epsxe              bios hel     open gl
Bleem !          bios hel     D3D
Duckstation    bios          D3D11

**Comment by forz0i** [comment]
best  emultor ps1  all time history
Bleem !          bios hel     D3D
Duckstation    bios          D3D11

**Comment by stenzek** [comment]
@forz0i please stop spamming random issues with off-topic comments.

**Comment by forz0i** [comment]
ok i am sorry for the message

**Comment by stenzek** [comment]
I (painfully, gosh, W7 is so annoying to install on semi-modern hardware) tested this on Windows 7 with both a RX580 and a GT710. I could not reproduce the bug on either GPU. The only thing I didn't do was install Windows Updates because of how long it takes.

I'm going to add an "adapter selection" option to the settings which should let you force the use of the software D3D renderer (WARP). Then we can try that and see if it's an issue with DuckStation or the GPU driver.

I'm wondering if now this is some setting in the NVIDIA/AMD graphics control panels which is causing the issue, because I honestly can't think of what else the problem could be. I've tested every configuration I have (all 3 major vendors), and none of them have the problem.

**Comment by stenzek** [comment]
Alright, I have managed to reproduce it now. Will investigate soon.

**Comment by stenzek** [comment]
Pushed a fix. @kurayami6 please re-test some of these games on the latest build.

**Comment by kurayami6** [comment]
I checked 5 of the games that previously had issues and they're all fixed.

**Comment by stenzek** [comment]
Great, thank you. I think we can close this now :)
