### ISSUE TITLE
[Feature Request] Auto-Fire Button 

### ISSUE THREAD

**Issue by fhyll** [stenzek/duckstation#1533]
There is some minigame in ps1 games that require to rapidly tap X button, the faster you tap the higher the success rate of minigames. Maybe because i'm getting old, this somehow make my finger tired. Hope the team can put some hotkey to enable Autofire of X button

i would like, if there is we can bind autofire X button to another places, normally i play with keyboard, so maybe we can bind it with letter M or something like that

or maybe the team can just make a toggle/hold hotkey to enable autofire for the button

**Comment by andercard0** [comment]
> There is some minigame in ps1 games that require to rapidly tap X button, the faster you tap the higher the success rate of minigames. Maybe because i'm getting old, this somehow make my finger tired. Hope the team can put some hotkey to enable Autofire of X button
> 
> i would like, if there is we can bind autofire X button to another places, normally i play with keyboard, so maybe we can bind it with letter M or something like that
> 
> or maybe the team can just make a toggle hotkey to enable autofire for the button
> 
> 
> 

Wow yeah...I agree. A turbo option for a single button (while held) is indeed a great addition; specially in some shmup / bullet hell games that did not have this option.

**Comment by ImSpecial** [comment]
This is a good feature request and there are rare times it would be most helpful, like with some mini-games in games (yo dawg), so I hope something like this can get added eventually too. I play with a pad at a PC, so being able to hold down some defined modifier key on the keyboard that makes your pad buttons act as turbo variants would be ideal for me.

**Comment by xerogabe106** [comment]
I would like to add a slight addendum to this request. I would like to manually set the rate of fire on a per button basis. For example I would like to speed up OR slow down the rate of fire on a per button basis. 

Currently, my PS1 game does not use R2 or L2. So I decided to use those buttons via hotkey to save state and pause the emulation. Problem is the buttons fire so often that even the gentlest of taps will cause the game to save 2-3 times or Pause/Unpause 2-3 times. 

The multiple save states isn't that big a deal, but the pausing can be a headache because it turns into a bit of trap you gotta wade out of. 

So, yeah. A turbo button is nice. But more granular options would be greatly appreciated. 

Please and thank you!

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/439537518289158b6a6f411d1d72ba3c01a75c40

For each controller, you get four auto fire slots, for which you select the playstation controller button, and bind a host controller key/button to it. I think four is a good balance between having enough for more complex games, and not overloading the UI.

> I would like to manually set the rate of fire on a per button basis. Meaning I would like to speed up OR slow down the rate of fire on a per button basis.

This is the case - you can set the rate at which it toggles in frames. By default it's 2 frames (for 30fps games).

**Comment by eadmaster** [comment]
was this exposed in the qt linux port?
i do not see an option in the GUI.

**Comment by stenzek** [comment]
Yes. Look here:

![image](https://user-images.githubusercontent.com/11288319/119216329-7b76f400-bb16-11eb-8285-ef43aced63d1.png)

If you're not using the git release, please talk to your packager, I have nothing to do with any third party packages and cannot help you.

**Comment by eadmaster** [comment]
nevermind, i had an error with the latest qt appimage...
