### ISSUE TITLE
Error shortcut

### ISSUE THREAD

**Issue by CristobalManga** [stenzek/duckstation#1535]
-batch -fullscreen -- <D:\Respaldo\PS1\Crash Team Racing.img>

Failed to load CD Image <D:\Respaldo\PS1\Crash Team Racing.img>

I'm wrong about something, but I don't know what? Can you help me please.

**Comment by stenzek** [comment]
Don't put angle brackets around the path, use quotes instead.
I.e. "D:\game.cue"
