### ISSUE TITLE
DuckStation just crashes

### ISSUE THREAD

**Issue by Haker120** [stenzek/duckstation#1536]
After update to version 0.1-3019-g3c2b11fc (master) emulator just crashes and turns off right after choosing a game or resume or even start BIOS. This is all I can say, all settings are default, no matter Vulcan, OpenGL, DX11 or software.

**Comment by stenzek** [comment]
I'm assuming the dev (non preview) version works fine?

**Comment by stenzek** [comment]
Also, try setting the controller interface to none, and the audio backend to null, and see if that changes anything.

**Comment by stenzek** [comment]
Also need hardware and OS info.

**Comment by Haker120** [comment]
Alright, some of these options worked, now I have to check which one. Odd, also I haven't tested non preview version, app updates automatically for me. ;)

**Comment by stenzek** [comment]
Closing as this was resolved? If you can narrow down a crash to a particular setting or provide the crash dump (preview build), I can investigate.
