### ISSUE TITLE
Various issues in vib-ribbon (PAL)

### ISSUE THREAD

**Issue by sys128** [stenzek/duckstation#1538]
**Game details**
SCES-02873 Vib-Ribbon (PAL)

**Description of the issue / bug**
Widescreen hack issue: In short, the game is unable to display things properly past its 4:3 boundaries.

CD seeking: I found that when playing different tracks on audio discs/isos, a little bit of the previous song will be played before the one you are trying to play begins. Again, not as much of an issue in other PSX emulators.

Track 1?: It seems that when reading the discs, the game ignores the fact that Track 1 in CDs is not meant to be read, and should instead start reading from Track 2, and then label _that_ as "track 1" in the game.

**Steps to reproduce**
Widescreen hack issue:
1. Turn on the "Widescreen Hack" option in Enhancement Settings and set the aspect ratio in Display Settings to anything wider than 4:3
2. Play any track and watch for any oddities, like obstacles' geometries being misshapen and constantly changing until it is in its original 4:3 boundaries.

CD seeking:
1. If necessary, burn a CD with multiple tracks or make an ISO [Audio CD or Mixed Mode CD] with a list of multiple songs with PowerISO.
2. After getting into the main menu of vib-ribbon, switch disc/rom with the Audio CD.
3. Go to "Play with my own choice of CD" > "Single track" > "Keep the current CD" 
4. Select a song, preferably towards the end.

Track 1?:
1. Like before, get a CD in some way, and insert it after loading the game and getting into the main menu.
2. Go to "Play with my own choice of CD" > "Single track" > "Keep the current CD"
3. Select track 1. Currently, it would wait a few seconds and then the stage is instantly failed with 0 points.

**Hardware/software**
Windows 10 1909, Intel Core i5-8250U, Intel UHD Graphics 620, 8GB RAM
Using OpenGL Renderer, but these issues are present in all renderers.

**Emulator version**
0.1-2997-g29cbdd7e (dev)

**Additional information**
These issues may have been present for a while due to the small playerbase, so I finally decided to report them as bugs.

There was also previously been a report on L+X obstacles not rendering correctly, but that has been fixed with a reset of the game.

**Comment by foxsevent** [comment]
My two cents on this.
The widescreen hack is a hack, like cheats it does something that the game wasn't made to do like in this case widescreen support, it's not an emulator issue, for some this hack will work for others it won't.
The only visible way to "fix" this would be to modify the game itself so it would render things in widescreen.

Why shouldn't track 1 be read? Audio CDs or music discs do store music on all tracks starting from 1.
The rule to skip track 1 is only in regards to special discs that store something else on track 1 like game data, this is what a lot of PS1 do.
Game data track 1.
Music track 2-99

**Comment by sys128** [comment]
> My two cents on this.
> The widescreen hack is a hack, like cheats it does something that the game wasn't made to do like in this case widescreen support, it's not an emulator issue, for some this hack will work for others it won't.
> The only visible way to "fix" this would be to modify the game itself so it would render things in widescreen.
> 
> Why shouldn't track 1 be read? Audio CDs or music discs do store music on all tracks starting from 1.
> The rule to skip track 1 is only in regards to special discs that store something else on track 1 like game data, this is what a lot of PS1 do.
> Game data track 1.
> Music track 2-99

Now I understand much of this a lot better! Thanks for your input! I appreciate it! ^_^ I will close this issue upon commenting.
