### ISSUE TITLE
Random crash in Castlevania SOTN

### ISSUE THREAD

**Issue by Farlander-001** [stenzek/duckstation#1539]
**Description of the issue / bug**
Game crashes after 20-30 minutes of playing. My monitor says "No Signal" until I close the game using Alt-F4. Heavy sound stuttering. Restarting with auto-created save state working as it should, and I can play 20-30 minutes again. Tried both hardware and software renderer - same result.

**Steps to reproduce**
Enable Fullscreen, play 20-30 minutes. 

**Hardware/software**
Linux Mint 20.1
Kernel: 5.8.0-41-generic
CPU: Intel Core i3-4330 (4) 3.500 GHz
GPU: Intel HD Graphics 4000
RAM: 8 GB

**Emulator version**
0.1-2997-g29cbdd7e

**Comment by stenzek** [comment]
Might be a driver bug related to https://github.com/stenzek/duckstation/issues/1218

**Comment by Farlander-001** [comment]
Log file is bigger than 10 MB. It can be downloaded here https://yadi.sk/d/Dp57-yFLOrZhtQ

**Comment by Farlander-001** [comment]
It is worth noting that only game crashes. Duckstation working as it should after I closed the game.

**Comment by nf6429** [comment]
@stenzek I've been playing through the gae, and had this issue after around 4 hours of play, the game just froze so bad that duckstation completely crashed. When i reloaded and changed to interpreter, didnt happen again. So this prob is an issue, but is extremely rare.

**Comment by stenzek** [comment]
@nf6429 try setting the CPU Fast Memory Mode in Advanced Settings to LUT instead of MMap.

**Comment by Nucleoprotein** [comment]
hmm:
"GP0(35h,37h,3Dh,3Fh) - Undocumented/Nonsense (Raw Texture + UNUSED shading)
These are undocumented inefficient nonsense commands: Parameters are same as for GP0(34h,36h,3Ch,3Eh), ie. with colors for all vertices, but without actually using that colors. Instead, the commands are rendering raw textures without blending.
In other words, the commands have same function as GP0(25h,27h,2Dh,2Fh), but with additional/unused parameters (and possible additional/unused internal gouraud shading calculations).
For whatever reason, **Castlevania** is actually using these nonsense commands, namely GP0(3Dh) and GP0(3Fh)"
