### ISSUE TITLE
Broken graphics while using nearest-neighbor - lots of games affected

### ISSUE THREAD

**Issue by Sekai9** [stenzek/duckstation#1542]
**Game details**
SLUS-00868 - Vigilante 8 - 2nd Offense (USA)
^ Redump verified

**Description of the issue / bug**
Random white/black lines or dots all over the place. Those graphical issues dissapear when using Bilinear, JINC2 or xBR.
You can clearly see it in this video:
https://streamable.com/apk1sp

This is one of the most affected games. At 0:13 you can see how it affects the Thunderbolt, at 1:15 i switch to Bilinear and those glitches go away, at 1:43 i enable the Software renderer and again, no more glitches.

**Steps to reproduce**
Just playing the game. Looks like some Intel driver bug to me, so i guess you need to test on the same hardware, or hopefully you'll be able to know what's going on just by looking at the video.
Also tested using the Interpreter, it made no difference.

**Enhancements information**
No enhancements at all.

**Hardware/software**
Intel i5-5300U + Intel HD 5500, Windows 10.

D3D + Intel HD 5500 > Issue is present
D3D + Microsoft Basic Render Driver > No issues.
OpenGL > Crashes Duckstation when compiling shaders, will open a bug later (TM).
Software > No issues.
Vulkan > not supported.

**Emulator version**
0.1-2997-g29cbdd7e

**Additional context**
Started noticing these glitches months ago, but due to lack of time, i couldn't properly test.
I will post more videos later.

**Comment by stenzek** [comment]
Sounds like a driver bug indeed. Or perhaps interpolation precision..

> OpenGL > Crashes Duckstation when compiling shaders, will open a bug later (TM).

Likely not fixable.

**Comment by Sekai9** [comment]
One more example:
**SLUS-01324 - Breath of Fire IV (USA)**
^ Redump verified. Tested this one exactly the same as Vigilante 8: 2nd Offense.

https://streamable.com/orhu88
0:14 > Bilinear
0:28 > Software rendering.

**Comment by Alien-Grey** [comment]
I've got a similar issue with Final Fantasy VII (Europe) - SCES-10867. Sometimes there are what look like broken horizonta land vertical green lines visible. Happens with both D3D11 and OpenGL renderers. I couldn't test Vulkan because the Intel HD Graphics hardware on that device doesn't support it. Only way to get rid of this is by using the Software renderer.

**Comment by Alien-Grey** [comment]
It's more visible in this screenshot.


![SCES-10867_2021-02-07_18-20-04](https://user-images.githubusercontent.com/25705769/107155466-de35ec80-6978-11eb-98bd-cc57a6510b96.png)

**Comment by Sekai9** [comment]
This issue is not present in the new **D3D12 renderer**, so i'll just keep using that.
Can't thank you enough for this. Awesome work!

**Comment by stenzek** [comment]
Pretty strange. It's using almost the exact same bytecode, same shader compiler as DX11. Weird driver issues I guess.
