### ISSUE TITLE
Graphical glitches in Jim Henson's The Hoobs (Europe) 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#155]
These issue happen with both OpenGL and D3D11.

There's a blue line underneath the opening video.

![Capture4](https://user-images.githubusercontent.com/31968468/77472033-6a294d80-6e67-11ea-964d-35b61d85ba27.PNG)

The in-game graphics are partially missing.

![SCES-03755_2020-03-25_02-37-30](https://user-images.githubusercontent.com/31968468/77472145-980e9200-6e67-11ea-9408-a5666b0c0298.png)

![SCES-03755_2020-03-25_07-02-58](https://user-images.githubusercontent.com/31968468/77472177-9fce3680-6e67-11ea-9ccf-ca559885f997.png)

Neither of these issues are present in Beetle PSX. 

![Capture](https://user-images.githubusercontent.com/31968468/77472293-cee4a800-6e67-11ea-958e-5822f7a77f9c.PNG)

![Jim Henson's The Hoobs (Europe)-200325-065457](https://user-images.githubusercontent.com/31968468/77472315-d4da8900-6e67-11ea-965e-47b7caf37e68.png)

![Jim Henson's The Hoobs (Europe)-200325-065504](https://user-images.githubusercontent.com/31968468/77472331-d86e1000-6e67-11ea-8754-946631d359eb.png)

**Comment by stenzek** [comment]
Is this still an issue on the latest builds? The blue line is probably overscan related and should be fixed, and the rendering issues may have been timing related.

**Comment by kurayami6** [comment]
It's fixed.
