### ISSUE TITLE
Emulation: Sound and Performance 

### ISSUE THREAD

**Issue by Abrahambrazil** [stenzek/duckstation#1552]
I was playing Crash Bandicoot, Bomberman Rumble Arena, and Street Fighter EX Plus 2 using Duckstation 0.1-2818 (I'm using Vulkan, region: NTSC-U, and all the other settings of the emulator are as DEFAULT) on my Xiaomi Mi Mix 2 with Android 10.
Then, I decided to upgrade to the lastest preview build and I noticed a huge difference in emulation because the speed is not the same as it used to be in Duckstation 0.1-2818, I also had audio issues during the intro of Street Fighter EX Plus 2. After that, I came back to Duckstation 0.1-2818 and Street Fighter EX Plus 2 is now running perfectly again (smooth and without the audio issue cited before) and the other games are fast and smooth like I'm playing on an actual PSX.
I don't know why the emulation changed like that.
I hope that the emulation keep improving and maintain its performance.
I am still on Duckstation 0.1-2818, I won't use this new version because it is not fast and smooth as the old version that I am using.

I love your emulator, it is the best PSX emulator for Android, it is free, and it is amazing. I just wanna thank all the developers for this masterpiece and I hope that it will get better and better.

**Comment by Ryusan-AT** [comment]
Stenzek t'a répondu ici 

https://github.com/stenzek/duckstation/issues/1551
