### ISSUE TITLE
Formula One 2001 (Europe) needs force interpreter on in per game settings or it will crash

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1556]
Without this the car is completely uncontrollable. It goes incredibly fast, moves by itself and after a minute or so the game will crash entirely. 

![SCES-03404_2021-02-01_12-07-01](https://user-images.githubusercontent.com/77198254/106404277-6eaa9380-6486-11eb-95f3-1c75d51b9abb.png)

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/3f981f0ceb9f96745aef4e26e5e8c67b65fa07ec
