### ISSUE TITLE
Disable linear filtering for GLES2 render path

### ISSUE THREAD

**Issue by Farlander-001** [stenzek/duckstation#1559]
**Describe the solution you'd like**
Strangely, I can't disable linear filtering when using software renderer. This will be great for 2D games present on PlayStation.

**Comment by stenzek** [comment]
Disable linear filtering in display settings?

**Comment by Farlander-001** [comment]
As I said, this option not working while using software renderer, at least with 2D games. I will dump some 3D game and try with it

**Comment by stenzek** [comment]
Which GPU/renderer?

**Comment by Farlander-001** [comment]
Atom N570 integrated graphics. Software renderer
![изображение](https://user-images.githubusercontent.com/62428757/106456227-cfa28d80-64bf-11eb-877a-484839816f3f.png)

**Comment by stenzek** [comment]
If it doesn't support GLES3, that's probably why. I use sampler objects to set the filter, which aren't supported in gles2. Would have to recreate the texture in such a case.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/43d1495a6344a5f64729b045a18bfda81830ee55
