### ISSUE TITLE
duckstation crash when plugging usb to playstation gamepad adapter

### ISSUE THREAD

**Issue by ProgrammingPlanet** [stenzek/duckstation#1560]
hi 

first of all great emulator....

but when i plug in my usb to ps2 gamepad adapter, duckstation closes and not launching untill i remove this adapter from pc.

here is image of my ps2 gamepad adapter - [image link](https://m.media-amazon.com/images/I/41KNUYOaauL.jpg)

and this link will lead to the driver software for this driver - [driver download link](https://drive.google.com/file/d/1xk92f9HSu2JD9XrlA2XHrOGYJStazPdJ/view?usp=sharing)

here is [crash.txt file](https://pastebin.com/SKRu92vH)

duckstation version -     0.1-3042-g7d036d6f(dev)

**Comment by stenzek** [comment]
Known broken driver - for future reference if anyone finds this on google:

1. Start duckstation with `-nocontroller` argument.
2. Go into settings and change the "SDL" controller interface to "DInput".
3. Restart duckstation without the `-nocontroller` argument.
