### ISSUE TITLE
Some Android Phone with 18.9:9 aspect ratio

### ISSUE THREAD

**Issue by tabnk** [stenzek/duckstation#1563]
**Is your feature request related to a problem? Please describe.**
Improper aspect ratio on Android Phone with notch 19.5:9 and without notch is 18.9:9 aspect LCD screen. 

**Describe the solution you'd like**
Currently only closer solution is using 19:9, however it does look a little weird on some android phone. 

However, a 19:9 aspect ratio is 3040:1440 whereas 18.9:9 is 3024:1440. Therefore, 18.9:9 will be perfect on phone with this aspect ratio.

**Comment by stenzek** [comment]
Rather than adding loads more AR options, I've implemented this as "Match Display" or "Match Window". Set the orientation to landscape, and the AR to "Match Display", and you should get 18.9:9. (only in preview build for now)

**Comment by tabnk** [comment]
It work as intended, Thank.
