### ISSUE TITLE
Starfighter Sanvein

### ISSUE THREAD

**Issue by waterclaws6** [stenzek/duckstation#1567]
Game details
SLUS-01302, Starfighter Sanvein (USA)

**Description of the issue / bug**
Starting intro for this game doesn’t display and play. No audio play also, just a black screen. 
You can still play the game without any issue by pressing start.

Steps to reproduce

1. Start the game

2. Wait for the intro to play. 

![SLUS-01302_2021-02-02_23-05-18](https://user-images.githubusercontent.com/78460448/106696677-35b80f00-65ab-11eb-8a76-f0c76d19cd87.png)

Enhancements information
All enhancements have been turned off

Hardware/software

Galaxy S20 FE 5G, Snapdragon 865 and Android 11

Laptop, AMD Ryzen 3200U, Vega 3 and Windows 10 Education X64

Vulkan, Software Render

Emulator version

DuckStation 0.1-3042-g7d036d6f Windows X64

DuckStation for Android 0.1-3019-g3c2b11fc (master) ARM64

**Comment by Kurayami7** [comment]
I'm sure I reported this game as broken ages ago and it was fixed. Maybe it regressed.

**Comment by waterclaws6** [comment]
That is the PAL Version that locked up. 

The NTSC - USA version doesn't lock up, it just doesn't play the intro at all.

**Comment by stenzek** [comment]
Wonder if it's the same issue as Vampire Hunter D - requiring really tight DMA timings.

Try setting the `DMA Max Slice Ticks` in compatibility settings to 100 or 200.

**Comment by Kurayami7** [comment]
Tried with 100 and 200, still a black screen.

**Comment by stenzek** [comment]
Okay, will have to check later.

**Comment by stenzek** [comment]
Disc timing issue - game does a seek followed by a read, and keeps retrying if the read takes too long to start.

**Comment by stenzek** [comment]
Fixed with https://github.com/stenzek/duckstation/commit/67344070ea86944e8bb5f4bc11d04565bd533528
