### ISSUE TITLE
[Request] support for MDF/MDS image format. 

### ISSUE THREAD

**Issue by mieser** [stenzek/duckstation#1570]
The emulator is currently missing support for the old Alcohol 120% mdf/mds file format. 

"The MDS file is comparable to the CloneCD Control File and cue sheet (.cue) file formats. However, their capabilities are not identical; also the cue sheet is a text file format.

Alcohol 120%'s MDF/MDS format is one of the few formats besides Nero's NRG, BIN/CUE and CloneCD's CCD/IMG/SUB disc image formats to support Mixed Mode CDs which contain audio CD tracks as well as data tracks." 

https://en.wikipedia.org/wiki/Media_Descriptor_File

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/753dd0480fcbe75a6dc3e346338dbf94ce31c374 , but still needs testing with multi-track images.

**Comment by mzso** [comment]
I had a problem in #2773, I don't know if it's because multi-track or completely separate.
