### ISSUE TITLE
Silent Hill - Dahlia Cutscene

### ISSUE THREAD

**Issue by Naratzull** [stenzek/duckstation#1572]
Description of the issue / bug
During the first cutscene with Dahlia, the game freezes dead
![SLES-01514_2021-02-03_22-34-13](https://user-images.githubusercontent.com/44362807/106786221-1f27bb80-6670-11eb-8d19-a58d5811090d.png)

Hardware/software
Windows 8.1
CPU: Ryzen 3 3100
GPU: GTX 1050Ti
RAM: 8 GB

Emulator version
0.1-3042-g7d036d6f

**Comment by stenzek** [comment]
Not a bug. Turn off PGXP/widescreen hack for this cutscene. You can do this easily by temporary checking disable all enhancements in advanced settings.
