### ISSUE TITLE
[Request] Launch games from other frontend on Android

### ISSUE THREAD

**Issue by SeventhSentinel** [stenzek/duckstation#1579]
**Is your feature request related to a problem? Please describe.**
Hello! I am using a frontend called Dig to launch all my emulators on Android. Dig will launch all of the emulators properly except for DuckStation. When it tries to launch a DuckStation game, the emulator is launched, but I am left to manually select my game at the main menu of DuckStation.

**Describe the solution you'd like**
I would like other apps to be able to directly launch DuckStation games so I can skip the top menu.

**Describe alternatives you've considered**
I briefly looked around for an alternative, but I couldn't find anything that made sense.

**Additional context**
This is what gave me the impression it was up to the emulator developer to fix this so that Dig can support it. [https://digdroid.com/forums/discussion/7/why-isn-t-emulator-abc-supported](url)

**Comment by stenzek** [comment]
It is definitely **not** the emulator's responsibility to sort out compatibility with third-party launches which we have no control over. The only thing the emulator should do is expose an activity which can be launched by the frontend.

DuckStation has this - `EmulationActivity`. See here: https://github.com/stenzek/duckstation/blob/469010868ed4b602ac066be75034ee3f1203172f/android/app/src/main/java/com/github/stenzek/duckstation/MainActivity.java#L336-L345

(so basically, you need to start `EmulationActivity` with `bootPath` set to the path of the game, and `resumeState` with a boolean indicating whether you want to auto-load state).

The only thing which possibly could be missing is the export flag in the manifest. I'll add that shortly.
