### ISSUE TITLE
World Destruction League - Thunder Tanks (USA) hangs before the main menu

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#158]
Stays on this screen forever.

![SLUS-01175_2020-03-25_12-20-57](https://user-images.githubusercontent.com/31968468/77492295-534d2000-6e94-11ea-88dc-f64650a0ad67.png)

![Capture](https://user-images.githubusercontent.com/31968468/77492311-5e07b500-6e94-11ea-85b8-b6cec4096545.PNG)

**Comment by stenzek** [comment]
The game does boot, it just gets stuck there for a very long time, periodically issuing CD-ROM commands.

**Comment by kurayami6** [comment]
Fixed as of the latest commit.
