### ISSUE TITLE
Failed to Create Host Display Device Context in Windows 8.1 and 10

### ISSUE THREAD

**Issue by arowhen1** [stenzek/duckstation#1584]
Please read before creating a new issue:

1. Make sure there is not already an open issue for this bug.
2. All enhancements **must** be off. To quickly disable all enhancements with affecting your normal config, in advanced options you can check "Disable All Enhancements".
3. All advanced options **must** be at their default values.
4. No cheats may be active. If you were using cheats, they should be disabled, and the game rebooted before reporting the bug.
5. Do not share save state files. Memory cards are okay.
6. Verify your dump, as we can not assist with issues resulting from bad dumps.
7. If playing PAL region software, please check whether or not the game has LibCrypt protection and that if it does, you have a correct SBI file (see https://github.com/stenzek/duckstation#libcrypt-protection-and-sbi-files for more information).
8. Please post your issue report in English as unfortunately this is the only language spoken by the developers. The Discord server has many helpful people if you need help translating.

**Remove everything before and including this line before submitting.**

**Game details**
[Serial Code, Region]
[i.e SLUS-00404 Ace Combat 2 (USA)]

**Description of the issue / bug**
[Describe what you are seeing and/or hearing during gameplay]

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
2. Which controller backend are you using in general settings

**Note:**
If you are using Duckstation on Android device please consider the following before report:
Are you using any kind of "memory optimizer" program such as: Ccleaner, Wisecleaner, Clean Master, Boost Android etc. ?
(if so, please, consider create an exception on it first and test; or even remove / uninstall it retest and then, if the problem persists continue with the report.

**Steps to reproduce**
[Try to provide as much detail as possible to reproduce the issue]

**Enhancements information**
[Make sure they are all turned off before report]

**Hardware/software**
[If Android, which phone and Android version]
[If desktop, your CPU, graphics card, and operating system]
[GPU Renderer - D3D11/OpenGL/Vulkan]

**Emulator version**
[Shown in the title bar of the emulator]

**Additional context**
[Add any other context about the problem here]

**Comment by stenzek** [comment]
Please fill out the template completely - several things are missing here.

This error will happen if you're trying to run on an unsupported configuration - for example, you selected Vulkan but your GPU does not support it.

**Comment by stenzek** [comment]
Closing due to lack of response.

**Comment by myownfriend** [comment]
@stenzek  Wasn't sure if I should start a new issue for this but I'm getting this exact same error on Fedora 34. The downloaded AppImage works just fine but after compiling it from master to get Wayland support, I'm getting the error on all renderer backends including Software.

**Comment by stenzek** [comment]
What does the log say? https://github.com/stenzek/duckstation/wiki/Enabling-Logging

**Comment by myownfriend** [comment]
Doesn't look to provide too much more information.
[duckstation.log](https://github.com/stenzek/duckstation/files/6828199/duckstation.log)

**Comment by stenzek** [comment]
That sounds like you didn't enable wayland in the cmake options. Should be something like `cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_NOGUI_FRONTEND=ON -DBUILD_QT_FRONTEND=ON -DUSE_DRMKMS=ON -DUSE_EGL=ON -DUSE_SDL2=ON -DUSE_WAYLAND=ON -DUSE_X11=ON -G Ninja ..`

**Comment by myownfriend** [comment]
Oh! The build instructions just said "When Wayland is enabled (default)" so I assumed I didn't have to specify any additional options. My bad.

Now I'm getting other issues. When launching a game, the OpenGL and software backends will show info in the status bar as if the game is running but nothing changes. Resizing the window makes the game/game list area go transparent and I get cursor trails. The Vulkan backend cause an immediate crash. The log under Vulkan doesn't even finish it's last message.

[duckstation.log](https://github.com/stenzek/duckstation/files/6828362/duckstation.log)


I'd say that some of this stuff could be Nvidia issues but that definitely didn't happen when I had it running on Wayland in Ubuntu.

**Comment by stenzek** [comment]
Sounds like typical Linux issues. Wayland is still a mess, but it does (mostly) work for me. This why I have:

> DuckStation does support Linux, but no support will be provided by the developer due to the huge range and variance of distributions. AppImage builds are provided, but we are not obliged to provide any assistance or investigate any issues, i.e. use at your own risk.

in the readme.

**Comment by myownfriend** [comment]
Oh :-(

**Comment by stenzek** [comment]
@myownfriend can see if the latest commits for Wayland make any difference, it's working flawlessly for now on AMD (even in GNOME with client side decorations).

**Comment by BailShamber** [comment]
> That sounds like you didn't enable wayland in the cmake options. Should be something like `cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_NOGUI_FRONTEND=ON -DBUILD_QT_FRONTEND=ON -DUSE_DRMKMS=ON -DUSE_EGL=ON -DUSE_SDL2=ON -DUSE_WAYLAND=ON -DUSE_X11=ON -G Ninja ..`



> @myownfriend can see if the latest commits for Wayland make any difference, it's working flawlessly for now on AMD (even in GNOME with client side decorations).

yup runs perfectly here as well.

**Comment by BailShamber** [comment]
well except some issues with drop down menus with the "QDarkStyle" theme, which has to be a qt bug, nothing to do with ducko.
![Screenshot from 2021-07-29 03-42-54](https://user-images.githubusercontent.com/49800926/127418508-c89c5fc2-91bb-4883-a325-5d24ac075aff.png)

all other themes are not affected.

**Comment by myownfriend** [comment]
Just recompiled from master and I'm still getting the same behavior except for the mouse trails. Guessing it's an Nvidia issue.

**Comment by stenzek** [comment]
I didn't think any of the compositors supported the nvidia blob anyway?

**Comment by myownfriend** [comment]
Mutter has supported it for a little while now. It already supported before I started using Linux in October of last year.
