### ISSUE TITLE
Crash when try to open a disk or add a folder in the game list option

### ISSUE THREAD

**Issue by Eddy00007** [stenzek/duckstation#1586]
I just update from version 0.1-2956-g44331976 (dev) to 0.1-3128-g05545566 (dev)

This happen when I use duckstation-qt-x64-ReleaseLTCG.exe

I went back to the default settings and got the same result

I attach the crash.txt file
regards

[crash.txt](https://github.com/stenzek/duckstation/files/5935308/crash.txt)

**Comment by stenzek** [comment]
Not getting any crashes here.

Unfortunately that crash file is incomplete. I've added minidump saving to the crash handler, so try switching to the preview build (settings -> update channel -> change latest to preview -> check for updates), and then uploading the `crash.dmp` file which should get created.

**Comment by stenzek** [comment]
Closing due to a lack of response. If you upload the crash dump, I can look into it.

**Comment by Chamlotte** [comment]
I've got this issue as well.

the crash.txt has only one line in it, `Exception 0xC0000005 at 0x00007FFAC8B62B26`

[crash.txt](https://github.com/stenzek/duckstation/files/6719574/crash.txt)

**Comment by stenzek** [comment]
It's probably a third party shell extension. I know oldnewexplorer seems to conflict with Qt

**Comment by Chamlotte** [comment]
Ow, oof, ouch. That could absolutely be the issue. Is there a line in a settings file could just paste the path into?
