### ISSUE TITLE
Graphical glitches and crash in Casper (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#159]
Garbage on the right side of the screen. Happens with both OpenGL and D3D11.

![Capture](https://user-images.githubusercontent.com/31968468/77495206-0705de00-6e9c-11ea-8d8d-31aa4f1be2f8.PNG)

After entering a loading zone the game displayed this message.

![SLUS-00162_2020-03-25_13-23-47](https://user-images.githubusercontent.com/31968468/77495280-2f8dd800-6e9c-11ea-911d-53f5dd54b329.png)

**Comment by stenzek** [comment]
Crash should be fixed in latest master. I think the stuff on the side is a result of computing the scanout rectangle incorrectly and common to all these games, I'm planning on rewriting it.

**Comment by kurayami6** [comment]
Yet more issues in Casper.

Certain items in chests can't be picked up. Casper claims the chest is empty even though the item is right in front of him.

![SLUS-00162_2020-03-28_05-27-48](https://user-images.githubusercontent.com/31968468/77788831-0e083880-70b6-11ea-8b67-cfbab8165dee.png)

The arrows on the floor don't render.

![SLUS-00162_2020-03-28_05-34-39](https://user-images.githubusercontent.com/31968468/77788899-2bd59d80-70b6-11ea-986e-52ce1525b0a4.png)

Beetle PSX for comparison.

![Casper (USA)-200328-053348](https://user-images.githubusercontent.com/31968468/77788929-38f28c80-70b6-11ea-92ea-d2a3c32d2650.png)

**Comment by forz0i** [comment]
It is possible to really modify to improve your graphics and graphics
processing data in D3D11 to fix this problem and other
The comparison and difficult, retroarch uses symbolic modulation ports by
their Beetle PSX HW which fx not bad but has trouble playing very slowly
slow
You can compare the performance of the Duckstation D3D11, you will find
that the data and graphics use the right formula for processing graphics
AND GIVE FAST performance

**Comment by kurayami6** [comment]
As of the latest version all known issues are fixed.
