### ISSUE TITLE
[Request] Add "undo save-" and "undo load state" options

### ISSUE THREAD

**Issue by ds22x** [stenzek/duckstation#1590]
This would greatly help when you accidentally either load a save state, or overwrite a save state.

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/762ab3ff438bac84268caf4587e1a572adb45d18. Undo save state doesn't really make sense, but there's a backup option added in https://github.com/stenzek/duckstation/commit/24306be7573741df10dae9c07fa918d10460288e.
