### ISSUE TITLE
Android TV compatibility - file explorer to locate games/bios files is not available

### ISSUE THREAD

**Issue by viktorkovarik** [stenzek/duckstation#1598]
Hi, I wanted to sideload Duckstation to my Android TV television (Philips) and Google TV box and I ran into issue. There is problem with integrated file explorer which is not available on Android TV can you please add support to some external file browsers for this platform or tweak this to be able to use native one (if present) on Android TV platform?

Thanks in advance!

**Comment by stenzek** [comment]
Android tv is not supported.

But you can add directories manually now in the game directory editor. In the menu there's an add path option.
