### ISSUE TITLE
[Feature Request] Dev Console Bios Support.

### ISSUE THREAD

**Issue by Trege** [stenzek/duckstation#16]
This is probably way beyond the scope of the project, but it'd be pretty cool to have support for the 8MB of RAM the developer consoles have, especially in the romhacking scene.

![Duckstation Dev bios](https://user-images.githubusercontent.com/5303028/74182162-260c2180-4c08-11ea-98c7-04ee60b2738a.png)

**Comment by stenzek** [comment]
Should be pretty straightforward.

**Comment by stenzek** [comment]
8MB RAM is added in https://github.com/stenzek/duckstation/commit/e382df0d41288491f4adb5eb2b5dcbebf9ebc0d2. Still need to expose it as a per-game setting.
