### ISSUE TITLE
Lifeforce Tenka (Europe) has graphical glitches and hangs after the first FMV

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#160]
Flashing line and squares at the top of the screen during the opening logos.

![Capture](https://user-images.githubusercontent.com/31968468/77496145-695fde00-6e9e-11ea-8109-a91b843cb975.PNG)

After the first FMV there's a loading screen and then the game hangs on a black screen.

![Capture2](https://user-images.githubusercontent.com/31968468/77496225-97452280-6e9e-11ea-9697-afbc7eb8ca20.PNG)

**Comment by stenzek** [comment]
Please retest on latest master after it builds.

**Comment by kurayami6** [comment]
It no longer hangs. However the graphical glitch during the opening logo is still present.

![Capture](https://user-images.githubusercontent.com/31968468/77859075-15187d80-7253-11ea-921f-c46bb0c3480c.PNG)

Also getting shot by the turret near the end of the first level causes the graphics to break entirely.

![SLES-00613_2020-03-30_06-46-23](https://user-images.githubusercontent.com/31968468/77859101-2feaf200-7253-11ea-81a5-fb446e1dcb78.png)

**Comment by kurayami6** [comment]
The loading screen also doesn't render properly.

Duckstation

![SLES-00613_2020-03-30_07-14-07](https://user-images.githubusercontent.com/31968468/77859684-99203480-7256-11ea-9358-a1bb0a257500.png)

Beetle PSX

![Lifeforce Tenka (Europe)-200330-071331](https://user-images.githubusercontent.com/31968468/77859700-aa694100-7256-11ea-8dac-7495ceab385e.png)

**Comment by stenzek** [comment]
Corruption should be fixed in latest master. The FMV issue is likely overscan related.

**Comment by stenzek** [comment]
This one's fixed as far as I can tell.
