### ISSUE TITLE
[Request] Controller Binding QoL

### ISSUE THREAD

**Issue by csudderth** [stenzek/duckstation#1603]
I primarily use Duckstation on Android and have a few feature requests regarding controller bindings.

1. Have hotkeys save to controller profiles. The current behavior is that hotkeys are universal and are not saved to the controller profile ini. 

2. Have button combinations be set as hotkeys. For example, I'd love to be able to press L3 + R3 to open the menu or press select + R2 to fast forward. 

3. Be able to map MEDIA_PLAY_PAUSE on Android. I am currently using Android 10 on a Nintendo Switch and the screenshot button on the left joycon is currently set to MEDIA_PLAY_PAUSE. I'd love to be able to use this key in a keymapping, such as the analog button or bringing up the menu.

4. Multiple keymappings for one button. For example, in Final Fantasy Tactics, I like to set L & R to their proper buttons as well as X- and X+ on the right joystick.

**Comment by vectorcr** [comment]
This would be a great feature to add to the android build. I just bought an adapter and realized that it wasn't compadible :(
