### ISSUE TITLE
Digimon World (SLUS-01032)

### ISSUE THREAD

**Issue by PanduGP** [stenzek/duckstation#1604]
**Game details**
Digimon World (USA) SLUS-01032

**Description of the issue / bug**
The game can't accept start button to enter the game

**Steps to reproduce**
Run the game as usual

**Hardware/software**
Pocophone F1 6GB
Android 10
CPU Snapdragon 845
GPU Adreno 630

**Emulator Version**
0.1-3019-g3c2b11fc (Android)

**Comment by Kurayami7** [comment]
Do you understand that filling the github with useless junk reports like this buries legitimate issues and stops them getting fixed? You've ignored the template and provided no useful information whatsoever.

**Comment by PanduGP** [comment]
Ah sorry for my ignorance
First time opening github on mobile
Will fix it asap
Thank you

**Comment by stenzek** [comment]
Is this game compatible with the analog controller/dualshock? Some games aren't.

Try setting your controller type to digital and see if it makes any difference. If so, we need to add an override to this game to force it.

**Comment by PanduGP** [comment]
> Is this game compatible with the analog controller/dualshock? Some games aren't.
> 
> Try setting your controller type to digital and see if it makes any difference. If so, we need to add an override to this game to force it.

Yes it actually works with digital gamepad mode. Thank you

**Comment by stenzek** [comment]
Great, thanks for checking. I'll leave this open to remind me to add an override for this game.

**Comment by Kurayami7** [comment]
Digimon World (USA) works perfectly fine with analogue. It doesn't need a per game setting. 

![SLUS-01032_2021-02-08_17-07-19](https://user-images.githubusercontent.com/77198254/107182134-4e537980-6a30-11eb-86d6-c55852a67a92.png)

![SLUS-01032_2021-02-08_17-07-29](https://user-images.githubusercontent.com/77198254/107182141-514e6a00-6a30-11eb-9b71-1b2a5042e26d.png)

**Comment by stenzek** [comment]
Even with the "force analog mode on reset" option checked? (that's likely more the issue, since a dualshock in digital mode behaves the same as a digital controller)

**Comment by Kurayami7** [comment]
Okay yeah that breaks it.

**Comment by stenzek** [comment]
Override added in https://github.com/stenzek/duckstation/commit/d1536fdc62182ca87f5376ce84dd99c76a51072f
