### ISSUE TITLE
Remove all aspect ratio options except for auto and 4:3

### ISSUE THREAD

**Issue by ReaperMan02** [stenzek/duckstation#1606]
The PlayStation, released in the mid 90s, was created during a time when the vast majority of households had a TV with a 4:3 aspect ratio, thus having any option other than Auto and 4:3, as any other option would distort the image significantly. The only exception to this however would be if the widescreen hack was turned on, or if the game natively supported widescreen mode, which is where "Auto" comes in.

**Comment by stenzek** [comment]
Please stop creating nonsense issues, it is not constructive. There's plenty of other emulators without enhancements which you can use if having the options bothers you that much.

**Comment by ReaperMan02** [comment]
They are not nonsense issues, they fucking make sense.
