### ISSUE TITLE
Graphics in Bedlam (Europe) are completely broken and the game hangs

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#161]
![SLES-00334_2020-03-26_02-27-54](https://user-images.githubusercontent.com/31968468/77554622-6ac6f000-6f0a-11ea-80e6-ad9d3caa867c.png)

![SLES-00334_2020-03-26_02-28-02](https://user-images.githubusercontent.com/31968468/77554638-70bcd100-6f0a-11ea-8ff0-d4189d5bbec9.png)

![SLES-00334_2020-03-26_02-28-08](https://user-images.githubusercontent.com/31968468/77554655-761a1b80-6f0a-11ea-8b18-b97e89f7652d.png)

![SLES-00334_2020-03-26_02-28-39](https://user-images.githubusercontent.com/31968468/77554669-7a463900-6f0a-11ea-9761-5245b5c7e696.png)

And finally it hangs on this screen. Or at least I can't progress any further. This might be the start menu and I just can't press the button. 

![Capture2](https://user-images.githubusercontent.com/31968468/77554765-977b0780-6f0a-11ea-83be-192609cc57a1.PNG)

**Comment by stenzek** [comment]
Please re-test on latest build.
