### ISSUE TITLE
[Qt Frontend] Add a "Lock Toolbar" option when right-clicking on the toolbar (and hide the toolbar handle).

### ISSUE THREAD

**Issue by fenrir0054** [stenzek/duckstation#1611]
There doesn't appear to be a way to lock the toolbar in position. Locking the toolbar would be nice so you can't accidentally click/drag it to another position, and also it would remove the toolbar drag handle which looks better and serves no purpose when you don't want to move the toolbar.

Currently right-clicking on the toolbar opens a context menu with the only option to close the toolbar (called "toolBar", which I assume is the default placeholder text?). This is redundant with the option in the View menu (not strictly an issue), however the two options don't synchronize their states so if you close it with the right click context menu it still shows checked (visible) under the View menu. See the second image below.

**Describe the solution you'd like**
Remove the toolbar toggle from the right click context menu and replace it with a "Lock Toolbar" option (which also hides the toolbar handle).

**Describe alternatives you've considered**
Add a "Lock Toolbar" option to the View menu and remove the right-click context menu entirely.

Add a "Lock Toolbar" option to the right-click context menu and keep the toggle option, but fix the toolbar visibility state synchronization issue between the two options.

![1](https://user-images.githubusercontent.com/61073421/107287461-9a4df080-6a27-11eb-842e-cb21d2840dd7.jpg)

![2](https://user-images.githubusercontent.com/61073421/107287477-a043d180-6a27-11eb-87df-9987a68b2066.jpg)

**Comment by stenzek** [comment]
Noting here for future reference: https://doc.qt.io/qt-5/qtoolbar.html#movable-prop

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/e75f1c1b6d6a92a85173b01e74206f9eff9f44dc
