### ISSUE TITLE
macOS: adaptive downsampling generates red and blue flickering lines

### ISSUE THREAD

**Issue by tycooko** [stenzek/duckstation#1618]
Pretty much what the title says. Happens in 100% of games when using adaptive downsampling and it's more and more noticeable as resolution increases. The lines are pretty thin, so I'm showing dark screen captures here, to help spot them.

I know, I know: **it's a Mac issue**. If anyone could be so kind to point me to whatever/whoever is responsible of this, I will take care of the next steps myself.

<img width="1093" alt="Screen Shot 2021-02-09 at 12 03 55" src="https://user-images.githubusercontent.com/75950926/107355554-e81e3380-6acf-11eb-905a-662f007be47d.png">
<img width="1093" alt="Screen Shot 2021-02-09 at 12 04 06" src="https://user-images.githubusercontent.com/75950926/107355562-eb192400-6acf-11eb-81bd-d0551a5d3dee.png">

**Comment by stenzek** [comment]
Hmm, doesn't happen on an NVIDIA GPU with native Vulkan at least.

Would probably need to look in a graphics debugger - it's almost like the UVs are off by one, and it's picking up nearby VRAM texels.

**Comment by tycooko** [comment]
As written in that unanswered email of one month ago, I'm at your disposition. Tell me how can I help you help me.

**Comment by stenzek** [comment]
Sorry, the email listed in my GH profile gets a *lot* of noise and I miss things occasionally.

Not really sure if you can do much, or if renderdoc is even compatible with macos. I've tried to use the xcode graphics debugging features in the past and it was very.... clunky and unreliable.

When I get a chance I'll throw together a patch with some extra clamping, but there's not much else I can think which could be causing this, other than sampler precision differences.

**Comment by tycooko** [comment]
Well, then I'll write here what I wrote there: you can instruct/lead me to have me do what YOU would have done yourself, if you had a Mac available, or we could do a TeamViewer session. It doesn't have to be NOW; it could be in a month, for that matter. Only..."in a month" sounds better than "I don't know if I'll ever be able to do something about it", right?
Just putting my two cents there.

**Comment by tycooko** [comment]
Anyway: only happens with Vulkan. Should I contact the guys at MoltenVK again? Can't they be helpful?

**Comment by stenzek** [comment]
Adaptive downsampling isn't implemented in OpenGL, since it'd require texture views (which needs GL4.3).

I'm probably just going to disable/remove the GL renderer for macs anyway, it's basically useless because of multiple driver bugs (texture buffers, shader compiler to name a few).

I very much doubt it's a MVK issue - the shaders here are quite simple. More likely it's just a difference in precision or interpolation which has to be worked around.

**Comment by tycooko** [comment]
> Adaptive downsampling isn't implemented in OpenGL, since it'd require texture views (which needs GL4.3).
> 
> I'm probably just going to disable/remove the GL renderer for macs anyway, it's basically useless because of multiple driver bugs (texture buffers, shader compiler to name a few).
> 
> I very much doubt it's a MVK issue - the shaders here are quite simple. More likely it's just a difference in precision or interpolation which has to be worked around.

I endorse the removal of OpenGL for the Mac. A few months ago, it was decent/playable. If you saw the colored, carnevalesque, glitchy mess that it is at this stage of the software, you'd remove it the second after.
Anyway: it won't probably give you too much of a help, but I temporarily solve the colored side lines by literally "cutting" them off, cropping the right and bottom side of the image...only to have them back every new update (and then I can hide them again, but needing different coordinates/parameters).

**Comment by stenzek** [comment]
> I endorse the removal of OpenGL for the Mac. A few months ago, it was decent/playable. If you saw the colored, carnevalesque, glitchy mess that it is at this stage of the software, you'd remove it the second after.

If I remember correctly it was bisected to this commit: https://github.com/stenzek/duckstation/commit/e71f6aa80a4d0c01f2ce71850103f9c20bed0bfc

I just didn't bother making it conditional on not-macos because of the other bugs, which had both performance and graphical implications (just didn't affect all games).

> Anyway: it won't probably give you too much of a help, but I temporarily solve the colored side lines by literally "cutting" them off, cropping the right and bottom side of the image...only to have them back every new update (and then I can hide them again, but needing different coordinates/parameters).

Crop parameters shouldn't be changing.. assuming you're going through game properties -> compatibility. Perhaps check that they're being saved to `gamesettings.ini`.

**Comment by tycooko** [comment]
Crop parameters don't change. It's the lines that move around (apparently). Sometimes they're above, sometimes they're below. With a version of the software a "9" parameter suffices to hide them; then in the next version I need to change it increase it to a "10", etc.

**Comment by stenzek** [comment]
Noticed this while investigating a different issue, https://github.com/stenzek/duckstation/commit/97cf3f770eb96da115d3d0926b137ff411dd6074 fixes it for me on Windows.

**Comment by tycooko** [comment]
I have to admit that I don't use the Windows version that much, but I haven't noticed the same happening on Windows, once every 10 or 14 days when I go there.
Anyway: can I try the fix? What file do I have to download? Thanks!

**Comment by andercard0** [comment]
> I have to admit that I don't use the Windows version that much, but I haven't noticed the same happening on Windows, once every 10 or 14 days, when I go there.
> Anyway: can I try the fix? What file do I have to download? Thanks!

Hi you can grab latest version here.

https://github.com/stenzek/duckstation/releases
Click Assets > Windows X64

**Comment by tycooko** [comment]
> > I have to admit that I don't use the Windows version that much, but I haven't noticed the same happening on Windows, once every 10 or 14 days, when I go there.
> > Anyway: can I try the fix? What file do I have to download? Thanks!
> 
> Hi you can grab latest version here.
> 
> https://github.com/stenzek/duckstation/releases
> Click Assets > Windows X64

Thanks, but I meant for macOS.

**Comment by stenzek** [comment]
You can grab the preview build here https://github.com/stenzek/duckstation/releases/tag/preview

**Comment by tycooko** [comment]
> You can grab the preview build here https://github.com/stenzek/duckstation/releases/tag/preview

There's no Mac version there. There hasn't been a Mac version in the preview builds in weeks. You only present a Mac version in the development builds now, apparently.

**Comment by stenzek** [comment]
Ah, it's missing from the create release job, whoops.

Can grab the artifact from here in the meantime

https://github.com/stenzek/duckstation/actions/runs/607484015

**Comment by tycooko** [comment]
Cool. Now DS hangs when I try to start any game. LOL. :)
I need to force quit it to take back control.

**Comment by tycooko** [comment]
The game start with software and OpelGL, but crash with Vulkan.

**Comment by stenzek** [comment]
Even with downsampling off? Because not much else has changed

**Comment by tycooko** [comment]
Yes. I'm just trying right now with downsampling disabled in the main settings and games that never had downsampling enabled in their individual settings, obviously selecting full boot. Vulkan doesn't work.
But why do you say that not much else has changed? I see a new option for achievements in the menu (very cool!).

**Comment by stenzek** [comment]
Nothing else except making the shader compilation interruptible. There's no API violations going on as far as I'm aware, only checked a couple of days ago, so without a backtrace there's not much I can do.

**Comment by tycooko** [comment]
This doesn't help?
[Log.txt](https://github.com/stenzek/duckstation/files/6056887/Log.txt)

**Comment by tycooko** [comment]
I don't know exactly how, but, all of a sudden, it has started working. I've had to clear caches/preferences several times (while it kept not working), reboot my Mac repeatedly, install, uninstall the app, reinstall the previous version... That's why I don't know exactly WHAT did it, but now it works correctly and the colored lines have disappeared.

**Comment by stenzek** [comment]
That log shows it stuck in MoltenVK, so maybe removing the cache solved it.. difficult to say. But not an emulator issue regardless.

Anyway, seems like the issue here is solved.
