### ISSUE TITLE
Spyro 2 and 3 (Europe) both crash with the same error message

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#162]
![Capture](https://user-images.githubusercontent.com/31968468/77555664-9eeee080-6f0b-11ea-9a87-6f10a7d91e9d.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/77556423-9cd95180-6f0c-11ea-8697-12f572f89c69.PNG)

**Comment by stenzek** [comment]
Please post the console log. I added specific logging of invalid commands for that reason.

**Comment by kurayami6** [comment]
Spyro 2.

![Capture](https://user-images.githubusercontent.com/31968468/77558147-b5e30200-6f0e-11ea-81f8-4b86406e14b9.PNG)

Spyro 3

![Capture2](https://user-images.githubusercontent.com/31968468/77558325-ec208180-6f0e-11ea-8839-7c293063ff27.PNG)

**Comment by stenzek** [comment]
Please retest on latest master,

**Comment by kurayami6** [comment]
Fixed
