### ISSUE TITLE
Archlinux - Controller not working with evdev

### ISSUE THREAD

**Issue by spinktvis** [stenzek/duckstation#1620]
Compiled from latest git. Enabled the evdev controller backend in General Settings - Miscellaneous. No controller input is detected at all, cannot even map buttons. Tested it with Dolphin-Emu, controller works with evdev. I am using a Logitech Rumblepad 2.

```
sudo pacman -Q libevdev
libevdev 1.11.0-1
```
```
sudo pacman -Qo /usr/lib/libevdev.so
/usr/lib/libevdev.so is owned by libevdev 1.11.0-1
```

**Comment by stenzek** [comment]
Are you a member of the `input` group, or whatever group owns `/dev/event/inputN` on Arch? What does the log say?

**Comment by stenzek** [comment]
Fwiw, you really don't want to use evdev generally. It's a fallback for where SDL doesn't work, mainly intended for the ODROID-Go Advance. Use SDL.

**Comment by spinktvis** [comment]
Thanks for that info Was just testing it to see if it worked. SDL works indeed fine. I don't see anything related in my logs to Duckstation and the Rumblepad unfortunately.

**Comment by stenzek** [comment]
Probably a permission issue then - you need access to the device nodes, which most distros don't give you by default (as it's a security risk).

**Comment by spinktvis** [comment]
Thanks for the reply. Just in the hopes to expand my knowledge a little, and for curiosities sake. Since Dolphin works with evdev, and Duckstation doesn't, even when being a member of the input group, is that because of the way evdev is implemented in Duckstation? Like you said it is for Odroid Go, which to my knowledge uses Emulationstation as its OS. So Emulationstation opens device nodes to the users? Is that correct?

**Comment by stenzek** [comment]
Looks like Dolphin uses udev to enumerate devices, whereas I just iterate through them sequentially and stop at the first input device it can't open. Probably why it's not showing up - your user might have access to the gamepad devices but not the keyboard/mouse/etc.

One of the many things I need to improve.. :)
