### ISSUE TITLE
Motion interpolation with runahead frames

### ISSUE THREAD

**Issue by garmendes** [stenzek/duckstation#1623]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Option to do motion interpolation when using runahead to target 60 fps.

**Describe alternatives you've considered**
Game-specif hacks that unlock the frame rate.

**Additional context**
It is possible to take advantage of the reduced latency that the runahead technique provides to introduce motion interpolation
between the runahead frames without introducing significant latency? For example, run 2 frames ahead and, intead of discarding then, interpolate and generate a additional frame, "doubling" the fps.

Example video using a prerecorded footage. But if this is possible then it can happen in real time.
https://www.youtube.com/watch?v=h9B9ZIB_Tyc

**Comment by stenzek** [comment]
I haven't came cross any FOSS libraries for framerate doubling, but my intuition is that this would be *way* too CPU-intensive to be realistic, as runahead already significantly increases CPU requirements. I get the impression you also need multiple frames of data for "good" interpolation.
