### ISSUE TITLE
Since latest update controller is not being recognised 

### ISSUE THREAD

**Issue by GitHubDan01** [stenzek/duckstation#1624]
Please read before creating a new issue:

1. Make sure there is not already an open issue for this bug.
2. All enhancements **must** be off. To quickly disable all enhancements with affecting your normal config, in advanced options you can check "Disable All Enhancements".
3. All advanced options **must** be at their default values.
4. No cheats may be active. If you were using cheats, they should be disabled, and the game rebooted before reporting the bug.
5. Do not share save state files. Memory cards are okay.
6. Verify your dump, as we can not assist with issues resulting from bad dumps.
7. If playing PAL region software, please check whether or not the game has LibCrypt protection and that if it does, you have a correct SBI file (see https://github.com/stenzek/duckstation#libcrypt-protection-and-sbi-files for more information).
8. Please post your issue report in English as unfortunately this is the only language spoken by the developers. The Discord server has many helpful people if you need help translating.

**Remove everything before and including this line before submitting.**

**Game details**
[Serial Code, Region]
[i.e SLUS-00404 Ace Combat 2 (USA)]

**Description of the issue / bug**
[Describe what you are seeing and/or hearing during gameplay]

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
2. Which controller backend are you using in general settings

**Note:**
If you are using Duckstation on Android device please consider the following before report:
Are you using any kind of "memory optimizer" program such as: Ccleaner, Wisecleaner, Clean Master, Boost Android etc. ?
(if so, please, consider create an exception on it first and test; or even remove / uninstall it retest and then, if the problem persists continue with the report.

**Steps to reproduce**
[Try to provide as much detail as possible to reproduce the issue]

**Enhancements information**
[Make sure they are all turned off before report]

**Hardware/software**
[If Android, which phone and Android version]
[If desktop, your CPU, graphics card, and operating system]
[GPU Renderer - D3D11/OpenGL/Vulkan]

**Emulator version**
[Shown in the title bar of the emulator]

**Additional context**
[Add any other context about the problem here]

**Comment by GitHubDan01** [comment]
Since latest update controller is not being recognised cannot input anything

**Comment by stenzek** [comment]
You did not fill out the issue report, therefore this is missing critical information.

Which controller interface are you using?

Also https://github.com/stenzek/duckstation/wiki/Enabling-Logging

**Comment by GitHubDan01** [comment]
> You did not fill out the issue report, therefore this is missing critical information.
> 
> Which controller interface are you using?
> 
> Also https://github.com/stenzek/duckstation/wiki/Enabling-Logging

I am using an xboxone pad Hyperkin and ive tried changing it from digital to analog to joystick and im pressing a button and nothing is happening

**Comment by GitHubDan01** [comment]
it is not recognising my previous inputprofile for the controller i had set up

**Comment by GitHubDan01** [comment]
[log.txt](https://github.com/stenzek/duckstation/files/5955344/log.txt)

**Comment by stenzek** [comment]
That's not a full log. Please follow the instructions otherwise I can't help you.

**Comment by GitHubDan01** [comment]
I've read online it isn't just me having this issue 

i followed this exactly and i copied everything it said into that .txt 
Open DuckStation.
Open Settings -> Advanced Settings.
Set the Log Level drop-down to Debug.
Check the Log To System Console and Log To File.
Close and re-open DuckStation.
Start your game and reproduce whichever issue you are having.
Either screenshot the console window, or:
Close DuckStation, and
Send us a copy of duckstation.log in your user directory

**Comment by stenzek** [comment]
> Which controller interface are you using?

(General Settings, "Controller Backend")

**Comment by GitHubDan01** [comment]
under settings i dont see anything that says general 

also i dont know what a backend is

I have tried to set the keys using digital to analog to joystick and nothing is working

**Comment by GitHubDan01** [comment]
I go to bindings i press up and nothing happens its like it doesn't recognise the pad but it did before the last update

**Comment by stenzek** [comment]
Look for this option in general settings:

![image](https://user-images.githubusercontent.com/11288319/107453031-f0d93d00-6b95-11eb-8ae8-d3c47f12aafd.png)

It should be set to SDL.
