### ISSUE TITLE
Limit upscaling options based on Android chipset

### ISSUE THREAD

**Issue by jpchow26** [stenzek/duckstation#1626]
**Is your feature request related to a problem? Please describe.**
To prevent disappointing less than knowledgable users, the Android application should do a general cutoff of upscaling options when the device chipset is detected to be less than ideal and simply hide any higher resolutions or features.

**Describe the solution you'd like**
Eg. if Snapdragon 400 series chipsets are detected, limit upscaling features to 720p as a maximum and hide the rest, and also disable xBR and JINC for example. If Mediatek only allow 3x or something and hide the rest. Users won't get mad at what they won't be able to see.

Maybe take a step further and test for Vulkan context and drop it from renderer features if the phone doesn't allow creating vulkan.

Hardware limiting can be updated as more complaints come in from troublesome devices and chipsets. It's not fun app work but it'll help in the long run with support requests.

**Describe alternatives you've considered**
Users aren't understanding what upscaling means in the vein of what their device is, since TBQH they don't read the Play store preamble and don't want to learn. So lets save them from themselves so you save your sanity with troublesome users complaining.

**Comment by tycooko** [comment]
It sounded like something out of Himmler's diary or something: "These rats they call 'people' are not worth our precious oxygen. We should execute the final solution for their own good."
I hope James Bond comes soon and busts your plans, while you sit there at your desk caressing your white cat and laughing.

**Comment by stenzek** [comment]
Unfortunately something like this is necessary - the way that many Android operate is "oh, the option is there, that means my $20 phone must support it. 1 star if it doesn't". I've had the pleasure of dealing with a few of them over the last few weeks.

More time spent dealing with angry "customers" (as they like to call themselves, I don't see how they're a customer when they haven't paid anything, but that's besides the point) means less time working on the actual software.

**Comment by tycooko** [comment]
> Unfortunately something like this is necessary - the way that many Android operate is "oh, the option is there, that means my $20 phone must support it. 1 star if it doesn't". I've had the pleasure of dealing with a few of them over the last few weeks.
> 
> More time spent dealing with angry "customers" (as they like to call themselves, I don't see how they're a customer when they haven't paid anything, but that's besides the point) means less time working on the actual software.

I'm sure it is. Still, "Let's save them from themselves" is a masterpiece of misanthropy and I'm loving its Evil Queen's vibes.
No one can help me not picture the evil cackle followed by thunders in the background happening at the end of this " master race of engineers' manifesto". :)

**Comment by PookaMustard** [comment]
An alternative solution would be to hide these settings (and show other advanced features that haven't made it to the Android frontend) behind something like Android's own "tap build number button in the status screen ten times to access Developer Options" thingy. Basically there'd be something like a "DuckStation version" in the advanced or general options menu, and it would appear to do nothing. Unless the user taps things several times in a row, or actually reads the app's manual/description what have you, they won't even know there are settings waiting to be revealed to them.

This would be a middleground between having to deal with less angry "customers" and showing the full array of options to those who are savvy (or random) enough to tap a button ten times.

**Comment by tycooko** [comment]
I really like this option, but besides that: isn't the whole "carefully valuing and tuning the device making DuckStation balanced" much more problematic and time-consuming to implement then the issues it wishes to solve? I mean, there are so many elements that constantly change a device's capabilities and performance: the RAM (which could be upgraded), the storage, the OS firmware version, apps that makes it more efficient that could or could not be present and, sometimes, part of the hardware simply weakens because of physical damage or dust during the years. Would DuckStation constantly monitor all of this and switch to lower or superior versions accordingly? Or would you follow a more practical but unnecessarily severe way of handling this, just cutting off features for certain devices, even if it is too much because the owners have actually upgraded them in some way?

**Comment by stenzek** [comment]
This is purely for Android - RAM can't be changed there.

While the advanced option tap is a good idea, I don't think hiding all enhancements behind it is a solution either.

**Comment by Richard-L** [comment]
I think this is part of a bigger discussion about Android experience, where everything needs to be spoonfed and done for you in the most OOBE way possible so an app is well received. For a more balanced word let's say "guidance" or "advice".

The problems people report about Android give plenty insight into what could be solutions. Total understanding if Sten doesn't want to do them, but in this case, it could be quick benchmark it performs on first run, or just checks what system is present from a database, to then choose "recommended" settings. Would allow you to increase the likelihood of users having a good experience with DS.

At the end of the day though, as long as there's another app that for some reason runs better for them, they will _always_ bring it up and not care about whatever "petty technical reasons" you geeks have for why it wouldn't in DS. It's just the ignorance and selfishness you need to be prepared to put up with if you're wanting Android success.

**Comment by 6lackmag3** [comment]
@stenzek maybe providing a description for resolution scale option should help? Or make a simple pop-up with warning if resolution is set higher than x4?
Btw DuckStation lacks even a basic manual which may be a great support for inexperienced users. That's my two cents.

**Comment by QmwJlHuSg9pa** [comment]
If you were to employ hardware heuristics, then my preference would be some kind of designation next to each option (perhaps an asterisk), with an explanatory [footer](https://source.android.com/devices/tech/settings/settings-guidelines#footer) stating something to the effect of "not recommended for your device".

Pretending that options do not exist within the program seems disingenuous.

**Comment by Richard-L** [comment]
Colours work well here I think. Options chosen with green shading is fine for device, red shading not so much.

**Comment by stenzek** [comment]
> If you were to employ hardware heuristics, then my preference would be some kind of designation next to each option (perhaps an asterisk), with an explanatory footer stating something to the effect of "not recommended for your device".
> 
> Pretending that options do not exist within the program seems disingenuous.

That sounds good in theory, but I suspect that it may not be sufficient. To paraphrase what a user was saying the other day "the option is there, it should work", and an explanation that their device was not powerful enough yielded nothing except "well you should make it work".

**Comment by foxsevent** [comment]
I'd say just add a pop up warning on the more demanding enchancrments like render resolution, PGXP and multi sampling.
Something like hey dipshit this function requires powerful device, your 80$ burner phone may not run well.
You could also limit these features, like what's the point in 10x upscaling on a 5inch 1080p phone.

But in all seriousness just ignore them, if they can't be bothered to learn and understand the most basic shit why waste time helping them.

You can't help people who won't help themselves.

**Comment by PookaMustard** [comment]
I had a sort of a decent idea, actually. If:

- the emulation speed is not consistently at 100% (e.g. for five seconds or more)
- the resolution upscaling is more than 1x

Then pop-up a window telling the user that they could downscale to fix their speed problems, with a yes or no. If they choose to dismiss the pop-up, it will re-appear again but this time with a "Don't show this again" checkbox. This way, users know that when their game was slow, DuckStation offered to speed it up for them.
