### ISSUE TITLE
This is Football 2 (Europe) hangs after opening FMV

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#163]
![Capture](https://user-images.githubusercontent.com/31968468/77560466-a74a1a00-6f11-11ea-96c9-d2ce6e6b4717.PNG)

**Comment by kurayami6** [comment]
Pooh's Party (USA) does the same thing after choosing a character.

![Capture](https://user-images.githubusercontent.com/31968468/77561146-71596580-6f12-11ea-9cb1-b587cf18c89e.PNG)

**Comment by stenzek** [comment]
Should be fixed by latest master.

**Comment by kurayami6** [comment]
This Is Football 2 no longer hangs during the opening but trying to start a game causes the whole emulator to freeze.

![Capture](https://user-images.githubusercontent.com/31968468/77832093-96a2d980-7187-11ea-87c2-345480ad0ac0.PNG)

**Comment by stenzek** [comment]
Fixed with GPU timings (not merged yet).

**Comment by stenzek** [comment]
Should be fixed on latest master.
