### ISSUE TITLE
Question: About screenshot

### ISSUE THREAD

**Issue by daikonman-sp** [stenzek/duckstation#1631]
Integer Upscaling.
If you take a screenshot, it will be 292 pixels horizontally. (All games)
I think the game screen is also 292 pixels horizontally.

PAR 1:1 is correct.(screenshot, game screen)

The duckstation libretro core is 320x240.

Thank you.

**Comment by stenzek** [comment]
It's probably because the screenshot grabs directly from VRAM and applies the AR, so the black borders added when the DAC is off aren't included.

**Comment by stenzek** [comment]
Ability to capture screenshots at window resolution was added in https://github.com/stenzek/duckstation/commit/359d1509be3abfc884bc74b63c7091bc308e632d
