### ISSUE TITLE
"Run the game in 'report mode' " feature

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#1633]
**Is your feature request related to a problem? Please describe.**
No. It's just a quality of life change that may help for users that use duckstation in day to day to have a option that launches the game without need to uncheck critical enhancement features before the test of a certain game and lost the previous configuration. 

**Describe the solution you'd like**
Run-ahead. Clock Speed control. Alternative CD-ROM speed. PGXP. Widescreen hacks. Cheat codes. 
Wow, duckstation have a lot of nice features to use in day to day basis, expanding the capacities which original Playstation console had. They contributes to make Duckstation a so nice experience!
But, some of them can lead to false positives reports.
That's why we ever recomend to uncheck some of these features before report something.
But uncheck everything and recheck the options again after make a report can be annoying, ever more when new fancy features comes in.
The idea is to provide easy-way to just run immediatelly the games with everything that potencially can lead to false positives off. This way, we can just ask to users to runs the game in "report mode" to be sure that everything is really off and then the user after this, can easily have the options on in their next section, without the need to turn everything off and on again.

**Comment by stenzek** [comment]
Already exists - see "disable all enhancements" in advanced options.
