### ISSUE TITLE
[SLUS-01161] Driver 2 (USA) (Disc 1) - Not recognizing memory cards

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#1634]
**Game details**
[SLUS-01161] Driver 2 (USA) (Disc 1)

**Description of the issue / bug**
The game doens't recognizes Memory cards.

**Steps to reproduce**
Try to save the game (after a mission or even try to save the game in the options in the first screen.

**Hardware/software**
[If Android, which phone and Android version]
i7-4790, GTX 1070, Windows 10 x64

**Emulator version**
0.1-3204-geabda297

**Comment by foxsevent** [comment]
Two things, make sure that your memory cards are configured.
Secondly make sure that overclocking in emulation settings is set to default.
Overclocking tends to break memory card reading when set above certain %

**Comment by stenzek** [comment]
Indeed, no issue here. Could very well be enhancement related.

If it's specific to some part of the game, if you provide details I can investigate.

**Comment by Shideravan** [comment]
Hmm, even deselecting everything, it seems that savestate was keeping old config CPU clock. Alright, it was caused by overclocking.
