### ISSUE TITLE
Add a gui to the nogui

### ISSUE THREAD

**Issue by ImSpecial** [stenzek/duckstation#1636]
No I'm not crazy, hear me out.

As a desktop user with a pretty big monitor, I really dislike the full-screen only (it's too big), and options buried under options, under options. Qt doesn't have the same elegance either, it's just a big ass white box for configuring...

Can nogui (quack) be made a sort of hybrid nogui (quack) like PPSSPP? 

https://i.imgur.com/EKP2jgh.png

https://i.imgur.com/Hby1eQ1.png

I'm not saying you should copy PPSSPP's design completely (yes I am actually), because that would be plagiarism, and that's bad, but please copy at least the being able to "window" the damn thing, and have the old-school menubar for mouse click click (quack) users, just change it a little so Hrydgard doesn't know.

Thanks.

**Comment by stenzek** [comment]
Most options are available in a menu bar in the full screen UI - enable the debug menu.

**Comment by ImSpecial** [comment]
I did not know about "debug mode", everything is pretty good now, but it doesn't remember if "full-screen" is checked or not, it seems to reset on every launch, can that be remembered, along with window size/positioning, etc. Also having that Alt+Enter shortcut to toggle is handy to have too, sorry for asking so much of you. (quack)
