### ISSUE TITLE
PBP Rom Format

### ISSUE THREAD

**Issue by dhanial** [stenzek/duckstation#1638]
> (Request)

Please add .pbp rom format compatibility

**Comment by stenzek** [comment]
Please use the search feature before creating new issues.

Duplicate of https://github.com/stenzek/duckstation/issues/17

I'd recommend migrating to CHD anyway. It compresses better, and is lossless unlike PBP.

**Comment by dhanial** [comment]
# actually i've compressed all my rom to pbp using fpse, but i wish you will add this ability
