### ISSUE TITLE
Cybersled (Japan) nothing but a black screen 

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#164]
Audio is playing but I can't interact with the game at all.

![Capture](https://user-images.githubusercontent.com/31968468/77564995-b16f1700-6f17-11ea-932c-52992e7b6f7e.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/77565019-b7fd8e80-6f17-11ea-98fa-0cc9863fc0f5.PNG)

**Comment by kurayami6** [comment]
Exactly the same as of the latest version. Music is playing but the game is frozen on a black screen. 

![2020-06-03_23-08-01](https://user-images.githubusercontent.com/31968468/83640371-62b4bc00-a5ef-11ea-83d0-7c9fbc75af06.png)

**Comment by Shideravan** [comment]
I don't have the japanese version for testing purposes, but in USA version is everything ok.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/02948f988d41ce99d1aae44e122b4ad8861efb79
