### ISSUE TITLE
[Android] Individual aspect ratio setting is ignored

### ISSUE THREAD

**Issue by 6lackmag3** [stenzek/duckstation#1640]
**Game details**
All games

**Description of the issue / bug**
Aspect ratio overrides not being saved in game properties/gamesettings.ini

**Steps to reproduce**
Run DuckStation, change aspect ratio in individual game properties, start the game - it will reset to global setting.

**Emulator version**
0.1-3187

**Comment by stenzek** [comment]
Couldn't reproduce after the other per-game setting fixes.

**Comment by 6lackmag3** [comment]
@stenzek regarding this issue, 'Game Native' aspect ratio not being saved in individual game settings, falling back to global.
