### ISSUE TITLE
[Feature Request] On-the-fly output resolution switching

### ISSUE THREAD

**Issue by DukeSkinny** [stenzek/duckstation#1642]
**Is your feature request related to a problem? Please describe.**
In the process of migrating my PSX emulation from Retroarch to Duckstation, I came upon what I imagined would be my no. 1 stumbling block: resolution switching & super resolutions. Currently, it seems Duckstation can only operate with 1 set resolution, and running super resolutions such as 1920x240 results in a very narrow image.

**Describe the solution you'd like**
Allow the output resolution to switch on-the-fly based on the native resolution of the game, ignoring higher internal resolutions in favor of a downscaled output. Good options to include might be:

- Integers of the horizontal resolution (1x = 320x240 -> 2x = 640x240 [...] -> 6x = 1920x240 etc.) to allow user choice of super resolutions
- Doubling of refresh rate (to accommodate 31khz monitors). This would cause a 320x240@60 Hz resolution game to output at 320x240@120 Hz
- Allow syncing at half the refresh rate to get rid of duplicate frames for 120 Hz

**Describe alternatives you've considered**
I have toyed around with the aspect ratio settings, integer scaling etc.. All options seem to produce the exact same result. Obviously, even solving that I still wouldn't be able to get the 320x240-to-640x480 switching to work.

Thank you for considering my request!

**Comment by Redemp** [comment]
What we want is switchres implementation. Same as GroovyMame. Using native res and super resolutions.
https://github.com/stenzek/duckstation/discussions/1613

**Comment by stenzek** [comment]
It's quite difficult for me to implement things like this, because I don't have any displays capable of these sorts of resolutions.

**Comment by CdrikPxL** [comment]
> It's quite difficult for me to implement things like this, because I don't have any displays capable of these sorts of resolutions.

We can help you, we are much users who use CRT Emudriver 2.0 on a 15khz screen with super resolution and native. We could be your tester when you have need 😉

**Comment by stenzek** [comment]
Remote testing for nontrivial features like this is insufficient.
