### ISSUE TITLE
DuckStation immediately hard-crashes on startup in the event that no audio playback device is detected as enabled in Windows at all

### ISSUE THREAD

**Issue by Akira13641** [stenzek/duckstation#1643]
I use Sony WH-1000XM3 headphones (which can either work by being plugged in with a regular 3.5mm audio cable, or wirelessly via bluetooth) in the bluetooth configuration. When they're not actively turned on, Windows considers there to be no available playback device (and so shows the little red "X" over the volume taskbar icon and such).

For whatever reason, DuckStation appears to expect there to *always* be an available audio device of some kind, as simply attempting to launch it with my headphones turned on and off consistently reproduces this crash when they're off.

**Comment by stenzek** [comment]
Can you specify whether you're using the preview or latest builds, and zip/upload the crash.dmp file which is created.

**Comment by Akira13641** [comment]
I'm using the "Latest Development Build" available in the releases section of this repository. As far as a `crash.dmp` file, whereabouts does DuckStation save that if it generates it?

To be clear, also, when I say "Hard crash" I mean like it pops up the generic "XYZ Application has stopped working" message box you'd get with any number of applications of Windows.

**Comment by stenzek** [comment]
dump file should be in the user directory (Documents\DuckStation, or the exe directory if using portable mode)

**Comment by Sekai9** [comment]
Well, for some reason DS is not generating the .dmp file for this specific crash.
But there's a .dmp in AppData\Local\CrashDumps... 
I'll DM you the .dmp file since it's almost 62MB...

0.1-3250-g9d05aa21

**Comment by westneat** [comment]
I also had this issue...took me awhile to realize that it was the disabled audio that was causing the problem. I did not get the "Application has stopped working" it just flashed open for a brief second and then crashed back to desktop.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/357235404ac616b893080b8eba77064dc7bca7d7
