### ISSUE TITLE
Analogue controller doesn't work in Cleopatra's fortune (Europe) 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#165]
Switching to digital works. 

![SLES-03935_2020-03-26_04-37-53](https://user-images.githubusercontent.com/31968468/77568595-f47fb900-6f1c-11ea-943f-b23ef74cf8f4.png)

Also I'm not sure if this is a problem or not.

![Capture](https://user-images.githubusercontent.com/31968468/77568648-10835a80-6f1d-11ea-9e8f-de72d8b19818.PNG)

**Comment by stenzek** [comment]
Please re-test on latest build.

**Comment by kurayami6** [comment]
Fixed
