### ISSUE TITLE
Can speed up the game, but does not affect the game music?

### ISSUE THREAD

**Issue by kongmao45678** [stenzek/duckstation#1652]
Hope to add this feature, so that you can play games quickly, and at the same time you can enjoy the normal music of the game, thanks!

**Comment by stenzek** [comment]
Not possible - sound runs in sync with the game itself. It's not like PCs where it's asynchronous.

Running the SPU slower when fast forwarding would just break games.

**Comment by kongmao45678** [comment]
Because I have implemented it in yabasanshiro, I made this suggestion. In yabasanshiro, the sound can be synchronized with real-time or with CPU.

**Comment by stenzek** [comment]
PS1 games tend to allocate voices/channels based on the current SPU state. i.e. when they want to play a new sound, they iterate through the voice list, looking for one with a zero volume.

So, if you ran the game quicker than the SPU, it would very quickly fill up all the voices, and at best you'd be missing sound effects, at worst the game would crash as some use the volumes as a way of timing game events.

Then you have the issue of games which use SPU RAM IRQs for things like lip syncing, text sync for dialogue playback, etc, and these would also break.

So while it might work for some games which use fixed channels for sound, most don't.
