### ISSUE TITLE
Chinese Language update

### ISSUE THREAD

**Issue by xujibbs** [stenzek/duckstation#1653]
It seemed current duckstation-qt_zh-cn.qm missed some translation. I find the code and wish somebody add in the translation.
the code is
msgctxt "QPlatformTheme|"
msgid "&No"
msgstr "否(&N)"

msgctxt "QPlatformTheme|"
msgid "&Yes"
msgstr "是(&Y)"

msgctxt "QPlatformTheme|"
msgid "OK"
msgstr "确定"

msgctxt "QPlatformTheme|"
msgid "Cancel"
msgstr "取消"

By the way, I also find an information from Duckstation i.e. "System failed to boot. The log may contain more information" and I failed to translate it because of the source code missing. I was appreciated if you add the source code accordingly.

**Comment by stenzek** [comment]
Known issue - we need to load the base Qt translations as well as the DuckStation translations. Alternatively you can add these in the ts file.
