### ISSUE TITLE
Graphical garbage in Buster Bros. Collection (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#166]
![Capture](https://user-images.githubusercontent.com/31968468/77575374-8c82a000-6f27-11ea-9a0d-52e4f63ec4c6.PNG)

**Comment by stenzek** [comment]
That "garbage" you're seeing is typically hidden by TVs in the overscan area. If you disabled overscan on a modern TV, you'd likely see it on a console too.

That said, I've rewritten the overscan handling, which fixes this game if you select the "crop overscan area" option. Will push it to master soon after some additional testing with PAL games.

**Comment by stenzek** [comment]
"Fixed" with the overscan changes, but the left/right side are obscured. It's likely this game will need a per-game fudge factor discussed in #33.
