### ISSUE TITLE
Fullscreen setting not being remembered in nogui/dev mode.

### ISSUE THREAD

**Issue by ImSpecial** [stenzek/duckstation#1660]
A quicky.

With the latest Development Build (duckstation-windows-x64-release.zip)...
and using "duckstation-nogui-x64" launcher...
with having dev mode togged, unchecking fullscreen, then close "duckstation-nogui-x64"...
restarting "duckstation-nogui-x64" and it's fullscreen again...!

Shouldn't the fullscreen setting be remembered? Bug or by Design?

**Comment by stenzek** [comment]
The debug menu is actually a fullscreen toggle, not a setting. I've removed the checkbox to make that more clearer.

If you want to start in fullscreen, the "Start Fullscreen" setting in General Settings will do the trick.
