### ISSUE TITLE
[Feature Request] Change "Open Quick Menu" Hotkey to "Toggle Quick Menu"

### ISSUE THREAD

**Issue by westneat** [stenzek/duckstation#1667]
**Is your feature request related to a problem? Please describe.**
When you use a button press on the controller to open the menu, you can't use the same button press to close it. And in fact, if you attempt to do so, the emulator will hang / crash.

**Describe the solution you'd like**
Instead of crashing on repeated presses of the "Open Quick Menu" hotkey, the menu should just toggle open/closed.

**Describe alternatives you've considered**
It's still possible to close the menu by navigating to the close button, but it is slower.

Thanks for consideration!

**Comment by stenzek** [comment]
Doesn't really fit into the current design - hotkeys don't activate when there's a dialog/menu open. If you bind the quick menu to escape, it will effectively toggoe.
