### ISSUE TITLE
[Feature Request] Remember last disc when using .m3u playlists

### ISSUE THREAD

**Issue by westneat** [stenzek/duckstation#1668]
**Is your feature request related to a problem? Please describe.**
When you load a .m3u playlist, the emulator always boots the first disc in the list. If you are playing through a multi-disc game, you will need to switch discs after boot each time you load the playlist.

**Describe the solution you'd like**
The emulator could create a small file to remember which disc in the playlist was last played. Could be as simple as a creating file containing the game title/ID that contains a number, e.g. 3 for disc 3. When the playlist is loaded, that disc will be loaded.

I imagine most people playing multi-disc games are starting with the first disc and playing through in order. This would prevent having to swap discs each time you play once you get to disc 2. And if for some reason someone needs to start over they can always manually change back to disc 1 or whatever. 

**Describe alternatives you've considered**
Alternatives involve using frontends to get around the disc swap.

**Comment by stenzek** [comment]
As of https://github.com/stenzek/duckstation/commit/50d712c3fe3aec2ec90dc6c2d3f224909712a3a9, multi-disc games when using m3u/pbp will use the first disc as a key for user settings and save states. So this should work fine now.

Note you'll need to start the game (right click -> default boot), not load state the first time, so it saves the state using the m3u as the image.
