### ISSUE TITLE
Driver (Spain) hangs when passing the intro with vulkan

### ISSUE THREAD

**Issue by fox140cv** [stenzek/duckstation#1670]
The game crashes after the intro just after finishing the loading screen that leads to the main menu jumping an error. I have investigated and the error occurs when increasing the resolution scale, it only occurs with vulkan, with d3d11 it does not occur. I made a backup of my original copy again to rule out that the image had errors.

SLES_019.78 Spain 
crc: 9EA08ED4

![Captura de pantalla (22)](https://user-images.githubusercontent.com/79443698/108682757-fff2b000-74f0-11eb-8014-7d380c28ed9c.png)

**Comment by stenzek** [comment]
Are you using any enhancements or downsampling? I can't seem to reproduce this, nor any Vulkan validation layer errors.

**Comment by fox140cv** [comment]
I just downloaded the latest version available and this error has been solved, it happens with the stable version. Thanks for your attention, do I close the issue?

**Comment by stenzek** [comment]
Sure. I'll be syncing the development/stable build soon anyway.
