### ISSUE TITLE
Allow binding buttons to mouse wheel

### ISSUE THREAD

**Issue by TheKins** [stenzek/duckstation#1671]
**Is your feature request related to a problem? Please describe.**
It does not currently appear possible to bind buttons to moving the mousewheel up and down. This prevents, for example, binding L1 and L2 to the mousewheel for switching weapons in Quake 2.

**Describe the solution you'd like**
The ability to bind buttons to the mousewheel would be appreciated, if possible. It may potentially be worth restricting this to when one of the controller slots has a mouse or lightgun inserted.

**Describe alternatives you've considered**
My current workaround is to bind the keys to other buttons on my mouse, but this isn't hugely comfortable.

**Additional context**
The [default mouse controls in Quake 2](https://i.imgur.com/LUZPiLR.png), as illustrated by the game.

**Comment by stenzek** [comment]
This is possible post UI revamp.
