### ISSUE TITLE
[Request] FMV videos less pixelated in core libretro

### ISSUE THREAD

**Issue by fox140cv** [stenzek/duckstation#1672]
Is it possible to make FMV videos look less pixelated by increasing the internal scaling resolution? As seen in the duckstation emulator or when the resolution is left at 1x in the retroarch menu.

Scale 1x tekken 3
![Captura de pantalla (25)](https://user-images.githubusercontent.com/79443698/108693003-9dec7780-74fd-11eb-968b-5f1452e25147.png)
Scale 4x tekken 3

![Captura de pantalla (26)](https://user-images.githubusercontent.com/79443698/108693014-a04ed180-74fd-11eb-85ea-a48503af779e.png)

**Comment by stenzek** [comment]
DuckStation has nothing to do with libretro/retroarch, please ask on their fork/issue tracker instead. https://github.com/libretro/duckstation/
