### ISSUE TITLE
Infestation (Europe) loses a lot of time during the opening 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#168]
During and after the first loading screen. Should the emulator be losing this much time? 

![Capture2](https://user-images.githubusercontent.com/31968468/77588599-48e76080-6f3e-11ea-8fc5-55e72f6880a5.PNG)

**Comment by stenzek** [comment]
Please retest on the latest build. I was unable to reproduce any slowdown, FMVs ran at ~600fps, loading at ~700fps, main menu at ~800fps, ~550fps ingame.

**Comment by kurayami6** [comment]
Must have been fixed at some point.
