### ISSUE TITLE
Selecting guncon or playstation mouse crashes the emulator in non qt mode.

### ISSUE THREAD

**Issue by Darkwolf1515** [stenzek/duckstation#1685]
**Description of the issue / bug**
Enabling one of these two inputs, in and out of a game, crashes duckstation in non qt mode, works just fine in qt however.

**Steps to reproduce**
Go to your controller settings in non qt mode, select one of those options, watch it crash.

**Hardware/software**
Intel i7 6600k, GTX 1080 8gb, Windows 10
GPU Renderer - D3D11
**Emulator version**
3250

**Additional context**
[Add any other context about the problem here]

**Comment by stenzek** [comment]
I believe this was fixed by https://github.com/stenzek/duckstation/commit/3ca3a78b58d09a828ee6387934e9dc106671e6c1
