### ISSUE TITLE
Chrono Cross SLUS-01080 CD 2

### ISSUE THREAD

**Issue by kanelakis** [stenzek/duckstation#1689]
**Game details**
SLUS-01080 Chrono Cross (USA) Cd 2

**Description of the issue / bug**
<entry code="SLUS-01080" title="Chrono Cross (USA) (Disc 2)" region="NTSC-U" compatibility="1">
    <compatibility>Doesn't Boot</compatibility>

**Enhancements information**
![2021-02-25](https://user-images.githubusercontent.com/26459477/109227198-3b76ce00-77c0-11eb-9f31-b67770b1cec9.png)

**Hardware/software**
Windows 10 64 Bit
Intel core i9 9900 3.40 ghz
Ram: 32 Gb
Video Card: Nvidia GeForce GTX 1080 8 Gb
GPU:Hardware: D3D11

**Emulator version**
DuckStation 0.1-3314-g52c842e3 (master)

**Additional context**
I hope I did everything right, Chrono Cross CD 2 practically does not start.

**Comment by andercard0** [comment]
Hm.. at the end of disc 1 when game prompt you to insert Disc 2, you do: System > Change Disc then Duckstation gives you option to: load from file or from list; 

What happen when you do it ?

**Comment by foxsevent** [comment]
Practically verify if your CD 2 is even correct, not corrupted and such, compare hashes.
http://redump.org/disc/21/
Both discs boot fine here.

**Comment by kanelakis** [comment]
> Hm.. at the end of disc 1 when game prompt you to insert Disc 2, you do: System > Change Disc then Duckstation gives you option to: load from file or from list;
> 
> What happen when you do it ?

I did the test by starting only disc 2, as I did with the other games, and those start, and when I play a new game it tells me to load disc 1.
Instead Chrono Cross gets stuck on the white screen of Playstation and does not go on.

**Comment by kanelakis** [comment]
> Practically verify if your CD 2 is even correct, not corrupted and such, compare hashes.
> http://redump.org/disc/21/
> Both discs boot fine here.

How do I test my game ISO?

**Comment by foxsevent** [comment]
> > Practically verify if your CD 2 is even correct, not corrupted and such, compare hashes.
> > http://redump.org/disc/21/
> > Both discs boot fine here.
> 
> How do I test my game ISO?

Right click on game (disc 2) Properties - Compute hashes and compare that to the one in the link labelled MD5.

**Comment by andercard0** [comment]
> > Hm.. at the end of disc 1 when game prompt you to insert Disc 2, you do: System > Change Disc then Duckstation gives you option to: load from file or from list;
> > What happen when you do it ?
> 
> I did the test by starting only disc 2
This is totally invalid and does not make any sense you should not to START playing game from disc 2. for god sake play first CD THEN after play it if game is really not loading you raise a proper issue.

**Comment by kanelakis** [comment]
> > > Practically verify if your CD 2 is even correct, not corrupted and such, compare hashes.
> > > http://redump.org/disc/21/
> > > Both discs boot fine here.
> > 
> > 
> > How do I test my game ISO?
> 
> Right click on game (disc 2) Properties - Compute hashes and compare that to the one in the link labelled MD5.

So I need to see the Hash number and compare it with MD5?

**Comment by foxsevent** [comment]
> > > > Practically verify if your CD 2 is even correct, not corrupted and such, compare hashes.
> > > > http://redump.org/disc/21/
> > > > Both discs boot fine here.
> > > 
> > > 
> > > How do I test my game ISO?
> > 
> > 
> > Right click on game (disc 2) Properties - Compute hashes and compare that to the one in the link labelled MD5.
> 
> So I need to see the Hash number and compare it with MD5?

Yes, like so.
![Przechwytywanie](https://user-images.githubusercontent.com/64225743/109229071-19327f80-77c3-11eb-861a-0c6e1498216b.PNG)
![Przechwytywanie1](https://user-images.githubusercontent.com/64225743/109229099-20598d80-77c3-11eb-92ab-dc2079524cff.PNG)

**Comment by kanelakis** [comment]
![2021-02-25 (1)](https://user-images.githubusercontent.com/26459477/109229324-6ca4cd80-77c3-11eb-9b52-d5cd2303992a.png)
Yes is different,i do i soved?

**Comment by foxsevent** [comment]
> ![2021-02-25 (1)](https://user-images.githubusercontent.com/26459477/109229324-6ca4cd80-77c3-11eb-9b52-d5cd2303992a.png)
> Yes is different,i do i soved?

Then your disc 2 is obviously broken ergo why it doesn't boot, make or get a new copy, don't ask from where we can;t help with that.

**Comment by kanelakis** [comment]
> > ![2021-02-25 (1)](https://user-images.githubusercontent.com/26459477/109229324-6ca4cd80-77c3-11eb-9b52-d5cd2303992a.png)
> > Yes is different,i do i soved?
> 
> Then your disc 2 is obviously broken ergo why it doesn't boot, make or get a new copy, don't ask from where we can;t help with that.

Since I made it years ago the ISO could be damaged over time, I will try to make a new one and I will do the test.

**Comment by foxsevent** [comment]
One thing I noticed is that your Chrono Cross folder has "ITA" in it, were your discs patched with a translation perhaps, if so then the hash won't match a clean copy.
And since this been asked does disc 1 boot?

**Comment by kanelakis** [comment]
> One thing I noticed is that your Chrono Cross folder has "ITA" in it, were your discs patched with a translation perhaps, if so then the hash won't match a clean copy.
> And since this been asked does disc 1 boot?

Yes the disc 1 boot.

**Comment by stenzek** [comment]
Sounds like a broken translation then, not a valid issue.
