### ISSUE TITLE
Graphical glitches in BallBlazer Champions (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#169]
Using D3D11 the ball on the loading screen is broken and causes the game to lag significantly. 

![SLUS-00068_2020-03-26_10-47-12](https://user-images.githubusercontent.com/31968468/77596387-f57e0e00-6f4f-11ea-8faa-a63b442b36b3.png)

![Capture](https://user-images.githubusercontent.com/31968468/77596440-1d6d7180-6f50-11ea-8b51-1730dc4f8beb.PNG)

Here's what it's supposed to look like.

![SLUS-00068_2020-03-26_10-38-21](https://user-images.githubusercontent.com/31968468/77596492-4261e480-6f50-11ea-9eff-4805d4005013.png)

The "Two player freeplay" text is broken in all renderers. 

![SLUS-00068_2020-03-26_10-38-08](https://user-images.githubusercontent.com/31968468/77596545-632a3a00-6f50-11ea-984c-42f0be76a180.png)

Here's what it looks like in Beetle PSX.

![BallBlazer Champions (USA)-200326-104012](https://user-images.githubusercontent.com/31968468/77596574-7fc67200-6f50-11ea-9a8f-6e2a6d202aa3.png)

**Comment by stenzek** [comment]
Unable to reproduce.

**Comment by kurayami6** [comment]
Must have been fixed at some point.
