### ISSUE TITLE
Cheat Fly out menu

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#1696]
As requested by a user on Discord

I'm always frustrated when need to choose a cheat and the window closes as showed down below:

![image](https://user-images.githubusercontent.com/43047877/109370386-d209c480-787e-11eb-84c7-a320d71bf299.png)

**Describe the solution you'd like**
Would be immensely better if the window is not retracted for each click on the cheat manager 

**Describe alternatives you've considered**
I guess he meant to make that fly out menu more time visible instead of each click close. 

So, [ ] Click > [ ] Click > loss focus > Close

**Additional context**
I told him to use the manager but looks like non-embedded cheats aren't showed there hence his request.

**Comment by stenzek** [comment]
Not really possible - it's a widget/OS menu, so activating an item will close it, that's how they work.

If you want a persistent menu, use the cheat list in Fullscreen UI mode (open the quick menu).

**Comment by andercard0** [comment]
> Not really possible - it's a widget/OS menu, so activating an item will close it, that's how they work.
> 
> If you want a persistent menu, use the cheat list in Fullscreen UI mode (open the quick menu).

No problem, will let him know about it thank you!
