### ISSUE TITLE
[Request] support for the PBP format/filetype

### ISSUE THREAD

**Issue by genova447** [stenzek/duckstation#17]
Not sure how easy/feasible it is to support that format.
But thought that, if it could be, it could be neat : o

In case it's not a format you have heard of before; you can use it to both compress and batch together multi-disc games into one (which also requires an emulator can 'tell' that it contains different discs, and can somehow switch between them).

Myself I don't know a great deal about the details, but I read that it isn't completely lossless - that the conversion to pbp changes the original data a bit... so I understand that like mednafen (not Beetle PSX in Retroarch), some people might not wish to support this format.

I was trying to look for some sort of documentation to help out a bit, but having a hard time... but maybe there is something useful to find here: https://github.com/libretro/beetle-psx-libretro/issues/36.

(Sorry not used to posting on GitHub, so my approach may be a bit odd ^^' )

**Comment by stenzek** [comment]
How common is the format? I was under the impression most people used bin/cue or CHD nowadays.

If it's widespread I'm happy to look into it, but otherwise there's more important issues for now. But I have no objections to supporting more formats, that's why the cd loader is modular, so hopefully can get around to it at some point :)

**Comment by tcamargo** [comment]
Format is widespread because it is the format used by PSP POPS (PS One emulation). Compression/format is lossless. So, you can't recreate the original ISO from a PBP file.

**Comment by tony971** [comment]
The compression isn't as good as CHD, but the multi-disc files are a neat feature. Of course, this is easily nullified by adding m3u support for your existing formats.

**Comment by MartyShepard** [comment]
That would be great if there was PBP support. At home I use the duck station and on the go on my PSP the PS1 PBP image/s. ePSXE supports the format, I would much rather only use Duckstation.

**Comment by 1900forever** [comment]
It's very common format when using emulators like epsxe to play PS games, and it's also the standard format for running PS games on PSP/PSV. It would be greatly appreciated if you can add this feature 👍

**Comment by mailsonm** [comment]
I would love to have support for this tbm (pbp) format, I have more than 500 roms in this format and I cannot test this emulator, but even not supporting the pbp format, it is the best ps1 emulator I've ever seen! thanks Stenzek for your work!
(the pbp format takes up less space on the hd so i usually use them more).

**Comment by iball** [comment]
I'd like to see PBP support as well.

**Comment by liberodark** [comment]
Really pbp support would be great.

**Comment by irnutsmurt** [comment]
just wanted to be another person to add a request for PBP support. Thanks

**Comment by mikael-bergstrom-ntisthlm** [comment]
PBP not only allowed a single file to include all disc images for a game, it can also include additional data like an icon, background+music, game title/region.

It was the native, official format for PS1 games emulated on the PSP, which is part of the reason why it's so widespread…

**Comment by krank** [comment]
PBP not only allowed a single file to include all disc images for a game, it can also include additional data like an icon, background+music, game title/region.

It was the native, official format for PS1 games emulated on the PSP, which is part of the reason why it's so widespread…

**Comment by stenzek** [comment]
One of the contributors is working on pbp support, but it's not super straightforward (things are undocumented and require reversing), so it will take some time.

**Comment by irnutsmurt** [comment]
If they haven't already, it might be worth looking at source code for another emulator like psppbb to get a hint how they do it.

**Comment by NeverSm1le** [comment]
> If they haven't already, it might be worth looking at source code for another emulator like psppbb to get a hint how they do it.

PPSSPP cannot play PS1 games, so there's no code to look at.

**Comment by krank** [comment]
I'm guessing whoever's doing this already know, but both the Beetle and PCSX Reloaded libretro cores support pbp. The PCSXR standalone does as well (source is available).

**Comment by ggrtk** [comment]
They do allow loading EBOOT.PBPs, but the support in those other programs is incomplete. I think we'd rather do it thoroughly and avoid adding in an unfinished feature.

**Comment by tlayne** [comment]
Throwing my hat in the ring. Very much looking forward to this if it is a possibility.

**Comment by Disfunktional** [comment]
Just dropping by to support this request... Great to hear its being looked at! 👍

**Comment by RupertAvery** [comment]
So is `lba_in_index` in `ReadSectorFromIndex(void* buffer, const Index& index, LBA lba_in_index)` basically the sector number? Since PBP compression is done in blocks of 16 sectors, could I just `lba_in_index / 16` to get the block number to decompress?

**Comment by ggrtk** [comment]
I'm currently working on the PBP support independently -- feel free to drop by Discord and discuss with us if you'd like to collaborate.

**Comment by MartyShepard** [comment]
> I'm currently working on the PBP support independently -- feel free to drop by Discord and discuss with us if you'd like to collaborate.

Great :)

**Comment by LondoJI** [comment]
Thanks!
I was used to run my images with Retroarch with PBP converted from ISOs, but since I checked all new features Duckstation has, I have no choice but to jump to Duckstation, however, my collection is quite long and all images were already changed to PBP (which is gives me 40% more disk space than if I let ISOS as they were). Would be great if Duckstation had PBP support, so I wouldn't need to change back to ISO files.

**Comment by stenzek** [comment]
> Thanks!
> I was used to run my images with Retroarch with PBP converted from ISOs, but since I checked all new features Duckstation has, I have no choice but to jump to Duckstation, however, my collection is quite long and all images were already changed to PBP (which is gives me 40% more disk space than if I let ISOS as they were). Would be great if Duckstation had PBP support, so I wouldn't need to change back to ISO files.

CHD will likely compress better than PBP.

**Comment by RinMaru** [comment]
> CHD will likely compress better than PBP.

it does. Only official Sony PBPs sometimes give better compression

**Comment by LondoJI** [comment]
However, I think is still better for Duckstation to support PBP as well. 

Anyway, I already changed all my ISOs to PBP, since disks were old. 

If you have any method to convert PBP to CHD, then I'm all ears (eyes).

**Comment by Nucleoprotein** [comment]
If there will be any in the feature all you dumps are permanently damaged by conversion to PBP because all tools i know, like PSX2PSP (which is most common i think) used for PBP compression cannot save all data ie. they are **not lossless** and you already lost some data from original BIN/CUE... so you have now only bad dumps 😢

**Comment by LondoJI** [comment]
Damn... I'll have to start from zero...

**Comment by RinMaru** [comment]
> Damn... I'll have to start from zero...

ISO to CHD is pretty quick more  so then to PBP

**Comment by vus7294** [comment]
So is This Project Cancelled?

**Comment by CPS2Evolved** [comment]
There seems to be a misconception about PBP being lossy.

According to Mick2k:
_**As far as I know only the original pbp files that you can download from PSN are lossy compression.
The reverse engineered pbp format that we can use is a normal lossless zlib compression.**_

Source:
https://retropie.org.uk/forum/topic/18784/bounty-chd-support-for-pcsx-rearmed/5?_=1612020307993&lang=en-US

**Comment by Darkwolf1515** [comment]
Yeah, all my files are in this format, the multidisc support is too good to give up.

**Comment by chrisballensky** [comment]
Is this still currently being worked on? I personally have the full US library in .pbp format, and it would be amazing to see support.

**Comment by Darkwolf1515** [comment]
Whats with all the hatred for those wanting this as an optional option?

**Comment by 6lackmag3** [comment]
Because there're lots of inaccurate buggy pbps with trimmed down audio/fmvs which may cause glitches and freezes. But instead of getting full accurate copies of games people will come and blame emulator for their faults. Don't think Stenzek want to deal with it.

**Comment by ImSpecial** [comment]
It probably has something to do with the whiny (even demanding) nature of the people who keep asking for it. We get it, we see the [Request] for it, keep bumping this with your passive-aggressive/begging/whatever won't just make a dev care about it more because...

It takes (free) time to learn and do a things, and the few developers here who maybe could learn and implement this PBP thing have better things they want to do with their (free) time.

So unless you do the Pull Request yourself, then don't expect this to be made a top priority, and even if you do, there's no guarantee because PBP's are flawed anyway.

**Comment by irnutsmurt** [comment]
Because I believe strongly in this project, and I'd like the devs to feel appreciated, can I donate? I know a lot of free time has probably gone into researching this, and even if it never gets implemented I'd like to show my appreciation for the hard work and effort on the project as a whole.

**Comment by stenzek** [comment]
> Whats with all the hatred for those wanting this as an optional option?

Drop the attitude. There's no hatred here, but the format is inferior and there's potential legal risks to including it (crypto libraries).

> Because there're lots of inaccurate buggy pbps with trimmed down audio/fmvs which may cause glitches and freezes. But instead of getting full accurate copies of games people will come and blame emulator for their faults. Don't think Stenzek wants to deal with it.

Android users are going to be demanding arseholes regardless.

> Because I believe strongly in this project, and I'd like the devs to feel appreciated, can I donate? I know a lot of free time has probably gone into researching this, and even if it never gets implemented I'd like to show my appreciation for the hard work and effort on the project as a whole.

No, I don't want to involve money in this project - both because it adds risk as it's an emulator based on Sony's hardware, as well as because people expect their demands to be met if they pay.

**Comment by vus7294** [comment]
I think chd is much better on cdda audio, but regular iso(cdxa and other), chd and pbp has pretty same size compression.
And psx2psp has only zipping whole iso, Unlike psn pbp, same as bin/cue.
But if you guys have hatred to pbp and cancel this project, i'd better to stay in beetle psx.

**Comment by stenzek** [comment]
If I hated the format, I would've closed the issue long ago.

What is starting to annoy me is people (especially android users) nagging us to add support. Nagging just makes us lose motivation, **considering we are basically donating our free time to working on this for you**.

> But if you guys have hatred to pbp and cancel this project, i'd better to stay in beetle psx.

Then please, keep using beetle (which is basically dead, nobody works on it anymore afaik). It's not going to bother me if rude people don't use my code.

**Comment by Darkwolf1515** [comment]
> > Whats with all the hatred for those wanting this as an optional option?
> 
> Drop the attitude. There's no hatred here, but the format is inferior and there's potential legal risks to including it (crypto libraries).

Sorry, didn’t mean to come off as having one, just was wondering why it seemed most disliked the idea. I didn’t have any intentions to nag for it, it’s an open source free project, I’m not rushing for what is free, timed donated work. Maybe I’ll swap my format of its really that inaccurate. Sorry again!

**Comment by irnutsmurt** [comment]
> No, I don't want to involve money in this project - both because it adds risk as it's an emulator based on Sony's hardware, as well as because people expect their demands to be met if they pay.

That's fair. I'm going to switch to CHD based on information I didn't have before. Thank you for working on this modern emulator. Your hard work is appreciated, and I'm sorry if I or others have came off entitled about this feature request. I can imagine how frustrating it must feel.

**Comment by Darkwolf1515** [comment]
> What is starting to annoy me is people (especially android users) nagging us to add support. Nagging just makes us lose motivation, **considering we are basically donating our free time to working on this for you**.

if anyone can explain, what’s the issue with android? (Not a user) I see a lot of distaste for them across many emulators, is it like, they download the emulator, get their roms from a place like “superepiccoolroms.net.gov” and then expect perfect 4k on their 10 year old generic phone? Or something else?

**Comment by stenzek** [comment]
> > What is starting to annoy me is people (especially android users) nagging us to add support. Nagging just makes us lose motivation, **considering we are basically donating our free time to working on this for you**.
> 
> if anyone can explain, what’s the issue with android? (Not a user) I see a lot of distaste for them across many emulators, is it like, they download the emulator, get their roms from a place like “superepiccoolroms.net.gov” and then expect perfect 4k on their 10 year old generic phone? Or something else?

Oh, but they do... :) read the reviews for any free android app, including this one, heh.

**Comment by foxsevent** [comment]
> > > What is starting to annoy me is people (especially android users) nagging us to add support. Nagging just makes us lose motivation, **considering we are basically donating our free time to working on this for you**.
> > 
> > 
> > if anyone can explain, what’s the issue with android? (Not a user) I see a lot of distaste for them across many emulators, is it like, they download the emulator, get their roms from a place like “superepiccoolroms.net.gov” and then expect perfect 4k on their 10 year old generic phone? Or something else?
> 
> Oh, but they do... :) read the reviews for any free android app, including this one, heh.

Are you sure you're not exaggerating a little bit?
![Screenshot_2021-02-20-19-24-14-973_com android vending](https://user-images.githubusercontent.com/64225743/108604982-607ad380-73b1-11eb-961d-0432d522b32e.jpg)
![Screenshot_2021-02-20-19-24-12-723_com android vending](https://user-images.githubusercontent.com/64225743/108604989-67094b00-73b1-11eb-9e92-4fee7a53abc7.jpg)
Unless I'm missing something, plus lot's of people are simply simple not malicious just wanting to play childhood games but have no experience with Android other than twitter or emulation, like my mom who wants to play amiga games on her phone.

**Comment by Nucleoprotein** [comment]
You only see fracture of reviews because Google Play store is stupid and will show only your language, check like this:
https://play.google.com/store/apps/details?id=com.github.stenzek.duckstation&hl=en&gl=US&showAllReviews=true

**Comment by foxsevent** [comment]
> You only see fracture of reviews because Google Play store is stupid and will show only your language, check like this:
> https://play.google.com/store/apps/details?id=com.github.stenzek.duckstation&hl=en&gl=US&showAllReviews=true

Ah thanks for clarification, I retract my previous post.

**Comment by Darkwolf1515** [comment]
> > You only see fracture of reviews because Google Play store is stupid and will show only your language, check like this:
> > https://play.google.com/store/apps/details?id=com.github.stenzek.duckstation&hl=en&gl=US&showAllReviews=true
> 
> Ah thanks for clarification, I retract my previous post.

“It's amazing that a developer can make an app work on Windows but on Android it's complete garbage. What's the point of having a PlayStation emulator if you can't even load iso. And please don't act like am a idiot”

I don’t think I’ve ever wanted to hit someone from the internet any more than him.

**Comment by foxsevent** [comment]
> > > You only see fracture of reviews because Google Play store is stupid and will show only your language, check like this:
> > > https://play.google.com/store/apps/details?id=com.github.stenzek.duckstation&hl=en&gl=US&showAllReviews=true
> > 
> > 
> > Ah thanks for clarification, I retract my previous post.
> 
> “It's amazing that a developer can make an app work on Windows but on Android it's complete garbage. What's the point of having a PlayStation emulator if you can't even load iso. And please don't act like am a idiot”
> 
> I don’t think I’ve ever wanted to hit someone from the internet any more than him.

The Dunning-Kruger effect is strong with that one, sadly even in this generation some people are still completely inept when it comes to software usage, which is somewhat fine but the true crux of the problem is not acknowledgeing it and being rude at.

**Comment by MojoJojoDojo** [comment]
If someone wants PBP support he or she could just create a PR lol.

**Comment by stenzek** [comment]
This has gone way off-topic, so I'm locking it for now until there is further updates.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/46ff2b553ddf2de81df472d443a4bd012fe69ce3 thanks to @ggrtk. We still need to figure out the best way to handle multi-disc images.
