### ISSUE TITLE
Big Duck Mode - Linux

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#1703]
**Game details**
Not Related

**Description of the issue / bug**
1.Big Duck Mode aka (NoGui) is not running in Linux

2.Discord Rich Presence not working

3.Full-screen not working properly as follows:

![Captura de tela de 2021-02-27 17-46-41](https://user-images.githubusercontent.com/43047877/109399840-ea7fea80-7923-11eb-9f54-ca8cd9ee1db5.png)

**Controller Troubleshoot Report**
Not Related

**Steps to reproduce**
1.(issue) Downloaded and unzip the .appimage emulator, give it execution permissions, try to run it and nothing happens.

2.(issue) set "discord rich presence" ON

3.(issue) click in full-screen button, screen at the left bottom and at right will be not filling entire screen

**Enhancements information**
Not Related

**Hardware/software**
System: Ubuntu 20.04.2
CPU i5 6gen 
8Gb DDR4

**Emulator version**
Latest Preview

**Additional context**
As discussed on Discord after you left I figured out how to solve this issue so decided to raise this so you don't forget to check when you can, if this is not necessary just close it as invalid :stuck_out_tongue: 

After tried to run Duckstation no GUI in Terminal the following error appears:

![image](https://user-images.githubusercontent.com/43047877/109399479-d1763a00-7921-11eb-8d1d-4aade3432c99.png)

So installing those dependencies (libsdl2) solved it as follows:

- sudo apt install libsdl2-2.0-0 and in case your Linux be 32Bits just add: sudo apt install libsdl2-2.0-0:386

**Comment by andercard0** [comment]
Tiny update about my reports in latest Preview build full-screen mode is working correctly now when choose [ ] Start in full-screen now is fixed. but, as soon as get out from full-screen background of it blinks a lot, can't ofc capture that in the pic below but easily reproduce able. 

![image](https://user-images.githubusercontent.com/43047877/111890651-40e3c480-89ca-11eb-9909-20a34293b61e.png)

Captured exact moment it blinks 

![image](https://user-images.githubusercontent.com/43047877/111890692-be0f3980-89ca-11eb-9519-cafdbca02c2d.png)

Other thing I've noticed is (as well shown down below) can't choose exclusive ful-lscreen resolution to it.

![image](https://user-images.githubusercontent.com/43047877/111890674-84d6c980-89ca-11eb-9df3-dcdc2c364d84.png)

**Comment by stenzek** [comment]
Fullscreen when running under wayland should be fixed with https://github.com/stenzek/duckstation/commit/47ba6e7449f3696745dd7c89b481c08a6f8ba3d5

If you're running under xorg, the flickering when switching to fullscreen is unavoidable; due to how gnome-shell handles things..
