### ISSUE TITLE
Digimon Card Battle, memory card recompiler issue

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#1705]
**Game details**
[Serial Code, Region]
Digimon Card Battle SLUS -01328

**Description of the issue / bug**
During the intro the game will ask you if you want to create a save file after which it will say that there is no memory card in slot 1.
This happens only in recompiler, no such issue in interpreter and cached.
Oddly enough the game sees the memory card in the continue menu.

**Steps to reproduce**
Boot the game in recompiler mode, select new game and get through the 1min intro until it asks you if you want to create a save file.

**Enhancements information**
None

**Hardware/software**
Win10
i7 4770
GeForce 1650S 
16gb DDR3
D3D11 render

**Emulator version**
Newest as of typing, please make the versions nr simpler or be able to be copied.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/520b64e711b34b47d7ce32a61b328dda6eb7eb85
