### ISSUE TITLE
Graphical glitches on the loading screen in Crusader - No Remorse

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#171]
Flashing yellow line on the top left corner of the loading box. Flashing red line at the bottom center of the screen. Happens with both OpenGL and D3D11. 

![SLUS-00268_2020-03-26_14-09-59](https://user-images.githubusercontent.com/31968468/77606505-cc6b7680-6f6b-11ea-841e-84bdea91f3df.png)

**Comment by stenzek** [comment]
Please verify with another source (preferably console) first.

**Comment by stenzek** [comment]
Confirmed by @HeroponRikiBestest as an emulator issue.

**Comment by stenzek** [comment]
Can't seem to reproduce on latest build.

**Comment by kurayami6** [comment]
The original issue has been fixed but a new one seems to have been introduced at some point. 

![Capture](https://user-images.githubusercontent.com/31968468/84592801-944d4300-ae8b-11ea-8471-35f9c7b3ee42.PNG)

**Comment by stenzek** [comment]
Which crop mode are you using?

**Comment by kurayami6** [comment]
"only overscan area" If I set it to "none" the problem gets much worse. 

![Capture2](https://user-images.githubusercontent.com/31968468/84594661-3c1c3e00-ae97-11ea-829b-0c87543bfeb1.PNG)

**Comment by stenzek** [comment]
FMV looks fine to me even in none mode. Are you using the PAL version by any chance?

**Comment by kurayami6** [comment]
I am.

**Comment by stenzek** [comment]
Hmm, probably similar issue to other PAL games.

**Comment by HeroponRikiBestest** [comment]
I no longer have the issues with the loading screen on software, opengl, or vulkan. Maybe move the pal fmv issue to a new topic.

**Comment by kurayami6** [comment]
This looks like the same problem as Blasto (Europe). I'll close this and merge it.
