### ISSUE TITLE
Lignux - Wine test with Screenshots & Dunnos

### ISSUE THREAD

**Issue by inukaze** [stenzek/duckstation#1712]
Hi there, like @stenzek said, try under Wine because by the moment i can't use the linux native version ( https://github.com/stenzek/duckstation/issues/1710 ) .

I Love this UI, is like all things i mention in « Feature Request » of projects like PCSX ReArmed, Mupen64Plus. Mainly

Ok here i go : 

1 - Akumajou Dracula X - Gekka no Yasoukyoku. Fan Spanish Re-Translation works perfectly
![DuckStation-007](https://user-images.githubusercontent.com/1647332/109493351-bced8b00-7a62-11eb-93ae-fff6c15c7091.png)

2 - In the second try i want test Final Fantasy IX, but i need to chage the sbi filenames for make it work properly
![DuckStation-008](https://user-images.githubusercontent.com/1647332/109493401-d262b500-7a62-11eb-8b3b-41d1324adf2b.png)

Because on another emulators, is used the serial for sbi patch.
![DuckStation-009-SBI-Files](https://user-images.githubusercontent.com/1647332/109493546-0ccc5200-7a63-11eb-9743-48793c5377eb.png)

Well i just see the readme and i understand must be the same name of disc image but with sbi extension. 

Well testing Final Fantasy IX (i just have OpenGL) i change some configurations i love is apply on the fly.
![DuckStation-012](https://user-images.githubusercontent.com/1647332/109493741-4dc46680-7a63-11eb-884b-c177b0aae813.png)

But i notice if i try to set internal resolution diferent of 1x, really does not work xD well, does not matter, maybe was a wine issue because the version of wine i am using. 

![DuckStation-013](https://user-images.githubusercontent.com/1647332/109493862-7a787e00-7a63-11eb-9311-195e5984f50f.png)

Going with the test i try with 2 Japanese Titles
![DuckStation-016](https://user-images.githubusercontent.com/1647332/109494002-ac89e000-7a63-11eb-9bc2-8e1e264743c8.png)

Tetris with CardCaptor Sakura
![DuckStation-015](https://user-images.githubusercontent.com/1647332/109494029-b9a6cf00-7a63-11eb-9524-ef05e28bdc28.png)

i don't like the 2D graphics without filtering, i really love i can set configuration per game.

![DuckStation-017](https://user-images.githubusercontent.com/1647332/109494131-dba05180-7a63-11eb-8b83-a6841dae4519.png)

I think now looks better 
![DuckStation-018](https://user-images.githubusercontent.com/1647332/109494165-e6f37d00-7a63-11eb-85ea-5e7648a0b8e0.png)

Next Japanese Title : GeGeGe no Kitarou - Gyakushuu! Youma Daikessen

Is the first time i see the retroachivements try to connect, was the first thing i configure. because on retroarch i use a lot in hardcore mode.

![DuckStation-019](https://user-images.githubusercontent.com/1647332/109494216-f96db680-7a63-11eb-8067-4f96bc0fc204.png)

![DuckStation-020](https://user-images.githubusercontent.com/1647332/109494336-20c48380-7a64-11eb-98ac-062b959f8292.png)
![DuckStation-021](https://user-images.githubusercontent.com/1647332/109494356-26ba6480-7a64-11eb-8f8b-71e4c714922f.png)

Dunnos : 
1 - Why Final Fantasy VII on the list the first Disc show a Title [the cue sheet not have set title yet, because i don't know if the UI read that value]

![DuckStation-004](https://user-images.githubusercontent.com/1647332/109494500-608b6b00-7a64-11eb-83f0-3e57fa288d54.png)

But the another two disc read the File name like title ?
![DuckStation-005](https://user-images.githubusercontent.com/1647332/109494547-6bde9680-7a64-11eb-96d5-e269646b720d.png)

and not less important, why i can't edit the title of the first disc ? 
The fact is a Re-Translated Version to Spanish is affecting that inside DuckStation ?

2 - In the UI the values in the right inferior corner, after the "100% 60/60 FPS" what are ? i just see
9.98ms average, 25.19ms worst

but i not idea about what is this information.

Well suggestion : in the left inferior corner, can add 
RetroAchivements : Yes
RetroAchivements : No
RetroAchivements : Not logged

3 - Well i love CHD format i just had use with MAME and ReDream emulators but all very simple. i want to know which is the best way for use chd format with DuckStation.

For example if i had a game like Overboard or Mortal Kombat Trilogy, both game use a lot of Track Files for the music of game. i can use qchdman for put inside the chd file format the follow structure

```
Game.cue
Game (Track 01 - Data).bin
Game (Track 01 - Data).sbi
Game (Track 02 - Music 01).bin
Game (Track 02 - Music 02).bin
Game (Track 02 - Music 03).bin
Game-Cover.png
Game-Disc1.png
Game-Disc2.png
Game-Disc3.png
Game-Disc4.png
Game-Disc5.png
```

All that inside of "Game.chd" file capable load from DuckStation ?

Well thank you for any helpful answer you can share with me.

**Comment by stenzek** [comment]
This is not an issue report, so I'm closing.

> But i notice if i try to set internal resolution diferent of 1x, really does not work xD well, does not matter, maybe was a wine issue because the version of wine i am using.

Check the log. I wouldn't be surprised if it was failing to compile shaders and falling back to the software renderer (outdated drivers).

> and not less important, why i can't edit the title of the first disc ?

Because it uses redump titles. Right click in the columns and you can show the file title instead.

> 2 - In the UI the values in the right inferior corner, after the "100% 60/60 FPS" what are ? i just see

speed, internal game frames per second, vsyncs per second (real console frame rate),

> Well suggestion : in the left inferior corner, can add
> RetroAchivements : Yes
> RetroAchivements : No
> RetroAchivements : Not logged

Not really interested in this to be honest. As far as I'm concerned, it's still a niche feature. It displays a notification when the game starts.

> For example if i had a game like Overboard or Mortal Kombat Trilogy, both game use a lot of Track Files for the music of game. i can use qchdman for put inside the chd file format the follow structure

Just use `chdman createcd`, it will take care of everything. See https://github.com/stenzek/duckstation/wiki/Adding-Game-Covers for covers.

**Comment by stenzek** [comment]
Looks like an edge case where you have GL4.2 but no support for ARB_explicit_unifrom_location. Will push a fix later.

**Comment by inukaze** [comment]
Thanks, for now is not possible for DuckStation fill the CheckSum of Game in Game Window Properties ?

Well meanwhile i going to test things like 
[MangoHud](https://github.com/flightlessmango/MangoHud)
[GOverlay](https://github.com/benjamimgois/goverlay) for Graphical Configuration of MangoHud but Requiere [Lazarus IDE](https://github.com/graemeg/lazarus)

For test like works this monitoring Tool with Native Games, Emulators and the Games & Emulators using compatibility layers like Wine or Proton.

I read you later :=)

**Comment by stenzek** [comment]
> Thanks, for now is not possible for DuckStation fill the CheckSum of Game in Game Window Properties ?

You have to click the compute hashes button.
