### ISSUE TITLE
Improvement of Cheevos List

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#1716]
**Is your feature request related to a problem? Please describe.**

Navigating trough Achievements list at the end is not being correctly showed.
As follows in the video just made: 

https://streamable.com/nl4n4n

**Describe the solution you'd like**
At the middle of cheevos list would be good if possible to make this list be followed correctly as happens
in the beginning.

**Describe alternatives you've considered**
Maybe, make lock Cheevos Collapse. 

**Additional context**
Nothing more to add here.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/f47f99b62d0f3316d4b0a15209fba78a92bd9374 / https://github.com/stenzek/duckstation/commit/9cc079223c482ffebd5a9fd8259d7f2871688cc1
