### ISSUE TITLE
Make VRAM/GPU readbacks faster

### ISSUE THREAD

**Issue by ivan89el** [stenzek/duckstation#1718]
**Game details**
All games where there is a rendering of the sun

**Description of the issue / bug**
Looking at the sun performance is greatly reduced.

**Note:**
No optimization programs. New and system installed only DuckStation

**Steps to reproduce**
Start the game, find the sun and look at it.

**Enhancements information**
Where there is no sun performance is fine.

**Hardware/software**
Windows 10 x64 AMD Radeon 540x, AMD Ryzen 2500U (Vulkan, DX11)
Android 10 Snapdragon 720G (Vulkan, GLES)

**Emulator version**
All

**Additional context**
https://sun9-9.userapi.com/impg/BWI8q2T1preJSWFZdp9f7s19R3dANBqsAGQgOA/WQK1CboLo6Y.jpg?size=1920x1080&quality=96&sign=28fc854475e5191c80b4b729b80e6475&type=album
https://sun9-31.userapi.com/impg/beAXJbdgIvJ-PYsp4KLpJEMJNWtI6rXcGrEfkQ/S4VRZD1kcyE.jpg?size=1920x1080&quality=96&sign=d5efcdc861f535b7768560905a8ee88b&type=album
Sorry my english. You can reformat the text if something is wrong.

**Comment by foxsevent** [comment]
Not really a real issue just disable or lower some enchancrments like MSSA or SSAA, these enchancrments don't play well with certain effects.

Not much that can be done about that either get a better pc/phone or lower the setting.

**Comment by ivan89el** [comment]
@foxsevent 
Yes, I tried different renderers (vulkan, dx11) MSSA or SSAA never included

**Comment by foxsevent** [comment]
> @foxsevent
> Yes, I tried different renderers (vulkan, dx11) MSSA or SSAA never included. The only thing that helped is the resolution of 1x.

I doubt that much can be done here but stenzek will definitely know more, who knows maybe there's a bug in the code or he'll find a way to better optimize this.

This is just how rendering work certain effects will require more power to render than others.
In this case it's the suns lens flare effect
All I can confirm is in Driver this effect shaves of good 20-30 fps, but that's not much when it runs at 400 fps.

**Comment by ivan89el** [comment]
@foxsevent You probably have fast vram, so the performance decline is not so noticeable. NFS 4 High Stakes is unstable even in 1x.

**Comment by stenzek** [comment]
Not really a bug. Mobile GPUs are **very** slow at readbacks.

There's some potential improvements which can be made here, but not sure if it will make a huge difference.

**Comment by stenzek** [comment]
For what it's worth, this issue is basically non-existent on desktop (I only see minor slowdown as @foxsevent also said). You can also use the software renderer as a workaround.

**Comment by ivan89el** [comment]
@stenzek Thanks!

**Comment by stenzek** [comment]
Not really sure what else can be done here specifically, apart from generally improving the emulator performance which I am doing over time.

**Comment by ivan89el** [comment]
@stenzek The problem is solved thanks to " Use Software Renderer For Readbacks". Thank you very much!
