### ISSUE TITLE
Mortal Kombat 4 very minor sound bug.

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#1719]
**Game details**
[Serial Code, Region]
Mortal Kombat 4 SLUS-00605

**Description of the issue / bug**
Really difficult to explain this so here's some videos,
Here's how it sounds in Ducko,
https://youtu.be/jfMAJUmIkps
And here's how it should sound.
https://youtu.be/9-4WH1xctUM?t=60

**Steps to reproduce**
Do Fatality nr 2 with Sub-Zero

**Enhancements information**
None.

**Hardware/software**
i7 4770
Geforce 1650S
16GB DDR3
D3D11

**Emulator version**
Newest preview as of typing.

**Comment by stenzek** [comment]
Have you confirmed this issue (preferably) on console or with other emulators? That second video looks like PC footage?

**Comment by Kurayami7** [comment]
I'll check later but I wonder if this was his problem. 

![Capture](https://user-images.githubusercontent.com/77198254/111015643-0e502f80-83fe-11eb-858b-7356ee12e133.PNG)

**Comment by Kurayami7** [comment]
Sounds completely fine in Duckstation. Tested with a redump verified copy and recompiler. 

![SLUS-00605_2021-03-13_15-09-19](https://user-images.githubusercontent.com/77198254/111019099-3006e200-8411-11eb-92db-ab8b1709ee4b.png)

**Comment by stenzek** [comment]
It definitely sounds... wrong, but I guess it's just a bug with the PS1 version. Instead of using a single voice, it's allocating it across all free voices.
