### ISSUE TITLE
Colin McRae Rally 2.0 (USA) (En,Fr,Es) thick black line on left hand side of screen

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#172]
![colin](https://user-images.githubusercontent.com/2696404/77635456-9212d100-6f8d-11ea-9683-dd3ff1576804.PNG)

**Comment by kurayami6** [comment]
This only happens in windowed mode and only if you have crop mode set to "none". 

Crop mode "none"

![Capture2](https://user-images.githubusercontent.com/31968468/85718635-0cd8bd00-b732-11ea-857e-6099f64dbf5b.PNG)

Crop mode "only overscan area"

![Capture](https://user-images.githubusercontent.com/31968468/85718697-1a8e4280-b732-11ea-9c42-e367e2268205.PNG)

Crop mode "all borders"

![Capture3](https://user-images.githubusercontent.com/31968468/85718831-3abe0180-b732-11ea-9fc7-51c1b61b350f.PNG)

**Comment by stenzek** [comment]
Yeah, this one will need a gameini tweak
