### ISSUE TITLE
Add an option to skip logical seeking to improve load times

### ISSUE THREAD

**Issue by LukeTheDuke240** [stenzek/duckstation#1728]
**Is your feature request related to a problem? Please describe.**
Duckstation loads certain games like Gran Turismo 2 (which accesses the cd whenever you change screens or options) very slowly compared to other PS1 emulators, which might be due to the fact that duckstation emulates CD-ROM with logical seeking. This slow loading persists even when overclocking is enabled, and cd read speedup is enabled, at least in gran turismo 2.

**Describe the solution you'd like**
Add an option (could be game specific) to disable logical seeking to improve load times. This might break some games that rely on accurate CDROM timing, but would significantly improve gran turismo 2.

**Describe alternatives you've considered**
Activating overclocking and cd read speedup yields close to no benefit on gran turismo 2, even on their maximum values. This is caused by 99% of the cd-rom time being logical seeking, and the other 1% being actual reading.

**Additional context**
![image](https://user-images.githubusercontent.com/60626522/109737770-8020c000-7c2b-11eb-86c9-328fce13e61b.png)

**Comment by stenzek** [comment]
_Really_ not a fan of this idea because it will break so many games. But I guess it could be an option.. just not sure what the values should be - "instant seek"? "speedup by N times"?

**Comment by Kurayami7** [comment]
FWIW I think this is a terrible idea. If a game itself has a problem it should be fixed with a fan patch, not a per game hack in the emulator itself that can and will break things.

**Comment by stenzek** [comment]
> FWIW I think this is a terrible idea. If a game itself has a problem it should be fixed with a fan patch, not a per game hack in the emulator itself that can and will break things.

They're not asking for a per game hack. They're asking for an enhancement to make the game load faster.

**Comment by LukeTheDuke240** [comment]
> FWIW I think this is a terrible idea. If a game itself has a problem it should be fixed with a fan patch, not a per game hack in the emulator itself that can and will break things.

It's clearly not a problem with gran turismo since other emulators don't seem to have 10 second+ load times on every screen. I kind of just want to know how and why the load times take so long and if it could be improved. It might not even be cdrom seeking that is causing it. I think skipping seeking would break certain games but it would be a significant improvement to certain games too

**Comment by Kurayami7** [comment]
I can time it on my real PS1 if you want. Which loading screen do you think takes too long.

**Comment by stenzek** [comment]
> It's clearly not a problem with gran turismo since other emulators don't seem to have 10 second+ load times on every screen. I kind of just want to know how and why the load times take so long and if it could be improved. It might not even be cdrom seeking that is causing it. I think skipping seeking would break certain games but it would be a significant improvement to certain games too

I'd almost be willing to bet those emulators are wrong. PCSXR especially basically has no CD timing the last time I looked. You cannot use it as a ground truth - compare against console.

Like I said, I'm *really* not a fan of these sorts of enhancements because they break so many games, and then people complain "game X is broken" and it's because they had CDROM speedup on. I usually get at least one a week. Hence why I encourage people to use fast forward instead.

But it's still a valid request.

**Comment by LukeTheDuke240** [comment]
> > It's clearly not a problem with gran turismo since other emulators don't seem to have 10 second+ load times on every screen. I kind of just want to know how and why the load times take so long and if it could be improved. It might not even be cdrom seeking that is causing it. I think skipping seeking would break certain games but it would be a significant improvement to certain games too
> 
> I'd almost be willing to bet those emulators are wrong. PCSXR especially basically has no CD timing the last time I looked. You cannot use it as a ground truth - compare against console.
> 
> Like I said, I'm _really_ not a fan of these sorts of enhancements because they break so many games, and then people complain "game X is broken" and it's because they had CDROM speedup on. I usually get at least one a week. Hence why I encourage people to use fast forward instead.
> 
> But it's still a valid request.

Oh yeah those emulators certainly have super inaccurate emulation, i'm just suggesting it as a quality-of-life improvement.

**Comment by Kurayami7** [comment]
Where are these supposedly long loading times? I just got to a race and nothing took more than a few seconds to load.

**Comment by LukeTheDuke240** [comment]
Races load fine, but loading a car model in the menu takes quite a while.
Here's a video of what I mean: [https://www.youtube.com/watch?v=LuBMvpktwH0](https://www.youtube.com/watch?v=LuBMvpktwH0)
I know these 2 emulators are in no way comparable, but I'm just using it do demonstrate loading times if the seeking was skipped. I know it would degrade the accuracy of the emulation.

**Comment by Kurayami7** [comment]
Oh you're playing Simulation mode. I was testing Arcade mode. You should have specified that. I'll check that one as well.

**Comment by Nucleoprotein** [comment]
I see some broken logic here. Duckstation is like first accurate enough emu to have very close to HW load times so you want to break accuracy and possible games to load faster? 

PS: How Duck compares to Mednafen or Xebra with loading times? PS Emu Pro emulators are not even close to proper CDROM emulation and psxfin was never really finished.

**Comment by LukeTheDuke240** [comment]
> I see some broken logic here. Duckstation is like first accurate enough emu to have very close to HW load times so you want to break accuracy and possible games to load faster?
> 
> PS: How Duck compares to Mednafen or Xebra in load times? PS Emu Pro emulators are not even close to proper CDROM emulation and psxfin was never really finished.

I want an optional feature for certain games to skip logical seeking (specifically for games that it wouldn't break) so that their load time would be improved. _I know_ this ruins the accuracy of the emulator and i understand if you guys don't want to include it so that you can stay 100% accurate.
Also mednafen has the same loadtimes as duck. (i.e. hardware accurate)

**Comment by stenzek** [comment]
I think you're underestimating how many games this will actually work in. Or if they "appear" to work but then get random breakage later on.

That's again why I suggest fast forwarding, the emulator is very fast so it's easy enough to do.

If it wasn't for people nagging so much for faster read speeds I wouldn't have done that either.

**Comment by Vaporeon** [comment]
Sometimes it is better for everyone sanity to just say no to these requests.
Going by past experience *most* people will accept it.

**Comment by stenzek** [comment]
I mean, it's not really that much more risky than the actual read speedup. But it's still a very dangerous option.

**Comment by DukeSkinny** [comment]
How about an option to automatically fast forward if the emulator detects data is loading while no audio is playing? Feasible?

**Comment by stenzek** [comment]
Pretty difficult to detect loading, plenty of games stream data ingame or render stuff while loading so I don't think such heuristics would be very reliable

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/98e4c181ca3f98633b2d94f536aee900c2ea5372. Seems to work well in RE3, but beware, this **will** break plenty of games.
