### ISSUE TITLE
CyberSled (Japan) missing disc serial

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#173]
![cyber](https://user-images.githubusercontent.com/2696404/77636581-4bbe7180-6f8f-11ea-8112-539805617457.PNG)
SLPS 00023

**Comment by stenzek** [comment]
The game code is pulled from the `SYSTEM.CNF` file on the disc. It's possible this game does not specify the executable name in this config file.

**Comment by stenzek** [comment]
This game does not appear to have a `SYSTEM.CNF` and the BIOS just loads `PSX.EXE`. Therefore, working as intended. Not much I can do unless there's another location we can pull the code from.
