### ISSUE TITLE
Gamepads on Android can't send inputs to the game

### ISSUE THREAD

**Issue by Xane123** [stenzek/duckstation#1730]
**Game details**
SCUS-94249 Twisted Metal III (USA)

**Description of the issue / bug**
Gamepads don't work in-game, period. I got a **Flydigi Wee 2T** today, put it in classic mode, then configured its buttons in Duckstation's controller options.

While the controller works perfectly in the menus, Twisted Metal III (the only PS game I have on my phone) doesn't respond to any button-presses (like up/down/X in menus). This problem isn't specific to that controller, either. I paired a single Joy-con to my phone, configured its buttons, and it also doesn't send inputs to the phone (but can barely interact with Duckstation's interface)...

**Controller Troubleshoot Report**
1. Only Flydigi's app. This behavior occurs regardless of if it's running or not. Plus, this bug affects more than the Wee 2T.
2. _(Controller backend option isn't on Android)_

**Note:**
_If you are using Duckstation on Android device please consider the following before report:
Are you using any kind of "memory optimizer" program such as: Ccleaner, Wisecleaner, Clean Master, Boost Android etc. ?_
My phone doesn't have any installed.

**Steps to reproduce**
[Try to provide as much detail as possible to reproduce the issue]
- Pair the Flydigi Wee 2T, Joy-con, or another gamepad to the phone.
- Go into Duckstation's options > Controller Options and set up the buttons.
- Start the game. After the 989 Studios logo disappears, pressing the cross/X button will not skip the video, but the touch controls will. Similarly, the menu won't respond to actual gamepad input, but the touch controls will.

**Enhancements information**
All enhancements were disabled using the option in Advanced Options before testing this bug last.

**Hardware/software**
Google Pixel 4a (5G), Android 11

**Emulator version**
DuckStation for Android 0.1-3187-gf580dbc6 (dev)
Built Feb  9 2021 01:08:11

**Additional context**
This probably affects every game and other controllers, but I don't think I have any other Bluetooth controllers to test. I can copy more game files to the phone to test if the bug affects them, if requested.

**Comment by 6lackmag3** [comment]
DualShock 4 works fine here. Flydigi Wee 2T is on the go, I,'ll test it soon.

**Comment by 6lackmag3** [comment]
@Xane123 my Wee 2T has arrived today. A nice little gamepad and it works flawless in DuckStation and other emus. Pair Wee 2T with smartphone and install Flydigi Game Center app from Google Play. On first run it will prompt you to upgrade firmware for your gamepad. Flash it and then change current mode from Flashplay to Classic. Now you good to go.

**Comment by stenzek** [comment]
Great, thanks for checking @6lackmag3.

**Comment by Xane123** [comment]
That's good to know, @6lackmag3. When I got my Wee 2T, I installed that from their website (using the QR code) but it strangely didn't say it had an update, and claimed I had the latest version when I went to check for them. Did you need to "activate" classic mode like the app claims, or did your controller appear to stay in classic once you launched another app from the Game Center like mine?

It feels like the "activation" that the Game Center wants is just an illusion and the controller secretly switches over to classic mode fine plugging it into the phone (which didn't work properly for me). I can use the FlyMapping mode to play using the touch controls, but being able to get rid of touch controls entirely would be better. When in "unactivated classic mode", the Wee 2T works perfectly in Minecraft, but not in Duckstation.

@stenzek I don't know... Is this really the intended behavior? The joy-con was also tested in the bug report and showed the same behavior, where it worked in the menu when setting up controls, but wouldn't send inputs to the game.

**Comment by 6lackmag3** [comment]
@Xane123 you may force specific connection mode for any game/app in Flydigi Game Center.

<details>
  <summary>Screenshot</summary>

![IMG_20210308_051026](https://user-images.githubusercontent.com/13922742/110265569-e8292a80-7fcc-11eb-8999-b4516da18d36.jpg)

</details>

I don't play any Android games except for emulators so I use my Wee 2T in classic/native mode only.
