### ISSUE TITLE
Control Setting loading profile Crashes

### ISSUE THREAD

**Issue by zkdpower** [stenzek/duckstation#1738]
Control Setting loading profile Crashes always in latest version.

**Comment by TheKins** [comment]
Getting this too, so putting a properly-formatted report here:

**Game details**
No game loaded.

**Description of the issue / bug**
Attempting to load an input profile in Controller Settings causes a crash.

**Controller Troubleshoot Report**
I utilize DS4Windows, and have had no problem with it on a previous version.
Controller backend is SDL.

**Steps to reproduce**
1.) Open Duckstation QT.
2.) Open the Settings menu.
3.) Go to Controller Settings.
4.) Click "Load Profile"
5.) Click any profile.
6.) Watch as the program closes before your very eyes.

**Enhancements information**
This crash can occur without a game even being loaded, so enhancements aren't especially relevant. But yes, this occurs even if they're disabled.

**Hardware/software**
Windows 10 Home
AMD Ryzen 5 1600
GeForce GTX 1070
D3D11 Renderer

**Emulator version**
DuckStation 0.1-3425-g0cbba59e (dev)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/ccda1553b7a263581b2f554e06b7ecc308bdd8c9, thanks for letting me know.
