### ISSUE TITLE
Cheevos Quick Menu Pause

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#1739]
**Game details**
Not Related

**Description of the issue / bug**
When accessing cheevos list (in quick menu) game pause but is not possible to unpause it after leave this list.

**Controller Troubleshoot Report**
Not related.

**Steps to reproduce**
Open quick menu > Achievements (when it opens) game is paused and remains paused even after i went back to the game and close quick menu. I've noticed that it only happens if option " Pause on Menu " is ON of course, but, isn't supposed to.

As my understand of this option should unpause the game after i choose (<<Back), to return to the game.
If, Pause on Menu is off this issue does not happens!

**Enhancements information**
Not Related

**Hardware/software**
Does not matter in this case! 

**Emulator version**
Duckstation 0.1-3417-g21e53016 (Preview)

**Additional context**
Still related to this another issue I'm facing which was already reported previously!

As follows you can see that close option is not accessible with controller i have to mouse click to close it, would be good if we could close it via controller too.

![1](https://user-images.githubusercontent.com/43047877/109894667-a9ae0b80-7c6c-11eb-9f13-0a9d2a7fa33f.png)

and here, when press my shortcut to close quick menu (with controller) could not access the list anymore it get stuck, paused. 
My only option was use mouse to unpause and then resume emulation. 

In this case this issue is made as follows: 

- Open quick menu (L3 my shortcut bind) > navigate trough Cheevos list > L3 back again then stuck and paused.

![image](https://user-images.githubusercontent.com/43047877/109895007-453f7c00-7c6d-11eb-9676-f2aaa23e0c95.png)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/c3d2999d7871a4f8868c9888f39058ff95b7d80e

> As follows you can see that close option is not accessible with controller i have to mouse click to close it, would be good if we could close it via controller too.

You can - hit the B or circle button.

**Comment by andercard0** [comment]
> Fixed in [c3d2999](https://github.com/stenzek/duckstation/commit/c3d2999d7871a4f8868c9888f39058ff95b7d80e)
> Issue still persist just tested here and it is paused only work around is to uncheck that option.
