### ISSUE TITLE
Arc The Lad III Disc Switch is not recognized

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#174]
put in disc 2 and  then start a new game 
it will say insert disc 1 and when you change disc it will stay on the insert disc 1 screen
![arc](https://user-images.githubusercontent.com/2696404/77637766-23d00d80-6f91-11ea-9e94-3d4f20ee0819.PNG)

**Comment by stenzek** [comment]
Should be fixed by latest master.

**Comment by benderscruffy** [comment]
stuck on the please wait screen now
![arc1](https://user-images.githubusercontent.com/2696404/77837125-e8536000-7197-11ea-9e17-4ea68a6b7c19.PNG)
![arc2](https://user-images.githubusercontent.com/2696404/77837126-ea1d2380-7197-11ea-9c5f-da8a126feba6.PNG)

**Comment by stenzek** [comment]
My bad - I did fix this, but another CDROM change broke it again. Should be fine now.

**Comment by benderscruffy** [comment]
fixed
