### ISSUE TITLE
Blaster Master - Blasting Again (USA) [major crash on Duckstation]

### ISSUE THREAD

**Issue by Cibomatto2002** [stenzek/duckstation#1744]
Operating System
	Windows 10 Home 64-bit
CPU
	AMD Ryzen 7
	Summit Ridge 14nm Technology
RAM
	16.0GB Dual-Channel Unknown @ 1197MHz (17-17-17-39)
Motherboard
	Dell Inc. 0VYXHD (AM4)
Graphics
	C27F390 (1280x720@60Hz)
	4096MB ATI AMD Radeon RX 580 (Dell)
Storage
	931GB Seagate ST1000DM010-2EP102 (SATA )
	119GB Samsung Flash Drive FIT USB Device (USB )
Optical Drives
	No optical disk drives detected
Audio
	High Definition Audio Device

Game will crash early into the game. tried this on to computers and it will crash in the same spot every time. I tried another emulator and it did not crash.

SLUS-01031 Blaster Master - Blasting Again (USA)

CRC-32 90930dff
CRC-32 c121b8ee
CRC-32 8d60d0fb

![Capture3-5-2021-8 41 37 AM](https://user-images.githubusercontent.com/21169038/110132126-75337000-7d90-11eb-9670-a4f25dc69f7e.jpg)
![Capture3-5-2021-8 42 18 AM](https://user-images.githubusercontent.com/21169038/110132140-795f8d80-7d90-11eb-94f3-ed11cd0e4bf7.jpg)
[crash.txt](https://github.com/stenzek/duckstation/files/6091277/crash.txt)
[crash.zip](https://github.com/stenzek/duckstation/files/6091285/crash.zip)

**Comment by andercard0** [comment]
Working good here as you might view below no crashes at all

![image](https://user-images.githubusercontent.com/43047877/110135556-6b6c3580-7dad-11eb-9cd0-ae2e3cefb741.png)

Please, check if your game is valid compute hashes

![image](https://user-images.githubusercontent.com/43047877/110135629-7de66f00-7dad-11eb-936e-203cc75dbdb4.png)

**Comment by stenzek** [comment]
Yeah, definitely check your dump is valid, the code it must've been trying to execute to end up in that state is very strange.

Will sort out the emu panicing, the result will probably be a game crash after that's fixed.

**Comment by Cibomatto2002** [comment]
Redump.org says it's a good copy it will crash at a certain cave I will make a video of it crashing and upload it to youtube.

**Comment by stenzek** [comment]
No need for now, I've sorted out the panic itself, it's just a question of whether this is valid code the game's trying to execute...

**Comment by Cibomatto2002** [comment]
I forgot to send the game properties sorry
![Capture3-5-2021-9 52 43 AM](https://user-images.githubusercontent.com/21169038/110139510-b92a7300-7d98-11eb-8cc4-2f9b09999026.jpg)

**Comment by stenzek** [comment]
I forgot to ask; What happens if you use the interpreter?

**Comment by Cibomatto2002** [comment]
I never did try it I just use the default settings I will try it tonight and report back to you no later than tomorrow..

**Comment by stenzek** [comment]
Panic should be fixed in https://github.com/stenzek/duckstation/commit/bf5f53e1d13df5febc934baf410985f0656c7ddb (preview build), but I'm still not sure if it's executing valid code (hence why I asked to check intepreter)

**Comment by Cibomatto2002** [comment]
just tried interpreter that fixed it sorry I wasted your time. I had no idea what interpreter was for. Is it ok to use it all the time?

**Comment by foxsevent** [comment]
> just tried interpreter that fixed it sorry I wasted your time. I had no idea what interpreter was for. Is it ok to use it all the time?

Yes you can use it all the time, interpreter is slightly more accurate than the default recompiler but it is much much slower aka far more demanding on the CPU.

**Comment by Cibomatto2002** [comment]
Will this get fixed so it will run on the fastest  recompiler?

**Comment by stenzek** [comment]
Did you try the latest preview build?

**Comment by Cibomatto2002** [comment]
When I downloaded it it was a older one I think it was yesterday I will downloaded it tomorrow and try again. Thanks for your time.

**Comment by Cibomatto2002** [comment]
just got Latest Preview Build from today so far it's working with no crashes with the Recompiler (Fastest)

**Comment by stenzek** [comment]
Great, thanks for checking!

**Comment by Cibomatto2002** [comment]
could you tell me why it was crashing so hard?

**Comment by stenzek** [comment]
Branches in branch delay slots. They're not really possible to handle in a recompiler, since the second branch's delay slot is unpredictable, so I just fall back to the interpreter for that one section of code (the rest runs as normal).

**Comment by Cibomatto2002** [comment]
thanks for explaining now I just need to wait for the Retroarch core to get updated looks like the last update was Feb 4 I hope it gets updated with this fix soon i use both thestand alone and core it depends on what computer i am on anyways thanks for getting to fixed so fast. :)
