### ISSUE TITLE
Wide Adjusted / Adjust Game Aspect Ratio

### ISSUE THREAD

**Issue by SA-X0** [stenzek/duckstation#1747]
**Is your feature request related to a problem? Please describe.**
2 emulators so far that i know of have this option, Mupen64Plus with GLideN64 (N64 Emulator) and Flycast (Dreamcast Emulator) (Even tough is called Widescreen Hack does act as Adjusted)
Some games have nice results while some not so much, but better than using widescreen hack on 3D games with or many 2D elements (not backgrounds).
Examples:
![Resident Evil - Code - Veronica (USA)-210305-130727](https://user-images.githubusercontent.com/69441718/110162135-ef292080-7db3-11eb-9a02-c0017260665f.png)
![Biohazard - Code - Veronica - Kanzenban (Japan)-210305-130503](https://user-images.githubusercontent.com/69441718/110162138-efc1b700-7db3-11eb-9f51-87b91f1acc8b.png)
![Super Mario 64 (Japan) (Rev 3) (Shindou Edition)-210305-132411](https://user-images.githubusercontent.com/69441718/110163843-39130600-7db6-11eb-915e-7904094b73ba.png)
![Super Mario 64 (Japan) (Rev 3) (Shindou Edition)-210305-132453](https://user-images.githubusercontent.com/69441718/110163845-39130600-7db6-11eb-86c5-607f7093f3c1.png)

**Describe the solution you'd like**
Is it possible for this feature to be available as well on Duckstation? 

**Describe alternatives you've considered**
Not sure if there's another alternatives, ones that already exist are patching the game executable, and codes to an extent.

**Additional context**
[Example](https://www.youtube.com/watch?v=yHtfe3CoUhk)

Thank You.

**Comment by foxsevent** [comment]
Not sure what you want exactly Duckstation already has a widescreen hack that works well with most 3D games.

**Comment by SA-X0** [comment]
I know about the widescreen hack, this is actually different.
Widescreen but doesn't stretch 2D stuff like HUD for example, will take 2 screenshots for an example.

**Comment by foxsevent** [comment]
> I know about the widescreen hack, this is actually different.
> Widescreen but doesn't stretch 2D stuff like HUD for example, will take 2 screenshots for an example.

I see, I'm sure if it was easily doable it would've been done already, it's just different how PS1 renders things vs N64 and Dreamcast.
Let's wait and see what stenzek thinks

**Comment by SA-X0** [comment]
![Resident Evil - Code - Veronica (USA)-210305-130727](https://user-images.githubusercontent.com/69441718/110162135-ef292080-7db3-11eb-9a02-c0017260665f.png)
![Biohazard - Code - Veronica - Kanzenban (Japan)-210305-130503](https://user-images.githubusercontent.com/69441718/110162138-efc1b700-7db3-11eb-9f51-87b91f1acc8b.png)

**Comment by SA-X0** [comment]
See for example on those 2 screenshots.
First one is with the widescreen cheat everything is good but the text gets stretched, the second one which Flycast use is Wide Adjusted (Called Widescreen Hack) doesn't touch the 2D stuff, the inventory for example switches to 4:3 while with widescreen cheat or hack gets stretched.

**Comment by ggrtk** [comment]
The widescreen hack works by performing horizontal scaling on vertices of polygons processed through the GTE, which gives us an anamorphic widescreen effect in GPU VRAM that we scale out on display output. It's done this way since we can't simply hack in an expansion of the game's framebuffer size as VRAM is flexibly shared with textures. Furthermore, the GPU will clip to the specified draw area during rendering, meaning we can't render outside of the specified framebuffer. Some games will process 2D HUD elements through the GTE, but it's certainly not necessary to do so, and the game can also get 2D elements into the framebuffer region with blits.

I don't know how those N64 emulators work, but I'm guessing they're probably creating a larger framebuffer where the polygons in the extra widescreen area aren't being clipped or culled. We don't really have that sort of flexibility due to the PS1's graphics setup, though perhaps with the right heuristics on detecting drawing and display areas a similar effect could be achieved with extra framebuffers. I'm not sure there's really a catch-all solution that will work on all cases though...

Feel free to correct any mistakes I've made here.

**Comment by SA-X0** [comment]
I could say otherwise for what i see on the rendering part, but in the end you guys know things better and how they work.
Specially more in depth stuff or innerly of a console of how it works and with enhancements that are possible.
But if you guys have a few games try that on Flycast or Mupen64Plus the Retroarch cores but i think the stand alone ones have that option as well, at least Mupen64plus, Flycast lacks stuff or options that the core has.
If this is possible and you guys considered it, awesome.
Tf not well, still thank you for taking the time for checking my request.

**Comment by foxsevent** [comment]
> I could say otherwise for what I've seeing on the rendering part, but in the end you guys know things better than i do and how they work.
> Specially more in depth stuff or innerly of a console of how it works and with enhancements that are possible.
> But if you guys have a few games try that on Flycast or Mupen64Plus the Retroarch cores but i think the stand alone ones have that option as well, at least Mupen64plus, Flycast lacks stuff or options that the core has.
> If this is possible and you guys considered it, awesome.
> Tf not, well, still thank you for taking the time for checking my request.

Like I said if it was that simple or even doable it would've been done by now by someone either on Duckstation, ePSXe , PCSXR or Retroarch Beetle core but none of them can do this.
And like it's been pointed out you can't compare what's possible between PS1, N64 and Dreamcast they're all vastly different system with huge differences when it comes to rendering, what's possible on one system maybe impossible on another, for example texture dumping and replacing on GC and N64 this is something easy and is possible for a very long time now while on PS1 it is something that only recently became possible but doesn't work well and will everything.

Who knows maybe what you're proposing is possible but if it was done Duckstation would be the first one to accomplish this.

**Comment by SA-X0** [comment]
I get the point.
You right foxsevent, specially on the texture dumping and replacing.
It's not common and Duckstation is among the first, i think Beetle PSX HW was another aside Duckstation to support that.
Flycast as well has texture replaecement but haven't seeing documentation of how it work but has the option for that.
Just want to be clear not trying tell otherwise on things that you guys have mentioned, each system if different of course is why i said you guy know things better.
Sorry foxsevent.

**Comment by stenzek** [comment]
There's already a widescreen hack, which is probably the best we can do as @ggrtk said.
