### ISSUE TITLE
[Feature Request] HLE bios / Free bios clone

### ISSUE THREAD

**Issue by Ember2528** [stenzek/duckstation#175]
It would be nice to have high-level bios emulation to use the emulator without extracting one form our own console. I know pcsxr has an implementation but it has a number of problems.

**Comment by stenzek** [comment]
Games patch the bios so hle'ing it isn't ever going to work for those. Would be better off with a free bios clone.

**Comment by stenzek** [comment]
DuckStation works with OpenBIOS - you can grab a copy by downloading PCSX-Redux: https://github.com/grumpycoders/pcsx-redux
