### ISSUE TITLE
Support for XBOX ONE Controller over wirless

### ISSUE THREAD

**Issue by gregdegruy** [stenzek/duckstation#1751]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to play games using an XBOX ONE Controller over wireless. Right now I am only able to play and configure a controller connected over witless. Only when the controller is connected over USB does it work.

**Describe the solution you'd like**
Support for my wirless XBOX ONE Controller to appear in the controller list when connected over Bluetooth.
![image](https://user-images.githubusercontent.com/8151045/110198532-17db0580-7e08-11eb-8890-b3b70d829a1b.png)

**Comment by stenzek** [comment]
Pretty sure this does work. Maybe try switching between SDL and XInput.

**Comment by stenzek** [comment]
Works fine here with an XBox One controller connected via bluetooth in both SDL and XInput modes.

Make sure you're binding the buttons, or you can load the predefined xbox pad profile.
