### ISSUE TITLE
Duckstation QT on Windows always freezes when I try to add a Game Directory

### ISSUE THREAD

**Issue by tifaucz** [stenzek/duckstation#1752]
**Description of the issue / bug**
Duckstation freezes when trying to add a game directory.

**Steps to reproduce**
Downloaded the latest windows version, open the qt exe file and clicking on Settings -> Add Game Directory

**Hardware/software**
Windows 10 x64
Radeon RX 560

**Emulator version**
0.1-3431-gc3d2999d

**Comment by stenzek** [comment]
I've seen a couple of people with this issue now. It's not an issue with the emulator but some third party shell extension conflicting with Qt.  Turn that off and it'll probably work, or you can add through nogui as a workaround.

In the other user's case it was a DLL named "oldnewexplorer64.dll".

**Comment by tifaucz** [comment]
Same happens with System -> Start Disc
