### ISSUE TITLE
Shortcut not being Assign (BigDuckMode)

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#1754]
**Game details**
Not related

**Description of the issue / bug**

Keys aren't being assigned in quick menu.

**Steps to reproduce**
Open quick menu > it will ask for a key counter starts > trey to press any key and nothing will be assgined (Keyboard only)

And if a key is already assigned. 

![unknown.png](https://user-images.githubusercontent.com/43047877/110241224-6edafa80-7f2e-11eb-8c70-7df1faa1973e.png)

**Enhancements information**
Not related

**Hardware/software**
Yet not related

**Emulator version**
Preview / Stable

**Additional context**
None

**Comment by stenzek** [comment]
Are you sure? This was working when I last checked (only a few hours ago)

**Comment by andercard0** [comment]
> Are you sure? This was working when I last checked (only a few hours ago)

![image](https://user-images.githubusercontent.com/43047877/110241528-1573cb00-7f30-11eb-8880-af762ecfdc0a.png)

yes, as you can see i have a updated version and just testing now, not working

**Comment by andercard0** [comment]
Fixed in

"commit/c3d2999d7871"

Thank You!
