### ISSUE TITLE
Failed to initialize OpenGl renderer on Mali t624/628

### ISSUE THREAD

**Issue by PolishMolish** [stenzek/duckstation#1758]
Pretty much what the title says, here is a log attached
https://pastebin.com/dUQ1tc6a

**Comment by stenzek** [comment]
Strange driver. GLES3.1 but no support for storage blocks in the fragment shader.

https://github.com/stenzek/duckstation/commit/a559139105d8d547220965b5c216d007563d5c7e adds a check and uses the fallback path in such a case. But it won't be accurate with mask bit handling, and will cause rendering errors in some games (e.g. Silent Hill).
