### ISSUE TITLE
Implement HostDisplay::GetHostRefreshRate() on Linux

### ISSUE THREAD

**Issue by vanfanel** [stenzek/duckstation#1760]
**Game details**
Any game that runs at 60fps with sidescrolling graphics, like Rayman [SLUS-00005] or Arcade Gears: Wonder 3 [SLPS-0092]

**Description of the issue / bug**
There's a **periodic video stutter/desynchronization: possibly a single-frame skip/missing, noticeable in continuous scrolling movement.**

**Controller Troubleshoot Report**
I am using the SDL backend for controllers.
No processes on my system stealing CPU time. Using Debian/Ubuntu/Raspberry Pi OS here, both in aarch64 and x86_64 architectures.

**Steps to reproduce**
For example:
-In Rayman: grab a long rope, and go up and down continuously, thus causing a continuous and uninterrupted movement. You will see a "skip" or "frame desync" every once in a while, not present on real HW.
-In Wonder 3: let the demo mode play and look at the scrolling movement of the THREE WONDERS color text in big letters. You will see a "skip" or "frame desync" during that sequence that does not happen in real HW. NOTE that, since it's a framerate control problem, it will happen on that sequence sometimes only, NOT always.
-The problem of course happens in any game running at 60fps but is easily noticed in 2D scrolling games (like the mentioned ones or SOTN). Framerate issues are not that noticeable in 3D games.

**Enhancements information**
No enhancements turned on.

**Hardware/software**
This is how I build Duckstation:
`cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_CHEEVOS=OFF -DENABLE_DISCORD_PRESENCE=OFF -DUSE_X11=OFF -DUSE_DRMKMS=ON -DBUILD_NOGUI_FRONTEND=ON -DBUILD_QT_FRONTEND=OFF -DBUILD_SDL_FRONTEND=OFF -DHAVE_EGL=ON ..
`
Every HW configuration I have at hand (all running different GNU/Linux distros, with different GPUs and CPUs) shows the same issue. The issue is present in VULKAN, OpenGL and Software renderer.
This is not CPU, GPU or emulation problem: this is clearly a framerate control problem.

**Emulator version**
Latest GIT (I `git pull` and build everytime I build, at least 1 time per week).

**Additional context**

**My guess is that there's a small mismatch between the emulated PSX framerate and the host's videomode vblank period.
That's what the "Sync to host refresh rate" option should fix, so of course I have enabled it along with vsync and audio resampling, but it simply doesn't seem to do anything.
Note that the reported refresh rates on the Duckstation menu are rounded: for example, I see "1366x768@60.000000" or "1280x720@60.00000", but video modes don't have exact 60.000000Hz refresh rates.
If DuckStation is using these rounded refresh rate values as host-side framerates, that could be the problem (just an speculation).** 

I have also played with any other framerate control options, and no option corrects this.

This defect is not present on the Libretro port, but RetroArch (the Libretro frontend) does detect the exact physical video modes framerate.

**Suggestion**
Since **my guess is that you are using the refresh rates reported by libDRM, and these rates are rounded**, the only way to get the precise refresh rates would be to have a video option for **actual framerate detection based on the number of vblanks per second: after a certain number of samples, deviation should be low.
This is what RetroArch does in SETTINGS->VIDEO->OUTPUT->ESTIMATED SCREEN REFRESH.**
So a similar tool/option would, in theory, get an exact refresh rate and avoid those stutters. 

**Additional note**
This kind of visual problem can go undetected by most people, and even those who can see a single-frame stutter need a continuous long sequence of correct frames to detect it: it doesn't mean the problem is not there.

**Comment by stenzek** [comment]
This option is not implemented in Linux yet.

**Comment by vanfanel** [comment]
@stenzek Oh sorry!
So it's still not implemented on NOGUI/BigDuck mode either?

**Comment by stenzek** [comment]
It is implemented in nogui, just only on Windows and Android (it's shared code with all frontends).

**Comment by vanfanel** [comment]
@stenzek Any news on this? This is the last step towards perfection on the NOGUI builds on GNU/Linux :)

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/924756860ef074b9b16d2cb6958e4bbd3225f565

Haven't tested on an ARM SBC, but seems fine on a desktop with an AMD GPU for both X11 and gbm/drm/kms.

**Comment by stenzek** [comment]
> Note that the reported refresh rates on the Duckstation menu are rounded: for example, I see "1366x768@60.000000" or "1280x720@60.00000", but video modes don't have exact 60.000000Hz refresh rates.

**Comment by vanfanel** [comment]
@stenzek Whoa!! So nice!! I have been waiting to see this for .. ehm... weeks! But I was looking at the commits every single day, waiting for it to happen, and it has happened! Thanks!

I will test ASAP (when I get back home and can do a proper build) and report!

**Comment by vanfanel** [comment]
@stenzek I have been doing tests with 240p test suite, and scroll movement is now perfect with Vulkan when "Sync to host refresh rate" is active. So it's fixed now, games move as they should :)

However, a small question: pressing ESC when building without SDL2 suppor (EVDEV for input) won't do anything, thus keeping me trapped in emulation until I forcefully reboot the machine. I have looked at the hotkey settings and nothing seems to allow me to configure the MENU key. What am I missing here?
This is (probably) a very stupid omission on my side, so opening a new issue for it doesn't seem adequate.
