### ISSUE TITLE
All but two of my games get added to the game list...

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [stenzek/duckstation#1763]
**Game details**
SLPM-87056 World Soccer Winning Eleven 2002 (Japan)
SLPM-86291 World Soccer Jikkyou Winning Eleven 4 (Japan)

**Description of the issue / bug**
All of my games under my game folder get detected when I add the folder to the **Game List Setting** except the two I mentioned above...Is this a bug or am I doing something wrong ? 

The format is like: 

F:\PS1 ISO\Game1_Folder\\(.bin & .cue)
F:\PS1 ISO\Game2_Folder\\(.bin & .cue)
F:\PS1 ISO\Game3_Folder\\(.bin & .cue)
.
.
.

I add "PS1 ISO" to the **Game List Setting** and all games are detected except the two I mentioned at the beginning...

I tried and put the two in a different folder(not under **F:\PS1 ISO\**) added that folder to the **Game List Setting** but they just dont wanna get added to the list....Am I doing something wrong ?

**Comment by stenzek** [comment]
What format are these games in? Do they have cuesheets?

**Comment by ReductoAdAbsurdum** [comment]
All have CUE files

**Comment by stenzek** [comment]
Are the dumps valid? Do the filenames in the cuesheets match the bin files? Check the log for any errors with those files: https://github.com/stenzek/duckstation/wiki/Enabling-Logging

**Comment by ReductoAdAbsurdum** [comment]
I just realized the dumps have errors in their cue sheets.....many thanks...
