### ISSUE TITLE
[Bug] Star Wars - Rebel Assault II - The Hidden Empire (Spain)

### ISSUE THREAD

**Issue by fox140cv** [stenzek/duckstation#1766]
Star Wars - Rebel Assault II - The Hidden Empire (Spain) (Disc 1)
CRC: 3A42C89C
Redump verified

A few seconds after starting a new game the image freezes but the sound continues and you can continue playing with the frozen image, I have tried D3D11, Opengl and Vulkan, all 3 failing and without improvements.

Emulator version
0.1-3431 latest
0.1-3505 preview

**Comment by foxsevent** [comment]
Google SBI file, get one for your game name it same as your rom and put it in the same folder.

**Comment by fox140cv** [comment]
This game does not require an .sbi file, plus duckstation reports LibCrypt protection. However I have been looking just in case and I have not found anything, thanks for commenting

**Comment by foxsevent** [comment]
> This game does not require an .sbi file, plus duckstation reports LibCrypt protection. However I have been looking just in case and I have not found anything, thanks for commenting

Apologises, it's a very common issue with PAL games Libcrypt and your issue did sound like an Libcrypt issue, but you are correct, tested my NTSC copy and same issue, upon starting any level and skipping the cut scene it's just a black screen with just the audion playing.

All enhancements disabled, interpreter, ICACHE and recompiler.

**Comment by Phantasm90** [comment]
I've tested the USA version with the passcode that unlocks every level, and the few chapters that can be played are 2, 11 and 12, every other chapter only display a black screen

**Comment by josebraund** [comment]
Hello good morning, the same problem happens to me I have the latest version 0.1 3945
You can see the cinematics and the menu before playing, in the first mission the spaceships are not seen. but if you listen to the dialogues and the music.

**Comment by foxsevent** [comment]
This was mentioned here somewhere but I can't find so I post it here as well.

Temporary solution is to set DMA Max Slice Ticks to 100 and DMA Halt Ticks to 100.
You can do this in advanced tab or in per game settings computability tab.

**Comment by josebraund** [comment]
excellent temporary solution , thanks you @foxsevent

**Comment by stenzek** [comment]
As best I can tell, fixed with https://github.com/stenzek/duckstation/commit/6543cc42d3558ce10c3ff58f3646e3c3d4ba834f (you will need to rescan)
