### ISSUE TITLE
Missing .qm translation file

### ISSUE THREAD

**Issue by DarkSwan86** [stenzek/duckstation#1767]
Hi @stenzek ,

i'm building from AUR the very latest duckstation and when i open the emulator, this warning appear
![duck2error](https://user-images.githubusercontent.com/24975273/110356014-1abd3c80-803a-11eb-8505-a093d26837a1.png)

Only recently appeared but i can't pinpoint exactly when it started. 

Thanks!

**Comment by ggrtk** [comment]
If you're using the duckstation-git package from AUR, it doesn't look like it copies any of the necessary files from the `duckstation/data` folder. A recent change added the requirement for duckstation-qt_en, but you might have seen this sort of error for other language settings on earlier package builds. Please check with the maintainer of the AUR, as we're not in charge of any third-party package distribution.

Alternatively, the duckstation-qt-bin AUR package seems to handle this properly, so maybe give that one a try.

**Comment by stenzek** [comment]
Closing as this is a packaging problem, and I have no control over it. I'd recommend using the appimage or building from source yourself.

**Comment by DarkSwan86** [comment]
Now the AUR package is fixed, this error is now fixed.
