### ISSUE TITLE
Taking screenshots causes the emulator to stutter 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#177]
As you can see taking a screenshot causes a massive time loss. 

![Capture](https://user-images.githubusercontent.com/31968468/77689069-2e23f300-6ff5-11ea-9744-4a1b36f78400.PNG)

**Comment by forz0i** [comment]
(mortal kombat special forces prototype)    Plase fix cd  crash  in
game  part 1
[image: Capture d’écran 26-03-2020 21.34.01.png]

**Comment by forz0i** [comment]
mortal kombat special forces prototype
Plase fix cd  crash  in part 1
[image: Capture d’écran 26-03-2020 21.34.01.png]

**Comment by deadair3210** [comment]
@forz0i don't take over other people's issue threads please

**Comment by stenzek** [comment]
This is likely because you're using a high resolution scale. Compressing the image takes time. It can be threaded out I guess.
