### ISSUE TITLE
Support webp format for covers

### ISSUE THREAD

**Issue by harlayzhou** [stenzek/duckstation#1774]
It will be wondfull if support webp format.

**Comment by RinMaru** [comment]
What's the advantage over png?

**Comment by harlayzhou** [comment]
of course more smaller in same quality.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/e10271e18ba396faab23d8eb446d33d7001c2098

This will only work for Qt and Android, not nogui. Nogui support would require pulling in a webp decoder as a dependency, and I'm not convinced it's worthwhile at this point.
