### ISSUE TITLE
Launching via command line doesn't seem to generate initial settings.ini

### ISSUE THREAD

**Issue by dankcushions** [stenzek/duckstation#1779]
context: trying to create a RetroPie build script, which will build and configure emulators to be launched via an external game launcher. ie, it will not be run directly, only ever booting straight into a game.

`./duckstation-nogui`
creates `~/.local/share/duckstation/settings.ini` 👍 

`./duckstation-nogui  -- game.foo`
doesn't create `~/.local/share/duckstation/settings.ini` 👎 

`./duckstation-nogui -portable`
creates `settings.ini` in same path as binary 👍 

`./duckstation-nogui -portable -- game.foo`
doesn't create `settings.ini` in same path as binary 👎 

`./duckstation-nogui -portable -settings /blah/duckstation.ini -- game.foo`
doesn't create `/blah/duckstation.ini` 👎 

the latter is what retropie would use, ideally, so it can stick the config file in a specific path, rather than symlinking etc.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/7241876cc70a4d7c2170524515959689273c3f2b
