### ISSUE TITLE
Drag & Drop to load a game.

### ISSUE THREAD

**Issue by ImSpecial** [stenzek/duckstation#1781]
Pretty self explanatory really, can something like this be added? Drag and drop a supported format like, CHD file, onto the window of DuckStation = load game.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/4685d66a2b53f5efeaa904b54ea1a46dffe53830

**Comment by ImSpecial** [comment]
As a bit of a ROM hacker I thank you so much! I was doing some testing with a hack I'm doing, where the images were just temp "tests" files and it was a pain in a half to constant having to navigate towards the patched game each time.
