### ISSUE TITLE
Can't open per game settings during gameplay

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1784]
Trying to play Battle Arena Toshinden which needs per game settings to not run super speed. They're not being applied by default when I start the game and I can't open the menu to turn them on during gameplay. I can only do it by right clicking in the game list. Using the very latest preview version of Duck. 

![1615287836216](https://user-images.githubusercontent.com/77198254/110653863-bead1080-8211-11eb-8356-7af6456ee68b.png)

And yes per game settings are one

![Capture](https://user-images.githubusercontent.com/77198254/110654539-53b00980-8212-11eb-97dc-1d8cfb8bf9b3.PNG)

**Comment by stenzek** [comment]
No issues opening it here, even tried a clean install.

**Comment by Kurayami7** [comment]
What could I be doing wrong then? I completely scrubbed duck off my computer, download a fresh version, I didn't touch a single setting.

**Comment by stenzek** [comment]
Are you starting the game directly instead of from the game list? Setting per-game settings requires the disc to be scanned and in the list.

**Comment by Kurayami7** [comment]
That's it. If I pick it from the list, per game settings work, if I start the game directly from the BIN/CUE it doesn't. Even if I've already started it from the list once I still can't open per game settings when starting from BIN/CUE. Is this explained or mentioned anywhere?

**Comment by stenzek** [comment]
No, it's not. But I probably should parse the compatibility settings anyway in such a case, since some of them are critical for the games to function.
