### ISSUE TITLE
Blaster Master - Blasting Again (USA) [major crash on Duckstation]

### ISSUE THREAD

**Issue by Cibomatto2002** [stenzek/duckstation#1789]
I could not reopen this issue so I had to make another one it's the same problem but not it will crash in on new area.using latest development build.
Recompiler (Fastest)

[crash.txt](https://github.com/stenzek/duckstation/files/6124376/crash.txt)

[crash.zip](https://github.com/stenzek/duckstation/files/6124381/crash.zip)

  83.7618] I/Bus: RAM is 2097152 bytes at 0000021CF6E60000
[   83.7633] I/GPUBackend: GPU thread started.
[   83.7638] I/Bus: Fastmem base: 0000021CF7610000
[   83.7690] I/MemoryCard: Loaded memory card from C:\Users\Jason\Documents\DuckStation\memcards\Blaster Master - Blasting Again (USA)_1.mcd
[   83.7855] I/CDROM: Inserting new media, disc region: NTSC-U, console region: NTSC-U
[   83.7893] I/CommonHostInterface: Target speed: 100.000000%
[   83.7898] I/CommonHostInterface: Syncing to audio and video
[   83.7903] I/CommonHostInterface: Max display fps: 0.000000 (skipping displaying frames when needed)
[   83.7908] I/CommonHostInterface: Audio input sample rate: 44100 hz
[   83.7913] I/CDROM: Removing CD...
[   83.7916] I/System: Re-using same media 'D:\Roms\Playstation 1 ROMS\Blaster Master - Blasting Again (USA).cue'
[   83.7920] I/CDROM: Inserting new media, disc region: NTSC-U, console region: NTSC-U
[   83.7923] I/MemoryCard: Loaded memory card from C:\Users\Jason\Documents\DuckStation\memcards\Blaster Master - Blasting Again (USA)_1.mcd
[   83.7997] W(DoState): Skipping loading memory card 1 from save state.
[   92.5148] W(DoEXP2Access): BIOS POST status: 0F
[   92.5154] W(DoEXP2Access): BIOS POST status: 0E
[   92.5158] W(DoEXP2Access): BIOS POST status: 01
[   92.5162] W(DoEXP2Access): BIOS POST status: 02
[   92.5165] W(DoEXP2Access): BIOS POST status: 03
[   92.5177] W(DoEXP2Access): BIOS POST status: 04
[   92.5196] W(DoEXP2Access): BIOS POST status: 05
[   92.5203] W(DoEXP2Access): BIOS POST status: 06
[   92.5223] W(DoEXP2Access): BIOS POST status: 07
[   98.2596] W(DoEXP2Access): BIOS POST status: 00
[   98.2771] W(DoEXP2Access): BIOS POST status: 01
[   98.3097] W(DoEXP2Access): BIOS POST status: 02
[   98.4604] W(DoEXP2Access): BIOS POST status: 00
[  102.0714] W(DoEXP2Access): BIOS POST status: 05
[  102.0719] W(DoEXP2Access): BIOS POST status: 08
[  102.5896] W(DoEXP2Access): BIOS POST status: 09
[  104.8978] E(WriteRegister): Unknown SPU register write: offset 0x19C (address 0x1F801D9C) value 0x0000
[  104.8983] E(WriteRegister): Unknown SPU register write: offset 0x19E (address 0x1F801D9E) value 0x0000
[  109.1266] I/MemoryCard: Writing memory card sector 63
[  112.8887] W(ExecuteCommand): CDROM Pause command while seeking - updating position
[  122.2847] I/MemoryCard: Writing memory card sector 63
[  127.2840] I/MemoryCard: Saved memory card to 'C:\Users\Jason\Documents\DuckStation\memcards\Blaster Master - Blasting Again (USA)_1.mcd'
[  135.3912] W(ExecuteCommand): CDROM Pause command while seeking - updating position
[  141.8780] W(ExecuteCommand): CDROM Pause command while seeking - updating position
[  147.9655] W(ExecuteCommand): CDROM Pause command while seeking - updating position
[  158.3480] I/MemoryCard: Writing memory card sector 63
[  159.6024] E(WriteRegister): Unknown SPU register write: offset 0x19C (address 0x1F801D9C) value 0x0000
[  159.6029] E(WriteRegister): Unknown SPU register write: offset 0x19E (address 0x1F801D9E) value 0x0000
[  163.3477] I/MemoryCard: Saved memory card to 'C:\Users\Jason\Documents\DuckStation\memcards\Blaster Master - Blasting Again (USA)_1.mcd'
Panic triggered: 'Trying to get branch target of indirect or invalid branch' in function CPU::GetBranchInstructionTarget (D:\a\duckstation\duckstation\src\core\cpu_types.cpp:117)

**Comment by stenzek** [comment]
This fix isn't in the development build yet. Please re-test on the preview build.

**Comment by stenzek** [comment]
Closing as this was not tested on the preview build. If the crash still occurs on the preview build, I will re-open and investigate.

**Comment by Cibomatto2002** [comment]
it seems to be working sorry about that I thought the Latest Development Build was newer than the  preview build and it would  have the fix.
