### ISSUE TITLE
Most of the audio in Machine Head (USA) only plays in one ear of my headphones

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#179]
Sound effects are fine but Music and dialogue only play in the left ear.

**Comment by stenzek** [comment]
This might be a bug in the game itself. It seems to configure the CD volume matrix so that both left/right channels from the CD audio are output to the left channel of the SPU. Have you tested/confirmed on (preferably) console or another emulator?

**Comment by kurayami6** [comment]
Just tried it in Beetle PSX and got the same problem. I'll close this but I hope it really is a problem with the game itself and not a case of no emulator being able to play it correctly.
