### ISSUE TITLE
Doesn't load cheat correctly for game with just one cheat

### ISSUE THREAD

**Issue by PugsyMAME** [stenzek/duckstation#1791]
When loading a game with a single cheat from chtdb.txt it will load cheats from the following game (including numbers from the header?). If it has more than one cheat it will load fine.

Example for the game a-train:-

; [ A-Train - Trains, Power, Money (USA) (1996) (Maxis) {SLUS-00003} <atrain> ]
:SLUS-00003
#Infinite Money
900A6230 77359400

; [ ATV Mania (USA) (2003) (Gotham Games) {SLUS-01545} <atvmania> ]
:SLUS-01545
#Time Always 0:00
8007704C 0000
etc

will load as:-

#Infinite Money
900A6230 77359400
00001545 0000000A
#Time Always 0:00
8007704C 0000
etc

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/6fa245ed613024db9136255a67fbe463075ffae1
