### ISSUE TITLE
[Vulkan] Tony Hawk Pro Skater 2 Screen Flickering

### ISSUE THREAD

**Issue by waspennator** [stenzek/duckstation#1793]
**Game Details**
[Serial Code, Region]
Tony Hawk Pro Skater 2 (USA) SLUS-01066
Redump verified

**Description of the issue / bug**
Going into the skater select screen with Vulkan as the graphic backend causes weird screen flickering, Tested it with the other 3 graphic backends and it only seems to happen with Vulkan.

**Steps to reproduce**
Start the game with Vulkan as the backend, then pick career or free skate and go into the skater select screen.
![Duckstation glitch](https://user-images.githubusercontent.com/78768499/111018864-d0f58e80-8378-11eb-8abe-ca0e8d9c8804.png)

**Enhancements information**
None.

**Hardware/software**
i5 6600k
Geforce GTX 1070
Windows 10
Vulkan

**Emulator version**
0.1-3534-Preview

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/c062cc2c26fea2dfdec7bd9110facbf9416d7779 (preview build).

If it's still happening, please let me know.

**Comment by waspennator** [comment]
Booted up Duckstation to check and yep, seems like that fixed the issue, thanks again for doing this.
