### ISSUE TITLE
Controller support not implemented in Qt frontend

### ISSUE THREAD

**Issue by Catcher40** [stenzek/duckstation#18]
If i launch the emulator via sdl and then run a game the controller works fine but if i try launching a game using the QT gui only the keyboard works the controller does nothing at all.

**Comment by stenzek** [comment]
Known issue. It is not implemented yet.

**Comment by Catcher40** [comment]
Sorry i did have a look to see if it was already known but couldnt find anything think i'm going blind in my old age. Not supposed to say it here but thanks for the emulator, its alot easier to use than certain others that need 57 plugins to be downloaded and configured.

**Comment by stenzek** [comment]
All good, I thought I mentioned this in the readme but apparently not. I'll leave the issue open for visibility.

**Comment by stenzek** [comment]
Implemented in latest master.

The only thing still missing is analog axis binding for the dualshock controller.

**Comment by stenzek** [comment]
Axis binding is implemented as of https://github.com/stenzek/duckstation/commit/262331504fb4dc2414bdd1b4a3e6e1dab8802e04
