### ISSUE TITLE
Mortal Kombat: Special Forces (May 11, 1999 prototype) randomly crashes with error message

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#180]
![Capture](https://user-images.githubusercontent.com/31968468/77705825-cd0c1780-7014-11ea-8175-6dde9b29d77c.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/77705837-d4cbbc00-7014-11ea-962e-7302752a0ef5.PNG)

**Comment by stenzek** [comment]
This is likely also fixed by https://github.com/stenzek/duckstation/commit/5b389ae13d19dfc3a202501a3c2b8828e79fb6a0

**Comment by kurayami6** [comment]
It now crashes with a different error message. Should I make a separate issue report or do you want to reopen this one?

![Capture](https://user-images.githubusercontent.com/31968468/81373866-19cd2d00-9141-11ea-8963-30e37ad51989.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/81373882-22256800-9141-11ea-8cbe-d1da625feb56.PNG)

**Comment by stenzek** [comment]
Hmm, that.. sh

**Comment by stenzek** [comment]
Try the latest push, see if you get a message about seeking to the end of the disc.

I don't really have much interest in getting these prototype games to work, but in this case some of my earlier hardware tests did show that the drive could seek to the lead-out area, just not read from it.

**Comment by kurayami6** [comment]
![Capture](https://user-images.githubusercontent.com/31968468/81374902-ab3d9e80-9143-11ea-9675-003b00edf7f8.PNG)

**Comment by stenzek** [comment]
Are there multiple tracks? Those sector numbers are too high for that file.

**Comment by kurayami6** [comment]
It's one bin file and one cue.

![Capture](https://user-images.githubusercontent.com/31968468/81375758-88ac8500-9145-11ea-94ab-7fe24e75c43a.PNG)

**Comment by kurayami6** [comment]
It's now crashing with a different error message. At least progress is being made.

![Capture](https://user-images.githubusercontent.com/31968468/81377013-f5c11a00-9147-11ea-8f19-96f1d1344bc6.PNG)

**Comment by stenzek** [comment]
Mode 170/submode 0xAA means it's definitely reading the lead-out area.. the question is why it's not stopping before then...

**Comment by stenzek** [comment]
Okay, I managed to reproduce the panic by setting up a fake disc read scenario. Give the latest push a try.

**Comment by kurayami6** [comment]
Played for about half an hour and didn't get any crashes. Looks like this is fixed. Well done.
