### ISSUE TITLE
System failed to boot

### ISSUE THREAD

**Issue by zenzaiwarrior** [stenzek/duckstation#1805]
Hello, I'm rather inexperienced with using emulators. I've been using Duckstation for a while without a problem but I recently tried to resume a save state and I received two error messages. One saying "Failed to open CD image from save state" and the other reading "System failed to boot. The log may contain more information." How can I resume my game? I tried loading the game via "start disc" in the system options but no luck.

**Comment by stenzek** [comment]
Please do not use the issue tracker for support questions. For the log, see https://github.com/stenzek/duckstation/wiki/Enabling-Logging

**Comment by zenzaiwarrior** [comment]
Hi Connor,

Sorry to be a bother but I got stuck on sending a copy of the
duckstation.log in my user directory. I don't know how to and I searched
for an answer on how to but came up short.  As stated, I really don't have
experience when it comes to this. I was able to take a screenshot of the
log. I've attached the screenshot to this email. Sorry again for the bother.

Best,
Owen
