### ISSUE TITLE
Cheevos View Profile...

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#1809]
**Game details**
Not Related

**Description of the issue / bug**
View profile... option only available in duckstation Dev version not Preview

![image](https://user-images.githubusercontent.com/43047877/111084531-9cf1a900-84f1-11eb-9b76-fe0b68c789b5.png)

**Controller Troubleshoot Report**
Not Related

**Steps to reproduce**
Settings > Achievements Settings > (Account) press: Login.. After logged in > View Profile... option will not be accessible 

**Enhancements information**
Not Related

**Hardware/software**
Not related 

**Emulator version**
Preview 
![image](https://user-images.githubusercontent.com/43047877/111084543-ada21f00-84f1-11eb-944b-11c50dc79620.png)

**Additional context**
Not a big of a deal but I'd like to report even so!
Login Cheevo's screen is being squished while moving, to reproduce: 

Click in Login... > try to move the window a bit to the side.

![image](https://user-images.githubusercontent.com/43047877/111084573-d32f2880-84f1-11eb-8b30-9b58bb89279c.png)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/3dc53dd93c2f7ab59658c181f6e18b5086177d35
