### ISSUE TITLE
Option to generate new memory cards.

### ISSUE THREAD

**Issue by Darkwolf1515** [stenzek/duckstation#1815]
**Is your feature request related to a problem? Please describe.**
Seemingly, theres no way to create new shared memory cards, not one I can find at least, would be useful for accidental deletions and the such.

**Describe the solution you'd like**
Just a button in the memory card options to create a new shared memory card, and if one exists already, make it more clear.

**Describe alternatives you've considered**
I suppose duplicating the card that comes with it would work, but that depends on you still having it.

**Comment by Darkwolf1515** [comment]
Nevermind, a bit more tinkering figured it out, made the directory not depend on the drive and erased the old one, a new one was instantly generated.

**Comment by stenzek** [comment]
The memory card editor has a "new" button.

**Comment by Darkwolf1515** [comment]
> The memory card editor has a "new" button.

Now i see it, although white on white is very hard to see in my defense.
