### ISSUE TITLE
Visual bug with enabling/disabling cheats in any game

### ISSUE THREAD

**Issue by tycooko** [stenzek/duckstation#1817]
1. Enabling/disabling cheats from "Tools --> Cheat manager" doesn't trigger a text confirmation on screen (only enabling/disabling them from "Cheats --> Enabled Cheats" does), although the cheats are indeed enabled/disabled.
2. Disabling (and only disabling: no idea why) cheats from "Cheats --> Enabled Cheats" doesn't uncheck the corresponding checkboxes inside "Tools --> Cheat manager", although the cheats are indeed disabled.

I've already confirmed that this happens in both the Windows and macOS version with the latest update.

**Comment by stenzek** [comment]
Working as intended. The cheat manager is separate to the menu or full screen UI cheat menu. I only have the message on the pop out menu because it closes after clicking (Qt restriction), so the user can't see any confirmation otherwise. With the cheat manager, the checkbox is obviously checked.

**Comment by tycooko** [comment]
I understand, but that's only the first of the two issues. The other one is that the codes stay checked in the cheat manager even when they've been disabled (outside).

**Comment by stenzek** [comment]
Again, working as intended. The core and UI are decoupled. It's simple, don't use both, only use one.

The pop out menu is redundant with the cheat manager and full screen UI anyway, and it doesn't scale well to large numbers of cheats. This is where having analytics would be good - I could drop it if nobody used it.

**Comment by tycooko** [comment]
I understand the reason why this works this way, but it seems so "wrong" to me because, when I enter the cheat manager and something is checked, I want to trust the information the app is giving me and expect that cheat to be on. 
The fact that, for the very valid reason you've pointed out, the cheat manager basically displays erroneous information doesn't seem right.
On the other hand, I can't use one. I can't add or edit cheats in the UI menu and I'd rather not to go all the way to the cheat manager, check a cheat, and then close the cheat manager again just to activate one cheat (which is what the UI menu is particularly practical for).
Anyway, just my two cents. Still, it seems that "Cheats-->Apply cheats" is just the remainder of something that's not used anymore, right?

**Comment by stenzek** [comment]
Not arguing about it. That's the way I've decided to do things, you're welcome to change it and submit it, but otherwise it's my project, my call.

Apply cheats is oneshot cheats, i.e. once-off codes which don't activate every frame.
