### ISSUE TITLE
Stuck on Bios Screen [Android]

### ISSUE THREAD

**Issue by MakotoTheGray** [stenzek/duckstation#1818]
Greetings, I'm a new user of Duckstation, I already have the bios file on its designated place, and also the image game file as well. 

The program is capable of listing the game, which in this is case "Legend of Mana", but when I start it, all that it does is boot the bios itself. 

I'm not knowledgeable about Duckstation or emulators in general, so I decided to come here for help. 

Thank you in advance.

**Comment by stenzek** [comment]
Please don't use the issue tracker for support - that's what discussions and discord are for.

In this case make sure your dump is valid and you're not using a Japanese bios for US/PAL games - they include extra region checks.
