### ISSUE TITLE
Racingroovy VS (Japan) hangs on the opening logo for a very long time

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#182]
I actually timed it. It stays on this logo for 1 minute and 29 seconds before continuing. 

![SLPS-00417_2020-03-27_15-56-02](https://user-images.githubusercontent.com/31968468/77723230-f8f2c180-7043-11ea-91f7-487626257677.png)

**Comment by and468860** [comment]
have to use emulation speed  maximum emulator cpu  start

**Comment by stenzek** [comment]
Seems to be something to do with memory cards. Running with no cards inserted (currently not possible on master due to a bug) it boots after a few seconds.

**Comment by kurayami6** [comment]
As of the latest version it take about 55 seconds to get past the opening logo. So it's improved but still isn't fixed.

**Comment by kurayami6** [comment]
As of the latest version the game takes about 49 seconds to get past the opening logo with the memory card inserted, which matches real hardware.
