### ISSUE TITLE
Rumble with DS4 Windows

### ISSUE THREAD

**Issue by stephenespinal22** [stenzek/duckstation#1828]
I'm not seeing anyway to use the rumble using DS4 Windows. In controller settings when clicking rumble, it asks you to hit a key as if rumble was a button. Not seeing any documentation about how it is supposed to be set up.

**Comment by ggrtk** [comment]
"For rumble, press any button/axis on the controller you wish to send rumble to."

**Comment by stephenespinal22** [comment]
Doesn't seem to be working, it works when testing in DS4 Windows, Steam, and Pscx2

**Comment by stenzek** [comment]
Use the SDL controller interface, don't use Ds4windows. Works fine for me.
