### ISSUE TITLE
MegaMan Legends voice sounds cut off within the first second.

### ISSUE THREAD

**Issue by jayare5** [stenzek/duckstation#1835]
It can be found as soon as you start to play, you move forward a bit to trigger a message from Roll. 
She says "Wait a second!" 
but it sounds like "-clip- a second!"

Next message says "There should be a Reaverbot around there somewhere..."
but it sounds like "... should be a Reaverbot around there somewhere..."

I've found this issue in other emulators as well, so this has me a bit worried that it's going to be a difficult or impossible issue to deal with. I can also google search to find others complaining about this same issue as far back as around 2010 or so (in other emus of course) but I am using the latest version of Duckstation.

- SLUS-00603 MegaMan Legends (USA)
- Duckstation version 0.1-3600-g1e1d864e (dev)
- I'm using a Windows PC
- CPU: i5-10300H 
- GPU: NVIDIA GeForce RTX 2060 6GB
- Windows 10 
- Renderer: D3D11
- No settings were changed whatsoever, this happens with everything default.
- My copy of the game is supposed to be a clean dump, though I've made a disc image from my own copy which is good, but has the same issue.

**Comment by Kurayami7** [comment]
It's not specific to Mega Man. Off the top of my head, Tomb Raider, Clock Tower 2, Bounty Sword Double Edge, warriors of might and magic, all have the same problem where the game is silent for too long and misses the first bit of dialogue.

**Comment by jayare5** [comment]
Ahh I see! Never played those (on emulator at least).
Out of all the games I emulated, only Mega Man Legends 1 and 2 have given me that problem so I can see how it might appear in other games now too. Considering this, should I update my topic to just audio in general?

**Comment by Kurayami7** [comment]
I've already made issue reports for all the games I mentioned but keep this one open anyway.

**Comment by stenzek** [comment]
Likely different causes.

**Comment by stenzek** [comment]
Fixed with https://github.com/stenzek/duckstation/commit/4441bb1a91a8fa97b591c8488dc940e42ef58c4f

I only tested the first stage, if it's still happening elsewhere let me know and I'll re-open.

**Comment by jayare5** [comment]
Whoa that was fast!!!
I will be testing :) Thank you
