### ISSUE TITLE
quick menu is not opening/showing up

### ISSUE THREAD

**Issue by mickey66092** [stenzek/duckstation#1837]
quick menu is not showing up anymore, tried to set a new hotkey to it but it is still not opening.showing up, tried on another pc and it happens the same. few builds back it worked but since one of two last builds it broke the function to it,

**Comment by stenzek** [comment]
You did not fill out the template, so I can't help you.

For what it's worth, it works fine here. Make sure you have the fullscreen UI enabled in settings.
