### ISSUE TITLE
Tunguska - Legend of Faith (Europe) runs way too fast

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#184]
The character moves like he's in fast forward and the interact menu doesn't work, making it impossible to get past the first screen.

![SLES-03298_2020-03-28_08-45-56](https://user-images.githubusercontent.com/31968468/77803565-8b8d7200-70d1-11ea-8e1c-140880278ffe.png)

The log spams this constantly. The game is running so fast it got from 1000 to 15000 in just a few minutes. 

![Capture](https://user-images.githubusercontent.com/31968468/77803603-a06a0580-70d1-11ea-929a-b9eb61a566d8.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/77803616-a95ad700-70d1-11ea-97bf-6e0fbb7661ea.PNG)

**Comment by kurayami6** [comment]
Still an issue as of the latest version.

**Comment by stenzek** [comment]
Seems to be running around 25fps with the latest changes.
