### ISSUE TITLE
Question re horizontal offset

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#1849]
Not sure how relevant this is to just TR or other games, too, but...

Duckstation
![image](https://user-images.githubusercontent.com/4934209/111889037-1f8ed280-89e2-11eb-8d12-23b9699f4855.png)

ePSXe
![image](https://user-images.githubusercontent.com/4934209/111889040-2d445800-89e2-11eb-80d2-db40f55f8968.png)

PC
![image](https://user-images.githubusercontent.com/4934209/111889048-3af9dd80-89e2-11eb-8184-badc30fc9e4b.png)

Would appreciate your opinion if this is...
- likey just the way it is on PS1?
- at all to do with something specific to emulation?
- to do with video settings causing it?

Thanks

**Comment by stenzek** [comment]
Not a bug. Probably working as intended.

You can use the offsets in game properties to adjust the position, or some titles have an option ingame.
