### ISSUE TITLE
When using vulkan, the fast forward simulator will freeze from time to time?

### ISSUE THREAD

**Issue by kongmao45678** [stenzek/duckstation#1856]
After testing, fast forward the simulator, (without limiting the frame, press a few times and then stop, press again) will freeze at any time, there is sound, operation and control, but the screen is not moving.
After changing to D3D11, everything is normal.
Both the official version and the development version have this problem

**Comment by stenzek** [comment]
Please fill out the issue template. I have no such issue, except for a flicker when toggling in fullscreen mode. This is unavoidable because turning vsync on/off with Vulkan requires recreating the swap chain. As a workaround, you could try disabling vsync.
