### ISSUE TITLE
hide cursor option in nogui

### ISSUE THREAD

**Issue by Cloneg** [stenzek/duckstation#1857]
**Is your feature request related to a problem? Please describe.**
Cursor/mouse does not dissapear in nogui mode fullscreen.

**Describe the solution you'd like**
Add hide cursor option in nogui like in qt mode.

**Describe alternatives you've considered**
After you enter fullscreen mouse does not dissapear and stays there making it difficult (not even possible) to move it out of the screen with just a controller.

**Comment by Kzitold** [comment]
+1
Having the cursor in a random spot can throw off menu navigation if you're unlucky.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/92f9b90edc3c745d50a87467f6855072a104e7b1
