### ISSUE TITLE
Music is broken in Jellyfish - The Healing Friend (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#186]
This screen is supposed to have music but is completely silent.

![SLPS-02892_2020-03-28_23-33-06](https://user-images.githubusercontent.com/31968468/77823101-d9938b80-714c-11ea-9970-6c35b3a9b652.png)

This screen is supposed to have music but the only audio is a low beeping sound like an alarm clock.

![SLPS-02892_2020-03-28_23-33-20](https://user-images.githubusercontent.com/31968468/77823123-efa14c00-714c-11ea-9b11-6e71d706cef3.png)

Gameplay is the same. Just a constant beeping sound.

![SLPS-02892_2020-03-28_23-33-53](https://user-images.githubusercontent.com/31968468/77823132-fdef6800-714c-11ea-8949-8574823f0a9a.png)

**Comment by stenzek** [comment]
Should be fixed on latest master.

**Comment by kurayami6** [comment]
Fixed. Thanks.
