### ISSUE TITLE
D-pad position for touchscreen dual stick layout is off-screen in landscape

### ISSUE THREAD

**Issue by Valkmiro** [stenzek/duckstation#1860]
![Screenshot_20210323-140534_DuckStation](https://user-images.githubusercontent.com/81216878/112107522-a1991a00-8be1-11eb-8c3e-c74154aa51aa.png)

see the up dpad button is way above and cant edit it,can you fix this? thanks a lot for your hardwork man 👍

**Comment by Valkmiro** [comment]
any follow up? cant wait to use duckstation xD

**Comment by stenzek** [comment]
You can set your display size in settings to a lower value as a workaround, and it'll fit on screen.

**Comment by Valkmiro** [comment]
alright will try,should i use preview ones or latest ones?

**Comment by stenzek** [comment]
latest, or play store beta.

**Comment by Valkmiro** [comment]
![Screenshot_20210329-150332_DuckStation](https://user-images.githubusercontent.com/81216878/112805633-094adb80-90a0-11eb-814e-4474681f37b4.png)
the dpad is still off screen even i change the display,any clue?

**Comment by Valkmiro** [comment]
hopefully this will get fix soon,thanks ^o^

**Comment by stenzek** [comment]
The dpad will move as one whole button now, and you can now move/resize with the touchscreen controller settings.
