### ISSUE TITLE
Box downsampling causes flashing - Vulkan renderer, running on Wayland (sway wm) 

### ISSUE THREAD

**Issue by rigopoui** [stenzek/duckstation#1863]
**Game details**
FFIX, Crash 2, Spyro 3, probably more.
Crash team racing shows no flashing.

**Description of the issue / bug**
When using vulkan renderer and using box downsampling option, while not using any multisampling, and at >1x res, I get constant flashing. The game still runs at normal speed and responds to input, but the image only updates every 2-4 seconds while it is flashing. Going frame by frame, I get two black frames, then two frames of the (usually stuck) game image, then two black frames... etc

**Steps to reproduce**
Enable both >1x internal res and box downsampling on Vulkan renderer. In Crash 2 it doesn't occur right away, but does once you enter a level.

**Enhancements information**
Bug only occurs when box downsampling is enabled, internal res is more than 1x, and multisampling is disabled, on vulkan renderer. With enhancements disabled, it's fine.

**Hardware/software**
Intel Pentium N3700, intel integrated graphics, Arch Linux, wayland (sway wm).

**Emulator version**
0.1-3659-g4cd8c959
(freshly compiled `duckstation-git` package from the AUR)

**Additional context**
Happens both in wayland and xwayland.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/c502f8b0a6a499bb45a3b3a34fe3ced04a737566
