### ISSUE TITLE
[Bug] Cubeb audio backend resets process volume to max device volume on startup

### ISSUE THREAD

**Issue by DCxDemo** [stenzek/duckstation#1866]
**Description of the issue / bug**
Cubeb audio backend resets process volume to max device volume on startup. Doesn't happen with SDL.

**Steps to reproduce**
1. Select Cubeb backend
2. Run the game
3. Change emu process volume to 50%
4. Restart the emulator
5. Resume the game -> process volume is now at 100%. 

**Emulator version**
0.1-3659-g4cd8c959 (master)

**Additional context**
Mozilla has open tickets for similar problem in firefox, so I'm not sure whether it's the way Cubeb is initialized in emu, or actually Cubeb bug.
https://bugzilla.mozilla.org/show_bug.cgi?id=1407288
https://bugzilla.mozilla.org/show_bug.cgi?id=1474189

**Comment by stenzek** [comment]
This doesn't really sound like an emulator issue :/ it sets the volume after creating the cubeb device, if the OS is doing something funky, just use the in-emulator volume control?

**Comment by DCxDemo** [comment]
well, i'd recommend using SDL backend as there is no such issue.

this is probably why it happens, i guess it should be process volume here, rather than just full volume.
```
  u32 m_output_volume = FullVolume;
```
https://github.com/stenzek/duckstation/blob/master/src/common/audio_stream.h#L90

**Comment by stenzek** [comment]
Yes, the initial volume is max, but then `BootSystem()` calls `UpdateSpeedLimiterState()`, which sets the volume to the configured value: https://github.com/stenzek/duckstation/blob/4cd8c959cea31571f99cef0e1ef1a3e20cf6bdad/src/frontend-common/common_host_interface.cpp#L840

So, shouldn't be a problem, unless there's a race condition somewhere in cubeb where creating and then setting the volume soon other doesn't work.

**Comment by DCxDemo** [comment]
that's exactly what it does. cubeb's max volume is the selected limit for the device, not for specific application. so if application is manually set to 50% by user via OS controls, instead of using that level, you're reseting it back to the max or whatever level is saved in settings. here's what it should be and how it actually works with SDL.

![100p](https://user-images.githubusercontent.com/13422696/112353073-0f257300-8cd4-11eb-905a-2dfdf5660ba5.png)

**Comment by stenzek** [comment]
Are you sure? Adjusting the volume in duckstation has no effect on the system volume mixer for me.

**Comment by DCxDemo** [comment]
okay.
got nogui building. i think this flag fixes the behaviour:

```
params.prefs = CUBEB_STREAM_PREF_NONE;
```
to
```
params.prefs = CUBEB_STREAM_PREF_PERSIST;
```
https://github.com/stenzek/duckstation/blob/master/src/frontend-common/cubeb_audio_stream.cpp#L46

```
  CUBEB_STREAM_PREF_PERSIST = 0x10, /**< Request that the volume and mute settings
                                         should persist across restarts of the stream
                                         and/or application. May not be honored for
                                         all backends and platforms. */
```

https://github.com/mozilla/cubeb/blob/master/include/cubeb/cubeb.h#L241

**Comment by ggrtk** [comment]
It's somewhat unintuitive that we need to manually set `CUBEB_STREAM_PREF_PERSIST`, which is only being used by Cubeb's WASAPI backend, to get the default IAudioClient behavior (see https://docs.microsoft.com/en-us/windows/win32/coreaudio/audclnt-streamflags-xxx-constants#remarks). It looks like this flag was added on behalf of Dolphin a couple of months ago, but Cubeb's defaults remained the same. I'll see if this is something that is possible for the maintainers to change upstream, since this seems to be the opposite of expected behavior.
