### ISSUE TITLE
[PC] PS2 Controller Issue

### ISSUE THREAD

**Issue by Synck667** [stenzek/duckstation#1867]
Greetings. I would like to report a controller issue.

So basically I use ps2 controller with adapter and it's usually recognized as ps3 controller by any emulator I use. Controls are usually set to DirectInput mode and duckstation seems to not register up-right, up-left, down-right and down-left on d-pad while playing any game. In SDL mode d-pad works without problems but R1 and L1 don't function (actual buttons, cannot bind them to anything in controller settings). So basically i get this issue only in Duckstation, the controller is 100% functional.

If you can find the way to fix this issue that would be really nice. I'm willing to answer other questions if needed.

Kind Regards.

**Comment by ggrtk** [comment]
Try setting up a custom SDL controller mapping with the instructions here: https://github.com/stenzek/duckstation#sdl-game-controller-database. A lot of controllers and adapters try to pass themselves off as DualShock 3s but mess something up along the way, and SDL can't handle all of these cases.

**Comment by stenzek** [comment]
Yeah, seems like a game controller db issue.

I've added diagonal support in the DInput wrapper in https://github.com/stenzek/duckstation/commit/f1fb7383b7e3f542fdb9cf77c3fa2570562e9c3b.

**Comment by Synck667** [comment]
It works now. Thanks.
