### ISSUE TITLE
Retry failed achievement unlock requests

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#1869]
If not to much trouble and if possible to have a sync success notification when cheevos are unlocked like a small green tick next to the cheevo popup?

I'm asking cause early on I have unlocked some cheevos only to a minute later get the cheevo award failed notification and in some games that minute is enough to save over your game and lock yourself out of said cheevo.

**Comment by RinMaru** [comment]
Would also be nice to scan all games and download the needed data instead of launching them individually

**Comment by stenzek** [comment]
I actually discussed this with one of the RA folks a while back, the result was storing achievement unlock data creates more potential problems than it solves, particularly with admin or user-initiated resets.

I'll leave this open as a reminder that I need to implement retrying if the initial request fails.

> Would also be nice to scan all games and download the needed data instead of launching them individually

This would spam the RA server, which I'd rather not do.

**Comment by stenzek** [comment]
Implemented in the rc_client switch https://github.com/stenzek/duckstation/commit/c773c763efc6c201bb4474f8aebc0bdf30756927
