### ISSUE TITLE
Net Yaroze Demo (Europe) hangs on BIOS screen

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#187]
![Capture](https://user-images.githubusercontent.com/31968468/77833611-f8b50c00-7192-11ea-8aac-cf78887b89ee.PNG)

**Comment by stenzek** [comment]
This is kinda pointless since the serial port is not emulated...

**Comment by kurayami6** [comment]
Then emulate it? What do you mean it's pointless?

**Comment by stenzek** [comment]
Depends if this is the boot disc or some compilation disc for the Net Yaroze. If it's a boot disc, then you'd have to emulate the PC side of the system anyway. The only serial port emulation I was planning for the serial port was for multiple consoles with link capability, but that's a very low priority.

**Comment by stenzek** [comment]
Confirmed to also be broken on console - first stage loader exec's a second exe, which crashes (if I remember correctly) due to a bad header field.

**Comment by stenzek** [comment]
http://redump.org/disc/45854/

@Zet-sensei is it possible that this could be a bad dump? Redump has two dumpers listed, or perhaps this disc is *really* picky about the BIOS/console it runs on. Can't seem to find too much information online about it, only it was given out in a competition with 1000 copies (https://crimson-ceremony.net/demopals/samplers/index.php)

**Comment by Zet-sensei** [comment]
The disc dump is correct and verified.
The disc can only be launched on a Net Yaroze console and not a regular one.

It was in fact given to 1000 winners on a contest between Net Yaroze Members.

You can't use it without emulating the hardware & having a dump from a Net Yaroze Memory card.

**Comment by stenzek** [comment]
Thanks for the info! From what I can tell, it doesn't seem to even get to the point of polling for the access card, so I guess there must be some other difference with the Yaroze consoles.
