### ISSUE TITLE
[Feature Request] Sound Interpolation Options (Disable/Enable Interpolation)

### ISSUE THREAD

**Issue by Mohsen865** [stenzek/duckstation#1870]
On DuckStation, the sound playback (in most cases) feels like it's hummed and or it plays a very low sample of what you hear on the real hardware.

There's a SPU plugin for the older PSX emulators _(called P.E.Op.S. DSound Audio Driver 1.9)_ which has selectable interpolation methods... It has a crystal clear sound **compared** to other plugins and also the DuckStation. Especially when you choose the **"0: None"** interpolation option! The reverb also sounds fantastic using this plugin...

I think the audio could be greatly improved if these options were available on DuckStation.
![P E Op S  DSound PSX SPU Audio Driver 1 9](https://user-images.githubusercontent.com/12261908/112549016-c3a9bc80-8dda-11eb-8104-564d8533c98a.png)

### Edit: 
The discontinued **"pSX"** emulator also has a great sound as well...
![pSX 1 13 Final version](https://user-images.githubusercontent.com/12261908/112550994-d8d41a80-8ddd-11eb-87dc-9c70ed04dcb0.png)

**Comment by stenzek** [comment]
Sounds much worse without interpolation imo. Duckstation is an accurate emulator, don't really have any interest in such hacks.
