### ISSUE TITLE
Wallpapers for aspect ratios.

### ISSUE THREAD

**Issue by CristobalManga** [stenzek/duckstation#1872]
An original idea for emulators came to mind, although there are already a few examples.

I was playing metal slug xx on PSP, and an option appeared that said, sharp mode and wide mode.

In sharp mode the game returned to its aspect ratio and the game looked great and to cover the black edges it put a super cool wallpaper.

![image](https://user-images.githubusercontent.com/78171867/112702728-c7c4f100-8e51-11eb-8db3-c16200f9cda0.png)

Now taking into account that retro consoles, up to the ps2 I think, have an aspect ratio of 4: 3, if we put widescreen in these games with emulators on pc and android, the game will stretch and look ugly, but if we put it in its real aspect ratio, there will be black edges.

And for the human eye it is uncomfortable, because it thinks that the game is not covering the entire screen and consciously puts the wide screen where the game practically loses its aspect ratio and the characters look fat and wide.

The idea is to have the option to put custom backgrounds to the games. This will make the game look sharp and the background covers the entire screen.

I even did an example with photoshop, look: Please keep that in mind, as it is so cool. 

![image](https://user-images.githubusercontent.com/78171867/112702756-d7443a00-8e51-11eb-92c2-5ae69e8e56d4.png)

![image](https://user-images.githubusercontent.com/78171867/112702773-e0350b80-8e51-11eb-9ced-016cc25bf296.png)

![image](https://user-images.githubusercontent.com/78171867/112702788-e75c1980-8e51-11eb-8b02-212bd16be193.png)

**Comment by stenzek** [comment]
Personally don't get the appeal, but this would require a couple of things:

 - Setting backgrounds.
 - Adjusting the output position based on user preferences, rather than always centering.

**Comment by CristobalManga** [comment]
The idea is to play the original PS1 aspect ratio and avoid stretching the game to fit your monitor screen which may have a different aspect ratio.

With the original aspect ratio there will be a small visual improvement, since the pixels will not be cluttered. But the black edges when set to 4: 3 look ugly.

And putting a background to each individual game will remove the black borders.

I hope to explain myself well, it is that I am using the google translator xd.

![image](https://user-images.githubusercontent.com/78171867/112721923-bf0d0300-8ec3-11eb-9abd-74ea394e2c03.png)

**Comment by stenzek** [comment]
Sorry, I have no interest in adding this any time soon. I'm trying to reduce the project's scope since the feature requests are becoming overwhelming.
