### ISSUE TITLE
Does there need to be a "system failed to boot" warning after I stop trying to load a Libcrypt protected game? 

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1875]
If I choose not to continue can't it just gracefully take me back to the game list?  Like, yeah I chose for it not to boot. It's not an error. 

![Capture](https://user-images.githubusercontent.com/77198254/112726146-06e96400-8f70-11eb-9879-7461f572e482.PNG)

![Capture2](https://user-images.githubusercontent.com/77198254/112726153-11a3f900-8f70-11eb-90b4-d8e72d92cddb.PNG)

**Comment by stenzek** [comment]
Yes, because it aborts the startup, and the caller displays an error if that function returns false.
