### ISSUE TITLE
NRG cd image format (REQ)

### ISSUE THREAD

**Issue by Pycur** [stenzek/duckstation#1877]
Is there any way to read Nero NRG CD image format?
Because it's only 1 file, and have all information what needed.
I would want to merge duckstation with QuickPlay frontend to play rar compressed games with a nice, screenshot filled GUI.
But it can cause problems when a game is not an iso, but a cue/bin, or ccd, or others, and the gui can only extract one file to start the rom, and if it misses the cue, there will no cd audio, only track 1 is detected and played.
I also want to mark this post as a reature request, if possible.

Thank you for this awesome emulator, better than all others ever!

**Comment by stenzek** [comment]
I don't have any dumps in nrg format to implement against. Isn't it also a closed specification? Like MDS/MDF. And basically a dead format.

I'll leave it open as a feature request but I have no plans to implement it myself. The cd image loader is quite nicely abstracted if anyone else wants to though.

**Comment by Pycur** [comment]
Now you mention, I don't now if it has to be licensed or something.  Wiki says it's a custom format: "The NRG file format uses a variation of the Interchange File Format (IFF)".
So it may not be just a simple iso format.

Another idea, avoiding another programs:
Is there any way to place a nice option enabled sidebar to the right where I can see a cover and some screenshots from the game in the main window? (if I have them of course)

I mean to look like this:
https://postimg.cc/dkJfHHB4

It would be more nice to see a game list with pictures.
Displayed pictures are assumed from the selected file's fully similar name+other characters, to be able to differ them, like bugs bunny.iso->bugs bunny.frontcover.jpg  and bugs bunny.screenshot1.jpg, and so on... :)

It works like that with quickplay, and it's a very nice and useful function. The gui looks much prettier with some promoting images.

Sorry to flood you here by these requests. I'm just happier than ever to see this emulator working. If you don't want it just say it so, and i will act as you like.

Thank you!

**Comment by Pycur** [comment]
I just found out Duckstation can open CHD files, but I thought they are virtual HDD files for mame games' hdds. But it turned out, that I can create my own CHD files from cue/bin CD images to CHD with the mame's integrated CHDMAN program. And it seems working.
