### ISSUE TITLE
Audio is broken in the opening cutscene of Nickelodeon Rugrats - Search for Reptar (USA)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#188]
![Capture](https://user-images.githubusercontent.com/31968468/77836949-3c1d7380-71af-11ea-9c8f-9ff34cacfee8.PNG)

**Comment by kurayami6** [comment]
Advanced Dungeons & Dragons - Iron & Blood - Warriors of Ravenloft (USA) has the same problem.

![Capture](https://user-images.githubusercontent.com/31968468/78102188-71d38e00-7435-11ea-9e8e-3e8b8bd9c1c7.PNG)

**Comment by kurayami6** [comment]
Putter Golf (USA) has the same problem. That's 3 games I've now found with this issue. Do I need to find more or can this be fixed? 

![Capture](https://user-images.githubusercontent.com/31968468/80267443-44040100-86e4-11ea-9183-2ba5cbff4037.PNG)

**Comment by kurayami6** [comment]
Still an issue as of the latest version.

**Comment by kurayami6** [comment]
Simple 1500 Series Vol. 92 - The Tozan RPG - Ginrei no Hasha (Japan) has the same problem. 

![Capture](https://user-images.githubusercontent.com/31968468/87859282-51ddc100-c977-11ea-8dca-728d760460ab.PNG)

**Comment by stenzek** [comment]
Rugrats should be fixed by https://github.com/stenzek/duckstation/commit/f28ef01d2488a562cbfbd1ad409d32f16c41342d. Not sure about the others.

**Comment by kurayami6** [comment]
As of the latest version there's only a slight crackling sound on the title screens of Putter Golf (USA) and Simple 1500 Series Vol. 92 - The Tozan RPG - Ginrei no Hasha (Japan). Nickelodeon Rugrats - Search for Reptar (USA) and Advanced Dungeons & Dragons - Iron & Blood - Warriors of Ravenloft (USA) seems to be completely fixed.

**Comment by stenzek** [comment]
This was fixed a while back.
