### ISSUE TITLE
Play Store issue: Region lock on Argentina (?)

### ISSUE THREAD

**Issue by Jenmet-cy** [stenzek/duckstation#1882]
Hi. I've been having problems with fetching the DuckStation app in some phones from the Play Store. After checking a bit, I've discovered that the app is region-locked in my country (Argentina). Is this intentional?
![photo_2021-03-29_00-09-37](https://user-images.githubusercontent.com/52474680/112782351-34431a00-9023-11eb-8ada-a8606490c460.jpg)

**Comment by stenzek** [comment]
Yes, some regions are excluded on Google Play. You can still sideload the apk.
