### ISSUE TITLE
Little translation error

### ISSUE THREAD

**Issue by projetto** [stenzek/duckstation#1885]
With italian language on menu appear 
Spegni %Senza Salvare

must be

Spegni Senza Salvare

**Comment by projetto** [comment]
my account was flagged. Now my comment is visible

**Comment by andercard0** [comment]
> my account was flagged. Now my comment is visible

hey there, correction mande in : #2143 but, there are a bunch of lines missing / not translated if you want to reach us on Discord where you can then we can add/ fix those. :)
