### ISSUE TITLE
Hardware renderer + PGXP culling correction crashes Marcel Desailly Pro Football (France)

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1888]
I narrowed it down to those two specific things. Tested with all other enhancements off and with all hardware renderers. Upscaling doesn't make a difference. With those the game will either crash entirely or move in slow motion while showing strange graphical glitches.

![SLES-03868_2021-03-31_03-42-31](https://user-images.githubusercontent.com/77198254/113028304-d5260680-91d6-11eb-91c3-1fd31259b772.png)

![SLES-03868_2021-03-31_03-56-51](https://user-images.githubusercontent.com/77198254/113028319-d9eaba80-91d6-11eb-81ed-10dbd7746a0c.png)

**Comment by stenzek** [comment]
Not a bug. Happens when games use fixed size geometry buffers and culling causes additional triangles to be drawn.

**Comment by Kurayami7** [comment]
Can culling be disabled by default or is that not one of the per game settings?
