### ISSUE TITLE
Input display

### ISSUE THREAD

**Issue by deserteagle417** [stenzek/duckstation#1889]
An option to display inputs. Can be simple and off in a corner like Bizhawk or other emulators. E.g., the inputs are shown in the bottom left corner here:
![image](https://user-images.githubusercontent.com/41058000/113042398-2697ac80-9169-11eb-96a9-de94c74b4a9a.png)
This would help immensely for speedrunning verification.

**Comment by stenzek** [comment]
Sure, seems reasonable.

**Comment by deserteagle417** [comment]
Thanks! Appreciate it!

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/251043f11a8a4b5a05b9f9cfce3f7c0d2fca27c7

It's only textual labels at this point, eventually I'll probably replace these with icons, possibly when I rework controller binding to be more graphical.
