### ISSUE TITLE
The "Pause On Focus Loss" option isn't working on my end

### ISSUE THREAD

**Issue by LOuroboros** [stenzek/duckstation#1891]
Basically that. I have the Pause On Focus Loss option located at Settings -> General Settings enabled, but when I switch to some other window, the emulator is still running normally in the background instead of being paused.
I'm using the latest precompiled build for Windows x64, v0.1-3701-gdf5de773.

**Comment by LOuroboros** [comment]
Nevermind. It seems that after restarting the emulator, the option does work normally.

**Comment by Josegg0** [comment]
To not open another issue "Pause On Focus" does not work in nogui for me with option enabled.
