### ISSUE TITLE
Resident Evil games controllers issue

### ISSUE THREAD

**Issue by Matheus-The-Razor** [stenzek/duckstation#1892]
I had downloaded it on EmuCR the DuckStation Git (2021/03/30) but the three games in the Resident Evil series are not being playable because they are not recognizing the control

**Comment by stenzek** [comment]
Please do not use those builds, they're likely out of date, and I don't know what changes they include (possibly malware).

Use the builds from GitHub (https://github.com/stenzek/duckstation/releases/tag/latest) and re-test. Resident Evil games work fine in my testing.

RE1 does not support analog mode, you should switch to digital mode, or disable enable analog on reset. I'll push a compatibility update later to do this automatically.

**Comment by Matheus-The-Razor** [comment]
The problem is not the build, but the keyboard that doesn't work I tested it with my Ipega and it works correctly

**Comment by stenzek** [comment]
Works fine here, a keyboard is what I tested with. Nobody else has reported this issue, so it may be because you're using a modified build.

**Comment by Matheus-The-Razor** [comment]
But I tested the build you sent me but it also didn't work

**Comment by stenzek** [comment]
Did you disable analog mode for RE1?

**Comment by Matheus-The-Razor** [comment]
Yes

**Comment by stenzek** [comment]
I have no idea then. It's pretty difficult for me fix something which I can't reproduce.

Try loading the Keyboard input profiles.
