### ISSUE TITLE
Legend of Legaia frezzes at end of the game.

### ISSUE THREAD

**Issue by Jvplay** [stenzek/duckstation#1895]
I don't know if this was fixed or not but a want to report my problem, i was playing Legend of Legaia when at certain specific part of game the emulation just frezzes for an unknow reason but continues to play the music. I'm near to the end of game at Conkram ready to go to the past when this happens:

https://user-images.githubusercontent.com/81720171/113225117-43b0a600-9263-11eb-9609-aa48c9c047a0.mp4

**Steps to reproduce**
Play until the spot in the video.

**Hardware/Software:**
Archlinux x64
Intel Core 2 Duo E8400
Nvidia Geforce 210
2GB DDR2 ram
OpenGL
libretro-duckstation-2105-1 running at retroarch

If anyone can help me i would appreciate.

**Comment by Kurayami7** [comment]
This was fixed a while ago in the standalone version of Duckstation. The Retroarch version is months out of date which is why it still has the issue.

**Comment by stenzek** [comment]
Read above. Also please read the template which states that we have no control over the libretro core - you should report the issue to them.

**Comment by Jvplay** [comment]
> This was fixed a while ago in the standalone version of Duckstation. The Retroarch version is months out of date which is why it still has the issue.

ok, thanks i will give a look in the standalone version

**Comment by Jvplay** [comment]
> Read above. Also please read the template which states that we have no control over the libretro core - you should report the issue to them.

Thanks for the advice!
