### ISSUE TITLE
Add option to store all files in one folder.

### ISSUE THREAD

**Issue by HelveticaToast** [stenzek/duckstation#1896]
**Is your feature request related to a problem? Please describe.**
I'm trying to have different configurations for each installation, but it doesn't work because all of the config files are in one folder in documents.

**Describe the solution you'd like**
A config option that saves all config files in the folder with the duckstation executable.

**Describe alternatives you've considered**
None.

**Comment by PookaMustard** [comment]
Create a file called portable.txt in your DuckStation folder.

**Comment by stenzek** [comment]
See above.
