### ISSUE TITLE
Lagnacure Legend (Japan) instantly hangs on a black screen

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#1897]
Tested with all enhancements off, with a redump verified copy, with both interpreter and recompiler and with "force interpreter" and "force recompiler icache" on in per game settings. 

VRAM shows the game frozen with a single pixel rendered.

![SLPS-02832_2021-04-02_09-04-09](https://user-images.githubusercontent.com/77198254/113359951-8920c080-9394-11eb-954d-dbca016951ba.png)

**Comment by Kurayami7** [comment]
The original, Lagnacure (Japan, Asia), boots but runs in slow motion in recompiler mode. Interpreter works fine. Not sure if it's the same problem as Lagnacure Legend or if they're broken for different reasons. 

![SLPS-01009_2021-04-02_18-28-28](https://user-images.githubusercontent.com/77198254/113399415-ebf17680-93eb-11eb-9d60-20dcc56b0aa6.png)

![Capture](https://user-images.githubusercontent.com/77198254/113399425-f14ec100-93eb-11eb-92e3-6ea5829f2f07.PNG)

**Comment by stenzek** [comment]
Make sure it's not running slow because of logging - turn it all off and see if the issue persists.

**Comment by Kurayami7** [comment]
Logging was already off the first time I tried it but I checked again. No logging whatsoever. The game simply doesn't run properly with the recompiler.

![Capture](https://user-images.githubusercontent.com/77198254/113405005-d2a0f800-93f4-11eb-806f-154588e2be7e.PNG)

**Comment by stenzek** [comment]
Just has some self-modifying code, or data in the same 4KB page as code. Using LUT fastmem will reduce most of the performance hit.

**Comment by stenzek** [comment]
1e44c2f3 forces LUT fastmem for Lagnacure. Lagnacure Legend gets further in recompiler mode, interestingly. Still need to debug it.

**Comment by stenzek** [comment]
Fixed in current preview release.
