### ISSUE TITLE
Emulator crashes on Open-Dialog

### ISSUE THREAD

**Issue by Rockatweb** [stenzek/duckstation#1899]
Hi there,
i have the problem, that i cannot access the open-dialog. For example when i want to change the memorycard file. 
The same problem is with the memorycard manager. If i click on the folder icon the emulator crashes.
If i want to add more gamefolders the emulator also crashes.

In the crash.txt is only this entry
Exception 0xC0000005 at 0x00007FFA9A2E2B26

**Comment by stenzek** [comment]
This is a problem with third party shell extensions injecting themselves, not the emulator.

In the past we've found oldnewexplorer64.dll causes issues.

Also, next time, please fill out the issue template, don't delete it.
