### ISSUE TITLE
Monkey Hero hangs on the first loading screen

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#19]
I can here audio playing but the screen is frozen on this. 

![Capture](https://user-images.githubusercontent.com/31968468/74209462-f1699a00-4cdb-11ea-9fdf-5fddbef4461f.PNG)

**Comment by stenzek** [comment]
Might be a MDEC issue. Will look into it when I have time.

**Comment by stenzek** [comment]
Not an MDEC issue, it's the lack of GPU timings for VRAM writes. I did have a heuristic for these previously, but it caused regressions in some other games. When I eventually implement these timings properly, this should fix the issue.

As an aside, you can skip the intro by hitting start and it'll go ingame, but there appears to also be sound bugs.

**Comment by stenzek** [comment]
Fixed by https://github.com/stenzek/duckstation/commit/b0b1fd8f1ae93f2d5c034839915db7789953433a
