### ISSUE TITLE
Text is invisible on the options menu of Spot Goes To Hollywood (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#190]
Duckstation

![SLUS-00014_2020-03-29_15-02-31](https://user-images.githubusercontent.com/31968468/77840083-dc36c500-71ce-11ea-827e-4e254c17ab7a.png)

Beetle PSX

![Spot Goes to Hollywood (USA)-200329-150437](https://user-images.githubusercontent.com/31968468/77840086-f375b280-71ce-11ea-8d0b-f122430a37a1.png)

**Comment by stenzek** [comment]
Which renderer? Does the software renderer have the same issue?

**Comment by kurayami6** [comment]
Happens with all renderers.

**Comment by kurayami6** [comment]
Still an issue as of the latest version. 

![SLUS-00014_2020-05-09_15-40-59](https://user-images.githubusercontent.com/31968468/81465220-bbb94c00-920b-11ea-8881-7f10ea90a87d.png)

**Comment by stenzek** [comment]
Needs tight CPU/DMA sync (fifo size = 16). Noting here for future gameini.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/16c47f455318dda2190d218b1133c3abc945091e

**Comment by kurayami6** [comment]
Fixed.
