### ISSUE TITLE
Provide option for MSAA & SSAA to be applied to 3d only.

### ISSUE THREAD

**Issue by rigopoui** [stenzek/duckstation#1900]
**Is your feature request related to a problem? Please describe.**
Submitting this as a feature request as I'm not sure whether it's a bug or just normal SSAA/MSAA behavior.
It looks like 2d elements are affected by anti-aliasing, when running on 1x resolution. 

Most of the time this is not an issue, but in games with 2d backgrounds, they can get strangely distorted. 
See here: 
![myimage](https://user-images.githubusercontent.com/45214361/113461648-1102db00-9426-11eb-849d-8646a6815b47.gif)
Notice how some high contrast and detailed sections get smoothed over and lose quality. It also looks to me like the affected parts of the 2d background kind of get shifted down and/or right.

**Describe the solution you'd like**
If this could be done, I'd like the option for SSAA/MSAA to affect only the 3d elements of a scene.

**Describe alternatives you've considered**
An alternative for me is to just use 4x res + downsample instead, but this solution performs much worse than than 4xSSAA

**Comment by stenzek** [comment]
Not possible - MSAA is a framebuffer not a polygon attribute, and already uses centroid sampling.
