### ISSUE TITLE
bug in MX Linux 19

### ISSUE THREAD

**Issue by NIDObr** [stenzek/duckstation#1904]
Good night, I'm having trouble running the duckstation on the MX-19.4_ahs_x64, I'm using the latest version of the duckstation (duckstation-qt-x64.AppImage)

uname -a:
`Linux host 5.10.0-5mx-amd64 #1 SMP Debian 5.10.26-1~mx19+1 (2021-04-01) x86_64 GNU/Linux`

This is the error message:
``$ ./duckstation-qt-x64.AppImage
/tmp/.mount_duckstRlbkzm/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_duckstRlbkzm/AppRun.wrapped)
/tmp/.mount_duckstRlbkzm/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_duckstRlbkzm/usr/lib/libQt5Widgets.so.5)
/tmp/.mount_duckstRlbkzm/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_duckstRlbkzm/usr/lib/libSDL2-2.0.so.0)
/tmp/.mount_duckstRlbkzm/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_duckstRlbkzm/usr/lib/libQt5Gui.so.5)
/tmp/.mount_duckstRlbkzm/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_duckstRlbkzm/usr/lib/libQt5Core.so.5)
/tmp/.mount_duckstRlbkzm/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_duckstRlbkzm/usr/lib/libpulse.so.0)
/tmp/.mount_duckstRlbkzm/AppRun.wrapped: /lib/x86_64-linux-gnu/libp11-kit.so.0: no version information available (required by /tmp/.mount_duckstRlbkzm/usr/lib/libgnutls.so.30)
/tmp/.mount_duckstRlbkzm/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_duckstRlbkzm/usr/lib/libpng16.so.16)
/tmp/.mount_duckstRlbkzm/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_duckstRlbkzm/usr/lib/libicui18n.so.66)
/tmp/.mount_duckstRlbkzm/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_duckstRlbkzm/usr/lib/libicuuc.so.66)
/tmp/.mount_duckstRlbkzm/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_duckstRlbkzm/usr/lib/libpulsecommon-13.99.so)
/tmp/.mount_duckstRlbkzm/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /tmp/.mount_duckstRlbkzm/usr/lib/libsystemd.so.0)
/tmp/.mount_duckstRlbkzm/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_duckstRlbkzm/usr/lib/libsndfile.so.1)
/tmp/.mount_duckstRlbkzm/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_duckstRlbkzm/usr/lib/libFLAC.so.8)
/tmp/.mount_duckstRlbkzm/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_duckstRlbkzm/usr/lib/libsqlite3.so.0)``

**Comment by ggrtk** [comment]
Your Linux distribution does not have new enough versions of glibc for running the provided AppImage. Versions 2.29 and 2.30 are about two years old at this point... acquire up-to-date versions or build the emulator from source yourself.

**Comment by stenzek** [comment]
As @ggrtk said, try building from source - the AppImages are built on Ubuntu 20.04 so you'll need a glibc version compatible with that.

**Comment by NIDObr** [comment]
Thanks for the answer, I will do this, I return with the result.

**Comment by NIDObr** [comment]
Thanks, after compiling glibc-2.29 and glibc-2.30 is working perfectly!
