### ISSUE TITLE
Cannot map Negcon L button to LB button with Xbox One Controller Bluetooth

### ISSUE THREAD

**Issue by Najip** [stenzek/duckstation#1907]
As the title issue, I Cannot map Negcon L button to LB (L1) button with Xbox One Controller Bluetooth.

My device is Pocophone F1 running Android 11. Set to another controller mode like Dualshock, analog, or digital, everything is working.

**Comment by stenzek** [comment]
I don't think this is a bug - L is an axis in the DuckStation implementation, not a button. Therefore you need to map it to an axis, such as a trigger or stick (assuming your phone's driver exposes the triggers as axes and not buttons, some don't).

**Comment by stenzek** [comment]
Halfaxes can be bound to buttons as of https://github.com/stenzek/duckstation/commit/a9a571cd6af04a80277e8923c1480a97a7b695d8
