### ISSUE TITLE
Retroarch core - possible for save states to use a relative path instead of absolute?

### ISSUE THREAD

**Issue by clodi95** [stenzek/duckstation#1908]
**Game details**
It's a multi-disc game saved as an .m3u playlist of .chd files (Final Fantasy IX PAL, but it's irrelevant)

**Description of the issue / bug**
a save state made on one device doesn't work on other devices (unlike... all other emulators I tested; specifically, I tried Beetle PSX HW and that loads the save state without problems), because Duckstation appears to be using the ROM's absolute path instead of relative for loading the ROM the save state refers to... or something like that (maybe the other cores don't check for the ROM path at all since they know/trust the save state refers to the rom that's currently loaded in retroarch, I don't know). If I load in Retroarch Android a save state I made in Windows and vice versa, I get the message *"failed to open cd image from save state: \*path to rom of other OS\*"*. 

**why this matters**: it renders impossible cloud-syncing of save states across devices. Normal saves work tho, and that's the workaround I've been using but it's still a big inconvenience in a lot of games and seems an easily solvable problem.

*Note*: Doing this on a non-multi-disc ROM (so not a playlist file), I still get the error, but the emulator is smart enough to instead load the same rom file from the other path (*"Using existing image file ...., this matches ..."*, the emu says).

**Steps to reproduce**
In Retroarch: on a first device, load an .m3u playlist and save a state; copy the state to a second device and load it from there. You'll get the error message "*failed to open cd image from save state \*path to rom on first device\**".

**Emulator version**
Latest SwanStation core I could download from within RetroArch 1.9.0

EDIT: just realized that the libretro core is not maintained by the dev of standalone duckstation, sorry. Maybe the problem applies to the standalone version too, tho.

**Comment by PookaMustard** [comment]
The RetroArch core is **no longer supported.**

Please open an issue with the RetroArc-

>EDIT: just realized that the libretro core is not maintained by the dev of standalone duckstation, sorry. Maybe the problem applies to the standalone version too, tho.

Oh. Please try the standalone version, as it's more up-to-date than SwanStation and may have your bug fixed already.

**Comment by stenzek** [comment]
See above. Please direct the issue to the libretro fork.
