### ISSUE TITLE
Achievement sound effect?

### ISSUE THREAD

**Issue by jacklongford** [stenzek/duckstation#1909]
Just a very small request, would it be possible to add in a sound effect or jingle for when an achievement is awarded please?
I really enjoy this on consoles and for some reason it just makes the award feel better and spurs me on to unlock more.

Thank you and great work on the emulator by the way!

**Comment by jacklongford** [comment]
Also, would it be possible to create the option to move the notification to the top right like on PS3? (Sorry if I'm asking too much!)

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/5568de1e03299974af999166bc2325a472cfc9a7
