### ISSUE TITLE
Graphical glitches and hang in JumpStart Wildlife Safari - Field Trip (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#191]
The game hangs on this screen and there's graphical garbage at the top. 

![Capture](https://user-images.githubusercontent.com/31968468/77840940-57e93f80-71d8-11ea-8033-34eee46c56cc.PNG)

**Comment by stenzek** [comment]
Colours at the top should be hidden by overscan if you change the crop mode.

Couldn't reproduce the hang.
