### ISSUE TITLE
Achievement User-Agent is incorrect

### ISSUE THREAD

**Issue by Jamiras** [stenzek/duckstation#1916]
**Game details**
Any

**Description of the issue / bug**
Requests being sent to the RetroAchievements server from Windows have a browser-like User-Agent:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0`

I believe this is because the static `HttpDownloader::Create` method calls `HTTPDownloaderWinHttp::Initialize` and `HTTPDownloaderWinHttp::Initialize` creates the `m_hSession` object before `SetUserAgent` is called in `Cheevos::Initialize`. This analysis was done entirely in github. I have not actually run through the debugger. I have not tested the behavior on any platform other than Windows.

**Steps to reproduce**
Log in to RetroAchievements, load a game with achievements, unlock an achievement. Use WireShark or a similar tool to verify the header.

**Hardware/software**
Windows 10

**Emulator version**
0.1-3712-ge94c68e8 (dev)

**Comment by stenzek** [comment]
Nice catch, thanks. Was also missing from Android.

Fixed in https://github.com/stenzek/duckstation/commit/d41b5be9080ccfcc36135b5ab2939ef51e4eb0f1

I've also made it send the OS and architecture. So you should get `Duckstation for <OS> (<Architecture>) <Version>`.
