### ISSUE TITLE
Duke Nukem (Europe) needs upscaling disabled by default 

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1918]
Upscaling completely breaks it like Doom and Star Wars: Dark Forces. 

![SLES-00987_2021-04-04_13-26-20](https://user-images.githubusercontent.com/77198254/113497992-486ba780-954c-11eb-87bb-2541b87dba81.png)

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/57830bdd3668df65ce3db95d539cf6dd68a6c63a
