### ISSUE TITLE
works on xbox 360 rgh with the same graphics quality 

### ISSUE THREAD

**Issue by xcamus** [stenzek/duckstation#1919]
Good afternoon,
emulator developers
could make a port for the xbox 360 RGH?
because the emulator that exists for the console is very bad
the duckstation is perfect, the graphics are beautiful and the image is very good
i would like to play with that same quality on my xbox 360 rgh

it is possible?
Does the current dusktation work on the xbox 360 rgh?

**Comment by stenzek** [comment]
No, don't have one, not interested in writing a PPC recompiler, sorry.
