### ISSUE TITLE
[Question] Flatpak version.

### ISSUE THREAD

**Issue by VaGNaroK** [stenzek/duckstation#192]
did you intend to compile this fabulous emulation tool for flatpak format and make it available for all linux distributions? Or do you currently only want to keep the project code?

**Comment by stenzek** [comment]
My main concern would be Qt. If Qt is simple enough to include in a flatpak, I don't see why I couldn't add it to the CI.

**Comment by stenzek** [comment]
Latest builds are available as AppImages, thanks to @ggdrt (https://github.com/stenzek/duckstation/pull/251). These can be found on the CI at 

I believe Flatpaks are a bit more annoying due to the build mechanism, but if the demand is there in the future we could look into it again.

**Comment by gal20** [comment]
Hi @stenzek, I can create the flatpak version if you are interested. It doesn't require any changes to this repository, the application can be submitted to [flathub.org](https://flathub.org/home) by creating a pull request to [flathub/flathub](https://github.com/flathub/flathub) with the building manifest. With your permission, I can create the PR to flathub.

**Comment by Pixelnarium** [comment]
For anyone who wants to maintain a flatpak of DuckStation I made one for myself here which can be used as a starting point. To be accepted to FlatHub it would need to be build against a specific version or specific commit and some more metadata inside the appdata.xml. Some cleanups inside the json too I think.

https://github.com/Pixelnarium/flatpak/tree/master/org.duckstation.DuckStation

As for a reason why I personally prefer flatpak versions of apps is because they normally run inside a sandbox. It is similar to Android in that case.

**Comment by stenzek** [comment]
Due to the high release frequency (young project), I'm not providing stable builds or versions. The closest you'll get is the development build, which I sync once every couple of weeks (on `latest` tag).

**Comment by Pixelnarium** [comment]
fyi: That would be OK in Flathub terms (it is the same with dolphin-emu). That is also just a [specific commit hash](https://github.com/flathub/org.DolphinEmu.dolphin-emu/blob/420fa790f5c000dd4c7bca88947f91eeef70cdb7/org.DolphinEmu.dolphin-emu.json#L74) that gets updated once a month or so. But just a varying tag is _not_ allowed on FlatHub.

Maybe when things get more stable and calm in development.

**Comment by j8r** [comment]
It is possible to make Flathubbot atomically bump the master commit hash, see https://github.com/flathub/net.rpcs3.RPCS3 as an example. @Pixelnarium, it would be awesome if you can go forward and submit your Flatpak to Flathub :heart: 

We can consider that we have @stenzek's approval (https://github.com/stenzek/duckstation/issues/1987#issuecomment-822022170 )

**Comment by stenzek** [comment]
Probably best to mark it as unofficial, since I'm not sure what the environment will be for building, and thus cannot support it (I only support Ubuntu as that's what I have).

**Comment by MojoJojoDojo** [comment]
> It is possible to make Flathubbot automatically bump the master commit hash, see https://github.com/flathub/net.rpcs3.RPCS3 as an example. @Pixelnarium, it would be awesome if you can go forward and submit your Flatpak to Flathub ❤️
> 
> We can consider that we have @stenzek's approval ([#1987 (comment)](https://github.com/stenzek/duckstation/issues/1987#issuecomment-822022170) )

Unrelated but I like how the RPCS3 AppImage got support for auto updates out of the box..
Makes it comfortable for use.

**Comment by j8r** [comment]
> Probably best to mark it as unofficial, since I'm not sure what the environment will be for building, and thus cannot support it (I only support Ubuntu as that's what I have).

Maybe, but at least the environment is easily reproducible. The runtime is there: https://github.com/KDE/flatpak-kde-runtime, more specifically https://github.com/KDE/flatpak-kde-runtime/blob/qt5.15lts/org.kde.Sdk.json.in We cannot be sure of the build environment even with an Ubuntu , which can vary with updates, packages, flavors and configurations.

**Comment by j8r** [comment]
> Unrelated but I like how the RPCS3 AppImage got support for auto updates out of the box..
Makes it comfortable for use.

It will be already built-in with Flatpak, if you install the Flatpak integration `gnome-software-plugin-flatpak` or `plasma-discover-backend-flatpak`.

Also, I'm not sure what's the point of AppImage if glibc is not included (in the binary or AppImage), compared to a regular dynamically linked binary, maybe except avoiding to have to `apt get` the dependencies.

**Comment by barthalion** [comment]
@Pixelnarium @j8r Feel free to open a PR and we'll sort it out from there. It's always easier to talk about a package when it exists and is easy to test.

**Comment by Pixelnarium** [comment]
Feel free to use my example as a starting point. Currently, I do not have the motivation to maintain this package on Flathub since it is heavily in development. Should also be a person who uses it more often than me.

**Comment by j8r** [comment]
Sure thing, can do. I however prefer to wait until I know how to automate the bump of the commit hash, especially with what @stenzek said:
> Due to the high release frequency (young project), I'm not providing stable builds or versions.
in the future

I know it is possible, RPCS3 and others do it (without hosting their own https://github.com/flathub/flatpak-external-data-checker) - but the docs are lacking. I've already ported Flycast, next this one and probably m64p in the future and obviously don't want to bump manually their commit hash.

**Comment by j8r** [comment]
I got @barthalion answer. I'll submit it in the following days @Pixelnarium then, thanks for your work!
