### ISSUE TITLE
[Aarch64/NOGUI] FF7 battle loading slowdowns on Pi4: dynarec cache misses?

### ISSUE THREAD

**Issue by vanfanel** [stenzek/duckstation#1920]
Hi there,

I have just built NOGUI from latest GIT, now that "sync to host refresh rate" works. And works very well indeed!

However, I see that the battle loading sequence in FF7 has MAJOR slowdowns, ruining the audio. It's not the whirl effect: the slowdown happens just after the whirl effect has finished, and just before the battle scene is shown.

More pointers:
-It only happens when a new game is started.
-It happens always after a new game is started.
-It does NOT happen if a saved game is loaded (I mean a real saved game, I don't use savestates and would never report anything related to savestates)
-It only happens on Pi4/aarch64. It happens in all backends: Vulkan, GL and Software.
-It does NOT happen on X86_64 on the same DuckStation configuration.
-There are no graphical errors to be seen, it's clearly a performance problem.
-On Pi4/aarch64, Tekken 3 realtime demo uses ~30 - ~40% CPU, and runs fullspeed with vsync ON.
-USB access is out of the question as I am using a FAST USB 3.1 pendrive to do the tests. Also, that would cause slowdowns on every battle load sequence, and as I said it only happens after a new game is started.

So it makes me think about some kind of cache miss sequence on battle loading, but only when the other FF7 engines (video playback + 2D scenes) have been recompiled: that would explain that major slowdown only happens in battle loading after intro playback.

**Comment by stenzek** [comment]
Are you sure this doesn't happen with the software renderer? The only slowdown I'm seeing is during the whirl, and it looks like that's because of a suboptimal path in `vkCmdCopyImage`.

**Comment by vanfanel** [comment]
@stenzek It happens with Vulkan, GL and Software renderers. All of them. And it happens AFTER the whirl animation has completed (ie, just before the battle starts).

Is there some functionality I can comment out to see if I can see a difference? (Even if the effect is disabled or there are other deffects: just as a test)

**Comment by stenzek** [comment]
I couldn't get any slowdown after the swirl.

I have a patch which swaps out the framebuffer blit for a draw, which fixes the only slowdown I could reproduce.

**Comment by stenzek** [comment]
Probably should test with cdrom preloading enabled to rule out storage bottlenecks.

**Comment by vanfanel** [comment]
@stenzek I have tried with CD image preloaded. Should have added to the first post too.. I always do (was something obvious to try because FF7 loads the battle data during the swirl).

About that patch, is it available to try? I hear the music heavily breaking after the swirl/whirl, just when the screen is still black, but maybe there's still something going on in the video system even if I can't see it.

**Comment by stenzek** [comment]
I've pushed the GL swirl slowdown fix: https://github.com/stenzek/duckstation/commit/2ed482132d5fa7b01d97d2bf5732f9c615a56aee

Will try profiling again tomorrow... but like I said, I wasn't seeing anything. How many frames does it run slow for? The log at verbose level should give some indication here.

**Comment by vanfanel** [comment]
@stenzek 

With that push, the slowdown is far less noticeable on the GL renderer!
However, it's still exactly the same with the Vulkan renderer.

I have logged the moment where it happens, using the verbose logging as you told me:

```
[  256.6800] W(ExecuteCommand): CDROM Pause command while seeking - updating position
[  256.9296] V/System: FPS: 30.49 VPS: 59.99 Average: 16.59ms Worst: 16.82ms
[  257.9296] V/System: FPS: 30.00 VPS: 60.00 Average: 16.59ms Worst: 16.82ms
[  258.9461] V/System: FPS: 29.51 VPS: 60.01 Average: 16.59ms Worst: 16.82ms
[  259.9461] V/System: FPS: 30.00 VPS: 60.00 Average: 16.59ms Worst: 16.84ms
[  260.9629] V/System: FPS: 30.49 VPS: 59.99 Average: 16.60ms Worst: 16.82ms
[  261.9629] V/System: FPS: 30.00 VPS: 60.00 Average: 16.59ms Worst: 16.83ms
[  262.9794] V/System: FPS: 29.51 VPS: 60.01 Average: 16.59ms Worst: 16.82ms
[  263.9962] V/System: FPS: 30.49 VPS: 59.99 Average: 16.59ms Worst: 16.82ms
[  265.0127] V/System: FPS: 29.51 VPS: 60.01 Average: 16.59ms Worst: 16.82ms
[  266.0295] V/System: FPS: 30.49 VPS: 59.99 Average: 16.59ms Worst: 16.83ms
[  267.0295] V/System: FPS: 30.00 VPS: 60.00 Average: 16.60ms Worst: 16.82ms
[  268.0295] V/System: FPS: 30.00 VPS: 60.00 Average: 16.59ms Worst: 16.82ms
[  269.0460] V/System: FPS: 29.51 VPS: 60.01 Average: 16.59ms Worst: 16.83ms
[  270.0460] V/System: FPS: 30.00 VPS: 60.00 Average: 16.59ms Worst: 16.81ms
[  271.0629] V/System: FPS: 30.49 VPS: 59.99 Average: 16.59ms Worst: 16.81ms
[  272.0794] V/System: FPS: 29.51 VPS: 60.01 Average: 16.59ms Worst: 16.82ms
[  273.0799] V/System: FPS: 3.00 VPS: 58.97 Average: 16.90ms Worst: 43.73ms
[  274.0802] V/System: FPS: 0.00 VPS: 59.98 Average: 16.59ms Worst: 24.87ms
[  274.4050] V/AudioStream: Audio buffer underflow, resampled 37 frames to 512
[  274.4398] V/AudioStream: Audio buffer underflow, resampled 445 frames to 512
[  274.4746] V/AudioStream: Audio buffer underflow, resampled 447 frames to 512
[  274.5094] V/AudioStream: Audio buffer underflow, resampled 445 frames to 512
[  274.5443] V/AudioStream: Audio buffer underflow, resampled 447 frames to 512
[  274.5791] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  274.6140] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  274.6488] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  274.6604] V/AudioStream: Audio buffer underflow with no samples, added 512 frames silence
[  274.6952] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  274.7300] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  274.7416] V/AudioStream: Audio buffer underflow with no samples, added 512 frames silence
[  274.7765] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  274.8113] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  274.8229] V/AudioStream: Audio buffer underflow with no samples, added 512 frames silence
[  274.8578] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  274.8810] V/AudioStream: Audio buffer underflow, resampled 223 frames to 512
[  274.8830] W(WaitForReadToComplete): Had to wait 1.61 msec for LBA 18679
[  274.9042] V/AudioStream: Audio buffer underflow, resampled 223 frames to 512
[  274.9391] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  274.9508] V/AudioStream: Audio buffer underflow, resampled 32 frames to 512
[  274.9855] V/AudioStream: Audio buffer underflow, resampled 414 frames to 512
[  274.9971] V/AudioStream: Audio buffer underflow with no samples, added 512 frames silence
[  275.0320] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  275.0435] V/AudioStream: Audio buffer underflow with no samples, added 512 frames silence
[  275.0670] V/AudioStream: Audio buffer underflow, resampled 357 frames to 512
[  275.0901] V/AudioStream: Audio buffer underflow, resampled 89 frames to 512
[  275.1003] V/System: FPS: 0.00 VPS: 49.99 Average: 19.93ms Worst: 34.50ms
[  275.1017] V/AudioStream: Audio buffer underflow with no samples, added 512 frames silence
[  275.1364] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  275.1480] V/AudioStream: Audio buffer underflow with no samples, added 512 frames silence
[  275.1829] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  275.1945] V/AudioStream: Audio buffer underflow with no samples, added 512 frames silence
[  275.2293] V/AudioStream: Audio buffer underflow, resampled 447 frames to 512
[  275.2409] V/AudioStream: Audio buffer underflow with no samples, added 512 frames silence
[  275.2642] V/AudioStream: Audio buffer underflow, resampled 222 frames to 512
[  275.2874] V/AudioStream: Audio buffer underflow, resampled 223 frames to 512
[  275.2991] V/AudioStream: Audio buffer underflow, resampled 52 frames to 512
[  275.3339] V/AudioStream: Audio buffer underflow, resampled 395 frames to 512
[  275.3454] V/AudioStream: Audio buffer underflow with no samples, added 512 frames silence
[  275.3803] V/AudioStream: Audio buffer underflow, resampled 445 frames to 512
[  275.3919] V/AudioStream: Audio buffer underflow with no samples, added 512 frames silence
[  275.4152] V/AudioStream: Audio buffer underflow, resampled 223 frames to 512
[  275.4384] V/AudioStream: Audio buffer underflow, resampled 223 frames to 512
[  275.4500] V/AudioStream: Audio buffer underflow with no samples, added 512 frames silence
[  275.4848] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  275.4964] V/AudioStream: Audio buffer underflow with no samples, added 512 frames silence
[  275.5312] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  275.5429] V/AudioStream: Audio buffer underflow with no samples, added 512 frames silence
[  275.5545] V/AudioStream: Audio buffer underflow with no samples, added 512 frames silence
[  275.5893] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  275.6011] V/AudioStream: Audio buffer underflow, resampled 53 frames to 512
[  275.6358] V/AudioStream: Audio buffer underflow, resampled 393 frames to 512
[  275.6473] V/AudioStream: Audio buffer underflow with no samples, added 512 frames silence
[  275.6822] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  275.6938] V/AudioStream: Audio buffer underflow with no samples, added 512 frames silence
[  275.7286] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  275.7635] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[  276.0305] V/AudioStream: Audio buffer underflow, resampled 497 frames to 512
[  276.1126] V/System: FPS: 0.00 VPS: 48.40 Average: 20.59ms Worst: 36.05ms
[  276.7156] V/AudioStream: Audio buffer underflow, resampled 439 frames to 512
[  276.7389] V/AudioStream: Audio buffer underflow, resampled 223 frames to 512
[  277.1128] V/System: FPS: 5.00 VPS: 59.99 Average: 16.60ms Worst: 16.73ms
```

**Comment by stenzek** [comment]
Not going to add a workaround for the Vulkan renderer unless other drivers also have a slow path here. The pi's driver is still relatively new, so issues are expected, and hopefully the copy image command will be optimized in time.

**Comment by vanfanel** [comment]
@stenzek Yes, I understand and that's perfectly logical.

Under OpenGL (GLES3.1 in the case of Raspberry Pi4) however, emulation is far from fullspeed. This is from running the BIOS only:

```
[    6.2961] I/GL::ShaderCache: 0 program binary formats supported by driver
[    6.2961] W(Open): Your GL driver does not support program binaries. Hopefully it has a built-in cache, otherwise startup will be slow due to compiling shaders.                                                                                                         
[    7.3025] I/CommonHostInterface: Compiling Shaders: 67/156
[    8.3086] I/CommonHostInterface: Compiling Shaders: 132/156
[    8.6094] I/Bus: Fastmem base: 0x7e94000000
[    8.6230] I/MemoryCard: Loaded memory card from /home/pi/.local/share/duckstation/memcards/shared_card_1.mcd
[    8.7248] I/CommonHostInterface: Refresh rate: Host=60.000000hz Guest=59.817333hz Ratio=1.003054 - can sync
[    8.7248] I/CommonHostInterface: Target speed: 100.305382%
[    8.7248] I/CommonHostInterface: Syncing to video
[    8.7249] V/AudioStream: Audio buffer underflow with no samples, added 2048 frames silence
[    8.7251] I/CommonHostInterface: Max display fps: 0.000000 (displaying all frames)
[    8.7252] I/CommonHostInterface: Audio input sample rate: 44234 hz
[    8.7254] I/CommonHostInterface: Using host vsync for throttling.
[    8.7273] W(DoEXP2Access): BIOS POST status: 0F
[    8.7275] W(DoEXP2Access): BIOS POST status: 0E
[    8.7279] W(DoEXP2Access): BIOS POST status: 01
[    8.7280] W(DoEXP2Access): BIOS POST status: 02
[    8.7286] W(DoEXP2Access): BIOS POST status: 03
[    8.7313] W(DoEXP2Access): BIOS POST status: 04
[    8.7318] W(DoEXP2Access): BIOS POST status: 01
[    8.7319] W(DoEXP2Access): BIOS POST status: 03
[    8.7321] W(DoEXP2Access): BIOS POST status: 04
[    8.7329] W(DoEXP2Access): BIOS POST status: 05
[    8.7341] W(DoEXP2Access): BIOS POST status: 06
[    8.7342] W(DoEXP2Access): BIOS POST status: 02
[    8.7350] W(DoEXP2Access): BIOS POST status: 05
[    8.7359] W(DoEXP2Access): BIOS POST status: 06
[    8.7390] W(DoEXP2Access): BIOS POST status: 07
[    8.7400] V/AudioStream: Audio buffer underflow, resampled 420 frames to 516
[    8.7485] V/AudioStream: Audio buffer underflow, resampled 245 frames to 512
[    8.7831] V/AudioStream: Audio buffer underflow, resampled 447 frames to 512
[    8.8179] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[    8.8876] V/AudioStream: Audio buffer underflow, resampled 380 frames to 512
[    9.7336] V/System: FPS: 0.00 VPS: 59.50 Average: 16.76ms Worst: 24.74ms
[   10.0606] V/AudioStream: Audio buffer underflow, resampled 437 frames to 512
[   10.0835] V/AudioStream: Audio buffer underflow, resampled 197 frames to 512
[   10.1417] V/AudioStream: Audio buffer underflow, resampled 188 frames to 512
[   10.1648] V/AudioStream: Audio buffer underflow, resampled 197 frames to 512
[   10.1997] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[   10.2345] V/AudioStream: Audio buffer underflow, resampled 446 frames to 512
[   10.3390] V/AudioStream: Audio buffer underflow, resampled 314 frames to 512
[   10.7503] V/System: FPS: 7.87 VPS: 60.00 Average: 16.62ms Worst: 16.65ms
[   11.7503] V/System: FPS: 56.00 VPS: 60.00 Average: 16.62ms Worst: 16.63ms
[   11.8253] V/AudioStream: Audio buffer underflow, resampled 393 frames to 512
[   12.7503] V/System: FPS: 60.00 VPS: 60.00 Average: 16.61ms Worst: 16.63ms
[   12.8705] V/AudioStream: Audio buffer underflow, resampled 96 frames to 512
[   13.7669] V/System: FPS: 59.02 VPS: 59.02 Average: 16.89ms Worst: 33.28ms
[   14.7669] V/System: FPS: 60.00 VPS: 60.00 Average: 16.61ms Worst: 16.62ms

```

This earlier line is particurlarly interesting:
`
[    6.2686] W(SetCapabilities): GL_EXT/OES_copy_image missing, this may affect performance.`

It seems that OES_copy_image extension is not supported by the Pi4 GLES driver?
In fact, this is what SDL2's testgles2 says about the supported extensions on the Pi4:
```

INFO: Renderer   : V3D 4.2
INFO: Version    : OpenGL ES 3.1 Mesa 21.0.1
INFO: Extensions : GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_dxt1 GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_EXT_draw_instanced GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_type_2_10_10_10_REV GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_ANGLE_pack_reverse_row_order GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_EXT_occlusion_query_boolean GL_EXT_texture_rg GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_EXT_draw_buffers GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_texture_compression_astc_ldr GL_NV_pixel_buffer_object GL_OES_depth_texture_cube_map GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_color_buffer_float GL_EXT_sRGB_write_control GL_EXT_separate_shader_objects GL_EXT_shader_implicit_conversions GL_EXT_shader_integer_mix GL_EXT_base_instance GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_draw_elements_base_vertex GL_EXT_primitive_bounding_box GL_EXT_shader_io_blocks GL_EXT_texture_border_clamp GL_KHR_context_flush_control GL_NV_image_formats GL_OES_draw_elements_base_vertex GL_OES_primitive_bounding_box GL_OES_shader_io_blocks GL_OES_texture_border_clamp GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_EXT_buffer_storage GL_EXT_float_blend GL_EXT_geometry_point_size GL_EXT_geometry_shader GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_OES_EGL_image_external_essl3 GL_OES_geometry_point_size GL_OES_geometry_shader GL_OES_shader_image_atomic GL_EXT_texture_compression_s3tc_srgb GL_MESA_shader_integer_functions GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_MESA_framebuffer_flip_y GL_EXT_texture_query_lod
```

...and even if it's a GLES 3.1 implementation, OES_copy_image is, in fact, missing from that list.
So, is there hope for the Pi4 or is DuckStation just a bit too much for the popular SBC?
Indeed, being so cheap and accesible, I was hoping to have the best PSX emulator running well on it, and it seems to be a common consensus that it does, but it's not what I see.
Of course all those tests were made with the latest MESA stable version, 21.0.1 as of today, on aarch64.

**Comment by dankcushions** [comment]
hmm, i copy image support should be supported for pi4 after my PR: https://github.com/stenzek/duckstation/pull/1121

a regression? if you can debug those tests it should be useful - don't have time myself right now :(

**Comment by vanfanel** [comment]
@dankcushions On my way! :)

Looks like this in `GPU_HW_OpenGL::SetCapabilities`:

```
Thread 1 "duckstation-nog" hit Breakpoint 1, GPU_HW_OpenGL::SetCapabilities (this=0x5559f7a4f0, host_display=0x5559662f70)
    at /home/pi/src/duckstation/src/core/gpu_hw_opengl.cpp:322
322       if (!GLAD_GL_VERSION_4_3 && !GLAD_GL_EXT_copy_image && !GLAD_GL_ES_VERSION_3_2 && !GLAD_GL_OES_copy_image)

(gdb) p GLAD_GL_EXT_copy_image
$5 = 0
(gdb) p GLAD_GL_ES_VERSION_3_1
$6 = 1
(gdb) p GLAD_GL_OES_copy_image
$7 = 0
(gdb) p GLAD_GL_ES_VERSION_3_2
$8 = 0

```

So my understanding is that `GL_ES_VERSION_3_1` is correct (as this is what the Pi4 supports) and we are missing either` GLAD_GL_OES_copy_image` or `GLAD_GL_EXT_copy_image`

But I don't see where are those supossed to be set...

**Comment by dankcushions** [comment]
as you can see, `GL_OES_copy_image` is supported by mesa: https://gitlab.freedesktop.org/mesa/mesa/-/blob/master/docs/features.txt#L280

so either mesa is not reporting it properly, or the features.txt list is lying? or something else. i think it's worth logging it with mesa: https://gitlab.freedesktop.org/mesa/mesa/-/issues

it's strange, i could have sworn it was working before hence my comment about how the warnings were no-longer present: https://github.com/stenzek/duckstation/pull/1121#issue-529598302

but if both SDL2 and glad are saying it's not there now, then that seems fundamental.

**Comment by vanfanel** [comment]
@dankcushions I have been talking with the MESA devs in #dri-dev, and they told me this:
-That features.txt is unreliable
-WRT to:
https://gitlab.freedesktop.org/mesa/mesa/-/blob/master/docs/features.txt#L280
what it really means to say is 'all drivers that have GL_ARB_copy_image'

So, I believe there's no `GL_OES_copy_image` available in V3D.
Unless I am misunderstanding something...

**Comment by vanfanel** [comment]
Well, I went all the way and directly asked one of the V3D devs: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4588

Fingers crossed! This is our last hope for fullspeed PSX emulation on the Pi4 with DuckStation.

**Comment by stenzek** [comment]
I checked the mesa source earlier and as best as I can tell, it lowers then to blits for the most part, perhaps most importantly for partial copies. So I suspect the hardware might not support it.

Another option might be to see if there's any way to improve the performance of the blit shader in the vulkan driver.

**Comment by vanfanel** [comment]
> I checked the mesa source earlier and as best as I can tell, it lowers then to blits for the most part, perhaps most importantly for partial copies. So I suspect the hardware might not support it.
> 

Sounds like it won't be possible to implement the extension then :(

> Another option might be to see if there's any way to improve the performance of the blit shader in the vulkan driver.

That would be the other way, yes. What should I ask the MESA/V3DV devs specifically?

**Comment by stenzek** [comment]
I'm going to revert the GL changes and use `glBlitFramebuffer()` again instead - it makes performance worse on the Mali driver.

Fun fact, Mali implements copy_image, but it does it on the CPU instead of the GPU, so I have to fall back to blitting there anyway.

For what it's worth, I get no slowdown at all on an ODROID-N2+.

> That would be the other way, yes. What should I ask the MESA/V3DV devs specifically?

What we need is a way to do partial texture copies/blits (basically a memcpy) efficiently.

**Comment by vanfanel** [comment]
@stenzek

So in Vulkan there's vkCmdCopyImage(), isn't that precisely a fast memcpy for blitting (partial copy, as it has a parameter that's an array of regions) between images? That's what I see here:

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdCopyImage.html

It seems to be a Vulkan 1.2 extension anyway, but according to the V3DV devs, it's already implemented on V3DV:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/4588

**Comment by stenzek** [comment]
`vkCmdCopyImage()` is core Vulkan, not 1.2.

**Comment by vanfanel** [comment]
@stenzek I was confused by the URL on the Khronos docs, "1.2-extensions" there made me think it's an 1.2 extension.

I am looking at the DuckStation sources and I see several vkCmdCopyImage() calls:
```

src/core/gpu_hw_vulkan.cpp:      vkCmdCopyImage(g_vulkan_context->GetCurrentCommandBuffer(), tex->GetImage(), tex->GetLayout(),
src/core/gpu_hw_vulkan.cpp:      vkCmdCopyImage(g_vulkan_context->GetCurrentCommandBuffer(), m_vram_texture.GetImage(), m_vram_texture.GetLayout(),
src/core/gpu_hw_vulkan.cpp:  vkCmdCopyImage(cmdbuf, m_vram_texture.GetImage(), m_vram_texture.GetLayout(), m_vram_texture.GetImage(),
src/core/gpu_hw_vulkan.cpp:    vkCmdCopyImage(cmdbuf, m_vram_texture.GetImage(), m_vram_texture.GetLayout(), m_vram_read_texture.GetImage(),
src/core/gpu_hw_vulkan.cpp:  vkCmdCopyImage(cmdbuf, source.GetImage(), source.GetLayout(), m_downsample_texture.GetImage(),
src/common/vulkan/staging_texture.cpp:  vkCmdCopyImageToBuffer(command_buffer, src_texture.GetImage(), VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
```
What would be the relevant one for the swirl effect?

I am sking here because, as you can see on the MESA gitlab thread here:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/4588#note_870093
...it seems that V3DV doesn't have efficient batching yet (when regionCount > 1).

The V3DV devs need to know how the Vulkan renderer works for this and if its calls vkCmdCopyImage use a regionCount > 1 at all, because there's a margin for improvement there.

**Comment by stenzek** [comment]
Yes, it's used in multiple places.

Based on my very short and undetailed profiling, it looks like vnCmdCopyImage or glBlitFramebuffer (forget which would have to check again) was allocating a buffer (??) and calling into the kernel, and that might have been why it was showing up.

I think the pis GPU is just really slow. The Mali-G52 in my odroid-n2 can do 4x with no slowdown, 5x with very minor slowdown on the swirl, and that's 25x the pixels of 1x with the somewhat unoptimal Mali blob.

Switching to 16 bit buffers instead of 32 bit may help, or reducing the precision in the shaders, but these made almost no difference on Mali at least.

Fwiw, the other thing which could explain the slowdown on the CPU side is the code reloading - it'll page fault when overwriting code as thats how it detects changes with fastmem, maybe these faults are taking too long. And after it faults a few times, rather than continuing to repeat that, it backpatches to slowmem. 

So you could try removing or commenting these lines: https://github.com/stenzek/duckstation/blob/master/src/core/cpu_code_cache.cpp#L834-L846 and seeing if it makes any difference. I could also use the speculative memory addresses to avoid the backpatching in the first place. Just kinda annoying because it might catch a function like memcpy and force it down the slow path, but it's going to happen after a few faults with the current behaviour anyway.

**Comment by vanfanel** [comment]
@stenzek I did a git pull, commented out the lines you mentioned in  https://github.com/stenzek/duckstation/blob/master/src/core/cpu_code_cache.cpp#L834-L846 and made a new build. No impact on performance/slowdown was seen by commenting the mentioned lines: same massive slowdowns in FF7 swirl effect, while for example a very demanding game like Tekken 3 is always at 100% during the realtime demo sequence.
I believe that rules out the CPU-side slowdown, right?

So let's see what could be happening on the GPU side.

As far as I understand, vkCmdCopyImage() with `regionCount = 1 ` is as fast as it can be on the Pi4, right? (According to the V3DV devs, the problem would be with `regionCount > 1 `, if I understood their explanation right).

Now, if vkCmdCopyImage() is allocating a buffer, could it be that the buffer allocation and/or calling in the kernel is the problem? Did you see it on the V3DV Vulkan driver code in MESA?

**Comment by stenzek** [comment]
Try pulling this branch: https://github.com/stenzek/duckstation/tree/address-space-clash

That gets rid of as many of the faults as possible by speculating when it's going to happen. But if it doesn't help, I'm not going to bother merging it.

> As far as I understand, vkCmdCopyImage() with regionCount = 1 is as fast as it can be on the Pi4, right? (According to the V3DV devs, the problem would be with regionCount > 1 , if I understood their explanation right).

Probably. The fact that it can't do partial copies is a real pain for DuckStation's renderer.

> Did you see it on the V3DV Vulkan driver code in MESA?

Yeah, was in the call stack.

**Comment by vanfanel** [comment]
@stenzek I have just built the `address-space-clash` branch and it doesn't make any difference.

WRT vkCmdCopyImage() with regionCount = 1, which is what you are using, you just said that it can't do partial copies, and that the lack of that feature affects DuckStation's rendererer.
What would be the function/extension needed for that in Vulkan? Again, I could ask the V3DV devs to implement it.

**Comment by stenzek** [comment]
Blitting would be slower than copying, but it looks like the v3d driver basically lowers it to a blit anyway.

**Comment by vanfanel** [comment]
@stenzek So nothing else to be implemented would help here?

**Comment by stenzek** [comment]
I'll need to profile it again.

**Comment by vanfanel** [comment]
@stenzek Sounds good :)
Keep me informed on the results so I can give precisse information to the V3D devs.

**Comment by vanfanel** [comment]
@stenzek Work is being done at the moment on improving V3DV performance and compatibility:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/3915
And also there's this specifick DuckStation/V3D thread:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/4588

So, this is the chance to get the slowdowns fixed, directly by the MESA V3D devs.
It would be great if you could profile and tell me what function is being currently slow, this is the right moment to get it sorted out :)

**Comment by stenzek** [comment]
Probably the easiest way is to time/instrument the vulkan calls. I haven't forgot about it, just quite busy with work at the moment.

**Comment by vanfanel** [comment]
@stenzek Sorry for the un-needed reminder then.
It's just that there's an window of opportunity here, with the V3D devs accepting feature and improvement requests, and DuckStation is very promising for the Pi4 if these slowdowns are fixed, which can be apparently done if we can give them the necessary information.

**Comment by vanfanel** [comment]
@stenzek In some MESA or DuckStation update, this was fixed.
FF7 battle loading sequence is now running perfectly, no slowdowns with software renderer or Vulkan anymore.
