### ISSUE TITLE
Audio Issues (Stuttering in Full Screen Mode)

### ISSUE THREAD

**Issue by Carl393** [stenzek/duckstation#1921]
I'm playing Final Fantasy VII thanks to this wonderful Emulator!!
(current playstation 1 console died)

Just wondering if anyone else is having this problem on their duckstation? in full screen mode sometimes the audio jumps when the music is playing (there's a brief pause in the music track)

does anyone else have this issue? 

Here are my settings.
Increasing the buffer size doesn't seem to make a difference. I even connected my pro audio card using SPDIF output
still no change.
<img width="398" alt="Capture" src="https://user-images.githubusercontent.com/14049856/113524419-91d3eb00-957c-11eb-9d0e-30918903daad.PNG">

**Comment by stenzek** [comment]
Sounds like a configuration issue.

Try using sync to host refresh rate (resampling must be enabled).
