### ISSUE TITLE
Post Processing Option dont appear in nogui

### ISSUE THREAD

**Issue by mrdeathjr28** [stenzek/duckstation#1922]
**Is your feature request related to a problem? Please describe.**
Option in qt

![postpqt](https://user-images.githubusercontent.com/6601480/113531629-df595380-958e-11eb-9ce4-d8a8911180f3.png)

But lack in nogui

![lckngui](https://user-images.githubusercontent.com/6601480/113531647-ed0ed900-958e-11eb-8815-39a6f6345d47.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Thanks

**Comment by stenzek** [comment]
Working as intended - nogui is a simplified frontend which does not contain all options.
