### ISSUE TITLE
D-Input rumble workaround?

### ISSUE THREAD

**Issue by Phantasm90** [stenzek/duckstation#1923]
I've been trying to get rumble on my gamepad (is a Seisa SJ-703TM, driver Universal Network Joystick) with x360ce, Xoutput and WoJ and all failed, i did bind it to rumble when i mapped the buttons but no luck, is there any workaround?

**Comment by stenzek** [comment]
Vibration is only supported with SDL and XInput. There's a feature request https://github.com/stenzek/duckstation/issues/1246 but I have no immediate plans to add force feedback to DInput, since it's a deprecated API and only exists for controllers which have issues with SDL and XInput.
