### ISSUE TITLE
Memory card editor dont appear in nogui

### ISSUE THREAD

**Issue by mrdeathjr28** [stenzek/duckstation#1924]
**Is your feature request related to a problem? Please describe.**

memory card editor appear in qt but dont in nogui

![mcedqt](https://user-images.githubusercontent.com/6601480/113531864-88a04980-958f-11eb-9744-0911d36056c6.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Thanks

**Comment by stenzek** [comment]
Same as #1922 - not supported in nogui. Use Qt or the BIOS memory card editor.
