### ISSUE TITLE
Green Dots?

### ISSUE THREAD

**Issue by Carl393** [stenzek/duckstation#1925]
Just wondering what these small green artifacts might be exactly?
see photo. It seems to only happen on background 2d images.

<img width="475" alt="Capture" src="https://user-images.githubusercontent.com/14049856/113541992-51db2b00-95b1-11eb-956e-9babeeaa3197.PNG">

**Comment by stenzek** [comment]
Not a bug - this happens at the edges of textures when using filtering. Check VRAM and you'll see where it's coming from.
