### ISSUE TITLE
Nintendo Switch Pro Controller support is limited

### ISSUE THREAD

**Issue by KommodoreKomrk** [stenzek/duckstation#1926]
**Game details**
N/A

**Description of the issue / bug**
-Nintendo Switch Pro, wired controller, cannot be used to remap any keys. Using the Dpad (any direction) only registers the input Mouse/Keyboard 3. Using the movement pads/sticks registered Keyboard|left/right/up/down, but did not translate into actual inputs while in the emulation main menu/no disk screen.

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
-Tried with and without Steam, only inputs registered while running Duckstation through Steam

2. Which controller backend are you using in general settings
-Used SDL and xinput, both had the same issue

**Steps to reproduce**
-Use a Switch Pro Controller

**Enhancements information**
Off

**Hardware/software**
Windows 10

**Emulator version**
 0.1-3712-ge94c68e8

**Additional context**

**Comment by stenzek** [comment]
Why is it registering as a keyboard? Is there some mode on the controller you have to set to make it act as a gamepad?

**Comment by ggrtk** [comment]
I've asked a friend to test his Switch Pro Controller, and it reports as a keyboard + mouse under the XInput backend and as a proper controller under the SDL backend.

If it isn't working under the SDL controller backend, try the instructions here https://github.com/stenzek/duckstation#sdl-game-controller-database to see if it's a Switch Pro Controller version that hasn't been added to the database yet. There's currently only one version of the controller listed for Windows.

**Comment by KommodoreKomrk** [comment]
> 
> 
> I've asked a friend to test his Switch Pro Controller, and it reports as a keyboard + mouse under the XInput backend and as a proper controller under the SDL backend.
> 
> If it isn't working under the SDL controller backend, try the instructions here https://github.com/stenzek/duckstation#sdl-game-controller-database to see if it's a Switch Pro Controller version that hasn't been added to the database yet. There's currently only one version of the controller listed for Windows.

While there are technically 4 different versions of the Switch Pro Controller, all 3 of them use the exact same layout. Both layouts are already added into the controller database, so there shouldn't be any need to add it again.

Your friend's controller registers properly using SDL (as it should), but is he using it wired, or wireless?



> 
> 
> Why is it registering as a keyboard? Is there some mode on the controller you have to set to make it act as a gamepad?

There are no separate software installs needed, nor are there different modes available to set it as. That's what it does as default, as stated by ggtk.

**Comment by KommodoreKomrk** [comment]
Update: Found a workaround by using the Xbox Controller preset. NONE of the inputs correspond with the actual inputs from the controller itself, but the preset seems to make it work anyways.

**Comment by stenzek** [comment]
If the axes are still having issues, that's likely a SDL/controller DB, which is outside the scope of duckstation.

Same deal if the controller is acting as a keyboard as well as a game controller - we can't be expected to special case every possible whacky behavior of devices out there, especially for those we don't own ourselves ;)
