### ISSUE TITLE
Stop Duckstation from reading ISO & CUE at the same time? (Covers issue)

### ISSUE THREAD

**Issue by jvhellraiser** [stenzek/duckstation#1930]
Is there anyway to disable this? not sure if i am explain this OK, English is not my main language
is when you open the emulator and the tiles load (covers) Duckstation keeps reading the ISO and the Cue
so i end up with 2 covers of the same game one for the Cue and One for the ISO and i was asking myself if there
a way to tell Duckstation to only read one of these 2? either ISO or CUE but no both..so there could be only 1 Cover..
![Screenshot 2021-04-05 211051](https://user-images.githubusercontent.com/16488761/113644798-8c959f80-9653-11eb-8ef2-d63a58b8da35.jpg)

**Comment by stenzek** [comment]
Name it .bin not .iso, and update the cue.
