### ISSUE TITLE
Glitches using OpenGL

### ISSUE THREAD

**Issue by JaegerFox** [stenzek/duckstation#1932]
**Description of the issue / bug**
In the last Preview more specific in this commit 4ed12bc
I have glitches using OpenGL

**Hardware/software**
Intel Celeron 1007U, Intel HD Graphics 2500, OpenGL Video Render, Windows 8.1

**Emulator version**
last preview or 4ed12bc

**Additional context**
maybe it is due to the OpenGL glitch of these integrated graphics

![SCES-00984_2021-04-06_03-43-11](https://user-images.githubusercontent.com/29095345/113683826-3e4fc300-968a-11eb-840e-e99f559b9dc6.png)

**Comment by stenzek** [comment]
Please don't use the OpenGL renderer on Windows, Intel drivers especially have both rendering and performance issues. Stick with D3D11.

**Comment by Kurayami7** [comment]
Would it be better to just disable OpenGL for Windows altogether?

**Comment by stenzek** [comment]
No, since it works fine on most drivers.

And for myself, it saves me having to boot into Linux or mess around with Android debugging to test a GL issue.
