### ISSUE TITLE
Shinsetsu Samurai Spirits Bushidou Retsuden (Samurai Spirits RPG)

### ISSUE THREAD

**Issue by jvhellraiser** [stenzek/duckstation#1933]
I am having issues with this specific game for some reason this game is not running well on Duckstation
it has FPS drops and the game frame holds from time to time i would say this is a emulator issue but this
game runs pretty well on other emulators, may you guys check this out?
just start the game normally and once you enter the part where Yubei & Haohmaru you will actually notice.

**Comment by stenzek** [comment]
I can't help when you don't fill out the template.
