### ISSUE TITLE
Raspberry Pi 4 cannot load nogui UI elements when running at 1080p (or higher)

### ISSUE THREAD

**Issue by dankcushions** [stenzek/duckstation#1934]
When running at 1080p or higher, the UI elements (widget notifications, quick menu, etc) are unable to be properly displayed and appear as black/corrupt:
![image](https://user-images.githubusercontent.com/13054748/113787944-d950a780-9733-11eb-8b0f-3cfa44fbf855.png)

The cause is apparently the low texture size limits of the pi's GPU:
![image](https://user-images.githubusercontent.com/13054748/113788063-23d22400-9734-11eb-97b9-7e52d2e27822.png)
```
[    3.1852] I/GPU_HW_OpenGL: Max texture size: 4096x4096
```
As suggested by @stenzek, it's possible to resolve this issue by running at a lower resolution:
```
[GPU]
FullscreenMode = 1280 x 720 @ 0.000000 hz
```
loads these elements fine. However the background for this is that I'm trying to create a build script for [Retropie](https://retropie.org.uk/), where 1080p is the default/typical resolution. We could make the install/launch script set the config to 720p when the user is running at 1080p or higher, but it would be nice to get duckstation to parity with the pcsx_rearmed or the libretro duckstation core in this regard ❤️ 

**Hardware/software**
Pi 4 2GB
Raspberry Pi OS 32-bit
```
[    1.8512] I/GL::Context: GL_VENDOR: Broadcom
[    1.8513] I/GL::Context: GL_RENDERER: V3D 4.2
[    1.8513] I/GL::Context: GL_VERSION: OpenGL ES 3.1 Mesa 19.3.2
[    1.8513] I/GL::Context: GL_SHADING_LANGUAGE_VERSION: OpenGL ES GLSL ES 3.10
```

**Emulator version**
Not sure how to get the version in nogui, but this is built from dev branch on the 5th April.

**Comment by dankcushions** [comment]
This is very strange. If I manually set
```
FullscreenMode = 1920 x 1080 @ 0.000000 hz
```
it works and displays menu items. If I remove this line, the described issue returns. btw, the line is not in the default generated config (I guess it is only there to override what duckstation uses automatically)

Verbose log: https://pastebin.com/319rgVFX

My only hunch is that without forcing 1080, duckstation is using a 4k video mode? My pi's /boot/config.txt is set to force 1080p but it's possible duckstation could override this via SDL/drm at runtime i think.

If this is the case, it would make sense as performance seems to be worse when I remove this line. I would suggest it should default to the current display resolution if possible.

**Comment by stenzek** [comment]
Few issues here:
 - The v3d driver doesn't support textures >4k x 4k, which is needed for higher resolutions to preserve full font resolution. It's not trivial to work around - downsampling the texture creates artifacts at the edges.
 - https://github.com/stenzek/duckstation/commit/32ac60414c6f5e7a746244a5ad5583ee58795c4c will use the current display resolution if no resolution is specified in the ini.
 - https://github.com/stenzek/duckstation/commit/0342d0a26e8452c8ca511a2e532b0d59107dcc63 fixes it using the incorrect resolution for KMS displays with Vulkan.
 - https://github.com/stenzek/duckstation/commit/19ca102b40e6ac5654d497096f6ce44d1b4e30c6 fixes the emulator getting wedged when toggling vsync/toggling fast forward on Mesa.

I haven't tested any of these on a Pi, but I don't see why it'd be different than the AMD GPU I was using.

**Comment by dankcushions** [comment]
Great thank you so much! I can at least confirm 
> 32ac604 will use the current display resolution if no resolution is specified in the ini.

... is working, and resolves my issue.

To be honest, given the pi4 struggles so badly beyond 1080p I think it would be a moot point if you fixed the UI for it at 4k modes. I'm happy to consider this fixed now it defaults to the display mode, as one of the first troubleshooting steps for RetroPie on Pi4 is "set to 1080p".

**Comment by stenzek** [comment]
I guess failing startup if it can't create the font atlas is probably a good idea here - UI isn't much use without any text. Will add that later.

And yeah, 4K on Pi is sluggish on a desktop, let alone an emulator drawing at 60fps.
