### ISSUE TITLE
[SCES-01444 Jackie Chan Stuntmaster ]

### ISSUE THREAD

**Issue by ViRuS-MaN** [stenzek/duckstation#1937]
i launch this game , i show the logo playsation , after that i show this screen

![screen](https://user-images.githubusercontent.com/62475321/113826235-370be080-9782-11eb-880e-a88a91adfba9.png)

and after this screen , i have a back screen

**Comment by stenzek** [comment]
Right click in game list ->  properties -> compatibility settings -> force interpreter.

Will push a compatibility update later.

**Comment by ViRuS-MaN** [comment]
thank now work fine
