### ISSUE TITLE
Codemasters Q3 2000 Demo (Europe) doesn't show the Playstation logo when using SCPH1000 BIOS

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1939]
Tested with all enhancements off, with a Redump verified copy, with interpreter and recompiler. When using SCPH1000 the game will hang on the BIOS screen for several seconds before jumping straight to the game without ever showing the Sony Playstation logo. I've also tested with SCPH1001 and SCPH7001 and they both work fine. I can test more if needed.

![SLED-03094_2021-04-07_20-35-36](https://user-images.githubusercontent.com/77198254/113853998-afee5500-97e1-11eb-837e-a2be350f900e.png)

**Comment by stenzek** [comment]
Why are you trying to load a PAL game on a Japanese BIOS......

The Japanese BIOSes have different behaviors with region checks. I believe later revisions check the region string as well, and won't boot non NTSC-J discs.
