### ISSUE TITLE
Shadows are broken in Ultraman - Fighting Evolution (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#194]
Happens with all renderers.

![SLPS-01248_2020-03-30_14-31-50](https://user-images.githubusercontent.com/31968468/77873080-9e03d900-7294-11ea-9dad-0fd06c1adc72.png)

Beetle PSX for comparison.

![Ultraman - Fighting Evolution (Japan)-200330-143631](https://user-images.githubusercontent.com/31968468/77873116-b83db700-7294-11ea-9551-c39d76eb5be5.png)

**Comment by stenzek** [comment]
What about the software renderer?

**Comment by kurayami6** [comment]
Looks fine in Software.

![SLPS-01248_2020-03-30_14-57-00](https://user-images.githubusercontent.com/31968468/77873836-cee50d80-7296-11ea-9ec8-60de07aafef4.png)

**Comment by stenzek** [comment]
Likely a mask bit issue then, similar to Silent Hill. Please test the software renderer in the future instead of stating "all renderers" when only testing the hardware renderers.

**Comment by stenzek** [comment]
Should hopefully be fixed https://github.com/stenzek/duckstation/commit/9446587e8fa7751b9977e7cdffe3a8f3b6d38d7c, please confirm when you have time.

**Comment by kurayami6** [comment]
Fixed.
