### ISSUE TITLE
Android - Trigger (L2 R2) always pressed - Xbox One S Wireless Controller

### ISSUE THREAD

**Issue by Mic-94** [stenzek/duckstation#1940]
**Game details**
All games

**Description of the issue / bug**
Trigger is always pressed up, when I Pressed it up then it's seems like the button is not pressed

**Controller Troubleshoot Report**
Im using Xbox One S Controller (Model 1708) - Contrell is working with native android games or on Windows - it's 100% functional

**Steps to reproduce**
1. Select Port 1
2. Select Controller type: Analog Controller (Dualshock)
3. Perform Automatic Mapping
4. Map Manually Trigers because automatic mapping do not map triggers and select button

**Hardware/software**
Xiaomi MI 6 - Android 9

**Emulator version**
0.1-3711

**Comment by stenzek** [comment]
Works fine for me with an xbox series controller on a oneplus 6 (Android 10). Unfortunately controllers are dependent on the device manufacturer providing drivers, and not screwing with the input maps.

Could you screenshot the bindings, particularly L1/L2?

**Comment by Mic-94** [comment]
![Screenshot_2021-04-08-08-28-53-554_com github stenzek duckstation](https://user-images.githubusercontent.com/82094596/113979061-1193db00-9845-11eb-8862-f6fd0b42ffc5.jpg)
I'm sending screenshot

> Works fine for me with an xbox series controller on a oneplus 6 (Android 10). Unfortunately controllers are dependent on the device manufacturer providing drivers, and not screwing with the input maps.
> 
> Could you screenshot the bindings, particularly L2/R2?

**Comment by stenzek** [comment]
Looks correct to me, same as mine. Could you follow https://github.com/stenzek/duckstation/wiki/Enabling-Logging and create a log where you press both triggers a few times?

**Comment by MojoJojoDojo** [comment]
I think I had that issue while I was using LInux with an Xbox One controller.

**Comment by Mic-94** [comment]
I don't have idea why but now it's working correctly. I don't even restarted my phone or reinstalled application. 
[duckstation.log](https://github.com/stenzek/duckstation/files/6281193/duckstation.log)

**Comment by stenzek** [comment]
Quite strange. If it happens again, grab a new log and I can investigate.

Controllers on Android are such a mess thanks to it being up to the vendor to provide support :(
