### ISSUE TITLE
"Shared" Rumble

### ISSUE THREAD

**Issue by soaresden** [stenzek/duckstation#1944]
**Game details**
[Serial Code, Region]
[i.e SLUS-00404 Ace Combat 2 (USA)]
Every game that supports Rumble (Gran Turismo, Resident Evil 2 ...Etc)

**Description of the issue / bug**
[Describe what you are seeing and/or hearing during gameplay]
For example, we start a duel race in arcade mode of gran turismo, and if the second player start the engine and the first player won't move, the first player got the vibration as well as the second ! As if it's a shared rumble

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
2. Which controller backend are you using in general settings

actually I have the very same issue on Batocera/Duckstation standalone. Both rumble are shared even if the rumble is configured distinctly
![image](https://user-images.githubusercontent.com/54243866/113916472-4d488980-97e0-11eb-8cd9-4e136b2f9a48.png)

**Note:**
If you are using Duckstation on Android device please consider the following before report:
Are you using any kind of "memory optimizer" program such as: Ccleaner, Wisecleaner, Clean Master, Boost Android etc. ?
(if so, please, consider create an exception on it first and test; or even remove / uninstall it retest and then, if the problem persists continue with the report.

**Steps to reproduce**
[Try to provide as much detail as possible to reproduce the issue]
Just configure each controller with rumble and play a rumble active game.
move one player only, and the second will get vibrations too !

**Enhancements information**
[Make sure they are all turned off before report]

**Hardware/software**
[If Android, which phone and Android version]
[If desktop, your CPU, graphics card, and operating system]
[GPU Renderer - D3D11/OpenGL/Vulkan]

**Emulator version**
[Shown in the title bar of the emulator]
![image](https://user-images.githubusercontent.com/54243866/113916581-6ea97580-97e0-11eb-8af1-ff409d89847a.png)

**Additional context**
[Add any other context about the problem here]

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/deeb8619182d6c935a866de0f9929dbadbbd74d3 (preview build).

No need to re-bind, was an error in how the bindings were being applied.
