### ISSUE TITLE
Could you add the possibility to enter custom aspect ratio please ?

### ISSUE THREAD

**Issue by SuperLumberjack** [stenzek/duckstation#1945]
Hello ! :-)

Two days ago, some people recommanded me your wonderful emulator and I have to say that I'm really impressed ! The picture quality is amazing !

Until now, I was using the "PCSXR-PGXP" emulator with the "Pete's OpenGL Windows GPU Version 1.78" video plugin. But it's clear that your emulator is so much better and simpler to use. Great job ! ;-)

The only thing which frustrated me was the aspect ratio in some games. Yes, it's consistent with the picture as it should have been displayed originally on a CRT TV. But I think that in some cases, today it's not consistent with a correct aspect ratio for our modern screens.

I will explain that with some pictures. I tried "Tomb Raider" and "Crash Bandicoot" and yes the aspect ratio is consistent with what it was originally. But if we compare for example the aspect ratio of Tomb Raider with the PC version, the aspect ratio doesn't match.

Here is the picture with your emulator (I enabled the widescreen hack, just to try, there are some glitches, but it doesn't change the problem in fact) :

![Tomb Raider I - DuckStation emulator - Widescreen hack Auto aspect ratio](https://user-images.githubusercontent.com/82117649/113922921-30b04f80-97e8-11eb-8c4b-7cc14cac9982.png)

We can notice that the picture is more compressed horizontally if we compare with the PC version. Here is the PC version :

![Tomb Raider I - PC version ATI GLRage](https://user-images.githubusercontent.com/82117649/113922984-46be1000-97e8-11eb-8870-03ea7419a2f4.png)

The "Pete's OpenGL Windows GPU Version 1.78" plugin with the PCSXR PGXP emulator, displays a different aspect ratio to match the aspect ratio of the PC version (the FOV is different with the PS1 version but the AR is correct here) :

![Tomb Raider I - PCSXR PGXP emulator with OpenGL plugin 1 78](https://user-images.githubusercontent.com/82117649/113923005-4f164b00-97e8-11eb-8f3a-37bffeb05ad8.png)

The only way to get a aspect ratio close to this with DuckStation is to force a 3:2 aspect ratio (I disabled the widescreen hack) :

![Tomb Raider I - DuckStation emulator - 3 2 aspect ratio](https://user-images.githubusercontent.com/82117649/113923039-59384980-97e8-11eb-84cf-9f442faf1998.png)

But the picture should have a resolution of "1656 x 1080" instead of "1620 x 1080" (3:2 AR) to have a correct aspect ratio.

**So my request is : could you add the possibility to enter a custom aspect ratio in the settings please ?_**

(with decimal numbers it would be better I think)

The problem is that it impacts the aspect ratio of the FMV too. So ideally it would be better to have a aspect ratio for the FMV and another for the graphics.

I think this option would be useful, because some games could be better too with a more correct aspect ratio.

We can see here that the aspect ratio is correct for "Crash Bandicoot" with PCSXR-PGXP and the OpenGL plugin 1.78 if we observe the circle with the dog :

![Crash Bandicoot - PCSXR PGXP emulator with OpenGL plugin 1 78](https://user-images.githubusercontent.com/82117649/113923112-6fdea080-97e8-11eb-918d-283c9b14c083.png)

But with DuckStation and the "Auto" aspect ratio, the circle isn't perfectly circular :

![Crash Bandicoot - DuckStation emulator - Auto aspect ratio](https://user-images.githubusercontent.com/82117649/113923122-73722780-97e8-11eb-8dff-07fe3fb83e05.png)

But beyond all of that, your emulator is close to perfection ! :+1: 
So thanks to you !

(sorry for my bad english)

**Comment by 6lackmag3** [comment]
Try changing crop mode.

**Comment by SuperLumberjack** [comment]
Thanks !

But I already tried. With Tomb Raider it isn't correct.

**Comment by SuperLumberjack** [comment]
You were correct **6lackmag3** ! ;-)

But the fact that I had to change the crop option reveals I think the real problem with the aspect ratio setting. Indeed, for Crash Bandicoot for example, I can have the correct aspect ratio if I choose the 4:3 aspect ratio and choose "All Borders" in the "Crop" option :

![DuckStation settings - Aspect Ratio](https://user-images.githubusercontent.com/82117649/113950928-cf51a600-9812-11eb-90f1-829075ff0ceb.png)

![Crash Bandicoot - DuckStation 4 3 aspect ratio all borders](https://user-images.githubusercontent.com/82117649/113951333-ada4ee80-9813-11eb-9548-a1ed2ebd8668.png)

But **here is the big problem for me** : I have to add borders to have the correct aspect ratio and... **the crop option change the aspect ratio** !

**I suggest to fix precisely the aspect ratio (DAR instead of PAR), so the crop option doesn't change it. Or maybe better : to propose an option to check, to preserve the aspect ratio !**

And of course, it would be cool to add the possibility to add some custom aspect ratios, with a decimal number or by entering a specific resolution. For Tomb Raider it's the only solution ^_^

What do you think ?

**Comment by TzakShrike** [comment]
I have to admit I've been aware of this issue for some time, as I was affected when it first started happening about 6 months ago, but I only ever mentioned it in passing.

**Comment by stenzek** [comment]
DuckStation is not pcsxr - if you want it to behave like that, please use it instead. In this case, it would require non-constant values in the widescreen hack expression, which would have an impact on speed - it's a concern since this code executes for every polygon.

You could use the stretch to fill option and size the window appropriately I guess.

**Comment by ggrtk** [comment]
Other emulators are a notoriously poor point of reference for aspect ratio comparisons. Many of them do not properly simulate the GPU+VDAC output and so are missing CRT effects that a number of games rely on.

There's little point in comparing to PC ports either, as they could be using aspect ratios or resolutions that are different from what is used on the PS1 version.

Custom display aspect ratios would mean using a slow path for the widescreen hack, but if we made it so that the widescreen hack did not apply when the aspect ratio is customized, people would probably complain that the widescreen hack isn't working.

Please understand that the default settings are as they are because they are suited for the general case. "All Borders" is not appropriate for this because it ignores CRT positioning parameters that many games use for proper visible centering and other graphical effects. Getting perfect circles on one game may result in imperfect circles on another game due to how those games are individually programmed, and that's not something that is our responsibility to fix or account for.

**Comment by SuperLumberjack** [comment]
OK. I perfectly understand. Thank you both for your answers ! ;-)

It's a bit pitiful, because as I said, beyond that this emulator is close to perfection and I could easily abandon PCSXR-PGXP for only use DuckStation.

I think some habits of the era of the CRTs aren't relevant anymore because we are using digital screens now and we can correct more easily some mistakes done in the past. But I understand how it would be complicated to implement custom aspect ratios.

But I wonder, wouldn't be possible if we simply precise in the settings that the widescreen hack can't be used when a custom aspect ratio is chosen ?

**Comment by SuperLumberjack** [comment]
I forgot to say that I tried to create a custom resolution in my Nvidia control panel. It could be the solution. It works in fact.

The only problem is when I take screenshots or capture a video. The aspect ratio is the original, not the one which is displayed.

**Comment by SuperLumberjack** [comment]
Hello again! :-)

I just wanted to say that **I found the perfect display settings for a modern screen**.
But you were right! With the "_Aspect Ratio_" set on "_Auto (Game Native)_" and the "_Crop_" option set on "_Only Overscan Area_", we have the same picture than on a CRT as we can see here with the game "_Legacy of Kain: Soul Reaver_":

![01 - DuckStation - Soul Reaver PS1 - AR Auto (Game Native)   Crop Only Overscan Area](https://user-images.githubusercontent.com/82117649/115906475-d9f17980-a467-11eb-8959-8e16f090ca2b.png)

![02 - Soul Reaver PS1 on Sony PVM](https://user-images.githubusercontent.com/82117649/115906495-dfe75a80-a467-11eb-8e00-a5b24cb646e4.png)

_(source of the 2nd picture: https://youtu.be/HMvZnHxPqe4 )_

But for me, on a modern screen it's definitely better to set the "_Aspect Ratio_" on "_4:3_" and the "_Crop_" option on "_All Borders_", because as you can see here, the PS1 version perfectly match the PC version (and the Dreamcast version too) in this case:

![03 - DuckStation - Soul Reaver PS1 - AR 4 3   Crop All Borders](https://user-images.githubusercontent.com/82117649/115906934-7ddb2500-a468-11eb-998c-88fc9abc6bd3.png)

![04 - Soul Reaver PC](https://user-images.githubusercontent.com/82117649/115906951-84699c80-a468-11eb-99cd-8e5bb7cb49a1.png)


**By the way, I would like to take the opportunity to talk about _a sound issue_ that I have with the warp gates in this game** (that we can see on the pictures above). When I change the destination with one of these gates, there is a sort of lag with the sound.

With the PCSXR-PGXP emulator, it's the opposite. There is no sound issue, but a graphic issue.


Thanks for your help!

**Comment by SuperLumberjack** [comment]
I fixed the issue with "_Vulkan_" instead of "_DirectX 11_" :-)

It was the antialiasing which was using too much resources.
