### ISSUE TITLE
Frame rate drop after updating to latest version

### ISSUE THREAD

**Issue by Lilly-98** [stenzek/duckstation#1947]
I haven't seen anyone else post about this but ever since I updated to the latest version I have been getting frame rate drops in all of my games. For example Spyro Year of the Dragon and Tomba. In Spyro it will lag when I am behind the Sunny Villa portal or when I'm in Cloud Spires and Tomba's frame rate will drop when playing after a while then go back to normal and then do it again. I don't know if it's my computer doing it but it was running smooth before I updated duckstation. I'm sorry if this is a stupid question but is this supposed to happen after updating or is it a bug?

**Comment by stenzek** [comment]
Please fill out the issue template - can't help you without that.

Couple of things to try:
 - enabling optimal frame pacing
 - enabling sync to host refresh

But nothing really has changed in the last few weeks which would affect performance.
