### ISSUE TITLE
Joshikousei no Houkago... Pukunpa (Japan): Missing Menu items and Graphical Issues

### ISSUE THREAD

**Issue by waspennator** [stenzek/duckstation#1949]
**Game Details**
Joshikousei no Houkago... Pukunpa (Japan) SLPS-00409
Redump Verified

**Description of the issue / bug**
Start screen, main menu, etc seems to be having issues with missing menu buttons, character select also looks weird as well as various other graphical issues persisting into gameplay (gameplay hud elements missing, certain characters colored wrong), tested on all of the graphic backends.

**Steps to reproduce**
Boot the game up with any backend and it should be noticeable on the title screen, main menu, and character select and into gameplay

**Enhancements information**
None

**Hardware/software**
i5 6600k
Geforce GTX 1070
Windows 10
Vulkan (Tested with all backends, but this is the one I mainly use)

**Emulator version**
0.1-3754-Preview

**Additional context**
![SLPS-00409_2021-04-08_14-19-35](https://user-images.githubusercontent.com/78768499/114093839-d6ab9a80-9878-11eb-96b3-863816e44126.png)
![SLPS-00409_2021-04-08_14-19-40](https://user-images.githubusercontent.com/78768499/114093853-dad7b800-9878-11eb-9b56-fb0e50d1a467.png)
![SLPS-00409_2021-04-08_14-39-36](https://user-images.githubusercontent.com/78768499/114093859-dca17b80-9878-11eb-83e9-d9342ab3e44a.png)

**Comment by stenzek** [comment]
Looks like a corrupted palette ending up in VRAM, could be coming from the CD-ROM or elsewhere. Needs further research.

**Comment by waspennator** [comment]
I also noticed that in game, certain characters on certain players side seem to absolutely screw up the coloring for whatever reason, doesn't happen with all of them, but it happens with a select few of them depending on which side they get picked for. Only have one controller so wasn't able to test out the P2 side much, but this happens if you pick the top left character as p1.

![SLPS-00409_2021-04-09_21-47-44](https://user-images.githubusercontent.com/78768499/114257510-bb768300-997d-11eb-89b9-c3c5b2b30332.png)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/6a0bd7ee644b6dc93a998bb24010eb004cf92290 - the game was spamming redundant read commands to the CD-ROM controller, and the seek pending flag wasn't getting cleared.

**Comment by waspennator** [comment]
Tested it again and yep, the title screen, menu, character select look normal now, gameplay ui is finally showing up and certain characters aren't having their color palettes mangled for whatever reasons, so yep, that fixed it.

Only thing i'm still kinda curious about is the unknown SPU register write for 0x19C and E, now that I noticed it in the logs.

**Comment by stenzek** [comment]
Unused registers in the SPU, plenty of games seem to clear them but it has no effect. It may have been part of SDK's SPU reset routine.
