### ISSUE TITLE
Multiple graphical glitches in Disney's Atlantis - The Lost Empire (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#195]
When using the software renderer there's a coloured square in the top left corner of the screen, a glitchy line running through the dialogue box and the character portrait doesn't render.

![Capture2](https://user-images.githubusercontent.com/31968468/77974049-c1d12880-7341-11ea-962e-8c67a6fe87da.PNG)

Item pictures are broken and there's a purple line and dots on the screen.

![Capture3](https://user-images.githubusercontent.com/31968468/77974187-1c6a8480-7342-11ea-8bb6-967b0271ff32.PNG)

Using OpenGL or D3D11 fixes some of these problems but not all.

![SCUS-94636_2020-03-31_11-01-33](https://user-images.githubusercontent.com/31968468/77974250-4ae85f80-7342-11ea-9963-2dc338650f16.png)

![SCUS-94636_2020-03-31_11-06-29](https://user-images.githubusercontent.com/31968468/77974261-5176d700-7342-11ea-8aa5-db91c22aec63.png)

**Comment by stenzek** [comment]
Please re-test on latest master.

**Comment by kurayami6** [comment]
Fixed. Thanks.
