### ISSUE TITLE
Formula One Arcade (Europe) crashes DuckStation after the Loading screen after Booting.

### ISSUE THREAD

**Issue by danylopez123** [stenzek/duckstation#1955]
**Game details**
SCES-03886 Formula One Arcade (Europe) (En,Fr,De,Es,It)

**Description of the issue / bug**
When Booting the game, after the first loading screen, when it tries to load into the main menu, it crashes with this window:
![imagen](https://user-images.githubusercontent.com/17708894/114271539-25d90300-9a12-11eb-83cf-1dc8ef1c85c3.png)
Even trying to break into a debugger crashes DuckStation.

**Steps to reproduce**
Launch the game, wait for the first loading screen, crash.

**Hardware/software**
CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60 GHz (8 CPUs), ~3.6GHz
Graphics Card: NVIDIA GeForce GTX 1050 Ti
Operating System: Windows 10 Pro
GPU Renderer - D3D11

**Emulator version**
DuckStation 0.1-3712-ge94c68e8 (dev)

**Comment by stenzek** [comment]
What happens if your switch to the interpreter? The other F1 games need it because they rely on stale code executing out of icache.

**Comment by danylopez123** [comment]
Huh.. that seems to fix the problem by changing the Execution Mode to Interpreter.
I mostly don't touch that option because i dont know what it can do but.. oh well, thanks for fixing my problem.
Closed.

**Comment by stenzek** [comment]
Great, I'll push a compatibility update later to auto enable it. Better to leave it on recompiler globally for speed.
