### ISSUE TITLE
Morita Kazurou no Chess (Japan): Title Screen Inconsistently Long Load Time

### ISSUE THREAD

**Issue by waspennator** [stenzek/duckstation#1956]
**Game details**
SLPS-02488 Morita Kazurou no Chess (Japan)
Redump Verified

**Description of the issue / bug**
While loading times for this game seems to usually be under 20 seconds most times using a mixture of actual hardware and other emulators like Ares, Beetle, and Mednafen. Duckstation seems to take around 35 seconds loading this up from the title screen, to the text box that makes a little jingle noise when it pops up and I don't know why.

Tested from the title screen up until the text box with the jingle noise comes up:

Ares: 15 Seconds the first time, 13 the second, 19 the third, 14 the fourth. (Tested multiple times since it seemed to vary dependingly, but stayed under 20 seconds all the time)

Beetle: 22 seconds the first time, 21 the second.

Mednafen: 16 seconds first, second, and third times.

Actual Hardware: 18 seconds aroundish

Duckstation: 35 seconds consistently (Checked out the logs too and it seems when you hit start, it does some wait for read messages, pops up 2 unknown SPU register write stuff, then writes to memory card sector 63 while loading for 35 seconds and slowly going through read messages.)

**Steps to reproduce**
Boot the game and wait until you hit the title screen with the flashing text box, then time it once you hit start, it should hit 35 seconds by the time the popup and the ding noise sounds off

**Hardware/software**
i5 6600k
Geforce GTX 1070
Windows 10
Vulkan 

**Emulator version**
0.1-3769 Preview Build

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/67344070ea86944e8bb5f4bc11d04565bd533528
