### ISSUE TITLE
Dead or Alive (USA), Visual Garbage on Training Stage

### ISSUE THREAD

**Issue by waspennator** [stenzek/duckstation#1958]
**Game details**
SLUS-00606 Dead or Alive (USA)
Redump Verified

**Description of the issue / bug**
For whatever reason on training mode, if you have forced interlaced mode enabled, there's this garbage texture line that appears in the training stage that takes up the middle of the screen. It's not as noticeable if you turn off forced interlacing, but it's still there if you jump close enough to the opponent. Tested with all the graphic backends and it happens across all of them.

**Steps to reproduce**
With Forced Interlacer: Start the game, go to training, select any character and when the match finally loads, the middle of the screen should have a garbage line texture in the middle once it centers out

Without Forced Interlacer: Same as before, but this time get close to the opponent and start jumping, you should notice some weird texture issues in the middle.

**Hardware/software**
i5 6600k
Geforce GTX 1070
Windows 10
Vulkan 

**Emulator version**
0.1-3769 Preview Build

**Additional context**
With Forced Interlacer on: 
![SLUS-00606_2021-04-11_09-59-35](https://user-images.githubusercontent.com/78768499/114311935-0394c300-9aae-11eb-8d02-c9cf6338cec4.png)

Without Forced Interlacer on: 
![SLUS-00606_2021-04-11_10-05-02](https://user-images.githubusercontent.com/78768499/114311948-13140c00-9aae-11eb-9aa3-94684642ee82.png)

**Comment by stenzek** [comment]
Are you toggling the option while it's running? I remember looking into this a while back, it requires interlacing on, and a reboot if you toggled it.

**Comment by waspennator** [comment]
First time I tested it, I had the interlacer on and the garbage line texture appeared in the middle, then I set the interlacer off, used the default boot option for the game from the game list, went into training mode and while the line isn't as noticeable, it is still there.

**Comment by stenzek** [comment]
Yep, I see. It clears the screen in two parts, and offsets the second by 2 rows instead of 1, which leaves the streak. Will need to research further, as I think this might be a regression.

**Comment by stenzek** [comment]
ODE bit timing related, fix is in the works.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/88618bde1c7164ab146d906e6b623aa49855ea98 (preview build).

I've also removed the force interlacing override, as it seems to work fine without it. You'll need to either rescan for it to pick up the new value, or manually go into game properties and uncheck `Force Interlacing`.

**Comment by waspennator** [comment]
Testing it out again and I can confirm that with forced interlacing on, the garbage texture line no longer shows up anymore. Only thing I did notice is that with the interlacer off, I tried jumping around again and noticed this again around the middle, though i'm unsure if it's something with the game or not at this point. 
![SLUS-00606_2021-04-14_11-54-10](https://user-images.githubusercontent.com/78768499/114757684-64740380-9d19-11eb-890e-070a80b49ea8.png)
