### ISSUE TITLE
Dying in Syphon Filter (USA) (v1.0) crashes the emulator

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#196]
Quickest way to do it is to go through the restaurant, jump out the window, shoot the lock off the gate and jump down the hole to your death. The game will freeze on a black screen before the emulator becomes unresponsive and crashes.

![SCUS-94240_2020-03-31_12-15-02](https://user-images.githubusercontent.com/31968468/77976741-82a6d580-7349-11ea-9526-6b9a4434d9e1.png)

![SCUS-94240_2020-03-31_12-15-09](https://user-images.githubusercontent.com/31968468/77976786-a5d18500-7349-11ea-83b9-c73f63a78837.png)

![SCUS-94240_2020-03-31_12-15-18](https://user-images.githubusercontent.com/31968468/77976790-ab2ecf80-7349-11ea-8535-022d71ba92df.png)

![Capture](https://user-images.githubusercontent.com/31968468/77976812-b8e45500-7349-11ea-8aec-aeb464407c43.PNG)

**Comment by stenzek** [comment]
Needs pausable linked list DMA/GPU timings.

**Comment by stenzek** [comment]
Should be fixed on latest master.
