### ISSUE TITLE
[Vulkan and D3D11] Fuujin Ryouiki Eretzvaju (Japan, Asia): Character portrait flickering

### ISSUE THREAD

**Issue by waspennator** [stenzek/duckstation#1960]
**Game details**
SLPS-01790 Fuujin Ryouiki Eretzvaju (Japan, Asia)
SLUS-00855 Evil Zone (USA)
Redump Verified

**Description of the issue / bug**
For some reason when using Vulkan or D3D11 as the graphic back ends, certain character portraits on the character select screen will start weirdly flickering slightly, this does not occur on the Software or OpenGL backends so i'm guessing it's something to do with those two. Tested the US version and it also happened on there too, so it's likely happening with all versions of the game.

**Steps to reproduce**
Start the game and go straight into practice mode, on the Vulkan/D3D11 backends, certain portraits on the left and bottom right should be flickering slightly, but the Software and OpenGL backends should look normal.

**Hardware/software**
i5 6600k
Geforce GTX 1070
Windows 10
Vulkan 

**Emulator version**
0.1-3777 Preview Build

**Additional Context**
Recording using Vulkan and D3D11 (Look at the portrait's eyes on the P1 side and the bottom right on the P2 side and you should notice the flickering)

https://user-images.githubusercontent.com/78768499/114446506-89883b00-9b8e-11eb-9739-7fd7da301ff1.mp4

Recording using Software and OpenGL

https://user-images.githubusercontent.com/78768499/114446720-c9e7b900-9b8e-11eb-9681-a217f5760435.mp4

**Comment by stenzek** [comment]
Seems to be rasterization precision related, and only happens on NVIDIA GPUs. Other games have similar issues, it's just not as noticeable.

Long term I'm planning on writing a software renderer using compute shaders, which will be able to accurately model the PS1 GPU's rasterization quirks as well as upscaling. I don't think it will ever be possible to get "perfect" rendering with full hardware renderers, let alone across all vendors with tiny variances.

**Comment by waspennator** [comment]
So would this mean this would ever be fixable in the future or is the only real option is to swap over to another renderer for different games?

**Comment by stenzek** [comment]
Correct. Using upscaling also works around the precision issue, at least on my NVIDIA GPU.

WARP is fine at 1x, so AMD and Intel might be as well, but would have to check.

**Comment by Shideravan** [comment]
I'm unable to replicate in 0.1-4736-gbacd834. Was this fixed?

**Comment by waspennator** [comment]
Testing this out again with the latest preview version, I don't know what changed, but apparently this is actually fixed now.

**Comment by stenzek** [comment]
It's likely just gpu dependent.
