### ISSUE TITLE
Soviet Strike lag +/- 17 fps

### ISSUE THREAD

**Issue by SlayerFFP** [stenzek/duckstation#1961]
**Game details**
[SLUS-00061 Soviet Strike (USA)]

**Description of the issue / bug**
[Média de 17 fps, e varia pra menos que isso, testei todos os modos de video com resolução interna x1]

![Screenshot_3](https://user-images.githubusercontent.com/82417276/114465654-c881b500-9bbd-11eb-80f7-731b37ba839b.png)
**Hardware/software**

[ Windows 10, intel hd 620, 16gb ram, ssd 120, i37100u]

tentei todos os modos

**Emulator version**

[0.1-3777-g62718b3c]

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/13b398ac46aa375fa1bfc547cb35c0d8ecffb13a (preview build).

Keep in mind this game runs at quite a low frame rate internally anyway. Overclocking may improve it.

**Comment by SlayerFFP** [comment]
> Fixado em [ 13b398a ](https://github.com/stenzek/duckstation/commit/13b398ac46aa375fa1bfc547cb35c0d8ecffb13a) (compilação de visualização).
> 
> Tenha em mente que este jogo é executado a uma taxa de quadros bastante baixa internamente de qualquer maneira. O overclocking pode melhorá-lo.

Thanks man, I appreciate your reply
