### ISSUE TITLE
[Request] Using aimtrak with sight on galaxian 3

### ISSUE THREAD

**Issue by zerdarker** [stenzek/duckstation#1962]
the pointer of galaxian 3 does not work with the aimtrak gun, with the mouse it is taken into account in the game.
But with the aimtrak configured in guncon the buttons of the gun work as well as the trigger but not the integrated sight in the game.

Is it possible to make the sight work in the game?

Thanks a lot it is a great emulator

**Comment by stenzek** [comment]
Not really sure if I can do much here. I don't own any of these lightguns, so all I can do is ensure it works with a mouse.

**Comment by stenzek** [comment]
Closing since I have no plans to buy one of these.
