### ISSUE TITLE
Audio Issue (Windows)

### ISSUE THREAD

**Issue by Carl393** [stenzek/duckstation#1964]
Does Duckstation Support SPDIF audio output?

Currently during Final Fantasy VII game, I can hear music during cut-scenes (cinematic movie sections) however not the sound effects. (I'm using a professional Audio Card)

otherwise The audio works during normal gameplay (music with sound effects)

Thank you!

**Comment by stenzek** [comment]
That would be up to your sound driver. DuckStation just outputs a single stereo audio stream with everything mixed in prior.

**Comment by Carl393** [comment]
ah ok! I'll try outputting via RCA (analog) output and see what happens!
maybe SPDIF output isn't sent from the emulator by default. we'll see what
happens!

Thank you!

Carl

**Comment by stenzek** [comment]
DuckStation doesn't know nor care about what the output type is. Like I said, it just hands off a 16-bit 44.1khz stereo stream to Cubeb/SDL/etc. Some parts of the audio being missing suggests another issue, maybe a bad dump.

**Comment by Carl393** [comment]
Thanks!

Carl
