### ISSUE TITLE
Add anti-dithering and CRT shaders for games with dithering in the assets

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [stenzek/duckstation#1965]
**Is your feature request related to a problem? Please describe.**
Although the True Color hack removes the dithering in many games, some have dithering patterns in sprites and textures and can't be removed that way. An example is some parts of Suikoden II, a 2D RPG.

**Describe the solution you'd like**
There are many shaders that could minimize or remove the effect: CRT shaders, anti-dithering shaders, LCD...

**Describe alternatives you've considered**
Libretro project has many shaders, even GLSL, but they are apparently not compatible with Duckstation and throws an small error when I try them.
https://github.com/libretro/glsl-shaders

**Additional context**
![SLUS-00958_2021-04-13_14-23-30](https://user-images.githubusercontent.com/16591467/114551536-d8ec6b00-9c63-11eb-8dcf-f8a01d4afa7b.png)

**Comment by stenzek** [comment]
The textures are 16 bit, it's not like you can just magically create more detail when there's none to begin with.

I suppose you could use a post shader to smooth it out - but I don't consider shaders part of the emu itself.
