### ISSUE TITLE
Not able to run AppImage on Ubuntu 18.04

### ISSUE THREAD

**Issue by kdnanmaga** [stenzek/duckstation#1967]
**Description of the issue / bug**
I tried running the AppImage on my 64 bit Ubuntu 18.04 and got the following error:
`./duckstation-nogui-x64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./duckstation-nogui-x64.AppImage)`

**Hardware/software**
CPU - Intel i5
OS - Ubuntu 18.04
Graphics card: VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)

**Comment by stenzek** [comment]
I only support the latest Ubuntu LTS with the appimage. Qt in particular has issues with the older version which comes with 18.04.

You can still build from source, assuming the dependencies are recent enough. 

Still, kinda silly that it uses the system libc, I thought appimages were meant to solve that problem.. :/

**Comment by kdnanmaga** [comment]
I tried building from source which gave me a host of other errors which I do not want to get into right now. Guess its time to do my long pending upgrade to the latest Ubuntu LTS.

Thanks for replying! :)
