### ISSUE TITLE
PlayStation Zone CD Vol. 1 (Germany): Eliminator Demo doesn't stop loading

### ISSUE THREAD

**Issue by waspennator** [stenzek/duckstation#1968]
**Game details**
SLED-01633 PlayStation Zone CD Vol. 1 (Germany)
Redump Verified

**Description of the issue / bug**
For whatever reason, trying to play Eliminator ends up causing it to get stuck on an infinite loading screen until you reset the emulator. Checking the logs seem to say something about async interrupt 1 not being properly set cause one's already unacknowledged. Tested it out on the full version and it happens as well, so it seems like a regression of #227

**Steps to reproduce**
Once you get to the main menu, click on demos and then click on the eliminator demo, no matter how long you wait, it should be stuck on the first bar and not load.

**Hardware/software**
i5 6600k
Geforce GTX 1070
Windows 10
Vulkan 

**Emulator version**
0.1-3784 Preview Build

**Additional Context**
![SLED-01633_2021-04-14_12-36-50](https://user-images.githubusercontent.com/78768499/114762317-db5fcb00-9d1e-11eb-95f2-89bd01731f63.png)
![Duckstation log5](https://user-images.githubusercontent.com/78768499/114762338-e0bd1580-9d1e-11eb-9cf5-236165d6006c.png)

**Comment by stenzek** [comment]
Full version is fixed with https://github.com/stenzek/duckstation/commit/62360d088aee8d16da4309d8fa665ff2b0b5d14b, can't check the demo.

It regressed because the CPU/RAM timing is more accurate now.

**Comment by waspennator** [comment]
Tested both versions again to check and can confirm that both the demo and the full version can now boot past the loading screen without soft locking forever.
