### ISSUE TITLE
Test drive le mans - Loading bar out of range

### ISSUE THREAD

**Issue by SlayerFFP** [stenzek/duckstation#1969]
**Game details**
slus 01077 test drive le mans

**Description of the issue / bug**
loading bar is out of range

**Hardware/software**
[ Windows 10, intel hd 620, 16gb ram, ssd 120, i37100u]

**Emulator version**
0.1-3784-g88618bde
![Screenshot_4](https://user-images.githubusercontent.com/82417276/114775643-e713b780-9d47-11eb-91af-bf391616e29a.png)

**Comment by stenzek** [comment]
Looks fine here. Did you test with all enhancements disabled?

![SLUS-01077_2021-04-22_14-05-37](https://user-images.githubusercontent.com/11288319/115654146-de3c6a80-a373-11eb-9527-23bb22be6d58.png)

**Comment by stenzek** [comment]
Closing due to lack of response. If this is still happening without enhancements, please provide clear and exact details on how to reproduce the issue.
