### ISSUE TITLE
PlayStation Zone CD Vol. 3 (Germany): Music Demo Loading Too Quickly?

### ISSUE THREAD

**Issue by waspennator** [stenzek/duckstation#1970]
**Game details**
SLED-01773 PlayStation Zone CD Vol. 3 (Germany)
Redump Verified

**Description of the issue / bug**
Testing around with the other emulators and actual hardware again, I think Duckstation might be loading the music demo a bit too quickly, considering it finishes loading in under a minute, least compared to the other emulators and hardware (Not counting Ares).

Beetle: test 1 = 1 minute, 10 seconds
Beetle: test 2= 1 minute, 9 seconds

Ares test 1 = 25 seconds
Ares test 2 = 25 seconds

Mednafen test 1 = 1 minute, 22 seconds
Mednafen test 2 = 1 minute, 22 seconds

Duckstation test 1 = 55 seconds
Duckstation test 2 = 55 seconds

Real hardware test 1 = 1 minute,14 seconds
Real harware test 2 = 1 minute,9 seconds

**Steps to reproduce**
Boot the game up, go to the demos, move over onto the music demo, start it, and as soon as you see the instruction menu with the character spinning the record on the bottom, start the timer and then stop it once it gets to the funky music and visuals, on Duckstation at least it should finish at around 55 seconds.

**Hardware/software**
i5 6600k
Geforce GTX 1070
Windows 10
Vulkan 

**Emulator version**
0.1-3784 Preview Build

**Comment by stenzek** [comment]
Sounds like it's within the margin of error. Even on console, no two units will perform exactly the same.
