### ISSUE TITLE
Kids Station - Oshaberi Oekaki Kikansha Thomas to Nakamatachi (Japan): Will not move past title screen

### ISSUE THREAD

**Issue by waspennator** [stenzek/duckstation#1971]
**Game details**
SLPS-03515 Kids Station - Oshaberi Oekaki Kikansha Thomas to Nakamatachi (Japan)
Redump Verified

**Description of the issue / bug**
I think this might actually be broken in all the emulators least from what i've seen, most footage i've seen of this game as well doesn't seem to go past the title screen, so I dunno if it's missing something or if this is just the entire game. I know my controller works cause I can skip the one intro cutscene before the title screen pops up, as well as the attract movies that play if you wait long enough on the title screen, but no matter what I press, it doesn't move past this. Only guess I got is that maybe it requires a certain peripheral support, like the Kids Station Controller to work past the title screen, unless it's something else?

**Steps to reproduce**
Start the game, repeatedly press X to confirm that you can skip past the one FMV before the title screen pops up, then start pressing anything, nothing should work and you'll be stuck on the title screen.

**Hardware/software**
i5 6600k
Geforce GTX 1070
Windows 10
Vulkan 

**Emulator version**
0.1-3784 Preview Build

**Comment by stenzek** [comment]
Has this been verified on console?

**Comment by gameblabla** [comment]
https://www.youtube.com/watch?v=THH8FwGS4MQ

I tried it on my PAL PS1 and i can't get past the titlescreen either.
You can still press X on the "attract movies" and get back to the titlescreen again, which leads me to believe it's not the whole game and that's indeed a titlescreen.
I could make a helicopter appear by pressing Select on the second controller. (this only worked on my official dualshock, my 3rd party one couldn't make it appear.)
Despite that however, i was still unable to get past the titlescreen.
I can only assume this needs a KIds Station controller (which i don't have) and my guess is that the Kids Station probably has its own controller ID (much like how the digital, dual shock... have different ones). That's only a worth guess though.

**Comment by stenzek** [comment]
Good enough for me. Many thanks for confirming.
