### ISSUE TITLE
Can't build on Linux: cubeb_oss.c: undefined reference to symbol strlcpy@@LIBBSD_0.0

### ISSUE THREAD

**Issue by it9exm** [stenzek/duckstation#1977]
**Game details**
N/A

**Description of the issue / bug**
Hello, I am trying to build duckstation from source on Linux but it gets stuck at this point, with both standard make and ninja.

```
[ 85%] Linking CXX executable ../../bin/duckstation-nogui
/usr/bin/ld: ../../dep/cubeb/libcubeb.a(cubeb_oss.c.o): undefined reference to symbol 'strlcpy@@LIBBSD_0.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libbsd.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/duckstation-nogui/CMakeFiles/duckstation-nogui.dir/build.make:201: bin/duckstation-nogui] Errore 1
make[1]: *** [CMakeFiles/Makefile2:2283: src/duckstation-nogui/CMakeFiles/duckstation-nogui.dir/all] Errore 2
make: *** [Makefile:136: all] Errore 2
```
A long time ago (around Fall 2019) I was able to build the 0.1 version, but I haven't tried since. Is everything ok with cubeb?

**Controller Troubleshoot Report**
N/A

**Steps to reproduce**
Tried to build following the steps on README.md

**Enhancements information**
N/A

**Hardware/software**
Fujitsu A555G, Intel i5-5200, AMD Radeon R7 M260, Debian sid

**Emulator version**
Latest Master

**Additional context**
Sorry for not filling the issue template in the previous report.

**Comment by stenzek** [comment]
Looks like a cubeb bug, I guess you have OSS installed/available on your system. We probably don't want to use it anyway...

Try this patch:

```diff
diff --git a/dep/cubeb/CMakeLists.txt b/dep/cubeb/CMakeLists.txt
index 08e65e9e..5df8bfe4 100644
--- a/dep/cubeb/CMakeLists.txt
+++ b/dep/cubeb/CMakeLists.txt
@@ -114,7 +114,7 @@ if(USE_OPENSL)
 endif()

 check_include_files(sys/soundcard.h HAVE_SYS_SOUNDCARD_H)
-if(HAVE_SYS_SOUNDCARD_H)
+if(HAVE_SYS_SOUNDCARD_H AND NOT LINUX)
   try_compile(USE_OSS "${PROJECT_BINARY_DIR}/compile_tests"
     ${PROJECT_SOURCE_DIR}/cmake/compile_tests/oss_is_v4.c)
   if(USE_OSS)

```

**Comment by it9exm** [comment]
Thank you, it went all smooth with this patch.
And yes, I have oss-compat which provides support for legacy software. 
So cubeb has troubles in building with oss support. Shall we open an issue there?

**Comment by stenzek** [comment]
If cubeb standalone also has issues building, sure.

**Comment by stenzek** [comment]
Strange, I don't get any issues building with oss-compat on Ubuntu. Perhaps something else is indirectly pulling in `-lbsd`. Anyway, worked around it downstream in https://github.com/stenzek/duckstation/commit/aa57ec6105758704827483ec4a5d12764601e824
