### ISSUE TITLE
When launching from command line gui is still visible on exit

### ISSUE THREAD

**Issue by Blad3forc3** [stenzek/duckstation#1978]
Can we have an option to disable the gui when launching from the command line and exiting?

**Comment by andercard0** [comment]
> Can we have an option to disable the gui when launching from the command line and exiting?

Fill out the template. 


**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by Blad3forc3** [comment]
a command line option like -nogui so it runs but doesnt fully load and keep open duckstation on exit

**Comment by Josegg0** [comment]
You can add  -batch in the command line:  duckstation-qt-x64-ReleaseLTCG.exe -batch -fullscreen -- <path to game>

  -help: Displays this information and exits.
  -version: Displays version information and exits.
  -batch: Enables batch mode (exits after powering off).
  -fastboot: Force fast boot for provided filename.
  -slowboot: Force slow boot for provided filename.
  -resume: Load resume save state. If a boot filename is provided,
    that game's resume state will be loaded, otherwise the most
    recent resume save state will be loaded.
  -state <index>: Loads specified save state by index. If a boot
    filename is provided, a per-game state will be loaded, otherwise
    a global state will be loaded.
  -statefile <filename>: Loads state from the specified filename.
    No boot filename is required with this option.
  -fullscreen: Enters fullscreen mode immediately after starting.
  -nofullscreen: Prevents fullscreen mode from triggering if enabled.
  -portable: Forces "portable mode", data in same directory.
  -nocontroller: Prevents the emulator from polling for controllers.
                 Try this option if you're having difficulties starting
                 the emulator.
  -settings <filename>: Loads a custom settings configuration from the
    specified filename. Default settings applied if file not found.
  --: Signals that no more arguments will follow and the remaining
    parameters make up the filename. Use when the filename contains
    spaces or starts with a dash.

**Comment by stenzek** [comment]
`-batch` does this.
