### ISSUE TITLE
Toca world touring cars gets stuck on the loading screen before a race.

### ISSUE THREAD

**Issue by alex91093** [stenzek/duckstation#1979]
![Screenshot_20210417-145133_DuckStation](https://user-images.githubusercontent.com/82280569/115123795-a789dd00-9f8c-11eb-859e-a7df194367e8.jpg)

**Game details**
[Serial Code, Europe]
[i.e SLUS-00404 Ace Combat 2 (USA)]

**Description of the issue / bug**
[Game always stops loading at this exact spot before gameplay starts]

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
2. Which controller backend are you using in general settings

**Note:**
If you are using Duckstation on Android device please consider the following before report:
Are you using any kind of "memory optimizer" program such as: Ccleaner, Wisecleaner, Clean Master, Boost Android etc. ?
(if so, please, consider create an exception on it first and test; or even remove / uninstall it retest and then, if the problem persists continue with the report.

**Steps to reproduce**
[Try to provide as much detail as possible to reproduce the issue]

**Enhancements information**
[Make sure they are all turned off before report]

**Hardware/software**
[If Android, which phone and Android version]
[If desktop, your CPU, graphics card, and operating system]
[GPU Renderer - D3D11/OpenGL/Vulkan]

**Emulator version**
[Shown in the title bar of the emulator]

**Additional context**
[Add any other context about the problem here]

**Comment by Zet-sensei** [comment]
I assume that is the SLES-02572 version, as I see French language on the game interface.
The game is LibCrypt protected on PAL versions of the game.

If the game is stucked on the loading screen, it is the copy protection that is triggered and you didn't dyumped the correct full copy of your game.

![TOCA](https://user-images.githubusercontent.com/52127625/115127837-12153a00-9fda-11eb-9266-01fd865a9a58.jpg)

**Comment by stenzek** [comment]
Closing as the issue template was not correctly filled out, and likely a dump issue.
