### ISSUE TITLE
Input Bug - Resident Evil Director's Cut Dualshock Ver.

### ISSUE THREAD

**Issue by sappergr** [stenzek/duckstation#1985]
There is a wierd input bug in these games. When using a Xinput controller, analog stick to the right does not work in the menus. Here is a video demonstration:

https://youtu.be/kAEZrVxshBk

It actually affects all Resident evil titles that are able to use analog mode. In Resident Evil 3 Nemesis its actually worse, niether left or right analog input works in the menu.
This was tested with no enhancements and with xinput controller backend.

**Comment by stenzek** [comment]
You didn't fill out the template.

Seems to be working fine here with both a DS4 in SDL mode and XBox Series controller in XInput mode.

What is the controller state when it's not activating? You can enable that in display settings.

**Comment by sappergr** [comment]
I will try to make a more detailed report.

**Comment by stenzek** [comment]
In that case it's a controller issue, not an emulator issue. Different controllers will require different scales, unfortunately all I can test with is DS4/XBox One pads, as that's all I have.
