### ISSUE TITLE
Provide a Flatpak

### ISSUE THREAD

**Issue by j8r** [stenzek/duckstation#1987]
Having an AppImage is quite good, but as https://github.com/stenzek/duckstation/issues/1967, https://github.com/stenzek/duckstation/issues/1904 and https://github.com/stenzek/duckstation/issues/861 has shown, it is not very portable across various Linux distributions.

Flatpak will solve this issue. Some other emulators are already available on Flathub: PPSSPP, Citra, PCSX2, RPCS3, and soon Flycast (working on it).

**Comment by stenzek** [comment]
I'm not interested in doing this myself, since I don't use it. If someone else wants to maintain one, go for it.

There was a discussion in #192 - apparently it needs a specific commit hash to build against, not a tag... so you'd have to update it potentially every day (for preview builds), or every week or so (for dev builds).

**Comment by stenzek** [comment]
(ironically, I thought AppImages were supposed to solve this dependency problem by including everything.... as usual, Linux software distribution is a complete disaster)

**Comment by j8r** [comment]
Sorry I didn't see that issue! For Qt/SDL: yes, it is easy to include: https://github.com/flathub/flathub/wiki/App-Requirements#shared-modules. For Qt, there is a KDE platform which should have what this project needs.

For the commit and tag needed, you can just use the Flathubot (see for an example https://github.com/flathub/net.rpcs3.RPCS3) which will bump the commit hash automatically, and the PR can be automerged.

For distribution, there is a very old, "universal" solution: static linking. Alpine Linux has to be used though.

Overall, there is not much maintenance. The biggest work is to set the application up at first.

**Comment by j8r** [comment]
Side note: I'm pretty sure why the AppImage does not run on older distributions. The libc6 version required by a binary must be equal or newer than the one used to compile it, being dynamically linked. Ubuntu 20.04 has a rather new libc6 version, which is not compatible with older ones. The solution is to compile with say 18.04, libc6 being backward compatible.

**Comment by stenzek** [comment]
Not changing that, 18.04 uses too old versions of libraries, qt being the main issue. The appimage should include libc imo.
