### ISSUE TITLE
Colony Wars Vengeance - Infinite Loading Issue

### ISSUE THREAD

**Issue by thomasheen** [stenzek/duckstation#1988]
Game details
Colony Wars Vengeance USA and Europe

Description of the issue / bug
Just testing out some games on the last update. Colony Wars Vengeance on the ps1 locks on an infinite loading screen when entering into any gameplay. Game works using ReARMed so its a core issue

Steps to reproduce
Try play any level

Hardware/software
Windows 10 
Intel i5 2,27GH

Emulator version
0.1-3659-g4cd8c959 (master)

**Comment by stenzek** [comment]
Timing issue. Probably works in pcsx because it's less accurate.

Fixed in https://github.com/stenzek/duckstation/commit/62360d088aee8d16da4309d8fa665ff2b0b5d14b (you will need to switch to the preview channel).
