### ISSUE TITLE
Grid View Increase hotkey not working

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#1989]
**Game details**
Not Related

**Description of the issue / bug**
In grid view when tried to increase size via CTRL + + the shortcut is not being recognized.
Via CTRL + Mouse scroll up works normally.

**Controller Troubleshoot Report**
Not Related

**Steps to reproduce**
- Run Duckstation in Grid Mode > Press CTRL + - to decrease then > CTRL + + to increase size of titles > Nothing will happen

**Enhancements information**
Not Related

**Hardware/software**
Not Related.

**Emulator version**
Happens in both versions DEV or Master (latest)

![image](https://user-images.githubusercontent.com/43047877/115165996-4dba0d80-a087-11eb-9565-49b8b37a75ad.png)

**Additional context**
None

**Comment by stenzek** [comment]
Working fine here...

**Comment by andercard0** [comment]
> Working fine here...

not it is not! but if you wont to investigate it is okay then thanks!

**Comment by stenzek** [comment]
Not much I can do if I can't reproduce it myself.

**Comment by andercard0** [comment]
> Not much I can do if I can't reproduce it myself.

Well, as discussed with Silent moments ago, there is something he quoted in regards of this. I can't yet increase the size of the covers back because in my scenario I was trying to do it via CTRL plus + BUT with the + = key, which means is indeed easy to reproduce since you have a laptop keyboard.

As he did commented: 
I bet he used num+ just like I did when testing the first time
but then I had a stroke of genius and tried + next to the number row
just reopen and clarify it is about that key and not the numpad one

because it literally wants a +, and you need to press Shift to get it
without Shift you get =

as a Work around we could do it via CTRL + Shift plus + so that way i (with my keyboard without the num pad option) works.
