### ISSUE TITLE
Graphics are broken in Tobal No. 1 (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#199]
I can hear the game playing, I just can't see it. Looks the same in Software, OpenGL and D3D11.

![SLPS-00400_2020-03-31_16-12-48](https://user-images.githubusercontent.com/31968468/77989725-379dba00-736b-11ea-93a9-98b82f5de3a2.png)

I can see the main menu if I turn on "Show VRAM"

![SLPS-00400_2020-03-31_16-13-53](https://user-images.githubusercontent.com/31968468/77989759-4b492080-736b-11ea-888e-4bce6a279d38.png)

**Comment by stenzek** [comment]
Does switching the crop mode change anything?

**Comment by kurayami6** [comment]
It makes the glitchy lines look slightly different.

None

![Capture](https://user-images.githubusercontent.com/31968468/77992955-daa60200-7372-11ea-9c5a-22b0a7e784fb.PNG)

Only overscan area

![Capture2](https://user-images.githubusercontent.com/31968468/77992996-ea254b00-7372-11ea-8bf3-fc153a2bac1f.PNG)

All Borders

![Capture3](https://user-images.githubusercontent.com/31968468/77993013-f6110d00-7372-11ea-9a50-072331b2801c.PNG)

**Comment by stenzek** [comment]
Seems this is relying on VRAM wrapping-around. Will have to handle this with a special case and do an extra framebuffer copy.

**Comment by stenzek** [comment]
Please retry on latest master.

**Comment by kurayami6** [comment]
Fixed.
