### ISSUE TITLE
Random fps drop/slow down on game

### ISSUE THREAD

**Issue by imadeput0287** [stenzek/duckstation#1992]
Hello,

I was use dev of Duckstation on Win x64 version 2021-04-11. 
My PC Spec :
Intel i7 3770
8GB DDR3 1600Mhz CL9
Asus TUF GTX 1650s

What I update was:
Renderer : Vulkan
Internal Res Scale : 5x
MSAA : 8x
True Color Rendering : Check
Texture Filtering : Bilinear

HW usage was very low,
CPU lower than 10%
GPU lower than 15%

But in the game sometime I got fps drop like game pause on half second (Please see attachment for Tekken 3 USA) - see on 00:00:07

https://user-images.githubusercontent.com/54795092/115212785-74ce1900-a133-11eb-9b80-322828dc13c4.mp4

If there is any log needed, please tell me how to produce.

Thank you.

**Comment by stenzek** [comment]
Are you running the game off slow storage? Sounds like a stall from I/O - maybe try preloading the image.

**Comment by imadeput0287** [comment]
Main drive are Sata3 SSD (OS and Duckstation) while rom (bin and cue) saved on external hdd using USB3. How i can do preloading the image sir?

**Comment by stenzek** [comment]
Loading off USB could explain it.

Preload is under console settings -> cd-rom emulation -> "preload image to RAM".

**Comment by imadeput0287** [comment]
I got it, play for 30mnt and no fps drops. Thank you.
