### ISSUE TITLE
Framelimiting is broken in Qt GUI

### ISSUE THREAD

**Issue by trostboot** [stenzek/duckstation#20]
e098c8334236f4a2b734c153300f9626bfaca2f8 broke framelimiting when using the Qt GUI. Vsync and fastforward toggles have no effect, it will always run uncapped. It's fine when using SDL.

**Comment by stenzek** [comment]
I'm not able to reproduce this. Could you please attach your `settings.ini`?

**Comment by trostboot** [comment]
Found the issue. This was in the settings.ini:

> [General]
SpeedLimiterEnabled = true
StartPaused = false
EmulationSpeed = 1.000000

> [%General]
SettingsVersion = 1
SpeedLimiterEnabled = true
StartPaused = false
EmulationSpeed = 100

Changing emulation speed to 1.00 in the %General section fixes it.
