### ISSUE TITLE
Virtual Sex (Russia) (Unl) goes to "Insert CD-ROM" screen after BIOS.

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#200]
Region is set to auto. The game is from Redump so it would have been verified to work on a real console. It also boots in Beetle PSX. 

![Capture](https://user-images.githubusercontent.com/31968468/78021782-89603780-739f-11ea-95d0-31b775a1f1ea.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/78021962-e0660c80-739f-11ea-966e-8c67f3a9f958.PNG)

**Comment by stenzek** [comment]
Can't say I really want my emulator associated with this game :P But I'll add an option to disable region checking at some point.

**Comment by kurayami6** [comment]
I don't think region is the problem since I've tried it with all region settings including auto and it doesn't boot in any of them.

**Comment by stenzek** [comment]
It likely is in this case - if the disc doesn't match one of the NTSC-U/NTSC-J/PAL regions, it returns an error. See https://github.com/stenzek/duckstation/blob/master/src/core/cdrom.cpp#L1378

**Comment by stenzek** [comment]
Enable region check option added to master. Try disabling it and see what happens.

**Comment by kurayami6** [comment]
Using the latest version and I can't find the option anywhere. Where is it?

![Capture2](https://user-images.githubusercontent.com/31968468/78071514-68bccf80-73e9-11ea-93fd-c3dd66024589.PNG)

In any case right clicking the game in the list and choosing "fast boot" makes it work. However it's a stuttering mess.

![Capture](https://user-images.githubusercontent.com/31968468/78071604-8a1dbb80-73e9-11ea-99ea-8166afd519e1.PNG)

**Comment by stenzek** [comment]
Have to do it via settings.ini for now. Use the software renderer. Games which cause constant readbacks like this will never be fast on the hardware renderers.
