### ISSUE TITLE
hotkey for enable/disable clock speed control

### ISSUE THREAD

**Issue by ronnyc4** [stenzek/duckstation#2000]
clock speed control overclock is very nice feature even though it's not perfect and cause some issues in some games (flickering, double speed, ect) but there is games that work well with it, make it runs at 60fps.
but even then, some games that work well with it might have some issues in certain condition of gameplay like level, menu, scene, etc.
it would be nice to be able to enable/disable the clock speed control while playing the game with a hotkey feature.
so if you enabled it in games and then encounter some issues while playing you just disabled it and enabled it again later on without go to menu.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/704c160c35ff617a77be852552e39b27e17a9f36
