### ISSUE TITLE
Resume State Option

### ISSUE THREAD

**Issue by Vasquarde** [stenzek/duckstation#2005]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Is your feature request related to a problem? Please describe.**
Resume option loads the last CD image loaded, not the last game loaded.

**Describe the solution you'd like**
Detect the last game loaded on close. Also an option to Resume State and load the last save state to load into the game even quicker. (context menu of picking through what save slot you wanted)

**Describe alternatives you've considered**
Loading through the game list is fine, but I have a lot of games.

**Additional context**

**Comment by stenzek** [comment]
Uhh, this is already the case. Pressing resume will load the most recent save state based on save time, which will be the resume state automatically saved when the game is closed.

There is also a context menu in the game list where you can load save slots or the resume state for that game....

**Comment by Vasquarde** [comment]
Whenever press resume, it always tries to load the last CD image. I have all my games converted to CHD now. I can produce a screenshot.

**Comment by stenzek** [comment]
Do you have "save state on exit" enabled in settings?
