### ISSUE TITLE
Graphical Glitch

### ISSUE THREAD

**Issue by imadeput0287** [stenzek/duckstation#2006]
I'm not sure it's appropriate to ask here. Please mark it close if you find this not appropriate.

I try the libretro core that forked from here, when I try any game it give graphical glitch like not perfect moving (see the video). Maybe there is an advise about something I'm missing?

PC HW:
Intel i7 3770
8GB of RAM
Nvidia 1650s
Windows 10 Pro x64
RetroArch 1.9.1 win64 - Swanstation Core

I tried to install VC Redist 2015-2019 x64 but nothing change.

https://user-images.githubusercontent.com/54795092/115501501-e4fcac00-a2a5-11eb-8646-7c93a413622c.mp4

Sorry if you found this not should be there.

Thank you.

**Comment by Nucleoprotein** [comment]
It is not a glitch, that is how PSX rendered (interlaced). You can disable interlacing in Settings -> Enhancements -> Disable Interlacing (force progressive render/scan)

**Comment by Nucleoprotein** [comment]
ahh, RetroArch.SwanStation.2021-04-21.13-25-23.mp4 - RetroArch not supported here, go to RetroArch support

**Comment by imadeput0287** [comment]
> 
> 
> ahh, RetroArch.SwanStation.2021-04-21.13-25-23.mp4 - RetroArch not supported here, go to RetroArch support

Thank you for your advise

**Comment by stenzek** [comment]
Swanstation is not duckstation, I have nothing to do it. If the problem happens in duckstation I'm happy to look into it, but otherwise I can't help.

**Comment by imadeput0287** [comment]
> Swanstation is not duckstation, I have nothing to do it. If the problem happens in duckstation I'm happy to look into it, but otherwise I can't help.

No worries, but @Nucleoprotein advise are work. Thank you anyway.
