### ISSUE TITLE
Build dependency not outlined in build instructions: rapidjson-dev

### ISSUE THREAD

**Issue by ArghKevin** [stenzek/duckstation#2013]
**Game details**
N/A

**Description of the issue / bug**
rapidjson-dev is a build dependecy when building on debian10

**Steps to reproduce**
building from current source after having followed current build instructions causes an error: rapidjson/document.h: file or folder not found 

**Hardware/software**
debian 10
**Emulator version**
master branch source code, with this being the most recent applicable commit: https://github.com/stenzek/duckstation/commit/fe1a5829094e859851e9f925f92804df7faf6419 

If there are any problems with this issue submission, let me know.

**Comment by stenzek** [comment]
It's not a dependency, rapidjson is included in-tree. There was just a missing reference in the cmake file, and on the CI it must've had the package installed. See https://github.com/stenzek/duckstation/commit/cc6ef019264c2670169ef05054dbff08cb60b077
