### ISSUE TITLE
Build error: "Undefined reference to 'Cheevos'"

### ISSUE THREAD

**Issue by ArghKevin** [stenzek/duckstation#2014]
**Game details**
N/A

**Description of the issue / bug**
Building via unix makefiles errors out if "CHEEVOS" is a deselected build option

**Steps to reproduce**
Comfigure the source code via CMAKE, deselect CHEEVOS, attempt to build a binary via MAKE

**Hardware/software**
Debian 10

**Emulator version**
Latest applicable commit is https://github.com/stenzek/duckstation/commit/fe1a5829094e859851e9f925f92804df7faf6419

let me know if there are any problems with this issue submission

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/8f821c776c24f1bb59d5a2c123d6e6a5c9b6dc14
