### ISSUE TITLE
graphic problem 

### ISSUE THREAD

**Issue by mattyfurniss** [stenzek/duckstation#2015]
I am having a number of problems in trying to play games aswell as a graphic problem in duckstation slient hill wen you set texture filtering to jinc2 and pgxp depth buffer on vulken and d3d11 there is
![SLUS-00707_2021-04-22_18-44-13](https://user-images.githubusercontent.com/83032415/115765524-cb8b5b00-a39e-11eb-8435-557f1f042d6f.png)
now if i turn off  the depth buffer get this
![SLUS-00707_2021-04-22_18-41-53](https://user-images.githubusercontent.com/83032415/115766105-7865d800-a39f-11eb-87d6-5e8f99a61d07.png)
if change to bilnear any others its fine but that filtering jinc2 is good. smoothing's right but does not seem to work properly. another 2 problems are game pad sets up fine and works for a while then dose not seem to work when I boot up game. I have to remove duckstation folder from documents and start again then set up joy pad and that seems to works again for a bit. also in resident evil same problems as well 
![SLUS-00747_2021-04-22_19-44-35](https://user-images.githubusercontent.com/83032415/115769725-c5e44400-a3a3-11eb-9d4a-6e427b44261e.png)
same lines in place in game when got it on jinc2
![SLUS-00747_2021-04-22_19-44-51](https://user-images.githubusercontent.com/83032415/115770058-207da000-a3a4-11eb-8fc0-cf7685c36a9c.png)
i hope might able to resolve these lssues as I do like duckstation however, having these .problems

**Comment by jpchow26** [comment]
These are enhancements, and not guaranteed to be acceptable or even work for all games. If disabling them for specific games is acceptable to you then that's how it has to be.

**Comment by stenzek** [comment]
None of these are bugs.

Depth buffer has low compatibility, because games use overlapping depth ranges.

The RE2 issue looks like it might be caused by CPU mode - this should be disabled and only enabled when absolutely necessary.

The texture lines are simply how the textures are - they're low resolution, and you don't notice it with nearest neighbor filtering because they're already blocky.

**Comment by mattyfurniss** [comment]
Hi OK no problem  I fort there was problem but its a shame can't use the filtering jinc2 for all games it smooths nice in games but end up having there's problems I do like the duckstation
