### ISSUE TITLE
persona 2 innocent sin and other games left analog stick jumps randomly

### ISSUE THREAD

**Issue by ISuckGood** [stenzek/duckstation#2016]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Is your feature request related to a problem? Please describe.**
When pressing up on analog stick sometimes it jumps to left/right

**Describe the solution you'd like**
Add a safe zone to the controller calibration that UP DOWN has more tolerance

**Describe alternatives you've considered**
Using the directional pad of the xbox controller is tiring for the fingers

**Additional context**
none

**Comment by stenzek** [comment]
You could try setting the axis scale, but I'm not sure if a deadzone makes sense here - the sticks have a continuous value, it's not "0 for a dead range and then 1 past that".

**Comment by ISuckGood** [comment]
pliz fix

**Comment by stenzek** [comment]
I work in this in my spare time and give it away for free. Therefore I decide what to work on. If you want to employ me full time I'll gladly do whatever you say, but otherwise take it the way it is. It's also open source so you're free to fork it and add it yourself.
