### ISSUE TITLE
Overblood 2 fps drops

### ISSUE THREAD

**Issue by Basmurd** [stenzek/duckstation#202]
On gameplay fps drops to 11. AVG 15. On prerendered movies no problem.

**Comment by stenzek** [comment]
Which FPS number? The first (internal game FPS) or the second (displayed frames per second)? If the first, does the game lag on console? If the second, check the console window for warnings about slowdown.

**Comment by Basmurd** [comment]
Yep, yellow color message about slowdown
![aC4jj0JM8e](https://user-images.githubusercontent.com/61318181/78163198-ba4c7500-7450-11ea-88c0-3281c01b15fd.png)
![QRfeU1odAt](https://user-images.githubusercontent.com/61318181/78163201-bb7da200-7450-11ea-86e4-076646212606.png)

**Comment by stenzek** [comment]
2ms lost is not really an issue. That can happen when under load, e.g. compiling a lot of new JIT blocks. Your frame times (2-3ms) look good.

I'd check that the game doesn't actually lag here on console. Many games do have performance issues.

**Comment by Basmurd** [comment]
Ok. I test that game on other PSX emulators, just for comparison.

**Comment by kurayami6** [comment]
I'm getting 20 FPS as of the latest version. What framerate does it run at on real hardware?

**Comment by Basmurd** [comment]
25 on PAL

**Comment by stenzek** [comment]
https://youtu.be/23juSWD0Ejs?t=251 looks like around 15-20fps, so I'd say this is probably working as intended.
