### ISSUE TITLE
Chrono Cross(jpn) freeze only at status screen

### ISSUE THREAD

**Issue by lw12131155** [stenzek/duckstation#2025]
I have Chrono Cross running beautifully through duckstation without the "-noauto" command line. No problems at all besides one:

When trying to access the status screen for a character the game move to the typical black loading screen (usually for a second or two), but freezes there. The music can still be heard but it essentially "freezes" as well, meaning it keeps skipping on one or two notes.

Not a biggie but it's odd that it is consistent with the status screen only.

**Comment by stenzek** [comment]
This has already been fixed in the preview build - see #553 and https://github.com/stenzek/duckstation/commit/600ae7bcc03c6b9d8537d8c05d56535c00183678.
