### ISSUE TITLE
Improve Bluetooth audio latency on Android Phone

### ISSUE THREAD

**Issue by tabnk** [stenzek/duckstation#2032]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Is your feature request related to a problem? Please describe.**
While using Bluetooth audio on Android Phone, there is noticeable audio lag with default Audio Buffer Size (2048 Frames) . Changing Audio Buffer Size to 1024 frames improved the latency a lot but audio became crackling. 

**Describe the solution you'd like**
Editable Audio Buffer Size. Or Anyway to reduce audio lag with Bluetooth.

**Comment by stenzek** [comment]
I'm not sure if this is actually possible - android's audio stack adds significant latency. A buffer size of 2048 frames is only 46ms, the latency is coming from elsewhere.

Lower buffer sizes requires that the emulator be more precise inter-frame timing, which Android is **terrible** at. You could try enabling optimal frame pacing, but that requires that your device's power management isn't screwing with clock speeds.

**Comment by tabnk** [comment]
Select Cubeb, Audio Buffer Size of 1024 Frames and Enabled optimal Frame Pacing. It did the job.
