### ISSUE TITLE
[Question / Feature Request] Parallel RunAhead

### ISSUE THREAD

**Issue by alpozcan** [stenzek/duckstation#2033]
**Is your feature request related to a problem? Please describe.**
How hard would it be to distribute runahead workload over multiple CPU cores?

**Describe the solution you'd like**
For N frames of runahead, would it be possible to have N+1 emulation threads running in parallel? One would run at 2x speed, the next one at 3x, and so on, to make N frames into the future available at the actual next frame?

**Describe alternatives you've considered**
No alternatives exist that I know of.

**Additional context**
[Same feature request](https://github.com/libretro/RetroArch/issues/10744) had been raised to Retroarch as well.

**Comment by stenzek** [comment]
No, not possible without significant emulator redesigns, and such a redesign would be much slower for the general case.
