### ISSUE TITLE
Missing Strings (all Languages) but English

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#2037]
**Game details**
Not related

**Description of the issue / bug**
There are 1 string missing for  translation as follows: 

Auto (Match Window) in the DisplayAspectRatio

Only new strings are :  

![image](https://user-images.githubusercontent.com/43047877/116748034-29d6c000-a9d5-11eb-8940-6edd05f6fd44.png)

Being only available in English ofc.

**Steps to reproduce**
None.

**Enhancements information**
Not Related

**Hardware/software**
Not related

**Emulator version**
Previous version

**Additional context**
[Add any other context about the problem here]

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/f39a5dcf5dedd67a6cfc49a02cfbe77a2fd8f0d4
