### ISSUE TITLE
medievil 2 CDROM::SetAsyncInterrupt error

### ISSUE THREAD

**Issue by shikulja** [stenzek/duckstation#204]
tested on
15c33ebedb5d7e8e72b23598e55b72ff8c8c3965

![Аннотация 2020-03-31 204447](https://user-images.githubusercontent.com/3386359/78058453-fd471380-7390-11ea-87cd-ef6e996b2609.png)

[    5.3640] W(CDROM::SetAsyncInterrupt): Not setting async interrupt 1 because there is already one unacknowledged

**Comment by stenzek** [comment]
Maybe it's just the Russian version? The US version seems to work fine.

**Comment by shikulja** [comment]
> Maybe it's just the Russian version? The US version seems to work fine.
yes, it looks like the official version, with an anti-defense patch
I can throw off the image if necessary

**Comment by shikulja** [comment]
> Maybe it's just the Russian version? The US version seems to work fine.

stopped working after the last change this week

**Comment by shikulja** [comment]
0c1547d9e3b6dc57f81d5ba49de085b5af5b3b23
fixed. but intro video start flickering

**Comment by shikulja** [comment]
~ a4a112f5d8d2d48ef695db747df4026c27a8e79f
fixed
