### ISSUE TITLE
(Android) Hide messages related to previously loaded games.

### ISSUE THREAD

**Issue by 6lackmag3** [stenzek/duckstation#2041]
How to reproduce: enable on-screen messages, start any game, exit, start other game.

https://user-images.githubusercontent.com/13922742/116764944-941a4f80-aa2b-11eb-901a-694a9356d22c.mp4

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/44f29da40fe2f25185600569cedfef33b5d69602
