### ISSUE TITLE
persona 2 innocent sin runs at 30 fps instead of 60 like previous version

### ISSUE THREAD

**Issue by ISuckGood** [stenzek/duckstation#2048]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Game details**
SLPS-02100 Persona 2 Innocent SIn

**Description of the issue / bug**
Applied latest patch m, now game runs at 30 FPS instead of 60 like before

**Controller Troubleshoot Report**
no

**Steps to reproduce**
Open game and look at fps . Shows 30/60 instead of 60/60 like before

**Enhancements information**
yes

**Hardware/software**
[If desktop, your CPU, graphics card, and operating system]
rtx0280s , core i9 10850
![2021-05-02_17h37_39](https://user-images.githubusercontent.com/42075250/116818730-20805b80-ab6d-11eb-8e4d-1a14044abbc6.png)

[GPU Renderer - D3D11/OpenGL/Vulkan]
D3d11

**Emulator version**
0.1-3919-g4875b2ec (dev)

**Additional context**
[Add any other context about the problem here]

**Comment by stenzek** [comment]
What does this game run at on console?

**Comment by ISuckGood** [comment]
I dont know what happened but now the game runs terrible after i upgraded the duckstation . Its like it runs half the previous fps . Also i cannot even power off the game . I need to close down duckstation now and repopen it. I looked on my old youtube videos i played this game and it runs much smoother

![2021-05-02_17h53_20](https://user-images.githubusercontent.com/42075250/116819222-63dbc980-ab6f-11eb-9541-bb2d38759a18.png)

**Comment by stenzek** [comment]
You'll need to post the log. https://github.com/stenzek/duckstation/wiki/Enabling-Logging

As for the FPS, I see no issue here. As far as I can tell, the game is supposed to run at 30fps.

**Comment by ISuckGood** [comment]
Ok . Sorry for the mistake
