### ISSUE TITLE
Discord still shows DuckStation after quitting DuckStation

### ISSUE THREAD

**Issue by Diskutant** [stenzek/duckstation#2049]
**Game details**
any game

**Description of the issue / bug**
When I start DuckStation, Discord shows me as playing DuckStation. After quitting DuckStation I'm still shown as playing DuckStation.

**Controller Troubleshoot Report**
none

**Note:**
none

**Steps to reproduce**
1. Start Discord
2. Start DuckStation
3. Check your Discord status ("Playing DuckStation")
4. Quick DuckStation
5. Check your Discord status ("Playing DuckStation")

**Enhancements information**
none

**Hardware/software**
Win 10
Discord Stable 83364 (9af39da)

**Emulator version**
DuckStation 0.1-3926-g6f5c00bc (master)

**Additional context**
none

**Comment by stenzek** [comment]
This isn't a duckstation issue, as far as I'm aware most emulators which use the old RPC library have this problem. The new library is not GPL compatible, therefore cannot be used.

I've added a delay to the rpc library so hopefully the clear message gets sent to discord (https://github.com/stenzek/duckstation/commit/6b2ce266d4f919c302f51a6edeeb2bc88ed76e32).. that's all we can really do.

**Comment by Diskutant** [comment]
Seems to work now, thank you!

**Comment by Diskutant** [comment]
Seems like it stopped working in new versions.

**Comment by Diskutant** [comment]
correction: It works only if no game is running when closing DuckStation. So first click PowerOff and then close DuckStation will do the job.
