### ISSUE TITLE
Virus - The Battlefield main menu runs at over 300 FPS

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#205]
The rest of the game runs at normal speed. 

![Capture2](https://user-images.githubusercontent.com/31968468/78076362-fef4f380-73f1-11ea-90ea-32e10611f7b2.PNG)

Gameplay stutters constantly while the log endlessly spams this error message. 

![Capture](https://user-images.githubusercontent.com/31968468/78076398-116f2d00-73f2-11ea-967f-22fa705cf8a6.PNG)

**Comment by stenzek** [comment]
Sounds like it needs GPU timings.

**Comment by stenzek** [comment]
We might have to GameINI this one when I eventually implement it - seems to require fifo size = 16, no run-ahead to prevent lost frame ingame.

**Comment by stenzek** [comment]
Nevermind with the GameINI, looks like this was the poly-line issue which also affected R4.

**Comment by kurayami6** [comment]
Game runs at normal speed despite the FPS counter claiming it's running at thousands. Gameplay no longer stutters.

**Comment by ggrtk** [comment]
Still seems like it's running too fast then. The FPS counter is based on the number of GP1 (0x05) writes, which shouldn't be happening thousands of times per second.

**Comment by stenzek** [comment]
Some games don't seem to vsync and essentially run uncalled though.
