### ISSUE TITLE
Allow the user to play games with Redbook audio like a CD player

### ISSUE THREAD

**Issue by Starmann** [stenzek/duckstation#2050]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to play the PS1 Redbook audio like you could on old CD players. That was a nice extra feature on a lot of games.

**Describe the solution you'd like**
Add in a GUI submenu that can play tracks off of games

**Describe alternatives you've considered**
In the long-term, it might be a better idea to emulate the BIOS's CD player. Alternatively, it might be best implemented as a separate executable or a Foobar2000 plugin or something.

**Additional context**
This might also be a good debugging tool. If for whatever reason a Redbook game is having audio issues, users could test if it's an emulation issue or an issue with the ROM.

**Comment by foxsevent** [comment]
Ok but why? Ducko already sorta already supports this just boot the bios go to the CD player then use the change disc option to select the disc with Red book audio.

Alternatively put the CD in any CD player or pc via cd drive emulator like deamon.
Or infinitively simpler google the soundtrack, you can find most of them easily online and quite often legally put there by the composers.

Debugging wouldn't really work as any issues with it would be in how the game handles audio playback.

**Comment by stenzek** [comment]
Not in the scope of an emulator, sorry.
