### ISSUE TITLE
Text box is rendered incorrectly when upscaled in Athena - Awakening from the Ordinary Life (Japan) 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#206]
OpenGL and D3D11

![SLPM-86185_2020-04-01_09-57-29](https://user-images.githubusercontent.com/31968468/78083299-c7da0e80-7400-11ea-8e34-af20f93b7ac2.png)

Software

![Capture](https://user-images.githubusercontent.com/31968468/78083377-fd7ef780-7400-11ea-8082-f1625b3e910b.PNG)

**Comment by stenzek** [comment]
Please re-test on latest master.

**Comment by kurayami6** [comment]
Not fixed. Turns out it's caused by upscaling the resolution. Does that make this issue invalid or is there a non hacky way it can be fixed? 

![Capture](https://user-images.githubusercontent.com/31968468/78130475-17eabc80-7465-11ea-8018-47e8b56f8f7c.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/78130484-1d480700-7465-11ea-8e1e-645c12cd93a5.PNG)

**Comment by stenzek** [comment]
Try dx11. OpenGL uses line width for upscaling whereas dx11 uses a geometry shader to expand the line to triangles. I may need to use the GS in OpenGL too.

**Comment by kurayami6** [comment]
Still wrong in D3D11.

![Capture](https://user-images.githubusercontent.com/31968468/78203374-8326a400-74e2-11ea-82bb-504c937f3d47.PNG)

**Comment by stenzek** [comment]
Okay. I will have to look into how it's rendering, it's possible my line width geometry shader isn't handling one of the cases correctly.

**Comment by stenzek** [comment]
Merged with #427.
