### ISSUE TITLE
Right analog-stick can't go up or down on Duckstation

### ISSUE THREAD

**Issue by Phantasm90** [stenzek/duckstation#2061]
**Description of the issue / bug**
Duckstation doesn't detect the right stick up or down of my gamepad, this doesn't happen on Xebra, Mednaffe and ePSXe, i can use the right stick of my other two controllers with no problem, it only happens with this controller (it's a G-Shark GS-GP702), i thought it might be just my laptop but now i tested it on another computer and it has the same right stick issue

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
No
2. Which controller backend are you using in general settings
SDL

**Additional context**
Here's some screenshots if it helps

![gamepad](https://user-images.githubusercontent.com/37343312/117087469-cf7c8d00-ad4f-11eb-9214-1993a314c1f7.png)

Duckstation
![duckstation](https://user-images.githubusercontent.com/37343312/117087483-dc00e580-ad4f-11eb-8df1-f783313930d6.png)

Mednaffe
![mednaffe](https://user-images.githubusercontent.com/37343312/117087497-ec18c500-ad4f-11eb-8c2d-c8d838b83d56.png)

ePSXe
![epsxe](https://user-images.githubusercontent.com/37343312/117087511-f5a22d00-ad4f-11eb-9eb5-259b6f224403.png)

Xebra
![xebra](https://user-images.githubusercontent.com/37343312/117087553-1c606380-ad50-11eb-8940-5255beff52bc.png)

**Comment by stenzek** [comment]
Probably not a duckstation bug. Try dinput, or you may need to add a game controller db entry.

**Comment by Phantasm90** [comment]
I couldn't map anything on Dinput, but mapping everything on gamecontrollerdb seems to have fixed it
