### ISSUE TITLE
Remember and fixed/locked window resolution (NoGUI)

### ISSUE THREAD

**Issue by LukasThyWalls** [stenzek/duckstation#2069]
**DESCRIPTION**:
I was looking at the emulator for a solution, but maybe there is more a feature request than a bug or something i didn't see.
The main issue is when use NoGUI, the window resolution in my end is always 1280x720, and i need always to resize the window to something i like. The settings i have are Aspect Ratio 4:3 and Internal Resolution 3x, but also i tried 1x but the window is the same because that's about internal resolution, not about the real resolution the game is shown.

**SOLUTION**:
The QT version has a menu option what says "Window Size" in "View" with "Scale 1x, 2x...". It remembers the size between reboots.
In the NoGUI version should be something like that, or put a custom resolution for the window or from command line, but in both cases could be useful a toggle to lock the window resolution and doesn't allow to resize the window (only if you go to settings or view to change it).
It could be better if it only affects when it's playing a game, not showing the menu.

**WORKAROUND**:
For now, i have been using Borderless Gaming to lock a window resolution, but i ran with an issue that it detects both NoGUI and QT versions as the same and both autoresizes to the same resolution, when the QT have the menu there so the game resolution aren't the same in both cases. Also it disable the title bar in the QT version. I didn't want Borderless Gaming affect the QT version, only the NoGUI version but there is what there is...
Also I detected an issue (i think) in the NoGUI version, because the "Pause on Focus Loss" didn't work (it works in the QT version), and the mouse is not wrapped inside the window when you are emulating with the GunCon, so you can easily click outside the window (you can open anything or clic other windows) and also the game doesn't pause.

**ADDITIONAL CONTEXT**:
I'm using now Duckstation 0.1-3919-g4875b2ec (dev). I tried this in two different computers with the same behaviour.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/eba5542ac06beeaf1620194bc208eabd90b8cb62
