### ISSUE TITLE
Artifacting on the opening screen of Zoids - Battle Card Game - Seihou Tairiku Senki (Japan)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#207]
Happens with Software, OpenGL and D3D11.

Duckstation

![SLPS-03255_2020-04-01_11-10-26](https://user-images.githubusercontent.com/31968468/78086580-23f56080-740a-11ea-9a51-3bdd168734da.png)

Beetle PSX

![Zoids - Battle Card Game - Seihou Tairiku Senki (Japan)-200401-110945](https://user-images.githubusercontent.com/31968468/78086597-2d7ec880-740a-11ea-98e3-24a02d7a8011.png)

**Comment by stenzek** [comment]
Seems like MDEC artifacts...

**Comment by kurayami6** [comment]
Still an issue as of the latest version.

**Comment by kurayami6** [comment]
Puppet Zoo Pilomy (Japan) has the same issue during the opening cutscene. 

![80935706-3dc30280-8e11-11ea-9128-45522a2d97cb](https://user-images.githubusercontent.com/31968468/83744150-0ad58e00-a69f-11ea-8e13-7b6cea81d28c.png)

**Comment by kurayami6** [comment]
Sesame Street Sports (USA) has the same problem. 

![SLUS-01180_2020-07-11_08-48-16](https://user-images.githubusercontent.com/31968468/87208897-79b79e00-c353-11ea-8b6e-d1e448572af5.png)

**Comment by stenzek** [comment]
Fixed with latest round of MDEC changes.
