### ISSUE TITLE
Implement axes in evdev controller backend

### ISSUE THREAD

**Issue by vanfanel** [stenzek/duckstation#2070]
I have just built latest NOGUI version, and even if I can easily assign circle, square, X, triangle, select, start, L and R buttons, the **Up Button, Down Button, Left Button and Right Button** can't be assigned no matter what.

I can even assign the "Quit Menu" button, etc... hotkeys seem to be easily assignable to gamepad buttons.

I use a Xbox360-compatible gamepad (8BitDo SN30 USB), which works fine elsewhere.

I have tried both "Digital Controller" and "Dual Shock" modes in "Controller Type", with the same results.

Maybe I am again trying to do things too son and EVDEV doesn't map direction buttons yet?

Since the UI is getting attention, I think it's a good moment to ask.

**Comment by stenzek** [comment]
Probably because I'm not handling axes yet.

**Comment by vanfanel** [comment]
Ah! Sorry, again ahead of time :)
I would say it's the last lacking feature on EVDEV so you can say farewell to SDL2 in NOGUI mode?

**Comment by dankcushions** [comment]
sorry to hijack, but does the evdev backend affect the binding button numbers in the ini? ie, using the standard evdev button ids? that would be really useful to me to leverage retropie's existing button configs!

(and how do i enable the evdev backend? compile option?)

**Comment by vanfanel** [comment]
@stenzek So you are keeping SDL input as the default for NOGUI?

**Comment by stenzek** [comment]
Yes. I have no interest in these "light builds", SDL is hardly a large dependency, and plenty of games/libraries use it.

Not making use of it is a silly Linux packaging idea which I do not understand.

**Comment by vanfanel** [comment]
@stenzek Well, I have no problem with SDL2, in fact I did some SDL2 work myself (namely KMSDRM).
Just wanted to know about your plans!

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/09791492361fd1a204f61608a6c6f8ef6046b484
