### ISSUE TITLE
Suikoden 2 [NTSC] - Turbo crashes the game during a battle on the World Screen

### ISSUE THREAD

**Issue by KFaded22** [stenzek/duckstation#2073]
Description of the issue / bug
Everytime I use turbo on the World Screen in a battle for easy leveling, the game crashes constantly. 
Used D3D11 and Vulkan backend. Happens on both.

Steps to reproduce
Start the game, go into the World Screen and turbo til you get into a battle and keep using turbo. The game will then promptly crash, either the very first battle or the 2nd. 

Hardware/software
Ryzen 5 1600AF
RX 580 (8gb)
Windows 10
Vulkan and D3D11

Build: 0.1-3968

**Comment by stenzek** [comment]
Is your dump valid? Fast forwarding should not affect emulation at all.

Also upload a memory card of where this crash occurs.

**Comment by KFaded22** [comment]
Yes I had dumped my own copy. 

I haven't used a memory card save, I've only used save state.

**Comment by stenzek** [comment]
Then save to memory card. I can't investigate it without one.

**Comment by KFaded22** [comment]
Alright will do

**Comment by stenzek** [comment]
Closing due to a lack of response. If you are still having this issue, please provide a memory card and I can investigate.
