### ISSUE TITLE
Mortal Kombat Trilogy (PBP) stucked, can't load properly.

### ISSUE THREAD

**Issue by D0rk1n** [stenzek/duckstation#2077]
This the PBP file of MK Trilogy.
![Github error report pbp](https://user-images.githubusercontent.com/83908633/117571969-6ad08200-b103-11eb-9ab7-be64d4960894.png)

At this part it got stuck can't load at the Main screen.
![Github error report pbp00](https://user-images.githubusercontent.com/83908633/117572038-a23f2e80-b103-11eb-9185-19cc18486f1a.png)

**Comment by foxsevent** [comment]
Could be just a bad dump of the game, on the first screenshot on the bottom press "compute hashes" press it and once done redo the screen shot and post it.

Another thing are you using any enhancrments? Like overclocking or CD speed up in Duckstation?

**Comment by stenzek** [comment]
You deleted the issue template. It clearly states issues without a completed template will be closed.
