### ISSUE TITLE
Jitsumei Jikkyou Keiba - Dream Classic (Japan) crashes the emulator 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#208]
![Capture](https://user-images.githubusercontent.com/31968468/78091007-78530d00-7417-11ea-9708-debf74d849b9.PNG)

**Comment by stenzek** [comment]
That looks like a freeze, not a crash. Probably similar issue to Syphon FIlter - infinite DMA chains which need GPU timings.

**Comment by stenzek** [comment]
Please re-test on latest master.

**Comment by kurayami6** [comment]
Gets a little further but still freezes in the latest version. 

![Capture](https://user-images.githubusercontent.com/31968468/79642801-f28adc00-81e2-11ea-8490-5965649beae5.PNG)

**Comment by stenzek** [comment]
Please check again on the latest build.

**Comment by kurayami6** [comment]
No longer hangs. It does stutter during every screen transition while in windowed mode but that's an unrelated issue. 

![Capture](https://user-images.githubusercontent.com/31968468/79682620-0ed05c80-8267-11ea-9476-53563f875307.PNG)

**Comment by stenzek** [comment]
Might be due to GPU readbacks. Try the software renderer.
