### ISSUE TITLE
Tomb Raider 3 cutscenes audio delayed

### ISSUE THREAD

**Issue by drdeathd** [stenzek/duckstation#2082]
I played the game in other emulators and the audio works fine, but here the sound is like a second delayed only in cutscenes (not the FMVs, the real ones), it's very annoying. I'm playing the USA version.

**Comment by andercard0** [comment]
> I played the game in other emulators and the audio works fine, but here the sound is like a second delayed only in cutscenes (not the FMVs, the real ones), it's very annoying. I'm playing the USA version.

First of all, fill out the template or your issue will be closed as invalid.

**Comment by stenzek** [comment]
Issue template not followed.

Also validate your dump, incorrect pregaps can cause this issue. You should also compare to console, not other emulators, they're known to get things wrong.

**Comment by dftf-stu** [comment]
> [...] You should also compare to console, not other emulators, they're known to get things wrong"

When you say "console" it might be useful to clarify: does this mean only original grey PSX or white PSOne units can be used for comparisons, or would playing on a PS2 also be acceptable (given they featured actual PS1 hardware inside)?  Then, what about playing PSX games on a PS3, PS4 or PS5, where they all run software-emulated?  Would those consoles be considered acceptable for comparisons, given they are all genuine consoles and any emulation on them is endorsed by Sony?
