### ISSUE TITLE
[Fullscreen] Fullscreen option incorrectly placed in "Settings", not "View", menu

### ISSUE THREAD

**Issue by dftf-stu** [stenzek/duckstation#2084]
**Is your feature request related to a problem? Please describe.**

The "Settings" menu lets you adjust various settings for the app, either directly, or by taking you to that section in the "DuckStation Settings" window.  For some reason, "Fullscreen" has been put at the top of this menu, despite it not being a settings-related item.

**Describe the solution you'd like**

Move "Fullscreen" to the top of the "View" menu, which is the logical place for it.  When you click the "Fullscreen" menu item, the view changes to full-screen mode.  It does not take you into any settings related to full-screen, so it is odd to place it on the "Settings" menu.

**Describe alternatives you've considered**

There is a "Fullscreen" toolbar icon, though if the app window is narrow, this toolbar icon can disappear from view (see screenshot).  ALT + ENTER also works (though is not a key-combo all Windows users are aware of).  Double-clicking on a running game does not currently change to full-screen mode (though another user has raised a ticket to request this be added).

**Additional context**

![DuckStation_FullScreenonSettingsMenuNotView](https://user-images.githubusercontent.com/83965343/117675679-b129ed80-b1a4-11eb-843c-783503b8be1f.png)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/6394671681d6df421009d55976f3009de74b6d46

The debug menu in nogui actually still has it in there, since there's no view menu. And it was the first UI developed, so Qt inherited it.
