### ISSUE TITLE
[Toolbar] Add a settings to use smaller toolbar icons

### ISSUE THREAD

**Issue by dftf-stu** [stenzek/duckstation#2086]
**Is your feature request related to a problem? Please describe.**

I tend to have _DuckStation_ snapped to one-half of my screen, which is 1366x768 resolution.  At half that horizontal size (683x768), the "Fullscreen" and "Settings" icons disappear from view, and have to be accessed via an "overflow" button.

**Describe the solution you'd like**

It would be great to have two options related to the toolbar added to the app.  Firstly, "Toolbar icon size" and then allow changing to sizes like 16x16, 24x24, 32x32, 48x48 and 64x64.  And secondly for a "Hide labels" option, so only the icons are shown.

**Describe alternatives you've considered**

Using the "Settings" menu to access both "Fullscreen" and "Settings" instead of the overflow.

**Additional context**

![DuckStation_ToolbarButtonsNotShownHalfScreen](https://user-images.githubusercontent.com/83965343/117677291-3d88e000-b1a6-11eb-884b-fa3f37c60a88.png)

**Comment by stenzek** [comment]
Not really something I wish to complicate the UI with. You can disable the toolbar in the view menu if you need the extra space ( I actually run with it hidden myself)

**Comment by dftf-stu** [comment]
You may have misunderstood the request: I want the toolbar visible, but to be able to use smaller-sized icons so that they don't overflow... it's not about gaining for vertical space
