### ISSUE TITLE
[Save-States] Add a feature to help cleanup outdated save-state files

### ISSUE THREAD

**Issue by dftf-stu** [stenzek/duckstation#2088]
**Is your feature request related to a problem? Please describe.**

I recently went into the "duckstation\savestates" folder and had around 500MB of files in there, most of which were from various games I've played in the past.  The only way to cleanup the folder is manually: cross-reference the filenames (e.g. SLUS-01234_1.sav) to the "Code" column in the Game List table to decide which I'd need to keep.

**Describe the solution you'd like**

It would be nice to have some sort-of "Save-State Cleanup" feature added to assist with this: perhaps on the Tools menu.  

It could have two simple options: "Delete save-states for any game not currently listed" and "Delete save-states that have not been accessed or modified in the last X days".

The first option would delete all save-states where the code part of a filename does not match the code of any game currently listed inside the app.  And the second one would allow the user to choose a number of days, such as "7", "14", "30", "60", "90".

**Describe alternatives you've considered**

The only current alternative is to tidy-up the folder manually, as described in the first section.

**Additional context**

N/A

**Comment by stenzek** [comment]
Couldn't you do this in explorer by ordering by date?

**Comment by stenzek** [comment]
In the interest of not leaving things open which I have zero interest in implementing, I'm going to close this. It's too niche of a use case and I'm not convinced of the value to work on it myself.
