### ISSUE TITLE
[Save-states] Add option to ZIP compress save-states

### ISSUE THREAD

**Issue by dftf-stu** [stenzek/duckstation#2089]
**Is your feature request related to a problem? Please describe.**

Currently, each save-state is saved as an individual file, (e.g. "SLUS-09876_1.sav", "SLUS-09876_2.sav", "SLUS-09876_3.sav"), with no compression.  This uses more disk-space, and also means the folder can easily soon house 100s of individual files, given you can have up-to 10 save-states for each game.

**Describe the solution you'd like**

Some other emulators, such as _Project64_, offer a "compress save-states" option; when turned-on, each save-state file is stored inside a .ZIP file.

I'd like to see DuckStation offer something similar, but with two choices: "Compress each save-state file individually" or "Use one ZIP file per-game to store all save-states for that game".

As examples, assume you have a game with code "SLUS-09876":

- With the first option set, you would have four individual ZIP files:
"SLUS-09876_1.zip"; "SLUS-09876_2.zip"; "SLUS-09876_3.zip"; "SLUS-09876_4.zip"
(inside each file would be the respective .SAV file)

- With the second option set, you only get one ZIP file:
"SLUS-09876.zip"
(inside would be all of the .SAV files: "SLUS-09876_1.sav"; "SLUS-09876_2.sav"; "SLUS-09876_3.sav"; "SLUS-09876_4.sav")

**Describe alternatives you've considered**

- On a Windows system, the user could right-click the "savestates" folder, go to Properties, go to [Advanced...] and then tick "Compress contents to save disk space" to apply NTFS compression to the folder.

- This doesn't save as-much as ZIP would: for example, I have four save-state files for a particular game.  The raw size is 16.8MB.  Under NTFS compression, this reduces to 11.9MB.  In a .ZIP file, this comes to just-under 8.7MB.

- It also doesn't address the issue of reducing the number of files in the folder, whereas the option to collect all save-states for each game into their own, respective ZIP file, would.  This would make tidying-up the folder (to remove obsolete save-states for games no-longer being played) easier.

**Additional context**

Example of such setting as offered in _Project64_:

![DuckStation_Project64CompressSaveStates](https://user-images.githubusercontent.com/83965343/117687067-51850f80-b1af-11eb-89aa-fd87bd8aa3dd.png)

**Comment by Vaporeon** [comment]
zstandard would be better than deflate for this.

**Comment by unknownbrackets** [comment]
FWIW, PPSSPP currently uses zstd for this (no option to disable), which largely seems to work well.

We did get a report of someone with a corrupt save state (which has a bunch of zeros at the end), and intentionally enabled xxhash consistency checks in zstd afterward.  I'd recommend that.

-[Unknown]

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/759938a5cf08076588d2a3110df0a33c279a1df2
