### ISSUE TITLE
Colours are wrong in Tiny Toon Adventures - Toonenstein - Dare to Scare! (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#209]
Software, OpenGL and D3D11 all look the same.

![Capture](https://user-images.githubusercontent.com/31968468/78096199-c0c4f780-7424-11ea-9932-7ad233a43040.PNG)

Beetle PSX for comparison

![Tiny Toon Adventures - Toonenstein - Dare to Scare! (USA)-200401-142150](https://user-images.githubusercontent.com/31968468/78096230-cfabaa00-7424-11ea-9aaf-662b9974389c.png)

**Comment by stenzek** [comment]
Try switching crop modes. 24-bit scanout can currently break with none/overscan, I need to handle it better.

**Comment by kurayami6** [comment]
Yeah switching to "crop all borders" fixes it. Should I close this then if you're planning to fix it?

**Comment by stenzek** [comment]
Sure. It's not an issue specific to this game.
