### ISSUE TITLE
[Settings] Remove repeated word "settings" after each item

### ISSUE THREAD

**Issue by dftf-stu** [stenzek/duckstation#2090]
**Is your feature request related to a problem? Please describe.**

- In the _DuckStation Settings_ window, currently every item in the left-hand column has the word "Settings" after its name
- In the "Settings" menu, each item also has the word "Settings" after it

In both cases, the user is looking in a Settings related area, so the context of "Settings" is implied, and repeating it after each option looks messy and is redundant.  In a restaurant or café, for example, a drinks menu might list "lemonade", "tea", "coffee", "fruit-juice" but not "lemonade drink", "tea drink", "coffee drink", "fruit-juice drinks" as it is redundant -- the customer is looking at a _drinks_ menu, so it's implied that every option is a type of drink

**Describe the solution you'd like**

Remove the word "Settings" from each option to make the UI neater

**Describe alternatives you've considered**

N/A

**Additional context**

See screenshot: removing the repeated word makes the UI neater to look at

![DuckStation_SettingsMenuLabelCleanups](https://user-images.githubusercontent.com/83965343/117691413-c6f2df00-b1b3-11eb-9b31-192ee1c9ee2a.png)

**Comment by dftf-stu** [comment]
Also, as a minor other observation: in the Settings menu, the icon next to "Game List" is a blue folder; but in the "DuckStation Settings" window, it's an orange filing-cabinet.  Nothing major, but a bit odd that this is the only option that uses a different icon in the two areas, whereas every-other option is consistent between them...

**Comment by stenzek** [comment]
No. I think that looks way worse, it's missing the context.

You're welcome to provide new icons. But I'm not an artist, hence the use of public domain icons.
