### ISSUE TITLE
Emulator running games in bin and cue format

### ISSUE THREAD

**Issue by FireSt0rmz** [stenzek/duckstation#2091]
Well, I think this is more of a doubt than a suggestion, but I would like to know if you can run games in bin and cue format on this emulator, because I am not getting it. If you have any method, someone could help me with this, because some games do not come in iso format and as much as I transform the bin and cue files into iso, even so the emulator cannot run it. If this method is not already in the emulator, I think it will be a great help to add it soon. Sorry for writing in English, I'm Brazilian and I'm using the Google translator. Thank you in advance for your help and or clarification.

**Comment by andercard0** [comment]
> Well, I think this is more of a doubt than a suggestion, but I would like to know if you can run games in bin and cue format on this emulator, because I am not getting it. If you have any method, someone could help me with this, because some games do not come in iso format and as much as I transform the bin and cue files into iso, even so the emulator cannot run it. If this method is not already in the emulator, I think it will be a great help to add it soon. Sorry for writing in English, I'm Brazilian and I'm using the Google translator. Thank you in advance for your help and or clarification.

First of all, don't  ignore the TEMPLATE, fill out it before raise any report here. 

Second, for 'doubts' or support please reach us in Discord.

**Comment by FireSt0rmz** [comment]
> > Well, I think this is more of a doubt than a suggestion, but I would like to know if you can run games in bin and cue format on this emulator, because I am not getting it. If you have any method, someone could help me with this, because some games do not come in iso format and as much as I transform the bin and cue files into iso, even so the emulator cannot run it. If this method is not already in the emulator, I think it will be a great help to add it soon. Sorry for writing in English, I'm Brazilian and I'm using the Google translator. Thank you in advance for your help and or clarification.
> 
> First of all, don't ignore the TEMPLATE, fill out it before raise any report here or it'll be considered invalid and closed.
> 
> Second, for 'doubts' or support please reach us in Discord.

Sorry for anything, this is the first time I have sent something here, so I am new to it, I go to Discord to see if I can solve something. So in this case, the emulator does not run games in bin and cue format, right?

**Comment by stenzek** [comment]
It's stated very clearly in the instructions. Please read them.

![Screenshot_20210511-034956](https://user-images.githubusercontent.com/11288319/117702633-1bc24400-b20c-11eb-8749-d6384050e6b5.jpg)

**Comment by FireSt0rmz** [comment]
> > > > Well, I think this is more of a doubt than a suggestion, but I would like to know if you can run games in bin and cue format on this emulator, because I am not getting it. If you have any method, someone could help me with this, because some games do not come in iso format and as much as I transform the bin and cue files into iso, even so the emulator cannot run it. If this method is not already in the emulator, I think it will be a great help to add it soon. Sorry for writing in English, I'm Brazilian and I'm using the Google translator. Thank you in advance for your help and or clarification.
> > > 
> > > 
> > > First of all, don't ignore the TEMPLATE, fill out it before raise any report here or it'll be considered invalid and closed.
> > > Second, for 'doubts' or support please reach us in Discord.
> > 
> > 
> > Sorry for anything, this is the first time I have sent something here, so I am new to it, I go to Discord to see if I can solve something. So in this case, the emulator does not run games in bin and cue format, right?
> 
> All good. fill out the template if there is a feature request or a issue (valid issue) or bug to report. read before ignore and / or delete it would be the best tip.

Okay, thank you very much
