### ISSUE TITLE
Framepacing issues with the OGL renderer

### ISSUE THREAD

**Issue by trostboot** [stenzek/duckstation#21]
When using the OpenGL hardware renderer, framepacing is visibly off, and there will be frequent judder. Software renderer and D3D11 hardware renderer don't appear to suffer from this issue.

I use SaGa Frontier (SCUS-94230) to test this, as it runs at 60fps with fast, smooth scrolling of fixed 2D backgrounds, making any inconsistencies easily visible to the naked eye.

This is on Win10 1909, with a GTX 1080, fwiw.

**Comment by stenzek** [comment]
Are you using vsync? It should be enabled to reduce the chances of frames being presented after your monitor's vblank.

Is it the same in the SDL frontend? I had to hack swap interval support around Qt's OpenGL context management, so I'm wondering if it's an issue there...

**Comment by trostboot** [comment]
Vsync is on, and the behaviour was the same with SDL.

**Comment by stenzek** [comment]
Strange, I'm not seeing any difference between the two APIs. Maybe I need to write a smooth scrolling demo...

**Comment by trostboot** [comment]
Here's a video comparing all three: 
[sagafrontier_framepacing.zip](https://github.com/stenzek/duckstation/files/4193820/sagafrontier_framepacing.zip)
On closer inspection, even software and D3D11 HW have the occasional duped frame, but it's not nearly as prevalent as with OGL HW.

And here's a save from that location: [shared_card_1.zip](https://github.com/stenzek/duckstation/files/4193824/shared_card_1.zip)

**Comment by kurayami6** [comment]
This is still an issue in top down 2D games. I think it's to do with the console's refresh rate not matching your monitor's refresh rate. Same thing happens in other emulators like Higan but in those it's always fixed by having Vsync on. Something must be wrong with how Duckstation does vsync.

**Comment by stenzek** [comment]
Closing as the OpenGL renderer is now "deprecated" in favor of Vulkan. I'm keeping it around for systems which don't support Vulkan, but I don't really consider bugs in it to be "critical" anymore.

That said, I did notice that it runs at 60hz instead of 59.9hz with GL on my Intel GPU. Doesn't happen with Direct3D or Vulkan.
