### ISSUE TITLE
Graphics are broken in Stray Sheep - The Adventure of Poe & Merry (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#210]
A few seconds into the game you meet a bird in the forest and things immediately go downhill. Happens with all 3 renderers. 

![POEEXE_2020-04-01_16-44-19](https://user-images.githubusercontent.com/31968468/78103433-abf25f00-7438-11ea-84c3-094a4bdb4deb.png)

**Comment by stenzek** [comment]
Please retry on latest master.

**Comment by kurayami6** [comment]
Fixed. Thanks.
