### ISSUE TITLE
Ridge Racer/Ridge Racer Revolution freezes on Pi4 

### ISSUE THREAD

**Issue by CometHunter92** [stenzek/duckstation#2100]
Ridge Racer (SLUS-00540), NTSC-U
Ridge Racer Revolution (SLUS-00214,) NTSC-U

but also Moto Racer (SLUS-00498), NTSC-U; and Moto Racer World Tour (SLUS-01321), NTSC-U.

Random freezings during gameplay.
During gameplay, not in the option menu, random unpredictable freezings occur. These are the only games that have that behaviour.
The freeze manifests itself as a "screenshot" of the action without any movement, and looping audio: the audio looping track is of subsecond duration.
It's impossible to exit the core, I have to unplug the Pi4.
(this morning I've installed the last libretro core from the last Preview build and after like 15 seconds from the freeze the gameplay resumed but then exited to Retroarch after few seconds of full speed gameplay).

I've tried stock configuration and also something different as, for example, fast boot on too.

Raspberry Pi4B 8GB at 1850 Mhz
Lakka image: Lakka-RPi4.arm-nightly-20210429-4685525.img
"Swanstation" core included in that image (and tried the latest preview armv7 core libretro version, donwloaded this morning)
Software renderer 
Threaded Video On

I have checked the checksum of Ridge Racer and it's all ok. Checked the checksum of the scph5501 bios and it's ok too.

All my 70+ PS1 games works fullspeed very well, without enhancements (I like the "original look"): these are the only 4 games that keeps freezing randomly, especially Ridge Racer. In p c s x r  these games don't freeze but they runs less accurate (no sound volume control in RRR, graphics bugs in moto racers' etc...)

However I'm happy that you are supporting again the libretro core :)

Thanks and sorry for my poor english

**Comment by stenzek** [comment]
Does it happen on standalone? I can't debug the arm version of the core at the moment, only x64.

**Comment by CometHunter92** [comment]
Mh, ok, I'll try to reproduce it in the standalone x64 version. I'll let you know!

**Comment by stenzek** [comment]
Was meaning standalone on arm. I'm wondering if this is an armv7 recompiler issue or a core issue. Could also check interpreter to confirm, but I'd think if it was a recompiler issue android users would've complained...

**Comment by CometHunter92** [comment]
Oh sorry, I'm dumb.
Didn't know there was a standalone on arm.
Do you mean the android version or I have to compile it for my linux on arm?
Sorry, I'm kinda dumb :)

**Comment by stenzek** [comment]
ARM builds on linux have to be manually compiled. If you're not sure how to do it, don't worry, I'll check it when I have time.

**Comment by CometHunter92** [comment]
I'll try to built it this night, I'll let you know!
Thanks a lot

**Comment by CometHunter92** [comment]
Compiled the standalone version in Raspbian on my Pi4. I have played Ridge Racer and tried to reproduce the freeze for like 30 minutes. Software rendering. It didn't freeze yet. 
I'm tired now, I'll retry tomorrow. 
(however I used the exact same settings of the libretro core, no freeze, steady 100% emulation velocity but wasn't smooth as on Lakka, some performance issue (frame pacing?) . I didn't expect to have less performance in the standalone)

**Comment by stenzek** [comment]
Very strange then issue then.

For the frame pacing, check "optimal frame pacing" in display settings. It's disabled by default because of potato android devices.

**Comment by CometHunter92** [comment]
Oh yes, thanks for the "frame pacing" tip.
I'll retry to reproduce the freeze on the standalone version, and I'll try to reproduce the freeze also in the libretro core version with log this time.
What kind of log do you need?

**Comment by stenzek** [comment]
I doubt the log will contain much useful information in the case of a freeze.

**Comment by CometHunter92** [comment]
Ok. Played the standalone version a little bit more, didn't freezed.
Now I'll try to run retroarch in debian on my Pi4 and try to reproduce the freeze from the libretro core.
If it will freeze I'll send you the backtrace.
Thanks again

**Comment by stenzek** [comment]
Can't seem to reproduce any freezes here after a couple of races in Ridge Racer or Moto Racer. Maybe it's a lakka thing?

**Comment by CometHunter92** [comment]
Me too, cannot reproduce the freeze in Retroarch with the Duckstation core in Raspbian and even in Lakka anymore after I updated the core with the pre-release. Maybe it was something linked to the old "SwanStation" core or something linked to my personal configuration.
I think you can close it. 
However thanks to have fixed the default - > 8mb ram and the save state for the 8mb, I was playing yesterday and cannot save the state because of the impossibility to save the 8mb ram, it was enabled by default by updating the core.
I was thinking to expose that to you but you've already fixed it. Thanks a lot.

**Comment by stenzek** [comment]
Yeah, copy/paste error when I added the option. You can save 8MB RAM states now anyway, but you definitely don't want to enable that option unless you're using a mod which needs it, it has the potential to break games.
