### ISSUE TITLE
failed to load eboot.pbp with compression level 0

### ISSUE THREAD

**Issue by ronnyc4** [stenzek/duckstation#2105]
**Game details**
SLUS01068 Nascar Rumble USA
SCUS94424 Bloody Roar II USA

**Description of the issue / bug**
.cue/.bin file work perfectly, but when converted to EBOOT.PBP with compression level 0 (psx2psp) the game failed to launch
as if it cannot recognize what game is it since it created a new memorycard named EBOOT_1.mcd

**Steps to reproduce**
convert nascar rumble, bloody roar II bin file to EBOOT.PBP using psx2psp with compression level 0
run the games with duckstation like usual
pops up message said memorycard has been created under the name EBOOT_1.mcd
![Screenshot (21)](https://user-images.githubusercontent.com/40845851/117975034-74065c80-b358-11eb-8ff5-c8423557285f.png)
failed to launch the game and go for the (memory card / cd ) menu instead
![2021-05-12_19-02-16](https://user-images.githubusercontent.com/40845851/117975751-3524d680-b359-11eb-9930-ebb9569a3fa8.png)

and when screen shooting the image file name only date there is no game id in the name.
"when converted with compression level 9 the games works fine
but base from personal experience the compression level 0 works better on psp and vita
so it would be nice to use the same EBOOT.PBP file (level 0) to each of them"

**Enhancements information**
when run with compression level 0 it created new memorycard named EBOOT_1.mcd as the file name
when run with compression level 9 it use the same memorycard with the .cue/.bin format games

**Hardware/software**
laptop ryzen 5 4600h using integrated graphic card
GPU Renderer - D3D11 (hardware)

**Emulator version**
latest development build Duckstation 0.1-3968-gd9151ceb (dev)

**Additional context**
every time new memorycard created (any new games) there is also pops up message said memorycard cannot be read and formatting

**Comment by stenzek** [comment]
Are you sure those PBPs are valid? Do they work on a PSP?

**Comment by stenzek** [comment]
Seems that when compressed_size == decompressed_size in the block, it's not a zlib stream. PSX-Packager confirms this. Will push a fix soon.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/69a266cdf26527fb176357bbab44047187aa4429
