### ISSUE TITLE
The game inputs sometimes get stuck

### ISSUE THREAD

**Issue by Kokyslav** [stenzek/duckstation#2107]
**Game details**
- i.e SLUS-01503 Harry Potter and the Chamber of Secrets (USA)

**Description of the issue / bug**
- Sometimes, the inputs looks like is stucked and it's not able to stop the player. I think it's caused by squeezing many inputs at once, the game then loses the value of the input and the input gets stuck, causing the player to keep moving. I play on keyboard, on notebook. But if you click on the input that seems to be "stucked", it resets and player stops.

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
- No, a only have Discord and Opera GX opened.
2. Which controller backend are you using in general settings
- The game is played on notebook with notebook's keyboard, and controller type is "Digital Controller".

**Steps to reproduce**
- Try to have 5 or more inputs clicked at once, and quickly release them all (maybe it will work in a certain order). One of the inputs stay stucked and player will keep moving.

**Enhancements information**
- I tried to manage enhancements like all on and all off, restarting the program after changing the stats, and nothing happened, it's still sometimes stucks.

**Hardware/software**
- CPU: AMD A4-9125 RADEON R3, 4 COMPUTE CORES 2C+2G, 2300 Mhz, 2 Core(s), 2 Logical Processor(s)
- Graphics card: AMD Radeon(TM) R3 Graphics
- OS: Windows 10 (20H2)
- Rendered: D3D11

**Emulator version**
- DuckStation 0.1-3968-gd9151ceb (dev)

**Additional context**
- All my advanced and enhancements options are off, and no cheats before been activated. My dump is verified, and everything seems to be in order. 
- If you have any questions about this bug, i'll try to answer immidiately.

**Comment by stenzek** [comment]
This sounds like a key rollover issue, maybe qt isn't sending all the release events. Try nogui

**Comment by Kokyslav** [comment]
It's the same for both, qt and nogui.

**Comment by stenzek** [comment]
I wonder if this is a game bug then, or maybe unique to your system. I have no issue pressing and releasing 8+ keys at once.

[padtest.zip](https://github.com/stenzek/duckstation/files/6468082/padtest.zip)

You can use this homebrew program to check what the emulated console thinks the state of the buttons are. The "show controller input" option in display settings will also show which buttons are pressed. See if they're stuck in both of these.

**Comment by Kokyslav** [comment]
After some testing, i noticed that it doesn't stuck when I press a 5 or more buttons at once, but only click with 2 buttons, and the input is stucked. I'm attaching a picture with the padtest and NohBoard, which shows that I don't hold any input, but DuckStation shows that I do. It's kinda annoying, when you go to finish and suddendly the game still going like no cares of inputs.
![image](https://user-images.githubusercontent.com/52084834/118028601-8df96c80-b363-11eb-9344-77e01f172e8c.png)

**Comment by stenzek** [comment]
I wonder if it's something else then, maybe keyboard layout related... because I can't reproduce this at all.
