### ISSUE TITLE
Duckstation not recognizing specific inputs on a specific controller. 

### ISSUE THREAD

**Issue by Raginhari7** [stenzek/duckstation#2108]
Forgive me if this particular issue has already been discussed, but I did a search and wasn't able to find anything similar.  That, and I suspect this is probably gonna be a niche case.
I'm trying to map my original PSX Dual Shock controller using a USB converter that was made by Finera.  For some reason I can't seem to get Duckstation to recognize the L1 and R1 buttons on it.  The converter, though cheap, does function, save for the vibration feature that I haven't gotten to work yet (don't really care about that anyways).  
I'm seeing activity from all of the buttons in the device properties pane in Windows 10, and they all map to ePSXe just fine... but I don't want to play ePSXe. Furthermore, I'm also using a different USB converter by HDE for my original PSX digital controller.  That controller maps perfectly.
So why do y'all think this one controller's L1 and R1 seem to be giving me issues?  I'm bewildered, seeing as I know the buttons are working.  Thanks for any light shed on this topic. Great emulator, otherwise. :)

**Comment by mirrornoir** [comment]
If all of the inputs are showing up for you in Windows settings and other applications, then the dinput controller backend in General settings will likely solve your issue. The SDL controller backend relies on profiles made for specific controllers and adapters and it's likely the some of the info for your specific adapter is missing from the SDL controller database. [See here](https://github.com/stenzek/duckstation/#sdl-game-controller-database) for more info about how to address that yourself. However the dinput backend should be sufficient.

**Comment by Raginhari7** [comment]
Thanks so much for the quick and detailed response.  I'll try/check all that out as soon as I get the chance. :)

**Comment by Raginhari7** [comment]
Well, that was absolutely it.  I didn't even know that was an option, nor would I have understood the distinction.  Thanks again for the nudge in the right direction. :)
