### ISSUE TITLE
[No Gui / Fullscreen UI] Emulator stays paused after pressing the menu hotkey in the disc change or cheats window

### ISSUE THREAD

**Issue by ds22x** [stenzek/duckstation#2109]
**Game details**
No GUI / Fullscreen UI

**Description of the issue / bug**
When opening the disc change or cheats window while using the fullscreen UI menu with "Pause in menu" enabled, if you press the menu hotkey again, it will open the fullscreen UI menu again while keeping the previous window open.
And when you close the window, the emulator stays paused until you press the Pause hotkey to untoggle it, with selecting "Resume game" doing nothing.

**Controller Troubleshoot Report**
1. None whatsoever.
2. SDL

**Steps to reproduce**
Press the menu hotkey, enter the cheats or disc change submenu, press the menu hotkey again, press B/O/'Controller Back'.

**Enhancements information**
-5x Internal Resolution Scale
-Bilineair Texture Filtering
-True Color Rendering
-Disable Interlacing
-PGXP Geometry, Texture, and Culling Correction

**Hardware/software**
Intel Core i5 9300H, Nvidia GTX 1650, Windows 10 Pro 20H2
D3D11

**Emulator version**
0.1-3968-gd9151ceb (dev)

**Comment by Cloneg** [comment]
Try to update to the latest preview version 0.1-4021. It doesn't happen to me.

**Comment by ds22x** [comment]
Just tried 0.1-4021-gf2cf8d29 (master) and nope, still the same.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/5ca50d81a0a58d3882ea1950e3cba50a33932ff3
