### ISSUE TITLE
Android - visual cropping on touch controls

### ISSUE THREAD

**Issue by fefo-dev** [stenzek/duckstation#2115]
Lastest build - 3968 from May 8

Noticed these strange framing issues while trying to resize controllers. This is a full frame picture, 1920x1080 - notice the cropped edges on some controllers:
https://images2.imgbox.com/47/e9/dYkTTmha_o.png

Buttons presses also have a similar issue:
https://images2.imgbox.com/05/1a/WaJdqjmH_o.jpg

DPI changes made no difference whatsoever. Dunno other relevant tests in this case, feel free to ask.

**Comment by fefo-dev** [comment]
https://files.catbox.moe/532yhe.mp4

Something I noticed by chance: you can "fix" it by moving a button to an edge - or make it worse. If I leave R1 on the right edge for example the second pic issue will not happen too (all face buttons had this problem, however CIRCLE has a uneven crop as shown).

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/0c1ac4e9a673de910fb764915fd9cbf41a677dab
