### ISSUE TITLE
Detecting games inside archives files like retroarch

### ISSUE THREAD

**Issue by Ninaadark18** [stenzek/duckstation#2116]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Is your feature request related to a problem? Please describe.*maybe and maybe not*
A clear and concise description of what the problem is. Ex. I'm always frustrated when [extracting the zip file I go out of space]

**Describe the solution you'd like*i hope you make the emulator search inside archives files and detecte games*

**Describe alternatives you've considered**
It's would not long to wait 5-10s while the emulator get the game from the archive file and start, also i want to mention the game shouldnot be extracted to local, and if it is after we close it it must be deleted
**Additional context**
I don't have

**Comment by stenzek** [comment]
No. See my comments here https://github.com/stenzek/duckstation/issues/620
