### ISSUE TITLE
X-Men - Mutant Academy (USA) broken sprites when upscaling

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#212]
![Capture](https://user-images.githubusercontent.com/31968468/78209908-1b795480-74f4-11ea-8b5f-ba2181538ce1.PNG)

**Comment by HeroponRikiBestest** [comment]
X-Men - Mutant Academy (Japan) also has this issue, although the Success logo appears after the bios screen, then the game freezes. The general European and German releases boot with no issues.

**Comment by kurayami6** [comment]
X-Men Mutant Academy 2 also hangs instantly after BIOS. I can see it frozen on this screen if I turn on "Show VRAM"

![SLUS-01382_2020-04-24_23-26-58](https://user-images.githubusercontent.com/31968468/80217622-5b5ed200-8683-11ea-9da7-bb8cf4ad3769.png)

**Comment by stenzek** [comment]
Might be fixed with the change which fixed https://github.com/stenzek/duckstation/issues/408

**Comment by kurayami6** [comment]
Both now boot but graphics are a bit screwed up with OpenGL and D3D11. Should I close this and make a separate issue?

**Comment by stenzek** [comment]
Looks like typical texture coordinate issues with flipped polygons when upscaling, same as all the other games. We should probably just make a single thread for them all because they all share the same cause.

**Comment by stenzek** [comment]
Merged with #427.
