### ISSUE TITLE
Dream Generation - Koi ka Shigoto ka!... (Japan): Save Game issue

### ISSUE THREAD

**Issue by waspennator** [stenzek/duckstation#2121]
**Game details**
SLPS-01482 Dream Generation - Koi ka Shigoto ka!... (Japan)
Redump Verified

**Description of the issue / bug**
I don't know why, but when I boot this game in particular up, Duckstation throws up an "Memory card could not be read, formatting" message, followed by a "Failed to Save to Memory Card message".

**Steps to reproduce**
Boot up the game and look at the save notification on the top, it should say it could not be read, formatting, followed by saying it failed to save to the memory card.

**Hardware/software**
i5 6600k
Geforce GTX 1070
Windows 10
Vulkan 

**Emulator version**
0.1-4042 Preview Build

**Additional Context**
![Duck game issue](https://user-images.githubusercontent.com/78768499/118386826-64487b80-b5d7-11eb-8032-56136119b093.png)

**Comment by stenzek** [comment]
Can't have question marks in filenames in Windows.

Fixed in https://github.com/stenzek/duckstation/commit/1fe2a1b1e65338bd81ef21f4b83ffc9796260374, but could be a while before it gets released, looks like GitHub's builders are down.
