### ISSUE TITLE
Audio anomaly when realtime synthesis music playback begins

### ISSUE THREAD

**Issue by vanfanel** [stenzek/duckstation#2123]
Hi @stenzek !

I found this little annoyance months ago, but hadn't reported it.
On Squaresoft games using realtime synthesized music (not streamed audio), just before the first note starts playing theres a strange sound, and after that music plays normally.

**How to replicate:** just load FF7 and let the credits music play. You will hear this strange and reverberated sound before the first tone of the song is played.

You can hear it multiple times after that, just before any realtime piece of music.

Happens on every DuckStation build I have done: NOGUI, X11 and LibRetro. It also happens in both ARM (aarch64) and X86_64.

**Comment by stenzek** [comment]
I'm not hearing it, but I tend to not be very good at noticing such things.

[SCUS-94163_2021-05-17_19-26-36.zip](https://github.com/stenzek/duckstation/files/6492824/SCUS-94163_2021-05-17_19-26-36.zip)

Here's an audio dump from the first few seconds - can you identify where this anomaly is?

Keep in mind that FF7 does heavily use reverb, so some amount is expected.

**Comment by stenzek** [comment]
Closing due to lack of response.

**Comment by vanfanel** [comment]
@stenzek I am under some BIG pressure with exams, I will go back to this when things settle down in my life. Please forgive me. I couldn't find any defects on your recording, but I have to compare it against my own builds from latest GIT, etc.

**Comment by stenzek** [comment]
All good, if it's still an issue we can always re-open.

**Comment by vanfanel** [comment]
@stenzek I had time today and build the latest GIT version for both X86_64 and aarch64, both running GNU/Linux.
I also built it both qt5 and NOGUI versions.

-On every situation, I got the strange noise when realtime music starts as I reported on the first message.
-I can NOT hear the anomaly on your audio dump. 

Is there a way to directly dump the duckstation audio on GNU/Linux?
I would like to record the anomaly, so you can hear it for yourself.

**Comment by vanfanel** [comment]
@stenzek I found something VERY interesting: the USA/NTSC version of FF7 does NOT show the anomaly.
Seems to happen on the PAL version only.
