### ISSUE TITLE
Making fast boot disabled by default.

### ISSUE THREAD

**Issue by Pesukarhu7** [stenzek/duckstation#2124]
Is your feature request related to a problem? Please describe.

All my games just showed black screens on boot no clue why until some dicking around in the setting to find fast boot was the cause.

Describe the solution you'd like

Id like for it to be disabled by default as it would mean all-around less confusion and i dont think something that makes games unable to even boot should ever be on by default.

Additional context

btw this is on android

**Comment by 6lackmag3** [comment]
Never had that issue on Android 🤔 All games start fine with fast boot on.

**Comment by stenzek** [comment]
Nope. It's not the emulator's fault that you're using bad dumps/bioses.

I have it disabled by default on android only because the users there are much more aggressive. If I disabled it on desktop people would complain that the emu wasn't authentic. I can't win.
