### ISSUE TITLE
Ability to use Mayflash bar + Wiimote as a gun?

### ISSUE THREAD

**Issue by jacklongford** [stenzek/duckstation#2126]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Is your feature request related to a problem? Please describe.**
I don't know if this could ever happen, however would it be at all possible to implement Mayflash bar + Wiimote support as a way to emulation a gun for use in games such as Time Crisis, Point Blank, Die Hard etc? I have an Android tablet which is compatible with both however I'm not sure if anything like this would be feasible. Thanks!

**Describe the solution you'd like**
Ability to use Mayflash bar + Wiimote as a gun.

**Describe alternatives you've considered**
I don't know of any alternatives.

**Additional context**
None.

**Comment by stenzek** [comment]
Not something I'm really interested in looking into.

If you could use something else to make the wiimote emulate a mouse, then it would "just work".

**Comment by ckeisc** [comment]
Use Dolphin bar mode 2, and it would emulate a mouse, and you can map a few buttons on Wiimote.

**Comment by jacklongford** [comment]
> Use Dolphin bar mode 2, and it would emulate a mouse, and you can map a few buttons on Wiimote.

Just tried this but it doesn't work unfortunately.
