### ISSUE TITLE
Hotkey to swap memory cards in slots.

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#2127]
**Is your feature request related to a problem? Please describe.**
In some games the slot 2 for memory card isn't supported making the memory card in that slot useless unless manually set to slot 1.

**Describe the solution you'd like**
A hotkey to swap the cards in the slots from 2 to 1 and back, this way both cards could be used in games that don't support slot 2.

Cheers.

**Comment by stenzek** [comment]
Duplicate of https://github.com/stenzek/duckstation/issues/1242

**Comment by foxsevent** [comment]
Apologies, missed that one.
