### ISSUE TITLE
Softlock in Chicken Run (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#213]
Start the game, go to hut 16 to get the butter knife, pick it up, talk to Babs and the game will softlock. Ginger will just stand there blinking forever.

![SLUS-01304_2020-04-02_22-10-11](https://user-images.githubusercontent.com/31968468/78243668-e7bc2000-752f-11ea-8e01-112203b922d7.png)

![Capture](https://user-images.githubusercontent.com/31968468/78243711-f3a7e200-752f-11ea-84ce-0813c7b5b0c6.PNG)

**Comment by stenzek** [comment]
Should be fixed in latest build. Hopefully doesn't regress anything else, CD-ROM code is really touchy.

**Comment by kurayami6** [comment]
Fixed. Thanks.
