### ISSUE TITLE
CMake Error at src/duckstation-qt/CMakeLists.txt:136

### ISSUE THREAD

**Issue by zagahlo** [stenzek/duckstation#2132]
I'm getting this error configuring the build system (cmake -DCMAKE_BUILD_TYPE=Release -DQt5_DIR ....)

```
CMake Error at src/duckstation-qt/CMakeLists.txt:136 (add_executable):
  Cannot find source file:

    ../duckstation/dep/mac/MoltenVK/libvulkan.dylib

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .h .hh .h++
  .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc

```

**Comment by stenzek** [comment]
You did not fill out the issue template. Closed.

Also, please read the instructions in the readme, I'm guessing you did not clone the submodule.

**Comment by zagahlo** [comment]
Thanks! It worked.

Shall I suggest a change to the [README.md building macOS section](https://github.com/stenzek/duckstation#macos-1)

Add a new step **between steps 2 and 3**:
_2.1. Move the cloned MoltenVK './dep/mac' folder into './duckstation/dep' folder_

Sorry about not fill out the template.
Thank you for your work.

**Comment by stenzek** [comment]
Step 2 is correct. The CI uses that exact command: https://github.com/stenzek/duckstation/blob/0474454e0b1e7618f7a51f1158e0c3c30de8281d/.github/workflows/rolling-release.yml#L374
