### ISSUE TITLE
The clunky touch controller android

### ISSUE THREAD

**Issue by konami123444** [stenzek/duckstation#2133]
The controller menu on android right now is not good
For some reason you need to click the edit menu all the time when you want to edit a thing 

You should do something similer to ppsspp 
Where all the option is there at your left screen for easy edit

The sizing of the virtual button is very bad 
It like a volume rocker where time it goes from volume 20 to 22 and miss 21 
Hopefully you get the picture 

![croppedImage.png](https://user-images.githubusercontent.com/82933935/118780353-26d53e00-b8b6-11eb-817d-990a9f06140a.png)

Newpipe audio controller 
You need to turn up the volume by swiping down and turn down by swiping up

 Do something like this where you can push your thumb up and down to the size that you want 
Maybe do it like 
Each size option is a small bar withen a bar that look like a video game loading bar

**Comment by stenzek** [comment]
Issue template ignored again.

I've added the features people asked for (layout editing, resizing), and you still complain. It's a free, open-source app, if you don't like it, submit a pull request, or stop complaining.

The touchscreen controller is quite possibly the most boring thing I could work on. DuckStation makes no money, my sole motivation is what I find interesting. Nagging me about these things makes me even less likely to want to change it.
