### ISSUE TITLE
Prevent Duckstation from appending game region on memory card filename

### ISSUE THREAD

**Issue by ugoplatamia** [stenzek/duckstation#2136]
**Is your feature request related to a problem? Please describe.**
Duckstation appends the region of the game as the filename on the memory card. I use Duckstation in conjunction with libretro/Retroarch and it names memory cards according to the filename.

**Describe the solution you'd like**
The memory card filename should be the filename of the game plus the memory card slot.

Ex. Game: "Castlevania Chronicles.chd"
Current behavior: "Castlevania Chronicles (USA)_1.mcd"
Wanted behavior: "Castlevania Chronicles_1.mcd"

**Describe alternatives you've considered**
(Only tested under Android)
3 Dots Menu > Start File > Select the game (to bypass the game directories list)
-For single disc games, this used to work recently, but now it also appends the region as the memory card filename. 
-For multi-disc games it append spaces as "%20" in the memory card filename. (This does not happen if using the game directory list, but it appends the region instead)

-Ex. Game: "Chrono Cross.m3u"
Current Behavior: "Chrono%20Cross_1.mcd"
Wanted Behavior: "Chrono Cross_1.mcd"

Since libretro builds are now available again, I can try to use the libretro core exclusively instead of using the individual desktop & android apps.

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/ff0bd7abc4a2cb21a5e545be0ad7ca2e7f30cad4 as "file title" memory card mode.

It should resolve the %20 to a space on Android too.
