### ISSUE TITLE
Software render readbacks crashing Duckstation.

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#2139]
**Game details**
[Serial Code, Region]
Broken Sword 2 SLUS-00812 

**Description of the issue / bug**
Crashes on boot up, no enhancements. 

**Steps to reproduce**
Enable "Use software render for readbacks" start Broken Sword 2.

**Enhancements information**
None

**Hardware/software**
i5 9000h 4ghz
Gefroce 1650
16GB ram
Win10
DX11 render.

**Emulator version**
Newest preview 

**Additional context**
Crash log/dump attached.
[Crash.zip](https://github.com/stenzek/duckstation/files/6511322/Crash.zip)

**Comment by stenzek** [comment]
Should've been fixed with https://github.com/stenzek/duckstation/commit/245dd5b27a0402b05a7b4602348b87ccdd0f1cce
