### ISSUE TITLE
Evil Dead - Hail to the King immediatly softlocks 

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#214]
The game starts in the item menu and you're supposed to press triangle to exit it and start playing. But pressing the button doesn't exit the menu. It makes the noise indicating you pressed the button but nothing happens. Tried with both digital and analogue. Also tried the game in Beetle PSX and it works fine.

![SLUS-01072_2020-04-03_12-05-19](https://user-images.githubusercontent.com/31968468/78314925-3bb61b80-75a7-11ea-91d2-385b9d70f662.png)

**Comment by kurayami6** [comment]
Still happens as of the latest version.
