### ISSUE TITLE
8bitdo xinput bluetooth not recognised

### ISSUE THREAD

**Issue by 9s78af9s87f9sd8f7** [stenzek/duckstation#2140]
**Description of the issue / bug**
I have 2 8bitdo controllers, sf30 pro and a sn pro 2

Both of those will not be recognised when i connect them in xinput mode  ( on the pads, not in duckstation) using bluetooth and try to configure them in controller settings.  I have tried changing the controller backend from sdl, xinput, dinput.

They will be recognised if they are set to dinput mode (on the pads, not in duckstation.) and the controller is set as normal to sdl, But then the paddle buttons on the underside of the pro 2 will not be recognised, and analog triggers will be seen as digital

If i just use usb, then both controllers will work perfectly,  but it's just bluetooth where the problem exists.

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
2. Which controller backend are you using in general settings

None 
I have tried all 3

**Note:**
If you are using Duckstation on Android device please consider the following before report:
Are you using any kind of "memory optimizer" program such as: Ccleaner, Wisecleaner, Clean Master, Boost Android etc. ?
(if so, please, consider create an exception on it first and test; or even remove / uninstall it retest and then, if the problem persists continue with the report.

**Steps to reproduce**
[Try to provide as much detail as possible to reproduce the issue]
See above
**Enhancements information**
[Make sure they are all turned off before report]

**Hardware/software**
[If Android, which phone and Android version]
[If desktop, your CPU, graphics card, and operating system]
[GPU Renderer - D3D11/OpenGL/Vulkan]

This on windows
i5  3570
gtx 1060
vulkan

**Emulator version**
[Shown in the title bar of the emulator]
0.1-4071-g64e0d83d (dev)

**Additional context**
[Add any other context about the problem here]

[duckstation.log](https://github.com/stenzek/duckstation/files/6511490/duckstation.log)

**Comment by stenzek** [comment]
Probably needs a game controller db entry.

**Comment by 9s78af9s87f9sd8f7** [comment]
There are no problems with either controllers in retroarch, whether i use bluetooth or usb, but here are some shots showing the controller is picked up in windows.

![controller1](https://user-images.githubusercontent.com/84475789/118962008-d6fd8200-b95c-11eb-8126-acc4ca85965f.JPG)
![controller 2](https://user-images.githubusercontent.com/84475789/118962036-dcf36300-b95c-11eb-97b8-185e9996ed5d.JPG)

**Comment by stenzek** [comment]
SDL requires a mapping to work with some of these controllers. Like I said, try creating one, and dropping it in the duckstation user directory as `gamecontrollerdb.txt`.

I can't do anything about it from here, since I don't own one of these controllers.

**Comment by 9s78af9s87f9sd8f7** [comment]
I opened the db file to check if the pro 2  was listed, and it is ,so i updated the db file to the newest one and i get the same results as before.

I then installed SDL2 gamepad and that finds the sn30 pro 2 in bluetooth mode when only when it is set to dinput mode on the controller .  When i connect using bluetooth and set the controller to Xinput mode,  the SDL2 programme does not detect the controller.
 
![tool capture dinput](https://user-images.githubusercontent.com/84475789/119200951-df051100-ba85-11eb-92ce-c32824898e66.JPG)
![tool capture xinput](https://user-images.githubusercontent.com/84475789/119200967-e4625b80-ba85-11eb-89ff-ca7fcfad85c9.JPG)


usb connection works perfectly.

So to try and rule out that it might be a problem with the bluetooth receiver, i have  bought another model.

**Comment by Ryusan-AT** [comment]
On my side, I use an 8bitdo SF30 Pro controller, and I don't have any problem with Bluetooth or USB with duckstation in Xinput
(I'm running Windows 10 Pro 21H1 and the latest version of the emulator).

**Comment by 9s78af9s87f9sd8f7** [comment]
Time for me to take my foot out of my mouth lol

I found out why it is happening.

These controllers only have a problem when there's one small thing different and it's the same thing that applies to duckstation.
 I'm running on windows 7 ......... my mistake people
