### ISSUE TITLE
[Controller Settings] Add option to cancel an in-progress 'Rebind All'

### ISSUE THREAD

**Issue by dftf-stu** [stenzek/duckstation#2142]
**Is your feature request related to a problem? Please describe.**

If you use the "Rebind All" feature on the _Controller Settings_ page, and then find your controller-input is not-detected, there appears to be no way to cancel the rebind, once started.

(In my case, I have a PS1/PS2-to-USB adaptor, which supports the vibration feature.  I switched from "SDL" to "XInput" to see if that would allow _DuckStation_ to output vibration to it; however, after I clicked "Rebind All", I found none of the buttons on the controller were detected, and could then find no-way to cancel the rebinding.  Apparently my controller-adaptor goes via "DInput" only.)

**Describe the solution you'd like**

-  The simplest solution would be: after a user clicks the [Rebind All] button, it should change to a [Cancel Rebind] button, therefore allowing an easy-way to abort the rebind attempt.

-  Alternatively, maybe after clicking [Rebind All], _DuckStation_ could check for a controller to be present, and if not warn: "DuckStation cannot detect any controller is plugged-in.  Are you sure you want to continue doing a Rebind All?"

-  Or maybe prevent users from changing the "Controller Backend" dropdown to any setting no-supported controllers are detected for?

**Describe alternatives you've considered**

-  On Windows, you can use _Task Manager_ to kill the _DuckStation_ process.

- Or, as depicted in my screenshot, you can rapidly press any button to skip-through most of the waiting, though I still had to wait in the "Axis Bindings" section, as no keyboard-button or mouse-button could be assigned there.

**Additional context**

![DuckStation_XInputCannotSkip](https://user-images.githubusercontent.com/83965343/119008150-d0393400-b989-11eb-9ab8-4b099a2de84c.png)

**Operating System and DuckStation versions**
Windows 10 Home (64-bit; non-ARM) Version 21H1 (Build 19043.985; May 2021 update-level)
DuckStation (Preview Channel) v0.1.4057, AMD64 build

**Comment by stenzek** [comment]
Not really interested in doing this, sorry.

> The simplest solution would be: after a user clicks the [Rebind All] button, it should change to a [Cancel Rebind] button, therefore allowing an easy-way to abort the rebind attempt.

How would you differentiate between binding to the mouse button and clicking the cancel button?

> Alternatively, maybe after clicking [Rebind All], DuckStation could check for a controller to be present, and if not warn: "DuckStation cannot detect any controller is plugged-in. Are you sure you want to continue doing a Rebind All?"

People do use keyboards, myself included.

> Or maybe prevent users from changing the "Controller Backend" dropdown to any setting no-supported controllers are detected for?

See above.
