### ISSUE TITLE
Nogui crashes on startup

### ISSUE THREAD

**Issue by imvr17** [stenzek/duckstation#2149]
**Description of the issue / bug**
The nogui version of the emulator shows an empty white window and crashes right after opening the executable

**Steps to reproduce**
-Double click on duckstation-nogui-x64-ReleaseLTCG.exe
-Watch it open a white empty window
-Wait and see how it closes itself

**Hardware/software**
-Intel Celeron N3060 @ 1.6GHz (2 CPUs) 
-Integrated graphics
-Windows 10

**Emulator version**
0.1-4057-g2285e219 (but it started a few updates ago)

**Additional context**
QT version works almost flawlessly

**Comment by stenzek** [comment]
Assuming you had exclusive fullscreen enabled, this is fixed in https://github.com/stenzek/duckstation/commit/6aa78b11feb6fa9eb60ed00132a1d021412a8a5b (also in the dev/latest branch).

Otherwise, I can't fix it without a crash dump.

**Comment by imvr17** [comment]
Well, I had exclusive fullscreen disabled and I didn't know how to make a crash dump, but then I downloaded another update and the issue suddenly got fixed 

Sorry for bothering you, and keep up the great work!
