### ISSUE TITLE
[SLES-00598 Jersey Devil (Europe)] freezes after in-game video

### ISSUE THREAD

**Issue by AD010** [stenzek/duckstation#2150]
**Game details**
SLES-00598 Jersey Devil (Europe)

**Description of the issue / bug**
 game freezes on frog boss after in-game video

**Steps to reproduce**
game work fine, but full freezes on frog boss after in-game video (controls not work after this)

**Hardware/software**
Intel Celeron G1840
Intel HD GT1 (Haswell)
8 GB RAM DDR3
Windows 10 Pro x64 (1909)
[GPU Renderer - D3D11 and OpenGL]

**Emulator version**
0.1-4071-g64e0d83d (dev)

https://user-images.githubusercontent.com/46242741/119113645-fadcc880-ba2d-11eb-9ab1-6dc2c7a8a617.mp4

**Comment by stenzek** [comment]
Invalid. I told you on Discord that I do not support romhacks, only original games. If the same issue happens on the original game, then I can investigate it.
