### ISSUE TITLE
"Skin color issues" in Winning Eleven's games

### ISSUE THREAD

**Issue by CometHunter92** [stenzek/duckstation#2153]
Tried "World Soccer Jikkyou Winning Eleven 4" (SLPM-86291) and "World Soccer Winning Eleven 2002" (SLPM-87056) and, well, it's kinda strange but "white" players have "black" skin.
I'm not racist but, their original skin is white. Like in the Ireland team, or the Italy team. Heavy patched games (that in Italy are really much diffused) are affected too.
On the original hardware and in pcsx the skin is the "correct one".
I haven't investigate enough to tell if other physical properties (like hair) are affected, I tested very little, but the skin color issue is soon noticeable.

**Comment by stenzek** [comment]
Issue template is not completed.
