### ISSUE TITLE
Problem with Cd-Audio (bin, cue)

### ISSUE THREAD

**Issue by altlyser** [stenzek/duckstation#2158]
Hi.
A very nice emulator. I changed it as the default in Launchbox, but I'm having trouble with "audio track" games.
All games are in bin + cue format (not track01.bin track02.bin etc.)
Tekken 1 (USA).cue has "cue parse error at line 49: invalid index location '61: 20: 10" error.
The bin file itself runs but no music.
Please help, I don't want to go back to epsxe :/ it works there.

`FILE "Tekken 1 (USA).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    INDEX 01 13:40:06
  TRACK 03 AUDIO
    INDEX 01 14:31:10
  TRACK 04 AUDIO
    INDEX 01 17:17:52
  TRACK 05 AUDIO
    INDEX 01 19:46:29
  TRACK 06 AUDIO
    INDEX 01 24:01:58
  TRACK 07 AUDIO
    INDEX 01 27:02:62
  TRACK 08 AUDIO
    INDEX 01 29:58:06
  TRACK 09 AUDIO
    INDEX 01 33:07:69
  TRACK 10 AUDIO
    INDEX 01 35:48:28
  TRACK 11 AUDIO
    INDEX 01 38:29:10
  TRACK 12 AUDIO
    INDEX 01 40:54:07
  TRACK 13 AUDIO
    INDEX 01 44:09:09
  TRACK 14 AUDIO
    INDEX 01 46:52:74
  TRACK 15 AUDIO
    INDEX 01 48:35:64
  TRACK 16 AUDIO
    INDEX 01 49:18:72
  TRACK 17 AUDIO
    INDEX 01 50:05:67
  TRACK 18 AUDIO
    INDEX 01 51:29:71
  TRACK 19 AUDIO
    INDEX 01 52:44:43
  TRACK 20 AUDIO
    INDEX 01 54:22:11
  TRACK 21 AUDIO
    INDEX 01 56:12:49
  TRACK 22 AUDIO
    INDEX 01 57:58:29
  TRACK 23 AUDIO
    INDEX 01 59:35:44
  TRACK 24 AUDIO
    INDEX 01 61:20:10
  TRACK 25 AUDIO
    INDEX 01 63:05:59
  TRACK 26 AUDIO
    INDEX 01 64:38:37
  TRACK 27 AUDIO
    INDEX 01 65:53:11
  TRACK 28 AUDIO
    INDEX 01 67:42:51
`

**Comment by stenzek** [comment]
Thanks for reporting, I knew there'd be regressions from the new cue parser. Will fix soon.

In the meantime, if you switch back to the dev/latest channel, it won't have this problem.

**Comment by stenzek** [comment]
Easy fix, https://github.com/stenzek/duckstation/commit/5556d8221b2094e2aadf26539c88bbac2b78cbf5 should sort it out. Should be released in about 10-15mins.

**Comment by Ryusan-AT** [comment]
great, I also had the same problem with the last 'preview' version.

**Comment by Ryusan-AT** [comment]
je viens de mettre à jour duckstation, mais j'obtiens une nouvelle erreur du coup.

![Sans titre](https://user-images.githubusercontent.com/32717360/119256524-61deb680-bbc1-11eb-9a04-4d677283865c.jpg)

Contenu de mon cue :

`FILE "Lunar_fr_cd2.bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    PREGAP 00:02:00
    INDEX 00 65:41:54
    INDEX 01 65:41:55
  TRACK 03 AUDIO
    INDEX 00 68:10:27
    INDEX 01 68:12:27`

**Comment by stenzek** [comment]
That's an... interesting combination. This wouldn't have been handled properly with the old libcue parser either. Will sort it out later.

**Comment by Ryusan-AT** [comment]
For information, I'm part of a French translation group for video games, the game being Lunar SSSC PS1, and this cue is automatically created by our tool that reformats the final iso.

**Comment by stenzek** [comment]
Do you know what the pregap of the second track is actually supposed to be? The old behavior would've to essentially create a one second pregap, and the `PREGAP` statement would've been ignored.

**Comment by Ryusan-AT** [comment]
Not at all, sorry. the cue is created by our iso rebuild tool (the iso is rebuilt entirely from scratch). And our hacker, the one who created the tools, is not available for me to ask.

Just that it was working fine before your changes (so, even in the 'lastest' version).

**Comment by stenzek** [comment]
Right. Well, I suspect that other tools would also choke on this file. I'll special case it anyway - that was actually one of my other goals with the parser rewrite, be more strict and catch potential issues in cuesheets before they break games.

**Comment by altlyser** [comment]
Tekken works for me. Thanks! It is a pity that I removed Sled Storm today, because I had had enough :)

**Comment by Ryusan-AT** [comment]
Ok great. I now only use duckstation for PS1 emulation, so it would be a shame if it didn't work anymore. However, in multi-track, no worries (track1.bin, track2.bin, etc).

Congratulations on your excellent work, it's a pleasure, and you're very reactive to our requests ^^ Thanks.

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation/commit/16efffa403118ff72cef095d2aaf02e59eb5613b should sort it out (10-15mins).

**Comment by Ryusan-AT** [comment]
Great, it works. So you don't need a pregap if an index0 is specified?

**Comment by stenzek** [comment]
Correct. The data between index 0 and index 1 is effectively the pregap. From my understanding of cuesheets, the pregap command effectively does the same thing, but instead of using data from the file, it inserts silence. So the index 0 effectively overrides the silent pregap in this case.
