### ISSUE TITLE
Swimming in water in Duke Nukem - Land of the Babes breaks graphics, movement and framerate

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#216]
Stand on this platform and jump into the pool of water below.

![SLUS-01002_2020-04-03_14-26-10](https://user-images.githubusercontent.com/31968468/78321935-0b777880-75b9-11ea-936f-17b5d885091c.png)

The framerate will instantly plummet, Duke won't be able to move and the graphics will break.

![Capture](https://user-images.githubusercontent.com/31968468/78322327-23033100-75ba-11ea-8427-cb37973c500c.PNG)

**Comment by stenzek** [comment]
Please screenshot the GPU debug menu. It's possible this is due to a large number of readbacks which are just slow in the hardware renderer. Although depending on the access pattern and whether any rendering occurs inbetween, I may be able to optimize.

**Comment by kurayami6** [comment]
![Capture](https://user-images.githubusercontent.com/31968468/78326321-d45b9400-75c5-11ea-842e-783a803b92c1.PNG)

**Comment by stenzek** [comment]
Not seeing any slowdown here.

**Comment by kurayami6** [comment]
It's still happening as of the latest version. Using OpenGL or D3D11 duke freezes in place, the graphics break and the framerate tanks.

![Capture](https://user-images.githubusercontent.com/31968468/78519075-81701f80-7805-11ea-9f21-8cf03e646d67.PNG)

Using software he gets stuck and the graphics break but the framerate is unaffected. 

![Capture2](https://user-images.githubusercontent.com/31968468/78519103-9c429400-7805-11ea-8962-9c14b0b115d0.PNG)

Here's my computer specs. 

![Capture3](https://user-images.githubusercontent.com/31968468/78519173-d2801380-7805-11ea-8d22-99c2389d2c6f.PNG)

**Comment by stenzek** [comment]
Framerate drops will be fixed in the latest build, since it doesn't need the round-trip to the CPU anymore. It's actually an interesting method of creating a screen wave effect.

In the hardware backends, it'll make the HUD shake as well. This is because the mask bit check is not currently implemented, I have it as a work-in-progress on another branch but it's not currently finished.

**Comment by stenzek** [comment]
Should hopefully all be fixed in the latest build. Turns out it was just the oversized copy, not the mask bit.

**Comment by kurayami6** [comment]
Fixed.
