### ISSUE TITLE
How to exit Fullscreen on DuckStation-nogui?

### ISSUE THREAD

**Issue by j8r** [stenzek/duckstation#2162]
**Is your feature request related to a problem? Please describe.**
Sorry for this dumb question: how to exit from DuckStation-nogui with a keyboard, and with a controller?
The Home/PS button does nothing, and same with the Esc button the keyboard too.
Also, same question for saving the state (nothing shown about this in the `Controller Settings` menu.

**Describe the solution you'd like**
- configurable exit bindings
- being able load/save state and exit with a controller, and of course keyboard

**Describe alternatives you've considered**
I've found some clues in several issues, but would like to have a proper solution.

**Comment by Cloneg** [comment]
Controller
Settings>Hotkey Settings> bind Open key Menu Button (e.g ps button) and then from the menu Exit Game.
Keyboard 
The same or  Settings>Hotkey Settings> bind Power Off System button (e.g Esc)

For save state you can configue in Hotkey Settings default are F1(load), F2(save), F3 and F4.

**Comment by j8r** [comment]
Thanks! That Quick menu will do it! Is it possible to have 2 bindings at the same time?

**Comment by Cloneg** [comment]
I don't think that button combinations is currently possible but there's already an open request for it. #1603

**Comment by j8r** [comment]
An issue I have now: I've set some options the configuration file, but when I start DuckStation the whole file is overwritten, instead of using the provided values and eventually adding the missing ones :confused:

**Comment by j8r** [comment]
An issue I have now: I've set some options in the configuration file, but when I start DuckStation the whole file is overwritten, instead of using the provided values and eventually adding the missing ones :confused:
