### ISSUE TITLE
Vib-Ribbon disc change not working

### ISSUE THREAD

**Issue by IlKiwi** [stenzek/duckstation#2164]
SCES-02873 Vib-Ribbon, (EU)

If i choose to play from a custom disc and select the ISO file with some mp3 files in it, the game simply ignores it and still asks me to insert a CD. 
I used PowerISO to create an ISO file with the music in it, I tried with .cue and .bin files, I tried changing the music files but still nothing.

CPU: Intel i5-8300H
GPU: Nvidia GeForce GTX 1650
OS: Windows 10
GPU Renderer: OpenGL

Version: 0.1-4046-g96330e55

**Comment by BloodRaynare** [comment]
VIb-Ribbon doesn't support mp3 files. You must create a CD audio images (44100Hz RAW PCM audio data) containing your custom songs. UltraISO can do that IIRC.

**Comment by stenzek** [comment]
Only raw bin files are supported as tracks in cuesheets. I might consider extending this to include wav, but MP3 is a proprietary format and has licensing issues, plus would require shipping an MP3 decoder library, or using WMF etc.
