### ISSUE TITLE
Pause menu is broken in Ducati World (Europe)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#217]
Happens with OpenGL, D3D11 and software. Pause the game and the menu will flicker in and out of existence.

![SLES-02821_2020-04-03_15-02-19](https://user-images.githubusercontent.com/31968468/78323042-58108300-75bc-11ea-8df0-1ed5e8878fd0.png)

![SLES-02821_2020-04-03_15-01-47](https://user-images.githubusercontent.com/31968468/78323044-5b0b7380-75bc-11ea-91c2-4281f8f3cc3a.png)

![SLES-02821_2020-04-03_15-02-13](https://user-images.githubusercontent.com/31968468/78323051-5f379100-75bc-11ea-8fee-1b6f14e6dff7.png)

**Comment by stenzek** [comment]
Fixed with GPU timings (not merged yet).

**Comment by stenzek** [comment]
Fixed in latest master.
