### ISSUE TITLE
OpenGL renderer broken on PowerVR drivers

### ISSUE THREAD

**Issue by Crypto137** [stenzek/duckstation#2170]
**Hardware/software**
Teclast P80 tablet running Android 10 Go Edition, Allwinner A133 CPU with integrated PowerVR GE8300 GPU.

**Description of the issue / bug**
OpenGL renderer doesn't work. On the games I've tested the emulator displays the following message: "Failed to initialize OpenGL renderer, falling back to software renderer.". A file titled "[bad_shader_1.txt](https://github.com/stenzek/duckstation/files/6533179/bad_shader_1.txt)" is created in the emulator folder (attached).

Not using any memory optimizer.

**Game details**
Tested with [SLUS-00756 Resident Evil 2 DualShock Edition (USA)] and [SLUS-00594 Metal Gear Solid (USA)]

**Controller Troubleshoot Report**
Touch controls, all default settings

**Steps to reproduce**
Launch any game

**Enhancements information**
No enhancements are used

**Emulator version**
May 18, 2021 Play Store Build

**Additional context**
The Vulkan renderer works, but produces visual glitches. Other applications that use OpenGL seem to function correctly on this device. Software mode works without any noticeable issues.

**Comment by stenzek** [comment]
It's a completely broken driver. Other people have reported the same issue, e.g. https://forums.imgtec.com/t/shader-doesnt-compile-on-fire-stick-4k/3184

I can't try to find a workaround since I don't have one of these devices, so I can't really do much about it, sorry.

But that's why they're all excluded on the play store.

**Comment by stenzek** [comment]
I came up with a theory as to why this might be broken; quoting myself:

```
so it's choking on untextured only-semitransparent
that'll result in something like
if (true)
  set output
else
  set output
  discard
I wonder if it doesn't like the DCE'ed discard
and if the discard was broken, that would mean that untextured polys would get rendered as opaque instead of transparent
which could explain the breakage in the vulkan driver
```

I've fixed this in https://github.com/stenzek/duckstation/commit/08876d132f8762b72a06dba5bf42020ed915c540, which is available in the preview build. Give it a try, it's in the preview build.

**Comment by Crypto137** [comment]
OpenGL seems to be working now, but produces visual glitches (such as horizontal lines and misaligned fonts) when rendering 2D graphics.

![Example 1 - SLUS-00594 Metal Gear Solid](https://user-images.githubusercontent.com/1700701/119462367-50c0b180-bd49-11eb-9329-14cd745f52eb.png)
![Example 2 - SLUS-00756 Resident Evil 2 DualShock Edition](https://user-images.githubusercontent.com/1700701/119462429-62a25480-bd49-11eb-9501-4458a213cdfa.png)
![Example 3 - SLUS-00067 Castlevania Symphony of the Night](https://user-images.githubusercontent.com/1700701/119462476-7057da00-bd49-11eb-92cb-8b7d7e52ab3c.png)

Here's my cache from the emulator folder if that's any help: 
[cache.zip](https://github.com/stenzek/duckstation/files/6537588/cache.zip)

**Comment by Crypto137** [comment]
After some more testing I've discovered that the 2D glitches with OpenGL get fixed when rendering at a resolution scale of 2x or higher.

**Comment by stenzek** [comment]
Same issue as on V3D/Pi4 I believe. Try with https://github.com/stenzek/duckstation/commit/eaab0cc0336a7803bd35b69cb33d571246eaf9d0

**Comment by Crypto137** [comment]
The issue remains, no visual changes.

**Comment by stenzek** [comment]
I can't do much else without having a device then, aside from trying other offsets.

Does the Vulkan renderer have this issue?

**Comment by Crypto137** [comment]
Vulkan does not have this issue.

However, it does have another problem that seems to have something to do with transparency (?). From the games I've tested, Castlevania seems to work properly, but in both Metal Gear Solid and Resident Evil 2 there are issues with semi-transparent 2D graphics.

![Screenshot_20210525-122302](https://user-images.githubusercontent.com/1700701/119474633-0a714f80-bd55-11eb-8604-ce7a69b69700.png)
![Screenshot_20210525-122310](https://user-images.githubusercontent.com/1700701/119474645-0e04d680-bd55-11eb-8095-72358bacc828.png)
![Screenshot_20210525-122600](https://user-images.githubusercontent.com/1700701/119474653-0fce9a00-bd55-11eb-9f43-e4b2ca3c73be.png)

**Comment by stenzek** [comment]
Ah. Not sure where to even begin with that one, either discard isn't working at all, or blending is broken.

I reduced the epsilon even further in the latest build, but other than that, I'm out of ideas to try remotely.

**Comment by Crypto137** [comment]
This seems to have done the trick, the horizontal lines are now gone in the OpenGL renderer. Excellent work!

**Comment by stenzek** [comment]
Great. I'll close this off then, one hardware renderer is better than none for these devices.
