### ISSUE TITLE
Pre-defined configuration options overwritten on first run

### ISSUE THREAD

**Issue by j8r** [stenzek/duckstation#2173]
**Description of the issue / bug**
When having only few options in `settings.ini`, DuckStation does not take them and then overwrites the whole file.

**Steps to reproduce**
Assuming you're on Linux and `~/.local/share/duckstation` is the duckstation directory:
```
cat > ~/.local/share/duckstation/settings.ini <<E
[Main]
StartFullscreen = true
E
```
Then start DuckStation: it is in windowed mode.

**Enhancements information**
Two possible solutions for my use-case:
- not ideal: pre-generate a config-file and exit, that can be changed after, like `mame -createconfig`.
- better: parse the existing `settings.ini` file, keep the defined values and set missing ones with the default values.

**Hardware/software**
Linux

**Emulator version**
Latest AppImage or Flatpak version.

**Additional context**
My use-case is to save some relevant settings, but not all are necessary. That's why I prefer to keep the "good defaults" for those, which may be subject to change.

**Comment by stenzek** [comment]
This is completely intentional. There's a version check on the settings file, and it resets to default if it fails. If you **must** use a custom config file, set `SettingsVersion` in `[Main]` to 3. But I will not support this configuration.

**Comment by j8r** [comment]
Good to know, thanks!

**Comment by j8r** [comment]
It works, but somethings is a bit weird: it takes the file as-is, and when I change one configuration a lot of other defaults will be also written to the file.

Can `-createconfig` also be considered?

**Comment by j8r** [comment]
Another weird thing:
- On a clean system (no settings.ini file), DuckStation set the Region to auto-detect
- On a settings.ini file missing this, it will set the Region to NTSC-U/C (US, Canada)

Other configurations may have this behavior too. I suspect some incorrect logic in the parser...

---

For those needing to set some options, now my only work-around is to do:
`timeout 1 ./duckstation-nogui-x64.AppImage`

Which will create the configuration file with the defaults and exit. Then, change your option values.

**Comment by stenzek** [comment]
I see no use case for that argument that I'm interested in, so no.

I'll check the fallback value for region later.

**Comment by j8r** [comment]
I checked some other affected options: it is also the case for VSync, TrueColor and RegionCheck.

Essentially the use case configuration versioning and automation.

**Comment by j8r** [comment]
I checked some other affected options: it is also the case for VSync, TrueColor and RegionCheck.

Essentially the use case is configuration versioning and automation.
