### ISSUE TITLE
Add a simple option to change the root directory for all "User" data from Documents to something else

### ISSUE THREAD

**Issue by skylord-a52** [stenzek/duckstation#2178]
**Is your feature request related to a problem? Please describe.**
Programs bloating my documents folder with unnecessary and often nondescriptive folders and files is a pet peeve of mine, especially when they're a portable installation and could just use their install location. I like to keep my documents folder for, well, my own documents, as much as possible.

Furthermore, I've already got my own folder for emulation set up, and I'd like to put all of Duckstation's files in there -- either in their own folders for things like BIOSs, or within Duckstation's folder for save states, caches, input profiles, etc. It's much nicer to have everything in one place than deal with executable and roms in one place, all other data in another.

**Describe the solution you'd like**
A quick and easy setting, probably under general settings, that lets you choose a root folder/path for all of the files that currently reside in C:/Users/<CurrentUser>/Documents/Duckstation. Changing this wouldn't move any files around or anything, just change the search location. 

If custom search locations for things like the BIOS folder are set, then changing the root path wouldn't disrupt those locations. There would also be a button that sets all subpaths to default, so that if you set a new root path and you do want to override your custom definitions for BIOS, memcard, etc. folders, you can do so easily.

Better yet would be if, on first run, the program asks the user for a path, and doesn't create any of the folders or files until it's given one or the user accepts the default path, so users don't have to deal with moving/deleting all the folders Duckstation creates on first startup.

**Describe alternatives you've considered**
There are options to change paths for certain things, like memcard and BIOS folders and maybe a few others, but you need to go through each setting tab and manually change it. Furthermore, there are some folders that do not have corresponding settings, meaning that there will always be some stuff hanging around in documents where it doesn't belong.

Edit: Just noticed there's an option to make a portable build, using a portable.txt file. That's great and I'll definitely use it, but I'd still love an in-program setting.

**Comment by stenzek** [comment]
Read the readme, this is something I considered from the very beginning. I'm starting to get real tired of people trying to tell me how to design my program. If you don't like the way I do things, fork it and maintain your own version, or don't use it.

Early on the shared data was very useful, as it allowed you to use multiple builds with the same memory cards and settings. Plenty of other emulators are the same, e.g. Dolphin.
