### ISSUE TITLE
240pTestSuitePS1 nothing  but a black screen

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#218]
https://github.com/filipalac/240pTestSuite-PS1/tree/master/binary

**Comment by stenzek** [comment]
Seems the initialization routines depend on the CD-ROM interrupts not triggering on the interrupt controller immediately. I fixed it by adding a delay, but I need to write hardware tests to figure out exactly what this delay is, as the CD-ROM is *very* touchy and prone to break games.

**Comment by Zet-sensei** [comment]
Seems to work now when testing.

![240p](https://user-images.githubusercontent.com/52127625/107223411-733af300-6a16-11eb-9359-6c5f00688cd8.png)

**Comment by stenzek** [comment]
Were you running the exe directly or from the disc? The disc code was the issue here and I haven't done anything specifically to address it.

**Comment by Zet-sensei** [comment]
From the disc image.

**Comment by stenzek** [comment]
Interesting. Different version maybe

**Comment by stenzek** [comment]
The emulator version of this works fine, the disc version is broken because it has incorrectly written CD access code which relies on the store buffer being emulated. Which I have no plans to do, since it would be way too slow, and no games depend on it.
