### ISSUE TITLE
game list search design flaw

### ISSUE THREAD

**Issue by designflaw222** [stenzek/duckstation#2180]
the game list only looks for .cue files, but even when you have .cue files, it doesn't find the game at all

it should also look for .bin files, and whatever other formats exist, should be an easy fix, currently only 15 out 30+ games are listed

**Comment by stenzek** [comment]
No. Bin files without cuesheets are not complete dumps - how would the emulator know where tracks start and end? (And don't mention epsxe, shipping a cue database is both legally questionable as well as unreliable)
