### ISSUE TITLE
Freeze on World Soccer Jikkyou Winning Eleven 3 - World Cup France '98 (Japan) (Rev 1) [SLPM_870.56]

### ISSUE THREAD

**Issue by soaresden** [stenzek/duckstation#2183]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

Please read before creating a new issue:

1. Make sure there is not already an open issue for this bug.
2. All enhancements **must** be off. To quickly disable all enhancements with affecting your normal config, in advanced options you can check "Disable All Enhancements".
3. All advanced options **must** be at their default values.
4. No cheats may be active. If you were using cheats, they should be disabled, and the game rebooted before reporting the bug.
5. Do not share save state files. Memory cards are okay.
6. Verify your dump, as we can not assist with issues resulting from bad dumps.
7. If playing PAL region software, please check whether or not the game has LibCrypt protection and that if it does, you have a correct SBI file (see https://github.com/stenzek/duckstation#libcrypt-protection-and-sbi-files for more information).
8. Please post your issue report in English as unfortunately this is the only language spoken by the developers. The Discord server has many helpful people if you need help translating.

**Remove everything before and including this line before submitting.**

**Game details**
[Serial Code, Region]
World Soccer Jikkyou Winning Eleven 3 - World Cup France '98 (Japan) (Rev 1) [SLPM_870.56]

**Description of the issue / bug**
[Describe what you are seeing and/or hearing during gameplay]

After passing every screen, logo brand with start, I'm stuck at this memory card screen
![image](https://user-images.githubusercontent.com/54243866/119891249-0a31a980-bf39-11eb-9856-32316ad893fe.png)

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
2. Which controller backend are you using in general settings

**Note:**
If you are using Duckstation on Android device please consider the following before report:
Are you using any kind of "memory optimizer" program such as: Ccleaner, Wisecleaner, Clean Master, Boost Android etc. ?
(if so, please, consider create an exception on it first and test; or even remove / uninstall it retest and then, if the problem persists continue with the report.

**Steps to reproduce**
[Try to provide as much detail as possible to reproduce the issue]

Just launch the game, pass the brand and you will get stuck at this screen too
Duckstation didn't crash
I don't know if it's related to memorycard or if the controller stop to respond ?

**Enhancements information**
[Make sure they are all turned off before report]
Tried to boot on PC Duckstation, also tried Batocera's pi4 Duckstation standalone
Tried with PCSX Rearmed on both PC and pi4, get stuck too
**Only pi4 Beetle PSX/Libretro passed this screen successfully** (don't know on PC libretro)

**Hardware/software**
[If Android, which phone and Android version]
[If desktop, your CPU, graphics card, and operating system]
[GPU Renderer - D3D11/OpenGL/Vulkan]

**Emulator version**
[Shown in the title bar of the emulator]
![image](https://user-images.githubusercontent.com/54243866/119891600-77453f00-bf39-11eb-9bfb-0c03ae956cd5.png)

**Additional context**
[Add any other context about the problem here]

EDIT: Thanks to Delta Oscar Uniform, setting the Settings **from Recompiler to Interpreter** solve the issue.
Subsidiary question, what can we do to make it work with recompiler ?
Can we add this game to a "interpreter only" game ?

**Comment by BloodRaynare** [comment]
Weird, it's just works just fine here with recompiler. Also, I'm currently using the same latest preview builds too.
![2021-05-28 08_05_04-World Soccer Jikkyou Winning Eleven 3 - World Cup France '98 (Japan)](https://user-images.githubusercontent.com/46045141/119914905-881ea080-bf8b-11eb-8ccc-f3827b2acbe0.png)
Have you checked your game's image dump hashes against redump?

**Comment by stenzek** [comment]
Executes code out of uncached ROM, needs recompiler icache.

**Comment by soaresden** [comment]
> Weird, it's just works just fine here with recompiler. Also, I'm currently using the same latest preview builds too.
> ![2021-05-28 08_05_04-World Soccer Jikkyou Winning Eleven 3 - World Cup France '98 (Japan)](https://user-images.githubusercontent.com/46045141/119914905-881ea080-bf8b-11eb-8ccc-f3827b2acbe0.png)
> 
> EDIT: Turns out, the game fails to load with recompiler if there's no options savefiles exist. So, for now the workaround for the recompiler is try to find an option savefile for this game or make it yourself with the game booted in interpreter mode.

Nice discovery ! 
If someone will try to load it, it will be stuck like me. It's a solution but not the best



> Executes code out of uncached ROM, needs recompiler icache.
Exactly what we figured it out. Delta told me you have a sort of "whitelist" to add it on ?
If yes, could you add it to so users won't have to manually switch for interpreter ?

**Comment by stenzek** [comment]
Yes, I'll push a gamesettings override for it later. Alternatively, you can set it yourself in game properties/compatibility settings (Force Recompiler ICache).

**Comment by soaresden** [comment]
Awesome ☻ ! Thanks
As soon as you push this, feel free to close this issue

**Comment by stenzek** [comment]
Override added in https://github.com/stenzek/duckstation/commit/4a13009af872476c0a675e9f72ea179c0eeef872.

I would not recommend giving the users the option to use the interpreter. There's only a few games which require it (e.g. Formula 1), since they expect stale code to execute out of the fully-simulated instruction cache. You're just throwing away performance for no reason otherwise.
