### ISSUE TITLE
Setting for each game

### ISSUE THREAD

**Issue by Lemoncak3** [stenzek/duckstation#2184]
Can you make the ingame setting saved only for that game instead of global setting? Maybe you can put the global setting when in menu before play the game? So ingame we can change the setting to which we want the games like since not all game have same setting. I know you can change ingame setting using hold button to each game and choose the setting but sometimes we have to see the actual performance to decide which setting is best for us, and back to game selection only to change the setting is a bit hard. Maybe you can consider this? Sorry for bad english, english is not my native language.

**Comment by stenzek** [comment]
1. You deleted the issue template so I'm ignoring your request.
2. This is already a thing. See game properties.
