### ISSUE TITLE
Ingame setting save to that game and not the global one.

### ISSUE THREAD

**Issue by Lemoncak3** [stenzek/duckstation#2185]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Is your feature request related to a problem? Please describe.**
Whenever i change the ingame setting the global one will be changed also. 

**Describe the solution you'd like**
Can you make the ingame setting is saved only for that game? Since not all game have same setting and i know about game properties in game selection menu but it's more convenient to change the setting ingame so we could see the actual performance ingame. Maybe you can put the global one in game selection menu like few other emulators so inside the game it's only changed for that game and not change the global one?

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by stenzek** [comment]
Again, this is already a thing. Open game properties while the game is running.

Please stop spamming my issue tracker.

**Comment by Lemoncak3** [comment]
But if i change the resolution for one game the others will have that same resolution with the recent changes.

**Comment by stenzek** [comment]
In the game list, right click -> game properties, user settings.

Or while ingame, view -> game properties, user settings.

**Comment by Lemoncak3** [comment]
I am using android and only that gear icon is diplayed and when i changet the settings inside other games will be changed as well
![Screenshot_20210529-112121](https://user-images.githubusercontent.com/67026697/120057863-ccd03780-c070-11eb-8c73-15ec459ff39e.png)
![Screenshot_20210529-112146](https://user-images.githubusercontent.com/67026697/120057867-cfcb2800-c070-11eb-96dd-cc4d791cf849.png)
When i changed the resolution to 4x other game will have 4x resolution as well. When i turned audio sync other game audio sync will be turned on as well.

**Comment by stenzek** [comment]
You never specified you were on android - how was I supposed to know that?

Anyway, I have no plans to make game properties accessible while ingame for android at this point. The desktop version can do it fine.

As an alternative, use the global settings to test in realtime. Then set them per game after you know what settings you want to use.

**Comment by Lemoncak3** [comment]
Okay thank you. Hope you will consider this in the future

**Comment by stenzek** [comment]
Audio/video sync are global settings and cannot be overridden per game. I will not be changing that - they're "system" settings, and should be consistent across all games.

Other settings like resolution/pgxp/filtering can be set per game.
