### ISSUE TITLE
[Suggestion] Load game EXE and extracted files from local disc

### ISSUE THREAD

**Issue by DCxDemo** [stenzek/duckstation#2186]
**Is your feature request related to a problem? Please describe.**
No. Just throwing in an idea.
Some emulators can run PS-EXE directly, but that obviously has one disadvantage of not being able to load files from CD. There was no PS1 emulator that ever attempted to address this issue.

**Describe the solution you'd like**
Do you think it would be possible to add the ability to load extracted games by creating a kind of virtual LBA map for the file system? Some file that will map a file on the local drive to some CD LBA value. may also pack all files including this info in a single archive for convenience. In cases game actually looks by file name, it would be possible to read file from local disc directly (using the root folder of loaded exe/cnf.

game folder (root)
-- system.cnf (file, 23)
---- psx.exe (file, 23)
---- gamedata (folder, 24)
------ gamefile.bin (file, 25)
------ gamefile2.bin (file, 555)

might also be applied as an iso patch system for simple mods/translations, etc without the need to ruin the target ISO. that's more like a modloader though.

Pros: 
* easier to mod existing games (especially ones with fixed lba adresses)
* easier to develop new games by having access to game files directly (cuts down ISO building time).

Cons:
* requirement to develop an additional format basically with the ways to create and load such files.
* risk of introducing yet another format of distribution for games/mods.
* inability to create a working ISO if file size will exceed original one (if modding existing ones).
* piracy concerns, however it's not like original ISOs are not pirated anyways.

**Describe alternatives you've considered**
Never existed. The closest I might think about are mkpsxiso's project xml files.
https://github.com/Lameguy64/mkpsxiso/blob/master/examples/example.xml

**Comment by stenzek** [comment]
Another option would be implying pcdrv, we have been discussing that on the PSXDEV Discord.
