### ISSUE TITLE
Widescreen patches database (PCSX2-like)

### ISSUE THREAD

**Issue by DCxDemo** [stenzek/duckstation#2187]
**Is your feature request related to a problem? Please describe.**
Widescreen hack is not aware of UI as mentioned in closed #1747. It also works poorly if original game was intelligent enough to cull the faces beyond 4:3 aspect ratio.

**Describe the solution you'd like**
PCSX2 addressed this issue with a per-game widescreen patch database (cheats_ws.zip).
Native PS1 widescreen patches can be found in this thread: https://forums.pcsx2.net/Thread-PSOne-Widescreen-Patches

**Describe alternatives you've considered**
It is possible right now to use Cheat Manager functionality to load these patches, but I'm sure it's inconvenient for many for just a proper widescreen.

**Comment by stenzek** [comment]
No plans to implement anything like this. The cheat system provides sufficient functionality.
