### ISSUE TITLE
Wrong window scale if using resume option in windowed mode, produces blurry image

### ISSUE THREAD

**Issue by DCxDemo** [stenzek/duckstation#2188]
**Game details**
Tested on Crash Team Racing, Crash Bash, but probably not realated to specific games, rather internal game resolution.

**Description of the issue / bug**
If internal resolution scale set to automatic based on window size, the image gets blurry in certain sizes. I assume it's calculated using closest width, but since PS1 games are heavily stretched most of the time (512x240), it makes sense to use either height or consider both for step calculation.

**Steps to reproduce**
* set resolution scale set to automatic based on window size
* go windowed mode
* slowly resize the window until scale integer jumps to the next step. you'll see a major quality boost.

**Hardware/software**
Windows. Any backend.

**Emulator version**
preview - 0.1-4119-g56c08254 (master)

**Additional context**
![poorscale](https://user-images.githubusercontent.com/13422696/120065994-f4c59800-c07c-11eb-9c68-b25747e1f20d.png)

**Comment by stenzek** [comment]
It's using height, and rounds up. Seems to work fine for me?

**Comment by DCxDemo** [comment]
are you using original vram buffer height or total vram height?
at about 700px height it drops down to 1024x432.
also if you keep stretching vertically, it keeps increasing the scale, despite actual screen buffer stays the same.
probably best to use both width and height then.

**Comment by stenzek** [comment]
I use height for consistency with screenshot sizing.

The VRAM size is not used, the display size is. Look for an OSD notification as you're resizing the window, it should match.

![image](https://user-images.githubusercontent.com/11288319/120067731-8dc9d280-c0c0-11eb-9586-9b3ba0d8dc05.png)
(image is 1442x1034)

**Comment by DCxDemo** [comment]
i see. it could be somehow related to resume state. i'll test that and check if i can figure out when exactly it happens. here you can see it's 432x after resume despite window being larger.

![12312411](https://user-images.githubusercontent.com/13422696/120067862-72da6c80-c086-11eb-8e73-0ce261621fa1.png)

```I use height for consistency with screenshot sizing.```
is it something internal? from the outside it looks like it just saves duckstation window buffer including the bars.
![123124123123121](https://user-images.githubusercontent.com/13422696/120067975-001dc100-c087-11eb-9047-2bd3145438e4.png)

**Comment by DCxDemo** [comment]
in lower resolution in returns to an even lower value
![123235235235](https://user-images.githubusercontent.com/13422696/120068559-f053ac00-c089-11eb-983a-14bf75490865.png)

**Comment by stenzek** [comment]
The resolution scale will still be an integer multiple. Fractional scaling does nothing but break games, this is true on almost all emulators.

**Comment by DCxDemo** [comment]
well it seems to be using incorrect integer step after you resume the game, if the resize event triggers, it fixes it up instantly back to correct value.

i am not aware of the ways you emulate/render, considering all the pgxp stuff, so i won't argue and it isn't related to this issue. but i don't see a problem in fractional scaling if you'd render to an additional scaled screen buffer, keeping the original vram scale for textures though.

**Comment by stenzek** [comment]
I'll check the resume case later.

Fractional scaling works fine for 3D, but breaks for 2D. e.g. your 31x31 rect is now 46.5x46.5 and not covering the rightmost/bottommost pixels.

**Comment by stenzek** [comment]
Resuming seems to set the correct scale fine here.

**Comment by DCxDemo** [comment]
It specifically happens with ```crop: all borders``` setting on vanilla install.
Consider adding requirement to upload settings file to your workflow if you can't reproduce it on local machine.

**Comment by stenzek** [comment]
All borders/resume fixed in https://github.com/stenzek/duckstation/commit/179a7aea8941c917db29ec7149f9aca4f076da1e
