### ISSUE TITLE
[Windows] Add groups to Cheats->Enable cheats menu

### ISSUE THREAD

**Issue by DCxDemo** [stenzek/duckstation#2189]
Games with many cheats included (i.e. Crash Team Racing) have them grouped in Cheat Manager, but they are all added as a single stack to Cheats -> Enabled cheats menu. Also figured out Apply cheats is empty. Not sure how this is supposed to function, but seems to be messed up a bit. Windows, Preview 0.1-4119-g56c08254 (master)

![poorscale](https://user-images.githubusercontent.com/13422696/120066181-052a4280-c07e-11eb-8bc3-daa252683273.png)

Expecting something like load state menu:
![state](https://user-images.githubusercontent.com/13422696/120066393-cb0d7080-c07e-11eb-961a-13c88f0aff77.png)

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/1b0b88f60be2bea3d2e28fbb25bcbf9a70bfafb3

**Comment by DCxDemo** [comment]
Much better, thanks.
