### ISSUE TITLE
Covert Ops - Nuclear Dawn (USA) (Disc 1) crashes during the opening cutscene

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#219]
![Capture](https://user-images.githubusercontent.com/31968468/78349246-0a613e00-75ef-11ea-9422-70148edc3270.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/78349255-0d5c2e80-75ef-11ea-8f98-ffdfb7d02ffc.PNG)

**Comment by stenzek** [comment]
Wow, something which uses the sound map? I haven't implemented this feature yet.

**Comment by stenzek** [comment]
Also should be fixed with https://github.com/stenzek/duckstation/commit/4e8da3cb417ad54d211327cfe0cde450bead45d4

**Comment by stenzek** [comment]
Doesn't seem to happen on the latest build.
