### ISSUE TITLE
Savestate QOL improvement suggestions

### ISSUE THREAD

**Issue by DfactorLongplays** [stenzek/duckstation#2192]
Hiya, I've been tinkering with DuckStation on Windows for a while and I've liked how both customizable, easy to use and modern it is.
After using PS1 emulation software for over a decade I've been always jumping between various emulators due to their limited feature set. So I figured I might as well suggest a few features that I feel like are missing in DuckStation.

**1. There's no way to completely disable OSD/GUI when switching savestates using "Select Previous/Next" hotkeys.**
It would be useful to have a toggle check mark option in "Display Settings" that completely hides the selection/preview window.

**2. It may sound like too much, but expanding the amount of available savestate slots to 100 would be a good idea in the long run.**
For game testing and content creation the convenience of saving at all key locations of a game is immeasurable. At first I thought that back in the day 10 was a lot, but after experiencing Beetle HW PSX with 100 slots... that was something else. 

**3. Change the behavior of "Select Previous/Next Slot" hotkey so that it instantly switches the slot without the need of pressing it twice.**
As of now tapping "Select Previous/Next Slot" doesn't actually change the savestate slot, but instead brings up savestate OSD and only after that another input will change the selected slot.
Sounds intentional, maybe have different hotkeys altogether that switch the slot instantly?

**4. Minimize stutter during gameplay while actively savestating,**
With the recent builds it's almost perfect but there's still noticeable stutter whenever the savestate is being written.

Thank you for making PS1 emulation exciting again!

**Comment by stenzek** [comment]
> 1. There's no way to completely disable OSD/GUI when switching savestates using "Select Previous/Next" hotkeys.

Not going to do that, more options just add confusion, so would not having any visual indicator of slot change.

> 2. It may sound like too much, but expanding the amount of available savestate slots to 100 would be a good idea in the long run.

Not going to do this, it's way too overwhelming in the UI. Maybe I'll add an option to browse for a load/save state path.

> 3. Change the behavior of "Select Previous/Next Slot" hotkey so that it instantly switches the slot without the need of pressing it twice.

I can change this.

> 4. Minimize stutter during gameplay while actively savestating,

It's instant for me. When you're using high resolution scales there will be a frame or two dropped when saving, because it has to downsample the framebuffer twice, once for the save data, another for the screenshot.

**Comment by stenzek** [comment]
Loading/saving from file added in https://github.com/stenzek/duckstation/commit/296a662e740ddf965f77ba76c984a5dbc18e95d0

Selector UI keypress behavior changed in https://github.com/stenzek/duckstation/commit/d64bc193fd72f1e0c2b03108e1e41f9a54b79020
