### ISSUE TITLE
Casper (USA): Garden BGM randomly resets

### ISSUE THREAD

**Issue by waspennator** [stenzek/duckstation#2194]
**Game details**
SLUS-00162 Casper (USA)
Redump Verified

**Description of the issue / bug**
For whatever reason, whenever you enter the garden area, the BGM plays for a bit before briefly resetting back to the beginning, right before hopping back to the correct spot, tested it out on console and this does not happen.

**Steps to reproduce**
Boot the game up with the save file supplied, click play and continue with the first save game called game 1 (It should put you right below a door into the garden), go through the door, raise your volume up if you have to and listen to the BGM, it should weirdly restart back at the beginning for a bit before jumping back to the correct spot again.

Pause the game and unpause to reset the BGM and hear the audio bug if you missed it the first time.

**Hardware/software**
i5 6600k
Geforce GTX 1070
Windows 10
Vulkan 

**Emulator version**
0.1-4125 Preview Build

**Additional Context**

[Casper Garden BGM Glitch Save.zip](https://github.com/stenzek/duckstation/files/6566039/Casper.Garden.BGM.Glitch.Save.zip)

**Comment by stenzek** [comment]
Seems to be related to seek timing - speeding it up fixes it. Another one which should be fixed once I finish that seek timing model...

**Comment by stenzek** [comment]
Fixed with https://github.com/stenzek/duckstation/commit/74013a0853a8fade147cf3995973351bae4b86d5

**Comment by waspennator** [comment]
While I can confirm now that the audio no longer randomly resets before looping back to the correct spot,

However I did notice something new now, if you start up a new game, go all the way to the left, up the door, past the fat ghost that tries to chasing you and into the kitchen at the top, then listen to the music. The music plays, but still sounds a little, off, raise your volume up and you should hear it act weird a little.


https://user-images.githubusercontent.com/78768499/121791869-e793c780-cbab-11eb-85ea-9f4bf0886891.mp4

**Comment by stenzek** [comment]
It seems it's just **really** sensitive to seek timings, and the buffer underflows really easily. Need to finish coming up with a model of the actual mechacon/DSP behavior (my last attempt makes things worse, not better), but the latest push fixes it in these two places at least.
