### ISSUE TITLE
[Android] Touch Screen Combo Key Like PPSSPP

### ISSUE THREAD

**Issue by Githubot1957** [stenzek/duckstation#2195]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Is your feature request related to a problem? Please describe.**
The touch button of duckstation has no combo key on android like ppsspp.
**Describe the solution you'd like**
https://github.com/hrydgard/ppsspp/pull/8096
**Describe alternatives you've considered**
Please consider adding this to the future update ty :)
**Additional context**
Keep up the good work duckstation is the best ps1 emulator on android.

**Comment by stenzek** [comment]
No interest in adding this, sorry. Touch gliding already provides similar functionality, and doesn't crowd the screen with more buttons.

**Comment by Githubot1957** [comment]
@stenzek How to combine multiple buttons using gliding? :)

**Comment by Githubot1957** [comment]
Touch gliding not support 3 or more buttons only two buttons can touch at the same time :(
Sorry I will give 1 star on playstore :)

**Comment by stenzek** [comment]
Attitudes like this is exactly why I am now only implementing features I am personally interested in.

You paid nothing for the app, you are not a customer, you have no right to dictate where development goes.

Honestly, why do I even bother? I sacrifice most of my free time for this software, and get absolutely nothing out of it, people only attack it. If it's that awful, go pay for epsxe or whatever.

**Comment by stenzek** [comment]
Wow, you're the same guy I previously blocked.

Pro tip, bullying people does not get them to do what you want.

**Comment by Githubot1957** [comment]
S O R R Y 🙏🥺
