### ISSUE TITLE
Add option to force scoped storage on Android <11

### ISSUE THREAD

**Issue by th0rig** [stenzek/duckstation#2196]
Device and Os
Sharp SHV41 android 10 upgraded from pie android 9
**Emulator version**
v0.1-4046

The emu unable to scan games from external storage in this case Microsd and all my games are in pbp format(not psp encrypted format) to save storage space actually I hate how google mess storage implementation like this for obb files fine but unable to read and write for other stuff like emulator photos and video editing export files and etc are anoying and if the reason is privacy why not apply scoped Storage for sd card without limiting ability to read and write to sdcard I feel capitalist aura behind it if you ask me to force people to buy expensive phones for bigger storage space
Here the screenshot
![Screenshot_20210530-205929](https://user-images.githubusercontent.com/52917124/120107225-68090000-c18a-11eb-9ae4-c6a0323a8de8.png)
![Screenshot_20210530-205913](https://user-images.githubusercontent.com/52917124/120107231-6e977780-c18a-11eb-9f2e-ecbc0511a6bd.png)

**Comment by stenzek** [comment]
Scoped storage should work here, but I disabled it on anything older than android 11 because apparently a bunch of phones screwed up the implementation.

What we'll probably need is an option to force scoped storage on older devices.

**Comment by stenzek** [comment]
Added an option to force scoped storage in the overflow menu in https://github.com/stenzek/duckstation/commit/4f51310e835ef4ee21bd64df6d6df58456737b78 (should be built in about 15mins or so). Re-adding your SD card should get listed as a `content://` path. Hopefully this will help.

**Comment by th0rig** [comment]
Thanks for your hard work I'll try the new version
