### ISSUE TITLE
[Libretro] Light gun issues: missing crosshair / missing "X Scale" option / crashing on close content with Vulkan

### ISSUE THREAD

**Issue by bslenul** [stenzek/duckstation#2197]
**Game details**
SLUS-00405 Time Crisis (USA), haven't tried any other light gun games yet.

**edit:** Tested Point Blank 1 and 3 (USA) as well, same issues.

**Description of the issue / bug**
Hey! Just read you've added Light Gun support to the Libretro core, thank you for that! I messed a bit with Time Crisis and I've noticed a few things however:

* ~~Unlike standalone, it seems to only work with software renderer atm, with OpenGL/D3D11/Vulkan you can't get pass the calibration screen, the screen flashes white every time you press the trigger but it's like you're shooting off-screen, so you're just stuck on that screen 😅 It works perfectly fine in software mode however.~~
**edit:** looks like it was a setting conflict or something, it works in HW after resetting my core options, sorry!
* There's no crosshair, which makes it near impossible to play with a mouse since you never really know where your cursor is.
* It's missing the "X Scale" option for the GunCon, so the crosshair is misaligned near the borders of the screen (see #1223).
* For some reason RetroArch will crash on close content if you're using Vulkan renderer and have device type set to "GunCon".

**Steps to reproduce**
* Boot Time Crisis with RetroArch and switch device type to GunCon (make sure to bind at least a gun trigger button in `Settings > Input > Port 1 Controls`).
* With HW renderer, try to pass the calibration screen.
* Switch to SW renderer and restart core, should be working now!
* Notice that the ingame crosshair during the calibration screen is misaligned when moving to the borders.
* And notice that the internal DuckStation crosshair is missing :(

**Hardware/software**
Windows 10 / i5-4670K / GTX 970

**Emulator version**
RetroArch 1.9.4 / DuckStation preview-9-gf3bfe2f8

**Comment by bslenul** [comment]
Also, looks like having GunCon as device type causes RA to crash on close content 🤔 

Crash log: https://pastebin.com/1i7md4p6
Verbose log: https://pastebin.com/DD8572X6

**Comment by stenzek** [comment]
Hmm, strange, I swear I tested it with the hardware renderers.. will look into it when I get a chance.

**Comment by stenzek** [comment]
The lack of crosshair is actually a larger issue with libretro cores and lightguns. I believe others render their own crosshair into the framebuffer before they hand it off. This has several problems:

1. The crosshair is limited to the resolution that the core is rendering at.
2. The framebuffer does not have the aspect ratio applied. The net result is squished or stretched crosshairs when it is AR corrected by the frontend.

I'm going to put together a proposal to have the frontend render the crosshair instead. I think this is a much better long term solution, and can benefit other cores as well.

**Comment by bslenul** [comment]
> Hmm, strange, I swear I tested it with the hardware renderers.. will look into it when I get a chance.

It might be another option causing this, I resetted my core options to default and now it works, sorry about that!

**Comment by bslenul** [comment]
For the crash I've mentioned in my 2nd post, it seems to only happen with Vulkan + GunCon for some reason, no crash with Vulkan + Digital/Analog Controller and Joystick/Mouse, no crash with OpenGL or D3D11 + any of the device types.

**Comment by n1ghttrap** [comment]
For this and other cores with a missing cursor/crosshair there is a hotkey to unhide the mouse cursor.  It is F11 by default.

**Comment by bslenul** [comment]
Yeah but it's not ideal because the cursor is hidden by default in fullscreen (and I don't believe there's a setting to disable that), and if you don't have a keyboard it means you have to bind the "Mouse Grab" hotkey to the mouse itself or to a controller. This might seem like a simple fix but it means:
* If you bind it to mouse, you'll basically lose 1 button that could have been useful ingame (especially if you only have a 3 buttons mouse).
* If you bind it to controller, you'll have to plug/pair the controller just for that.
* If you bind it to controller, you'll basically lose 1 button globally (because RA doesn't handle overrides + hotkeys well at all, unless you edit the .cfg manually... -_-).

And that's nitpicking but I don't feel like a mouse cursor has the same "charm" as a crosshair :D 

Also @stenzek I've noticed the Vulkan + GunCon doesn't only crash on close content, but any time the video is "reinitialized", like switching from fullscreen to window, changing the internal resolution, etc.
Here's another crash log (triggered by going from window to fullscreen): https://pastebin.com/aH7d6tXi

**Comment by n1ghttrap** [comment]
> Yeah but it's not ideal because the cursor is hidden by default in fullscreen (and I don't believe there's a setting to disable that), and if you don't have a keyboard it means you have to bind the "Mouse Grab" hotkey to the mouse itself or to a controller. This might seem like a simple fix but it means:
> 
> * If you bind it to mouse, you'll basically lose 1 button that could have been useful ingame (especially if you only have a 3 buttons mouse).
> * If you bind it to controller, you'll have to plug/pair the controller just for that.
> * If you bind it to controller, you'll basically lose 1 button globally (because RA doesn't handle overrides + hotkeys well at all, unless you edit the .cfg manually... -_-).
> 
> And that's nitpicking but I don't feel like a mouse cursor has the same "charm" as a crosshair :D
> 
> Also @stenzek I've noticed the Vulkan + GunCon doesn't only crash on close content, but any time the video is "reinitialized", like switching from fullscreen to window, changing the internal resolution, etc.
> Here's another crash log (triggered by going from window to fullscreen): https://pastebin.com/aH7d6tXi

Fair enough, just thought I'd mention the work-around in case you wanted it.

**Comment by stenzek** [comment]
X scale added, and close context crash fixed in latest builds.

As I mentioned above, crosshair rendering should be the responsibility of the frontend.

**Comment by bslenul** [comment]
Awesome, thank you! :D
