### ISSUE TITLE
Loading screen gets stuck in NHL FaceOff 2001 (USA) [SCUS-94577]

### ISSUE THREAD

**Issue by MadClown** [stenzek/duckstation#2205]
**Game details**
SCUS-94577 NHL FaceOff 2001 (USA)
Verified with redump.

**Description of the issue / bug**
Can't start the hockey match because the progress bar stops loading 2/3 of the way.

**Steps to reproduce**
Start the game by selecting "quick start" when at the main menu.

**Enhancements information**
No enhancements enabled

**Hardware/software**
Tested with the following and it happened on both.
Intel i7-7700HQ, Nvidia 1050ti, Windows 10
Intel i5-3210M, Intel HD 4000, Windows 10
[GPU Renderer - D3D11/Software]

**Emulator version**
0.1-4071-g64e0d83d (dev)
0.1-4126-g179a7aea (master)

![SCUS-94577_2021-06-01_13-49-51](https://user-images.githubusercontent.com/2918532/120389122-d95ac700-c2e0-11eb-9064-87f2d03723a2.png)

**Comment by foxsevent** [comment]
Are you sure about that redump verified? Cause it works fine here.

**Comment by MadClown** [comment]
Well, regarding the dump, it matches the only dump on redump but it's not actually verified. Maybe it's a bad dump after all.

**Comment by stenzek** [comment]
Should be fixed in https://github.com/stenzek/duckstation/commit/3a831c543dd27e29021d1e360480c819ff295c1c  (preview build)
