### ISSUE TITLE
[libretro] - Segmentation fault on Linux when using Vulkan API

### ISSUE THREAD

**Issue by aqxa1** [stenzek/duckstation#2208]
**Game details**
All games affected.

**Description of the issue / bug**
Segmentation fault when loading libretro core when using the Vulkan renderer, I.e. when the core is loading a game and setting up the GPU. Here's the GDB output:
    `Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007fffaf56f6a6 in RetroCreateVulkanDevice(retro_vulkan_context*, VkInstance_T*, VkPhysicalDevice_T*, VkSurfaceKHR_T*, void (*(*)(VkInstance_T*, char const*))(), char const**, unsigned int, char const**, unsigned int, VkPhysicalDeviceFeatures const*) ()`

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open? No.
2. Which controller backend are you using in general settings N/A

**Steps to reproduce**

1. Load Retroarch
2. Load content
3. Select game and load game with Duckstation core

**Hardware/software**
Ryzen 5900x, RX 6800, Gentoo Linux
GPU Renderer = Vulkan
RADV and AMDVLK vulkan drivers tested, both exhibiting the issue.

**Emulator version**
Latest from libretro build bot, and also the version included on [duckstation.org](https://www.duckstation.org/libretro/duckstation_libretro_linux_x64.zip). I'd compile it myself, but I'm not sure how, or which branch/repo to use.

**Additional context**
This is on a Wayland system (Sway) but the X11 version of Retroarch (through XWayland) also has the issue.

**Comment by stenzek** [comment]
Potential fix has been pushed, it's available at https://www.duckstation.org/libretro/duckstation_libretro_windows_x64.zip (the core updater should pull it eventually, but not sure what schedule it runs on).

**Comment by aqxa1** [comment]
Thanks, looks all good on my end.

**Comment by stenzek** [comment]
Great, thanks for checking!
