### ISSUE TITLE
D3D11 fast forward does not work on the duckstation libretro core

### ISSUE THREAD

**Issue by Cibomatto2002** [stenzek/duckstation#2209]
D3D11 fast forward does not work on the duckstation libretro core.

Windows 10

**Comment by stenzek** [comment]
It works fine for me. Make sure you're not forcing vsync in your graphics driver. Regardless, this is a frontend issue, the core does not control vsync.

You also deleted the issue template. The bug tracker is not for support requests.

**Comment by Cibomatto2002** [comment]
sorry about that i have another problem the vulkan driver shows only a black screen.

here is the computer I have https://www.amazon.com/Celeron-Processor-Windows-Computer-Ethernet/dp/B08GFPT9CL/ref=pd_rhf_se_p_img_1?_encoding=UTF8&psc=1&refRID=9B120K8F8Q6P7PX9D64W

**Comment by stenzek** [comment]
Do other vulkan cores work? Again, I doubt this is a core issue, I only tested vulkan earlier today and it was also fine.

**Comment by Cibomatto2002** [comment]
Thanks for your time I only mentioned these to broblems  because you can change the GPU inside duckstation so I thought it was a duckstation problem for me I had I got the d3d11
 fast forward working. When I get home from work tonight I will change retroarch to the vulkan driver and see if it works or not

**Comment by Cibomatto2002** [comment]
I got it working all I did was quit retroarch ands restart it now vulkan works.
