### ISSUE TITLE
Part of the title screen is missing in HBO Boxing (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#221]
As you can see part of it is cut off. Happens with all renderers and all crop modes.

![Capture](https://user-images.githubusercontent.com/31968468/78414079-2522c980-7666-11ea-9aa9-1f33331e2ca7.PNG)

The in game graphics are also broken.

![SLUS-01027_2020-04-04_11-11-01](https://user-images.githubusercontent.com/31968468/78414096-3ff53e00-7666-11ea-9353-99d5a43a4b1b.png)

Beetle PSX for comparison.

![HBO Boxing (USA)-200404-111424](https://user-images.githubusercontent.com/31968468/78414113-54d1d180-7666-11ea-9a51-e8a15bae7a10.png)

![HBO Boxing (USA)-200404-111532](https://user-images.githubusercontent.com/31968468/78414118-5c917600-7666-11ea-974e-7af0fae4552c.png)

**Comment by stenzek** [comment]
This is probably a regression from https://github.com/stenzek/duckstation/commit/5302f8381807c3736a9d439bd6727404ba8dbd59 Could you please try it on this build: https://ci.appveyor.com/project/stenzek/duckstation/builds/31909739/job/wtp8212lq0r3uus7/artifacts

**Comment by kurayami6** [comment]
Yeah neither of the issues are present in that build.

**Comment by stenzek** [comment]
Great, thanks. Will revert the FF8 change for now and investigate it more later.
