### ISSUE TITLE
[Libretro] Seg Fault on linux armv8, GLES 3.1 (rpi4) - works via gdb or with fastmem disabled

### ISSUE THREAD

**Issue by dankcushions** [stenzek/duckstation#2211]
**Game details**
SLUS-00402 Tekken 3 (USA)
(pbp but tried bin/cue also)

**Description of the issue / bug**
Seg fault when launching core. Seems to affect all games.
bt:
```[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0xb0485f30 (LWP 18825)]
[New Thread 0xab137f30 (LWP 18826)]
[New Thread 0xaa135f30 (LWP 18827)]
[Thread 0xab137f30 (LWP 18826) exited]

Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0xacbf64c4 in CPU::CodeCache::s_code_storage () from /opt/retropie/libretrocores/lr-duckstation/duckstation_libretro.so
(gdb) bt
#0  0xacbf64c4 in CPU::CodeCache::s_code_storage () at /opt/retropie/libretrocores/lr-duckstation/duckstation_libretro.so
```
i get it to continue from this with `handle SIGSEGV nostop noprint` as per https://github.com/stenzek/duckstation/issues/861#issuecomment-716259649, but weirdly then it seems to boot fine!

[verbose log of seg fault run normally](https://github.com/stenzek/duckstation/files/6588126/runcommand.log)
[diff of the above vs working under gdb](https://www.diffchecker.com/YdOXhPQC)

It also works if I disable fastmem, but I'm not sure if the crash is expected with it enabled since it's on by default for my hardware (armv8 in 32-bit mode). If it's expected I can adjust the retropie install script to disable it for this configuration, but you may want to force this within the code.

**Steps to reproduce**
Launch with fastmem set to LUT (ie, the default), crash...

**Enhancements information**
(settings at default - not been able to boot in to change yet)

**Hardware/software**
[INFO] [GL]: Vendor: Broadcom, Renderer: V3D 4.2.
[INFO] [GL]: Version: OpenGL ES 3.1 Mesa 19.3.2.
(unable to use Vulkan in this version of Mesa - RPI OS hasn't upgraded beyond this as yet)
armv8 (32-bit mode)
Raspberry Pi 4 plus Raspberry Pi OS 5.10.11-v7l+

**Emulator version**
https://www.duckstation.org/libretro/duckstation_libretro_linux_armv7.zip
RetroArch 1.9.4 (Git c226bd8)

**Comment by stenzek** [comment]
This is normal? That's the whole point of fastmem, it uses segfaults to backpatch code to call to C++ instead.

Don't run it under a debugger and it'll work fine. Or disable fastmem/set it to nostop if you must use a debugger.

**Comment by stenzek** [comment]
Tested on my pi4 (raspbian 10, 5.10.11-v7l+ apparently) with the build from duckstation.org, no issues with fastmem on.

If your script is hooking the signal handlers and preventing the application from responding to them, then that might be the problem. I can't support such ridiculous setups.

**Comment by stenzek** [comment]
For the record, you **really** don't want to disable fastmem. It can be anywhere from 20% to 50% of a performance hit in some games. Find a proper solution, distributions repacking the core and disabling options like this just gives users a non-optimal experience.

**Comment by dankcushions** [comment]
yep, you're right! worked fine when launching via the command line, so clearly not anything to do with duckstation. for reference, to do it via this particular bash launcher script i had to pipe stdin to /dev/null. ie  `[launch command here] </dev/null [params]`.

Hopefully in retropie soon :)
