### ISSUE TITLE
Cheevos tracked game info be shown in OSD or Big Duck Mode.

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#2218]
**Is your feature request related to a problem? Please describe.**
Not related to a problem but would be a nice convenience if not much trouble to ask.

**Describe the solution you'd like**
Basically this 
![Przechwytywanie](https://user-images.githubusercontent.com/64225743/120879513-25995600-c5c4-11eb-85ac-9cc5a8f80c6d.PNG)
If we could access it without having to go to cheevos settings either on OSD or Big Duck mode Achievement section or below game name on the bottom right.
As in some games it shows useful data that can't be tracked any other way other than manually keeping track.  

Cheers.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/531845a0c7771212f4e6ab621e34210b7888aa9b
