### ISSUE TITLE
resume bugs after using PPF patches 

### ISSUE THREAD

**Issue by zkdpower** [stenzek/duckstation#2222]
when i Power off(ESC Key to Pause) a game with ppf patches(PPF function Actived and Game process all OK), and then i Click the "resume",the fault tip will popup --- "failed to open CD image ****.ppf" used by save state. system failed to boot, the log may contain more information.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/e118b5486e6f5e344580ae4c551697b373d2545f (you will need to re-save).
