### ISSUE TITLE
Exclude files listed inside m3u from the game list

### ISSUE THREAD

**Issue by xeropresence** [stenzek/duckstation#2223]
**Is your feature request related to a problem? Please describe.**
Using m3u's makes it easy to have one entry for multi-disc games, but at the cost of having an extra entry and keeping the original discs as well.

**Describe the solution you'd like**
Exclude files listed inside m3u from the game list

**Describe alternatives you've considered**
I read there is PBP support but the compression is not as good as CHD, so using that is possibly an alternative

**Additional context**
https://i.imgur.com/5GUPJZ3.png

Would also be nice if it would grab the cover-art for either the first disc or the last selected disc and used that automatically

**Comment by stenzek** [comment]
Similar functionality as https://github.com/stenzek/duckstation/issues/1077

As a workaround, you can place the chds in a subdirectory, put the m3u in the parent directory, and disable recursive scanning. So the m3u would contain
```
subdir/disc1.cue
subdir/disc2.cue
```
and so on.

**Comment by foxsevent** [comment]
> Similar functionality as #1077
> 
> As a workaround, you can place the chds in a subdirectory, put the m3u in the parent directory, and disable recursive scanning. So the m3u would contain
> 
> ```
> subdir/disc1.cue
> subdir/disc2.cue
> ```
> 
> and so on.

Huh neat didn't know about this, thanks it definitely helps and sorry if it was written somewhere in FAQ or something and I missed it.

Cheers
