### ISSUE TITLE
Save files invalidated?

### ISSUE THREAD

**Issue by Defreezer** [stenzek/duckstation#2226]
**Game details**
General issue affecting every game.
First discovered in Rage Racer (SLUS-00403).

**Description of the issue / bug**
Hello. I've met a strange problem with Duckstation that I've yet to find a solution to. Prior to discovering Duckstation's "portable.txt" functionality, I've attempted to move its folder from where it was originally placed (ex. D:\Duckstation), to a subfolder within the same partition, in the same drive (ex. D:\Subfolder 1\Subfolder 2\Duckstation) and made the appropriate adjustments to its BIOS settings so it would be aware of their new location. The folders in which the memory cars are located (C:\Users\[username]\Documents\DuckStation\memcards) seemed to be of no issue as that folder was not moved whatsoever.

However, upon booting Duckstation from its new location, even with the appropriate location for the shared memory cards (ex. C:\Users\[username]\Documents\Duckstation\memcards\shared_card_1.mcd), the emulator no longer seems to be able to (or at least refuses to) read them. When the "save/load game" screen is entered in any game I already had .mcd save files for, the following message is reported:

"Memory card at C:\Users\[username]\Documents\Duckstation\memcards\[GAME SERIAL]_1.mcd could not be read, formatting."

After which nothing else happens. The games themselves likewise report that there are no existent save files to be loaded, and generally prompt the creation of new ones. I have not made any changes in the emulator or its dependencies whatsoever, besides moving the emulator's folder and changing the required path settings that refer to the emulator's location rather than the memcards folder. I admit it was a user's mistake, but reversing the steps did not solved the problem. Making the emulator's folder portable by adding the portable.txt file, transferring the memcards folder to the emulator's root folder and changing the paths in the memory card options has not solved it, either.

**Steps to reproduce**
Moving the Duckstation folder (not in portable mode) to another location while having existent saved games in the Documents\Duckstation\memcards folder, then attempting to load a saved game. Options set: Separate Card Per Game Title, Single Card for Sub-Images checked.

**Enhancements information**
I have investigated this with enhancements disabled, but it made no difference.

**Hardware/software**
Intel i7 6700k
Radeon RX 570
Windows 7 SP1 64bit (I'm aware that it's unsupported)
Vulkan renderer.

**Emulator version**
0.1-3862-g8f821c77

**Comment by foxsevent** [comment]
Not really a issue with the game you just messed up your memory card configuration when switch to portable mode.
Use the memory card tool to check on which memory card your save file is and in memory card settings point to it and/or move the file or copy the save to the new memory card.

**Comment by Defreezer** [comment]
The problem appeared before I switched to portable mode, when I simply moved the folder. I have set the options to "Separate Card Per Game Title" and "Single Card for Sub-Images". Displacing the .mcd files, creating new ones and replacing the saves in the new .mcd files with those from shared_save.mcd seems to have mostly resolved the problem, though I do wonder why it fails to detect them. Is there a way to restore all the .mcd files automatically?

**Comment by foxsevent** [comment]
Automatically no, you just gotta move the saves files or the memory cards, it may not detect them simply due to name mismatch.
This did happen to me recently where untill recently my Tomb Raider 1 memory cards were named Tomb Raider 1 (rev 3) USA 1.mcd  now it's just Tomb Raider 1 USA.mcd

**Comment by Defreezer** [comment]
The filenames of the .mcd's were never changed, only the path of the emulator. I was thinking more of detecting the saves within them (.mcs) automatically.

**Comment by foxsevent** [comment]
> The filenames of the .mcd's were never changed, only the path of the emulator. I was thinking more of detecting the saves within them (.mcs) automatically.

No, the only way that can happen is if you suddenly started playing a different version of the same game, USA saves aren't compatible with EU/UK game and vice versa.

"Memory card at C:\Users[username]\Documents\Duckstation\memcards[GAME SERIAL]_1.mcd could not be read, formatting.

This means exactly that it couldn't find the memory card so it created a new one, so either the name of the card was wrong or the path was.

**Comment by Defreezer** [comment]
That's strange. I did check the path after changing folders. Transferring them manually works well enough, though it will take some time.

**Comment by stenzek** [comment]
This sounds like a configuration issue. I couldn't reproduce it with the instructions you gave (two exe directories, one shared user/data directory in documents).
