### ISSUE TITLE
all these demos show nothing but a black screen

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#223]
https://psx.amidog.se/doku.php?id=psx:download:misc

**Comment by stenzek** [comment]
Sorry, this is one that at this point in time I have no plans to fix.

Most of those demos abuse internal behavior of the GPU, which no game that I'm aware of does, and requires extremely high simulation accuracy. Such accuracy would also prevent the use of a hardware renderer. As the goal of DuckStation is for a "reasonable" level of accuracy (running as many games as possible without hacks) while focusing on speed, having these demos run would not align with that goal as it would slow things down.

That might change in the future, but for now they will stay broken. Except for the infinite DMA chain one, that'll probably work once I implement GPU timings.

**Comment by benderscruffy** [comment]
ok fair enough
