### ISSUE TITLE
Rumble

### ISSUE THREAD

**Issue by TommvinHuwaltzky** [stenzek/duckstation#2236]
Since update `0.1-4126-g179a7aea (dev)` it seems that only the little rumble-motor is being used. Playing Final Fantasy VIII with a DualShock 4 (via DS4Windows), and even when bumping vibration up to 50 in Controller-Settings, only a little can be felt.
Was still functioning as intended on the previous version.

**Comment by stenzek** [comment]
You didn't fill out the issue template.

**Comment by TommvinHuwaltzky** [comment]
sorry, how do I do that? feeling like an idiot rn... :P
