### ISSUE TITLE
Freezes when state-load a slot with different settings for controller port 2 in Japanese

### ISSUE THREAD

**Issue by KONA-cheese** [stenzek/duckstation#2239]
Hello. I'm sorry for my bad English.

**Game details**
- SLPS-01100 Tales of Destiny(jpn)
- SLPS-01244 Choro Q 3(jpn)
- SLPS-01230 Parasite Eve (jpn)

**Description of the issue / bug**

With the language setting set to "Japanese", set controller port 2 to "Digital Controller".
next, do the state-save, set controller port 2 to "None".
next, the game freeze when load the saved slot.

In the same way, if state-save in the "None" state, set "Digital Controller", and then load saved slot, it too freezes.

Did not freeze if the language is English.

All games I own have freezes.

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
No.

2. Which controller backend are you using in general settings
SDL

**Steps to reproduce**
1. Set the language setting to "Japanese".
2. Reboot application.
3. Set controller port 2 to "Digital Controller".
4. Start any disc.
5. Do state-save.
6. Set controller port 2 to "None".
7. Do state-load.
8. Freeze.

**Hardware/software**

- desktop PC
- OS - windows10
- cpu - AMD Ryzen 5 2600 Six-Core Processor 3.40 GHz
- graphics card - NVIDIA GeForce GTX 1060 3GB
- GPU Renderer - D3D11

**Emulator version**

0.1-4126-g179a7aea

**Comment by stenzek** [comment]
Seems to be an issue with the translation - the order of operands to the format string can't be swapped for OSD messages. I've removed the problematic line for now (https://github.com/stenzek/duckstation/commit/22d1e6cf020d9645034df403137dfe33de5ace01).

**Comment by KONA-cheese** [comment]
Thank you for your help.

**Comment by KONA-cheese** [comment]
I have checked it in version 0.1-4202-gda9c4c11. Thank you.
