### ISSUE TITLE
Minor issue with the pause button

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#224]
If you pause a game, power off with it still paused and then start a different game the pause button will still appear pressed even though the game is playing. 

![Capture](https://user-images.githubusercontent.com/31968468/78463799-8c9f4e80-7724-11ea-98f2-acc7c74097fe.PNG)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/e24e4c20e146a5697e56a86f9b89f336612bd410
