### ISSUE TITLE
Fun! Fun! Pingu - Youkoso! Nankyoku e (Japan): FPS counter displays 0 during almost all of game

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#2244]
**Game details**
[Serial Code, Region]
SLPS-02306 Fun! Fun! Pingu - Youkoso! Nankyoku e (Japan)

**Description of the issue / bug**
When playing, the FPS counter displays 0 at all times, save for the initial BIOS boot, the logo FMV, and load screens.

**Steps to reproduce**
Play the game as normal.

**Enhancements information**
I have turned off all enhancements.

**Hardware/software**
Intel i7-4600u@2.1ghz, Intel HD 4400, Linux Mint 20.
Occurs on Software, OpenGL, and Vulkan.

**Emulator version**
0.1-4046-g96330e55

**Comment by stenzek** [comment]
If the game is still working, this isn't a bug. The fps counter is based on a heuristic which isn't necessarily correct in 480i mode.

**Comment by HeroponRikiBestest** [comment]
Understandable, sorry to bother you.
