### ISSUE TITLE
RetroArch analog toggle with key combo

### ISSUE THREAD

**Issue by deivkiau** [stenzek/duckstation#2248]
**Request**
Add option to toggle analog with key combo in RetroArch.

**Details**
If using X360/XONE/DualShock4/DualSense etc... controller you can't toogle an analog, there is no key left on controller to bind as analog button. Even more RetroArch itself do not have option in controls "analog toggle" button.

**Example**
Mednafen implementation: hold L1+L2+R1+R2+START+SELECT for couple of seconds.

**Comment by stenzek** [comment]
I don't really like this idea. Such a button combination is valid for a game and would conflict.

DuckStation has a built in list of games which are incompatible with dualshock, so you can safely turn on auto analog, and it will be disabled when necessary. If there's any missing games from that list, we can easily add them.

**Comment by deivkiau** [comment]
I dont like it too, what mednafen done. But my suggestion would be like double click of SELECT button if it possible ?

**Comment by stenzek** [comment]
Again, that would conflict with an actual game input.

Why do you need the analog toggle in the first place? The automatic enable will work fine.

**Comment by deivkiau** [comment]
Force analog mode works only at start/reset and if I make changes to control in game (choose digital from analog and vise versa) you can't toggle analog back, your only option is to restart.

**Comment by stenzek** [comment]
What game? I'm still not seeing a use case here.

**Comment by deivkiau** [comment]
In any game, let's say DRIVER 2 (USA) (REV 1.1). Start game with "Force Analog" disabled with DualShock selected and in-game you can't re-enable analog without reseting the game.

**Comment by stenzek** [comment]
Why would you start the game with it disabled? The whole point is to turn the option on globally and leave it enabled.

Setting the controller type to none (and unpausing), and then back to dualshock should also reset it.

**Comment by deivkiau** [comment]
I like vibration of DualShock, but not analog so much. Usually playing with D-PAD, but some times with Analog (switching in-game). I try change controller type from DualShock - GamePad - DualShock and yes, it's reset itself. But my point was, to make easier way in RetroArch to toggle analog ON or OFF.

**Comment by stenzek** [comment]
Then I think a better way would be for the frontend to provide a way for cores to expose commands/options, such as toggling the state (e.g. what I have in the quick menu on Android).

I'm not going to add a "secret" combination which potentially conflicts with games. Not when there's already a way to effectively toggle it (by changing the controller type in the frontend).

**Comment by deivkiau** [comment]
Actually I agree with you, mednafen combo always messing up game with such combo.
