### ISSUE TITLE
Swagman (USA) hangs when you choose a save slot

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#225]
![SLUS-00151_2020-04-05_11-59-51](https://user-images.githubusercontent.com/31968468/78465191-a39a6c80-7735-11ea-8053-221d7a8b5179.png)

**Comment by stenzek** [comment]
I wonder if this is related to the startup delays in Racinggroovy due to memory cards...

**Comment by stenzek** [comment]
Not able to reproduce.

**Comment by kurayami6** [comment]
Yeah it works now. Just out of curiosity before I close this, what did you do that fixed it?

**Comment by stenzek** [comment]
Not sure. You could try the older builds to narrow it down.
