### ISSUE TITLE
[Feature Request] Leaderboards?

### ISSUE THREAD

**Issue by ozgurkazancci** [stenzek/duckstation#2250]
First of all, many thanks for such a great emulator! 
Really stable, solid and fast!

I'd kindly request "Leaderboards" support through RetroAchievements. Do you have any such plan?

Thank you.

**Comment by stenzek** [comment]
Not something I'm interested in implementing due to the low number of PS1 games which have leaderboards. But if anyone else wants to do it, go for it.
