### ISSUE TITLE
Dolphin's Dream (Japan) - Music sometimes messed up during dive

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#2254]
**Game details**
SLPM-86122, Dolphin's Dream (Japan)

**Description of the issue / bug**
Sometimes, upon entering a dive, the music will be messed up and sound incorrect, like so:
https://user-images.githubusercontent.com/50224630/121621380-e8e4b900-ca20-11eb-9e64-4f1ee2423543.mp4
Normally, it sounds like this: 
https://user-images.githubusercontent.com/50224630/121621394-eda96d00-ca20-11eb-8947-fc08c5ba9f71.mp4

**Steps to reproduce**
Mash circle through the menus to begin the dive, and then swim back up towards the surface to end it. Repeat this until you can hear messed up audio during your dive.

**Enhancements information**
I checked "disable all enhancements" in advanced options while testing and recording this issue.

**Hardware/software**
Intel i7-4600u@2.1ghz, Intel HD 4400, Linux Mint 20.
Occurs on Software, OpenGL, and Vulkan.

**Emulator version**
0.1-4208-g44da1335

**Additional context**
I also tried to reproduce this bug on the European version of the game, Diver's Dream, and was unable to. If anyone experiences this bug while playing that version of this game, please reply to this issue with confirmation and steps to recreate it there.

**Comment by stenzek** [comment]
Seems to use the same style of music streaming as Casper. See if the latest preview build changes anything, since I've tweaked the CD seek emulation there.

**Comment by stenzek** [comment]
As far as I can tell this is fixed with the seek timing improvements.

**Comment by HeroponRikiBestest** [comment]
Yep, appears to be fixed as of the latest builds. Thank you!
