### ISSUE TITLE
Chrono Cross has weird glitches not present on Console

### ISSUE THREAD

**Issue by Xaymar** [stenzek/duckstation#2255]
**Game details**  
SLUS-01041 Chrono Cross (USA)

**Description of the issue /  bug**  
Over time, some glitches appear in Chrono Cross not present on console:

1. Visible text corruption during Combat, getting increasingly worse the longer you play. This happens almost immediately, with less than ~10 minutes of play time. Similar issue reported in #1501
2. Sometimes the inventory loses the ability to add or remove items, making stores and combat useless for getting items. Observed thrice in 10 tests.

**Steps to reproduce**  
I failed to get any useful reproduction steps other than just running the game and playing it, as nothing else seems to be critical in triggering these issues. No cheats are active, all enhancements are off, and BIOS used is SCPH-5501/5503/7003.

**Enhancements information**
Disable All Enhancements checked for reproducible case

**Hardware/software**
AMD Ryzen 5950X, NVIDIA RTX 3090, Windows 10 20H2, D3D11

**Emulator version**
0.1-4208-g44a1335 (2021-06-09T21:01:54+10:00)

**Additional context**  
Dump is verified with modded console against original disc, and matches [redump](http://redump.org/disc/20/). Only noticable difference, aside from the glitches, is the framerate: Duckstation runs at 59.81, console runs at 59.94 (according to the monitor used).

**Comment by stenzek** [comment]
No save file provided, I can't investigate without one.

**Comment by stenzek** [comment]
> Only noticable difference, aside from the glitches, is the framerate: Duckstation runs at 59.81, console runs at 59.94 (according to the monitor used).

DuckStation is running at the correct frequency for progressive mode. See https://psx-spx.consoledev.net/graphicsprocessingunitgpu/#gpu-timings

**Comment by stenzek** [comment]
For the graphical issues, if you're not going to provide a save file, try enabling recompiler icache in game properties -> compatibility settings.

**Comment by Xaymar** [comment]
Save file: [Chrono Cross (USA) (Disc 1)_1.zip](https://github.com/stenzek/duckstation/files/6635979/Chrono.Cross.USA.Disc.1._1.zip)

**Comment by Xaymar** [comment]
Hit send too early. If you use the above memory card, the first four are okay, and the fifth one is corrupted. Key items disappeared, stats are weird, inventory is weirder (some people lost their weapons somehow), and money is well... way too high compared to what I had before.

> For the graphical issues, ..., try enabling recompiler icache in game properties -> compatibility settings.

This does seem to fix the problem.

**Comment by stenzek** [comment]
If the save is already corrupted, there isn't much I can do there. I need to be able to observe and debug the issue when it happens, not afterwards.

It's also possible that a game bug caused the corruption. Game bugs do exist.

**Comment by Xaymar** [comment]
> If the save is already corrupted, there isn't much I can do there. I need to be able to observe and debug the issue when it happens, not afterwards.

My tests ran from the 4th save slot. The 5th save slot was different testing to reproduce a crash/freeze on load bug, which happened once before testing, but never again after it. I'll see if I can get closer to the location where things break.

> It's also possible that a game bug caused the corruption. Game bugs do exist.

I'm not ruling it out so far, though I haven't been able to reproduce the bug(s) with the original disc on a console yet. It's possible that the unique sequence of events on Duckstation is causing these glitches, as I haven't gotten the same characters in the intro sequence on console yet.

**Comment by Xaymar** [comment]
Repro'd the inventory bug on console. A very specific order of actions results in the inventory losing its ability to be modified, corrupting on save.

Text corruption goes away with Icache.
