### ISSUE TITLE
Medal of Honor (USA) / Medal of Honor - Underground (USA) - Strange controls

### ISSUE THREAD

**Issue by deivkiau** [stenzek/duckstation#2257]
**Game details**
SLUS-00974 Medal of Honor (USA)
SLUS-01270 Medal of Honor - Underground (USA)

**Description of the issue / bug**
1. If you set controller type to **DualShock** with **Force Analog Mode** disabled _(like DualShock with analog toggle off with a real console, navigating only with D-PAD)_ at intro it will automatically turn on **analog mode** which make issue no. **2**.
2. In-game you can't move crosshair vertically only horizontally. But if controller type change to **Digital**, everything works as supposed to.

**Emulator version**
RetroArch - 2021-06-11 from https://www.duckstation.org/

**Additional details**
Try on mednafen - It's OK.

**Reproduction**
Link to YouTube - https://youtu.be/dHf_A0wV47o file to big to upload.

**Comment by foxsevent** [comment]
Yeah I don't think this is a real issue, these two games are just dumb this way.
When starting or restarting a level they turn on analog mode if Dual Shock is present.

For the second issues it's these games dumb Dual analog aiming configuration left stick moves the cross hair Left and right and the right one up and down.

Only solution is to switch analog off when starting a level or just switch pad type to digital.

**Comment by stenzek** [comment]
Please compare with console to ensure this behavior is not normal, and just a quirk of how this game is designed.

**Comment by stenzek** [comment]
As @foxsevent said, it seems the horizontal/vertical aiming is done using both sticks. Left stick adjusts horizontal aim and forward/backward, right stick adjusts vertical aim and strafes.

Mednafen might not be engaging analog mode, and that's why it's "different" there.
