### ISSUE TITLE
Android TV package.

### ISSUE THREAD

**Issue by divid3byzer0** [stenzek/duckstation#2259]
**Is your feature request related to a problem? Please describe.**
Will Duckstation have in the (near or far) future an Android TV specific package? Mind you, I have been using the regular Android version (installing the APK directly, since it does not appear on Google Play), but on Android TV and with a gamepad, navigation is a bit difficult and I cannot add it to the main launcher screen. I don't want to sound ungrateful, I have been enjoying the emulator and this is just a minor nuisance.
My request is just a suggestion and nothing more.

**Describe the solution you'd like**
A Duckstation package built specifically for Android TV with easy gamepad navigation, and a combination of keys to exit the emulator / go to options for example.

**Describe alternatives you've considered**
Using the Retroarch core, but since it's always a bit behind the official one and I'm only interested in PSX emulation, it's a bit overkill (but I can live with it).

**Comment by Margen67** [comment]
Duplicate of #1093

**Comment by divid3byzer0** [comment]
> Duplicate of #1093

Indeed it is...I tried to search but I guess I'm not too familiar with GitHub, because I couldn't find anything related to Android TV.

Having read the other issue, it's clear stenzek has no interest in Android TV and he has every right to do so. As things stand now, there are some options to people who intende to use it for running Duckstation.

**Comment by stenzek** [comment]
It works on android tv, but I'm not writing a separate UI for devices which are significantly underpowered, and I don't even own.

With scoped storage being a requirement in a few months, every emu is going to have this issue.

The duckstation core libretro core is up to date. Swanstation is months behind and slower.
