### ISSUE TITLE
Spyro 3 softlock in preview build.

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#2261]
**Game details**
[Serial Code, Region]
Spyro - Year of the Dragon (USA) 
SCUS-94467 

**Description of the issue / bug**
Game soft locks on the main menu on the newest preview build, works fine on latest, possible anti piracy measure triggered?
https://youtu.be/Pd7tjU4L1ME

**Steps to reproduce**
Start the game in the newest preview build.

**Enhancements information**
Tested with no enhancements,

**Hardware/software**
i5-9300H
Geforce 1650
16GB DDR4
D3D11 

**Emulator version**
![Przechwytywanie](https://user-images.githubusercontent.com/64225743/121828285-6af20d80-ccbf-11eb-926d-ab8f55d4c8b1.PNG)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/f2bfbabdcbd2c25d1ac06051e67d6899133348a1
