### ISSUE TITLE
biohazard 3,dino risis 1&2 jap version stuck at warning screen after loading.

### ISSUE THREAD

**Issue by zkdpower** [stenzek/duckstation#2262]
biohazard 3,dino risis 1&2 Japanese version were stuck at warning screen after loading.
forbidden any enhancement.

**Comment by foxsevent** [comment]
Reports with deleted template will be ignored and closed.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/f2bfbabdcbd2c25d1ac06051e67d6899133348a1
