### ISSUE TITLE
Dino Crisis splash screen softlock.

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#2263]
**Game details**
[Serial Code, Region]
Dino Crisis (USA)
SLUS-00922

**Description of the issue / bug**
Like the title says game soft locks on the first splash screen with warning about gore, only happens on the preview version works fine on latest.
Seems to be a bigger issue affecting multiple games.

**Steps to reproduce**
Start game with on the preview build.

**Enhancements information**
Tested with no enhancements.

**Hardware/software**
i5-9300H
Geforce 1650
16GB DDR4
D3D11

**Emulator version**
![Przechwytywanie](https://user-images.githubusercontent.com/64225743/121832487-6f6ff380-ccca-11eb-9d7b-08eeb54585a6.PNG)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/f2bfbabdcbd2c25d1ac06051e67d6899133348a1
