### ISSUE TITLE
Project - Horned Owl (USA): Emulator says Playstation Mouse not supported

### ISSUE THREAD

**Issue by waspennator** [stenzek/duckstation#2269]
**Game details**
SCUS-94408 Project - Horned Owl (USA)
Redump Verified

**Description of the issue / bug**
For some reason, Duckstation says this game is not compatible with the playstation mouse, despite being playable just fine with it.

**Steps to reproduce**
Boot up the game with the playstation mouse select for the 1st controller port and it should pop up the "Playstation mouse is not supported for this game"

**Hardware/software**
i5 6600k
Geforce GTX 1070
Windows 10
Vulkan 

**Emulator version**
0.1-4251 Preview Build

**Comment by foxsevent** [comment]
Yeah it's not really a bug just an error in the database, same thing was with Broken Sword.
Just needs a correction no need to worry.
Also small note since you're on windows 10 it's best to use D3D11 render, it's just very slightly more compatible, performance wise it's the same as Vulcan.

**Comment by stenzek** [comment]
Shouldn't be any compatibility differences between the two renderers.

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/e4fb028c8cee653db4997f250319be453b17c173

**Comment by waspennator** [comment]
Updated and it still pops up the "Playstation Mouse is not supported error"
![Horned owl](https://user-images.githubusercontent.com/78768499/122421037-545ee700-cf49-11eb-88d9-3e2b88ad80f6.png)

**Comment by stenzek** [comment]
The controller type mask is cached in the game list, you'll need to rescan.

**Comment by waspennator** [comment]
Just did that and it seemed to fix it, thanks mate.
