### ISSUE TITLE
Eliminator (Europe) (En,Fr,De,Es,It) stuck on loading screen

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#227]
when the game goes to load level one it is stuck on the loading screen
![elim](https://user-images.githubusercontent.com/2696404/78470196-1a496100-775a-11ea-8c8a-60181e29887d.PNG)
![elim1](https://user-images.githubusercontent.com/2696404/78470197-1c132480-775a-11ea-8c49-da22ddd2d7c7.PNG)

**Comment by stenzek** [comment]
Confirmed fixed by @kurayami6 on discord.
