### ISSUE TITLE
[Libretro] Weak force feedback 

### ISSUE THREAD

**Issue by n1ghttrap** [stenzek/duckstation#2270]
Using Silent Hill and 2 different Wii U Pro Controllers via 2 different Mayflash adapters to test.  Just feels very subdued per gun shot and during the low health heartbeat compared to how I remember it other emulators.  I'll test in Beetle and the standalone just to be sure, but wondering if there could be an option to adjust this in any case as it feels fine in other games/emulators.  Thanks in advance.

**Comment by stenzek** [comment]
You didn't fill out the issue template. Closing.

Beetle's emulation is likely incorrect here. DuckStation's vibration emulation has been hardware tested. The main issue is other controllers have a vastly different feel/profile compared to dualshock.

Standalone has a vibration bias option which can increase the intensity across the board, I will expose this in the libretro core in the future.
