### ISSUE TITLE
Actual CD/backups support

### ISSUE THREAD

**Issue by VermillionFury007** [stenzek/duckstation#2271]
It woud be cool if we could use actual fisical cds to run in the emulator...

**Comment by stenzek** [comment]
You deleted the issue template.

Also duplicate of https://github.com/stenzek/duckstation/issues/1271

This isn't something I have any plans to implement at the moment. My intuition is that due to spinup/spindown it'll cause drastically inconsistent seek times, resulting in emulation hitches.
