### ISSUE TITLE
Disney's The Little Mermaid II (USA): Pearl Black box and other graphical issues

### ISSUE THREAD

**Issue by waspennator** [stenzek/duckstation#2272]
**Game details**
SLUS-01286 Disney's The Little Mermaid II (USA)
Redump Verified

**Description of the issue / bug**
When using any of the graphical backends save for the software one, the pearls in the game have this weird black box around them, also noticed the light shining on the right looks a bit weird too.

**Steps to reproduce**
Start up the game with any backend that isn't software and skip through the intro until you get in game, it should only be about 30 seconds or so before you see a pearl with a black box border engulfing it on the left, light should also look weird on the right too.

**Hardware/software**
i5 6600k
Geforce GTX 1070
Windows 10
Vulkan 

**Emulator version**
0.1-4251 Preview Build

**Additional Context**

Software Renderer:
![SLUS-01286_2021-06-16_21-31-42](https://user-images.githubusercontent.com/78768499/122327364-f8657580-ceea-11eb-963c-96badd12adf3.png)

Vulkan/D3D11/OpenGL renderers:
![SLUS-01286_2021-06-16_21-17-13](https://user-images.githubusercontent.com/78768499/122327369-fb606600-ceea-11eb-8435-32c928e73e53.png)

**Comment by backgamon** [comment]
Are u using the preview version of duckstation, or the stable one?
I have same problem if i use the preview.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/815146e7d8e7a4bc862f6309484bc3cd046a2318
