### ISSUE TITLE
FMV filtering

### ISSUE THREAD

**Issue by backgamon** [stenzek/duckstation#2273]
Hi,

When using the downsampling adaptive option , all FMV are filtered.
But if u not using FMV are pixelated.

Any chance to add an option to always filter FMV without using the downsampling adaptive?.

FMV without adaptive:
https://www.youtube.com/watch?v=q8rAn4f-Z_c

FMV with adaptive (look much better):
https://www.youtube.com/watch?v=9PNfMZnTU1c

**Comment by stenzek** [comment]
Issue template not completed.

Not something I'm interested in doing, sorry. It's not an off/on toggle, adaptive downsampling uses a bunch of shaders and intermediate textures which need to be created at init time.
