### ISSUE TITLE
What happened to the android port

### ISSUE THREAD

**Issue by strikersix23** [stenzek/duckstation#2275]
Im curious what happened to the Android code i know it was removed but why? Was it to hard to maintain or did you lose an device and cant test it, or was it unfeasible to continue?

**Comment by stenzek** [comment]
It's moved to the play store, or https://www.duckstation.org/android/duckstation-android.apk

But you should use the play store build, since we can see crash reports from it.

**Comment by strikersix23** [comment]
So auto builds go to those places now, is there an Android branch

**Comment by stenzek** [comment]
No auto builds, it's in sync with the play store beta.

**Comment by strikersix23** [comment]
Ok thank you
