### ISSUE TITLE
[REQUEST] use mouse for light gun games

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#228]
games such as ghoul panic and the point blank series

**Comment by stenzek** [comment]
Latest build has Namco GunCon support. However, you still need to use the keyboard to activate the buttons, will add mouse binding soon.

**Comment by kurayami6** [comment]
This has been added now, hasn't it? Can this be closed?

**Comment by stenzek** [comment]
I was keeping it open until I added the UI for setting the crosshair image.

**Comment by stenzek** [comment]
Custom crosshair support is added, so I'm closing this now.
