### ISSUE TITLE
[RetroArch] [RetroPie on RPi4] Shader compilation failures when changing AA and IR.

### ISSUE THREAD

**Issue by adelpha** [stenzek/duckstation#2282]
**Game details**
All games.

**Description of the issue / bug**
Changing AA and IR settings together in the libretro version causes shader compilation errors that result in the OpenGL renderer failing to initialize. 

**Steps to reproduce**
Simply start switching IR and AA options (e.g. enable 2xIR and 2xMSAA, switch to 3xIR, disable AA, switch to 1xIR) and it'll fail very quickly.

Fallback to software renderer never works either, just results in a black screen while the game continues running.

Changing IR options a few times usually brings display back.

**Enhancements information**
Occurs whether enhancements are enabled or disabled.

**Hardware/software**
RPi4B at default clocks
RetroPie
RetroArch 1.9.4
Full KMS (dtoverlay=vc4-kms-v3d,noaudio)
Occurs with both "gl" and "glcore" drivers

**Emulator version**
lr-duckstation 0.1-4189-g1d0f21af

**Additional context**
PasteBin of sample RA logfile here:
[https://pastebin.com/UsqBbtsc](https://pastebin.com/UsqBbtsc)

**Comment by stenzek** [comment]
This driver is only GLES 3.1 compliant and does not support per-sample shading (required for one of the copy shaders). I'll push a patch later to disable MSAA unless you have GLES 3.2.
