### ISSUE TITLE
About custom Bios

### ISSUE THREAD

**Issue by BDJoe360** [stenzek/duckstation#2285]
Thank you very much for bringing such a high quality emulator
However, due to some custom PS games need to go to custom BIOS to run normally.
So can you add the option to specify that the game uses the specified BIOS in the attribute settings of each game?
Thank you very much.

**Comment by stenzek** [comment]
Issue template removed, closing.

But no, I see no use case for this. As far as I'm aware there's no known compatibility issues with games and specific BIOS versions, and you can already set a BIOS per-region.

**Comment by BDJoe360** [comment]
Thank you for your reply
The reasons why you need to use custom bios are as follows:
Because part of the game translated from Japanese to Chinese :needs to use the modified special BIOS font, and different games use different BIOS. So these special games can use the specified BIOS settings on the best!!








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stenzek/duckstation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月20日(星期天) 中午1:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [stenzek/duckstation] About custom Bios (#2285)





 
Issue template removed, closing.
 
But no, I see no use case for this. As far as I'm aware there's no known compatibility issues with games and specific BIOS versions, and you can already set a BIOS per-region.

**Comment by stenzek** [comment]
I do not provide any support for romhacks, as many of them are written for inaccurate emulators and do not run on hardware. This would especially be the case for modified BIOSes - unless you replaced the ROM chip, it would not work on console.

However, you can still set the BIOS for the Japanese region to your custom/patched image.
