### ISSUE TITLE
2 unrelated crashes in KulaQuest (Japan) 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#229]
When using OpenGL the emulator will randomly freeze, I assume due to the massive amount of VRAM copies the game spams.

![Capture](https://user-images.githubusercontent.com/31968468/78470997-137a1880-7771-11ea-92d0-ea6ee4c60a94.PNG)

![Capture4](https://user-images.githubusercontent.com/31968468/78470992-0ceba100-7771-11ea-8449-0944e9ffb511.PNG)

I tried switching to Software which fixed the problem but then It crashed with this error when I died in level 5 or maybe 6.

![Capture2](https://user-images.githubusercontent.com/31968468/78471024-50dea600-7771-11ea-885e-fe5cdbd57d06.PNG)

**Comment by stenzek** [comment]
Oversized/overlapping VRAM copies are implemented on the GPU in the latest build, which should solve the slowdown problem.

I've changed the assert to a warning - there's still some unknowns about what this bit does, but the game is probably just streaming audio so it doesn't matter. Give it a go anyway.
