### ISSUE TITLE
achievements login error

### ISSUE THREAD

**Issue by kenshero99** [stenzek/duckstation#2295]
![Capture](https://user-images.githubusercontent.com/86216770/122705171-77451000-d255-11eb-87fc-deed5c93771e.PNG)
tried to login with two different accounts that i know works for sure ,but still the same problem.
how can i get it to login?

**Comment by stenzek** [comment]
Issue template deleted, closing.

From your screenshot it looks like you're using Windows 7, which is not supported. Please read the Windows 7 paragraph here: https://github.com/stenzek/duckstation#windows
