### ISSUE TITLE
SLPS-01475 Zen Nihon Joshi Pro Wrestling - Joou Densetsu - Yume no Taikousen (Japan)

### ISSUE THREAD

**Issue by Jetup13** [stenzek/duckstation#2299]
**Game details**
[SLPS-01475 Zen Nihon Joshi Pro Wrestling - Joou Densetsu - Yume no Taikousen (Japan)]

**Description of the issue / bug**
Major graphical errors on software, Vulkan (Tried Vulkan on Android), and D3D11 modes. Only thing that plays correctly is are the FMV's for the intro and entrances. Game seems to hang when loading into a match

**Steps to reproduce**

Launch game and the first load screen you'd immediately notice broken texture. Menus are navigable but also have broken texture. 

**Enhancements information**
All enhancements are off with the disable enhancement button

**Hardware/software**
Dell OptiPlex 9020
Intel Core i5-4590 CPU @ 3.30GHz (4 CPUs)
16384MB RAM
Intel HD Graphics 4600 2160MB
Windows 10
Tried D3D11 and Software

Samsung S10e 
Snapdragon 855 (Adreno 640)
Android 11
Tried Vulkan, OpenGL, and Sofware

**Emulator version**
0.1-4287-g2ab38aa4

**Additional context**
CHD format. 
Mode/2 ea56a7ba699d96136b17ed05f49982b2
Audio a0580798280736865f5a3a0acf0070a3

![SLPS-01475_2021-06-21_10-23-21](https://user-images.githubusercontent.com/62556437/122804760-234e2180-d27d-11eb-946e-2e24ff045d43.png)
![SLPS-01475_2021-06-21_10-23-03](https://user-images.githubusercontent.com/62556437/122804773-26491200-d27d-11eb-9ec5-3911b9f2bc65.png)

**Comment by stenzek** [comment]
Should be fixed in https://github.com/stenzek/duckstation/commit/7ac537bf73e7233eec09fe7b93ba4c843d389e7e (preview build).
