### ISSUE TITLE
SLUS-00674 International Superstar Soccer Pro '98 (USA) freeze when writing options to MC

### ISSUE THREAD

**Issue by adelpha** [stenzek/duckstation#2301]
**Game details**
SLUS-00674 International Superstar Soccer Pro '98 (USA)
SLES_01218 International Superstar Soccer Pro '98 (Europe)

**Description of the issue / bug**

**Edit: Works in Execution Mode: Interpreter (slowest). Fails in Cached Interpreter and Recompiler.**
**Edit 2: Works consistently in Recompiler if CPU underclocked to 50%. Other values may work too.**

Game freezes when trying to create memory card options file during first startup. Rendering continues but game won't progress past this screen:

![SLUS-00674](https://i.imgur.com/pJly9vf.png)

**Steps to reproduce**
Make sure you're using Cached Interpreter or Recompiler.
Load game, press Start at start screen.
Game will attempt to save options to MC and freeze. No data is written to the MC.

**Enhancements information**
All enhancements/advanced features disabled.

**Hardware/software**
Windows 10 21H1
Intel Core i7-5820K CPU @ 3.30GHz
NVIDIA GeForce GTX 980
D3D11/Vulkan

**Emulator version**
DuckStation 0.1-4287-g2ab38aa4 (dev)

**Additional context**
Occurs in libretro version on RPi4 too.

**Comment by andercard0** [comment]
Just tested here and it is working fine, as follows: 

![Soccer98](https://user-images.githubusercontent.com/43047877/122997539-7f4e9e00-d382-11eb-805a-8440f30506d2.png)

Double check your game hashes here: http://redump.org/disc/177/
![hashes](https://user-images.githubusercontent.com/43047877/122997550-81186180-d382-11eb-8454-8081bfc77220.png)

Here is the MC created.
[Memory Card.zip](https://github.com/stenzek/duckstation/files/6697334/Memory.Card.zip)

**Comment by adelpha** [comment]
Hashes are identical in my image.

**Comment by BloodRaynare** [comment]
Same problem as #2183 (It's even the same game, just with different language), use "Recompiler ICache" to get past it if using Recompiler.

**Comment by adelpha** [comment]
Ah, didn't think to search the Japanese title. Thanks.

**Comment by dankcushions** [comment]
But doesn't that mean
> SLUS-00674 International Superstar Soccer Pro '98 (USA)
> SLES_01218 International Superstar Soccer Pro '98 (Europe)

...need to be added to https://github.com/stenzek/duckstation/blob/master/data/database/gamesettings.ini so it happens automatically, like the JP version https://github.com/stenzek/duckstation/commit/4a13009af872476c0a675e9f72ea179c0eeef872 ?

**Comment by adelpha** [comment]
Good point. Reopening so Stenzek sees it.

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/8ddc1d6016c6b76fa2b58c5bd8d43c6d30538bc1
