### ISSUE TITLE
Croc 2 Vulkan issue.

### ISSUE THREAD

**Issue by backgamon** [stenzek/duckstation#2303]
Game details
SLES_020.88 - Croc 2 - legend of the Gobbos (Europe).

Description of the issue / bug
The game has missing geometry during introduction with Vulkan render.
With OpenGL render intro are fine.

Steps to reproduce
Just launch game under Vulkan with or without ehancement.

Hardware/software
Core I9 10850K@4.7/4.8Ghz
Asus Maximus Formula XII
64 Gb Gskill Trident Z RGB 3600Mhz@XMPII.
Gigabyte 2070 RTX 8G OC[466.47]
Windows 10 Pro x64[19042.1052]

Emulator version
0.1-4304-g226acdfe - Checked on stable too -> Same problem.

Additional context
OGL:
![Ogl](https://user-images.githubusercontent.com/39404647/123075572-a192fb00-d418-11eb-93dd-5c41a382ad7c.jpg)
Vulkan:
![Vulkan](https://user-images.githubusercontent.com/39404647/123075606-a9eb3600-d418-11eb-9b49-212c1a534a35.jpg)

https://www.youtube.com/watch?v=p4F6U24AahM

**Comment by stenzek** [comment]
Not a Vulkan issue, it's an upscaling issue. But fixed in https://github.com/stenzek/duckstation/commit/98f0e5908b7573e45b4d6335de2dec82d94e95ca
