### ISSUE TITLE
[Windows] Emulator open and close after some seconds

### ISSUE THREAD

**Issue by CyberMSX** [stenzek/duckstation#2304]
**Description of the issue / bug**
The emulator open in Windows 10 for 4-5 seconds and close.
But in Windows 7 it's working very well.

**Hardware/software**
Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
RAM: 10Gb
AMD Radeon R7 240 Series (2Gb VRAM)
Windows 10 [10.0.19043.1081]
[GPU Renderer - D3D11]

**Emulator version**
0.1-4287-g2ab38aa4

**Comment by stenzek** [comment]
This is probably a third party library interfering.

Please upload the `crash.dmp` file located in the user directory.

**Comment by CyberMSX** [comment]
[crash.zip](https://github.com/stenzek/duckstation/files/6701386/crash.zip)

**Comment by stenzek** [comment]
Yep, buggy driver. See here: https://www.google.com/search?client=firefox-b-d&q=EZFRD64.dll

You can start duckstation with `-nocontroller`, or set the controller interface to "None" to prevent it from loading this broken driver.
