### ISSUE TITLE
(Vib Ribbon) Can't start main game

### ISSUE THREAD

**Issue by GuiMiTomo** [stenzek/duckstation#2306]
SCES-02873 (Vib Ribbon Europe)
When I start the game, I can only use custom musics and not the main game.
![image](https://user-images.githubusercontent.com/76497419/123119235-3eff2680-d43b-11eb-8a60-b5c224f65a16.png)
OS: Windows 10
Processor: ![image](https://user-images.githubusercontent.com/76497419/123119714-ac12bc00-d43b-11eb-9095-66f63c89579a.png)
DuckStation version: ![image](https://user-images.githubusercontent.com/76497419/123119912-d2385c00-d43b-11eb-8e91-cafe116d9182.png)

**Comment by stenzek** [comment]
You deleted the issue template.

This is probably a bad dump. Make sure you have the correct hashes in game properties which match http://redump.org/disc/17774/
