### ISSUE TITLE
customize the "post processing" for different games in the game list

### ISSUE THREAD

**Issue by crashGG** [stenzek/duckstation#2308]
I hope to customize the "post processing" for different games in the game list, because some 2D games are set to scan lines to look better, while 3D games don’t need it.
<img width="442" alt="2021-06-25_002136" src="https://user-images.githubusercontent.com/80488411/123334187-65ac8280-d54b-11eb-8c3f-0c15199a5b40.png">
<img width="513" alt="2021-06-24_094641" src="https://user-images.githubusercontent.com/80488411/123334212-6fce8100-d54b-11eb-8b78-39b1b2935d27.png">

**Comment by stenzek** [comment]
I'm not planning any further enhancements to the post processing system. The long term plan is to switch to reshade but it's not a priority.
