### ISSUE TITLE
[Feature Request] Densha De Go train controller emulation

### ISSUE THREAD

**Issue by n1ghttrap** [stenzek/duckstation#2315]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Densha De Go controller support that reads analog joystick axes, throttles especially.

**Describe alternatives you've considered**
There are none.  The game only reads incremental digital presses and is agnostic of lever position via standard controller input.

**Additional context**
It would just be neat and this functionality only exists in MAME's buggy and slow driver for the games.  Unsure if it's because it's hard to implement or it's just a distant/obscure prospect.

**Comment by stenzek** [comment]
Duplicate of https://github.com/stenzek/duckstation/issues/511
