### ISSUE TITLE
No subimages when using "Preload Image To RAM" and .M3U playlist

### ISSUE THREAD

**Issue by MortiSNZ** [stenzek/duckstation#2318]
**Game details**
SLUS-00892, Final Fantasy VIII (USA)

**Description of the issue / bug**
After enabling "Preload Image To RAM", booting from a .M3U playlist will only load the first CD image. No subimages are available.

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
No
2. Which controller backend are you using in general settings
XInput

**Steps to reproduce**
Enable "Preload Image To RAM" and boot from a .M3U playlist file.

**Enhancements information**
I have tested with and without enhancements and the issue is present regardless.

**Hardware/software**
Intel i7 7700, NVIDIA GTX 1070 Ti, Windows 10
GPU Renderer - D3D11

**Emulator version**
DuckStation 0.1-4315-gf7587eae (dev)

**Additional context**
None

**Comment by foxsevent** [comment]
Yeah that's kinda intended, unless you want it to devour 4gb or more of your RAM.

**Comment by stenzek** [comment]
I have no plans to preload multi image files. Playlists aren't the intended way of handling multi disc in duckstation anyway, there is a game list and you can switch to any file.

I'll make it skip preloading for >1 image files and display a message to avoid confusion.

**Comment by MortiSNZ** [comment]
the problem with changing the disc without the playlist is that it defaults to creating a new memory card, and setting up a shared memory card exclusively for a multi disc game is complicated otherwise. it also means i can't use the change disc hotkey.
