### ISSUE TITLE
Final Fantasy Tactics Freeze During Battle

### ISSUE THREAD

**Issue by StewDaddy** [stenzek/duckstation#2319]
**Final Fantasy Tactics 1.3**
[Serial Code, Region]
I do not know where to find this information but my region is US.
[i.e SLUS-00404 Ace Combat 2 (USA)]

**Description of the issue / bug**
Game freezes during battle shortly after start as soon as the computer takes its turn.

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open? NO
2. Which controller backend are you using in general settings? Tried all 3 options

**Note:**
If you are using Duckstation on Android device please consider the following before report:
Are you using any kind of "memory optimizer" program such as: Ccleaner, Wisecleaner, Clean Master, Boost Android etc. ?
(if so, please, consider create an exception on it first and test; or even remove / uninstall it retest and then, if the problem persists continue with the report.

**Steps to reproduce**
I tried regular game start, as well as loading from a saved state.  I have no idea what the issue could be so I have tried various different options from the settings. The game loads and soon after engaging in any form of battle (i.e. generic or storyline progression) the game freezes on the "enemy's" first or second turn which is seconds after combat starts. There seems to be no exceptions.

**Enhancements information**
All enhancements are off.

**Hardware/software**
Alienware Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz 2.21GHz (16 processors)
NVIDIA GeForce RTX 3070 Laptop GPU
Windows 10 Home 64-bit OS, x64-based processor

[GPU Renderer - D3D11/OpenGL/Vulkan] I have tried all available options

**Emulator version**
DuckStation 0.1-4315-gf7587eae (dev) 

**Additional context**
I cannot play Final Fantasy Tactics on Duckstation. The game freezes when battle starts. I think it could be my settings as I'm only about a few hours into this. I just can't figure out what's wrong. I have tried every renderer option and both adapter settings for my pc (which is an Intel UHD Graphics or NVIDIA GeForce RTX 3070 Laptop GPU for my Alienware running Win10). The emulation speed shows 100% but then freezes and the FPS drops to 0. I also have tried various internal resolution scaling, multisample antialiasing and texture filtering. I also turned all enhancements off.

I'll be honest...I have very little idea what any of these things do. I watched a video on how to get started with DuckStation as I am moving over from ePSXe. I know that some games have issues where others do not and I think that FFT might be one of those games. All other games that I've tried worked fine. I just don't know what I need to do to solve the issue. Any help would be greatly appreciated.

**Comment by foxsevent** [comment]
"Final Fantasy Tactics 1.3" this tells me the game you have was modded in which case we can;t help you as mods tend to break things.
Try running a unmodded clean version of the game.

**Comment by StewDaddy** [comment]
Oh ok. I'll see if I can find one that isn't and get right back to you. Thanks for this.

Sent from Yahoo Mail on Android 
 
  On Sat, Jun 26, 2021 at 16:23, ***@***.***> wrote:   


"Final Fantasy Tactics 1.3" this tells me the game you have was modded in which case we can;t help you as mods tend to break things.
Try running a unmodded clean version of the game.

**Comment by StewDaddy** [comment]
Well...I found the original version (which I thought I had) and that seems to have solved my issue! Thanks a lot for the simple yet accurate fix!
