### ISSUE TITLE
Opening FMV of BoF4 flickering D3D11

### ISSUE THREAD

**Issue by bajolzas** [stenzek/duckstation#232]
The lower half of the screen of Breath of Fire IV's opening FMV flickers when using D3D11, this doesn't happen with OpenGL.

**Comment by stenzek** [comment]
Could you post a screenshot of the affected scene? I can't seem to reproduce this.

**Comment by kurayami6** [comment]
I'm getting it in D3D11 as well. Must be yet ANOTHER D3D11/Windows 7 issue. You're either gonna need to fix the root cause or warn windows 7 users that D3D11 is broken for them. I've found dozens of other games that are broken with D3D11/Windows that I haven't bothered reporting. 

![SLUS-01324_2020-04-08_20-43-46](https://user-images.githubusercontent.com/31968468/78775671-f300c700-79d9-11ea-932b-694cb7cbfaf4.png)

**Comment by stenzek** [comment]
@kurayami6 I'm starting to think of it being less of a Windows 7 issue and more of a specific driver/vendor issue.

Silly question, can you try using the SDL frontend? I've noticed some other strange things with the D3D11 backend, like it being locked to vsync in Qt but not SDL on my laptop, but my desktop is fine.

**Comment by kurayami6** [comment]
Still happens with SDL.

![Capture](https://user-images.githubusercontent.com/31968468/78778034-ef6f3f00-79dd-11ea-9715-bee7cef1c0a5.PNG)

**Comment by stenzek** [comment]
Alright, must be an unrelated issue then... unfortunately not much I can do until I can find a system I can reproduce it on. Will try on my AMD GPU soon.

**Comment by stenzek** [comment]
Worked fine on my RX580. I guess I'll have to install Windows 7 somewhere and see if it happens there... :/

**Comment by ggdrt** [comment]
I can't reproduce this issue on Windows 7 with Intel HD Graphics 4400. Works properly with both Qt and SDL frontends.

**Comment by kurayami6** [comment]
My computer specs. Let me know if you need any more info. 

![Capture](https://user-images.githubusercontent.com/31968468/78859081-ab2d7e80-7a71-11ea-8f87-c9c6fefd72b2.PNG)

**Comment by stenzek** [comment]
Let's continue to discuss this in #153.

**Comment by stenzek** [comment]
Actually, I don't think this was #153. I suspect it may have been due to a regression from my interlacing changes, but it only happens when upscaling is enabled.

Please re-test on the latest build.

**Comment by kurayami6** [comment]
Flickering is fixed.

**Comment by bajolzas** [comment]
I didn't see the replies before. I am using win10 and not 7, also at the time I tried to take screenshots of the issue, but could not get them to show it.
Not that it matter anymore, as the issue seems to be fixed.
