### ISSUE TITLE
LoD Character portrait overlay is wrong

### ISSUE THREAD

**Issue by bajolzas** [stenzek/duckstation#233]
Legend of Dragoon's Character portrait overlay looks wrong:
![SCUS-94491_2020-04-05_15-28-29](https://user-images.githubusercontent.com/51722671/78501771-2da5fd80-7755-11ea-9fe9-8f65111ae8ad.png)

Here is how it looks on beetle psx:
![lod portrait](https://user-images.githubusercontent.com/51722671/78501783-38f92900-7755-11ea-8a83-74f5ac8e3d71.png)

**Comment by stenzek** [comment]
I wonder if this is related to #206. Try without upscaling and/or the software renderer.

**Comment by bajolzas** [comment]
at 1x resolution it looks different but still not right

**Comment by stenzek** [comment]
Okay, I suspect this is the same issue as #55 with the games drawing lines with triangles, and different rasterization behavior of D3D/GL.

**Comment by stenzek** [comment]
Seems to be fixed in latest build.
