### ISSUE TITLE
Scooby-Doo! Night of 100 Frights (USA) (Proto): Black Screen cutscene issue

### ISSUE THREAD

**Issue by waspennator** [stenzek/duckstation#2334]
**Game details**
PSXEXE Scooby-Doo! Night of 100 Frights (USA) (Proto)
Redump Verified

**Description of the issue / bug**
For some reason when running this with the Duckstation emulator, instead of playing the cutscenes, it displays a black screen for a few moments before heading straight to the map screen, tested it out with Beetle PSX and can confirm the intro and a cutscene are supposed to play before the map screen, so this isn't supposed to happen.

**Steps to reproduce**
Start the game and it should go onto a black screen for a bit before transitioning to the map menu, skipping over the cutscenes it should normally play

**Hardware/software**
i5 6600k
Geforce GTX 1070
Windows 10
Vulkan 

**Emulator version**
0.1-4332 Preview Build

**Comment by stenzek** [comment]
Sorry, I don't investigate issues with prototypes since:

1. They're technically illegal to distribute (you don't have permissions from the rightsholder, and you can't purchase a license).
2. Often the issues are present on console as well.
