### ISSUE TITLE
[Feature Request] New scaling mode, "Hybrid" (Integer Upscale + Linear Downscale)

### ISSUE THREAD

**Issue by HeyItsLollie** [stenzek/duckstation#2335]
![UpscalingMockup](https://user-images.githubusercontent.com/30498581/123585232-308f8100-d826-11eb-9d64-0739bf7c9c26.png)
Current options for upscaling allow for either sharp but unevenly-scaled pixels, or soft-scaled linear filter, with no room inbetween.
I'd like to see a two-step hybrid scaling solution implemented:
* Scale from the internal resolution (no filtering) to one multiple higher than the target resolution.
* Downscale back down to fit the target resolution using bilinear filtering.

**Example:**
Resident Evil's internal resolution is 320x240, and the user's target resolution is 1440x1080 (4.5x scale, common for 4:3 on 1920x1080 screens). DuckStation would upscale by 5x (to 1600x1200) with point filtering, and then scale back down to fit the target.

I'd recommend doing the initial upscale on horizontal and vertical axes separately, to account for games with specialty-use resolutions. (EG: Wipeout 3's menu runs at 512x240. Silent Hill's menu runs at 320x448.)

Mock-up comparisons. (Recommend opening these images in new tabs)

![Upscale_1aSimple](https://user-images.githubusercontent.com/30498581/123585294-52890380-d826-11eb-91b7-24c826e356e9.png)
![Upscale_1bHybrid](https://user-images.githubusercontent.com/30498581/123585302-561c8a80-d826-11eb-8ac1-5577266cb16b.png)

---
The issue of unevenly-scaled pixels also currently appears in Integer Scaling when trying to conform to a game's native aspect ratio, and so a "hybrid" approach would benefit this scaling mode as well. This would help combat "pixel shimmering" in games where the screen scrolls horizontally at a constant rate.

![Upscale_2aIntSimple](https://user-images.githubusercontent.com/30498581/123586569-42722380-d828-11eb-9c89-32dc723b4c14.png)
![Upscale_2bIntHybrid](https://user-images.githubusercontent.com/30498581/123586064-8b75a800-d827-11eb-85aa-de039dd0f576.png)

**Comment by HighBunkerHxH** [comment]
This looks to be promising and interesting, no more pixel shimmering when using integer scaling if this happens

**Comment by stenzek** [comment]
Was added in https://github.com/stenzek/duckstation/commit/09e7a5843f0c0efb8352af22297a6c1576d97c03
