### ISSUE TITLE
Qt doesn't open with controller pluged in

### ISSUE THREAD

**Issue by bajolzas** [stenzek/duckstation#234]
If I try to open the Qt version with my Dualshock 3 controller pluged in, the cmd shows the following message and then just closes:

![error qt ps3](https://user-images.githubusercontent.com/51722671/78507391-9c944e00-7777-11ea-8cec-2143b4fb1dc2.png)

I usually use BetterDS3 to turn it into a Xbox360 controller, and if I do the same happens:
![error qt x360](https://user-images.githubusercontent.com/51722671/78507418-c9e0fc00-7777-11ea-824b-f7cce7638187.png)

While the sdl version works, I don't seem to find an option to rebind controls, be it keyboard or controller.

**Comment by stenzek** [comment]
Fixed in latest build.
