### ISSUE TITLE
Add support for region-free PSP-dumped PSX BIOS

### ISSUE THREAD

**Issue by RaydenX93** [stenzek/duckstation#235]
There is an PSX bios that can be dumped off of PSPs which is apparently region-free and provides better performance than the original PSX's ones.

I'm not sure if duckstation is already able to use this BIOS. If not, it may be interesting to make it compatible with this optimized BIOS for better performance/stability.

References:
- https://github.com/libretro/beetle-psx-libretro/issues/519
- https://github.com/gingerbeardman/PSX

**Comment by stenzek** [comment]
No idea, I don't have a PSP to dump one off. But feel free to try it, if you place the image in its own directory and configure the BIOS path, it should try to use it. It'll just complain in the log :)

**Comment by Ember2528** [comment]
It seams to run just fine just from playing a bit of Crash and Spyro. The only problem seams to be that fastboot doesn't work

**Comment by stenzek** [comment]
That's expected. Fastboot relies on patching the BIOS, and as a precaution it won't patch images which don't have a known hash.

**Comment by genova447** [comment]
In case RaydenX93 hasn't seen - but this is now properly implemented (tried it yesterday, and works with fastboot as well)
https://github.com/stenzek/duckstation/pull/637
