### ISSUE TITLE
[Question] Why does translated "Akumajou Dracula X [SLPM-86023]" slowdown while unpatched does not?

### ISSUE THREAD

**Issue by vanfanel** [stenzek/duckstation#2353]
**Game details**
SLPM-86023 Akumajou Dracula X: Gekka no Yasoukyoku

**Description of the issue / bug**
Game slows down while on semi-static file selection screen. It's specially affecting the music, which is heavily distorted everytime slowdown happens.
**Slowdown seems to be tied to text changing on screen.**
These can be seen on the console if logging is turned ON:

```
[  241.7488] V/System: FPS: 59.95 VPS: 59.95 Average: 16.60ms Worst: 16.61ms
[  242.7496] V/System: FPS: 59.95 VPS: 59.95 Average: 16.60ms Worst: 16.61ms
[  243.7505] V/System: FPS: 59.95 VPS: 59.95 Average: 16.60ms Worst: 16.62ms
[  244.7513] V/System: FPS: 59.95 VPS: 59.95 Average: 16.60ms Worst: 16.62ms
[  245.6895] V/AudioStream: Audio buffer underflow, resampled 874 frames to 880
[  245.7095] V/AudioStream: Audio buffer underflow, resampled 735 frames to 884
[  245.7295] V/AudioStream: Audio buffer underflow, resampled 736 frames to 880
[  245.7495] V/AudioStream: Audio buffer underflow, resampled 736 frames to 884
[  245.7521] V/System: FPS: 58.95 VPS: 58.95 Average: 16.88ms Worst: 33.29ms
```

**Steps to reproduce**
Apply the english translation available here:
https://www.romhacking.net/translations/1427/
to the japanese version of Castlevania SOTN, which is [SLPM-86023] Akumajou Dracula X: Gekka no Yasoukyoku.
Then run the game on Duckstation and access the file selection screen.
Whenever a text changes on screen, there's an audio distortion.

**Hardware/software**
Raspberry Pi 4 running Debian 10 in aarch64 mode, latest stable MESA, DuckStation NOGUI build from latest GIT code.

**Emulator version**
Latest GIT code.

**Additional context**
**My theory** The translation is doing something wrong with text on the file selection screen: that's obvious because there's displaced text on the NO DATA banner on the space for MEMORY CARD2.
I suspect the game causes internal errors (maybe it tries to write memory off-limits?) and DuckStation somehow slows down on those. Loging is totally disabled when the slowdowns happen.
Could I be right?

**Comment by stenzek** [comment]
Romhacks are not supported.

Please don't open issues complaining about performance on hardware which barely meets the minimum requirements. It's difficult enough managing the huge range of devices on android, let alone SBCs too. The code is there, yes, but I make no guarantees about how it will work.

If you can reproduce this issue on an android device, or a x86 machine, then I will consider looking into it. But as it's a romhack, the same deal applies really, it's probably doing something which hits a slow path, and unless a retail game also does it, I have no interest in changing anything.
