### ISSUE TITLE
Purge "obsolete" translation strings. Before big releases

### ISSUE THREAD

**Issue by shikulja** [stenzek/duckstation#2355]

**Comment by stenzek** [comment]
`lupdate` might have a feature to do this, not sure.

But I'd rather not mess with others' translation files, it just leads to conflicts.

**Comment by andercard0** [comment]
> 
> 
> _No description provided._

As Stenzek said, you might want to open the file: update_translations.bat with any text editor and add the following line:

set LUPDATE=..\..\dep\msvc\qt\6.1.0\msvc2019_64\bin\lupdate.exe ./ ../core/ ../frontend-common/ -tr-function-alias translate+=TranslateString **-no-obsolete** -tr-function-alias translate+=TranslateStdString -tr-function-alias QT_TRANSLATE_NOOP+=TRANSLATABLE

This way you can remove (for your translation) obsolete entries. 
I personally do prefer to keep these lines in other to see what i had in my, like, guesses for terms and all that.
