### ISSUE TITLE
enable option so PEC can activate/deactivate codes on duckstation

### ISSUE THREAD

**Issue by overlordchaos** [stenzek/duckstation#2357]
**Is your feature request related to a problem? Please describe.**
enable an option so i can "link" my PEC (PSX Emulation Cheater) program to the emulator. make duckstation to "emulate" the old PEC plug in to take codes or deactivate codes like the old plug in had.

**Describe the solution you'd like**
emulate the old plug in. the old plug in allowed to select a video plug in and acted as a "bridge" to allow codes to be injected into the gpu. it never processed graphics so i guess its not that difficult.

**Describe alternatives you've considered**
adding millions of codes for each game for each region manually... yea that is not happening.

**Comment by foxsevent** [comment]
Yeah I don't see that happening, for one PEC is old as fuck with way outdated cheat database, two Duckstation comes with cheats for most games already if not you can just google the game shark cheat you want throw it into a text file (with proper formatting)  and you're done, this is far simpler then having the dev write in the archaic plugin support this would require.

**Comment by overlordchaos** [comment]
> Yeah I don't see that happening, for one PEC is old as fuck with way outdated cheat database, two Duckstation comes with cheats for most games already if not you can just google the game shark cheat you want throw it into a text file (with proper formatting) and you're done, this is far simpler then having the dev write in the archaic plugin support this would require.

duckstation cheat management is garbage compared how to the archaic PEC interface works. not to mention its fully editable. before blasting old software of how "old-archaic and useless it is" make sure your new garbage is up to standards.

**Comment by andercard0** [comment]
> 
> 
> > Yeah I don't see that happening, for one PEC is old as fuck with way outdated cheat database, two Duckstation comes with cheats for most games already if not you can just google the game shark cheat you want throw it into a text file (with proper formatting) and you're done, this is far simpler then having the dev write in the archaic plugin support this would require.
> 
> duckstation cheat management is garbage compared how to the archaic PEC interface works. not to mention its fully editable. before blasting old software of how "old-archaic and useless it is" make sure your new garbage is up to standards.

If, your 'standards' arent't in line with the scope of this project, simply stay with your archaic turd and do not use Duckstation. 
Soon, as soon as the developer himself see it your requests will be closed as invalid as it is and maybe, due to your non-polite arguments you'll be blocked to create new issues here as well. 
Congrats!

**Comment by foxsevent** [comment]
> > Yeah I don't see that happening, for one PEC is old as fuck with way outdated cheat database, two Duckstation comes with cheats for most games already if not you can just google the game shark cheat you want throw it into a text file (with proper formatting) and you're done, this is far simpler then having the dev write in the archaic plugin support this would require.
> 
> duckstation cheat management is garbage compared how to the archaic PEC interface works. not to mention its fully editable. before blasting old software of how "old-archaic and useless it is" make sure your new garbage is up to standards.

Reading and understanding aren't your strong points are they, I refereed to the plugin support hat PEC needs as archaic as only ePSXe and PCSXR still use it despite no more plugins are being developed and most PS1 emu devs moved on to simpler and better systems, I also siad that PEC cheat databases is outdated cause it wasn't updated in many many years.
Nor once did I call PEC garbage or useless. if you wanna keep using then keep using it with emulators it support, don't expect something this old being coded into Duckstation.

**Comment by overlordchaos** [comment]
> > > Yeah I don't see that happening, for one PEC is old as fuck with way outdated cheat database, two Duckstation comes with cheats for most games already if not you can just google the game shark cheat you want throw it into a text file (with proper formatting) and you're done, this is far simpler then having the dev write in the archaic plugin support this would require.
> > 
> > 
> > duckstation cheat management is garbage compared how to the archaic PEC interface works. not to mention its fully editable. before blasting old software of how "old-archaic and useless it is" make sure your new garbage is up to standards.
> 
> Reading and understanding aren't your strong points are they, I refereed to the plugin support hat PEC needs as archaic as only ePSXe and PCSXR still use it despite no more plugins are being developed and most PS1 emu devs moved on to simpler and better systems, I also siad that PEC cheat databases is outdated cause it wasn't updated in many many years.
> Nor once did I call PEC garbage or useless. if you wanna keep using then keep using it with emulators it support, don't expect something this old being coded into Duckstation.

you did. read the first line "for one PEC..." second I HAVE manually updated the database, from sites that updated it trough many years + my own codes. PEC has worked for me for over 20 years. duckstation cheat support is near useless. no idea why you cannot have a OPTION to use PEC with duckstation. as optional nor forced. but fine i will keep using my archaic pec and emulators.

**Comment by CookiePLMonster** [comment]
> duckstation cheat support is near useless

I wish GitHub issues didn't have a character limit so you could say what is the issue about Duck's cheat sup... _oh wait_.

**Comment by overlordchaos** [comment]
> > duckstation cheat support is near useless
> 
> I wish GitHub issues didn't have a character limit so you could say what is the issue about Duck's cheat sup... _oh wait_.

try 5 minutes PEC then the duckstation cheat system. then you will know why duckstation cheat system is awful. i dont need to write 500 pages of reasons why one is superior to the other. many emulators have shitted on pec. and none of them exists in the present. yet PEC keeps having people using it daily. i guess duckstation will follow the same path as its predecessors that refused to support PEC and shit on its name.

**Comment by PugsyMAME** [comment]
500 pages of reasons? As far as I'm aware there is only one thing that PEC cheater can do that can't be currently done in Duckstation and that's modifier codes.

Duckstation cheat support is far superior to what you can do in PEC, that's a simple fact.
I can list several things that you can do with DS format cheats that you can't with PEC cheater, but I see no point in wasting time listing or explaining as you've made your mind up already.

**Comment by overlordchaos** [comment]
> 500 pages of reasons? As far as I'm aware there is only one thing that PEC cheater can do that can't be currently done in Duckstation and that's modifier codes.
> 
> Duckstation cheat support is far superior to what you can do in PEC, that's a simple fact.
> I can list several things that you can do with DS format cheats that you can't with PEC cheater, but I see no point in wasting time listing or explaining as you've made your mind up already.

20 years of no problems usage of PEC VS duckstation a garbage emulator with a nice UI and nice upgrades to the graphics/forgetting about plugs in usage. nothing else. bleem perfected emulation on 1998. so duckstation is 23 years behind on emulation AND dropping support for PEC.

**Comment by Nucleoprotein** [comment]
Duckstation cheat system is **state of art**, is best cheat system for PSX games you can get.
This whole conversation is over: "i'm familiar with PEC and do not want to learn nothing new" ... but you can import standard cht files? so what's is the problem? This should be rejected and locked, as PEC is dead.

**Comment by overlordchaos** [comment]
> Duckstation cheat system is **state of art**, is best cheat system for PSX games you can get.
> This whole conversation is over: "i'm familiar with PEC and do not want to learn nothing new" ... but you can import standard cht files? so what's is the problem? This should be rejected and locked, as PEC is dead.

PEC is not dead, maybe in development but that happen around 2005 so are old news. .cht files are not used on pec is a gigantic game list witch i doubt duckstation garbage cheat system would be able to handle without crashing 50% of the times used.
your emulator is garbage and you threat it as if it where the first of its kind and breaking new ground.

bleem, the latest version runned about 90% of all the ps1 games without no issues before it was discontinued by a sony lawsuit. and that was around 2000. so duckstation is 21 years behind still.

**Comment by Nucleoprotein** [comment]
> bleem, the latest version runned about 90% of all the ps1 games 

This is stupid, can somebody lock this thread?

**Comment by andercard0** [comment]
> 
> 
> > bleem, the latest version runned about 90% of all the ps1 games
> 
> This is stupid, can somebody lock this thread?

Unfortunately not! I would love to we'll need to wait for sten.

**Comment by stenzek** [comment]
Locked. It's a free application, have realistic expectations, it's not our job to fulfill your rediculious requests.
