### ISSUE TITLE
Rungo's stage plays too fast - Battle Arena Toshinden [SCUS-94003]

### ISSUE THREAD

**Issue by Phantasm90** [stenzek/duckstation#2362]
**Game details**
[SCUS-94003 Battle Arena Toshinden (USA)]

**Description of the issue / bug**
When you play on Rungo's stage the game plays about twice as fast for some reason and it makes it hard to play, i haven't noticed this problem with the other characters stages

**Steps to reproduce**
Just play until you get to fight against Rungo, i think it's the stage itself that makes the game play too fast

**Hardware/software**
Windows 7 Ultimate
HP Pavillion dv4 intel i5 2,27GH
D3D11

**Emulator version**
0.1-4401-g0c4629bd (master)

https://user-images.githubusercontent.com/37343312/124391108-653b8680-dcc5-11eb-82f4-0793b69b84a0.mp4

**Comment by stenzek** [comment]
Does it run any slower with interpreter? This game is really timing sensitive

**Comment by Phantasm90** [comment]
No, it runs just the same, though i noticed that when the sand mountain in the background is in clear view, the game runs at normal speed, with or without Interpreter

![SCUS-94003_2021-07-05_00-23-14](https://user-images.githubusercontent.com/37343312/124413762-af555400-dd27-11eb-8905-4ad55deaf542.png)

**Comment by stenzek** [comment]
GTE timings are enough to bring this down to 30fps. I have it on a branch, need to finish the recompiler support, and reduce the perf hit.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/30db081a645481cb40b74730ba3f5dcfe12e19c4

**Comment by Phantasm90** [comment]
Great, thanks. by the way can you add "force recompiler icache" in the compatibility settings for "PSEXE Toushinden (Japan)", i already did by myself but it might be needed to have it by default

![PSEXE Toushinden (Japan)](https://user-images.githubusercontent.com/37343312/127243111-6758698d-852e-4622-9c28-5f62e0850a1f.png)
