### ISSUE TITLE
Addie no Okurimono - To Moze from Addie (Japan) suffers from flickering graphics

### ISSUE THREAD

**Issue by Hector-Eli-Wood** [stenzek/duckstation#2363]
**Game details**
Game: Addie no Okurimono - To Moze from Addie (Japan) 
Serial number: SCPS-10126
Emulator version - Duckstation 0.1-440-g0c4629bd

**Description of the issue / bug**

There is a flickering effect during the opening video, on the title screen and during gameplay. This occurs regardless of settings or renderer. Although using the software renderer makes the flickering much worse. It should be most noticeable on the title screen. 

![SCPS-10126_2021-07-05_02-17-24](https://user-images.githubusercontent.com/86927936/124395928-3b787300-dd4a-11eb-8102-080b73a45528.png)

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
No

2. Which controller backend are you using in general settings
Analog controller

**Steps to reproduce**
Start the game. It will be immediately obvious as soon as the first video begins. 

**Enhancements information**
Tested with all settings default and with all enhancements off.

**Hardware/software**
Tested with both.

**Emulator version**
Emulator version - Duckstation 0.1-440-g0c4629bd

**Additional context**
I have tested the game in both standalone Mednafen and Beetle PSX. The flickering does not occur in either. I wasn't able to test on real hardware. 

My own computer specs.

![Capture](https://user-images.githubusercontent.com/86927936/124395980-72e71f80-dd4a-11eb-8bfb-3f9fea92bb29.PNG)

**Comment by stenzek** [comment]
This seems to require perfect bit-accurate blending, which currently isn't possible with the hardware renderer. I've forced software for now in https://github.com/stenzek/duckstation/commit/2f2dc9cf72925590793ea771acfe82b252937377, but I'll come back to this when I look at switching the hardware renderers to use 16-bit render targets.

**Comment by Hector-Eli-Wood** [comment]
Sure no problem. However this change has fixed the flickering but introduced a different issue where these garbage lines appear during the opening video. 

![Capture](https://user-images.githubusercontent.com/86927936/124472905-06b7fa80-dde2-11eb-9957-bcac3a257802.PNG)

**Comment by stenzek** [comment]
Unrelated issue. I'll check it when I have time.
