### ISSUE TITLE
Enable force analog mode on reset in controller dualshock

### ISSUE THREAD

**Issue by fox140cv** [stenzek/duckstation#2364]
**Game details**
SLES_008.41 Oddworld - Abe's Oddysee (Spain)
SLES_015.05 Oddworld - Abe's Exoddus (Spain) (Disc 1)
SLES_027.54 Vagrant Story (Europe) with PAL/NTSC Selector

**Description of the issue / bug**
In most games you can have forced analog mode enabled when restarting with the dualshock controller and the controller responds fine except for these that I detail:
-Abes oddysee works fine in menus, but when you enter a new game, a message appears stating that no driver was found.
-Abes Exoddus, if the option to force the analog mode is activated, the use of the D-pad in the analog does not work. This happens to some other game but now I don't remember
-Vagrant Story, in this particular case applying the PAL / NTSC Selector patch that was used in the original console to change the region, no button works when the option is activated.

**Enhancements information**
Tested with all settings default and with all enhancements off.

**Hardware/software**
CPU intel i5 6600k
Nvidia gtx 1060
windows 10 x64

**Emulator version**
0.1-4401-g0c4629bd

**Additional context**
In previous versions there was the DisableAnalogModeForcing option which is still present in the libretro core and resolve the problem especially in the case of the vagrant story

![Captura de pantalla (42)](https://user-images.githubusercontent.com/79443698/124402309-bda76e00-dd2f-11eb-809f-5f43ae06d934.jpg)
![Captura de pantalla (43)](https://user-images.githubusercontent.com/79443698/124402327-d879e280-dd2f-11eb-9f0f-7a83fe543f41.jpg)

**Comment by foxsevent** [comment]
Yeah, both Abe games don't support analog controls and most often these "patched" do neither.
Which means that your pad ain't gonna work in analog mode so disable it, and if you must have analog control enable "use analog sticks for dpad in digital mode"

**Comment by fox140cv** [comment]
It is true as in many others and nevertheless in recent versions of duckstation they have been solved being able to play with this option enabled without having to resort to the configuration of each game.
In previous versions you could choose disable analog mode forcing in each game but this option seems to be not available.

**Comment by foxsevent** [comment]
Okay, im not understating something here, if you don't want this option on then why don;t you disable it by unticking it?

**Comment by fox140cv** [comment]
There are solutions, we agree, what I suggest is that all the games that do not have dualshock compatibility work for me less these that I comment, and I have counted more than 30.
The idea is to leave it configured from the application.
The option map the analog button in controller settings it is a workaround but I use the original dualshock 2 and 3 and the buttons are busy
If it can't be fixed, I'll set it up with an alternative that we talked about

**Comment by foxsevent** [comment]
> There are solutions, we agree, what I suggest is that all the games that do not have dualshock compatibility work for me less these that I comment, and I have counted more than 30.
> The idea is to leave it configured from the application.
> The option map the analog button in controller settings it is a workaround but I use the original dualshock 2 and 3 and the buttons are busy
> If it can't be fixed, I'll set it up with an alternative that we talked about

I suppose, we will see what sten will say, regardless your solution won't won't work with your Vagrant Story as that game does support analog controls, it's just that hacked in selector which doesn't work in analog mode.

**Comment by stenzek** [comment]
Romhacks aren't supported. You're on your own to work out any issues.

Disabling analog mode forcing happens when the entry in the game database does not have analog controller listed. If oddworld doesn't support it, it should be removed here.
