### ISSUE TITLE
Button assignment problem

### ISSUE THREAD

**Issue by dieselpower1** [stenzek/duckstation#2368]
**Controller Troubleshoot Report**
Hi I have a problem. I am unable to assign the L2 and P2 buttons on the Defender Vortex controller. All other buttons are assigned without problems. For example, I tried to assign buttons in the old epsxe emulator, all buttons are assigned without problems, including L2 and P2. I do not use any additional programs for the controller, I do not use Steam

**Emulator version**
0.1-4315-gf7587eae

Thanks

**Comment by stenzek** [comment]
It may need a SDL game controller db file: https://github.com/gabomdq/SDL_GameControllerDB/

Or, use dinput.

But otherwise I can't do anything, since I don't have this controller.
