### ISSUE TITLE
We need crt rendering filter

### ISSUE THREAD

**Issue by Ninaadark18** [stenzek/duckstation#2370]
Why don't you bring us crt old tv (composite, S-Video and components cables) for the standalone emulator.
and add a one-click options for (Like real hardware, normal emulation and high-end emulation) because the ps1 had a lot of 2d games and they look better with these options

[Cv:Sotn](https://twitter.com/CRTpixels/status/1408451743214616587?s=20) 
[Cv:Sotn Richter](https://twitter.com/CRTpixels/status/1408838224328466441?s=20) 
[FF:Origins](https://twitter.com/CRTpixels/status/1407368025066590217?s=20) 
and even the 3D games looks better 
[Vagrant story](https://twitter.com/CRTpixels/status/1394717785088045058?s=20)

**Comment by stenzek** [comment]
Considering this is a free application, the only things "needed" are what I find interesting. This request is kinda rude, and you didn't even follow the template.

**Comment by stenzek** [comment]
Also, not only do demanding requests like this make me even less likely to work on a feature, I think crt filters look terrible personally, and have zero motivation to add them otherwise. This isn't my job, I work on what I find fun ;)

**Comment by Ninaadark18** [comment]
> Also, not only do demanding requests like this make me even less likely to work on a feature, I think crt filters look terrible personally, and have zero motivation to add them otherwise. This isn't my job, I work on what I find fun ;)

Sorry if you find my words offending.
Btw the template you mentioned didn't ahowed up for me as previous so I wrote what I like because it didn't aproch.
I enjoy what you work on and it was a mistake to ask you something, thanks.

**Comment by stenzek** [comment]
Requests are fine, like half of the issues on here are requests. It was the demanding nature and lack of template which annoys me.

**Comment by Ninaadark18** [comment]
> Requests are fine, like half of the issues on here are requests. It was the demanding nature and lack of template which annoys me.

I wonder where is the lack of template that annoys you.. if you read the template it's so simple and I explained everything in text and gave links to comparesing pics insted of download them then upload them here because there with their respected owner and fellow discussers

**Comment by BailShamber** [comment]
@Ninaadark18 It's probably a language barrier, your title sounded demanding "We need...etc" and starting the issue with "why don't you..." sounds demanding as well.
best way to go about it is to type the feature request like a robot, like this:

Title: "[Feature request]: CRT shader"

and use the template with simple and short answers to the questions in it, without stuff like "why don't you" and such.
