### ISSUE TITLE
Sortable columns in Cheat Manager/Memory Scanner?

### ISSUE THREAD

**Issue by aybe** [stenzek/duckstation#2371]
**Is your feature request related to a problem? Please describe.**

It's difficult to analyze many values in memory at once.

**Describe the solution you'd like**

It would be great if both data grids could be sorted by columns.

**Describe alternatives you've considered**

Right now, you must add them in the order you want them to be, pretty boring.

**Additional context**

<img width="578" alt="duckstation-qt-x64-ReleaseLTCG_2021-07-05_20-49-33" src="https://user-images.githubusercontent.com/1537591/124509570-82aa4680-ddd2-11eb-89b5-27fe09583c62.png">

**Comment by stenzek** [comment]
Let's keep track of these in #2179.

**Comment by PugsyMAME** [comment]
Added the sort functionality along with some other changes to memory scanner:-

https://github.com/stenzek/duckstation/pull/2478

![image](https://user-images.githubusercontent.com/18102600/128509976-68dd47b2-1903-42a5-bb89-83299fa581e8.png)

**Comment by aybe** [comment]
Amazing!
