### ISSUE TITLE
Being able to view a memory region in Cheat Manager/Memory Scanner

### ISSUE THREAD

**Issue by aybe** [stenzek/duckstation#2372]
**Describe the solution you'd like**

It would be great if we can see real-time changes in a memory region, like the following:

<img width="596" alt="NO$PSX_2021-07-05_20-51-16" src="https://user-images.githubusercontent.com/1537591/124509806-d3ba3a80-ddd2-11eb-868e-9bd50af140f6.png">

**Comment by stenzek** [comment]
Let's keep track of these in #2179.
