### ISSUE TITLE
Fast Forward mute option

### ISSUE THREAD

**Issue by Hyze01** [stenzek/duckstation#2373]
**Is your feature request related to a problem? Please describe.**
The game volume set by the hotkeys is different from the one set by the settings, volume up/down changes fast forward audio too even if you are with fast forward turned off.

**Describe the solution you'd like**
A button to "Mute Fast Forward" or a way to keep the Fast Forward volume different from the normal volume.

**Describe alternatives you've considered**
I tried binding mute and fast forward toggle to (Space key), but this way mute won't work.

**Additional context**

**Comment by stenzek** [comment]
This is already a thing. Set the fast forward volume to 0%.
