### ISSUE TITLE
(Android) Tilt controls

### ISSUE THREAD

**Issue by Luggy7** [stenzek/duckstation#2376]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Is your feature request related to a problem? Please describe.**
Can be difficult to manage lots of buttons on touchscreen

**Describe the solution you'd like**
Left and right tilt of the device to be assigned to buttons such as the shoulder buttons or left and right analogue sticks for racing games especially

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by SecularSteve** [comment]
I can see it working for games with Analogue support, but tilting using the D-Pad as an input source is going to drive people mad.
