### ISSUE TITLE
Ability to preload multi-disc game images

### ISSUE THREAD

**Issue by yaywalter** [stenzek/duckstation#2378]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Is your feature request related to a problem? Please describe.**
My games are stored on a slow external hard drive, and the preload option only works for single-disc games. Additionally, Duckstation assumes a game is multi-disc if loaded via an m3u file, even if it's a single-disc game.

**Describe the solution you'd like**
An additional option to preload multi-disc games to RAM would be the preferred solution, since I understand that some people might not want to preload multi-disc games to RAM due to the time it takes to preload and/or not having enough RAM to do so.

**Describe alternatives you've considered**
Checking whether games loaded via m3u contain multiple discs or not would partially address the issue, though it's less of an alternative solution to my feature request and more of a fix to a related issue.

**Additional context**
![MultiDiscLoad](https://user-images.githubusercontent.com/6369132/124887021-68bb6000-df9a-11eb-9457-e4754735752d.png)

**Comment by stenzek** [comment]
Working as intended. The way preloading works is it replaces the original image with a memory image, so the extra discs are lost. Therefore, the only way to handle it would be to preload *all* discs into memory, and that is getting into gigabytes of memory territory.

> Additionally, Duckstation assumes a game is multi-disc if loaded via an m3u file, even if it's a single-disc game.

Then don't use a playlist? Playlists are treated as multi-CD images internally.

**Comment by yaywalter** [comment]
I'm aware that loading all the discs into RAM would use gigabytes, my request was for the ability to do precisely that since I have the RAM to spare. As for the m3u thing, I have my own reasons for using them... but I understand that most people won't be using them for single-disc games, just thought I'd point it out.

**Comment by foxsevent** [comment]
Yeah if you have a slow HDD why would you want to wait 5min for the 4gb image to load into ram.
Preload to RAM is really just a nitche case for most users it's completely unnecessary.
Such cases are when loading games from a network storage since it's connection and latency can be unreliable or if you have a HDD with very aggressive spin down cycles which can cause the occasional hitch.
But if I can run games of 10mbs pendrive then most HDD won't have issues.

But the real issue would be android users using this feature on potato phone's with 2gb of ram trying to preload 4gb pbp which are also multi disc format then coming to discord to complain or 1 star the app on app store m

**Comment by yaywalter** [comment]
When I said "slow drive", it was shorthand for HDD with very aggressive spin down cycles. There's programs out there like NoSleepHD which can prevent it from spinning down, sure, but I don't always have my game drive connected so it's easy to forget to make sure to have something like that running.

As for the Android thing, I understand that for most users, only preloading a single disc would be the preferred behavior (if they even want preloading at all)... I just would like there to also be an option for multi-disc preloading.

**Comment by stenzek** [comment]
> I'm aware that loading all the discs into RAM would use gigabytes, my request was for the ability to do precisely that since I have the RAM to spare.

Tell that to android users who will go into a raging fit when the app kills itself for using too much memory on their 2gb phone.

**Comment by foxsevent** [comment]
> > I'm aware that loading all the discs into RAM would use gigabytes, my request was for the ability to do precisely that since I have the RAM to spare.
> 
> Tell that to android users who will go into a raging fit when the app kills itself for using too much memory on their 2gb phone.

You could tuck that extra settings in advanced settings and only on desktop.
But yeah it seriously isn't that big of a deal, how often do you swap discs to necessitate 2-5min preloading to RAM. Or 10+ min if compressed.

**Comment by yaywalter** [comment]
> 
> 
> > I'm aware that loading all the discs into RAM would use gigabytes, my request was for the ability to do precisely that since I have the RAM to spare.
> 
> Tell that to android users who will go into a raging fit when the app kills itself for using too much memory on their 2gb phone.

Does the Android version even have a preloading option? Unless there's a strict goal of perfect feature parity between the PC and Android versions, it seems like the kind of thing that wouldn't even be particularly useful on mobile platforms. But if it does have the option to preload single-disc games, I'm not asking for its behavior to change and suddenly start consuming way more RAM than it currently does. I'm asking for a separate multi-disc preload option, one that could perhaps be disabled/hidden unless it detects that the user has a sufficient amount of RAM.

> 
> 
> > > I'm aware that loading all the discs into RAM would use gigabytes, my request was for the ability to do precisely that since I have the RAM to spare.
> > 
> > 
> > Tell that to android users who will go into a raging fit when the app kills itself for using too much memory on their 2gb phone.
> 
> You could tuck that extra settings in advanced settings and only on desktop.
> But yeah it seriously isn't that big of a deal, how often do you swap discs to necessitate 2-5min preloading to RAM. Or 10+ min if compressed.

The goal isn't to improve disc swapping times, it's to prevent the need to access the hard drive even while using just one disc of a multi-disc game... i.e Gran Turismo 2 which is multi-disc, but where most of my time would be spent using just the Simulation Mode disc. You can say it's not that big of a deal, but that applies just as equally to the currently existing single-disc preload option.

**Comment by stenzek** [comment]
> Does the Android version even have a preloading option? Unless there's a strict goal of perfect feature parity between the PC and Android versions, it seems like the kind of thing that wouldn't even be particularly useful on mobile platforms.

Yes, and yes, it's the same code. It is useful there as SD cards can have latency spikes.

There is another alternative, don't use playlists and switch games from the list, and preloading will work fine. That's the intended workflow anyway. Not to mention quicker preloading times to begin with, since it only needs to read one disc.

I'm not going to change how it's implemented, but if you want to, pull requests are welcome.

**Comment by yaywalter** [comment]
That's not my ideal workflow, but fair enough.
