### ISSUE TITLE
All FMVs in Blue's Clues - Blue's Big Musical (Australia) are silent

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#238]
Maybe the same problem as Akuji the Heartless. Steve looks just as confused as I.

![SLES-03570_2020-04-07_01-53-53](https://user-images.githubusercontent.com/31968468/78578551-08a7ac80-7873-11ea-94bd-457fcc3d579d.png)

**Comment by kurayami6** [comment]
Must be a different problem. Still silent as of the latest version.

![Capture](https://user-images.githubusercontent.com/31968468/80529466-d8b77900-89da-11ea-81fb-8bede13f141e.PNG)

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/0710e3b6d384526ed939f742f8f657623bb354bb

**Comment by kurayami6** [comment]
The game is no longer silent but there's a hiss as the audio track starts. This happens in both the NTSC and PAL versions. Listen at the 3 second mark.

[SLES-03570_2020-07-02_05-19-32.zip](https://github.com/stenzek/duckstation/files/4861964/SLES-03570_2020-07-02_05-19-32.zip)

**Comment by kurayami6** [comment]
Apparently the audio hiss happens on real hardware as well.
