### ISSUE TITLE
Fan Noise

### ISSUE THREAD

**Issue by shiyorin** [stenzek/duckstation#2380]
**Game details**
[Serial Code, Region]
[i.e SLUS-00404 Ace Combat 2 (USA)]

**Description of the issue / bug**
It made my windows fan noises really loud whenever I operate the game, I don't know why and how to fix or ease it
I use GPU Renderer-Vulkan because when I use other, it will stutter when I operate the game
My proccesor is AMD Ryzen 5 4600H 

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
Just playstation bios scph1001 bin file 
2. Which controller backend are you using in general settings
XLinput

**Comment by stenzek** [comment]
An emulator or application has no control over fan speeds. You should use the Direct3D renderer, and make sure it's not running with a discrete GPU if your system contains one.
