### ISSUE TITLE
Input Mapping Bug

### ISSUE THREAD

**Issue by stoniemahonie** [stenzek/duckstation#2386]
I set the "analog" button in the controller configuration on mouse button 3 (mid-wheel click).

Then i start a game from a frontend with the -fullscreen -batch commands.

Ingame i can't use mouse button 3 to switch the analog status but instead it is mapped to mouse button 2 (right mouse button).

If i use duckstation without a frontend, no problem, mouse button 3 works as mapped.

I hope it is clear what i meant, if not i will try to explain it better.

**Comment by stenzek** [comment]
Issue template not completed.
