### ISSUE TITLE
Several games crashes randomly in ARM-based builds

### ISSUE THREAD

**Issue by Raypuia** [stenzek/duckstation#2387]
**Game details**
SLUS-00461, Xevious 3D/G+ (USA)
SLUS-00690, G. Darius (USA)
SLUS-00548, Street Fighters EX Plus Alpha (USA)
SLUS-00561, Mega Man X4 (USA)
SLUS-01334, Mega Man X5 (USA)

**Description of the issue / bug**
Most of the games mentioned above crashes very randomly on ARM devices, sometimes like 15secs after runtime or 30secs.

Even if running then in CPU Interpreter it stills crash.

**Steps to reproduce**
[Try to provide as much detail as possible to reproduce the issue]
It happens on all known dumps, it crash DuckStation after a few seconds of runtime.

**Hardware/software**
Redmi Note 8 [OpenGL ES 3.0/Vulkan 1.0]

**Emulator version**
Lastest git

**Comment by stenzek** [comment]
The only crashes I've seen reported from this device are running Vulkan, and it's during presentation (likely when apps were switched).

There's clearly something else going on here, I don't get any crashes in the mega man games on my SD845. Maybe try clearing data to reset settings, and check the hashes of your dumps.
