### ISSUE TITLE
CPU Debugger Read/Write Breakpoints

### ISSUE THREAD

**Issue by Colmines92** [stenzek/duckstation#2390]
**Is your feature request related to a problem? Please describe.**
Right now Duckstation is a very powerful and feature rich emulator. It's included cpu debugger is one of these powerful features, but right now it only supports execution breakpoints. It would be really great that it supported read/write breakpoints as well.

**Describe the solution you'd like**
^^ To implement read/write breakpoints, if possible.

**Describe alternatives you've considered**
^^

**Additional context**
^^

**Comment by stenzek** [comment]
Please use https://github.com/stenzek/duckstation/issues/2179 for debugger requests.
