### ISSUE TITLE
Controller mapping misaligned for analog button, port 1

### ISSUE THREAD

**Issue by stoniemahonie** [stenzek/duckstation#2392]
**Game details**
**[any, any]**
[i.e SLUS-00404 Ace Combat 2 (USA)]

**Description of the issue / bug**
[Describe what you are seeing and/or hearing during gameplay]

"Analog" button in controller settings for Port 1 is mapped to "Mouse/Button3"

Ingame, the mapped "Mouse/button3" won't work , but instead "Mouse/button2" works for the mapped button. Vice versa, if "Mouse/Button2" is mapped to the "analog" button, "Mouse/Button3" works instead if used from the command line.

When playing a game via Duckstation with the normal Windows-Gui, it works as mapped.

I'm using a Dualshock 4 with DS4 Windows. The PS button is configured as Mousebutton3 so i can use it in Duckstation like a regular old Dualshock button. It is also a very great feature being able to change the analog status on-the-fly.

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?

**- DS4Windows**

2. Which controller backend are you using in general settings

**- Xinput**

**Steps to reproduce**
Map the Mouse Button 3 to analog in controller settings, port 1. Then use Duckstation from the commandline with "-fullscreen -batch"

Now use mouse button 3 and it wont work.

**Enhancements information**
[Make sure they are all turned off before report]

**Hardware/software**
Desktop, AMD Ryzen 3700x, Windows 10 21H1 - 19043.1083
Nvidia GTX 1060 - D3D11

**Emulator version**
0.1-4422-g79dcc9d (dev)

**Additional context**
[Add any other context about the problem here]

**Comment by stenzek** [comment]
This doesn't make any sense to me. Why are you binding it to mouse 3? DS4Windows is not necessary, just use the SDL controller interface, and the PS button will be bindable as a controller button.

But regardless, the actual third mouse button works as expected for me. So this sounds like an interoperability issue with DS4Windows, which again, is not necessary.

**Comment by stoniemahonie** [comment]
Despite my personal preference on why/how using ds4windows, you can also use sdl and configure the keyboard/mouse for duckstation and if you map mousebutton 3 to analog in port 1 and press it while using duckstation from the commandline, you have no function while the game runs on that button. But mbutton2 (right mouse button) works, so there must be a typo in the code bc it does not work as mapped when using from command line.

This is the command line i use for instance:

C:\Duckstation\latest\duckstation-nogui-x64-ReleaseLTCG.exe "F:\G-Police.PBP" -fullscreen -batch

But if i use the duckstation gui it works. So there is something wrong. Hope it makes sense now.

**Comment by stenzek** [comment]
> Despite my personal preference on why/how using ds4windows

DS4Windows is not supported, and I am not installing it. I can't support things which I do not use myself. It might work, but I can't provide any assistance or fixes (i.e. use at your own risk).

> C:\Duckstation\latest\duckstation-nogui-x64-ReleaseLTCG.exe "F:\G-Police.PBP" -fullscreen -batch

You didn't mention that you were switching between nogui and qt in the initial report. The bindings between the two frontends are not necessarily compatible, due to different input sources. There's no real reason to use nogui on Windows anyway, Qt supports all the same command line arguments, and you can enable the fullscreen UI within it.

I've pushed a change to remap the indices in https://github.com/stenzek/duckstation/commit/134056bb9387c95f3dd4dc7cc34bdc8b60b3293d, but there will be other key names which differ between the two frontends. Stick with one, don't switch between them.

**Comment by stoniemahonie** [comment]
I did some more testing, you can map the mousebutton 2/3 to any action and tick the show controller input in the display settings. I used the up button. When using mouse buttons 1,4 and 5 it works and the Controller input OSD shows "up". Only button 2 and 3 are reversed, but only when using the nogui exe. This is without ds4windows and only the keyboard and mouse. 

Also loaded up the profile keyboard (no numpad) and mapped "up" to mousebutton3 and its the same result.

mind you, its just reversed when using duckstation-nogui-x64-ReleaseLTCG.exe, not when using duckstation-qt-x64-ReleaseLTCG.exe.

**Comment by stoniemahonie** [comment]
Well i did mention that i was using duckstation from the commandline, but you are right, i should have written that i used the nogui exe, sorry. 

Thank you for looking into it :)
