### ISSUE TITLE
Garbage on edges of the screen/triangles offset in OpenGL renderer

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#24]
On the right side of the screen and bottom left. After a while they go away and the sides of the screen start shaking. 

![Capture](https://user-images.githubusercontent.com/31968468/74405096-6a095b80-4e80-11ea-8805-88c52231fe4a.PNG)

**Comment by stenzek** [comment]
Does toggling "Linear Filtering" under display change anything?

Basically, wondering whether it's a GPU issue or just a display issue due to upscaling.

**Comment by stenzek** [comment]
I've seen some similar issues in other games which are only present in OpenGL too. If you're using Windows, try the DX11 renderer.

**Comment by kurayami6** [comment]
I'm using Windows 7. I tried it with the D3D11 renderer and it seems to fix it.

**Comment by kurayami6** [comment]
Using OpenGL, King's Field 2 has the same problem.

![Capture](https://user-images.githubusercontent.com/31968468/74437761-cab68980-4ebc-11ea-9194-9b0dfad7a65c.PNG)

**Comment by stenzek** [comment]
Okay. Good that it's the same issue I'm seeing and can reproduce it. Will investigate when I have time.

**Comment by stenzek** [comment]
In a few cases where there was differences around the edges between D3D and OpenGL, the outputs match up now.

**Comment by stenzek** [comment]
I think this has all been solved now - please re-open if the issue is persisting.
