### ISSUE TITLE
[X86_64 GNU/Linux, DuckStation NOGUI] Buffer underflows during BIOS boot sequence/animation

### ISSUE THREAD

**Issue by vanfanel** [stenzek/duckstation#2404]
**Description of the issue / bug**
Audio dropouts are apparent during the bootup animation using the software renderer on my X86_64 laptop computer from last year (HW info later).
This is what the console log says:

```
[    0.5065] I/GL::ContextEGL: Got version 4.5 (Core)
[    0.5096] I/GL::Context: Created a OpenGL context
[    0.5123] I/GL::Context: GL_VENDOR: X.Org
[    0.5123] I/GL::Context: GL_RENDERER: AMD STONEY (DRM 3.35.0, 5.4.0-73-generic, LLVM 10.0.0)
[    0.5123] I/GL::Context: GL_VERSION: 4.5 (Core Profile) Mesa 20.0.8
[    0.5124] I/GL::Context: GL_SHADING_LANGUAGE_VERSION: 4.50
[    0.5124] V/OpenGLHostDisplay: Using GLES2 draw path: no
[    0.5124] V/OpenGLHostDisplay: Using PBO for streaming: yes
[    0.5211] E(LoadTexture): Failed to open texture resource 'resources/logo.png'
[    0.7045] E(LoadTexture): Failed to open texture resource 'resources/logo.png'
[    0.8568] I/NoGUIHostInterface: Host display initialized at 1366x768 resolution
[    0.8570] I/SDLControllerInterface: Controller 0 inserted
[    0.8573] I/SDLControllerInterface: Opened controller 0 (instance id 0, player id 0): X360 Controller
[    0.8574] I/SDLControllerInterface: Rumble is supported on 'X360 Controller' via gamecontroller
[    0.8574] I/ControllerInterface: Host controller 0 connected, updating input map
[    0.8574] I/SDLControllerInterface: Controller 0 deadzone size set to 0.250000
[    0.8575] I/SDLControllerInterface: Controller 0 deadzone size set to 0.250000
[   11.7150] I/HostInterface: Boot Filename: <BIOS/Shell>
[   11.7151] I/HostInterface: Creating 'Cubeb' audio stream, sample rate = 44100, channels = 2, buffer size = 2048
[   11.7235] I/CubebAudioStream: Minimum latency in frames: 1102
[   11.7235] W(OpenDevice): Minimum latency is above buffer size: 1102 vs 1024, adjusting to compensate.
[   11.8154] I/System: Console Region: NTSC-U/C (US, Canada)
[   11.8186] I/Common::MemoryArena: File mapping name: duckstation_1552
[   11.8189] I/Bus: RAM is 2097152 bytes at 0x7f012c80e000
[   11.8219] I/GPUBackend: GPU thread started.
[   11.8225] I/Bus: Fastmem base: 0x7effffffe000
[   11.8357] I/CDROMAsyncReader: Read thread started with readahead of 8 sectors
[   11.8366] I/MemoryCard: Loaded memory card from /home/manuel/.local/share/duckstation/memcards/shared_card_1.mcd
[   11.8751] E(SetScreensaverInhibit): Unknown type: 7
[   11.8752] E(SuspendScreensaver): Failed to suspend screensaver.
[   11.8757] V/AudioStream: Audio buffer underflow with no samples, added 826 frames silence
[   11.8758] I/CommonHostInterface: Refresh rate: Host=59.999866hz Guest=59.817333hz Ratio=1.003052 - can sync
[   11.8758] I/CommonHostInterface: Target speed: 100.305153%
[   11.8758] I/CommonHostInterface: Syncing to audio and video
[   11.8758] I/CommonHostInterface: Max display fps: 0.000000 (displaying all frames)
[   11.8758] I/CommonHostInterface: Audio input sample rate: 44234 hz
[   11.8759] I/CommonHostInterface: Using host vsync for throttling.
```

This is when the BIOS bootup runs:

```
[   11.8799] V/AudioStream: Audio buffer underflow, resampled 344 frames to 354
[   11.8926] V/AudioStream: Audio buffer underflow, resampled 38 frames to 302
[   11.8992] V/AudioStream: Audio buffer underflow with no samples, added 288 frames silence
[   11.9341] V/AudioStream: Audio buffer underflow, resampled 226 frames to 294
[   11.9675] V/AudioStream: Audio buffer underflow, resampled 286 frames to 294
[   12.0355] V/AudioStream: Audio buffer underflow, resampled 312 frames to 376
[   12.8813] V/System: FPS: 0.00 VPS: 59.56 Average: 16.68ms Worst: 22.09ms
[   13.2109] V/AudioStream: Audio buffer underflow, resampled 75 frames to 292
[   13.2312] V/AudioStream: Audio buffer underflow, resampled 124 frames to 300
[   13.2645] V/AudioStream: Audio buffer underflow, resampled 285 frames to 292
[   13.2843] V/AudioStream: Audio buffer underflow, resampled 186 frames to 293
[   13.2909] V/AudioStream: Audio buffer underflow with no samples, added 296 frames silence
[   13.2978] V/AudioStream: Audio buffer underflow with no samples, added 290 frames silence
[   13.3310] V/AudioStream: Audio buffer underflow, resampled 270 frames to 299
[   13.3842] V/AudioStream: Audio buffer underflow, resampled 157 frames to 292
[   13.8980] V/System: FPS: 7.87 VPS: 60.01 Average: 16.54ms Worst: 17.07ms
[   13.9714] V/AudioStream: Audio buffer underflow, resampled 110 frames to 286
[   14.9136] V/System: FPS: 55.13 VPS: 60.05 Average: 16.57ms Worst: 16.81ms
[   15.9297] V/System: FPS: 60.03 VPS: 60.03 Average: 16.58ms Worst: 16.78ms
[   16.9458] V/System: FPS: 60.03 VPS: 60.03 Average: 16.58ms Worst: 16.80ms
[   17.9620] V/System: FPS: 60.03 VPS: 60.03 Average: 16.56ms Worst: 16.97ms
[   18.9784] V/System: FPS: 3.94 VPS: 60.02 Average: 16.57ms Worst: 17.13ms
[   19.3522] V/AudioStream: Audio buffer underflow, resampled 267 frames to 285
[   19.9944] V/System: FPS: 10.83 VPS: 60.04 Average: 16.56ms Worst: 17.15ms
[   21.0107] V/System: FPS: 58.05 VPS: 60.02 Average: 16.57ms Worst: 17.14ms
[   22.0272] V/System: FPS: 56.08 VPS: 60.01 Average: 16.52ms Worst: 17.10ms
[   23.0431] V/System: FPS: 58.08 VPS: 60.04 Average: 16.56ms Worst: 17.11ms
[   23.5930] I/GPUBackend: GPU thread stopped.
[   23.6025] V/AudioStream: Audio buffer underflow, resampled 206 frames to 286
[   23.6089] V/AudioStream: Audio buffer underflow with no samples, added 284 frames silence
[   23.6170] V/AudioStream: Audio buffer underflow with no samples, added 358 frames silence
```

**Enhancements information**
No enhancements are active on my experiments, except for "disable interlacing" which seems to be faster than leaving interlacing on.

**Hardware/software**
X86_64 laptop, using Lubuntu Linux 20.04 LTS and Duckstation in NOGUI mode.
Hardinfo information:
```
-Processors-
AMD A4-9125 RADEON R3, 4 COMPUTE CORES 2C+2G	0	0:0	2300,00 MHz	
AMD A4-9125 RADEON R3, 4 COMPUTE CORES 2C+2G	1	0:1	2300,00 MHz	
-Display-
Resolution		: 1366x768 pixels
-OpenGL-
Vendor		: X.Org
Renderer		: AMD STONEY (DRM 3.35.0, 5.4.0-73-generic, LLVM 10.0.0)
Version		: 4.5 (Compatibility Profile) Mesa 20.0.8
Direct Rendering		: Yes

```

Duckstation relevant video/audio options:
==Video==
-GPU RENDERER: Software
-Enable VSYNC: ON
-Threaded rendering: ON
-Sync to host refresh rate: ON
-Optimal frame pacing: ON
==Audio==
-Audio backend: CUBEB /SDL2 (same results)
-Buffer size: 2048
-Sync to output: ON
-Resampling: ON
==Other==
-Execution mode: Recompiler (Fastest)
-Recompiler Fast Memory Access: MMap (Hardware, Fastest, 64-bit only)

**Emulator version**
Latest GIT version.

**Additional context**
I would say Duckstation should run the boot sequence/animation just fine on this computer, using the aforementioned settings.
Someting is not right, since even on a 2.3GHz X86_64 system, using the software renderer, Duckstation is unable to run the boot sequence fullspeed without audio defects. 

So it's not a problem with the Pi4 after all (and I hope it's OK to open an issue as I have reproduced the issues on X86_64 as asked: I don't want to annoy the devs).
This is a continuation of:
https://github.com/stenzek/duckstation/issues/2383

**Comment by BailShamber** [comment]
Try disabling "Sync To Output" in audio settings.

**Comment by stenzek** [comment]
Perhaps I should have been more specific in my other post, but the only "supported" platforms are Windows, Android, and now UWP/Xbox. If you want to use Linux, that's fine, but you're on your own. There's just too many drastically different setups to provide any sort of consistency for debugging.

Probably should make that clearer in the readme too...

For the record, it was fine on my system. Some hitches when first booting are expected while everything gets synchronized, but it should settle down after a couple of seconds.

**Comment by stenzek** [comment]
It's also been pointed out that this is a **very** low end CPU (to the extent where a good number of ARM systems have more compute). Therefore my points from the other thread apply here - it'll likely work fine without vsync and/or optimal pacing.

**Comment by vanfanel** [comment]
> Some hitches when first booting are expected while everything gets synchronized, but it should settle down after a couple of seconds.

@stenzek That's exactly what I am reporting :)
I have tried even more powerful computers, and it's all the same during the first 2-3 seconds.
In fact, a Pi4 at 1.5GHz is able to run Tekken 3 fullspeed without a single buffer underflow for hours. But both the fastest computer I could find (not mine) and the Pi4 show the same audio problems during BIOS boot, or during silent boot if FAST BOOT mode is activated.

Also, this is not GNU/Linux specific. The same happens on Android but it's way harder to debug, so I thought it was OK to do a GNU/Linux report where I can easily get logs, do changes on the code for experiments on your request, etc.

When you say "while everything settles down", do you mean the different threads?
Maybe it's just a matter of getting some thread stabilization before proceeding with the boot?

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation/commit/921c5cdfbf9ec7b90cb720ba60acc85f745edc31 clears up the tiny blip I was able to occasionally reproduce.
