### ISSUE TITLE
[Feature Request] A Feature that show us the Pointer for the PSX MEM

### ISSUE THREAD

**Issue by mbrking** [stenzek/duckstation#2407]
hey duckstation team, 

can u guys please add maybe a simple feature that show us the Pointer for the PSX MEM, 
this would be really helpfull for CheatEngine Address Converter

Duckstation version 0.1-4488-gab9109f3 (master)

duckstation-qt-x64-ReleaseLTCG.exe+1EEF88: 48 8B 05 09 E6 52 00     - mov rax,[duckstation-qt-x64-ReleaseLTCG.exe+71D598] //rax and ABC+71D598 = psx mem start

![duckstation](https://user-images.githubusercontent.com/25385591/125489273-45cab428-153b-494e-9cbd-3de93861fbd9.jpg)

**Comment by stenzek** [comment]
There is one, `Bus::g_ram` will point to the base address. But this changes every boot because of how fastmem is implemented.

It will print the ram address every boot to the log. https://github.com/stenzek/duckstation/blob/c2c204c845f0ef4760a8550827bdc4856abf2ebe/src/core/bus.cpp#L296

**Comment by mbrking** [comment]
ty very much
