### ISSUE TITLE
Duckstation is an amazing Ps1 emulator but is missing and option

### ISSUE THREAD

**Issue by jvhellraiser** [stenzek/duckstation#2408]
**Is your feature request related to a problem? Please describe.**
Duckstation is an amazing Ps1 emulator but is missing and option, Download Covers the reason i mention it
is because i had the covers and suddenly when i update all my covers are gone it really got mad cause doing so 
it takes some time to fine them  [...]

**Describe the solution you'd like**
Is simple i just want to right click the game and click on download cover for this game option
or for Duckstation to do as Epsxe (Download all covers option).

**Describe alternatives you've considered**
well you can do as Redream they have a cache folder for the emulator
there the emulator finds the ID of the games you have and download them
from a server.

**Additional context** 
![Capture](https://user-images.githubusercontent.com/16488761/125555667-090560d5-3145-4000-8fda-cd5ead6f9188.PNG)
(I do not want to see this all the time)

**Comment by stenzek** [comment]
No, and frankly I'm sick of being asked about this. Covers are copyrighted artwork, and **may be illegal to distribute**. I am not a lawyer, so I don't know if that is the case or not, but I am not taking the risk.

I don't care if other emulators do it, maybe they have legal advice to say it's fine (especially if they're paid like epsxe, they can afford lawyers, I can't).

It doesn't take long to google for an image to use, right click and set. Or you can drop them in the covers directory and it'll find them by game serial, title, or file name.
