### ISSUE TITLE
Box textures are misaligned in Crash Bandicoot (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#241]
OpenGL and D3D11

![SCUS-94900_2020-04-07_12-17-48](https://user-images.githubusercontent.com/31968468/78623200-73d09d80-78ca-11ea-9ba1-68a578453de7.png)

Software

![Capture](https://user-images.githubusercontent.com/31968468/78623258-98c51080-78ca-11ea-9f12-495ef24a4e73.PNG)

**Comment by stenzek** [comment]
As far as I can tell this also occurs on console.

**Comment by kurayami6** [comment]
It doesn't. Unless these speedrunners aren't playing on real hardware.

![Capture](https://user-images.githubusercontent.com/31968468/78623609-61a32f00-78cb-11ea-9cd1-c0c6ef7950a4.PNG)

https://youtu.be/7-IPwGQUxgI?t=758

**Comment by stenzek** [comment]
The camera is also in a different position there, which affects it. But yeah, it does look lightly off...

**Comment by stenzek** [comment]
Rounding texture coordinates instead of truncating them fixes it:

![image](https://user-images.githubusercontent.com/11288319/78624486-1558ee80-78cd-11ea-919f-e6b6d9773cec.png)

Unfortunately, it also breaks other graphics, particularly 2D sprites, so this will need more research.

**Comment by stenzek** [comment]
Latest build should fix this at 1x internal resolution. Upscaling will still be broken, I need to find a better solution there, as there's multiple issues affected by it.
