### ISSUE TITLE
Application builds fine on M1 Mac but crashes on startup

### ISSUE THREAD

**Issue by ultrasiq** [stenzek/duckstation#2415]
Process:               DuckStation [7942]
Path:                  /Users/USER/*/DuckStation.app/Contents/MacOS/DuckStation
Identifier:            com.github.stenzek.duckstation
Version:               0
Code Type:             ARM-64 (Native)
Parent Process:        ??? [1]
Responsible:           DuckStation [7942]
User ID:               501

Date/Time:             2021-07-15 13:02:11.501 -0400
OS Version:            macOS 11.4 (20F71)
Report Version:        12
Anonymous UUID:        DD76E1F7-3515-0DA2-2566-F56024245722

Sleep/Wake UUID:       78DD4F82-F915-40CD-A56D-66557C8F73F4

Time Awake Since Boot: 25000 seconds
Time Since Wake:       18000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x0000000103d6c000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2

kernel messages:

VM Regions Near 0x103d6c000:
    __LINKEDIT                  103b4c000-103d6c000    [ 2176K] r--/r-- SM=COW  /Users/*/DuckStation.app/Contents/MacOS/DuckStation
--> mapped file                 103d6c000-103d70000    [   16K] r--/r-x SM=PRV  Object_id=9b04778b
    __TEXT                      103d84000-103e04000    [  512K] r-x/r-x SM=COW  /usr/lib/dyld

Application Specific Information:
dyld: launch, loading dependent libraries
@executable_path/../Frameworks/QtWidgets.framework/Versions/5/QtWidgets

Thread 0 Crashed:
0   dyld                          	0x0000000103de1e80 memcmp + 16
1   dyld                          	0x0000000103da2490 ImageLoaderMachO::validateFirstPages(linkedit_data_command const*, int, unsigned char const*, unsigned long, long long, ImageLoader::LinkContext const&) + 136
2   dyld                          	0x0000000103da9420 ImageLoaderMachOCompressed::instantiateFromFile(char const*, int, unsigned char const*, unsigned long, unsigned long long, unsigned long long, stat const&, unsigned int, unsigned int, linkedit_data_command const*, encryption_info_command const*, ImageLoader::LinkContext const&) + 268
3   dyld                          	0x0000000103da1080 ImageLoaderMachO::instantiateFromFile(char const*, int, unsigned char const*, unsigned long, unsigned long long, unsigned long long, stat const&, ImageLoader::LinkContext const&) + 172
4   dyld                          	0x0000000103d88588 dyld::loadPhase6(int, stat const&, char const*, dyld::LoadContext const&) + 668
5   dyld                          	0x0000000103d91864 dyld::loadPhase5(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 1368
6   dyld                          	0x0000000103d91288 dyld::loadPhase4(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 208
7   dyld                          	0x0000000103d90da0 dyld::loadPhase3(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 600
8   dyld                          	0x0000000103d90758 dyld::loadPhase1(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 252
9   dyld                          	0x0000000103d88104 dyld::loadPhase0(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 468
10  dyld                          	0x0000000103d87ca8 dyld::load(char const*, dyld::LoadContext const&, unsigned int&) + 196
11  dyld                          	0x0000000103d92208 dyld::libraryLocator(char const*, bool, char const*, ImageLoader::RPathChain const*, unsigned int&) + 56
12  dyld                          	0x0000000103d9c604 ImageLoader::recursiveLoadLibraries(ImageLoader::LinkContext const&, bool, ImageLoader::RPathChain const&, char const*) + 344
13  dyld                          	0x0000000103d9adbc ImageLoader::link(ImageLoader::LinkContext const&, bool, bool, bool, ImageLoader::RPathChain const&, char const*) + 160
14  dyld                          	0x0000000103d8aa08 dyld::link(ImageLoader*, bool, bool, ImageLoader::RPathChain const&, unsigned int) + 328
15  dyld                          	0x0000000103d8d01c dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 7472
16  dyld                          	0x0000000103d85258 dyldbootstrap::start(dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*) + 476
17  dyld                          	0x0000000103d85038 _dyld_start + 56

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000103d6c000   x1: 0x000000016dca1b00   x2: 0x0000000000000be0   x3: 0x0000000000040001
    x4: 0x0000000000000003   x5: 0x0000000000000000   x6: 0x0000000103e0c280   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x000000016dca22f0  x10: 0x0000000000000001  x11: 0x0001803000000000
   x12: 0x0000000000000032  x13: 0x0004000000000000  x14: 0x000000000056f408  x15: 0x000000016dca2270
   x16: 0x00000000000000c5  x17: 0x000000016dca2288  x18: 0x0000000000000000  x19: 0x0000000103e11680
   x20: 0x0000000000000bf0  x21: 0x000000016dca1b00  x22: 0x0000000103d6c000  x23: 0x0000000000000003
   x24: 0x000000016dca26e0  x25: 0x000000016dca9c18  x26: 0x000000016dca9d90  x27: 0x000000016dca1b00
   x28: 0x000000000000000c   fp: 0x000000016dca1500   lr: 0x0000000103da2490
    sp: 0x000000016dca14c0   pc: 0x0000000103de1e80 cpsr: 0x20000000
   far: 0x0000000103d6c000  esr: 0x92000007

Binary Images:
       0x102154000 -        0x10285bfff +com.github.stenzek.duckstation (0) <39346824-3322-3CB4-B794-0C8949A897EE> /Users/USER/*/DuckStation.app/Contents/MacOS/DuckStation
       0x103d84000 -        0x103e03fff  dyld (852) <CF624584-51D6-329D-91C5-6BEDFADFB2D2> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 3
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=9.9M resident=0K(0%) swapped_out_or_unallocated=9.9M(100%)
Writable regions: Total=26.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=26.6M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                          56.0M                1 
Stack                                          8176K                1 
VM_ALLOCATE                             1.0G                1 
__DATA                                      1 9.0M                4 
__DATA_CONST                          160K                2 
__LINKEDIT                               2464K                3 
__TEXT                                       7712K                2 
mapped file                                    16K                1 
===========                     =======  ======= 
TOTAL                                            1.1G              15

**Comment by stenzek** [comment]
From the readme

> MacOS builds are no longer provided, as I cannot support a platform which I do not own hardware for, and I'm not spending $1000+ out of my own pocket for a machine which I have no other use for.

> You can still build from source, but you will have to debug any issues encountered yourself.

> If anyone is willing to volunteer to support the platform to ensure users have a good experience, I'm more than happy to re-enable the releases.

Code signing error sounds like a build issue.

**Comment by ultrasiq** [comment]
> From the readme
> 
> > MacOS builds are no longer provided, as I cannot support a platform which I do not own hardware for, and I'm not spending $1000+ out of my own pocket for a machine which I have no other use for.
> 
> > You can still build from source, but you will have to debug any issues encountered yourself.
> 
> > If anyone is willing to volunteer to support the platform to ensure users have a good experience, I'm more than happy to re-enable the releases.
> 
> Code signing error sounds like a build issue.

I understand that you're not supporting it any more, but can you at least point me in the right direction here? I have no idea what I'm looking at.

**Comment by stenzek** [comment]
Nor do I. I don't own an M1 mac so I've never seen this error before. But like I said it sounds like a signature issue and you need to resign the binary and all libraries it uses

**Comment by ultrasiq** [comment]
Ok, thanks anyway! I'll try and figure this out.

**Comment by lbibass** [comment]
> Ok, thanks anyway! I'll try and figure this out.

If you are still having issues, I used [macOS Gatekeeper Helper](https://github.com/wynioux/macOS-GateKeeper-Helper) to resign the app, and that fixed my crashes on my m1 machine.
