### ISSUE TITLE
Mesa OpenGL breaks transparency (and other things)

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#242]
Anything transparent renders as completely solid (Tested in: Tetris with Card Captor Sakura- Eternal Heart (Japan), R-Type Delta (Japan), Pop'n Tanks (Japan)

Black screens/fade to black screens sometimes render as white(Tested in: Tetris with Card Captor Sakura- Eternal Heart (Japan) noticable on the loading screen, will sometimes render as white and the mouse thing running by creates a black line, R-Type Delta (Japan) after choosing start game, the screen where the words R-TYPE DELTA fade in sometimes renders with a white background instead of black)

All gameplay renders as a black screen: Dino Crisis 2 (USA)

**Comment by stenzek** [comment]
This was fixed with https://github.com/stenzek/duckstation/commit/9dc82a738f282c91d92fc253ab06b6388c3f7a5d
