### ISSUE TITLE
"Separate Card Per Game (File Title)" setting not exposed on Android

### ISSUE THREAD

**Issue by ugoplatamia** [stenzek/duckstation#2421]
**Description of the issue / bug**
"Separate Card Per Game (File Title)" setting not exposed on Android.

**Steps to reproduce**
Controller Settings > Memory Card Type > Setting Missing

**Hardware/software**
Amazon Fire HD10 (2019)

**Emulator version**
June 28 2021 Build, via Google Play

**Comment by stenzek** [comment]
Fixed, but it won't show up until I release a new android build, and I'm not sure when that will be yet.
