### ISSUE TITLE
Bugs Bunny and Taz PAL GFX problems.

### ISSUE THREAD

**Issue by backgamon** [stenzek/duckstation#2430]
**Game details**
SLES_028.96
Bugs Bunny & Taz (Europe)

**Description of the issue / bug**
Game are sort of downsampled, like software mode when using upscaling, and textures wobble.
On the NTSC version no problem at all.

**Steps to reproduce**
Just launch the game.

**Hardware/software**
I9 10850k@4.8/4.9Ghz
Asus Maximus XII Formula
64Go DDR4 GSkill Trident Z 3600Mhz[XMPII]
Gigabyte 2070 RTX 8G OC
Windows 10 Pro x64
Using Vulkan render (all render doesn't work)

**Emulator version**
0.1-4525-gdfd67664

**Additional context**
Video of PAL and NTSC version.
https://www.youtube.com/watch?v=ZVZAY62tyFs

**Comment by foxsevent** [comment]
Try disabling enhancements, just because some enhancements work on a version of a game doesn't mean they will work on every version of said game, and this screams to me Depth buffer enhancement issue.

**Comment by stenzek** [comment]
Did you read the issue template? Enhancement issues are not bugs.

**Comment by foxsevent** [comment]
> Did you read the issue template? Enhancement issues are not bugs.

It's not an enhancement bug thou.

**Comment by stenzek** [comment]
Why are you switching renderers? Just stick with one...

**Comment by foxsevent** [comment]
> Why are you switching renderers? Just stick with one...

Sten read what im saying, this game Bugs Bunny & Taz PAL has a graphical glitch on all hardware renders and especially is broken on DX12 but not in software mode with no enhancements.
I was switching renders to showcase this issue, and reseting on each switching doesn't change i=anything.

**Comment by stenzek** [comment]
Posting the console output would've been helpful here - it clearly said that it was doing an oversized VRAM fill, forcing everything to be downsampled and read back on the CPU as they weren't implemented in the hardware renderers.

This one is easily solvable though, unlike most upscaling issues: https://github.com/stenzek/duckstation/commit/70209db402e367ca70e098d873c36903ccdecb4b
