### ISSUE TITLE
Keys or buttons for analog sticks

### ISSUE THREAD

**Issue by Bobba435** [stenzek/duckstation#2432]
I use my switch pro controller with a wire and it all buggy and stuff so I have to use keys for movement and camera (Steam works out the rest) but I can't put in any keys for analog movement so I'm stuck with the games that don't require analog sticks and I want to play ape escape.

**Comment by stenzek** [comment]
Issue template not completed. Also merging with https://github.com/stenzek/duckstation/issues/1502
