### ISSUE TITLE
loading state crash aftering player number change in some fight game.

### ISSUE THREAD

**Issue by zkdpower** [stenzek/duckstation#2434]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Game details**
[Serial Code, Region]
[i.e SLUS-00213 Tekken 2 (USA)]

**Description of the issue / bug**
because some state is created only 1p play, then, once setting an 2p participant, to load this previous  state/single player state would cause crashed.

**Comment by stenzek** [comment]
Works fine here. You'll need to be more specific or include the crash dump file.

**Comment by stenzek** [comment]
Translation issue again;

https://github.com/stenzek/duckstation/blob/e17c93ab04f9f88d9ff8e66ce241ffbfec053220/src/duckstation-qt/translations/duckstation-qt_zh-cn.ts#L8037-L8038

You can't change the order of format string operands on core strings. Only those which are numbered.
