### ISSUE TITLE
portable version

### ISSUE THREAD

**Issue by crazydownload** [stenzek/duckstation#2437]

**Comment by crazydownload** [comment]
it is necessary that the settings folder be stored in the folder with the program and not in the windows user folder so that you can transfer the program with you on external disks, flash drives or in the cloud

**Comment by andercard0** [comment]
> it is necessary that the settings folder be stored in the folder with the program and not in the windows user folder so that you can transfer the program with you on external disks, flash drives or in the cloud

Invalid issue template not filled up. 
Also, portable mode is already live, just create a portable.txt inside duckstation's root folder and done.

**Comment by andercard0** [comment]
> and what to write to the portable file the new location of the settings folder?

Nothing. Only portable.txt and done. 
Please do close this issue where possible and get help on our discord.

**Comment by stenzek** [comment]
The issue tracker is for bug reporting, **not support questions**. Please read the readme file.
