### ISSUE TITLE
Black screen on Hot Wheels Turbo Racing

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#244]
Both the European and North American versions hit a black screen after the opening fmv, regardless of whether you skip it or not.

**Comment by stenzek** [comment]
Please re-test on latest build.

**Comment by stenzek** [comment]
Fixed by https://github.com/stenzek/duckstation/commit/9d1eb321ec1764ec4c4d918d977465b8db92dda4
