### ISSUE TITLE
Vib-Ribbon - Music (CD-ROM)

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#2445]
Okay this case is too specific so I'll title this way:
'The ability to read music CD-ROM'

So, this game Vib-ribbon has a built-in feature that we can use our own music CDs so, in order to do that we go trough the menu and choose > Game > Play with my own choice of CD as follows: 

![image](https://user-images.githubusercontent.com/43047877/126917255-69e24c14-caf5-4091-81ca-d2be80767d7c.png)

At the moment, we can easily change or insert our own music via: System > Change Disc > From game list or from file. 
and it is working well as far as i can tell; but, we can't via physically CD's.

So, with the implementation made recently that let us to boot our games from reals Discs, I'd like to ask, if feasible the ability to change it; of course not only specifically for this game but maybe if there are more games with this feature as well this option would be useful.

**Game details**
Game: Vib-Ribbon - Code: SCES-02873

**Steps to reproduce**
Boot it up > Game > (choose from the menu) Play with my own choice of CD > single / all tracks, done!
(atm we can only do it via .cue file not with read Discs)

**Emulator version**
Current: Duckstation Preview 0.1-4564-g0da756b0

**Additional context**
Nothing.

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/96fb81733d4c2a9b66f2e3065bf59227781eb3f2, but I haven't tested it at all. CDDA reads may not work.

If you're changing discs on the physical drive, you'll probably need to change disc -> remove media first, then reselect the same drive. Going from game dump -> physical media should be fine to go directly.

**Comment by andercard0** [comment]
> Added in [96fb817](https://github.com/stenzek/duckstation/commit/96fb81733d4c2a9b66f2e3065bf59227781eb3f2), but I haven't tested it at all. CDDA reads may not work.
> 
> If you're changing discs on the physical drive, you'll probably need to change disc -> remove media first, then reselect the same drive. Going from game dump -> physical media should be fine to go directly.

Thanks! working good just tested with single track option.

But, when i did select all tracks it does read the CD then black screen as if i actually change game not disc as follows:
![image](https://user-images.githubusercontent.com/43047877/127230193-f517106d-3865-461a-a032-e880931b656d.png)

and if i try to reset or shutdown the game or emulator i got this: 
![image](https://user-images.githubusercontent.com/43047877/127230512-39c8f3eb-7fd2-4021-996e-780754e04ee3.png)

If you think it is important, I can fill out a new ticket as a issue since this one was originally open as a feature request.

**Comment by stenzek** [comment]
Need the log file.

**Comment by andercard0** [comment]
> Need the log file.

Here it is.
[duckstation.log](https://github.com/stenzek/duckstation/files/6893941/duckstation.log)
