### ISSUE TITLE
[QT] Game Properties inaccessible when launching game from CLI/Shortcut

### ISSUE THREAD

**Issue by ds22x** [stenzek/duckstation#2448]
When launching a game from the CLI or a shortcut (be it a desktop or a Steam shortcut), using the QT version, the Game Properties option will be grayed out and inaccessible.
Only when loading a game from the gamelist will the option be accessible, which is part of the reason why I use the QT version instead of NoGUI, as with the latter there's no way of accessing the option while a game is running to begin with.
Using the latest build based on https://github.com/stenzek/duckstation/commit/dfd6766411f6d6e2f0aa73a686fb662f3c2cde25

**Comment by stenzek** [comment]
Issue template not completed.

This is working as intended. For game properties to work (and per-game settings), it needs to be a scanned directory, and the game present in the game list. If you launch a file that has been scanned, game properties is accessible as expected.

**Comment by ds22x** [comment]
Guess I'll just have to switch back to the Libretro core then, seeing there's otherwise no way to adjust the overscan when the games running.

**Comment by stenzek** [comment]
How mature. Making silly threats like that.

What you're complaining about works perfectly fine, I tested it. Make sure the game you're launching via command line has been scanned.
