### ISSUE TITLE
[Feature Request] Add support for D3D9 and OpenGL 3.0

### ISSUE THREAD

**Issue by SilentMRG** [stenzek/duckstation#2453]
Hello...

Please add the Direct3D 9 API if possible.

And also add, if possible, OpenGL 3.0 support.

Note: I suspect that the OpenGL API that is in the emulator requires version 4.0 or higher to work, because when I run the emulator in OpenGL, the emulator closes with the BEX error.

Here I use an Intel HD Graphics 1000 with DirectX 9/10.1 plus OpenGL 3.0 support, and I know I'm not the only one with very low performance hardware. So, the D3D9 API and OpenGL version 3.0 will help people like me a lot.

Thank you very much for your attention! 

👍🤓🖒

**Comment by stenzek** [comment]
You deleted the issue template.

No. D3D9 doesn't support integers in pixel shaders, so it cannot accurately emulate the PS1 GPU. I have no desire to write half assed renders which don't work for some games, and share no code with the more modern renderers.

If your GPU supports DX10, that'll work fine, albeit perhaps not very well with upscaling. The software renderer is also an option.

**Comment by SilentMRG** [comment]
> You deleted the issue template.
> 
> No. D3D9 doesn't support integers in pixel shaders, so it cannot accurately emulate the PS1 GPU. I have no desire to write half assed renders which don't work for some games, and share no code with the more modern renderers.
> 
> If your GPU supports DX10, that'll work fine, albeit perhaps not very well with upscaling. The software renderer is also an option.

I thought the model was just a sampling model. Nevermind...

I understood everything. So I will continue to support (monetary) the ePSXe team.

**Comment by BailShamber** [comment]
Okay, no reason to name another emu just to try to antagonize the dev.

Plus if your CPU is one of these or newer https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units#Gen6
it should support opengl 3.3 on linux since opengl drivers there are better (minimum requirement for duckstation is 3.1)

**Comment by stenzek** [comment]
Enjoy giving your money away to an emu which is no longer maintained, and can't even play a decent part of the library without issues. Blocked.

Seriously, why do you think you're entitled to change the direction of a project you got for free? You're not a customer, you didn't pay anything.
