### ISSUE TITLE
fix android app

### ISSUE THREAD

**Issue by AbdelKaderSouf** [stenzek/duckstation#2456]
right now it runs like khara on my galaxy s6 but epxse and retroarch run fine bro 
bros told me that duckstation was best but they pranked me becuase this app is garbage worth zero stars but i give 1 star until you fix it
thanx bye and may Allah bless you when you do

**Comment by andercard0** [comment]
> right now it runs like khara on my galaxy s6 but epxse and retroarch run fine bro
> bros told me that duckstation was best but they pranked me becuase this app is garbage worth zero stars but i give 1 star until you fix it
> thanx bye and may Allah bless you when you do

Issue template ignored issue Invalid! It's a free app for god sake be more reasonable here, I think it's asking too much of an android user.. but who knows!

**Comment by AbdelKaderSouf** [comment]
bro who are you shut up im talking to the app maker not you little boy

**Comment by RinMaru** [comment]
With that attitude your gonna be lucky if the dev doesn't just close this lol. He's not a fan of Entitled t#%&$.

**Comment by AbdelKaderSouf** [comment]
shut up im here to tell the app maker to fix his broken app not to talk to little puss boys

**Comment by RinMaru** [comment]
> shut up im here to tell the app maker to fix his broken app not to talk to little puss boys

Lol look at you having a cute tantrum.

**Comment by AbdelKaderSouf** [comment]
shut up kafir im not talking to you anymore only to the app maker so he fixes the broken app he published
Allah will forgive you if you sincerely repent for being haram and accept the truth of Islam

**Comment by RinMaru** [comment]
> shut up kafir im not talking to you anymore only to the app maker so he fixes the broken app he published
> Allah will forgive you if you sincerely repent for being haram and accept the truth of Islam

Jesus loves you even if your entitled.

**Comment by stenzek** [comment]
Blocked.
