### ISSUE TITLE
Minor audio bug Gran Turismo 2

### ISSUE THREAD

**Issue by CometHunter92** [stenzek/duckstation#2457]
SCUS-94455 Gran Turismo 2 - Arcade Disco & SCUS-94488 Gran Turismo 2 -Simulation Disc

It's a very minor bug, almost unnoticeable, but when you exit the save menu after the saving, during the transition back to the main menu the audio glitches and stutters.
Only when you do that, for now.
The strange thing is that it wasn't in Duckstation till the very few last revisions. Started to happen like one month ago, but I don't remember correctly the version where it started.
Still happens in 0.1-4525-gdffd67664 (dev).
All settings are default, no enhancement. Software renderer.
Happens in Libretro core and Win standalone.

**Comment by stenzek** [comment]
Issue template not completed, it specifically says it must or the issue will be closed.
