### ISSUE TITLE
no sound in latest version

### ISSUE THREAD

**Issue by ISuckGood** [stenzek/duckstation#2458]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

Please read before creating a new issue:

1. Make sure there is not already an open issue for this bug.
2. All enhancements **must** be off. To quickly disable all enhancements with affecting your normal config, in advanced options you can check "Disable All Enhancements".
3. All advanced options **must** be at their default values.
4. No cheats may be active. If you were using cheats, they should be disabled, and the game rebooted before reporting the bug.
5. Do not share save state files. Memory cards are okay.
6. Verify your dump, as we can not assist with issues resulting from bad dumps.
7. If playing PAL region software, please check whether or not the game has LibCrypt protection and that if it does, you have a correct SBI file (see https://github.com/stenzek/duckstation#libcrypt-protection-and-sbi-files for more information).
8. Please post your issue report in English as unfortunately this is the only language spoken by the developers. The Discord server has many helpful people if you need help translating.

**Remove everything before and including this line before submitting.**

**Game details**
All

**Description of the issue / bug**
No sound

**Controller Troubleshoot Report**
none

**Note:**

**Steps to reproduce**
Open any game

**Enhancements information**
[Make sure they are all turned off before report]

**Hardware/software**
Core i9 , rtx 2080s , sound blaster ae5 plus
[GPU Renderer - D3D11]

**Emulator version**
latest

**Additional context**
[Add any other context about the problem here]

**Comment by stenzek** [comment]
Nothing has changed with audio emulation. Likely a configuration issue.
