### ISSUE TITLE
Minor audio bug Gran Turismo 2

### ISSUE THREAD

**Issue by CometHunter92** [stenzek/duckstation#2459]
[SCUS-94455 Gran Turismo 2 - Arcade Disc (USA) / SCUS-94488 Gran Turismo 2 -Simulation Disc (USA)]

It's a very minor bug, almost unnoticeable, but when you exit the save menu after the saving, during the transition back to the main menu the audio glitches and stutters.
Only when you do that, for now.
The strange thing is that it wasn't in Duckstation till the very few last revisions. Started to happen like one month ago, but I don't remember correctly the version where it started.

**Steps to reproduce**
[Main menu -> save game -> save -> exit to return to the main meni -> audio glitch happens]

Video Enhancement are off, default settings.

**Hardware/software**
[Asus ZenBook Win 10, Intel(R) Core(TM) i7-8550U CPU, 8 Gb RAM, GeForce MX150 / RPi4 b 8 gb ram, Retroarch 1.9.5]
[Software Renderer]

Software Version
[0.1-4525-gdffd67664 (dev)]

**Comment by stenzek** [comment]
The revision number you've listed isn't valid, but as best I could tell I already fixed this in https://github.com/stenzek/duckstation/commit/b41d56d3054e4196070b662b51d002320c8bab1c
