### ISSUE TITLE
[Feature Request]1:1 pixel aspect ratio mode

### ISSUE THREAD

**Issue by bajolzas** [stenzek/duckstation#246]
I've made this request for beetle psx [before.](https://github.com/libretro/beetle-psx-libretro/issues/561)
Basically I want duckstation to be able to output at 1:1 pixel ratio.

To elaborate, here you can see the config menu of Valkyrie Profile at its normal ratio:
![SLUS-01156_2020-04-08_00-09-42](https://user-images.githubusercontent.com/51722671/78729396-d610b900-7931-11ea-9a3d-b3b20220335d.png)

Here you can see the same but at 1:1 pixel ratio on pcsxr:
![valkyrie profile menu](https://user-images.githubusercontent.com/51722671/78729421-e5900200-7931-11ea-82d6-b1ce556c01e5.png)

Notice how the circle is much more of an actual circle now.
Granted the former is how it looks on hardware, but to me the latter looks better.

**Comment by stenzek** [comment]
Should be relatively simple to add. May as well add a widescreen option while we're at it.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/fbfd838e22c9e3e28378904027dd6643b56e5c7c

**Comment by bajolzas** [comment]
It seems what was implemented was a screen ratio of 1:1 and not a pixel ratio of 1:1
Here is the screen I showed above at 1:1 screen ratio:
![vp 1-1 screen](https://user-images.githubusercontent.com/51722671/78992063-54d44480-7b32-11ea-890e-c709111bbcea.png)
