### ISSUE TITLE
Fatal errors should close Duckstation, but dont

### ISSUE THREAD

**Issue by wheelmac92** [stenzek/duckstation#2463]
**Game details**
No specific game

**Description of the issue / bug**
![image](https://user-images.githubusercontent.com/58401060/127777244-14305a0b-e17d-48db-8b55-248ef4f80f1b.png)
The problem is NOT that this error appears, the problem is that WHEN errors like this appear, they open behind the main Duckstation window, and I cannot see them. Then, I will try booting more ISOs over and over, realize nothing works, only to eventually try minimizing the Duckstation window to see that the emulator crashed.

Suggested Fix:
When any Fatal Error windows open, can the main Duckstation window get closed automatically?

**Steps to reproduce**
Any generic error

**Enhancements information**
Turned off

**Hardware/software**
i7 7700hq
GTX 1050
16gb RAM

**Emulator version**
![image](https://user-images.githubusercontent.com/58401060/127777343-c75c765d-3b12-40b9-9b85-2c01769bbcd6.png)

**Additional context**
[Add any other context about the problem here]

**Comment by stenzek** [comment]
If those errors are happening, then you either have a bad dump, or a game is doing something which isn't being handled. It shouldn't happen under normal circumstances.

**Comment by wheelmac92** [comment]
@stenzek It happens while modding the game

**Comment by stenzek** [comment]
Then you're doing something which will be unpredictable and/or crash on console too.
