### ISSUE TITLE
Some textures seem corrupt in Tail Concerto

### ISSUE THREAD

**Issue by ualaa1** [stenzek/duckstation#2467]
**Game details**
SLUS-00660 Tail Concerto US

**Description of the issue / bug**
Some texture in game seems to be corrupt.

**Steps to reproduce**
It is in the beginning area of the game. Some of the gate textures seem corrupt. Gate is not supposed to have these white things on top or have grass go through it. I also managed to trigger a bug causing the nearby wall to disappear, but I can't seem to trigger it now.
On the fourth screenshot, the lantern's shadow on the wall seem to be wrong. And on the fifth, not only is the shadow seemingly wrong, there is a weird black spot next to the table.

**Hardware/software**
D3D11 Intel(R) Core(TM) i7-9750H CPU

**Emulator version**
0.1-4599-ga542fa85

**Additional context**
![SLUS-00660_2021-08-02_20-53-23](https://user-images.githubusercontent.com/68984176/127955592-461e6cd2-8e3e-47d0-a743-84ce5f8470c0.png)
![SLUS-00660_2021-08-02_20-54-04](https://user-images.githubusercontent.com/68984176/127955604-e057c5f1-f9a1-4e13-b1c1-e049c1a6164a.png)
![SLUS-00660_2021-08-02_20-53-45](https://user-images.githubusercontent.com/68984176/127955599-9d43854b-4590-488a-854f-242632bca664.png)
![SLUS-00660_2021-08-02_21-50-13](https://user-images.githubusercontent.com/68984176/127959581-12ac7b64-b3b5-4b1c-8788-faa2ff74b492.png)
![SLUS-00660_2021-08-02_21-52-19](https://user-images.githubusercontent.com/68984176/127959754-b0b01e62-a92b-4d95-883d-e8d5170cf70e.png)

**Comment by stenzek** [comment]
Gate looks like bog standard polygon fighting. Check on console.

**Comment by ualaa1** [comment]
Found a video recording that seems to be from a PS2. The gate seems relative normal?
https://youtu.be/yUruLBthxAw?list=PLzdTTZKx2qFHSkaIzmgmb796mic7qL5t_&t=874

**Comment by BailShamber** [comment]
It's a different angle in the video time stamp than the screenshots you provided before.
Plus there's the grass texture and the roof texture overlap the gate at about 14:37
![Screenshot from 2021-08-03 09-51-51](https://user-images.githubusercontent.com/49800926/127978627-78a657cb-b857-432a-8bce-d9e1c1462413.png)

**Comment by stenzek** [comment]
That video does not show the same camera angles. The camera angle determines the polygon sort order, and thus the fighting.

I'm going to close this as invalid, this sort of thing was very common in PS1 games. Some used smaller polygons to mitigate the effect. DuckStation's depth buffer enhancement can also clean them up.
