### ISSUE TITLE
Fast Forward does not seem to work

### ISSUE THREAD

**Issue by ualaa1** [stenzek/duckstation#2468]
**Game details**
All games I have

**Description of the issue / bug**
I hold down tab to fast forward, but games still runs at roughly the same speed. Even after remapping and trying all sorts of solutions, game is still at similar speed at fast forwarding

**Steps to reproduce**
Hold down whatever key you mapped to be the fast forward key, it should say begin fast forwarding or something similar, then notice that the FPS is still around 60 or 30 instead of being faster.

**Hardware/software**
D3D11 Intel(R) Core(TM) i7-9750H CPU

**Emulator version**
0.1-4599-ga542fa85

**Additional context**
https://streamable.com/x1v1jh for an example

**Comment by stenzek** [comment]
Fast forward works fine, this is a support issue not a bug report. Make sure you're not forcing vsync in drivers, and/or use blit swap chain.
