### ISSUE TITLE
Having the emulator minimized during the BIOS screen causes stuttering

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#247]
As you can see.

![Capture](https://user-images.githubusercontent.com/31968468/78744662-7ce26d00-79a5-11ea-9a34-beed8b78c38d.PNG)

**Comment by stenzek** [comment]
Sorry, this seems a little ridiculous. It is not surprising at all that an OS de-prioritizes a program when it is not in the foreground.
