### ISSUE TITLE
Vanark Zipped Issue

### ISSUE THREAD

**Issue by rods012** [stenzek/duckstation#2472]
**Game details**
[SLUS-01035 Vanark (USA)]

When reading from a zip file the game will freeze right before the tutorial level starts at the "Start Your Engine" screen. I had multiple changes made to the core options and I toggled them one at a time to see if they were the issue **they were not**. After some testing it turned out that when reading Vanark from inside a zip file is what was causing the issue. I tried unzipping it and playing it on default core settings **AND** with changes to renderer, execution mode, scaling, antialiasing, and fast boot. With it unpacked all attempts were successful. I noticed that the Vanark files are not a singular bin file, but multiple (unlike many other ROMs). 

I attempted the tests with other software open in the background as well as with nothing else open.

**Steps to reproduce**
From my attempts, as long as Vanark is in a ZIP file (that was the only format I tested) it seemed to have this behavior. The format of the content itself was bin & cue. There were 12 different bin files. The zip file was in a folder with other zipped bin & cue files for other games. This was tested both with default settings for the duckstation emulator as well as  customized settings with Antialiasing, renderer, execution mode, scaling and fast boot. The settings **DID NOT** change the results. Whether the game was zipped or not did.

**Enhancements information**
Attempted with enhancements turned off and on.

**Hardware/software**
CPU - 9900K
GPU - 2080
RAM - 32GB 3200MHz
STORAGE - WD Blue 1TB SSD
[GPU Renderer - D3D11 & Vulkan]

**Emulator version**
Version 1.9.7 - Retroarch

**Comment by stenzek** [comment]
This doesn't really make any sense. Verity that the dump is correct by comparing the hashes to redump.

Otherwise, the core has nothing to do with zips. It only accepts extracted file paths. Maybe this is a frontend bug.
