### ISSUE TITLE
Analog to dpad

### ISSUE THREAD

**Issue by JimiMonkey** [stenzek/duckstation#2475]
Hello everyone. I'd like to ask having analog to dpad feature like retroarch does, for instance, have both analog and digital movement at the same time without choosing one or another. Right now you can map only the dpad or analog to a single button, so if you could map multiple butttons or just have a toggle for games that have analog input as well would be awesome. Some comands i prefer on dpad, others on analog stick, anyway, have a nice one.

**Comment by stenzek** [comment]
1. You couldn't be bothered, or were too arrogant to fill out the issue template and deleted it.
2. This is already a thing.

**Comment by JimiMonkey** [comment]
I read it and thought that it was correct, sorry if what I wrote didn't match what you expected, I will search then, thank you.
