### ISSUE TITLE
Emulator is frozen after monitor on/off cycle

### ISSUE THREAD

**Issue by aybe** [stenzek/duckstation#2476]
**Game details**
SLUS-90049 Ridge Racer Turbo (USA)

**Description of the issue / bug**
Every time I keep the emulator on and turn the monitor off, when I come back and turn the monitor on, the emulator is frozen and must be restarted with task manager.

**Steps to reproduce**
- pause the game or the emulator
- turn off monitor
- turn on monitor
- application is frozen

**Hardware/software**
I7 4770, RX 5600 XT, Windows 10
D3D11

**Emulator version**
0.1-4599-ga542fa85 (dev)

**Comment by stenzek** [comment]
Sounds specific to your system, I can't think of how this would happen otherwise, unless it's losing the graphics device (in which case all games would have this problem)

**Comment by aybe** [comment]
No, if I play say, RE8, that doesn't happen, I don't have to kill the process because I switched the monitor off/on during a break.

Any idea on how to debug this ?

**Comment by aybe** [comment]
@stenzek anything to say?

**Comment by PugsyMAME** [comment]
Stenzek has spoken already. I can't see how it's anything to do with DS, problem must be at your end.

The problem sounds like it's your graphics card to me. Update to latest bios and drivers and cross your fingers.

Also might be worthwhile completely removing power from your monitor for a few seconds (pull the plug so the light goes out) and then reconnect the power and see if that works/
