### ISSUE TITLE
Excessive VRAM Read Texture Updates Kill MSAA/SSAA Performance

### ISSUE THREAD

**Issue by Awakened0** [stenzek/duckstation#2477]
**Game details**
SLUS-00806 / Gex 3 - Deep Cover Gecko (USA)
SCUS-94243 / Einhaender (USA)

**Description of the issue / bug**
Gex 3 and Einhander have water effects in certain areas that warp the screen. When combined with MSAA or SSAA (I usually use 4x SSAA with all 3D games without issue) there is a big performance drop while those effects are active. When I mentioned Gex on Discord, @stenzek theorized it was because of there being many "VRAM Read Texture Updates" during those effects. When AA is disabled, there doesn't seem to be an effect on unlocked FPS.

https://user-images.githubusercontent.com/4565863/128441394-275245fa-6394-4d83-a784-6073eb0007ba.mp4

https://user-images.githubusercontent.com/4565863/128441405-2dae8cfd-f169-4b53-915e-fcdd5c4f1450.mp4

**Steps to reproduce**
Gex 3:
1. Start a New Game, skip cutscenes with Start.
2. Grab the remote on the stairs. Enter "The Pole" and go into the TV (pick any objective).
3. Exit through the gate. Go left past the Santa snowman and around the house. To the right is a "Danger Ice Ahead" sign; go in the hole to the next area. Go straight ahead into the "Rest Area." Jump into the water and press L2 to dive (X plus down to surface).

Einhander:
This game doesn't let you save level progress, so the only way to get to the problem area is to play up to Stage 4 from the beginning. It starts after this boss:

![ein](https://user-images.githubusercontent.com/4565863/128442131-04acda0a-cf54-4014-95db-2887b24df61a.png)

A couple seconds into the area where there's water at the bottom the performance should tank a bit, but not as badly as Gex. The easiest way to get up to this part of the game is to use this save file, pick the "Unknown Fighter Type II" and two Flash weapons or a Flash and Juno:

[Einhaender (USA)_1.zip](https://github.com/stenzek/duckstation/files/6942441/Einhaender.USA._1.zip)

**Enhancements information**
Even with the lowest 2x SSAA or 2x MSAA setting, there's a drop in performance in the areas shown in the videos. Only disabling AA entirely fixes it on my hardware.

**Hardware/software**
i5 2500k, GTX 970, Windows 10
GPU Renderer - D3D11

**Emulator version**
0.1-4599-ga542fa85

**Additional context**
I was iffy about posting an issue report about this since it only happens with AA enhancements enabled. But there was interest in looking into it when I mentioned it on Discord.

**Comment by stenzek** [comment]
Gonna say this is "won't fix", because resolving the msaa target to update the framebuffer is a necessary step. D3D11 can't do partial MSAA resolves either, so it's copying the whole framebuffer even only a tiny bit of it is modified.

Vulkan can do a partial resolves and may not exhibit such a slowdown. But I don't recommend using MSAA anyway in the first place, since it breaks too many games.
