### ISSUE TITLE
Audio clipping in South Park (USA)

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#248]
There's a noticeable crackle in South Park whenever you hit a turkey with a snowball (occasionally doesn't seem to occur when you hit multiple in a row in quick succession).

[SLUS-00936_2020-04-07_22-45-23.wav.zip](https://github.com/stenzek/duckstation/files/4448481/SLUS-00936_2020-04-07_22-45-23.wav.zip)

**Comment by stenzek** [comment]
As best I can tell this is just how the game is... But please comment/re-open if the issue does not occur on console.
