### ISSUE TITLE
Tomb Raider Music Issue

### ISSUE THREAD

**Issue by MufasaFasagan** [stenzek/duckstation#2482]
Tomb Raider
SLES-00024
Verified by Redump.org

**Description of the issue / bug**
Tomb Raider (also TR2) music does not loop.

**Steps to reproduce**
Once the music has changed track it doesn't go back to the previous one or when you discover a secret, it will play the "secret" music track, but will not go back to the background music.

**Hardware/software**
i5 4570
Radeon R9 380
Vulkan

Emulator version
0.1-4599 Preview Build

**Comment by stenzek** [comment]
Invalid. This is not an issue with the emu, it's a bug in the game and happens on console. Please test issues like this on console before making bogus reports.

This one in particular is asked every couple of weeks and I'm a little tired of it.
