### ISSUE TITLE
SLUS-00270 (Wing Commander IV) Disc 1 incorrectly flagged as European release

### ISSUE THREAD

**Issue by prietveld** [stenzek/duckstation#2484]
**Game details**
SLUS-00270 Wing Commander IV - The Price of Freedom - Disc1

**Description of the issue / bug**
In the Game List, this game shows a European region flag in stead of a US flag. Disc 2, 3 and 4 do show the correct US flag. Tried with several different images.

**Steps to reproduce**
Add the disc image to a folder that is scanned by DuckStation and look at the Game List.

**Hardware/software**
Windows 7x64

**Emulator version**
0.1-4599-ga542fa85 (dev)

**Comment by andercard0** [comment]
Same as related here: #1460 and here #1487 

🤔 SLUS-00270 - http://redump.org/disc/7599/

**Comment by stenzek** [comment]
Could you right click -> properties in the game list and screenshot it? Or, give the **executable** hash shown (HASH-XXXXXXXX), I'll need it to correct the database entry.

**Comment by prietveld** [comment]
Sure, that is HASH-CFEB84E6E4C6260B

**Comment by stenzek** [comment]
Looking into it, this isn't actually a bug, or incorrect entry in the database. The region string on the disc for this game is Europe/PAL. So, a mastering error on their part.

(the flag is displayed based on the region string on the disc itself, not from the database)
