### ISSUE TITLE
Color theme

### ISSUE THREAD

**Issue by shikulja** [stenzek/duckstation#2488]
1. Add a theme for qt that better matches the windows theme. Now there is a gray theme, it is good, but still there is a slight dissonance in it.
2. Add a light theme with Pastel colors to the nongui version, add auto-selection of a light/dark theme depending on system settings.

**Comment by stenzek** [comment]
> Add a theme for qt that better matches the windows theme. Now there is a gray theme, it is good, but still there is a slight dissonance in it.

Use the default/native theme (first option in list).

> Add a light theme with Pastel colors to the nongui version, add auto-selection of a light/dark theme depending on system settings.

Not really interested in doing this. Nogui is intended for TVs, not desktops.
