### ISSUE TITLE
[Feature Request] Consider to add AMD FidelityFX Super Resolution (FSR) support in DuckStation ?

### ISSUE THREAD

**Issue by Tikilou** [stenzek/duckstation#2489]
**Is your feature request related to a problem? Please describe.**

It's not related to a problem but AMD FSR (FidelityFX Super Resolution) add the possibility for any harware platform/OS to a good upscaling with less CPU/GPU ans so much less energy than a native resolution (HD, 4K...)
AMD FSR use spatialization (Nvidia DLSS use vectorisation), for example, RPCS3 emulator have implemented it recently. [https://wccftech.com/new-tools-allow-amd-fsr-injection-in-rpcs3-emulator-and-potentially-in-every-game/]

**Describe the solution you'd like**
It could be a good solution for better performances on high resolution for many devices, and less energy consumption on laptop, or others devices with battery.

**Describe alternatives you've considered**
No other alternative

**Additional context**
No Additional context

**Comment by stenzek** [comment]
I'm not sure it would be very beneficial here. I believe it also requires specific input resolutions, and PS1 render at all kinds of different resolutions internally.
