### ISSUE TITLE
Wizard's Harmony (Japan) instantly hangs after BIOS with error about logic seeking

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#249]
![Capture2](https://user-images.githubusercontent.com/31968468/78752607-ba4ff600-79b7-11ea-8ad3-4ac95f47dcf4.PNG)

**Comment by kurayami6** [comment]
Still happens as of the latest version.

**Comment by stenzek** [comment]
Fixed by https://github.com/stenzek/duckstation/commit/466e4099d42960a97105bbdf9e61a87269402e8d
