### ISSUE TITLE
Final Fantasy 7  slowdown issue, halfspeed at waterfall+finaldescent

### ISSUE THREAD

**Issue by meesbaker** [stenzek/duckstation#2493]
**Game details**
[SCUS-94164+SCUS-94165, USA]

**Description of the issue / bug**
[Inside waterfall scene before fighting diamond weapon after bugenhagen uses the Ancient Key in disc2+Final Platforms before Jenova Synthesis in disc3 have a slowdown issue. It is  the same thing that happens on the PC version. There is an fmv playing in the background in those scenes and fmvs in ff7 run in 15fps whereas normal field speed is 30fps. The overlapping makes everything go in half speed. The music still plays normally fast and the emulator still reports to run in 60fps but the movement of the character is slowed down to half the normal speed. Same as textboxes or anything else happening in field in those scenes. Normally this only occurs on pc version but not on console because ps1 can handle multiple framerates on the screen. Playing on console or other emulators this slowdown problem does not occur but unfortunately in Duckstation it does.]

**Controller Troubleshoot Report**
The issue has nothing to do with my controller, it works fine. I use a ps3 controller, xinput driver in retroarch.

**
**Hardware/software**
[HP Z400 , Intel Xeon W3680@6*4ghz , NVIDIA GTX 1060 8GB RAM]
[Vulkan but the issue happens in all renderers and all possible emulator settings]

**Emulator version**
[1.90 Duckstation Core in RetroArch]

The issue can be seen on this video: 
https://youtu.be/utcT7vXX724

Waterfall Glitch at 6:26:30, Final. Platforms at 6:57:10

**Comment by stenzek** [comment]
Not going to do anything about this unless you provide a save file
