### ISSUE TITLE
Final Fantasy 7 Slowdown Issue at Waterfall and Final Descent 

### ISSUE THREAD

**Issue by meesbaker** [stenzek/duckstation#2494]
Game details
[SCUS-94164+SCUS-94165, USA]

Description of the issue / bug
[Inside waterfall scene before fighting diamond weapon after bugenhagen uses the Ancient Key in disc2+Final Platforms before Jenova Synthesis in disc3 have a slowdown issue. It is the same thing that happens on the PC version. There is an fmv playing in the background in those scenes and fmvs in ff7 run in 15fps whereas normal field speed is 30fps. The overlapping makes everything go in half speed. The music still plays normally fast and the emulator still reports to run in 60fps but the movement of the character is slowed down to half the normal speed. Same as textboxes or anything else happening in field in those scenes. Normally this only occurs on pc version but not on console because ps1 can handle multiple framerates on the screen. Playing on console or other emulators this slowdown problem does not occur but unfortunately in Duckstation it does.]

Controller Troubleshoot Report
The issue has nothing to do with my controller, it works fine. I use a ps3 controller, xinput driver in retroarch.

**
Hardware/software
[HP Z400 , Intel Xeon W3680@6*4ghz , NVIDIA GTX 1060 8GB RAM]
[Vulkan but the issue happens in all renderers and all possible emulator settings]

Emulator version
[1.90 Duckstation Core in RetroArch]

The issue can be seen on this video:
https://youtu.be/utcT7vXX724

Waterfall Glitch at 6:26:30, Final. Platforms at 6:57:10

The attached virtual memory card holds a save right before waterfall screen. Its for disc2 (SCUS94164). The waterfall screen can be entered from the save directly by running left after loading. Then the game will receive the slowdown.

[savefile.zip](https://github.com/stenzek/duckstation/files/6956058/savefile.zip)

**Comment by Nucleoprotein** [comment]
This looks exactly as on HW:
https://youtu.be/fu9V0yW9mjc?t=9170

I remember that too from my playthrough.

**Comment by meesbaker** [comment]
Im not sure if thats just an accuracy thing. Look at the second example final descent. PS1 doesnt go THAT slow. I think the ps1 footage is just performance there. Its slightly stuttery but its not a halfspeed slowdown like on pc version due to the fmv 15fps cut. Try to play waterfall on ps1 with textspeed setting at maxi and mash through and compare it will be faster. And check out final descent in disc3 i know that console doesnt go half speed there. The platforms are a bit more performant on ps2slim yes, but its not just an innaccurcy thing. I have never played on an emu that goes half speed there.

**Comment by stenzek** [comment]
Maybe because the other emus are wrong then? I'll need something more quantifiable before I spend time debugging this.

**Comment by Nucleoprotein** [comment]
I think that difference results from GPU/GTE timings that other emus not emulate properly.

**Comment by stenzek** [comment]
GTE should be the same on PS2, but the GPU will have different timings, absolutely. It's still a little surprising though, duckstation's gpu timings are approximated and should be too fast, not too slow.

**Comment by stenzek** [comment]
I think this is working as intended. PS2 slim uses emulation for the CPU (MIPS on PPC), so it's going to have the same accuracy problems as older PS1 emulators. They don't properly emulate the timings for the CPU, so it ends up slower in some places, and fater in others.

DuckStation matches the video @Nucleoprotein linked. It's also running internally at 20fps, not 15 (the cutscene runs at 15):
![image](https://user-images.githubusercontent.com/11288319/128815435-8a3da5cf-8e02-4c6a-a69c-efca19144cdd.png)


I don't have the time at the moment to port the save over to my console to check, but I'd expect it to behave the same. If you can confirm this on a **PS1 console**, then I'm happy to reopen.
