### ISSUE TITLE
no vibration on xbox series x controller connected with bluetooth to android

### ISSUE THREAD

**Issue by greatwroth** [stenzek/duckstation#2495]
Connecting a new xbox wireless controller ([share button in the middle](https://www.xbox.com/en-us/accessories/controllers/xbox-wireless-controller)) to my android 10 phone over bluetooth when I attempt to set the vibration device it says "The selected device does not support vibration." Doing the same using a usb cable it works as intended.

**Comment by andercard0** [comment]
> 
> 
> Connecting a new xbox wireless controller ([share button in the middle](https://www.xbox.com/en-us/accessories/controllers/xbox-wireless-controller)) to my android 10 phone over bluetooth when I attempt to set the vibration device it says "The selected device does not support vibration." Doing the same using a usb cable it works as intended.

Invalid. issue template not filled.

**Comment by stenzek** [comment]
That's because the driver doesn't support it. Bring it up with your device manufacturer, it won't work in any game.

Also, no support is provided for the android app

**Comment by greatwroth** [comment]
Thank you. But FYI there is no issue template in the project readme or wiki and google is not helping.
