### ISSUE TITLE
I suggest to delegate some parts to speed up development. 

### ISSUE THREAD

**Issue by olsongleb** [stenzek/duckstation#2496]
It would be possible to allow individuals to approve edits in separate sections. After all, the site allows you to roll back changes at any time.
For example, there is a person who constantly uploads localization in his language, you can let him accept edits for localization for his language.
Or there is another person who is well versed in some kind of graphical API, often suggests edits to this section of the code, you can allow him to independently approve his edits and accept from other people in this section.

I suggest allowing experienced people to independently contribute to the sections they understand. And allow them to approve / reject edits from other people to "their" sections. 

Then in the section "issues" there will be only those that really require the attention of the author, the development time will be reduced. And maybe someday there will be time to add support for playstation 2 =)

**Comment by olsongleb** [comment]
For example, right now 5/12 "pull requests" are about localization

**Comment by stenzek** [comment]
Trying to tell me how to run my own project is quite rude. Yes, almost all pull requests are translation, because nobody else is working on the actual source.
