### ISSUE TITLE
[Libretro] A Few Controller Settings Have Different Defaults Than Stand Alone

### ISSUE THREAD

**Issue by Awakened0** [stenzek/duckstation#2497]
**Description of the issue / bug**
Here are the defaults that differ in libretro from standalone:

Controller (1-8) Force Analog on Reset = On
Controller (1-8) Use Analog Sticks for D-Pad in Digital Mode = On
Controller (1-8) Vibration Bias = duckstation_Controller1.XScale

**Steps to reproduce**
Just comparing the latest stand alone Win64 build settings with the latest libretro one. These options are hidden unless you select DualShock as your controller type. Pressing spacebar sets each option to default in RetroArch if you've changed them.

**Emulator version**
Stand alone: 0.1-4599-ga542fa85
libretro: 0.1-4645-g879ba6ca

**Additional context**
Not sure if any of these are intentional differences from stand alone. "Force Analog on Reset" doesn't seem safe to have on by default, since it breaks input in the BIOS. And the "Vibration Bias" default is a weird value that looks like a bug. That setting also has another non-numerical value, "Scales X coordinates relative to the center of the screen.".

**Comment by stenzek** [comment]
Working as intended, since you can't bind the analog toggle in libretro (no way to expose custom buttons), auto mode is enabled by default.
