### ISSUE TITLE
My game crashes after opening

### ISSUE THREAD

**Issue by felipeses** [stenzek/duckstation#2498]
Initially everything was perfect. After some games crashed, I tried to open it again (emulator) and saw that the txt contacted this:

ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 0000000010003654)
0000000010003654 (EZFRD64): (filename not available): DllCanUnloadNow
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 0000000010001B2A)
0000000010001B2A (EZFRD64): (filename not available): DllCanUnloadNow
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFCBE2E2811)
00007FFCBE2E2811 (WINMM): (filename not available): PlaySoundW
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFCC7D07034)
00007FFCC7D07034 (KERNEL32): (filename not available): BaseThreadInitThunk
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFCC9D02651)
00007FFCC9D02651 (ntdll): (filename not available): RtlUserThreadStart

Can someone help me?

Latest version.

My config: 
Intel G5400
GT 1030
8gb ram

**Comment by stenzek** [comment]
This is a support issue. You'll need to upload the full crash dump. It's probably a buggy controller driver.
