### ISSUE TITLE
Main menu of Pajama Sam - You Are What You Eat (USA) is broken at higher resolution with OpenGL

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#250]
D3D11 and Software look fine.

![Capture](https://user-images.githubusercontent.com/31968468/78789056-f8690c00-79ef-11ea-8783-89bf262ab829.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/78789125-0dde3600-79f0-11ea-87b9-0f5966b001ce.PNG)

**Comment by stenzek** [comment]
Might need to use the geometry shader for lines...

**Comment by stenzek** [comment]
Forgot to update this issue - please re-test, GL uses the geometry shader for lines now, same as D3D if your driver supports it (most desktops should).

**Comment by kurayami6** [comment]
Fixed.
