### ISSUE TITLE
The ability to run games from zip, 7z, rar archives 

### ISSUE THREAD

**Issue by olsongleb** [stenzek/duckstation#2500]
**Describe the solution you'd like**
When the checkbox "load image into RAM" is checked, unpack it into RAM and run from there.

**Describe alternatives you've considered**
If there is no checkbox “load image into RAM”, unpack it into a temporary directory of the operating system and run from there.

**Comment by CookiePLMonster** [comment]
https://github.com/stenzek/duckstation/issues/2499#issuecomment-896390100

**Comment by stenzek** [comment]
Stop requesting features without using the search feature. I'm getting tired of it, there's been too many in the last few days, and I'm going to start blocking people if it continues.

> No. Duplicate of #620. Quoting myself:
> 
> > The main issue is archive formats are not "seekable". In other words, you can't say "I want to read offset 2352 from file xyz" without decompressing the whole thing first.
> > Creating an "index" may be possible, then you can seek to the closest "block" and decompress from there. The other alternative is just to decompress into memory first, which I'll probably add when I add the option to preload disc images to RAM.
> > zip should be doable as I already ship zlib. RAR most likely no, because of license concerns. 7z, perhaps, depending on whether I pull in the libraries for the auto-updater when I write that.
> > My best advice would be to just use chd. It's compatible with most of the big-name emulators now, and compresses better than archive formats anyway.
> 
> > I still don't like this idea.
> > What happens if there's multiple files in the zip? Which one to load?
> > These would have to be cached on disk somewhere - where do we cache it? How many games do we save?
> > Honestly this just seems like a way for pirates to be lazy with their downloaded games, which is not the point of the emulator. Compressed disc formats work much better.

**Comment by CookiePLMonster** [comment]
> I will wait for this function:

CHD still makes this function useless.

**Comment by stenzek** [comment]
No, you won't, because I'm not adding this feature. It's completely useless and flawed.
