### ISSUE TITLE
Support for subchannel reading in chd format

### ISSUE THREAD

**Issue by Sanaki** [stenzek/duckstation#2502]
**Is your feature request related to a problem? Please describe.**
Currently, when loading a chd that contains subchannel data, the load fails if an sbi file is not present as well. The subchannel data is not considered at all. Since one of the common reasons people will use chd is the desire to reduce everything down to one file, this behavior runs contrary to that goal.

**Describe the solution you'd like**
If the loaded chd has subchannel data present, that data is used and the requirement for the sbi file is lifted. This likely ties in strongly with #1229 in terms of implementation requirements.

**Describe alternatives you've considered**
Usage of sbi files works fine, and qualifies as a viable alternative, but an inherently less optimal one.

**Additional context**

Steps to produce the chd in question:
1. Get a Redump-verified bin+cue dump of a LibCrypt protected game. I used Ape Escape (Europe) due to the ability to quickly validate functionality (cursor won't move on title screen if subchannel read fails). Get the sbi from Redump as well.
2. Use [SBITools](https://github.com/Kippykip/SBITools/releases/latest) on a Windows system (wine is not sufficient for this tool) with the `-cue2ccd` flag to produce a ccd+img+sub.
3. Use [Aaru](https://github.com/aaru-dps/Aaru/releases/latest) to convert the ccd to toc via `aaru i convert -f game.ccd game.toc`
4. Use chdman to convert the toc to chd via `chdman createcd -i game.toc -o game.chd`

**Comment by stenzek** [comment]
Last time I checked chdman doesn't actually use the subchannel data from the dump, unless this has changed?

Also, it would break the "missing SBI" detection.

**Comment by Sanaki** [comment]
It includes the subchannel data, yes. The only supported input format with subchannels is toc though, hence the somewhat roundabout conversion chain up there. When extracting back to cue, it'll actually yell at you about not being able to extract the subchannels because of it. I'm aware of the SBI detection being an issue at that point, but the same would need to be addressed for ccd+img+sub (issue linked above). That said, I don't expect this to be any sort of priority. To my knowledge, no emu has implemented it yet. Other than perhaps MAME, but I have no working knowledge of how it handles LibCrypt stuff.

**Comment by stenzek** [comment]
> I'm aware of the SBI detection being an issue at that point, but the same would need to be addressed for ccd+img+sub (issue linked above).

Incorrect - we can simply detect the presence of the .sub file, and throw the error if it doesn't exist (for libcrypt games). This isn't possible (afaik) for CHD, since there's no indication to whether the CHD was created with subchannel data, or it was autogenerated.

**Comment by Sanaki** [comment]
Ah, I see what you mean. The metadata shown provides that indication. SUBTYPE will be NONE if no subchannel data is present.

**Comment by stenzek** [comment]
Hrm, okay, I'll have to double-check on my end when I have time.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/e739c114a47edc43d140ec683f62877f1d7365b2
