### ISSUE TITLE
Add option to display CPU speed (overclock/underclock) to bottom ribbon/ screen

### ISSUE THREAD

**Issue by TomMattinson** [stenzek/duckstation#2504]
Currently the emulator speed is visible on the lower ribbon, and can optionally be displayed over the game feed. It would be useful for it to be possible to display the CPU speed in the same way, for verification purposes. (Ideally this along with other information on the Console Settings tab), similarly to how many things from other tabs are selectable in the Display Settings tab.

**Comment by stenzek** [comment]
I don't really see the benefit of this. Too much information => overload and nobody will look at it anyway.
