### ISSUE TITLE
Wipeout XL/2097 - "Firestarter" Track not playing

### ISSUE THREAD

**Issue by Hari-82** [stenzek/duckstation#2505]
**Game details**
SCUS-94351 Wipeout XL (USA)

**Description of the issue / bug**
in Wipeout XL I cannot select the Prodigy's track "Firestarter". the other tracks seems to play fine, is just that one missing (witch is the only one that I want to play with...). 

I tried multiple disc images. At first I was thinking it was due to the CHD file that I was using but then it doesn't work with a freshly downloaded multitracks bin+cue.
I also mounted the cue file on a virtual drive and played it with a music player (foobar2000) and it plays all the tracks fine including Firestarter-

**Steps to reproduce**
you can check this in the option menu in-game, in the sound settings on the bottom there is a track selector and when I set Firestarter it will plays something else.

**Hardware/software**
Windows 10, i5-6400, GTX 960
Hardware - OpenGL

**Emulator version**
0.1-4599-ga542fa85(dev)

**Additional context**
Same issue in stand-alone and with the Retroarch core. 
in RA with beetle HW and SW the track is there and it works fine...

**Comment by bslenul** [comment]
Dunno if it's useful or not but when switching to that track it spams this for like 8 lines: `E(ExecuteCommand): Invalid/out of range seek to 00:00:8C` and it just keeps playing the current track.

Tested on the US version, MD5s verified against Redump database, "Reed/Seek Speedup" set to "None".

**Comment by Goblan** [comment]
Same here. Duckstation 0.1-4669-g15b14202 (master) running on Windows 10. That track won't play no matter what.

**Comment by larwood** [comment]
Can confirm on my setup as well. Firestarter track won't play with Duckstation but with ePSXe it does.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/18241978ea056a81ff9847f0ad89658f886153ea.
