### ISSUE TITLE
Duckstation theme menu Font/Colors transparent

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#2510]
**Game details**
Not related

**Description of the issue / bug**
After change theme the menu got messy/transparent (?)

**Steps to reproduce**
Run duckstation normally go to settings > theme set it to Default or white.
After, settings > click in any menu in the left to the right as showed in the video below:

https://streamable.com/pc4vxs
In the given example, it's happening only when I change theme > Default and Fusion.

Example affected (fusion theme)

![image](https://user-images.githubusercontent.com/43047877/129496501-169bc862-1042-462a-adcd-447c2ea46c86.png)

**Enhancements information**
Not related

**Hardware/software**
Not related

**Emulator version**
Preview Latest - 0.1-4661-g64abbd64 

**Additional context**
Nothing.

**Comment by stenzek** [comment]
Fixed with https://github.com/stenzek/duckstation/commit/15b14202467437b3710a541e598517ca9a959f6b.
