### ISSUE TITLE
(Android) Auto-load PPF doesn't work

### ISSUE THREAD

**Issue by 6lackmag3** [stenzek/duckstation#2514]
**Game details**
Tested on Castlevania SOTN [SLUS-00067] ([Quality Hack](https://www.romhacking.net/hacks/3606/)) and Darkstalkers 3 [SLUS-00745] ([Uncensored Hack](https://www.romhacking.net/hacks/5659/)).

**Description of the issue / bug**
Auto-apply image patches feature's not working. 

**Steps to reproduce**
Place .ppf in the game folder and name it accordingly to image filename. Turn on 'Apply Image Patches' in advanced settings. Start a new game.

**Enhancements information**
No enhancements used, fast boot off.

**Hardware/software**
realme XT, Snapdragon 712, Android 10 64bit.

**Emulator version**
0.1-4646

**Additional context**
This also applies to DuckStation libretro core as well.

PS: It's an insignificant bug really. Please don't bother with it any time soon, Stenzek. Thanks for your time and effort.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/e45f15ef41fd608c6e214cee2a0708a5b4b5e50c, but I'm not sure when I'll push a new android build yet.
