### ISSUE TITLE
Tomb Raider Greatest Hits not working

### ISSUE THREAD

**Issue by F3arM3** [stenzek/duckstation#2515]
**Game details**
[SLUS-00152 Tomb Rider, (USA)]
[i.e SLUS-00404 Ace Combat 2 (USA)]

**Description of the issue / bug**
[When I try to load Lara's home or load the game itself I get a black loading screen, when I try loading the ninja demo I get a loading screen that fills up but doesn't go away, and the tomb raider 2 demo does load but when I pause it freezes]

**Steps to reproduce**
[just try to load any section of the game other than the menus]

**Enhancements information**
[Make sure they are all turned off before report, Yes]

**Hardware/software*
[If desktop, your AMD Ryzen 7 1700 eight-Core Processor, Radeon (TM) RX 480 Graphics, and 19043.1110]
[GPU Renderer - D3D11/OpenGL/Vulkan, all 3 have this issue]

**Emulator version**
[DuckStation 0.1-4599-ga542fa85 (dev)]

**Additional context**
[Add any other context about the problem here]

**Comment by stenzek** [comment]
You have a bad dump most likely

**Comment by F3arM3** [comment]
Ok, I'll try dumping it again tomorrow

**Comment by F3arM3** [comment]
I dumped it again using imgburn and at 1x/8x speed and it still didn't work

**Comment by bslenul** [comment]
Doesn't seem to be an issue with DuckStation:

Ninja demo:

![image](https://user-images.githubusercontent.com/33353403/129800732-61b0f712-82a5-43f7-8233-5d507a0f1f72.png)

Lara's home:

![image](https://user-images.githubusercontent.com/33353403/129800753-e3f61192-c8b2-4ae3-8f50-c068a4159890.png)

**Comment by F3arM3** [comment]
Weird, my disk is in really good shape, but I am dumping another game at the moment to test to see if it is my setup, and if the game works I'll try dumping tomb raider again

**Comment by F3arM3** [comment]
Ok, I tried resident evil 1 dualshock (SLUS-00747) which does work and you can probably add to the compatibility list, and am now dumping tomb raider for a 3rd time

**Comment by F3arM3** [comment]
Still doesn't work, I am going to try a full 3d game, Soul Reaver and see if it has issues with full 3d games

**Comment by stenzek** [comment]
You're probably not dumping with a cue sheet/toc. TR needs the audio tracks.

Regardless, this is a support issue, not a bug.
