### ISSUE TITLE
Linux binary in /usr/local/bin: failed to load text font failed to aquire host display

### ISSUE THREAD

**Issue by rcampbel3** [stenzek/duckstation#2516]
**Game details**
emulator generic when built from source on Linux Ubuntu 20.04 and try to run as standalone binary

**Description of the issue / bug**
I've been building duckstation from source on Ubuntu 20.04 for months every week or so, copying over duckstation* to /usr/local/bin and running it. Today, after building I noticed that I am unable to run the binary standalone -- it runs, and GUI renders, but I get the following two error messages when I try to run a game:

failed to load text font
failed to acquire host display

when I run ./duckstation-qt from the build/bin dir, everything works.

Is there some file or set of files that I can copy to ~/.local/share/duckstation/ somewhere so that I can run it as a standalone binary again? This was working for me for many months.

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open? no
2. Which controller backend are you using in general settings - SDL?

**Note:**
If you are using Duckstation on Android device please consider the following before report:
Are you using any kind of "memory optimizer" program such as: Ccleaner, Wisecleaner, Clean Master, Boost Android etc. ?
(if so, please, consider create an exception on it first and test; or even remove / uninstall it retest and then, if the problem persists continue with the report.

**Steps to reproduce**
[Try to provide as much detail as possible to reproduce the issue]

Build from latest source on Ubuntu 20.04
copy binaries to /usr/local/bin
attempt to run the outside of source tree

**Enhancements information**
emulator works when run from build dir ... so, it's not an enhancement issue

**Hardware/software**
Ubuntu 20.04 x64
i7 cpu
Nvidia GeForce 1060
using vulkan renderer

**Emulator version**
Duckstation 0.1-4669-g15b14202 (master)

**Comment by stenzek** [comment]
That's because it's missing its data files? Of course it won't work.

Stop trying to wedge duckstation into linux distributions's silly directory structures. It's designed to be run out of a single self contained directory.

**Comment by BailShamber** [comment]
@rcampbel3 for applications that are meant to be ran from a self contained directory it should be done like that:
`/usr/lib/duckstation/`  < this has the binary and other files
`/bin/duckstation-qt` < this should be a symlink to `/usr/lib/duckstation/duckstation-qt`
At least that's how firefox does it on at least debian and ubuntu.
btw I have tested and it works.

**Comment by stenzek** [comment]
If anything it probably should be in /opt. IMO it doesn't belong in the system directories, since those are maintained by the package manager. If you want to launch it from anywhere, symlink it in /usr/local/bin.

**Comment by rcampbel3** [comment]
ok, yeah I could do that or write a wrapper script that runs it from the build directory, but my point is that it was working as a standalone binary not that many commits ago, and ultimately, there should be a 'make install' option that does a systemwide install and puts files needed by duckstation in system directories like /usr/share/duckstation .
