### ISSUE TITLE
[Feature Request] "Dump audio" function similar to Dolphin

### ISSUE THREAD

**Issue by NintendoManiac64** [stenzek/duckstation#2518]
**Is your feature request related to a problem? Please describe.**
Not really, I'm just looking for a way to get the music from the PS1 version of BattleTanx: Global Assault (it doesn't show up as a music CD in the likes of foobar2000).

**Describe the solution you'd like**
A "dump audio" function just like it exists in Dolphin whereby it dumps the audio to an LPCM WAV file of whatever sample rate and bit depth the game engine outputs to before the console itself does any resampling (at least I _think_ that's what Dolphin is doing as it's the only way I can think of to explain why using the "dump audio" on F-Zero GX results in a wacky sample rate that's something like 29kHz IIRC despite the ADX music files in F-Zero GX being 44.1kHz and the GameCube's DAC hardware being locked to 48kHz output).

**Describe alternatives you've considered**
Ripping the music files directly from the disc, but the game in question (BattleTanx: Global Assault) is not identified by music CD ripping software unless I'm doing something wrong.

**Additional context**
While the N64 version of BattleTanx: Global Assault is generally regarded as the better version of the game, I wanted to at least get a copy of the much higher-fidelity music from the PS1 version of the game.

**Comment by stenzek** [comment]
Not possible in a generic way. Games use different audio formats.

You can dump audio from the debug menu, if you want individual channels, you can do that by uncommenting this line and compiling yourself: https://github.com/stenzek/duckstation/blob/18241978ea056a81ff9847f0ad89658f886153ea/src/core/spu.h#L10

**Comment by NintendoManiac64** [comment]
> Not possible in a generic way. Games use different audio formats.

Could you elaborate what you mean?  Using Dolphin as a reference, it's built-in "dump audio" function works regardless of whether the game uses OGG Vorbis music, BRSTM ADPCM music, or real-time synthesized music.

**Comment by stenzek** [comment]
>  its built-in "dump audio" function works regardless of whether the game uses OGG Vorbis music, BRSTM ADPCM music, or real-time synthesized music.

Which is exactly what duckstation's audio dumping does.

**Comment by NintendoManiac64** [comment]
> Which is exactly what duckstation's audio dumping does.

...then maybe I'm blind, because I very much looked to see if any such audio dumping existed and I was not able to find it in the GUI (and yes, I was using the latest 2021-07-31 release).

Care to direct me to its location?

**Comment by stenzek** [comment]
Debug menu. You need to enable it in advanced options. This is turning into a support issue and not a bug request.
