### ISSUE TITLE
User Setting For 8MB RAM cannot be set back to default

### ISSUE THREAD

**Issue by ll811** [stenzek/duckstation#2519]
**Description of the issue / bug**
Changing settings on a per game basis in the properties menu allows you to cycle between 3 options on/off and then a setting that just follows whatever general emulation setting you have on. If you turn on the 8mb ram setting there's no way to set it back to its default state, clearing the gamesettings.ini or deleting it does not solve this issue either. You're now stuck with either having this on or off and a permanent gear icon will display on the games list for that game. 

**Steps to reproduce**
1. right click game then click properties
2. go to user settings (console) 
3. turn on 8MB RAM (Dev Console) and hit close 
4. you can no longer set it back to its default. 

**Hardware/software**
Windows 10
**Emulator version**
0.1-4599-ga542fa85 (dev)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/1081c132cf8f949c0410065cb74cc4647a704085
