### ISSUE TITLE
Gameplay in 102 Dalmations (USA) extremely shaky

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#252]
Once you enter the first level, moving around makes the screen extremely shaky. Standing still results in no shake. Performance seems to impact it, but it still happens even at full speed.

**Comment by HeroponRikiBestest** [comment]
Here is video capture of the issue.
[2020-04-08_22-08-41.mkv.zip](https://github.com/stenzek/duckstation/files/4452638/2020-04-08_22-08-41.mkv.zip)

**Comment by stenzek** [comment]
Fixed by GPU timings from what I can tell.

**Comment by stenzek** [comment]
Should be fixed in latest master.
