### ISSUE TITLE
Switching to Vulkan backend is now causing issues?

### ISSUE THREAD

**Issue by Dustinbed** [stenzek/duckstation#2521]
**Description of the issue / bug**
When I first downloaded the emulator, I was able to use the Vulkan backend without issues.  I recently tried to start up a game and got the "Failed to create host display device context" and "Failed to acquire host display" error messages.  I'm able to open qt version but the nogui version crashes on open.  

**Steps to reproduce**
If I go into the display setting and change the renderer to Vulkan, I experience the above issues.  Any other renderer works fine but at a lesser framerate.  

**Hardware/software**
AMD Ryzen 7 4800H Processor, NVIDIA GTX 1660Ti, Windows 10

**Emulator version**
0.1-4599-ga542fa85 (dev)

**Additional context**
The weirdest part is that I was able to use the Vulkan renderer before but something changed at some point, I'm not sure what, and made it not work.

**Comment by stenzek** [comment]
Support issue, not a bug
