### ISSUE TITLE
Fix matching \ identification of images

### ISSUE THREAD

**Issue by shikulja** [stenzek/duckstation#2528]
1. If the volume label is erased in the image, then the identification by the cover hash works, if there is a volume label, or it is changed, then the hash determination does not work.

![image](https://user-images.githubusercontent.com/3386359/129883482-180a7888-121f-4748-a9c4-bb87e564d355.png)

2. In the cheat code manager, hash detection does not work at all.

3. Refuse to use, matching image files by file name. It's comfortable, but over time, this will cause many problems. 
When everyone will name the images, and the covers and cheat codes for them, whatever they want, because of this, the collection will have to be manually edited if people will share their work. Unassociating by name manually will determine the correct naming of the files.

**Comment by shikulja** [comment]
it may be related to the 1. problem. haven't checked yet.
if there are two images, the original slus-xxx and the modified one. then the cover is taken for slus-xxx for both images, although the cover is explicitly specified for the second (modified image) by hash

**Comment by stenzek** [comment]
This is working as intended, the hash is only used when a matching serial isn't found.

You can use the file title for the covers instead.

**Comment by shikulja** [comment]
@stenzek
i want to leave this as a future request. this requires some work, especially matching images and cheats if the hash is explicitly specified instead of the name or label of the image

**Comment by stenzek** [comment]
I'm not planning on changing it. Pull requests are welcome if you want to do it.
