### ISSUE TITLE
JumpStart Wildlife Safari (USA) Color difference on loading screen sprites

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#253]
on both software an opengl, the blue on the loading screen sprites is different from the darker blue loading screen background. If you start on opengl, then switch to software, this is fixed. If you start on software, switching between backends doesn't fix the issue.
![image](https://user-images.githubusercontent.com/50224630/78833729-34758000-79a2-11ea-8a89-0982ccffd188.png)
On opengl, before switching to software
![image](https://user-images.githubusercontent.com/50224630/78833827-5f5fd400-79a2-11ea-8fc7-84d47ff7650c.png)
On opengl, after switching to software

**Comment by kurayami6** [comment]
Still an issue as of the latest version. The letters on the first screen also look broken. Notice how the bottom of the top row is squashed and the top of the words "Jumpstart" are cut off?

![Capture](https://user-images.githubusercontent.com/31968468/85938654-8ea73100-b952-11ea-882c-392c5f7614db.PNG)

**Comment by Shideravan** [comment]
Not sure if this is really a bug or just something that we cannot see in original hardware due to low resolution and use of tube monitors with less color range. Maybe a test with original hardware is desirable.

**Comment by stenzek** [comment]
Can't seem to see any difference here on the latest builds.
