### ISSUE TITLE
8BitDo SN30 Pro+ in Dinput mode: cannot bind Z Rotation axis

### ISSUE THREAD

**Issue by prietveld** [stenzek/duckstation#2530]
**Description of the issue / bug**
When binding controls in 'controller settings' for an Analog Controller (DualShock), I am unable to bind the Z Rotation axis of my SN30 Pro+ controller in SDL mode, or ANY button or axis in Dinput mode. 

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open? - No.
2. Which controller backend are you using in general settings - SDL and Dinput.

**Steps to reproduce**
- Start the SN30 Pro+ in Dinput mode with Start+B (required in Windows 7 to have wireless functionality).
- Confirm all buttons and axes working via Devices and Printers > Game Controller Settings (all work).
- Try to bind Z Rotation axis (right stick y) in DuckStation:
-- with SDL backend: vertical axis movement isn't picked up. Horizontal axis (or any other button or axis) is picked up.
-- with Dinput backend: none of the buttons or axes are picked up at all.

**Hardware/software**
Windows 7x64

**Emulator version**
0.1-4599-ga542fa85 (dev)

**Additional context**
Note that in Xinput mode on Windows 10 the controller does work as expected.

**Comment by PugsyMAME** [comment]
Duckstation does NOT officially support Windows 7, in the main it works but I repeat WIndows 7 is not officially supported so don't report bugs with it. Just be glad it works as well as it does.

You've stated above that it works in Windows 10 so you already have your solution.

**Comment by prietveld** [comment]
Too bad, but fair enough

**Comment by stenzek** [comment]
Windows 7 is not supported. I only support OSes which still have support from their vendor, and Win7 has been out of support for over a year.
