### ISSUE TITLE
Minor graphical bug in sorcerer's stone when widescreen hack is paired with geometry correction

### ISSUE THREAD

**Issue by F3arM3** [stenzek/duckstation#2531]
**Game details**
[SLUS-01415 Harry Potter and the Sorcerer's Stone (USA)]

**Description of the issue / bug**
[When running Sorcerer's stone in widescreen with geometry corrections on, fires can sometimes cause random lines to appear, especially noticeable in Gryffindor common room]

**Steps to reproduce**
[All you need to do is use widescreen hack and geometry corrections (it being checked off is enough to make it happen) and stand in  front of the common room fire]

**Enhancements information**
[Make sure they are all turned off before report, I have them on because they are causing the bug]

**Hardware/software**
[AMD Ryzen 7 1700 eight-Core Processor, Radeon (TM) RX 480 Graphics, and 19043.1110]
[GPU Renderer - D3D11/D3D12/OpenGL/Vulkan Visible in all, but especially in D3D12 and Vulkan]

**Emulator version**
[0.1-4599-ga542fa85 (dev)]

**Comment by PugsyMAME** [comment]
You need to read the text before you carry on raising a new issue, I refer you to points 2, 3 and 4 below that you have just flagrantly ignored:-

Please read before creating a new issue:

1. Make sure there is not already an open issue for this bug.
2. All enhancements **must** be off. To quickly disable all enhancements with affecting your normal config, in advanced options you can check "Disable All Enhancements".
3. All advanced options **must** be at their default values.
4. No cheats may be active. If you were using cheats, they should be disabled, and the game rebooted before reporting the bug.

**Comment by F3arM3** [comment]
I am sorry if it came off as me ignoring it and if I caused any trouble, but I just wanted to point out this issue in case somebody decides to make these functions better but I did not see anywhere that I could mention it for any future improvements.

**Comment by BloodRaynare** [comment]
I think to report issues about enhancement you can use #427.

**Comment by F3arM3** [comment]
Thank you
