### ISSUE TITLE
Game title shows %20 in place of blank/space character in Android 11 phone

### ISSUE THREAD

**Issue by StarryWindy** [stenzek/duckstation#2535]
**Description of the issue / bug**
When I open DuckStation on Android 11 phone, and I put some game playlist for multi-disc titles like Gran Turismo 2 (USA), the game title will show as Gran%20Turismo%202%20(USA). This issue is carried over to the game cover and memory card related to the multi-disc playlist that they share the same %20 in the name (renaming them with proper space character won't work).

**Steps to reproduce**
Simply run DuckStation on Android 11 phone while having the multi-disc game playlist on the directory.

**Hardware/software**
Vivo V20 with Snapdragon 720G, Android 11

**Emulator version**
DuckStation for Android 0.1-4568-gd2e12f31

**Additional context**
I think this issue may have to do with how the paths are handled on Android 11, because I didn't see such issues on my Android 10 phone.

**Comment by stenzek** [comment]
Should be fixed in https://github.com/stenzek/duckstation/commit/7eceee6a2003be3e597724221fc3c3578758c30f, but I'm not sure when I'll do another Android release.
