### ISSUE TITLE
support for multiple mice and the choice of input devices 

### ISSUE THREAD

**Issue by olsongleb** [stenzek/duckstation#2536]
**Is your feature request related to a problem? Please describe.**
multiplayer does not work in quake2 using two gamepads and two mice 

**Describe the solution you'd like**
so that multiple mice can be used and that a specific device can be selected 

1a -- controller
1b -- controller
1c -- ps mouse
1d -- ps mouse

it is necessary to configure the second "ps mouse" to the second real device "mouse" 
![изображение](https://user-images.githubusercontent.com/71244842/130038889-e9afdf05-c787-4c62-9c7b-1fe24119477c.png)

now both players are controlled by one real mouse

**Comment by stenzek** [comment]
No, this was discussed here https://github.com/stenzek/duckstation/discussions/2112

**Comment by olsongleb** [comment]
There is **no** need to draw a second cursor, it works by reading the device. And, yes, the code will be platform dependent. This question is about compatibility with games, I gave the example above. I understand that there is no time. But I hope that if someone writes such support in the future, the edits will be reviewed.
