### ISSUE TITLE
Loading times when opening doors in Resident Evil 2 are shorter than on real hardware.

### ISSUE THREAD

**Issue by Newtype14** [stenzek/duckstation#2539]
**Game details**
SLUS-00748 & SLUS-00756 Resident Evil 2 - Dual Shock Ver. (USA)
Also tried the Japanese version and it was the same.
Hashes are the same as on Redump.

**Description of the issue / bug**
I'm not sure if this is even an issue. It's more of a question that I have.
Loading times when opening doors in RE2 are twice as fast as on real PlayStation hardware.
I would simply like to understand why.

**Steps to reproduce**
All enhancements are disabled, but I do know that loading times when opening doors in RE2 are affected by CD-Rom emulation. The higher either your read or seek speed is, the faster the load times will be. They're both set to "None".

Doors in old RE games are actually hidden loading times and I believe the loading time begins AFTER the door animation, when the screen is black for a few seconds. What I do is I start a playthrough of the Leon A scenario and make it to the first door (takes about 12 seconds to get to).

On a real PS1 (I don't own one but I've seen playthroughs of speedruns), the screen stays black after the door animation for about 2.86 seconds while the game is loading.

On another emulator that I use, Beetle PSX HW, the loading time is exactly the same.

On Duckstation, the loading time is halved! Every door loading time in the game is twice faster.

I'm just wondering why it's faster on Duckstation.

**Hardware/software**
CPU: Intel i7-8700k
GPU: NVIDIA GeForce 1070 TI
OS: Windows 10 Enterprise LTSC 1809
GPU Renderer: Vulkan (Same thing happens on all the others)

**Emulator version**
0.1-4599-ga542fa85 (dev)
I also tried the Retroarch core of Duckstation and it was the same.

**Comment by stenzek** [comment]
Loading times will differ between consoles. Duckstation's model matches my console. I don't care what beetle does, it's definitely not accurate (it doesn't consider the track jumps)
