### ISSUE TITLE
Robbit mon Dieu/Jumping Flash 3 (Japan) Weird grid objects on OpenGL

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#254]
When playing on OpenGL, weird grid-like patterns appear across the level plane in the void
![image](https://user-images.githubusercontent.com/50224630/78834898-2163af80-79a4-11ea-8b4d-3bd895364594.png)
on software (how it should look):
![image](https://user-images.githubusercontent.com/50224630/78834920-2a548100-79a4-11ea-8dd5-375d6774e1d0.png)

**Comment by HeroponRikiBestest** [comment]
Fixed on latest version.

**Comment by HeroponRikiBestest** [comment]
Apparently this is still broken on Direct3d, I can't test that myself though.

**Comment by JoshShabel** [comment]
Fixed on direct3d.

**Comment by HeroponRikiBestest** [comment]
Fixed on Direct3D.
