### ISSUE TITLE
Add CDI file support

### ISSUE THREAD

**Issue by matheuswillder** [stenzek/duckstation#2540]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Is your feature request related to a problem? Please describe.**
Looking through my old backups I found a few games that were ripped in this file format. I know it's not a usual format for PlayStation games but I found that PCSX-Reloaded can emulate them without the need to mount them, but I can't find any other more modern emulator that can use this format.

**Describe the solution you'd like**
Add support for the CDI file format if it is relevant enough.

**Describe alternatives you've considered**
I can't find much information about this format, only that it is created by [DiscJuggler](https://en.wikipedia.org/wiki/DiscJuggler) and besides PCSX-Reloaded only few other free software can open it, [here a list](https://en.wikipedia.org/wiki/Comparison_of_disc_image_software).

**Additional context**
Although PCSX-Reloaded can emulate it without the need to mount the image, the PCSX ReARMed core in RetroArch cannot.

Sorry if this issue is duplicated or irrelevant. And thank you if this can be considered.

**Comment by stenzek** [comment]
I don't see the need to support formats which aren't really used. I'd never heard of this format before now. If it's widespread I'd reconsider.

**Comment by matheuswillder** [comment]
Ok I understand. Thank you for the excellent emulator.

**Comment by andro13s** [comment]
Some games I downloaded are in this format.

**Comment by PookaMustard** [comment]
> Some games I downloaded are in this format.

Unless you own the original game in some form or shape, pirated games are not supported ;)

**Comment by 6lackmag3** [comment]
I thought CDI/GDI are used for DC disc images.

**Comment by matheuswillder** [comment]
@6lackmag3 I think the format was mostly used in the past and so still possible to find PS1 games ripped in this format too. I've found some open source programs that can handle CDI files (e.g. [Aaru Data Preservation Suite](https://github.com/aaru-dps/Aaru)) and as @stenzek doesn't plan on supporting it on DuckStation them when I have more free time I'll try to use it to use my backups.
