### ISSUE TITLE
"Tomb Raider II (Italy)" - SLES-00107 incorrectly named as "Euro Demo 01 (Europe)"

### ISSUE THREAD

**Issue by l0r3n2o** [stenzek/duckstation#2544]
Game has the correct code SLES-00107 but is incorrectly named in the Title section

**Comment by stenzek** [comment]
Need the hashes for both to correct the database entry (from game properties).

**Comment by l0r3n2o** [comment]
It appears that the CDs have the same Serial but different hashes according to Redump.

![1](https://user-images.githubusercontent.com/61325790/130323248-53ffcec9-fa57-4a90-975c-c8ba8b0fe759.jpg)
![2](https://user-images.githubusercontent.com/61325790/130323249-9d954b1c-54ea-4c8e-ad77-4ff680685b53.jpg)

**Comment by bslenul** [comment]
* Tomb Raider II - Starring Lara Croft (Italy): SLES-00107 / HASH-B3C0A02D27EEBB8
* Euro Demo 01 (Europe): SCES-00107 / HASH-AAD8E924C9D6759C

**Comment by l0r3n2o** [comment]
- Euro Demo 01 (Europe): SLES-00107 / HASH-B3C0A02D27EEBB8
But the game is Tomb Raider II
![immagine](https://user-images.githubusercontent.com/61325790/130324960-cacbc724-9694-4a9b-9814-a4aca37a4221.png)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/95ccf82ff67774eac250fcd7d2b59c470ce73241
