### ISSUE TITLE
Change Discs Automatically

### ISSUE THREAD

**Issue by DJRM2021** [stenzek/duckstation#2548]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Is your feature request related to a problem? Please describe.**
As an arcade cabinet maker, Having duckstation to change discs automatically (Example, Metal Gear Solid) will be awesome.

**Describe the solution you'd like**
Whatever multi-disc game may it be, there's always a screen in-game that prompts the player to change to disc 1/2/3/4/5 etc., and press start (or any button). I would like the emulator to automatically detect if the game is already asking for a change of disc and it should be able to load the next correct disc.

**Describe alternatives you've considered**
a hotkey mechanism that can be bound to the emulated PS1 controller. Example, to change to disc 2, press select + triangle, for disc 3, press select + circle, and so on.

**Additional context**
Probably we can start off the solution by checking the game ids and disc #'s? Pretty much the same as how the Dolphin emulator finds the next correct disc from the game list.

**Comment by stenzek** [comment]
No, how would the emu know that the game is requesting a disc change?

> a hotkey mechanism that can be bound to the emulated PS1 controller. Example, to change to disc 2, press select + triangle, for disc 3, press select + circle, and so on.

There's already a change disc hotkey.
