### ISSUE TITLE
Graphics in Disney's Treasure Planet are completely broken in all renderers 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#255]
OpenGL

![SCUS-94647_2020-04-09_11-44-34](https://user-images.githubusercontent.com/31968468/78849408-bffd1880-7a57-11ea-9c07-912b4ca416eb.png)

Software

![SCUS-94647_2020-04-09_11-44-49](https://user-images.githubusercontent.com/31968468/78849420-c9868080-7a57-11ea-97ed-ab3610a75a27.png)

D3D11

![SCUS-94647_2020-04-09_11-44-59](https://user-images.githubusercontent.com/31968468/78849437-cee3cb00-7a57-11ea-9d61-a6b5d5529271.png)

**Comment by HeroponRikiBestest** [comment]
The European version returns a different error screen.
![image](https://user-images.githubusercontent.com/50224630/78852586-98fc0380-79d1-11ea-95c0-2f3df7b4f3de.png)

**Comment by stenzek** [comment]
Seems to be an MDEC issue.

**Comment by kurayami6** [comment]
Still completely broken as of the latest version.

**Comment by kurayami6** [comment]
Fixed as of the latest version.
