### ISSUE TITLE
C-12: Final Resistance

### ISSUE THREAD

**Issue by JackWhiteX** [stenzek/duckstation#2550]
Good afternoon. Very much I ask you to add an inversion of the right analog stick for this game. Thank you very much.

**Comment by andercard0** [comment]
> 
> 
> Good afternoon. Very much I ask you to add an inversion of the right analog stick for this game. Thank you very much.

Invalid issue template not filled will be closed soon!

**Comment by JackWhiteX** [comment]
Found a problem with the control in the game: no inversion of the right analog device. How to fix it?

**Comment by JackWhiteX** [comment]
Понятно. Запомню на будущее, что обращаться к разработчикам со своими просьбами данного эмулятора БЕСПОЛЕЗНО.
