### ISSUE TITLE
[libretro] Add Core Option Catagories

### ISSUE THREAD

**Issue by Awakened0** [stenzek/duckstation#2551]
**Is your feature request related to a problem? Please describe.**
DuckStation is an option rich emulator, so navigation would benefit greatly from the libretro API's new core option category support. The latest point release of RetroArch (1.9.8) supports it. Each category gets it's own submenu in the core options menu.

**Describe the solution you'd like**
Add categories to the libretro core's options. They could probably use similar categorization to the fullscreen UI standalone has. There's a small instruction paragraph about how to add them [here](https://github.com/libretro/RetroArch/tree/master/libretro-common/samples/core_options#adding-core-option-categories), and [template files here](https://github.com/libretro/RetroArch/tree/master/libretro-common/samples/core_options/example_categories).

**Describe alternatives you've considered**
The existing giant list of options isn't so bad once you get used to it, but it'd certainly be quicker to navigate with submenus.

**Additional context**
Here's an example screenshot:
![cats](https://user-images.githubusercontent.com/4565863/130375550-eda9b21d-0ae7-41a1-9e7c-80b8885bb5f5.png)

**Comment by stenzek** [comment]
Implemented in 3d43f4aaa8f19bb02ae30f76f31e8865d6e32787. Everything is in categories, because otherwise it ends up all over the place order-wise.

**Comment by Awakened0** [comment]
Thank you!
