### ISSUE TITLE
[Settings] The "Show Enhancement Settings" option appears to be non-functional

### ISSUE THREAD

**Issue by dftf-stu** [stenzek/duckstation#2552]
**Game details**

[N/A - this issue relates to the DuckStation app itself]

**Description of the issue / bug**

The "Show Enhancement Settings" option in Settings > Advanced Settings... > Tweaks/Hacks list appears non-functional.

**Steps to reproduce**

1. Launch _DuckStation_ on Windows
2. On the **Settings** menu, click **Advanced Settings...**
3. Under the "**Tweaks/Hacks**" heading, un-tick the "**Show Enhancement Settings**" option
4. Click the **[Close]** button, then close _DuckStation_ completely
5. Launch a new instance of _DuckStation_
6. Go back into the Settings and note that the category "Enhancement Settings" in the left-hand list is still present, and selectable

**Enhancements information**

[N/A to this issue: this bug does not relate to a game, but the app itself]

**Hardware/software**

OS: Windows 10 Home (64-bit) Version 21H1 (OS Build: 19043.1165)
GPU Renderer (Settings > Display Settings > Renderer) mode: "Software"

**Emulator version**

0.1-4687-g4848c724 (master) - "Preview" update channel

**Additional context**

1. The official Wiki page (https://www.duckstation.org/wiki/Settings) offers little information at this time
2. As far as I know, there is no official or unofficial manual (e.g. a PDF) for _DuckStation_
3. I did a _Google_ search for _duckstation "show enhancement settings"_, but it found no results

**Screenshot**
As per the attached screenshot: when "Show Enhancement Settings" is un-ticked, the "Enhancement Settings" page within the "DuckStation Settings" dialog is still visible, and selectable.  Logically, I would assume when you untick a setting called "Show Enhancement Settings" that the "Enhancement Settings" area should become hidden.  While I could be misunderstanding what this option does, the lack of any official help for the "Tweaks/Hacks" area (hovering-over, or clicking on, any option offers no help-text at the bottom of the dialog) means I can only attempt to make a logical-deduction, based on the setting's name.

![DuckStation_ShowEnhancementSettingsNonFunctional](https://user-images.githubusercontent.com/83965343/130522824-263b1b9d-a045-4bb1-aa69-e82e3ae4c02b.png)

**Comment by stenzek** [comment]
Works fine here. It shows the enhancements in the bottom right corner while the game is running.

**Comment by dftf-stu** [comment]
If course it works there... because you know what it does.

I didn't, and it's not explained anywhere, so how am I, like most-other users who come-across it, supposed to know what it does?  As I say, there is no in-app help for it, it's not on the Wiki and even a Google search finds nothing.

"It's been discussed on Discord", I'm sure you'll say.  It may surprise some, but not everyone in the world uses it, you know!  Some in-app help text would be nicer...

**Comment by stenzek** [comment]
> "It's been discussed on Discord", I'm sure you'll say. It may surprise some, but not everyone in the world uses it, you know! Some in-app help text would be nicer...

Pull requests are welcome. But otherwise, this isn't something I'm interested in doing myself.
