### ISSUE TITLE
[Settings] Add some help-text for the "Tweaks/Hacks" items

### ISSUE THREAD

**Issue by dftf-stu** [stenzek/duckstation#2553]
**Is your feature request related to a problem? Please describe.**

If a user goes into Settings > "Advanced Settings..." they will see a scrollable-list of settings under the heading "Tweaks/Hacks".
Unlike in most areas of the _DuckStation_ settings, if they were to hover-over, or click-on, any of these settings, no help-text is given at the bottom of the dialog (in the text-field above the "Restore Defaults" and "Close" buttons) to explain what any of them do.

**Describe the solution you'd like**

When a user hovers-over (or clicks on) any of these options, provide some text below about what that setting actually does.

**Describe alternatives you've considered**

1. I have tried the official Wiki (https://www.duckstation.org/wiki/Settings) but this is very-incomplete, as-of-now
2. I have tried _Google_ searches, putting particular settings "in quotes" to exact-phrase match, but most yield no-results
3. I have tried to see if any manual for _DuckStation_ exists, such as a PDF file, but all I can find are unofficial, third-party forum posts or websites with "getting started" type guides

**Additional context**
As per screenshot: click on, or hover-over, any of the settings in this area and no further details will be provided at the bottom of the dialog to explain what they do

**OS version**
Windows 10 Home (64-bit) Version 21H1 (OS Build: 19043.1165)
Renderer: "Software"

**App version (from titlebar)**
0.1-4687-g4848c724 (master) - "Preview" update channel

![DuckStation_TweaksHacksNoHelpText](https://user-images.githubusercontent.com/83965343/130524707-2bb70d0a-62b6-43da-ba08-1522763d056e.png)

**Comment by stenzek** [comment]
Nope. There's a reason they're in that section, you're not meant to mess with them if you don't know what you're doing.

**Comment by dftf-stu** [comment]
With respect, how can you expect anyone to ever "know what [they're] doing" if you never explain what they do to begin with?

Surely for such settings you could at-least explain them on the Wiki site?
