### ISSUE TITLE
[Game List] PS2 game-images are not filtered-out

### ISSUE THREAD

**Issue by dftf-stu** [stenzek/duckstation#2554]
**Is your feature request related to a problem? Please describe.**

Oddly, if you have both PS1/PSOne/PSX roms and PS2 disc-images/ISOs/ROMs in the same folder (or within the same recursive folder-structure) then _DuckStation_ will actually list every PS2 game it finds in the Game List...!

**Describe the solution you'd like**

Surely these should be filtered-out, either based on the game's code (e.g. a "SCES" or "SLUS" that is out-of-known-range) or the size of the file -- no PS1 single-disc game would ever be 4GB in size.

**Describe alternatives you've considered**

Well, I could always just move the PS2 games into a folder that _DuckStation_ won't recursively scan into, of course! ;)
But I thought it would be interesting to report this nonetheless as I was still surprised this would even be a thing!

**OS and Renderer info**
Windows 10 Home (64-bit) Version 21H1 (OS Build 19043.1165)
"Software" renderer

**App version**
Version: 0.1-4687-g4848c742 (master)
Update Channel: "Preview"

**Additional context**
See screenshot for examples of three PS2 games which get listed in the "Game List" / "Game Grid" area:

![DuckStation_PS2GamesVisibleInBrowser](https://user-images.githubusercontent.com/83965343/130526626-75b7cdec-f8fb-4ef7-b6e2-cf2ffbf6c767.png)

**Comment by stenzek** [comment]
Multi disc pbp files can be beyond 700mb.

Don't put PS2 and PS1 games in the same directory. Problem solved.

**Comment by dftf-stu** [comment]
_PBP files are particularly easy with PS1 games, because they can hold multiple tracks and discs in a single file_

Huh, guess I learnt something new there.  I've **never** encountered that format before -- I've only ever had multi-disc games presented with each disc as a separate file, such as "Oddworld - Abe's Exoddus - PAL (Disc 1 of 2)".

Fair enough, then!
