### ISSUE TITLE
Garbage on the screen in Elder Gate (Japan)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#256]
Happens with all renderers.

![SLPM-86494_2020-04-09_13-44-51](https://user-images.githubusercontent.com/31968468/78856155-42da9f00-7a69-11ea-848a-6be8f221ddfc.png)

Beetle PSX for comparison

![Elder Gate (Japan)-200409-134858](https://user-images.githubusercontent.com/31968468/78856170-538b1500-7a69-11ea-9ad7-800849453850.png)

**Comment by kurayami6** [comment]
Still happens as of the latest version.

**Comment by stenzek** [comment]
Fixed with the latest timing changes.
