### ISSUE TITLE
Cannot get Rumble to work with MGS1

### ISSUE THREAD

**Issue by l3gi0n0fh3ll** [stenzek/duckstation#2567]
**Game details**
SLUS-00594 Metal Gear Solid (Disc 1) (v1.1).cue

**Description of the issue / bug**
I am using a PS2 controller with [this adapter](https://www.amazon.ca/Controller-Adapter-Converter-Compatible-Playstation/dp/B07GJCCF2T/ref=sr_1_7?dchild=1&keywords=ps2+to+pc+adapter&qid=1630351087&sr=8-7). I do not get any vibration effects in MGS1, even after enabling it in the in-game options ... there is also a vibration test in the options which does not work... All the other buttons work as expected. here are my settings: 

https://i.ibb.co/FYW145q/controller.jpg

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open? **NO**
2. Which controller backend are you using in general settings: **Analog Controller (DualShock)**

**Emulator version**
**0.1-4599-ga542fa85 (dev)**

**Comment by 6lackmag3** [comment]
Enable 'Force Analog Mode on Reset'. Otherwise gamepad will start in digital mode. Also try different controller backend.

**Comment by l3gi0n0fh3ll** [comment]
For the **Analog Controller (DualShock)** I enabled 'Force Analog Mode on Reset' ... but I still do not get any vibration ...
I tried the **Digital Controller** backend and the vibration settings doesn't even show up in the game....

I have two different PS2 controllers and both have this problem...

**Comment by 6lackmag3** [comment]
@l3gi0n0fh3ll
That's not backend it's controller type. You can find controller backend in general settings.
Perhaps adapter doesn't provide power needed for vibration. Some reviews also say vibration is not supported with this one.

> I tried the **Digital Controller** backend and the vibration settings don't even show up in the game....

**Comment by stenzek** [comment]
Support issue not a bug...

**Comment by l3gi0n0fh3ll** [comment]
I tried a Logitech F510 both in Dinput and Xinput mode changed the controller backend to Dinput and Xinput...I still do not get vibration in the game....

I also tried a Philips USB controller....no luck....Am I doing something wrong ? I tried 4 controllers and none of them work...

**Comment by 6lackmag3** [comment]
@l3gi0n0fh3ll 
I use Logitech F710 gamepad among others and vibration works absolutely fine for me. Make sure you install official drivers for your gamepads.
Also you need to bind gamepad for rumble feature in Controller Settings/Port 1. It's under axis bindigs.

**Comment by l3gi0n0fh3ll** [comment]
Ok, I got the Logitech to work... 

When the backend is Dinput the first controller that you setup is registered as **Controller0** .
When the backend is Xinput the first controller that you setup is registered as **Controller1**.

Is this info right ?

**Comment by 6lackmag3** [comment]
@l3gi0n0fh3ll if it works for you then it's ok I think.
I'm using SDL by default and gamepad is registered as Controller0.
Btw my F710 is in XInput mode (there's a D/X switch on the upper side).
