### ISSUE TITLE
Anti piracy warning screen in Pax Corpus (Europe) is broken in all renderers 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#257]
Here's what it looks like on screen.

![Capture](https://user-images.githubusercontent.com/31968468/78861891-5261e400-7a79-11ea-94e1-6d399693a8c7.PNG)

And here's what it looks like If I take a screenshot.

![SLES-00953_2020-04-09_15-44-26](https://user-images.githubusercontent.com/31968468/78861944-6dccef00-7a79-11ea-90d1-c89b05b1feba.png)

**Comment by stenzek** [comment]
Please retry on latest master when it builds.

**Comment by kurayami6** [comment]
Fixed. By the way, you might want to tell whoever is still working on Beetle PSX how you fixed it since it's still broken in that emulator. 

![Capture](https://user-images.githubusercontent.com/31968468/79037125-c46d3100-7c11-11ea-94f9-90665eb94ffd.PNG)

**Comment by stenzek** [comment]
It likely works in beetle's software renderer. It'd just be the hardware renderers where they don't handle the wrap-around of VRAM addresses correctly.
