### ISSUE TITLE
Nintendo Pro Controller Support for Android

### ISSUE THREAD

**Issue by vectorcr** [stenzek/duckstation#2572]
\Type: Feature request

Description: I would like to be able to use a Nintendo Pro Controller to play games on the DiskStation. I paired the controller and noticed that the application is not registering any of the inputs. I used other emulators and games on my device and they are able to read the inputs for the controller without any issues. 

Alternatives: None 

Additional Context:
Device: Redmi Note 10 Pro
OS: Android 11 (MIUI 12.5) 
Controller: Nintendo Pro Controller
Connection: Bluetooth

**Comment by 6lackmag3** [comment]
Have you tried mapping buttons manually in Controller settings?

**Comment by vectorcr** [comment]
Closing this request, I just found out that this is an isolated issue with the accessibility features on Android 11 on some carriers. Please disregard. USB method does work normally. More information here on the android 11 issues 
https://issuetracker.google.com/issues/163120692?pli=1
