### ISSUE TITLE
High CPU% in CronoCross will cause the battle cursor to disappear.

### ISSUE THREAD

**Issue by agentoranger** [stenzek/duckstation#2574]
SLUS-01041 ChronoCross USA

ChronoCross in battle cursor disappears at High CPU%

As we know, ChronoCross performs exceptional well with a high CPU%, this grants the ability to run up to 60 fps in battle and on the field.  The game is not bound directly the CPU so high fps is possible at a normal gamespeed.  High CPU%, like 500% is required to keep the game running at 60 fps thru all of the battle animations that one might experience.  Even slice-and-dice experiences an fps slowdown at 350%, which is low enough to solve some, but not all of the cursor disappearance issues when running at high cpu%.  This is certainly an exceptional experience when running at high CPU%.

**Steps to reproduce**
Set ChronoCross too 350% to 500% CPU.  When in battle, the cursor will disappear when in the initial dream sequence and during other parts of the game.

**Enhancements information**
I have some enhancements enabled, but in the spirit of running CronoCross, this is the best possible experience for this title.  I know its not commonplace to hunt down these kind of bugs, but it would be a boon to ChronoCross players to see this issue considered for resolution.

NTSC-U, CPU 350% - 500%, 2xSSAA, TrueColor, xBR, PGXP/Cull/Tex

**Hardware/software**
Windows 10 10.0.19043.1165
Intel 6700k at 4.6Ghz
16 GB of DDR4 at 4100 MHz
GeForce 1080 at 1729Mhz

**Emulator version**
DiskStation  0.1.4703-g5b3c7072

**Additional context**
This issue appears to be bound to the CPU%, the lower the CPU% the less the issue occurs thought high CPU% of around 500% is required to maintain 60/60.

I am happy to help in any way that I can.

Thanks for considering, have a nice evening.

**Comment by stenzek** [comment]
Not a bug. Of course overclocking breaks games, that's why there's a warning on startup.

**Comment by BailShamber** [comment]
This is not an emulator bug or problem, it's the game code that isn't meant to run on a faster than stock cpu clock, the game itself has to be hacked and edited which has nothing to do with the emu.
