### ISSUE TITLE
UWP Builds Broken - Won't Launch

### ISSUE THREAD

**Issue by Nun-z** [stenzek/duckstation#2577]
**Game details**
[Serial Code, Region]
[i.e SLUS-00404 Ace Combat 2 (USA)]
Not applicable/all games.

**Description of the issue / bug**
[Describe what you are seeing and/or hearing during gameplay]
The UWP build is broken, as it closes before launching.  Everything after and including this commit (https://github.com/stenzek/duckstation/commit/4f190aa90200b16cde004f316edf75800ededbdd) produces broken UWP builds, and all UWP builds before it work properly.  Actually, unless I'm mistaken, when I just revert that one commit, it seems to work.

**Controller Troubleshoot Report**
Not applicable.

**Note:**
If you are using Duckstation on Android device please consider the following before report:
Are you using any kind of "memory optimizer" program such as: Ccleaner, Wisecleaner, Clean Master, Boost Android etc. ?
(if so, please, consider create an exception on it first and test; or even remove / uninstall it retest and then, if the problem persists continue with the report.

**Steps to reproduce**
Install the latest UWP Duckstation app to your Windows PC.  Then, try to launch it.  You will see that it closes by itself after a minute or so of loading.

**Enhancements information**
[Make sure they are all turned off before report]
Not applicable.

**Hardware/software**
[If Android, which phone and Android version]
[If desktop, your CPU, graphics card, and operating system]
[GPU Renderer - D3D11/OpenGL/Vulkan]
UWP -> Tested on Windows 10 PC.  Details here: https://gist.github.com/Nun-z/899eaf9451f9a61182daecad14cc56ca

**Emulator version**
[Shown in the title bar of the emulator]
All versions of the emulator after the commit was made.

**Additional context**
[Add any other context about the problem here]

**Comment by Nucleoprotein** [comment]
UWP build is for XBOX, not supported on Windows.

**Comment by Nun-z** [comment]
The issue also occurs for Xbox.

**Comment by mansoor909** [comment]
Tested on xbox series x
Both versions have been tested
1-Latest Preview Build Note: It crashes after booting
2-Latest Development Build  Note: it works just fine

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/a4358240ad244ac372107e725c026a89b5fc9381
