### ISSUE TITLE
Super Gals! Kotobuki Ran Special - Ikemen Get You Gals Party (Japan) instantly hangs after BIOS 

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#258]
It stays on a black screen forever while the BIOS sound loops. If I turn on "Show VRAM" I can see a bit of the graphics.

![SLPM-87135_2020-04-09_16-25-00](https://user-images.githubusercontent.com/31968468/78864426-f0a47880-7a7e-11ea-8aee-5a49457349b7.png)

**Comment by stenzek** [comment]
Broken due to current timer behavior. Firing timer IRQs when target and counter == 0 gets the game to boot. Need to research how it actually behaves here and when the comparison happens.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/ef97131c9d778547c9dbed0a566ded20f555fb4f
