### ISSUE TITLE
Castlevania Symphony of the Night level texture flicker as you move from upscaling.

### ISSUE THREAD

**Issue by wpninja2** [stenzek/duckstation#2584]
**Game details**
[Serial Code, Region]
[SLUS-00067GHA Castlevania Symphony of the Night US]

**Description of the issue / bug**
[Many of the level areas the floor and ceiling textures violently flicker as you move "Tested on 2 different pc's".  
Geometry Correction was not used. You really start to notice it at the end of Alchemy labs and Marble Gallery, you really can't miss it.]

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?-Drivers are up to date and I only have steam open when I am playing a game off it.

2. Which controller backend are you using in general settings-Digital Controller / Actual Controller-PS2 Duel Shock 2 with a usb attachment off ebay for $5, best $5 I have ever spent.

**Note:**
If you are using Duckstation on Android device please consider the following before report:
Are you using any kind of "memory optimizer" program such as: Ccleaner, Wisecleaner, Clean Master, Boost Android etc. ?
(if so, please, consider create an exception on it first and test; or even remove / uninstall it retest and then, if the problem persists continue with the report. -
I have Ccleaner and always mark my gaming software as ignore/exceptions

**Steps to reproduce**
[Like said in the title the bug is caused by upscaling the internal res, the further past 1x it goes the worse it gets.
Just simply moving back and forth will make the ceiling and floor flicker like mad during many areas such as Alchemy labs later half and Marble Gallery
The only fixes I know is to set Downsampling to Box or click the box that says Integer Upscaling]

**Enhancements information**
[Technically is an enhancement bug]

**Hardware/software**

[2 PC's that were used
HP Laptop
CPU-7400u Intel I7 GPU-Nvidia 940m 2 gig gpu chip

Asus Rog Desktop
CPU-9700f Intel I7 GPU -ASUS Turbo Geforce 2070 Super]
[GPU Renderer - Both D3D11]

**Emulator version**
[0.1-4599-ga542fa85 (dev)]

**Additional context**
[This "is" an enhancement bug due to upscaling which seems like the only fix is to crop the image in some way. I can only hope that it will be possible to properly upscale this game with future updates.]

**Comment by stenzek** [comment]
Issues with enhancements are not bugs...
