### ISSUE TITLE
Bindings are not saved per Controller Type

### ISSUE THREAD

**Issue by Blackbird88** [stenzek/duckstation#2586]
**Description of the issue / bug**
If you for example bind Playstation Mouse to PC Mouse LMB/RMB and then switch to DualShock then its Left/Right bindings will still be bound to PC Mouse instead of it "remembering" the original bindings you had before

**Steps to reproduce**
Bind something in one controller type and switch to different one. Bindings will be mixed like this, possibly due to them sharing names?
![image](https://user-images.githubusercontent.com/4414625/132141206-300d2669-6639-4879-8e8c-0ab7396e665c.png)

**Hardware/software**
Intel Core i7-10700K
Nvidia GeForce RTX 3070
Windows 10 64-bit (21H1)
XInput backend

**Emulator version**
![image](https://user-images.githubusercontent.com/4414625/132141253-90be4a4e-16e0-4a15-927e-a52c802b9660.png)

**Comment by stenzek** [comment]
Working as intended. The config keys used by bindings aren't unique for each controller type.
