### ISSUE TITLE
Duckstation is not compatible with my PS2 controller to USB adapter.

### ISSUE THREAD

**Issue by l3gi0n0fh3ll** [stenzek/duckstation#2587]
**Description of the issue / bug**
I recently bought [this](https://www.amazon.ca/HDE-Dual-Controller-Adapter-Converter/dp/B01J4JVFXI/ref=sr_1_14?dchild=1&keywords=ps2+to+usb&qid=1630878908&sr=8-14) adapter to be able to connect my PS2 controller to PC and use it in Dinput mode.
When I just plug in the adapter without installing any drivers, Duckstation works fine...
But when i install the drivers for the adapter, Duckstation closes itself just after launching it.
I really need to install the drivers, because without them the rumble function doesn't work.

EDIT: I just tried x360ce and it also closes itself with the drivers installed...works fine when the drivers are uninstalled.

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open? **No**
2. Which controller backend are you using in general settings: **Dinput**

**Hardware/software**
i5-6500
GTX 1080
Windows 10 pro

**Emulator version**
0.1-4599-ga542fa85 (dev)

**Comment by BloodRaynare** [comment]
Known issue with this kind of adapter, see #1560. To put it simply, the drivers are just too ancient (Basically only works until Win7, and IIRC even only works perfectly in 32-bit OSes).

**Comment by stenzek** [comment]
Broken drivers...

**Comment by l3gi0n0fh3ll** [comment]
Any adapters out there that work ? Or is there anyway to find a newer driver ?

**Comment by l3gi0n0fh3ll** [comment]
Apparently, The Dolphin devs fixed this issue ? 

Look [here](https://forums.dolphin-emu.org/Thread-dolphin-dev-builds-past-5-0-3977-crash-on-startup-with-my-controller-plugged-in) and [here](https://github.com/dolphin-emu/dolphin/pull/5582) . 

Here is my Event Viewer report: 

> Faulting application name: duckstation-qt-x64-ReleaseLTCG.exe, version: 1.0.0.1, time stamp: 0x6136b6d8
> Faulting module name: EZFRD64.DLL, version: 0.0.0.0, time stamp: 0x50ac9aa9
> Exception code: 0xc0000005
> Fault offset: 0x0000000000002203
> Faulting process id: 0x1fc0
> Faulting application start time: 0x01d7a405a1a55d67
> Faulting application path: B:\DuckStation\duckstation-qt-x64-ReleaseLTCG.exe
> Faulting module path: C:\Windows\USB_Vibration\081001\EZFRD64.DLL
> Report Id: d2147e47-09e7-446b-9eb5-3e450f128b94
