### ISSUE TITLE
1080p 5x integer vertical crop

### ISSUE THREAD

**Issue by TheRealYasri** [stenzek/duckstation#2588]
**Is your feature request related to a problem? Please describe.**
When you select 5x on a 1080p screen there are black borders at the top and bottom.

**Describe the solution you'd like**
Option to crop x pixels at the top and bottom.

**Describe alternatives you've considered**
Tried 4x but not the best on a 1080p display.

**Additional context**
https://www.youtube.com/watch?v=m5X7_dpdWwM

**Comment by stenzek** [comment]
Don't use integer scaling then? There's also line cropping options in game properties.

**Comment by TheRealYasri** [comment]
I like to use 5x so it looks as nice as possible. Games of the PS1 era and before were made for crt displays so they were made with some dead space on the top and bottom for overscan to have some padding between different tv models.

The mister projects supports this officially on a lot of the home console cores and newer upscalers like retrotink 5x also support it.

What you do is 5x a 240p image to 1200, then chop off 60 on top and 60 on bottom to make it 1080. For 224 res at 5x its 10 pixels top/bottom. With a option to move the up or down a bit to aline it better.

Here is another article, please watch the video I posted in the original post.
https://www.retrorgb.com/retrotink5x-new-scanline-features.html

**Comment by Defreezer** [comment]
I'd like to see this implemented as well. Users would greatly benefit from a custom overscan cropping function for integer scaling.
