### ISSUE TITLE
[Feature Request] trilinear filtering

### ISSUE THREAD

**Issue by n1ghttrap** [stenzek/duckstation#2589]
I just find it looks better than bilinear for low res textures such as those on the PS1 and I imagine it's a trivial thing to implement.

**Comment by stenzek** [comment]
These requests are getting silly. PS1 has no mipmaps.

**Comment by n1ghttrap** [comment]
Why bother enhancing anything?  Why bother with the other texture options? It's your emulator and it's up to you what to implement, but maybe you should consider whether you want it publicly open for suggestion or not.  It's no 'sillier' than any other thing the PS1 doesn't do natively.

**Comment by n1ghttrap** [comment]
Apologies, I meant to say 3 point bilinear filtering.   Now I do indeed feel silly.
