### ISSUE TITLE
Castlevania - Symphony of the Night (USA) // Missing left part of the menu screen

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#259]
Some lines are missing on the left side of the screen.

On all the renderers -D3D, OGL and soft).
All crop options tested (even OFF).

![SOTN](https://user-images.githubusercontent.com/52127625/78885806-7f080280-7a5d-11ea-9ecf-08cb37b6a67b.jpg)

**Comment by stenzek** [comment]
Should be fixed on the latest build.
