### ISSUE TITLE
Road Rash is crashing

### ISSUE THREAD

**Issue by jpaulobf** [stenzek/duckstation#2594]
**Game details**
SLUS-00035 / HASH-435CD7BEE54D74A7, USA

**Description of the issue / bug**
Game crashs after playing a while

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
No
2. Which controller backend are you using in general settings
SDL

**Steps to reproduce**
Runs the game, play the simplest mode (trash mode), runs the first track (the city), play for a while until buildings start to be showed in red, than the emulator crashs.

**Enhancements information**
All off

**Hardware/software**
[If desktop, your CPU, graphics card, and operating system]
I5 11400f + GTX 1060 6GB + Win 10
D3D11

**Emulator version**
0.1-4714-g6c628bb8

**Additional context**
Run Trash Mode, first track (the city), you play for a while, then the buildings start to become red, and than, the emulator crash.

![1](https://user-images.githubusercontent.com/10994298/132383884-234867d7-e941-41cb-a782-81c87b84790f.png)

**Comment by BailShamber** [comment]
Btw the screenshot shows that you're using vulkan (which isn't necessarily an issue), but make sure you're able to reproduce this bug in dx11

**Comment by jpaulobf** [comment]
The problem is happening include with software render.

This wasn't happening in my previous version of emulator (about 2 months aged, but I don't know the exact version)

![2](https://user-images.githubusercontent.com/10994298/132400379-b20785f5-5df1-4e79-981c-a5ff6186fc2d.png)

**Comment by andercard0** [comment]
Mostly likely invalid, please provide a log file.

**Comment by jpaulobf** [comment]
I don't know where can I find the log file... Someone, help?

With this option enabled (disable all enhancements) the game runs normal.

![3](https://user-images.githubusercontent.com/10994298/132401708-00a67c8e-8c75-4512-a66a-801d7595c335.png)

**Comment by BailShamber** [comment]
Set the log level to "Debug" then play the game until the issue happens, then stop the game, and click tools from up top, and select "Open data directory", a folder will open and in it you will find a file called "duckstation.log", upload this file here.

**Comment by BailShamber** [comment]
@jpaulobf btw when the issue happens, do you get some areas where at least some buildings display correctly?

**Comment by BailShamber** [comment]
This could be produced with disc speed up (10x)
@jpaulobf go to console settings and set disc speed up to "None" and it should be fixed

**Comment by stenzek** [comment]
Why do you not read the warning displayed on startup that the disc speed enhancements will break games.......
