### ISSUE TITLE
Ogre Battle - Limited Edition audio looping

### ISSUE THREAD

**Issue by RadiantHero6** [stenzek/duckstation#2596]
**Game details**
Serial Code, Region
SLUS-00467 Ogre Battle: Limited Edition (USA)

**Description of the issue / bug**
Audio skipping/missing audio. When starting the game and choosing your tarot cards, music is meant to play but no music actually plays. During any fight scene, the music will loop again and again the first 2-3 seconds or so

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open? DGvoodoo V2 is installed, but was/is not on while using Duckstation.
2. Which controller backend are you using in general settings. General settings

**Steps to reproduce**
Start a new game, when the old man is pulling the tarot cards for the player, no music is playing. To test for battle music looping, finish the first map, as you encounter a fight at the end. When playing up to the second level and getting into a fight, the same issue happens again. 

**Enhancements information**
[https://imgur.com/a/8J1hzfJ]

**Hardware/software**
CPU: AMD Ryzen 7 2700X, GPU: Radeon RX 580 OS: Windows 10
GPU Renderer - D3D11/12

**Emulator version**
[https://imgur.com/a/SaASMgY]

**Additional context**
Video of bug in action here https://www.youtube.com/watch?v=7j1VLvYxpK4

Memory card at level two for quick setup and testing https://www.dropbox.com/s/iq6qesjfrmbn4qs/Ogre%20Battle%20-%20Limited%20Edition%20%28USA%29_1.mcd?dl=0

**Comment by andercard0** [comment]
Yeah, we have tested this earlier in Discord in other modes interpreter and so on no dice, issue is really weird. My copy is correctly verified too.
