### ISSUE TITLE
The new UI looks awful on 125% scaled screens

### ISSUE THREAD

**Issue by SecularSteve** [stenzek/duckstation#2598]
**Game details**
n/a

**Description of the issue / bug**
The icons simply look terrible if the scaling on your desktop isn't 1x.

**Controller Troubleshoot Report**
n/a

**Steps to reproduce**
Simply go to "Settings > System > Display > Scale and layout > Change size to 125%" on Windows 10/11

**Enhancements information**
n/a

**Hardware/software**
Laptop, Intel i5-4200 Dual Core 2.50 GhZ, Intel® HD Graphics 4600, Windows 10
GPU Renderer - D3D11

**Emulator version**
0.1-4714-g6c628bb8 (dev)

**Additional context**

![Capture](https://user-images.githubusercontent.com/33793273/132636223-734518a3-bd10-4b4e-8cdd-8e092d7c6f41.PNG)

**Comment by stenzek** [comment]
It's a qt bug. I fixed it in the source for 150% since that's what I use, but an unmodified qt has the same issue at 150% as well (it uses 1x instead of 2x icons and resizes with nearest neighbour)
