### ISSUE TITLE
Ape Escape crash

### ISSUE THREAD

**Issue by CometHunter92** [stenzek/duckstation#2599]
**Game details**
SCUS-94423 , Ape Escape (NTSC-U)

**Description of the issue / bug**
On linux arm 32 bit it crashes and shuts down when the player gets control of Skipe just at the beginning of the first level. When on interpreter mode it works and doesn't crash. 

**Steps to reproduce**
just open the game and enter the first level and it crashes when in recompiler mode

**Enhancements information**
all enhancements turned off, software renderer

**Hardware/software**
Raspberry Pi4/standalone and Retroarch core

**Emulator version**
don't know, it's the development version just before the last one, the one from end of july

**Additional context**
didn't try the standalone on windows

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/d2e90b051680cca78cfa1381894c6eaf5a143d72
