### ISSUE TITLE
Cyberwar (Japan) (Disc 1) instantly hangs after BIOS screen 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#26]
![Capture](https://user-images.githubusercontent.com/31968468/74499446-c7acaf00-4f37-11ea-9f53-54786e82e8eb.PNG)

**Comment by kurayami6** [comment]
Still hangs instantly as of the latest version.

![Capture](https://user-images.githubusercontent.com/31968468/76518396-27549680-64b3-11ea-81ec-e5badd96afbf.PNG)

**Comment by stenzek** [comment]
I have verified the fix for this game booting on console. However, now it gets stuck waiting for the SPU read bit to go high, which will be a separate issue. But, it gets past the first FMV with the DMA fix.

**Comment by stenzek** [comment]
Please retest on latest master.

**Comment by kurayami6** [comment]
It no longer crashes. Seems like it took a lot of work to fix. Thanks.
