### ISSUE TITLE
An Overlay for DuckStation (for now, meant specifically for 16:9 monitors)

### ISSUE THREAD

**Issue by SecularSteve** [stenzek/duckstation#2601]
**Is your feature request related to a problem? Please describe.**
I don't think anybody likes the black borders when they're playing full-screen without any widescreen hacks on a 16:9 monitor, so I propose a simple 4:3 default overlay.

**Describe the solution you'd like**
Basically, an adaptive dynamic overlay for screens too wide for a 4:3 display without any black borders.

**Describe alternatives you've considered**
Just a basic 16:9 overlay/background to make the display in general look a bit prettier.

**Additional context**
I've taken the liberty of making my own in GIMP in less than a minute.
Released under the CC-BY SA 4.0, it's meant to be more of a 0.1 prototype than anything.

![DS1overlay](https://user-images.githubusercontent.com/33793273/132760665-72f05c69-ca06-4a5c-b29f-5dbcb0f8f87f.png)

ZIP contains the XCF and the PNG file.

[DS1overlay.zip](https://github.com/stenzek/duckstation/files/7139699/DS1overlay.zip)

**Comment by stenzek** [comment]
No interest in anything like this sorry. I think it was already requested too
