### ISSUE TITLE
Option to Remove FF/Rewind/Pause indicators Upper-Right Corner

### ISSUE THREAD

**Issue by TsukiyoX** [stenzek/duckstation#2603]
Hi. After the new update, is there any way to remove the FF/Rewind/Pause indicators on the upper right of the screen? I think it should be counted as an OSD that can be turned off.

If not, is there any way for me to revert back to the previous version of Duckstation?

Thank you in advance.

**Comment by stenzek** [comment]
The issue tracker is not for support, please don't treat it as one.

Look in advanced options for status indicators.
