### ISSUE TITLE
all gamepad analog set same axis+ 

### ISSUE THREAD

**Issue by zephirusgit** [stenzek/duckstation#2609]
Hello friends. Today, i download,duckstation from github , duckstation-windows-x64-release
To use in windows 11arm(now support x86 and x64 arquitecture.), over Raspberry pi 3b+ , the emulation work fine 30fps average. But find a great bug. Wen configure joysticks.  The bug is equal in all joysticks.

I take analog joystick or digital. And select up button, and take the same value from down. In the axis. The same problem habe right and left. Same axis same value.. 

In the game up and down go only down. And left and right , only go to right. 
I find the config. In documents folder. 
And see the problem. 
Bottonup = Controller0/+Axis1
Bottondown = Controller0/+Axis1
The same problem in right left
BottonLeft = Controller0/+Axis0
BottonRight = Controller0/+Axis0
I edit.the cfg and change value + to -

Bottonup = Controller0/-Axis1
Bottondown = Controller0/+Axis1
BottonLeft = Controller0/-Axis0
BottonRight = Controller0/+Axis0

The problem is solve. 
Other problem using nintendo switch control pro. Is dont see (direccional hat keys)
 cant detect these buttons. 
I try using x example D-Pad 1 up ,left right down and not work. Or hat 0 N , hat 0 S ,Hat 0 W , Hat 0 E, and not work. Is posible add these keys? If left analog stick fail, the hat is a solution. :) thanks. Is a great emulator. Can u add suport from dx9? To use d3dx9.dll (shader , to best performance?) Now i use dx11.

**Comment by stenzek** [comment]
The bug tracker is not for support.

There's a native arm64 version anyway...
