### ISSUE TITLE
Blasto (Europe) (En,Fr,De,Es,It) // Intro FMV cut out

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#261]
Tested on all renderers (D3D,OGL and soft).
Tested with all crop options.

The bug was/is present on multiple other emulators.

![Blasto_Europe_EnFrDeEsIt_-_BlastoMDECError](https://user-images.githubusercontent.com/52127625/78886354-56ccd380-7a5e-11ea-8331-c106ec7af634.jpg)

**Comment by stenzek** [comment]
Not sure if this was fixed at some point.

**Comment by Zet-sensei** [comment]
The problem remains on 0.1-753 after a new test.

**Comment by Zet-sensei** [comment]
After a new test on 0.1-841.
Only a faint line line is present now with the "Only Overscan Area" option.
The problem remains the same with the 2 other crop options.

![Blasto](https://user-images.githubusercontent.com/52127625/81728653-17453d00-948b-11ea-967c-bca2f2846666.jpg)

**Comment by kurayami6** [comment]
Crusader - No Remorse (Europe) has the same problem. 

![SLES-00587_2020-06-26_20-12-27](https://user-images.githubusercontent.com/31968468/85846657-7e277700-b7e9-11ea-8f8f-268a3882ea3d.png)

**Comment by stenzek** [comment]
Fixed with https://github.com/stenzek/duckstation/commit/362905e3df0c2b01d414528dd2bf92ec3539cb68
