### ISSUE TITLE
Emulator Crashes Randomly

### ISSUE THREAD

**Issue by MortimerScharf** [stenzek/duckstation#2610]
**Game details**
[SLUS-00706 Tenchu: Stealth Assassins (USA)]

**Description of the issue / bug**
Game crashes at random mid-level. 

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
No, but I do have Steam open (not playing any games there though).
2. Which controller backend are you using in general settings?
DInput.

**Note:**
If you are using Duckstation on Android device please consider the following before report:
Are you using any kind of "memory optimizer" program such as: Ccleaner, Wisecleaner, Clean Master, Boost Android etc. ?
(if so, please, consider create an exception on it first and test; or even remove / uninstall it retest and then, if the problem persists continue with the report.

I am using Duckstation on W10.

**Steps to reproduce**
I just play the game normally. The emulator will crash and close itself at will while playing the game on any of the levels for no apparent reason.

**Enhancements information**
[Make sure they are all turned off before report]
All turned off, I never bothered enabling them anyway.

**Hardware/software**
[If Android, which phone and Android version]
[If desktop, your CPU, graphics card, and operating system]
Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz, 4095MB NVIDIA GeForce GTX 1050 Ti (EVGA), Windows 10.
[GPU Renderer - D3D11/OpenGL/Vulkan]
D3D11, as recommended by the emulator (I am not sure if I should change it to D3D12, Vulkan or OpenGL).

**Emulator version**
[Shown in the title bar of the emulator]
Duckstation 0.1-4722-ge12474ac (Master)

**Additional context**
Just that, the game crashes at will and it's starting to be really annoying. I am attaching the crash .txt file just in case.
[crash.txt](https://github.com/stenzek/duckstation/files/7162865/crash.txt)

**Comment by stenzek** [comment]
Can't do anything without instructions to reproduce it, or the crash dump file (the dmp not the txt)

**Comment by MortimerScharf** [comment]
[crashdump.zip](https://github.com/stenzek/duckstation/files/7162940/crashdump.zip)

I just tried to attach the ".dmp" file but Github wouldn't allow me to, so I just zipped it. There are no instructions to reproduce the crash, just playing any of the levels for long enough will cause the emulator to crash.

**Comment by stenzek** [comment]
This was the result of the achievement doing a word read from `0x001FFFFD`, which went off the end of guest memory. https://github.com/stenzek/duckstation/commit/bacd834840a12b7df19df175bb5cbf286c93d43f makes cheevos use the safe routines, which (now) handle unaligned accesses.

Whatever achievement this was probably won't work as intended, but I don't see how it would on any emu.
