### ISSUE TITLE
Geometric Correction Broke 2D Texture Placement for SuperSponge

### ISSUE THREAD

**Issue by Trimint123** [stenzek/duckstation#2614]
Title said it all. Sometimes the enemies will be off the ground and most characters sometimes gone.

Without Geometric Correction
![SLUS-01352_2021-09-15_16-43-13](https://user-images.githubusercontent.com/25479107/133410885-faccdc81-c635-4c7d-8ca9-f52690c7007f.png)

With Geometric Correction
![SLUS-01352_2021-09-15_16-43-05](https://user-images.githubusercontent.com/25479107/133410897-3bbc408a-73d6-4134-b4d2-f00756cf68f8.png)

**Comment by Trimint123** [comment]
One thing I wanna point out is that it fixed itself if you disabled then re-enable it, but only for temporary as when the game loads the next section, it broke again.

**Comment by stenzek** [comment]
You didn't read the issue template, because enhancement issues are not bugs. See https://github.com/stenzek/duckstation/issues/427
