### ISSUE TITLE
Ninja - Shadow of Darkness (USA) - Game softlocks when entering cutscene of the first boss

### ISSUE THREAD

**Issue by Tarranium** [stenzek/duckstation#2615]
SLUS-00435 Ninja - Shadow of Darkness (USA)

I tried all the different renderers, disabling all enhancement and completely resetting the game and even reinstalling the emulator, but every single time I get to the cutscene of the boss of the first level when the screen fades to black to start it, the game softlocks. It just goes black, no sound and the framerate counter goes to 0.

It doesn't softlock on other emulators so it's not the game.

I've been trying with different versions of Duckstation and just today I tried with the latest preview version (0.1-4736-gbacd8348 2021-09-15T12:24:33+10:10) as well, and it still softlocks at the cutscene.

OS: Windows 10
CPU: AMD Ryzen 5 2600X
GPU: AMD Radeon RX480

**Comment by andercard0** [comment]
Not a emulator issue! 

Just did replay it here and as you can see, I'm at the end of the first boss/level: 

![image](https://user-images.githubusercontent.com/43047877/133491070-621e096a-56b5-402b-9403-88208258f701.png)

i went trough the market part as normal... 

and just started the second level with no issues!

![image](https://user-images.githubusercontent.com/43047877/133491242-60549bb7-4bae-45b5-8dc7-f3eaa8852b97.png)

working as inteded please do make sure your dump is valid. 

In the game list right click properties: 
![image](https://user-images.githubusercontent.com/43047877/133491358-599d1a1c-f87a-4e9b-aee3-068a22a4dfd5.png)

> compute hasshes
Your game should be as below and as here: http://redump.org/disc/7682/ if you'd like to compare.

![image](https://user-images.githubusercontent.com/43047877/133491468-b65447e1-df01-4fe1-bc72-95e8fa4b9048.png)

if not, then you have a bad dump, you must to dump it again.
