### ISSUE TITLE
SLES-02026 Legacy of Kain - Soul Reaver (Spain) don´t work in lasted version 

### ISSUE THREAD

**Issue by ricardomr90** [stenzek/duckstation#2616]
Please read before creating a new issue:

1. Make sure there is not already an open issue for this bug.
2. All enhancements **must** be off. To quickly disable all enhancements with affecting your normal config, in advanced options you can check "Disable All Enhancements".
3. All advanced options **must** be at their default values.
4. No cheats may be active. If you were using cheats, they should be disabled, and the game rebooted before reporting the bug.
5. Do not share save state files. Memory cards are okay.
6. Verify your dump, as we can not assist with issues resulting from bad dumps.
7. If playing PAL region software, please check whether or not the game has LibCrypt protection and that if it does, you have a correct SBI file (see https://github.com/stenzek/duckstation#libcrypt-protection-and-sbi-files for more information).
8. Please post your issue report in English as unfortunately this is the only language spoken by the developers. The Discord server has many helpful people if you need help translating.

[SLES-02026 Legacy of Kain - Soul Reaver (Spain)]

[The game don´t work, only stade in black screen]

1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?

no

2. Which controller backend are you using in general settings

I´m using Duckstation for windows 

If you are using Duckstation on Android device please consider the following before report:
Are you using any kind of "memory optimizer" program such as: Ccleaner, Wisecleaner, Clean Master, Boost Android etc. ?
(if so, please, consider create an exception on it first and test; or even remove / uninstall it retest and then, if the problem persists continue with the report.

[Try to provide as much detail as possible to reproduce the issue]

in the version 0.1-4423-g32ab7c13 works well

[Make sure they are all turned off before report]

[Intel(R) Core(TM)2 Quad CPU    Q9650  @ 3.00GHz   3.00 GHz, NVIDIA GeForce GTX 650 Ti, Windows 10]
[GPU Renderer Vulkan]

[0.1-4714-g6c628bb8 (dev)]

**Comment by andercard0** [comment]
Invalid! as you can see below, working as intended.
(Most likely a bad dump)

![image](https://user-images.githubusercontent.com/43047877/133516568-332dbb52-c1e9-4ae0-815e-0ed06e529801.png)

![image](https://user-images.githubusercontent.com/43047877/133516705-76e1e124-5935-4588-8959-91b1daa9e78b.png)

Please, validade your dump and confront in this site: http://redump.org/disc/27944/

to do so, right click in the game list properties
![image](https://user-images.githubusercontent.com/43047877/133516731-193d35ad-4c3b-44e2-8c78-65d1185f5557.png)

then compute hashes
(validate with the site: http://redump.org/disc/27944/)
![image](https://user-images.githubusercontent.com/43047877/133516779-fd806c73-ee83-4ac0-a505-daa1133d941f.png)
