### ISSUE TITLE
[Feature request] Game list filtering

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#2618]
**Is your feature request related to a problem? Please describe.**
If you have a huge list of games, it's hard to navigate among them.

**Describe the solution you'd like**
A real-time filter to filter the games shown in the game list. We can have a search bar with a dynamic search that will be narrowing the games shown in the game list.

![1_QJNf4iiqW0_2DlFD75hnzA](https://user-images.githubusercontent.com/12163923/131204424-5301621c-f47d-4a36-970f-f9a1a5427498.gif)

**Describe alternatives you've considered**
(blank)

**Additional context**
There's a similar solution found in most of MAME's frontends. Also, I'm pretty sure that Qt has support for this.

**Comment by stenzek** [comment]
Was implemented in the UI refactor way back.
