### ISSUE TITLE
ARM 64 bit compile fails with "cannot convert 'bool' to 'EGLNativeWindowType'"

### ISSUE THREAD

**Issue by bobbybudnick** [stenzek/duckstation#2619]
**Game details**
Did not get that far.

**Description of the issue / bug**
The compile with "ninja" fails with an error like "cannot convert 'bool' to 'EGLNativeWindowType'".

**Controller Troubleshoot Report**
Did not get that far.

**Steps to reproduce**
Just doing a normal compile by following the README.md.

**Enhancements information**
Did not get that far.

**Hardware/software**
I am using a Khadas VIM 3 ARM SBC running Debian Buster 64 bit.  

**Emulator version**
Latest Libretro version.  I searched for an issue tracker on the Libretro Github page but did not see one.

**Additional context**
My take on the problem is that some software in the distribution may be too old.  As you may know, upgrading some ARM devices to the latest distributions is not always easy or I would have already.  I can post further information if needed.

**Comment by stenzek** [comment]
The libretro sources are not public, and it is definitely not in this repository. Nor is it in any libretro repository. 

A64 binaries are available at https://www.duckstation.org/libretro/

**Comment by bobbybudnick** [comment]
Thank you for that link.  It used to be that binary software had a really bad chance of working with Linux or you needed to install a bunch of libraries.  Not only did this load perfectly with no errors which was amazing in itself, but the performance is unlike anything  I have ever seen on this device.  The person that programmed this emulator is a coding genius without a doubt.
