### ISSUE TITLE
 PaRappa the Rapper - The Hip Hop Hero (Europe) (En,Fr,De,Es,It) // Music stops just after the first error done by the player.

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#262]
The music shouldn't stop until a Game Over screen/Try Again.

![ParappaSoundPAL](https://user-images.githubusercontent.com/52127625/78886758-09049b00-7a5f-11ea-8562-932527af2174.jpg)

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/777809b3b08a49099677fd2ae0deb8fed42a5f34.

**Comment by Zet-sensei** [comment]
Fix confirmed.
