### ISSUE TITLE
Libcrypt Problem One Games Like Jackie Chan 

### ISSUE THREAD

**Issue by Atari12345** [stenzek/duckstation#2620]
can u guys resolve this problem its not possible to play some games like  Jackie Chan Stuntmaster (Europe) 

Libcrypt is a problem the emulator canot ready this games can u provide an actualization with something that make this games work 
but do it for all at once to avoid future problems make a check on the games and actualize with the proper pograms or files 

to be a 100 % work , honestly this is far the best of all emulators  for ps1 amazing ! thanks for this there are a few bugs for us 

to take care and report them its important . 
![1](https://user-images.githubusercontent.com/90123403/133823353-630db06e-389c-496b-9531-4eeb48b6331b.png)

**Comment by andercard0** [comment]
Invalid!

can you please READ what the messasge says and provide a valid .SBI file ?

also, there is a option in advanced options that could help you if you read it carefully

![image](https://user-images.githubusercontent.com/43047877/133823977-1d06017c-2ac8-4aee-8422-aa0937db65eb.png)

**Comment by stenzek** [comment]
Libcrypt games work fine with a complete dump.

**Comment by Atari12345** [comment]
yes it work , i allow it to work without sbi file and the game now just work fine , yes the emulator is very nice im still learning a few things i can see now the jackie chan game now is working fine i tested than for the help , its not that i dont read caurefully but its to many things in the emulator :) aprecciated thanks

**Comment by stenzek** [comment]
**Do not complain when your game breaks** if you tick that option.

If you do not provide a SBI file, **it will break or crash at some point if it does not on boot.**

**Comment by Atari12345** [comment]
yes i understand now i did donwload a sbi file from the game and rename it and add to the file of the game and wheni run the game the message dint appear this this so it mean the sbi file is correct and the game now run without crash thans

**Comment by Atari12345** [comment]
but what I wanted to say is that in the future they could update the game files in the emulator with this type of problems to avoid the malfunction of these types of protected games it would be easier like this than going around looking for sbi files , so they would be soon all included in the emulator and automatically ready to be used when you enter this type of protected game is the perfect emulator

**Comment by stenzek** [comment]
No, since it's technically a key and I'm not sure on legality.
