### ISSUE TITLE
Controller no longer detected

### ISSUE THREAD

**Issue by 60fpshacksrock** [stenzek/duckstation#2622]
**Game details**
[Serial Code, Region]
[SLUS-00707 Silent Hill (USA)]

**Description of the issue / bug**
[No input]

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
No.

2. Which controller backend are you using in general settings?
DInput usually. Tried all three and nothing.

**Note:**
If you are using Duckstation on Android device please consider the following before report:
Are you using any kind of "memory optimizer" program such as: Ccleaner, Wisecleaner, Clean Master, Boost Android etc. ?
(if so, please, consider create an exception on it first and test; or even remove / uninstall it retest and then, if the problem persists continue with the report.

**Steps to reproduce**
[Not much other than it not working]

**Enhancements information**
[None]

**Hardware/software**
[If desktop, your CPU, graphics card, and operating system]
[Athlon(tm) Dual Core Processor 4050e x64, Nvidia GeForce 9200, Windows 7 64-bit]

**Emulator version**
[0.1-4714-g6c628bb8]

**Additional context**
It used to work on older builds.
[Here is some information from devmanview that might help:]

==================================================
Device Name       : HID-compliant game controller
Manufacturer      : (Standard system devices)
Service           : 
Device Type Code  : HIDClass
Device Type Name  : Human Interface Devices
Device Instance ID: HID\VID_079D&PID_0202\6&27056260&0&0000
Location          : 
Capabilities      : 0x000000e0
Config Flags      : 0x00000000
Disabled          : No
Connected         : Yes
Device Registry Time 1: 9/20/2021 12:39:44 PM
Device Registry Time 2: 9/20/2021 10:09:48 AM
Drive Letter      : 
Container ID      : {de5c815c-2a37-11eb-830e-fb8dc7834ca7}
Driver Description: HID-compliant game controller
Driver Version    : 6.1.7601.24386
.inf File         : input.inf
.inf Section      : HID_Raw_Inst.NT
Driver Date       : 6/21/2006
Driver Registry Time: 12/19/2020 9:23:31 PM
==================================================

**Comment by stenzek** [comment]
Issue tracker is not for support.

**Comment by 60fpshacksrock** [comment]
Then where should I have posted this?

**Comment by andercard0** [comment]
> 
> 
> Then where should I have posted this?

Nowhere, windows 7 is not supported.

**Comment by 60fpshacksrock** [comment]
@stenzek

Thank you. The latest update fixed the issue. SDL now works.
