### ISSUE TITLE
Final Fantasy VIII (Disc 4) FMV freezes and stuck

### ISSUE THREAD

**Issue by MogKite** [stenzek/duckstation#2626]
**Game details**
SLUS-00910 Final Fantasy VIII (USA) (Disc 4)

**Description of the issue / bug**
The first FMV of the game permanently freezes the scene with no means of even proceeding to the game.

**Steps to reproduce**
There were no fixes. Rebooting does not work.
All Enhancements Disabled.

**Hardware/software**

Intel(R) Celeron(R) CPU  N2940  @ 1.83GHz   1.83 GHz, Intel(R) HD Graphics, Windows 10
GPU Renderer - Hardware (D3D11)

**Emulator version**
0.1-4739-g1cc6ee48 (dev)

**Additional context**
The FMV freeze point where there is no way for me to get through the game
![ffviii disc 4 fmv freeze point](https://user-images.githubusercontent.com/34450639/134761716-b1b73a1b-6626-4b62-baf7-c03ffc05475d.png)

**Comment by stenzek** [comment]
You likely have a bad dump.

**Comment by MogKite** [comment]
> You likely have a bad dump.

What do you mean by that? What could be the cause?

**Comment by BloodRaynare** [comment]
That means your game's dump either has a lots of unintended bad/missing datas. You can check this by right clicking of your game on the emu's game list, then go to "Properties" and compute your dump's hashes then verify it against redump database.
