### ISSUE TITLE
Flickering with freesync and gsync on all apis

### ISSUE THREAD

**Issue by ps1freak26** [stenzek/duckstation#2627]
Game Details
Ridge Racer Revolution, Croc Legend of the Gobbos, Hot Wheels Turbo Racing and Crash Team Racing. All are ntsc versions.

Description of the issue / bug
With both amd and nvidia graphics they both flicker which is more like backlight strobing but really slow and hurts your eyes and is very noticable over time and gets worse. Monitor used is LG 32qn600b that can do 1440p75 but not 1440p60 so I can't use vsync without stuttering at that resolution. All apis d3d11, opengl, and vulkan on both the emulator and the retroarch core cause this problem. The fast forward option is not the cause. 

Controller Troubleshoot Report
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
2. Which controller backend are you using in general settings

Steps to reproduce
Set to d3d11, fullscreen mode to 2560x1440 @ 75.0* hz, Disable v-sync and sync to host refresh, and enable freesync or gsync on both the monitor and the amd or nvidia drivers.
On retroarch set to d3d11, opengl, and vulkan for core settings for exclusive fullscreen, turn windowed fullscreen off, and disable vsync.

Enhancement information
All enhancements, cheats, and advanced settings are turned off and still flickers.

Hardware/software
CPU: Intel Core i5 4590
GPU: Nvidia GTX 1660 Super with driver version 471.68
OS: Windows 10 21H1
GPU Renderer - D3D11/OpenGL/Vulkan
CPU: AMD Ryzen 5 4600g
GPU: AMD Vega 7 integrated graphics with driver version 21.8.2
OS: Windows 10 21H1
GPU Renderer - D3D11/OpenGL/Vulkan

Emulator Version
DuckStation 0.1-4714-g6c628bb8 (dev) and latest retroarch core

Additional Context
Nvidia drivers that have the windowed setting working with gsync also flickers but even worse than exclusive fullscreen on amd.

**Comment by stenzek** [comment]
I've found for VRR to work, I needed to enable vsync.

> On retroarch set to d3d11, opengl, and vulkan for core settings for exclusive fullscreen, turn windowed fullscreen off, and disable vsync.

This is not duckstation's issue.

**Comment by ps1freak26** [comment]
VRR does work expect vulkan on amd and that I said both the core and emulator which are seperate have the flickering issue. Beetle psx hw in retroarch does not have flickering with opengl and has vrr working so it's not retroarch's fault. VRR working is not the point the point is that there is flickering when it works and it doesn't say 75hz on information on the monitor which is how to see if vrr is working.

**Comment by stenzek** [comment]
Then use beetle, I have no time for circlejerking retroarch users that always blame my code. It's a problem with retroarch, because the core **does not control anything to do with sync or refresh**, but what would I know, I only wrote the core.
