### ISSUE TITLE
Puzzle Bobble 3dx and 4 have a music delay and wrong ones at starting gameplay

### ISSUE THREAD

**Issue by Hellzio** [stenzek/duckstation#2628]
Puzzle Bobble 4
SLPS-01492 - Japanese
I think vulkan,why i think?,because i stetted multiple times to see if it get solved.
So,the problem.When the intro starts you can hear nothing and after like 4 or 5 seconds the song starts.In main menu the music has a delay aswell and in gameplay it starts like an ending part of some song and then the real songs begins.I tested with and without the enhance settings and still the same,changed many options and still the same.In Epxse works pretty well but of couse i love more your work rather than that emultor since it doesn't look that great as yours.PB3DX has the same problem,song delays and sometimes it starts with a wrong one.
*My Specs:
Z370 HD3
I5 8600k 3.6
Palit 1660 Super 6gb
16gb Ram 2400
2tb black as primary and 2tb blue
-Thanks for making this awesome emulator.

**Comment by stenzek** [comment]
You should compare against console, not epsxe, it has notoriously bad cdrom emulation, especially with timing.

**Comment by Hellzio** [comment]
> 
> 
> You should compare against console, not epsxe, it has notoriously bad cdrom emulation, especially with timing.

I did,tested my original game with not hacked ps1 and also hacked one,both works pretty well,sadly it's a emulator bug or error.

**Comment by bslenul** [comment]
Weird, sounds correct for me:

https://user-images.githubusercontent.com/33353403/134938394-51d07452-0913-45ef-8af9-594951c26529.mp4

**Comment by Hellzio** [comment]
> 
> 
> Weird, sounds correct for me:
> PB4_edit.mp4

Wow that's weird mate,i tested my original on a original psx,then dumped the game tested in the emulator and that happen,also tested a copy on disc on a ps3 and psx aswell and it works fine but in emulator sounds delayed and end songs while it loads the correct one.

**Comment by Hellzio** [comment]
> 
> 
> Check your game's dump hashes against redump database (Right click the games you want to check the hashes in the game lists, then choose "compute hash"). Since these games uses CD audio which is notoriously difficult to dump properly with only generic dvd-roms/cd-roms, at least to redump standards. Basically, to dump PS1 games with CD Audio you'll need a preservation grade plextor drives.

It shows this:
SLPS-01492 / HASH-4706276D6F601379
Thanks for the help.

**Comment by BloodRaynare** [comment]
That's not what I meant, I meant this (I used "Magical Hoppers" for example)
![image](https://user-images.githubusercontent.com/46045141/135172681-7e627e97-4448-45c5-b23f-9ca0a259784d.png)
You must choose "Compute hashes" to reveal the MD5 hashes of your dump.
Anyway, this is slowly turns into a support thread.

**Comment by stenzek** [comment]
You need to compare the track times as well for CDDA games. It should match redump, e.g. http://redump.org/disc/23860/

If the times match, then there's a potentially an issue here and I'll reopen. But otherwise it sounds like a bad dump.

**Comment by stenzek** [comment]
It's not the emulator's fault if your dump is incorrect.
