### ISSUE TITLE
(Android) Cannot set Gamesir T4 as device for vibration

### ISSUE THREAD

**Issue by shipfridge** [stenzek/duckstation#2631]
**Description of the issue / bug**
Trying to set my Gamesir T4 as a device for vibration results in failure. Error says said device does not support vibration, even though it does.

**Steps to reproduce**
Connect Gamesir T4 via Bluetooth. Go to Controller Settings then Port 1. Tap on "Device for Vibration" option, then press any button on Gamesir T4.

**Hardware/software**
Samsung J7 2018, Android 9

**Additional context**
![Screenshot_20210930-100743_DuckStation](https://user-images.githubusercontent.com/65115066/135430075-796c02f4-3ea2-4d0f-9135-f8423cbe2ded.jpg)
![20210930_173915](https://user-images.githubusercontent.com/65115066/135430098-5e31cffa-54f2-4db7-8ba2-ab81c8717ad9.jpg)

**Comment by stenzek** [comment]
This repository has nothing to do with the android app as explained in the readme, nor do I provide any support for it (it's free).

Regardless, vibration in android is dependent on your device and kernel supporting it. The app has no control here.
