### ISSUE TITLE
RetroArch core memory card naming differences

### ISSUE THREAD

**Issue by notdexterslab** [stenzek/duckstation#2633]
[This initially started as a post on r/retroarch.](https://www.reddit.com/r/RetroArch/comments/pynb2z/help_with_m3uduckstation_save_files_on_android/)

When copying over save files from my PC to my android (Android AArch64 (64-bit)) phone (both running RetroArch 1.9.10 and the latest DuckStation core version), I noticed that multi-disc games running on my phone from an .m3u file wouldn't load the existing saves, while single-disc games ran fine. For both systems, I have **Memory Card 1 Type** set to **"Separate Card Per Game (Game Title)"** in Port Settings.

I eventually found that where my PC would create memory card files with the same naming convention for single- and multi-disc games, the Android version would use a different convention for .m3u games. For the game I was testing with, it would save on PC as **"Xenogears (USA)_1.mcd"**, but on Android it's saving as **"_storage_emulated_0_emulator games_psx_Xenogears_Xenogears (USA)_1.mcd"**.

As a workaround, I could simply rename my existing save to the newly-created one, and it's worked fine, but I wanted to bring attention to this and ask why this was happening.

**Comment by andercard0** [comment]
Invalid!
1.No issue templated filled/ignored 
2. We do not provide assistance for RA'core 
3. 3.Android is not supported anymore.

**Comment by stenzek** [comment]
This repository is not for the retroarch core. But the same code is used on PC and android.
