### ISSUE TITLE
R-Type Delta (NTSC-U) random crashes 

### ISSUE THREAD

**Issue by CometHunter92** [stenzek/duckstation#2634]
**Game details**
[SLUS-00877, R-Type Delta (NTSC-U)]

**Description of the issue / bug**
[Random crashes in the arm32 version; I have to try win64 version too.
Crashes happen randomly from the second level and forth on, when you die or select "continue" or "left"; also crashes happen randomly when entering records page.
Doesn't happen in a old code version (tried an april and may DS version and doesn't seem to happen]

**Steps to reproduce**
[Just playing the game and trying to die in the second level to trigger random crashes.
They happen in interprer mode too.
Autosave feature in the game is on.
Vibration in the game is on.]

**Enhancements information**
[All enhancements, beside "disable interlacing" are off, software rendering, both in recompiler and interpreter mode]

**Hardware/software**
[RPi4, in arm32 standalone and RA core too]
[Software renderer]

**Emulator version**
[latest version]

**Comment by stenzek** [comment]
Can't do much without a backtrace.
