### ISSUE TITLE
X2 - No Relief (Japan) SLPS-00766]  not recognized in game list

### ISSUE THREAD

**Issue by 3dfxguy** [stenzek/duckstation#2637]
**Game details**
[Serial Code, Region]
[i.e SLUS-00404 Ace Combat 2 (USA)]
X2 - No Relief (Japan) SLPS-00766]

**Description of the issue / bug**
[Describe what you are seeing and/or hearing during gameplay]
not recognized in game list

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
2. Which controller backend are you using in general settings

**Note:**
If you are using Duckstation on Android device please consider the following before report:
Are you using any kind of "memory optimizer" program such as: Ccleaner, Wisecleaner, Clean Master, Boost Android etc. ?
(if so, please, consider create an exception on it first and test; or even remove / uninstall it retest and then, if the problem persists continue with the report.

**Steps to reproduce**
[Try to provide as much detail as possible to reproduce the issue]

**Enhancements information**
[Make sure they are all turned off before report]

**Hardware/software**
[If Android, which phone and Android version]
[If desktop, your CPU, graphics card, and operating system]
[GPU Renderer - D3D11/OpenGL/Vulkan]
Vulkan
**Emulator version**
[Shown in the title bar of the emulator]
0.1-4745-g13c5ee8b (dev)

**Additional context**
[Add any other context about the problem here]

**Comment by bslenul** [comment]
Shows fine here, probably missing .cue or bad dump.

![image](https://user-images.githubusercontent.com/33353403/135747903-f8f5fd59-0201-4008-bf83-5b6b1ec3b49b.png)
