### ISSUE TITLE
Metal Gear Solid slowdown on exynos 990

### ISSUE THREAD

**Issue by Nejsplitter** [stenzek/duckstation#2638]
SLUS-00594 metal gear solid usa

I use duckstation on my android, snapdragon 765g, adreno 620 and mgs works flawlessly for the whole game, however my brothers android which has an Exynos 990, Mali-G77 MP11 and uses the exact same settings as me and same version emulator stutters/slowdowns heavily whenever the ninja camo/stealth camo is rendered on screen, i find this strange as such hardware is at least similar or better than my own device no ? and yet has these massive slowdowns

**Comment by andercard0** [comment]
> SLUS-00594 metal gear solid usa
> 
> I use duckstation on my android, snapdragon 765g, adreno 620 and mgs works flawlessly for the whole game, however my brothers android which has an Exynos 990, Mali-G77 MP11 and uses the exact same settings as me and same version emulator stutters/slowdowns heavily whenever the ninja camo/stealth camo is rendered on screen, i find this strange as such hardware is at least similar or better than my own device no ? and yet has these massive slowdowns
> 
> 

Invalid, issue template not fiiled. Also, there is no Android support anymore!
