### ISSUE TITLE
Spyro 2 - Gateway to Glimmer (Europe) (En,Fr,De,Es,It) // Missing sound effects on the title screen

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#265]
There should be multiple sound effects during the title screen : from the beginning with the Insomniac Games panel to the arrival of Spyro on screen (and a caveman pursued by a dinosaur).

But only the music is present after some seconds.

![Spyro2Sound](https://user-images.githubusercontent.com/52127625/78895495-44a76100-7a6f-11ea-8136-8ba4cd9a02bf.png)

**Comment by stenzek** [comment]
Please re-test on the latest build - the cutscene audio fix may have affected this as well.

**Comment by Zet-sensei** [comment]
Fixed on 0.1-699.
