### ISSUE TITLE
[Feature Request] A option/filter to show "archived files types" (.zip .7z, .rar) in game list.

### ISSUE THREAD

**Issue by ImSpecial** [stenzek/duckstation#2653]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Is your feature request related to a problem? Please describe.**
Not a problem just a QoL thing I'd like to see added to DuckStation. I still use .7z for maximum compression (yes it's still better then CHD's for storage purposes), and I don't need a bunch of games taking up more space then needed when not playing them. But having them not show with all the missing gaps, just looks kinda bad.

I'm not asking to have DuckStation be able to read inside archived files, or to play them, I know seek times would be an issue for that, only for these kind of extensions to be listed along side the other playable formats that DuckStation's game list can normally show.

**Describe the solution you'd like**
Show everything in a list, not just playable CUE, BIN, CSO, CHD, and whatever other playable formats there are, but the archived files as well. So it might looks something like this;

Final Fantasy IX (Disc 4).7z
Final Fantasy Tactics.7z
Final Fantasy Tactics.chd
Final Fantasy VII (Disc 1).7z
Final Fantasy VII (Disc 2).7z
Final Fantasy VII (Disc 3).7z
Final Fantasy VII (Disc 3).bin
Final Fantasy VII (Disc 3).cue
Final Fantasy VIII (Disc 1).7z
...
...
...

You get the idea here.

PPSSPP (I'm sure you know what this is by now) handles things great IMO and can do this and is pretty much what I'm asking for here, so just copy them. (more below)

**Describe alternatives you've considered**
N/A

**Additional context**
PPSSPP handles things like this, so load up that emulator for yourself if you want more of an understanding.

PPSSPP's game list looks like so;
https://i.imgur.com/aEh7hhx.png

And when you try to click on one to play it, you get this message;
https://i.imgur.com/ti3ToKE.png

**Comment by ImSpecial** [comment]
I'm not asking to have them read or play these just to show them.

**Comment by ImSpecial** [comment]
Because it's a list of games? It should display the list of all my available games that I have at my disposable. Do you have a bookshelf? Maybe a shelf with DVD's on it? Been to a Library? The requirements for a shelf is not that you need you constantly use every one of the things you have on them at all time. Does Vol. 1, Vol. 2, Vol. 4 look good? Doesn't look good to me personally, and with the missing Vol. 3 that is technically there it should still be in the list...

And lastly maybe skimming past a title will get in the mood for something? Your right though, something here doesn't make sense!

_(This is one of those rare times in life you just ask to speak to the manager...)_

**Comment by ImSpecial** [comment]
See the second image, it's an option/filter, doesn't have to be on by default, it effects only those to enable it.

**Comment by PugsyMAME** [comment]
Use Windows File Explorer then - that shows you a list of all the games in a directory. It works well.

Any scanning beyond taking the filename at face value will need the library import to extract the 7z first to check the disc ids and add it to the library with the correct information. So if you have 100s of 7zipped games then a library scan time would increase considerably. Possible Yes, worthwhile absolutely not.

Just convert your disc rips to CHDs and be done with it.

**Comment by stenzek** [comment]
I've been through this time and time again, ZIP FILES ARE NOT USABLE FOR EMULATORS. For multi-track games, which file do you open? What if there's more than one file in the zip? Not to mention the huge decompression time before starting the game.

Use a compressed disc image format. That's what they're there for. It's not the software's job to take care of your dodgy pirated roms.
