### ISSUE TITLE
Notorious "Trophy bug" in "Moto Racer World Tour" is present in Duckstation

### ISSUE THREAD

**Issue by CometHunter92** [stenzek/duckstation#2656]
**Game details**
[SCES-03037, "Moto Racer World Tour" (PAL)]

**Description of the issue / bug**
[After winning a championship you get stuck on the trophy screen. The game freezes but not the emulator.]

**Steps to reproduce**
[Win a championship and press X to exit the trophy screen and you get stuck]

**Enhancements information**
[No enhancements]

**Hardware/software**
[Happens on all platforms, old and newest code version.]

**Emulator version**
[0.1-4743-g8864b48c]

**Additional context**
[The issue is present on the NTSC version too.
The bug happens even when playing the original disc on the PS2 and PS3.
Only original PS1 hardware get it right.
Found a workaround in Duckstation: when got stuck I "eject the disc" and then "insert it" again.
After a few seconds the game get back to the loading screen without problems.
If you want a savestate just before entering the trophy screen I can win a championship for you.]
![SCES-03037_2021-10-14_19-36-49](https://user-images.githubusercontent.com/83950018/137622892-cb403b6d-040e-4f0a-b494-8ad5208a2e66.png)

**Comment by stenzek** [comment]
Sounds like a mechacon timing issue. Will look at it when I get a chance, pretty busy at the moment.

**Comment by stenzek** [comment]
This has been fixed with the range of CD-ROM changes in recent releases. Didn't think to check it before.
