### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by xdccrlz** [stenzek/duckstation#2659]
Do you planning to develope iOS version?
All of the best emu’s and projects have iOS port:
ppsspp, dolphinios, flycast, sm64ex etc.
With AltKit hard job of JIT implementation was sufficiently  solved. 
Otherwise, existing solutions like retroarch, provenance, happy chicken and so on, don’t use JIT and on all platforms significantly inferior duckstation in quality and speed.
If you haven’t time, motivation or other resources for development iOS version give us  at least the list of tasks necessary to solve before the successful implementation of the project.
Thank you for your wonderful product.

**Comment by DamnBoi706** [comment]
Also provenance is planning to port duckstation core from the openemu on the Mac to iOS so you could check out their progress
