### ISSUE TITLE
Spyro 2 - Gateway to Glimmer (Europe) (En,Fr,De,Es,It) // The games locks up when entering the first level

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#266]
After the intro and walking to the first portal, a second intro launches for the first level.

A second cinematic launches normally and after that, the game stays still with the music.

Completely locked up and the CD ROM status can't go further, always cycling on the same sectors.
![Spyro2Freeze](https://user-images.githubusercontent.com/52127625/78896112-43c2ff00-7a70-11ea-9836-4d746a1ef10e.png)

**Comment by kurayami6** [comment]
Locked up for me when I tried to enter the Colossus Level. 

![Capture2](https://user-images.githubusercontent.com/31968468/78898352-fddd5980-7ab6-11ea-9e91-7df2aa6ceae6.PNG)

![Capture](https://user-images.githubusercontent.com/31968468/78898306-ec944d00-7ab6-11ea-84a0-76b4a95c3911.PNG)

**Comment by stenzek** [comment]
Potentially silly question, but I believe this is a libcrypt game, do you have the .sbi files with the same filename included alongside the bin/cue image? (so if your image was named `spyro2.cue`, there should be `spyro2.sbi`. The console should include a message saying replacement sectors were loaded)

**Comment by kurayami6** [comment]
No, Redump doesn't provide that as far as I know and that's where I get all my games. Ideally the emulator should be accurate enough that the copy protection is never triggered in the first place. I've beaten all 3 Spyro games in Beetle PSX multiple times and they never crashed or needed additional files.

**Comment by Zet-sensei** [comment]
Redump doesn't provide any game image of any kind.

But we are providing SBI file references on the website - http://redump.org/disc/1182/sbi/

**Comment by stenzek** [comment]
@kurayami6 I removed your comment because it mentioned obtaining games from redump. As far as I'm aware, redump.org does not provide games, and if they did it would not be legal ;)

I believe the original issue here is related to libcrypt, looking at the handling code of invalid sub-q data Mednafen still seems to deliver the sector but I'm ignoring it. It might only require that GetLocP skip the sector, which would make more sense as the non-subchannel data would still be correct.

**Comment by Zet-sensei** [comment]
Fixed with https://github.com/stenzek/duckstation/commit/a4a112f5d8d2d48ef695db747df4026c27a8e79f
