### ISSUE TITLE
Ace Combat 3 (Japan) (Disc 1) Freezes on first loading screen

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#267]
After creating your save file, the game freezes on the first loading screen after the loading bar fills up.
CDROM status:
![image](https://user-images.githubusercontent.com/50224630/78922555-9a6a1200-7a4b-11ea-9615-a22874912df3.png)

**Comment by Zet-sensei** [comment]
Fixed after testing with https://github.com/stenzek/duckstation/commit/a4a112f5d8d2d48ef695db747df4026c27a8e79f

![Ace Combat 3](https://user-images.githubusercontent.com/52127625/79027820-018fdf80-7b8e-11ea-879b-a797645b5182.jpg)

**Comment by Zet-sensei** [comment]
After some tests, seems to work only on Interpreter Mode.
Doesn't work on Recompiler Mode.

**Comment by kurayami6** [comment]
Just tried the game in recompiler mode and got to gameplay with no crash. The audio is a bit crackly though. Is it still crashing for anyone or can this be closed?

![SLPS-02020_2020-06-04_16-56-33](https://user-images.githubusercontent.com/31968468/83725048-a0afef80-a684-11ea-94a3-fceedb2d439c.png)

**Comment by HeroponRikiBestest** [comment]
Works for me. Maybe open an issue about the audio crackling, though.
