### ISSUE TITLE
Planet of the Apes (USA) audio desync during opening fmv.

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#268]
The audio is slightly out of desync during the opening fmv in cubeb and sdl. This is most notable at the very end of the cutscene, where one of the characters is knocked out by one of the apes with the butt of their gun. Said character finishes saying "Sophie, Sophie, aaaaaah!" before the subtitles for the dialog pop up onscreen.

**Comment by HeroponRikiBestest** [comment]
This seems to happen in every cutscene, not just fmvs.

**Comment by kurayami6** [comment]
This doesn't seem to be happening anymore.
