### ISSUE TITLE
Bios

### ISSUE THREAD

**Issue by LokiInside** [stenzek/duckstation#2690]
was post bio but I schuldend

**Comment by andercard0** [comment]
> 
> 
> Bios colection detected ps1 over 15 [ps1_BIOS.zip](https://github.com/stenzek/duckstation/files/7447515/ps1_BIOS.zip)

please, DO NOT attache BIOS files here, remove it ASAP and close this issue reach us in discord.

**Comment by LokiInside** [comment]
was tray to close don't know how

**Comment by LokiInside** [comment]
dev stil for Mac works perfect ! even with old QT5

**Comment by andercard0** [comment]
> 
> 
> was tray to close don't know how

REMOVE this attachment and hit CLOSE right now please.

**Comment by LokiInside** [comment]
ok i tray
