### ISSUE TITLE
How to add game covers/thumbnails to the UWP (Series X) version?

### ISSUE THREAD

**Issue by Tiller24** [stenzek/duckstation#2691]
### Discussed in https://github.com/stenzek/duckstation/discussions/2647

<div type='discussions-op-text'>

<sup>Originally posted by **Tiller24** October 12, 2021</sup>

I've looked at every setting I could, but maybe I'm missing something. How do you add cover art or thumbnails to the games when you are selecting a game?

I believe Retroarch will automatically download these, is there a feature like that available for the standalone Duckstation ?</div>

**Comment by stenzek** [comment]
The issue tracker is not for support.

You can put covers in the user data directory just like on any other platform. It's in local

**Comment by stenzek** [comment]
Also, what you mention about that frontend automatically downloading covers is illegal (covers are copyrighted), and is something I will **never** do.
