### ISSUE TITLE
Issues in Formula 1 NTSC-U (SCUS-94353)

### ISSUE THREAD

**Issue by CometHunter92** [stenzek/duckstation#2696]
**Game details**
SCUS-94353 Formula 1 (USA)

**Description of the issue / bug**
There are two versions of the game: 
the original has an intro movie that doesn't play on DuckStation (it get skipped somehow);
both version have a reverb loop getting stuck after the loading screen.

**Steps to reproduce**
Just load the game: the intro is skipped and the audio reverb getting stuck is present in the first loading screen before entering the menu too. 

**Enhancements information**
All enhancements are off. Tried recompiler and interpreter.

**Hardware/software**
PC-RPi4
all versions (standalone, arm, libretro core etc...)

**Emulator version**
Happens with every version I know so far.

**Additional context**
The game has two versions: Rev1 has the intro removed as some tobacco sponsorships and probably leftover of different languages from the PAL version (the image is smaller compared to the original).
I know you're busy, take time, I'm only reporting bugs hoping to help somehow with the development :)
Thanks

**Comment by stenzek** [comment]
Reverb issue happens on console too, it's because these games don't reset the SPU on starting, the intensity of it depends on the time it takes to read the executable from disc.

Ignoring the rest because you mentioned libretro.
