### ISSUE TITLE
Intro skipped on SCUS-94353 Formula 1 (USA) original version

### ISSUE THREAD

**Issue by CometHunter92** [stenzek/duckstation#2697]
**Game details**
SCUS-94353 Formula 1 (USA)

**Description of the issue / bug**
There are two versions of the game:
the original (not the greatest hits revision) has an intro movie that doesn't play on DuckStation (it get skipped somehow)

**Steps to reproduce**
Just load the game: the intro is skipped

**Enhancements information**
All enhancements are off. Tried recompiler and interpreter.

**Hardware/software**
PC-RPi4
all versions (standalone x64, arm32)

**Emulator version**
0.1-4788-gae92ce84

**Additional context**
The game has two versions: Rev1 has the intro removed as some tobacco sponsorships and probably leftover of different languages from the PAL version (the image is smaller compared to the original).
I know you're busy, take time, I'm only reporting bugs hoping to help somehow with the development :)
Sorry for the errors in the last bug report.
Thanks

**Comment by stenzek** [comment]
Intro seems fine. Maybe your dump is bad.

![image](https://user-images.githubusercontent.com/11288319/139777569-3d20c60e-917b-4dae-920e-b9f4138ae28c.png)
