### ISSUE TITLE
Duckstation libretro core shm_open error 13

### ISSUE THREAD

**Issue by suetlung** [stenzek/duckstation#2698]
**Game details**
[Serial Code, Region]
[Super Robot War Alpha (JP)]

**Description of the issue / bug**
Platform: ubuntu 20.14 snap store
Version: 1.9.12
Core: psx duck station
Game: super robot war alpha
File format: pbp
Issue: terminates when loading pbp rom
Error: shm_open failed (13). Seems related to the permission flag when calling it.

**Hardware/software**
[If desktop, your CPU, graphics card, and operating system]
[GPU Renderer - Vulkan]

**Emulator version**
core version: 1.9.12

**Additional context**
N/A

**Comment by stenzek** [comment]
Wrong repository.
