### ISSUE TITLE
ps4 controller with ds4windows no recognize

### ISSUE THREAD

**Issue by SennaGitHub** [stenzek/duckstation#2699]
hi, i have a problem with ps4 controller, using ds4windows program to play emulator, but not recognize the controller, i cant setup buttons and in other emulators, dont have any problems.

im using a nin switch pro controller via bluetooth without problems, but with the ps4, not recognize.

thanks.

**Comment by stenzek** [comment]
The issue tracker is for reporting bugs, not support.

DS4Windows isn't necessary, SDL handles the DS4 protocol natively.
