### ISSUE TITLE
The Next Tetris (Europe) hangs after opening FMV

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#27]
The logos play, then an FMV of the word Tetris forming, then it immediately hangs. 

![Capture](https://user-images.githubusercontent.com/31968468/74509658-2d0f9880-4f56-11ea-8375-72d943751f46.PNG)

**Comment by stenzek** [comment]
Fixed by https://github.com/stenzek/duckstation/commit/34f1c644f599a2a0319d0edeeef5dd929ec7fa2c
