### ISSUE TITLE
 Pac-Man World - 20th Anniversary (USA) softlocks if you try and create or load a save

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#270]
Try and load a save from the main menu and it softlocks.

![SLUS-00439_2020-04-10_23-38-01](https://user-images.githubusercontent.com/31968468/78994919-9097fa00-7b84-11ea-8853-f7e5929876b1.png)

Try and create a save at the end of a level and it softlocks.

![SLUS-00439_2020-04-10_23-35-51](https://user-images.githubusercontent.com/31968468/78994956-a60d2400-7b84-11ea-9be1-3bbf34ea1315.png)

**Comment by Zet-sensei** [comment]
Fixed after testing with https://github.com/stenzek/duckstation/commit/a4a112f5d8d2d48ef695db747df4026c27a8e79f

I can save after finishing a level and load from the Memcard on the main menu.
