### ISSUE TITLE
[Feature Request]: CRT (S-VIDEO, COMPOSITE & COMPONENTS CAPABLE)

### ISSUE THREAD

**Issue by Ninaadark18** [stenzek/duckstation#2700]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Is your feature request related to a problem? Please describe.**
Yes and no yes a problem when I play a game and it's sharp and not look like the real hardware or near. No because it's not an actual problem that prevents me anytime from play

**Describe the solution you'd like**
If you can and it would make me and some people very happy.

I suggest that you make us have a crt look (composite, S-Video and components cables) for the standalone emulator (I don't know by filter or shader or something else it's up to you)

**Describe alternatives you've considered**
I am sorry for don't have any alternatives now

**Additional context**
because the ps1 had a lot of 2d games and they look better with these options

[Silent Hill](https://twitter.com/CRTpixels/status/1454934807578873856?s=20) for silent hill it's must be played in composite

[RE2](https://twitter.com/CRTpixels/status/1454518206618652674?s=20) 
[Cv:Sotn](https://twitter.com/CRTpixels/status/1408451743214616587?s=20) 
[Cv:Sotn Richter](https://twitter.com/CRTpixels/status/1408838224328466441?s=20) 
[FF:Origins](https://twitter.com/CRTpixels/status/1407368025066590217?s=20) 
and even the 3D games looks better 
[Vagrant story](https://twitter.com/CRTpixels/status/1394717785088045058?s=20) 

Thanks and sorry If you take my words as rudeness last time

**Comment by stenzek** [comment]
I have no interest in making games look like rubbish with filters like this.

Pull requests are welcome if you want to add it, but it's not something I'm going to do.

**Comment by liljotik** [comment]
Lots of people want the authentic experience without having to buy an expensive CRT television.

**Comment by stenzek** [comment]
Then those people have the freedom to write shaders and/or extend the post processing system as needed. That's the advantage of being open source.

Putting it more bluntly, you didn't pay anything, therefore you're not a customer or a stakeholder, therefore I don't have to do on what any "people" want. I simply work on what I find interesting.

**Comment by liljotik** [comment]
That's fair, I'm just saying there ARE legit reasons why people might want that old CRT look. I'm sure there are existing shaders and filters that could be added to Duckstation rather than having to make them all from scratch. That probably wouldn't be too much work.

**Comment by stenzek** [comment]
And you're missing the point completely that it's not something which I want to do.

Anyone else is welcome to go ahead and port shaders if they like. In which case they should open a pull request and I'll merge it, that way everyone can benefit.
