### ISSUE TITLE
Memory card can't be read, says formatting?

### ISSUE THREAD

**Issue by Legotron123** [stenzek/duckstation#2701]
**Game details**
[SLUS-01041 Chrono Cross Disk 1, USA]

**Description of the issue / bug**
[Memory card can't be read, says formatting?]

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open? No
2. Which controller backend are you using in general settings SDL
Not sure if this part is necessary

**Steps to reproduce**
[I don't know? I downloaded the emulator, set up the Bios files, booted up the rom I downloaded, and upon start there was a message about how the memory card file couldn't be read, with the word "formatting" after a comma. I tried switching the settings to sharing a memory card between all games but that just gave me a similar message. Closing and reopening Duckstation made the message go away, but I still can't save in the game.]

**Enhancements information**
[They are off as far as I can tell]

**Hardware/software**
[If desktop, your CPU, graphics card, and operating system]
[Intel(R) Core(TM) 17-9750H CPU/Intel(R) UHD Graphics 630/Windows 10]

**Emulator version**
[0.1-4788-gae92ce84 (dev)]

**Additional context**
[This is literally my first time using Duckstation, just installed it this morning, no idea what I need to do. I searched Memory Card in the open issues thing and found nothing.]

**Comment by liljotik** [comment]
Duckstation says that every time you start a game for the first time. I think because by default it treats every game as having its own memory card. You can change it in memory card settings. 

![Capture](https://user-images.githubusercontent.com/92196998/140061222-a8442f69-09c5-418d-84f5-7dd0a40c400d.PNG)

![Capture2](https://user-images.githubusercontent.com/92196998/140061315-82bf342a-424c-4417-82cc-4cdd3c8bc46c.PNG)

**Comment by stenzek** [comment]
Please don't use the issue tracker for support, it's for bugs.

**Comment by liljotik** [comment]
I was wrong. I still get that message with shared card when I start a game for the first time. 

![Capture](https://user-images.githubusercontent.com/92196998/140062721-ade15e59-de41-46cd-b3da-87741fce98e1.PNG)

**Comment by Legotron123** [comment]
> I was wrong. I still get that message with shared card when I start a game for the first time.
> 
> ![Capture](https://user-images.githubusercontent.com/92196998/140062721-ade15e59-de41-46cd-b3da-87741fce98e1.

> Please don't use the issue tracker for support, it's for bugs.

Where should I go for this then?

**Comment by Legotron123** [comment]
> I was wrong. I still get that message with shared card when I start a game for the first time.
> 
> ![Capture](https://user-images.githubusercontent.com/92196998/140062721-ade15e59-de41-46cd-b3da-87741fce98e1.PNG)

This is why I mentioned trying a shared memory card in the form.

**Comment by liljotik** [comment]
Maybe it doesn't let you save during the prologue? 

![SLUS-01041_2021-11-04_00-07-59](https://user-images.githubusercontent.com/92196998/140065652-b5ae648b-4264-4be3-aa48-4e7017afc021.png)

**Comment by Legotron123** [comment]
> Maybe it doesn't let you save during the prologue?
> 
> ![SLUS-01041_2021-11-04_00-07-59](https://user-images.githubusercontent.com/92196998/140065652-b5ae648b-4264-4be3-aa48-4e7017afc021.png)

Maybe. I'll try after taking a shower
