### ISSUE TITLE
Glitch on FF8 opening credits

### ISSUE THREAD

**Issue by daFourch** [stenzek/duckstation#2704]
**Game details**

Final Fantasy VIII (USA)

**Description of the issue / bug**

When resolution is set higher than x1, there are visual glitches instead of fading out. Maybe this has to do with the fact this opening is in 480i.

![Final Fantasy VIII](https://user-images.githubusercontent.com/72701886/140197975-8832bafd-aa06-49cc-80bb-a1e7bd9e00b0.png)

**Steps to reproduce**
Set resolution higher than x1.
Launch the game and wait for the opening credits cinematics.
There should be some glitches during fade out transitions.

**Enhancements information**
[Resolution higher than X1]

**Hardware/software**
[GPU Renderer - Vulkan]

**Emulator version**
[1.9.7 Libretro Version]

**Comment by stenzek** [comment]
Did you even read the template? Not everything works with upscaling.

**Comment by daFourch** [comment]
I'm confused. Where should I report bugs with upscaling then? Not everything works for now, okay, but isn't it planned to be otherwise in the future?

**Comment by stenzek** [comment]
No. Some games render in a way which is incompatible with upscaling at the hardware level. This is one of them (it draws individual lines, one at a time, so it wouldn't benefit from upscaling anyway).

The libretro core is also not supported here, this repository is for the desktop application. They decided to bring back their crappy fork, so please nag them instead.

**Comment by daFourch** [comment]
Okay sorry for the nuisance, I didn't know. I thought it was a bug worth reporting since Bettle PSX, with upscaling and downsampling (forgot to mention I was using this too on DS) manages to make this Opening work.

Where/Who could I report this bug to then, for the core fork?

Thanks again

**Comment by Sekai9** [comment]
The known workaround is disabling interlacing.
![image](https://user-images.githubusercontent.com/77129103/140412153-3b2db68c-e8a0-4bdc-bc46-fc264d84f12f.png)
