### ISSUE TITLE
.m3u Files Not Loading Properly in Vib-Ribbon

### ISSUE THREAD

**Issue by MetalNeo** [stenzek/duckstation#2707]
**Game details**
SCES-02873, Vib-Ribbon (Europe)

**Description of the issue / bug**
When attempting to load custom CD files in the game, the game fails to properly load the CD if the game and CD are loaded from a .m3u file where they are listed together. When loaded from the file selection dialog, the CD file loads without issue.

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
No.
2. Which controller backend are you using in general settings
Digital Controller (tested using keyboard)

**Steps to reproduce**
From the main menu, select English -> Game -> Play with your own choice of CD -> Single Track -> (change Disc from .m3u selection) -> (attempts to load and fails) -> (change Disc from File) -> (attempts and loads successfully).

**Enhancements information**
"Disable All Enhancements" is ticked on

**Hardware/software**
Ryzen 2600X, RX 5700 XT, Arch Linux 
OpenGL

**Emulator version**
0.1-4790-g639260b4

**Additional context**
Issue was noticed originally in Libretro core. Tested in standalone emulator and noted issue persisted.
Testing was done with both .cue and .chd files for the base game. .cue was used for the additional files.
Also tested in Japanese version of the game with same result. SCPS-18012 Vib-Ribbon (Japan)
Issue is not present in alternative emulator, Beetle PSX core (HW and software versions) in RetroArch.
Logs below follow same process as above in "Steps to reproduce." Logs start when changing disk for the first time.

test.m3u file:
Vib-Ribbon (Europe) (En,Fr,De,Es,It).chd
test.cue

test.cue file:
FILE "test.bin" BINARY
  TRACK 01 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:00:00

Logs:

[  281.6164] I/CDROM: Removing CD...
[  281.6165] E(LocateFile): Seek to LBA 4274980521 failed
[  281.6166] E(ReadFile): File not found: 'SYSTEM.CNF'
[  281.6166] I/CDROM: Inserting new media, disc region: Other, console region: PAL
[  284.5721] W(CompleteSeek): Logical seek to non-data sector [00:02:00], reading after seek
[  284.5721] W(DoSeekComplete): Logical seek to [00:02:00] failed
[  290.8633] E(LocateFile): Seek to LBA 196605 failed
[  290.8633] E(ReadFile): File not found: 'SYSTEM.CNF'
[  290.8633] E(LocateFile): Seek to LBA 196605 failed
[  290.8633] E(ReadFile): File not found: 'SYSTEM.CNF'
[  290.8633] E(LocateFile): Seek to LBA 196605 failed
[  290.8633] E(ReadFile): File not found: 'PSX.EXE'
[  290.8633] E(ReadExecutableFromImage): Failed to read fallback PSX.EXE from disc
[  290.8633] W(GetEntryForDisc): No entry found for disc (exe code: '', hash code: '')
[  290.8633] E(LocateFile): Seek to LBA 196605 failed
[  290.8633] E(ReadFile): File not found: 'SYSTEM.CNF'
[  290.8633] E(LocateFile): Seek to LBA 196605 failed
[  290.8634] E(ReadFile): File not found: 'SYSTEM.CNF'
[  290.8634] E(LocateFile): Seek to LBA 196605 failed
[  290.8634] E(ReadFile): File not found: 'PSX.EXE'
[  290.8634] E(ReadExecutableFromImage): Failed to read fallback PSX.EXE from disc
[  290.8636] I/SDLControllerInterface: Controller 0 deadzone size set to 0.250000
[  290.8639] I/CDROM: Removing CD...
[  290.8640] E(LocateFile): Seek to LBA 196605 failed
[  290.8640] E(ReadFile): File not found: 'SYSTEM.CNF'
[  290.8640] I/CDROM: Inserting new media, disc region: Other, console region: PAL
[  290.8640] I/System: Inserted media from /home/metalneo/ROMs/PS1/test.cue (, test)
[  290.8640] I/MemoryCard: Memory card at '/home/metalneo/.local/share/duckstation/memcards/test_1.mcd' could not be read, formatting.

**Comment by stenzek** [comment]
If you open another issue about the retroscum core, I'm going to block you. They tried to blackmail me, and brought back their crappy fork (it is not duckstation), so they can deal with the problems. Need to update 

As for the actual issue, the report here was incorrect - it's not an issue switching the playlist entry, the new TOC just wasn't being used. Fixed in https://github.com/stenzek/duckstation/commit/425dee2f0b33e8b2df8f91f724a4bef16c40bc0b
