### ISSUE TITLE
Unable to Build Master (needs #include <future> in gamepropertiesdialog.cpp)

### ISSUE THREAD

**Issue by theofficialgman** [stenzek/duckstation#2708]
**Description of the issue / bug**
Unable to build since this commit https://github.com/stenzek/duckstation/commit/85ea9a629a2a2eba2cff0d8f638619987451c7cf

gameproperiesdialog.cpp needs ` #include <future>`
with this added, duckstation builds

**Steps to reproduce**
cmake -DCMAKE_BUILD_TYPE=Release -GNinja ..
ninja

**Hardware/software**
arm64 ubuntu bionic linux

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/0adbfcbb1f8508852cb16b253fde0920093161e6

Can't be bothered to build on my arm machines at the moment so hopefully that sorts it out

**Comment by cobalt2727** [comment]
I can confirm this fixed the issue on both of my ARM SBCs
