### ISSUE TITLE
Squarish Screen in Resident Evil 3

### ISSUE THREAD

**Issue by mohsinous** [stenzek/duckstation#271]
there is weird problem in 1x, 2x, 3x, 4x and 5x internal res in RE3

1X
![1X](https://user-images.githubusercontent.com/32609205/79006240-f927ac80-7b6d-11ea-9b0e-b3cee5c13209.png)
2X
![2X](https://user-images.githubusercontent.com/32609205/79006250-fe84f700-7b6d-11ea-9a8c-46714a5c972f.png)
3X
![3X](https://user-images.githubusercontent.com/32609205/79006258-03e24180-7b6e-11ea-8263-6c631f3af880.png)
4X
![4X](https://user-images.githubusercontent.com/32609205/79006267-080e5f00-7b6e-11ea-8159-391cc5c3be87.png)
5X
![5X](https://user-images.githubusercontent.com/32609205/79006272-0ba1e600-7b6e-11ea-807f-7f1615464416.png)

**Comment by stenzek** [comment]
Caused by bilinear texture filtering being enabled
