### ISSUE TITLE
[Feature Request] Per-Game Settings on UWP (Xbox).

### ISSUE THREAD

**Issue by GABO1423** [stenzek/duckstation#2719]
**Is your feature request related to a problem? Please describe.**
Unlike the version for Windows, Per-Game Settings don't actually work as intended on the UWP version of DuckStation. While this version is limited to the NoGUI interface which lacks the functionality to set up game-specific configurations, it should still theoretically support a gamesettings.ini file that was configured beforehand. This is already the case with Controller Profiles, which can be configured on the Windows version and then transferred over to the UWP version, which are then recognized and work as expected. 

**Describe the solution you'd like**
The solution is pretty simple in concept, make it so the UWP version can recognize and use a gamesettings.ini file. Ideally, it should be possible to load it from the app's LocalState folder. (To be more specific, the folder the settings.ini file is located/where you would put bios files in if not using a USB drive)

**Describe alternatives you've considered**
N/A

**Additional context**
Here are some screenshots of a gamesettings.ini file, and how the settings aren't recognized:
![image](https://user-images.githubusercontent.com/35014183/141040576-d441016b-8cf0-4473-8c78-bfbfc4f78433.png)
![11-9-2021_10-49-13_PM-ufrsv0uq](https://user-images.githubusercontent.com/35014183/141040749-b37dd38e-3bbf-4b86-ab94-de24c73f3b62.png)

Using NoGUI on Windows shows this instead:
![Captura de pantalla 2021-11-09 225205](https://user-images.githubusercontent.com/35014183/141040906-7ff6a448-443b-4002-9844-94f0e07ee098.png)

Thanks in advance for reading.

**Comment by darkxex** [comment]
Does anyone know how to do this?

**Comment by darkxex** [comment]
@stenzek could you close this thread? the feature is working in the last build.

**Comment by GABO1423** [comment]
> @stenzek could you close this thread? the feature is working in the last build.

Awesome! Thanks for letting me know!

**Comment by GABO1423** [comment]
Sorry @darkxex, how exactly you got this to work? I still can't get DuckStation to recognize the gamesettings.ini file I have. I still get the "No-Per Game Settings Set" Message.

**Comment by darkxex** [comment]
1. revisa que tengas actualizada la versión uwp y la versión standalone.
2. copia el gamesettings.ini en en el directorio local state (la carpeta raíz de duckstation).
3. ya debería mostrarte la configuración personalizada.

**Comment by GABO1423** [comment]
Good thing I speak Spanish I guess.
I tried that and nothing, I still got that message.

**Comment by darkxex** [comment]
Check this ![IMG_20220120_151946532.jpg](https://user-images.githubusercontent.com/17991404/150398256-9382ef3b-da83-4dbc-ae4f-f19dcb79e39b.jpg)![IMG_20220120_151958218.jpg](https://user-images.githubusercontent.com/17991404/150398288-1db2b410-8bf3-42f6-8f5f-05da9d6cd8b8.jpg)

**Comment by GABO1423** [comment]
I'll keep trying I guess, thanks.

**Comment by darkxex** [comment]
btw i'm using xbox one x

**Comment by GABO1423** [comment]
Seems I found the issue. Per-Game Settings for some reason only work when using bin/cue formatted rips. If using CHD or PBP files, the settings are not recognized. So this is a different issue altogether. I'll open a new issue about it.
