### ISSUE TITLE
Upscaling in Ubik (Europe) doesn't effect screen resolution even though it is working in VRAM

### ISSUE THREAD

**Issue by goodrain1992** [stenzek/duckstation#2721]
**Game details**
 [SLES - 00722] Ubik (Europe) (En,Fr,De)

**Description of the issue / bug**
Upscaling isn't effecting screen resolution. This is x4 with Vulkan.

![SLES-00722_2021-11-10_23-57-40](https://user-images.githubusercontent.com/94057177/141180718-69714ca2-bc0c-4c34-86ff-ab2cbbc16e28.png)

It is upscaling in VRAM though. 

![SLES-00722_2021-11-10_23-57-54](https://user-images.githubusercontent.com/94057177/141180769-6686180b-7130-43ca-8dd8-74c0453a0529.png)

**Controller Troubleshoot Report**
No
Analog 

**Steps to reproduce**
Just get to gameplay and try upscaling

**Enhancements information**
All off except upscaling

**Hardware/software**
gtx 1080, Nvidia i7, Windows 10
Vulkan renderer

**Emulator version**
Duckstation version 0.1-4811-gc54c5f1b

**Additional context**
[Add any other context about the problem here]

**Comment by stenzek** [comment]
Not a bug, read the template, enhancements are hacks and not guaranteed to work with all games

**Comment by goodrain1992** [comment]
Do you know why it doesn't work?

**Comment by goodrain1992** [comment]
Did a bit more research. Tried all the backends and none of them made a different. This game really doesn't like upscaling. Besides not increasing screen resolution, upscaling in the game also causes graphical glitches. See those dots in the background?

![SLES-00722_2021-11-12_09-27-49](https://user-images.githubusercontent.com/94057177/141378210-7209fab7-e03e-4c26-9103-3a75dd2fb467.png)

True color rendering disabled + PGXP makes characters visible through walls regardless of resolution setting.

![SLES-00722_2021-11-12_09-31-25](https://user-images.githubusercontent.com/94057177/141378438-dea9ae99-0a75-4272-91dc-2923208aa867.png)

**Comment by ggrtk** [comment]
> Do you know why it doesn't work? Strange since downsampling works but resolution increasing doesn't. Texture filtering doesn't seem to work either. As I said it is working in VRAM and screenshots come out at the size matching the resolution I set it to. It just doesn't show on the screen.

The polygons are being rendered at upscaled resolution on the upper left framebuffer, sure, but you can easily see that the bottom left framebuffer, which is probably the final image being outputted on this particular frame, is at a lower resolution. There are some things that games can do which require hardware renderers to sample at native resolution. You can trace the GPU commands to get a better sense of what they are for this particular game.

> Did a bit more research. Tried all the backends and none of them made a different. This game really doesn't like upscaling. Besides not increasing screen resolution, upscaling in the game also causes graphical glitches. See those dots in the background?
> 
> True color rendering disabled + PGXP makes characters visible through walls regardless of resolution setting.

As has already been stated, enhancements are hacks that are not guaranteed to work with all games.

**Comment by goodrain1992** [comment]
@ggrtk Thanks for the explanation. I really appreciate it. So is there no way to make upscaling work in this game?
