### ISSUE TITLE
[Feature request] The ability to download SBI files if one isn't present

### ISSUE THREAD

**Issue by goodrain1992** [stenzek/duckstation#2723]
First of all this warning system is great. It's saved me quite a few times from running protected games. But would it be possible when it's triggered for there to be a download option and have Duckstation pull the file directly from Redump? Since they're freely available on the website. Something like " This game requires an SBI file. Download now?" and have it go to the corresponding game folder. 

![space debris](https://user-images.githubusercontent.com/94057177/141382273-20a3f4f4-4d5b-4152-a2c1-7858dc24e068.PNG)

**Comment by stenzek** [comment]
You deleted the template, and I'm not sure on the legality of including SBI files, so no.

**Comment by goodrain1992** [comment]
I assumed SBI files were legal since Redump has them for download on their website. They wouldn't offer copyrighted files. What did I miss from the template and I'll include it.

**Comment by goodrain1992** [comment]
**Is your feature request related to a problem? Please describe.**
The majority of people probably don't know what an SBI file is. Having a simple download option would make it much easier and more convenient.

**Describe the solution you'd like**
An option to download the required SBI file directly from Redump when one isn't present.

**Describe alternatives you've considered**
The alternative is going to Redump and manually searching for the game you want. 

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by stenzek** [comment]
I'm still not adding it, because I'm not paying for legal advice to know whether it's safe or not, for a project which actually costs me out of pocket to keep running.

If you want to pay for legal advice so I can be certain it's safe, then sure. But otherwise, it's really not a big deal to obtain these files manually.

**Comment by goodrain1992** [comment]
@stenzek tbh I don't have a thousand bucks lying around to pay for a consultation. But I noticed your profile said PHD student. Maybe you could ask a law professor at your college for advice. But I guarantee Sony isn't going to sue over SBI files either way. If you listen to their CEO their attitude seems to be to pretend their old games don't even exist.

**Comment by stenzek** [comment]
Your guarantee is not sufficient when I'm the one who's going to be liable. It's open source, if you want such a feature, you can add it for yourself.
