### ISSUE TITLE
True Color rendering needs to be off by default in Gakkou no Kowai Uwasa - Hanako-san ga Kita!! (Japan)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#2724]
**Game details**

Gakkou no Kowai Uwasa - Hanako-san ga Kita!! (Japan)
PSXEXE / HASH-B39B28CB8E99EF28

**Description of the issue / bug**
True color rendering causes graphical flickering around the game border.

![PSXEXE_2021-11-12_15-46-45](https://user-images.githubusercontent.com/94057177/141411748-c606725f-ac7c-4227-99e7-55826c86ddc2.png)

**Controller Troubleshoot Report**
No
Analog 

**Steps to reproduce**
Start the game with true color rendering and a hardware renderer 

**Enhancements information**
All of except for true color rendering. Tested with Vulkan at x4 and native res.

**Hardware/software**
GTX 1080, intel i7, Windows 10
 Vulkan

**Emulator version**
Duckstation 0.1 - 4815 - gf982a2a5

**Additional context**
[Add any other context about the problem here]

**Comment by stenzek** [comment]
Overridden in https://github.com/stenzek/duckstation/commit/10cf8ef6381933e40d69416c0b36c991964db862
