### ISSUE TITLE
Vulkan ??

### ISSUE THREAD

**Issue by azoreseuropa** [stenzek/duckstation#273]
Are you going to add Vulkan ?

**Comment by stenzek** [comment]
No plans. There currently isn't any benefit - draw calls are lucky to push more than a couple of hundred in most games, and you lose the driver offloading stuff to its worker thread so it may actually end up slower. There's still some more performance to squeeze out of the GL renderer, I just haven't done it yet.

The main reason I would consider it would be if there was some compelling feature I could make use of.
