### ISSUE TITLE
Key to close the emulator + lack of filters

### ISSUE THREAD

**Issue by Felipefpl** [stenzek/duckstation#2736]
**Is your feature request related to a problem? Please describe.**

I'm frustated i cant close the emu when choosing certain display/enhancement options, i can close espxe using the ESC key.

**Describe the solution you'd like**

Using the ESC key would be perfect to solve this.

**Describe alternatives you've considered**

I cant use alt+f4 when using those certain options too, it would be good if we could choose it.

The emu is also missing some nice filters like 2xsai, super2xsai, the LQ/HQ filters, it would be NICE to have those on duckstation.

**Comment by stenzek** [comment]
You can bind escape to power off system, and use batch mode to auto exit.
