### ISSUE TITLE
[Feature Request] Incremental Speed Adjustment 

### ISSUE THREAD

**Issue by Giacomino99** [stenzek/duckstation#2738]
**Is your feature request related to a problem? Please describe.**
Currently in DuckStation there are three options for speeds that the emulator will run the game at: "Emulation Speed", "Fast Forward Speed", and "Turbo Speed". In some games a more fine-grained control of the speed that the game runs at would be beneficial.

**Describe the solution you'd like**
Three new Hotkeys for controlling the speed of the emulation:
1. "Increase Speed": increases the emulation speed by some percentage (maybe user configurable).
2. "Decrease Speed": decreases the emulation speed by some percentage.
3. "Reset Speed": resets the speed back to the normal value

**Describe alternatives you've considered**
N/A

**Additional context**
This feature is currently available in the emulator "BizHawk".

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/61f7e99508ba38e0158e3cc1913bde0796c1c795
