### ISSUE TITLE
Issue with CD audio on real discs

### ISSUE THREAD

**Issue by Nerdy-boi** [stenzek/duckstation#2739]
Game details
SPLM-86252 DDR2nd ReMix (Japan) and likely other games that use CD audio

Description of the issue / bug
The emulator appears to add a 2 second gap between Track 1(Data) and Track 2(audio.) throwing off the entire game, this issue is relevant for ddr as it appears to sync music to the timing of the cd.  using a verified Dump removes this issue.

Steps to reproduce
Use a Real disc on any drive
Load in Duckstation
Play Any song

Hardware/software
Ryzen 7 2700
Rx 5700 (2021.11.1 Drivers)
Vulkan and D3D11

Emulator version
0.1-4788-gae92ce84

Included Log Files
[duckstation BINCUE DDR2nd Remix(Japan).log](https://github.com/stenzek/duckstation/files/7573172/duckstation.BINCUE.DDR2nd.Remix.Japan.log)
[duckstation Real Disc DDR2nd Remix(Japan).log](https://github.com/stenzek/duckstation/files/7573173/duckstation.Real.Disc.DDR2nd.Remix.Japan.log)
84

**Comment by stenzek** [comment]
See if https://github.com/stenzek/duckstation/commit/7c769b19410030761a059a19be96121d819e369c changes anything... technically they'll be missing index 0 now, but I doubt the games care

**Comment by Nerdy-boi** [comment]
Works perfectly. thank you.
