### ISSUE TITLE
Games with PCM music multi-tracks // Delay when reading music tracks on some games

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#274]
After some extensive tests between the original consoles & some other emulators, there is a delay when the music should start on character selection screen and the fighting stages on these SNK titles.

- Real Bout Garou Densetsu (Japan)
- Real Bout Garou Densetsu Special - Dominated Mind (Japan)
- Samurai Spirits - Amakusa's Revenge Special (Japan)

**Comment by Zet-sensei** [comment]
Same kind of delay when reading music tracks on Goemon - Shin Sedai Shuumei (Japan).
https://psxdatacenter.com/games/J/G/SLPM-86997.html

Compared with Mednafen & original hardware (music starts directly during transitions).

**Comment by Zet-sensei** [comment]
Clearly a 2 secs delay, like a PREGAP problem after testing other games.

For example, just tested today.
- Mickey's Wild Adventure (Europe) (No EDC) -> On the Sound Test, when launching a music, exactly 2 secs of silence before each music track beginning.
- Simple 1500 Series Vol. 93 - The Puzzle Bobble - Puzzle Bobble 4 (Japan) -> 2 seconds of silence during the gameplay before the music starts in-game.

**Comment by kurayami6** [comment]
Razor Freestyle Scooter (USA) might have the same problem. When you start practice mode there's a few seconds of total silence before the music starts.

**Comment by stenzek** [comment]
At least in the case of Real Bout Garou Densetsu, it's not due to the pregap, the game seeks to the correct location. It's the delay I have for switching between single/double speed.

**Comment by Zet-sensei** [comment]
Tested all the games mentioned on the issue with 0.1-753 version.

Fixed.
