### ISSUE TITLE
Duckstation incorrectly warns that several games are incompatible with Namco Guncon 

### ISSUE THREAD

**Issue by MikeHerbertbailbonds** [stenzek/duckstation#2742]
**Game details**

Elemental Gearbolt (USA)
SLUS-00654 / HASH-322324B21D639BC

![g](https://user-images.githubusercontent.com/94663834/143382530-9dea865d-7265-41bb-b93b-cb367fac45af.PNG)

Ghoul Panic (Europe) 
SCES-02543 / HASH-D9366E02B7905252

![ma](https://user-images.githubusercontent.com/94663834/143382592-7cecbaa1-6013-4161-9f80-e2f174e69940.PNG)

Maximum Force (Europe) 
SLES-01001 / HASH-67609DD34D1E05C6

![max](https://user-images.githubusercontent.com/94663834/143382669-cb9ccfaa-87be-45cc-b9f6-5b4872bca953.PNG)

Mighty Hits Special (Europe)
SLES-02244 / HASH-6480DC989A1310F9

![might](https://user-images.githubusercontent.com/94663834/143382731-a8ceb0e9-d27f-4eaa-841f-942127462311.PNG)

Moorhuhn X (Germany) 
SLES-04174 / HASH-126E0069891E8ACB

![mo](https://user-images.githubusercontent.com/94663834/143382815-c451c3e2-179e-4f1b-9457-f4c2c4eab853.PNG)

**Description of the issue / bug**
All of the listed games are compatible with Guncon. I've tested and verified. 

**Controller Troubleshoot Report**
No
Guncon

**Steps to reproduce**
Start the game with the Guncon selected

**Enhancements information**
All off. 

**Hardware/software**

![specc](https://user-images.githubusercontent.com/94663834/143383856-6d1dd0c8-9058-4080-9088-f98c083bb2b7.JPG)

Tested with Software and Vulkan

**Emulator version**
Duckstation 0.1 - 4819 - g83a031e2

**Additional context**
Here's Wikipedia's list of Guncon compatible games.

![S](https://user-images.githubusercontent.com/94663834/143383954-15b30660-8cd2-433f-9d2c-5c0b2c30209e.PNG)

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation/commit/23a34cb119fa17278072c7a74f45f4b1444abf30
