### ISSUE TITLE
Default Toggle Fast Forward hotkey changes window focus (windowed screen)

### ISSUE THREAD

**Issue by platyhooks** [stenzek/duckstation#2744]
**Description of the issue / bug**
Using the toggle default Fast Forward hotkey (alt) changes DuckStation's window focus. Requiring the user to click back into the window to use hotkeys afterwards.

**Steps to reproduce**
When running in windowed mode and the Fast Forward hotkey (alt) is used the window focus seems to change. After turning Fast Forward off. You can longer user hotkeys (save\load states, save screenshot, fast forward) until you click back into emulator window. Though it does appears the toggle fast forward hotkey itself continues to work. 

If the emulator is fullscreen the issue does not occur.   
  
_This might be a windows issue with using the alt key because changing the hotkey binding seems to alleviate the issue._

**Enhancements information**
Toggled the "Disable All Enchantments" hack to test.

**Hardware/software**
5600x, 3080 RTX, Win 10 Pro
Hardware (D3D11)

**Emulator version**
0.1-4788-gae92ce84 (dev)

**Comment by stenzek** [comment]
Alt is not the default hotkey... If you must use alt, this is likely not fixable, as windows/qt is going to intercept it long before we handle it, and it'd break menu accelerators.

**Comment by platyhooks** [comment]
Crap it appears your right. Restore Defaults doesn't change the hotkeys. I had to delete settings.ini for that.  
Sorry for the bother.

**Comment by stenzek** [comment]
Right. Resetting defaults only applies to settings which actually have a default value (i.e. not controllers/hotkeys).
