### ISSUE TITLE
Twinbee RPG (Japan, Asia)- Discrepancy between software and opengl transparency

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#275]
In the intro sequence, a transparency effect is rendered differently between the two renderers.
![image](https://user-images.githubusercontent.com/50224630/79080076-dd381e00-7cc7-11ea-9a0c-f7d1ea9fe467.png)
Software, correct transparency
![image](https://user-images.githubusercontent.com/50224630/79080081-e628ef80-7cc7-11ea-9dfd-170497fb80f3.png)
OpenGL, incorrect transparency

**Comment by stenzek** [comment]
Please re-test on the latest build when you have time.

**Comment by stenzek** [comment]
Fixed by https://github.com/stenzek/duckstation/commit/9446587e8fa7751b9977e7cdffe3a8f3b6d38d7c
