### ISSUE TITLE
duckstation-git-1:5280.287b1e1a-1

### ISSUE THREAD

**Issue by visious25** [stenzek/duckstation#2751]
**Game details**
[Serial Code, Region]
[SLES-01660 Rollcage (Europe)]
[SLUS-00437 Tomb Raider II (USA)]

**Description of the issue / bug**
[Both games start normally and stopping before gameplay]

**Steps to reproduce**
[1. Rollcage
[visious@archlinux]: ~>$ duckstation-qt 
Program directory "/opt/duckstation"
User directory: "/home/visious/.local/share/duckstation"
[    0.1767] I/SDLControllerInterface: Loading game controller mappings from '/opt/duckstation/database/gamecontrollerdb.txt'
Loaded translation file for language  "en"
[   24.7157] I/HostInterface: Boot Filename: /home/visious/PlayStation/PS1/RollCage/RollCage - PAL/RC.img
[   24.7748] W(ErrorHandler): X11 Error: BadMatch (invalid parameter attributes) (Error 8 Minor 34 Request 154)
[   24.7772] W(ErrorHandler): X11 Error: BadMatch (invalid parameter attributes) (Error 8 Minor 34 Request 154)
[   24.7881] W(ErrorHandler): X11 Error: BadValue (integer parameter out of range for operation) (Error 2 Minor 34 Request 154)
[   24.7912] W(ErrorHandler): X11 Error: BadValue (integer parameter out of range for operation) (Error 2 Minor 34 Request 154)
[   24.7957] W(ErrorHandler): X11 Error: BadValue (integer parameter out of range for operation) (Error 2 Minor 34 Request 154)
[   24.7971] W(ErrorHandler): X11 Error: BadValue (integer parameter out of range for operation) (Error 2 Minor 34 Request 154)
[   24.7984] W(ErrorHandler): X11 Error: BadValue (integer parameter out of range for operation) (Error 2 Minor 34 Request 154)
[   24.9069] I/GL::Context: Created a OpenGL context
[   24.9113] I/GL::Context: GL_VENDOR: NVIDIA Corporation
[   24.9113] I/GL::Context: GL_RENDERER: GeForce G105M/PCIe/SSE2
[   24.9113] I/GL::Context: GL_VERSION: 3.3.0 NVIDIA 340.108
[   24.9113] I/GL::Context: GL_SHADING_LANGUAGE_VERSION: 3.30 NVIDIA via Cg compiler
[   24.9470] E(CompileShader): Shader compiled with warnings:

[   24.9470] E(CompileShader): Shader compiled with warnings:

[   24.9470] E(CompileShader): Shader compiled with warnings:

[   24.9471] E(CompileShader): Shader compiled with warnings:

[   24.9473] E(Link): Program linked with warnings:

[   24.9476] E(Link): Program linked with warnings:

[   25.0222] E(LoadTexture): Failed to open texture resource 'resources/logo.png'
[   25.0364] I/HostInterface: Creating 'Cubeb' audio stream, sample rate = 44100, channels = 2, buffer size = 2048
[   25.0389] I/CubebAudioStream: Minimum latency in frames: 1102
[   25.0416] I/System: Loading CD image '/home/visious/PlayStation/PS1/RollCage/RollCage - PAL/RC.img'...
[   25.0420] I/System: Auto-detected console PAL region for '/home/visious/PlayStation/PS1/RollCage/RollCage - PAL/RC.img' (region PAL)
[   25.0420] I/System: Console Region: PAL (Europe, Australia)
[   25.0420] I/HostInterface: Searching for a PAL (Europe, Australia) BIOS in '/home/visious/.local/share/duckstation/bios'...
[   25.0439] W(FindBIOSImageInDirectory): Falling back to possibly-incompatible image '/home/visious/.local/share/duckstation/bios/SCPH1001.BIN': SCPH-1001, 5003, DTL-H1201, H3001 (v2.2 12-04-95 A)
[   25.1602] I/GameSettings: Loaded settings for 260 games
[   25.1604] I/GameSettings: Loaded settings for 1 games
[   25.1625] I/Common::MemoryArena: File mapping name: duckstation_4045829
[   25.1626] I/Bus: RAM is 2097152 bytes at 0x7f1d2e1c9000
[   25.1661] I/GPU_HW_OpenGL: Max texture size: 8192x8192
[   25.1661] I/GPU_HW_OpenGL: Per-sample shading: supported
[   25.1661] I/GPU_HW_OpenGL: Max multisamples: 16
[   25.1661] I/GPU_HW_OpenGL: Uniform buffer offset alignment: 256
[   25.1662] W(SetCapabilities): GL_EXT/OES_copy_image missing, this may affect performance.
[   25.1662] I/GPU_HW_OpenGL: Max texel buffer size: 134217728
[   25.1662] I/GPU_HW: Resolution Scale: 3 (3072x1536), maximum 8
[   25.1662] I/GPU_HW: Multisampling: 1x
[   25.1662] I/GPU_HW: Dithering: Disabled
[   25.1662] I/GPU_HW: Texture Filtering: Nearest-Neighbor
[   25.1662] I/GPU_HW: Dual-source blending: Supported
[   25.1662] I/GPU_HW: Using UV limits: NO
[   25.1662] I/GPU_HW: Depth buffer: NO
[   25.1662] I/GPU_HW: Downsampling: Disabled
[   25.1663] I/GPU_HW: Using software renderer for readbacks: NO
[   25.1895] I/GL::ShaderCache: 1 program binary formats supported by driver
[   25.1905] I/GL::ShaderCache: Read 126 entries from '/home/visious/.local/share/duckstation/cache/gl_programs.idx'
[   25.3779] I/Bus: Fastmem base: 0x7f1bf727f000
[   25.4061] I/CDROMAsyncReader: Read thread started with readahead of 8 sectors
[   25.4094] I/MemoryCard: Loaded memory card from /home/visious/.local/share/duckstation/memcards/Rollcage (Europe) (En,Fr,De,Es,It)_1.mcd
[   25.4771] I/CDROM: Inserting new media, disc region: PAL, console region: PAL
[   25.5581] I/FrontendCommon: Screensaver suspended by 0x3a00025.
[   25.5610] I/CommonHostInterface: Target speed: 100.000000%
[   25.5610] I/CommonHostInterface: Syncing to audio and video
[   25.5611] I/CommonHostInterface: Max display fps: 0.000000 (skipping displaying frames when needed)
[   25.5611] I/CommonHostInterface: Audio input sample rate: 44100 hz
[   41.1925] W(ExecuteCommand): CDROM Pause command while seeking from 184 to 166 - jumping to seek target
[   42.6877] W(BeginCommand): Cancelling pending command 0x09 (Pause) second response
[   44.3825] W(ExecuteCommand): CDROM Pause command while seeking from 253 to 166 - jumping to seek target
[   60.8275] I/MemoryCard: Writing memory card sector 63
[   64.3804] W(DoEXP1Access): EXP1 write: 0x1F7FFFD8 <- 0x00000031
[   64.3805] W(DoEXP1Access): EXP1 write: 0x1F7FFFD4 <- 0xBFC01530
[   64.3805] W(DoEXP1Access): EXP1 write: 0x1F7FFFB4 <- 0x00004124
[   64.3805] W(DoEXP1Access): EXP1 write: 0x1F7FFFC4 <- 0x1F7FFFD8
[   64.3805] W(DoEXP1Access): EXP1 write: 0x1F7FFFC8 <- 0x00000001
[   64.3805] W(DoEXP1Access): EXP1 write: 0x1F7FFFBC <- 0x00008674
[   64.3805] W(DoEXP1Access): EXP1 write: 0x1F7FFF90 <- 0x80191D99
[   64.3805] W(DoEXP1Access): EXP1 write: 0x1F7FFF8C <- 0x00000000
[   64.3805] W(DoEXP1Access): EXP1 write: 0x1F7FFF88 <- 0x00000001
[   64.3805] W(DoEXP1Access): EXP1 write: 0x1F7FFF94 <- 0x00002CDC
it stops here]

[2. Tomb Raider II 
[visious@archlinux]: ~>$ duckstation-qt 
Program directory "/opt/duckstation"
User directory: "/home/visious/.local/share/duckstation"
[    0.2043] I/SDLControllerInterface: Loading game controller mappings from '/opt/duckstation/database/gamecontrollerdb.txt'
Loaded translation file for language  "en"
[   21.0904] I/HostInterface: Boot Filename: /home/visious/PlayStation/PS1/Tomb Raider/Tomb Raider 2/Tomb Raider 2 [U] [SLUS-00437].img
[   21.1296] W(ErrorHandler): X11 Error: BadMatch (invalid parameter attributes) (Error 8 Minor 34 Request 154)
[   21.1305] W(ErrorHandler): X11 Error: BadMatch (invalid parameter attributes) (Error 8 Minor 34 Request 154)
[   21.1406] W(ErrorHandler): X11 Error: BadValue (integer parameter out of range for operation) (Error 2 Minor 34 Request 154)
[   21.1425] W(ErrorHandler): X11 Error: BadValue (integer parameter out of range for operation) (Error 2 Minor 34 Request 154)
[   21.1444] W(ErrorHandler): X11 Error: BadValue (integer parameter out of range for operation) (Error 2 Minor 34 Request 154)
[   21.1457] W(ErrorHandler): X11 Error: BadValue (integer parameter out of range for operation) (Error 2 Minor 34 Request 154)
[   21.1473] W(ErrorHandler): X11 Error: BadValue (integer parameter out of range for operation) (Error 2 Minor 34 Request 154)
[   21.2062] I/GL::Context: Created a OpenGL context
[   21.2106] I/GL::Context: GL_VENDOR: NVIDIA Corporation
[   21.2106] I/GL::Context: GL_RENDERER: GeForce G105M/PCIe/SSE2
[   21.2106] I/GL::Context: GL_VERSION: 3.3.0 NVIDIA 340.108
[   21.2106] I/GL::Context: GL_SHADING_LANGUAGE_VERSION: 3.30 NVIDIA via Cg compiler
[   21.2495] E(CompileShader): Shader compiled with warnings:

[   21.2496] E(CompileShader): Shader compiled with warnings:

[   21.2496] E(CompileShader): Shader compiled with warnings:

[   21.2496] E(CompileShader): Shader compiled with warnings:

[   21.2499] E(Link): Program linked with warnings:

[   21.2501] E(Link): Program linked with warnings:

[   21.3200] E(LoadTexture): Failed to open texture resource 'resources/logo.png'
[   21.3294] I/HostInterface: Creating 'Cubeb' audio stream, sample rate = 44100, channels = 2, buffer size = 2048
[   21.3320] I/CubebAudioStream: Minimum latency in frames: 1102
[   21.3346] I/System: Loading CD image '/home/visious/PlayStation/PS1/Tomb Raider/Tomb Raider 2/Tomb Raider 2 [U] [SLUS-00437].img'...
[   21.3351] I/System: Auto-detected console NTSC-U region for '/home/visious/PlayStation/PS1/Tomb Raider/Tomb Raider 2/Tomb Raider 2 [U] [SLUS-00437].img' (region NTSC-U)
[   21.3351] I/System: Console Region: NTSC-U/C (US, Canada)
[   21.3351] I/HostInterface: Searching for a NTSC-U/C (US, Canada) BIOS in '/home/visious/.local/share/duckstation/bios'...
[   21.3369] I/HostInterface: Using BIOS 'SCPH1001.BIN': SCPH-1001, 5003, DTL-H1201, H3001 (v2.2 12-04-95 A)
[   21.4634] I/GameSettings: Loaded settings for 260 games
[   21.4635] I/GameSettings: Loaded settings for 1 games
[   21.4653] I/Common::MemoryArena: File mapping name: duckstation_4050768
[   21.4654] I/Bus: RAM is 2097152 bytes at 0x7f391cb83000
[   21.4682] I/GPU_HW_OpenGL: Max texture size: 8192x8192
[   21.4683] I/GPU_HW_OpenGL: Per-sample shading: supported
[   21.4683] I/GPU_HW_OpenGL: Max multisamples: 16
[   21.4683] I/GPU_HW_OpenGL: Uniform buffer offset alignment: 256
[   21.4683] W(SetCapabilities): GL_EXT/OES_copy_image missing, this may affect performance.
[   21.4683] I/GPU_HW_OpenGL: Max texel buffer size: 134217728
[   21.4683] I/GPU_HW: Resolution Scale: 3 (3072x1536), maximum 8
[   21.4684] I/GPU_HW: Multisampling: 1x
[   21.4684] I/GPU_HW: Dithering: Disabled
[   21.4684] I/GPU_HW: Texture Filtering: Nearest-Neighbor
[   21.4684] I/GPU_HW: Dual-source blending: Supported
[   21.4684] I/GPU_HW: Using UV limits: NO
[   21.4684] I/GPU_HW: Depth buffer: NO
[   21.4684] I/GPU_HW: Downsampling: Disabled
[   21.4684] I/GPU_HW: Using software renderer for readbacks: NO
[   21.4916] I/GL::ShaderCache: 1 program binary formats supported by driver
[   21.4918] I/GL::ShaderCache: Read 126 entries from '/home/visious/.local/share/duckstation/cache/gl_programs.idx'
[   21.6695] I/Bus: Fastmem base: 0x7f37e1c7e000
[   21.7022] I/CDROMAsyncReader: Read thread started with readahead of 8 sectors
[   21.7043] I/MemoryCard: Loaded memory card from /home/visious/.local/share/duckstation/memcards/Tomb Raider II - Starring Lara Croft (USA)_1.mcd
[   21.7671] I/CDROM: Inserting new media, disc region: NTSC-U, console region: NTSC-U
[   21.8373] I/FrontendCommon: Screensaver suspended by 0x3a0001c.
[   21.8390] I/CommonHostInterface: Target speed: 100.000000%
[   21.8393] I/CommonHostInterface: Syncing to audio and video
[   21.8395] I/CommonHostInterface: Max display fps: 0.000000 (skipping displaying frames when needed)
[   21.8395] I/CommonHostInterface: Audio input sample rate: 44100 hz
[   37.9181] I/MemoryCard: Writing memory card sector 63
[   84.3578] I/FrontendCommon: Screensaver resumed.
it stops here]

**Emulator version**
[duckstation-git-1:5280.287b1e1a-1]

**Additional context**
[I'm currently running arch linux]

**Comment by stenzek** [comment]
Talk to your packager they've probably screwed things up (unless it's also broken with the appimage)

**Comment by visious25** [comment]
Hi, it's not appimage I've installed form AUR https://aur.archlinux.org/packages/duckstation-git/ this is the latest package (the package is fine.)

**Comment by stenzek** [comment]
Then talk to your packager. I don't use arch so it's not my problem

**Comment by visious25** [comment]
I will. With all your respect the packager tell me to report the problem here first. The packager is responsible to build the package from the source code.

**Comment by kattjevfel** [comment]
> Talk to your packager they've probably screwed things up (unless it's also broken with the appimage)

Come on man, I try to set up the pkgbuild basically just the same way as the github workflow, do you really have to be an asshole to all other packagers than yourself?

**Comment by visious25** [comment]
I have downloaded the last appimage.I tried with chmod +x duckstation-qt-x64.AppImage and it's not working at all (I mean it doesn't run any game).

**Comment by visious25** [comment]
These 2 games are not working even on windows 10. I have already tested if you are curious.

**Comment by visious25** [comment]
It would be nice to open this issue as bug.

**Comment by ggrtk** [comment]
These two titles are working fine for me on Windows 10.

**Comment by stenzek** [comment]
TR2 is also fine here, the fact that it's writing into EXP1 suggests that either it's a bad dump (BIOS or game), which you can verify in game properties, or your packager screwed something up, which is why I suggested using the official build.

**Comment by stenzek** [comment]
> I will. With all your respect the packager tell me to report the problem here first. The packager is responsible to build the package from the source code.

Then they should read the very clear message I have in the readme:
> DuckStation does support Linux, but no support will be provided by the developer due to the huge range and variance of distributions. AppImage builds are provided, but we are not obliged to provide any assistance or investigate any issues, i.e. use at your own risk. However, these binaries may be incompatible with older Linux distros (e.g. Ubuntu distros earlier than 20.04 LTS) due to older distros not providing newer versions of the C/C++ standard libraries required by the AppImage binaries. If you are using a packaged version of DuckStation from another source, please do not ask us for assistance and speak to your packager instead.

**Comment by BailShamber** [comment]
> I have downloaded the last appimage.I tried with chmod +x duckstation-qt-x64.AppImage and it's not working at all (I mean it doesn't run any game).
@visious25 
Try setting `WAYLAND_DISPLAY=no` env var before running the appimage and report back whether it made games work.

**Comment by visious25** [comment]
@stenzek, @BailShamber
I'm only using AUR (Arch User Repository) packages. I don't mess up with appimages. Duckstation working well, I'm happy with arch.

The point is I solved my problem, for some reasons my ISOs was corrupted, I don't know why. I re-download the games and working fine.

Thank you all
