### ISSUE TITLE
Duckstation incorrectly warns that several games are incompatible with the Playstation Mouse

### ISSUE THREAD

**Issue by helmutkohl1991** [stenzek/duckstation#2753]
**Game details**

Arkanoid Returns (Japan)
SLPS-00948 / HASH-906281BBF781FE85

![ark](https://user-images.githubusercontent.com/95162882/143764263-0398f45a-0db7-444b-8d2f-44a06f214ba6.PNG)

Cyberia (USA)
SLUS-00053 / HASH-E39AD9F02AD1891

![cyber](https://user-images.githubusercontent.com/95162882/143764277-2c51c56d-8171-455b-b7f5-40c9bd3a28fb.PNG)

Front Mission Alternative (Japan)
SLPM-87398 / HASH-5FF4539320A13641

![fro](https://user-images.githubusercontent.com/95162882/143764292-f1f20f9e-4608-4d26-9268-2049b6f44c91.PNG)

Virtual Pool (USA)
SLUS-00034 / HASH-CF360ED0B0227E7F

![pool](https://user-images.githubusercontent.com/95162882/143764307-58b79904-40aa-4b53-a46e-87ad56bf0479.PNG)

Shanghai - True Valor (Europe)
SLES-01618 / HASH-21996BF2A2BD1357

![shang](https://user-images.githubusercontent.com/95162882/143764545-303c7d07-11fd-4175-b4e1-3fc724664493.PNG)

**Description of the issue / bug**
All of these games are compatible with the PlayStation Mouse

**Controller Troubleshoot Report**
No
PlayStation Mouse

**Steps to reproduce**
Start the games with PlayStation Mouse

**Enhancements information**
All off

**Hardware/software**
![specs](https://user-images.githubusercontent.com/95162882/143764344-8e36a810-6253-415c-a745-b7f591645911.jpg)

Tested with Software

**Emulator version**
Duckstation 0.1 - 4838 - g46f9da97

**Additional context**
Wikipedia's list of games that support PlayStation Mouse.

![mouse](https://user-images.githubusercontent.com/95162882/143764416-a50d0d1a-6f45-4da0-8722-bf2f4cf94e60.PNG)

https://en.wikipedia.org/wiki/PlayStation_Mouse

**Comment by bslenul** [comment]
https://github.com/stenzek/duckstation/pull/2743#issuecomment-979440727
#2748
#2742

You know you can use a single GitHub account to report multiple issues, right? 🤔

**Comment by helmutkohl1991** [comment]
@bslenul Just how it has to be at the moment. Also I noticed you didn't change the warning in Puffy: P.S. I Love You. Are you SURE the game doesn't support Guncon? 

![PSX_Longplay_-_Puffy_no_PS_I Love_You_-_JP_000058](https://user-images.githubusercontent.com/95162882/143766823-faff8d88-ac8c-43a9-9f62-9d84221fca6a.jpg)

https://youtu.be/Ta8pUs8ruGA?t=93

**Comment by bslenul** [comment]
Hm yeah weird, I definitely updated that one, not sure why the notification is still appearing 🤔 

![image](https://user-images.githubusercontent.com/33353403/143767762-5e021f92-7ad2-4621-ac81-2aea6cb68c0d.png)

Serial and MD5 are correct:

![image](https://user-images.githubusercontent.com/33353403/143767728-32e89a9e-431d-4ab2-88ab-29e4b89a4498.png)

**Comment by helmutkohl1991** [comment]
@bslenul That took care of the warning, thanks. Now the only one I'm confused about is Die Hard Trilogy 2: Viva Las Vegas. Duckstation has no warning about the Guncon being incompatible but both the US and Euro versions say the gun IS incompatible. 

![diehard](https://user-images.githubusercontent.com/95162882/143776297-60ed615d-f6a6-426e-9ea3-73d5de6a1c9c.PNG)

But Wikipedia says otherwise.

![Capture](https://user-images.githubusercontent.com/95162882/143776333-436f03c5-1274-4253-9e15-17bc26a4671a.PNG)

**Comment by bslenul** [comment]
You have to set the GunCon in port 2 for that game ;)

**Comment by helmutkohl1991** [comment]
@bslenul Well now I feel dumb lol. Thanks for the info.

**Comment by helmutkohl1991** [comment]
@bslenul Any idea how to fix this? The red thing is the actual crosshair and it's not matching up with Duckstation's at all. 

![Capture](https://user-images.githubusercontent.com/95162882/143779369-d438f304-1aa2-4137-b5b8-d1fc634ba9b6.PNG)

**Comment by bslenul** [comment]
Go to the in-game options > controls > calibrate gun, then it should be fine:

![image](https://user-images.githubusercontent.com/33353403/143779685-9d053b7b-d34e-4fbb-9bb3-02e8b8576af4.png)

We're getting way off-topic tho... :p
