### ISSUE TITLE
Duckstation incorrectly warns that several games are incompatible with the Negcon controller

### ISSUE THREAD

**Issue by sigarettenstank** [stenzek/duckstation#2755]
**Game details**

Arkanoid Returns (Japan)
SLPS-00948 / HASH-906281BBF781FE85

![ark](https://user-images.githubusercontent.com/95235094/144084885-17eee08c-5e4a-4246-a233-d17da66ca3a4.PNG)

J. League Soccer - Prime Goal EX (Japan)
SLPS-00079 / HASH-58FBE07C09E0F30C

![soccer](https://user-images.githubusercontent.com/95235094/144085006-996332b4-7ced-4de0-80d9-3e10adf600c1.PNG)

Studio P (Japan)
SLPS-00403 / HASH-27FA743AEF08E74B

![studio](https://user-images.githubusercontent.com/95235094/144085093-307902cd-a396-422e-9514-df9a955ce34e.PNG)

Tempest X3 (USA)
SLUS-00283 / HASH-4EF52B0D98433D56

![temp](https://user-images.githubusercontent.com/95235094/144085180-4f6117dc-de57-4054-98d5-8b50ddf752e9.PNG)

**Description of the issue / bug**
All of these games are compatible with the Negcon controller.

**Controller Troubleshoot Report**
No
Negcon controller

**Steps to reproduce**
Start the game with the Negcon controller

**Enhancements information**
All off

**Hardware/software**

![143764344-8e36a810-6253-415c-a745-b7f591645911](https://user-images.githubusercontent.com/95235094/144085658-7e2ec6d4-0154-48f0-b222-2066dbe8da36.jpg)

Tested with Software

**Emulator version**
Duckstation 0.1 - 4838 - g46f9da97

**Additional context**
Wikipedia's list of Negcon compatible games.

https://en.wikipedia.org/wiki/NeGcon#

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/f63f5d829d72b83dbc82d961b754028d3aa98f05.
