### ISSUE TITLE
Twinbee RPG (Japan, Asia), True Love Story 2 (Japan) (Disc 1)  texture coordinate off-by-one error in OpenGl

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#276]
![image](https://user-images.githubusercontent.com/50224630/79080135-2e481200-7cc8-11ea-8052-983c3a58dae0.png)
software
![image](https://user-images.githubusercontent.com/50224630/79080140-386a1080-7cc8-11ea-839a-0bb37bb25e4e.png)
opengl

![image](https://user-images.githubusercontent.com/50224630/79080147-40c24b80-7cc8-11ea-93b7-aa7c841706c7.png)
software
![image](https://user-images.githubusercontent.com/50224630/79080157-4750c300-7cc8-11ea-8f7f-dad2addd19e4.png)
opengl

**Comment by stenzek** [comment]
Merged with https://github.com/stenzek/duckstation/issues/361
