### ISSUE TITLE
Can you replace resume button with start?

### ISSUE THREAD

**Issue by kotenok2000** [stenzek/duckstation#2762]
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Is your feature request related to a problem? Please describe.**
I have disabled save state on exit and deleted savestates, but big play button still reads resume and gives  "no resume savestate found" popup when clicked.

**Describe the solution you'd like**
Change resume button to start if there are no savestates for a game.
**Describe alternatives you've considered**

**Additional context**

**Comment by stenzek** [comment]
This behaviour was reworked in the UI overhaul (with the confirm popup).
