### ISSUE TITLE
Mechwarrior 2 (USA) save stating on main menu forces reload memory card

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#277]
Every time I load a save state on mechassult 2 on the main menu, a screen about a new memory card being inserted appears, requiring me to either save or load data whenever a save state is loaded on the menu. 
![image](https://user-images.githubusercontent.com/50224630/79105319-48640d80-7d25-11ea-8cb5-cd1f0c5f65f8.png)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/25af5ef9d98c369260327c62461405a9dce2259c
