### ISSUE TITLE
Missing cubes in rendered image

### ISSUE THREAD

**Issue by spacepaw** [stenzek/duckstation#2770]
**Game details**
It's a demo/homebrew program (single ps-exe) that can be downloaded from the demo scene portal called "pout":
https://www.pouet.net/prod.php?which=49578

**Description of the issue / bug**
1. In the lower right corner of the screen should be 3 cubes, which are missing
2. Signification lag between text page changes

**Controller Troubleshoot Report**
Steam not open, not aware of any drivers or wrappers being installed. Controller Backend is SDL.

**Steps to reproduce**
1. Load ps-exe file
2. Missing cubes in lower right corner immediately "visible"
3. Wait a few seconds for the text page to change, notice huge lag/freeze

**Enhancements information**
Turned all off

**Hardware/software**
AMD Ryzen 3900X, NVIDIA GeForce RTX 2080, Windows 10
Renderer: Hardware (D3D11) (can be reproduced with all renderers)

**Emulator version**
0.1-4788-gae92ce84 (dev)

**Additional context**

How it looks in duckstation:
![image](https://user-images.githubusercontent.com/76810945/146670556-7def7dc0-4a8a-435a-b1c5-e11508a7ec9f.png)

How it looks on hardware and avocado emulator:
![image](https://user-images.githubusercontent.com/76810945/146670578-f4cc5d41-9a38-4fae-b2fe-823d0f230885.png)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/1185f8f6aa99e8e48e31fa78dbf28815b3260039 (requires booting with software renderer).
