### ISSUE TITLE
Displays black screen only

### ISSUE THREAD

**Issue by spacepaw** [stenzek/duckstation#2771]
**Game details**
It's a demo/homebrew program (single ps-exe) that can be downloaded from the demo scene portal called "pouet":
https://www.pouet.net/prod.php?which=33229

**Description of the issue / bug**
DuckStation displays just a black screen. You can still hear the music though.

**Controller Troubleshoot Report**
Steam not open, not aware of any drivers or wrappers being installed. Controller Backend is SDL.

**Steps to reproduce**

1. Load ps-exe file
2. Notice it displays a black screen only

**Enhancements information**
Turned all off

**Hardware/software**
AMD Ryzen 3900X, NVIDIA GeForce RTX 2080, Windows 10
Renderer: Hardware (D3D11)

**Emulator version**
0.1-4788-gae92ce84 (dev)

**Additional context**

How it looks in DuckStation:
![image](https://user-images.githubusercontent.com/76810945/146781677-654c7529-682e-4506-960e-8b17b561a828.png)

How it looks on hardware and Avocado:
![image](https://user-images.githubusercontent.com/76810945/146781708-57bb7671-1c0c-4d59-9e69-347ac28aefc6.png)

**Comment by stenzek** [comment]
Fixed by https://github.com/stenzek/duckstation/commit/25f725c263995aac33de82cb8726351dc44858c2
