### ISSUE TITLE
Emulator hangs during open file dialog

### ISSUE THREAD

**Issue by PopovMark** [stenzek/duckstation#2772]
**Game details**
This is not a game issue, it's an emulator issue.

**Description of the issue / bug**
On the Qt frontend, when starting a file, adding a gamelist directory, or changing the disc from a file, instead of opening the window for selecting a file, the emulator hangs. It continues to hang until it is closed, which then results in an empty crash dump and a crash.txt file in which is written: "Exception 0xC0000005 at 0x00007FF9FB3F3D96". This means I am unable to even launch a game from the frontend, having to resort to the nogui version.

**Controller Troubleshoot Report**
It's a keyboard, nothing special about it.

**Steps to reproduce**
Run the emulator with the Qt frontend, then do any of the following:

Start File;
Start BIOS -> Change Disc -> From File;
Settings -> Gamelist Settings -> Add.

**Enhancements information**
They're turned off.

**Hardware/software**
Laptop
Win10
Intel Core i5-7300HQ
NVIDIA GeForce GTX 1050
12 GB RAM
Direct3D 11 frontend

**Emulator version**
0.1-4788-gae92ce84 (dev)

**Comment by stenzek** [comment]
Not an emu issue, you're probably using a broken shell extension like oldnewexplorer which seems to conflict with qt.
