### ISSUE TITLE
Run ahead lagging on powerful specs.

### ISSUE THREAD

**Issue by Bateman34** [stenzek/duckstation#2776]
**Game details**
Every game

**Description of the issue / bug**
Run ahead causes game to stutter and run poorly despite my specs being more than enough.

**Steps to reproduce**
Using default, with run ahead active (I tried 1 frame, 2 frame, etc.)

**Enhancements information**
default

**Hardware/software**
GTX 970, i7 9700, 16GB DDR4 3400mhz ram

**Emulator version**
0.1-4788-gae92ce84

**Comment by stenzek** [comment]
Not a bug, but the latest preview build enables runahead with the recompiler.

**Comment by Bateman34** [comment]
Ok thank you for confirming
