### ISSUE TITLE
Animorphs - Shattered Reality (USA) opening runs at hundreds/thousands of fps

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#278]
It's exactly what the title describes. It runs at an incredibly high framerate, resulting in a lot of slowdown and the intro taking much longer to finish playing.

**Comment by stenzek** [comment]
Is this still an issue in the latest build? The intro seems fine.

**Comment by kurayami6** [comment]
The game does claim to be running at 600 FPS but I don't see any slowdown. It looks like it's running exactly the same as on real hardware. I think this can be closed. 

https://youtu.be/TAB5I_Rj3ZY?t=48
