### ISSUE TITLE
Rewind is broken on all games since Christmas Eve.

### ISSUE THREAD

**Issue by SilentHeII** [stenzek/duckstation#2781]
**Game details**
SCUS-94164, Final Fantasy VII (USA) (Disc 2)
SLUS-00707, Silent Hill (USA)
SLUS-00152, Tomb Raider (USA)
Various others

**Description of the issue / bug**
Rewinding during gameplay will cause the game to hang or freeze almost as if you removed the game disc. My rewind settings ate 100 frames total saved with one frame every 10 seconds. I have 16GB of RAM and did not have this issue before yesterday's update.

**Steps to reproduce**
Enable rewind, play any game and try loading rooms/menus/effects and rewind to the previous room. Continue playing and the game will freeze trying to load an effect/menu/room.

**Enhancements information**
All enhancements aside from rewind turned off.

**Hardware/software**
https://pcpartpicker.com/list/vNr3fP
Set renderer to D3D11.

**Emulator version**
0.1-4854-gbee50481

Here is a video example: https://streamable.com/uyj2e7

**Comment by SilentHeII** [comment]
[Final Fantasy VII (USA) (Disc 1)_1.zip](https://github.com/stenzek/duckstation/files/7777331/Final.Fantasy.VII.USA.Disc.1._1.zip)
Here is the save I used for the video.

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/541947c6f8f0bf674b38a647a5700fb6a647687e
