### ISSUE TITLE
Great amounts of dithering even though True Color Rendering is used

### ISSUE THREAD

**Issue by RavenMacDaddy** [stenzek/duckstation#2788]
**Game details**
![image](https://user-images.githubusercontent.com/67732686/147588963-beda17db-6c19-467d-9287-5b708847f72f.png)

**Description of the issue / bug**
Even though True Color Rendering is enabled, there are great amounts of dithering in what seems to be all games, using Chrono Cross as a clear example of this.

Thing is, TCR has worked flawlessly previously, regardless of GPU driver version or Windows OS from what I recall, so I'm really not sure what's the root of the issue.

Pictures:

![image](https://user-images.githubusercontent.com/67732686/147589626-f06d7f37-8cb0-4cc0-a919-ed20f33619ee.png)

![image](https://user-images.githubusercontent.com/67732686/147589745-e3e531a1-ec79-4a4f-8249-0973f0e2848b.png)

![image](https://user-images.githubusercontent.com/67732686/147589758-53abcfc0-5bf8-4e76-9d70-d536b9e71936.png)

![image](https://user-images.githubusercontent.com/67732686/147589780-222fe729-e8e7-4284-8b68-a80f52490065.png)

![image](https://user-images.githubusercontent.com/67732686/147589885-9e15abc2-c33f-45af-b010-87b6ea7ed3bc.png)

![image](https://user-images.githubusercontent.com/67732686/147589907-d1adc2cb-c56f-4e5e-b5e2-bfcc042a4589.png)

**Steps to reproduce**

1. Run a game that's using a lot of dithering in its rendering, like Chrono Cross.
2. In the example given, the demo that's playing directly at boot or at least after pressing a button to get to the title screen will show multiple scenes where dithering is used, and consequently where the issue occurs.

**Enhancements information**

![image](https://user-images.githubusercontent.com/67732686/147589675-2d2e4f01-c4fd-434e-b3d1-cbc38dc90f08.png)

True Color Rendering is enabled which should disable any dithering.

**Hardware/software**
CPU: Ryzen 3600
GPU: GTX 1080 - driver 497.09
OS: Windows 11 - 22000.376

GPU Renderer - Regardless of which one is being used; D3D11/OpenGL/Vulkan

**Emulator version**
![image](https://user-images.githubusercontent.com/67732686/147589525-5251fd2d-71b8-453c-86f9-7b4b96b69c8d.png)

**Additional context**
This issue is very similar to what's being shown in #1218.

**Comment by drachenschanze** [comment]
Are you sure that isn't dithering baked into the textures? Some games do that. 

![1634947608842](https://user-images.githubusercontent.com/96800307/147713511-a89e77fb-d729-4e4f-b2c8-ed6f020d18ee.png)

**Comment by RavenMacDaddy** [comment]
Good question. I just recalled having run Chrono Cross previously without the dithering, but I'll try some more titles to make sure. 

If you know any titles where TCR should definitely remove any dithering, let me know and I'll test on my system.

**Comment by stenzek** [comment]
The textures only have 16 bit colour depth (either direct, or from a 4/256 colour palette). The only time you get "smooth" gradients is when lighting is used in combination with the texture, which is not the case here.
