### ISSUE TITLE
Nightmare Creatures II (USA) - skipping vector while audio is playing anyways

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#279]
During Therapy (the game's training mode) the terminal returns 

    [ 3826.4304] W(DoSectorRead): Skipping sector 266670 as it is a audio sector and we're not playing
    [ 3826.4309] W(DoSectorRead): Skipping sector 266671 as it is a audio sector and we're not playing
    [ 3826.4316] W(DoSectorRead): Skipping sector 266672 as it is a audio sector and we're not playing]
constantly, the number increasing rapidly as you play. Despite this, audio is currently playing. This may be intended behaviour, but I'm not sure.

**Comment by stenzek** [comment]
That happens when the CD-ROM is reading data from an audio track. The game might unintentionally do this. As long as nothing is broken, it should be fine.
