### ISSUE TITLE
Performance issue in hogs of war.

### ISSUE THREAD

**Issue by mzso** [stenzek/duckstation#2790]
### Game details

SLES-01041

### Description of the issue/bug

There's a remarkable slowdown, stutter when multiple explosions are happening with enhancements enabled.
Otherwise the game runs at normal speed, so I'm thinking there might be an issue here with the enhancements performance, or such.

### Steps to reproduce

I have these set:
![kép](https://user-images.githubusercontent.com/4479090/147821240-1eaf8ead-23ac-468a-892d-bd3a0c929a08.png)

The issue typically represents itself with cluster grenades or airburts. Also the similar effect of spy/sniper pigs coming out of hiding, shown at the end of the second video.
I tried to record it as representatively as possible, with also recording without enhancements for comparison:
https://drive.google.com/file/d/1aFtxYiOo6TioO6OC3jKKXe6xHDCDW6lE/view?usp=sharing
https://drive.google.com/file/d/1JfxN0xLOUo4_XdcRr7pvHkPgP3DrEyx8/view?usp=sharing
https://drive.google.com/file/d/1DzOGfLg26gv9jt2WjkPsowWFqO_ZWJvk/view?usp=sharing
https://drive.google.com/file/d/1YiWC9VL2fsIb2uOfsdX8rDXQHMIumeaS/view?usp=sharing

### Software and hardware information

Windows 10. Ryzen R5 1600, Asus DUAL-RX580-O4G

### DuckStation version

0.1-4854-gbee50481 (master)

### DuckStation rendering backend

Direct3D 11

### DuckStation controller backend, drivers and wrappers

Xinput with DSHidMini (doubt that it's relevant)

### Additional context

Not really scientific observation, but I think I saw a spike in GPU usage during these stutters, when I happened to look.
I don't think a few rather low tech effects should result in such huge increase in CPU usage and the game stuttering.

**Comment by andercard0** [comment]
Slow downs and stutters are being caused due to this XBR filter you're using in combination with a higher resolution your PC will struggle. also, turn off Preserve projection precison and you'll be good to go. not a emulator issue.

**Comment by mzso** [comment]
[**@andercard0**](https://github.com/andercard0) commented on [2021. dec. 31. 12:56 CET](https://github.com/stenzek/duckstation/issues/2790#issuecomment-1003357390 "2021-12-31T11:56:22Z - Replied by Github Reply Comments"):
> Slow downs and stutters are being caused due to this XBR filter you're using in combination with a higher resolution your PC will struggle. also, turn off Preserve projection precison and you'll be good to go. not a emulator issue.
> 
> oh, and by the way, the issue template is clear when it states:  

Won't disabling this reduce the graphics quality?

> **All enhancements must be off. To quickly disable all enhancements with affecting your normal configuration, you can check Disable All Enhancements in Advanced Options.**
> 
> Making this topic invalid i do believe!

Well, how do you open issues **_about_** enhancements then?
