### ISSUE TITLE
Tomba blue flash when exiting from menu

### ISSUE THREAD

**Issue by ualaa1** [stenzek/duckstation#2791]
### Game details

SCUS-94236 Tomba! USA

### Description of the issue/bug

When exiting out of the menu in software renderer, it flashes blue for a second.
Have not tested on hardware render.

https://user-images.githubusercontent.com/68984176/147914252-1cb85509-ab0e-4d90-b244-3ee05db50687.mp4

### Steps to reproduce

Go to menu, which is activated using triangle button.
Exit menu and see the blue flash

### Software and hardware information

Windows 10 Intel I7

### DuckStation version

0.1-4788, through automatic updater

### DuckStation rendering backend

Software

### DuckStation controller backend, drivers and wrappers

Using keyboard controls

**Comment by stenzek** [comment]
Does this happen on hardware?

**Comment by coornio** [comment]
Seems to be normal, watch the video at the timestamp.
