### ISSUE TITLE
Hydro Thunder CTD

### ISSUE THREAD

**Issue by rhester72** [stenzek/duckstation#2792]
### Game details

SLUS-00847 Hydro Thunder (USA)

### Description of the issue/bug

Game crashes to desktop just before completing level load after starting a game (either in demo mode or done while attempting actual gameplay).

### Steps to reproduce

- Boot the disc
- Wait until it goes into demo mode and tries to load a level
- Crash to desktop

### Software and hardware information

RetroPie 4.7.1 on Rasperry Pi 4B 4GB

### DuckStation version

gf799f62a taken from https://www.duckstation.org/libretro/duckstation_libretro_linux_aarch64.zip

### DuckStation rendering backend

Software

### DuckStation controller backend, drivers and wrappers

Generic PS3 knockoff mapped as DualShock Analog controller

**Comment by rhester72** [comment]
Got this from the runcommand log:

Panic triggered: 'Failed to evict guest register for new allocation' in function AllocateHostReg (../../src/core/cpu_recompiler_register_cache.cpp:203)
Aborting application.

**Comment by stenzek** [comment]
No crash here on aarch64, and I don't see why it would, aarch64 has plenty of registers and should never run out.

This repo is also not for the libretro core as the template states.

**Comment by rhester72** [comment]
Apologies, I assumed aarch64 because of the CPU, but RetroPie is still running 32-bit armv7.

Will reopen in the correct area.

**Comment by rhester72** [comment]
Actually, I'm a bit confused - this isn't SwanStation, it's the 'official' libretro core taken directly from the duckstation site:

https://www.duckstation.org/libretro/duckstation_libretro_android_armv7.zip

Where should issues against it be opened?

**Comment by stenzek** [comment]
Because that is not part of this repository. I'll check armv7 when I have time.
