### ISSUE TITLE
Red Asphalt is crashing emulator

### ISSUE THREAD

**Issue by cyb3rm4n** [stenzek/duckstation#2794]
### Game details

SLES-00056 Rock & Roll Racing 2 - Red Asphalt (Europe)

### Description of the issue/bug

Game crashes after Interlplay intro movie

### Steps to reproduce

1. Start emulator
2. Choose game from game list OR open directly ISO/BIN+CUE
3. Wait until game loads, watch or skip Interplay movie

### Software and hardware information

Windows 10, AMD Razer 5 3600, 16GB RAM, nVidia 1660

### DuckStation version

0.1-4854-gbee50481 (master), auto-updated from game updater

### DuckStation rendering backend

Direct3D 11

### DuckStation controller backend, drivers and wrappers

XInput, no modified drivers or wrappers

### Additional context

Errors from crash.txt:

ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF7CD7F007E)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF7CD7F007E)
00007FF7CD7F007E (duckstation-qt-x64-ReleaseLTCG): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 126 (Address: 000001F7EA7F0000)
ERROR: SymGetLineFromAddr64, GetLastError: 126 (Address: 000001F7EA7F0000)
ERROR: SymGetModuleInfo64, GetLastError: 1114 (Address: 000001F7EA7F0000)
000001F7EA7F0000 ((module-name not available)): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 126 (Address: 0000000000001A4D)
ERROR: SymGetLineFromAddr64, GetLastError: 126 (Address: 0000000000001A4D)
ERROR: SymGetModuleInfo64, GetLastError: 1114 (Address: 0000000000001A4D)
0000000000001A4D ((module-name not available)): (filename not available): (function-name not available)

**Comment by coornio** [comment]
I tested the NTSC version of the same game from the pile since I had it handy. No crashes at all with it here, it plays perfectly well. It appears that whatever is wrong, it's limited to the PAL version specifically.

**Comment by drachenschanze** [comment]
Happens for me too. With interpreter it just freezes on a black screen. With recompiler the whole emulator crashes.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/30a53fbb3c2a58375bf28e43242d72974740ec84, you'll need to rescan
