### ISSUE TITLE
Transformers Beast Wars Transmetals lockup

### ISSUE THREAD

**Issue by BParks21** [stenzek/duckstation#2795]
### Game details

SLUS-01160 Transformers - Beast Wars Transmetals (USA)

### Description of the issue/bug

After the opening fmv's the game locks up before the main menu. Tested Vulkan and OpenGL. Tested RetroArch and Standalone. 

### Steps to reproduce

Boot the game see if you can make it past the opening fmv's

### Software and hardware information

Windows 10, i7 8086k, Nvidia GTX 1080ti

### DuckStation version

latest dev build and latest retroarch build and preview build

### DuckStation rendering backend

Vulkan

### DuckStation controller backend, drivers and wrappers

xinput

**Comment by PugsyMAME** [comment]
I confirm this is an issue. I traced the code and knocked up a quick cheat that modifies the game code that at least lets you get past the various lockups. It's a bit of an ugly hack...it took 2 minutes so sue me.

Basically enable the cheat and when the screen goes black or the loading bar stops, just hold down R1 for 3 seconds and release and the game should continue loading. I think there are other problems but this at least shows the game is capable of running.

#Workaround for Game Hanging - Press R1 for a few seconds when the screen goes black or the loading bar stops
A701B52E 10001060
D7000000 00000008
A701B52E 10601000

**Comment by drachenschanze** [comment]
Same for me. This game used to work. Must have regressed.

**Comment by BParks21** [comment]
Yeah I think I saw it running in a YouTube video with Duckstation before.

**Comment by stenzek** [comment]
Was fixed a while ago.
