### ISSUE TITLE
Analog sensitivity setting

### ISSUE THREAD

**Issue by Draic0** [stenzek/duckstation#2796]
### Problem statement

In some games standard analog axis sensitivity seems to be not enough. In Darkstone if you tilt your analog stick to a marginal position the character is supposed to run. But it only happens if you tilt it like 100% percent. And it doesn't work at all if you do it in a diagonal direction. Also seems like aiming in FPS games - like Medal of Honor - also suffers from this problem: moving the stick diagonally feels kind of slower than expected.

### Proposed solution

In some other emulators the problem is mitigated by axis sensitivity setting. Could you please make something similar for DuckStation?

### Alternatives considered

I tried this with a number of controllers. DualShock 4 works slightly better but far from being perfect. The easiest way to play Darkstone is to switch to digital mode, but it is inferior.

### Additional context

You start Darkstone, enable analog mode and tilt the stick in various directions. When tilted Up, Down, Left and Right, it causes the character to run - but only in marginal position. But when tilted Up+Right, Up+Left, Down+Right or Down+Left the character only walks. Also try aiming in Medal of Honor or move the cursor in Warcraft: diagonal movement feels slower. Seems that this doesn't depend much on a particular controller as well.

**Comment by stenzek** [comment]
This already exists - "axis scale"

**Comment by Draic0** [comment]
> This already exists - "axis scale"

Yes, sorry. I tried that one but didn't understand how it works. Turned out this setting only works correctly in the PC version. In Android build it breaks axis input if set =<1.00 and value that are >1.00 seem to be all the same. Looks like a bug.
