### ISSUE TITLE
Ninja - Shadow of Darkness (USA) - loading bar is misaligned on opengl and directx

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#280]
![image](https://user-images.githubusercontent.com/50224630/79106181-d4c30000-7d26-11ea-8b30-78f149d49c13.png)
software
![image](https://user-images.githubusercontent.com/50224630/79106187-da204a80-7d26-11ea-811c-b6adbd904480.png)
opengl

**Comment by stenzek** [comment]
Please re-test on latest build, the Castlevania fix may also affect this.

**Comment by kurayami6** [comment]
This is still an issue. The loading bar is broken with OpenGL and D3D11 at all resolutions. The title of this issue should be changed. 

OpenGL and D3D11 at x1. Notice how the bottom corners of the loading bar are missing?

![d3d11](https://user-images.githubusercontent.com/31968468/83747663-4a52a900-a6a4-11ea-99a7-f4978cbbe20b.PNG)

OpenGL and D3D11 at x4

![SLUS-00435_2020-06-04_20-42-06](https://user-images.githubusercontent.com/31968468/83747723-62c2c380-a6a4-11ea-85c7-c2ebed56eded.png)

**Comment by stenzek** [comment]
Probably was fixed by the line changes a while back.
