### ISSUE TITLE
Distorted picture in KoF'98 when selecting Auto (Game Native) display aspect ratio

### ISSUE THREAD

**Issue by dezraj** [stenzek/duckstation#2800]
### Game details

SLPM-86201 King of Fighters '98, The - Dream Match Never Ends (Japan)

### Description of the issue/bug

Hello! I have made some comparisons with different KoF'98 releases and in different emulators and it seems that Duckstation is applying a slightly distorted aspect ratio to the game when using the "Auto (Game Native)" display option. For comparison I have used the sun picture in the introduction movie, which should be perfectly circled, not oval. Take a look:

Final Burn Neo:
![fbn](https://user-images.githubusercontent.com/27839354/148694313-e5c2576b-6a12-4ee5-82b5-8de0715b5a87.jpg)

Raine:
![raine](https://user-images.githubusercontent.com/27839354/148694327-7d57e603-88a9-4fbd-95c7-5538e063bcc0.jpg)

Duckstation (PAR1:1):
![duck](https://user-images.githubusercontent.com/27839354/148694343-ebbc9573-7321-4769-9af0-c37781453e62.jpg)

Duckstation (Auto "Game Native"): 
![duck2](https://user-images.githubusercontent.com/27839354/148694356-599e1aae-e41f-4974-8f88-7acebe95c72c.jpg)

So, considering the comparison above, it seems that the correct aspect ratio for this game should be Pixel Aspect Ratio, so perhaps this format should be the one automatically applied when the user selects "Auto"?

Thank you so much for your work.

### Steps to reproduce

1) Load the game and let the introduction animation play.
2) Pause the emulation when the sun and fire show.
3) Change the display aspect ratio to either PAR1:1 or Auto (Game Native).
4) Unpause the emulation to see the effect.

### Software and hardware information

Windows 10, i5-10400, Intel UHD Graphics 630 (27.20.100.9316)

### DuckStation version

0.1-4788-gae92ce84 (dev) (GitHub Releases)

### DuckStation rendering backend

Direct3D 11

### DuckStation controller backend, drivers and wrappers

SDL, no additional drivers or programs installed.

**Comment by stenzek** [comment]
Likely working as intended, we have to emulate the TV, not necessarily what looks "best".
