### ISSUE TITLE
Tempest X3 - Analog Toggle Causes Menu Confirmation Button Press

### ISSUE THREAD

**Issue by spotanime** [stenzek/duckstation#2803]
### Game details

SLUS-00283 TEMPEST X3

### Description of the issue/bug

Using Xbox button for Analog toggle on Xbox One controller causes Cross input when switching.

### Steps to reproduce

Using Xbox One controller via Xbox Wireless Adapter, XInput.

Assigned Xbox button (Button 5) to Analog on type Analog Controller.

Playing Tempest X3 which only supports digital controllers. Pressed Analog button to go into Digital Controller mode. Works fine. But if I press Analog button again to go back into Analog Controller mode, it also seems to send a Cross button press (via game menu it sends a confirmation that advances the menu). I can consistently recreate this.

I've attached screenshots that show controller configuration and input tests. I've verified that Steam is closed and launching Game Bar through the Xbox Button is turned off, also attached.

I've tested this in another game - SCES-00163 DISNEY'S MICKEY'S WILD ADVENTURE - and the Analog button toggle does **not** send a button confirmation as with Tempest X3. 

(Interestingly, although Mickey's Wild Adventure only supports Digital controller input, D-pad works regardless of whether Analog toggle is set to Digital or Analog).

### Software and hardware information

Windows 10, Ryzen 7 1700X, EVGA GeForce RTX 2070 SUPER XC ULTRA

### DuckStation version

0.1-4866-g51041e47, updated via app automatic updater

### DuckStation rendering backend

Direct3D 11

### DuckStation controller backend, drivers and wrappers

XInput

### Additional context

![Screenshot 2022-01-13 074457](https://user-images.githubusercontent.com/76781697/149337573-f013151c-7fd0-44db-ad53-f3286d1a4a07.png)
![Screenshot 2022-01-13 074832](https://user-images.githubusercontent.com/76781697/149337614-1ca9d80e-8611-4ad9-b9fc-e0e6282b5b10.png)
![Screenshot 2022-01-13 081109](https://user-images.githubusercontent.com/76781697/149337626-321e4835-dc83-4d79-9fb4-3c6d7c6a0ca2.png)
![Screenshot 2022-01-13 081339](https://user-images.githubusercontent.com/76781697/149337644-730d1cf0-91da-4c05-89ad-7024d079c2ef.png)

**Comment by stenzek** [comment]
This seems invalid. It's unpredictable how games that don't support analog mode will react when it's forced.

If it's different to how the console behaves, then maybe this is an issue.

**Comment by ggrtk** [comment]
Also, your Controller Type is set to Analog Joystick, which very few games support. Analog Joystick is different from the typical Analog Controller.
