### ISSUE TITLE
[Linux] Inhibit screensaver not working

### ISSUE THREAD

**Issue by hayguneys** [stenzek/duckstation#2806]
### Game details

SCUS-94163 Final Fantasy VII

### Description of the issue/bug

Hi was playing FF7, on latest arch with Kde desktop, I enabled Inhibit screensaver but that doesn't seem to make the anything actually work. I disabled screensaving on the OS settings but that trick didn't really work since there's other idle settings that kick in if "nothing is happening" which ofcourse means that I'm using a gamepad and not the keyboard and mouse. Am I overlooking something stupid here? Any advice would be super cool, not sure if it's my desktop environment or just that that feature only works on windows.

I don't think the game has anything to do with this issue, btw.

### Steps to reproduce

Just play any game for more than 15 minutes on linux using duckstation with a gamepad

### Software and hardware information

Arch Linux, Rx580, FX-8300

### DuckStation version

0.1-4860-g8e56bb3f (master)

### DuckStation rendering backend

Vulkan

### DuckStation controller backend, drivers and wrappers

SDL

### Additional context

Using x11 not wayland

**Comment by stenzek** [comment]
This has been implemented for some time.
