### ISSUE TITLE
Multiple Button Mappings

### ISSUE THREAD

**Issue by GitHubEnjoyerr** [stenzek/duckstation#2811]
### Multiple Keys for 1 Buton

Me & my dad were playing his old game through _the power of emulation_ BUT he prefers keyboard over controller because he originally played it on PC BUT I just can't play on the keyboard, so whenever it's my turn I have to: Alt-Enter,  Settings, Controller Settings, Load Profile, Dualshock 4... so I guess You could understand my frustration in how I have to do it every SINGLE **TIME** it's the turn of the other person (we were playing Collin McRae Rally2), AND I know that DS4Win exists... Idk why but it just doesn't work... 
All that I'm sain' is **implement mapping multiple keys to the same button or/and add a hotkey to change through input profiles**

### Proposed solution

**Implement mapping multiple keys for the same button + Hotkey for switching between input profiles**

### Alternatives considered

DS4Win, Although it for some reason doesn't run properly

ePSXe ;)

**Comment by stenzek** [comment]
Obviously you didn't read the help text where it says multiple bindings can be set by shift-clicking.
