### ISSUE TITLE
Music problem in FIFA World Cup 98

### ISSUE THREAD

**Issue by ToniBC** [stenzek/duckstation#2813]
### Game details

SLES-01269 Copa del Mundo - Francia '98 (Spain)

### Description of the issue/bug

When the game loads and you see the Press Start screen or you are in the game menu, the music only plays for a few seconds, then stops and restarts constantly. Go into a loop.

The error occurs in all regions of the game.

### Steps to reproduce

Just start the game, enter the menu and wait 10 seconds approx.

### Software and hardware information

Windows 10 x64, Intel I7-7700k, GTX 970 (511.23)

### DuckStation version

DuckStation 0.1-4866

### DuckStation rendering backend

Vulkan

### DuckStation controller backend, drivers and wrappers

nothing relevant

**Comment by BloodRaynare** [comment]
Enable "Force Recompiler ICache" in the per-game settings, but if enhancements is used, set the CPU clock speed slider to 120% as well.

**Comment by ToniBC** [comment]
I'm running it in Interpreter mode, which would have to be the best option, without CPU OC.

The PGXP options shouldn't affect the music, since other emulators with that enabled don't crash.

I'll try it later and I'll let you know if putting iCache or Recompiler mode fixes it.

**Comment by stenzek** [comment]
Invalid because you're using enhancements.
