### ISSUE TITLE
The first line of a character's dialogue will sometimes be very quiet in Tail Concerto (USA)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#282]
Here's the SPU while it's happening. I don't know what any of this means though or if it indicates anything obviously wrong. The earliest I can recall it happening is when you first meet Cyan at the castle.

![Capture](https://user-images.githubusercontent.com/31968468/79118018-0217b880-7dd0-11ea-92a0-70a674b42a04.PNG)

**Comment by stenzek** [comment]
Couldn't reproduce.
