### ISSUE TITLE
Hardware renderer broken on Raspberry Pi 4

### ISSUE THREAD

**Issue by Askmewho** [stenzek/duckstation#283]
HI! I compiled master on aarch64 with latest mesa but it seems it cant create context
or it's failing to compile shaders

ubuntu@ubuntu:~/Desktop/duckstation/build/src/duckstation-qt$ ./duckstation-qt
[    0.5887] I/HostInterface: Program path: "/home/ubuntu/Desktop/duckstation/build/src/duckstation-qt/duckstation-qt" (directory "/home/ubuntu/Desktop/duckstation/build/src/duckstation-qt")
[    0.5888] I/HostInterface: User directory: "/home/ubuntu/.local/share/duckstation"
[    2.6808] I/HostInterface: Boot Filename: <BIOS/Shell>
QEGLPlatformContext: Failed to create context: 3009
QEGLPlatformContext: Failed to create context: 3009
QEGLPlatformContext: Failed to create context: 3009
QEGLPlatformContext: Failed to create context: 3009
QEGLPlatformContext: Failed to create context: 3009
QEGLPlatformContext: Failed to create context: 3009
QEGLPlatformContext: Failed to create context: 3009
QEGLPlatformContext: Failed to create context: 3009
QEGLPlatformContext: Failed to create context: 3009
[    2.7255] I/OpenGLDisplayWidget: Got a OpenGL ES 3.1 context
[    2.7882] I/CubebAudioStream: Minimum latency in frames: 1102
[    2.7981] I/GPU_HW_OpenGL: GL_VERSION: OpenGL ES 3.1 Mesa 20.1.0-devel (git-e78a7a1 2020-04-06 bionic-oibaf-ppa)
[    2.7982] I/GPU_HW_OpenGL: GL_RENDERER: OpenGL ES 3.1 Mesa 20.1.0-devel (git-e78a7a1 2020-04-06 bionic-oibaf-ppa)
[    2.7982] I/GPU_HW_OpenGL: Max texture size: 4096x4096
[    2.7982] I/GPU_HW_OpenGL: Max line width: 32
[    2.7983] I/GPU_HW_OpenGL: Uniform buffer offset alignment: 256
[    2.7983] W(SetCapabilities): GL_EXT_copy_image missing, this may affect performance.
[    2.7983] W(SetCapabilities): Texture buffers are not supported, VRAM writes will be slower.
[    2.7984] E(GLDebugCallback): GL_INVALID_ENUM in glGetIntegerv(pname=GL_MAX_DUAL_SOURCE_DRAW_BUFFERS)
[    2.7984] W(SetCapabilities): Dual-source blending is not supported, this may break some mask effects.
[    2.7985] I/GL::ShaderCache: 0 program binary formats supported by driver
[    2.7985] W(Open): Your GL driver does not support program binaries. Hopefully it has a built-in cache, otherwise startup will be slow due to compiling shaders.
[    2.7986] I/GPU_HW: Resolution Scale: 1 (1024x512), maximum 4
[    2.7986] I/GPU_HW: Dithering: Disabled
[    2.7986] I/GPU_HW: Texture Filtering: Disabled
[    2.7987] I/GPU_HW: Dual-source blending: Not supported
[    2.8203] I/HostInterface: Compiling Shaders...
Segmentation fault

**Comment by stenzek** [comment]
I wasn't aware people were using DuckStation on AArch64! I haven't optimized for it all yet. The JIT did work the last time I tried though.

Will look into it. Probably a result of me dropping the GLES backend, since it was annoying to maintain two GL renderers.

**Comment by Askmewho** [comment]
I would love if you keep gles. Your emulator it's the only than features gles backend and also have a lot more rendering options than psxrearmed doesn't have.. I will promote your emulator on my YouTube channel (a little one, just 2k subs) once I got it working.

**Comment by stenzek** [comment]
The GL renderer supports GLES as well, just not with the GLES2-style path of the now-dropped GLES renderer (uses a modern GLES3 path with buffer streaming).

The GLES backend only existed because the ARM/Mali drivers were stupidly slow and stalled all the time. But I'm hoping I can work around that.

Don't expect miracles with performance yet, as it's not optimized for A64 at all (the JIT generates rather crap code). It can still run games full speed on my ODROID-N2 though, even pinned to the A53 cluster. Haven't tried on my Pi4 yet.

**Comment by Askmewho** [comment]
I know it have a long road, but we need this emulator not bc of speed, just bc of quality. As far as I saw on YouTube your emulator does provide the quality I want. The speed could be improved later. Obviously it haves bug, etc. But it seems quite good so far.. and I've never heard about it.

**Comment by stenzek** [comment]
Well, good news I fixed the crash... bad news the hardware renderers are pretty borked. Seems to be an issue with texture uploads.

![image](https://user-images.githubusercontent.com/11288319/79141287-dced6f00-7dfc-11ea-88b0-4926fa65101f.png)

Looking into it now, but it's probably more than a simple fix and will require more debugging.

**Comment by Askmewho** [comment]
Ok! I am on it! Hope you fix that soon! Thanks for the support

**Comment by Askmewho** [comment]
Tested, yeah, it's glitchy and slow, but hey man.. this looks really promising. Amazing!

**Comment by stenzek** [comment]
As best I can tell, it looks like the colours being returned by the texture sampler are off-by-one, which is causing this graphical corruption. I have a feeling this is a driver bug, perhaps with precision not being respected, because the actual texture data seems fine.

**Comment by stenzek** [comment]
Someone else with the same issue:

https://www.raspberrypi.org/forums/viewtopic.php?f=68&t=266652

I'm not going to spend more time on this for now, seems like it's a driver problem.

**Comment by Askmewho** [comment]
No problem, I update mesa frequently, I will inform you when It get fixed. Thanks.

**Comment by stenzek** [comment]
The Mesa people are usually pretty awesome with bug reports. I might try and write a simple program which shows the bug and log it, otherwise try to fix it myself. Just not for a little while, too frustrated with it at the moment after a few hours debugging :P

**Comment by Askmewho** [comment]
Thanks for the effort. I will follow this emulator development closely. Arm needs something better. Just if you like report the bug, @chema will fix it I guess. But I think than the dynarec it's more important at this point.

**Comment by Askmewho** [comment]
I just recompile it with optimization flags {I forget them last time}  and it's much better [While not amazingly fast} . This will be something else dude!! hey, did you reported the bug on mesa issue tracker???

**Comment by SpaceAgeHero** [comment]
Any news on this? Would love to use DuckStation with Lakka x64 on RPi4.

https://github.com/libretro/Lakka-LibreELEC/issues/1056

**Comment by stenzek** [comment]
Last time I checked the driver bug still wasn't fixed, and the Vulkan driver wasn't anywhere near usable yet. Could have changed since, feel free to try for yourself.

**Comment by stenzek** [comment]
Using the latest Mesa Git and v3dv driver, the Vulkan renderer seems to work fine and does not hit this shader compiler bug.
