### ISSUE TITLE
Title screen of Marby Baby Story (Japan) is broken in all renderers.

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#284]
Duckstation.

![SLPS-01738_2020-04-14_04-21-10](https://user-images.githubusercontent.com/31968468/79148363-b2091800-7e08-11ea-8845-d6a577beeea4.png)

Beetle PSX.

![Marby Baby Story (Japan)-200414-042927](https://user-images.githubusercontent.com/31968468/79148405-c2b98e00-7e08-11ea-9fa0-346927a52290.png)

**Comment by Zet-sensei** [comment]
![Baby](https://user-images.githubusercontent.com/52127625/79805702-ffd0d380-8366-11ea-8037-d0e65610601d.jpg)

Tested on all 3 renderers on 0.1-708.

Should be closed.

**Comment by kurayami6** [comment]
Yeah it's fine now. I'm curious what the problem was and what fixed it.
