### ISSUE TITLE
Artifacting during screen transition in Dragon Valour (USA) using OpenGL and D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#286]
Software.

![Capture](https://user-images.githubusercontent.com/31968468/79199710-b836dd00-7e78-11ea-870b-7e3a98a99075.PNG)

OpenGL and D3D11

![SLUS-01092_2020-04-14_17-46-43](https://user-images.githubusercontent.com/31968468/79199749-c553cc00-7e78-11ea-90d2-b551ff9fa608.png)

**Comment by stenzek** [comment]
Might be related to the FF8 transitions which are sometimes broken. Been meaning to look into that.

**Comment by stenzek** [comment]
Should be fixed in the latest build, probably when the FF7 fixes. Make sure to disable true colour. I think I might actually make that the default since there's some games it is causing to break.

**Comment by stenzek** [comment]
Hm, nevermind, while it's not blocky it still doesn't look correct.

**Comment by stenzek** [comment]
Please re-test on latest build, as best I can tell this appears to be fixed, assuming true colour is off.
