### ISSUE TITLE
Breath of Fire III (Europe), (France) & (Germany) // Error with moving sprites (Software renderer only)

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#287]
![BoF III](https://user-images.githubusercontent.com/52127625/79244438-32666200-7e77-11ea-89b1-1b965a6a6457.jpg)

With the the Software renderer, some moving sprites are sometimes incorrectly rendered with their walking animation (one line is flickering on the right).

Works fine on D3D11 and OGL.

**Comment by kurayami6** [comment]
The dev tried to fix this a little while ago by copypasting code from Beetle PSX. I guess it didn't work.

**Comment by Zet-sensei** [comment]
Panzer Bandit (Japan) is also affected by the same problem.

Tested with https://github.com/stenzek/duckstation/commit/01bc0eb6507bb43dfbe8bd31e23829cb3ea0ac60.

![Panzer](https://user-images.githubusercontent.com/52127625/79279717-ea633180-7eae-11ea-990b-8f058990c901.jpg)

**Comment by Zet-sensei** [comment]
Fixed on 0.1-786.
