### ISSUE TITLE
[Request] Make dithering's resolution scalable

### ISSUE THREAD

**Issue by cascardian** [stenzek/duckstation#29]
I actually like the dithering effect and will nearly always choose to keep it intact when I play, especially in horror games. For that semi-original feeling, I also play most games in, at most, 2x internal resolution. Dithering currently doesn't upscale alongside the internal resolution setting and its blockiness clashes with that a bit.

This is something that's possible on Beetle PSX. for instance. The fix should be to either make it scale alongside the internal resolution setting or even make it independently scalable for maximum control.

**Comment by stenzek** [comment]
Currently the dither pattern should be applied over pixels at the rendered resolution. i.e. at 2x scale, the dithering will be applied every pixel, giving twice the number of "patterns" per 1x resolution.

Are you saying you want a mode where it applies the dither pattern at the 1x resolution, i.e. you get small "blocks" of same-coloured pixels?

Should be pretty straightforward if this is the case.

**Comment by cascardian** [comment]
I think we mean the same thing, yes. Pictures speak a thousand words, though, so allow me to illustrate.

This is in Beetle PSX HW at 2x internal resolution, with _1x (native)_ dithering set:
![sh-2x1x](https://user-images.githubusercontent.com/6861423/74974649-ea523280-5425-11ea-9547-8acbd874709b.jpg)

This is at 2x internal resolution with _internal resolution_ (2x in this case) dithering set:
![sh-2x2x](https://user-images.githubusercontent.com/6861423/74974719-0bb31e80-5426-11ea-8401-70cf7138c90d.jpg)

This is what it looks like in DuckStation at 2x internal resolution, with dithering enabled:
![ds-sh-2x](https://user-images.githubusercontent.com/6861423/74975665-b841d000-5427-11ea-9fd9-589428f8a1bc.jpg)

The size of the dithering pattern in DS remains the same regardless of the internal resolution set. I think it might be nice to have the option of scaling the dithering pattern alongside the internal resolution, maybe even independently (which Beetle PSX currently does not allow) if that is technically feasible.

This is obviously a low-priority request, though. Thank you for your consideration.

**Comment by stenzek** [comment]
Was pretty simple to implement. It can be found under GPU settings as "Scaled Dithering". Please re-open if the option does not fit your requirements.
