### ISSUE TITLE
Valkarie Profile (USA)- massive slowdown in battles

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#291]
As soon as a battle starts, the game grinds to a halt and plays at about 5 fps. Every time the menu to choose your action pops up, the video freezes. The actual game is still running, you can hear the music and the noises from navigating the menu, and as soon as you choose an action, the video resumes running (albeit very badly) until it's time for you to choose another action.

**Comment by stenzek** [comment]
I suspect this is GPU timing related.

**Comment by stenzek** [comment]
Should be fixed in latest master.

**Comment by innerphilim** [comment]
Just tested on the US version of the game, the battle no longer freezes.
