### ISSUE TITLE
Gradius Deluxe Pack (Japan) // Scrambled graphics & game very slow

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#293]
On Gradius II, on the selection screen and further, the game screen is completely scrambled on Software mode.

![GradiusII](https://user-images.githubusercontent.com/52127625/79283331-cce69580-7eb7-11ea-8125-fae353619b01.jpg)

Black screen on D3D11 & OGL renderers.
The game is starting also to be slow extremely slow beginning that point (even on Recompiler Mode).

**Comment by Zet-sensei** [comment]
Just a quick update.
We're definitely moving in the right direction, the game is launchable now.
Sometimes the game slowing down when multiple ennemies are on screen.
Some part of the playfield and some ennemies are correctly rendered now on software.

![Gradius II](https://user-images.githubusercontent.com/52127625/80649156-c89ea880-8a71-11ea-8753-7ae482ebd9a7.jpg)

Sprites are missing on D3D11 and OpenGL renderers.

**Comment by stenzek** [comment]
Should be fixed in https://github.com/stenzek/duckstation/commit/237f469baa3f8d33b5dfedd333f06ba0e53f7f73

**Comment by Zet-sensei** [comment]
Fixed.
Thanks!
