### ISSUE TITLE
Herohero-kun to Ralph no Daibouken (Japan) // No controller response (DualShock only)

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#294]
No button & control responses on the title screen and further when the controller selected is on DualShock Mode.

Works only with the Digital controller option selected inside the emulator panel.

**Comment by Zet-sensei** [comment]
Same issue with Ganbare Goemon - Ooedo Daikaiten (Japan).

**Comment by ggdrt** [comment]
There are a good number of titles that are not compatible with DualShock (or Dual Analog) controllers running in Analog mode, which is what I think DuckStation's Analog Controller pad setting emulates. Original controllers had an "ANALOG" button that let you switch the controller to Digital mode for backwards compatibility with those games.

The instruction manual for Chippoke Ralph no Daibouken says it has analog controller support but only for the rumble feature and not the analog sticks, so it would probably be the same case for the Herohero-kun version. Ganbare Goemon seems to lack analog controller support entirely.

**Comment by stenzek** [comment]
The analog/dualshock controller should start in digital mode and avoid analog mode entirely if the game doesn't support it. Sounds like I have a bug somewhere, need to look into it.

**Comment by stenzek** [comment]
Please re-test on latest build.

**Comment by Zet-sensei** [comment]
Fixed.
