### ISSUE TITLE
Coloured bar at the bottom of the screen in Spyro The Dragon (USA) with all crop modes while paused

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#295]
Crop: None

![SCUS-94228_2020-04-15_20-21-30](https://user-images.githubusercontent.com/31968468/79326910-f60a3300-7f56-11ea-91d2-bb1d9074f685.png)

Crop: Only overscan area

![SCUS-94228_2020-04-15_20-18-50](https://user-images.githubusercontent.com/31968468/79326957-05897c00-7f57-11ea-9a1c-ac663ed8cf5d.png)

Crop: All borders 

![SCUS-94228_2020-04-15_20-19-42](https://user-images.githubusercontent.com/31968468/79326989-10dca780-7f57-11ea-9de5-5f07a3e3658e.png)

**Comment by stenzek** [comment]
I'm not seeing this at all.

**Comment by kurayami6** [comment]
Just checked it again. It doesn't happen in software. Only OpenGL and D3D11.

**Comment by stenzek** [comment]
Try disabling display linear filtering.

**Comment by stenzek** [comment]
GPU settings -> screen display -> linear upscaling

**Comment by kurayami6** [comment]
Tried it. Didn't make a difference.

**Comment by stenzek** [comment]
Is this still happening on the latest build? I can't seem to reproduce it, so there might be more specific conditions under which it happens.

**Comment by kurayami6** [comment]
Yes it still happens. It changes colour depending what level you're in.

![Capture](https://user-images.githubusercontent.com/31968468/80401273-6756c800-88ff-11ea-9c86-5784831eb2a4.PNG)

**Comment by kurayami6** [comment]
Fixed.
