### ISSUE TITLE
Sparkle effect in Spyro The Dragon (USA) is incorrect at higher resolution with OpenGL

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#297]
When Sparx flies around or when you blow up a treasure chest with a rocket there's a sparkle effect. It looks fine at native resolution in all renderers and is also fine when Upscaled in D3D11. It's only broken when upscaled in OpenGL.

OpenGL at x4

![SCUS-94228_2020-04-16_04-08-17](https://user-images.githubusercontent.com/31968468/79376079-f88f7b80-7f9c-11ea-9889-dff7b63faa01.png)

D3D11 at x4

![SCUS-94228_2020-04-16_04-07-21](https://user-images.githubusercontent.com/31968468/79376137-1066ff80-7f9d-11ea-9448-058744d9160a.png)

**Comment by stenzek** [comment]
Might want to check this one on the latest build too.

**Comment by kurayami6** [comment]
Fixed.
