### ISSUE TITLE
Lines under characters names are incorrect in Spyro 2 when upscaled in OpenGL.

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#299]
OpenGL at x4.

![SCUS-94425_2020-04-16_17-04-44](https://user-images.githubusercontent.com/31968468/79425262-c6b1ff80-8004-11ea-92aa-9a1cb36ad61d.png)

D3D11 at x4

![SCUS-94425_2020-04-16_17-05-55](https://user-images.githubusercontent.com/31968468/79425292-d2052b00-8004-11ea-9ad9-f7404da9a288.png)

**Comment by kurayami6** [comment]
Pause menu is also wrong.

![SCUS-94425_2020-04-16_18-49-20](https://user-images.githubusercontent.com/31968468/79435532-244d4880-8013-11ea-9005-33660d5d778c.png)

**Comment by stenzek** [comment]
I wasn't able to reproduce this, it might be GPU-specific.

But try the latest build, I replaced the line width with a geometry shader, so it should be the same as D3D11 now.

**Comment by kurayami6** [comment]
Fixed.
