### ISSUE TITLE
[Question] Minimum OpenGL requirements?

### ISSUE THREAD

**Issue by DarkSwan86** [stenzek/duckstation#3]
Hi stenzek!

Can you add to the readme of the project the minimum requirement version of OpenGL for your emulator?

I'm eager to try it on Linux when the first version will come out but i can't tell if my quite old laptop will run it :) . Thanks!

**Comment by stenzek** [comment]
At the moment - OpenGL 3.3 or OpenGL ES 3.0. But only due to a hardcoded line in the shader generator: <https://github.com/stenzek/duckstation/blob/master/src/core/gpu_hw_shadergen.cpp#L21>

If I make that dynamic, it'll run on OpenGL 3.0 and upwards.

**Comment by DarkSwan86** [comment]
Thanks! I have an Intel Sandybridge HD3000 (max OpenGL 3.3 with Mesa) so in theory should work! Just curious, when you say "OpenGL 3.0 and upwards" you mean maybe even OpenGL 4.x or only between 3.0 and 3.3? Thanks again!

**Comment by stenzek** [comment]
I'm not using any compatibility context functionality, so 3.0+ including 4.x.
