### ISSUE TITLE
 GAME wipeout 2097 EUR

### ISSUE THREAD

**Issue by ghost911-hub** [stenzek/duckstation#303]
Hello the game hangs on the second load at the start of the game

**Comment by kurayami6** [comment]
Works fine for me. Does it crash every time?

![SLES-00327_2020-04-18_02-04-15](https://user-images.githubusercontent.com/31968468/79589588-036f1b00-8119-11ea-9f64-87e182d0bfe1.png)

**Comment by stenzek** [comment]
Might not affect this game, but please try with both fast boot and TTY output turned off if you have them enabled. Sometimes they can cause games to break.

**Comment by ghost911-hub** [comment]
![blocked](https://user-images.githubusercontent.com/63866260/79598627-980b5600-80e4-11ea-9077-1242dc830524.PNG)
![enabled](https://user-images.githubusercontent.com/63866260/79598648-9e99cd80-80e4-11ea-9b4f-30a829e524a1.PNG)
Hello, the games hang despite the options

**Comment by ghost911-hub** [comment]
it doesn't work in the European version
this does not work in the european version it hangs when loading at the start of the game

**Comment by Zet-sensei** [comment]
stenzek said to turn OFF those options and you tested it with all the options ON.

Try again after UNCHECKING : 
- Enable TTY Output
- Fast Boot.

**Comment by kurayami6** [comment]
I've tried it in the latest versions of Duckstation, Beetle PSX and ePSXe and it works fine in all of them. I'm not allowed to tell you where to get games but you're probably using a bad dump. What does the log say when it hangs?

**Comment by ghost911-hub** [comment]
> stenzek said to turn OFF those options and you tested it with all the options ON.
> 
> Try again after UNCHECKING :
> 
>     * Enable TTY Output
> 
>     * Fast Boot.

Not Working
