### ISSUE TITLE
Fighting Force 1 black screen after character select

### ISSUE THREAD

**Issue by robertobernardo80** [stenzek/duckstation#304]
Tested with NTSC US and PAL (en_fr_de) versions.

**Comment by kurayami6** [comment]
Works fine for me. You'll have to provide more information.

![SLUS-00433_2020-04-18_18-17-27](https://user-images.githubusercontent.com/31968468/79632175-f990fa80-81a0-11ea-8107-1475c9947cf1.png)

**Comment by stenzek** [comment]
Make sure the usual things are disabled - fast boot/ TTY output

**Comment by robertobernardo80** [comment]
fast boot and TTY output are disable.

After characters select :
![Capture1](https://user-images.githubusercontent.com/63899433/79638035-be340300-8183-11ea-8469-cc9ff18dcf7a.JPG)

here are my settings
![Capture2](https://user-images.githubusercontent.com/63899433/79638040-c68c3e00-8183-11ea-9183-edc5ddf5040a.JPG)
![Capture3](https://user-images.githubusercontent.com/63899433/79638042-ca1fc500-8183-11ea-9987-4575f805c568.JPG)

**Comment by kurayami6** [comment]
Probably a bad dump. I think this emulator needs to show a warning message if someone plays a game that isn't verified by Redump like Dolphin does. It could say something like "This game isn't Redump verified. Please don't report any issues you encounter while playing"

**Comment by stenzek** [comment]
@kurayami6 easier said than done. Lots of different formats for images, and redump only provides hashes for bin/cue. Fortunately the datfile has it split per track, so in theory we could read/hash whatever image the user provides and hash one track at a time, and it should match. Will look into it some time..

**Comment by robertobernardo80** [comment]
I had two bad dumps (ntsc and pal), with another it works perfectly.
Thank you for your help.

![Capture4](https://user-images.githubusercontent.com/63899433/79642849-209afc80-81a0-11ea-9d18-c1e3042f6591.JPG)
