### ISSUE TITLE
Audio issues in Spyro: Year of the Dragon (USA) (v1.1)  

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#305]
The opening cutscene is silent. This is probably caused by the same thing that causes some of the cutscenes in Spyro 2 to be silent.

![Capture](https://user-images.githubusercontent.com/31968468/79636044-551ab280-81b8-11ea-9883-f0889e7a8998.PNG)

The rocket explosion sound effect is broken. Go to Enchanted Towers, light the rocket to blow up the statue and the sound of the explosion is completely distorted.

![SCUS-94467_2020-04-18_20-48-52](https://user-images.githubusercontent.com/31968468/79635908-2cde8400-81b7-11ea-8423-9e70a69752cf.png)

**Comment by kurayami6** [comment]
Opening cutscene audio is fixed.

**Comment by stenzek** [comment]
Could be worth re-checking this with the recent SPU changes.

**Comment by stenzek** [comment]
I'm going to assume this is fixed. If it is not, please let me know and I will re-open.
