### ISSUE TITLE
Failing to load BIOS crashes the emulator 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#306]
![Capture](https://user-images.githubusercontent.com/31968468/79643331-d9375f00-81e5-11ea-8b49-73e76b2e3355.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/79643335-db99b900-81e5-11ea-872c-fe7a680dc062.PNG)

**Comment by stenzek** [comment]
Ugh, I thought I fixed this. Will look into it soon.

**Comment by stenzek** [comment]
Fixed by https://github.com/stenzek/duckstation/commit/d5a5432a8ba450169039d1b66f35b1461f608622
