### ISSUE TITLE
Glitchy line in the background of stages in Dead Or Alive (USA) with all renderers 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#308]
OpenGL and D3D11

![SLUS-00606_2020-04-20_19-44-03](https://user-images.githubusercontent.com/31968468/79738789-950ca180-8340-11ea-9d4c-16bf250338e1.png)

Software

![SLUS-00606_2020-04-20_19-46-03](https://user-images.githubusercontent.com/31968468/79738818-a2299080-8340-11ea-9f71-0e038682f023.png)

**Comment by stenzek** [comment]
Seems to be an interlacing-related issue - the height to clear is off-by-one.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/b25ed6c151e65d630e2c2a1ce449a8bdbd7109a8
