### ISSUE TITLE
Broken graphics in Slam 'n Jam '96 featuring Magic & Kareem (USA) with OpenGL and D3D11

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#309]
OpenGL and D3D11 at x1

![Capture](https://user-images.githubusercontent.com/31968468/79746538-7e207c00-834d-11ea-900e-b69b3b2b64e5.PNG)

OpenGL and D3D11 at x4

![SLPS-00426_2020-04-20_21-15-26](https://user-images.githubusercontent.com/31968468/79746568-8aa4d480-834d-11ea-9e00-f8f0d7de951f.png)

Software

![Capture2](https://user-images.githubusercontent.com/31968468/79746585-92fd0f80-834d-11ea-825c-2c142fd519ed.PNG)

**Comment by stenzek** [comment]
Please re-test on latest build. This probably will still break at >1x resolution scale if it's similar to Dark Forces/Doom/etc, but 1x should be fixed.

**Comment by kurayami6** [comment]
It's now significantly worse. 

Using OpenGL and D3D11 at x1 there's now garbage under the text in the menus and the black square covers the entire court.

![Capture](https://user-images.githubusercontent.com/31968468/79868098-c2ca1700-8422-11ea-96c2-0067b3d5bba0.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/79868141-d4132380-8422-11ea-91e4-7e8175166056.PNG)

Using OpenGL and D3D11 at x4 there is now no text in the menus and the garbage graphics on the court are the same.

![SLUS-00022_2020-04-21_22-47-07](https://user-images.githubusercontent.com/31968468/79868219-f1e08880-8422-11ea-9fe2-98fdcf25fb65.png)

![SLUS-00022_2020-04-21_22-47-33](https://user-images.githubusercontent.com/31968468/79868232-f5740f80-8422-11ea-992f-a7d1de195f01.png)

**Comment by kurayami6** [comment]
Glitches as of the latest version.

Garbage on the loading screen at x1

![Capture](https://user-images.githubusercontent.com/31968468/85938952-05ddc480-b955-11ea-9c4a-2cbf8d5c6f27.PNG)

Garbage on the court at x1

![Capture2](https://user-images.githubusercontent.com/31968468/85938958-0d9d6900-b955-11ea-855a-3a7f2ba82234.PNG)

Garbage on the court at x4

![SLUS-00022_2020-06-28_15-32-50](https://user-images.githubusercontent.com/31968468/85938970-1c841b80-b955-11ea-8864-c37e0adf2b69.png)

There's also a low audio buzzing during the opening logos and FMV that didn't used to happen.

[SLUS-00022_2020-06-28_15-30-41.zip](https://github.com/stenzek/duckstation/files/4841743/SLUS-00022_2020-06-28_15-30-41.zip)

**Comment by stenzek** [comment]
Seems fine on latest version. Obviously doesn't work with upscaling - will add gameini.
