### ISSUE TITLE
Parasite Eve 2: frezzes after select a weapon [SLUS-00662]

### ISSUE THREAD

**Issue by SmilingVLADISLAV** [stenzek/duckstation#310]

**Comment by kurayami6** [comment]
Do you mean right at the beginning when you do target practice? It doesn't, I just tried it. 

![SLUS-01042_2020-04-20_22-59-27](https://user-images.githubusercontent.com/31968468/79754352-c1351c00-835a-11ea-803e-1387f64e9574.png)

**Comment by SmilingVLADISLAV** [comment]
I used save from EPSXE. If you go into the inventory and select a weapon and then a bullet to it, the game will freeze.

**Comment by kurayami6** [comment]
Did that and it still didn't freeze. Try starting a new game and see if it still happens. Using saves from a different emulator probably causes problems.

![SLUS-01042_2020-04-20_23-19-39](https://user-images.githubusercontent.com/31968468/79756268-bdef5f80-835d-11ea-85a4-c2eb7c157c48.png)

**Comment by SmilingVLADISLAV** [comment]
Try my save file. https://yadi.sk/d/X-GM5usiZ-lD7g

**Comment by SmilingVLADISLAV** [comment]
Checked at the beginning, it works. I'm already on the second disk :( Is it possible to safely transfer the save?

**Comment by kurayami6** [comment]
I don't think swapping saves works in this emulator so I can't check, sorry. If starting a new game without the EPSXE save file fixed the freeze then that must have been the issue and this can be closed.

**Comment by SmilingVLADISLAV** [comment]
The first mission, a skyscraper: the same problem, freezes. On the training mission, everything is in order. I'll try to download another version.

**Comment by stenzek** [comment]
Please try switching to the interpreter (not cached interpreter) mode and see if it makes any difference.

In theory the memory cards should be compatible, but if they weren't I wouldn't be surprised if the game just crashed.

**Comment by SmilingVLADISLAV** [comment]
That build work for me) https://www.emucr.com/2020/04/duckstation-git-20200414.html

**Comment by innerphilim** [comment]
If you really want to test use PSX Memory Card Manager and MemcardREX tools to extract your save and import it to Duckstation Memory Card file.

**Comment by innerphilim** [comment]
I tested the game for hours with my Memory Card file taken from ePSXe in the latest builds and didn't find any freeze.

Also the serial number SLUS-00662 is for the first Parasite Eve game.

**Comment by SmilingVLADISLAV** [comment]
> I tested the game for hours with my Memory Card file taken from ePSXe in the latest builds and didn't find any freeze.
> 
> Also the serial number SLUS-00662 is for the first Parasite Eve game.

Emulator supports .mcr. There was an unsuccessful build, it works well on others.

**Comment by innerphilim** [comment]
So this can be closed I think.

**Comment by kurayami6** [comment]
This is obviously nonsense and going nowhere. Close it.
