### ISSUE TITLE
Battle transition is possibly broken in Masumon Kids - The Another World of the Master of Monsters (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#312]
I can't find any footage of it online but I doubt it's supposed to look like this. If anyone has the game and can check it on real hardware that would be great. 

![SLPS-01426_2020-04-20_23-47-25](https://user-images.githubusercontent.com/31968468/79760863-03169000-8364-11ea-8ec4-9f90eb08819e.png)

**Comment by stenzek** [comment]
That's definitely broken :D Did you try the software renderer?

**Comment by kurayami6** [comment]
Software looks a bit different.

![SLPS-01426_2020-04-21_01-51-23](https://user-images.githubusercontent.com/31968468/79771861-bab29e80-8372-11ea-91fa-6fc6a88aea7a.png)

**Comment by stenzek** [comment]
The blow-out in brightness was probably improved by the recent colour/dithering changes. Otherwise, based on what I can see online, this might be working as intended: https://youtu.be/YDDCA6wyBm0?t=214 But, this might be emu footage, who knows...
