### ISSUE TITLE
Ridge Racer Type 4 (USA) | Lines appearing in race

### ISSUE THREAD

**Issue by jpchow26** [stenzek/duckstation#313]
Crazy lines appearing when using D3D11 or OpenGL. Not in software. Using local build on checkout aaf9dca:

D3D11:
![image](https://user-images.githubusercontent.com/10886704/79776342-9bc8f380-8303-11ea-9bce-23b1af2436a5.png)

opengl:
![image](https://user-images.githubusercontent.com/10886704/79776390-adaa9680-8303-11ea-8ec3-99e0e4ba2107.png)

Software:
![image](https://user-images.githubusercontent.com/10886704/79776430-b9965880-8303-11ea-8e35-480d9735559a.png)

**Comment by stenzek** [comment]
Should be fixed in https://github.com/stenzek/duckstation/commit/1ee418aebf0902a8c9a10c0e7e544fe0f535f7e5

**Comment by jpchow26** [comment]
updating to latest works
