### ISSUE TITLE
Regression in T Kara Hajimaru Monogatari (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#315]
Settings are identical in both versions. 

Duckstation version 0.1-701

![SLPS-01350_2020-04-21_23-58-48](https://user-images.githubusercontent.com/31968468/79875077-784d9800-842c-11ea-812a-be079ecc0fad.png)

Duckstation 0.1-711

![SLPS-01350_2020-04-21_23-49-47](https://user-images.githubusercontent.com/31968468/79875181-9ddaa180-842c-11ea-9cd0-f1725c5e88c6.png)

**Comment by stenzek** [comment]
Is there an offset when compared with the software renderer? (use END to switch between the two)

**Comment by kurayami6** [comment]
Tested it a bit more. It happens in 0.1-711 when using higher resolution with OpenGL and D3D11. Software is fine. Doesn't happen in 0.1-701 with any settings.

**Comment by stenzek** [comment]
It's might be the hack I ported from Beetle causing the issue - I left it enabled for higher resolutions because the vertex offset alone still had broken flipped sprites in 2D games.

**Comment by kurayami6** [comment]
I don't mean to be presumptuous or tell you how to do your job but I don't think Beetle PSX is an emulator you should be copying from. It has a LOT of issues. As a matter of fact I started using this emulator because I was sick of Beetle.

**Comment by stenzek** [comment]
Sure. Which is why I eventually found another way of fixing the sprite issue, it just doesn't work with resolution scaling. Might still find a way around that too, but for now it's easier to just play 2D games at 1x scale. It's not like they benefit from upscaling anyway.

**Comment by kurayami6** [comment]
Fixes as of the latest version.
