### ISSUE TITLE
Graphical glitch during the opening cutscene of Combat Choro Q (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#318]
Happens with all renderers, all resolutions and all crop modes.

![SLPS-01904_2020-04-22_05-56-55](https://user-images.githubusercontent.com/31968468/79914427-9fc25600-8468-11ea-8d2b-8644a79e28ee.png)

**Comment by stenzek** [comment]
May be fixed by https://github.com/stenzek/duckstation/commit/0ef0c36704c2ba79cd9c80e649c953c3fc0bfb5e, although I'm doubtful as it looks like more than a single column of pixels.

**Comment by kurayami6** [comment]
Happens on real hardware. My mistake.
