### ISSUE TITLE
Pressing the esc key doesn't exit out of fullscreen mode

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#32]
Only way I've found to exit is to Control-Alt-Delete and manually shut down the emulator.

**Comment by stenzek** [comment]
Binding a key combination to toggle full screen will allow you to exit. But yeah, adding a stop emulation hotkey bound to escape by default is probably a good idea.

**Comment by shikulja** [comment]
> Binding a key combination to toggle full screen will allow you to exit. But yeah, adding a stop emulation hotkey bound to escape by default is probably a good idea.

and add standart alt+enter to fullscreen
