### ISSUE TITLE
Graphical glitch during screen transition in Perfect Performer - The Yellow Monkey (Japan) when upscaling OpenGL and D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#321]
OpenGL and D3D11 at x4. Looks fine at x1

![SLPS-02135_2020-04-22_08-30-44](https://user-images.githubusercontent.com/31968468/79920820-5a0b8a80-8474-11ea-8205-4998cda90438.png)

Software

![Capture](https://user-images.githubusercontent.com/31968468/79920862-71e30e80-8474-11ea-8152-c2a03ca55474.PNG)

**Comment by stenzek** [comment]
Merged with https://github.com/stenzek/duckstation/issues/427
