### ISSUE TITLE
Graphical garbage on the level select screen in Disney's Atlantis 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#322]
See that purple stuff around the letters? Happens with all renderers. 

![SCUS-94636_2020-04-22_23-45-02](https://user-images.githubusercontent.com/31968468/79989865-b235a180-84f3-11ea-9225-233181c60a1b.png)

**Comment by stenzek** [comment]
Did the fix for Crash Bandicoot change anything here?

**Comment by kurayami6** [comment]
No

**Comment by stenzek** [comment]
Looks like it might palette issue. Have you verified this does not occur on console?

**Comment by kurayami6** [comment]
Yeah I just checked and this happens on console. I know it's a big ask but could you possibly take a look at the game's code and see why this happens? Because it seems ridiculous that the devs didn't fix it.
