### ISSUE TITLE
Broken graphics on scoreboard in Disney's Atlantis. 

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#323]
Happens with all renderers. 

![SCUS-94636_2020-04-22_23-19-22](https://user-images.githubusercontent.com/31968468/79994250-0e4ef480-84f9-11ea-9056-9ce2eb4c0019.png)

**Comment by stenzek** [comment]
Looks like an upscaled screenshot. Is the issue also present at 1x scale?

**Comment by kurayami6** [comment]
No. It's only broken when upscaling OpenGL and D3D11.

**Comment by stenzek** [comment]
Upscaling issue -> https://github.com/stenzek/duckstation/issues/427
