### ISSUE TITLE
Suzuki Bakuhatsu (Japan) freezes the emulator 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#324]
It might be causes by looking at the bomb instructions with the magnifying glass. 

![Capture2](https://user-images.githubusercontent.com/31968468/80028874-37877900-8529-11ea-8050-38e15bc70b96.PNG)

**Comment by stenzek** [comment]
Is this just when the debug GPU device is enabled + DX11? Until the latest build that will crash if you aren't running the emulator under a debugger.

Does it also happen on the software renderer?

**Comment by stenzek** [comment]
Closing as this does not seem to be reproducible. If it is still happening, please post which settings you are using which causes it, and I will investigate.
