### ISSUE TITLE
Can't save state with a hotkey in Nekketsu Oyako (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#325]
Save stating manually works fine but If I try and do it with a key I get this error message. 

![Capture](https://user-images.githubusercontent.com/31968468/80031064-7ff46600-852c-11ea-8a42-6a0e5c7d4413.PNG)

**Comment by stenzek** [comment]
Working as intended if the game does not have a valid code in the executable. Some games are like this. It should show up blank in the list too.

**Comment by kurayami6** [comment]
You intend it to not work? I don't understand.

**Comment by stenzek** [comment]
I mean you're not going to to be able to create per game save states when there is no game code.

You can still use global states though.
