### ISSUE TITLE
Explosion sound effect is broken in  Simple 1500 Series Vol. 24 - The Gun Shooting (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#326]
Just blow up this thing at the start of the game and you'll hear a horrible crackling sound.

![Capture](https://user-images.githubusercontent.com/31968468/80059567-aa1b4780-856f-11ea-9cae-20d8eefc1cd1.PNG)

**Comment by stenzek** [comment]
Might be worth re-checking after the recent SPU clipping changes.

**Comment by kurayami6** [comment]
Fixed but there must have been a regression recently. This is the third game in a row I've tried with glitches that didn't used to be there in OpenGL and D3D11. 

![SLPS-02474_2020-05-13_01-39-04](https://user-images.githubusercontent.com/31968468/81714698-aa499b80-94ba-11ea-824b-8c2540ab36b5.png)

**Comment by kurayami6** [comment]
It doesn't happen in this one so It must have been caused by the fix for Bedlam and Rise 2.

![Capture](https://user-images.githubusercontent.com/31968468/81717976-8ee08f80-94be-11ea-8ce9-cac0795c204f.PNG)

**Comment by stenzek** [comment]
Did you turn on Bilinear Texture Filtering by any chance? Those look like artifacts from that option.
