### ISSUE TITLE
Upscaling doesn't work in OpenGL as of the latest version

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#328]
D3D11 still works fine. 

![1587660798160](https://user-images.githubusercontent.com/31968468/80129924-25fea980-85db-11ea-867d-f6a0dbcbaa64.png)

**Comment by stenzek** [comment]
This is a good example of where you should look at/attach the log - upscaling isn't broken, the whole GL renderer was broken and it was falling back to software on NVIDIA. The log would tell you both the shader error as well as that it was using the software renderer.

Fixed, regardless.
