### ISSUE TITLE
Graphical glitches on the title screen of SuperLite 1500 Series - Memories Off (Japan) with OpenGL and D3D11

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#329]
OpenGL and D3D11 at x1

![Capture2](https://user-images.githubusercontent.com/31968468/80151674-ca91e300-85fd-11ea-9389-f30f9740359f.PNG)

OpenGL and D3D11 at x4

![SLPM-86583_2020-04-24_07-28-24](https://user-images.githubusercontent.com/31968468/80151714-d67da500-85fd-11ea-96f6-688416b94ab1.png)

Software

![Capture](https://user-images.githubusercontent.com/31968468/80151737-e1d0d080-85fd-11ea-97d4-514b99573d68.PNG)

**Comment by kurayami6** [comment]
Still an issue as of the latest version.

**Comment by stenzek** [comment]
Not present on latest version.
