### ISSUE TITLE
Video output not taking GP1(07h) setting into account

### ISSUE THREAD

**Issue by ggdrt** [stenzek/duckstation#33]
Thought this was worth mentioning since this was also an issue in Beetle PSX hardware renderers that we fixed a while back.

Currently, DuckStation doesn't seem to emulate video output properly for titles that use native framebuffers shorter in height than the visible NTSC scanline range. 

![](https://user-images.githubusercontent.com/45282415/74616457-b05af680-50dc-11ea-8478-f9fbce5baa6e.PNG)

For example, NTSC Wild Arms uses a 232 height framebuffer during gameplay and calls GP1(07h) with Y1=16 and Y2=248, relying on the GPU+DAC to fill an extra 8 blank lines for a full 240 visible lines (I think the signal generated by hardware is actually 243 visible lines, but most emulators stop at 240). The 232 height framebuffer already includes 8 lines of black pixels on the top, but relies on the GPU+DAC to fill in the extra 8 bars at the bottom to complete the letterboxing.

Another game we tested on was Threads of Fate at the title screen (Y1=30, Y2=238) that has 14 blank scanlines filled in by the GPU+DAC at the top and another 18 blank scanlines filled in at the bottom.

Chrono Cross also changes the GP1(07h) setting between frames to create a screen shake effect like so: https://www.youtube.com/watch?v=a-ovOoISyLA

I haven't checked yet if this is an issue with PAL games but hopefully this is enough information to work off of.

**Comment by stenzek** [comment]
The current behavior is to crop to the active display area. But yeah, sounds like offering an option to display the full area will be worthwhile.

Will require a bit of refactoring, but shouldn't be too significant.

**Comment by ggdrt** [comment]
Along this same train of thought, an option to hide the vertical overscan region or otherwise set the range of visible scanlines would be nice to have for games that relied on television borders to hide miscellaneous textures/garbage along the edges of the outputted framebuffer.

**Comment by stenzek** [comment]
Latest master adds a "crop mode" setting which can be switched between "none", "overscan" and "all borders". I haven't tested with this particular game, but the none/overscan settings should still allow these sorts of effects (at least it works with screen centering in a few games).

Not closing yet because I'm not sure on the number of displayed lines before vblank that the GPU outputs, or if the numbers are correct for PAL modes.

**Comment by stenzek** [comment]
Properly fixed with upcoming overscan changes.

**Comment by ggdrt** [comment]
I think the current values are off right now, the `Crop: None` setting is showing extra non-active scanlines that are part of the vertical blanking interval.

Here's a patch with updated line values. It fixes `Crop: None` but causes `Crop: Only Overscan Area` to bug out, probably due to some other calculations further down in `GPU::UpdateCRTCDisplayParameters()`.

[0001-GPU-Fix-vertical-display-line-values.txt](https://github.com/stenzek/duckstation/files/4406544/0001-GPU-Fix-vertical-display-line-values.txt)

**Comment by kurayami6** [comment]
@ggdrt Is there not a way to fix it correctly and without resorting to hacks and patches?

**Comment by stenzek** [comment]
@ggdrt ah thanks, I wasn't sure on the ticks/lines to use, and just picked what seemed reasonable. Will investigate why the overscan path is breaking.

@kurayami6 it's not a hack, the values I was using in my calculations were incorrect.

**Comment by stenzek** [comment]
@ggdrt I feel like using static values for the start/end may be insufficient for modelling the CRTC. Some games still have borders on one side only with the changed values.

Do you know if the hsync signal always occurs on the same tick, or whether it is relative to the display end tick? If it's relative, that would explain what I'm seeing and using a "maximum displayed" ticks value instead, cropping that, and splitting the borders evenly might work.

**Comment by ggdrt** [comment]
The horizontal blanking interval should always start on the same GPU cycle/tick for each scanline from what I'm aware. We use 3288 for the start of hblank in Beetle since 488 is the first tick for the active video portion of the scanline, and an active video width of (3288 - 488) = 2800 ticks makes for clean division with all the possible pixel clock dividers.

I think if you wanted to be more accurate to NTSC specs the active video portion is ~52.6 us meaning that hblank starts on around tick number 3312, but it's been a long time since I've done a waveform measurement on the console video output so I'm not sure how close the actual generated signal is to 52.6 us.

GP1(06h) values of 608 to 3168 are usually considered the standard for well-centered NTSC games and using an active video portion of 488 to 3288 gives us a nice 120 ticks on each side so it works out decently. Unfortunately some games don't seem to use 608 to 3168 and are permanently horizontally shifted by a couple of ticks. 

We gave an option in Beetle for users to shift the image by a couple of ticks for these kinds of games, though this doesn't really help for weirdly coded games like Breath of Fire IV where FMVs are shifted to the left while gameplay is shifted to the right. I didn't want to do add an automatic centering method since I wouldn't be surprised if some games used GP1(06h) for effects like how Chrono Cross changes GP1(07h) for screen shakes.

As an aside I think GP1(06h) documentation is another area where the Nocash specs are bit questionable... I think it should say `counted in GPU clock cycles relative to the leading edge of the horizontal sync pulse` instead.

**Comment by stenzek** [comment]
I see, thank you for the detailed write up, much appreciated. I was going to write some hardware tests but that saves me the time!

So if I understand it correctly, then hsync/active video are fixed and the X only controls when the DAC starts reading VRAM?

Yeah, automatically centering the image would also break games with position control/screen centering options as well. I guess it could be yet another crop mode, or could do like you suggested and just have a fudge factor per game. As annoying as "game inis" are here I'm not sure there's much else we can do.. at least it's less of a "hack" and more of an "enhancement".

**Comment by ggdrt** [comment]
> So if I understand it correctly, then hsync/active video are fixed and the X only controls when the DAC starts reading VRAM?

Yep that's correct.
