### ISSUE TITLE
SuperLite 1500 Series - Wizard's Harmony R (Japan) hangs on title screen

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#330]
Press start and the game will fade to black and hang. Turning on "Show VRAM" shows that it's just frozen on the title screen.

![SLPM-87190_2020-04-24_07-37-42](https://user-images.githubusercontent.com/31968468/80152350-d7630680-85fe-11ea-8f54-438bc2a5978f.png)

![SLPM-87190_2020-04-24_07-37-52](https://user-images.githubusercontent.com/31968468/80152359-daf68d80-85fe-11ea-8b91-6881ea593dc7.png)

![SLPM-87190_2020-04-24_07-38-21](https://user-images.githubusercontent.com/31968468/80152371-dfbb4180-85fe-11ea-9fb0-3b1ef3f36652.png)

**Comment by Zet-sensei** [comment]
![Wizard](https://user-images.githubusercontent.com/52127625/80292997-c4b21400-875b-11ea-83bf-150ad309ca63.jpg)

Goes in-game on 0.1-742.

Should be closed.

**Comment by kurayami6** [comment]
So it does. I wonder what fixed it. 

![SLPM-87190_2020-04-26_09-58-08](https://user-images.githubusercontent.com/31968468/80293664-8260f500-87a4-11ea-924d-efbc9a5ee1bd.png)
