### ISSUE TITLE
Street Fighter Alpha - Warriors' Dreams (Europe) // Missing layer of background.

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#331]
On all renderers. 

The last layer of background is missing.
Tested on 0.1-723.

![Sans titre](https://user-images.githubusercontent.com/52127625/80155655-7289bb00-85c2-11ea-968b-6f79d1be1d9c.jpg)

The layer is rendered correctly only if our character is on the full right side of the screen.

![Street](https://user-images.githubusercontent.com/52127625/80156046-402c8d80-85c3-11ea-8d1b-6827635de422.jpg)

**Comment by Zet-sensei** [comment]
Only that specific stage is affected on the game.

Tested through all the game and finished it.

**Comment by stenzek** [comment]
Please re-test on the latest build when you get a chance, the fix for Darkstalkers may be relevant.

**Comment by Zet-sensei** [comment]
Fixed.
