### ISSUE TITLE
Controller isn't detected in Analog Controller Service Disc (Revised) (Europe)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#332]
![2020-04-24_07-50-25](https://user-images.githubusercontent.com/31968468/80158608-4135dd00-860c-11ea-8adb-6a5bae745c9f.png)

Works fine in Beetle PSX.

![Analog Controller Service Disc (Revised) (Europe)-200424-080659](https://user-images.githubusercontent.com/31968468/80158625-4c890880-860c-11ea-8182-8c9560c788c8.png)

**Comment by kurayami6** [comment]
Still doesn't work as of the latest version.

**Comment by CookiePLMonster** [comment]
Works with **0.1-1600**, but the LED check (whatever it is) times out. Inputs are registered correctly.

![image](https://user-images.githubusercontent.com/7947461/91159832-e949d880-e6c8-11ea-9470-a1f576683f64.png)
![image](https://user-images.githubusercontent.com/7947461/91159860-f36bd700-e6c8-11ea-80f7-5a9e2bca1f2b.png)

**Comment by ggrtk** [comment]
Fixed in #1105.
