### ISSUE TITLE
BIOS screen overlaps with game screen in Analog Controller Service Disc (Revised) (Europe)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#333]
Happens with all renderers and all resolutions.

![2020-04-24_08-24-37](https://user-images.githubusercontent.com/31968468/80158746-9a057580-860c-11ea-84bd-89f1352e1aae.png)

**Comment by stenzek** [comment]
Has this been verified in console? The reverb not being cleared out by the BIOS I can kinda understand, but as far as I'm aware it's not supposed to clear out VRAM.

**Comment by kurayami6** [comment]
This does happen on real hardware.
