### ISSUE TITLE
Graphical glitches during the tile matching minigame in Disney's The Lion King - Simba's Mighty Adventure (USA)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#336]
See how the top of Scar's head is distorted and he's covered in pixels? Happens in all renderers.

![SLUS-01282_2020-04-25_01-31-51](https://user-images.githubusercontent.com/31968468/80232713-afc07c80-8698-11ea-897b-567e4e141e2a.png)

**Comment by kurayami6** [comment]
Still an issue as of the latest version.

**Comment by ggrtk** [comment]
This behavior is present on original hardware.

**Comment by stenzek** [comment]
That's a relief. This was a similar issue to Castlevania.
