### ISSUE TITLE
Graphical glitch during chase level in Disney's The Lion King - Simba's Mighty Adventure (USA) with OpenGL

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#337]
Happens with OpenGL at all resolutions. D3D11 and software look fine.

![SLUS-01282_2020-04-25_03-13-24](https://user-images.githubusercontent.com/31968468/80241046-42b3e380-86a6-11ea-8767-90227c622141.png)

**Comment by stenzek** [comment]
Merged with https://github.com/stenzek/duckstation/issues/361
