### ISSUE TITLE
Holes in the ghosts in Pac-Man World - 20th Anniversary (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#338]
Happens with OpenGL at all resolutions. D3D11 and software are fine. 

![SLUS-00439_2020-04-25_04-43-04](https://user-images.githubusercontent.com/31968468/80246373-a68eda00-86af-11ea-85de-ec727ec7a670.png)

**Comment by stenzek** [comment]
Merged into #361
