### ISSUE TITLE
Sprite glitches in X-Men vs. Street Fighter - EX Edition (Japan) with OpenGL

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#340]
Happens at all resolutions with OpenGL. D3D11 and software look fine.

![SLPS-01284_2020-04-25_05-02-53](https://user-images.githubusercontent.com/31968468/80248074-975d5b80-86b2-11ea-9ddd-7b04e3231179.png)

**Comment by stenzek** [comment]
Merged with https://github.com/stenzek/duckstation/issues/361
