### ISSUE TITLE
Graphics in Rise 2 - Resurrection (USA) are completely broken and gameplay is a black screen

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#341]
![SLUS-00186_2020-04-25_08-54-51](https://user-images.githubusercontent.com/31968468/80263602-76a5fd80-86d4-11ea-8d60-e55b873e28d8.png)

![SLUS-00186_2020-04-25_08-57-38](https://user-images.githubusercontent.com/31968468/80263613-7efe3880-86d4-11ea-9bed-b80ae8eb9bcb.png)

Gameplay is a black screen but I can still hear it and I can see it if I turn on "Show VRAM" 

![SLUS-00186_2020-04-25_08-55-59](https://user-images.githubusercontent.com/31968468/80263622-8887a080-86d4-11ea-895c-11ec5073b279.png)

**Comment by stenzek** [comment]
Please re-test on latest build.
