### ISSUE TITLE
Ground texture is broken in The Centaur's Forest in Disney's hercules using OpenGL

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#343]
Happens at all resolutions with OpenGL. D3D11 and software look fine.

![Capture](https://user-images.githubusercontent.com/31968468/80279076-86f2c280-873e-11ea-8af9-ed3ce1c065bd.PNG)

**Comment by stenzek** [comment]
Merged with https://github.com/stenzek/duckstation/issues/361
