### ISSUE TITLE
Lucky Luke - Western Fever (Europe) softlocks during the first mission.

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#344]
When you walk up to this Mexican a cutscene is supposed to start where he gives you a key but the cutscene never triggers and you're stuck. From what I've read online this is the game's copy protection but I don't know if that's true. 

![SLES-03530_2020-04-26_05-55-29](https://user-images.githubusercontent.com/31968468/80289861-dd82ef80-8784-11ea-9797-cd1b8b0ba62d.png)

**Comment by stenzek** [comment]
Looks like a libcrypt game. Are you providing the SBI file and is it being loaded? Check the log.

**Comment by kurayami6** [comment]
No I don't have any additional files, just BIN and CUE.

**Comment by stenzek** [comment]
Issue is possibly invalid then.

You need the SBI files to play libcrypt games.

**Comment by kurayami6** [comment]
Didn't you fix this issue with libcrypt games a while ago?

**Comment by stenzek** [comment]
The libcrypt games I tested work fine. But you need the SBI files to tell it which sectors have invalid subq data as part of the protection, otherwise it will break.

**Comment by kurayami6** [comment]
In that case I think this emulator should show a warning message if people try and play Libcrypt games without the additional files. Otherwise people will have no idea why things are breaking. Are you certain more accurate emulation wouldn't stop the protection from triggering?

**Comment by stenzek** [comment]
And how is the emulator supposed to know which games have this protection?

Yes. Accuracy has nothing to do with it. The protection is built around invalid subq data on certain sectors of the disc. If you don't know which sectors to invalidate, the protection won't pass. It's the same in mednafen/beetle.

**Comment by kurayami6** [comment]
Don't take that attitude with me. I'm trying to help you. Isn't there a list anywhere of which games use Libcrypt?

**Comment by stenzek** [comment]
It is a legit question. I don't see how the emulator can inform users that their dump is incomplete when it has no way of knowing if the game uses this protection.

**Comment by stenzek** [comment]
Anyway, I'm going to close this as it is possibly invalid. If the issue persists even when using the SBI file, it's either a CD-ROM issue or something else entirely and I will reopen it.

**Comment by kurayami6** [comment]
Well I'll get back to you on that.

**Comment by kurayami6** [comment]
Alright the emulator is detecting the SBI file but the cutscene still isn't triggering. I put it in the same folder as the BIN and CUE files. Should it be somewhere else? 

![Capture](https://user-images.githubusercontent.com/31968468/80296230-74b76980-87bc-11ea-9012-148bb6de505b.PNG)

**Comment by stenzek** [comment]
Is it loading the SBI? You should see a message saying "N replacement sectors loaded from <filename>" after booting the game.

Note that it has to have the same file title as the bin/cue/chd. So if it was called "Bob.cue", the sbi would have to be called "Bob.sbi".

**Comment by kurayami6** [comment]
Renamed the SBI file and finally he wakes up. Thanks for the help. Unfortunately most people still won't have any idea what's going wrong when they encounter Libcrypt and you're gonna keep getting bug reports about it. Maybe you should include a README file with instructions or something?

![SLES-03530_2020-04-26_13-07-18](https://user-images.githubusercontent.com/31968468/80296535-85b5aa00-87bf-11ea-8ad8-f938c70f9f6d.png)

**Comment by stenzek** [comment]
I guess I could add a note saying that sbi files are required for libcrypt games, but really it's up to the user to know which of their games are protected. Like I said before, it's the same as with any other emulator.
