### ISSUE TITLE
Graphical glitches in Lucky Luke - Western Fever (Europe) with OpenGL

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#345]
These all occur with OpenGL at all resolutions. D3D11 and software look fine.

![SLES-03530_2020-04-26_05-34-13](https://user-images.githubusercontent.com/31968468/80290651-15d8fc80-878a-11ea-91e7-8228af274151.png)

![SLES-03530_2020-04-26_06-46-12](https://user-images.githubusercontent.com/31968468/80290656-1e313780-878a-11ea-925e-2f6abdead55e.png)

![SLES-03530_2020-04-26_05-41-58](https://user-images.githubusercontent.com/31968468/80290659-238e8200-878a-11ea-8916-0360f2b7e0a3.png)

**Comment by stenzek** [comment]
Merged with https://github.com/stenzek/duckstation/issues/361
