### ISSUE TITLE
Crackling and popping sound in the music of Lucky Luke - Western Fever (Europe) 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#346]
[SLES-03530_2020-04-26_06-54-40.zip](https://github.com/stenzek/duckstation/files/4533997/SLES-03530_2020-04-26_06-54-40.zip)

**Comment by stenzek** [comment]
The clipping seems to be present in the raw ADPCM stream, rather than the result of mixing. Does this also occur on the console?
