### ISSUE TITLE
Graphics on the TV above the track in Running High (Japan) are broken in all renderers

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#347]
You can't see it because this emulator doesn't have a way to record videos but the graphics on that TV flicker in and out of existence. 

![SLPS-00751_2020-04-26_09-26-42](https://user-images.githubusercontent.com/31968468/80293383-3a40d300-87a2-11ea-9e3a-5e6b119e0ac5.png)

**Comment by stenzek** [comment]
Does this happen in other emus/on console? It seems to use (0,0) as a texture source for both framebuffers rather than the opposite framebuffer, which is why on every other frame it renders only what has been drawn so far. And I don't think texture page selection is broken :/

**Comment by kurayami6** [comment]
Happens on real hardware.
