### ISSUE TITLE
Vampire Savior - EX Edition (Japan) // Missing background layer.

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#348]
On the character selection screen, a layer is missing.

![Vampire](https://user-images.githubusercontent.com/52127625/80293473-f2995780-875f-11ea-9099-e435c1536105.jpg)

**Comment by benderscruffy** [comment]
same issue as #71

**Comment by stenzek** [comment]
Should be fixed in latest build.

**Comment by Zet-sensei** [comment]
Fixed on 0.1-755.
