### ISSUE TITLE
Exploding vertices in Men in Black - The Series - Crashdown (USA) with OpenGL and D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#349]
I think that's what it's called. Happens with OpenGL and D3D11 at all resolutions. Doesn't happen with software. 

![SLUS-01387_2020-04-27_04-30-29](https://user-images.githubusercontent.com/31968468/80316302-614de200-8840-11ea-97c4-b1269f52dd85.png)

![SLUS-01387_2020-04-27_04-17-01](https://user-images.githubusercontent.com/31968468/80316303-67dc5980-8840-11ea-83b7-6023439bd151.png)

**Comment by stenzek** [comment]
Should be fixed as of https://github.com/stenzek/duckstation/commit/ce46dbeeca805cf53a1e394216451715a0580fee.

**Comment by kurayami6** [comment]
Fixed.
