### ISSUE TITLE
Mary-Kate and Ashley - Winners Circle (USA) freezes the emulator when using the software renderer

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#350]
Always at the exact same moment right after the first screen fades to black. Only happens with software, OpenGL and D3D11 work fine.

![SLUS-01362_2020-04-27_05-32-22](https://user-images.githubusercontent.com/31968468/80317679-85152600-8848-11ea-8ba5-1f6e1c7b3857.png)

![Capture](https://user-images.githubusercontent.com/31968468/80317685-8ba39d80-8848-11ea-9e4e-1e9f29b835c7.PNG)

**Comment by stenzek** [comment]
Please re-test on the latest build.

ps hi /vg/, thanks for the constructive criticism and I'm flattered my little fun side project is a meme emulator :)

**Comment by kurayami6** [comment]
Fixed.
