### ISSUE TITLE
Flickering green pixels in the main character's shadow in City Of Lost Children (USA) when upscaling OpenGL

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#353]
![SCUS-94150_2020-04-28_04-57-40](https://user-images.githubusercontent.com/31968468/80409921-07ffb480-890d-11ea-91ed-fc7840ff7c36.png)

**Comment by stenzek** [comment]
Merged with https://github.com/stenzek/duckstation/issues/361
