### ISSUE TITLE
Red and green pixels on the anti piracy screen in YoYo's Puzzle Park (Europe)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#354]
In the top left corner. Happens with all renderers, all resolutions and all crop modes. 

![Capture](https://user-images.githubusercontent.com/31968468/80410328-bc013f80-890d-11ea-8462-814ae79b43fd.PNG)

**Comment by stenzek** [comment]
Given this is likely a static VRAM upload and not being rendered, the chances of it being an issue in DuckStation's renderer are lower. Please verify this does not occur on console.
