### ISSUE TITLE
Graphical glitch during cutscenes in Lucky Luke - Western Fever when upscaling with OpenGL

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#355]
Only happens when upscaling OpenGL. Happens with all crop modes. 

![Capture](https://user-images.githubusercontent.com/31968468/80420784-afd1ae00-891e-11ea-88af-810fbfc1cbc9.PNG)

**Comment by stenzek** [comment]
Merged with https://github.com/stenzek/duckstation/issues/361
