### ISSUE TITLE
Tekken 2 (Japan) // Crashes the emulator heavily.

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#357]
Black screen after the BIOS boot.

Can't close the emulator or taking any commands with keyboard/mouse.

Need to kill the process on Task Manager.

**Comment by stenzek** [comment]
Caused due to an infinite DMA chain with no commands.

I've written a hardware test which determines how this behaves on the console, will implement in the emulator soon.

**Comment by stenzek** [comment]
Please re-test on latest build.

**Comment by Zet-sensei** [comment]
Fixed by commit https://github.com/stenzek/duckstation/commit/9d1eb321ec1764ec4c4d918d977465b8db92dda4
