### ISSUE TITLE
Threads of Fate (USA) // Messy 3D display (triangles, flickering) with Recompiler & Cached Interpreter.

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#358]
Flickering incorrect 3D elements & triangles.

![Threads](https://user-images.githubusercontent.com/52127625/80426535-33bb7400-88e6-11ea-898a-169e844c129a.jpg)

Note - This game is complex to emulate.
Requires correctish CPU branch delay slot emulation.

**Comment by stenzek** [comment]
Does switching between interpreter (not cached) and recompiler change anything?

**Comment by Zet-sensei** [comment]
The game is correctly rendered on Interpreter Mode only.
Recompiler & Cached Interpreter does have the problem.

**Comment by kurayami6** [comment]
Still an issue with recompiler mode as of the latest version. The game also stutters a lot. 

![SLUS-01019_2020-06-05_16-47-40](https://user-images.githubusercontent.com/31968468/83845523-67db4d80-a74c-11ea-9fed-5d6ed07eb3c8.png)

**Comment by Zet-sensei** [comment]
Issue should be closed as a gameini file exists now - with the Interpreter CPU Mode forced for that game.

**Comment by Zet-sensei** [comment]
In order to support the JPN version of the game.
Please add also to gamesettings.ini

```
# SLPS-02330 (DewPrism (Japan, Asia))
[SLPS-02330]
ForceInterpreter = true
```

**Comment by stenzek** [comment]
Should be fixed in the recompiler as of https://github.com/stenzek/duckstation/commit/042bdd9c0cd7e07694fb2ec412297b29487c2809.

Could you please re-test DewPrism as well?

**Comment by Zet-sensei** [comment]
Graphics confirmed as fixed on the recompiler mode (no more triangle explosions), but the game pauses and stutters for about 200ms between transitions and new scenes (even when trying to load the main title screen). 

Cached interpreter isn't recommended as it renders one frame per around 2550ms during the first seconds of the game (after choosing a character).

Same for DewPrism (the JPN version of the game).

I leave you the choice ro either reopen the issue ticket, left it closed or reclassify it for another time (at your will).
We have discussed a bit on Discord about the complexity of the game code (especially the conditional branch).

**Comment by stenzek** [comment]
I'm not able to reproduce the frame time spikes, neither on the main menu nor starting a new game. Is there something I'm missing?

The cached interpreter issue is just log spam - could work around that by turning off the log, but I'm going to remove the message which gets repeated later anyway.
