### ISSUE TITLE
Audio is broken during the first boss fight of Nightmare Creatures (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#359]
And let me just go on record as saying I hate this fucking game and have no desire to ever play it again except to test for issues. 

[SLUS-00582_2020-04-28_08-19-24.zip](https://github.com/stenzek/duckstation/files/4542278/SLUS-00582_2020-04-28_08-19-24.zip)

**Comment by stenzek** [comment]
Then.. don't play it again? :)

Sounds similar to the clipping in #326, which I suspect has something to do with voice allocation, it seems to play the same effect/note on a bunch of channels when it probably should only be played on one.

**Comment by kurayami6** [comment]
Fixed.
