### ISSUE TITLE
Super Puzzle Fighter II Turbo (USA) // Incorrect screen position & flickering line

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#360]
- On the Capcom FMV at startup, a line is flickering.

- The game screen is incorrectly positioned on all renderers and crop options.
![Puzzle](https://user-images.githubusercontent.com/52127625/80427340-cdcfec00-88e7-11ea-8560-342b91d7a12d.jpg)

**Comment by Zet-sensei** [comment]
After a new test on version 0.1-841.
The flickering line only appears with : 'No Crop' and 'All Borders' options.

'Only Overscan Area' option is visually correct now (with a slight incorrect position).

**Comment by stenzek** [comment]
In that case, it's probably not a bug. The "overscan area" was usually hidden on TVs of the time.
