### ISSUE TITLE
OpenGL Renderer Issues

### ISSUE THREAD

**Issue by stenzek** [stenzek/duckstation#361]
Rather than having a separate thread for issues only present in the OpenGL renderer, let's keep them all here to make it easier to track.

This should only be used for issues which are present in the OpenGL renderer and not in the D3D11/Software renderers.

 - ~~Graphical glitch during cutscenes in Lucky Luke - Western Fever when upscaling with OpenGL: #355~~
 - ~~Flickering green pixels in the main character's shadow in City Of Lost Children (USA) when upscaling OpenGL #353~~
 - ~~Graphical glitches in Lucky Luke - Western Fever (Europe) with OpenGL #345~~ 
 - ~~Ground texture is broken in The Centaur's Forest in Disney's hercules using OpenGL #343~~ 
 - ~~Sprite glitches in X-Men vs. Street Fighter - EX Edition (Japan) with OpenGL #340~~ 
 - ~~Graphical glitch during chase level in Disney's The Lion King - Simba's Mighty Adventure (USA) with OpenGL #337~~ 
 - Twinbee RPG (Japan, Asia), True Love Story 2 (Japan) (Disc 1) texture coordinate off-by-one error in OpenGl #276 
 - ~~Holes in the ghosts in Pac-Man World - 20th Anniversary (USA) #338~~

**Comment by kurayami6** [comment]
Jax has a blue square on his head when upscaling OpenGL in Mortal Kombat: Special Forces

![SLUS-00824_2020-04-28_15-27-47](https://user-images.githubusercontent.com/31968468/80454235-141b5e80-896d-11ea-9f6a-cd7a95f581a0.png)

**Comment by kurayami6** [comment]
Red dots on the carpet in Disney's Atlantis when upscaling OpenGL.

![SCUS-94636_2020-04-29_04-30-42](https://user-images.githubusercontent.com/31968468/80524074-6478d780-89d2-11ea-9b68-549dd9138545.png)

**Comment by kurayami6** [comment]
Broken desk in Disney's Atlantis when upscaling OpenGL

![SCUS-94636_2020-04-29_04-33-26](https://user-images.githubusercontent.com/31968468/80524300-bfaaca00-89d2-11ea-9f63-542dfd0fb1fe.png)

**Comment by kurayami6** [comment]
Broken graphics on Sarcophagus in Disney's Atlantis when upscaling OpenGL

![SCUS-94636_2020-04-29_04-44-05](https://user-images.githubusercontent.com/31968468/80525447-968b3900-89d4-11ea-8982-d9d197e7fe36.png)

**Comment by HeroponRikiBestest** [comment]
opengl off by one in the boss health bar for 70's Robot Anime - Geppy-X - The Super Boosted Armor (Japan) (Disc 1)
opengl
![image](https://user-images.githubusercontent.com/50224630/80565928-92482700-89a6-11ea-8818-3e6ae6ed111d.png)
software
![image](https://user-images.githubusercontent.com/50224630/80565935-97a57180-89a6-11ea-9f2e-de6d9b89f94d.png)
another off by one error in Bomberman Fantasy Race (Japan)
opengl
![image](https://user-images.githubusercontent.com/50224630/80566011-c7547980-89a6-11ea-9638-abfa58d4811d.png)
software
![image](https://user-images.githubusercontent.com/50224630/80566028-d63b2c00-89a6-11ea-94b7-325cfd50da5c.png)
the disjoined stamina meter pixels at the top flicker (they dont on software)

**Comment by kurayami6** [comment]
Texture on loading bar is misaligned in Championship Motocross 2001 featuring Ricky Carmichael (USA) when upscaling with OpenGL.

![SLUS-01230_2020-04-29_18-23-41](https://user-images.githubusercontent.com/31968468/80577022-82cdea00-8a49-11ea-9edf-74e893b587a1.png)

**Comment by stenzek** [comment]
I've pushed a change which may affect some of these: https://github.com/stenzek/duckstation/commit/557a6c3696b79a000f9dcbd84f530d360849f608

Strangely enough, it was all fine on my AMD GPU, but broken on Intel and NVIDIA. Gotta love subtle rasterization differences, it's all probably within spec, just very slightly different behavior.

**Comment by kurayami6** [comment]
Mortal Kombat is fixed, City Of Lost Children is fixed, both the issues with Lucky Luke are fixed. I'll test the rest later.

**Comment by kurayami6** [comment]
Hercules is fixed, Pac-Man is fixed, Atlantis is fixed except for the sarcophagus which it turns out is also broken in D3D11 so I'll make a separate issue for that.

**Comment by kurayami6** [comment]
The X-Men VS Street Fighter glitch is another one that happens with both OpenGL and D3D11 so not relevant to this discussion.

**Comment by kurayami6** [comment]
Lion King and Motocross are both fixed.

**Comment by stenzek** [comment]
All these appear to be fixed.
