### ISSUE TITLE
UX/UI Improvements

### ISSUE THREAD

**Issue by stenzek** [stenzek/duckstation#362]
Please feel free to add to this thread if you have any ideas which you think would make the UI better for you, as a user.

- [ ] Storing last played information with games so you can sort by most recent
- [x] Built-in memory card manager
- [x] Hide system console (#74)
- [ ] Grouping games into categories
- [ ] Automatic download of box art in game list
- [ ] Search feature for game list
- [ ] Displaying compressed size as well as uncompressed size in game list
- [x] Star rating for game compatibility (would need a web service/backend as well)
- [x] Discord API integration - displaying game name
- [x] Auto updater (#60)
- [x] Multiple mappings for buttons
- [ ] Launch random game from list
- [x] Integer scaling of display
- [ ] Disc image verification
- [x] Automatic analog mode enable for controllers
- [x] Saving of window size/position, column size/order
- [ ] Automatic renaming from game title<->game code memory cards
- [ ] Hide games from list
- [ ] Indicator when overrides are present
- [ ] Custom sort order/sort tags

**Comment by Basmurd** [comment]
New feture, separate memcard per game, is awesome, but not intuitively for management. How about card name, have the name from tag cue, bin or iso file? Qt version not see iso files at all O_O

**Comment by stenzek** [comment]
@Basmurd Could you clarify what you mean there? You can choose to have the memory cards named after the game code or the title of the game (which is the filename if you don't use the redump database). Or are you meaning pull some metadata from the cuesheet and use that?

Are there any PlayStation disc images in ISO format? Most games take advantage of CD/XA to some extent, so they need the raw 2352 byte sector dumps (bin format). That said, I could add a ISO image loader which dynamically generates the extra content if the use cases are there. Maybe some homebrew would use it?

**Comment by Basmurd** [comment]
I watched the settings inattentively, such an option already exists. Sorry :) My other request is still valid. QT version does not see ISO files.

**Comment by tony971** [comment]
* #75 can be merged into this
* support .m3u files for multi-disc games (and possibly replace the individual discs with them in the games list)
* use keyboard bindings if mapped controller isn't currently plugged

**Comment by kurayami6** [comment]
The ability to mute the emulator would be nice.

**Comment by ignacionelson** [comment]
@kurayami6 volume controls (up, down, mute) would be awesome

**Comment by kurayami6** [comment]
A column for flags of the countries the games are from. Redump always includes the country in the game's title so it should be easy for the emulator to check. And if someone is using a dump with no country listed in the name the flag can just show up as a white square with a question mark.

**Comment by stenzek** [comment]
Latest builds can hide the system console (it's hidden by default, enable via advanced options), integer scaling for display (works best when used in conjunction with linear upscaling/filtering **disabled**), and Discord presence support.

.. whenever the CI finishes building.

**Comment by Basmurd** [comment]
What about the synchronization of saves, memory cards and save states, to google drive or something else?

**Comment by stenzek** [comment]
@Basmurd not a bad idea, but I feel like for the desktop version there's too many platforms. Easier to just run the emu out of a synced folder. For the Android version though, it could be an idea.

**Comment by Basmurd** [comment]
> @Basmurd not a bad idea, but I feel like for the desktop version there's too many platforms. Easier to just run the emu out of a synced folder. For the Android version though, it could be an idea.

You can simply synchronize the folder with the saves to transfer to other platforms or between PCs.

**Comment by stenzek** [comment]
Volume control in Qt is now hooked up. I also added volume up/down/mute hotkeys.

**Comment by heckez-sys** [comment]
custom anything you can code

**Comment by heckez-sys** [comment]
[Feature Request] motion blur

**Comment by heckez-sys** [comment]
add perspective correction

**Comment by fefo-dev** [comment]
Looked into a bunch of issues to get here just to find that you pinned it earlier, nice.

Are bin files unlisted to avoid making a mess on libraries with correct cue sheets? My guess as the emulator works on single file bins correctly, and I'm one of those.

Also, is there a way to display the mouse cursor (if active perhaps) in fullscreen mode? Mostly to point stuff in some cases. It works as expected on window mode, which is a big upgrade from every other ps1 emu.

These are extreme edge-cases so I felt better to post here instead of creating an issue, forgive me if its not the heart of the thread. Been loving this emulator so far, thank you for the excellent work.

**Comment by stenzek** [comment]
> Are bin files unlisted to avoid making a mess on libraries with correct cue sheets? My guess as the emulator works on single file bins correctly, and I'm one of those.

That's correct. Single file .bins work fine if you load them directly, but to avoid duplicating entries in the game list they're not included there, as for multi-track games you'd end up with N+1 entries in the game list, with most of them being useless unless you really wanted to play that specific audio track in the shell's CD player ;)

> Also, is there a way to display the mouse cursor (if active perhaps) in fullscreen mode? Mostly to point stuff in some cases. It works as expected on window mode, which is a big upgrade from every other ps1 emu.

I'm adding a software cursor for guncon games, so yeah, I could also make the standard cursor an option there.

**Comment by fefo-dev** [comment]
Thanks you.

@tony971 
> use keyboard bindings if mapped controller isn't currently plugged

Multiple bindings would be nice, even if hot swapping works without a hitch.

**Comment by andercard0** [comment]
- [ ] Translation of the emu
I could do it just tell me where the texts are and will do my best!

**Comment by stenzek** [comment]
>  Translation of the emu
> I could do it just tell me where the texts are and will do my best!

I don't think I compiled the Qt DLLs with localization support, but most of the UI (apart from things like OSD messages) calls the translator, so it should be possible without too much work. Will look into it the next time I update Qt.

**Comment by picili** [comment]
Add a 'last date played' collumn, so by sorting by it, one can check recently played games
When selecting a game, a preview window shows a screenshot of the savestates that will be loaded when starting the game

**Comment by andercard0** [comment]
Button Bindings new look:
(Comestic Suggestion)

**Before**
![Before2](https://user-images.githubusercontent.com/43047877/86304530-7d298780-bbe5-11ea-8af4-0a8fd1c29ee2.png)

**After**
![New](https://user-images.githubusercontent.com/43047877/86304567-98949280-bbe5-11ea-88fe-e19fc32f3f7d.jpg)

**Comment by Abbanon** [comment]
Here's a few things I recommend:
- Have the emulator remember window scale/window size 
- Have the ability to select screen size quick presets (x1, x2, x3, x4, etc. - as seen in other emulators)

**Comment by Abbanon** [comment]
- The ability to modify window size by integers based on your selected aspect ratio

Example, as seen in VBA-M:
![Screenshot_1](https://user-images.githubusercontent.com/37251822/86515085-99dfde00-bde4-11ea-9836-ee1c2d2a478a.png)
Example, as seen in PPSSPP:
![Screenshot_2](https://user-images.githubusercontent.com/37251822/86515090-a2d0af80-bde4-11ea-889d-72da09f64334.png)

**Comment by Shideravan** [comment]
Support for Manuals (which can be handled by a external .pdf reader).
There 2 ways to give access to this. Automatically downloading them from replacement docs http://www.replacementdocs.com/download.php?list.14 based on software available in the list or supporting for MAME's softwarelist psx.xml (https://github.com/mamedev/mame/blob/master/hash/psx.xml), which can be used to use for images and manuals (such as those from Progetto Snaps) 
http://www.progettosnaps.net/manuals/
Maybe a support for MAME PlayStation .xml could be needed for this, but if so, I can talk directly to the Antopisa so he can make the separate software manuals available, especially the PlayStation ones to be used directly on the DuckStation (or even I can create these sets myself based with those already available).
This is a image of QMC2 using MAME's softwarelist .xml support to community-created images and manuals for MAME.
![image](https://user-images.githubusercontent.com/12163923/88173976-d770a380-cbf9-11ea-9bcb-0f6f1c5583a0.png)

**Comment by Shideravan** [comment]
Cheat code support (compatible with gameshark codes)

**Comment by Abbanon** [comment]
The ability to choose how long the on-screen display messages stay visible would be nice. Either via slider or a set of choices.
Sometimes I find myself wanting to be able to read them but they disappear too quickly.

**Comment by stenzek** [comment]
> The ability to choose how long the on-screen display messages stay visible would be nice. Either via slider or a set of choices.
Sometimes I find myself wanting to be able to read them but they disappear too quickly.
This one's a bit tricky. The function which displays the message takes a duration, different messages have different durations (e.g. errors stay up for longer). I suppose I could add a multiplier to it though.

**Comment by Blackbird88** [comment]
File Format row like Dolphin has so you can see whether the game is CUE/BIN, CHD etc.
![image](https://user-images.githubusercontent.com/4414625/89720497-0e550080-d9d3-11ea-9c8d-73b641c6781e.png)

**Comment by RinMaru** [comment]
I guess a neat feature would be the ability to have **multi disc games** use a **single memory card** instead of one for every disc. a quick workaround would be to _allow the user to optionally assign memory cards to games_

**Comment by CookiePLMonster** [comment]
When switching between software/hardware rendering and/or changing the resolution scale, messages are being displayed in top left by default. However, when toggling PGXP, no such feedback is given. In places where the effect of PGXP is not clearly visible, it might leave the user confused as so whether the feature is enabled or not.

**Comment by stenzek** [comment]
> When switching between software/hardware rendering and/or changing the resolution scale, messages are being displayed in top left by default. However, when toggling PGXP, no such feedback is given. In places where the effect of PGXP is not clearly visible, it might leave the user confused as so whether the feature is enabled or not.
> 
> EDIT:
> I have realized since that this information is shown in the emulator window, my confusion came from the fact I was using it in fullscreen. I still kind of think it would be nice to make it consistent, though.

Indeed. The issue is I have two paths for displaying messages from the core, one is a general "display message", the other is an explicit "display OSD message". I'll probably just make the former use an OSD message instead of the status bar, it's more appropriate.

**Comment by andercard0** [comment]
Hey Sten.. if it isn't asking too much I'd like two things.

- Refresh game list option.
'Refresh' option likewise Cemu does (right click on game list > Refresh) or let us choose a shortcut in hotkey settings menu 
would be good as well.

Yeah! I know that there is a Configuration > Game list > Scan new games option. But, please, consider a shortcut.

Maybe adding refresh button on the toolbar like Dolphin has:
- Refresh | Controllers | Graphics - 
Wish I could to set up my controllers direct from the interface.. same as dolphin does :)

**Comment by tony971** [comment]
Any chance of getting a Game List setting to show playlists instead of their individual discs?

**Comment by HeroponRikiBestest** [comment]
The option to set a custom aspect ratio as well as a custom widescreen hack aspect ratio.

**Comment by mirrornoir** [comment]
It would be nice if Duckstation had a visual indication that User Settings are active in the Game List. PPSSPP and RPCS3 have this feature and it can be handy to see at a glance which games have custom settings instead of needing to dig into properties. 

Here's the feature in RPCS3, both Kingdom Hearts games have Custom Configs, while Killzone uses Global Config: 
![image](https://user-images.githubusercontent.com/19215655/94643162-26028400-02b4-11eb-9efe-75a09ce3aeb2.png)

**Comment by Richard-L** [comment]
@mirrornoir https://github.com/stenzek/duckstation/issues/778

**Comment by Abbanon** [comment]
And to further add onto @mirrornoir's post, here's the custom per-game config icon for PPSSPP, in both grid view and list view:
![Screenshot_3](https://user-images.githubusercontent.com/37251822/94678184-1b63e100-02ec-11eb-8409-f5d9aaa618aa.png)
![Screenshot_2](https://user-images.githubusercontent.com/37251822/94678191-1c950e00-02ec-11eb-9885-85516eebebec.png)

**Comment by HeyItsLollie** [comment]
> Button Bindings new look:
> (Comestic Suggestion)
>
> **After**
> (image) [New](https://user-images.githubusercontent.com/43047877/86304567-98949280-bbe5-11ea-88fe-e19fc32f3f7d.jpg)

Tagging onto this, order the button list so that button groups appear together, without being split across columns. EG: Triangle, Cross, Circle and Square are a group. Start, Select, and Analog could _maybe_ be a group, debatable. "I" and "II" for the NeGcon, etc.

This is a minor suggestion for sure, but it would make the binding panel easier to read from a glance.

**Comment by ImSpecial** [comment]
Not really a feature request, and I have no idea if this is a feasible thing to do or something your willing to look into or think about later down the road, heck maybe it's already planned, I dunno, but I wanted to mention it anyway because it seems like this would be a harder change to do later down the road then dealing with it early.

DuckStation IMO needs to stick with one of it's menu's/GUI's and abandon the other (QT vs. SDL) because they have missing and different options from each other, there really shouldn't be two executable doing almost the same thing, consolidating them both into a single executable, taking the best/all from both worlds is what I'm trying to say you should try and achieve, etc. EZ-PZ, eh?

**Comment by ImSpecial** [comment]
Drop the giant Duck? God no! I actually prefer that one myself, and just kinda wished for it to be more feature complete/comparable to the Qt one settings wise so I didn't have to deal with two frontends... I didn't know SDL was more or less for dev purposes and Qt was meant for end users, if that's the case then I guess you want to keep SDL "light". Keep them both if your thinking of removing it IMO.

**Comment by foxsevent** [comment]
If possible please add "hide disc images if they're part of a playlist" so just the playlist file will shown and not the playlist and all the disc like it is now.
![Przechwytywanie](https://user-images.githubusercontent.com/64225743/97746059-04323200-1aea-11eb-90ff-4cb617b98e2e.PNG)

**Comment by cs50-account** [comment]
I'd love an exit on shutdown feature.

**Comment by foxsevent** [comment]
Recently I noticed you added on right click - memory card editor for discs images but not playlist, please add this as playlist use thier own memory cards.

**Comment by andercard0** [comment]
Hey Sten! our hacker man (Unicorngoulash) has some ideas for UX / UX improvements as follows:

Ideas/Suggestion: 
1:AOB scan and injection cheat format as a an alternative duckstation exclusive to rom patching.

2:User assignable button inputs to turn any code on or off

3:Further implementation of the gameshark pro code types

4:The option to turn on SSAA, MSAA per game besides general.

5:A way to access the FPS cap as a code type to set conditions to bypass load times.

6:Turbo control for individual buttons (5ms will usually do)

7:Hardware scan to have duckstation set a recommended setting like pc games would.

8:Debugger

9:Giving Unicorngoulash a bucket with kfc hot wings. (It's finger lickin good)

**Comment by Unicorngoulash** [comment]
Ideas/Suggestion
1:AOB scan and injection cheat format as a an alternative duckstation exclusive to rom patching.
  Example: Normal
                 
                 [Always activate flying]
   Scan:      AOBS= 3A 00 41 00
   Inject:     AOBI=  3A 00 00 24]


   Example: Byte skipp 

                 [Moon Jump]
   Scan:      AOBS= FF FF ?? ?? 00 24 (Will scan FF FF 00 24)
   Inject:     AOBI=  FF FF E3 20

Can obviously be improved, but this is the general idea. 

2:User assignable button inputs to turn any code on or off
3:Further implementation of the gameshark pro code types
4:The option to turn on SSAA, MSAA per game besides general.
5:A way to access the FPS cap as a code type to set conditions to bypass load times.
6:Turbo control for individual buttons (5ms will usually do)
7:Hardware scan to have duckstation set a recommended setting like pc games would.
8:Debugger
9:Giving Unicorngoulash a bucket with kfc hot wings. (It's finger lickin good)

Note: These are just some thoughts, no demands. Stenzek works hard and it's his emulator. I'm just pitching ideas to increase the Ducks superiority.

**Comment by Shideravan** [comment]
Idea: Use save blocks to ilustrastrate in the game list. The block images can be saved when a block is created for that game in the memory card image. You can even give support for block animations :)

**Comment by foxsevent** [comment]
> Idea: Use save blocks to ilustrastrate in the game list. The block images can be saved in a special cache when a block is created for that game in the memory card image. You can even give support for block animations (saving the multiple images and animate then in the list) :)

Interesting idea, thou you do realize those icons/animations are like 10x10 pixels in size?
One issue with this is that some games have more than 1 icon/animation that changes.
Plus there's the problem of how the emulator would know which save is from which game when you would have multiple saves on a card, maybe reference and match the region code of both?

**Comment by Shideravan** [comment]
> > Idea: Use save blocks to ilustrastrate in the game list. The block images can be saved in a special cache when a block is created for that game in the memory card image. You can even give support for block animations (saving the multiple images and animate then in the list) :)
> 
> Interesting idea, thou you do realize those icons/animations are like 10x10 pixels in size?
> One issue with this is that some games have more than 1 icon/animation that changes.
> Plus there's the problem of how the emulator would know which save is from which game when you would have multiple saves on a card, maybe reference and match the region code of both?

Yes I do. No problem if it's 10x10 in size in fact. You can just stretch both vertically and horizontally with filtering off. Qt itself has support for this.
`QImage img("gameblock.png");
QImage img2 = img.scaled(hvalue, vvalue, Qt::KeepAspectRatio);`
Also, the idea isn't get the icon from a multisave memory card (that would sound a little stupid). The idea is get the image from the streaming data when **creating** a new save file (or copying/overwriting) when the game itself already running. **Dolphin** itself  do it for get ar image for gamecube games

**Comment by stenzek** [comment]
> Idea: Use save blocks to ilustrastrate in the game list. The block images can be saved in a special cache when a block is created for that game in the memory card image. You can even give support for block animations (saving the multiple images and animate then in the list) :)

A couple of problems here:
 - Wouldn't work in shared mode - there isn't always a clear connection between the save filename and the game id.
 - Requires you to open the game *and* save before the image is known and can be displayed.

**Comment by Shideravan** [comment]
> > Idea: Use save blocks to ilustrastrate in the game list. The block images can be saved in a special cache when a block is created for that game in the memory card image. You can even give support for block animations (saving the multiple images and animate then in the list) :)
> 
> A couple of problems here:
> 
> * Wouldn't work in shared mode - there isn't always a clear connection between the save filename and the game id.
> * Requires you to open the game _and_ save before the image is known and can be displayed.

You can add the option to show the memory blocks image in the list only if a separated save from game is selected and put the info in the checkbox something like "Requires that you manually create a save file inside the game first to image to be shown".

**Comment by SA-X0** [comment]
Hello there stenzek, not sure if this the right place or do i need to open a feature request?
Could it be considered the support for the 4mbs PS2 bios?
Beetle PSX HW loads them without any problem, in order to make them work i had to trim it down the PS2 bios to 512kbs with HEX (Sorta what Sony did with the PS2 V1.90A bios included on the PS3) otherwise Duckstation dosen't recognize them.
From my part i would like if you could consider for support of the 4mbs PS2 bios without been hashed (since there's many)
Thanks and have a nice.

**Comment by im-eliminator** [comment]
Would it be possible to change discs using the controller instead of needing a keyboard and mouse?  I think that would improve the experience of playing on a big screen in full screen.

**Comment by Blackbird88** [comment]
When Alt+tabbing from Exclusive Fullscreen, it'd be nice if it kept the game in fullscreen in background instead of going back to Windowed (also how Dolphin works).
Current behavior makes Game Pause screen feature of LaunchBox very awkward.

**Comment by thechad666** [comment]
the ability to completely exit (ui) with one key on a controller for the sake of front end users

**Comment by fefo-dev** [comment]
A hotkey to toggle texture dumping/replacement would be useful for controlled dumps and comparison.

**Comment by shakeyourbunny** [comment]
- Support for .7z, .rar and .zipped files which contain the game files (iso, bin, cue, wav tracks).
- Support for Networking

**Comment by bmsuseluda** [comment]
I would love to change the data directory

**Comment by GideonZhi** [comment]
Hi! Speaking as a romhacker, the state of hacking utilities on PS1 is... well, honestly, it's pretty shit. The debugging features in the SDL version are actually a step above what most PS1 emulators have - being able to visualize vram and trace CPU execution is immediately really helpful. But I'd love to have a just-in-time debugger, with disassembly, register views, and breakpoints at my disposal. Huge bonus points if system function names resolve :)

I know this is an enormous ask and I'm not expecting much, but damned if it wouldn't be incredibly nice.

**Comment by stenzek** [comment]
> Hi! Speaking as a romhacker, the state of hacking utilities on PS1 is... well, honestly, it's pretty shit. The debugging features in the SDL version are actually a step above what most PS1 emulators have - being able to visualize vram and trace CPU execution is immediately really helpful. But I'd love to have a just-in-time debugger, with disassembly, register views, memory editor, and breakpoints at my disposal. Huge bonus points if system function names resolve :)
> 
> I know this is an enormous ask and I'm not expecting much, but damned if it wouldn't be incredibly nice.

Qt frontend has a debugger.

**Comment by GideonZhi** [comment]
> Qt frontend has a debugger.

I'm sorry, but I can't find it. I do see it in the changelist, and I've found the memory scanner in the cheat manager, but I'm not sure that's what you mean. I don't see anything in the settings to enable it either (set the execution mode to Interpreter just in case that was a requirement.) Do I need to add something to the settings.ini file to enable it?

**Comment by stenzek** [comment]
> > Qt frontend has a debugger.
> 
> I'm sorry, but I can't find it. I do see it in the changelist, and I've found the memory scanner in the cheat manager, but I'm not sure that's what you mean. I don't see anything in the settings to enable it either (set the execution mode to Interpreter just in case that was a requirement.) Do I need to add something to the settings.ini file to enable it?

Advanced settings -> show debug menu, then debug -> cpu debugger. Don't need to use interpreter, it will switch automatically as needed.

**Comment by GideonZhi** [comment]
Oh sweet, thanks!

**Comment by HeyItsLollie** [comment]
Reposting a UX/UI suggestion that originated in #1013, and expanding upon it based on a couple older suggestions in this thread:
Split the Controller Settings menu off into its own screen, and implement a Controller Profile list into the UI.

![Mockup of expanded Controller Profiles screen](https://user-images.githubusercontent.com/30498581/105690458-c2c5ed00-5f47-11eb-9ad2-75bfd6e275f6.png)

The key point is to make it more readily apparent that a Controller Profile is only meant to handle a single controller type.

In DuckStation's user data folder (C:\Users\\[user]\Documents\DuckStation), there's a folder called "inputprofiles" where user-made controller profiles are stored. This folder could be used to automatically populate the profiles list, alongside the default profiles that come with DuckStation. (@ggrtk has mentioned separating controller configs out into their own *.ini files, via #1365)

The list could be sorted in a few ways:
- Controller Type
- Name
- Favorites (ordered alphabetically, and with DuckStation's profiles being favorited by default)

"Load" and "Save" would become fairly redundant. In their place:
- "New Profile" and "Delete Profile", to do what you'd expect them to do.
- "Open in Explorer..." to open the "inputprofiles" folder, where controller profile *.ini files can be dropped in.

Finally, a couple updates for the Button Bindings section:
- Button icons next to each binding. In this instance, I've opted for generalized button prompts. (via @andercard0's [comment from earlier in this thread](https://github.com/stenzek/duckstation/issues/362#issuecomment-652718182))
- Reorganizing the bindings to be easier to read at a glance, with buttons displayed in groups, in a way that relatively represents the controller type being bound. Eg: D-Pad and Action Buttons on the left and right columns, shoulders and triggers spanning across both columns.

**Comment by arnoldsecret** [comment]
Making the emulator portable by creating a directory where you can store your BIOS files without depending on the `Documents` folder on Windows.

**Comment by jpchow26** [comment]
> Making the emulator portable by creating a directory where you can store your BIOS files without depending on the `Documents` folder on Windows.

If you wish to use a "portable" build, where the user directory is the same as where the executable is located, create an empty file named portable.txt in the same directory as the DuckStation executable.

**Comment by ImSpecial** [comment]
Throwing this in here in case you missed it, about the full-screen stuff saving

https://github.com/stenzek/duckstation/issues/1636#issuecomment-778597593

**Comment by vanfanel** [comment]
I have noticed that sometimes, when going back to the main menu from some sub-menus, there is no highlighted option and there's no way to control the menu anymore (so I have to kill duckstation-nog with killall).

Also, is there a way to disable GUI messages from appearing on top of running games?

**Comment by danvx6** [comment]
I've been trying to set up a way to sync saves seamlessly between my Windows PC and Android phone.  I've been doing this with other emulators for many years. To do this in the way that works with my syncing app, I hope these features can be added:
Windows version:
-change user directory in options or config file (or specifically the memcards and savestates directories) Currently can set the shared memcard directory, but I'd much prefer to keep game-specific memcards and keep them all synced
Android version:
-change memcard and savestate save location
or at least be able to use a shared memcard with custom directory like in the Windows version. At current, I can't find this option, so I can't even get a shared memcard synced to the proper directory on my phone.

**Comment by shikulja** [comment]
Here it would be nice to somehow align, or at least highlight in bold
![image](https://user-images.githubusercontent.com/3386359/109404165-86394700-7974-11eb-992b-e67e03eac218.png)

esc from game. Yes\No buttons need add to .ts
![image](https://user-images.githubusercontent.com/3386359/109404207-d2848700-7974-11eb-99bd-81fc38643b84.png)

**Comment by AireagoirSteam** [comment]
Just wondering how hard implementing the hide game option.

As for a feature request would be cool if the game list could have 3d overflow like hexaflow for the vita. Or even a bit more 3d boxes.
Could even ad and option for it or have it work like a theme?

**Comment by andercard0** [comment]
> Just wondering how hard implementing the hide game option.
> 
> As for a feature request would be cool if the game list could have 3d overflow like hexaflow for the vita. Or even a bit more 3d boxes.
> Could even ad and option for it or have it work like a theme?

3D boxes like this ? 

![image](https://user-images.githubusercontent.com/43047877/109405343-6bec7280-794e-11eb-82bb-c621dfe9f9b6.png)

**Comment by AireagoirSteam** [comment]
@andercard0 like what you put bit also like this.

![screen_02](https://user-images.githubusercontent.com/22620774/109405479-c7c3f500-7968-11eb-9df8-c7bebf4dea3d.jpg)

Having both as an option would be a great way to display game lists.

**Comment by AireagoirSteam** [comment]
Another cool option if not already implemented would be game manual support. But not sure quite how that could be implimented

**Comment by foxsevent** [comment]
> Another cool option if not already implemented would be game manual support. But not sure quite how that could be implimented

That would be a nice feature if not for one tiny little problem, to my knowledge there is no database that has complete scans for all the PS1 games.
Even Sony official PS1 digital releases most often don't have the manuals.

If such database does exist please let me know.

**Comment by fefo-dev** [comment]
Standard request for every touchscreen interface: Snap move/resize buttons.

Last time I asked this to PPSSPP they made so you can manually adjust the snap grid, with a numeric field for ease of use. A nifty example.

**Comment by HeyItsLollie** [comment]
> If such database does exist please let me know.

For what it's worth, there's a couple collections on Archive.org. Far from complete, but still several hundred manuals available.
1. https://archive.org/details/playstationmanuals?&sort=titleSorter
2. https://archive.org/details/SonyPlaystationManuals

**Comment by Pycur** [comment]
For Automatic download of box art in game list you can use this site: http://psxdatacenter.com
There are almost every psx game has a cover and some screenshot named by the release number like SLUS-01248.
Here's a link:
http://psxdatacenter.com/images/covers/U/0-9/SCUS-94231.jpg
Try to get a link list or a mirror from it's owner.

----

I also made some thinking about the gui to show the covers and some screenshots...
Is there any way to place a nice option enabled sidebar to the right where I can see a cover and some screenshots from the game in the main window? (if I have them of course)

I mean to look like this:
https://i.postimg.cc/TwbXPBWM/duckstation.jpg
It would be more nice to see a game list with pictures.
Displayed pictures are assumed from the selected file's fully similar name+other characters, to be able to differ them, like bugs bunny.iso->bugs bunny.frontcover.jpg and bugs bunny.screenshot1.jpg, and so on... :)

Thank you!

**Comment by PookaMustard** [comment]
The developer is not implementing automatic box art download due to possible copyright shenanigans. At this point, it's better off for you to prove in court that box arts belong under fair use or are exempt of copyright.

There are hundreds of sources of box arts that you can download, throw into the covers folder for duckstation, and just forget about it.

**Comment by Pycur** [comment]
Ok, maybe not automated, but what about the option to view them like on my pic? I know it has a cover gallery option, but that only allows 1 picture, and it would be nice to see some ingame screens and eg. title screen... :)
Aaaand not by any force. I it's ok, then ok, if not then that ok too.

**Comment by Daisouji** [comment]
Being able to save the resize and the position of the NoGUI client window.

**Comment by AireagoirSteam** [comment]
Being able to hide duplicate supported game files.

**Comment by dankcushions** [comment]
Hotkey combos for controller buttons. Eg:
```
OpenQuickMenu = Controller0/Button5+Button3
```
this makes things better in a controller-only environment (eg, Retropie), where you don't have spare buttons for hotkey functions.

Also, ability to exit, load, and save states via a hotkey (probably a bit useless until combos are implemented)

**Comment by Pycur** [comment]
Is it acceptable, to ask for an "export game list to file" like csv with QT's list?
I mean id, name, filename, size, etc/row...
I found the database file in the cache but it's only readable by eyes, not for softwares...
Thanks!

**Comment by Starmann** [comment]
Make the bios a per-region setting so that you can select the exact version.

Eg:

```
NTSC = "C:\Something\NTSC-1.0.bin"
PAL = "C:\Something\PAL-1.1.bin"
```

**Comment by stenzek** [comment]
> Make the bios a per-region setting so that you can select the exact version.

Uhh, this is already the case? See BIOS settings...

**Comment by hamara47** [comment]
An option for changing audio output device would be neat.

**Comment by dftf-stu** [comment]
> Make the bios a per-region setting so that you can select the exact version.

Put all your ".BIN" BIOS files into one folder, then go to Settings > "BIOS Settings...", click the [Browse...] button in the "BIOS Directory" area, browse to the folder you put all the BIOS files in, then click [Select Folder].  Then set each of the three dropdowns at the top to the relevant BIOS file for that area.

Then go to "Console Settings" on the left and set the "Region" dropdown at the top to "Auto-Detect"

**Comment by dftf-stu** [comment]
> Reposting a UX/UI suggestion that originated in #1013, and expanding upon it based on a couple older suggestions in this thread

I love the re-ordered layout of the controller-buttons on the right -- makes much-more logical-sense to-me to put the buttons that are on the left-side of the controller in the left column, and those on the right in the right column!

**Comment by foxsevent** [comment]
If possible could we get a "hotkeys" section in Big Duck mode, so you could ad more options like the newly added toggle for CPU OC and memory card swapping without cluttering the main menu.

**Comment by Shockwave508** [comment]
Would it be possible to show the number of achievements completed, versus the amount of them supplied by Retro Achievements, where applicable?

Something like "4/50 Achievements", optionally with the images of the five most recently attained, if there's some screen space left over?

**Comment by AM-PM** [comment]
Would it be possible for DuckStation to ignore the screen saver dimming rules as it usually happens when a person's computer prepares to go to sleep?

**Comment by SecularSteve** [comment]
I've been thinking of giving all of the current icons a "Flat Theme" in the View Menu of the Qt UI from scratch.
Something similar to what Dolphin looks like.

Does anyone have the SVGs of all of the original icons currently used in "duckstation/src/duckstation-qt/resources/"?

**Comment by andercard0** [comment]
> I've been thinking of giving all of the current icons a "Flat Theme" in the Settings of the Qt UI from scratch.
> Something similar to what Dolphin looks like.
> 
> https://dolphin-emu.org/m/user/blog/progress-report/2018-january/QtMain_thumb.png
> 
> Does anyone have the SVGs of all of the original icons currently used in "duckstation/src/duckstation-qt/resources/"?

Interesting, I'm doing those **right now** something as follows: 
![image](https://user-images.githubusercontent.com/43047877/124978843-a9ea5900-e008-11eb-9ddd-647de9656c7e.png)

I'm kinda stuck with the BIOS one and others in which I wasn't capable of finish 😆if you want join our discord so we can chat about it or you can handle it if you have time ofc. those icons iirc are only free JPGs that Stenzek use.

**Comment by SecularSteve** [comment]
I'm there already.

**Comment by stenzek** [comment]
> Does anyone have the SVGs of all of the original icons currently used in "duckstation/src/duckstation-qt/resources/"?

Almost all are from the public domain Tango icon set: https://commons.wikimedia.org/wiki/Tango_icons

**Comment by olsongleb** [comment]
Add hotkey F5 to update the list. 
![изображение](https://user-images.githubusercontent.com/71244842/129015367-927b484b-0baa-46dc-9701-010d9dfedd29.png)

Hopefully this is not a duplicate. there was nothing on the text search "f5"

**Comment by bmsuseluda** [comment]
I couldn't find an option to save game specific settings in the nogui frontend. I think this would be an awesome feature.
Thanks for the great work.

**Comment by CS-PRO1** [comment]
Hey I'm on Android, I don't have a controller so I'm using touchscren input.
I couldn't find any option to add r3 and l3 as independent buttons. Nor I could find how they work with the current dual analog pad touchscreen options
Could you please either tell me what I'm missing here? Or maybe add r3 and l3 as separate buttons?
Thanks in advance..

**Comment by Basmurd** [comment]
It would be nice to add a hard FPS limiter for games, so that when the CPU frequency increases, the game does not fly away at 120 FPS, as Chrono Cross does. Vertical synchronization and other limiters do not help. Adding 4 FPS modes 25, 30, 50 and 60, so that even when overclocking, you can control the speed, it would help a lot. Emulation Speed does not help in this case, since the game slows down, you can add an option here.

**Comment by SecularSteve** [comment]
The new UI looks awful on 125% scaling.

![image](https://user-images.githubusercontent.com/33793273/132635655-6e50f6fe-815f-4f3e-80ef-5109ff22e78e.png)

Is this solvable?

**Comment by SecularSteve** [comment]
> 
> 
> It would be nice to add a hard FPS limiter for games, so that when the CPU frequency increases, the game does not fly away at 120 FPS, as Chrono Cross does. It would also help to play Spider Man normally. Vertical synchronization and other limiters do not help. Adding 4 FPS modes 25, 30, 50 and 60, so that even when overclocking, you can control the speed, it would help a lot. Emulation Speed does not help in this case, since the game slows down, you can add an option here. Or the FPS limit by region + the option of a half frame rate.

This could prove really useful for games like "Need For Speed 3 - Hot Pursuit".

I've only tested this on the PAL version, but overclocking to 300% gets the game to run at a maximum framerate of 65 FPS during gameplay, which seems to be where the developers capped it.

It's not that it feels weird, but the game would feel more natural if I could cap it at 30 for example.

**Comment by SecularSteve** [comment]
I noticed that @stenzek missed a spot in the BIOS menu when he replaced the Icons in the UI for a flatter, and nicer looking theme:

![glass](https://user-images.githubusercontent.com/33793273/133851138-94e5777f-2fb3-461d-8190-e8a13bed1a82.PNG)

So I made one of my own in a literal minute:

![search](https://user-images.githubusercontent.com/33793273/133852679-04088eb9-8272-466c-bfab-cce2085e4ab9.png)

ZIP contains both the SVG and PNG, both under the CC BY-SA 4.0

[search.zip](https://github.com/stenzek/duckstation/files/7188404/search.zip)

**Comment by andercard0** [comment]
> 
> 
> I noticed that @stenzek missed a spot in the BIOS menu when he replaced the Icons in the UI for a flatter, and nicer looking theme:
> 
> ![glass](https://user-images.githubusercontent.com/33793273/133851138-94e5777f-2fb3-461d-8190-e8a13bed1a82.PNG)
> 
> So I made one on my own in a literal minute:
> 
> ![search](https://user-images.githubusercontent.com/33793273/133852679-04088eb9-8272-466c-bfab-cce2085e4ab9.png)
> 
> ZIP contains both the SVG and PNG, both under the CC BY-SA 4.0
> 
> [search.zip](https://github.com/stenzek/duckstation/files/7188404/search.zip)

I left a bunch of icons away don't worry, I'll add some of 'em soon.

**Comment by qurious-pixel** [comment]
![image](https://user-images.githubusercontent.com/62252937/138577581-088f6a3c-6050-4d5f-b067-627d0e2ff405.png)

`QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=3 ./duckstation-qt-x64.AppImage`

icons and text scaled together. notice the title.

**Comment by stenzek** [comment]
Mostly implemented these days.
