### ISSUE TITLE
Crusader- No Remorse (USA) load screen graphical error

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#365]
During the load screens in Crusader- No Remorse, there's always some sort of flickering garbage in the top left of the graphic. This does not occur on real hardware. Happens on both software and opengl.
![image](https://user-images.githubusercontent.com/50224630/80518808-d81bd580-893b-11ea-8957-27c6c0dc846f.png)

**Comment by kurayami6** [comment]
I reported this weeks ago. Before you report an issue, try typing it into the search bar and seeing if someone has already reported it.

**Comment by HeroponRikiBestest** [comment]
sorry, my bad.
