### ISSUE TITLE
Army Men - Sarge's Heroes (USA) unusually long load times

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#366]
The loading screen slows down a lot at about this point.
![image](https://user-images.githubusercontent.com/50224630/80519137-6001df80-893c-11ea-82e2-3c7146761836.png)
On real hardware it takes about 20-25 seconds to load, it can take up to 2 minutes in duckstation.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/f856a8ad65de2f1ebac34272dc081a53ea0df692

**Comment by jackdroido** [comment]
Yep, seems good now !

**Comment by DarkFrost89** [comment]
Army Men - World War - Team Assault [U] [SLUS-01435] Has Fixed too :D
