### ISSUE TITLE
BIOS screen doesn't fade out properly in King's Field (USA)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#369]
Instead the text spazzes out and jumps around the screen. Happens with all renderers. 

![Capture](https://user-images.githubusercontent.com/31968468/80543504-563ab380-89f2-11ea-9312-e9bb5c7891ed.PNG)

**Comment by stenzek** [comment]
This only happens for a couple of frames. Might be something to do with where the CRTC parameters are being latched.

**Comment by ggrtk** [comment]
Fixed as of 6bc7cf2.

**Comment by stenzek** [comment]
Fantastic!
