### ISSUE TITLE
Choosing the link cable option in Metal Jacket (Japan) crashes the game

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#370]
Now obviously there is no cable inserted and it won't work but I'm sure that wouldn't crash the game on a real console. It'd probably either show an error message saying there's no cable inserted or do nothing. 

![2020-04-29_09-24-37](https://user-images.githubusercontent.com/31968468/80549385-71acbb00-8a00-11ea-984f-7f9b9e6657b7.png)

**Comment by stenzek** [comment]
Are you sure about this? It might not have a timeout and just wait indefinitely until another console connects.

**Comment by stenzek** [comment]
I think this might be the case. Looking at the disassembly I can't see any obvious counter, it's just polling `SIO_STAT` and waiting until `DSR` and `CTS` go high. If another console was connected, this would happen after the intros.

Happy to investigate more if you can show it behaving differently on console, but with the information I have at the moment I think think this is invalid.
