### ISSUE TITLE
Sound effects will sometimes get stuck in an endless loop in Re-Loaded - The Hardcore Sequel (USA)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#373]
When you kill an enemy sometimes the sound of him exploding and screaming will loop endlessly.

[SLUS-00382_2020-04-29_15-13-35.zip](https://github.com/stenzek/duckstation/files/4549877/SLUS-00382_2020-04-29_15-13-35.zip)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/1b618b8c46407ba20ae55c633786fe0651584960
