### ISSUE TITLE
Players move way too fast in NBA Jam Extreme (USA)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#374]
Everything else is fine. The framerate, the announcer, the music etc... It's just the players move around the court like they're on fast forward. 

![SLUS-00388_2020-04-29_15-55-09](https://user-images.githubusercontent.com/31968468/80564938-9588f480-8a32-11ea-8d02-f610aaca95ac.png)

**Comment by stenzek** [comment]
Looks like it's not vsyncing.

It does use the dot clock timer which currently not implemented, first game I've seen which does. Might be related.

**Comment by kurayami6** [comment]
WCW Nitro (USA) might have the same problem.

![SLUS-00397_2020-05-06_14-50-59](https://user-images.githubusercontent.com/31968468/81139661-ddb39400-8fa9-11ea-89ab-c133271f8169.png)

**Comment by kurayami6** [comment]
WCW-nWo Thunder (USA) has the same problem.

![SLUS-00779_2020-05-19_02-36-00](https://user-images.githubusercontent.com/31968468/82237847-a6fe5600-9979-11ea-84e9-136e81fb98de.png)

**Comment by kurayami6** [comment]
Total NBA '97 (Europe) has the same problem.

![SCES-00623_2020-05-28_06-14-35](https://user-images.githubusercontent.com/31968468/83067749-8dac8680-a0aa-11ea-8b63-75224ae4df4c.png)

**Comment by stenzek** [comment]
Original game is fixed with icache, was added a while back.
