### ISSUE TITLE
FIFA - Road to World Cup 98 (USA) hangs after the first screen

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#375]
![SLUS-00520_2020-04-29_16-07-20](https://user-images.githubusercontent.com/31968468/80565314-88b8d080-8a33-11ea-9ae5-256d764d072a.png)

![Capture](https://user-images.githubusercontent.com/31968468/80565345-92dacf00-8a33-11ea-822f-7d7c6da48f26.PNG)

**Comment by stenzek** [comment]
Please re-test on latest build.

**Comment by kurayami6** [comment]
Fixed
