### ISSUE TITLE
Sarcophagus texture is broken in Disney's Atlantis (USA) when upscaling OpenGL and D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#377]
OpenGL and D3D11

![SCUS-94636_2020-04-30_05-27-54](https://user-images.githubusercontent.com/31968468/80638597-09171a00-8aa4-11ea-88f8-282e50cb8507.png)

Software

![Capture](https://user-images.githubusercontent.com/31968468/80638633-17fdcc80-8aa4-11ea-8d61-4424335f9fa0.PNG)

**Comment by stenzek** [comment]
Merged with #427.
