### ISSUE TITLE
Team Buddies (USA) has slow loading times, and stays stuck on top of that

### ISSUE THREAD

**Issue by TheArcadeStriker** [stenzek/duckstation#378]
![image](https://user-images.githubusercontent.com/24653951/80639801-830dbb80-8a30-11ea-9100-654cfa2e1b9b.png)
Build used is 0.1-774-g5a1b008
Plays the FMV intros fine, but on this first loading screen, not only it takes around 2 minutes to fill the bar, but also it stays stuck there even when the bar is filled.

**Comment by jpchow26** [comment]
#366 also logged for slow loading times

**Comment by stenzek** [comment]
I looked into Army Men, not exactly sure what it's waiting for.. it's not in a loop waiting for some event from hardware, so it might be interrupt related.

These might share the same issue.

#182 also has a loading time problem on startup, but that's got something to do with memory cards.

**Comment by TheArcadeStriker** [comment]
Checked in 0.1-841-g777809b and the loading issue is gone! Game works great!
This can be closed now.
