### ISSUE TITLE
game list dont stay avalaible in sdl mode

### ISSUE THREAD

**Issue by mrdeathjr28** [stenzek/duckstation#38]
hi

game list dont stay avalaible in sdl mode, game list stay avalaible in qt mode

thanks

**Comment by stenzek** [comment]
This is intentional. The SDL frontend is meant to be as simple as possible. Actually, the reason I switched to Qt in the first place was because it would've been too complex/ugly to implement the game list in imgui, at least with the amount of time I wanted to spend on it.
