### ISSUE TITLE
First level of Frogger (USA) drops to between 0 and 1 FPS

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#380]
Pick retro level 1.

![SLUS-00506_2020-04-30_11-35-04](https://user-images.githubusercontent.com/31968468/80663327-0255ca80-8ad7-11ea-981a-c68ccdd6a9ca.png)

Then try jumping across the road and the framerate will start fluctuating between 0, 1 and 30.

![Capture](https://user-images.githubusercontent.com/31968468/80663380-2d401e80-8ad7-11ea-8ecc-a087acae7de1.PNG)

**Comment by stenzek** [comment]
Please re-test on latest build.

**Comment by kurayami6** [comment]
Fixed.
