### ISSUE TITLE
Music is distorted in Alone in the Dark - The New Nightmare (USA) (Disc 1)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#381]
Title screen music

[SLUS-01201_2020-05-01_07-30-28.zip](https://github.com/stenzek/duckstation/files/4561539/SLUS-01201_2020-05-01_07-30-28.zip)

Hallway music when you leave the first room in Aline's story.

[SLUS-01201_2020-05-01_07-35-54.zip](https://github.com/stenzek/duckstation/files/4561562/SLUS-01201_2020-05-01_07-35-54.zip)

Also after you choose your character and the narrator says "Alone in the dark" there's a faint popping noise. Probably unrelated but I'll mention it anyway.

[SLUS-01201_2020-05-01_07-38-15.zip](https://github.com/stenzek/duckstation/files/4561580/SLUS-01201_2020-05-01_07-38-15.zip)

**Comment by RazielZnot** [comment]
There is no distortion, this is the artistic choice of the composer.

**Comment by kurayami6** [comment]
@RazielZnot If you can prove that it sounds like that on real hardware I'll close this.

**Comment by RazielZnot** [comment]
@kurayami6 prove? I owe you nothing, dude, even though, I do have the game and real hardware. This game sounds like it should and whether you believe in it or not it's a matter of wasting developer's and other people's time.

**Comment by kurayami6** [comment]
@RazielZnot Well I'm obviously just going to take your word for it. This issue will stay open until there's proof of what it's supposed to sound like.

**Comment by stenzek** [comment]
Quick look at the waveform doesn't show any obvious clipping, although the right channel is substantially louder than the left.

I searched for some videos and it seems like @RazielZnot might be correct - it sounds pretty similar there. As far as I'm concerned I can't see any evidence that this is a bug, but happy to reconsider.

**Comment by kurayami6** [comment]
@stenzek I wouldn't trust random videos on the internet since they'd all be emulator footage and given the state of PS1 emulation it's possible no emulator handles the game correctly. I'll close this though. Thanks for checking.

**Comment by stenzek** [comment]
Yes, indeed. Hence why I said *might be correct*.

If the footage looks very good/clean/free of composite artifacts, it's probably from an emulator. I've found speedrun to be a good source though, since they're usually run on console.

**Comment by stenzek** [comment]
For what it's worth, this one looks pretty conclusive: https://www.youtube.com/watch?v=97A9TfuD-PY
