### ISSUE TITLE
Analog mode not enabling in some games

### ISSUE THREAD

**Issue by stuken** [stenzek/duckstation#382]
Change d04b252962f7dd2400ab1c7f8b692c98081275bb has caused some regression with enabling analog control in a few games. It might make sense to expose the analog button as a controller bind or UI switch.
Games where this is currently happening:

- Chrono Cross
- Grand Turismo 1 & 2
- Ridge Racer Type 4
- Wipeout 3 Special Edition

**Comment by stenzek** [comment]
Thanks for bisecting.

Should these games switch to analog mode automatically, or do they require manual activation? Because for the latter, yeah, exposing the button would be the only way.

The DualShock is sadly quite underdocumented - I've been meaning to write some tests to figure out exactly what some of the commands are supposed to do.

**Comment by stuken** [comment]
My memories of the behavior on real hardware are hazy, the only ones I can say with certainty is both Gran Turismo games definitely did automatically enable the analog on the dual shock.

**Comment by stenzek** [comment]
All good :) I'll poke around and see if there's some other command which should switch the mode which it's missing.

**Comment by ToppestOfDogs** [comment]
Crash 2, Metal Gear Solid, MGS VR Missions, Gex 2 and 3, and Croc are all also not working.
I don't know if any of those games require pressing the analog button, but having beetle-psx with analog on by default works.

**Comment by stenzek** [comment]
Thanks for the list. Will look into those when I have time. I'm considering adding the analog toggle button anyway :)

**Comment by stenzek** [comment]
I've added the analog toggle/lock functionality, so for these games which don't enable analog mode themselves, you should be able to toggle it on now.

Will look into making an auto-enable option as well.

FWIW, if you're running out of buttons and have a 360/XBox One pad and can't bind the guide button, follow these instructions: <https://github.com/AntiMicro/antimicro/issues/90#issuecomment-493733899>

**Comment by stenzek** [comment]
Merged with #362.
