### ISSUE TITLE
Glitchy line on the first screen of Iron Man & X-O Manowar in Heavy Metal (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#383]
On the right hand side of the screen. This seems to only happen at native resolution. Changing crop modes doesn't hide it.

Software

![Capture](https://user-images.githubusercontent.com/31968468/80817650-32a38300-8c15-11ea-9d45-d45e3131c400.PNG)

OpenGL

![Capture3](https://user-images.githubusercontent.com/31968468/80817704-4bac3400-8c15-11ea-9aeb-199bf436b0b0.PNG)

D3D11

![Capture2](https://user-images.githubusercontent.com/31968468/80817783-70a0a700-8c15-11ea-8c59-f5b17756ee7d.PNG)

**Comment by stenzek** [comment]
This may be fixed by https://github.com/stenzek/duckstation/commit/0ef0c36704c2ba79cd9c80e649c953c3fc0bfb5e

**Comment by kurayami6** [comment]
Not fixed unfortunately.

**Comment by stenzek** [comment]
I wonder if it's just filtering, since unless I'm blind I can't see any lines in the screenshots. Does it happen with "Linear Upscaling" disabled in GPU options?

**Comment by kurayami6** [comment]
Right side of the screen. Can you see it better now?

![Capture](https://user-images.githubusercontent.com/31968468/82142289-87cece00-987e-11ea-8443-fea2e8e6d53a.PNG)

**Comment by stenzek** [comment]
You didn't confirm whether linear upscaling affects it.

Regardless, I've pushed a change which fixes it in South Park, so it may change things here.

**Comment by kurayami6** [comment]
Seems to be fixed. Thanks.
