### ISSUE TITLE
Iznogoud (Europe) randomly pauses itself

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#384]
Maybe the game is self aware and trying to keep me from playing it because it's astoundingly awful. It works fine in Beetle PSX.

![SLES-00480_2020-05-02_14-34-17](https://user-images.githubusercontent.com/31968468/80855380-286c9d80-8c84-11ea-9006-6182a7c06e28.png)

**Comment by stenzek** [comment]
As in it's triggering the pause menu like the controller button is pushed, not freezing periodically?

**Comment by kurayami6** [comment]
Yeah the pause menu keeps randomly showing up.

**Comment by stenzek** [comment]
That sounds very strange. I wonder if it's controller related or something else. Does it behave the same with both the digital and analog controllers? Also try disconnecting the controller (setting it to none) while the game is running and see if it still happens.

**Comment by kurayami6** [comment]
Happens with both controller types. Doesn't happen if you just stand still. It happens while you're running and jumping around.

**Comment by kurayami6** [comment]
Fixed as of the latest version.
