### ISSUE TITLE
Teleporter sound effect is broken in Gex 3 - Deep Cover Gecko (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#385]
Specifically this one in Slappy Valley.

![SLUS-00806_2020-05-03_10-14-09](https://user-images.githubusercontent.com/31968468/80895418-117f8700-8d28-11ea-99b7-7d2cdc4904f0.png)

[SLUS-00806_2020-05-03_10-14-14.zip](https://github.com/stenzek/duckstation/files/4569381/SLUS-00806_2020-05-03_10-14-14.zip)

**Comment by stenzek** [comment]
Could be worth re-checking with the recent SPU clipping fixes.

**Comment by kurayami6** [comment]
Fixed.
