### ISSUE TITLE
Floor texture is broken in Batman Beyond - Return of the Joker (USA) when upscaling OpenGL and D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#388]
OpenGL and D3D11

![SLUS-01207_2020-05-04_12-46-35](https://user-images.githubusercontent.com/31968468/80933281-698cbb00-8e06-11ea-99ca-399ef2913afa.png)

Software

![Capture](https://user-images.githubusercontent.com/31968468/80933293-74dfe680-8e06-11ea-8041-81f857d90974.PNG)

**Comment by stenzek** [comment]
Merged with #427.
