### ISSUE TITLE
Question about performance in Disney's Goofy's Fun House (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#390]
The game runs pretty terribly. 15 FPS when standing still and as low as 7 when transitioning between rooms. Can anyone confirm whether or not it runs this bad on real hardware? If not are there any optimizations to the emulator that could make it run better?

![Capture](https://user-images.githubusercontent.com/31968468/80948198-fbabb800-8e34-11ea-9807-0e27db13266c.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/80948218-049c8980-8e35-11ea-8081-f719014299e7.PNG)

**Comment by stenzek** [comment]
I think this is invalid. See https://www.youtube.com/watch?v=ax4EE2ioz2M

(note that PSX-on-PS2 emulation is not completely faithful, the GPU is emulated, but the CPU runs at the same speed. But it's not going to be the difference between running at 15fps and 30fps)

**Comment by stenzek** [comment]
As for making it better, "overclocking" the CPU/GPU might help, but could also break things. Something to consider in the future.
