### ISSUE TITLE
Silent hill incorrect effects on loading screens

### ISSUE THREAD

**Issue by Basmurd** [stenzek/duckstation#391]
During loading, the character seems to be floating in a texture that does not disappear, but fills the limits of the character’s animation. Everything is fine during the game. Need to call ghostbusters? :)
![SLES-01514_2020-05-04_11-57-22](https://user-images.githubusercontent.com/61318181/80951125-e5cfd000-8dff-11ea-9d23-240974165b3f.png)
![SLES-01514_2020-05-04_11-57-23](https://user-images.githubusercontent.com/61318181/80951128-e7999380-8dff-11ea-8d58-fe15a6b485f8.png)
![SLES-01514_2020-05-04_11-57-26](https://user-images.githubusercontent.com/61318181/80951130-e8322a00-8dff-11ea-9482-865073afed57.png)

**Comment by stenzek** [comment]
Hah, yes, I noticed this and was meaning to look into it!

**Comment by stenzek** [comment]
This took me way too long to figure out... turns out it relies on the precision of the "old GPU model" in regards to gouraud shading. I might add an option to select the old/new behavior and when I eventually add per-game overrides, we can set it for Silent Hill.

Another alternative is to use true colour, the precision doesn't get lost in the first place so it works fine.

**Comment by stenzek** [comment]
For what it's worth, it breaks on newer consoles too, unless GDQ is running on an emulator ;) https://youtu.be/_u320GZ-_B8?t=673

When I get a chance I'll write a hardware test to confirm the behavior difference between the old/new GPUs.

**Comment by Basmurd** [comment]
It's pretty fun to watch the protagonist whisk the air around him into a dense cloud. Swam 100 meters in the air and loaded :)

**Comment by stenzek** [comment]
Fixed by https://github.com/stenzek/duckstation/commit/bf3c83658a6def84ce0d9a854cf4c74098bc9a24. Make sure you have true colour turned off, otherwise it'll still break.
