### ISSUE TITLE
Graphical glitch on the name entry screen of SuperLite 1500 Series - Emmyrea (Japan) when upscaling OpenGL and D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#394]
OpenGL and D3D11 at x4

![SLPM-87043_2020-05-05_15-41-03](https://user-images.githubusercontent.com/31968468/81037764-353cfb80-8ee7-11ea-9e79-cdeb329b45e1.png)

Software

![SLPM-87043_2020-05-05_15-41-48](https://user-images.githubusercontent.com/31968468/81037778-3ff79080-8ee7-11ea-9e0d-c3fcf5f6cfe5.png)

**Comment by stenzek** [comment]
Merged with #427.
