### ISSUE TITLE
Graphical garbage during screen transitions in NASCAR Thunder 2004 (USA)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#396]
Happens with all renderers. 

![Capture](https://user-images.githubusercontent.com/31968468/81044217-3f66f600-8ef7-11ea-8ab2-dae1d0079a5f.PNG)

**Comment by kurayami6** [comment]
True Love Story - Remember My Heart (Japan) has the same problem after the first cutscene. 

![SLPS-01151_2020-06-03_14-43-05](https://user-images.githubusercontent.com/31968468/83599597-efd82080-a5af-11ea-92e1-693bd838ece3.png)

**Comment by kurayami6** [comment]
T kara Hajimaru Monogatari (Japan) has the same thing. After the opening FMV.

![SLPS-01350_2020-06-09_17-26-41](https://user-images.githubusercontent.com/31968468/84118879-f1558d00-aa76-11ea-8151-9fb4f260cc35.png)

**Comment by stenzek** [comment]
Footage I found online also seems to have this issue.
