### ISSUE TITLE
Pink line on the side of the screen during EA logo screen in NASCAR Thunder 2004 (USA) when using OpenGL and D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#397]
Happens at all resolutions with OpenGL and D3D11. Doesn't happen with software. 

![SLUS-01571_2020-05-05_17-33-42](https://user-images.githubusercontent.com/31968468/81044344-87861880-8ef7-11ea-8588-5f340ff399ef.png)

**Comment by stenzek** [comment]
Should be fixed in https://github.com/stenzek/duckstation/commit/2bc1c67236dd5ae467f167f69607b3a75bbabd99

**Comment by kurayami6** [comment]
Fixed.

**Comment by stenzek** [comment]
Actually, I don't think this fix was correct, and the software renderer was overcropping. The video is effectively 320x220, but with the overscan crop option crops one pixel on the left, which is where the pink line is coming from.

In 24-bit mode the GPU might handle the active range differently, resulting in this not being visible. I'll have to write a test and run it on my console.

**Comment by stenzek** [comment]
Fixed properly with https://github.com/stenzek/duckstation/commit/19cebd97da9a9681413ed555e5c36db3cb1685b6
