### ISSUE TITLE
Sound effect of kicking certain enemies is broken in Xena - Warrior Princess (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#399]
Spin kick this guy in the first level and you'll hear it. I hope they reboot this show and actually let Xena and Gabrielle be gay. Get Bruce Campbell back as well. 

![SLUS-00977_2020-05-06_01-27-05](https://user-images.githubusercontent.com/31968468/81084669-87a70800-8f39-11ea-89d5-3062f065e3fa.png)

[SLUS-00977_2020-05-06_01-27-10.zip](https://github.com/stenzek/duckstation/files/4581841/SLUS-00977_2020-05-06_01-27-10.zip)

**Comment by stenzek** [comment]
Is this still happening on the latest build?

**Comment by kurayami6** [comment]
Nah it's fixed now. Thanks.
