### ISSUE TITLE
[SLUS-00707] Silent Hill displaying sprites incorrectly in hardware renderers

### ISSUE THREAD

**Issue by JimiMonkey** [stenzek/duckstation#40]
I'm using the recompiler, but it happens with interpreters as well on every backend and settings that could test.

I have an i5-3570, RX 560 and 8GB DDR3 using latest drivers on Windows 10 1909

![Sem título](https://user-images.githubusercontent.com/31172426/75637817-6b1fe400-5c07-11ea-9018-41808d651860.jpg)

**Comment by stenzek** [comment]
Yeah.. I thought I fixed this at some point but it broke again. I believe fixing in the hardware backends is a little tricker due to how it uses the mask bit, but software shouldn't have an issue.

**Comment by JimiMonkey** [comment]
In software mode happens the same, also resolution upscaling doesn't work. It is not game breaking though

![Sem título2](https://user-images.githubusercontent.com/31172426/75638346-3b261000-5c0a-11ea-9a0a-2fcba441dd9b.jpg)

**Comment by stenzek** [comment]
Should be fixed in the software renderer on latest master. Hardware renderers are more complex, I need to think of a way to handle the mask bit check without falling back to software.

**Comment by stenzek** [comment]
Should be fixed as of https://github.com/stenzek/duckstation/commit/9446587e8fa7751b9977e7cdffe3a8f3b6d38d7c.
