### ISSUE TITLE
Upscaling doesn't effect characters in City Of Lost Children (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#402]
Is the game doing something fucked up that means the characters can't be upscaled? Are they not actually 3D models?

OpenGL at x4

![SCUS-94150_2020-05-06_17-25-38](https://user-images.githubusercontent.com/31968468/81148185-27f34000-8fbf-11ea-9f95-c5e7a72784c9.png)

Software

![Capture2](https://user-images.githubusercontent.com/31968468/81148207-317ca800-8fbf-11ea-981c-cba06c80bb9b.PNG)

**Comment by stenzek** [comment]
Possibly. Can you check the VRAM view?

**Comment by kurayami6** [comment]
Looks like she's upscaled in VRAM.

![SCUS-94150_2020-05-06_17-54-27](https://user-images.githubusercontent.com/31968468/81150104-b9b07c80-8fc2-11ea-974f-55bae7cec14e.png)

**Comment by stenzek** [comment]
That's really strange then. The only way it should be downscaling is if it is copying it to the CPU first, then using the mask bit to draw it "over the top". I really doubt it's rendering like this and it's probably more likely a bug, but I've seen games rendering in really silly ways before...

If you've used renderdoc before, could you capture a two frame trace and upload it?

**Comment by kurayami6** [comment]
I don't know how to do that, sorry. You'll have to do it.

**Comment by stenzek** [comment]
I don't have the game. But perhaps someone who does can capture a trace.

Alternatively, I was considering writing some sort of fifolog type system inspired by dolphin for capturing and replaying GPU commands. If I eventually do that you will be able to capture that way.

**Comment by stenzek** [comment]
I guess the other thing to check is the GPU debug window - see if the VRAM reads are fluctuating at all

**Comment by kurayami6** [comment]
You mean VRAM read texture updates? It's staying at 2. 

![Capture](https://user-images.githubusercontent.com/31968468/81154582-63920800-8fc7-11ea-8ae0-53659dfe8f4a.PNG)

**Comment by stenzek** [comment]
The fact that it's an idle frame means that the stats may not be correct, but the number of VRAM writes is a little high for an entirely GPU rendered scene.

Anyway, can investigate when I'm able to obtain a trace of what it's doing.

**Comment by stenzek** [comment]
Merged with #427.
