### ISSUE TITLE
Wu-Tang - Shaolin Style (USA) crashes with error message

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#406]
![Capture](https://user-images.githubusercontent.com/31968468/81290985-569b1480-90ac-11ea-8f88-b34db41ec755.PNG)

**Comment by jpchow26** [comment]
Something to do with Sub Channel data?

[   19.6665] W(CDROMAsyncReader::DoSectorRead): Read of LBA 282326 failed
Panic triggered: 'Sector read failed' in function CDROM::DoSectorRead (C:\Users\jchow.CP\source\GitHub\duckstation\src\core\cdrom.cpp:1454)

>	duckstation-qt-x64-ReleaseLTCG.exe!Y_OnPanicReached(const char * szMessage, const char * szFunction, const char * szFile, unsigned int uLine) Line 129	C++
 	duckstation-qt-x64-ReleaseLTCG.exe!CDROM::DoSectorRead() Line 1458	C++
 	[Inline Frame] duckstation-qt-x64-ReleaseLTCG.exe!std::_Func_class<void,int,int>::operator()(int <_Args_0>, int <_Args_1>) Line 969	C++
 	duckstation-qt-x64-ReleaseLTCG.exe!System::RunEvents() Line 997	C++
 	[Inline Frame] duckstation-qt-x64-ReleaseLTCG.exe!System::RunFrame() Line 518	C++
 	duckstation-qt-x64-ReleaseLTCG.exe!QtHostInterface::threadEntryPoint() Line 864	C++

**Comment by stenzek** [comment]
I think this would happen if it reads past the end of the disc.

I wonder if it's trying to play the last track and reaching the end, will have to check if that scenario is being correctly handled.

**Comment by stenzek** [comment]
Looking at redump's track listing, yeah, LBA 282326 (minus 75*2) puts it at 282176, exactly the end of the disc. I'll add a check for this in a bit, can see if that works.

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/ee9456e7669028ad0cbec17174c1f2dbf1e118c3. Completely untested, but in theory it should work...

**Comment by jpchow26** [comment]
resolved on 5b389ae

**Comment by stenzek** [comment]
Great, thank you for checking!
