### ISSUE TITLE
BIOS startup chime runs for too long/continues into games

### ISSUE THREAD

**Issue by stenzek** [stenzek/duckstation#407]
Re-posting the issue as I'm a goose and hijacked my other thread.

Known cases:
 - Disney's Hercules (USA)
 - Disney's Tarzan (USA)
 - Youkai Hana Asobi (Japan)
 - Wacky Races (Europe)
 - Quake 2
 - Aging Disc (Japan)
 - Shura no Mon (Japan)
 - and probably others.

More info:
 - https://github.com/stenzek/duckstation/issues/292
 - https://github.com/stenzek/duckstation/issues/342
 - https://github.com/stenzek/duckstation/issues/114

If anyone has these games on console and is equipped to create a recording of these starting up, I would very much appreciate it, since I don't have them. As I've stated in the other threads, something is completely undocumented here, or it is a side-effect of the faster booting in the emulator.

Otherwise, my plan is to start writing some test code to see what does and doesn't cause the reverb to mute. It's just.. not straightforward, because of the circumstances of the bug my usual method of running code doesn't apply (sideloading it via caetla), since that skips the intro entirely.

**Comment by HeroponRikiBestest** [comment]
Twinbee Taisen Puzzle-dama (Japan) also has this issue

**Comment by GitToTheHub** [comment]
I have the same issue in Croc - Legend of the Gobbos (Europe)
- Game-Code: SLES-00593
- Region: PAL
- Bios: SCPH7502 (PAL)
- DuckStation-Version: 0.1-1969-g671033fd (master)
I uploaded a Video that shows the issue on wetransfer.com: https://we.tl/t-NRjC8RLUuo (It's valid until 17. October 2020, filename: DuckStation 0.1-1969-g671033fd (master) 2020-10-10 22-13-12.mp4)

**Comment by stenzek** [comment]
Not actually a bug - happens on console too in games which don't properly reset the SPU on boot. Volume just depends on how long it takes for the shell to read the executable, this is closer to console in recent builds.
