### ISSUE TITLE
Rock 'Em Sock 'Em Robots Arena (USA) hangs after BIOS screen

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#408]
Hangs on a black screen. Turning on "Show VRAM" shows that it never gets past the BIOS.

![SLUS-01124_2020-05-08_13-54-33](https://user-images.githubusercontent.com/31968468/81368627-90fbc480-9133-11ea-853b-fc5af82002cd.png)

**Comment by stenzek** [comment]
Check the CD-ROM state. Is it stuck reading?

**Comment by kurayami6** [comment]
![Capture](https://user-images.githubusercontent.com/31968468/81369549-12545680-9136-11ea-95ed-9fb562c9923d.PNG)

**Comment by stenzek** [comment]
Okay, nothing obvious. Will need to debug the game itself then.

**Comment by kurayami6** [comment]
I just realized that both this game and X-Men Mutant Academy 1 and 2 which also instantly crash were all made by the same studio. I wonder if they share the same problem. 

![Capture](https://user-images.githubusercontent.com/31968468/81480090-b93a0f00-926a-11ea-8f07-0ab1112d7cde.PNG)

**Comment by stenzek** [comment]
Should be fixed in https://github.com/stenzek/duckstation/commit/65c42cd30e63fa185dd938b88c7b7b00ffacaa16

**Comment by kurayami6** [comment]
Fixed.
