### ISSUE TITLE
[Request] Per-game settings/overrides.

### ISSUE THREAD

**Issue by fenrir0054** [stenzek/duckstation#41]
I'd imagine this would be pretty low on the priority list at this point, but it would be nice to have support for loading different graphic and input settings for different games. When loading the game it could check for an ini file matching the game, and if found load with those settings instead. The file could be stored (by default at least) at .\overrides\SCUS-94221_override.ini for example. There could also be a menu entry such as Settings>Save game override which would automatically create said file with the current settings.

PPSSPP has a system similar to this, for reference.

**Comment by stenzek** [comment]
In an ideal world we wouldn't need per-game hacks :)

But for disabling problematic enhancements for specific games it could be an idea.

**Comment by fenrir0054** [comment]
Different configs wouldn't just be for different hacks needed to make games work (or not break others), but also for different input configurations for different games as well. And I don't know if there's any future plans for stuff like shaders/filters but those types of things tend to work well with some games and not well with others, just depending on what kind of visuals the game has. So even in an ideal world this would be a useful feature IMO.

**Comment by stenzek** [comment]
Yeah, that is a fair point.

Postprocessing would be nice but not a priority at the moment.

**Comment by Blackbird88** [comment]
Would also be nice for cheats (so we can use those widescreen patches https://forums.pcsx2.net/Thread-PSOne-Widescreen-Patches) and CPU overlocking if that eventually comes :)

**Comment by stenzek** [comment]
Was implemented a little while back.
