### ISSUE TITLE
Returning to title screen in Mortal_Kombat_-_Special_Forces_(May_11,_1999_prototype) completely breaks graphics and framerate

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#410]
Die and then choose "EXIT TO TITLE " The graphics will become a broken mess and the framerate will drop to 1 FPS. Works fine in Beetle PSX.

![2020-05-08_18-31-00](https://user-images.githubusercontent.com/31968468/81387672-68d38c00-915a-11ea-8db1-15300c968ec9.png)

![2020-05-08_17-57-08](https://user-images.githubusercontent.com/31968468/81387694-71c45d80-915a-11ea-9005-3be2f9d7f11b.png)

**Comment by stenzek** [comment]
Could you please merge these issues into one thread per game? It makes it easier to keep track of.

**Comment by kurayami6** [comment]
@stenzek Sure. By the way, this issue looks similar to the one in Treasure Planet. I wonder if fixing it would fix both games.

**Comment by kurayami6** [comment]
Health bar is glitched when using OpenGL and D3D11.

OpenGL and D3D11 at x1

![81386948-383f2280-9159-11ea-9fbc-25f8d96ba54b](https://user-images.githubusercontent.com/31968468/81392421-fd8db800-9161-11ea-90ee-74fc4808a8cd.PNG)

OpenGL and D3D11 at x4

![81386997-4db44c80-9159-11ea-945c-e8fe53a8645a](https://user-images.githubusercontent.com/31968468/81392446-0aaaa700-9162-11ea-9661-90506134c9eb.png)

Software

![81387043-60c71c80-9159-11ea-9e84-da1fa8db5a13](https://user-images.githubusercontent.com/31968468/81392501-1eeea400-9162-11ea-9b8a-ff5f66d429f0.PNG)

**Comment by stenzek** [comment]
Fixing prototypes are outside the scope of the project.

**Comment by forz0i** [comment]
x3 720p  fix the title  in D3D11
Plase active Use Debug device in d3d11 not work ?

Le mar. 4 août 2020 à 11:31, Connor McLaughlin <notifications@github.com> a
écrit :
