### ISSUE TITLE
Audio clipping in Monkey Magic (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#411]
I tested this game months ago and it was fine so this must be a regression.

[SLUS-00930_2020-05-08_19-06-49 (2).zip](https://github.com/stenzek/duckstation/files/4598114/SLUS-00930_2020-05-08_19-06-49.2.zip)

[SLUS-00930_2020-05-08_19-11-29.zip](https://github.com/stenzek/duckstation/files/4598110/SLUS-00930_2020-05-08_19-11-29.zip)

**Comment by stenzek** [comment]
Any idea how long ago it was working? There's been numerous changes since then, a bisect would be appreciated.

**Comment by kurayami6** [comment]
I last tested it on March 12.

**Comment by stenzek** [comment]
Do you know to bisect? If you're building locally, it's pretty straightforward (`git bisect start`, `git bisect bad`, `git bisect good <hash of the last working commit>`, then build/test and `git bisect bad` or `git bisect good` depending on whether it's broken.

Otherwise pick a date halfway inbetween the last working build and the broken build, check that build, and repeat with the upper-lower half until you find the build which broke it.

**Comment by stenzek** [comment]
This kind-of sounds like the error I was hearing in Valkyrie Profile. Will update here when I look into/fix that as it may have the same cause.

**Comment by stenzek** [comment]
Valkyrie Profile issue is caused by https://github.com/stenzek/duckstation/commit/08ad5aad5322c8ebd1d68330408a4f979b4df474 (interrupt fires too early). So try https://github.com/stenzek/duckstation/commit/54abd37daa726dd95ba56a0fb0b5b60a7f493d91  (https://ci.appveyor.com/project/stenzek/duckstation/builds/31711711)

**Comment by kurayami6** [comment]
It sounds better in that build but still not correct.

[SLUS-00930_2020-05-08_20-11-35.zip](https://github.com/stenzek/duckstation/files/4598386/SLUS-00930_2020-05-08_20-11-35.zip)

**Comment by stenzek** [comment]
Check the SPU debug window. Do you see the interrupt value enabled at any point during the broken voice? (I'm still trying to work out if this is a related issue or not)

**Comment by kurayami6** [comment]
Yes it's enabled during the broken title screen music, the broken sound effect of the meteorite crashing at the beginning of the level and when Monkey and the bat talk in their broken voices. 

![Capture](https://user-images.githubusercontent.com/31968468/81400668-046ff700-9171-11ea-810c-76e811c43e6a.PNG)

**Comment by stenzek** [comment]
Hmm, I'm not seeing any misaligned repeat addresses there (which is what's breaking Valkyrie Profile), but give the latest commit a try. Otherwise this is a different issue.

**Comment by kurayami6** [comment]
Still broken as of the latest version unfortunately. Must be a different issue. At leas you managed to fix a different game in the process though.

**Comment by stenzek** [comment]
I wouldn't be surprised if it was still interrupt timing related, just a different cause.

**Comment by stenzek** [comment]
Okay, nothing to do with interrupts, looks like a CD-ROM issue. Should be fixed by https://github.com/stenzek/duckstation/commit/37d9f6344dd58a9a490a853e50dde5ae2371d10d

**Comment by kurayami6** [comment]
Music, sound effects and voices are fixed. Game still suffers from really bad audio popping though. Want me to close this and make a separate issue?

[SLUS-00930_2020-05-11_23-20-57.zip](https://github.com/stenzek/duckstation/files/4609837/SLUS-00930_2020-05-11_23-20-57.zip)

**Comment by stenzek** [comment]
Probably a bug, but should be verified on console.

**Comment by kurayami6** [comment]
Didn't even need to waste a CD-R for this one. Just checked and the popping doesn't happen in Beetle PSX. I'm fairly sure it didn't used to happen in Duckstation either.

**Comment by stenzek** [comment]
![image](https://user-images.githubusercontent.com/11288319/81582494-78213680-93f3-11ea-8f45-38bdce223e89.png)

yeah this probably isn't normal.

**Comment by stenzek** [comment]
FWIW, you probably should be testing against Mednafen rather than Beetle, from what I've heard it's more buggy. But apart from borrowing the reverb algorithm from there I haven't looked at/used it enough enough of it to be able to really have much of an opinion.

**Comment by stenzek** [comment]
I edited your comment to remove the mention of piracy. This is the second time I've had to do this, and your last warning. While it might happen in the community and we can't really do much about it, to protect ourselves legally as emulator developers we can't facilitate it in any way.

**Comment by kurayami6** [comment]
@stenzek Jawohl, Mein fuhrer! I'll be on my best behaviour.

**Comment by stenzek** [comment]
Popping should be fixed in https://github.com/stenzek/duckstation/commit/634880b5e3f6dd96e277e3b163946e77979570af.

**Comment by kurayami6** [comment]
All the popping in game is gone but I've noticed I can still here it faintly If I press start to skip the opening logos and videos. This might be within normal parameters and not a bug though. Listen carefully at the 3, 8, 12, 17, 20 and 27 second marks. 

[SLUS-00930_2020-05-12_02-37-49.zip](https://github.com/stenzek/duckstation/files/4610952/SLUS-00930_2020-05-12_02-37-49.zip)

**Comment by stenzek** [comment]
I think the game is just very loud and sounds muffled.

**Comment by stenzek** [comment]
Try with https://github.com/stenzek/duckstation/commit/d866bd9cb81ef441ddad329de3ce5b1cc33b0dd6

**Comment by kurayami6** [comment]
Popping is fixed. The game also breaks when upscaled but since you're already aware of that issue I'll close this. 

![SLUS-00930_2020-05-12_14-18-27](https://user-images.githubusercontent.com/31968468/81638477-b0109400-945c-11ea-89aa-28cb50c9afa7.png)

![SLUS-00930_2020-05-12_14-12-34](https://user-images.githubusercontent.com/31968468/81638490-b999fc00-945c-11ea-91ba-5d0ca7126006.png)

![SLUS-00930_2020-05-12_14-20-01](https://user-images.githubusercontent.com/31968468/81638507-c4549100-945c-11ea-88ee-3f59ce3c88e6.png)
