### ISSUE TITLE
Dark texture is incorrectly applied to main character in Monkey Hero

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#412]
In the first level the texture of being in darkness is applied at all times, even when in light. Happens with all renderers. 

![SLUS-00765_2020-05-09_01-32-31](https://user-images.githubusercontent.com/31968468/81421848-7b1eeb80-9195-11ea-96a5-ed40ae3cf9f4.png)

Here it is on real hardware. Sorry for the quality.

![IMG_20200509_012658](https://user-images.githubusercontent.com/31968468/81421904-938f0600-9195-11ea-91d1-2bdd9c1df9a7.jpg)

**Comment by stenzek** [comment]
Gosh damn Monkey Hero.. at least it boots and the sound works..

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/f65651823e5d09020290c113115df2b61e1739dd
