### ISSUE TITLE
Certain characters aren't being upscaled in Madden NFL 99 (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#413]
This is OpenGL at x4. See how the players on the far left and far right are upscaled while the rest aren't?

![SLUS-00729_2020-05-09_19-38-34](https://user-images.githubusercontent.com/31968468/81470248-275fe100-922d-11ea-8a52-25e745049a1a.png)

**Comment by heckez-sys** [comment]
2 close to the cam? idk

**Comment by stenzek** [comment]
Looks like it's because the characters are being drawn offscreen and then rendered as a sprite.

The fix will be applying the resolution scale in the vertex shader instead of the fragment shader, post-interpolation. Hopefully it won't regress anything...

**Comment by stenzek** [comment]
Merged with #427.
