### ISSUE TITLE
Flickering bar at the top of the screen during the opening logo in Hajime no Ippo - The Fighting! (Japan)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#414]
Happens with all crop modes and all renderers. Doesn't happen in Beetle PSX.

![SLPS-00945_2020-05-09_21-21-05](https://user-images.githubusercontent.com/31968468/81472421-52513180-923b-11ea-9729-c9ac78610852.png)

**Comment by stenzek** [comment]
Probably MDEC related.

**Comment by kurayami6** [comment]
Still happens as of the latest version.

**Comment by stenzek** [comment]
Fixed with the latest round of MDEC changes.
