### ISSUE TITLE
Purple pixels on cards in Gunfighter - The Legend of Jesse James (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#415]
Possibly the same issue as the level select screen in Atlantis The Lost Empire and the bush in the opening cutscene of Lucky Luke - Western Fever. 

![SLUS-01398_2020-05-09_21-27-08](https://user-images.githubusercontent.com/31968468/81472565-4dd94880-923c-11ea-963c-ad1b8c91769d.png)

![79989865-b235a180-84f3-11ea-9225-233181c60a1b](https://user-images.githubusercontent.com/31968468/81472614-98f35b80-923c-11ea-901e-0b8258b4cf92.png)

![SLES-03530_2020-05-09_21-34-31](https://user-images.githubusercontent.com/31968468/81472656-e8d22280-923c-11ea-88ff-901d8ae4cc81.png)

**Comment by stenzek** [comment]
Have you verified this on console? I believe the Atlantis one at least was present on there.

**Comment by kurayami6** [comment]
You were right. I just checked and this happens on my real PS1 as well. I'll check Atlantis and Lucky Luke as well. 

![IMG_20200509_230546](https://user-images.githubusercontent.com/31968468/81474728-af081880-924a-11ea-87c1-2c76663d33b5.jpg)

**Comment by stenzek** [comment]
Great, thank you for checking on console. Much appreciated.
