### ISSUE TITLE
No music in R-Type Delta when going underwater

### ISSUE THREAD

**Issue by picili** [stenzek/duckstation#416]
In R-Type Delta (US version) level 2, when going under water, level music is supposed to change. Currently (v1.0.281) sound effects are still working but music stops.

**Comment by stenzek** [comment]
Thanks for the report! Should be fixed by https://github.com/stenzek/duckstation/commit/777809b3b08a49099677fd2ae0deb8fed42a5f34. If it is still broken, please let me know.
