### ISSUE TITLE
Balls are broken in Ultimate 8 Ball (USA) when upscaling D3D11 and at all resolutions with OpenGL

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#417]
OpenGL and D3D11 at x4

![SLUS-00864_2020-05-11_00-19-15](https://user-images.githubusercontent.com/31968468/81501919-37a3b900-931e-11ea-86c5-d5aec8209c34.png)

OpenGL at native resolution

![Capture2](https://user-images.githubusercontent.com/31968468/81501929-45593e80-931e-11ea-8a69-8713f380f515.PNG)

Software

![Capture](https://user-images.githubusercontent.com/31968468/81501937-4e4a1000-931e-11ea-93b2-eff3d894bca5.PNG)

**Comment by stenzek** [comment]
Not broken in Direct3D at 1x on latest build.
