### ISSUE TITLE
Certain words get cut off in Clock Tower II - The Struggle Within (USA)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#418]
Listen to how the "What" in "What was that" gets cut off. 

[SLUS-00695_2020-05-11_02-21-40.zip](https://github.com/stenzek/duckstation/files/4606079/SLUS-00695_2020-05-11_02-21-40.zip)

![SLUS-00695_2020-05-11_02-21-52](https://user-images.githubusercontent.com/31968468/81504797-a38e1d80-932e-11ea-8f70-ea6f0fd095b2.png)

**Comment by kurayami6** [comment]
World Soccer Winning Eleven (Japan) might have the same problem. Listen to how the I gets cut off in "Italy"

[SLPS-00272_2020-05-16_02-47-29.zip](https://github.com/stenzek/duckstation/files/4635876/SLPS-00272_2020-05-16_02-47-29.zip)

**Comment by kurayami6** [comment]
World Soccer Winning Eleven '97 (Japan) (v1.1) sounds like it has the same problem.

[SLPM-86035_2020-05-16_04-21-05.zip](https://github.com/stenzek/duckstation/files/4636388/SLPM-86035_2020-05-16_04-21-05.zip)

**Comment by stenzek** [comment]
Issue seems to be the game not setting the volume on the CD-ROM quickly enough, before it starts playing.

**Comment by kurayami6** [comment]
Warriors of Might and Magic (USA) has the same problem. Every time the tutorial voice speaks.

[SLUS-01204_2020-05-19_04-58-58.zip](https://github.com/stenzek/duckstation/files/4646136/SLUS-01204_2020-05-19_04-58-58.zip)

**Comment by kurayami6** [comment]
Zero Divide (USA) has the same problem.

[SLUS-00183_2020-05-18_00-20-21.zip](https://github.com/stenzek/duckstation/files/4647465/SLUS-00183_2020-05-18_00-20-21.zip)

**Comment by Shideravan** [comment]
I'm not the one best suited to check this, but at least in the Zero Divide (USA) the problems seems solved.

**Comment by stenzek** [comment]
Fixed with https://github.com/stenzek/duckstation/commit/67344070ea86944e8bb5f4bc11d04565bd533528
