### ISSUE TITLE
NBA Live 96 crashes due to unimplemented GP0 command

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#419]
![Capture](https://user-images.githubusercontent.com/31968468/81524626-382b6680-9395-11ea-803b-25dcb636b78d.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/81524632-3d88b100-9395-11ea-932a-30ead480b3fe.PNG)

**Comment by stenzek** [comment]
Was a DMA issue not GPU. Should be fixed in https://github.com/stenzek/duckstation/commit/7d887edf17dc4b9b749fd8962092564b158bbf38

**Comment by kurayami6** [comment]
Fixed.
