### ISSUE TITLE
Adidas Power Soccer (Europe) hangs on first loading screen

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#420]
![SLES-00189_2020-05-11_15-37-23](https://user-images.githubusercontent.com/31968468/81527361-5e550480-939d-11ea-8746-58c4fcec05b4.png)

![Capture](https://user-images.githubusercontent.com/31968468/81527250-1df58680-939d-11ea-9413-c545d087041e.PNG)

**Comment by stenzek** [comment]
Please re-test on latest build.
