### ISSUE TITLE
Pro Pinball - Fantastic Journey (USA) hangs after BIOS.

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#421]
Instantly hangs on a black screen after BIOS. Here's what it looks like with "Show VRAM" on.

![SLUS-01261_2020-05-11_22-07-38](https://user-images.githubusercontent.com/31968468/81560983-ce7f7c80-93d5-11ea-9699-44def1978b16.png)

When using the OpenGL renderer the log will spam this endlessly. 

![Capture](https://user-images.githubusercontent.com/31968468/81561039-e1924c80-93d5-11ea-80a6-254ff02de925.PNG)

**Comment by stenzek** [comment]
This was working...

**Comment by stenzek** [comment]
Works here. Make sure you don't have "disable interlacing" enabled, the game needs it.

We either need a gameini here or to change the default. The only downside is it makes 50/60hz 480i games look like rubbish with combing.

**Comment by kurayami6** [comment]
It's always the game you'd least expect that turn out to be the most difficult to emulate.
