### ISSUE TITLE
Little Big Adventure (Europe) (En,Fr,De,Es,It) // Crashes after the anti piracy screen.

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#422]
The emulator crashes after few seconds when trying to read the game.
Just after the usual anti-piracy screen.

**Comment by stenzek** [comment]
Should hopefully be fixed by https://github.com/stenzek/duckstation/commit/c114873ed8ca9160a6f7a8ba14143517b855ed34

**Comment by Zet-sensei** [comment]
Fixed.
Thanks!
