### ISSUE TITLE
Text is broken in Zork I - The Great Underground Empire (Japan) with OpenGL and D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#423]
OpenGL at x1

![opengl x1](https://user-images.githubusercontent.com/31968468/81644276-c3c2f700-946a-11ea-8a13-bd8c4680ceae.PNG)

D3D11 at x1

![d3d11 x1](https://user-images.githubusercontent.com/31968468/81644294-cc1b3200-946a-11ea-9c58-9fdeacd2166f.PNG)

OpenGL at x4

![OpenGL x4](https://user-images.githubusercontent.com/31968468/81644328-db9a7b00-946a-11ea-8337-dd008d46b65c.png)

D3D11 at x4

![SLPS-00271_2020-05-12_16-06-33](https://user-images.githubusercontent.com/31968468/81644349-e48b4c80-946a-11ea-8aa8-e2eae9ac7d5e.png)

Software

![software](https://user-images.githubusercontent.com/31968468/81644362-ea812d80-946a-11ea-9916-38a47e455899.PNG)

**Comment by stenzek** [comment]
Probably texture filtering. If not, I'll untag.
