### ISSUE TITLE
Graphical glitches in Zoop - America's Largest Killer of Time! (USA) with all renderers

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#424]
Software

![Capture](https://user-images.githubusercontent.com/31968468/81645284-aa22af00-946c-11ea-82d1-e426db350d48.PNG)

OpenGL

![SLUS-00078_2020-05-12_16-15-31](https://user-images.githubusercontent.com/31968468/81645319-b9096180-946c-11ea-8bc5-5d5902e8969a.png)

Beetle PSX for comparison.

![Zoop - America's Largest Killer of Time! (USA)-200512-161650](https://user-images.githubusercontent.com/31968468/81645367-ccb4c800-946c-11ea-8e40-69c172ad7043.png)

**Comment by stenzek** [comment]
Is this still happening on the latest build?

**Comment by kurayami6** [comment]
Everything seems to be fixed.
