### ISSUE TITLE
Screen transition is broken in Zoids - Teikoku vs Kyouwakoku - Meka Seitai no Idenshi (Japan) with OpenGL and D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#425]
OpenGL and D3D11 at x1

![Capture](https://user-images.githubusercontent.com/31968468/81646136-0df9a780-946e-11ea-8c7b-1b76521c2379.PNG)

OpenGL and D3D11 at x4

![SLPS-02982_2020-05-12_16-28-48](https://user-images.githubusercontent.com/31968468/81646164-19e56980-946e-11ea-8350-d6ce71ea7eaa.png)

Software

![Capture2](https://user-images.githubusercontent.com/31968468/81646173-1fdb4a80-946e-11ea-8571-b6877b103191.PNG)

**Comment by stenzek** [comment]
Texture filtering?
