### ISSUE TITLE
Zoku Mikagura Shoujo Tanteidan - Kanketsuhen (Japan) (Disc 1) hangs on the first screen

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#426]
![SLPS-02266_2020-05-12_16-58-02](https://user-images.githubusercontent.com/31968468/81648658-65017b80-9472-11ea-8af9-fbaf032b1e9d.png)

![Capture](https://user-images.githubusercontent.com/31968468/81648700-75195b00-9472-11ea-8f0e-e03ffe4200cf.PNG)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/d7bd21c06dbaf4d8b3866acd2c2417be694668dd
