### ISSUE TITLE
Graphical glitches in Powerslave with OpenGL and D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#428]
OpenGL and D3D11 at x1

![Capture2](https://user-images.githubusercontent.com/31968468/81710490-1aa1ee00-94b6-11ea-8044-868f3de4d5ff.PNG)

OpenGL and D3D11 at x4

![SLUS-00102_2020-05-13_01-05-11](https://user-images.githubusercontent.com/31968468/81710573-2a213700-94b6-11ea-8851-7e341d7a0f18.png)

Software

![Capture](https://user-images.githubusercontent.com/31968468/81710599-33120880-94b6-11ea-96b9-d06b8d02673e.PNG)

**Comment by stenzek** [comment]
Probably invalid due to texture filtering again. Please test on a stock config.

**Comment by kurayami6** [comment]
Yeah I never even realized I had it on. Does it serve any purpose or just break games?

**Comment by jpchow26** [comment]
Makes 3D textures appear smoother. 2D tiled elements will artifact as you see.
