### ISSUE TITLE
Graphical glitches in Xena Warrior Princess with OpenGL and D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#429]
OpenGL and D3D11 at x1

![Capture2](https://user-images.githubusercontent.com/31968468/81712212-b2eca280-94b7-11ea-98fd-eec60a3b22d4.PNG)

OpenGL and D3D11 at x4

![SLUS-00977_2020-05-13_01-14-04](https://user-images.githubusercontent.com/31968468/81712254-bda73780-94b7-11ea-8240-19d39f630521.png)

Software

![Capture](https://user-images.githubusercontent.com/31968468/81712311-ca2b9000-94b7-11ea-8129-745f8cd9ef97.PNG)

**Comment by stenzek** [comment]
Turn off bilinear texture filtering. Please stop wasting my time with these invalid issue reports.
