### ISSUE TITLE
Snatcher (Japan) // Crashes on Cached Interpreter & Recompiler modes.

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#430]
For reference - The game can only be executed on Interpreter mode.

**Comment by kurayami6** [comment]
Still happens as of the latest version. Right after the opening Konami logo. 

![Capture](https://user-images.githubusercontent.com/31968468/85939465-2ad43680-b959-11ea-9d2a-adabc712d0c2.PNG)

**Comment by Zet-sensei** [comment]
With some tests on 0.1-1998-g43bafe1a, now the game only works on Cached Interpreter and Recompiler CPU Modes.
The Interpreter CPU Mode can't load the game anymore.

After our discussions and a suggestion on Discord, seems iCache related, as enabling Recompiler iCache on Advanced Settings broke the game once more.

**Comment by stenzek** [comment]
This ended up being a CD-ROM issue, not a CPU issue. It should work in all modes as of https://github.com/stenzek/duckstation/commit/3890a539eeeb4d7086679dc160f197cfe9f28eac

**Comment by Zet-sensei** [comment]
Fixed.
Tested with the 3 CPU Execution modes.
