### ISSUE TITLE
Advanced V.G. (Japan) // Missing effect on sprites during the intro.

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#431]
There is a missing 'fading away' effect when characters sprites are sliding on-screen (probably with semi-transparency gradient).

Instead of fading away with a rapid movement, the sprites are accumulating.

![AVG](https://user-images.githubusercontent.com/52127625/81761980-be49c900-94cb-11ea-993b-3a2e74692b9a.jpg)

The correct behaviour should be like that.
![AVGCorrect](https://user-images.githubusercontent.com/52127625/81762025-da4d6a80-94cb-11ea-850e-8dd0622a7972.jpg)

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/bf3c83658a6def84ce0d9a854cf4c74098bc9a24

**Comment by Zet-sensei** [comment]
Confirmed.
Fixed.
