### ISSUE TITLE
Zero Pilot - Gin'yoku no Senshi (Japan) (v1.1) has regressed as of the latest version

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#432]
There's a strange looping sound effect that only happens as of the latest version. The BIOS also sounds wrong.

[SCPS-10049_2020-05-13_13-34-09.zip](https://github.com/stenzek/duckstation/files/4619684/SCPS-10049_2020-05-13_13-34-09.zip)

Here's commit 1.0.305 for comparison. Notice how the BIOS sounds a lot better and there's no looping sound effect?

[SCPS-10049_2020-05-13_13-38-26.zip](https://github.com/stenzek/duckstation/files/4619692/SCPS-10049_2020-05-13_13-38-26.zip)

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/d461d7c87a1dee4db7e00a2a9aa6ce9ef807a357

**Comment by kurayami6** [comment]
Fixed
