### ISSUE TITLE
Graphics in Zero Divide (USA) flicker horribly with all renderers 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#433]
![SLUS-00183_2020-05-13_14-50-29](https://user-images.githubusercontent.com/31968468/81772490-575afd00-9529-11ea-9d21-0629283eec34.png)

**Comment by jpchow26** [comment]
oddly enough, turning on view vram stops the flickering.

**Comment by stenzek** [comment]
I think this was fixed by https://github.com/stenzek/duckstation/commit/7d887edf17dc4b9b749fd8962092564b158bbf38

**Comment by kurayami6** [comment]
Flickering is fixed but I noticed the announcer at the beginning of the round gets partially cut off. 

[SLUS-00183_2020-05-18_00-20-21.zip](https://github.com/stenzek/duckstation/files/4640391/SLUS-00183_2020-05-18_00-20-21.zip)

**Comment by kurayami6** [comment]
I'll close this and add Zero Divide to the list of games with the same problem.
