### ISSUE TITLE
Zeitgeist (Japan) hangs during opening cutscene

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#434]
The opening cutscene shows a black screen for a little while and then freezes on this. I can still hear audio playing. 

![2020-05-13_15-11-02](https://user-images.githubusercontent.com/31968468/81773877-a9515200-952c-11ea-8964-a6a6f9f6e3b1.png)

**Comment by stenzek** [comment]
Is this still happening on the latest build?

**Comment by Zet-sensei** [comment]
Fixed.
Should be closed.

**Comment by kurayami6** [comment]
Yeah it's fixed.
