### ISSUE TITLE
Screen doesn't fade out properly in Yuuwaku Office Ren'ai-ka (Japan) with OpenGL and D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#435]
After the chick is finished talking the screen is supposed to fade to black and then go to the name  entry screen. With OpenGL and D3D11 it almost fades to black and stays like this for a few seconds before transitioning. 

![SLPS-01460_2020-05-13_20-35-09](https://user-images.githubusercontent.com/31968468/81802637-c94b3a80-9559-11ea-844c-09e3e698d13e.png)

**Comment by stenzek** [comment]
Does the speed drop during this? I wonder if it's doing a bunch of readbacks or something.

**Comment by kurayami6** [comment]
It gets stuck for a few seconds. The framerate drops from 59 to 0.

**Comment by stenzek** [comment]
59fps? vps? There's a difference between internal framerate and displayed frames. That's why I asked for the speed percentage ;)

**Comment by kurayami6** [comment]
Speed stays at 100%

![Capture](https://user-images.githubusercontent.com/31968468/81819664-efc99f80-9572-11ea-96bd-b325a05e8656.PNG)

**Comment by stenzek** [comment]
Hm, not slowdown due to readbacks then I guess

**Comment by stenzek** [comment]
Are you sure this is an issue? That screen looks pretty dark to me, and a couple of seconds delay for a transition seems normal?

**Comment by kurayami6** [comment]
It doesn't happen at all with the software renderer.

**Comment by stenzek** [comment]
So what's the issue? The delay or the near-black colour? The latter could just be result of accumulated blending error on a 8-bit-per-channel framebuffer.

**Comment by kurayami6** [comment]
It's one issue. In the software renderer after the girl is finished talking the screen will fade to black and then the name entry screen will appear. In OpenGL and D3D11 the fade to black doesn't fully happen. It fades to almost black, stays that way for a few seconds, then fully fades out and goes to the name entry screen. I know I've gone on about this before but If this emulator had an easy way to record video I could just record it happening and show you the difference between renderers.

**Comment by jpchow26** [comment]
If you're on Windows the Xbox game bar (WIN+G) has a built in screen recording utility that works well. Capture it there. And quit the snark please. It's unnecessary in bug reports.

**Comment by stenzek** [comment]
The game is probably achieving the fade out by blending a copy of the framebuffer with a gradually decreasing vertex colour. You're talking about an error of 1/255. It's not surprising that happens in the hardware renderers, which have an intermediate precision of 8 bits per channel instead of 5 bits per channel.

Switching to a 5551 format might fix this, but the problem is 5551 formats are not guaranteed to be supported on all hardware, so I can't make it a requirement. I guess I could offer that as an option, but really we're talking about something which you can't see by eye...

**Comment by kurayami6** [comment]
Yagami Hiroki no Game-Taste - Munasawagi no Yokan (Japan) has the same fade out problem. 

![SLPS-02064_2020-05-14_14-32-57](https://user-images.githubusercontent.com/31968468/81893058-0d891a00-95f0-11ea-8783-9753f29b33d5.png)

**Comment by stenzek** [comment]
Please retry on the latest build. You'll need to ensure true colour is disabled (I probably should turn it off by default). If it's achieving this fade-out through vertex colours in a similar way to Adventure V.G and Silent Hill, it should fix it.

**Comment by kurayami6** [comment]
Fixed.
