### ISSUE TITLE
Yuukyuu no Eden - The Eternal Eden (Japan) (v1.1) hangs instantly after BIOS.

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#436]
![Capture](https://user-images.githubusercontent.com/31968468/81804447-72933000-955c-11ea-8e90-4d5736f2d47b.PNG)

**Comment by stenzek** [comment]
Linked list DMA goes off to null-pointer land.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/e293c22cde601c4799321e911f02cf1f5c915046

**Comment by kurayami6** [comment]
Fixed.
