### ISSUE TITLE
Yuukyuu Gensoukyoku Ensemble 1 and 2 both hang after the first logo

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#437]
They both hang after this screen.

![SLPS-01742_2020-05-13_22-06-57](https://user-images.githubusercontent.com/31968468/81810333-1c2aef00-9566-11ea-90de-98280b421ffb.png)

The log is the same for both games.

![Capture](https://user-images.githubusercontent.com/31968468/81810354-26e58400-9566-11ea-86db-f36ef815f25b.PNG)

**Comment by stenzek** [comment]
Should be fixed in the latest build. No idea about the second one, might be the same issue.

**Comment by kurayami6** [comment]
Both fixed. Keep it up.
