### ISSUE TITLE
Graphical glitch on mode select screen in Yoshimoto Mahjong Club Deluxe (Japan) with OpenGL and D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#438]
OpenGL and D3D11 at x1

![Capture](https://user-images.githubusercontent.com/31968468/81849224-94f76e80-9599-11ea-9331-0ddf09fbd794.PNG)

OpenGL and D3D11 at x4

![SLPS-01758_2020-05-14_04-08-51](https://user-images.githubusercontent.com/31968468/81849268-a6407b00-9599-11ea-98d9-1af9f186623a.png)

Software

![Capture2](https://user-images.githubusercontent.com/31968468/81849295-af314c80-9599-11ea-800f-cea5ffa22818.PNG)

**Comment by stenzek** [comment]
That's the... opposite of what I would expect.

**Comment by stenzek** [comment]
Should be fixed by fc0560087fde6f517c4141a6fa674ad92fead081

**Comment by kurayami6** [comment]
Fixed.
