### ISSUE TITLE
The screen briefly turns to graphical garbage every time you switch resolutions in Yamifuku Natsu - Teito Monogatari Futatabi (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#439]
![Capture](https://user-images.githubusercontent.com/31968468/81854806-cc6a1900-95a1-11ea-904a-df3febdeff51.PNG)

**Comment by stenzek** [comment]
The resolution switch is intended as a debug option, so this isn't really a bug.

But still, it shouldn't be doing that.

**Comment by stenzek** [comment]
Can't seem to reproduce. It does look like a FMV/24-bit image being displayed as 16-bit though.
