### ISSUE TITLE
Simple 1500 Series Vol. 57 - The Meiro (Japan) hangs after logos

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#44]
![Capture](https://user-images.githubusercontent.com/31968468/75828464-fd8ad800-5dff-11ea-8ce6-aa20ea0d49c1.PNG)

**Comment by stenzek** [comment]
I wonder if it's related to #26... I believe that one's a DMA issue, it's configuring it in a way which isn't documented. I'm waiting for some parts to arrive then I'll be able to run hardware tests.

**Comment by kurayami6** [comment]
Fixed as of the latest version.
