### ISSUE TITLE
Flickering line on the right side of the screen in X2 - No Relief (Japan) with all renderers 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#440]
Flickering blue bar on the right side of the screen. Happens with all renderers and all crop modes. Doesn't happen in Beetle PSX. 

![Capture](https://user-images.githubusercontent.com/31968468/81923189-991a9f00-9620-11ea-971a-6713420ecd10.PNG)

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/0ef0c36704c2ba79cd9c80e649c953c3fc0bfb5e

**Comment by kurayami6** [comment]
Fixed.
