### ISSUE TITLE
X-COM - UFO Defense (USA) hangs on the first loading screen

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#441]
![SLUS-00141_2020-05-14_21-35-30](https://user-images.githubusercontent.com/31968468/81930777-64144980-962c-11ea-995b-5a290a9d3fc2.png)

![Capture](https://user-images.githubusercontent.com/31968468/81930795-6b3b5780-962c-11ea-8d8b-3e83c0fbb868.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/81930859-7c846400-962c-11ea-9f90-0c9ebead1f81.PNG)

**Comment by kurayami6** [comment]
The European version gets to a broken menu and crashes if you click anything.

![SLES-00054_2020-05-14_22-33-27](https://user-images.githubusercontent.com/31968468/81934976-37affb80-9633-11ea-8ec5-648c593b4993.png)

**Comment by kurayami6** [comment]
The Japanese version seems to work fine.

![SLPS-00257_2020-05-14_22-37-04](https://user-images.githubusercontent.com/31968468/81935197-98d7cf00-9633-11ea-8344-bef94f16027a.png)

**Comment by stenzek** [comment]
Can't seem to reproduce this. Is it still happening on the latest build?

**Comment by kurayami6** [comment]
Fixed as of the latest version.
