### ISSUE TITLE
X Games Pro Boarder (USA) hangs on the first level

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#442]
A few seconds into the race the game will hang and start looping the same audio over and over. 

![SLUS-00704_2020-05-14_23-42-12](https://user-images.githubusercontent.com/31968468/81942601-aabe6f80-963d-11ea-9187-52db5fbf9993.png)

[SLUS-00704_2020-05-14_23-42-19.zip](https://github.com/stenzek/duckstation/files/4628801/SLUS-00704_2020-05-14_23-42-19.zip)

**Comment by stenzek** [comment]
Looks like it might be GPU timing related.

**Comment by kurayami6** [comment]
The game no longer hangs for me but the music is still broken. It sounds like parts of it are being skipped.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/15652b4c1f5511d231b10bbc20d0f69aa4f912bf
