### ISSUE TITLE
[Regression] DualShock Axis Bindings Broken

### ISSUE THREAD

**Issue by tony971** [stenzek/duckstation#443]
The analog sticks on my xbox one controller do nothing. I tried re-binding them. They bind, but are useless. Windows 10

**Comment by stenzek** [comment]
Working fine here. Depending on the game, you may need to manually enable analog mode as some of the triggers for switching to analog mode before broke certain games, so I removed them (and they likely weren't correct anyway). If you don't see a "Controller 1 switched to analog mode." message pop up during game boot, this is likely the case.

1. Bind a button or key to the "analog" button.
2. Boot your game, and push that button.
3. You should see a message saying "Controller 1 switched to analog mode.", assuming the game hasn't locked it to digital mode.
4. Sticks should work as normal.

If you save and resume the game, you won't need to switch the controller to analog mode again (it's part of the save state). However, if you reset the game, you will.

I'm planning on adding a "auto enable analog mode" option in the near future to automate this.

**Comment by tony971** [comment]
I'm having the same issue on beetle, so it's probably not duckstation specific. The analog sticks work in other libretro cores, though. So I have no idea what's going on.

**Comment by stenzek** [comment]
Did you try toggling the analog mode button? If the axises are being picked up in the controller binding panel (when you clear and rebind them), there's no reason they should not be working ingame.

**Comment by tony971** [comment]
I didn't have an analog button set and it defaulted to analog being turned off. After I set the analog button and toggled it, it worked fine. Any chance of changing the default behavior if Analog Controller is the selected controller type?

**Comment by stenzek** [comment]
Adding an auto-enable analog mode is on my todo list as I said.

I don't want to enable it by default as that would break games which don't support the controller.
