### ISSUE TITLE
Advanced V.G. // Infinite loading loop on VS. screen & missing music in-game.

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#444]
The game is missing all CDDA tracks in-game (no music at all, only sound effects) and goes in an inifinite loop on the VS. screen.

The log contains that info when the loop begins.
> D/CDROM: CDROM executing command 0x0E
D/CDROM: CDROM executing command 0x02
D/CDROM: CDROM executing command 0x03
D/CDROM: Seek time for 74 LBAs: 20000
D/CDROM: Read sector 121500 as CDDA
[...]
D/CDROM: Read sector 121574 as CDDA

**Comment by stenzek** [comment]
Both issues should be fixed as of https://github.com/stenzek/duckstation/commit/e1157bff654df1c07614975a0c7adaa96e957e16

**Comment by Zet-sensei** [comment]
Fixed.
Thanks, as always.
