### ISSUE TITLE
Text boxes are broken in World Soccer Jikkyou Winning Eleven 3 - Final Ver. (Japan) (v1.1)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#447]
OpenGL and D3D11 at x4

![SLPM-86162_2020-05-16_04-45-25](https://user-images.githubusercontent.com/31968468/82085516-88f1e500-9730-11ea-922d-bcc036edcdaa.png)

OpenGL and D3D11 at x1

![Capture2](https://user-images.githubusercontent.com/31968468/82085543-94dda700-9730-11ea-920f-ceba5792f83b.PNG)

Software

![Capture](https://user-images.githubusercontent.com/31968468/82085585-9effa580-9730-11ea-9dcf-26942bf66ee6.PNG)

**Comment by kurayami6** [comment]
As of the latest version x4 is the same and x1 is even more broken. 

![Capture](https://user-images.githubusercontent.com/31968468/86209283-94e91780-bbb5-11ea-86c3-5814160fc367.PNG)

**Comment by stenzek** [comment]
No longer an issue on the latest build.
