### ISSUE TITLE
Magical Drop III - Yokubari Tokudai-gou! (Japan) // The game is locked after the initial loading screen.

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#448]
The game cannot be loaded.

Stays on the loading screen after a first selection on a menu.

> 
> D/CDROM: Seek time for 155 LBAs: 1483744
> D/CDROM: Read sector 2572: mode 2 submode 0x08 into buffer 0
> D/CDROM: Read sector 2573: mode 2 submode 0x08 into buffer 1
> D/CDROM: Read sector 2574: mode 2 submode 0x08 into buffer 2
> W(CDROM::SetAsyncInterrupt): Not setting async interrupt 1 because there is already one unacknowledged
> D/CDROM: Read sector 2575: mode 2 submode 0x08 into buffer 3
> W(CDROM::SetAsyncInterrupt): Not setting async interrupt 1 because there is already one unacknowledged
> D/CDROM: Read sector 2576: mode 2 submode 0x08 into buffer 4
> W(CDROM::SetAsyncInterrupt): Not setting async interrupt 1 because there is already one unacknowledged
> D/CDROM: Read sector 2577: mode 2 submode 0x08 into buffer 5
> W(CDROM::SetAsyncInterrupt): Not setting async interrupt 1 because there is already one unacknowledged
> D/CDROM: Read sector 2578: mode 2 submode 0x08 into buffer 6
> W(CDROM::SetAsyncInterrupt): Not setting async interrupt 1 because there is already one unacknowledged
> D/CDROM: Read sector 2579: mode 2 submode 0x08 into buffer 7
> W(CDROM::SetAsyncInterrupt): Not setting async interrupt 1 because there is already one unacknowledged
> D/CDROM: Read sector 2580: mode 2 submode 0x08 into buffer 0
> W(CDROM::SetAsyncInterrupt): Not setting async interrupt 1 because there is already one unacknowledged

**Comment by stenzek** [comment]
DMA goes off to null pointer land and needs the interrupt to fire to progress.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/e293c22cde601c4799321e911f02cf1f5c915046

**Comment by Zet-sensei** [comment]
Fixed.
