### ISSUE TITLE
Ballerburg-Castle Chaos (USA) hangs when trying to start a campaign 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#45]
Tried Forest campaign and it crashed after the first loading screen. Tried Volcano campaign and it played the cinematic and crashed after the second loading screen. 

![Capture](https://user-images.githubusercontent.com/31968468/75935440-4c557200-5ed3-11ea-96b9-0f7243d97c0a.PNG)

**Comment by benderscruffy** [comment]
goes ingame now
just started forest level
![ball](https://user-images.githubusercontent.com/2696404/78241496-0e1f9280-7513-11ea-9e99-bb76eb5c33a3.PNG)
