### ISSUE TITLE
Can the AppImage be downloaded somewhere?

### ISSUE THREAD

**Issue by probonopd** [stenzek/duckstation#451]
Thanks for making an AppImage. Can it be downloaded somewhere?

**Comment by stenzek** [comment]
There's a link at the top of the README.md in the repo:
> Latest Windows and Linux (AppImage) Builds: https://ci.appveyor.com/project/stenzek/duckstation

Choose Ubuntu18.04 -> Artifacts.

**Comment by probonopd** [comment]
Thanks, but I must be overlooking something - don't see an AppImage there...

![noappimage](https://user-images.githubusercontent.com/2480569/82119674-f1ac8200-976f-11ea-81f3-4c5a1c5b70a4.png)

**Comment by ggdrt** [comment]
You caught the CI before it had run the AppImage build for that particular commit. It's done now: https://ci.appveyor.com/project/stenzek/duckstation/build/job/qb648n961x0cefhi/artifacts

**Comment by stenzek** [comment]
Sorry, AppVeyor is quite... slow at building.

Perhaps we should write a guide on how to download/use the AppImages like I did for Windows.

**Comment by ggdrt** [comment]
> Perhaps we should write a guide on how to download/use the AppImages like I did for Windows.

Self-assigning this as mentioned in Discord.

**Comment by probonopd** [comment]
Still no AppImage, only a .7z file. Please don't put AppImages into other archives, please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages/cc2441518975caca23e9ce2dba6f08a22c678d1e#common-mistake for the reason. Thanks!

**Comment by stenzek** [comment]
There's two appimages, one for each frontend. Both are in the archive. That said I don't see why we couldn't upload them separately though.

**Comment by ggdrt** [comment]
> Please DO NOT put an AppImage into another archive like a .zip or .tar.gz. While it may be tempting to avoid users having to set permission, this breaks desktop integration with the optional appimaged daemon, among other things. 

I don't think breaking desktop integration was really a concern for us since users would just extract the two AppImages out of the archive and overwrite their pre-existing files.

The reason why I archived both together was to have users grab both versions simultaneously like with the Windows builds, but pushing the two AppImages separately seems fine in this case.

**Comment by stenzek** [comment]
Non-zipped AppImages can now be found in the releases page, currently compiled by the GitHub Actions CI: https://github.com/stenzek/duckstation/releases/tag/latest

Whether we end up using AppVeyor or Actions doesn't really matter here - the two will be separate downloads and now zipped. I think this solves the issue, I just have to update the README. If there's still something missing, please let me know.

**Comment by probonopd** [comment]
Thank you very much @stenzek. Is there a reason why the version and architecture are missing from the filename, and why the zsync file (for updating) is not being published?

**Comment by probonopd** [comment]
A required library is missing and needs to be bundled inside the AppImage:

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/12af1e062ea357e8f232d2ae0599e534aec75719/database/DuckStation/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/2023

**Comment by stenzek** [comment]
I'm not a Linux expert, but shouldn't `libGLX.so` be provided by the vendor and/or distro? (part of the driver)

I've got a near-complete refactor of all the GL context management which will load this dynamically, so shouldn't be a problem then.

**Comment by probonopd** [comment]
Actually you are right. libGLX is one of the libraries that should usually come with the distribution. https://github.com/AppImage/pkg2appimage/blob/master/excludelist 

Thanks for pointing this out.  :+1:  This is a bug in our test system which I will fix.

**Comment by probonopd** [comment]
...but it is not even available for xenial:

```
E: Unable to locate package libglx0
```

So this means that this application cannot run on xenial?

**Comment by stenzek** [comment]
I haven't tested it on xenial, but I don't see why it shouldn't work.

libglx0 isn't in a package on its own, it'll be part of the graphics driver. So likely one of the libgl mesa packages, unless you're using the NVIDIA blob. But then there's this whole glvnd thing as well, and I'm not sure how that fits in (my Linux driver stack knowledge is a few years out of date).
