### ISSUE TITLE
[Hardware] Spyro 2 - Seams Between Textures

### ISSUE THREAD

**Issue by tony971** [stenzek/duckstation#452]
When using hardware renderers, seams appear throughout the Insomniac logo when it starts to rotate. I used to know more examples of this happening, but it's the easiest one to reproduce and I usually stick to software. I'm not sure how avoidable this is, as every emulator I've tried has this issue.

**Comment by stenzek** [comment]
Could you take a screenshot of the seams? I'm not seeing any here, but I might not be looking in the right spot.

**Comment by tony971** [comment]
![SCUS-94425_2020-05-16_09-50-01](https://user-images.githubusercontent.com/7101253/82121421-62f23200-977c-11ea-85a9-42f956eb948f.png)

Here you go

**Comment by stenzek** [comment]
That looks like the typical sorts of artifacts seen on the edges when bilinear texture filtering is enabled. If you have it on, try turning it off.

For what it's worth, I frame stepped through the whole thing on my system and couldn't see any seams.

**Comment by tony971** [comment]
It was a bilinear filter issue, like you suspected. Does not reproduce with it disabled.
