### ISSUE TITLE
Gunbird (Japan) // Flickering scrambled line on the right side of screen.

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#453]
For reference.
Happens with all Crop options.

![Gunbird](https://user-images.githubusercontent.com/52127625/82119843-08f46b00-9782-11ea-9c5b-0fc139e773f8.jpg)

**Comment by stenzek** [comment]
Looks like a single column of pixels. Might be overscan related...

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/0ef0c36704c2ba79cd9c80e649c953c3fc0bfb5e

**Comment by Zet-sensei** [comment]
Fixed.
