### ISSUE TITLE
The first loading screen in World Cup Golf - Professional Edition (USA) takes way too long

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#455]
I timed it. It takes 55 seconds in Duckstation and 17 in Beetle. 

![SLUS-00063_2020-05-16_23-38-52](https://user-images.githubusercontent.com/31968468/82133955-33533080-9835-11ea-9e36-ddf285595a2e.png)

**Comment by stenzek** [comment]
Try without a memory card. Might be related to Racinggroovy.

**Comment by kurayami6** [comment]
Didn't make a difference.

**Comment by stenzek** [comment]
DMA goes off to null pointer land.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/e293c22cde601c4799321e911f02cf1f5c915046

**Comment by kurayami6** [comment]
Fixed.
