### ISSUE TITLE
Loud beeping sound during the loading screen before a match in World Cup 98 (USA). 

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#456]
![SLUS-00644_2020-05-17_17-43-59](https://user-images.githubusercontent.com/31968468/82138793-80032f80-9866-11ea-972f-7045a1fa719c.png)

[SLUS-00644_2020-05-17_17-43-42.zip](https://github.com/stenzek/duckstation/files/4639843/SLUS-00644_2020-05-17_17-43-42.zip)

**Comment by kurayami6** [comment]
Still an issue as of the latest version.

**Comment by BloodRaynare** [comment]
Still happens in latest preview version (24c37324).
But, apparently it sounds fine in Interpreter mode.

**Comment by stenzek** [comment]
AFAICT fixed with https://github.com/stenzek/duckstation/commit/75b69a6f7e4df33e82a7f46ed1d87c55fa5d6d47
