### ISSUE TITLE
A blank white screen briefly flashes after the BIOS screen in Woody Woodpecker Racing (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#457]
After the BIOS there's several seconds of black, then a blank white screen flashes briefly, then the first logo screen appears. 

![SLUS-01188_2020-05-17_18-14-42](https://user-images.githubusercontent.com/31968468/82139496-7f20cc80-986b-11ea-9798-7d5e2d3c1e79.png)

In Beetle the white screen is a white line.

![Woody Woodpecker Racing (USA)-200517-182535](https://user-images.githubusercontent.com/31968468/82139608-5816ca80-986c-11ea-86dd-44a7dafcc4fd.png)

**Comment by stenzek** [comment]
How does the console behave?

**Comment by kurayami6** [comment]
Just checked. Flashes the white screen on real hardware. Looks like Beetle is the one doing it wrong.

**Comment by stenzek** [comment]
Thanks for checking.
