### ISSUE TITLE
Question about Wipeout XL (USA) (Beta)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#458]
In Duckstation the game hangs on a blue screen after the BIOS. In Beetle PSX, ePSXe, and on my real PS1 it gets past the blue screen and hangs on a red screen. The game is verified by Redump so all I can think is maybe it only works on a dev console? I don't know if adding support for that is within the scope of this project.

![Capture](https://user-images.githubusercontent.com/31968468/82152845-6504df80-98a7-11ea-8ff8-5b024d8238a2.PNG)

**Comment by stenzek** [comment]
Not within scope if it doesn't work on console.
