### ISSUE TITLE
Changing songs in WipEout (USA) doesn't work

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#459]
Choosing anything other than random will turn off music altogether. 

![SCUS-94301_2020-05-18_02-41-50](https://user-images.githubusercontent.com/31968468/82154659-b49cd880-98b2-11ea-8b78-9f4ceb51248e.png)

**Comment by stenzek** [comment]
Relies on sub-channel position being updated while seeking. Fix incoming soon.

**Comment by stenzek** [comment]
Should be fixed in https://github.com/stenzek/duckstation/commit/5d46556b7da0b6b17a849d629fc6e46401bafcc3

**Comment by kurayami6** [comment]
Fixed. Thanks.
