### ISSUE TITLE
Graphical glitches in Winter Releases '97 and 98 (Europe) with OpenGL and D3D11

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#460]
Select a game and then quit back to the game selection screen. 

Winter Releases - '97 Demo 01 (Europe) at x1

![Capture](https://user-images.githubusercontent.com/31968468/82155667-e8c7c780-98b9-11ea-827a-29be5f01a552.PNG)

Winter Releases - '97 Demo 01 (Europe) at x4

![capture3](https://user-images.githubusercontent.com/31968468/82155696-29bfdc00-98ba-11ea-892b-e13898712022.PNG)

Winter Releases '98 (Europe) at x1

![capture 4](https://user-images.githubusercontent.com/31968468/82155791-c2565c00-98ba-11ea-95c0-192df5728194.PNG)

Winter Releases '98 (Europe) at x4

![82155205-8caf7400-98b6-11ea-9ca2-51911825ae52](https://user-images.githubusercontent.com/31968468/82155835-f762ae80-98ba-11ea-96ba-944d4089b02f.PNG)

**Comment by stenzek** [comment]
Can't seem to reproduce this?
