### ISSUE TITLE
Panekit - Infinitive Crafting Toy Case (Japan) does not boot

### ISSUE THREAD

**Issue by LuigiBlood** [stenzek/duckstation#461]
Using SCPH1001.bin, Panekit gets stuck to the Playstation logo with a weird looping sound.

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/d41bf86eaa7097b4eb0ae933719a68a4ffbee704

**Comment by Zet-sensei** [comment]
Fixed after verification.
Issue could be closed.
