### ISSUE TITLE
Waku Waku Derby (Japan) softlocks on the first loading screen

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#463]
I left it running for over 10 minutes. It never gets past this screen. That wooden horse just rocks back and forth forever. 

![SLPS-01157_2020-05-19_08-41-38](https://user-images.githubusercontent.com/31968468/82267334-586bae80-99af-11ea-9154-96e3a9d29f51.png)

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/3c7229dfe26ce905fbf8d4a3648783579b07d380

**Comment by Zet-sensei** [comment]
After some tests, fixed.
Should be closed.

**Comment by stenzek** [comment]
Thanks @Zet-sensei!
