### ISSUE TITLE
Wip3out (Europe) (En,Fr,De,Es,It) // Crashes in-game just after the first checkpoint.

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#464]
That specific version of the game does crash after the first checkpoint.
Other versions of Wipeout 3 (even the Special Edition) aren't affected at all.
![SCES-01909_2020-05-19_02-44-58](https://user-images.githubusercontent.com/52127625/82272392-c8137680-997a-11ea-99c4-45f1cdf3ee8e.png)

Leaving parts of the log file when the crash occurs, as some hints are maybe inside.

`D/CDROM: CDROM executing command 0x11
D/CDROM: Read sector 175080 as CDDA
D/CDROM: Read sector 175081 as CDDA
D/CDROM: Read sector 175082 as CDDA
D/CDROM: CDROM executing command 0x11
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F800400 (value 0x00007EA5)
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F800402 (value 0x0000FB69)
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F800404 (value 0x0000B3A1)
E(Bus::DoInvalidAccess): Invalid bus dword read at address 0x1F800400
E(Bus::DoInvalidAccess): Invalid bus dword read at address 0x1F800404
E(Bus::DoInvalidAccess): Invalid bus dword write at address 0x1F800408 (value 0x007E0101)
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F80040C (value 0x00000000)
E(Bus::DoInvalidAccess): Invalid bus word read at address 0x1F800408
E(Bus::DoInvalidAccess): Invalid bus word read at address 0x1F80040A
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F80040E (value 0x0000000A)
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F800410 (value 0x00008499)
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F800412 (value 0x0000FC37)
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F800414 (value 0x00003362)
E(Bus::DoInvalidAccess): Invalid bus dword read at address 0x1F800410
E(Bus::DoInvalidAccess): Invalid bus dword read at address 0x1F800414
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F800420 (value 0x00008498)
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F800422 (value 0x0000014F)
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F800424 (value 0x0000347A)
E(Bus::DoInvalidAccess): Invalid bus dword read at address 0x1F800420
E(Bus::DoInvalidAccess): Invalid bus dword read at address 0x1F800424
E(Bus::DoInvalidAccess): Invalid bus dword write at address 0x1F800418 (value 0x007E0101)
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F80041C (value 0x00000000)
E(Bus::DoInvalidAccess): Invalid bus word read at address 0x1F800418
E(Bus::DoInvalidAccess): Invalid bus word read at address 0x1F80041A
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F80041E (value 0x0000000A)
E(Bus::DoInvalidAccess): Invalid bus dword write at address 0x1F800428 (value 0x007E0101)
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F80042C (value 0x00000000)
E(Bus::DoInvalidAccess): Invalid bus word read at address 0x1F800428
E(Bus::DoInvalidAccess): Invalid bus word read at address 0x1F80042A
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F80042E (value 0x0000000A)
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F800430 (value 0x00007EA5)
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F800432 (value 0x0000FB69)
E(Bus::DoInvalidAccess): Invalid bus word write at address 0x1F800434 (value 0x0000B3A1)

[..]

D/CDROM: Read sector 175100 as CDDA
W(CDROM::SetAsyncInterrupt): Not setting async interrupt 1 because there is already one unacknowledged
D/CDROM: Read sector 175101 as CDDA
D/CDROM: Read sector 175102 as CDDA
D/CDROM: Read sector 175103 as CDDA
D/CDROM: Read sector 175104 as CDDA
D/CDROM: Read sector 175105 as CDDA
D/CDROM: Read sector 175106 as CDDA
D/CDROM: Read sector 175107 as CDDA
D/CDROM: Read sector 175108 as CDDA
D/CDROM: Read sector 175109 as CDDA
D/CDROM: Read sector 175110 as CDDA
W(CDROM::SetAsyncInterrupt): Not setting async interrupt 1 because there is already one unacknowledged
`

**Comment by kurayami6** [comment]
Probably because the game has Libcrypt copy protection.

![Capture](https://user-images.githubusercontent.com/31968468/82277416-236d5500-99cb-11ea-9cf4-14a967bab579.PNG)

**Comment by Zet-sensei** [comment]
I didn't check directly by myself that issue (reported to me from an another user yesterday).

Invalid issue.
