### ISSUE TITLE
Buster Bros. Collection (USA) // No CDDA music.

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#465]
There is no music on the 3 games inside the collection.
The CDDA tracks aren't being read.
![BusterBros](https://user-images.githubusercontent.com/52127625/82273338-92bc5800-997d-11ea-8f10-7504695521eb.jpg)

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation/commit/415880fc40115a34c414b41d0ed84d99ce626171 should fix the game locking up at least. Which parts is the CDDA missing from?

**Comment by Zet-sensei** [comment]
There was no music inside the 3 games, only the SFX were being played.

With the fix, we have the CDDA tracks (tracks 2 to 61 on the disc) working now on the 3 games.
