### ISSUE TITLE
Resolution change isn't applied until you move the character in VR Golf '97 (USA) 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#466]
If you switch from x1 resolution to a higher resolution or from OpenGL to D3D11 or vice versa, the game will stay at native resolution until you move the character. 

![SLUS-00198_2020-05-19_22-00-30](https://user-images.githubusercontent.com/31968468/82324328-cd290200-9a1c-11ea-8357-029c57472cc7.png)

![SLUS-00198_2020-05-19_22-00-34](https://user-images.githubusercontent.com/31968468/82324356-d87c2d80-9a1c-11ea-92b7-3ddd1961f3e2.png)

**Comment by stenzek** [comment]
This one's invalid. As I said in the other thread, runtime resolution switching is a debug feature. VRAM gets "resized" as best it can, but things are going to break, this is unavoidable.

In this game's case, it's probably not rendering the frame until you move. So no matter what, you can't pull more pixels out of thin air until the game re-draws itself. Well, unless you saved the last frame's worth of commands, but that's silly.

**Comment by kurayami6** [comment]
Fair enough. I've tested hundreds of games and so far this is the only one I've found that does this.
