### ISSUE TITLE
Music plays at the wrong speed during loading screens in Voice Idol Collection - Pool Bar Story (Japan) (Disc 1)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#467]
There's a noticeable slow down and speed up. It sounds fine in Beetle.

[SLPS-00775_2020-05-19_22-47-20.zip](https://github.com/stenzek/duckstation/files/4650609/SLPS-00775_2020-05-19_22-47-20.zip)

![SLPS-00775_2020-05-19_22-48-24](https://user-images.githubusercontent.com/31968468/82329531-cc946980-9a24-11ea-8438-a00738914726.png)

**Comment by stenzek** [comment]
Uses sequenced music tied to timer2, but IRQs are firing at a constant rate. Needs more investigation.

**Comment by stenzek** [comment]
Seems it's sending commands to the CD-ROM controller before they finish. Ignoring these commands "fixes" it, but this needs verification with hardware tests to ensure this is how the CD-ROM behaves.

**Comment by stenzek** [comment]
Behavior confirmed on console, which turns out to be quite different to what I expected.

Should be fixed with https://github.com/stenzek/duckstation/commit/0672cf4873982b4e6cba41540d4b9c55c16a0080, as well as the longer loading times.

**Comment by kurayami6** [comment]
Fixed.
