### ISSUE TITLE
Buster Bros. Collection (USA) // Cropping problem, missing a part of the screen.

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#468]
An example on Buster Buddies as we could see directly the problem.

Without any cropping or the "All borders" options activated.
Please also see the flickering line (present on other emulators like Mednafen or XEBRA, but not on the HW).
![SLUS-00208_2020-05-19_19-25-54](https://user-images.githubusercontent.com/52127625/82358358-b5df1a00-9a06-11ea-90fd-965d619f22ab.png)

With the "Overscan Area only" cropping option activated, the screen is overcropped.
Part of the screen is missing on the right side.
![SLUS-00208_2020-05-19_19-26-05](https://user-images.githubusercontent.com/52127625/82358359-b7104700-9a06-11ea-8d6e-a9c62461cd8e.png)

**Comment by stenzek** [comment]
We might just need a separate crop range for this game...

**Comment by Zet-sensei** [comment]
After some rapid investigations, same problem applies (at least) for :
- Captain Commando
- Super Puzzle Fighter II Turbo

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/stenzek/duckstation/commit/8bf21fd5a026545bed74ef8cf5d99955043ffd3f.

As a comment on the commit, I've added the same override values also for the JPN version and found some for Captain Commando.
Not idea for Super Puzzle Fighter II Turbo at this point for the correct crop range.
