### ISSUE TITLE
Water is broken in Virtual Kyoutei '98 (Japan) with OpenGL and D3D11

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#469]
When upscaled with OpenGL and D3D11 it looks like this. It also jitters horribly at all resolutions with OpenGL.

![SLPS-01396_2020-05-20_04-13-41](https://user-images.githubusercontent.com/31968468/82362900-6cb3b800-9a50-11ea-8dc0-8f4cce83004c.png)

It looks fine with Software and D3D11 at x1

![Capture2](https://user-images.githubusercontent.com/31968468/82363111-bbf9e880-9a50-11ea-9fce-068bf4b8edeb.PNG)

**Comment by stenzek** [comment]
Doesn't seem to be happening on the latest build. Broken with upscaling, though.
