### ISSUE TITLE
Destruction Derby (EUR) black screen (unknown command in cdrom)

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#47]
![derby](https://user-images.githubusercontent.com/2696404/76065743-2c06df80-5fc7-11ea-9987-bf12b1c67f4b.PNG)

**Comment by stenzek** [comment]
Please retry on latest master, and post the command number from the log.

**Comment by benderscruffy** [comment]
![derby](https://user-images.githubusercontent.com/2696404/76136767-33ce8e80-6070-11ea-9c39-594b4a74de15.PNG)

**Comment by stenzek** [comment]
Implemented `SetSession` in latest master, but I haven't tested it with this game.

**Comment by benderscruffy** [comment]
goes ingame now
