### ISSUE TITLE
Virtual Fireplace Screensaver (Europe) (Unl) and Virtual Aquarium Screensaver (Europe) (Unl) both crash with the same error message

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#470]
![Capture](https://user-images.githubusercontent.com/31968468/82371466-98896a80-9a5d-11ea-8d88-35cecabd7302.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/82371471-9b845b00-9a5d-11ea-849b-da2a009cdaa7.PNG)

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/11c2b5a1e85aae84c740016a62d0898bb04b97f4
