### ISSUE TITLE
QT issue on laptop

### ISSUE THREAD

**Issue by bryc** [stenzek/duckstation#472]
My laptop is resolution 1366x768, and I am having various issues.

1. The Settings dialog is cut off screen, sometimes its the top (titlebar off screen) or bottom is off screen.
2. If I try to resize the Settings dialog from the top titlebar, it outpaces my mouse and makes the window completely disappear. After this, I cannot click Settings anymore and have to reopen duckstation.

Just my initial observations. Using Windows 10 and the dev build in releases.

**Comment by heckez-sys** [comment]
dev builds are unstable

**Comment by stenzek** [comment]
I was planning on adding vertical scrolling to the settings window, which should solve the issue. The main issue is the controller bindings.

**Comment by bryc** [comment]
![image](https://user-images.githubusercontent.com/1408749/82406530-df169f00-9a34-11ea-881e-608f21b3043a.png)

This is what I'm seeing (moved taskbar to vertical to see underneath). I cannot read the full descriptions of each option. The SDL version works for now, but not as many nice features/configurability.

**Comment by tony971** [comment]
The same thing happens with Windows desktop scaling.

**Comment by bryc** [comment]
Yep, that fixes the issue here.
