### ISSUE TITLE
I Tested Some Games

### ISSUE THREAD

**Issue by DarkFrost89** [stenzek/duckstation#473]
First stenzek Thanks For Create This Awsome Emulator, I Enjoy help test some games and try Better this emulator

First I Write My Test System
Core2 Duo e8400 cpu
4gb 1600 mhz ram
samsun 750 evo ssd
msı r9 280 gaming edition 3gb 384 bit gpu

And Tested Games
Games Hash Verified By Redump.org

Blade [U] [SLUS-01215]
`<entry code="SLUS-01215" title="Blade [U] [SLUS-01215]" region="NTSC-U" compatibility="5">
    <compatibility>No Issues</compatibility>
    <version-tested>0.1-908-g9f22684</version-tested>
    <comments>Just Little Audio Video Desync İngame Server Level (Tested By Dark Frost And Game Verified By Redump.org)</comments>
</entry>`

Dino Crisis [U] [SLUS-00922]
`<entry code="SLUS-00922" title="Dino Crisis [U] [SLUS-00922]" region="NTSC-U" compatibility="5">
    <compatibility>No Issues</compatibility>
    <version-tested>0.1-908-g9f22684</version-tested>
    <comments>Works Perfect (Tested By Dark Frost And Game Verified By Redump.org)</comments>
</entry>`

Dino Crisis 2 [U] [SLUS-01279]
`<entry code="SLUS-01279" title="Dino Crisis 2 [U] [SLUS-01279]" region="NTSC-U" compatibility="5">
    <compatibility>No Issues</compatibility>
    <version-tested>0.1-908-g9f22684</version-tested>
    <comments>Works Perfect (Tested By Dark Frost And Game Verified By Redump.org)</comments>
</entry>`

Civilization II [U] [SLUS-00792]
`<entry code="SLUS-00792" title="Civilization II [U] [SLUS-00792]" region="NTSC-U" compatibility="5">
    <compatibility>No Issues</compatibility>
    <version-tested>0.1-908-g9f22684</version-tested>
    <comments>Works Perfect (Tested By Dark Frost And Game Verified By Redump.org)</comments>
</entry>`

Parasite Eve II [CD1] [U] [SLUS-01042]
`<entry code="SLUS-01042" title="Parasite Eve II [CD1] [U] [SLUS-01042]" region="NTSC-U" compatibility="5">
    <compatibility>No Issues</compatibility>
    <version-tested>0.1-908-g9f22684</version-tested>
    <comments>Works Perfect (Tested By Dark Frost And Game Verified By Redump.org)</comments>
</entry>`

Metal Slug X [U] [SLUS-01212]
`<entry code="SLUS-01212" title="Metal Slug X [U] [SLUS-01212]" region="NTSC-U" compatibility="5">
    <compatibility>No Issues</compatibility>
    <version-tested>0.1-908-g9f22684</version-tested>
    <comments>Works Perfect (Tested By Dark Frost And Game Verified By Redump.org)</comments>
</entry>`

Doom [U] [SLUS-00077]
`<entry code="SLUS-00077" title="Doom [U] [SLUS-00077]" region="NTSC-U" compatibility="4">
    <compatibility>Graphical/Audio Issues</compatibility>
    <version-tested>0.1-908-g9f22684</version-tested>
    <comments>Graphic Change Line İn 5x Upscaling, if Drop Graphic 1x Works Perfect (Tested By Dark Frost And Game Verified By Redump.org)</comments>
</entry>`

Chaos Break [E] [SLES-03107]
`<entry code="SLES-03107" title="Chaos Break [E] [SLES-03107]" region="PAL" compatibility="0">
    <compatibility>Unknown</compatibility>
    <version-tested>0.1-908-g9f22684</version-tested>
    <comments>Main İntro Video Slowly Works, İngame Not Have Bug (Tested By Dark Frost And Game Verified By Redump.org)</comments>
</entry>`

MediEvil II [U] [SCUS-94564]
`<entry code="SCUS-94564" title="MediEvil II [U] [SCUS-94564]" region="NTSC-U" compatibility="5">
    <compatibility>No Issues</compatibility>
    <version-tested>0.1-908-g9f22684</version-tested>
    <comments>Works Perfect (Tested By Dark Frost And Game Verified By Redump.org)</comments>
</entry>`

Vampire Hunter D [U] [SLUS-01138]
`<entry code="SLUS-01138" title="Vampire Hunter D [U] [SLUS-01138]" region="NTSC-U" compatibility="0">
    <compatibility>Unknown</compatibility>
    <version-tested>0.1-908-g9f22684</version-tested>
    <comments>İntro Video Works But, Blackscreen issue İn Main Menu, need Fixed Main Screen, Not Playable Yet :( (Tested By Dark Frost And Game Verified By Redump.org)</comments>
</entry>`

C-12 - The Final Resistance [U] [SCUS-94666]
`<entry code="SCUS-94666" title="C-12 - The Final Resistance [U] [SCUS-94666]" region="NTSC-U" compatibility="5">
    <compatibility>No Issues</compatibility>
    <version-tested>0.1-908-g9f22684</version-tested>
    <comments>Works Perfect (Tested By Dark Frost And Game Verified By Redump.org)</comments>
</entry>`

Carmageddon [E] [SLES-01960]
`<entry code="SLES-01960" title="Carmageddon [E] [SLES-01960]" region="PAL" compatibility="0">
    <compatibility>Unknown</compatibility>
    <version-tested>0.1-908-g9f22684</version-tested>
    <comments>Works Good, But Sometime FPS Limiter Wont Work (Tested By Dark Frost And Game Verified By Redump.org)</comments>
</entry>`

**Comment by stenzek** [comment]
Thank you for the compatibility entries. I'll add them soon.

In the future, could you please post them in the compatibility thread? Just makes it easier for me to keep track of :)

**Comment by stenzek** [comment]
Merged with master compatibility list in https://github.com/stenzek/duckstation/commit/379e5083a4a0a009d625fc6544299475bc909c19
