### ISSUE TITLE
Victory Spike (Japan) hangs instantly after BIOS

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#475]
![Capture](https://user-images.githubusercontent.com/31968468/82737020-30929700-9d71-11ea-85d2-13569fc58aef.PNG)

**Comment by stenzek** [comment]
Linked list DMA going off to null pointer land again...

It's easy to "fix" by breaking the transfer, but I want to to test how the console behaves rather than throwing a hack fix in there...

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/e293c22cde601c4799321e911f02cf1f5c915046

**Comment by kurayami6** [comment]
Fixed.
