### ISSUE TITLE
Title screen music is broken in V.I.P. (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#477]
[vip.zip](https://github.com/stenzek/duckstation/files/4672259/vip.zip)

![SLUS-01228_2020-05-21_09-27-15](https://user-images.githubusercontent.com/31968468/82737206-94698f80-9d72-11ea-93ca-372915ebd69c.png)

**Comment by stenzek** [comment]
Is this still happening on the latest build? Can't seem to reproduce.

**Comment by kurayami6** [comment]
Fixed as of the latest version.
