### ISSUE TITLE
The first screen of Vegas Games 2000 (USA) takes too long.

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#478]
In Duckstation it takes 23 seconds for this screen to transition to the next one. In Beetle It only takes 7

![SLUS-00836_2020-05-21_04-23-16](https://user-images.githubusercontent.com/31968468/82737254-1fe32080-9d73-11ea-9e02-dc73e9ebeca9.png)

**Comment by stenzek** [comment]
Is this still an issue on the latest builds with the DMA changes?

**Comment by kurayami6** [comment]
Fixed as of the latest version.
