### ISSUE TITLE
Pro Pinball series no music or sound fx

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#48]
Pro Pinball - Big Race USA (USA)
Pro Pinball - Fantastic Journey (USA)
Pro Pinball - Timeshock! (USA)
all 3 nothing but black screens

**Comment by benderscruffy** [comment]
![pinball](https://user-images.githubusercontent.com/2696404/76504544-e3e23400-6482-11ea-9163-efc56983ee1f.PNG)

**Comment by stenzek** [comment]
Well, this was a crazy one. The game renders in full 480i resolution, but has a rather interesting way what I can only guess is checking which field is currently being scanned out. It copies a white pixel to VRAM, enables the "skip odd/even lines depending on which field is being displayed" bit, draws a 1x1 pixel of a different colour, and then reads it back to the CPU. If the value has changed, then that line is not currently being displayed.

Why they did this, and do it 100+ times per frame is kinda beyond me. Why not just poll the status bit? I guess they must've had their reasons.

I have a patch to fix the game, but it requires additional work to implement in the hardware backends. Will finish soon.

**Comment by stenzek** [comment]
Should be fixed in latest master.

You'll probably want to play this game with the software renderer though. Due to the readbacks, it runs **very** slow in the hardware renderers. On the Intel GPU in my laptop, D3D is considerably faster than the GL renderer, and the NVIDIA GPU can run full speed, but barely.

**Comment by benderscruffy** [comment]
ok they go ingame now but no music or sound fx

**Comment by stenzek** [comment]
Music/sound appears to be working fine here, at least in Fantastic Journey. Try checking the SPU debug screen and seeing if any of the volumes are 0%, and if some of the voices are flashing white.

**Comment by benderscruffy** [comment]
i only tested big race and none of the volumes were 0% and none of the voices were flashing white

**Comment by stenzek** [comment]
As far as I can tell the music/sfx seems to be working in these games.
