### ISSUE TITLE
The video on the briefing screen in Uprising X (USA) is broken with all renderers 

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#480]
![SLUS-00686_2020-05-22_04-52-06](https://user-images.githubusercontent.com/31968468/82737339-cc250700-9d73-11ea-8949-dda53f83d8a4.png)

**Comment by stenzek** [comment]
It this still broken in the latest build?

**Comment by kurayami6** [comment]
Yes.

**Comment by stenzek** [comment]
I can't seem to reproduce what it is in the screenshot above.

**Comment by kurayami6** [comment]
Then it MUST be a bug if only one of us is getting it.

**Comment by stenzek** [comment]
Barely noticable in the latest build, probably needs precise MDEC timing.
