### ISSUE TITLE
There's a coloured line on the title screen of U.S. Navy Fighters (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#481]
On the right side of the screen. Happens with all crop modes.

![SLPS-00994_2020-05-23_05-04-27](https://user-images.githubusercontent.com/31968468/82737378-17d7b080-9d74-11ea-9007-ca4bed12b87c.png)

**Comment by stenzek** [comment]
Might just be a case of usually being hidden on CRTs - the game's configuring an X offset of 1 pixel (which is why it gets the line on the right).

**Comment by kurayami6** [comment]
Might be. I have no way of checking.

**Comment by kurayami6** [comment]
This does not happen on real hardware. My TV hides nothing and there's no line. 

![Uploading IMG_20200710_124831.jpg…]()

**Comment by kurayami6** [comment]
I've confirmed this doesn't happen on real hardware.

**Comment by stenzek** [comment]
Fixed by https://github.com/stenzek/duckstation/commit/4d1880091eb03173a77ef39047096c4c2688cc2f
