### ISSUE TITLE
Graphics take a few seconds to switch to high resolution in Velldeselba Senki - Tsubasa no Kunshou (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#482]
Even if I start the emulator with the resolution at x4, when the level starts the graphics will be at native res for a few seconds before automatically switching.

![SCPS-10027_2020-05-21_04-26-58](https://user-images.githubusercontent.com/31968468/82737454-684f0e00-9d74-11ea-9be5-a180fc888eae.png)

![SCPS-10027_2020-05-21_03-31-58](https://user-images.githubusercontent.com/31968468/82737460-6d13c200-9d74-11ea-8198-5a1757f09d35.png)

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/38fc843541d2a111c856b1e0bd7cf3f9b5476c1d

**Comment by kurayami6** [comment]
Fixed.
