### ISSUE TITLE
Graphical glitches in Umi no Oh! Yah! (Japan) with all renderers

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#483]
OpenGL and D3D11 at x4

![SLPS-01623_2020-05-22_10-06-16](https://user-images.githubusercontent.com/31968468/82737560-368a7700-9d75-11ea-95f8-212ce80d0445.png)

OpenGL at x1

![umi2](https://user-images.githubusercontent.com/31968468/82737572-4c983780-9d75-11ea-8702-3358b4669a4c.PNG)

D3D11 at x1 and software

![umi](https://user-images.githubusercontent.com/31968468/82737578-57eb6300-9d75-11ea-9e42-1b4efefa1fa7.PNG)

**Comment by stenzek** [comment]
Sorry, I'm not seeing where the issue is here?

**Comment by kurayami6** [comment]
The blue garbage on the dude's nose.

**Comment by stenzek** [comment]
Ah, got it, thanks. Probably a texture coordinate issue.

**Comment by stenzek** [comment]
OpenGL renderer is unofficially deprecated, and otherwise it's a typical upscaling issue.
