### ISSUE TITLE
Trying to start a mission in Vigilante 8 (USA) (v1.1) causes the game to reset itself

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#484]
After the loading screen finishes the screen will turn black and the opening logo will appear, followed by the start menu. 

![SLUS-00510_2020-05-24_04-25-34](https://user-images.githubusercontent.com/31968468/82737821-02b05100-9d77-11ea-940a-677b2ead813b.png)

**Comment by stenzek** [comment]
Might also be fixed by https://github.com/stenzek/duckstation/commit/1494f2bc75b5c68b92d5f8f3831860e473e01b4a

**Comment by kurayami6** [comment]
Fixed.
