### ISSUE TITLE
Starting a mission in Vigilante 8 - 2nd Offense (USA) causes the game to crash

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#485]
![Capture](https://user-images.githubusercontent.com/31968468/82737906-6dfa2300-9d77-11ea-9536-6bbf0cbc12a4.PNG)

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/1494f2bc75b5c68b92d5f8f3831860e473e01b4a

**Comment by kurayami6** [comment]
Fixed.
