### ISSUE TITLE
Speed and graphical issues in Rollcage Stage II (Europe) 

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#486]
The logos, opening video and language selection screen all go by in only a few seconds. Graphics on the main menu also flicker.

![SCES-01922_2020-05-25_02-39-45](https://user-images.githubusercontent.com/31968468/82759516-57180700-9e31-11ea-817a-3f433104ba12.png)

![SCES-01922_2020-05-25_02-39-42](https://user-images.githubusercontent.com/31968468/82759523-5b442480-9e31-11ea-947a-079d68d82613.png)

**Comment by stenzek** [comment]
Probably timing related.

**Comment by TzakShrike** [comment]
This doesn't happen anymore, at least for me.

**Comment by stenzek** [comment]
It's an issue which only happens if you use the dual shock controller

**Comment by Shideravan** [comment]
Doesn't happening to me in USA version on 0.1-2499-g770dd5a6.

**Comment by stenzek** [comment]
Fixed with the latest timing changes.
