### ISSUE TITLE
Strange looping sound effect during the loading screen before a match in Ultraman Tiga & Ultraman Dyna - Aratanaru Futatsu no Hikari (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#487]
I've confirmed this doesn't happen on real hardware.

[SLPS-01455_2020-05-25_08-17-46.zip](https://github.com/stenzek/duckstation/files/4674517/SLPS-01455_2020-05-25_08-17-46.zip)

![SLPS-01455_2020-05-25_08-17-52](https://user-images.githubusercontent.com/31968468/82766228-a295d980-9e60-11ea-9e51-af013ed97b09.png)

**Comment by stenzek** [comment]
Seems to be the left-over reverb from the BIOS which is apparently never cleared from sound RAM, when the game re-enables reverb, it's still there until the buffer loops around and it gets overwritten.

**Comment by kurayami6** [comment]
This is the same problem as Twilight Hen so I'm gonna close this and merge it.
