### ISSUE TITLE
A bit of the BIOS sound effect plays during the loading screen after the opening FMV in Twilight Syndrome - Kyuumei Hen (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#488]
At least it sounds like the BIOS. 

[SLPS-00405_2020-05-25_09-02-16.zip](https://github.com/stenzek/duckstation/files/4674621/SLPS-00405_2020-05-25_09-02-16.zip)

**Comment by kurayami6** [comment]
UEFA Champions League - Season 2000-2001 (Europe) has what seems to be the same problem during the first loading screen. 

[SLES-03262_2020-05-25_09-38-21.zip](https://github.com/stenzek/duckstation/files/4674625/SLES-03262_2020-05-25_09-38-21.zip)

![SLES-03262_2020-05-25_09-37-00](https://user-images.githubusercontent.com/31968468/82767571-ef32e200-9e6b-11ea-862a-f42ca4f2e1d6.png)

**Comment by stenzek** [comment]
Does turning on fast boot change it at all? If it doesn't happen, then you could be correct about it being part of the BIOS chime.

**Comment by kurayami6** [comment]
Turning on fast boot fixes it. Must be the BIOS then.

**Comment by stenzek** [comment]
Interesting. Must end up playing that part of RAM somehow, will need to investigate.

**Comment by kurayami6** [comment]
Thoroughbred Breeder II Plus (Japan) has the same problem. Right after you start a new game.

[2020-06-05_15-14-33.zip](https://github.com/stenzek/duckstation/files/4734069/2020-06-05_15-14-33.zip)

**Comment by kurayami6** [comment]
Ultraman Tiga & Ultraman Dyna - Aratanaru Futatsu no Hikari (Japan) has the same problem. Halfway through the loading screen before a match.

[SLPS-01455_2020-05-25_08-17-46.zip](https://github.com/stenzek/duckstation/files/4734079/SLPS-01455_2020-05-25_08-17-46.zip)

**Comment by stenzek** [comment]
Merging with https://github.com/stenzek/duckstation/issues/407 as the underlying cause is the same.
