### ISSUE TITLE
Enhancement - Option to load entire ISO into RAM on or near startup

### ISSUE THREAD

**Issue by TzakShrike** [stenzek/duckstation#489]
Would it be possible to have an option to load the entirety of an ISO into RAM early? Perhaps on load, or streamed into RAM during the opening minutes of the game?
As all PSX games are <1GB, and RAM is pretty plentiful these days, it'd be a nice way to take disk access (or network access) out of the equation.
It might not realistically be much of a benefit in many cases given disc reads are already done asynchronously, but it could definitely help for streaming across a network.

**Comment by stenzek** [comment]
This was implemented in https://github.com/stenzek/duckstation/commit/9496c992f7da5bb8644c91d0f093a4f6ab239e5a
