### ISSUE TITLE
Roswell Conspiracies - Aliens, Myths & Legends (USA) no music or sound fx

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#49]
during gameplay you only hear your gun fire any other time there is nothing

**Comment by stenzek** [comment]
Please re-check on latest master, I've pushed some changes for CDDA.

**Comment by benderscruffy** [comment]
music plays ingame but is missing from developers screens and intro

**Comment by stenzek** [comment]
Please re-test the audio issue on latest master.

**Comment by benderscruffy** [comment]
fixed
