### ISSUE TITLE
Screen vibrates constantly in True Pinball (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#490]
![SLUS-00337_2020-05-25_14-24-42](https://user-images.githubusercontent.com/31968468/82778075-9e36e400-9e93-11ea-84c5-8af7acd7cef0.png)

**Comment by stenzek** [comment]
So from what I can tell this is rendering in 480 lines mode in a different manner to most games - it has two framebuffers, one for each field, rather than interleaving them. Will require some re-working of the display shaders.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/e368dbbadc8ea1ad840656688d0b986ea3c25cc7

**Comment by kurayami6** [comment]
It now works perfectly with the software renderer. As expect it's beyond broken with hardware. Should this be closed now?

![Capture](https://user-images.githubusercontent.com/31968468/82835185-a11eec80-9f06-11ea-8f76-f507a4d0ed1d.PNG)

**Comment by stenzek** [comment]
Make sure you don't have disable interlacing checked.

I probably should handle that case better...

**Comment by kurayami6** [comment]
D3D11 is fine but this is what it looks like with OpenGL at x1 without "disable interlacing" checked.

![Capture](https://user-images.githubusercontent.com/31968468/82835552-b7797800-9f07-11ea-8efd-405de0d7813b.PNG)

**Comment by stenzek** [comment]
Okay will look into it tomorrow

**Comment by stenzek** [comment]
OpenGL shoudl be fixed with https://github.com/stenzek/duckstation/commit/cb66889856ac49bd8cecbe733213baabc94009d9

**Comment by kurayami6** [comment]
Fixed. These pinball games will be the death of us all.
