### ISSUE TITLE
Garbage line on the loading screen of True Love Story - Remember My Heart (Japan)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#491]
On the black screen after you choose the scenario. Then when the name entry screen appears the left side of the screen flickers. Probably because that line is still there screwing things up. Strangely it only seems to happen with OpenGL at x1. All other renderers and resolutions are fine.

![Capture2](https://user-images.githubusercontent.com/31968468/82783425-c7f70780-9ea1-11ea-8499-f9420f86be6d.PNG)

![Capture](https://user-images.githubusercontent.com/31968468/82783436-cfb6ac00-9ea1-11ea-99a8-5b2b298f5530.PNG)

**Comment by kurayami6** [comment]
Tetris Plus (USA) has the same problem. 

![Capture](https://user-images.githubusercontent.com/31968468/83867658-214a1b00-a76d-11ea-8dae-44d4eee83c2f.PNG)

**Comment by stenzek** [comment]
OpenGL vertex positioning issue - closing as OpenGL renderer is "deprecated".
