### ISSUE TITLE
Triple Play Baseball (USA) crashes instantly after BIOS

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#492]
![capture2](https://user-images.githubusercontent.com/31968468/82838664-3d99bc80-9f10-11ea-802b-bc1acd9b4396.PNG)

![Capture](https://user-images.githubusercontent.com/31968468/82838672-45596100-9f10-11ea-96dc-63c79a22f37f.PNG)

**Comment by stenzek** [comment]
Can't seem to reproduce on latest build.

**Comment by kurayami6** [comment]
Fixed.
