### ISSUE TITLE
Certain reverbed SFX last too long in Final Fantasy VII

### ISSUE THREAD

**Issue by ggrtk** [stenzek/duckstation#493]
Occurs when selecting a new game, gaining exp after a battle, when casting magic, etc. It's the most obvious when selecting a new game since there's no other audio playing in the background. It sounds as if the reverbed sample is being repeated / sustained for too long / keyed off too late.

Also occurs in Final Fantasy Tactics for the sound effect played when starting a new game, when skipping the cutscene right after starting a new game, some sound effects when using skills, etc. Might happen in other Square titles too since a lot of them make plenty use of reverb.

**Comment by stenzek** [comment]
Think this might've just been an ADSR issue - sounds better with https://github.com/stenzek/duckstation/commit/8eb3ac69b2c63733739336bff76bae8cebc87a15.

Might still not be perfect though.

**Comment by stenzek** [comment]
As far as I can tell this is improved now - if it is still sounding incorrect, please let me know.
