### ISSUE TITLE
Triple Play 98 (Japan) hangs on the loading screen before a match

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#494]
After the opening Video the game hangs on a black screen. Turning on "Show VRAM" shows that it's frozen on the loading screen.

![SLPS-00887_2020-05-26_08-37-57](https://user-images.githubusercontent.com/31968468/82846719-99267300-9f2d-11ea-8ab9-1cd4a37a2575.png)

![Capture](https://user-images.githubusercontent.com/31968468/82846779-dee33b80-9f2d-11ea-9a42-b21b9b3cdad3.PNG)

**Comment by Zet-sensei** [comment]
The game plays fine on my end after a verification on 0.1-1998-g43bafe1a (SW renderer and all 3 CPU Modes tested).

The issue should probably be closed.

**Comment by stenzek** [comment]
Thanks for checking.
