### ISSUE TITLE
Can't start battle or arcade mode in Trash It (Europe)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#496]
I apologize if this is just me being too dumb to figure it out but when I try and select either of those options the game just plays a noise and nothing happens. It works fine in Beetle.

![SLES-00256_2020-05-26_10-40-20](https://user-images.githubusercontent.com/31968468/82884330-ee42a300-9f86-11ea-9281-8c4663088b71.png)

**Comment by stenzek** [comment]
Try enabling a second controller.

**Comment by kurayami6** [comment]
That fixes it. I guess I was just being dumb.

**Comment by stenzek** [comment]
To be fair, it's not super obvious it's expecting a second controller.
