### ISSUE TITLE
Chaos Break - FMVs slow on hardware renderers due to oversized VRAM writes

### ISSUE THREAD

**Issue by DarkFrost89** [stenzek/duckstation#497]
Just Main İntro Have a Problem,İntro Video Half And Not Working Good
I did'nt Tested USA Version Because Only This Games Released EU,And JAPAN
https://youtu.be/ysdHEv1YunU

**Comment by stenzek** [comment]
Not really a bug per-say, just a result of oversized VRAM writes being slow in the hardware renderers.

Still a valid issue though - this can be implemented more efficiently.

**Comment by DarkFrost89** [comment]
> 
> 
> Not really a bug per-say, just a result of oversized VRAM writes being slow in the hardware renderers.
> 
> Still a valid issue though - this can be implemented more efficiently.

stenzek ı test japan version of this game but ı didnt have any video problem here issue just EU version Only

**Comment by DarkFrost89** [comment]
Stenzek Latest commit 23436f0 make a new problem
flickering screen
in chaos break eu version
https://cdn.discordapp.com/attachments/695823554712698962/714830398105845790/2020-05-26_16-15-01.mkv
japan version is working good 
maybe LibCrypt Make This Error
I Found This List LibCrypt Protected games
https://docs.google.com/spreadsheets/d/1Yvh6m5whajKC73-EjcES73IJlQGphc_I9FKSzWE_fok/edit#gid=0

**Comment by stenzek** [comment]
That's because you have "Disable Interlacing" turned on. Fixed in https://github.com/stenzek/duckstation/commit/445bd02cad2f5658670e0cccaa9997a02557adf2

**Comment by kurayami6** [comment]
I can't understand a word of what he wrote but the opening logo screen is broken with all renderers. 

![SLES-03107_2020-06-04_20-59-42](https://user-images.githubusercontent.com/31968468/83749375-f7c6bc00-a6a6-11ea-8a67-ff6baf3a7be5.png)

**Comment by stenzek** [comment]
I suspect this might be normal.. the slow VRAM writes were fixed a while back.
