### ISSUE TITLE
All videos are broken with OpenGL as of the latest version. 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#498]
Every game I've tested looks like this with OpenGL as of the latest version. 

![SLUS-00447_2020-05-26_20-54-38](https://user-images.githubusercontent.com/31968468/82892945-aa09cf80-9f93-11ea-8a3e-8fea5a428ac7.png)

**Comment by stenzek** [comment]
Fixed by https://github.com/stenzek/duckstation/commit/04f131f97991508c9d0006d07498bf5e51e92913
