### ISSUE TITLE
Music track doesn't loop properly in Treasure Gear (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#499]
[SLPS-00819_2020-05-27_04-00-18.zip](https://github.com/stenzek/duckstation/files/4684121/SLPS-00819_2020-05-27_04-00-18.zip)

![SLPS-00819_2020-05-27_04-02-03](https://user-images.githubusercontent.com/31968468/82934544-f7eff900-9fce-11ea-85fa-63c7e90e0643.png)

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/2dd7f48d9743d02213a67f7bce0121ff87834f91

**Comment by kurayami6** [comment]
Fixed.
