### ISSUE TITLE
Twisted Metal 4 (USA) glitchy graphics line down bottom of the screen (Opengl)

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#50]
![tm4](https://user-images.githubusercontent.com/2696404/76079055-dccca900-5fde-11ea-997d-95ffd79bf20c.PNG)

**Comment by stenzek** [comment]
Will be fixed with upcoming overscan changes.

**Comment by stenzek** [comment]
Fixed with overscan changes from a while back. The issue still persists with the "all borders" option, but this is expected. Use "None" or "Only Overscan Area" (the default).
