### ISSUE TITLE
Graphical glitches on the status screen of Transport Tycoon 3D - Sl Kara Hajimeyou!! (Japan)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#500]
OpenGL and D3D11 at x4. The textures inside the boxes are off-centre. 

![SLPS-00694_2020-05-27_06-12-48](https://user-images.githubusercontent.com/31968468/82947311-2bd51980-9fe3-11ea-933b-fa5a0ef9acc3.png)

OpenGL and D3D11 at x1. See the black X on the left-hand side? In the bottom right corner of that box is a little bit of green.

![Capture2](https://user-images.githubusercontent.com/31968468/82947570-9e45f980-9fe3-11ea-9c87-491dc213c8f9.PNG)

In Software the textures are all aligned properly and that little bit of green isn't there. 

![Capture](https://user-images.githubusercontent.com/31968468/82947605-ad2cac00-9fe3-11ea-8b74-06a441b403f9.PNG)

**Comment by stenzek** [comment]
Doesn't seem to be an issue any more.
