### ISSUE TITLE
Toushinden (Japan) (v1.1) runs way too fast

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#501]
The narrator speaks too fast and the characters move in fast forward.

![PSXEXE_2020-05-27_14-42-43](https://user-images.githubusercontent.com/31968468/82978870-f4895b80-a028-11ea-980d-ff1b05a4c5d3.png)

The log spams this at a million miles an hour.

![Capture](https://user-images.githubusercontent.com/31968468/82978987-44682280-a029-11ea-80ac-918df6d9d49d.PNG)

**Comment by stenzek** [comment]
Fixed with GTE timings.
