### ISSUE TITLE
Touge Max G (Japan) hangs instantly after BIOS

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#502]
Turning on "Show VRAM" shows that it's frozen on this screen.

![SLPS-02361_2020-05-27_18-01-36](https://user-images.githubusercontent.com/31968468/82993973-c4e84c80-a044-11ea-8c5d-e236a385a966.png)

![Capture](https://user-images.githubusercontent.com/31968468/82994004-d0d40e80-a044-11ea-8be6-da12f784270c.PNG)

**Comment by kurayami6** [comment]
Still broken as of the latest version.

**Comment by CookiePLMonster** [comment]
With a redump verified image, works fine on the latest version, and I remember it working for at least two weeks. Can probably be closed.

![image](https://user-images.githubusercontent.com/7947461/93689322-c5ae5e00-facd-11ea-82a8-8b69832ed01b.png)

**Comment by stenzek** [comment]
Great, thanks for checking!
