### ISSUE TITLE
Opening the status screen in Chrono Cross (Japan) (Disc 1) causes the game to hang

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#503]
The game will immediately hang on a black screen while the music loops endlessly.

![2020-05-27_18-28-02](https://user-images.githubusercontent.com/31968468/82996319-1d6d1900-a048-11ea-905c-6418bf74b992.png)

![Capture](https://user-images.githubusercontent.com/31968468/82996339-26f68100-a048-11ea-98b7-b68448ef417c.PNG)

**Comment by stenzek** [comment]
Interestingly, only seems to affect the Japanese version.

**Comment by andercard0** [comment]
It is happening with US version as well, I was about to raise a issue for it. But just found here. :p

**Comment by stenzek** [comment]
Duplicate of #553.
