### ISSUE TITLE
Graphical garbage after the opening FMV in Total NBA '96 (Europe)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#504]
Between when the opening FMV ends and when the main menu appears. Only shows up for about 1 frame.

![SCES-00067_2020-05-28_05-34-41](https://user-images.githubusercontent.com/31968468/83064518-3ce65f00-a0a5-11ea-93ec-3cf1172f9098.png)

**Comment by stenzek** [comment]
Seems to be your standard 8-bit->5-bit switch. Needs console verification.
