### ISSUE TITLE
Ninja: Shadow of Darkness hangs on the loading screen in Total Play (France) (Demo)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#505]
![SLED-02126_2020-05-28_07-41-39](https://user-images.githubusercontent.com/31968468/83075270-e84bdf80-a0b6-11ea-9de0-2b1a39c01705.png)

The log just repeats this endlessly. 

![Capture](https://user-images.githubusercontent.com/31968468/83075286-f00b8400-a0b6-11ea-9652-b3baf6761be7.PNG)

**Comment by stenzek** [comment]
Can't seem to reproduce on latest build.

**Comment by kurayami6** [comment]
Still happening for me unfortunately. That's strange. The log is a bit different now though. 

![Capture](https://user-images.githubusercontent.com/31968468/84592671-c5794380-ae8a-11ea-9265-08f50f09c473.PNG)

**Comment by Zet-sensei** [comment]
Same problem for me.

For information, it exists two versions of the disc, with different Serial IDs.

Total Play (France) (SLED-01872) --> with Tomb Raider demos + Ninja one, which is working fine.
Total Play (France) (SLED-02126) --> with other demos + another Ninja version, which isn't working like kurayami6 explained.

**Comment by Kurayami7** [comment]
This is fixed and can be closed. Probably fixed by the same change that fixed Tomb Raider since it was the same error message for both. 

![SLED-02126_2021-02-27_22-50-06](https://user-images.githubusercontent.com/77198254/109386356-4cede080-794e-11eb-8823-22eae7e6fa77.png)

**Comment by stenzek** [comment]
Sounds like it, yeah, based on that log. Thanks for checking.
