### ISSUE TITLE
Some of the opening screens in Tom and Jerry in House Trap (USA) vibrate with OpenGL and D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#508]
It's very noticeable at x1 resolution and less noticeable but still present at x4.

These screens vibrate.

![SLUS-01191_2020-05-28_21-26-41](https://user-images.githubusercontent.com/31968468/83136097-4239bd00-a12a-11ea-88d8-9c8b360e372d.png)

![SLUS-01191_2020-05-28_21-26-44](https://user-images.githubusercontent.com/31968468/83136122-4d8ce880-a12a-11ea-9f1e-1daed96058cd.png)

![SLUS-01191_2020-05-28_21-26-52](https://user-images.githubusercontent.com/31968468/83136137-51b90600-a12a-11ea-90f6-8c2e69a0654f.png)

![SLUS-01191_2020-05-28_21-27-00](https://user-images.githubusercontent.com/31968468/83136146-54b3f680-a12a-11ea-8ec3-80165718cfcc.png)

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/7d66569d699a7fd160d94513f7aeeff4bdefb8f7

**Comment by kurayami6** [comment]
Fixed.
