### ISSUE TITLE
Marvel vs. Capcom - Clash of Super Heroes (USA) glitchy characters (Opengl)

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#51]
![marvel](https://user-images.githubusercontent.com/2696404/76079445-9e83b980-5fdf-11ea-9a2b-c87227b1a1e6.PNG)
![marvel1](https://user-images.githubusercontent.com/2696404/76079449-a04d7d00-5fdf-11ea-916b-c53ece2b7834.PNG)
![marvel2](https://user-images.githubusercontent.com/2696404/76079453-a2174080-5fdf-11ea-8083-54464b7f1229.PNG)

**Comment by stenzek** [comment]
Does it also occur with the D3D renderer?

**Comment by benderscruffy** [comment]
no problems with D3D renderer

**Comment by stenzek** [comment]
Should be fixed in latest master.
