### ISSUE TITLE
Tom and Jerry in House Trap (Europe) hangs on the memory card screen

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#510]
![SLES-03181_2020-05-29_09-18-27](https://user-images.githubusercontent.com/31968468/83203994-0afcf780-a18e-11ea-9a30-e4dc217e164a.png)

![Capture](https://user-images.githubusercontent.com/31968468/83204009-14865f80-a18e-11ea-9a02-defd4b0e4ba4.PNG)

**Comment by stenzek** [comment]
Game crashes with system error.

**Comment by kurayami6** [comment]
Tiny Toon Adventures - Plucky's Big Adventure (Europe) does the same thing.

![SLES-03547_2020-06-01_10-19-04](https://user-images.githubusercontent.com/31968468/83366386-1a7c7a80-a3f2-11ea-9fc8-64a57f6dec45.png)

**Comment by stenzek** [comment]
Fixed with the latest timing changes.
