### ISSUE TITLE
Fox Junction (Japan) - FMVs split (or glitching)

### ISSUE THREAD

**Issue by AbandonedWitchStarlight** [stenzek/duckstation#512]
The opening FMVs in Fox Junction seem to split (like its glitching). 
Happens in both OpenGL and D3D11.
![SLPS-01355_2020-05-29_20-02-59](https://user-images.githubusercontent.com/53141496/83258109-45937e00-a1e8-11ea-9191-3f75b5dbf42b.png)

**Comment by stenzek** [comment]
It's likely the game is displaying non-interleaved interlaced video, which was implemented recntly. Make sure you have "Disable Interlacing" turned off.

We'll probably want to override it for these games at some point...

**Comment by AbandonedWitchStarlight** [comment]
Thanks for the advice, because it turns out the whole game is also having the same problem with the interlacing option turned on

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation/commit/3848276fa2d50f2a353f6043b7b150c7de87641f should fix this even with interlacing disabled.
