### ISSUE TITLE
Switching renderers while the emulator is paused breaks the pause button

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#514]
Doing so while a game is paused causes the emulator to unpause itself. Pressing the pause button again after that will cause it to go insane and rapidly pause and unpause itself.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/de8aef4f44c6e179a3aba5a3854ad287f0eaaccb

**Comment by kurayami6** [comment]
Fixed.
