### ISSUE TITLE
Loading time discrepancy in Tokimeki Memorial Drama Series Vol. 3 - Tabidachi no Uta (Japan) (Disc 1)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#515]
In Duckstation the loading time between starting the game and the name entry screen appearing is 28 seconds. In Beetle it's 17.

![SLPM-86224_2020-05-30_13-03-01](https://user-images.githubusercontent.com/31968468/83318633-fbf37380-a279-11ea-884d-5006ffaf6f3a.png)

![SLPM-86224_2020-05-30_13-02-03](https://user-images.githubusercontent.com/31968468/83318634-feee6400-a279-11ea-9e06-571be4c6de64.png)

**Comment by stenzek** [comment]
Any idea how long the console takes for these loading time differences? Not saying DuckStation is correct, but I don't trust Beetle when it comes to timing either.

**Comment by stenzek** [comment]
It's doing... something during this time, not reading from disc.

**Comment by stenzek** [comment]
Was never verified on console, and isn't breaking the game.
