### ISSUE TITLE
Army Men 3D [U] [SLUS-00491] Main Menü Sound Stucking

### ISSUE THREAD

**Issue by DarkFrost89** [stenzek/duckstation#517]
After 0.1-967-gf856a8a Army Men 3D [U] [SLUS-00491] Have a New Problem
Sound Stuck Main Menu
https://youtu.be/0Xl7A-_4GVM

**Comment by kurayami6** [comment]
The game has now regressed to the point there is no music on the title screen at all.

**Comment by stenzek** [comment]
Was fixed with https://github.com/stenzek/duckstation/commit/559dc23e4ed2752b6bb8c0f6bf9a5feaa1a7a945
