### ISSUE TITLE
Strange controller behaviour in Tiny Toon Adventures - Plucky's Big Adventure (USA)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#518]
If I start the game with the controller set to analogue I can't move the character. Switching to digital causes the game to automatically pause itself. I unpause it and the game controls fine. After that both analogue and digital work fine. I can switch between the two and control the character. 

![SLUS-01393_2020-06-01_10-38-14](https://user-images.githubusercontent.com/31968468/83366763-7811c680-a3f4-11ea-8ad5-56ee9411890c.png)

**Comment by stenzek** [comment]
The pause-on-switch might be related to sending the incorrect ID after switching. As for the analog mode, is it possible this game does not support analog mode?

**Comment by ggrtk** [comment]
Can't reproduce this issue on latest build. Both Digital Controller and Analog Controller (in both modes) work properly.
