### ISSUE TITLE
The opening logo of Time Bokan Series - Bokan desu yo (Japan) is broken with disable interlacing ticked

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#519]
![SLPS-01211_2020-06-02_10-54-29](https://user-images.githubusercontent.com/31968468/83468316-bf18be00-a4bf-11ea-92af-372bcd4d751d.png)

**Comment by kurayami6** [comment]
Time Bokan Series - Bokan GoGoGo (Japan) has the same problem during gameplay.

![SLPS-03133_2020-06-02_11-14-38](https://user-images.githubusercontent.com/31968468/83469325-bd042e80-a4c2-11ea-99d0-7df39e9a0549.png)

**Comment by stenzek** [comment]
This is likely working as intended. The games use non-interleaved interlaced display.

That said, I could probably halve the display height if interleaved scanout is disabled. But really, you want interlacing enabled for these games, as you're potentially losing half the vertical resolution.

**Comment by stenzek** [comment]
Behavior with interlacing force-disabled should be improved in https://github.com/stenzek/duckstation/commit/3848276fa2d50f2a353f6043b7b150c7de87641f

**Comment by kurayami6** [comment]
Fixed.
