### ISSUE TITLE
Star Wars - Dark Forces (USA) graphic glitches (Opengl)

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#52]
![star](https://user-images.githubusercontent.com/2696404/76079893-a6902900-5fe0-11ea-974d-fc3d1571a039.PNG)

**Comment by stenzek** [comment]
This is because of how it draws vertical lines using triangles. On the PSX GPU, I believe every row/line inside a triangle will have at least one pixel shaded. This doesn't occur on PC GPUs which have sub-pixel precision.

**Comment by kurayami6** [comment]
Please don't resort to hacks. Emulation is never going to improve if everyone just does things the same wrong way as everyone else.

**Comment by stenzek** [comment]
@kurayami6 It's not so much a "hack" as working within the limitations of PC graphics APIs (detecting when there is "lines" and drawing them as lines).

**Comment by stenzek** [comment]
This should be fixed on D3D11 now. Not sure about GL, it might still be broken there. You must use 1x resolution scale.

**Comment by stenzek** [comment]
Issue does not seem to be present in OpenGL anymore at 1x resolution scale. Due to the way the game renders, it would not benefit from upscaling anyway.
