### ISSUE TITLE
Triggering the first cutscene in Akuji The Heartless permanently lowers the framerate 

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#521]
The game runs at a stable 30 FPS until you trigger this cutscene in the first level at which point the framerate instantly drops to exactly 20 FPS and never increases. 

![SLUS-00715_2020-06-02_22-17-30](https://user-images.githubusercontent.com/31968468/83532270-5e29ce00-a531-11ea-80d9-dc871fa8fd0b.png)

**Comment by Shideravan** [comment]
Did you checked with other emulators or in the console hardware if this issue isn't a bug from the game itself?

**Comment by stenzek** [comment]
Was never confirmed whether this occurs on console.

Seem to only be when you skip the cutscene, so it is possible it is a game bug.
