### ISSUE TITLE
The loading screen before the team selection screen will sometimes freeze temporarily in Three Lions (UK)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#522]
I have no idea if it's triggered by specific conditions. Out of the seven times I played the game, the issue occurred three times. The spinning disc icon will freeze for about 20 seconds before resuming.

![SLES-00876_2020-06-02_19-44-53](https://user-images.githubusercontent.com/31968468/83532584-ca0c3680-a531-11ea-99fd-91bf1d0ea70a.png)

The log begins spamming this as soon as the freeze occurs and stops as soon as the freeze ends.

![Capture](https://user-images.githubusercontent.com/31968468/83532695-f3c55d80-a531-11ea-9793-e9ce17f72f34.PNG)

**Comment by stenzek** [comment]
Those messages are normal, I believe it's usually part of modchip detection.
