### ISSUE TITLE
Exiting a photo in the gallery in Thunder Force V - Perfect System (Japan) will cause the screen to glitch very briefly

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#523]
Go to digital viewer, graphics viewer, select a photo and when you exit out of the photo the screen will very briefly glitch out. I can't describe exactly what it looks like but I've confirmed it doesn't happen on real hardware or in Beetle PSX.

![SLPS-01406_2020-06-02_13-53-40](https://user-images.githubusercontent.com/31968468/83533087-78b07700-a532-11ea-82cf-3aa879c0245c.png)

**Comment by stenzek** [comment]
Doesn't show with interlacing off. There's a one frame delay where the "old" field will still be displayed with it on.
