### ISSUE TITLE
Load time discrepancy in Total NBA 98 (Europe)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#524]
In Duckstation the loading screen before a match takes about 28 or 29 seconds. On real hardware it takes exactly 40 seconds. Which is great for this particular game but obviously means something is running too fast and might have negative consequences in other games. 

![SCES-01079_2020-06-03_15-33-23](https://user-images.githubusercontent.com/31968468/83599479-9839b500-a5af-11ea-8e15-fe3494ec3373.png)

**Comment by stenzek** [comment]
Doesn't seem to be causing any issues.
