### ISSUE TITLE
 Frame time has greatly increased

### ISSUE THREAD

**Issue by Basmurd** [stenzek/duckstation#525]
Strange thing. On all renders, but not in all games, I checked SpiderMan and Dune 2000, the frame time increased and reached 42-49ms, which is quite a lot. Any guesses?
![duckstation-qt-x64-ReleaseLTCG_xX9gFY1uHQ](https://user-images.githubusercontent.com/61318181/83739691-9b3fae80-a65e-11ea-982a-04402a87ab7a.png)
![duckstation-qt-x64-ReleaseLTCG_Gyx8qBn4cs](https://user-images.githubusercontent.com/61318181/83739701-9e3a9f00-a65e-11ea-9d84-ecf56625a211.png)

**Comment by Basmurd** [comment]
And some more information.  SpiderMan has frame drops of up to 20 FPS. Especially noticeable with a spider instinct.

**Comment by stenzek** [comment]
- What are your system specifications?
- Which renderer are you using?
- Are you using the recompiler?
- Does using the null audio backend change anything?
- Check the GPU debug stats window when the frame drops occur - are there a high number of VRAM reads/batches drawn?

**Comment by stenzek** [comment]
Closing because of a lack of response. If things are still slow, please provide the requested details and I will look into it.
