### ISSUE TITLE
Madden NFL 99 (USA) has broken music on the title screen and sometimes crashes.

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#526]
Music on the title screen is broken. It sounds like parts of it are being skipped. 

[SLUS-00729_2020-06-04_22-01-40.zip](https://github.com/stenzek/duckstation/files/4729811/SLUS-00729_2020-06-04_22-01-40.zip)

![SLUS-00729_2020-06-04_22-09-23](https://user-images.githubusercontent.com/31968468/83755141-74aa6380-a6b0-11ea-9171-ec80d5f55e05.png)

Sometimes the game will crash after the cutscene with Madden. Out of the five times I played the game it crashed twice. 

![SLUS-00729_2020-06-04_22-03-52](https://user-images.githubusercontent.com/31968468/83754977-34e37c00-a6b0-11ea-98e5-1caf1ab9d1db.png)

![Capture](https://user-images.githubusercontent.com/31968468/83754999-3b71f380-a6b0-11ea-964e-6140f8bcb0c2.PNG)

**Comment by stenzek** [comment]
Looks to be something to do with SPU interrupts, voices 0/1 trigger the IRQ when it should be triggered by 23/24.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/98987643b329151cd0b82c92e8985ea26e0933ce
