### ISSUE TITLE
Wrong size rumble motor triggered with controller test app

### ISSUE THREAD

**Issue by jpchow26** [stenzek/duckstation#527]
I ran the Padtest 1.0 homebrew with my XBox One pad

https://shendosoft.blogspot.com/2014/03/padtest-ps1-homebrew.html

From the site:
"To test rumble press L3 for big motor and R3 for small motor."

In DuckStation L3 triggers the small motor and R3 triggers the big motor

**Comment by stenzek** [comment]
Fixed by https://github.com/stenzek/duckstation/commit/009e474c51b764a08da8d8173adab381a102c0d5, confirmed in Discord.
