### ISSUE TITLE
Games stutter quite badly if the emulator is minimized with Software or D3D11 + vsync 

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#528]
The most obvious example is Tokimeki Memorial Drama Series Vol. 3 - Tabidachi no Uta (Japan) (Disc 1). It runs in slow motion. 

![Capture](https://user-images.githubusercontent.com/31968468/83832281-9f3a0200-a72c-11ea-9e56-48335ba630ed.PNG)

**Comment by stenzek** [comment]
Not happening on my desktop with a NVIDIA GPU. Might be Windows 7 related.
