### ISSUE TITLE
Increasing or decreasing the volume slider while a game is running causes terrible audio stuttering

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#529]
Very easy to test. Just start a game and quickly drag the slider left or right.

![Capture](https://user-images.githubusercontent.com/31968468/83832437-0657b680-a72d-11ea-962e-9b3335d6c78c.PNG)

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/b2595a3b3b7ac1b19b494ce1d026067113f0afbe

**Comment by kurayami6** [comment]
Fixed.
