### ISSUE TITLE
Skeleton Warriors (Europe) Opengl error

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#53]
when you start fighting the skeletons the error keeps on popping up
![skeleton](https://user-images.githubusercontent.com/2696404/76130057-53e85880-6044-11ea-937e-88276e2b9fd6.PNG)

**Comment by benderscruffy** [comment]
Nicktoons Racing (USA) same error
![racing](https://user-images.githubusercontent.com/2696404/76131186-77ad9d80-6048-11ea-95d1-d46b1efa418a.PNG)

**Comment by stenzek** [comment]
This should no longer happen on latest master. Please update if the error is still popping up.

**Comment by benderscruffy** [comment]
fixed
