### ISSUE TITLE
Starting a new game in Thoroughbred Breeder - Sekai Seiha-hen (Japan) (v1.0) causes the screen to glitch out

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#531]
Choose start and the graphics will break and the screen will flicker in and out of existence for a few seconds. Doesn't happen in Beetle PSX.

![SLPS-01324_2020-06-05_14-56-20](https://user-images.githubusercontent.com/31968468/83838609-124b7480-a73d-11ea-9338-bbe2d4f1d17b.png)

![SLPS-01324_2020-06-05_14-55-40](https://user-images.githubusercontent.com/31968468/83838618-1b3c4600-a73d-11ea-9bd4-7c8d48453454.png)

**Comment by stenzek** [comment]
Seems to be another one related to FIFO size...

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/16c47f455318dda2190d218b1133c3abc945091e

Make sure to remove the `GPUFIFOSize` line under `[Hacks]` in your `settings.ini`, or set it to `16`, as the default has changed.

**Comment by kurayami6** [comment]
Fixed.
