### ISSUE TITLE
Audio pop as the title screen fades in in Thousand Arms (USA) (Disc 1)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#532]
This doesn't happen in Beetle PSX.

[SLUS-00845_2020-06-05_15-56-01.zip](https://github.com/stenzek/duckstation/files/4734199/SLUS-00845_2020-06-05_15-56-01.zip)

![SLUS-00845_2020-06-05_15-56-30](https://user-images.githubusercontent.com/31968468/83842238-c3560d00-a745-11ea-9ec7-a374037446b3.png)

**Comment by stenzek** [comment]
Our good old friend BIOS reverb strikes again. Doesn't seem to happen with fast boot. Merging with https://github.com/stenzek/duckstation/issues/407
