### ISSUE TITLE
Theme Aquarium (Japan) usually hangs on the loading screen after the name entry screen

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#534]
Of the 4 times I tried it, it hung 3 times. 

![SLPS-01768_2020-06-05_17-19-31](https://user-images.githubusercontent.com/31968468/83849721-2c904d00-a753-11ea-8220-36cea9b1b2b2.png)

It has Error detection code. Not sure if that makes any difference.

![Capture](https://user-images.githubusercontent.com/31968468/83851596-f6080180-a755-11ea-875b-baaae55bc4cb.PNG)

**Comment by stenzek** [comment]
Unable to reproduce.
