### ISSUE TITLE
Tenga Seiha (Japan) hangs instantly after BIOS screen

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#536]
Hangs on the Playstation logo while the log spams for a few seconds before stopping as well. 

![SLPS-00712_2020-06-06_22-54-01](https://user-images.githubusercontent.com/31968468/83944751-33998700-a849-11ea-8d9f-e017c274d006.png)

![Capture](https://user-images.githubusercontent.com/31968468/83944752-372d0e00-a849-11ea-84f2-646cfd6d10c6.PNG)

**Comment by stenzek** [comment]
Does boot, just takes a while because of GPU timeouts.

**Comment by stenzek** [comment]
Doesn't require TTY logging enabled anymore, as it boots with icache enabled.
