### ISSUE TITLE
The piracy warning screen of Tenchu - Stealth Assassins (Europe) flickers with all renderers 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#537]
![SLES-01374_2020-06-07_04-03-39](https://user-images.githubusercontent.com/31968468/83951305-e979cb00-a873-11ea-8492-417029db77c9.png)

**Comment by stenzek** [comment]
Another FIFO size issue...

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/16c47f455318dda2190d218b1133c3abc945091e

Make sure to remove the `GPUFIFOSize` line under `[Hacks]` in your `settings.ini`, or set it to `16`, as the default has changed.

**Comment by kurayami6** [comment]
Fixed.
