### ISSUE TITLE
Graphics load incorrecty at the beginning of Tecmo World Golf - Japan (USA)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#539]
At the beginning of the game there's a few frames of green garbage. On real hardware this garbage loads diagonally up but in Duckstation it loads left to right. 

Here's Duckstation.

![Capture](https://user-images.githubusercontent.com/31968468/83972781-792b8200-a925-11ea-8168-358ebaacaa62.PNG)

And here's real hardware.

![Capture2](https://user-images.githubusercontent.com/31968468/83972792-8ba5bb80-a925-11ea-9d2f-ac4667eb6c5f.PNG)

https://www.youtube.com/watch?v=Yi4ngiFK39k&t=44s

**Comment by stenzek** [comment]
Probably MDEC timing (which is approximate). If it is just timing related, not really something I'm interested in looking into as I'm not going for that level of accuracy, but if there's something else going on then it's valid.
