### ISSUE TITLE
Formula One 99 (USA) (En,Fr,Es) stuck on loading screen

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#54]
![formula](https://user-images.githubusercontent.com/2696404/76130870-44b6da00-6047-11ea-9e3d-6adedc5e7df6.PNG)

**Comment by benderscruffy** [comment]
gets past the loading screen now but next screen is nothing but a black screen
![formula](https://user-images.githubusercontent.com/2696404/78331860-7a54d180-75b9-11ea-837d-590576df246f.PNG)

**Comment by kurayami6** [comment]
Still an issue as of the latest version.

![Capture](https://user-images.githubusercontent.com/31968468/83701926-8bb86980-a64e-11ea-861b-4a892fcdb7cd.PNG)

**Comment by Shideravan** [comment]
Reproduced here. This happens in both interpreter and recompiler modes.

**Comment by stenzek** [comment]
Yep, apparently the game needs the CPU's instruction cache emulated. Not going to be working any time soon.

**Comment by Zet-sensei** [comment]
Should be closed.

The game works now with icache implemented.
