### ISSUE TITLE
The second loading screen in Tecmo Stackers (USA) briefly glitches out with all renderers

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#540]
In software, OpenGL and D3D11 at x1 the screen turns black for a few frames. In OpenGL and D3D11 at higher resolution the graphics break for a few frames.

![SLUS-00315_2020-06-08_01-39-18](https://user-images.githubusercontent.com/31968468/83973355-3d92b700-a929-11ea-90dc-518235bbd197.png)

![SLUS-00315_2020-06-08_01-39-44](https://user-images.githubusercontent.com/31968468/83973359-408da780-a929-11ea-831b-2dc346b8ccbc.png)

**Comment by stenzek** [comment]
The "breakage" is because of an oversized VRAM write.

**Comment by stenzek** [comment]
Was never confirmed on console.

**Comment by ggrtk** [comment]
These momentary blank frames are reproducible on original hardware.
