### ISSUE TITLE
Progressing dialogue in Teitoku no Ketsudan II (Japan) causes the screen to glitch out

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#541]
When you get to this dialogue screen, pressing the button to advance the dialogue causes the screen to glitch out and stay frozen like this for several seconds. This is with the software renderer. 

![Capture](https://user-images.githubusercontent.com/31968468/83973808-20abb300-a92c-11ea-9a0d-7076ddcbcba5.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/83973814-2903ee00-a92c-11ea-887a-8add0321b934.PNG)

**Comment by stenzek** [comment]
Probably related to the other issues where the screen display is all over the place when switching resolutions.

**Comment by ggrtk** [comment]
Took a quick look at this -- looks to be a drawing-related issue rather than a display one. The drawing offset is supposed to be at the center of a 320x240 drawing area, but the drawing area is being set to the full VRAM with offset at (0, 0) before the OT gets DMA transferred.

**Comment by stenzek** [comment]
Interesting. Do you know if it does set the correct offset at some point? Wondering if it needs tighter sync and the game is relying on a bunch of empty draw packets at the start taking some time away, similar to Vampire Hunter D.

**Comment by ggrtk** [comment]
The offset values being used earlier in the same frame seem reasonably correct. It either uses (0, 0) to (319, 239) with offset (160, 120) or (0, 0) to (319, 479) with offset (160, 360), depending on which framebuffer is being displayed/drawn. In both cases, the drawing area gets set to the full VRAM with offset (0, 0) before the OT transfer so the graphics always end up drawn to the upper left corner of VRAM. I took a look at this in Nocash and it looks like there's an extra pair of draw area and offset calls missing in DuckStation that would result in proper drawing behavior.

Nocash
```
Set draw area and offset to framebuffer
Set draw area and offset to VRAM
Set draw area and offset to framebuffer
Set draw area and offset to VRAM
Set draw area and offset to framebuffer
Multiple CPU to VRAM copies (placed in far right of VRAM)
Framebuffer clear (VRAM fill)
OT draw framebuffer
```

DuckStation
```
Set draw area and offset to framebuffer
Set draw area and offset to VRAM
Set draw area and offset to framebuffer
Set draw area and offset to VRAM
Multiple CPU to VRAM copies (placed in far right of VRAM)
Framebuffer clear (VRAM fill)
OT draw framebuffer
```

**Comment by stenzek** [comment]
Fixed in latest build as far as I can tell.
