### ISSUE TITLE
[Bug] Game Serial Code not read correctly when SYSTEM.CNF contains tab characters instead of spaces

### ISSUE THREAD

**Issue by TzakShrike** [stenzek/duckstation#542]
In particular, this fails:
```
BOOT	= cdrom:\SLUS_010.80;1
TCB		= 4
EVENT	= 16
STACK	= 801fe000
```
(bloody width 8 tabs. These are actually width 4 and used for alignment)

and this doesn't:
```
BOOT = cdrom:SLPM_860.47;1
TCB = 4
EVENT = 16
STACK = 801FFF00

```

and this also doesn't:
```
BOOT = cdrom:\SCPS_100.85;1
TCB = 4
EVENT = 16
STACK = 801FFFF0
```

**Comment by TzakShrike** [comment]
Haven't read enough to grok it properly yet, but at first blush I'd swap
else if (ch == ' ')
to
else if (ch == ' ' || ch == '\t')
on line 66 of core/game_list.cpp
Sorry for not submitting a proper patch :)

**Comment by TzakShrike** [comment]
Affects Chrono Cross, probably others?

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/7b4b2d5dc5de3c8023c269858d796a9a0798974f
