### ISSUE TITLE
Switching from windowed to fullscreen while D3D11 is compiling shaders causes the screen to get stuck for a few seconds

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#543]
![Capture](https://user-images.githubusercontent.com/31968468/83997330-80907100-a9a1-11ea-871e-482f91d681ff.PNG)

**Comment by stenzek** [comment]
Not really fixable. The emu thread isn't accepting window resize events while it's busy compiling shaders. Ideally you shouldn't see the message on startup anyway because it should be hitting the cache.

**Comment by kurayami6** [comment]
I get the message when I start Teitoku no Ketsudan III (Japan) for the first time.

**Comment by stenzek** [comment]
Every time the game starts?

**Comment by kurayami6** [comment]
No, only the first time. I can get the message to appear every time If I empty the cache.

**Comment by stenzek** [comment]
I don't really see where the problem is then.

For what it's worth, you should never need to empty the shader cache. The shader cache on my system was created on the 3rd of April. The only reason you'd ever need to clear it out would be to clear out old/duplicate shaders to save space.

**Comment by kurayami6** [comment]
Alright well if there's nothing you can do than close this.
