### ISSUE TITLE
Team Buddies (USA) hangs on the loading screen before a match

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#544]
In Beetle PSX this screen takes about 7 seconds. In Duckstation it takes about 1 minute 30 seconds for the loading bar to fill and then it hangs. 

![SLUS-00869_2020-06-08_19-26-44](https://user-images.githubusercontent.com/31968468/84014953-7761cd00-a9be-11ea-81f2-de7533c7fab2.png)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/d4665e8b22ef8442c0bb03c1ee66fbbdfd313188
