### ISSUE TITLE
Loud audio buzzing after you finish a mission in Taxi 2 (France) 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#545]
[SLES-03597_2020-06-08_19-38-00.zip](https://github.com/stenzek/duckstation/files/4745123/SLES-03597_2020-06-08_19-38-00.zip)

**Comment by stenzek** [comment]
Seems to be reading a bunch of XA sectors from the wrong file, because it gets an EOF and resets.

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/0710e3b6d384526ed939f742f8f657623bb354bb

**Comment by kurayami6** [comment]
Fixed.
