### ISSUE TITLE
Title screen music in Taiho Shichauzo - You're Under Arrest (Japan) (Disc 1) is slightly too slow

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#546]
It's very obviously wrong when compared to how it sounds in Beetle PSX.

[SLPM-86782_2020-06-09_15-02-15.zip](https://github.com/stenzek/duckstation/files/4750198/SLPM-86782_2020-06-09_15-02-15.zip)

![SLPM-86782_2020-06-09_15-48-07](https://user-images.githubusercontent.com/31968468/84110826-f27fbd80-aa68-11ea-94f4-3f22f5f94008.png)

**Comment by stenzek** [comment]
Could you please compare against Mednafen, not Beetle?

Mednafen can record audio from the game using the `-soundrecord filename.wav` command line parameter.

Although this does sound like the tempo is a bit over the place.

**Comment by kurayami6** [comment]
No need for that. I'll check it on real hardware when I get the chance. Probably tonight or tomorrow.

**Comment by stenzek** [comment]
Needs GPU FIFO size = 16.

**Comment by stenzek** [comment]
What a strange one. The FIFO size breaks the music sequencer because the game sits there polling until the GPU is idle after getting the DMA interrupt, with interrupt disabled. With the smaller FIFO size, the DMA interrupt doesn't fire until later, meaning the sequencer doesn't fall behind.

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/16c47f455318dda2190d218b1133c3abc945091e

Make sure to remove the `GPUFIFOSize` line under `[Hacks]` in your `settings.ini`, or set it to `16`, as the default has changed.

**Comment by kurayami6** [comment]
Fixed.
