### ISSUE TITLE
Graphical glitch in Castlevania - Symphony of the Night (USA) when killing the zombie soldiers

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#547]
When you attack or kill them the blood effect has green pixels mixed in. This happens with all renderers.

![night](https://user-images.githubusercontent.com/31968468/84227872-e5c29e80-ab28-11ea-9fd4-80964310b4bb.png)

Here's footage of them being killed on real hardware.  

https://youtu.be/C9wue7Yo8BA?t=223

**Comment by stenzek** [comment]
Looks like an upscaled screenshot. Does it happen at 1x scale?

**Comment by kurayami6** [comment]
Yes it does. 

![Capture](https://user-images.githubusercontent.com/31968468/84427568-781d8c00-ac68-11ea-9221-f78ca859baa6.PNG)

**Comment by kurayami6** [comment]
A few more graphical glitches. 

A line through the skull sprite.

![Capture](https://user-images.githubusercontent.com/31968468/84474389-18f26280-acce-11ea-9a71-3d01a42b5ecc.PNG)

A black line on the border between light and dark when entering the cave in the ice cavern.

![Capture2](https://user-images.githubusercontent.com/31968468/84474458-36273100-acce-11ea-91dc-7b4e6f29acd3.PNG)

**Comment by kurayami6** [comment]
No idea why this happened. At some point attacking started causing a red line to appear next to Alucard, then after a while it stopped happening. 

![Capture](https://user-images.githubusercontent.com/31968468/84489773-89f14480-ace5-11ea-9eed-ef39e94aeb12.PNG)

**Comment by stenzek** [comment]
Seems to be interpolation related, but in the case of the green blood the responsible texel is in the middle of the sprite. So maybe due to interpolation that texel doesn't get used on the console? But I find that hard to believe :/

**Comment by stenzek** [comment]
I believe this was confirmed to occur on console.
