### ISSUE TITLE
Doom (USA) can see thru walls and ceiling (Opengl)

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#55]
![doom](https://user-images.githubusercontent.com/2696404/76130989-ad05bb80-6047-11ea-8862-7d94012c81d2.PNG)

**Comment by stenzek** [comment]
This is the same underlying issue as #52. Software renderer will work fine.

**Comment by stenzek** [comment]
Issue does not seem to be present in OpenGL anymore at 1x resolution scale. Due to the way the game renders, it would not benefit from upscaling anyway.
