### ISSUE TITLE
Vulkan Renderer - Known Issues

### ISSUE THREAD

**Issue by stenzek** [stenzek/duckstation#554]
DuckStation now has a nice shiny Vulkan hardware renderer. To use it, just switch backends like normal. Initial benchmarks show a sizable performance improvement (30-40%) on Intel GPUs, but less so on AMD and NVIDIA versus Direct3D.

But more importantly it lets me deprecate the OpenGL renderer, which is quite annoying in some ways. I'm not going to drop it any time, so if you don't have Vulkan capable hardware and run Linux you won't be forced to Software, I'm just not considering bugs in the OpenGL renderer to be critical anymore.

For the most part, it shouldn't be any more buggy than the other renderers - a lot of code is shared. But there are a few known issues which I haven't got around to fixing yet:

- [x] ~Mask bit test is broken (games like Silent Hill don't display correctly). I'm planning on rewriting how this works to avoid flushing so much anyway.~
- [x] ~There is no way to select the GPU. It will default to the first GPU in multi-GPU systems. I need to add an adapter selector to the UI.~
- [x] Images in the save save state selector UI and SDL frontend are broken - this is because ImGui's Vulkan renderer does not support multiple textures. I need to write my own.
- [x] ~No support for MoltenVK on macOS (yet). I'll add this eventually.~
- [ ] Binary bloat - glslang adds a megabyte or so to the binary. I might use a dll here with shaderc or something instead.
- [x] ~libretro core does not support Vulkan (yet). But to be fair it doesn't support D3D yet either.~
- [x] ~Requires dual-source blend and large texture buffers, so it won't work on mobile drivers. I have plans to work around this.~

**Comment by azoreseuropa** [comment]
Thanks for the news. I will wait for this:

 No support for MoltenVK on macOS (yet). I'll add this eventually.
