### ISSUE TITLE
Vulkan crashes on macOS

### ISSUE THREAD

**Issue by azoreseuropa** [stenzek/duckstation#555]
Here is the text copying for you. My picture showing:

<img width="299" alt="Screen Shot 2020-06-20 at 9 26 24 AM" src="https://user-images.githubusercontent.com/16481778/85198485-a6d6da80-b2d8-11ea-9d16-7df80c9e63a1.png">

Crashes in zip here:
[Vulkan crashes.zip](https://github.com/stenzek/duckstation/files/4807651/Vulkan.crashes.zip)

**Comment by stenzek** [comment]
I guess you're providing your own MoltenVK binary, because I don't have one in git ;)

https://github.com/stenzek/duckstation/commit/f54876deb03eda0053331955df2a589d3a4e759c should hopefully fix the crash (assuming MoltenVK still supports the old extension), but I can't test it at the moment.

**Comment by azoreseuropa** [comment]
> I guess you're providing your own MoltenVK binary, because I don't have one in git ;)
> 
> [f54876d](https://github.com/stenzek/duckstation/commit/f54876deb03eda0053331955df2a589d3a4e759c) should hopefully fix the crash (assuming MoltenVK still supports the old extension), but I can't test it at the moment.

Rebuilding and no longer crash but error:

[mvk-error] VK_ERROR_INITIALIZATION_FAILED: vkCreateMacOSSurfaceMVK(): On-screen rendering requires a layer of type CAMetalLayer.

<img width="329" alt="Screen Shot 2020-06-20 at 10 47 26 AM" src="https://user-images.githubusercontent.com/16481778/85200016-87917a80-b2e3-11ea-8167-04afbccf300f.png">

<img width="415" alt="Screen Shot 2020-06-20 at 10 47 16 AM" src="https://user-images.githubusercontent.com/16481778/85200027-911ae280-b2e3-11ea-85a1-6c866ed73e8e.png">

**Comment by stenzek** [comment]
Yeah, sounds like I'll need to create the layer. I was hoping I could skip that and just pass it a NSView instead. Will do it when I can use a mac again.

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation/commit/eaca5eca079ff5bb5c45a3b8377e5e7b5f7ef8c5 creates the layer as needed.

But, looks like VRAM writes are borked (probably something texel-buffer related, the same issue which is causing Dolphin's GPU texture decoding to break on MVK). I need to come up with a SSBO-based solution for mobile drivers anyway, so that's another use case for it.

**Comment by stenzek** [comment]
VRAM writes shouldn't be broken anymore. It seems to work okay on an NVIDIA GPU, but OpenGL also works there. Note you'll need to provide your own dylib from MoltenVK (gfx-portability crashes due to some push constant issue), and set it on the command line via `LIBVULKAN_PATH=/path/to/libMoltenVK.dylib /path/to/duckstation-qt` until I sort out a .app bundle.

**Comment by azoreseuropa** [comment]
> VRAM writes shouldn't be broken anymore. It seems to work okay on an NVIDIA GPU, but OpenGL also works there. Note you'll need to provide your own dylib from MoltenVK (gfx-portability crashes due to some push constant issue), and set it on the command line via `LIBVULKAN_PATH=/path/to/libMoltenVK.dylib /path/to/duckstation-qt` until I sort out a .app bundle.


I dont understand. What do you mean your own dylib ? I guess I will wait until you sort out a .app bundle. It will be much better than exec to be honest. :)

**Comment by stenzek** [comment]
> I dont understand. What do you mean your own dylib ? I guess I will wait until you sort out a .app bundle. It will be much better than exec to be honest. :)

If you were getting MVK errors before, it means you had a libvulkan somewhere :) So whatever you were doing before should be sufficient.

**Comment by azoreseuropa** [comment]
> If you were getting MVK errors before, it means you had a libvulkan somewhere :) So whatever you were doing before should be sufficient.


Impressive. It's working properly now. I can't wait for a .app soon.

**Comment by stenzek** [comment]
Great, thanks for the feedback!
