### ISSUE TITLE
Judge Dredd (USA) Graphical Errors

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#556]
On all renderers, when playing with a lightgun, the white flash that shows up whenever you shoot only covers a small box.
![image](https://user-images.githubusercontent.com/50224630/85208524-17d0bf00-b2e6-11ea-857f-4c5775c10190.png)
![image](https://user-images.githubusercontent.com/50224630/85208530-20c19080-b2e6-11ea-812d-110012b5890b.png)
Instead of covering the entire screen https://youtu.be/90BZQ2DiQcU?t=341.

Additionally, the effects on a hurt enemy are broken on Vulkan.
![image](https://user-images.githubusercontent.com/50224630/85208563-68481c80-b2e6-11ea-8566-c2876b484011.png)
Opengl and Software (the enemy on the right):
![image](https://user-images.githubusercontent.com/50224630/85208622-c248e200-b2e6-11ea-9aba-8d26490eae48.png)

**Comment by stenzek** [comment]
I think the white flash might be fixed when using the overscan crop mode instead of none.

Transparency issues should hopefully be fixed with https://github.com/stenzek/duckstation/commit/73cdd676adcce8fbfc50f60aa74c5a375a35ae29

**Comment by HeroponRikiBestest** [comment]
Fixed
