### ISSUE TITLE
Viewpoint (USA) black screen when starting level 1

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#56]
cdrom error  in log

**Comment by stenzek** [comment]
Please retry on latest master, and post the command number from the log.

**Comment by benderscruffy** [comment]
![view](https://user-images.githubusercontent.com/2696404/76136823-bd7e5c00-6070-11ea-92fd-249829236747.PNG)

**Comment by benderscruffy** [comment]
fixed
