### ISSUE TITLE
Silent Hill Flashlight Vulkan / Slow Drop-down List

### ISSUE THREAD

**Issue by IPeluchito** [stenzek/duckstation#569]
![SLUS-00707_2020-06-24_20-15-32](https://user-images.githubusercontent.com/64821708/85643913-1e02ca80-b65b-11ea-872b-ab2c287d15f3.png)

![Duckstation](https://user-images.githubusercontent.com/64821708/85644056-85207f00-b65b-11ea-92fe-1c613f3039c7.png)
**Windows 8.1 / RTX 2060
Silent Hill Problem only in Vulkan**

**Comment by stenzek** [comment]
The drop down list thing is a Qt bug. Will have to check the flashlight, is it also broken in OpenGL?

**Comment by IPeluchito** [comment]
**Confirmed**, the problem happens only in **Vulkan**, DX11 and OpenGL work perfectly ... and I just discovered another problem but with the audio there is a strange background sound when fighting dogs, I will see if I upload it to **YouTube**...

**Comment by stenzek** [comment]
Please try with the latest build (or https://github.com/stenzek/duckstation/commit/15afe4f4367bdad3975457e6e897f264f3a527b8), the fix for Final Fantasy 9 might be related here.

**Comment by IPeluchito** [comment]
**Flashlight** and **Sound** issue **FIXED** in **Vulkan**, but **Sound** issue remains in **DirectX 11** and **Open GL**...
