### ISSUE TITLE
Resolution changes don't work with D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#57]
Only with OpenGL.

**Comment by stenzek** [comment]
Will need more detail for this one, as both D3D and GL go down the same code path for setting changes so this shouldn't be specific to a renderer.

 - Which frontend?
 - Are you changing it while emulation is running?
 - Are you using the hotkeys? (The hotkeys only temporarily change the scale, when you change any other setting the one which was chosen in the UI will be reset)

**Comment by kurayami6** [comment]
Using QT frontend. No I'm not using hotkeys. I think resolution scaling just doesn't work at all with D3D11. I can switch between resolutions while ingame with OpenGL just fine but as soon as I switch to D3D11 it automatically turns to native resolution regardless of what resolution I have it set to. 

With OpenGL

![Capture](https://user-images.githubusercontent.com/31968468/76135262-5f09ab80-6079-11ea-8b18-11929477f5d5.PNG)

And as soon as I switch to D3D11

![Capture2](https://user-images.githubusercontent.com/31968468/76135280-86f90f00-6079-11ea-8984-f8bec4457573.PNG)

**Comment by stenzek** [comment]
That's very strange. It works fine for me on both NVIDIA and Intel GPUs. I'm wondering if it's specific to this game and how it's scanning out the framebuffer (some behavior requires downsampling).

I've also added some logging to show the current settings on initialization/setting update, so this will display the internal rendering resolution in the log.

**Comment by kurayami6** [comment]
Tried with a different game. Same thing. I'm on Windows 7 if it makes a difference. I also tried setting the resolution before starting the game and it didn't make a difference. 

![Capture](https://user-images.githubusercontent.com/31968468/76135870-400e1800-607f-11ea-81fc-63597e589e08.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/76135873-4b614380-607f-11ea-9b95-a4a0b1aa53fd.PNG)

**Comment by stenzek** [comment]
What does the log show? You should see something like this:

![image](https://user-images.githubusercontent.com/11288319/76136156-3f26b780-607a-11ea-8f84-28115785b49c.png)

I'm now wondering if something is failing to create in the renderer and it's falling back to software.

**Comment by kurayami6** [comment]
![Capture](https://user-images.githubusercontent.com/31968468/76136421-528b5000-6085-11ea-9b15-f825429a4568.PNG)

**Comment by stenzek** [comment]
I think I see what's going on. Windows 7 isn't compatible with large/partial uniform buffers, but I didn't end up using the latter anyway. Pushed a fix to master, but I don't have any Win7 machines left so I can't test. Please let me know if it's still broken.

**Comment by kurayami6** [comment]
Using the latest version D3D11 instantly crashes with an error. OpenGL works fine. 

![Capture](https://user-images.githubusercontent.com/31968468/76138198-a4d66c00-6099-11ea-8c60-e0432b974173.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/76138202-abfd7a00-6099-11ea-97ba-642518f7b177.PNG)

**Comment by stenzek** [comment]
I've pushed a change which modifies the map behavior slightly, as well as adds additional logging to hopefully figure out what's going on. If it still throws the error, please paste the updated error output.

**Comment by stenzek** [comment]
Okay, latest push should hopefully fix things. It's going down a slower path, but there's not much else I can do for Windows 7, it's just missing features.

**Comment by kurayami6** [comment]
Fixed. Unfortunately Windows 10 is missing the feature of not being dogshit so I have to stay on 7 until Microsoft comes out with something better. 

![Capture](https://user-images.githubusercontent.com/31968468/76155819-bc6b2e80-6145-11ea-8eb9-7f2fbb819411.PNG)
