### ISSUE TITLE
Audio crackling when scrolling through menus or pressing buttons in Teitoku no Ketsudan III (Japan) with D3D11

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#570]
This crackling isn't picked up by dumping audio and seems to happen less each time you play the game. Each time it happens the emulator speed drops and the frametime shoots up.

![Capture](https://user-images.githubusercontent.com/31968468/85651535-a335c000-b6eb-11ea-85f6-7bdbb8c57c01.PNG)

This screen is the most reliable place to reproduce it. 

![SLPS-00788_2020-06-25_13-52-20](https://user-images.githubusercontent.com/31968468/85651577-c9f3f680-b6eb-11ea-8498-59159ce482a7.png)

**Comment by stenzek** [comment]
Not seeing any frame drops here.
