### ISSUE TITLE
Game pausing randomly in Moto Racer

### ISSUE THREAD

**Issue by picili** [stenzek/duckstation#572]
When in game, in Moto Racer (Europe) (En,Fr,De,Es,It,Sv), game pauses (as if pressing Start button) randomly (few times a minutes)

Controller Type: Port 1: Digital Controller. Port 2 : None

v0.1-1115-g0b261e8

**Comment by kurayami6** [comment]
Sounds like the same problem as Iznogoud (Europe)

**Comment by stenzek** [comment]
Can anyone confirm whether this just affects the PAL version? Might also be related to the Rollcage II issue.

**Comment by kurayami6** [comment]
Happens in the US version as well. 

![SLUS-00498_2020-06-27_20-54-57](https://user-images.githubusercontent.com/31968468/85920605-84385900-b8b8-11ea-9824-1478a3d50fbd.png)

**Comment by picili** [comment]
> 
> 
> Sounds like the same problem as Iznogoud (Europe)

Indeed, don't know abouit Rollcage, but two games from French devs.

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/bff5432879c4a3898358606269272f4f9d69ef8d

**Comment by picili** [comment]
Indeed, thanks !
