### ISSUE TITLE
Delay when run Emu

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#573]
I am having an issue always when I lauch emulator, it takes like 20 seconds to open, a friend said that when configured it to launch as administrator should fix this but it does not for me; still have a delay of 20 seconds to open the emulator. By the by, emulator is not in any windows partition I really dunno if this is important to mention or what else should quote here to troubleshoot this and provide more details on my end. 

Anything, just let me know I will inform if there is something missing. 

TY.

**Comment by stenzek** [comment]
Definitely shouldn't need to run as admin. No emulator should be.

Could you enable the log (settings -> advanced options), set it to the debug, and "enable system console". Then post the console window?

There isn't too much which happens before the main window is displayed, so I'm wondering if something is slowing down Qt's initialization. So, also check the SDL frontend and see if it has the same problem.

**Comment by andercard0** [comment]
Okay, here:
short log tho 🤔 

[   20.3191] I/SDLControllerInterface: Controller 0 inserted
[   20.3275] I/SDLControllerInterface: Opened controller 0 (instance id 0, player id 0): XInput Controller
[   20.3280] I/SDLControllerInterface: Rumble is supported on 'XInput Controller'
[   20.3281] I/ControllerInterface: Host controller 0 connected, updating input map
[   20.3285] I/SDLControllerInterface: Controller 0 axis scale set to 1.000000
[   20.3286] I/SDLControllerInterface: Controller 0 deadzone size set to 0.250000
[   20.3295] I/SDLControllerInterface: Controller 0 axis scale set to 1.000000
[   20.3296] I/SDLControllerInterface: Controller 0 deadzone size set to 0.250000
[   20.6586] E(CDImage::Open): Unknown extension '.log' from filename 'G:/Emuladores/Playstation 1 isos\CTR - Crash Team Racing (USA)\package.log'

**Comment by stenzek** [comment]
This is what I get:
```
[    0.2311] I/SDLControllerInterface: Controller 0 inserted
[    0.2319] I/SDLControllerInterface: Opened controller 0 (instance id 0, player id 0): XInput Controller
[    0.2324] I/SDLControllerInterface: Rumble is supported on 'XInput Controller'
[    0.2328] I/ControllerInterface: Host controller 0 connected, updating input map
[    0.2331] I/SDLControllerInterface: Controller 0 axis scale set to 1.000000
```

So yeah, sounds like it might be a Qt issue.

Did you try the SDL frontend? Does it have the same problem?

**Comment by andercard0** [comment]
Tried here it takes a bit more than 5 seconds to load. and take a look how it opens
![SDL](https://user-images.githubusercontent.com/43047877/85926506-5b8f6f80-b876-11ea-8c51-e55a0f10d4ba.PNG)

**Comment by stenzek** [comment]
Yes, the missing icon in SDL is a known issue with the Vulkan renderer. It only affects the main page and the save state UI.

The 5 second delay is probably mostly creating the Vulkan device, which takes a few seconds. (this doesn't happen in Qt until you boot a game).

So, pretty sure I can say this is something to do with Qt. Just no idea what it could be...

**Comment by stenzek** [comment]
Might be controller related. Does it have the same problem if you start the emu with the controller disconnected?

**Comment by andercard0** [comment]
> 
> 
> Might be controller related. Does it have the same problem if you start the emu with the controller disconnected?

Hey Sten, No! 
Actually, since last 2 updates the issue does not happen anymore. 
Here it is the log capture with and without a controller. 

**Without Controller** 
[    0.2303] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button11' to button
[    0.2306] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button12' to button
[    0.2307] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button13' to button
[    0.2308] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button14' to button
[    0.2309] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button4' to button
[    0.2310] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button6' to button
[    0.2311] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button3' to button
[    0.2312] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button0' to button
[    0.2313] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button1' to button
[    0.2314] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button2' to button
[    0.2315] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button9' to button
[    0.2316] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller axis 'Controller0/+Axis4' to button
[    0.2317] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button10' to button
[    0.2317] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller axis 'Controller0/+Axis5' to button
[    0.2318] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button7' to button
[    0.2319] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button8' to button
[    0.2323] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button5' to button
[    0.2331] W(CommonHostInterface::AddAxisToInputMap): Failed to bind controller axis 'Controller0/Axis0' to axis
[    0.2335] W(CommonHostInterface::AddAxisToInputMap): Failed to bind controller axis 'Controller0/Axis1' to axis
[    0.2339] W(CommonHostInterface::AddAxisToInputMap): Failed to bind controller axis 'Controller0/Axis2' to axis
[    0.2343] W(CommonHostInterface::AddAxisToInputMap): Failed to bind controller axis 'Controller0/Axis3' to axis

**With Controller**
[    0.2320] I/SDLControllerInterface: Controller 0 inserted
[    0.2325] I/SDLControllerInterface: Opened controller 0 (instance id 0, player id 0): XInput Controller
[    0.2327] I/SDLControllerInterface: Rumble is supported on 'XInput Controller'
[    0.2328] I/ControllerInterface: Host controller 0 connected, updating input map
[    0.2330] I/SDLControllerInterface: Controller 0 axis scale set to 1.000000
[    0.2332] I/SDLControllerInterface: Controller 0 deadzone size set to 0.250000
[    0.2335] I/SDLControllerInterface: Controller 0 axis scale set to 1.000000
[    0.2336] I/SDLControllerInterface: Controller 0 deadzone size set to 0.250000

If there is nothing else to troubleshoot I guess you could close this ticket! 
Thank You!

**Comment by andercard0** [comment]
Sorry Sten, Still Happening as follows No controller attached
Man, doesn't have a pattern. 🤔 

[   20.2768] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button11' to button
[   20.2771] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button12' to button
[   20.2772] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button13' to button
[   20.2773] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button14' to button
[   20.2774] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button4' to button
[   20.2774] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button6' to button
[   20.2775] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button3' to button
[   20.2776] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button0' to button
[   20.2777] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button1' to button
[   20.2777] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button2' to button
[   20.2778] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button9' to button
[   20.2779] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller axis 'Controller0/+Axis4' to button
[   20.2779] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button10' to button
[   20.2780] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller axis 'Controller0/+Axis5' to button
[   20.2781] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button7' to button
[   20.2781] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button8' to button
[   20.2786] W(CommonHostInterface::AddButtonToInputMap): Failed to bind controller button 'Controller0/Button5' to button
[   20.2794] W(CommonHostInterface::AddAxisToInputMap): Failed to bind controller axis 'Controller0/Axis0' to axis
[   20.2797] W(CommonHostInterface::AddAxisToInputMap): Failed to bind controller axis 'Controller0/Axis1' to axis
[   20.2801] W(CommonHostInterface::AddAxisToInputMap): Failed to bind controller axis 'Controller0/Axis2' to axis
[   20.2805] W(CommonHostInterface::AddAxisToInputMap): Failed to bind controller axis 'Controller0/Axis3' to axis

**Comment by stenzek** [comment]
Apparently this isn't happening anymore?

**Comment by andercard0** [comment]
Nope, still happening. : (

![log delay 2 - Controller ON](https://user-images.githubusercontent.com/43047877/90577429-490b2580-e197-11ea-962e-dbcfebcd74d3.png)

![log delay](https://user-images.githubusercontent.com/43047877/90577432-49a3bc00-e197-11ea-9407-0f022fe7f567.png)

Just for test purposes did a clean install and same results:

![delay clean install](https://user-images.githubusercontent.com/43047877/90577628-d77fa700-e197-11ea-8faf-dcd442e91e02.png)

**Comment by KrossX** [comment]
Try a build before the auto updater?
