### ISSUE TITLE
Paris-Marseille Racing II (France) - stuck at Memory Card check

### ISSUE THREAD

**Issue by picili** [stenzek/duckstation#574]
In Paris-Marseille Racing II (France), cannot pass the Memory Card page (press X, doesn't work)

0.1-1115-g0b261e8

**Comment by kurayami6** [comment]
Sounds like the same problem as Tom and Jerry in House Trap (Europe) and Tiny Toon Adventures - Plucky's Big Adventure (Europe).

**Comment by stenzek** [comment]
Doesn't seem to be registering any pad input at all. Might be related to the other PAL games with controller issues.

**Comment by stenzek** [comment]
Are you using the analog controller? This page https://www.mobygames.com/game/playstation/paris-marseille-racing-ii/techinfo suggests that the digital controller is not supported by the game.

**Comment by picili** [comment]
Tried using analog controller and got the same issue

**Comment by kurayami6** [comment]
Are you starting the emulator with the controls set to analogue or are you starting with digital and switching?

**Comment by stenzek** [comment]
Remember to right click -> full boot after changing the controller type (I'm adding an option to disable loading controllers from save states but for now you have to full boot it to apply the change).

**Comment by picili** [comment]
Got rid of the resume savestate in the file system anyway (btw, would be nice to be able to do it from within the interface)

And you are right, it works with analog controller ! (which is funny since the x button should not cause problem).

So I guess you can close the issue ;)

**Comment by kurayami6** [comment]
You can close the issue yourself.

**Comment by stenzek** [comment]
> Got rid of the resume savestate in the file system anyway (btw, would be nice to be able to do it from within the interface)

You can do that currently - right click -> Delete Save States. But there's no option to only delete the resume state, I can add that I guess.
