### ISSUE TITLE
Dialogue in certain cutscenes ends too early or is missing entirely in The Fireman 2, Pete and Danny (Japan)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#575]
Dialogue during the cutscene where you save the employee in the bathroom part way through level 2 ends to early. You can see their lips moving but there's no sound. 

![SLPS-00148_2020-06-28_20-48-31](https://user-images.githubusercontent.com/31968468/85949112-3135d300-b998-11ea-895b-ecaca36efb3d.png)

The conversation between Pete and Danny after you save the woman at the end of level 2 is completely silent. 

![SLPS-00148_2020-06-28_20-53-27](https://user-images.githubusercontent.com/31968468/85949126-4874c080-b998-11ea-8638-4de1fe6e2dd6.png)

**Comment by stenzek** [comment]
Not sure what's going on here. The game is pausing the CD-ROM, hence why the dialogue gets off.

**Comment by Shideravan** [comment]
I can confirm that still happening in 0.1-2499-g770dd5a6.
