### ISSUE TITLE
Analogue contols are completely broken in Firebugs (Europe) 

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#576]
When you get to gameplay the game behaves as if buttons are being pressed when they aren't. At the beginning of the race the ship will automatically start moving backwards. The pause button also doesn't work. Digital controller option work fine and analogue will also work fine if you start the game with digital and switch to it. 

![SCES-03884_2020-06-28_17-48-39](https://user-images.githubusercontent.com/31968468/85949211-db155f80-b998-11ea-8c48-d848d6e03eff.png)

**Comment by Shideravan** [comment]
The problem is fixed at 0.1-2499-g770dd5a6. The issue can be closed.

**Comment by stenzek** [comment]
Thanks for checking
