### ISSUE TITLE
Game Pausing Randomly

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#577]
There is bug maybe, before it starts second stage it pause from nothing then I am being force to push X and 'try again' then it start over! Fisrt print is the start of the gameplay then second is the issue happening.
Tried to change my joystick but same results.

If that matters, I was using Xbox 360 controller (first try) and Playstation 4 controller at my second try.

**Issue**: 
Game pausing randomly

**Game**: Bust a Groove
Region:USA

**Steps to reproduce the issue**: 
As soon as you get into the second stage and it happens on the 
start menu.

![Stage](https://user-images.githubusercontent.com/43047877/86063267-e4f29d80-ba40-11ea-93f7-92bd2e889da7.PNG)
![Stage2](https://user-images.githubusercontent.com/43047877/86063265-e3c17080-ba40-11ea-850b-ac6a6367dd7f.PNG)

**[Update]** 
Disregard this:
~~By the way second game **Bust a Groove 2** works great besides, controllers are messy.~~
~~when i have to push (forward foward 0) --> --> 0 it does not recognizes the 2 forwards it simply give me a "Miss" in game.
as if I hadn't pressed or input the command. it happens only when i have to press forward, back, up or down. not with Steps to reproduce the issue (Bust a Groove 2)~~ ~~Just keep playing and when you will have to push front, back, up or down it will not recognizes it~~

**Comment by TzakShrike** [comment]
Not just this stage, also happens on PAL but it is rare, also occurs in several other games but had been overlooked until recently. @stenzek likely fixed it by adjusting serial timing for controllers.

**Comment by andercard0** [comment]
Thanks! 
Confirmed fixed here problem solved!
