### ISSUE TITLE
Rayman (NTSC-U) - text is flickering 

### ISSUE THREAD

**Issue by MojoJojoDojo** [stenzek/duckstation#580]
The text is flickering as you can see in the video that I will show here below.
I tried to disable interlacing and change between all the renderers including software but it didnt fix it.
https://streamable.com/b15vi3

**Comment by stenzek** [comment]
Seems to be GPU draw time related.

**Comment by Shideravan** [comment]
Tested in 0.1-1419-g34a515cd and seems to be fixed!

**Comment by Pik-a-boo** [comment]
Seems like it's not fixed.
