### ISSUE TITLE
Multiple PS1 games issues

### ISSUE THREAD

**Issue by Mysticus92** [stenzek/duckstation#583]
I'm Mysticus92. It's a pleasure to meet you.
I found some issues.
For the European version of Crash Bash, the Loading screen gets stuck when entering in Adventure mode and Battle mode.
For the European version of Medievil, when entering the level 4, the game crashes with a Disc Warning icon.
For games required with a virtual Namco GunCon like Time Crisis and Point Blank games, the spark color is missplaced which is down-right at the aim icon.
I hope you fix them soon enough.

**Comment by kurayami6** [comment]
Both Crash Bash and Medievil have libcrypt copy protection. Always check Redump before you report a game as broken since it might just have copy protection that needs to be patched.

**Comment by Mysticus92** [comment]
Oh I'm sorry for this.

**Comment by kurayami6** [comment]
That's alright, I've made the same mistake several times.

**Comment by Mysticus92** [comment]
But again I found an issue.
Like I said first, for games required with a virtual Namco GunCon like Time Crisis and Point Blank games, the spark color is missplaced which is down-right at the aim icon.

**Comment by kurayami6** [comment]
Which renderer are you using and what resolution?

**Comment by Mysticus92** [comment]
Everything on default.

**Comment by kurayami6** [comment]
Tried it with D3D11 at x1 and the spark is in the center of the crosshair. You might have to talk to Stenzek about it on Discord.

**Comment by stenzek** [comment]
> For the European version of Crash Bash, the Loading screen gets stuck when entering in Adventure mode and Battle mode.
> For the European version of Medievil, when entering the level 4, the game crashes with a Disc Warning icon.
Yep, this is possibly libcrypt - google for "sbi files" and place them alongside your bin/cue/chd. The sbi file must have the same name as the bin/cue/chd.

> For games required with a virtual Namco GunCon like Time Crisis and Point Blank games, the spark color is missplaced which is down-right at the aim icon.

I just pushed a change which improves the position registration of the lightgun; but I've also found that some games are off by a amount proportional to the distance from the center of the screen - potentially accounting for CRT curvature. We might need a tweak option for this, as adjusting the scale factor will fix one game but break another.

**Comment by Mysticus92** [comment]
Thank you for the upgrade!
Games required a virtual gun like Point Blank works like a charm now.
