### ISSUE TITLE
[SLPS-00203] Screen problem

### ISSUE THREAD

**Issue by salalan** [stenzek/duckstation#585]
Thank you for creating a great emulator.

I have a problem on the right side of the screen.

Sorry, my bad english.

[SLPS-00203] Tenchiwokurau2 sekihekinotatakai

![duck-999](https://user-images.githubusercontent.com/67092430/86427738-edd7bd80-bd25-11ea-9482-9676ef5cee9f.jpg)

**Comment by stenzek** [comment]
Seems like it's overcropping.

Does using the "None" crop mode instead of "Only Overscan Area" change anything?

**Comment by salalan** [comment]
Aspect Ration: 4:3
Crop: None

![duck-033](https://user-images.githubusercontent.com/67092430/86505868-af650000-be04-11ea-84ab-5a64c9dc7a53.jpg)

**Comment by stenzek** [comment]
Should hopefully be fixed with the latest build, specifically https://github.com/stenzek/duckstation/commit/e42d5fed75dfd7affb48299f86b12610e9280672. Please let me know if it is still getting cropped.

**Comment by kurayami6** [comment]
Looks fixed to me. 

![SLPS-00203_2020-07-06_02-49-36](https://user-images.githubusercontent.com/31968468/86537582-68295d00-bf33-11ea-9de3-e58127427f3d.png)

**Comment by salalan** [comment]
Thank you for the fix.
But it seems a bit insufficient.

![rearm-009](https://user-images.githubusercontent.com/67092430/86558346-0fd67780-bf94-11ea-9252-48181764f4ef.jpg)

![rearm-010](https://user-images.githubusercontent.com/67092430/86558350-12d16800-bf94-11ea-9cd1-7288e088e088.jpg)

**Comment by salalan** [comment]
Not displayed correctly when upscaling.

![up-002](https://user-images.githubusercontent.com/67092430/86693857-04438900-c046-11ea-9411-0cd1df9a2d6a.jpg)

**Comment by stenzek** [comment]
Is the right line incorrect when upscaling in the VRAM view as well? I'm wondering if this a GS/line expansion issue.

**Comment by ggrtk** [comment]
Just to rule out other possibilities, can you show what it looks like at 1x resolution but with a larger window size? If the column still shows as partially cut off then I can submit a patch that's been tested on other titles that should also solve this problem.

**Comment by ggrtk** [comment]
Should be resolved by f369e3c4763f3ac233cfedc428e93de1dd63da08, since the texcoords are no longer being adjusted when linear filtering is turned off.
