### ISSUE TITLE
[Feature Request] Postprocessing shader implementation

### ISSUE THREAD

**Issue by Abbanon** [stenzek/duckstation#589]
Not sure what to type in this field, really, the title is self-explanatory.
But having the ability to use postprocessing shaders would be pretty neat.
Things like vignette, CRT (Composite, S-Video, Component/RGB), etc.
Snes9X has a great selection to choose from:
![Screenshot_1](https://user-images.githubusercontent.com/37251822/86542912-f8da4b80-bee7-11ea-841a-917cb3656cd2.png)

**Comment by stenzek** [comment]
Implemented in latest builds. Format is GLSL-like shaders (same as Dolphin).
