### ISSUE TITLE
Tomb Raider III - Adventures of Lara Croft (USA) (v1.1) menu audio runs too fast

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#59]
![tr3](https://user-images.githubusercontent.com/2696404/76137453-14d3fa80-6078-11ea-983f-6979f31a9f55.PNG)

**Comment by stenzek** [comment]
The crash should be fixed now, but there's an underlying issue here - the CDROM produces audio at a faster rate than the SPU can play. I need to investigate further what the actual problem here is, but the game appears to work fine.

**Comment by stenzek** [comment]
Should be fixed in the latest build.
