### ISSUE TITLE
Lady Maid (Japan) loads faster than on real hardware

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#590]
On my real PS1 and in Beetle PSX the time between the PS1 logo fading to black and the memory card access icon appearing on screen is 15 seconds. But in Duckstation it's only 12 seconds. This doesn't cause any issues for this particular game as far as I can tell but it might for more timing sensitive games. 

![SLPM-87157_2020-07-07_01-33-10](https://user-images.githubusercontent.com/31968468/86611601-3a571d80-bff2-11ea-9eb4-f741901a63fc.png)

**Comment by stenzek** [comment]
Likely differences in disc seek timing.
