### ISSUE TITLE
Title screen is broken with all renderers in Naruto - Shinobi no Sato no Jintori Gassen (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#593]
Random parts of it keep flashing on the screen one at a time. 

![SLPS-03553_2020-07-08_09-49-17](https://user-images.githubusercontent.com/31968468/86857478-f2bfb700-c101-11ea-80aa-fc306b4c743f.png)

![SLPS-03553_2020-07-08_09-49-05](https://user-images.githubusercontent.com/31968468/86857491-f81d0180-c101-11ea-97bf-a1f59fa3939e.png)

**Comment by azoreseuropa** [comment]
> Random parts of it keep flashing on the screen one at a time.
> 
> ![SLPS-03553_2020-07-08_09-49-17](https://user-images.githubusercontent.com/31968468/86857478-f2bfb700-c101-11ea-80aa-fc306b4c743f.png)
> 
> ![SLPS-03553_2020-07-08_09-49-05](https://user-images.githubusercontent.com/31968468/86857491-f81d0180-c101-11ea-97bf-a1f59fa3939e.png)

Your picture isn't good enough. It is not explain anything. ;) You need to give him more details. Are you using vulkan or OpenGL ? What version ? What PC do you use ? Etc. Make sure you give him the details so he will help you with that.

**Comment by kurayami6** [comment]
I already answered your first question in the title of the issue. As for "version" I don't know what that means. If you mean what version of the game, there's only one. If you mean what version of the emulator, I always use the latest. That's just the common sense thing to do. The developer and I have discussed hundreds of issues together and he is aware of my PC specs.

**Comment by azoreseuropa** [comment]
> I already answered your first question in the title of the issue. As for "version" I don't know what that means. If you mean what version of the game, there's only one. If you mean what version of the emulator, I always use the latest. That's just the common sense thing to do. The developer and I have discussed hundreds of issues together and he is aware of my PC specs.

Oh that's good. I didnt know. Please forgive me. Dont take me wrong. I hope this game can be resolve asap. Cheers

**Comment by stenzek** [comment]
I think this bug is invalid. Don't disable interlacing. I think I'm going to have to change the default, it seems to break too many games.
