### ISSUE TITLE
Love And Destroy (Japan) hangs instantly after BIOS. 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#597]
![Capture](https://user-images.githubusercontent.com/31968468/86980214-a7bba780-c1c6-11ea-83f3-de8d38b76bfd.PNG)

I can see a single white dot in the lower left corner if it turn on "Show VRAM"

![SCPS-10124_2020-07-09_09-23-08](https://user-images.githubusercontent.com/31968468/86980257-bbffa480-c1c6-11ea-8774-6dec9d3369b9.png)

**Comment by stenzek** [comment]
Due to CD-ROM resetting during seek. Need to write a hardware test to confirm whether the position changes after reset.

**Comment by stenzek** [comment]
Fixed by https://github.com/stenzek/duckstation/commit/c5e8327e7a383921b5be496e958ff92304b2afa3
