### ISSUE TITLE
CPU debug breakpoints are not implemented

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#598]
I loaded the infinite health cheat for Bug's Life, tried swapping to Disney-Pixar A Bug's Life (USA) (v1.0) and it just got stuck loading it forever. 

The emulator acknowledges that the disc has been swapped. 

![Capture](https://user-images.githubusercontent.com/31968468/87070615-64ac1380-c25c-11ea-8250-75472f57e1bc.PNG)

But as soon as I choose "continue" the Code Breaker disc goes insane.

![2020-07-10_03-14-36](https://user-images.githubusercontent.com/31968468/87070740-9624df00-c25c-11ea-8d16-bfa322ce4372.png)

![SCUS-94288_2020-07-10_03-09-04](https://user-images.githubusercontent.com/31968468/87070778-a2a93780-c25c-11ea-9723-b2364a1159ed.png)

![Capture2](https://user-images.githubusercontent.com/31968468/87070796-a937af00-c25c-11ea-8e15-2ba58946391e.PNG)

![Capture3](https://user-images.githubusercontent.com/31968468/87070802-ab017280-c25c-11ea-8130-65e151630c01.PNG)

**Comment by stenzek** [comment]
CPU hardware breakpoints aren't implemented, same reason AR carts don't work. It's not straightforward for a recompiler.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/442b801d396fcce562bf0616b6b5e099d26b283a
