### ISSUE TITLE
[Request] PGXP

### ISSUE THREAD

**Issue by SpaceAgeHero** [stenzek/duckstation#6]
Hi,
please include PGXP perspectve correct texturing and subpixel precision, developed by iCatButler:
https://github.com/iCatButler/beetle-psx-libretro/tree/master/pgxp

**Comment by stenzek** [comment]
Initial PGXP support added in https://github.com/stenzek/duckstation/commit/0c1b637549d430137f57d01100b9774df92b1e81

**Comment by Blackbird88** [comment]
Awesome! Bit unrelated but is there plan for CPU overclocking too? I tried finding issue for it to follow, but can't find any to follow

**Comment by MojoJojoDojo** [comment]
Added now https://github.com/stenzek/duckstation/issues/681
