### ISSUE TITLE
Several of the games in Arcade Party Pak (USA) are broken or have issues

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#604]
Graphics in 720° are completely broken.

![Capture](https://user-images.githubusercontent.com/31968468/87236334-5f50f380-c42b-11ea-87c2-374450f066f1.PNG)

Super Sprint hangs on this screen.

![SLUS-00952_2020-07-12_08-52-51](https://user-images.githubusercontent.com/31968468/87236339-7a236800-c42b-11ea-9bdf-72ac5e015794.png)

Toobin has flickering during screen transitions which isn't present on real hardware.

![SLUS-00952_2020-07-12_10-33-22](https://user-images.githubusercontent.com/31968468/87236344-8d363800-c42b-11ea-94fe-b9e322af5dcf.png)

**Comment by stenzek** [comment]
Re reported and this one's not showing in search
