### ISSUE TITLE
Swapping dics in PS-X-Change Version 1.0 (Europe) (Unl) causes a crash

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#605]
![Capture](https://user-images.githubusercontent.com/31968468/87240543-b7085280-c45d-11ea-878a-d0cc5c69de36.PNG)

![Capture 2](https://user-images.githubusercontent.com/31968468/87240545-ba034300-c45d-11ea-9498-a44a355960f5.PNG)

**Comment by stenzek** [comment]
Emulator crash was fixed a few days ago. The program does detect the disc change, but crashes after trying to start the game.

I don't really see any point in investigating this further unless it's an issue which also happens in another game - the emulator is not region locked in the first place.
