### ISSUE TITLE
observation of few games behavior

### ISSUE THREAD

**Issue by deivkiau** [stenzek/duckstation#607]
DuckStation Ver.: **Retroarch** (Can't find anywhere, but latest update 2020-07-12 / 17:00:00).
Render: Vulkan.
BIOS: SCPH5500, SCPH5501, SCPH5502.

All games are Redump valid. 

**Crash Bandicoot - Warped (USA) / SCUS-94244, SCUS-94244CE**
1. After BIOS ends, last second of sounds keep repeating until loading screen appear.

**Driver 2 (USA) Rev 1 / SLUS-01161GH**
1. Game is too fast.

**Hogs of War (USA) / SLUS-01195**
1. After BIOS ends, last second of sounds keep repeating until loading screen appear.
2. Game is very too fast.

**Medal of Honor - Underground (USA) / SLUS-01270, SLUS-01270GH**
1. After BIOS ends, last second of sounds keep repeating until loading screen appear.
2. Game is too fast.

**Rally Cross 2 (USA) / SCUS-94247**
1. After BIOS ends, last second of sounds keep repeating and game intro overlap on it.
2. Game is too fast.

**KKND Krossfire (Europe) / SLES-01246**
1. BIOS ends way too quickly. (Want to mention, that this issue is on all emulators which I tried. Maybe this is real hardware issue).

**Army Men 3D (USA) / SLUS-00491, SLUS-00491CE**
1. In-Menu: joystick presses usually not registered at first time. Other times visual of selected menu very delaying acording to joystick presses.
In-Game: there is no issue here.
2. Game is very too fast.

_Suggestion: If there is no way to match timing in BIOS-to-Game transicion maybe you can make like PS1 Classic Mini does. Use BIOS loading separate scene and after that, load a game. I'm not developer, just saying :)_

Overall I see huge potential DuckStation over existing PS1 emulators, games run pretty well, main issue is timing in game and especially in BIOS-to-Game transicion. **Good work guys !**

**Comment by stenzek** [comment]
The BIOS sound is a known issue; see https://github.com/stenzek/duckstation/issues/407

All emulators I'm aware of have it; just to varying degrees based on loading time. I've spent a fair bit of time researching this, part of what it needs is delays for changing the CD-ROM speed.

**Comment by stenzek** [comment]
Just checked Driver 2 - seems to be running a consistent speed for me, with the odd framerate drop. Is there a specific area in the game where it's running too fast?

**Comment by deivkiau** [comment]
It's consistent, but the gameplay in overall is too fast. FPS drop is expected, it's natural behavior, real hardware have it. I've played for many hours Driver 2 and feel is not the same.

**Comment by Shideravan** [comment]
### **Retested everything with 0.1-2499-g770dd5a6**

**Crash 3**: Still happening
**Driver 2**: Fixed
**Hogs of War**: Fixed
**Medal of Honor Underground**: Bios sound keeps looping until the first "loading". But game's speed is normal.
**Rally Cross 2**:  Bios sound keeps looping until the first "loading". But game's speed is normal.
**KKND Crossfire**: I don't have the game for testing purposes. But the best solution is test in original hardware and see if this is a normal behavior with the game itself or even with the game image tested. By description, don't see Duckstation related.
**Army Men 3D**: I had played this game in playstation and the issue of sometimes failing to recognizing commands in menu are something from the game itself as far I remember (but not happens in most of times, the same way that is happening in Duckstation). No issues (at least, not anymore) then... The speed is normal.

Conclusion: Just the issues regarding the BIOS is (still) happening. @stenzek what do you think about closing this issue and open a new one "games with last sound of bios looping until first ingame loading" and put these (and other games with similar problem) there?

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation/issues/407

Use fast boot as a workaround.
