### ISSUE TITLE
Gekido crashes with error message

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#61]
![Capture](https://user-images.githubusercontent.com/31968468/76142815-3c04e900-60c5-11ea-9968-691d63604109.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/76142819-46bf7e00-60c5-11ea-9e7e-16c68c18a930.PNG)

**Comment by stenzek** [comment]
Unable to reproduce on latest master. Please re-test.

**Comment by kurayami6** [comment]
Fixed.
