### ISSUE TITLE
SCUS-94900 Crash Bandicood - Rolling Stones bonus round bug

### ISSUE THREAD

**Issue by senhorlinguica** [stenzek/duckstation#612]
Game: Crash Bandicood (SCUS-94900)

Duckstation 0.1-1261

Sometimes the game hangs in Rolling Stone's bonus round. Not happens all the times, and happens with all APIs... here is a quick video to illustrate:

https://youtu.be/tnyovvt2aIo

**Comment by kurayami6** [comment]
Always include what version of the game you're using. US, Europe, etc... Since bugs often happen in some versions but not others.

**Comment by stenzek** [comment]
SCUS-94900 is NTSC-U.

**Comment by andercard0** [comment]
So, Just tested here and the problem only occurs in USA version as mentioned by Danilo. 
- 
Performing more tests with another version of the game i.e: European the issue does not occure at all. But not satisfied with it I decided to test on real Harware and guess what. Mentioned issue does not happen at all, game flows perfectly with or without MC attached to the Playstation by the way. 

Hope these help to find out what is going on with the game, anything else from my end and our friend (who raised this) just let us know. Will glad to help.

**Comment by Shideravan** [comment]
The video isn't active anymore, but the bug is and I can confirm. Hanging in this screen. Maybe memory card related @stenzek ?
![image](https://user-images.githubusercontent.com/12163923/101556245-31032000-3999-11eb-9285-4b38609cabf3.png)

**Comment by stenzek** [comment]
Tested without enhancements? I couldn't reproduce this issue anymore.

**Comment by Shideravan** [comment]
Yes, sir. Even with latest version. 
The ugly thing about this issue is that it's happens randonly. Sometimes freezes, sometimes don't.

**Comment by Shideravan** [comment]
If you can be fast enough, You can get the freeze before Tawna rise her arms, LOL (butterflies still moves)
![image](https://user-images.githubusercontent.com/12163923/102018921-18a35480-3d4f-11eb-924f-fa3135779e9c.png)

**Comment by Shideravan** [comment]
@stenzek maybe it's a bug in the game itself. The same problem happens in Mednafen and even ePSXe (https://gamefaqs.gamespot.com/boards/196986-crash-bandicoot/46924977). The ideal is to check this bug in the original hardware to be sure, but apparently or it's a issue that can escape the scope of the emulation.

**Comment by stenzek** [comment]
Can't seem to reproduce this anymore. It's possible the timing changes from a little while back fixed this.
