### ISSUE TITLE
The opening text crawl in Star Wars - Rebel Assault II - The Hidden Empire (USA) (Disc 1) is broken with all renderers

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#613]
It's a flickering mess. I've tried it with all renderers and at both native and higher resolution. I've also tried with " disable interlacing" on and off. 

![SLUS-00381_2020-07-14_20-06-38](https://user-images.githubusercontent.com/31968468/87414095-8d425d80-c60e-11ea-8205-a24edbce2f17.png)

**Comment by stenzek** [comment]
Can't seem to reproduce. Might've been a VRAM wrap-around thing.
