### ISSUE TITLE
Sanvein (Europe) hangs on a black screen after the first loading screen

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#614]
![SLES-02919_2020-07-15_15-28-40](https://user-images.githubusercontent.com/31968468/87507488-d34ffd80-c6b0-11ea-878c-33f3af69db16.png)

![log](https://user-images.githubusercontent.com/31968468/87507634-16aa6c00-c6b1-11ea-894f-d10b3388e41a.PNG)

The game does not use libcrypt. 

![Capture](https://user-images.githubusercontent.com/31968468/87507686-2b86ff80-c6b1-11ea-97ae-80e71ab6e5e0.PNG)

**Comment by stenzek** [comment]
Can't reproduce on latest build.
