### ISSUE TITLE
Adding Widescreen 16:9 Aspect Ratio

### ISSUE THREAD

**Issue by tabnk** [stenzek/duckstation#615]
Possible to add proper 16:9 widescreens support ? Without stretching..

**Comment by stenzek** [comment]
Might be possible to get anamorphic widescreen by adjusting GTE math.

**Comment by Richard-L** [comment]
Always nice when this is done. Not so nice all UI layers of game menus are consequently stretched, still. From following PSX emulation a little bit, my impression is it's more or less impossible to have the best of both, is it?

**Comment by stenzek** [comment]
Implemented in latest build.

Regarding menus/huds, reposting what I said on Discord:
> re HUD, not... really. If the game draws the HUD using sprites, then they could be scaled. But, most games use tris/quads, because then texcoords can be scaled. Then there's the question of things like lines - those would have to be scaled too. But in which direction? And how do you know they're not the output of the GTE and have already been scaled

**Comment by tabnk** [comment]
Great. :D
