### ISSUE TITLE
Pop'n Music 6 - Multiple rendering errors caused by "Disable Interlacing" option

### ISSUE THREAD

**Issue by isocosa** [stenzek/duckstation#616]
Enabling "Disable interlacing" option in Pop'n Music 6 seems to cause a a lot of issues with menus in all the rendering backends:

-The intro animation has the "let's make nice music together" text cut off, along with the "PRESS START BUTTON" text disappearing.
![pm6-attract-forceprog_on](https://user-images.githubusercontent.com/38756203/87700963-8004aa80-c797-11ea-818b-19efef65346f.png)
This is how it looks like without "Disable interlacing" option on, which is how the screen is supossed to look like:
![pm6-attract-froceprog_off](https://user-images.githubusercontent.com/38756203/87701209-e12c7e00-c797-11ea-97a3-13974ae2bbee.png)

-If you enable a hi-speed option in the options, the hi-speed setting will show up on the main menu screen. However, with disabled interlacing, it blinks and sometimes says HI-SPEED x10 for a single frame, regardless of your hi-speed setting.

-When the transition into the song select menu in ARCADE mode ends, you can see an incompletely rendered version of the menu for a few frames.
![pm6-songselect-forceprog_on](https://user-images.githubusercontent.com/38756203/87702414-adeaee80-c799-11ea-9204-797a1cce5734.png)

-In CHALLENGE MODE, the points displayed on the song select screen aren't fully rendered and flicker, along with the "music select" text:
![pm6-norma-forceprog_on](https://user-images.githubusercontent.com/38756203/87702249-74b27e80-c799-11ea-84c0-14fcd9431acf.png)
Without the option, the menu appears correctly:
![pm6-norma-forceprog_off](https://user-images.githubusercontent.com/38756203/87702277-7ed47d00-c799-11ea-92b5-a01c5be3afde.png)

-The results screen that appears after beating NORMAL ARCADE MODE doesn't render completely:
![pm6-results-forceprog_on](https://user-images.githubusercontent.com/38756203/87703564-5d749080-c79b-11ea-9e5c-3039328e42b7.png)
Without the option, the screen appears correctly:
![pm6-results-forceprog_off](https://user-images.githubusercontent.com/38756203/87703592-6a917f80-c79b-11ea-9c85-c3a6b5b7807d.png)

-The menu that appears on the results screen in FREE MODE doesn't display completely:
![pm6-freemode-forceprog_on](https://user-images.githubusercontent.com/38756203/87704168-48e4c800-c79c-11ea-87fa-8dce3ee49a13.png)
Without the option, the menu appears correctly:
![pm6-freemode-forceprog_off](https://user-images.githubusercontent.com/38756203/87704205-55692080-c79c-11ea-8bad-95892e931e26.png)

There's most likely more such issues present, but those are the ones I was able to find so far.

**Comment by stenzek** [comment]
If it's rendering correctly with interlacing enabled (the option disabled), then this isn't really a bug. Some games require interlaced rendering to draw properly, otherwise it can break their field detection -> game waits too long for the GPU -> things don't render in time.

**Comment by isocosa** [comment]
Well, then I guess this is not a bug.
Apart from these bugs, this game seriously benefits from these enhancements, as it removes blurring caused by the interlacing. The game runs in 60fps in high-res mode (512x480 framebuffer, but without overscan the end resolution is 512x384), so displaying it nicely on modern screens is definitely tricky. I guess the best idea would be to implement alternate interlace modes like Mednafen. Bob offset interlace with vsync would work great for this game.

**Comment by stenzek** [comment]
Adding additional deinterlacing filters are on my to-do list :)
