### ISSUE TITLE
[Request] Add support for .m3u

### ISSUE THREAD

**Issue by RiskyJumps** [stenzek/duckstation#619]
For RetroArch to be able to swap discs on multi-disc games, an index file (.m3u) is required. The file is just a simple text file that lists all the  .cue (for .bin/.cue) or .chd files (separated by newline characters).

For more info, please look at: [multiple-disk-games](https://docs.libretro.com/library/beetle_psx_hw/#multiple-disk-games)

**Comment by tony971** [comment]
https://github.com/stenzek/duckstation/issues/362#issuecomment-620896992

https://github.com/stenzek/duckstation/issues/17#issuecomment-584463596

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/f3df4f91a280dbd9e04d6b6d016ecbf22634bbc2

Needs a core file update to signal that DuckStation can accept m3u files now - you can edit it yourself in the meantime.
