### ISSUE TITLE
Metal Slug X - Lockup due to DMA

### ISSUE THREAD

**Issue by and468860** [stenzek/duckstation#62]
metal slug x makes stop to read graphics card  nivdia e intel hd .
not now renderer all dix, open, soft.
sorry poorly written english not using google translate

**Comment by benderscruffy** [comment]
i think what they are trying to say is after you choose your character and it goes to load level one
nothing but a black screen

**Comment by stenzek** [comment]
Okay, yeah, this looks like a DMA issue.

**Comment by stenzek** [comment]
Fixed by GPU timings (not merged yet, but soon)

**Comment by stenzek** [comment]
Should be fixed now in master.
