### ISSUE TITLE
[Request] [Libretro] Change memcard 1 file extension from .mcd to .srm, and remove _1 suffix

### ISSUE THREAD

**Issue by ds22x** [stenzek/duckstation#621]
This would help make savefiles cross-compatible between the different PSX cores, as currently you have to rename and change the file extension for them to transfer them between cores.

**Comment by ggrtk** [comment]
As a dissenting opinion, I would argue that this is one of the behaviors that the other libretro cores should change, not DuckStation. I haven't seen other PlayStation simulators other than the libretro forks using .srm, which seems to be a naming carryover from Libretro's early SNES days.

**Comment by negativeExponent** [comment]
this should rather be a request to support for libretro api save file handling (aka retro_get_memory_data/size api), which should save in .srm extension. the extension might not be exclusive to RA but since they are the ones using it, it should make it easier in identifying that it is saved  from libretro and using the said api.

**Comment by stenzek** [comment]
.srm also only supports "one save", whereas the PS1 has two memory cards. I'll probably add an option similar to Bettle though.

**Comment by bslenul** [comment]
Yeah, would be great if we had a new "Memory Card 1 Type" option like "Separate Card Per Game (Libretro)" or whatever, where it would simply read/write .srm, it would be really nice to have a single file compatible with all cores.

I tried with my MGS memory card and it looks like there's no conversion needed or anything, I just had to rename my .srm to _1.mcd and it worked.

**Comment by stenzek** [comment]
Merged with #1064
