### ISSUE TITLE
Simple 1500 Series Vol. 31 - The Sound Novel (Japan) takes significantly longer to boot than it should

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#624]
In Duckstation the time between the PS1 logo fading away and the D3Publisher logo appearing is 11 seconds. In Beetle PSX the transition is immediate. 

![Capture](https://user-images.githubusercontent.com/31968468/87847582-c46d8300-c91c-11ea-9970-d5c9d33cf974.PNG)

![SLPS-02840_2020-07-18_17-26-25](https://user-images.githubusercontent.com/31968468/87847583-c9cacd80-c91c-11ea-835a-0b0a70bb53be.png)

**Comment by stenzek** [comment]
I don't trust Beetle on this one. It's seeking to an out-of-range sector and I've verified this takes a couple of seconds on my console.
