### ISSUE TITLE
Duckstation libretro: build process hangs Raspberry Pi 3b+

### ISSUE THREAD

**Issue by vanfanel** [stenzek/duckstation#626]
Hi there

I have read GREAT things about duckstation, so I am trying to build a GNU/Linux **64bit (aarch64) version for the Raspberry Pi 3b+**, from the latest GIT sources in this repository.

I am configuring like this:
```

pi@raspberrypi:~/src/libretro/duckstation/build $ cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_LIBRETRO_CORE=ON ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Version: 3.13.4
CMake Warning at CMakeLists.txt:41 (message):
  Building for Android or libretro core, disabling SDL frontend


CMake Warning at CMakeLists.txt:45 (message):
  Building for Android or libretro core, disabling Qt frontend


Building for Android or libretro core, disabling Discord Presence support
Building for Android or libretro core, disabling SDL2 support
-- Performing Test COMPILER_SUPPORTS_WALL
-- Performing Test COMPILER_SUPPORTS_WALL - Success
-- Performing Test COMPILER_SUPPORTS_MEMACCESS
-- Performing Test COMPILER_SUPPORTS_MEMACCESS - Success
-- Performing Test COMPILER_SUPPORTS_OFFSETOF
-- Performing Test COMPILER_SUPPORTS_OFFSETOF - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Looking for include file AudioUnit/AudioUnit.h
-- Looking for include file AudioUnit/AudioUnit.h - not found
-- Looking for include file pulse/pulseaudio.h
-- Looking for include file pulse/pulseaudio.h - not found
-- Looking for include file alsa/asoundlib.h
-- Looking for include file alsa/asoundlib.h - found
-- Looking for include file jack/jack.h
-- Looking for include file jack/jack.h - not found
-- Looking for include file audioclient.h
-- Looking for include file audioclient.h - not found
-- Looking for include files windows.h, mmsystem.h
-- Looking for include files windows.h, mmsystem.h - not found
-- Looking for include file SLES/OpenSLES.h
-- Looking for include file SLES/OpenSLES.h - not found
-- Looking for include file android/log.h
-- Looking for include file android/log.h - not found
-- Looking for include file sndio.h
-- Looking for include file sndio.h - not found
-- Looking for include file sys/audioio.h
-- Looking for include file sys/audioio.h - not found
-- Looking for include file kai.h
-- Looking for include file kai.h - not found
Building AArch64 recompiler
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/src/libretro/duckstation/build
pi@raspberrypi:~/src/libretro/duckstation/build $
```

...but then, during the compilation, the gcc compiler (cc1plus in TOP) is forever stuck at 100% building this:
`
[ 54%] Building CXX object dep/vixl/CMakeFiles/vixl.dir/src/aarch32/disasm-aarch32.cc.o`

It stays there forever. I have waited for 1 hour, and it doesn't seem to end.
I have a swap file (4GB) availabe, so memory shouldn't be a problem.
I had to enable this swap file because I was previously getting:
`c++: fatal error: Killed signal terminated program cc1plus`

I am also puzzled to see aarch32 files building, because you can clearly see this on the configure output:
`Building AArch64 recompiler`

So, what is going on here? Is that aarch32 file supposed to be built at all? Why does it take forever and ever?

Thanks!

PD: gcc and kernel version:

```
pi@raspberrypi:~ $ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/8/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --disable-libphobos --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6) 
pi@raspberrypi:~ $ uname -r
5.4.51-v8+

```

**Comment by stenzek** [comment]
The A32 file you're seeing is part of vixl, the AArch32/64 emitter I use to generate code. It can take quite a bit of memory and time to compile, especially in release mode. For what it's worth, it does build fine on my Pi4 4GB.

I can probably drop the A32 emitter, but I don't think it will make much difference here. As far as I can tell, the Pi3 GPU does not support GLES 3, so you won't be able to use the hardware renderer, and the software renderer is very slow in comparison.

**Comment by vanfanel** [comment]
@stenzek Thanks for taking the time to answer, and of course for your work on duckstation :)

So, all in all, since GLES3 is not supported on the Pi3, the emulator will be using the (slow) software renderer, even if I can manage to build it somehow... right?
So maybe this emulator is not suited for Pi3 anyway.

**Comment by stenzek** [comment]
CPU-wise the Pi3 is sufficient, even more so when I get around to the latest round of recompiler improvements. It's the GPU which is lacking. You _might_ be able to use the Vulkan driver with the Pi3, but I'd be surprised if that worked without issues.

**Comment by vanfanel** [comment]
Oh, yes, the Pi3 Vulkan driver is worth a try! I didn't know Duckstation also had a Vulkan renderer, that's great news. But I am currently having trouble building a working version of the Vulkan driver to start with:
https://github.com/Yours3lf/rpi-vk-driver/issues/17

I have a Pi4 too, but I would like to see DuckStation on the Pi3, moreover with these new recompiler optimizations!
Also, isn't GLES2 an option?
 
And...Is it possible to leave the aarch32 emitter out of the compilation in aarch64? How could I try to do it?

**Comment by stenzek** [comment]
I use a number of GL3/GLES3 features in the hardware renderers which are not available in GLES2, so it would require a different design, which could not achieve the same accuracy levels.

Generally speaking, I'm not sure if the pool of devices which only have GLES2 _and_ AArch64 is large enough to be worth supporting. Anything made in the phone space in the last 4-5 years or so should have both GLES3 and AArch64.

**Comment by vanfanel** [comment]
Then it's going to be Vulkan or nothing for the Pi3. You're right in that the Pi3 being aarch64 and GLES2 only is relatively strange...

Anyway, what could be done regarding the aarch32 emitter in aarch64? Not being able to build on the Pi3 would prevent me to try the Vulkan driver.

**Comment by stenzek** [comment]
If it can't compile the A32 emitter, it's probably going to struggle to compile the A64 emitter too. I'm guessing you have less than 4GB of RAM? Because it seems to build okay on my Pi4 with 4GB (ignoring the graphics driver bugs it hits).

**Comment by vanfanel** [comment]
@stenzek The problem is that there are no Pi3 with more than 1GB. I tried swapping (4GB) but as the RAM is used up and it starts using swap, the compilation process eventually stops and the whole machine seems unresponsive even if I only let make use 1 core.

**Comment by stenzek** [comment]
You'll probably have to cross-compile then. 1GB of RAM is simply insufficient for compiling complex C++ projects such as vixl, and potentially even the core of DuckStation.

**Comment by vanfanel** [comment]
Thanks @stenzek 

My course of action for DuckStation on Pi3 64bit will be cross-compilation and Vulkan.
Whenever I get the Vulkan driver to work, that's it.

**Comment by vanfanel** [comment]
@stenzek If you have ever cross-compiled the RA core, I could use some help.
I have installed these cross-compiler packages in Ubuntu (note aarch64 binutils are also installed as a dependency):

`sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
`
Then copied over the Raspberry Pi OS 64 rootfs to the build computer, so I have the target system headers and libs:
`sudo rsync -av --progress /media/manuel/rootfs /opt/ --exclude rootfs/home/pi
`
Then tried to configure DuckStation using cmake, passing it the crosscompiler, target system rootfs, and ` CMAKE_SYSTEM_PROCESSOR` just in case:
`CC=/usr/bin/aarch64-linux-gnu-gcc CXX=/usr/bin/aarch64-linux-gnu-g++ cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_LIBRETRO_CORE=ON -DCMAKE_FIND_ROOT_PATH=/opt/rootfs -DCMAKE_SYSTEM_PROCESSOR=aarch64 ..`

...but results are very weird, and I don't know where the problem could be, so any suggestions are welcome:```


manuel@hp15db0:~/src/duckstation/build$ CC=/usr/bin/aarch64-linux-gnu-gcc CXX=/usr/bin/aarch64-linux-gnu-g++ cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_LIBRETRO_CORE=ON -DCMAKE_FIND_ROOT_PATH=/opt/rootfs -DCMAKE_SYSTEM_PROCESSOR=aarch64 ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc -- broken
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/usr/bin/aarch64-linux-gnu-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/manuel/src/duckstation/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/opt/rootfs/usr/bin/make cmTC_9c5bd/fast && /opt/rootfs/usr/bin/make: 1: ELF�
                                                                                                      �@�r@8: not found
    /opt/rootfs/usr/bin/make: 2: T: not found
    /opt/rootfs/usr/bin/make: 3: Q�tdR�td�Q�Q�Qxx/lib/ld-linux-aarch64.so.1GNUGNU���=: not found
    /opt/rootfs/usr/bin/make: 3: R�w�xr�ңQ�WNb�: not found
    /opt/rootfs/usr/bin/make: 4: Syntax error: ")" unexpected
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "/home/manuel/src/duckstation/build/CMakeFiles/CMakeOutput.log".
See also "/home/manuel/src/duckstation/build/CMakeFiles/CMakeError.log".
```

**Comment by stenzek** [comment]
Thanks for the details. I might see about adding this to the CI so you don't need to compile on-device (depends how many headers are needed.. should be minimal for libretro)
