### ISSUE TITLE
(Libretro) Core crashes on startup with "system shut down" on Tegra X1 Ubuntu Linux (Nintendo Switch)

### ISSUE THREAD

**Issue by Feranthur** [stenzek/duckstation#627]
Hello. I've compiled the core with no issues on a Nintendo Switch running L4T Ubuntu (Tegra X1). However, when i try to start Tekken 3, the core crashes with a "system shut down - failed to load content" message. The same game runs fine on Beetle PSX HW with Vulkan Renderer, and also on PCSX Rearmed. Bios is also present. Any ideas?

**Comment by stenzek** [comment]
Enable logging in the core settings, and retroarch, and check the terminal.

**Comment by Feranthur** [comment]
Hello. I got it working, turns out it didn't like both the bios and .cue game i was using for Beetle. After replacing both, it started fine with Vulkan.
