### ISSUE TITLE
Directional analogue controls don't work during gameplay in Rat Attack! (USA)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#628]
All other buttons work fine and I can use the control stick to navigate the menus, I just can't move during gameplay. Digital controls work fine. 

![SLUS-00656_2020-07-20_03-10-07](https://user-images.githubusercontent.com/31968468/87880703-23271f80-ca37-11ea-888a-2120b5414c11.png)

**Comment by stenzek** [comment]
What happens if you toggle analog mode?

**Comment by kurayami6** [comment]
If I start with digital and switch to analogue the movement controls work fine.

**Comment by stenzek** [comment]
Interesting. I wonder if it's the same issue (yet again) as Rollcage II.

**Comment by Shideravan** [comment]
It's working properly as of 0.1-2499-g770dd5a6.

**Comment by ggrtk** [comment]
This was probably fixed by the Analog Controller updates from last month.
