### ISSUE TITLE
Speed and upscaling issues in Megatudo 2096 (Japan)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#629]
The models on the select screen only upscale in VRAM.

![Capture](https://user-images.githubusercontent.com/31968468/87883478-fda41100-ca4a-11ea-93e5-b427012b4b90.PNG)

![SLPS-00435_2020-07-20_05-15-19](https://user-images.githubusercontent.com/31968468/87883484-0399f200-ca4b-11ea-823b-f4f8e3fabe9f.png)

Gameplay runs at a million miles per hour making the game unplayable.

![SLPS-00435_2020-07-20_05-28-14](https://user-images.githubusercontent.com/31968468/87883500-21ffed80-ca4b-11ea-9796-66dc7d095afc.png)

**Comment by stenzek** [comment]
Has been fixed with icache.
