### ISSUE TITLE
No sound effects in Monkey Hero

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#63]
The music is playing but the sound of hitting enemies, picking things up, etc is missing. The game is also running well below full speed but that's probably a separate issue. 

![Capture](https://user-images.githubusercontent.com/31968468/76154228-f7149d00-612c-11ea-8d7e-ab691eef70c2.PNG)

**Comment by kurayami6** [comment]
As of the latest version the game has regressed to having no sound at all.

**Comment by stenzek** [comment]
After some investigation, we discovered that this game turns the voice off almost immediately after turning the voice on, which we suspect on the real console would result in the second write being ignored. I've implemented this behavior in https://github.com/stenzek/duckstation/commit/306499fd0817a71996f3370d8741212497b5494f - both the music and sound effects appear to work now.

Still needs confirmation with a hardware test.
