### ISSUE TITLE
Games which require interlacing enabled

### ISSUE THREAD

**Issue by stenzek** [stenzek/duckstation#632]
List of games which need interlacing forced on for when I eventually implement gameinis:

 - Pop'n Music 6 
 - Mr. Driller G (Japan)
 - Pro Pinball - Fantastic Journey (USA) (and all other Pro Pinball games it seems)
 - True Pinball (USA)
 - Shinobi no Sato no Jintori Gassen (Japan) 
 - Time Bokan Series - Bokan desu yo (Japan)
 - Dead Or Alive (USA)

I'll add the game serials/codes to these later. But for other games, please post their title **and** code, since the code is what we will use for the gameini.

**Comment by kurayami6** [comment]
Rat Attack! (USA) SLUS-00656
Arcade Party Pak (USA) SLUS-00952

**Comment by stenzek** [comment]
Closing as this is solved via game settings now.
