### ISSUE TITLE
Audio crackling during the opening logos in 20-seiki Striker Retsuden - The 20th Century's Real Strikers (Japan)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#633]
The emulator is running full speed so that isn't the issue. It doesn't happen in Beetle PSX. Tested with Vulkan and the software renderer and it happens in both. 

[SLPS-02348_2020-07-21_16-18-03.zip](https://github.com/stenzek/duckstation/files/4951709/SLPS-02348_2020-07-21_16-18-03.zip)

![SLPS-02348_2020-07-21_16-24-50](https://user-images.githubusercontent.com/31968468/88020846-c418f600-cb6f-11ea-98bc-2c7e960934fc.png)

**Comment by Shideravan** [comment]
I can confirm. That happens in both cubeb and SDL.

**Comment by stenzek** [comment]
Needs console verification.

The game is using 1/8 interleave with 18900hz stereo XA coding, when it should be 1/16. Treating it as 18900hz makes it sounds garbage. So either the game is meant to sound terrible, or there's something we're missing and it should be interpreted as 37800hz.

**Comment by Shideravan** [comment]
Finally found the issue!

**Comment by stenzek** [comment]
Closing until verified on console.
