### ISSUE TITLE
[Feature Request] Analog deadzone configuration

### ISSUE THREAD

**Issue by Abbanon** [stenzek/duckstation#634]
Title says it all. Since there's a seemingly endless selection of controllers people can use, having the ability to tweak the deadzone radius of the analog stick inputs would be very useful in many cases.

**Comment by stenzek** [comment]
There's a `Deadzone` setting you can add to the ini under `[ControllerN]`, range is 0.01..0.99. But it isn't exposed in the UI yet.

**Comment by Abbanon** [comment]
Oh! I didn't think about "hidden" `.ini` options. PPSSPP also does this. 
I'll go ahead and close it.
