### ISSUE TITLE
Wipeout3 (USA) CD audio issues

### ISSUE THREAD

**Issue by Ziemas** [stenzek/duckstation#635]
When pausing and choosing to restart the current race CD audio disappears and doesn't come back.

```[ 5311.3760] D/CDROM: CDROM executing command 0x11 (GetlocP)
[ 5311.3770] D/CDROM: Read sector 94969 as CDDA
[ 5311.3931] D/CDROM: Read sector 94970 as CDDA
[ 5311.4092] D/CDROM: Read sector 94971 as CDDA
[ 5311.4106] D/CDROM: CDROM executing command 0x1A (GetID)
[ 5311.4106] D/CDROM: Seek time for 94971 LBAs: 20088275
[ 5312.0278] D/CDROM: CDROM executing command 0x11 (GetlocP)
[ 5312.0308] D/CDROM: CDROM executing command 0x11 (GetlocP)
[ 5312.0615] D/CDROM: CDROM executing command 0x11 (GetlocP)
[ 5312.0947] D/CDROM: CDROM executing command 0x11 (GetlocP)
[ 5312.1284] D/CDROM: CDROM executing command 0x11 (GetlocP)
```

Seems like the game assumes audio playback will continue alongside GetID.

Another issue is when starting a CD track. It seems to start playing for a second and then restart from the start again. A video of this (with the CD status window) can be found here https://cdn.discordapp.com/attachments/695823554712698962/735128896030375987/wo3.mp4

**Comment by Kurayami7** [comment]
I can't reproduce either of these issues. Unless someone else wants to test further this can be closed.

**Comment by Ziemas** [comment]
Indeed, I can't reproduce these issues anymore either.

**Comment by stenzek** [comment]
I wanted to leave this open because I'm pretty sure the emulation isn't correct here - GetID seeks to zero (and stops playing), the game notices it and restarts the track, and I'm guessing it should continue playing without restarting.

**Comment by stenzek** [comment]
Fixed properly with https://github.com/stenzek/duckstation/commit/36bfc461f9c7ecbbe2d6ffb4817e98e28a2de64e.
