### ISSUE TITLE
Crashes when try to use a controller button as a hotkey

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#638]
### Version
DuckStation 0.1-1304-gc8b6712

### What happens?
The emulation crashes when trying to use a controller button on hotkey.

### What *should* happen?
Not to crash and permit to use controller button as a hotkey.

### What hardware, operating system, and Duckstation version?  On desktop, GPU matters for graphical issues.
I7-4930, 16GB RAM, GTX 1070
Windows 10 x64
Using PS3 controller with SCPToolkit to simulate a XInput controller.
In the controller bindings the issue doesn't happen, only in the hotkey.

**Comment by ggrtk** [comment]
This should be fixed as of 855fc9a.

**Comment by stenzek** [comment]
Please let me know if this is still happening.

**Comment by Shideravan** [comment]
Now it's fine, thank you 😊
