### ISSUE TITLE
Unable to compile any configuration of platform on Windows 10

### ISSUE THREAD

**Issue by mforan26** [stenzek/duckstation#639]
### Version
Latest

### What Happens?
No matter what configuration I try to compile in Visual Studio I get the following part way through the process:

> 21>D:\dev\duckstation\src\common\dimensional_array.h(59,14): error C2672: 'detail::GetRankSize': no matching overloaded function found (compiling source file gpu_hw_vulkan.cpp)
> 21>D:\dev\duckstation\src\common\dimensional_array.h(64): message : see reference to alias template instantiation 'detail::GetArrayImplType<T,rank_param,sizes...>' being compiled (compiling source file gpu_hw_vulkan.cpp)
> 21>D:\dev\duckstation\src\common\dimensional_array.h(94): message : see reference to class template instantiation 'detail::DimensionalArrayExplicitRank<T,rank_param,sizes...>' being compiled (compiling source file gpu_hw_vulkan.cpp)
> 21>D:\dev\duckstation\src\common\dimensional_array.h(58,2): error C2975: 'sizes': invalid template argument for 'detail::GetRankSize', expected compile-time constant expression (compiling source file gpu_hw_vulkan.cpp)
> 21>D:\dev\duckstation\src\common\dimensional_array.h(49): message : see declaration of 'sizes' (compiling source file gpu_hw_vulkan.cpp)
> 21>D:\dev\duckstation\src\common\dimensional_array.h(58,1): error C2975: 'rank': invalid template argument for 'detail::GetRankSize', expected compile-time constant expression (compiling source file gpu_hw_vulkan.cpp)
> 21>D:\dev\duckstation\src\common\dimensional_array.h(49): message : see declaration of 'rank' (compiling source file gpu_hw_vulkan.cpp)
> 21>D:\dev\duckstation\src\common\dimensional_array.h(58,1): error C2975: 'sizes': invalid template argument for 'detail::GetRankSize', expected compile-time constant expression (compiling source file gpu_hw_vulkan.cpp)
> 21>D:\dev\duckstation\src\common\dimensional_array.h(49): message : see declaration of 'sizes' (compiling source file gpu_hw_vulkan.cpp)
> 

### What _should_ happen?

Binaries are created and placed in bin folder.

### What hardware, operating system, and Duckstation version?

i7-4770K, 16GB RAM, GTX 1050
Windows 10 x64

**Comment by ggrtk** [comment]
A quick search says these are errors caused by older versions of Visual Studio. Are you running with Visual Studio 2019?

**Comment by mforan26** [comment]
Can confirm I'm running 2019.

**Comment by stenzek** [comment]
Try updating your visual studio installation.

**Comment by mforan26** [comment]
Updated Visual Studio. It compiled fine.
