### ISSUE TITLE
Bios was wrong for Android

### ISSUE THREAD

**Issue by azoreseuropa** [stenzek/duckstation#640]
Android: Rockman 8 was supposed to show Japanese flag in bios because the bios in settings auto as default but its USA flag on list - look: 

![Screenshot_20200721-220512_DuckStation](https://user-images.githubusercontent.com/16481778/88112223-ec6c1900-cb9e-11ea-8c19-bf58216cf476.jpg)

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/a7e24da7fe535ae73599ca8d338519155817c58b

**Comment by azoreseuropa** [comment]
Yes, it does. Thanks so much!
