### ISSUE TITLE
Certain lines of dialogue stutter in Dino Crisis (USA) (Rev 1)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#642]
During the cutscene in the control room at the beginning of the game. 

[SLUS-00922_2020-07-22_22-36-38.zip](https://github.com/stenzek/duckstation/files/4959973/SLUS-00922_2020-07-22_22-36-38.zip)

![SLUS-00922_2020-07-22_22-40-10](https://user-images.githubusercontent.com/31968468/88177860-d88ee880-cc6c-11ea-98c4-17a3564664c6.png)

**Comment by stenzek** [comment]
Fixed with https://github.com/stenzek/duckstation/commit/5634e821c55f1108fdad5432e8b02e4b7552999c
