### ISSUE TITLE
[SLUS-00684] Jackie Chan Stuntmaster (NTSC-U) freezes in first logo video

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#643]
**Version**
DuckStation 0.1-1313-g10cd00c

**Issue** 
The game image freezes in this screen.
Tested with both .bin+.cue verified ReDump's file (md5="d4c9bdde0e8741972d7b262b8ffd3093") and verified MAME CHD.

![image](https://user-images.githubusercontent.com/12163923/88177779-c9be1c80-cbff-11ea-9221-b0005a86d189.png)

**Comment by senhorlinguica** [comment]
Try it here, and indeed its happening, but if you use the interpreter works normal. If you use the recompiler, you can press "start" and you'll pass and the game continue normally.

**Comment by Shideravan** [comment]
@senhorlinguica Yes, I just realized that the issue only happens in Recompiler mode. I initially was misled to that happening in interpreter too because the emulator was self-resuming an auto-created "resume save-state" created when in recompiler mode. Sh*t... But at least that helped me to find another ugly issue not directly related with the Jackie Chan's Game (https://github.com/stenzek/duckstation/issues/644) LOL

**Comment by stenzek** [comment]
Works fine in interpreter, I'll add a compatibility entry to force it.

**Comment by DonelBueno** [comment]
It doesn't crash here in recompiler mode, I can pass trough all logos without skipping anything.

Can someone else confirm this?
