### ISSUE TITLE
Auto Loading "resume Save State" even when "save state on exit" isn't checked

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#644]
**Version**
0.1-1313-g10cd00c

**Issue**
If you check "Save State on Exit", load a game, exit, uncheck "Save State on Exit" and run the game, the emulator will auto-load a "resume save state" even if you don't want to.
The best workaround I see is to put in the options the checkbox "Auto-load the Resume Save State on start", then the user can do an auto-savestate and boot the game without necessarily load the save state. That said, I also think that "Save State on Exit" is a bad option to be checked by default, as a user can have tons of "auto-created save states" without even realizing it, which can lead to mistakes.

**Comment by stenzek** [comment]
That's the whole point of the feature though - to resume where you left off. For what it's worth, you can force a full/fast boot by right clicking on the game.

I'll change it to do a full boot if the "save state on exit" option is disabled though, as you don't want to load a stale state.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/961afdf76547d0072eb1ce1cdeade8d51ba3212a
