### ISSUE TITLE
"Automatic based in window size" is setting a wrong value to output

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#645]
**Version**
0.1-1313-g10cd00c

**Specs**
Windows 10 x64, 1920x1080 desktop default resolution

**Config**
Enhancement->Resolution Scale->Automatic based in window size

Tested in 3 scenarios: starting the game in fullscreen, rendering in main window and rendering in a separate window. All three scenarios gives the same error. 

**Issue**
When select the resolution scale "Automatic based in window size" option is chosen, the message "invalid resolution scale 0x specified. Maximum is 32" and the output gives only a low-resolution scale.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/9b7512f7b84351d1e81535aade7e52d54b0dda5d
