### ISSUE TITLE
[SCES-02105] Crash Team Racing hangs while loading race 

### ISSUE THREAD

**Issue by RaydenX93** [stenzek/duckstation#646]
I can't start a race in CTR, PAL Version. 
I can get to menus and, if I start a campaign, I get to the warp room and can drive around but the game hangs while loading a race, both in adventure mode and in arcade mode.

Rom name: CTR - Crash Team Racing (Europe) (En,Fr,De,Es,It,Nl) (No EDC) (Tried with the EDC one as well, same error)
OS: Win 10 x64 2004
BIOS: PSP 6.60 (I tried with SCPH5502 as well, same error)
Duckstation version tested: 0.1-1313-g10cd00c

See attached log:
[duckstation_crashcove.log](https://github.com/stenzek/duckstation/files/4961073/duckstation_crashcove.log)

This is my first time reporting a bug, so please do let me know the best way I can help.

Thanks

**Comment by kurayami6** [comment]
First thing you should always do when reporting a game crash is check Redump to make sure the game doesn't have libcrypt copy protection. This game does which is likely why it crashes. 

![Capture](https://user-images.githubusercontent.com/31968468/88200942-2e25be00-cc8a-11ea-84c3-40d5c48e1924.PNG)

**Comment by RaydenX93** [comment]
Yep, it works with the .sbi file. Thanks!

Can some kind of automatic check be implemented for libcrypt protection?

**Comment by stenzek** [comment]
Not really a way for the emulator to detect it. You could use heuristics, but there's no completely consistent behavior across games.

Would have to add it to the metadata.

**Comment by Dr-Vendetta** [comment]
what about a list of games that the emulator checks against and warns the user about the problem
