### ISSUE TITLE
Fix SHIFT/CTRL key mappings

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#647]
Currently allows you to map these keys without effect.

You'd said:

> won't let you use it because qt probably isn't firing key events for shift

Also would be useful to distinguish left and right SHIFT/CTRL.

Many thanks.

**Comment by Richard-L** [comment]
Sten, is there any chance for love for this? This is literally keeping me from playing with DS. Just because so many habits exist from PC gaming where using left/right ctrl/shift is so commonplace. That said, I'm of course aware there are other things you want to prioritise.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/ae3ad04bfc48957193e465058d2c3bb1a01e9f7b
