### ISSUE TITLE
Custom Crosshair image not displayed on Vulkan

### ISSUE THREAD

**Issue by mirrornoir** [stenzek/duckstation#648]
Vulkan renderer does not display custom crosshair images unlike software and OpenGL renderer. For reference I'm on Linux using an Nvidia GTX 970 with Nvidia 450.57 proprietary drivers. Taking a glance at the commits, https://github.com/stenzek/duckstation/commit/655dff84e247a1d2ddb8b516c78d86f5644bb378 looks related but I'm no good at understanding what Vulkan code is trying to do.

I've attached the crosshair I'm trying to use, comes from [this custom MAME crosshair pack](https://mrdo.mameworld.info/mame_artwork_supp.php).
![sm2-red](https://user-images.githubusercontent.com/19215655/88213287-81febb80-cc26-11ea-9bf1-6e3b79a45b47.png)

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/4a3e5ed6442bc8c1e8d0f72ac7aab58796269ebc

**Comment by mirrornoir** [comment]
I can confirm that https://github.com/stenzek/duckstation/commit/4a3e5ed6442bc8c1e8d0f72ac7aab58796269ebc fixes the issue, thanks :+1:
