### ISSUE TITLE
Crash on 'Change Disc'

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#649]
![image](https://user-images.githubusercontent.com/4934209/88215200-94471c80-cc5b-11ea-9484-b06c87c9c76d.png)

Having had Tomb Raider 3 (EU) loaded, then pressing 'Change Disc' to choose a fast boot of Silent Hill (JP) from game list prompted this.

**Comment by Shideravan** [comment]
"Change disc" option in duckstation is equivalent to do this the real hardware: 
_1- open the disk cover with the console on
2- change the first disc for the second one (what you choose in game list)
3- close the disk cover_
You usually use this to progress with games with more than 1 CD (example: Final Fantasy 7) or unlock features (ex.: in Vigilant 8 2nd offense, if you pause the game, change the disc to OG Vigilante 1 game, you unlock old arenas to multiplayer). But you usually don't open the disk cover with a game running and change for another one without knowing what you're doing you the game will crash.

**Comment by stenzek** [comment]
Crashing when changing disc is still a bug though - those options should be disabled.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/e30c0a6881ed1d8abdab9bd1bed5d311899df159

(adds a "change disc" option to the menu instead of booting)

**Comment by stenzek** [comment]
Closing since it is fixed. Please comment if the crash is still occurring.
