### ISSUE TITLE
Music skipping in Time Crisis (USA)

### ISSUE THREAD

**Issue by mirrornoir** [stenzek/duckstation#651]
There's very minor audio skipping when changing music tracks throughout the game. The most noticeable is in Act 1 once you go through the doorway to the courtyard area, the music track changes and plays for about a second, then restarts that same track and continues playback normally. I've verified this issue does not happen in beetle-psx-hw.

I've included a screenshot of the SPU State when this issue happens. Voice 18 and 19 is the new track starting, you can see the issue happen in the SPU when these two voices are triggered twice for the "skipping" music. I've not had to post about an audio issue before so let me know what other info may help.
![image](https://user-images.githubusercontent.com/19215655/88232174-67870b00-cc43-11ea-9963-5e13a8948ab2.png)

**Comment by stenzek** [comment]
Hmm, sounds like the audio in the pregap. I've noticed other games where this is happening too.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/10f23667c90364e6c54e34fbc25b4733c095d246.

**Comment by mirrornoir** [comment]
That fixed it, thanks :+1: 
 
I'll update the compatibility entry for this game.
