### ISSUE TITLE
[libretro]: Invalid card 2 save path when used as "Shared Between All Games"

### ISSUE THREAD

**Issue by negativeExponent** [stenzek/duckstation#652]
ditto above:

![duckstation-memcar2-shared-path-issue](https://user-images.githubusercontent.com/54053706/88250942-c8fab880-ccdb-11ea-9995-7205709933b6.png)

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/99b0ba3f20a8aa5359ce2fef9653d93e77eeb74d (untested).

I also changed it to be named `duckstation_shared_card_N.mcd`, as `shared_card_N.mcd` might conflict with other cores.

**Comment by negativeExponent** [comment]
looks fine now, both saving and loading. Thanks.
![memcard2](https://user-images.githubusercontent.com/54053706/88359442-2b6bbb80-cda5-11ea-9bf6-dca28f16277a.png)
