### ISSUE TITLE
Game Wizard Plus (China) (Unl) hangs on the opening screen

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#656]
![2020-07-24_04-55-30](https://user-images.githubusercontent.com/31968468/88362132-c9b84b00-cdbe-11ea-8b04-cf70d26e49d4.png)

![Capture](https://user-images.githubusercontent.com/31968468/88362138-cd4bd200-cdbe-11ea-8693-cf5fa6aec624.PNG)

**Comment by stenzek** [comment]
Probably https://github.com/stenzek/duckstation/issues/598
