### ISSUE TITLE
Cheat Factory for Final Fantasy IX (Europe) (Unl) hangs on the title screen

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#658]
![UKPPSXEXE_2020-07-24_16-38-07](https://user-images.githubusercontent.com/31968468/88366290-24a46f00-cdcc-11ea-806d-933acb17371b.png)

![Capture](https://user-images.githubusercontent.com/31968468/88366297-28d08c80-cdcc-11ea-9f46-0f640c350499.PNG)

**Comment by stenzek** [comment]
I've said before any of these cheat discs aren't going to work until CPU breakpoints are implemented: https://github.com/stenzek/duckstation/issues/598

**Comment by kurayami6** [comment]
This is nothing to do with that. It hangs on the title screen before I even get to the cheats.
