### ISSUE TITLE
[Suggestion] Auto-include hash already checked in "export compatibility info"

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#659]
This may help to keep track of the issues when a game is broken. The ideal is just include the hashes if a status different than "no issue" is selected and the hash was previously verified.
In the compatibility list in Google drive this information can be in a new column and the game list can just ignore the new information to show.

**Comment by stenzek** [comment]
I guess we could add a "hash valid" tag to the entry. But that requires me to implement pulling the hash from the redump dat file, as well as checking it first :)

**Comment by stenzek** [comment]
On further thought, I don't want to complicate the process by validating the hashes when you click the export button.
