### ISSUE TITLE
Playstation logo appears twice in Gambler Jiko Chuushinha - Ippatsu Shoubu! (Japan)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#661]
After the opening PS1 logo fades away there's several seconds of black, then a glitchy version of the logo reappears for about 1 frame before the game's logo screen. This doesn't happen in Beetle PSX.

![SLPS-02509_2020-07-25_00-36-13](https://user-images.githubusercontent.com/31968468/88403428-e335b300-ce0f-11ea-9d0e-44127eb9b989.png)

![Capture](https://user-images.githubusercontent.com/31968468/88403440-e6c93a00-ce0f-11ea-90f6-cb4b157be2e8.PNG)

![SLPS-02509_2020-07-25_00-36-23](https://user-images.githubusercontent.com/31968468/88403457-ee88de80-ce0f-11ea-9b6f-946023aaa036.png)

**Comment by stenzek** [comment]
Probably a side effect of how I implement interlacing. Needs a buffer clear/copy when interlacing is switched on.

**Comment by TzakShrike** [comment]
I observed the same thing on a different game for a single frame BTW.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/818892cb1b5cb5dc90490bbe83fb50754af81b58
