### ISSUE TITLE
[SLUS-00035] Road Rash (USA)

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#662]
![image](https://user-images.githubusercontent.com/12163923/88413960-7f30d180-cdb2-11ea-82aa-e917a3d500fd.png)
![image](https://user-images.githubusercontent.com/12163923/88414072-a8516200-cdb2-11ea-9602-96a9c65a55ac.png)
**Version**
0.1-1334-g10f2366

**Specs**
Windows 10 x64
Using CHD (Hashes in the second image).

**Issue**
The music track in main menu is completely messy, going back and forward as you select things in menu. 
Tested the same CHD in MAME and this issue don't happen there.
Maybe related with https://github.com/stenzek/duckstation/issues/655 ?

**Comment by stenzek** [comment]
Only one track, no CDDA, so not the same problem.

**Comment by Shideravan** [comment]
Fixed as of 0.1-2433-g9089c973
