### ISSUE TITLE
The opening FMV of Minna no Takaramono - Watashi no Licca-chan - Otetsudai wo Shiyou (Japan) always stutters at the same points

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#663]
Tested with both Software renderer and Vulkan, fullscreen and windowed. The audio always stutters briefly at the exact same points. Doesn't happen in Beetle PSX. When it happens the log says this. 

![Capture](https://user-images.githubusercontent.com/31968468/88423772-abd6fe80-ce2f-11ea-9b0c-0fa81b55542e.PNG)

You can hear it stutter at the 3 second mark and the 14 second mark. 

[SLPM-87025_2020-07-25_04-15-00.zip](https://github.com/stenzek/duckstation/files/4973716/SLPM-87025_2020-07-25_04-15-00.zip)

**Comment by stenzek** [comment]
Fixed with https://github.com/stenzek/duckstation/commit/dd48a1f5858c5d4b4a91533c2302d1664a67effb
