### ISSUE TITLE
[SLUS-00423, SLUS-00746, SLPS-00800] Street Fighter Collection (USA and Japan)/Collection 2 (USA) - Incorrect graphics when upscaled

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#664]
![image](https://user-images.githubusercontent.com/12163923/88444888-de640580-cdf5-11ea-8a0f-4214cbfba82a.png)
![image](https://user-images.githubusercontent.com/12163923/88444951-15d2b200-cdf6-11ea-9f0a-84083e463c3b.png)
![image](https://user-images.githubusercontent.com/12163923/88445176-6dbde880-cdf7-11ea-967c-0e59a6686757.png)

**Version**
0.1-1336-gd711baa

**Issue**
If use a different resolution scale than 1x, graphic corruptions in HP meter, in Super Street Fighter II and Super Street Fighter II Turbo (Collection 1) and World Warrior, Champion Edition, Turbo Hyper Fighting (Collection 2). Tested with USA and Japan versions.

**Comment by stenzek** [comment]
Might be related to lines expansion. There's a few edge cases where it could break.

Upscaling issues are not considered critical bugs as it is an enhancement, and some games are impossible to upscale in a generic way, so there's a single thread for them here: https://github.com/stenzek/duckstation/issues/427 (I've pinned it now so it's more visible).

In this particular case it's a 2D/sprite game so no advantage to upscaling in the first place, we should just force it to 1x via gameini when I add that.
