### ISSUE TITLE
Dialogue stutters in Exodus Guilty (Japan).

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#667]
Just choose this chick and listen to her talk. Tested with both software renderer and Vulkan. 

[SLPS-01721_2020-07-25_20-56-34.zip](https://github.com/stenzek/duckstation/files/4975445/SLPS-01721_2020-07-25_20-56-34.zip)

![SLPS-01721_2020-07-25_21-02-18](https://user-images.githubusercontent.com/31968468/88455679-ab377a00-ceba-11ea-9840-7fa7d9fe9fd4.png)

**Comment by stenzek** [comment]
Fixed with https://github.com/stenzek/duckstation/commit/dd48a1f5858c5d4b4a91533c2302d1664a67effb
