### ISSUE TITLE
Auto Analog Mode locks gamepad in BIOS and some games

### ISSUE THREAD

**Issue by IPeluchito** [stenzek/duckstation#669]
**Enable Analog Mode on Reset** does not work in **Doom Trilogy (SLUS-00077)**, it has to be enabled manually for the buttons to work...

**Dualshock 4 (DS4Windows Xinput profile)**

**Comment by stenzek** [comment]
Might be a case of the game explicitly setting the controller to digital mode. Does it switch back to digital if you switch to analog while in the BIOS screen?

**Comment by ggrtk** [comment]
Doom doesn't support Analog Mode, it's a 1995 title which was before the Dual Analog / DualShock release in 1997. So if you're booting Doom with the "Enable Analog Mode on Reset" option, then you're probably having to manually switch back to Digital Mode for the buttons to work.

**Comment by IPeluchito** [comment]
Same issue on BIOS display, Agile Warrior F-111X, Castlevania Symphony of the Night, maybe others .... if you manually switch to Analog it works fine...

**Comment by IPeluchito** [comment]
The main problem is that with **Auto Analog Mode Enabled** no button works **!!!** Except for the Analog button ... even on the Bios screen, I hope I explained it well, excuse my English ...

**Comment by stenzek** [comment]
If the game does not support analog mode, then the auto enable mode will prevent you from using the controller. This is why I was hesitant to add the option in the first place, because it breaks games which do not understand the analog controller.

**Comment by IPeluchito** [comment]
Enable Analog Mode on Reset locks gamepad in BIOS and some games... that's it

FIN

**Comment by stenzek** [comment]
I'm not sure what you want me to do about it. How is the emulator supposed to know which games support and do not support analog mode?
