### ISSUE TITLE
Sound Bug in Agile Warrior F-111X (SLUS-00023)

### ISSUE THREAD

**Issue by IPeluchito** [stenzek/duckstation#670]
Before loading the background sound of the CD a **beep** is heard, then the background sound of the CD is heard normally ...

**Comment by kurayami6** [comment]
You should post a recording of it and specify at what point in the game it happens. Also what renderer you're using and if it happens in other emulators.

**Comment by IPeluchito** [comment]
https://youtu.be/59nX65JPJZ8

**Comment by kurayami6** [comment]
Are you talking about that buzzing sound during the virgin interactive logo? Could you try with a Redump verified version of the game and see if it still happens?

**Comment by stenzek** [comment]
Hmm, yeah, could be dump related. It starts playing CDDA but can't seem to reproduce the buzz.

**Comment by IPeluchito** [comment]
You are right, I just tried it with another image (13 bin files and 1 cue) and it works correctly ....
