### ISSUE TITLE
Right-click game list directory to give "open folder" option

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#671]
This is a mini-suggestion I would find very useful: allow right-clicking a game list path to offer "open location" in the given file browser (ie explorer).

I often go there to extract games, delete others, etc. So this would be a handy little shortcut.

Thanks for considering.

**Comment by stenzek** [comment]
I think this is already a thing? (Right-click -> Open Containing Directory)

**Comment by Richard-L** [comment]
Ah, I meant from "Game List Settings".

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/77481f5b231c9fd480e697120e79e8726185ea27
