### ISSUE TITLE
Unrecognized holded keys after load state

### ISSUE THREAD

**Issue by zeraln** [stenzek/duckstation#674]
Duckstation is a nearly perfect emulator, but i have a request when using a load state.
All the emulators that I used before when executing a load state, the pressed key will continue to work if I keep it holding during the load, but with this emulator it doesn't happen the same, and i need to press the key again to continue the command.
Have a way to solve this issue?

**Comment by ggrtk** [comment]
Think this is a duplicate of #1088 which was solved.
