### ISSUE TITLE
Fail to Boot issue (UTF-8)

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#676]
Hi!

**Issue**: System fail to boot

**Steps to reproduce it**: A friend told me yesterday he is getting issues when boot the emulator as you may view here in the capture attached. 

![UTF](https://user-images.githubusercontent.com/43047877/88991835-22ed1680-d2b8-11ea-9b6e-2d8f060d5e2a.png)

Path he is using was as follows: D:\**Emulação**\duckstation\bios 
It seems to be related to words with accents like shown above, **Emulação** (meaning in Brazilian Portuguese) emulation, is the cause of DS does not 'see' the BIOS. 

when we change it to: D:\emulacao\duckstation\bios it does work.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/66e79091d3afb7671ffd3af5644773e2dc244743. Please confirm.

There's a few other places which still use fopen, e.g. chds. So if you have unicode characters in the path of the chd image, it probably won't load either.

**Comment by andercard0** [comment]
> 
> 
> Should be fixed with [66e7909](https://github.com/stenzek/duckstation/commit/66e79091d3afb7671ffd3af5644773e2dc244743). Please confirm.
> 
> There's a few other places which still use fopen, e.g. chds. So if you have unicode characters in the path of the chd image, it probably won't load either. bin/cue would be fine.

Yo Sten, 
Confirmed it's working now. But. same behaviour is now in gamelist.

Example: 
D:\Emulação\Jogos... Emulator is not showing games

D:\Emulaçao\Jogos... if the accent is removed in game path game list imediately appears.

**Comment by stenzek** [comment]
Should all be fixed now, hopefully. I've also patched up the CHD loader to support UTF-8 filenames.

**Comment by andercard0** [comment]
> Should all be fixed now, hopefully. I've also patched up the CHD loader to support UTF-8 filenames.

 It is working now; could not test with CHDs because I do not have those, and I'm too lazy to convert them. 

But main problem was solved! 

Thank You. 😁
