### ISSUE TITLE
Regression in D3D11 backend for several games

### ISSUE THREAD

**Issue by Abbanon** [stenzek/duckstation#677]
As of a few builds ago (specifically, I first noticed it in the un-merged test build linked in the Discord here: https://github.com/stenzek/duckstation/suites/986187316/artifacts/12659271 -- But it might have started a build or two earlier than that) there's been some major regressions with the **D3D11** backend, notably with the title **Ace Combat 2 [SLUS-00404]**.
I haven't tested any other titles yet.
Previously, these issues only happened to a minor degree in **2x** and higher, but now the issues are considerably worse than before and happen even at **1x**.

Here's some screenshots:
- Here's **Software Rendering**, which is perfectly normal.
![Software Rendering](https://user-images.githubusercontent.com/37251822/89043463-8443d280-d316-11ea-9658-034a6941b04f.png)

- Here's **D3D11** at **1x**. I've highlighted the erroneous bits.
![d3d11 - 1x](https://user-images.githubusercontent.com/37251822/89043678-d8e74d80-d316-11ea-900f-7e69e7353a13.png)

- And here's **D3D11** at **2x**, which makes everything considerably worse. It's like this from **2x** to max.
(I know anything above **1x** belongs in the **Graphics Upscaling Issues Megathread**, but figured I'd include it in posts here for the sake of comparison and visual clarity to see just how bad this has regressed.)
![d3d11 - 2x](https://user-images.githubusercontent.com/37251822/89044167-9a9e5e00-d317-11ea-87c2-177ef56f5522.png)

- Previously, this was the only issue when upscaling in **D3D11** to **2x** or higher:
(Again, for comparison's sake.)
![88049089-79bd5800-cb22-11ea-9ccd-57c9350371a6](https://user-images.githubusercontent.com/37251822/89044498-0c76a780-d318-11ea-8076-593f21293126.png)

As for additional information:
- I can't test Vulkan, my computer doesn't support it.
- OpenGL doesn't seem to work for me beyond **1x**, changing it to **2x** or higher doesn't actually do anything at all. But at **1x** it's 1:1 with **Software Rendering**.

**Comment by stenzek** [comment]
I'd guess it's probably https://github.com/stenzek/duckstation/commit/d711baaa31b3409333a8baf55383faf247767c0b

Strange that it's fine in OpenGL though, that change happens at the frontend before it hits any API-specific code.

**Comment by Abbanon** [comment]
Discovered another game that suffers with this **D3D11** at **1x** regression, **Front Mission 3 [SLUS-01011]**.
- **Software Rendering**:
![software](https://user-images.githubusercontent.com/37251822/89105767-1d93e700-d3f2-11ea-8fdf-77a4da20a8e8.png)

- **D3D11* at **1x**:
![d3d11 1x](https://user-images.githubusercontent.com/37251822/89105780-30a6b700-d3f2-11ea-9757-d059cd5cd30f.png)

- **D3D11** at **5x** (For comparison/clearer indication to see how messed up it is):
![d3d11 5x](https://user-images.githubusercontent.com/37251822/89105794-4f0cb280-d3f2-11ea-9fcd-24a16dcd0081.png)

**Comment by Abbanon** [comment]
After further testing, this seems to have been addressed and fixed in the latest build at the time of this message. Closing this issue!
