### ISSUE TITLE
Black screen after intro movie in Final Fantasy IX on Android RetroArch

### ISSUE THREAD

**Issue by mikerogerz** [stenzek/duckstation#678]
Using default settings, Vulkan video driver.

**Comment by stenzek** [comment]
Hmm, might be a regression. This was working a few weeks ago.

**Comment by stenzek** [comment]
Seems to be working here on a Mali GPU. Which device are you using? Does it affect other games?

**Comment by mikerogerz** [comment]
I'm on the Nvidia Shield TV pro.. all other games have been working
perfectly fine. Is there any way I can help with debugging?

**Comment by mikerogerz** [comment]
Replied without seeing your edit.

I really appreciate it. Love the emulator, performance is incredible. Also if it's any help, I'm on the Nvidia Shield TV Pro.

**Comment by stenzek** [comment]
Try the latest build, in particular https://github.com/stenzek/duckstation/commit/be6ae8b70b1ee18d371ea6c697bd0e47a2e4ef76

With any luck it'll be the same issue. But that was on a Mali GPU, so it might not be.

**Comment by mikerogerz** [comment]
As soon as the retroarch buildbot compiles the latest version, I'll test it
out. Thanks a lot.

**Comment by mikerogerz** [comment]
@stenzek Just tested the latest build, and the same issue is happening.

You can actually see graphical glitches earlier if it helps... if instead of going to New Game and waiting for the intro video to finish, select Continue, then attempt to read from a memory card. Then go back to the main screen, and the graphics are corrupted. Not sure if related, but thought that might be easier to test.

**Comment by stenzek** [comment]
Obviously an issue with VRAM readbacks then. Just strange that it doesn't happen on a desktop NVIDIA GPU, given they should be running similar drivers.

**Comment by mikerogerz** [comment]
If there's any other info I can provide, let me know.

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation/commit/dd0ae0fc9d7a39584d0af22d70840c3e3cb4d29b fixes the graphical corruption on a Mali GPU when going in/out of the load screen. Hopefully will fix the Shield too.

**Comment by mikerogerz** [comment]
@stenzek Thanks a lot. I'll test on the Shield tomorrow and let you know.

**Comment by mikerogerz** [comment]
@stenzek Seems to be fixed now, at least the previously reported errors. I didn't progress much in the game (just testing), but no more black screen nor visual corruptions on the in-game menu like before.
