### ISSUE TITLE
Failing to create or overwrite a savestate

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#679]
**Version**
0.1-1375-gb6f871d2

**Config**
Windows 10 x64

**Issue**
The emulator is failing to create a savestate, possibly due error in the path generation (take a look at "/" and "\" in the image below)

![image](https://user-images.githubusercontent.com/12163923/89092628-b17d9880-d389-11ea-9b58-3f2913801ef0.png)

**Comment by stenzek** [comment]
Can't seem to reproduce this. The forward vs backslashes shouldn't be a problem.

Can you enable the system console log in advanced options, set the log level to developer, try again and paste the output?

**Comment by Shideravan** [comment]
Strangely enough, but as soon as I did the procedure the error stopped showing up. Maybe because I saved a new configuration? hmmm

**Comment by Shideravan** [comment]
Strangely enough, but as soon as I did the procedure the error stopped showing up. Maybe because I saved a new configuration? hmmm
![image](https://user-images.githubusercontent.com/12163923/89093450-e04b3d00-d390-11ea-98ec-2d1e2bedacc5.png)

**Comment by stenzek** [comment]
Not sure. If it happens again please let me know and I'll look into it.
