### ISSUE TITLE
No directional input in Crisis Beat (Japan) when using DualShock controller

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#68]
Tried with both analog sticks and D-pad. Every other button works fine but I can't move or scroll through the menus.

**Comment by stenzek** [comment]
This appears to be specific to the DualShock controller. Using the digital controller works fine.

**Comment by stenzek** [comment]
Please re-test on latest build.

**Comment by kurayami6** [comment]
Fixed.
