### ISSUE TITLE
[Feature Request] CPU overclocking 

### ISSUE THREAD

**Issue by MojoJojoDojo** [stenzek/duckstation#681]
As the title says the ability to overclock the emulated PS1 CPU.

**Comment by Blackbird88** [comment]
I'd like to add that it'd be nice if it was slider like Dolphin has
![image](https://user-images.githubusercontent.com/4414625/91561862-937d6680-e93c-11ea-9363-0b7b7825915e.png)

ePSXe and PCSX-R sadly only have few preset values which is kinda limiting :/
![image](https://user-images.githubusercontent.com/4414625/91561979-b60f7f80-e93c-11ea-8b77-6cea89c765fc.png)
![image](https://user-images.githubusercontent.com/4414625/91561950-ab54ea80-e93c-11ea-9991-88c5f4102f79.png)

**Comment by MojoJojoDojo** [comment]
I think Stenzek said its not feasible for PS1 so it would be similar to what PCSX-R and ePSXe does (and in a way beetle psx).

**Comment by stenzek** [comment]
The "Dolphin way" might be possible. Been a while since I looked at how we did it there, but if I remember correctly it adjusted all other events relative to the overclock, rather than making the CPU take "less time to execute".

**Comment by stenzek** [comment]
Implemented in latest build.
