### ISSUE TITLE
Broken OSD

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#682]
In version "5f9481d" the OSD for both FPS/VPS and event messages is broken after some ALT+TAB fullscreen toggling it seems: 
![image](https://user-images.githubusercontent.com/4934209/89110477-37154d00-d44b-11ea-968e-7df18aba7610.png)

Restarting DS fixes it.

**Comment by stenzek** [comment]
Hmm, haven't noticed this one. Could you give me some more details, including your GPU/driver and which renderer?

**Comment by Richard-L** [comment]
I experienced this on two different machines now, and can't reproduce it reliably either.

- NVidia Quadro M620, Vulkan
- NVidia GeForce (some ~2012 chip), D3D11

Is it thinkable it has to do with switching from PAL to J-NTSC? I do that a lot.

**Comment by stenzek** [comment]
The OSD code's gone through multiple changes since this issue, hopefully it's not happening anymore. If it still is, let me know and  I will re-open.
