### ISSUE TITLE
[Request]Retro Achievements support

### ISSUE THREAD

**Issue by RinMaru** [stenzek/duckstation#683]
So i just uninstalled RetroArch in favor of your Emu and I love it. no more bloat. I do miss one thing though and thats https://retroachievements.org/ integration would it be possible to add the feature to this in the Stand alone Emu?

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/d6b8a80eb705ba317fc15cf710a1a07b846a6d38. Still needs hardcore mode, leaderboards, and Linux support.
