### ISSUE TITLE
White lines on wheels in Gran Turismo 2 with PGXP enabled

### ISSUE THREAD

**Issue by bigol83** [stenzek/duckstation#685]
I tested it with native resolution too and it isn't a resolution issue but a bug introduced by PGXP

The same bug is also in Beetle HW PGXP 

![Gran Turismo 2 (Europe) (Disc 2) (Gran Turismo Mode Disc)-200802-124924](https://user-images.githubusercontent.com/38129260/89121432-2f8f8b80-d4bf-11ea-9e6d-cfc5a391026f.png)

I'm using retroarch build 

nvidia gt 1030 card
g4400 cpu

**Comment by stenzek** [comment]
If this is still happening on the latest release, please list it in https://github.com/stenzek/duckstation/issues/733
