### ISSUE TITLE
[Request] Put the "``"s automatically in Compatibility info export

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#686]
This will help to people just comment with the generated results in https://github.com/stenzek/duckstation/issues/450 without the need to put the "``" manually and avoid wrong comments there :)

**Comment by Shideravan** [comment]
This will help with grouped ones to, as put "``"s will show them in gray squares which can help you to see every entry to update the list ;-)

**Comment by stenzek** [comment]
Not planning on implementing this.
