### ISSUE TITLE
[SLUS-00215/SLUS-00216] Motherboard image in game options is broken in Namco Museum 1, 1.1 and 2

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#688]
**Version**
0.1-1407-g08b81764

**How you find this screen?**
Start a game and press "triangle" button in the arcade game title screen. This is the game options screen.

**In the original console**
This is a image example of how this screen are shown in the original console
![image](https://user-images.githubusercontent.com/12163923/89130270-df71f280-d4d9-11ea-8476-a2622d2c1d26.png)

**In Duckstation**
This is 2 images examples of how this screen are shown in DuckStation. Isn't a scalling issue as it happens in both software and hardware renderers, in both interpreter and recompiler execution modes.

_Software Renderer_ (Pac-Man)
![image](https://user-images.githubusercontent.com/12163923/89130319-57401d00-d4da-11ea-9579-3a4d9987b528.png)

_Hardware Renderer_ (Toy Pop)
![image](https://user-images.githubusercontent.com/12163923/89130355-b6059680-d4da-11ea-8136-f6d45c9ef2fe.png)

**Comment by stenzek** [comment]
Thanks for the reference image. Definitely broken :)

**Comment by Shideravan** [comment]
Fixed in 0.1-1415-gdd9705ef
Thanks to https://github.com/stenzek/duckstation/commit/dd9705ef31f3359f8d41a88b58cdc42599c733c4
