### ISSUE TITLE
CART World Series (USA) freezes up when it goes to load any race

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#69]
![cart](https://user-images.githubusercontent.com/2696404/76160951-6c05c800-6169-11ea-9b3c-137319285da9.PNG)
![cart1](https://user-images.githubusercontent.com/2696404/76160952-6dcf8b80-6169-11ea-9874-15fbc3b1953a.PNG)

**Comment by stenzek** [comment]
Please re-test on latest master.

**Comment by benderscruffy** [comment]
goes ingame now
