### ISSUE TITLE
Broken water textures in 40 Winks with PGXP texture correction enabled

### ISSUE THREAD

**Issue by ds22x** [stenzek/duckstation#691]
![SPOILER_40_Winks_USA-200802-230509](https://user-images.githubusercontent.com/45218067/89177600-20c2da80-d58c-11ea-860b-71cc3f02281d.png)
Seems to only happen when texture correction is enabled.
The water textures look fine with the same settings with Beetle PSX.

Tested on the RetroArch Duckstation core for Windows, using both DirectX11 and Vulkan renderers, regardless of resolution settings, using Windows 10 with an Intel Core i5-9300H CPU, a Nvidia GTX 1650 GPU, and 16GB of DDR4 RAM

**Comment by Shideravan** [comment]
I think that PGXP texture correction is preliminar yet. Most of the games that I tested has any kind of issue.
![image](https://user-images.githubusercontent.com/12163923/89199872-99726880-d585-11ea-934b-6ad1518faa55.png)
![image](https://user-images.githubusercontent.com/12163923/89200274-23223600-d586-11ea-99a3-cf5d699dc55d.png)
![image](https://user-images.githubusercontent.com/12163923/89200471-72686680-d586-11ea-9864-656942d7a10d.png)
![image](https://user-images.githubusercontent.com/12163923/89200910-17833f00-d587-11ea-807f-a72ea245d594.png)

**Comment by Richard-L** [comment]
@ds22x this is the effect, right?

https://cdn.discordapp.com/attachments/695640472202379428/739168259038904340/5AfqSJqT1l.mp4

**Comment by ds22x** [comment]
That is the effect, yes.

**Comment by RinMaru** [comment]
works fine on the windows standalone version

**Comment by Shideravan** [comment]
> works fine on the windows standalone version

I'm using the windows standalone version and have the issues. Please check you checked PGXP Geometry Correction and PGXP Texture Correction in GPU Settings.

**Comment by Richard-L** [comment]
@RinMaru still have the same issue to with the latest version

**Comment by RinMaru** [comment]
im on ver 0.1 - 394-g75156b76 and i dont have those issues

**Comment by RinMaru** [comment]
still no issue here with latest build got Intel i5-6402p AMD RX 480
![SLUS-00874_2020-08-03_19-23-14](https://user-images.githubusercontent.com/15071652/89236537-dd359400-d5be-11ea-964a-48c7fe2aea74.png)

**Comment by Richard-L** [comment]
Curious.

What hardware do you have?

And any chance you could test Tomb Raider, too?

**Comment by RinMaru** [comment]
> Curious.
> 
> What hardware do you have?
> 
> And any chance you could test Tomb Raider, too?

Yep Tomb Raider has the Issue here

**Comment by stenzek** [comment]
Seems to be specific to NVIDIA... fine on Intel.

**Comment by RinMaru** [comment]
I got AMD lol

**Comment by stenzek** [comment]
Well, I get the tomb raider issue on the NV GPU in my laptop, but not Intel.

**Comment by RinMaru** [comment]
Tomb raider is the only game i could repro on

**Comment by Blackbird88** [comment]
Happens in MGS1 too. Water flickers.
![SLUS-00594_2020-08-09_19-26-56](https://user-images.githubusercontent.com/4414625/89738106-5711c580-da76-11ea-878f-a3f25000bd5c.png)

**Comment by RinMaru** [comment]
**### Games Affected By PGXP**

1. 40 Winks (**SLUS-00874**) - _Flickering water_
2. Crash Bandicoot Warped (**SCUS-94244**) - _Visible seams in geometry from a distance_
3. Tomb Raider (**SLUS-00152**) - _Corrupted textures on geometry_
4.  Metal Gear Solid (**SLUS-00594**) - _Flickering water_

**Comment by stenzek** [comment]
I already have a fix - it's in the uv-limits branch. Just have to refactor things so it doesn't have a small performance hit to non-pgxp mode (enhancements shouldn't have any perf impact when they're disabled IMO).

**Comment by RinMaru** [comment]
alright well it should be helpful to list games here for any PGXP problems

**Comment by MojoJojoDojo** [comment]
Well if it counts games that PGXP have no affect on then you have all of the games that got developed by Argonaut Games (except Alien: Resurrection) and Alundra 2.

**Comment by stenzek** [comment]
Sure, can list them here. But it might be worth using a new thread once the UV limit fix is in.

I don't consider PGXP issues critical as it's an enhancement, so like with upscaling I'd rather not have different threads for each game (as some of them may not be fixable).

**Comment by stenzek** [comment]
Should hopefully be fixed with https://github.com/stenzek/duckstation/commit/5c6e92cdfc8a5533c153580385415e19c2dcc382

For other games with PGXP incompatibilities, please use https://github.com/stenzek/duckstation/issues/733
