### ISSUE TITLE
[Feature request] Sharp bilinear filter for native resolution.

### ISSUE THREAD

**Issue by levonnn** [stenzek/duckstation#692]
At the moment the only way to achieve even upscaling of pixels is using higher than native resolution. Up to 5 or more almost without losing sharpness of image. There's one downside though. Some games like Castlevania: Symphony of the Night use 3D at some points and these elements end up being rendered at non-native resolution. So purist freaks like myself can't enjoy the original visuals. I'd really love this feature included at some point in the future.

**Comment by stenzek** [comment]
Duplicate of https://github.com/stenzek/duckstation/issues/1564
