### ISSUE TITLE
[SLUS-00449]Arcade's Greatest Hits - The Atari Collection 2 (USA): Graphical errors in Paperboy game

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#693]
**Version**
0.1-1409-ge198e315

**Issue**
Strange blacklines flickering in screen when the paperboy starts to run. It happens in both software and hardware renderers.
![image](https://user-images.githubusercontent.com/12163923/89199422-e6a20a80-d584-11ea-8370-29047c98901e.png)

**Comment by stenzek** [comment]
Not seeing the black lines, but the text doesn't look correct.

**Comment by Shideravan** [comment]
It's in the middle of the screen. I'm sending a video.
https://youtu.be/FLfuqLI73WQ

**Comment by Shideravan** [comment]
I think this is the expected behavior: https://www.youtube.com/watch?v=9HDaS8D-qMk

**Comment by stenzek** [comment]
Can't reproduce in the latest build. If it's still happening for you, please let me know.

**Comment by Shideravan** [comment]
No, it's solved in recent builds :)
