### ISSUE TITLE
[SCUS-94200] Battle Arena Toshinden (USA) and [SLUS-00183] Zero Divide (USA): Speed issues ingame

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#695]
**Version**
0.1-1409-ge198e315

**Issue**
These games run in a unnatural faster speed while in fight itself. As the issue seems to be correlated, I put both games in the same report.

**Comment by stenzek** [comment]
Probably these games which need the CPU or GPU to be slower. The ones I've looked at, the CPU seems to be the issue, and it's not going to be precise until I add icache emulation (which will not be in the recompiler).

**Comment by Shideravan** [comment]
The game [SLUS-00658] DBZ - Dead Ball Zone (USA) (En,Fr,De,Es,It) has the same issue.

**Comment by stenzek** [comment]
Zero Divide appears to be fixed with the icache enabled.

**Comment by Shideravan** [comment]
Battle Arena toshinden seems to be fixed too in recent versions. Closed.
