### ISSUE TITLE
[SLUS-01215] Blade (USA): Strange performance issues.

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#696]
**Version**
0.1-1409-ge198e315

**Issue**
Strange performance issues ingame. After a while duckstation can't mantain 100% speed.
Tested in both interpreter/recompiler and with software and vulkan rederers.

**Comment by stenzek** [comment]
That's really strange. How long is "a while"? Can you check if the memory usage of the process grows?

If it was a code cache issue, the problem shouldn't happen in pure interpreter.

**Comment by stenzek** [comment]
Could be worth re-checking with the latest build - in particular the list-based block linking which could fill up and slow things down isn't used anymore.

**Comment by stenzek** [comment]
Closing due to lack of response. Please provide more detail if this is still occurring.
