### ISSUE TITLE
[GUI-QT] Windows: When resizing the window, the scroll bar isn't considerated to everything fit in the screen

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#697]
**Version**
0.1-1409-ge198e315

**SO**
Windows 10 x64

**Issue**
With a big game list, when changes the size of the window, the scrollbar is over "compatibility stars"
![image](https://user-images.githubusercontent.com/12163923/89210033-c4fd4f00-d595-11ea-9aa3-293fd7836db0.png)

**Comment by ggrtk** [comment]
Should be fixed by 6e0b71a.
