### ISSUE TITLE
[SLUS-00952] Arcade Party Pak (USA) - "Purple screen of death" in Super Sprint

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#699]
**Version**
0.1-1409-ge198e315

**Issue**
If you chooses Super Sprint, the game will freeze in a flickering purple screen. The game softlocks at this point.

**Comment by stenzek** [comment]
Can't reproduce in the latest build. If it's still happening for you, please let me know.

**Comment by Shideravan** [comment]
No, it's fixed in the recent builds :)
