### ISSUE TITLE
Dare Devil Derby 3D (USA) black screen

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#70]
shows one developers screen then nothing but a black screen

**Comment by stenzek** [comment]
Can't seem to reproduce this one, could you be more specific?

**Comment by benderscruffy** [comment]
shows the mindscape screen then nothing but a black screen after that
![dare](https://user-images.githubusercontent.com/2696404/76502901-d7a8a780-647f-11ea-8ddf-095d4504d958.PNG)
![dare1](https://user-images.githubusercontent.com/2696404/76502906-d9726b00-647f-11ea-90f9-a631a51a968d.PNG)
![dare2](https://user-images.githubusercontent.com/2696404/76502911-db3c2e80-647f-11ea-898f-75bc53e6f27f.PNG)

**Comment by stenzek** [comment]
Please retry with "enable tty output" turned off. The way this is implemented breaks some games, I suspect this may be one of them.

**Comment by benderscruffy** [comment]
correct if you turn off enable tty output it goes ingame
