### ISSUE TITLE
[SLUS-00576] Crime Killer (USA) - Screen is slightly stretched vertically

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#703]
**Version**
0.1-1409-ge198e315

**Issue**
The image on the screen is slightly stretched vertically, which is enough to crop the logo on the loading screen.

Duckstation (software renderer)
![image](https://user-images.githubusercontent.com/12163923/89233463-0276d200-d5c0-11ea-88bd-e29457a7053a.png)

MAME
![image](https://user-images.githubusercontent.com/12163923/89233509-17ebfc00-d5c0-11ea-8e91-1bd6530f8c66.png)

Ps.: The game has a screen positioning option, but I didn't used in the examples. Just to be sure, I tested the game with "no memory card" option and this is the first screen in the game. Both tested using the same CD image. 
It's also worth noting how perfectly round objects (as the circle in the logo in the image above) are shown in an oval shape due the stretching.

**Comment by stenzek** [comment]
What if you use the "none" crop mode?

**Comment by Shideravan** [comment]
With crop mode set to "none" the game displays correctly. 
![image](https://user-images.githubusercontent.com/12163923/89250717-bb9ed180-d5eb-11ea-9ac1-bb6d09a4dba1.png)

**Comment by stenzek** [comment]
Not a bug then.

**Comment by Shideravan** [comment]
Well, then I'll close the issue
