### ISSUE TITLE
[GUI-QT] Linux: can't open Duckstation AppImage, Qt platform plugin not found

### ISSUE THREAD

**Issue by Codalunga** [stenzek/duckstation#704]
When trying to open DuckStation:

<pre>./duckstation-qt-x64.AppImage
qt.qpa.plugin: Could not find the Qt platform plugin &quot;wayland&quot; in &quot;&quot;
qt.qpa.plugin: Could not load the Qt platform plugin &quot;xcb&quot; in &quot;&quot; even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
</pre>

Fedora 32 Gnome Wayland
i7-8565U

**Comment by stenzek** [comment]
This seems more like an AppImage issue.. There is Wayland support, but it's disabled by default as depending on your system setup, you might get the X11 EGL headers. But I successfully used it on an ODROID-N2.

**Comment by Codalunga** [comment]
@stenzek just trying to open DuckStation on Xorg, but I get pretty much the same error:
<pre>./duckstation-qt-x64.AppImage
qt.qpa.plugin: Could not load the Qt platform plugin &quot;xcb&quot; in &quot;&quot; even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
</pre>
Not sure if it's because it's actually running some Wayland compatibility layer or something different.

**Comment by stenzek** [comment]
@ggrtk any idea if the Wayland platform plugin can be packaged with the AppImage? Ideally we don't want to go do through XWayland if possible :)

**Comment by ggrtk** [comment]
Should be possible, will look into this.

**Comment by BailShamber** [comment]
Apparently the linuxdeploy qt plugin doesn't have the needed qt-wayland libs.

https://github.com/linuxdeploy/linuxdeploy-plugin-qt/issues/22

But in the future it might be something that will be implemented, when they upgrade their platform base from ubuntu trusty to newer.

https://github.com/linuxdeploy/linuxdeploy-plugin-qt/pull/25

**Comment by BailShamber** [comment]
@Codalunga Try
`env QT_QPA_PLATFORM=xcb ./duckstation-qt-x64.AppImage`

**Comment by ggrtk** [comment]
> Apparently the linuxdeploy qt plugin doesn't have the needed qt-wayland libs.
> 
> But in the future it might be something that will be implemented, when they upgrade their platform base from ubuntu trusty to newer. (ubuntu trusty end of life is at April 2022)

This is known to us. I played around with a different tool that supposedly had support for the Wayland Qt platform plugin, but was never able to get it to work properly in all cases.

> Try
> `env QT_QPA_PLATFORM=xcb ./duckstation-qt-x64.AppImage`

Shouldn't be necessary, a workaround was added in the linked PR from October.

**Comment by stenzek** [comment]
There's an open PR to fix this in `linuxdeploy-plugin-qt` by adding an environment variable for platforms, but it appears to be dead.

Therefore, this is not an issue for duckstation to solve. Long term it might be better to just release static linked binaries instead...
