### ISSUE TITLE
[Libretro] Auto analog mode not working

### ISSUE THREAD

**Issue by ds22x** [stenzek/duckstation#706]
Don't know if the issue is already known, but the auto analog mode option currently doesn't do anything for the Libretro core.

**Comment by stenzek** [comment]
You have the controller type set to analog, right?

**Comment by ds22x** [comment]
Yes I have, but it doesn't seem to automatically switch.
It's especially noticable with games that refuse to work with the DualShock.

**Comment by stenzek** [comment]
Pretty sure I did check it a while back.

What do you mean by "games that refuse to work with dualshock"? If you have the auto enable option enabled, those games shouldn't have any controller input at all (it won't be recognized).

**Comment by ds22x** [comment]
That's right, when auto is enabled and the controller type is set to analog, those games don't have any inputs at all.
But yeah, the auto option doesn't seem to work, neither when the control type is set to analog nor digital.

**Comment by stenzek** [comment]
That's... working as intended then?

It'll have no effect with the type set to digital controller - `Automatically enables analog mode in supported controllers at start/reset.`. The only supported controller for this is the analog controller.

If it wasn't auto-switching to analog mode, those games which aren't dualshock compatible would receive d-pad input as usual. This is the reason why I was very hesitant to add the option in the first place, but people kept asking for it.

**Comment by ds22x** [comment]
I see.
I assumed it would work the same way Beetle PSX handles it, where it detects when a game supports the DualShock, it will switch the controls to analog, and keeps them digital when it doesn't support them after the BIOS.

**Comment by ds22x** [comment]
E.G.:
https://youtu.be/HV-Y9tQqrm4
https://youtu.be/NpZot5Xbe9M

**Comment by ggrtk** [comment]
> I see.
> I assumed it would work the same way Beetle PSX handles it, where it detects when a game supports the DualShock, it will switch the controls to analog, and keeps them digital when it doesn't support them after the BIOS (an example of this is with Rayman, where I have to specifically set it to digital with DuckStation for the controls to work, whereas with Beetle leaving the control type to DualShock and enabling the Analog toggle will still allow for functioning controls).

Beetle doesn't do any sort of automatic detection. Beetle's "Enable DualShock Analog Mode Toggle", like the description says, allows for the emulated DualShock controller to be toggled between digital mode and analog mode like original hardware. When this option is disabled, the DualShock controller is forced to analog mode and you can't toggle modes at all.

Having "Enable DualShock Analog Mode Toggle" on in Beetle is equivalent in behavior to having "Auto Analog Mode" off in DuckStation.

**Comment by ds22x** [comment]
Except it clearly works to detect and set it appropriately with Beetle in cases like Rayman and Ridge Racer, while it will always set it to analog with DuckStation.

**Comment by ggrtk** [comment]
I think this issue can be closed now, as hopefully the updated naming and description will clear up any misconceptions about what this option does.

**Comment by stenzek** [comment]
Sounds reasonable.
