### ISSUE TITLE
Android frontend doesn't let you override/set the BIOS filename

### ISSUE THREAD

**Issue by saintbepis** [stenzek/duckstation#707]
Bios scph5501.bin is recognized by the emulator on android but bios SCPH7502.BIN is not and will stay on a black screen or crash when used

**Comment by stenzek** [comment]
scph7502.bin is one of the filenames which will be searched, but only for running PAL games. If you're trying to run a NTSC game with it, it won't work.

I will add an option which you can use to set the BIOS for all regions to a specific file soon.

**Comment by saintbepis** [comment]
Oooooh I see. So that means bios's have to be used with games with the same region coding as the bios for now?

**Comment by stenzek** [comment]
Doesn't have to be. There is an option in the standalone versions "BIOS Path" which will be used if the BIOS for one of the regions can't be found, it just doesn't exist in Android yet.

This path happens to default to `bios/scph1001.bin`'. So as a workaround, if you rename `scph7502.bin` to `scph1001.bin` it should work for all regions in the meantime.

**Comment by saintbepis** [comment]
Thats a really neat work around that managed to boot the other bios. Unrelated to this thread but is there a way I can transfer my epsxe save files to duckstation?

**Comment by stenzek** [comment]
Memory cards should be compatible, assuming they're 128KB in size. Just need to rename/move them.

**Comment by saintbepis** [comment]
> Memory cards should be compatible, assuming they're 128KB in size. Just need to rename/move them.

Thats all I needed to know, thank you. :)

**Comment by forz0i** [comment]
add   bios HLE  internal  in duckstation

Le mar. 4 août 2020 à 21:36, Connor McLaughlin <notifications@github.com> a
écrit :

**Comment by stenzek** [comment]
Latest versions let you import BIOSes, which is a workaround for this issue.
