### ISSUE TITLE
[Bug] Minor UI problem regarding multiple languages

### ISSUE THREAD

**Issue by TzakShrike** [stenzek/duckstation#708]
![image](https://user-images.githubusercontent.com/658980/89336500-72767c80-d6d4-11ea-86d7-f36642770eea.png)

These behave like the wrong kind of checked list item. They should function like radiobuttons rather than checkboxes. This is incredibly minor.

**Comment by stenzek** [comment]
Fixed by https://github.com/stenzek/duckstation/commit/92bc65d88350dd6fe737d43e60c9a5c71a9303fb
