### ISSUE TITLE
[Libretro] Option to load CD image to RAM not exposed

### ISSUE THREAD

**Issue by brianblakely** [stenzek/duckstation#709]
Is this always enabled in libretro?  Always disabled for some reason?

Thanks!

**Comment by stenzek** [comment]
The main reason I didn't expose this was because I don't use imgui with the libretro core, so there's no way to draw the loading bar. If you're happy with the emu just freezing while it preloads, I'll add it :P

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/2cc1fe9c026ddc5c369e05a9ad9257a39d49b1dc, but I haven't tested it. Let me know if it does not work.
