### ISSUE TITLE
Darkstalkers 3 (USA) graphic glitches in both opengl and d3d11

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#71]
on the character select screen it is missing the background and the characters have glitchy lines on them
![dark](https://user-images.githubusercontent.com/2696404/76161572-99557480-616f-11ea-995f-1b5de6035e72.PNG)

**Comment by benderscruffy** [comment]
happens in software aswell but the characters are fine
![dark1](https://user-images.githubusercontent.com/2696404/76161666-72e40900-6170-11ea-840f-9d1a090cebb4.PNG)

**Comment by and468860** [comment]
This graph is the same as another 2d game has a lot of software only

**Comment by stenzek** [comment]
Should be fixed in latest build.

**Comment by Zet-sensei** [comment]
Fixed.
