### ISSUE TITLE
[Regression] [SLUS-00510] Vigilante 8 (USA) - Garbage in mid range assets textures

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#711]
**Version**
0.1-1419-g34a515cd

**Issue**
Garbage in mid range floor textures.

Take a look at these examples:

Colorado level (_Software renderer_)
![image](https://user-images.githubusercontent.com/12163923/89370722-d2aaf580-d6b7-11ea-9fa4-2f0a80c13b23.png)

Utah level (_Vulkan renderer_)
![image](https://user-images.githubusercontent.com/12163923/89370874-26b5da00-d6b8-11ea-87c4-ca75a4289f42.png)

Nevada (_Vulkan renderer_)
![image](https://user-images.githubusercontent.com/12163923/89371021-89a77100-d6b8-11ea-9dd7-9fa6d9dd0ae1.png)

Arizona (_Vulkan renderer_)
![image](https://user-images.githubusercontent.com/12163923/89371055-a0e65e80-d6b8-11ea-9190-afdfa6e6b14d.png)

**Comment by stenzek** [comment]
I wonder if this is the same underlying issue as some of the sprites in Castlevania... everything seems correct

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/0de34d7bf770f06726524ca1c406acb52795c210 (preview build).
