### ISSUE TITLE
Rayman 1 (Japan) - Level Complete music plays multiple times

### ISSUE THREAD

**Issue by RibShark** [stenzek/duckstation#714]
Another Japan exclusive bug (PAL/NTSC-U uses sequenced audio for the level complete theme, Japan uses a CD-DA track).
When completing most levels, the level complete music ends up looping and can be heard twice. This doesn't happen on the first level, but it does on most including the second. This bug also occurs in Mednafen, but not on console or other tested emulators (PCSXR/ePSXe).

**Comment by RinMaru** [comment]
Mednafen is the most accurate PS1 emu you sure it doesnt happen on real hardware?

**Comment by RibShark** [comment]
> 
> 
> Mednafen is the most accurate PS1 emu you sure it doesnt happen on real hardware?

I have tested on a PS2 (SCPH-77000) with an actual disc and it does not occur.

**Comment by MojoJojoDojo** [comment]
Yeah it happens on mednafen too I tried to play on it once.

**Comment by TzakShrike** [comment]
@RinMaru Did you mean XEBRA?

**Comment by Zet-sensei** [comment]
Fixed on 0.1-2108 after some verifications.

Should be closed.

**Comment by stenzek** [comment]
Could've been the recent SPU changes. Thanks again for confirming.

**Comment by Zet-sensei** [comment]
Regression when testing with the 0.1-4255 preview version.
The bug reappeared.

The 0.1-420 2 development version isn't impacted.

**Comment by stenzek** [comment]
Ugh, just when I thought I'd found all the regressions from the recent cd changes. Thanks for catching

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/67344070ea86944e8bb5f4bc11d04565bd533528, but please let me know if it's still happening as it seemed inconsistent for me in the first place.
