### ISSUE TITLE
[SLUS-90001] Rayman (USA) (Playable Game Preview) - Text flickering

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#715]
**Version**
0.1-1425-g05f0ce6d

**Issue**
Text flickering in this screen (end of the demo).
To make easy to track the issue, I'm including a savestate attached in this issue report.
Just go to finish sign to end the level and see the text flickering.
The issue also happens in software renderer.

![image](https://user-images.githubusercontent.com/12163923/89457830-645c4680-d73c-11ea-9c8a-4fff79eb929e.png)

**Comment by Shideravan** [comment]
Just to be clear, it's a different issue than https://github.com/stenzek/duckstation/issues/580 as the text in Level 3 isn't flickering anymore.

**Comment by stenzek** [comment]
Please don't post save states, they contain copyrighted data (BIOS and game code), as well as being tied to the path of the CD image on your computer.

**Comment by stenzek** [comment]
This was likely fixed with the draw timing changes, as the other Rayman flickering seemed to be.
