### ISSUE TITLE
[SLUS-00862] Next Tetris, The (USA) - Crashes after opening

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#717]
**Version**
0.1-1443-g7ab521f7

**Issue**
After the initial FMV, the game crashes.
Tested with both interpreter and recompiler modes, with software and hardware renderers.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/d4665e8b22ef8442c0bb03c1ee66fbbdfd313188
