### ISSUE TITLE
Graphical glitches in Vigilante 8

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#72]
Patches of Red and Green graphical garbage at the bottom of the screen. Using OpenGL. 

![Capture](https://user-images.githubusercontent.com/31968468/76162917-04b23d00-6196-11ea-96b4-f869ded5260a.PNG)

**Comment by kurayami6** [comment]
I'm not seeing the garbage pixels anymore but the screen flashes red and green when you die. 

![SLUS-00510_2020-06-04_12-10-45](https://user-images.githubusercontent.com/31968468/83707122-97129180-a65c-11ea-9017-1efe74ef1ce2.png)

**Comment by stenzek** [comment]
Can't seem to reproduce this.

**Comment by kurayami6** [comment]
Yeah it's fixed but I'm seeing garbage at the edge of the screen as the camera rotates. I'll have to check the game on real hardware. 

![SLUS-00510_2020-06-14_22-16-18](https://user-images.githubusercontent.com/31968468/84592998-e17de480-ae8c-11ea-9459-3a2580260c2a.png)

**Comment by stenzek** [comment]
Looks like a culling issue. Which is handled in software/by the game.

**Comment by kurayami6** [comment]
Yeah it's a real hardware issue.
