### ISSUE TITLE
[SLPS-01079] Side Pocket 3 (Japan) - Messy text in-game

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#720]
**Version**
0.1-1448-g472f1c1c

**Issue**
Text messages of "foul" in-game is messy. To trigger it, just don't hit any ball in a match.
Tested in software and hardware renderers, with interpreter and recompiler modes.
![image](https://user-images.githubusercontent.com/12163923/89577105-933eef00-d806-11ea-9f78-51bf519dd023.png)

**Comment by stenzek** [comment]
Can't seem to reproduce. Looks like a VRAM write didn't finish or something...

![image](https://user-images.githubusercontent.com/11288319/89730624-b4604380-da83-11ea-8b02-350fe686793c.png)

If this isn't happening, could you save a screenshot with "Show VRAM" checked?

**Comment by stenzek** [comment]
Closing due to lack of response.

**Comment by Shideravan** [comment]
Of course, here the screenshot with the issue in latest Duckstation version using "Show VRAM"
![image](https://user-images.githubusercontent.com/12163923/101080668-d0827600-3587-11eb-8ea3-bf06f8a504da.png)
