### ISSUE TITLE
[Request] [Libretro] Add Start+Select+L1+L2+R1+R2 digital <> analog toggle

### ISSUE THREAD

**Issue by ds22x** [stenzek/duckstation#721]
Would allow for (relatively) easy toggling between digital and analog controller modes when controller type is set to analog.

**Comment by Shideravan** [comment]
Oh please, don't do this, this comand is used by various squaresoft games as software reset

**Comment by ds22x** [comment]
It is?
Weird Beetle PSX uses it as a combo key then.
Still, a combo key of any kind would be appreciated, as the RetroArch core (currently) doesn't have any way to set an analog switch button (and I doubt it'll be as easy to set as in standalone DuckStation anyway).

**Comment by stenzek** [comment]
Yeah, I don't like the idea of this either. In the standalone version, I usually map the xbox/guide button to analog, and it works flawlessly. The fact that you can't map the guide button seems more like a retroarch/libretro issue.

That said, maybe we can put it behind an option or something.

**Comment by ds22x** [comment]
I think you can map it on Windows (provided you disable all the Xbox stuff), but I do know that the Nvidia Shield doesn't allow you to, as it has it mapped as a home button.
Right now though you can't remap controls for the DuckStation RetroArch core anyway, but when it becomes available, it should be possible to just have it in core controller mapping.

**Comment by stenzek** [comment]
libretro doesn't have enough buttons exposed to use the guide as well. See https://github.com/libretro/RetroArch/blob/master/libretro-common/include/libretro.h#L188

**Comment by ds22x** [comment]
Well that sucks.

**Comment by TzakShrike** [comment]
The vast majority of PSX games use L1+R1(+L2+R2)+Select+Start as a soft reset, as others noted, so if you're going to do something like this, use a different combination.

The home button not working correctly is a LibRetro issue. I alerted them to it YEARS ago, along with telling them how to fix it. They weren't interested in UX issues then, and in terms of UX had MUCH bigger fish to fry, anyway.

**Comment by stenzek** [comment]
We could potentially use the button combination as a toggle, since the chord would be processed before it hit the emulated controller. But only in standalone, libretro doesn't use my controller binding system, so doesn't really help here :/

**Comment by stenzek** [comment]
Merging with #1064 for anyone who wishes to pick it up, as I'm no longer adding any new features to the libretro core.
