### ISSUE TITLE
UTF8 Again

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#724]
As reported by a user on discord, when trying to open Duckstation for the first time he reports that the settings are not being saved after exiting and open the emulator again.

As we validate, he has installed Duckstation on the following path:
**C:\Users\Léo\Documents\DuckStation**

And as I imagined, we removed the accent from his username like this:
**C:\Users\Leo\Documents\DuckStation** and the emulator opened and saved the settings normally.

Perhaps, we return to that problem with UTF-8 again.

**Comment by hhromic** [comment]
We solved a similar problem in another project using `MultiByteToWideChar()` from `windows.h`: https://gitlab.com/solarus-games/solarus/-/merge_requests/1326/diffs

In case you haven't figured out a solution yet.

**Comment by stenzek** [comment]
Yeah, I'm aware. I've fixed up almost all of the places where DS was using `fopen()` and the other ANSI functions, this one's probably in an external library :p

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/ac4251078086752652f36f241f5da9908290d025. Haven't tested it though, so confirmation would be appreciated.

**Comment by andercard0** [comment]
Confirmed with the user, case solved Thank You!
