### ISSUE TITLE
[SLUS-01035] Vanark (USA) - Blinking options in in-game "Mars defence force" selection menu

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#725]
**Version**
0.1-1448-g472f1c1c

**Issue**
In this menu the items in the screen are blinking.
Tested in both software and hardware renderers, with Recompiler and Interpreter modes.
![image](https://user-images.githubusercontent.com/12163923/89702799-63cdd680-d91b-11ea-9f2e-f4646a9c8a1d.png)

**Comment by stenzek** [comment]
Can't seem to reproduce this. Do you have interlacing disabled? (I get flickering with it off)

**Comment by stenzek** [comment]
Closing as this appears to be invalid. Please comment if it is still flickering for you with interlacing enabled.
