### ISSUE TITLE
PBP Format Support

### ISSUE THREAD

**Issue by RyanBram** [stenzek/duckstation#727]
First of all, I want to say thank you very much for creating one of the best Playstation Emulator.

Second, I want to suggest about supporting PBP format in DuckStation. Currently, only PCSX Re-Armed and Mednafen core in libretro which support PBP.

The advantage of PBP format:
1. Can compress Playstation game by huge margin
2. Only need 1 file for 1 game (usually most Playstation game will have more than 1 file for each titles, e.g in bin + cue format)
3. Can combine multidisk into 1 PBP, which is really nice to have feature.

Thanks.

**Comment by MojoJojoDojo** [comment]
This is a duplicate of https://github.com/stenzek/duckstation/issues/17
BTW it was said to be problematic to implement.

**Comment by RyanBram** [comment]
Oops, sorry for the duplication.
So I think it can be closed now.

Thanks.
