### ISSUE TITLE
[Request] Savestate backup

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#728]
When "overwriting" a savestate, rather than just overwrite, save the former savestate as GameCode_number.backup rather than just delete the former one. This way not just the user can get a former savestate when a savestate corrupts, but also can return back to old savestate when a savestate is overwrote unintentionally.

**Comment by stenzek** [comment]
How would the backup be exposed in the UI? Not really sure how this is different from just having more slots.

**Comment by Shideravan** [comment]
The same way than PCSX2 already does for example. It's completely different from more slots, as the beckups are generated automatically and can be redeemed when the user wants to, indirectly. "Sh*t i lost my savestate when it corrupted/I overwrote it. Phew no prob, there's a automatic backup of it in savestates folder". Don't need to expose in UI, but you can turn the savestate backups optional in the general menu.

**Comment by Shideravan** [comment]
In time, I lost some savestates due corruption when using a new version of Duckstation, but I'm checking it better of how to replicate the issue before create a new issue report for that issue. But I leave here a small provocation for you to think about for now: It seems that old created savestates are incompatible with new duckstation version, but the auto-updater will ever ask to you to update the emulator and it be incompatible to old savestates. And there's no place to download old binaries. I'm downloading every new binary and putting in a folder, then when a new problem happens, I try to check with older binaries. But it seems that maybe Duckstation are corrupting old savestates when opening with a incompatible new version. As I can't post these savestates, I'm trying to figure out how to replicate this issue but I don't know how, as it seems it's randomically corrupting.

**Comment by stenzek** [comment]
I guess I could make it move rather than overwrite the old file.

For what it's worth, you can download old builds, it's just a bit more involved. On https://github.com/stenzek/duckstation/commits/master, if you find a commit with a checkmark next to it, then go to Create Rolling Release -> windows-build, you can download the windows-x64 artifact (which is used to create the release).

But personally I'd just recommend `git bisect` and compiling yourself. Much quicker.

**Comment by Shideravan** [comment]
That will be enough, thank you!
And thanks to show how to easily get old builds, that will be useful to keep track of regressions.

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation/commit/762ab3ff438bac84268caf4587e1a572adb45d18 will restore the old state when failing loading a bad state, https://github.com/stenzek/duckstation/commit/24306be7573741df10dae9c07fa918d10460288e adds an option to back up old saves before overwriting (but I still don't see a use case for this, so it's in advanced settings).
