### ISSUE TITLE
[Request] When loading a old version of savestates that aren't compatible anymore, display exactly the version of that savestate is compatible

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#730]
The same way that Dolphin already does.

**Comment by stenzek** [comment]
Not really interested in doing this to be honest. Save states aren't meant to be long-term or portable solutions, that's what memory cards are for.

Doing so would require me to create _another_ commit after the change which altered the version to record the commit which changed it (you can't know the commit hash before commiting).

**Comment by stenzek** [comment]
You can see which versions the save state version was bumped at by looking at the history for this file: https://github.com/stenzek/duckstation/commits/master/src/core/save_state_version.h. As you can see, it doesn't happen very often.

**Comment by Shideravan** [comment]
Good to know! Well, I'll check changes to this file to see when old savestates are incompatible then.
Given the fact that it's been _days_ since the last change, I can deduce then there IS something that are making some savestates be corrupted. I just don't know for now how to reproduce. But for this request in particular I'll close then.
