### ISSUE TITLE
Error to boot

### ISSUE THREAD

**Issue by Sh3v10** [stenzek/duckstation#736]
I don't know what happened. Emulator worked perfectly until yesterday. Suddenly it stopped working and showed this message.
![Error_capture_100820](https://user-images.githubusercontent.com/69474545/89805871-e44b2d80-dafb-11ea-96c1-4c58cf7c6ee1.JPG)

**Comment by stenzek** [comment]
Enable the log (settings -> advanced settings -> log level -> debug, and check "system console"). Post the output.

**Comment by Sh3v10** [comment]
![error_debug](https://user-images.githubusercontent.com/69474545/89812045-24fb7480-db05-11ea-85d6-df7cdf2ea425.JPG)

**Comment by stenzek** [comment]
Try deleting your shader cache - everything in `Documents\DuckStation\cache`. It _shouldn't_ be a problem, but it doesn't make sense for CreateInputLayout to fail like that...

**Comment by Sh3v10** [comment]
![capture_error2](https://user-images.githubusercontent.com/69474545/89814045-2bd7b680-db08-11ea-8d43-1e75993deb70.JPG)

**Comment by stenzek** [comment]
I've pushed a change to reduce the input layout size when uv limits aren't needed - see if that makes any difference. Otherwise, try using the Vulkan renderer instead.

The crash on shutdown should also be fixed - but that won't solve the boot problem. It really doesn't make sense for it to be returning a device lost error there.

**Comment by Sh3v10** [comment]
Ok, I already tried with the vulkan renderer but goes with some pop audio and lagging. Then i put back on D3D11 and runs but it doesnt go smooth as before the "boot error". I reopened the emulator and the "boot error" appeared again.

**Comment by Sh3v10** [comment]
I have noticed something strange whit the emulator:

1. I delete the duckstation folder in "documents" then I delete the Main folder.
2. I download the latest version of the emulator from github.
3. I run a first boot again and everything works fine. =)
4. I close the emulator.
5. I run a second time and the "boot error" message appears again. =(

My Nvidia drivers are up to date.

**Comment by stenzek** [comment]
Can you try to narrow down which file needs to be deleted to fix it? Because I can't reproduce this issue at all.

Some likely culprits:
- `settings.ini`
- `and everything in the cache directory`
