### ISSUE TITLE
Front mission 3 Flicker

### ISSUE THREAD

**Issue by saintbepis** [stenzek/duckstation#743]
Front mission 3's title screen and options will flicker if you hold down on the d-pad.
I'm using Vulkan on android 10 and it happens with and without PGXP.

**Comment by stenzek** [comment]
Is this still happening on the latest build? Can't seem to reproduce it on desktop, so it may be driver specific...

**Comment by saintbepis** [comment]
> Is this still happening on the latest build? Can't seem to reproduce it on desktop, so it may be driver specific...

Just tested it on the latest build from an hour ago, its been fixed

**Comment by stenzek** [comment]
Great, thanks for confirming. I guess GT2 wasn't the only game broken by the recent refactor :)
