### ISSUE TITLE
Gran Turismo 2 PAL intro shows black screen and doesn't start race anymore

### ISSUE THREAD

**Issue by CaptainAlphabet** [stenzek/duckstation#745]
Changes made between 2020-08-08 and 2020-08-10 now lead to issues with Gran Turismo 2 PAL. I experienced the following issues using the RetroArch core on a Windows 10 PC as well as on an Nvidia Shield Android TV box.

1) The intro movie only shows a black screen while the sound plays normally.

2) The loading sequence before a race where the list of participants appears car name by car name goes very slow. It takes about 3 seconds for each new name to show up on the list. When the list is complete nothing happens. The race doesn't start and the log doesn't show any error.

These issues are gone when I restore my DuckStation version backed up on 2020-08-07.

**Comment by stenzek** [comment]
Thank you for the bisect. Will try to look into it in the next couple of days.

**Comment by stenzek** [comment]
Silly typo in my recent refactoring... I'm surprised this didn't break more games.

Should be fixed with https://github.com/stenzek/duckstation/commit/025e01ca47225512b4133327682eaaa00d625850. Please comment if it is still happening on your end :)

**Comment by CaptainAlphabet** [comment]
Thank you very much for the quick fix. It works again. (-:
