### ISSUE TITLE
Added Chinese language :)

### ISSUE THREAD

**Issue by phoe-nix** [stenzek/duckstation#746]
https://github.com/phoe-nix/duckstation/blob/master/src/duckstation-qt/translations/duckstation-qt_Chinese-Simplified.ts

**Comment by TzakShrike** [comment]
Nice. This should be **_zh_**

**Comment by ggrtk** [comment]
@phoe-nix Thank you, I will handle getting this proofread/edited and PR'd in.

Traditional Chinese version is also being worked on at the moment.

**Comment by stenzek** [comment]
Many thanks! :)

**Comment by stenzek** [comment]
Added with https://github.com/stenzek/duckstation/commit/3a437637a659d527428c3ef4a107421f4f868e9b
