### ISSUE TITLE
BIOS Detection

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#747]
We'd discussed this every now and then. Thought I'd summarise into an issue for reference.

It'd be great if DS could scan the provided BIOS location for "known-good" BIOS dumps at hand of MD5 hashes or similar, and create a BIOS list (similar to the game list). It will scan _all_ files in the provided folder, perhaps after a warning that very large files will take long to have their hashes generated, and that thus the folder should be kept tidy containing _only_ BIOS dump files, which generally are always <1mb in size.

Later when we have game inis, DS should automatically choose from available BIOSes the one known to work best with the selected game. I presume there are some differences here sometimes, albeit likely quite rare.

**Comment by Richard-L** [comment]
Super nice improvement as of today!

Per region, in the drop-down, I'd suggest showing only the "correct" found ones. In this case for me only this one: 

![image](https://user-images.githubusercontent.com/4934209/93916521-f8449a80-fd09-11ea-9434-77233b0de019.png)

**Comment by RinMaru** [comment]
PSOne bios are marked as unknown

**Comment by RaydenX93** [comment]
What about another list with something like "Extra" for region free/special BIOSes, such as the one from PSP, plus a checkboxes to force the extra bios to be loaded before all the others?

**Comment by stenzek** [comment]
Has been implemented in latest builds.

@RaydenX93 if you want to use the PSP bios, simply select it for all regions.
