### ISSUE TITLE
control problems

### ISSUE THREAD

**Issue by dml360** [stenzek/duckstation#748]
In some games, when the dualshock model is selected, the control does not work, these problems happens in following games: 

Castlevania Simphony of the night (slus - 00067) USA region  

Crash Bandcoot (scus 94900) USA region - 

Fade to Black (slus 00236 ) USA region - 

Final Fantasy 7 (scus 94163) USA region - 

Rage Racer (slus 00403) USA region - 

And in the game "Megaman X5" (slus 01334) USA region, in Dualshock mode the analog does not work

PS: is solved by selecting the "Digital controller" model

An individual configuration system per game could be implemented there it would not be necessary to always change each game, since without the dualshock we would lose the rumble.

Thanks in advance for making this incredible emulator of the nostalgic PS1 available

My specs:

W10 Pro

CPU: i5 8400

GPU: GTX 1060 6gb

RAM: 16gb ddr4 2400

Duckstation build: 0.1 - 1485

Joystick: XBOX ONE (i dont use bluetooth, i used usb cable)

**Comment by ggrtk** [comment]
Do you have "Enable Analog Mode on Reset" turned on? If so, you'll need to manually toggle the DualShock back to digital mode (using your Analog button binding) for those games. Alternatively, turn that setting off.

**Comment by dml360** [comment]
yes I activated, 

If you switch via the guide button to digital mode, the control starts to work, but the analog does not work,

Would it be possible to allow 2 inputs for each command? there we could put the movements in both directional and analog, because playing crash 1 in digital is horrible

**Comment by ggrtk** [comment]
If you hold shift and click on the button binding box, it should open a dialog box that allows you to create multiple bindings for  that button. Axis-to-button bindings are supported, so you should be able to get the behavior you want this way.

**Comment by dml360** [comment]
This same problem of those games that I mentioned also happen in retroarch (bettle psx hw) but they don't happen in epsxw 2.0.5
my doubt is: will this problem also happen in real hardware?

**Comment by ggrtk** [comment]
Yes, the behavior of these games not working when the DualShock controller is set to analog mode is accurate to real hardware. "Enable Analog Mode on Reset" is an enhancement/hack that will cause issues with these games.
