### ISSUE TITLE
[Request] Exclusive Fullscreen

### ISSUE THREAD

**Issue by tony971** [stenzek/duckstation#75]
The compositor on my laptop isn't very efficient. I have a huge performance penalty for rendering the desktop and not resizing to the output resolution. Exclusive Fullscreen could really help out.

**Comment by stenzek** [comment]
In terms of compositor overhead, a smart compositor should detect the fullscreen window and scan out the application's buffer directly. I know DWM on Windows 10 does this.

But, exclusive fullscreen is useful for another reason - reducing stuttering in PAL games by setting the host to a 50hz refresh rate where supported, so I'll probably end up implementing it for that reason.

**Comment by stenzek** [comment]
Also note that this'll probably be a Windows-exclusive feature. As far as I'm aware there are no APIs on Linux to achieve exclusive fullscreen, it's entirely up to the driver, and the only way to change the refresh rate is with xrandr, nothing for Wayland. If I'm incorrect here, please let me know!

**Comment by tony971** [comment]
It's actually my Surface Book on Windows 10 that has the issue. The screen resolution is 3000x2000, so I'm sure that doesn't help. Launching through [12noon Display Changer](https://12noon.com/?page_id=80), (which resizes the desktop while the target application is running), has been able to counteract the performance hit for other emulators.

**Comment by stenzek** [comment]
Surprising that it becomes a performance hit. I don't have much issue displaying at 4K on a 2017 XPS 15, but it does tax the GPU. So if nothing else but to save battery it might be worthwhile :)

So, basically we want a exclusive fullscreen option *as well* as a resolution setting for it.

**Comment by tony971** [comment]
As far as I've experienced, exclusive fullscreen has set the desktop resolution to match the internal resolution of the program.

**Comment by stenzek** [comment]
This was implemented a while back for D3D.
