### ISSUE TITLE
[PBPX-95002] Interactive CD Sampler Disc Volume 4 (USA) - Hangs in Armored Core demo

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#751]
**Version**
0.1-1490-g76978986

**Issue**
If choose Armored Core demo, it freezes in black screen. the actual Armored Core game doesn't hag, just the demo in the Interactive CD Sampler 4. Tested in both interpreter and recompiler.

**Comment by stenzek** [comment]
Closing due to inability to reproduce.

**Comment by Shideravan** [comment]
It's solved in recents versions
