### ISSUE TITLE
 CDDA Fighting Force track won't repeat.

### ISSUE THREAD

**Issue by ewertonpires2** [stenzek/duckstation#754]
Hello everyone,
I've been playing Fighting Force for a few minutes and noticed that the level's digital music track doesn't repeat when it ends. I use the same .bin .cue image to play with Beetle PSX and the CDDA track repeats normally.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/6d75f42e12f88467c781846ee2ada8e8eb58eae8. Please comment if it is still occurring.
