### ISSUE TITLE
Emulator hangs when assigning shortcuts

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#767]
okay, I was trying to assign a hotkey for fast-forward but after assign it DS freezes

To reproduce issue: load a game normally start to play go to configuration >
shortcut configuration (in my case was changing Fast Foward) so > General tab > 
click on the option so the emu starts to count waiting for a input I did choose a button. 

I did close the options in order to return to play, the game just freeze. 
There was no another option but to restart the emulation.

**Comment by stenzek** [comment]
Can you reliably reproduce this? I can't seem to.

**Comment by andercard0** [comment]
Sorry for lack of information, I'll enable log to file and attach here as soon it happens again.

**Comment by stenzek** [comment]
Closing due to activity. If this is still happening please let me know.
