### ISSUE TITLE
SAVE STATE ERROR

### ISSUE THREAD

**Issue by Tiagosampaio02** [stenzek/duckstation#768]
I cannot use the SAVE STATE tool. The problem occurs in Windows users who use graphical accentuation in the computer's user name. Is there a solution for this or are you already working to solve this problem?

For example, I use my PC's username (Ant**ô**nio Tiago) and this letter that has a graphic accent is not read by the emulator  and this causes an error when using SAVE STATE.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/a895c0278949560a71de6797abb4221870e0722b

If it's still not saving for you, please comment and I'll look into it again.
