### ISSUE TITLE
Game stuck 3 seconds after save game.

### ISSUE THREAD

**Issue by phoe-nix** [stenzek/duckstation#769]
Tested on "Saiyuki - Journey West" SLPM-86339
1529 ga895c027 fixed.

**Comment by stenzek** [comment]
Was about to ask if this was on the latest version, since I pushed a fix for the hang when "Show OSD Messages" was disabled yesterday :)

To confirm, the freeze is no longer happening?

**Comment by phoe-nix** [comment]
Yes, no freeze anymore, i tested for 12 hours. thanks for fixing.
