### ISSUE TITLE
[Request] Screen orientation/rotation setting.

### ISSUE THREAD

**Issue by KrossX** [stenzek/duckstation#770]
Some games have an optional tate mode to make better use of the screen space. It would be nice to be able take advantage of such mode without having to actually rotate the monitor.

![DonPachi Tate mode](https://i.imgur.com/cVzpUuN.png)

**Comment by TzakShrike** [comment]
Until this feature is added...
If you're using an Intel chipset, you can already do this with Ctrl+Alt+Arrow Keys.
I'm fairly certain nVidia has a similar thing with maybe even the same shortcut, but I can't check that now.
No idea about AMD, but I mean surely it can do it, right?

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/7a3a72ec3d0c6fb78f2d4aa7945393c89a20d9f9.
