### ISSUE TITLE
[SCES-030.85] Sound glitches on the first stage Ms Pacman Maze Madness

### ISSUE THREAD

**Issue by diegoginard** [stenzek/duckstation#771]
The sound cuts out at the beginning of the first stage as if the cd was scratched.

**Comment by stenzek** [comment]
Can't seem to reproduce this. If it's still an issue and you have a verified dump, please let me know and I'll re-open.

**Comment by diegoginard** [comment]
hello long ago I solved it by disabling ntsc timing
