### ISSUE TITLE
[SCUS-94242] Interactive CD Sampler Disc 6 (USA) - Various graphical errors in menu.

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#772]
**Version**
0.1-1530-g6d75f42e

**Issue**
1) Freezes for a sec. when press L1 or R1 in menu (tested in other emulators and it don't see correct as the others changes instantly). 
2) If you're changing the item in the menu when pressing R1 or L1 button, the menu item can stop in a strange position. 
3) Sometimes, the items can be fully the same cor of the selection object.
![image](https://user-images.githubusercontent.com/12163923/90473893-61793280-e0fa-11ea-94fc-d4b9540b120b.png)

**Comment by stenzek** [comment]
Closing due to lack of response. If this issue is also happening on console, please comment and I will look into it.

**Comment by Shideravan** [comment]
Isn't freezing anymore in recent versions. But the graphical bug still happens. But I checked in other emulators as well and this graphical issue happens too. Maybe it's a bug in game menu itself. The best thing to do is to check in real hardware to see if this is applicable. But the main issue which was the freeze isn't happening in 0.1-2433-g9089c973 anymore.
