### ISSUE TITLE
Libretro port request: Add the possibility to set the first and last scanline for PAL games.

### ISSUE THREAD

**Issue by kilokanios** [stenzek/duckstation#773]
Just like beetle psx. It is needed for some scanlines shaders and PAL games to get scanlines even.

**Comment by Awakened0** [comment]
I'd like this for NTSC games too. The more robust cropping in Beetle is useful since so many games have different amounts of unused scanlines/overscan. And the current overscan cropping options in Duck stretch the image, while Beetle keeps the set aspect ratio.

**Comment by stenzek** [comment]
Scanline start/end offsets added in https://github.com/stenzek/duckstation/commit/362905e3df0c2b01d414528dd2bf92ec3539cb68, enhancement to preserve AR tracked in https://github.com/stenzek/duckstation/issues/1138.
