### ISSUE TITLE
Auto-Updater formatting and improved summary

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#775]
Two thoughts I wanted to collect re the auto-updater:

- Formatting (we'd already discussed this on Discord once). Imo most important is for people to see the change/improvement, as the auto-updater has a strong aspect of promotion for DS to it. It's a great summary of activities, all the work that was done, and at the same time offers it to people as a service, by clicking "download and install". Thus to see changes more legibly is desirable I believe.
- Full summary. The auto-updater should list the changes of all intermediate versions. Currently it only shows the changes of the latest version being updated to. Ideally it would include everything depending on the "current version" the user has.

Many many thanks!

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/71a38adbc7ac296e08101b9cebbecd2400afbf1f
