### ISSUE TITLE
Icon indicating overrides in game list

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#778]
Quick suggestion now that we have overrides: Think a new column in the main window with icons indicating "this game has overrides" would be nice. Something like an "edit" icon perhaps https://material.io/resources/icons/?search=edit&icon=edit&style=outline

What do you think?

**Comment by stenzek** [comment]
Would probably want to differentiate between user-set overrides and compatibility overrides.

**Comment by Richard-L** [comment]
Hmm yeah. That would mean three states then, right?

User settings, compatibility settings, and both.

I was actually thinking the menus for this are too nice to be hidden under a right click > properties. Not sure a new button in the main toolbar called "customise" is legitimate?

Perhaps this potentially new column might also offer access when hovering.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/ad9712afcaef5dbb0b4c1c8f5ad8f084e5a59698
