### ISSUE TITLE
[Request] Option to store memcard in the same folder as the game image

### ISSUE THREAD

**Issue by fenrir0054** [stenzek/duckstation#779]
It would be nice to have an option to have the memory card loaded and saved in the same directory as the loaded game when the per-game memcard setting is enabled. This is an option in emulators such as bsnes/Higan as well as mGBA, and while it makes a bit more "logical" sense for them as the saves for those systems were actually saved to the game cartridge I think it'd be useful here anyway.

The most practical advantage this would have is for people who emulate on multiple systems, e.g. on a desktop computer in front of their monitor and also on a different computer in front of their TV. If you keep your ISO files on an external drive then you can just swap between systems without having to worry about transferring your save data, as it's just saved on the external drive alongside the ISO (or playlist location if you're loading from a playlist).

**Comment by stenzek** [comment]
While not specifically what this was asking for, https://github.com/stenzek/duckstation/commit/5aa70cf797a2b779efe11686f920ca71f5726cdd adds the ability to set a memory card directory outside of the user directory.
