### ISSUE TITLE
Setting game directory doesn't work 

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#78]
Add directory 

![Capture](https://user-images.githubusercontent.com/31968468/76280203-2e2dae80-62e5-11ea-84f5-eb9963e71dda.PNG)

Choose the folder 

![Capture2](https://user-images.githubusercontent.com/31968468/76280225-3dacf780-62e5-11ea-972a-aaf6a2bc9789.PNG)

Picking yes or no makes doesn't make a difference. I've tried both 

![Capture3](https://user-images.githubusercontent.com/31968468/76280243-44d40580-62e5-11ea-956f-58e19c233de6.PNG)

Then fuck all 

![Capture4](https://user-images.githubusercontent.com/31968468/76280268-5a492f80-62e5-11ea-839c-0a9decdb2c83.PNG)

**Comment by stenzek** [comment]
I'm unable to reproduce this, even with a clean settings/config. What format are your disc images in? And does the console report any errors regarding CD Images/Content Scanning?

**Comment by kurayami6** [comment]
Fixed it. Turns out it was my mistake. I had the games in folders within folders within folders. I guess 3 layers of folders was too many for the emulator to handle.

**Comment by stenzek** [comment]
Folders within folders shouldn't be an issue, if you select "yes" to the recursive check. Will check that on my end.

**Comment by stenzek** [comment]
A four-folder-deep hierarchy seems to work okay for me. Maybe it's a path length issue?

**Comment by kurayami6** [comment]
Alright I've found the problem. First time I tried to set the directory I chose "no" for recursive scanning. When nothing came up in the list I then set the path again and picked yes and still nothing happened. Seems if you pick no, yes won't work if you try again.

**Comment by stenzek** [comment]
Did you remove the path from the game list first?

**Comment by kurayami6** [comment]
No, I picked the same game folder and just tried choosing "yes" for recursive scanning since it prompted me to choose "yes or no"

**Comment by stenzek** [comment]
Alright. If you had removed it from the search directory list in `Game List Settings`, it would have worked as intended.

But, this would be confusing, so I've pushed a fix which handles it properly, i.e. changes the recursive flag if you re-add the same directory twice to whatever the most recent choice was.

**Comment by kurayami6** [comment]
Thank you very much.

**Comment by stenzek** [comment]
All good, better than these sorts of issues ending up in a release and confused users! :)
