### ISSUE TITLE
Android - can't add game directory

### ISSUE THREAD

**Issue by fefo-dev** [stenzek/duckstation#782]
Had this issue since the very first Android release, but set it aside due to its newness. It's still present in the latest build available at the time however.

When trying to add a new game directory I get a "No apps can perform this action" prompt. I'm on Android 9, Lineage OS, and I suspect the way used to ask for a file browser or whatever it needs is either too specific or reliant on some key app. I can provide more info if this is clarified.

On a sidenote, the duckstation folder wasn't created in /sdcard at first, but doing it manually created its subfolders on the next run. Nothing happened to the main problem however.

Thanks.

**Comment by stenzek** [comment]
The creating of the user directory should be fixed as of the latest version - the app will request external storage permissions before starting.

Not sure what's going on with the add game directory failing, it uses the file selector built into Android. For what it's worth, I tried LineageOS based on Android 10 on my ODROID-N2 and it seems to work fine...

**Comment by fefo-dev** [comment]
Seems to be the reason, my Files app (com.android.documentsui) was disabled. For reference: https://images2.imgbox.com/a3/bf/GRDs1peE_o.png. Never had any issue with file/folder picking with FX Explorer so I had no clue.

Game (Parasite Eve) booted normally but was slightly buggy. Couldn't test others because mine are mostly .bins, so you might need to pick a poison between manual game picking like on PC or dealing with users that don't know why stuff doesn't work. I'll check back latter and report a new bug if necessary.

I'll leave it open in case there's anything you want to add.

Much appreciated.

**Comment by stenzek** [comment]
> Game (Parasite Eve) booted normally but was slightly buggy.

Not sure how I'm supposed to fix it if you don't say *how* it is buggy.

> Couldn't test others because mine are mostly .bins, so you might need to pick a poison between manual game picking like on PC or dealing with users that don't know why stuff doesn't work.

Having only .bins will not work for multi-track games, which is why I don't support it in the game list. Most people have one bin file per track, which means indexing bin files would result in N entries in the game list for N tracks. You're the first person who's not using cuesheets that I've encountered.

**Comment by fefo-dev** [comment]
> Not sure how I'm supposed to fix it if you don't say _how_ it is buggy.
Just a loose quip, I'll file a proper bug report after I debug properly.

> You're the first person who's not using cuesheets that I've encountered.
Nice. I need to look into a consolidated format in the future, folders annoy me.

**Comment by stenzek** [comment]
For what it's worth, CHD is single-file and compressed. Most people are switching to that.
