### ISSUE TITLE
Changing internal resolution causing RetroArch to crash

### ISSUE THREAD

**Issue by nickp85** [stenzek/duckstation#786]
Device: nvidia shield 2017
App: RetroArch aarch64 1.9.0
Core: Duckstation 0.1-1580g136a9d60

I have been playing FFVII on a 6x internal resolution but wanted to test something on a lower internal resolution.  No matter what value I try to change it to, RetroArch crashes.

This was not always the case as I've changed it in the past.  Not sure if the crash is in RetroArch or in the Core.

Thanks

**Comment by nickp85** [comment]
Just downloaded latest and still crashing when changing internal resolution

**Comment by nickp85** [comment]
Still happening in latest dev build @stenzek

**Comment by stenzek** [comment]
Not sure if you're still watching this issue, but I've finally managed to reproduce this locally. There's an underlying bug in retroarch which is causing the core to not be notified when things are reinitialized. https://github.com/stenzek/duckstation/commit/627a3109b32dde253ea103c1484d673b5b1f4391 has a workaround, which seems to work for me at least.

**Comment by stenzek** [comment]
Context caching was likely the issue here, and has been disabled in https://github.com/stenzek/duckstation/commit/b2de5945c42564c39416c8dd02f0a2a820f94f37
