### ISSUE TITLE
[General?] Wrong sound equalization (Example with [SCUS-94569] Disney's Aladdin in Nasira's Revenge (USA))

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#787]
**Version**
0.1-1580-g136a9d60

**Issue**
I ever "feel" that some sounds in some games aren't the same as the output from Playstation 1, but didn't reported before because it's seems a little "subjective", but I found a good example, which I also tested in real hardware.
In the game [SCUS-94569] Disney&apos;s Aladdin in Nasira&apos;s Revenge (USA) the sound from music is so louder than the voice and soundFX sounds, that the movement to "stealth stealling" (circle button without sword equiped - triangle disequip sword) is barely audible. In the real hardware the background music is lower, then the "tara-du-dadara" humming is audible. Please, take a look on this.

**Comment by Kurayami7** [comment]
I just checked on my real PS1. It sounds identical to Duckstation. The music is much louder than Ali's humming but you can fix it by lowering the music volume in the game's options menu. I don't know what real hardware you tried it on but I think this can be closed.

**Comment by stenzek** [comment]
Would need captures from both to investigate.
