### ISSUE TITLE
Audio bug in MGS1 (disc 1) (Rev 1)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#79]
When you get caught by an enemy in the first area there's an enemy alerted noise followed by three short alarm buzzing sounds. Often (but not every time) the third alarm noise will play forever.

**Comment by Blackbird88** [comment]
Well, according to #15 audio emulation isn't finished yet so I'd assume all sound bugs are result of that

**Comment by kurayami6** [comment]
Still an issue as of the latest version.

[SLUS-00594_2020-05-09_15-50-33.zip](https://github.com/stenzek/duckstation/files/4602773/SLUS-00594_2020-05-09_15-50-33.zip)

**Comment by kurayami6** [comment]
Seems to have been fixed at some point.
