### ISSUE TITLE
[Bug] Screen dimensions calculated incorrectly with integer scaling

### ISSUE THREAD

**Issue by TzakShrike** [stenzek/duckstation#794]
Running at **resolution scale 2x**, with **integer scale ON** (naturally), and **crop none**, and so the output should be 1024x960, correct? Turned on show resolution to be sure, and it agrees.
Running with a screen resolution of EXACTLY 1024x960, in fullscreen, DuckStation decides that 1024x960 doesn't multiply/fit cleanly into 1024x960 (integer upscale 2x), and outputs instead at only 1x.

**Comment by TzakShrike** [comment]
I miscalculated for the above because I also had 4:3 set, however this still occurs at certain resolutions. 1280x960 has this issue in the above example.

**Comment by ggrtk** [comment]
Fixed in e0f3a4f17bdf48ee939a85f8432ec77e46df00cf
