### ISSUE TITLE
After entering and exiting a shop there are distortions on the 2D background in FFVII

### ISSUE THREAD

**Issue by nickp85** [stenzek/duckstation#796]
Device: Shield 2017
Emulator: RetroArch aarch64 nightly with latest release of Duckstation
Game: FFVII
Driver: Vulkan

Many times when you enter a shop and then exit, the 2D background develops graphical glitches. I have not seen this with other emulators in the past.

![80AEE044-DEF7-44AD-B467-D929A2BE9D85](https://user-images.githubusercontent.com/59027847/90984509-664b4580-e543-11ea-84a8-d690651ef27c.jpeg)

**Comment by nickp85** [comment]
Appears to also happen when you talk to someone and it triggers a party change dialogue

**Comment by stenzek** [comment]
Haven't seen this on desktop. I wonder if it's related to https://github.com/stenzek/duckstation/issues/678

**Comment by mikerogerz** [comment]
The graphical glitches seem to be extremely similar to in the menu at the start of the game (Where you select New Game or Continue). That's the first thing I noticed in terms of issues before the black screen after the intro video.

**Comment by stenzek** [comment]
Yeah, I suspect it's the VRAM round trip. For some reason it's only happening on mobile drivers...

**Comment by nickp85** [comment]
Appears to be fixed by the latest dev build!
