### ISSUE TITLE
2D features in FFVII not rendering properly

### ISSUE THREAD

**Issue by nickp85** [stenzek/duckstation#797]
Device: Shield 2017
Emulator: RetroArch aarch64 nightly with latest release of Duckstation
Game: FFVII
Driver: Vulkan

When the 2D backgrounds have “smoke” or glow like effects they don’t render properly. This is observable at many points of FFVII as I’ve been playing. Have not observed this with other emulators.

![C1881612-D1E8-4BFB-B538-A5BC7D498512](https://user-images.githubusercontent.com/59027847/90984586-dce84300-e543-11ea-8ccf-a61b168fea7f.jpeg)

**Comment by nickp85** [comment]
Definitely the worst one so far
![CE110B2C-EB7B-41C4-AA60-98700D255A39](https://user-images.githubusercontent.com/59027847/90986477-1e331f80-e551-11ea-8a82-6fe4444ebb70.jpeg)

**Comment by stenzek** [comment]
I feel like this might be unique to Vulkan/Android, or maybe libretro. Does it happen with the OpenGL renderer?

**Comment by nickp85** [comment]
I switched to OpenGL and went back to a few problem spots like the example I gave. OpenGL seems to handle it better. I did get some slowdown in battles though with OpenGL. I’ve read that Vulkan is usually best for devices like the Shield

**Comment by stenzek** [comment]
I'm not suggesting to use OpenGL over Vulkan (it's unofficially deprecated in DS anyway, only there for older devices). Just wanted to see if it was specific to the renderer, or the platform.

I don't have a Shield, but I'll try to reproduce on a Mali GPU.

**Comment by nickp85** [comment]
Thank you! Game is very much playable despite some of the graphical glitches. I’ve been wanting to play FFVII OG for a while now and not that remastered version where they made a bunch of fixes. Wanted all the text errors And bad translations I remember from 1997 :)

**Comment by nickp85** [comment]
Just tested this on the dev build that published a moment ago, looking much better!!!
