### ISSUE TITLE
Graphical garbage in Pizza Hut Disc 2 (USA) (EDC)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#80]
After the opening video telling you to eat pizzas, the screen will briefly turn to this before going to the demos. It only happens when using the D3D11 renderer. Resolution is at x1. 

![Capture](https://user-images.githubusercontent.com/31968468/76376770-452fd780-639d-11ea-8c2c-8d649748d4e3.PNG)

When using OpenGL it correctly displays this screen.

![Capture2](https://user-images.githubusercontent.com/31968468/76376983-cedfa500-639d-11ea-8cd4-98ae5205bdf8.PNG)

**Comment by kurayami6** [comment]
Pizza Hut Disc 1 (USA) has the same problem. 

![Capture](https://user-images.githubusercontent.com/31968468/76502262-d5eade00-6497-11ea-8ab7-0a4f354b2c98.PNG)

**Comment by stenzek** [comment]
I'm collapsing this to https://github.com/stenzek/duckstation/issues/153 as it seems to be the same issue. If it is a different issue and persists with the OpenGL/Software renderers, please re-open.
