### ISSUE TITLE
SLES-00098 Mass Destruction (E) Audio problems on the game stage and intro video skips 

### ISSUE THREAD

**Issue by diegoginard** [stenzek/duckstation#801]
<entry code="SLES-00098" title="Mass Destruction (E)" region="PAL" compatibility="4">
    <compatibility>Graphical/Audio Issues</compatibility>
    <version-tested>0.1-1600-g032127a7</version-tested>
    <comments>Audio problems on the game stage and intro video skips</comments>
</entry>

**Comment by stenzek** [comment]
Might be the same issue as #798 (which is because the CPU executes too many instructions per frame. Need to implement icache...)

**Comment by Zet-sensei** [comment]
After new some tests on 0.1-1641, the issue should be closed.

**Comment by stenzek** [comment]
Thanks @Zet-sensei
