### ISSUE TITLE
 Is there any way to increase the 30fps to 60fps

### ISSUE THREAD

**Issue by momoids** [stenzek/duckstation#803]
Is there any way to increase the 30fps to 60fps. I am learning english but i not fluent.

**Comment by stenzek** [comment]
Not without overclocking and patching the game (has to be done for each, there is no general solution).

**Comment by momoids** [comment]
Thanks!

Em ter., 25 de ago. de 2020 às 22:35, Connor McLaughlin <
notifications@github.com> escreveu:
