### ISSUE TITLE
Large DualShock motor not variable strength

### ISSUE THREAD

**Issue by jpchow26** [stenzek/duckstation#804]
Making this a ticket for proper tracking. Currently DS is setting the large motor to 100% or 0% strength. This is actually variable. I've modded DS source locally and spewed the large motor data to log when doing the B1 test in Gran Turismo 2.
[duckstation.log](https://github.com/stenzek/duckstation/files/5131395/duckstation.log)

Attached log output showing range. 

Changed source below:

```
 case State::GetStateButtonsMSB:
    {
      if (m_rumble_unlocked)
      {
        if (data_in != 0)
            Log_ErrorPrintf("*** LARGE MOTOR VALUE *** = 0x%02X", data_in);
        SetMotorState(0, data_in);
      }
[duckstation.log](https://github.com/stenzek/duckstation/files/5131392/duckstation.log)

```

**Comment by ToniBC** [comment]
In Gran Turismo 2, the vibration does not work well, it is constantly vibrating. It may be related to the vibration values that are discussed here.

**Comment by stenzek** [comment]
Latest release (once it builds) switches back to variable vibration strength, and adds a bias (so as to not break FF8).

**Comment by jpchow26** [comment]
works with my local build!
