### ISSUE TITLE
[Request] run-ahead mode

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#807]
Is it possible to create a run-ahead mode in Duckstation to reduce even more the input lag in the games, the same way that bsnes do for snes games?

**Comment by stenzek** [comment]
Not likely with the hardware renderers. The cost for reading back from the host GPU is way too high. Maybe with the software renderer.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/e01d66d18e85449a63fb97bfdfa8f7d3d3330a92
