### ISSUE TITLE
Multipe issues in  Nekketsu Oyako (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#81]
First off the game doesn't have a number in the list. I'm not sure if it's supposed to be like that.

![Capture4](https://user-images.githubusercontent.com/31968468/76382203-05242100-63ac-11ea-8c16-28290b563063.PNG)

Second the BIOS screen and the opening logo briefly overlap

![Capture3](https://user-images.githubusercontent.com/31968468/76382226-1705c400-63ac-11ea-8134-80964404519e.PNG)

Thirdly in level 2 when you knock down an octopus on top of the whale its sprite seems to break a little. I haven't played on real hardware so I'm not sure if that's normal.

![Capture](https://user-images.githubusercontent.com/31968468/76382274-47e5f900-63ac-11ea-9060-ad5035674ad8.PNG)

And finally the second boss's sprite is completely fucked. 

![Capture2](https://user-images.githubusercontent.com/31968468/76382309-621fd700-63ac-11ea-8437-19d6d3904083.PNG)

There could be more issues further in but that's as far as I played.

**Comment by stenzek** [comment]
Looks like https://github.com/stenzek/duckstation/issues/153 - wasn't able to reproduce.
