### ISSUE TITLE
Add "Force NTSC Timings (60hz)" to Compatibility Settings

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#810]
I think this one should be added to the per-game settings.

Do we know the ratio of PAL games that should or should _not_ have this checked? You'd think the ones needing it are the exception, so ideally per default, this option would be unchecked in GPU settings (as I believe is the case).

Thank you!

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/b2057ac6cc0035a05874c79553f5499af22afc04
