### ISSUE TITLE
Add "Update will break save states" warning to Updater

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#812]
Just a thought if perhaps you could add a flag you can add manually, so that a warning is shown inside the updater popup when a version update breaks savestates. Gives people the chance to "skip" first, save to their memory cards, and then re-trigger the updater.

Many thanks

**Comment by TzakShrike** [comment]
Note from previous conversation. My suggested dodgy way to do this was to have a set string appended to commit messages (eg. "(Warning: Breaks savestates)", or "Savestate version changed") and to search for that substring when the updater presents the changelog to the user.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/e88d36513e0f66f83d160002cb3afe0d64f07751

Note that you'll need to be on at least this build before updating to a save-state-changing-build, as the warning is prepended in the program itself.
