### ISSUE TITLE
Allow re-triggering of Updater if chosen "skip" previously

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#814]
Currently when choosing "Skip this update" to save to memcards due to broken savestates, you can then not re-trigger the auto-updater by selecting "Check for updates". It will falsely say no update is available, as I assume a one time skip is permanent. This shouldn't be.

**Comment by Konkonfaux** [comment]
Isn't there a "Remind me later" option to press instead of skipping?

**Comment by Richard-L** [comment]
There is yes, but skip and remind me later should be merged. Or at least there should be a chance to "undo" a skip.

**Comment by CookiePLMonster** [comment]
IMO Skip should only concern automatic checks, and a manual Check for Updates should **always** report a new version.

**Comment by Richard-L** [comment]
I agree actually

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/4d9e58ac42701b03dc9238d4a180becd8a649ab4
