### ISSUE TITLE
Issues with accentuation and Pt-Br .Ts file edit

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#816]
Howdy Stenz,

So. A user (Ewerton) reported on Discord the following issues since latter update of DS. 

![StopEmulationMessage1](https://user-images.githubusercontent.com/43047877/91778673-9f318d00-ebc9-11ea-80f3-bb12993bd463.png)

Screenshot refers to:  Are you sure you want to stop the emulation ? 

I can easily solve the accentuation issue by only removing those ' ç, ã, õ ' etc
Which will do soon to workaround the problem even temporarily.

~Second issue is:
Trying to edit the .TS file avaiable on GH is not editable anymore. as you may view below:~

~Right picture shows .TS file completly blocked. for comparative purposes only here is the files so you can check for yourself what I'm trying to say~ solved it by redownloading repo again; Did not know that only 'cause i was overwriting old files would cause all this mess.

That said, please check when you can.

Thank You!

**Comment by stenzek** [comment]
Should hopefully be fixed by https://github.com/stenzek/duckstation/commit/8d5a6acfc707499b9a59572b8dd78a5131e12d0c
