### ISSUE TITLE
Crash on game list rescan

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#817]
Not sure this is interesting: 
![image](https://user-images.githubusercontent.com/4934209/91882322-11b27380-ec83-11ea-9d2a-528cab75b99e.png)

On v0.1-1641-gb2057ac6, some games would start a different one in the list when using right-click > resume, and I thought perhaps something is wrong with the list itself. Upon wanting to rescan, this error came up.

**Comment by stenzek** [comment]
Fixed with https://github.com/stenzek/duckstation/commit/ad61815cad90e6f9b946307049db9a454329e71f
