### ISSUE TITLE
Rebase odroidgo branch

### ISSUE THREAD

**Issue by valadaa48** [stenzek/duckstation#819]
Hi @stenzek, as we discussed in discord, let me know when you rebased the odroidgo advance branch so we can give standalone a test to see how it performs compared to libretro. Thanks

**Comment by stenzek** [comment]
See https://github.com/stenzek/duckstation/tree/go2

Performance still isn't great - it's mainly CPU emulation which is to be expected, and I have futher planned optimizations there.

What's concerning me the most is that the software renderer is almost as fast as the hardware renderer. That means that the GPU driver overhead is way too high, or it's GPU-bound. Using 16-bit textures doesn't speed it up, so I don't think it's a memory bandwidth issue. The Mali driver on the Go-Advance seems heavier than on my N2 for some reason, threading the GPU out might be the only way to solve this.

**Comment by valadaa48** [comment]
Thanks for rebasing. That's an interesting observation regarding GPU overhead. What GPU driver is used on the N2? Is it the g31 bifrost blob, same as the OGA?

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation/tree/go2fast2
