### ISSUE TITLE
Graphical glitches and hang in Disney's The Emperor's New Groove (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#82]
There's a black seam on the right hand side of the screen. There are black dots all over everything. Both Kuzco and Pacha are covered in holes. After a few seconds on this screen the game also hangs and begins repeating the same music clip over and over. Using the D3D11 renderer at native resolution. 

![Capture](https://user-images.githubusercontent.com/31968468/76396193-d5d1dc00-63cc-11ea-92e7-74e028b27c4b.PNG)

The log

![Capture](https://user-images.githubusercontent.com/31968468/76396395-34975580-63cd-11ea-8b12-e496874fb977.PNG)

**Comment by kurayami6** [comment]
Game no longer hangs as of the latest revision but the graphical glitches are still present.

**Comment by stenzek** [comment]
This seems to be a GPU vendor issue, possibly with texture sampling precision. I can't reproduce it on an Intel GPU, but it shows up on NVIDIA.

**Comment by stenzek** [comment]
Please re-test with your GPU on latest master. I've added a hackfix which seems to fix it on NVIDIA for me. Yet again, NV are the odd ones out with Intel and AMD's behavior matching...

**Comment by kurayami6** [comment]
Fixed. Just don't forget to remove the hack if NVIDIA ever get off their arse and fix it properly.

**Comment by stenzek** [comment]
I don't think NVIDIA is technically in the wrong here, it's probably more likely there's a threshold for how precise texture interpolation is, and they just have different behavior, but still within spec.
