### ISSUE TITLE
Libcrypt File sbi.

### ISSUE THREAD

**Issue by mattitotti** [stenzek/duckstation#823]
Hello Yesterday on retroarch i found this new emulator for the PS1 ❤️ i tried medievil 2 parassite Eve 2 and the don t have any issues....i played Spyro 3 year of the dragon PAL version (i'm italiano) and the game stuck on shela peak....what can i do for play this game i have the file sbi renemed as the iso please can you help me?

**Comment by RaydenX93** [comment]
1. Are you using good dumps from redump collection (bin/cue files)?
2. If yes, did you get the sbi files from redump?
3. If yes, did you put all 3 files in the same folder?

**Comment by mattitotti** [comment]
I have a perfect Copy of this game took by domustation with epsxe i have no problem  i have sbi file sub file and CCD file IMG file and cue file....no i didn't get sbi file from redump collection....

**Comment by RaydenX93** [comment]
come on discord and message me there, i'll help you. delete this issue

**Comment by mattitotti** [comment]
It s useless i download Spyro 3 in redump and even the sbi file from there It s the same

**Comment by stenzek** [comment]
IIRC Spyro 2 PAL has some crashing issues so this may be a bug.

**Comment by stenzek** [comment]
I deleted your comment because you mentioned piracy, which is against the rules.

**Comment by mattitotti** [comment]
This Is the libcrypt protection but i have the sbi file renamed in the same title of the bin....

**Comment by mattitotti** [comment]
I tried even the bar patch that removed the libcrypt protection but on shela peak the games block.....

**Comment by stenzek** [comment]
If it's similar to an issue I've seen in other PAL games, try forcing NTSC timings.

Otherwise it may have the same cause as Spyro 2, which I have not looked into yet.

**Comment by mattitotti** [comment]
Spyro 2 has the same libcrypt protection.....

**Comment by stenzek** [comment]
I know. But I'm pretty sure the S2 issue isn't libcrypt related, because other libcrypt games work fine.

**Comment by mattitotti** [comment]
Do you Say that the game doesn't block for the libcrypt protection, am i correct that i renamed the sbi file in the same name of bin file ?
Es: spyro3.cue
spyro3.bin
Spyro3.sbi

**Comment by kilokanios** [comment]
Spyro 3 has both Libcrypt protection and anti-crack protection. Make sure the copy is bit-perfect (check the checksum with Redump) and that the .sbi file is correct (you can download it from the same Redump page).

**Comment by mattitotti** [comment]
I have a perfect Copy of the game....runs perfectly on epsxe , i tried even the Copy of redump with bad patch and sbi file but on duckstation don t work

Scarica Outlook per Android<https://aka.ms/ghei36>
________________________________

**Comment by stenzek** [comment]
Spyro 2/3 PAL issues should be fixed in the latest build, a gameini is used to force the interpreter.

Unfortunately it's not possible to run them with even the cached interpreter - the libcrypt protection modifies the code just before it's about to execute, well after it's been cached.
