### ISSUE TITLE
Tweaks/Hacks table in Advanced Settings has user editable names

### ISSUE THREAD

**Issue by Blackbird88** [stenzek/duckstation#829]
I don't think this is intended behavior

![image](https://user-images.githubusercontent.com/4414625/92325803-a7684d00-f04d-11ea-8f37-d08c523c2346.png)

**Comment by stenzek** [comment]
Indeed it should not be.

**Comment by stenzek** [comment]
Fixed with https://github.com/stenzek/duckstation/commit/1e6d50e4dc275be306f2cd8d787060558fcca49b
