### ISSUE TITLE
Bugs has no eyes in Bugs Bunny- Lost In Time

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#83]
Using D3D11 renderer. I apologize if it's just the game being shitty and it's supposed to look like this. 

At Native resolution.

![Capture2](https://user-images.githubusercontent.com/31968468/76413704-ffe5c700-63e9-11ea-8b17-68cb9806213e.PNG)

At x4 resolution

![Capture](https://user-images.githubusercontent.com/31968468/76413735-0d9b4c80-63ea-11ea-8ba1-ca57a61628e0.PNG)

**Comment by stenzek** [comment]
I think this is also https://github.com/stenzek/duckstation/issues/153 - couldn't reproduce on my end
