### ISSUE TITLE
libretro: Converting memory cards

### ISSUE THREAD

**Issue by IngwiePhoenix** [stenzek/duckstation#830]
I have quite some progress in a game and only now found out that DuckStation has an internal resolution changer - which is just plain amazing. That, FXAA and other settings, make this easily the best PSX emulator I have seen thus far!

However... Now, my games are on a different memory card format and I need to convert  (PCSX ReARMed -> DuckStation).

It'd be nice to be able to convert memory card formats for switching users.

**Comment by IngwiePhoenix** [comment]
Here are the two files for reference.

[memcards.zip](https://github.com/stenzek/duckstation/files/5181070/memcards.zip)
(contains `.srm` - used by the previous core - and `.mcd` which is used by DuckStation)

**Comment by IngwiePhoenix** [comment]
Got it. I just realized that... well, allow me to explain.

This tool: http://moberg-dybdal.dk/psxge/
...can convert between saves.

In the example given in the .zip file, you'll find one `.srm` file - which is a **generic** extension used by libretro - and a `.mcd` file.

To transfer your save:
1. Open PSXGE
2. "Open MC Image"
3. Click the save you want to extract
4. "Save Single Game save"
5. "Open MC Image"
6. In the dialog, navigate to the folder holding the `.srm` image, and enter it's name into the name box. PSXGE does not list `.srm` files, but absolutely accepts them. Why? I don't know, really. I assume PCSX ReARMed uses the Bleem image format, just like DuckStation seems to use.
7. "Open Single Game save"
8. "Save MC image"

Done. It's... a bit cumbersome, but it's at least something :) Might be useful to let people know - in a wiki, FAQ or alike - that this is a possibility they can go for.

**Comment by stenzek** [comment]
I think you're over-complicating this. "mcd" is just an extension, like "srm" and "mcr". If the file is 128KB in size, it is a PlayStation memory card image, and you can simply rename it. No need to use third-party applications.

That said, automatically using the existing srm files is on my TODO list.

**Comment by stenzek** [comment]
Closing as this is not an issue.

**Comment by oxr463** [comment]
> I think you're over-complicating this. "mcd" is just an extension, like "srm" and "mcr". If the file is 128KB in size, it is a PlayStation memory card image, and you can simply rename it. No need to use third-party applications.
> 
> That said, automatically using the existing srm files is on my TODO list.

Thanks for this!
