### ISSUE TITLE
Moto Racer (Europe) (En,Fr,De,Es,It,Sv) [SLES-00469] // The pause menu opens up randomly in-game.

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#831]
After a report from a user on Discord and some tests on my side, I can confirm the bug is present (on 0.1-1666).

When you are playing a single race, the game pauses up randomly.

The dump hashes values are correct against the Redump database (and multiple times verified).
The problem occurs on all CPU Execution Modes too (Interpreter, Cached, Recompiler).

![MotoRacer](https://user-images.githubusercontent.com/52127625/92382221-8adf1a00-f10c-11ea-93b6-bc87b162d1b5.jpg)

**Comment by Richard-L** [comment]
Have this issue too.

**Comment by RaydenX93** [comment]
yep, same problem here

**Comment by Zet-sensei** [comment]
Inspired by the fix for Destructin Derby 2 done earlier today, I've tried to change some values on the DMA slices.
After testing on 4 tracks, no more issue with a pause menu triggering randomly.

Please add these lines to gamesettings.ini.

```
# SLES-00469 (Moto Racer (Europe) (En,Fr,De,Es,It,Sv))
[SLES-00469]
DMAMaxSliceTicks = 225
DMAHaltTicks = 100
```

The issue could be closed after adding those lines in a next update.

**Comment by Richard-L** [comment]
This now also happens with "Frogger (USA)"

**Comment by Richard-L** [comment]
![ezgif-6-01ac9053e24e](https://user-images.githubusercontent.com/4934209/100896233-b3ce3b80-34be-11eb-9da5-bff3ce690ad2.gif)

Also noticing it with SLUS-00232 Pandemonium! (USA). Noticeably only occurred in that very stage of the first level, suddenly started happening, almost as if game progress played a factor. Similar behaviour in Frogger (above).

Also believe this only started happening after using savestates once.

**Comment by stenzek** [comment]
Gameini override added in https://github.com/stenzek/duckstation/commit/d7de578d4a8b00ab8c7cb0d4bc4c4c9b409a23e7

**Comment by Shideravan** [comment]
The issue happens in Moto Racer (USA) in 0.1-2499-g770dd5a6. I'm thinking if these bugs are somehow related with Issue #1167 .

**Comment by Shideravan** [comment]
No more issues with Frogger (USA), Destruction Derby 2 (USA) (although I cannot can activate the "analog" button in this game anymore even using Dual Shock Control option). In Pandemonium! the pause screens seems to still happening, just once after entering in this exact scene. Very strange...

**Comment by Zet-sensei** [comment]
> 
> 
> The issue happens in Moto Racer (USA) in 0.1-2499-g770dd5a6 too. I'm thinking if these bugs are somehow related with Issue #1167 .

We need to add the same gameini overrides for the US & JPN versions of the game in a next update.

**Comment by stenzek** [comment]
I think once I gain some performance in other areas, I'll just make 100 the default, that way we don't need to override anything.

But in the emu's correct state, I think the perf cost would be too high for really low spec machines.

**Comment by stenzek** [comment]
Gameini added for US and Japanese versions in https://github.com/stenzek/duckstation/commit/b2a6ad143cdf7221a0d634ac31cffeac681b4f95
