### ISSUE TITLE
[Front Mission 3 (Japan)] Vulkan validation errors and crashes on RADV

### ISSUE THREAD

**Issue by Oschowa** [stenzek/duckstation#832]
Version of duckstation: 9bb278b166d42
OS: Arch Linux
Driver/GPU: RADV on RX580

When running the game Front Mission 3 (Japan) with the vulkan renderer and otherwise default settings, I'm getting a crash before the main menu when using the RADV driver. It works fine with the proprietary vulkan driver and the OpenGL and Software backends.

There is a lot of vulkan validation error spam which leads me to believe this is a duckstation bug (the last two errors seems related to the crash: 
[validation.txt](https://github.com/stenzek/duckstation/files/5183286/validation.txt)

Backtrace of a RADV debug build for reference:
[radv_backtrace.txt](https://github.com/stenzek/duckstation/files/5183287/radv_backtrace.txt)

**Comment by stenzek** [comment]
Thanks for the validation log. I have a RX 580 and will look into this soon.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/2cecb8bbdbafe0c42e9d57d971f812f7d31f6b6a

**Comment by Oschowa** [comment]
Thanks, it's now fixed for me.
Although the force-enabling of the validation layers introduced with 455f359 caused crashes for me when creating the vulkan instance, because the validation layers have been renamed to VK_LAYER_KHRONOS_validation and VK_LAYER_LUNARG_standard_validation has been deprecated and doesn't exist anymore on my system. Maybe that should be change as well?
