### ISSUE TITLE
Input not detected - Using Mayflash PS3 adapter (Windows10)

### ISSUE THREAD

**Issue by Exequiel3k** [stenzek/duckstation#833]
Hi,
I'm trying to input the button using a PS3 controller connected via Mayflash PS3 Adapter and nothing is responding.
Is this normal? I can't find any settings to change deviceID neither..

**Comment by ggrtk** [comment]
Try the instructions in the README for setting up a user-provided SDL game controller database and see if that solves your issue.

**Comment by Exequiel3k** [comment]
Hey, yeah that solved it.
Thanks!
