### ISSUE TITLE
Vulkan fails to create hardware context

### ISSUE THREAD

**Issue by KawaiiDinosaur** [stenzek/duckstation#834]
Duckstation version: g455f5391
OS: Windows 10 version 2004
GPU:  Radeon RX 5700  XT
Driver version: Adrenalin 20.8.3

When trying to boot a disc or bios, I receive an error. Log for reference:

I/SDLControllerInterface: Controller 0 axis scale set to 1.000000
I/SDLControllerInterface: Controller 0 deadzone size set to 0.250000
I/HostInterface: Boot Filename: C:\Games\ROMs\Playstation\Castlevania - Symphony of the Night (USA)\Castlevania - Symphony of the Night (USA).cue
I/Vulkan::Context: Available extension: VK_KHR_device_group_creation
I/Vulkan::Context: Available extension: VK_KHR_external_fence_capabilities
I/Vulkan::Context: Available extension: VK_KHR_external_memory_capabilities
I/Vulkan::Context: Available extension: VK_KHR_external_semaphore_capabilities
I/Vulkan::Context: Available extension: VK_KHR_get_physical_device_properties2
I/Vulkan::Context: Available extension: VK_KHR_get_surface_capabilities2
I/Vulkan::Context: Available extension: VK_KHR_surface
I/Vulkan::Context: Available extension: VK_KHR_win32_surface
I/Vulkan::Context: Available extension: VK_EXT_debug_report
I/Vulkan::Context: Available extension: VK_EXT_debug_utils
I/Vulkan::Context: Available extension: VK_EXT_swapchain_colorspace
I/Vulkan::Context: Enabling extension: VK_KHR_surface
I/Vulkan::Context: Enabling extension: VK_KHR_win32_surface
I/Vulkan::Context: Enabling extension: VK_EXT_debug_report
E(CreateVulkanInstance): (CreateVulkanInstance) vkCreateInstance failed:  (-6: VK_ERROR_LAYER_NOT_PRESENT)
E(CreateRenderDevice): Failed to create Vulkan context
E(ReportError): Failed to acquire host display

**Comment by stenzek** [comment]
Whoops, I accidentally committed the hardcoded-validation-layers-enabled. Should be fixed with https://github.com/stenzek/duckstation/commit/9a52c54c2fc269dba4becf2a7f54b45344bab50e.

**Comment by KawaiiDinosaur** [comment]
It's fixed now.  Thanks.
