### ISSUE TITLE
Create please duckstation core for s905w (armeabi-v7a).

### ISSUE THREAD

**Issue by bennington111** [stenzek/duckstation#837]
Create please duckstation core for s905w (armeabi-v7a).

**Comment by stenzek** [comment]
Sorry, an armv7 recompiler is not part of the scope of the project at this time. Most armv7 devices also do not have a GLES3 capable GPU, so they would have to use the software render which is too slow.

The SoC you listed (Amlogic S905W?) is AArch64, but only has a GLES2 GPU (Mali-450).

**Comment by Cibomatto2002** [comment]
What about the Raspberry Pi 4 will it run on there someday the emulator for the Playststion 1 for the pie is not so good all we got is PCSX ReARMed.

**Comment by dankcushions** [comment]
runs on pi4 already - needs raspi pi os 64-bit.
