### ISSUE TITLE
possible add a option for window size and ppf patch?

### ISSUE THREAD

**Issue by phoe-nix** [stenzek/duckstation#839]
this is useful for stream.
and support ppf patch?

**Comment by stenzek** [comment]
Window size is on my TODO list.

I do not know what ppf patches are, but if it's not very complex, maybe.

**Comment by Nucleoprotein** [comment]
PPF patches are used for translations or modding, many ppf patches can be found on romhacking.net.
Source code of patch maker and applier can be found here: https://github.com/meunierd/ppf/tree/master/ppfdev
They are supported by ePSXe as in memory patching if gamename.ppf patch is found in iso directory.

**Comment by stenzek** [comment]
Window size is added in https://github.com/stenzek/duckstation/commit/46b97dd4a801f4cfa2ff09ca5a70a53b7893a970.

**Comment by stenzek** [comment]
Automatic PPF applying added in https://github.com/stenzek/duckstation/commit/9aa386e96cad6d07d00cdb9f75159ceca294bc4a. You need to put a .ppf file with the same name as the disc image in the directory it's stored in, and it will be applied if you check the "Apply Image Patches" option in console settings.
