### ISSUE TITLE
Can't get past the title screen of Monkey Magic

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#84]
The placement of "new game" is screwed up and pressing buttons does nothing. 

![Capture](https://user-images.githubusercontent.com/31968468/76432679-69280300-6407-11ea-8a5c-cd81fabd7c50.PNG)

The log

![log](https://user-images.githubusercontent.com/31968468/76432749-80ff8700-6407-11ea-8a25-48eadc50855d.png)

For comparison here's what the title screen looks like in Beetle PSX. As a sidenote, a screenshot option would be very useful. 

![Monkey Magic (USA)-200312-021121](https://user-images.githubusercontent.com/31968468/76432813-9674b100-6407-11ea-9732-56de85c43e50.png)

**Comment by benderscruffy** [comment]
goes ingame for me
![monkey](https://user-images.githubusercontent.com/2696404/76504121-0cb5f980-6482-11ea-9354-c4414f7d9cc4.PNG)

**Comment by stenzek** [comment]
May have been fixed with the latest CD-ROM changes.

**Comment by kurayami6** [comment]
Yeah it's seems to be fixed. Thanks.
