### ISSUE TITLE
Battle Arena Toshinden (USA) vídeo accelerated!!!! In Duckstation emulator!

### ISSUE THREAD

**Issue by momoids** [stenzek/duckstation#841]
Battle Arena Toshinden (USA) accelerated!!!! In Duckstation emulator!

Vídeo:
https://www.youtube.com/watch?v=hC4PD-tHTiw&feature=youtu.be

**Comment by DarkSwan86** [comment]
Duplicate of #695 .

**Comment by stenzek** [comment]
Closing as it is a duplicate.

As an aside, try using the interpreter, or forcing recompiler icache in the game properties.

**Comment by momoids** [comment]
Ok! I'm Try..
