### ISSUE TITLE
Duckstation Freezing Xbrz filter - RA

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#842]
Sten a user on Discord (Pt-br) Channel reported a issue while applying Xbrz filter as follows:

Steps to reproduce issue:

While game is running, go to Config > Texture Filtering > choose a option i.e:.Xbrz,
and then back to game or else; try to get out RA it will freeze. 

Celphone Model: Galaxy Note 9 - Snapdragon 845

RA log attached as well just in case tho.
[retroarch.log](https://github.com/stenzek/duckstation/files/5211778/retroarch.log)

**Comment by stenzek** [comment]
Shader compiling for XBR filtering takes a very long time, this is expected.
