### ISSUE TITLE
Unable to map an axis on controller

### ISSUE THREAD

**Issue by backgamon** [stenzek/duckstation#847]
Hi,

I use a HAMA PS2 to PC USB converter with a dualshock 2.
All buttons/Axis works, except one:
![Screenshot - 13_09_2020 , 09_49_02](https://user-images.githubusercontent.com/39404647/93013279-3f62bb00-f5a7-11ea-9db5-92cfd8e48995.jpg)
RightX axis doesn't work on Dualshock version.
Pad standard working well, only one axis from the dualshock are not detected.

All others emu/program i use detect the controller (entirely).
https://www.hama.com/bilder/00039/abx/00039960abx.jpg

**Comment by ggrtk** [comment]
Can you see if setting up an optional SDL game controller database fixes this issue? Instructions are here: https://github.com/stenzek/duckstation/tree/d9241303082ddf18605c60ddeadf923e714f4f0c#sdl-game-controller-database

**Comment by backgamon** [comment]
Allready tryed...no luck :(

**Comment by stenzek** [comment]
Does using xinput vs SDL make any difference?

**Comment by backgamon** [comment]
Using Xinput cause all buttons/axis not detected anymore.
With SDL(default) as i write before, i only have 1 axis undetected.

I have another adapter (SmartJoypad):
https://i.ebayimg.com/images/g/6H0AAOSw4B9e54g4/s-l1600.jpg
It use the same button/axis of the Hama and it work.
But that adapter doesn't support vibration.

**Comment by hhromic** [comment]
Perhaps you will need to make your own SDL database entry for your adapter and then provide that to duckstation using the external database function.

The same community database repository has instructions on how to make your own mappings: https://github.com/gabomdq/SDL_GameControllerDB

**Comment by backgamon** [comment]
I follow instruction from SDL_GameControllerDB and now all my controller works!

[ 03000000ff1100004133000000000000,39960 Hama Converter,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a2,lefttrigger:b4,righttrigger:b5,platform:Windows, ]
