### ISSUE TITLE
Missing graphics in Best Buy Greatest Hits Demo Disc - Volume One (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#85]
Using D3D11 renderer at x1 resolution.

![Capture](https://user-images.githubusercontent.com/31968468/76485532-dfad1b00-6470-11ea-9a2e-74cd9c6d8bf3.PNG)

For comparison, here's what it looks like in Beetle PSX.

![Best Buy Greatest Hits Demo Disc - Volume One (USA)-200312-144934](https://user-images.githubusercontent.com/31968468/76485593-0e2af600-6471-11ea-9de2-5f9259de7ea1.png)

**Comment by stenzek** [comment]
I'm collapsing this to https://github.com/stenzek/duckstation/issues/153 as it seems to be the same issue. If it is a different issue and persists with the OpenGL/Software renderers, please re-open.
