### ISSUE TITLE
Rumble in Libretro port does not work

### ISSUE THREAD

**Issue by ToniBC** [stenzek/duckstation#851]
I was testing this emulator under Retroarch on Windows 10 x64, even with an iso to test the controller, but I can't get the vibration to work.

Even if I select "Analog (Dualshock)" as Controller 1, it still does not work.

The controller is one compatible with Xinput.

In other PSX emulators, obviously with the same game, it works without problems, but not in Duckstation.

Is this function enabled in Libretro or is there an error?

Thank you.

**Comment by stenzek** [comment]
It should work, but I never tested it (I don't personally ever use the libretro core).

Will check it when I have time.

**Comment by ToniBC** [comment]
Thanks, there are many of us who prefer to use the libretro core for the extras and generally better performance and compatibility.

Being able to configure everything, even per game settings within the same friendly interface is a great advantage, among other things.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/d2ad114354e549b6eb33fa0f383bf268860792a5

**Comment by ToniBC** [comment]
Thanks, when it compiles I will test it to see if it works.

A question or suggestion, usually when cores are compiled in libretro, as in stadalone, it would be advisable to incorporate the build number, because now it only indicates "Duckstation" and it would have to put "Duckstation 0f33242" for example. That way you can check whether or not the current compilation has the changes reflected.

**Comment by ToniBC** [comment]
I confirm that the vibration works correctly, thank you very much.
