### ISSUE TITLE
[SLPS-02120]Shiritsu Justice Gakuen Nekketsu Seisyun  Nikki 2 (JPN) -The name entry screen in Adventure Mode is not depicted correctly.

### ISSUE THREAD

**Issue by pan2marumie3** [stenzek/duckstation#853]
**Version**
0.1-1750-g8d5a6acf

**Issue**
The name entry screen in Adventure mode (Nekketsu Seisyun Nikki 2 mode) is not correctly displayed and cannot be entried.
![SLPS-02120_2020-09-15_20-01-38](https://user-images.githubusercontent.com/71323507/93202818-4f88bf00-f78e-11ea-9f26-7165f7a4f97a.png)
![SLPS-02120_2020-09-15_20-01-45](https://user-images.githubusercontent.com/71323507/93202822-51eb1900-f78e-11ea-953b-f9300ede1433.png)
![SLPS-02120_2020-09-15_20-01-06](https://user-images.githubusercontent.com/71323507/93202833-56afcd00-f78e-11ea-8207-93402f7c8656.png)

**Comment by stenzek** [comment]
Definitely a bug. Could be timing-related - I've seen others like this, does enabling interlacing change anything?

**Comment by pan2marumie3** [comment]
I enabled interlacing as you described and it worked fine.
![SLPS-02120_2020-09-16_00-33-58](https://user-images.githubusercontent.com/71323507/93231991-56c2c380-f7b4-11ea-8773-67470d5606f6.png)

**Comment by stenzek** [comment]
Okay, great. I'll leave this issue open so I remember to add a compatibility entry for this game to force interlacing on.
