### ISSUE TITLE
libretro - Mute CD Audio

### ISSUE THREAD

**Issue by IngwiePhoenix** [stenzek/duckstation#855]
A small addition that would just mute the CD Audio. Sometimes a game doesn't provide BGM controls. So when I want to play my own music instead of the BGM (i.e. during grinding phases) it'd be nice to just have it mute the CD Audio.

Obviously, this doesn't work/apply to all games, just those that actively use CD Audio.

My usecase is the german port of Hogs Of War (SLES-02767).

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/ca0bfc39a28d6d2fee085bccf34ce04b1e3c6a54, along with a nice handy hotkey to toggle it.

Unfortunately libretro doesn't have a way to add hotkeys, so you'll have to toggle it in the menu. I haven't tested it, but it should work.
