### ISSUE TITLE
duckstation qt dont allow compile

### ISSUE THREAD

**Issue by mrdeathjr28** [stenzek/duckstation#857]
hi

ducktstation qt dont allow compile if disable qt frontend works but with qt appear this error (in before versions compile works 25-06-2020):

CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5LinguistTools/Qt5LinguistToolsConfig.cmake:22 (message):
  The package "Qt5LinguistTools" references the file

     "/usr/lib/qt5/bin/lrelease"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/x86_64-linux-gnu/cmake/Qt5LinguistTools/Qt5LinguistToolsConfig.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Qt5LinguistTools/Qt5LinguistToolsConfig.cmake:38 (_qt5_LinguistTools_check_file_exists)
  /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  CMakeLists.txt:94 (find_package)

thanks

**Comment by stenzek** [comment]
You're missing a package. On Ubuntu this is located in qtbase5-dev-tools, qttools5-dev

**Comment by mrdeathjr28** [comment]
> You're missing a package. On Ubuntu this is located in qtbase5-dev-tools, qttools5-dev

solved thanks
