### ISSUE TITLE
automatically change disk (feature request)

### ISSUE THREAD

**Issue by dml360** [stenzek/duckstation#858]
I don't know if it is possible, but I saw that the dolphin has this feature and it is incredible, would it be possible also here on the duckstation? 

Considering Duckstation is wonderful, this feature would make it almost perfect

**Comment by stenzek** [comment]
Not really sure how one could do that. For multi-disc games, how would the emulator know which disc to switch to?

Some games do stop the CD-ROM before switching discs so this could potentially be a trigger (e.g. FF8). But not all (e.g. MGS).

**Comment by tony971** [comment]
I can't help on the triggers, but knowing which disc to switch to could be as simple as loading the next disc in the playlist (assuming a game was launched through an m3u file).

**Comment by phoe-nix** [comment]
you can find gameInfo.db from PSX2PSP, path is PSX2PSP1.42\Files
i suggest use save id as per-game id for multi-disc games

**Comment by dml360** [comment]
So, I thought it was something interesting, I don’t know how but the dolphin makes this change automatically (brilliantly) otherwise I’m wrong REDREAM also makes this change automatically

**Comment by stenzek** [comment]
There's no way to reliably detect when a game wants a disc change (not all stop the CD drive), so I don't really see how this would be possible in a generic way.

It's quick enough to change discs anyway, if you want to do it entirely with a controller, use the fullscreen UI.
