### ISSUE TITLE
Crash Bash (SCES_02834): Crash onloading a map.

### ISSUE THREAD

**Issue by IngwiePhoenix** [stenzek/duckstation#862]
![image](https://user-images.githubusercontent.com/2893716/93538734-1e0b2180-f94f-11ea-8c34-0ea9b65f43d7.png)

Crash Bash had this odd issue where making a copy of the disc and loading it on a modchip would result in only the first four levels being playable. Could be anti-piracy, but I doubt that. Back then, I would wager that inexperience was a factor.

This is a bin/cue rip I just made. The CUE file contains this:
```
FILE "SCES_02834.BIN" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
```

The offset is quite obvious - and I am certain this is correct. As I do not have a proper debugger at hand, there is nothing I can do right now - which leads me to my question: What exactly would you like me to look at? Stack trace, any specific values representing the VM registers of the PS1?

I am using this with RetroArch 1.9.0 and DuckStation reports itself as such:
![image](https://user-images.githubusercontent.com/2893716/93538965-bf927300-f94f-11ea-8ec1-901d96671cdd.png)

That unfortunately didn't give me the version information though, so I dug into the core info files:
```
PS E:\Games\RetroArch\info> type .\duckstation_libretro.info
display_name = "Sony - PlayStation (DuckStation)"
authors = "stenzek"
supported_extensions = "cue|bin|img|chd|m3u"
corename = "DuckStation"
manufacturer = "Sony"
categories = "Emulator"
systemname = "PlayStation"
systemid = "playstation"
database = "Sony - PlayStation"
license = "GPLv3"
permissions = ""
display_version = "v0.1"
supports_no_game = "false"
firmware_count = 3
firmware0_desc = "scph5500.bin (PS1 JP BIOS)"
firmware0_path = "scph5500.bin"
firmware0_opt = "true"
firmware1_desc = "scph5501.bin (PS1 US BIOS)"
firmware1_path = "scph5501.bin"
firmware1_opt = "true"
firmware2_desc = "scph5502.bin (PS1 EU BIOS)"
firmware2_path = "scph5502.bin"
firmware2_opt = "true"
notes = "(!) scph5500.bin (md5): 8dd7d5296a650fac7319bce665a6a53c|(!) scph5501.bin (md5): 490f666e1afb15b7362b406ed1cea246|(!) scph5502.bin (md5): 32736f17079d0b2b7024407c39bd3050| This core also supports No-Intro BIOS images."
description = "DuckStation is a totally new PlayStation 1 (aka PSX) emulator focusing on playability, speed, and long-term maintainability. Accuracy is not the main focus of the emulator, but the goal is to be as accurate as possible while maintaining performance suitable for low-end devices. "Hack" options are discouraged, the default configuration should support all playable games with only some of the enhancements having compatibility issues. A "BIOS" ROM image is required to start the emulator and to play games. You can use an image from any hardware version or region, although mismatching game regions and BIOS regions may have compatibility issues. A ROM image is not provided with the emulator for legal reasons, you should dump this from your own console using Caetla or other means. DuckStation includes hardware rendering (OpenGL, Vulkan and D3D11), upscaling and 24-bit color and a 64-bit dynarec."
```

So, that's all I got...

**Comment by IngwiePhoenix** [comment]
![image](https://user-images.githubusercontent.com/2893716/93539127-26179100-f950-11ea-81fb-d4e1939092a2.png)
Sorry for the blunder. x.x PrintScr and RetroArch are no friends it seems! ^^;

**Comment by stenzek** [comment]
Have you added the SBI file alongside it?

**Comment by IngwiePhoenix** [comment]
I had no idea that was a thing - so I took to a few Youtube videos and blog posts and educated myself. Huh, LibCrypt. Learned something :)

That also ended up fixing my issue. Gotta thank Redump for compiling them in a nice list to look them up at and download them. Thank you for pointing this out to me!
