### ISSUE TITLE
Spyro 2 PAL - Crash when loading a save file

### ISSUE THREAD

**Issue by NibSnipe** [stenzek/duckstation#863]
![Capture d’écran (30)](https://user-images.githubusercontent.com/64591783/93581179-14120e80-f9a1-11ea-9070-28f2a90664c4.png)

When I load my save file in-game, the game crashes and this error message shows up.

Is there a way to fix it?

**Comment by stenzek** [comment]
I think Spyro 2/3 have compatibility issues. You could try forcing NTSC timings or the interpreter, but it's probably an emulation bug. For what it's worth, the NTSC-U/C versions work fine.

**Comment by NibSnipe** [comment]
I tried forcing NTSC timings, didn't work, tried the interpreter, didn't work too.

**Comment by stenzek** [comment]
Can you upload your memory card here so I can check why it's hitting unexecutable code?

Also make sure you have the SBI file alongside the disc image with the same filename.

**Comment by NibSnipe** [comment]
C:\Emulation\Sony\PS1\Duckstation\memcards\Spyro 2 - Gateway to Glimmer (Europe) (En,Fr,De,Es,It)_1.mcd

**Comment by NibSnipe** [comment]
https://github.com/NibSnipe/Memcards/raw/master/Spyro%202%20-%20Gateway%20to%20Glimmer%20(Europe)%20(En%2CFr%2CDe%2CEs%2CIt)_1.mcd

**Comment by NibSnipe** [comment]
Here's the memory card: https://github.com/NibSnipe/Memcards/raw/master/Spyro%202%20-%20Gateway%20to%20Glimmer%20(Europe)%20(En%2CFr%2CDe%2CEs%2CIt)_1.mcd

**Comment by stenzek** [comment]
Should be fixed in the latest build. I had to force the game to interpreter and add an icache hack, it uses self-modifying code in a way which is not compatible with the recompiler.
