### ISSUE TITLE
some multi-tracks do not play

### ISSUE THREAD

**Issue by phoe-nix** [stenzek/duckstation#864]
in winning eleven 2002 (slpm87056), track 7 and 8 can not play, and other multi-tracks games also have this problem. 
format: cue+bin
after beat game, track 2 will play, but before playing finish, game screen is end, and change next track 7, but cant hear anything. same problem in other winning eleven and multi-tracks games. hope fix.
```
FILE "WE2002_J.bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    INDEX 01 29:00:32
  TRACK 03 AUDIO
    INDEX 01 31:18:14
  TRACK 04 AUDIO
    INDEX 01 31:29:56
  TRACK 05 AUDIO
    INDEX 01 33:50:56
  TRACK 06 AUDIO
    INDEX 01 36:11:27
  TRACK 07 AUDIO
    INDEX 01 38:27:67
  TRACK 08 AUDIO
    INDEX 01 38:41:71
  TRACK 09 AUDIO
    INDEX 01 41:43:59

```

**Comment by stenzek** [comment]
This sounds like a pregap problem. Try adding `PREGAP 00:02:00` to tracks 2-9.

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation/commit/2219b9aa66f2932df3c7c9935b6246fb029bc79e should also work around these incorrect cuesheets without breaking games without pregaps.

**Comment by phoe-nix** [comment]
but work on other emu, i will try edit cue file.

**Comment by phoe-nix** [comment]
more problem on latest version, track 4 only play 2 seconds, then repeat, and all trackers delay 2 seconds or more.
im not sure if image dump problem, i will try redump format.

**Comment by phoe-nix** [comment]
i tried redump format, all tracks ok lol

**Comment by phoe-nix** [comment]
PCM tracks delay about 1 second on latest version.
