### ISSUE TITLE
Portable mode is broken

### ISSUE THREAD

**Issue by RazielZnot** [stenzek/duckstation#867]
If path is:
d:\duckstation
Then it works as intended.

But if moved like this:
d:\emulators\ps1\duckstation
Then it doesn't work and falls back to user directory, which is awful.

Creating portable.txt and running with -portable parameter gives same result.

**Comment by stenzek** [comment]
Are you sure you're not missing something? I run the emu in a subdirectory in portable mode and it's always been fine.

**Comment by RazielZnot** [comment]
And what could I miss? I downloaded emulator, moved it to another directory, created portable.txt, placed BIOS where it should be and duckstation just can't find it, instead it creates empty directories in the user documents and tells me to check log, but the log is nowhere to be found for some reason.

Then I moved duckstation to the root of the disk, deleted directory from user documents and it found BIOS right away. Playing games, creating saves, changing settings works without issues in this case.

For example PCSX2 uses similar way to set portable mode and it doesn't have such issue on my PC. Could it be Windows 7 related?

**Comment by RazielZnot** [comment]
Ok, enabled logging into file and moved it to user documents, but there is nothing useful in the log at all, only these two error messages which where shown after attempt to start BIOS:

E(ReportError): Failed to load NTSC-U BIOS
E(ReportError): System failed to boot. The log may contain more information.

**Comment by stenzek** [comment]
Are you creating portable.txt in the same directory as the exe? I just tried on a clean build and it worked fine.

There's three ways to trigger portable mode:
 - Adding a portable.txt file next to the exe.
 - Having settings.ini in the next to the exe.
 - Using -portable on the comamnd line.

Any of these three is sufficient. Portable mode takes precedence over the documents directory - if any of these tests pass, the documents directory will be ignored even if it exists.

**Comment by RazielZnot** [comment]
I tried creating portable.txt and using -portable on command line, also after running emulator in the disk root settings.ini was created next to exe and I moved duckstation back inside another directory and still portable mode fails.

Just now I renamed duckstation to duck and path looks like this:
d:\duck
And it also broke portable mode. Total deleting of duck directory and creating it from scratch in the same place, creating portable.txt, placing BIOS fixes it. Maybe duckstation somehow relies on MUI cache?

To answer my question, in the registry I deleted all keys about duckstation in MUI cache and now portable mode works if I make clean install into d:\emulators\ps1\duckstation
But If I rename it to d:\emulators\ps1\duck or move into disk root then it breaks portable mode again, and only if I return it back to d:\emulators\ps1\duckstation it works. But now I don't see keys about duckstation in registry, it probably requires windows restart for them to appear? This is very weird, what the hell could be the cause of this?

So in total it seems if I delete directory with emulator and make clean install into another place, then portable mode works, but if I rename or move emulator somewhere else afterwards, then portable mode breaks until I return emulator back.

I also made RAM disk with FAT32 and portable mode works no matter how deep duckstation is buried there or how many times I move it around.

**Comment by stenzek** [comment]
MUI has nothing to do with it. It literally looks for a file named settings.ini/portable.txt

Using -portable overrides the file check and forces it to the exe directory. The only way I could think of this being a problem is if it was failing to get the path to the exe for some reason. There's an easy way to test that - run it in non-portable mode, go to controller settings, and see if you can load any input profiles. If none show up, the exe path check is failing.

**Comment by RazielZnot** [comment]
Checked non-portable mode.

Made clean install into disk root, placed BIOS into user directory, started emulator, opened controller settings, profiles visible.

Closed emulator, renamed directory, started emulator, opened controller settings, profiles didn't show up.

**Comment by backgamon** [comment]
It work for me too, my directory are  :
 
E:\playstation\duckstation-windows-x64-release

**Comment by stenzek** [comment]
[duckstation-qt-x64-Release.zip](https://github.com/stenzek/duckstation/files/5251355/duckstation-qt-x64-Release.zip)

Can you try this build with some additional debugging info? Drop the exe in the directory which isn't working with portable mode, run it, and copy/paste the text in the console window.

**Comment by RazielZnot** [comment]
It shows wrong path. Path in the log is the one before I changed location to D:\duckstation. Where does it take it? Search in the registry didn't give results even after windows restart, but restart changed this path in the log to the real one and when I renamed it again, emulator still shows the one before renaming. Any idea where it can stored?

```
PIN: 'D:\duckstation-windows-x64-release\duckstation-qt-x64-Release.exe' (U16 65) LE: 0
After canonicalize: 'D:\duckstation-windows-x64-release\duckstation-qt-x64-Release.exe'
GetPathDirectory('D:\duckstation-windows-x64-release\duckstation-qt-x64-Release.exe')
out: 'D:\duckstation-windows-x64-release'
Program directory "D:\duckstation-windows-x64-release"
User directory: "C:\Users\REDACTED\Documents\DuckStation"
[    0.1065] W(INISettingsInterface): Settings could not be loaded from 'C:\Users\REDACTED\Documents\DuckStation\settings.ini', defaults will be used.
[    0.1067] E(ReportError): Settings version -1 does not match expected version 3, resetting
[    0.1217] I/SDLControllerInterface: Controller 0 inserted
[    0.1219] I/SDLControllerInterface: Opened controller 0 (instance id 0, player id 0): XInput Controller
[    0.1223] I/SDLControllerInterface: Rumble is supported on 'XInput Controller'
[    0.1224] I/ControllerInterface: Host controller 0 connected, updating inputmap
[    0.1226] I/SDLControllerInterface: Controller 0 axis scale set to 1.000000
[    0.1227] I/SDLControllerInterface: Controller 0 deadzone size set to 0.250000
[    0.1230] I/SDLControllerInterface: Controller 0 axis scale set to 1.000000
[    0.1231] I/SDLControllerInterface: Controller 0 deadzone size set to 0.250000
```

**Comment by stenzek** [comment]
Path comes from `QueryFullProcessImageNameW()` with `GetCurrentProcess()` as the handle.

Seems like there's a known issue with it: https://social.msdn.microsoft.com/Forums/windowshardware/en-US/4b7b3884-d0bb-4812-bc18-2078c61d4b90/queryfullprocessimagename-gives-wrong-path-for-renamed-directory?forum=windowsgeneraldevelopmentissues

Try this build instead, which uses GetModuleFileName: 
[duckstation-qt-x64-Release.zip](https://github.com/stenzek/duckstation/files/5251430/duckstation-qt-x64-Release.zip)

**Comment by RazielZnot** [comment]
This one works flawlessly.

**Comment by stenzek** [comment]
Alright, I'll push the change later. What a strange Windows bug...

**Comment by RazielZnot** [comment]
So, I close ticket?

**Comment by stenzek** [comment]
Sure, or wait for me to push the fix.

**Comment by RazielZnot** [comment]
I'll close now. Thanks.
