### ISSUE TITLE
Formula One 99 (SLUS-00870) - Crashes when trying to select tracks

### ISSUE THREAD

**Issue by BloodRaynare** [stenzek/duckstation#869]
If I choose the "Circuits" in Quick Race, the emulator crashes with this message box:

![f199errorduckstation](https://user-images.githubusercontent.com/46045141/93706696-e2d94000-fb52-11ea-9c9e-4ebae7994ab2.png)

Using latest commits (fa3307e)

**Comment by stenzek** [comment]
Ignoring these sectors seems to work.. I probably should do a hardware test some time to confirm though.

**Comment by BloodRaynare** [comment]
Just updated the emulator to the latest commit (e2fab72 as of the writing of this post) and it's no longer crashing
![SLUS-00870_2020-09-25_07-52-11](https://user-images.githubusercontent.com/46045141/94214836-e844da80-ff04-11ea-8fb0-7c368202fa75.png)
