### ISSUE TITLE
Pro Pinball Series not work

### ISSUE THREAD

**Issue by ToniBC** [stenzek/duckstation#871]
The Pro Pinball series of games do not work, at least in the Libretro version, I have not tested it in the Standalone version yet. Everything in Windows 10 x64.

Pro Pinball: The Web (USA)
Pro Pinball: Timeshock! (EUR)
Pro Pinball: Fantastic Journey (EUR)
Pro Pinball: Big Race USA (EUR)

These games do not load, they always stay with a black screen or in the case of "Pro Pinball: The Web (USA)", it stays on the logo, but does not continue.

Those are the versions I tried, but the same thing happens in all of them.

Let's see if someone can verify it too or see what problem they have.

Thank you.

**Comment by stenzek** [comment]
That's because you're using the libretro version which currently does not load game compatibility inis.

You need to enable interlacing, and these games will work fine. But due to the number of GPU readbacks it's quite slow in the hardware renderers, and they don't benefit from upscaling anyway, so use software.

**Comment by stenzek** [comment]
See here: https://github.com/stenzek/duckstation/blob/fa3307e5f11f5e6535a7ba2b8c4fce51a8013d8e/data/database/gamesettings.ini#L29

**Comment by ToniBC** [comment]
Obviously, if it is put in Software mode and left in interlacing mode, the game works, but the ball looks like a blind due to the interlacing of the image.

Not to mention that the resolution is also affected among other improvements.

It is a hardware processor error, which is also present in Beetle PSX HW for example, but other older emulators can reproduce it as "epsxe" if I remember correctly.

That is why I reported the error.

**Comment by stenzek** [comment]
It's not an error. These games need interlacing enabled to work, as it renders a polygon and reads it back to detect which field is being displayed. Very inefficient way of doing so, but that's how they work.

So, again, this is not a bug. 

The resolution is irrelevant - they are 2D games, upscaling will make no difference. This is why I use a compatibility setting in the standalone version - it will only use software for these games, and everything else will run with whatever you have configured.

The "fix" for the combing is to implement a better deinterlacing filter. This is something in my to-do list, but it might end up being a standalone-only feature as if I remember correctly RA also offees deinterlacing.

**Comment by ToniBC** [comment]
Ok, thanks for clearing things up and explanation. Responses are greatly appreciated.

Then we will close this error as it is not one as such. I solved the problem by applying a shader, but the result is not very good, but acceptable.

Something similar happened with the core parallel of the N64, that the games needed deinterlacing (like those of Star Wars) and they implemented that in the emulator itself.

As you say, ideally for all these games that do not support "progressive", the emulator applies a filter.

I'll tell you about parallel, because there they solved that issue very well, and the same technique may be applied in this emulator.

Thank you.
