### ISSUE TITLE
[Request] assign controller setting profile to specific game

### ISSUE THREAD

**Issue by Trokinos** [stenzek/duckstation#877]
Hello,

I noticed the current build of Duckstation expanded the individual game properties by adding an user and compatibility tab. 
The user setting tab allow to assign a different controller to a specific game.

That's great already, but would it also be possible to assign a different profile for the selected controller ?

I mean when you assign a controller buttons to your keyboard, it's possible to save what you did to a profile file, so you can have a same controller having different keys assigned to it by loading a different profile file.

Having the possibility to have the profile added to the user setting of a game properties would allow the user to not have to go to Settings -> Controller Settings -> Load Profile everytime he wants to use a key binding specifically made for a game.

**Comment by stenzek** [comment]
This one's easier said than done, loading profiles overwrites the current config, but game settings are "overlayed" on top and don't affect the global config.

It's still possible, just a bit more complicated.

**Comment by Trokinos** [comment]
I have a hard time sometime to find where i put my shoes already, so i can imagine how really difficult coding something is :-D so no worry as long as i remember where to load profiles.
Keep up the good work, my favorite emulator by far.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/0b858658cac45d5685eec814fd45bf6d9f2cc1d6

Note that only the bindings from the profile are used, so you may want to set the controller type in the game settings too. This is so it doesn't clobber/overwrite the global settings.
