### ISSUE TITLE
Graphical glitches in Dodonpachi (Japan) (Rev 1)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#88]
Glitchy lines all over the place 

![Capture](https://user-images.githubusercontent.com/31968468/76531354-31818f80-64c9-11ea-9fbe-eaa775bcbfc7.PNG)

**Comment by kurayami6** [comment]
Little Ralph has the same problem. 

![Capture](https://user-images.githubusercontent.com/31968468/76604062-262e7280-6562-11ea-99f0-2b4e42e0cafd.PNG)

**Comment by kurayami6** [comment]
Castlevania Chronicles 

![Capture](https://user-images.githubusercontent.com/31968468/76607390-04d08500-6568-11ea-846c-d2c6bcec6835.PNG)

**Comment by stenzek** [comment]
Should be fixed in latest master.
