### ISSUE TITLE
Error to boot multi disc game

### ISSUE THREAD

**Issue by Porginette** [stenzek/duckstation#881]
HI,
I have a following problem,
I manage perfectly to play mono disc games (beyond the beyond for example) the games are launched.
But when I try to launch multi disc games like xenogears (for example), duckstation does not recognize the .m3u folder that I created to compile the two discs with the button "start disc", and when I directly try to launch the game from the disc1.cue it marks me the following error : 
"Fail to load CD image" and "System fail to boot".
I searched searched but I cannot find the solution.
Thanks for your help !

PS : i have the 3 bios ; NTSC-J, NTSC-UC and PAL-E (scph5500.bin, scph5501.bin and scph5502.bin).

**Comment by stenzek** [comment]
The m3u should show up in the game list.

If it's not loading the cue file directly you likely have an error in your cue file. If you enable the log in advanced options it'll probably tell you what's wrong with it.

**Comment by Porginette** [comment]
Indeed after having activated, in the advanced options of DuckStation the logs and observed the problems, 
I tested in .cue and .m3u a recently downloaded No-Intro collection and it works perfectly with the emulator.

So I just realized that a significant portion of my R ** s collection is completely obsolete, 
I have to clear everything and change everything.

That being said DuckStation is remarkable ! 

Thanks for this emulator ; )
Ty for help,
And all my support in this wonderful project.

Cordially.

**Comment by Porginette** [comment]
On the other hand,
I still cannot find a way to make DuckStation recognize the .m3u files when I click on "start disc" button, 
whereas with the other emulators I have no problem.

**Comment by stenzek** [comment]
Ah, looks like playlists aren't included in the default filter. Try start disc -> dropdown file type -> Playlists. I'll fix that soon.

That said, just launch it from the game list, it's easier ;)

**Comment by Porginette** [comment]
Ah ok !
TY : )
Have a good day.

**Comment by stenzek** [comment]
m3u added to open file filter in https://github.com/stenzek/duckstation/commit/e2fab72bcbb7d2a432b7e3ce1582d90168d48aa1
