### ISSUE TITLE
analog mode controller cant work on Castlevania - Symphony of the Night/Akumajou Dracula X - Gekka no Yasoukyoku

### ISSUE THREAD

**Issue by phoe-nix** [stenzek/duckstation#882]
SLPM-86023
SLUS-00067
SLES-00524

**Comment by stenzek** [comment]
Added force digital controller for these games in https://github.com/stenzek/duckstation/commit/4274bc1daf5d4dd12b8b5d5bbe2caa50599ebdc3

**Comment by phoe-nix** [comment]
in bios menu, also cant use analog mode.

**Comment by phoe-nix** [comment]
after u force digital controller for this game, analog can use, but digital stuck sometimes.
