### ISSUE TITLE
Can't seem to bind any buttons from the PlayStation Classic controller on DuckStation

### ISSUE THREAD

**Issue by foxprite** [stenzek/duckstation#884]
As the title suggests attempting to bind any button from the PlayStation Classic controller on Duckstation results in... nothing happening. The controller is working properly on Windows 10 and RetroArch.

**Comment by ggrtk** [comment]
Follow the instructions here for setting up an SDL game controller database: https://github.com/stenzek/duckstation/tree/fb420bad82f39d6666b31f8494b48c55870f8d65#sdl-game-controller-database

I was able to get a PlayStation Classic controller working this way on Windows 10.

**Comment by foxprite** [comment]
Thanks, I'll try to give that a go.
