### ISSUE TITLE
cover file name need same as image's without redump.dat

### ISSUE THREAD

**Issue by phoe-nix** [stenzek/duckstation#889]
can you make it as game code?

**Comment by stenzek** [comment]
It already checks for the code. See https://github.com/stenzek/duckstation/wiki/Adding-Game-Covers

**Comment by phoe-nix** [comment]
i mean not download redump.dat

**Comment by stenzek** [comment]
Yep, I had an error in the serial-based cover path check. Should be fixed in https://github.com/stenzek/duckstation/commit/41f36d06733ebadb495d4383de9944bf5a6a3521. Let me know if it's still broken.

**Comment by phoe-nix** [comment]
and the title name font change size by scrolling cover size, can you lock the font size? too much problems on new version lol

**Comment by stenzek** [comment]
The font size changing is intended - otherwise you would have small images with large captions. You can turn the captions off in the view menu.

But that said, I never tested it at 100% scaling (I run 4K @ 150%), I probably should make sure it looks okay there...

**Comment by phoe-nix** [comment]
Latest version fixed this problem, thanks.
