### ISSUE TITLE
Implement missing GameShark commands

### ISSUE THREAD

**Issue by stenzek** [stenzek/duckstation#890]
https://macrox.gshi.org/The%20Hacking%20Text.htm#playstation_code_types

**Comment by BloodRaynare** [comment]
Sorry for adding nothing to the discussion, but any news on this? Because I have a C-type codes that I want to use in DigimonTamers Battle Evolution (Digimon Rumble Arena in US/EU) along with "Unlock All Characters" codes to fix the broken FMV/freezing during the intro sequence when that code is activated.

**Comment by stenzek** [comment]
> Sorry for adding nothing to the discussion, but any news on this? Because I have a C-type codes that I want to use in DigimonTamers Battle Evolution (Digimon Rumble Arena in US/EU) along with "Unlock All Characters" codes to fix the broken FMV/freezing during the intro sequence when that code is activated.

Can you paste the codes? I'll look at what needs to be added.

**Comment by BloodRaynare** [comment]
> 
> 
> > Sorry for adding nothing to the discussion, but any news on this? Because I have a C-type codes that I want to use in DigimonTamers Battle Evolution (Digimon Rumble Arena in US/EU) along with "Unlock All Characters" codes to fix the broken FMV/freezing during the intro sequence when that code is activated.
> 
> Can you paste the codes? I'll look at what needs to be added.

```
C012AB34 FF80
50001804 0000
8012AB34 0001
```

Here's an example of C-type codes for the Digimon Rumble Arena (the "Unlock All Characters" codes).

**Comment by stenzek** [comment]
Isn't that just "activate all codes"? Couldn't it just be omitted?

Or is this not a gameshark code?

**Comment by BloodRaynare** [comment]
> 
> 
> Isn't that just "activate all codes"? Couldn't it just be omitted?
> 
> Or is this not a gameshark code?

Well, it's GS code.
Anyway, I found it from here: http://www.codetwink.com/view-cheats-3183-title-digimon+rumble+arena.html (Except the C-type codes, I put it myself)
And actually, there's a "One codes per character" version that can be used too with the D-type codes. However, It's just, there's too much lines to insert for just one cheat. But, it works I guess.

**Comment by stenzek** [comment]
C0 command implemented in https://github.com/stenzek/duckstation/commit/c406f0708f25704ee041d4b132f08122a9dc83b7

**Comment by stenzek** [comment]
All known gameshark codes added as of https://github.com/stenzek/duckstation/commit/09495b1d933f3e0fc86f8eb77c53b3724020f186.
