### ISSUE TITLE
Formula One 99 - Loading issue

### ISSUE THREAD

**Issue by gp2man** [stenzek/duckstation#894]
`<entry code="SLUS-00870" title="Formula One 99 (USA) (En,Fr,Es)" region="NTSC-U" compatibility="2">
    <compatibility>Crashes In Intro</compatibility>
    <version-tested>0.1-1835-ge2fab72b</version-tested>
</entry>
`

**Comment by BloodRaynare** [comment]
No, actually it does boot. Set your CPU execution mode to "Interpreter" (No need if you have "gamesettings.ini" in database directory)

**Comment by stenzek** [comment]
Indeed, gameini will force interpreter for this game.

If you're using the libretro core, you'll have to manually set it to interpreter, as I can't ship additional files with the core library :(
