### ISSUE TITLE
[Request] Either implement the libretro cheat interface or allow to set 'load cheat file automatically' in libretro.

### ISSUE THREAD

**Issue by i30817** [stenzek/duckstation#895]
Currently cheats are not working in retroarch, and there is no way to set `duckstation_Main.AutoLoadCheats = "true"` in the core settings file and have it do anything either.

In fact AutoLoadCheats seems to assume the format is PCSR here: https://github.com/stenzek/duckstation/blob/03f052e12ec1ece41381de72824a7d8159a1add9/src/frontend-common/common_host_interface.cpp#L2161

**Comment by stenzek** [comment]
Thanks, I completely forgot about adding cheat support to the libretro core.

For what it's worth, the libretro core doesn't use CommonHostInterface, so none of that code is executed.

**Comment by i30817** [comment]
That explains why i couldn't find the location of the program dir defined anywhere in the libretro dir, which is used to find the 'cheats' directory. I was doing some experimentation (that failed ofc) of moving and renaming the cheat file to the top dir of the cheats retroarch dir and setting the 'obvious name' of that property in the core options .cfg in the hope that a console output or a notification would appear.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/e7cfc699753ef4d7ced59e7b51583ea5e2d6f1de

**Comment by i30817** [comment]
Well this is doing something but it's either not completely right or the cheatfiles i tried were completely broken (very possible considering the total lack of quality control on cheats).

Anyway; i tried the one file for fear effect 2 the cheat database has (setting infinite ammo) and it didn't work; then (and this is how i know that this is doing something, because it doesn't log in the info setting about it), tried Disney Atlantis: some subtitle with a cheat to enable 'extra stuff' (cheat number 3 of that only file again), and it activated a single movie (out of several, it activated the end movie), which i could deactivate by restarting without the cheat.

Maybe there is a off by one in the locations or something.

**Comment by stenzek** [comment]
Yes, it's a mess, they don't even follow the standard (+ as code separator). I hacked a check in there for using +/-/space as separators (same as beetle), which is silly.

**Comment by i30817** [comment]
Oh, i was trying the Fear Effect 2 cheatfile (there is only one). It doesn't work either in beetle or here.

**Comment by stenzek** [comment]
That's probably because it's labelled as "Game Buster". Only GameShark codes are supported, you'll need to convert the cheats.

**Comment by i30817** [comment]
Oh dear. That... well, kind of a footgun from libretro-database, though understandable if the alternative is nothing.

**Comment by i30817** [comment]
Maybe the emulator could use a onscreen notification that it doesn't support gamebuster/Xploder if it attempts to run a cheat file with "(Game Busters)" or "(Xploder) in the filename?

And while we're at it, when turning on a cheat with "+????" in the code this is obviously a placeholder for a joker command so turning this on does nothing at best, so maybe a on screen notification for that would be nice too.

**Comment by stenzek** [comment]
The original issue here is fixed, so closing.

No plans at the moment for supporting other cheat formats, other emus don't support them either and there doesn't seem to be any demand.

gamehacking.org has plenty of compatible cheats in GS format anyway.
