### ISSUE TITLE
Destruction Derby 2 (SCUS-94350) - Pause menu shows nothing

### ISSUE THREAD

**Issue by BloodRaynare** [stenzek/duckstation#896]
![SCUS-94350_2020-09-25_14-31-58](https://user-images.githubusercontent.com/46045141/94239411-f6fab400-ff3b-11ea-8854-7d8e99baef8d.png)

When pressing start during gameplay to pause the game, it shows nothing.
Tried every renderer (except Vulkan, because my GPU didn't support it) and all of them yield same results.

By the way, here's how the pause menu originally looks like

![DD2](https://user-images.githubusercontent.com/46045141/94239163-979ca400-ff3b-11ea-8f22-8bf4572de5dd.png)

**Comment by stenzek** [comment]
Seems to be DMA timing related, same as Vampire Hunter D.

**Comment by stenzek** [comment]
Fixed with gameini in https://github.com/stenzek/duckstation/commit/7210b0826a623ee31b56cf92688a9be308dedcb1
