### ISSUE TITLE
Improve Android touchscreen controls

### ISSUE THREAD

**Issue by kevinalpian** [stenzek/duckstation#897]
![GIF_20200926_004546](https://user-images.githubusercontent.com/56602652/94299342-bc236b00-ff91-11ea-909d-c2fcb48dad84.gif)

**Comment by stenzek** [comment]
Yep, the touchscreen controls are *very* basic. Replacing them is on my todo list.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/4b8ae472ab763a63ce53fd3123b587d7873ed28c
