### ISSUE TITLE
Automatically change to 4:3 during FMVs

### ISSUE THREAD

**Issue by genova447** [stenzek/duckstation#898]
Please excuse me if this has already been requested - I tried to search a bit around, and couldn't find anything.

But similar to PCSX2's ability to automatically switch the game window to 4:3 rather than {other format} when there's an FMV playing, I thought  that this would be neat here as well.
I am far from aware of most game's way of 'behaving' when the widescreen hack is applied, but at least for all the games I have played myself, the FMVs are always stretched, as is reasonable to expect.

It could be a neat feature if Duckstation could 'detect' that a video file is playing, switch to 4:3 - and then switch back to whatever it was previously once the FMV is over.

Of course this should probably be a togglable option, and a per-game-basis option as well... in case there are some PS1 games that have 16:9 FMVs
Maybe as an extra thing with this could be, when 4:3 FMVs are detected to have black borders at the top and bottom, making it really a 16:9 (or close to anyway) - then just zoom the whole thing in... still technically being 4:3, but giving the illusion of 16;9 because the FMV-borders have been removed - if all that makes sense :o 

(sorry if I make it overly lengthy)

**Comment by stenzek** [comment]
Interesting idea. Most FMVs are 24-bit (instead of 16-bit), so we could potentially switch AR there.

As for borders, don't think anything can be done there.

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/d73271ec0a8bd6288655f89680f6e9314e47eeef

**Comment by DonelBueno** [comment]
It doesn't work in some games, like in Looney Tunes Racing and both Medal of Honor, for example.

Is there a way to Identify when MDEC is being used instead?

**Comment by RazielZnot** [comment]
@DonelBueno some games use 16bpp FMVs, Medal of Honor does exactly that, that's why detection fails. Probably it's is possible to use DMA transfers as a trigger, but those also can be used for streaming animated textures and still images decompressed by MDEC, so this can create additional issues.

**Comment by Richard-L** [comment]
Just want to say there where it _does_ work it's amazing and makes a great difference.

Is there theoretically a possible trigger for still images like these?
https://cdn.discordapp.com/attachments/695823573830598706/762087534967652412/unknown.png
