### ISSUE TITLE
[Bug] Savestate/memcard interaction issue leading to possible failed save

### ISSUE THREAD

**Issue by TzakShrike** [stenzek/duckstation#899]
As demonstrated on stream.
Possible workaround is to compare the memcard on disk and in state for equality on load, but underlying issue is possibly something not being tracked correctly in savestate.

**Comment by stenzek** [comment]
Worked around in https://github.com/stenzek/duckstation/commit/3b68c4028d7e6958996900c5eac5666b392cb225. Please comment if the issue is still persisting.
