### ISSUE TITLE
[Bug] Soundscope.

### ISSUE THREAD

**Issue by TzakShrike** [stenzek/duckstation#900]
Trying to start Soundscope (select while playing music in BIOS music player with a 7000/9000 series BIOS) results in freeze or nothing.

**Comment by TzakShrike** [comment]
Trying to start Soundscope (select while playing music in BIOS music player with a 7000/9000 series BIOS) results in freeze or nothing.

**Comment by Kurayami7** [comment]
Still happens as of the latest version. Press select with a CD loaded, this command shows up in the log and the whole thing freezes.

![Capture](https://user-images.githubusercontent.com/77198254/113735674-cf34a600-973f-11eb-9d3c-c6ab61aeb35f.PNG)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/40731b49fc2ef1a7e300d681a03988dedac7e0cc
