### ISSUE TITLE
Castlevania - Symphony of the Night

### ISSUE THREAD

**Issue by madruded** [stenzek/duckstation#902]
`<entry code="SLUS-00067" title="Castlevania - Symphony of the Night" region="NTSC-U" compatibility="0">
    <compatibility>Unknown</compatibility>
    <version-tested>0.1-1850-g8342fec2</version-tested>
    <comments>Game Castlevania Symphony of the Night is not recognizing the analogue option, I tested it in other games and the analog works normal.
need help</comments>
</entry>
`

**Comment by stenzek** [comment]
Analog is not supported in this game.
