### ISSUE TITLE
[Bug Report] Remembering window size/position doesn't work for games rendered to a separate window

### ISSUE THREAD

**Issue by Abbanon** [stenzek/duckstation#905]
Currently, with `Render To Main Window` set to **off/unchecked**, the separate game window's size/location isn't being remembered.
It's only working for the main DuckStation window. Any chance this could be addressed to work for the separate window too?

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/f7de39f3d04b220e0b5defd814e431378623e009
