### ISSUE TITLE
FoxKids.com - Micro Maniacs Racing (USA) stuck on loading screen

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#91]
when you choose your character then it goes to load the track it stops loading
![micro](https://user-images.githubusercontent.com/2696404/76600664-4ea67480-6542-11ea-82da-41fd9eb86855.PNG)

**Comment by benderscruffy** [comment]
still happens in the latest master

**Comment by stenzek** [comment]
Narrowed down to CD-ROM issue. Fix pending hardware tests.

**Comment by stenzek** [comment]
Should be fixed as of https://github.com/stenzek/duckstation/commit/110aa8bd936e79a7e9085e79b68204bc27e2e3d2
