### ISSUE TITLE
[Bug] UI warning for overclock not issued correctly

### ISSUE THREAD

**Issue by TzakShrike** [stenzek/duckstation#912]
Checking "Enable...Overclocking" and then clicking "No, take me back to safety." correctly removes the checkmark in the UI, but maybe it doesn't toggle the option back off, because checking it once again does not produce the warning, but checking it TWICE does.

Ironically, this allows users to turn overclocking on without ever accepting the warning.

**Comment by stenzek** [comment]
This was fixed in https://github.com/stenzek/duckstation/commit/1da6db7260fbe340de8dbe4fd0e31d1aea7f222b
