### ISSUE TITLE
Save states incompatible

### ISSUE THREAD

**Issue by Punishedhanma** [stenzek/duckstation#913]
After updating to the newest version I wasnt able to load my savestates and got an error message that said "Save state is incompatible: expecting version 42 but state is version 40." Is there a way to fix this?

**Comment by heckez-sys** [comment]
yes use a memcard for your games

**Comment by Richard-L** [comment]
@Punishedhanma are you coming from an older version? A warning for save state breaking upon update has recently been added: https://github.com/stenzek/duckstation/issues/812

I assume you may not have seen it.

Sometimes when new features are added to the emulator the save states must change, and the workaround is to save all your games to a memory card as heckez-sys mentions. You can use Tools > Memory Card Editor to organise your data.

**Comment by stenzek** [comment]
I had to bump the version to support overclocking.

Go back to an older build, save your game to memory card, and then update. The last build before the save state version change can be downloaded here: https://github.com/stenzek/duckstation/suites/1262054882/artifacts/19339376

**Comment by Punishedhanma** [comment]
Its fixed now, thanks a lot for your help.
