### ISSUE TITLE
Add "Year" column to game list

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#915]
Mini thing: Could you add a "Year" column here, pulled from redump?
![image](https://user-images.githubusercontent.com/4934209/94820768-1e9cc100-0401-11eb-872d-4a8c2ff04750.png)

**Comment by stenzek** [comment]
I'm not seeing where redump lists the year in their web viewer, nor does the dat file you can download include it.

**Comment by Richard-L** [comment]
Oh I just assumed redump would hold something as basic as year??

That's a bummer 🙁

There must be data available on this somewhere that we could use?

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/ff14e8aede6f0e852d346ac27509fb2897b606f4
