### ISSUE TITLE
[Bug] Resume button glitches and crash when last savestate is not present

### ISSUE THREAD

**Issue by hhromic** [stenzek/duckstation#917]
When there is no last savestate present (for example with the Save State On Exit option disabled), Duckstation behaves wrongly in the following situation:

* Press the "Resume" button in the toolbar.
* Duckstation correctly notifies that there is no last savestate to resume from.
* The "Resume" button now is turned into "Power Off" and is disabled.
* Double-click on any game in the gamelist to start a new game.
* Duckstation crashes without any error messages (nothing in debug log either).

I think that the "Resume" button should not turn into "Power Off" when the last savestate is not found.
Maybe this is the source of the crash?

**Comment by stenzek** [comment]
Fixed in 7cf8f6046468ef7e4225a01f54bf6c6850065b9f
