### ISSUE TITLE
[BUG] T'ai Fu - Wrath of the Tiger [U] music/sound issue.

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#920]
A bit of an issue woth Taifu Wrath of the tiger, one no music, problem with audio tracks also VPS is at 25-27 where it should be constant 30 which causes noticeable stuttering.
Game is in CHD compressed,
Uncompressed bin/cue music works and VPS is fine, but sound effects are broken, loud screeching noises.

**Comment by stenzek** [comment]
VPS should be 60.

This sounds like https://github.com/stenzek/duckstation/issues/655 - old versions of chdman were creating incorrect chds. Try re-dumping/converting to CHD again.

**Comment by foxsevent** [comment]
Could be, I've been using same chdman for a while, where can I get a newer version?

**Comment by stenzek** [comment]
Should be included in the latest MAME release: https://www.mamedev.org/release.php

**Comment by foxsevent** [comment]
Sorry for the late response.
Using a new fresh dump game works fine music, sound effects and all.
Compressing it using the newest chdman gives me same results as before broken cd audio.

**Comment by stenzek** [comment]
Interesting. I wonder if this is related to getting different hashes from CHD images in game properties.

**Comment by foxsevent** [comment]
> Interesting. I wonder if this is related to getting different hashes from CHD images in game properties.
Possibly, it's just HASH that's different but LBA as well, maybe that's the culprit.
![Original](https://user-images.githubusercontent.com/64225743/94987681-60944700-0568-11eb-942e-ddf0ba2344ee.PNG)
![Compressed](https://user-images.githubusercontent.com/64225743/94987683-625e0a80-0568-11eb-87bc-152e39cd2455.PNG)
![Decompressed](https://user-images.githubusercontent.com/64225743/94987684-625e0a80-0568-11eb-9b62-3d4967efc769.PNG)

**Comment by foxsevent** [comment]
This is from the OLD CHKD.

> chdman - MAME Compressed Hunks of Data (CHD) manager 0.225 (mame0225)
Input file:   c:\tiger.chd
File Version: 5
Logical size: 708,715,584 bytes
Hunk Size:    19,584 bytes
Total Hunks:  36,189
Unit Size:    2,448 bytes
Total Units:  289,508
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     418,196,298 bytes
Ratio:        59.0%
SHA1:         7584ee228025c93368ed5d95a59c0d5ffc7359f4
Data SHA1:    52f97bf9d0989a00eef603f72c54a0d46ba985c4
Metadata:     Tag='CHT2'  Index=0  Length=92 bytes
              TRACK:1 TYPE:MODE2_RAW SUBTYPE:NONE FRAMES:88113 PREGAP:0 PG
Metadata:     Tag='CHT2'  Index=1  Length=90 bytes
              TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:8595 PREGAP:150 PGTYP
Metadata:     Tag='CHT2'  Index=2  Length=88 bytes
              TRACK:3 TYPE:AUDIO SUBTYPE:NONE FRAMES:13720 PREGAP:0 PGTYPE
Metadata:     Tag='CHT2'  Index=3  Length=88 bytes
              TRACK:4 TYPE:AUDIO SUBTYPE:NONE FRAMES:15851 PREGAP:0 PGTYPE
Metadata:     Tag='CHT2'  Index=4  Length=88 bytes
              TRACK:5 TYPE:AUDIO SUBTYPE:NONE FRAMES:14058 PREGAP:0 PGTYPE
Metadata:     Tag='CHT2'  Index=5  Length=88 bytes
              TRACK:6 TYPE:AUDIO SUBTYPE:NONE FRAMES:12323 PREGAP:0 PGTYPE
Metadata:     Tag='CHT2'  Index=6  Length=88 bytes
              TRACK:7 TYPE:AUDIO SUBTYPE:NONE FRAMES:15226 PREGAP:0 PGTYPE
Metadata:     Tag='CHT2'  Index=7  Length=88 bytes
              TRACK:8 TYPE:AUDIO SUBTYPE:NONE FRAMES:16033 PREGAP:0 PGTYPE
Metadata:     Tag='CHT2'  Index=8  Length=87 bytes
              TRACK:9 TYPE:AUDIO SUBTYPE:NONE FRAMES:8447 PREGAP:0 PGTYPE:
Metadata:     Tag='CHT2'  Index=9  Length=89 bytes
              TRACK:10 TYPE:AUDIO SUBTYPE:NONE FRAMES:14048 PREGAP:0 PGTYP
Metadata:     Tag='CHT2'  Index=10  Length=89 bytes
              TRACK:11 TYPE:AUDIO SUBTYPE:NONE FRAMES:13355 PREGAP:0 PGTYP
Metadata:     Tag='CHT2'  Index=11  Length=89 bytes
              TRACK:12 TYPE:AUDIO SUBTYPE:NONE FRAMES:13501 PREGAP:0 PGTYP
Metadata:     Tag='CHT2'  Index=12  Length=89 bytes
              TRACK:13 TYPE:AUDIO SUBTYPE:NONE FRAMES:15785 PREGAP:0 PGTYP
Metadata:     Tag='CHT2'  Index=13  Length=89 bytes
              TRACK:14 TYPE:AUDIO SUBTYPE:NONE FRAMES:13609 PREGAP:0 PGTYP
Metadata:     Tag='CHT2'  Index=14  Length=89 bytes
              TRACK:15 TYPE:AUDIO SUBTYPE:NONE FRAMES:12286 PREGAP:0 PGTYP
Metadata:     Tag='CHT2'  Index=15  Length=89 bytes
              TRACK:16 TYPE:AUDIO SUBTYPE:NONE FRAMES:14532 PREGAP:0 PGTYP

This is the new one.

> C:\Users\Daniel>c:\chdman info -i c:\tiger2.chd
chdman - MAME Compressed Hunks of Data (CHD) manager 0.225 (mame0225)
Input file:   c:\tiger2.chd
File Version: 5
Logical size: 708,715,584 bytes
Hunk Size:    19,584 bytes
Total Hunks:  36,189
Unit Size:    2,448 bytes
Total Units:  289,508
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     418,194,407 bytes
Ratio:        59.0%
SHA1:         048f25d0f51a4182b1bace8bd16d372c2f7aec1c
Data SHA1:    da1273fa29e32665af2f6365797c72951bbb2068
Metadata:     Tag='CHT2'  Index=0  Length=92 bytes
              TRACK:1 TYPE:MODE2_RAW SUBTYPE:NONE FRAMES:88263 PREGAP:0 PG
Metadata:     Tag='CHT2'  Index=1  Length=87 bytes
              TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:8445 PREGAP:0 PGTYPE:
Metadata:     Tag='CHT2'  Index=2  Length=88 bytes
              TRACK:3 TYPE:AUDIO SUBTYPE:NONE FRAMES:13720 PREGAP:0 PGTYPE
Metadata:     Tag='CHT2'  Index=3  Length=88 bytes
              TRACK:4 TYPE:AUDIO SUBTYPE:NONE FRAMES:15851 PREGAP:0 PGTYPE
Metadata:     Tag='CHT2'  Index=4  Length=88 bytes
              TRACK:5 TYPE:AUDIO SUBTYPE:NONE FRAMES:14058 PREGAP:0 PGTYPE
Metadata:     Tag='CHT2'  Index=5  Length=88 bytes
              TRACK:6 TYPE:AUDIO SUBTYPE:NONE FRAMES:12323 PREGAP:0 PGTYPE
Metadata:     Tag='CHT2'  Index=6  Length=88 bytes
              TRACK:7 TYPE:AUDIO SUBTYPE:NONE FRAMES:15226 PREGAP:0 PGTYPE
Metadata:     Tag='CHT2'  Index=7  Length=88 bytes
              TRACK:8 TYPE:AUDIO SUBTYPE:NONE FRAMES:16033 PREGAP:0 PGTYPE
Metadata:     Tag='CHT2'  Index=8  Length=87 bytes
              TRACK:9 TYPE:AUDIO SUBTYPE:NONE FRAMES:8447 PREGAP:0 PGTYPE:
Metadata:     Tag='CHT2'  Index=9  Length=89 bytes
              TRACK:10 TYPE:AUDIO SUBTYPE:NONE FRAMES:14048 PREGAP:0 PGTYP
Metadata:     Tag='CHT2'  Index=10  Length=89 bytes
              TRACK:11 TYPE:AUDIO SUBTYPE:NONE FRAMES:13355 PREGAP:0 PGTYP
Metadata:     Tag='CHT2'  Index=11  Length=89 bytes
              TRACK:12 TYPE:AUDIO SUBTYPE:NONE FRAMES:13501 PREGAP:0 PGTYP
Metadata:     Tag='CHT2'  Index=12  Length=89 bytes
              TRACK:13 TYPE:AUDIO SUBTYPE:NONE FRAMES:15785 PREGAP:0 PGTYP
Metadata:     Tag='CHT2'  Index=13  Length=89 bytes
              TRACK:14 TYPE:AUDIO SUBTYPE:NONE FRAMES:13609 PREGAP:0 PGTYP
Metadata:     Tag='CHT2'  Index=14  Length=89 bytes
              TRACK:15 TYPE:AUDIO SUBTYPE:NONE FRAMES:12286 PREGAP:0 PGTYP
Metadata:     Tag='CHT2'  Index=15  Length=89 bytes
              TRACK:16 TYPE:AUDIO SUBTYPE:NONE FRAMES:14532 PREGAP:0 PGTYP

**Comment by foxsevent** [comment]
![old](https://user-images.githubusercontent.com/64225743/94991333-bbd33300-0582-11eb-9f72-64498465f106.PNG)
![new](https://user-images.githubusercontent.com/64225743/94991335-bc6bc980-0582-11eb-9fe7-df6ae3ec2b1f.PNG)

**Comment by foxsevent** [comment]
Broken cue sheet file, my bad.
