### ISSUE TITLE
Crash Team Racing SCES_021.05 Not Boot

### ISSUE THREAD

**Issue by diegoginard** [stenzek/duckstation#932]
<entry code="SCES-02105" title="Crash Team Racing-PSX-PAL" region="PAL" compatibility="1">
    <compatibility>Doesn't Boot</compatibility>
    <version-tested>0.1-1932-g395f5e2c</version-tested>
    <comments>freezes on the first screen after bios boot</comments>
</entry>

**Comment by stenzek** [comment]
Duplicate of #933.
