### ISSUE TITLE
Crash Team Racing SCES_021.05 Not boot

### ISSUE THREAD

**Issue by diegoginard** [stenzek/duckstation#933]
<entry code="SCES-02105" title="Crash Team Racing-PSX-PAL" region="PAL" compatibility="1">
    <compatibility>Doesn't Boot</compatibility>
    <version-tested>0.1-1932-g395f5e2c</version-tested>
    <comments>freezes on the first screen after bios boot</comments>
</entry>

**Comment by Zet-sensei** [comment]
You need the SBI file with your dump for emulating correctly the LibCrypt protection on the game.

Issue should be closed - user error & not a bug on the emulator.

**Comment by stenzek** [comment]
Needs libcrypt.
