### ISSUE TITLE
Kitchen Panic (J) SLPS_013.95 Graphical issues

### ISSUE THREAD

**Issue by diegoginard** [stenzek/duckstation#934]
<entry code="SLPS-01395" title="Kitchen Panic (J)" region="NTSC-J" compatibility="4">
    <compatibility>Graphical/Audio Issues</compatibility>
    <version-tested>0.1-1932-g395f5e2c</version-tested>
    <comments>It has a glitch in the background images</comments>
</entry>

**Comment by stenzek** [comment]
Looks like this was fixed by https://github.com/stenzek/duckstation/commit/fe25f005c25b7a2289de4cfa02f19090f1576935
