### ISSUE TITLE
how to import save .gme for ducksation?

### ISSUE THREAD

**Issue by momoids** [stenzek/duckstation#935]
how to import save .gme for ducksation? 
to import saves with .GME extension how do I do? 
(English is not my native language!)

**Comment by andercard0** [comment]
> 
> 
> how to import save .gme for ducksation?
> to import saves with .GME extension how do I do?
> (English is not my native language!)

Try to rename it for: **.mcd** and import it via Menu tools **>** Memory card editor.

**Comment by stenzek** [comment]
1. Tools -> Memory Card Editor
2. Select the card you wish to import the gme to from the drop-down list
3. Select "Import Card" at the bottom of the window
4. Navigate to the gme path
5. Save

**Comment by momoids** [comment]
Thanks!

**Comment by oxr463** [comment]
What about on Android?

**Comment by stenzek** [comment]
@oxr463 Android does not have a memory card editor yet. You would have to use the editor on the desktop version, and then copy your memory card to your device.
