### ISSUE TITLE
01.1901-g9bf1d61f - Controllers are not working (Linux Version)

### ISSUE THREAD

**Issue by BassHero** [stenzek/duckstation#938]
Hello!

Despite the new version showing game covers is very cool, I'm still using the version 01.-1719-g2bed6764 because the controllers stop to work. My OS is Ubuntu 20.04.

My controller is "Twin USB Joystick", a adapter that I'm using to plug 2 PS2 controllers (Dualshock) on PC.

Thanks for attention.

Renato Ramalho
Brazil

**Comment by stenzek** [comment]
Did you try using the SDL controller database listed on the main page? https://github.com/stenzek/duckstation#sdl-game-controller-database

**Comment by BassHero** [comment]
Yes, I tried it after your answer. I also tried to select the SDL option in "Controller Backend" in "General Settings", but in both cases, don't work. In the previous version works automatically.
