### ISSUE TITLE
Graphics are completely broken in Real Bout Garou Densetsu Special - Dominated Mind (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#94]
Character portraits are missing

![Capture2](https://user-images.githubusercontent.com/31968468/76619477-140efd00-657f-11ea-8284-b5d7eaa16fc7.PNG)

And in game speaks for itself

![Capture](https://user-images.githubusercontent.com/31968468/76619512-2db04480-657f-11ea-8eb5-9265b2d35fbc.PNG)

**Comment by kurayami6** [comment]
Using OpenGL it's a lot better but still glitchy.

![Capture](https://user-images.githubusercontent.com/31968468/76699986-e0f77580-6706-11ea-918d-69e9288c749d.PNG)

**Comment by stenzek** [comment]
Does this still occur on master? I am unable to reproduce in D3D.

The glitches around the edges are a separate common issue between a few games, it happens when the texture coordinates are flipped. I have a fix planned.

**Comment by kurayami6** [comment]
Yes it still occurs. I think all these graphical glitches I'm getting in various games are caused by me using D3D11 and Windows 7. If you're unable to develop this emulator in a way that D3D11 doesn't break on Windows 7 maybe it'd be better to just disable it for Windows 7 users and just have them use OpenGL since it always seems to work fine.

**Comment by stenzek** [comment]
I have a theory it's to do with the texture upload/decoding. Could you switch on "Show VRAM" in the debug options and attach a screenshot?

I'll work around it if there's an easy fix, but I'd rather not add another/slower code path for an operating system which is no longer supported by its vendor ;)

**Comment by kurayami6** [comment]
![Capture](https://user-images.githubusercontent.com/31968468/77330960-2bff3180-6d74-11ea-91a6-1c5e521a7ed5.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/77330977-328da900-6d74-11ea-84f6-4365403df1cf.PNG)

**Comment by stenzek** [comment]
Yeah, the sprites for the characters are incorrect (pattern to the right of the top framebuffer). Not sure where it's going wrong, but just use OpenGL in the meantime and I'll try to look at it when I have enough time to set up a win7 machine...

**Comment by stenzek** [comment]
https://github.com/stenzek/duckstation/issues/153
