### ISSUE TITLE
[Request] Controller axes separation/mirroring

### ISSUE THREAD

**Issue by AJB-Tech** [stenzek/duckstation#940]
Apologies if this already exists - there's a few different ways to word this issue but I couldn't find anything that matches what I have in mind.

To play some racing games (e.g. Gran Turismo 2) with smooth car acceleration, I tend to bind acceleration to the PS1's right analog stick, then bind the right trigger to the up-half of the analog, and the left trigger to the down-half. This can be a little fiddly as the two triggers are simply separate directions on the same axis and not actually distinct. 

Currently with Duckstation this isn't possible, as binding the right stick's movement to a trigger isn't adjustable, so pressing a trigger either has the no effect (as it tries to move the analog both up and down), or has the opposite effect to what's intended.

I believe other emulators currently have the ability to split or at least mirror the axes, so that I could for instance bind right stick up to the "positive" trigger axis and down to the "negative" axis so that it works correctly.

**Comment by CookiePLMonster** [comment]
What you are asking for would not be solved by separating axes, because ultimately the information sent to the game needs to be "merged" too. Effectively, with that setup you would not be able to press throttle and brake at once.

You should look into emulating a NeGcon controller since most racing games (Gran Turismo included) support it. You can map the I button to LT and II to RT, and get proper pressure sensitive throttle and brake this way.

**Comment by AJB-Tech** [comment]
I appreciate the response. Do you know how to either bind the other buttons correctly with the NeGcon, or at least use the keyboard at the same time? As most of the Sony controller buttons seem to be missing on the NeGcon so navigating the game's UI becomes a bit of a mess.

**Comment by CookiePLMonster** [comment]
I map the rest accordingly, so L/R go as LB and RB, and A/B as B/Y respectively. Games supporting NeGcon usually support navigating menus with it too so it's not an issue.

**Comment by AJB-Tech** [comment]
Thanks for the help, much appreciated. I'll mark this as closed now.
