### ISSUE TITLE
[BUG] Final Fantasy VIII clicking sound during intro FMV

### ISSUE THREAD

**Issue by jrt05** [stenzek/duckstation#941]
Final Fantasy VIII Disk 1 Intro FMV Music has clicking sound. Seems to be very fast clicking, maybe 10-20 clicks a second. Clicking only happens in right speaker.  Issue does not occur in Beetle psx. Issue sometimes doesn't occur, but mostly does.

CPU -  i5-8600K
Video - NVIDIA GeForce RTX 2070 SUPER
Sound - DELL SR2320L

Using latest build 0.1-1941-g790a1173 (master)

md5 of Disk 1 - 50d5b62e81b5369f18c8a145af716af9

**Comment by stenzek** [comment]
I'm not hearing this at all. You mean the FMV after selecting new game, right?

**Comment by jrt05** [comment]
Yeah, after selecting new game. Thanks.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/6a4a47fbdf67e974c27c7d8de7333ad48904e2c8

**Comment by jrt05** [comment]
Awesome, works great now.
