### ISSUE TITLE
.bin images not being detected in game list

### ISSUE THREAD

**Issue by kattjevfel** [stenzek/duckstation#943]
When adding a directory to the "Game List Settings", it successfully finds .cue sheets (along with its .bin files) and .img files, but not standalone .bin files. The majority of my games are in .bin (I should rename them, but that's irrelevant) and thus are not being detected.

I'd be grateful if standalone .bin images would be detected and added to the game list, or at least be given a reason why not.

**Comment by stenzek** [comment]
Working as intended. If I listed bin files in the game list, multi track games with one bin per track would repeat for every track.

Just create a cue, problem solved.
