### ISSUE TITLE
[Request] Cover Art Cache

### ISSUE THREAD

**Issue by RinMaru** [stenzek/duckstation#944]
Having High Quality cover art can cause the UI scrolling to lag until the list has been fully cached would it be possible to have DS build a cache of the cover art at load to eliminate the stutter like Dolphin does?

**Comment by stenzek** [comment]
It's already cached in memory after first load.

Can't say I've seen any stutter when scrolling but that was also off a nvme SSD. The only other option would be to include the cover in the game list cache...

**Comment by RinMaru** [comment]
its pretty bad on HDD i mean its not unmanageable but its definitely not a smooth experience

**Comment by stenzek** [comment]
This will basically mean storing the image in the game list cache and using additional memory at idle. I'm not sure how I feel about that, we're talking potentially hundreds of megabytes if not gigabytes of memory for users with large libraries.

**Comment by HeyItsLollie** [comment]
Don't store the high-quality image. Cache a version of the artwork that is vastly lower in image quality and resolution.

**Comment by Ninaadark18** [comment]
How i get automatically cover art for my games in the standalone emulator?

**Comment by andercard0** [comment]
> How i get automatically cover art for my games in the standalone emulator?

https://github.com/stenzek/duckstation/wiki/Adding-Game-Covers

**Comment by Ninaadark18** [comment]
> > How i get automatically cover art for my games in the standalone emulator?
> 
> atm there is no auto cover download for duckstation you might have to add them as the wiki below shows.
> https://github.com/stenzek/duckstation/wiki/Adding-Game-Covers

Thanks

**Comment by stenzek** [comment]
Covers are loaded asynchronously and cached in memory with a MRU list post UI revamp.
