### ISSUE TITLE
Settings to be Updated.

### ISSUE THREAD

**Issue by RinMaru** [stenzek/duckstation#948]
- **PowerSlave** SLUS-00102- Force Digital
**Note:** _OC to 300% to Achieve 60FPS. Not Extensively Tested_
- **Tomb Raider** SLUS-00152- Force Digital
- **Megaman** Legends SLUS-00603- Force Digital
- **Hexen** SLUS-00348- Force Digital, Disable Upscaling
- **Gex** SLUS-00042- Force Digital
- **Megaman x4** SLUS-00561- Force Digital
- **Road Rash** SLUS-00035- Force Digital
- **StarBlade Alpha** SLUS-00057- Force Digital
- **Spot Goes to Hollywood** SLUS-00014- Force Digital
- **Philsoma** SCUS-94403- Force Digital
- **Rampage World Tour** SLUS-00549- Force Digital
- **Soul Blade** SLUS-00240- Force Digital
- **Blood Omen Legacy of Kain** SLUS-00027- Force Digital
- **Die Hard Trilogy** SLUS-00119- Force Digital
- **Disrupter** SLUS-00224- Force Digital
- **Megaman 8** SLUS-00453-  Force Digital
- **R-Types** SLUS-00753- Force Digital
- **Guardian's Crusade**  SLUS-00811- Force Digital

**_Will be updated as more is tested_**

**Comment by stenzek** [comment]
Added in https://github.com/stenzek/duckstation/commit/0825bd1d2da39aea82b2ff740823b3e3c596d0ba
