### ISSUE TITLE
Clicking "Reset to default" in Advanced Settings crashes Duckstation.

### ISSUE THREAD

**Issue by Skynet19972029** [stenzek/duckstation#949]
![asdasdadad](https://user-images.githubusercontent.com/72090667/95598039-ce87b500-0a25-11eb-90d7-e9cec64d3c91.png)

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/907bba19c029342d2f8131a7ce338265995863ca
