### ISSUE TITLE
Multiple issues with demo disc that I'm not sure of the name of

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#95]
I picked it at random from Redump. They have it named "Rival Schools + Resident Evil 2  + Bloody Roar + Street Fighter EX Plus Alpha  + Mr Domino  + Victory Boxing 2 (France)" but on the title screen it's just called "Total Play Playstation 100%" In any case it doesn't show up in the list even though it's from Redump and in the same directory as every other game. Maybe because the name is too long?

![Capture4](https://user-images.githubusercontent.com/31968468/76630462-247da280-6594-11ea-8400-c7f3626fde1a.PNG)

![Capture3](https://user-images.githubusercontent.com/31968468/76630103-8be72280-6593-11ea-930e-8bec45e0aa99.PNG)

Second the BIOS music plays well into the first loading screen.

![Capture](https://user-images.githubusercontent.com/31968468/76630145-9c979880-6593-11ea-8f18-1f59227aad92.PNG)

Thirdly there's graphical garbage on the title screen

![Capture2](https://user-images.githubusercontent.com/31968468/76630179-ade0a500-6593-11ea-9c60-70cf73b642f8.PNG)

**Comment by stenzek** [comment]
Looks like https://github.com/stenzek/duckstation/issues/153 - the BIOS sounds continuing to play are a common issue with reverb.
