### ISSUE TITLE
Skullmonkeys objects keep disappearing

### ISSUE THREAD

**Issue by Lilly-98** [stenzek/duckstation#952]
![SLUS-00601_2020-10-10_10-59-56](https://user-images.githubusercontent.com/72661583/95658507-e5dba680-0ae8-11eb-87a0-b6b3a1786c53.png)
![SLUS-00601_2020-10-10_00-25-52](https://user-images.githubusercontent.com/72661583/95658525-0c99dd00-0ae9-11eb-8c38-22337558ccd4.png)
 

This started happening yesterday.

**Comment by stenzek** [comment]
Fixed with https://github.com/stenzek/duckstation/commit/fe25f005c25b7a2289de4cfa02f19090f1576935

**Comment by Lilly-98** [comment]
Thank you so much!
