### ISSUE TITLE
Kyuutenkai (Japan) // Black screen after the Memory Card selection screen

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#954]
After a report from a user on Discord & some verification on my side, I can confirm the game isn't displaying anything (black screen) after the Memory Card selection screen.

The music goes by and the CD-ROM is read in the background, playing the CDDA tracks.

All CPU modes & all Renderer modes have been tested before reporting.
Tested on 0.1-1969-g671033fd.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/902024d225e1488c7d5021a8937772dc31eee3dc

**Comment by Zet-sensei** [comment]
Confirmed, thanks.
