### ISSUE TITLE
Bilinear filtering on Android bug

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#957]
![Screenshot_20201011_083732_com.github.stenzek.duckstation.jpg](https://user-images.githubusercontent.com/4934209/95672462-45958880-0ba1-11eb-97da-07c0472f05c2.jpg)

Lots of transparencies? Looks curious though :)

Edit: can only reproduce with Vulkan. Works fine under OpenGL

**Comment by 6lackmag3** [comment]
Got this with OpenGL renderer and bilinear filtering.
How to reproduce: run SLUS-00923, press 'Select' while in-game.
GPU: Adreno 616

![re3_bug](https://user-images.githubusercontent.com/13922742/98123879-842e1280-1ec3-11eb-87e8-a931d9db622d.jpg)

**Comment by stenzek** [comment]
This is probably a driver bug, and with Tomb Raider at least, it works fine in Vulkan.

I'll be adding the "no edge filtering" variants of the filters to Android soon, which might work around the issue, but there's an easier fix, just use Vulkan ;)

**Comment by 6lackmag3** [comment]
Yes, Vulkan's fine but OpenGL is somewhat faster :)
Also, can you add a filter similar to 'Adaptive 2D smoothing' found in Beetle PSX HW? It works really nice with RE and Dino Crisis titles, smoothing out backgrounds, hiding grain and rough pixels.
A pair of screenshots for comparison:
Beetle PSX w/adaptive smoothing
![01_beetle](https://user-images.githubusercontent.com/13922742/98130776-aaf04700-1ecb-11eb-8b45-55193eb85fac.png)
DuckStation w/bilinear filtering
![01_duckstation](https://user-images.githubusercontent.com/13922742/98130786-b04d9180-1ecb-11eb-9410-e8076dea4c76.png)
Beetle PSX w/adaptive smoothing
![02_beetle](https://user-images.githubusercontent.com/13922742/98130811-b5124580-1ecb-11eb-845f-ab85e742fd99.png)
DuckStation w/bilinear filtering
![02_duckstation](https://user-images.githubusercontent.com/13922742/98130831-bcd1ea00-1ecb-11eb-913b-bc320ad1ff26.png)

PS: thanks for the amazing work you've done!

**Comment by stenzek** [comment]
Strange. Vulkan is much faster on my phone.

**Comment by stenzek** [comment]
Closing as it's an Adreno bug and not really fixable - if you must use the OpenGL renderer for some reason, don't use it with texture filtering.

**Comment by Richard-L** [comment]
This is the phone I have the problem on: https://www.gsmarena.com/huawei_mate_10_pro-8854.php

Doesn't look like it says Adreno anywhere. But I could be wrong.

**Comment by stenzek** [comment]
Ah, it could be the lack of dual source blending. Might be a way to get that in GLES, will have to check
