### ISSUE TITLE
[Libretro] Rename double option 'Mute CD Audio' to 'CD-ROM Read Speedup'

### ISSUE THREAD

**Issue by 6lackmag3** [stenzek/duckstation#964]
![ds_mute_cd](https://user-images.githubusercontent.com/13922742/95760801-1f144200-0cb4-11eb-84a8-58a1ef91146f.jpg)

**Comment by stenzek** [comment]
Fixed with https://github.com/stenzek/duckstation/commit/d1018abd5b913577f3b10b05cf065b1ac06ffd8c
