### ISSUE TITLE
Kitchen Panic (J) sound issues

### ISSUE THREAD

**Issue by diegoginard** [stenzek/duckstation#966]
<entry code="SLPS-01395" title="Kitchen Panic (J)" region="NTSC-J" compatibility="4">
    <compatibility>Graphical/Audio Issues</compatibility>
    <version-tested>0.1-1998-g43bafe1a</version-tested>
    <comments>Cda sound issues during gameplay</comments>
</entry>

**Comment by stenzek** [comment]
Can you provide more detail? What does "cda sound issues" mean?

**Comment by diegoginard** [comment]
Background music during the game is choppy and then stops playing

**Comment by stenzek** [comment]
Sounds fine to me? Looping at the end of the track is also fine.

Is it in a specific location in the game?

**Comment by diegoginard** [comment]
in the first stage

**Comment by stenzek** [comment]
Confirmed via Discord to be a dump issue.
