### ISSUE TITLE
Spyro 2 (Modded/hacked jumping)- Freeze when gliding.

### ISSUE THREAD

**Issue by Skynet19972029** [stenzek/duckstation#968]
This problem does not happen on previous versions of DS nor in other emulators.
Tried all 3 CPU modes.

I attached a differential patcher for the original rom "Spyro 2 - Ripto's Rage! (USA)"
You need the bin/cue inside the same folder as the patcher with the name of the files "SP2 Unicorngoulash's Hacked Edition V2.0" (doesn't matter what's writte on the cue, it will be patched too.) Wait a while and It will patch the files.

[SP2 Unicorngoulash's Hacked Edition V2.0 - Bin patcher.zip](https://github.com/stenzek/duckstation/files/5368054/SP2.Unicorngoulash.s.Hacked.Edition.V2.0.-.Bin.patcher.zip)

In case a log file is needed, please, tell me.

**Comment by stenzek** [comment]
Apparently this was fixed by yesterday's changes? If it's still happening please let me know and I'll re-open.
