### ISSUE TITLE
[Feature request] Option to autoload cheats

### ISSUE THREAD

**Issue by DonelBueno** [stenzek/duckstation#969]
It would be nice to have an option to autoload specific cheat files for each game, like what RetroArch does, but for the standalone version.

**Comment by Richard-L** [comment]
https://github.com/stenzek/duckstation/issues/907#issue-711196598

**Comment by DonelBueno** [comment]
@Richard-L In the way I'm proposing it won't depend on a save state file.

**Comment by stenzek** [comment]
It already exists. Save it as `<game title>.cht` and put it in the cheats subdirectory of your user directory.

**Comment by DonelBueno** [comment]
Wow, didnt know it was that simple. Sorry for the inconvenience.

**Comment by foxsevent** [comment]
I dunno about that formatting, basic PCSXR format works fine.

> 
[Infinite energy P1]
80173AAA 0080
[P2 No health		]
80174A6E 0000

Speaking of which a suggestion, could the automatic cheat loading be also set by game code? Similar to covers like so 
SCES-02101.CHT it would make things easier for most cheat packs use game codes and it's not that hard to change the files name slightly with something like bulk renamer,

**Comment by DonelBueno** [comment]
The formatting works fine if you load the cheat file manually, it even respects the "enable" or "disable" for each specific cheat code.

**Comment by foxsevent** [comment]
Then the issues is somewhere in the filename, try directly copying the title of the game from Duckstation game proprieties.

**Comment by DonelBueno** [comment]
That doesn't work either. The names were already the same anyway (I copyed them directly from the .cue files name)

**Comment by foxsevent** [comment]
Can you post the cheat file here? or the text inside at least, I will copy it and see if it works for me,

**Comment by DonelBueno** [comment]
https://pastebin.pl/view/24a83e6f

**Comment by stenzek** [comment]
That's a libretro format file. I don't use that garbage format for auto-saving/loading, but you can still import/load it.

Once you load it and enable a cheat, it should auto-save in PCSXR format with the appropriate filename.

**Comment by foxsevent** [comment]
Sorry for the late reply, all I can say triple check your filenames, even a single space can make a difference.
In my case your cheat file worked fine, copied it into a basic TXT file renamed it to match the game and changed the extension to cht pasted it into the cheat folder launched the game and it worked, it loaded the file and enabled the selected cheats.

**Comment by DonelBueno** [comment]
@foxsevent It autoloaded even using the libretro format I provided?

**Comment by foxsevent** [comment]
> @foxsevent It autoloaded even using the libretro format I provided?

Yup, auto loaded and worked.

**Comment by foxsevent** [comment]
> OMG, I'm dumb AF, the option "auto load cheat files" was unchecked, I had never seen it there before.

XD don't feel to dumb. none of us thought of that.

**Comment by DonelBueno** [comment]
> > OMG, I'm dumb AF, the option "auto load cheat files" was unchecked, I had never seen it there before.
> 
> XD don't feel to dumb. none of us thought of that.

I even searched for "cheats" on the settings.ini file, but it wasn't there before.
