### ISSUE TITLE
[Request] Dark theme 

### ISSUE THREAD

**Issue by HeyAlucard** [stenzek/duckstation#97]
I think it would be great for using at night

**Comment by stenzek** [comment]
While we could explicitly style it with QStyleSheets, but it's probably better to wait for official Qt support, e.g. https://bugreports.qt.io/browse/QTBUG-72028

**Comment by mrdeathjr28** [comment]
> I think it would be great for using at night

SDL mode is very good (dark color)

**Comment by stenzek** [comment]
Two dark theme options added as of https://github.com/stenzek/duckstation/commit/55a2c7309799097f4dc2e86f4a9ec62e2e839621

One based on QDarkStyleSheet, and the other based on the Fusion theme. Personally I prefer the Fusion theme.
