### ISSUE TITLE
Bluetooth controller bug

### ISSUE THREAD

**Issue by saintbepis** [stenzek/duckstation#970]
When playing any game on a Bluetooth controller the screen brightens once you press a button making the screen slighter more brighter, my guess is that the controller is placing a selection overlay during game play.

(Before pressing a button on the controller to move)
![Screenshot_20201012-234032_DuckStation.png](https://user-images.githubusercontent.com/42784790/95826772-acbd5500-0ce7-11eb-94d5-71444674afc3.png)

(After pressing a button on the Bluetooth controller to move) 
![Screenshot_20201012-235111_DuckStation.png](https://user-images.githubusercontent.com/42784790/95826830-c2cb1580-0ce7-11eb-9cb5-3a381a683113.png)

**Comment by stenzek** [comment]
Should've been fixed with https://github.com/stenzek/duckstation/commit/d130fc94651161312cf3381b851428f8f68c37cc, please let me know if it's still happening.
