### ISSUE TITLE
Please release a new android version to test it :)

### ISSUE THREAD

**Issue by HJMBgit84** [stenzek/duckstation#971]
It seems that have been some new improvements in the emulator, so I think we will love to test new Android versions. :)

**Comment by stenzek** [comment]
Play Store updates require reviews and processing time, so I can't push every build to the Play Store. Usually I wait until I have a few changes to add together.

If you want to test the latest version before it is pushed to the Play Store, you can sideload the apk listed here: https://github.com/stenzek/duckstation/releases

**Comment by HJMBgit84** [comment]
I have an additional question sorry if I am bothering, Why I just see one release on github in the releases section, I usually check github for a new apk releases every day but I just see pre-release 1.0 even when We see that changes are being made in the code. So I just want to understand please.

**Comment by stenzek** [comment]
The actual version number isn't shown on GitHub because it works purely off tags.

0.1-NNNN is the "number of revisions since 0.1 was released".

**Comment by HJMBgit84** [comment]
Ohh ok ok now I got it :) thanks for clarifying, this emulator is the best for graphics on psx thanks and keep doing your great job, thanks :)
