### ISSUE TITLE
OpenGL es not working 

### ISSUE THREAD

**Issue by saintbepis** [stenzek/duckstation#974]
I'm using a s20 ultra on the android 11 beta and I get a pop up saying failed to create or configure audio stream and makes the audio not play, cubeb does work though.

**Comment by stenzek** [comment]
Interesting, it seemed to work on Android 11 in the emulator and on one of the phones I tested. Just keep using cubeb for now I guess.

**Comment by stenzek** [comment]
Seems I forgot to add a CMake module. The latest build should hopefully fix OpenSL ES.
