### ISSUE TITLE
[Enhancement] Ability to remap controller buttons

### ISSUE THREAD

**Issue by msmigiel** [stenzek/duckstation#977]
Environment:
- Duckstation version unknown (latest version in Google Play store as of 10/15/20 - please consider adding an About box)
- Android 10
- Samsung Galaxy S10e

Request:
Please add the ability to remap buttons for external controllers. For some reason, my controller (an 8bitdo FC30 Pro) has the face buttons (X, O, etc...) mapped backwards and I cannot find a way to change them.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/0aa3b6b3991d378709326ee553ea4e473064c3c6 (preview build only for now).
