### ISSUE TITLE
Vanark (U) freeze in the fist mission

### ISSUE THREAD

**Issue by diegoginard** [stenzek/duckstation#978]
<entry code="SLUS-01035" title="Vanark (U)" region="NTSC-U" compatibility="3">
    <compatibility>Crashes In-Game</compatibility>
    <version-tested>0.1-2039-g95f78216</version-tested>
    <comments>freeze on first mission after training</comments>
</entry>

**Comment by Zet-sensei** [comment]
Can't reproduce after some tries on my side.
I can go to ACT 2 without any problem.

Tested with 0.1-2108 on both Interpreter & Recompiler Modes / SW renderer.

**Comment by stenzek** [comment]
Thanks for checking!
