### ISSUE TITLE
Resolution error with Wayland

### ISSUE THREAD

**Issue by DarkSwan86** [stenzek/duckstation#979]
Hi @stenzek !

I'm trying to use Duckstation on Manjaro KDE with a wayland session but everytime i try to start a game, DS gives me these errors:
![wayland error](https://user-images.githubusercontent.com/24975273/96189036-146ddd00-0f40-11eb-846e-c8bca6fd610a.png)
![wayland error 2](https://user-images.githubusercontent.com/24975273/96189035-13d54680-0f40-11eb-93a5-b036082a0f7c.png)

If I use DS on a X11 session, it works fine.

I'm using the very last compiled version from source (95f7821). 

System specs: 

Operating System: Manjaro Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.15.1
Kernel Version: 5.4.67-1-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Core™ i3-2350M CPU @ 2.30GHz
Memory: 5.5 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 3000 (Mesa 20.1.8)

If you need more informations or logs, just ask! :)

**Comment by stenzek** [comment]
Did you enable Wayland support? (`-DUSE_WAYLAND=1` in the cmake command line)

I probably should enable it by default, it's not used if you're using X11, the only reason I haven't is because the appimage packager won't include the wayland Qt plugin for some reason, so it's not useful there.

**Comment by DarkSwan86** [comment]
Ok now it works fine, please take in consideration the idea to add that line by default. :)

But now there is another problem, when i start a game i can hear the sound but nothing appears. If i press fullscreen the game appear but in a small window. My laptop resolution is 1366x768. Look at the screenshot below for the problem.
![Screenshot_20201016_104406](https://user-images.githubusercontent.com/24975273/96237421-93ddc980-0f9d-11eb-843d-c1ee3cdc4560.png)

**Comment by stenzek** [comment]
Hm, maybe it's an issue with kwin.. it works fine on gnome-shell.

Try disabling render-to-main-window.

**Comment by DarkSwan86** [comment]
Ok, disabling render-to-main-window now shows a detached window but still i can't go fullscreen. If i press Fullscreen the windows remain the same size.

**Comment by stenzek** [comment]
I'm not sure there's all that much I can do about that. The fullscreen state of the window is entirely controlled by Qt, so if your compositor isn't allowing it for reason, it could be a Qt bug or a KWin bug...

I'll look into it anyway but this might be a "can't fix". Despite being around for how many years now, wayland still seems to be a mess...

**Comment by DarkSwan86** [comment]
Thanks! Take your time, i'll try to dig around on the web if something popup about this problem.

**Comment by stenzek** [comment]
Window resizing should be fixed with https://github.com/stenzek/duckstation/commit/e1473274592432ac72f3e94ef24cb8e1152a4d06

Still not sure what's wrong with it rendering to the main window, could be a Qt issue as the game list breaks when you stop emulation too :/

**Comment by stenzek** [comment]
If this is still happening, it's probably a qt/compositor issue. Might be fixed when move Linux builds to Qt6
