### ISSUE TITLE
Couple bugs

### ISSUE THREAD

**Issue by sapfel93** [stenzek/duckstation#980]
Hello there. I'm running the latest version of Duckstation on Google Play with the Snapdragon 855 Samsung Galaxy S10+. So far I think the emulator has great potential but I've noticed some bugs. First of all, with resolutions above 3x, the FMV's get corrupted. (I used Chrono Cross as an example).

![Screenshot_20201016-214452_DuckStation](https://user-images.githubusercontent.com/26125401/96326085-c7e7d780-0ffb-11eb-9703-53a479430a74.jpg)

Second of all, when unpausing the game or starting it from the menu, there are moments when the music for a second or two become high-pitched and wrong. This also happens commonly with resolutions above 3x. I hope the format is correct for reporting this and I hope the emulator gets better.

**Comment by stenzek** [comment]
> First of all, with resolutions above 3x, the FMV's get corrupted. (I used Chrono Cross as an example).

Seems like a driver bug. Does it happen in both OpenGL and Vulkan?

> Second of all, when unpausing the game or starting it from the menu, there are moments when the music for a second or two become high-pitched and wrong. This also happens commonly with resolutions above 3x. I hope the format is correct for reporting this and I hope the emulator gets better.

Disable video sync/vsync. Android doesn't handle the mismatch in refresh rate as well as Windows does.

**Comment by sapfel93** [comment]
Issue happens on both and disabling vsync didn't fix the audio issue.

**Comment by stenzek** [comment]
No idea then, my phone had the audio issue (happens when frames drop) and it's fine with vsync disabled.

**Comment by sapfel93** [comment]
The audio bug seems to happen when i go into settings, it causes the music to glitch out for about 1-2 seconds and then mostly corrects itself.

**Comment by stenzek** [comment]
Settings in the game or settings in the app?

**Comment by sapfel93** [comment]
Oh sorry. Settings in the app.

**Comment by stenzek** [comment]
That's kinda expected. It takes a brief moment for everything to synchronize back up after pausing/resuming.

Same deal with pulling open the system UI - it forces a display resize which takes longer than a frame, so things get resampled briefly.

**Comment by stenzek** [comment]
FMV issue should be fixed in the latest play store build (at least it is for me).
