### ISSUE TITLE
Pepsiman soft lock?

### ISSUE THREAD

**Issue by psyalemao** [stenzek/duckstation#981]
Hello,

I would like to report what apparently seems to be a soft lock on the game. The game freezes after a part of a level, I attached a savestate.

**Comment by stenzek** [comment]
Please don't post save states, they contain copyrighted content including BIOS/game code and assets.

Which level does it freeze in? Pepsiman was fine the last time I checked.

**Comment by psyalemao** [comment]
Sorry didn't know about the copyright with savestates.

Stage 4 Level 1 that is freezing, near the end. I checked my game dump and it is matching the checksums from redump.

**Comment by stenzek** [comment]
Can you reproduce it reliably? It seems fine here on free play for stage 4/level 1, although I had to use cheats to finish the level :P

**Comment by psyalemao** [comment]
I was using cheats too lol. Could be a cheat or a config settings. I will mess with the cheats or settings. I uploaded a log.
[duckstation.log](https://github.com/stenzek/duckstation/files/5398406/duckstation.log)

**Comment by Zet-sensei** [comment]
After a discussion with a user on Discord earlier today, the same issue appeared. 
The user disabled entirely the PXGP options on his side.

So, we most probably need to add (at least) some lines to gamesettings.ini for bypassing the problem in the future.

```
# SLPS-01762 (Pepsiman (Japan))
[SLPS-01762]
DisablePGXPCulling = true
```

**Comment by stenzek** [comment]
Thanks @Zet-sensei , added in https://github.com/stenzek/duckstation/commit/b1c78d8bea94b159baa3abf2cd4adced5226d33f
