### ISSUE TITLE
Syphon Filter (Spain) PAL working on NTSC-on-PAL mode by default, causing black screens on pause

### ISSUE THREAD

**Issue by Jenmet-cy** [stenzek/duckstation#982]
I've found a bug with Syphon Filter's Spanish (SCES-01914) variant. After entering pause, the game stays on a black screen, but the emulator keeps running as seen in the trace. The only change made to the emulator settings was enabling Fast Boot, increasing resolution and enabling widescreen hacks. The game is compressed using CHDMAN, but it happens on the original .bin/.cue, too.
![DS](https://user-images.githubusercontent.com/52474680/96346367-ce189b00-1071-11eb-904d-9aa132d36086.png)
[duckstation.log](https://github.com/stenzek/duckstation/files/5395908/duckstation.log)

**Comment by Jenmet-cy** [comment]
I restored DS's default configuration, and the same still happens. To reproduce, in the first mission enter The Place, kill the first guy that appears on your left, and pause here: 
![DS](https://user-images.githubusercontent.com/52474680/96349758-1a6ed580-1088-11eb-8df2-71cd6d400a0a.png)

[duckstation.log](https://github.com/stenzek/duckstation/files/5396196/duckstation.log)
This log was took with the default config on "Trace" level.

**Comment by Jenmet-cy** [comment]
After the last build, I can no longer reproduce the issue in the same place. I'll keep testing, though.

**Comment by Jenmet-cy** [comment]
I've made a test with another copy of the game (The English European version). The same thing happens.
[duckstation.log](https://github.com/stenzek/duckstation/files/5417204/duckstation.log)
Someone should test if this also happens in the US version.

**Comment by stenzek** [comment]
Can't seem to reproduce it on a couple of tries here.

**Comment by Jenmet-cy** [comment]
What version(s) did you test?

**Comment by stenzek** [comment]
SCES-01910 and SCUS-94240

**Comment by Jenmet-cy** [comment]
I'll retest with the European version in the next days, since I can't reproduce it again now, but the Spanish version keeps hanging in the exact same place as before.

**Comment by Jenmet-cy** [comment]
Tested the European version in the same place. The same behaviour happens. Here's a GIF to illustrate it better, and a new log.
[duckstation.log](https://github.com/stenzek/duckstation/files/5468445/duckstation.log)


![ezgif com-gif-maker](https://user-images.githubusercontent.com/52474680/97769846-078ae500-1b0d-11eb-899c-696f304b19f7.gif)

**Comment by stenzek** [comment]
Are you using any enhancements?

**Comment by Jenmet-cy** [comment]
I restored the default configuration again on DuckStation, and it seems that the black screen triggered in the European version is caused due to me enabling Force 60Hz timings. However, the issue persists in the Spanish version without enhancements.

**Comment by stenzek** [comment]
I can't tell if PGXP is enabled in that video, but make sure it's disabled, and you're not using disc read speedup.

**Comment by Jenmet-cy** [comment]
The GIF is from the European version. The bug from that one was caused due to me enabling the Force 60Hz option.

The one with the issue now is the Spain version, on default (no enhancements) configuration.

**Comment by stenzek** [comment]
@Zet-sensei sorry for the ping, do you have the Spanish version of Syphon Filter and are you able to confirm this bug?

**Comment by Jenmet-cy** [comment]
I am talking out of ignorance, so this probably doesn't have anything to do with the bug, but the Spain version works on 60FPS by default. Spain is a PAL region, and PAL60 wasn't really a thing on the PSX days. Maybe it's related to that?

**Comment by stenzek** [comment]
It should be 50fps. Make sure you're not overriding the option somewhere.

**Comment by Jenmet-cy** [comment]
![Captura de pantalla (11)](https://user-images.githubusercontent.com/52474680/97772150-f51ba600-1b22-11eb-9f07-52f8cae1908d.png)
I restored my config one more time to check. It runs at 60FPS by default. Strange...

**Comment by stenzek** [comment]
Make sure you don't have game overrides set for it. Uncheck apply game settings in general to confirm

**Comment by Jenmet-cy** [comment]
Apply per-game settings disabled before booting the game. Still running at 60FPS.
![Captura de pantalla (12)](https://user-images.githubusercontent.com/52474680/97780680-d63e0380-1b64-11eb-877b-26d69e856484.png)

**Comment by stenzek** [comment]
Open debug settings (need to enable it in advanced), check show GPU state and scroll down, and look at the "Clock" setting. If the game is running incorrectly it will say "NTSC-on-PAL".

**Comment by Nucleoprotein** [comment]
It was long time ago and i'm not sure but i think i got similar problem in Syphon Filter EU Demo in this place on real HW - but i can unpause and it works fine, only pause menu was black, maybe game bug? I think this need HW test.

**Comment by Jenmet-cy** [comment]
@stenzek Yes, it does say NTSC-on-PAL on GPU state. But I have deleted my config and checked that per-game settings are disabled. There shouldn't be any settings override. What could be the issue?

**Comment by stenzek** [comment]
No idea. I even tried the PAL version with a NTSC BIOS and it still ran in PAL mode for me. Not much I can do about it since I can't reproduce it, maybe try with a second copy of the emulator in portable mode (so it doesn't use _any_ of your config), and boot the game directly.

**Comment by Jenmet-cy** [comment]
Tested on portable mode, with NOCASHPSX free BIOS (to check if it is a BIOS dump issue), still playing at 60FPS. Strangely enough, NOCASH BIOS starts on PAL-on-PAL mode, then when the game boots it switches to NTSC-on-PAL mode.

**Comment by Nucleoprotein** [comment]
Dump is valid, non patched ect.? http://redump.org/disc/19089/

**Comment by Jenmet-cy** [comment]
I'll check the checksums later, as I don't have my PC right now. But I tested the game on ePSXe, and it works at 50 FPS there, without the pause issue.

**Comment by stenzek** [comment]
Can't reproduce with a valid dump (MD5 45b5b67e6a472039a794ff40ea3215d4) and 5502 BIOS. Game runs at 50fps and does not hang.

**Comment by Jenmet-cy** [comment]
Yes, I can confirm it. I did a redump (had to borrow a portable CD/DVD player), and the game now works properly.
