### ISSUE TITLE
Save state is incompatible: expecting version 42 but state is version 40.

### ISSUE THREAD

**Issue by gilbertoferreira** [stenzek/duckstation#983]
Hi there

I am running VoidLinux and Retroarch 1.9.0 and using Duckstation to run some PS1 games.

(Duckstation is pretty much stable and fast then others cores...)

Previously I was running Kubuntu Linux and running retroarch from PPA, then I was able to load the save state normally.

But now, when I tried I get this message:

[   11.8466] E(ReportError): Save state is incompatible: expecting version 42 but state is version 40.

Is there any way to perform some save state converter from version 40 to the version 42???
Thanks

**Comment by stenzek** [comment]
Working as intended - save states are not intended to be compatible between versions.

You can use the old version, save your game to memory card, and then upgrade to the new version and create a new save state. The last build for version 40 is here: https://github.com/stenzek/duckstation/actions/runs/279487058

As an aside, I have the ability to auto-upgrade old saves with any future bumps to the state version, so hopefully this will be pretty rare in the future.
