### ISSUE TITLE
Problems updating duckstation

### ISSUE THREAD

**Issue by lauramachts** [stenzek/duckstation#985]
I downloaded the latest version of the emulator and when i open it shows a window with a update but everytime i click to update, the emulator says it was updated successfully but then pops up the same window again telling me to update to the same version. it's like the update never installs, even duckstation telling me it was updated

**Comment by DonelBueno** [comment]
You probably renamed the .exe of DuckStation.

**Comment by strangrish** [comment]
> 
> 
> You probably renamed the DuckStation's .exe.
> 
> If you want to keep it with another name, close the emulator after it is updated, delete the old .exe and rename the new .exe accordingly.

I did that lol thanks

**Comment by stenzek** [comment]
So the issue was just the executable name?

The updater isn't very "smart", it uses the version embedded in the exe, downloads the new build and basically extracts it over the top. So this would explain why it wasn't "updating".

**Comment by strangrish** [comment]
> 
> 
> So the issue was just the executable name?
> 
> The updater isn't very "smart", it uses the version embedded in the exe, downloads the new build and basically extracts it over the top. So this would explain why it wasn't "updating".

Yeap, it was more simple that i was imagining. I just created a shortcut of the exe and changed the name, works fine.

**Comment by stenzek** [comment]
Great, glad to hear you sorted it out.
