### ISSUE TITLE
Emulation freezes, when disconnecting Bluetooth-Soundbox

### ISSUE THREAD

**Issue by GitToTheHub** [stenzek/duckstation#986]
When disconnecting a Bluetooth-Soundbox during emulation, the emulation freezes. The Gui is still active and respond by e.g. hovering the menu items there. But when using the menu-action system > exit, the Gui freezes too. The only solution was to kill the program.

Version used: Latest Master (0.1-2604-g7755e238)
OS: Windows 10 64-Bit Build 2004

**Comment by stenzek** [comment]
Try using SDL instead of cubeb for the audio backend.

**Comment by GitToTheHub** [comment]
Thank you, with SDL it's working. What's the difference between SDL and Cubeb?

**Comment by stenzek** [comment]
cubeb in theory has lower latency. Sounds like it's a bug with cubeb itself, although it may have already been resolved upstream, it's been like a year since I've updated it...

**Comment by GitToTheHub** [comment]
Thank you, I understand. I will use SDL and see if it will lag.
You do a very good job with the emulator, thank you! :)

**Comment by GitToTheHub** [comment]
Maybe it's worth to open an issue for cubeb here?

**Comment by stenzek** [comment]
I probably should update to the latest version before we do that.. :)

**Comment by GitToTheHub** [comment]
Ok :)

**Comment by stenzek** [comment]
cubeb has been updated, although I didn't see any major changes, so it might not change anything.

**Comment by GitToTheHub** [comment]
Yes, unfortunately it doesn't fixed the issue. I tried it with the latest master and the emulation still freezes after disconnecting the bluetooth soundbox. But with SDL everything is fine and didn't noticed any lag in sound. I tested it for one week with SDL.

**Comment by stenzek** [comment]
It's a bit difficult to report the bug to cubeb upstream without a call stack.

Eventually I'll add a crash reporter and we can figure out what's causing this. Unless you have Visual Studio installed and feel like compiling yourself :)

**Comment by GitToTheHub** [comment]
Yep, this is true. Without a call stack, it's hard to debug.
Is there no log option i can enable to send you a log with the exception?
Currently I didn't setup Visual Studio for DuckStation. If I have a lot of time and there is no other option, i can maybe do it 😄
________________________________
Von: Connor McLaughlin <notifications@github.com>
Gesendet: Montag, 26. Oktober 2020 14:54
An: stenzek/duckstation <duckstation@noreply.github.com>
Cc: Manuel Beck <manuelbeck87@outlook.de>; Author <author@noreply.github.com>
Betreff: Re: [stenzek/duckstation] Emulation freezes, when disconnecting Bluetooth-Soundbox (#986)


It's a bit difficult to report the bug to cubeb upstream without a call stack.

Eventually I'll add a crash reporter and we can figure out what's causing this. Unless you have Visual Studio installed and feel like compiling yourself :)

**Comment by stenzek** [comment]
If this is still happening, please upload the crash dump and I can investigate.
