### ISSUE TITLE
Legacy of Kain Soul Reaver CHD compression issue.

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#987]
Game works fine as clean CUE/BIN but if compressed to CHD it soft locks near the beginning after you pass the first door in the game and encounter the first vampires, a cut scene should play but instead it soft locks.

**Comment by stenzek** [comment]
Sounds like a dump issue - make sure the hash matches in game properties.

**Comment by foxsevent** [comment]
> Sounds like a dump issue - make sure the hash matches in game properties.

Hashes matches.
![Bez tytułu](https://user-images.githubusercontent.com/64225743/96445877-e246ce80-1210-11eb-86df-8c8099b764b7.png)

**Comment by stenzek** [comment]
No idea then, seems fine here, but not sure if I was playing up until the right point.

**Comment by foxsevent** [comment]
Here's a savestate if that helps, and it is near the beginning, but with all the cut scenes it can take 15-20min to get there, if you fast forward it 5min, it's shortly after you first time enter the material realm, you jump over a pool of water and the aforementioned door  cut scene and softflock.
[SLUS-00708_1.zip](https://github.com/stenzek/duckstation/files/5401665/SLUS-00708_1.zip)

**Comment by stenzek** [comment]
Please don't post save states, they contain copyrighted data.

Could be disc timing related I guess...

**Comment by Nucleoprotein** [comment]
PAL version?
https://problemkaputt.de/psx-spx.htm#cdromprotectionlibcrypt
Nasty LibrCrypt: http://redump.org/disc/1177/

**Comment by foxsevent** [comment]
> PAL version?
> https://problemkaputt.de/psx-spx.htm#cdromprotectionlibcrypt
> Nasty LibCrypt: http://redump.org/disc/1177/
> As NoCash says, it hangs in that place, when you encounter first vampires if you not have correct sub data.
> 
> @stenzek
> Where I can see TTY Output?

Nah NTSC US in my case, as far as im aware it's just a random bug, quick restart fixes it, thou if you save to memory card before this bug happens it corrupts the save as on that save it always will happen.
It's a weird streaming issue when the game can't stream the data it needs.

**Comment by foxsevent** [comment]
> Please don't post save states, they contain copyrighted data.
> 
> Could be disc timing related I guess...

Sorry about that, how about memory card files are those ok to post? If not the again sorry please delete, but on the first card load Soul Reaver A then just keep moving forward until you pass the first wooden door.
Here's also a screenshot of the glitch, I also noticed that the two vampires that should be in that room aren't there.
[Desktop.zip](https://github.com/stenzek/duckstation/files/5465836/Desktop.zip)
![SLUS-00708_2020-10-30_15-48-45](https://user-images.githubusercontent.com/64225743/97720165-3763c980-1ac8-11eb-841b-455e5161e2d2.png)

**Comment by stenzek** [comment]
Yep, memory cards are fine.

**Comment by rtissera** [comment]
We would need chman -info on the CHD file to see how it's encoded.
Probably related to subcode handling as libcrypt uses that if my memories are correct.

**Comment by Nucleoprotein** [comment]
Wait, you can include sbi in CHD?

**Comment by rtissera** [comment]
I don't think so, probably needs .sbi file aside and handling it.

**Comment by Nucleoprotein** [comment]
But autor is using NTSC USA so no LibCrypt there, strange.

**Comment by Shideravan** [comment]
I'm using a good dump of the original game in CHD with all the subsectors. Is playing correct for me as expected and passing this part in the last Duckstation version (.1-2499-g770dd5a6). Probably is error with your dump or something that already been solved.
@stenzek I think you can close it now :)
![image](https://user-images.githubusercontent.com/12163923/101562903-09b34f80-39a7-11eb-8e00-6b1e0014829e.png)

**Comment by Shideravan** [comment]
Also @foxsevent try to check the hashes if yours is the same as mine. If don't is, you can be sure that you disc image is not a good dump
![image](https://user-images.githubusercontent.com/12163923/101563152-834b3d80-39a7-11eb-9c77-0108949c630e.png)

**Comment by foxsevent** [comment]
> Also @foxsevent try to check the hashes if yours is the same as mine. If don't is, you can be sure that you disc image is not a good dump
> ![image](https://user-images.githubusercontent.com/12163923/101563152-834b3d80-39a7-11eb-9c77-0108949c630e.png)

If you were to read the whole thread you would see that I posted my dumps hash and it's the same.

We all kinda forgot about this thread, it's still unknown what caused this bug but it is a random bug that happened once and just persisted on the save file, that's why it kept happening to me, I was loading up a broken save file, starting a fresh new game fixed everything.

So I close this.
