### ISSUE TITLE
DuckStation App-Crash on Windows 10 (it won't even start)

### ISSUE THREAD

**Issue by Mohsen865** [stenzek/duckstation#988]
I tried both _Qt_ **and** _SDL_ **on** _Windows 10 Version 1909_ but it doesn't work... I tried to run the executable using the cmd but still no luck. The command window shows something like an error message when I try to run the Qt fronted:

![DuckStation](https://user-images.githubusercontent.com/12261908/96523598-f9260900-1282-11eb-80e5-789ace760302.png)

![DuckStation](https://user-images.githubusercontent.com/12261908/96526917-c0d6f880-128b-11eb-82c6-2b0a27f3042f.gif)

**Comment by stenzek** [comment]
I wonder if it's crashing in SDL due to a controller, because I can't think of much else which would break that early in initialization.

Try dropping this settings.ini in the directories with the executables (it has the controller backend disabled).

[settings.zip](https://github.com/stenzek/duckstation/files/5405717/settings.zip)

**Comment by Mohsen865** [comment]
### It worked! 😮
Thank you very much...
Now the application is running!
It starts with XInput but crashes as soon as I switch to SDL.
Wish it had DInput as well... Lol
I'll test other stuff at a later time...
**Thanks again** 🙏

![controller](https://user-images.githubusercontent.com/12261908/96534169-0f8c8e80-129c-11eb-93a8-1374c95115ba.png)

**Comment by stenzek** [comment]
No plans to add DInput, it's a deprecated API. SDL supports DInput controllers anyway.

If I had to guess I'd say there must be some driver causing SDL to crash.. I've seen drivers for headsets causing it to take a very long time to start before, but not crashing.
