### ISSUE TITLE
RetroArch core segfaults in software mode

### ISSUE THREAD

**Issue by vanfanel** [stenzek/duckstation#990]
Hi!
After building latest GIT version as a RA core, I have found out that setting the software renderer causes the duckstation core to segfault on start.
Is that known/expected?

Also, OpenGL renderer on the Pi4 (which is GLES 3.1, no working Vulkan driver yet) seems to be pretty much slow and Tekken 3 demo mode shows a lot of glitches.
Is that also expected? Using latest stable MESA (2.20.1).

**Comment by dankcushions** [comment]
tekken 3 + gles 3.1 works great for me on libretro core + pi4 - full speed, no glitches, although i am a few commits behind master.

note that i had to make some changes to RA so it would get the right gles context: https://github.com/libretro/RetroArch/pull/11181

**Comment by vanfanel** [comment]
@dankcushions Oh my, so RA isn't able to select the right context... That's bad. Why won't they merge your PR? I just don't get git. It was very easy for me to get things merged in the past.

**Comment by vanfanel** [comment]
@dankcushions 

It seems that RetroArch is able to detect GLES 3.1 here, from runing with the -v parameter I can see:
```

[INFO] [GL]: Vendor: Broadcom, Renderer: V3D 4.2.
[INFO] [GL]: Version: OpenGL ES 3.1 Mesa 20.2.1.
[INFO] [GL]: Using ARB_sync to reduce latency.
[INFO] [GL]: Using resolution 1360x768
[INFO] [GL]: Default shader backend found: glsl.

```

But how can I see what GLES 3 version is DuckStation using?
Tekken3 is not fullspeed here, shows audio gaps.

**Comment by dankcushions** [comment]
that's just the GL driver info - that's not used to determine GLES version support (although you technically could, but not sure if it would work for all drivers/platforms).

the GLES version support is determined in cores via a call to libretro API `RETRO_ENVIRONMENT_SET_HW_RENDER` - i show the issue here: https://github.com/libretro/RetroArch/issues/11143

if you look in your verbose log, you should see something like:
```
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting OpenGLES3.2 context.
```
that should fail, but instead it succeeds because (without my PR) retroarch compiles with `HAVE_OPENGLES3` will return ok when you request any GLES 3.x context, regardless of what the hardware supports.

**Comment by vanfanel** [comment]
@dankushions How are you building RA with GLES3 support?
My understanding is that I need to pass all these to the configure script. Can you please confirm this is right?:
`--enable-egl --enable-opengles --enable-opengles3 --enable-opengles3_1 --enable-opengles3_2`

**Comment by dankcushions** [comment]
i also have
`--disable-videocore --enable-kms --enable-egl --disable-vulkan --disable-wayland` but i can't be sure as i go via retropie's build scripts. obviously you will need my PR for the --enable-opengles3_* stuff to work.

**Comment by vanfanel** [comment]
@dankcushions Yes, I have your PR already, and also `--disable-videocore --enable-kms --enable-egl --disable-vulkan --disable-wayland`.
But what I mean is: Are `--enable-opengles --enable-opengles3 --enable-opengles3_1 --enable-opengles3_2` all needed, or just `--enable-opengles  --enable-opengles3_2` should be enough?

**Comment by dankcushions** [comment]
--enable-opengles3 and --enable-opengles3_1 is what you want. you don't want --enable-opengles3_2 as pi4 doesn't support it. not sure if --enable-opengles is needed.

**Comment by vanfanel** [comment]
@dankcushions Understood. What version of MESA are you using? I would like to replicate your setup as much as possible.

**Comment by dankcushions** [comment]
https://pastebin.com/JUzR0L6D
```
[INFO] [GL]: Vendor: Broadcom, Renderer: V3D 4.2.
[INFO] [GL]: Version: OpenGL ES 3.1 Mesa 19.3.2.
```

**Comment by vanfanel** [comment]
Ok, building RA with your PR and the `--enable-egl --enable-opengles --enable-opengles3 --enable-opengles3_1` configure options, games like Tekken 3 are almost fullspeed, bu there are small audio gaps sometimes.
Are you overclocking your Pi? It's almost there...

**Comment by dankcushions** [comment]
i did notice one drop... i wonder if it's an I/O thing as I'm running from an ancient USB thumb drive. there's some cd-related core options that could help.

i'm not overclocking but i do use `dtoverlay=vc4-kms-v3d-pi4` to enable pure kms, and `hdmi_enable_4kp60=1` (i don't run in 4k but i believe this overclocks the core and gpu slightly, regardless).

i would like to try standalone as it should be a little bit faster without the RA overhead. i need to create a retropie build script for it...

**Comment by vanfanel** [comment]
@dankcushions I am not using dtoverlay=vc4-kms-v3d-pi4 but dtoverlay=vc4-kms-v3d, as I understand latest kernels use vc4-kms-v3d simply, without the pi4 part, and it works on Pi3 & 4 equally.

Thanks for the `hdmi_enable_4kp60=1` hint!

About the option to improve i/o impact, I think you mean the thread for CD reading.
Anyway, this still doesn't explain why I see no background in Soul Blade's character selection menu.

**Comment by dankcushions** [comment]
> Anyway, this still doesn't explain why I see no background in Soul Blade's character selection menu, or those massive errors in Tekken 3.

yeah, i understand this is related to precision issues with the pi4's mesa driver. this also causes issues in yabause: https://github.com/devmiyax/yabause/issues/737

i am sure mesa/the pi dev team could fix, but we need to identify the specific issue to log it...

**Comment by vanfanel** [comment]
@dankcushions Maybe software mode would be a better solution for now on the Pi4.
Does DuckStation software renderer work for you?

**Comment by stenzek** [comment]
Closing based on discussion in #861.
