### ISSUE TITLE
Scanning on Android crashes due to bad dumps / too many images

### ISSUE THREAD

**Issue by RinMaru** [stenzek/duckstation#993]
Duckstation doesn't seem to like allot of games in a game directory on Android. I have Android 6.0 LG V990

Have Duckstation installed on internal storage and games off an SD and once selecting it Duckstation crashes after 2 seconds.

**Comment by stenzek** [comment]
I've seen a few crashes on the play store console caused by bad dumps. This is likely the issue.

I'm fixing them as I see them.

**Comment by RinMaru** [comment]
These arnt bad dumps the bin,cue converted to CHD. Before hand were checked against redump crc

**Comment by stenzek** [comment]
Does the latest build make any difference here? I've moved scanning to a worker thread so it doesn't lock up the UI thread, and added a progress bar.

**Comment by RinMaru** [comment]
i havent bothered testing with all my games on so ill close this and reopen if its an issue still when i get around to it
