### ISSUE TITLE
PlayStation 3 (PowerPC) Port?

### ISSUE THREAD

**Issue by SpaceAgeHero** [stenzek/duckstation#994]
Would it be possible to provide a version of this emulator for PS3?
Since RetroArch is available on PS3, maybe just a core would be possible.

Could it be compiled with [PSL1GHT](https://github.com/ps3dev/PSL1GHT)?

Sorry if this is asked too much. :-D I'm not a developer and have no idea what this would mean from a programming perspective. Would it require the whole code base to be adjusted just for PowerPC?
Also I don't know what else is missing. Proper GPU support could also be problematic, right? Vulkan is not supported, but GL?

**Comment by stenzek** [comment]
No GL support, it would require an entirely custom renderer. It would also require a separate JIT backend.

I guess theoretically you could compile an interpreter-only/software renderered core, but I'd guess it'd be too slow to be usable.

Sorry, I don't any any personal interest in such a port, and the very small number of potential users isn't sufficient motivation. Thankfully Sony's emulator exists on PS3 ;)
