### ISSUE TITLE
[libretro] scph5502.bin rom ignored?

### ISSUE THREAD

**Issue by maxlefou** [stenzek/duckstation#995]
I tried to run a PAL game but it doesn't work, saying the BIOS file is missing. While it's there, in `system` folder (you should mention somewhere that it's where the BIOS file should be. Some cores uses subfolders for that)

I got the logs after some tries and I think i found another problem

```
[libretro ERROR] [LoadImageFromFile] Failed to open BIOS image 'D:\roms\TOOLS\retroarch\system\scph1001.bin', errno=2
[libretro ERROR] [LoadImageFromFile] Failed to open BIOS image 'D:\roms\TOOLS\retroarch\system\scph1002.bin', errno=2
[libretro ERROR] [LoadImageFromFile] Failed to open BIOS image 'D:\roms\TOOLS\retroarch\system\ps-21e.bin', errno=2
[libretro ERROR] [LoadImageFromFile] Failed to open BIOS image 'D:\roms\TOOLS\retroarch\system\scph5552.bin', errno=2
[libretro ERROR] [LoadImageFromFile] Failed to open BIOS image 'D:\roms\TOOLS\retroarch\system\ps-30e.bin', errno=2
[libretro ERROR] [LoadImageFromFile] Failed to open BIOS image 'D:\roms\TOOLS\retroarch\system\scph7002.bin', errno=2
[libretro ERROR] [LoadImageFromFile] Failed to open BIOS image 'D:\roms\TOOLS\retroarch\system\scph7502.bin', errno=2
[libretro ERROR] [LoadImageFromFile] Failed to open BIOS image 'D:\roms\TOOLS\retroarch\system\scph9002.bin', errno=2
[libretro ERROR] [LoadImageFromFile] Failed to open BIOS image 'D:\roms\TOOLS\retroarch\system\ps-41e.bin', errno=2
[libretro WARN] [GetBIOSImage] No suitable BIOS image for region PAL could be located, using configured image 'D:\roms\TOOLS\retroarch\system\scph1001.bin'. This may result in instability.
[libretro ERROR] [LoadImageFromFile] Failed to open BIOS image 'D:\roms\TOOLS\retroarch\system\scph1001.bin', errno=2
```
My rom is `scph5502.bin`. It's said on [the libretro website](https://www.libretro.com/index.php/category/duckstation/) that this one can be used with duckstation but it seems the core just simply consider there's no BIOS if there's no `scph1001.bin` rom. Putting this file makes it working again.

Not sure if something is wrong or if it's just me then...

**Comment by stenzek** [comment]
Are you using an old version? I changed the BIOS search to look for any 512KB image in the BIOS directory a while back.

**Comment by stenzek** [comment]
Also, regarding documentation, the system directory is controlled by the frontend, not the emulator. Therefore any instructions I give could be incorrect. Please refer to your frontend's documentation for where to play firmware/system files.

**Comment by stenzek** [comment]
Closing due to lack of response, and I'm pretty sure this issue has been fixed anyway.
