### ISSUE TITLE
[Libretro] Option to Hide System Messages

### ISSUE THREAD

**Issue by Awakened0** [stenzek/duckstation#996]
This core shows messages like "System reset." or "Saved memory card to ...", which I'd like to hide. Setting the "Log Level" option to "None" doesn't hide them like I'd expect. Some of these double up with RetroArch's notifications too:

![Untitled](https://user-images.githubusercontent.com/4565863/96768773-3a660800-13ac-11eb-81d2-fddf662c7224.png)

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/339283979508505fe56a9bb0de1d122073f135b3

**Comment by Awakened0** [comment]
Thanks!
